templates/ai/what-is-kubeflow.html, templates/aws/fips.html, templates/aws/index.html, templates/azure/fips.html, templates/azure/index.html, templates/download/iot/intel-iotg.html, templates/gcp/index.html, templates/legal/data-privacy/2013-03-25/index.html, templates/legal/data-privacy/2016-02-08/index.html, templates/legal/data-privacy/index.html, templates/managed/apps/cassandra.html, templates/security/fips.html, templates/support/community-support.html, templates/telco/openran.html
- Fixed the change requested in this issue: https://github.com/canonical-web-and-design/web-squad/issues/4852
- As a drive by, updated every instance I could find of optimize/optimized/optimizing/optimization in the project, as long as it was within copy, and not a URL/third party package/config etc
- View the site your web browser at: https://ubuntu-com-11303.demos.haus/download/iot/intel-iotg
- See that the typo pointed out in the copy doc has been updated
- Visit:
- https://ubuntu-com-11303.demos.haus/ai/what-is-kubeflow
- https://ubuntu-com-11303.demos.haus/aws/fips
- https://ubuntu-com-11303.demos.haus/aws
- https://ubuntu-com-11303.demos.haus/azure/fips
- https://ubuntu-com-11303.demos.haus/azure
- https://ubuntu-com-11303.demos.haus/gcp
- …
=> Use UK spelling of "optimise" and its derivatives

webapp/certified/views.py
Replace category name ubuntu core to device for vendor pages
- Visit https://ubuntu-com-11309.demos.haus//certified/vendors/Advantech https://ubuntu-com-11309.demos.haus//certified/vendors/DFI and check that the categories column show "Device" instead of "Ubuntu Core" (compare with https://ubuntu.com/certified/vendors/Advantech)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11308
=> Fix categories for vendor pages

templates/about/release-cycle.html
The 21.04 is named [Hirsute Hippo](https://releases.ubuntu.com/21.04/), not [Impish Indri](https://releases.ubuntu.com/21.10/).
These names got mixed up.
I flipped the order of the rows in the table, but kept the names intact.
- Corrected release name - version number mismatch in release-cycle.html.
- Follow the Process as outlined in #11295.
Fixes #11295
_No relevant screenshot, no styling changed, purely data._
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices …
=> Match codename with release number (mixup)

webapp/shop/api/ua_contracts/advantage_mapper.py
- The `include-active-machines` was lost during refactoring. Added it back.
- Check a user with active machines
- Does the number of machines show up?
=> Fix active machines count

templates/certified/model-details.html
Updates one style to match the examples that use heading elements. You can check an example of it at https://ubuntu-com-11319.demos.haus/certified/201901-26804
- View the site locally in your web browser at: http://0.0.0.0:8001/certified/201901-26804
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4857
=> Update accordion to vanilla-3.0 patterns

static/js/src/chart-data.js
- Updates a kernel version name from '20.04.5 kernel' to '5.15 kernel'
- View the site locally in your web browser at: https://ubuntu-com-11326.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle
Fixes https://app.zenhub.com/workspaces/-web-tribe-5931746dba512f05402b61f6/issues/canonical-web-and-design/ubuntu.com/11291
=> Update kernel name in release cycle chart

templates/support/index.html
- Correct spelling of Memcached on /support
- View the site locally in your web browser at: http://0.0.0.0:8001/support or https://ubuntu-com-11331.demos.haus/support
- Search for spelling 'Memached' and check there are no results
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11304
=> Correct spelling of Memcached on /support

templates/certified/hardware-details.html, templates/certified/model-details.html, webapp/certified/views.py
Add subsystem id to hardware details page
- Check https://ubuntu-com-11336.demos.haus/certified/202108-29379/20.04%20LTS
- Compare with current https://ubuntu.com/certified/202108-29379/20.04%20LTS
I did this using my common sense. Feel free to suggest any ammendments, changing the format, orthography...
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11311
=> Add subsystem id to hardware details

templates/security/certifications.html, templates/security/disa-stig.html, templates/security/fips.html, templates/security/index.html
- The videos were embedded at a fixed size meaning half the registration form was cut off. I have added a script to allow scrolling.
- View the site locally in your web browser at: https://ubuntu-com-11332.demos.haus
- Check each page with embedded bright talk videos to see if the registration form is accessible. 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11192
=> Allow registration for embedded brighttalk videos

templates/engage/base.html
Expand columns when there is no form
- Check some engage pages without form such as https://ubuntu-com-11335.demos.haus/engage/custom-ubuntu-pro-image-on-azure
- See that the column expands to take up more space and the content centers.
- Compare with current https://ubuntu.com/engage/custom-ubuntu-pro-image-on-azure
- Check the engage pages with form are undisturbed https://ubuntu-com-11335.demos.haus/engage/gsi-managed-it-service
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11268
originally requested by @malina-i 
=> Expand columns for engage pages without forms

static/js/src/chart-data.js, static/js/src/chart.js, templates/shared/_kernel-support-schedule.html
- Makes the y-axis margin spacing based of the longest label length
- Fill in missing data to chart-data.js
- Update spacing in _kernel-support-schedule.html
- Find different graphs generated by chart.js and check the spacing of the y-axis margin is correct.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11300
=> Fix spacing issue in chart.js

redirects.yaml
- Added a rule in redirects.yaml to redirect any url calls ending in `/index` to the same url without `/index`
ex. `/security/index` redirects to `/security`
- Test some different urls adding /index to the end. This will only work with the main page.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4761
=> Redirects calls to /index to the same url minus /index

tests/shop/advantage/test_advantage_mapper.py, tests/shop/advantage/test_api.py, webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/api/ua_contracts/api.py, webapp/shop/views.py
- Move the parsing process from `api.py` to `advantage_mapper.py`
- Buy subscription as guest
- Buy subscription logged in
- Does it still work?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/513
=> Move API response conversion to mapper

requirements.txt, templates/404.html, webapp/app.py, webapp/security/api.py, webapp/security/views.py
This is an attempt to provide a better structure for handling CVE 404 errors following my comment here:
https://github.com/canonical-web-and-design/ubuntu.com/pull/11305#discussion_r824645422
Basically, we ended up in a situation where we were trying to raise a 404 error from within the `security_api_error` error handler, but we had to do it manually with `flask.render_template` rather than the more proper `flask.abort` because you can't `abort` from within an active `errorhandler`.
I think this was pointing to a sort of code smell, that we shouldn't really have got as far as raising a `SecurityAPIError` if really all that happened is that a CVE is missing. In fact, I think it would be much more reasonable for `SecurityAPI.get_cve` to simply return `None`, rather than an error, if the CVE …
=> Improve handling of API errors

templates/wsl/index.html
- Updates `/wsl` as per the [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit) and [design](https://user-images.githubusercontent.com/9105999/157416010-031da986-9b50-412a-ba65-ae502ef73aa5.png) more info can be found in the issue.
- View the site locally in your web browser at: https://ubuntu-com-11341.demos.haus/wsl    - Be sure to test on mobile, tablet and desktop screen sizes
- Compare against design and copydoc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4838
=> Update wsl page

templates/wsl/index.html, webapp/app.py, webapp/views.py
- Create view_func to pull just the wsl tutorials and render them on `/wsl`
- More details on [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11346.demos.haus/wsl
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4848
=> Render all wsl tutorials from discourse on `/wsl`

static/js/src/PurchaseModal/components/PaymentMethodForm.tsx
- Only call the customer info update endpoint once the form as been changed
- Log in
- Go to `/advantage/subscribe`
- Make sure `/customer-info-anon` is not called when the page loads and the VAT number is not deleted
=> Advantage: only update customer info if the payment form has changed

templates/openstack/index.html, templates/telco/vnf.html
- Update extendable containers illustration on `/telco/vnf` and `/openstack`
- Compare against [copydoc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#) and see [issue](https://github.com/canonical-web-and-design/web-squad/issues/4879) for more information
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4879
=> Update extendable containers illustration

templates/account/invoices/index.html, tests/shop/advantage/fixtures/purchase-3ds.json, tests/shop/advantage/fixtures/purchase-failed.json, tests/shop/advantage/test_advantage_mapper.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/api/ua_contracts/models.py, webapp/shop/api/ua_contracts/parsers.py, webapp/shop/api/ua_contracts/schema.py, webapp/shop/views.py
- Convert payment json responses to Payment objects
- For now we only convert /account/invoices and the download endpoints to use it
- The new payments endpoint will return Payment objects too
- Go to /account/invoices and download invoices 
- Does it work?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/514
=> Create purchase objects

templates/ai/what-is-kubeflow.html
- Updates p-inline-image to p-logo-section on /what-is-kubeflow
- View the site locally in your web browser at: https://ubuntu-com-11362.demos.haus/ai/what-is-kubeflow
- Check the logo sections are rendering correctly
=> Update p-inline-image to p-logo-section on /what-is-kubeflow

templates/ai/what-is-kubeflow.html
- Updates inline-images to logo-section
=> Updates inline-images to logo-section

templates/wsl/index.html
- There were two `data-testid` on the `/wsl` page which caused cypress to keep failing and I removed one 
1. Go to `/tests/cypress/forms/forms_spec.js` 
2. Please do `context.skip` or`it.skip` to save time and avoid making a bunch of spam submission
3. Move the` /tests/cypress/forms/forms_spec.js` file to the `/tests/cypress/integration` folder
4. run `yarn run cypress:open`
5. Click `forms_spec.js` in the cypress test window
6. Check the test passes on `/wsl` 
Fixes # …
=> Remove data-testid on `/wsl`

templates/azure/ebook/index.html, templates/azure/fips.html, templates/azure/pro.html
- Change instances of  'e-book' to 'eBook' on `/azure/eBook`, see [copydoc](https://docs.google.com/document/d/1JL_TeFBg1tSqiYIiXU0IwJTKWRDKJEXWtEgLRWFnToI/edit)
- Changed any other instances I found in the codebase
- Search the codebase for any instances of 'e-Book' and check they have been replaced by 'eBook'
- specifically search: https://ubuntu-com-11372.demos.haus/azure/ebook
https://ubuntu-com-11372.demos.haus/azure/fips
https://ubuntu-com-11372.demos.haus/azure/pro
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4912
=> Change instances of  'e-book' to 'eBook'

templates/azure/private-offer.html
- Update '/azure/private-offer' buttons lengths but shortening text, as per [copydoc](https://docs.google.com/document/d/1P4sqhsi6jqWwbqjrBDuAOABGIcbJDM6Efy59ztaroVk/edit)
- View the site locally in your web browser at: https://ubuntu-com-11373.demos.haus/azure/private-offer
- Check that the text on the buttons matches that on the [copydoc](https://docs.google.com/document/d/1P4sqhsi6jqWwbqjrBDuAOABGIcbJDM6Efy59ztaroVk/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4906
=> Update '/azure/private-offer' buttons lengths

redirects.yaml, templates/engage/base_engage_unlisted.html, templates/engage/unlisted/custom-ubuntu-pro-image-on-azure.html, templates/engage/unlisted/shell-onboarding.html, webapp/app.py, webapp/views.py
We had a complaint recently that an engage page went live, and it should not have been visible in the index or "You may be interested in" section on engage page thank you pages. We didn't have the functionality to support that, so this PR adds it, with two pages that should not appear on /engage, or in the "You may be interested in" section.
- https://ubuntu-com-11375.demos.haus/engage/unlisted/custom-ubuntu-pro-image-on-azure
- https://ubuntu-com-11375.demos.haus/engage/unlisted/shell-onboarding
- You should see two engage pages
- Attempt to visit:
- https://ubuntu-com-11375.demos.haus/engage/custom-ubuntu-pro-image-on-azure
- …
=> Add unlisted engage pages

static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx, static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx, static/js/src/advantage/react/hooks/useURLs.ts, static/js/src/advantage/users/app.tsx, static/js/src/advantage/users/hooks/useRequestAccountUsers.tsx
- Add dismissible onboarding notification
- go to https://ubuntu-com-11327.demos.haus/advantage?test_backend=true
- log in with an account with only one user
- see that the notification is showing on top of the table
- click "Manage account users"
- it should take you to /users
- go back and dismiss the message
- it should go away
- reload the page
- it should still be gone
- open the console and paste `localStorage.removeItem("dismissedOnBoardingNotification");` then press enter
- reload the page
- the notification should be back
- go to /users and add another user
- go back to /advantage, the notification should not show
Fixes canonical-web-and-design/commercial-squad#525
=> Add dismissible notification

.github/workflows/blog-links.yaml
The AMD site is causing regular timeouts and so ignoring them for now.
Check code.
=> Ignore amd link from blog linkchecker

static/sass/styles.scss, templates/templates/base.html
- Wrapped the notification in a `p-strip` < `u-fixed-width` so it follows the size conventions of vanilla.
- Set a z-index of 10 on targeting so it is visible and interact-able. This is under the z-index of the navigation (39) and p-modal (100)
- Go to https://ubuntu-com-11381.demos.haus/#success and make sure the width follows the rest of the page.
- Check for any other screen overlays that have a lower z-index than 10.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11316
=> Reduce width of success notification banner

static/js/src/advantage/react/components/FeatureSwitch/FeatureSwitch.tsx
Switch inputs on /advantage are currently broken, this fixes them
- Check your subscriptions, under "Features", the switch inputs should render correctly
Before:
After:
=> Fix switches on /advantage

webapp/security/views.py
- Removed releases as they are not being used in the cve template
- View the site locally in your web browser at: http://0.0.0.0:8001/cves/CVE-2019-20503
- See that cve renders correctly
- You can also try out different cve ids 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11379
=> Remove releases from cve view

tests/cypress/utils.js
- Disable cypress test on `/wsl` temporarily
- The test will be reverted when this [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/11389) is resolved. 
Fixes #
=> Disable cypress test on `/wsl` temporarily

templates/certified/search-results.html, templates/certified/shared/category-search-results.html
- Remove vendor name from model name in the table on `/certified` to make the table look simpler
- Please QA at https://ubuntu-com-11385.demos.haus/certified 
( e.g. https://ubuntu-com-11385.demos.haus/certified?q=GIGABYTE and 
https://ubuntu-com-11385.demos.haus/certified/desktops?vendor=Dell )
Fixes #11283 
Before 
After
=> Remove vendor name from model name in the table on `/certified`

.github/workflows/cypress-main.yaml
The cypress test is very noisy in the marketing channel and the web team are the ones that should really be alerted.
Check the code.
=> Remove marketing ping when cypress fails

templates/security/notices/lsn.html, templates/security/notices/usn.html, webapp/security/api.py, webapp/security/views.py
- add get notice function to api class
- refactor notice view to comply with new payload structure
- update usn template to comply with new variable names 
**NOTE: Must be merged AFTER releases endpoint has been updated on security api as base_url needs will need to be updated**
- Click on any notice and see that it renders correctly
- Try out any and all links on the template and make sure that they work
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11272
=> Update notice views to consume security api

templates/engage/shared/_de_engage_form.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_es_engage_form.html, templates/engage/shared/_it_engage_form.html, templates/engage/shared/_pt_engage_form.html, templates/engage/shared/_ru_engage_form.html
Due to a change in form processing in the Marketo API, fields that are duplicated in forms are repeated in the receiving Marketo field eg. `utm_something=foo` *2 -> `"foo, foo"`. This is an undesirable behaviour. This PR fixes affected forms by ensuring fields are only present once.
- Removed duplication of utm parameters in all affected forms.
- Go to https://ubuntu-com-11394.demos.haus/engage/isv-microk8s?utm_campaign=foo
- Open the Network tab of your dev tools
- Ensure the payload of the `submit` call only contains one `utm_campaign`
=> Ensure Marketo forms do not send duplicated utm fields

templates/gov/index.html, templates/server/index.html
- Use find tool to find instances of the old intel logo and replace it with the new one.
- **This does not fix logo that are pulled from the partners DB**
- Search the site for any uses of the old intel logo. This can be visually or by using the asset link: https://assets.ubuntu.com/v1/c24cb4b9-logo-intel.svg
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11297
=> Update old intel logo across site

static/js/src/advantage/subscribe/reducers/form-reducer.js, templates/advantage/subscribe/form/_feature_coverage.html
UA selector: Set billing period to monthly when selecting apps. 
This will allow users who have UA apps in their offerings to purchase them.
- Login with an account that has been offered an UA apps listing.
- Go to `/advantage/subscribe`
- Try to buy `UA Apps`
=> UA selector: Set billing period to monthly when selecting apps.

requirements.txt, webapp/app.py
Match the USN IDs are valid so we don't match potentially problematic strings.
- Make sure you can still view USN and LSN detail pages
=> Add a regex match on USN routes.

templates/aws/index.html
- Updates 'Azure' to 'AWS' on `/aws' as per [copydoc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit#heading=h.tx97ex3wcna4)
- Go to https://ubuntu-com-11401.demos.haus/aws
- Compare against [copydoc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit#heading=h.tx97ex3wcna4) 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4976
=> Update typo on /aws

templates/lxd/index.html
- Fix a typo
Before:
After:
Fixes #
=> Fix typo on /lxd

tests/shop/advantage/test_advantage_mapper.py, tests/shop/advantage/test_api.py, tests/shop/advantage/test_parsers.py, webapp/app.py, webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/api/ua_contracts/api.py, webapp/shop/api/ua_contracts/parsers.py, webapp/shop/api/ua_contracts/primitives.py, webapp/shop/api/ua_contracts/schema.py, webapp/shop/decorators.py, webapp/shop/schemas.py, webapp/shop/views.py
- Add new purchase endpoint which does:
- Get purchase account ensure a purchase account
- PUT customer info
- Preview or make purchase
- Endpoint info: `POST /advantage/purchase/{preview}` Returns an `Invoice` if preview or `Purchase` if not preview.
- Payload sample:
```
{
"customer_info": {
"payment_method_id": "",
"email": "albert.kolozsvari+testerabcd340@canonical.com",
"name": "abc",
"address": {
"city" : "London2",
"country": "GB",
"line1": "",
"postal_code": "123123",
"state": ""
},
"tax_id": {
"type": "",
"value": ""
}
},
"products": [
{
"product_listing_id": "lAObiUcHYzxOh_EVHCLGHoc8eARipfgy7itnjK1xSOiE",
"quantity": 1
}
],
"marketplace": "canonical-ua",
"action": "purchase",  // can be resize or trial too
"previous_purchase_id": "",
"captcha_value": "123"
}
```
- Add get …
=> Add new purchase endpoint and get purchase v2

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
it's per-token.. so adding token into this line to make it clearer and more accurate
- changed a line of UI copy
- Hover machine activity number tooltip
- See that the correct text is displayed 
=> Drive-by to make line of copy be more accurate

tests/cypress/forms/forms_spec.js, tests/cypress/utils.js
- The cypress test is failing again because the form in `/shared/forms/interactive/internet-of-things.html` has been updated a few days ago but the cypress test for the pages using that form hasn't been updated (The form is being used in multiple pages)
- I wrote a seperate cypress test for the pages using the same form (`/shared/forms/interactive/internet-of-things.html`) 
Fixes #
=> Remove iot pages from cypress test

tests/cypress/utils.js
-  `/pricing/devices` was missing from this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11409)
Fixes #
=> Update cypress test on /pricing/devices

navigation.yaml, templates/lxd/index.html
- Update `Get in touch` button's href from `/kubernetes/contact-us` to `/lxd#get-in-touch` 
- Capitalise `Lxd` in the navigation 
Fixes #
=> Update Get in touch button url

templates/advantage/index-no-login.html, templates/advantage/index.html, templates/shared/forms/interactive/advantage-beta.html, tests/cypress/forms/forms_spec.js
- Added the prompt to sign up for the beta programme back
- Added e2e tests checking for this message
- updated the notification to use the new action pattern
- go to https://ubuntu-com-11414.demos.haus/advantage
- see the notification
- log in
- see that the notification is still here
Fixes #11413
=> Reintroduce beta notification

templates/kubernetes/docs/1.21/components.md, templates/kubernetes/docs/1.22/components.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/supported-versions.md
- Fix install instructions as th cs -> charmhub redirection was returning wrong versions
- Remove links to versioned charms in cs as these no longer exist
=> K8s cs fixes

templates/cloud/public-cloud.html, templates/shared/_ubuntu_pro_on_public_cloud.html
- Updated as per [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/cloud/public-cloud
- Check against doc to see all changes have been made
- Test button on last section
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5040
=> Update copy, add cta button on /cloud/public-cloud

static/js/src/advantage/users/hooks/useRequestAccountUsers.tsx, webapp/shop/advantage/views.py
- Prevent sentry errors for 404 errors on /advantage/users
- Open console
- Go to /advantage with a user without a purchase account
- You will get a 404 from `account-users` request, but it will not retry the call.
- Use the demo. If you go to sentry you will not see any errors for your user
=> Prevent 404 sentry errors from advantage/users

tests/shop/advantage/test_api.py, webapp/app.py, webapp/shop/api/ua_contracts/api.py
- There is an uncaught exception happening when your session expires.
- Now we catch it again.
- Go to ubuntu.com and login
- Switch to testing environment
- You will get the 500 page
- Try the same on this demo
- You will not get a 500
=> Fix error handling for unauthorized exceptions

templates/blog/article.html
- Remove contextual Marketing elements from Ukraine blog post 
- 
- Ensure https://ubuntu-com-11456.demos.haus/blog/canonical-standing-with-ukraine contains no contact us CTA or newsletter form.
- Ensure they are still present on other blog posts.
=> Remove contact us and newsletter from Ukraine blog

webapp/views.py
- This adds a one time acquisition URL to enrichment form data
- Fill any form on ubuntu.com
- Ensure the respective Marketo lead contains the right "Acquisition URL" value
- Fill a form on another ubuntu.com page with the same email address
- Ensure the "Acquisition URL" value hasn't changed
=> Adds acquisition URL to enrichment form data

templates/certified/hardware-details.html, webapp/certified/views.py
On certificates with no hardware details the hardware
details through an exception due to an attempt to
use a variable that didn't get set.
On review, the variable wasn't actually needed.
- I removed it
- and also updated the hardware details page to show a message when no details are available.
- Edit webapp/certified/views.py to update the url to point to staging.
- View the site locally in your web browser at: http://0.0.0.0:8001/certified/201906-27103 and http://0.0.0.0:8001/certified/201906-27103/18.04%20LTS
- Verify that both pages load without any error and that they show no hardware details.
Fixes #11403
Here are screenshots of the …
=> fix exception on hardware details page

webapp/shop/api/ua_contracts/models.py, webapp/shop/api/ua_contracts/schema.py
- Make subscription_id optional for purchases payload.
- Can Will visit /account/invoices? 
- For some reason he has purchases without subscription info.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/551
=> Fix /invoices page

static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx
- Add _Additional subscriptions purchased directly with Canonical will not be affected._ line to the cancellation modal.
- Have a monthly subscription
- Open the cancel modal
- You will see the new line
Fixes #https://github.com/canonical-web-and-design/ubuntu.com/issues/9468
=> Update cancellation modal

static/js/src/advantage/ecom-events.js, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/subscribe/listeners/form-event-listeners.js, static/js/src/advantage/subscribe/listeners/ui-event-listeners.js
- Added tracking for product selection and modal interaction
- Go to https://ubuntu-com-11325.demos.haus/advantage/subscribe?test_backend=true
- click on different options
- open and close the modal
- it should log those actions
Fixes canonical-web-and-design/commercial-squad#507
=> Add tracking at different steps before checkout

static/sass/_pattern_takeovers.scss, templates/takeovers/shared/_takeover.html
- Added a new takeover class for a 22.04 pre-release special
- The takeover won't exist until this is merged so you'll need to inspect the page and do the following to replicate the screenshot
- Visit the [demo](https://ubuntu-com-11486.demos.haus/)
- Open dev tools
- Change the class of the takeover to `p-takeover--jammy`
- You could also hide the image, change the text to match what's in the screenshot and replace the CTA with:
```
<button class="p-button--positive" disabled>Coming April 21</button>
```
(The button will appear automatically when the takeover is created and has its `class` metadata set to `jammy`)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5106
=> add new "jammy" takeover class for pre release

templates/base_index.html, templates/takeovers/shared/_takeover.html
- Fixed an issue where the takeover text wouldn't become visible if an image isn't present
- Visit the [demo](https://ubuntu-com-11488.demos.haus/)
- Refresh the page until you see the Jammy Jellyfish takeover
- See that the text is visible
=> make sure takeover text appears if image is not present

templates/base_index.html
Prevented an empty link appearing when a takeover doesn't have a primary CTA:
- Visit the [demo](https://ubuntu-com-11496.demos.haus/)
- Refresh the page until you see the Jammy takeover
- See that the empty green `a` element is not there
=> Fix bug where takeovers would show an empty anchor element if not CTA data was present

.github/workflows/pr.yaml, codecov.yml
- Fix incorrect codecov reports for pull requests (will need to be verified once this pull request gets merged, added a task to the related issue)
- bump codecov/codecov-action to v3
- set [require_base](https://docs.codecov.com/docs/pull-request-comments#requiring-the-base-andor-head-commit) to true
- set [allow_coverage_offsets](https://docs.codecov.com/docs/comparing-commits#pseudo-comparison) to true 
- set actions/checkout@v2 `fetch-depth` to `0` to fetch all history for codecov
Fixes …
=> Fix incorrect codecov reports for pull requests

templates/download/raspberry-pi/index.html
**Note: Needs the download buttons updated**
- Updates raspberry-pi download page for the 22.04 refresh, see [copydoc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#heading=h.o491tg9cg8gy)
- Compare against [copydoc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#heading=h.o491tg9cg8gy)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4988
=> Update raspberry-pi download page

templates/shared/_ubuntu-advantage-service-description-ja.html
On this page, ESM is translated as "拡張セキュリティメンテナンス", not
"拡張済みセキュリティメンテナンス", so we have algined it with that.
The UA service description page in Japanese has wrong Japanese translation.
- https://ubuntu.com/legal/ubuntu-advantage-service-description/ja
- Correct: 拡張セキュリティメンテナンス（ESM）
- Wrong: 拡張済みセキュリティメンテナンス (ESM)
Fixes #11483
=> ua service description: fix wrong Japanese translation

templates/core/index.html
- Removed Honeywell logo as per PdM request
- Make sure the logo has been removed
Fixes # https://github.com/canonical-web-and-design/ubuntu.com/issues/11506
=> Remove Honeywell logo

static/js/src/chart-data.js, templates/about/release-cycle.html
- Updated chart data and legend
- Changed all instances of "Charmed Kubernetes" to "Canonical Kubernetes"
- Specific changes were discussed and approved on MM with Pdm, here is the original [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle#kubernetes-release-cycle
- See that the chart has been updated matching the new screen shot
- See that all instances of "Charmed Kubernetes" have been changes to "Canonical Kubernetes"
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5103
=> Update Canonical Kubernetes release cycle chart

templates/internet-of-things/index.html
**This is part of a round of smart start related updates that are all to go live at the same time**
- Updated /internet-of-things to match the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#)
- See that the page matches the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5082
=> Update /iot page with smart start changes

templates/ceph/index.html, templates/openstack/features.html, templates/openstack/support.html, templates/pricing/infra.html, templates/shared/pricing/_ua-for-infrastructure.html
- Change all instance of 72tb to 192tb pages listed below
- Implemented related copy changes where needed
- Originally requested via:
- /pricing/infra [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
- /openstack/support [copy doc](https://docs.google.com/document/d/1mHaZQ_VZnISTUEpYKiVK-Ejr5ne8lVevpxEc0LpXYKI/edit#)
- /openstack [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#heading=h.hf5huil04ges)
- /openstack/features [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
- /ceph [copy doc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit#)
**NOTE: The issue also requests these changes for …
=> Update copy on ua for infra table and related pages

templates/desktop/developers.html, templates/desktop/organisations.html
- Updates Lenovo laptop running 22.04 image, as the old one had a windows toolbar at the bottom
- Go /organisations /developers
- Make sure they *dont* look like the image below:
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11524
=> Update lenovo laptop images

templates/raspberry-pi/desktop.html
- Update desktop image on /raspberry-pi/desktop to use 22.04
- Check the imag on /raspberry-pi/desktop
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11525
=> Update desktop image on /raspberry-pi/desktop

templates/certified/model-details.html
Fixes #11518
This removes the hard coded _development board_ text from the certificate description.
- View the site at: https://ubuntu-com-11519.demos.haus/certified/202105-29000
- expand one of the certificates to verify that _development board_ text is removed.
=> Remove 'development board' text

templates/blog/product-cards/_kubeflow_deploy-tutorial.html
Replace the deploy kubeflow tutorial with get started docs
- Check the new link works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/runs/6124698153?check_suite_focus=true
=> Replace the deploy kubeflow tutorial with get started docs

templates/shared/contextual_footers/_ua_got_questions.html, templates/support/thank-you.html
Remove the modal trigger on the get help button to lead the user to the support contact form.
- Login and scroll down to the contextual footer
- Click the "Contact us" button 
- See you end up somewhere useful for a user with questions
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11538
=> Lead the help button to the support form on the advantage page

templates/about/release-cycle.html
- Fixed aria controls so that the chart is hidden until clicked
- View the site locally in your web browser at: https://ubuntu-com-11550.demos.haus/about/release-cycle
- Click through each tab and make sure everything shows as expected
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11542
=> Fix aria controls for Canonical k8s release chart

static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/components/ExplainingTable.tsx
- Add a table explaining user roles
- Go to https://ubuntu-com-11476.demos.haus/advantage?test_backend=true
- Log in
- navigate to https://ubuntu-com-11476.demos.haus/advantage/users?test_backend=true
- check that there is a table explaining user roles at the bottom and that the info is correct
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/557
--------------------------------------------------
--------------------------------------------------
=> Add roles explaining table

static/sass/_pattern_shop-cart.scss, templates/advantage/subscribe/index.html
Fixes canonical-web-and-design/commercial-squad#455
- Added small copy explaining that taxes will be calculated
- Go to [/advantage/subscribe](https://ubuntu-com-11498.demos.haus/advantage/subscribe)
- check that there is a text underneath the button explaining that taxes will be calculated
=> Improve TAX message

.github/workflows/cypress-main.yaml, templates/core/services/index.html, templates/shared/_rt-kernel-beta-banner.html, tests/cypress/forms/forms_spec.js
- Removed duplicated data test id that causes error on `/core/services` and `/robotics`
- Removed duplicated cypress test for `/robotics` page
- Scheduled cypress test for forms so it runs only one time a day
Fixes #
=> Fix and schedule cypress test for forms

templates/kubernetes/install.html
- Added link to resources page, as per [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit)
- View the site locally in your web browser at: https://ubuntu-com-11564.demos.haus/kubernetes/install
- See that the change was added and test the link
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5221
=> Copy update /kubernetes/install

navigation.yaml
- Remove industry report from k8s subnav
- View the site locally in your web browser at: https://ubuntu-com-11566.demos.haus/kubernetes
- See that subnav item has been removed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11557
=> K8s subnav update

templates/download/xilinx/index.html
- Updated as per [copy doc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit)
- Switched tab order to reflect doc
- View the site locally in your web browser at: https://ubuntu-com-11570.demos.haus/download/xilinx
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5200
=> Update copy on /download/xilinx

templates/server/index.html, templates/shared/_cloud-survey-banner.html
- Updated the text on the Cloud pricing survey banner
- View the site in your web browser at: https://ubuntu-com-11577.demos.haus/ceph
- See that the text matches what's given in the [issue](https://github.com/canonical-web-and-design/web-squad/issues/5233)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5233
=> update text of cloud survey banner

templates/kubernetes/compare.html, templates/kubernetes/what-is-kubernetes.html
- Added resources link to /kubernetes/what-is-kubernetes([doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#)) and /kubernetes/compare([doc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit#))
- https://ubuntu-com-11567.demos.haus/kubernetes/compare
- https://ubuntu-com-11567.demos.haus/kubernetes/what-is-kubernetes
- Test resources link
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5225 https://github.com/canonical-web-and-design/web-squad/issues/5224
=> Add resources link to relevant k8s pages

templates/kubernetes/docs/ingress.md
- Fixed a link broken by markdown/HTML mismatch
- View the site in your web browser at: https://ubuntu-com-11579.demos.haus/kubernetes/docs/ingress
- See that the link in the notification in the Istio Ingress section works, and isn't rendered as [MetalLB][]
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11534
Before:
After
:
=> Fix broken link in /kubernetes/docs/ingress

templates/openstack/index.html
- Update `announement` to `annoucement`
- Go to `/openstack`
- Compare page against [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#)
Fixes [#5278](https://github.com/canonical-web-and-design/web-squad/issues/5278)
=> Fix typo on /openstack

templates/desktop/index.html
- The "Visually stunning" section on /desktop included a reference to 20.04, this PR updates it to match Oliver's suggestions in the [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit)
- See that the "Visually stunning" section matches Oliver's suggestions in the copy doc
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11592
=> update "Visually stunning" section on /desktop for 22.04

navigation.yaml, templates/templates/footer.html, templates/templates/navigation-enterprise-h.html
- Updated meganav landscape links
- Added /landscape link to footer
- Added link to login portal to landscape subnav
- https://ubuntu-com-11603.demos.haus/#enterprise
- https://ubuntu-com-11603.demos.haus/landscape
- Check meganav > support and services and find that "Landscape remote management" and "Compliance reporting" route to new correct pages on u.com
- Test footer link
- Test subnav link
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5298
=> Update footer and meganav landscape links

navigation.yaml, templates/legal/data-privacy/index.html, templates/legal/data-privacy/recruitment.html
- Added /legal/data-privacy/recruitment based on the [copy doc](https://docs.google.com/document/d/1D_irZPx4n67_Lhg-9P2-Iu9jZM9Va7n0/edit#)
- Visit https://ubuntu-com-11606.demos.haus/legal/data-privacy/recruitment
=> Add recruitment page to /legal/data-privacy

webapp/app.py
- Add a blog title to Ubuntu blog (by default it's "Blog")
- Go to https://ubuntu-com-11607.demos.haus/blog/feed
- Make sure that the title tag contains the new title as a value
=> add a title to the blog RSS feed

templates/landscape/index.html
- Fixed typo in "infrastructure"
- View the site locally in your web browser at: http://0.0.0.0:8001/landscape
- Check typo has been fixed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11609
=> fix heading typo

static/js/src/chart-data.js, templates/about/release-cycle.html
- Update the release cycle page and chart for latest k8s
- 
=> Release cycle 1.24

templates/download/iot/index.html
- Updated as per [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#heading=h.jkuclkic3jjq)
- View the site locally in your web browser at: https://ubuntu-com-11613.demos.haus/download/iot
- See that requested copy updates have been made
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5292
=> Update copy on /download/iot

templates/kubernetes/resources.html
- Update Kubernetes and cloud-native operations report link
- go to `/kubernetes/resources` or https://ubuntu-com-11615.demos.haus/kubernetes/resources
- compare page against [copy doc](https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit#)
Fixes [#5211](https://github.com/canonical-web-and-design/web-squad/issues/5211)
=> Update report link on /kubernetes/resources

templates/openstack/what-is-openstack.html
Fix the pricing-calculator link on what-is-openstack
- Check the link is the correct one.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/runs/6520688424?check_suite_focus=true
=> Fix the pricing-calculator link on what-is-openstack

navigation.yaml, templates/kubernetes/docs/autoscaler.md, templates/kubernetes/docs/operator-charms.md, templates/kubernetes/docs/shared/_side-navigation.md
- Added page for usage of K8s Operator charms
- Added page for Cluster Autoscaler operator
=> K8s add cluster autoscaler docs

templates/server/index.html
- Updated as per [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11632.demos.haus/server
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5368
=> Update copy on /server 

templates/download/iot/_login.html, templates/download/raspberry-pi-core.html
- Removes the ebook Form
- Add a video on Ubuntu Core
- Updates copy **Note: suggestion tool was not used, so it isn't clear what is changed**
- Go to https://ubuntu-com-11633.demos.haus/download/raspberry-pi-core and compare against [copydoc](https://docs.google.com/document/d/1Ig906jbgB39QHw61uHMvIsRbSBUjchJBDkMZl0WzlWM/edit#heading=h.m0dm79vhykyd)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5375
=> Remove get eBook form, embed Ubuntu Core video

navigation.yaml, templates/kubernetes/docs/nvidia-dgx.md, templates/kubernetes/docs/shared/_side-navigation.md
- Add nvidia dgx support page
- add to navigation
- 
=> Add K8s NVIDIA DGX page

templates/azure/index.html
- Added a link to the 22.04 Ubuntu Pro image on Azure Marketplace, per the copy doc: https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit#
- View the site in your web browser at: https://ubuntu-com-11647.demos.haus/azure
- See that the page matches the copy doc suggestions
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5381
=> add 22.04 azure marketplace link to /azure

templates/pricing/devices.html
- Made a small tweak to the Embedding Programme heading on /pricing/devices, according to the copy doc: https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.2r4boi163qbs
- View the site in your web browser at: http://0.0.0.0:8001/pricing/devices
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5384
=> update embedding programme title on /devices

templates/automotive/index.html, templates/shared/forms/interactive/automotive.html
- Create a contact modal for automotive. Previously it was using the general IoT one.
- Go to https://ubuntu-com-11636.demos.haus/automotive and click the 'Contact Canonical' button to trigger the modal.
-  Compare content against [copydoc](https://docs.google.com/document/d/1oY_lMp92TAzHNqGXEJZmWVtHf9hcChgZfmVA9gm324g/edit#)
- Complete the form and make sure it submit and sends you to a thank you.
- Check you can close the modal without submitting
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5335
=> Create /automotive contact modal

templates/desktop/organisations.html
- Added a link in the hero strip to a datasheet according to the [copy doc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
**Note:** there's a second comment from Oliver in the copy doc that I think needs to be addressed separately when Dave is around.
- View the site in your web browser at: http://0.0.0.0:8001/desktop/organisations
- See that the changes match the copy doc, and the link works
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5435
=> add link to datasheet on /desktop/orgs

templates/download/raspberry-pi/index.html
- Updated headings on /download/raspberry-pi to read "Certified for" rather than "Works on", according to Oliver's comments in the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit)
**Note:** David Beamonte Arbues's comments are being addressed in another issue, those changes can't go live until June 16th, so please ignore those in this instance.
- View the site your web browser at: http://0.0.0.0:8001/download/raspberry-pi
- See that the changes match the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5434
=> update heading copy on /download/rpi

templates/templates/navigation-developer-h.html
- Add `Ubuntu Desktop` on developer dropdown menu
- [Copy doc](https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit)
- Go to https://ubuntu-com-11683.demos.haus/
- Click developer in the navigation check `Ubuntu Desktop` is added 
Fixes [#5464](https://github.com/canonical-web-and-design/web-squad/issues/5464)
=> Add a link on dropdown menu

templates/desktop/organisations.html
- Updated as per [copy doc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11671.demos.haus/desktop/organisations
- See that the link has been updated
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5455
=> Update datasheet link on /desktop/organisations

templates/security/docker-images.html
- Updated as per [copy doc](https://docs.google.com/document/d/1zZibtjU141e4mBxo_0PtfYxJ6e5fyaaAdFZ6v945XAM/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11668.demos.haus/security/docker-images
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5463
=> Update FAQ on /security/docker-images

templates/aws/pro.html
- Add 22.04 content to /aws/pro
- Go to https://ubuntu-com-11675.demos.haus/aws/pro and compare against [copydoc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#heading=h.4hyflila1isb)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5452
=> Add 22.04 content to /aws/pro

static/js/src/advantage/subscribe/renderers/version-details.js
- Updated as per [relevant comment on doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?disco=AAAAZvdq89s)
**NOTE: This copy doc is massively out of sync with the live site. As it is unclear if the older comments are still relevant, this PR only addresses the most recently requested change in the comment linked above. See [comment](https://github.com/canonical-web-and-design/web-squad/issues/5432#issuecomment-1144814204)**
- Under "What Ubuntu version are you running?" click on both 24.04 LTS and 20.04 LTS and see …
=> Update copy for 22.04 LTS and 20.04 LTS

tests/shop/advantage/test_api.py, webapp/app.py, webapp/shop/api/ua_contracts/api.py, webapp/shop/schemas.py, webapp/shop/views.py
- Create new endpoint for calculating purchase price without user.
- Try this CURL command
```
curl --location --request POST 'https://ubuntu-com-11687.demos.haus/account/canonical-ua/purchase/calculate' \
--header 'Content-Type: application/json' \
--data-raw '{
"country": "GB",
"products": [
{
"product_listing_id": "lAFpm3dPX4PL26zY9tYA-6bA6-YR-VdzTz3nw-uNXlJY",
"quantity": 1
}
],
"has_tax": false
}'
```
Does it work? Try different parameters. 
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/599
=> Add calculate price endpoint

requirements.txt, webapp/app.py, webapp/views.py
A replacement for the [renovate PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11667) as it needs some code updating
Search keyword on https://ubuntu-com-11471.demos.haus/server/docs e.g. "Ubuntu" it should return results
Another example search "packer" with the global search https://ubuntu-com-11471.demos.haus/search?q=packer
Same steps for https://ubuntu-com-11471.demos.haus/tutorials
Same steps for the global search
Same steps for the other doc searches such https://ubuntu-com-11471.demos.haus/core/docs. All the others should work if these work.
=> Update search with new arguments

templates/internet-of-things/index.html
- Updated as per [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.wm0gfggkoe1y)
- See that the logo has been updated
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5481
=> Update Xilinx logo on /iot

releases.yaml, templates/download/intel-nuc.html, templates/download/iot/index.html, templates/download/raspberry-pi/index.html
**Copy updates to be deployed on 16th of June.** Therefore the UC22 download links don't work
- check https://ubuntu-com-11699.demos.haus/download/iot against https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#
- check https://ubuntu-com-11699.demos.haus/download/raspberry-pi 
againsts https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#
- check https://ubuntu-com-11699.demos.haus/download/intel-nuc against https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit#
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5424 …
=> UC22 copy updates

templates/core/index.html
- A download CTA incorrectly states version 20 of core, it should be 22
=> fix version number typo on core page

releases.yaml, templates/download/shared/_core_raspberry_pi_download.html
- fixed broken core download links on /download/raspberry-pi
- View the site in your web browser at: http://0.0.0.0:8001/download/raspberry-pi
- See that the download links under "Download Ubuntu Core" work
=> update core rpi 22 links with latest checksums

templates/blog/blog-card.html
- Fix /blog description formatting
- Go to https://ubuntu-com-11730.demos.haus/blog?page=3 and check the blog descriptions are rendering correctly. Note the small images look strange but this behavior was present before.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11715
=> Fix /blog description formatting

templates/templates/_navigation.html
[Previous PR merged](https://github.com/canonical-web-and-design/ubuntu.com/pull/11732), removed search AND sign in button - Uncomment sign-in button
- Make sure Sign in button shows and you can sign in
=> Uncomment sign-in button

static/js/src/openstack-deployment-chart.js
- Delete unnecessary survey link
- Go to https://ubuntu-com-11722.demos.haus/openstack
- Check there is no a strange link at the bottom of the page on all screens.
- [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#heading=h.f9c4o523ne3b) if you need
Fixes #11720
=> Delete unnecessary survey link

templates/templates/docs/shared/_docs.html, templates/tutorials/index.html, tests/test_routes.py, webapp/app.py, webapp/views.py
Temporarily remove all search
Check that search and /search endpoints have been removed in the following URLs:
- https://ubuntu-com-11737.demos.haus/server/docs
- https://ubuntu-com-11737.demos.haus/core/services/guide
- https://ubuntu-com-11737.demos.haus/kubernetes/docs
- https://ubuntu-com-11737.demos.haus/core/docs
- https://ubuntu-com-11737.demos.haus/tutorials
- https://ubuntu-com-11737.demos.haus/ceph/docs
- https://ubuntu-com-11737.demos.haus/openstack/docs
- https://ubuntu-com-11737.demos.haus/security/livepatch/docs
- …
=> Temporarily remove all search

templates/security/_notice-brief.html, templates/security/notices.html, templates/shared/_pagination.html, webapp/security/api.py, webapp/security/views.py
- Add function to api class for getting all notices
- Update notice list view to consume endpoint and refactor filtering accordingly 
- Remove date formatting from template (now handled in view)
- See that notice list loads as expected
- Test pagination
- Test searching by notice id, cve id, notice title, or notice description (lower and upper case)
- Test ability to toggle order 
Fixes https://github.com/canonical-web-and-design/master-epics/issues/409
=> Update notice list view to consume api

webapp/certified/views.py
Only show search results page if search query parameter present.
Fixes #11428 
Go to https://ubuntu-com-11740.demos.haus/certified?nonsense. Check you see the homepage.
Go to https://ubuntu-com-11740.demos.haus/certified?q=nonsense. Check you see the search results page.
=> Only show certified search page of search query present

templates/core/index.html
- Fix a typo in a link on /core
- Click "Full disk encryption" in the key features section on https://ubuntu-com-11745.demos.haus/core and check it goes to https://ubuntu-com-11745.demos.haus/core/features/full-disk-encryption
Fixes #11741
=> Fix a typo in a link on /core

templates/download/server/step2.html
- Updated the support dates on step 2 of /download/server to reflect the 22.04 release
- View the site in your web browser at: http://0.0.0.0:8001/download/server
- Click "Option 2"
- See that the dates match the suggestions in the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5559
=> update support dates in /download/server

templates/automotive/index.html, templates/internet-of-things/gateways.html, templates/internet-of-things/networking.html, templates/internet-of-things/shared/_links.html, templates/internet-of-things/smart-city.html, templates/internet-of-things/smart-displays.html
**[Smart displays](https://ubuntu.com/internet-of-things/smart-displays)**
- Added cards linking to other IoT pages - [copy doc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit#heading=h.qkat7vybg1m)
**[Gateways](https://ubuntu.com/internet-of-things/gateways)**
- Added cards linking to other IoT pages - [copy doc](https://docs.google.com/document/d/18ffTcNolrtJS9AvjMfa8KW94uLfC0KzmHtTe-jMYmlo/edit#heading=h.nby4fxmsrrg3)
**[Automotive](https://ubuntu.com/automotive)**
- Added cards linking to other IoT pages - [copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#heading=h.7zytw966kvza)
**[Networking](https://ubuntu.com/internet-of-things/networking)**
- Added cards linking to other IoT pages - [copy …
=> add iot links section

templates/tutorials/index.html, webapp/views.py
Following on from https://github.com/canonical-web-and-design/ubuntu.com/pull/11759#issuecomment-1164171740, actually, a bunch of tutorials search URLs [exist in public web pages](https://www.google.com/search?q=%22ubuntu.com%2Ftutorials%3sFq%3D%22+-site%3Aubuntu.com). This means Google search bot could well hit us with searches by crawling these URLs. So we shouldn't reenable this search until we have bot protection.
Go to https://ubuntu-com-11764.demos.haus/tutorials?q=fish - check no search is performed and you see all results.
=> Disable tutorials search again

templates/blog/newsletter-form.html
Add finance option to newsletter signup
- Go to https://ubuntu-com-11664.demos.haus/blog
- Sign up for newsletters with the finance option checked (make a note of the email you use)
- Check that your submission has appeared in Marketo (Scott can help you with this if you need)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5449#event-6707591309
=> Add finance newsletter signup

templates/security/cve/cve.html, webapp/security/views.py
- Formatted patches and tags to pass through to template as needed
- Refactored template to comply with new data
- View the site locally in your web browser at: http://0.0.0.0:8001/security/CVE-2020-11984 (or any other cve containing patches or populated tags)
- See that are correctly shown
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11317
=> Fix missing patches and tags in CVEs

webapp/app.py
In the demo, go to `/server/docs`, do a search or two.
=> Reenable search for /server/docs

templates/core/index.html, templates/internet-of-things/smart-city.html
- Updated link to the Ubuntu Core datasheet to point to the new 22 version
- Updated the copy doc link on /core
- visit https://ubuntu-com-11776.demos.haus/core
- see that the "Read the Ubuntu Core datasheet" link takes you to the 22 version of the datasheet
- see that the link to the copy doc takes you to [this copy doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit)
- visit https://ubuntu-com-11776.demos.haus/internet-of-things/smart-city
- see that the "Ubuntu Core 22 ›" link takes you to the 22 version of the datasheet
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5591 & https://github.com/canonical-web-and-design/web-squad/issues/5592
=> update ubuntu core datasheet links to 22 version

templates/advantage/subscribe/form/_type_select.html
- Updated the text accompanying the selection of either AWS, Azure or Google Cloud to remove mention of a support offer that is no longer available, according to Lech's comment in the [copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?disco=AAAAbrKej5s&usp=suggestion_email_discussion&usp_dm=true&ts=62bb1886)
:warning: there are many unresolved comments in the copy doc, I've spoken to Lech and he's going to clean it up, this PR addresses just one urgent comment
- Visit https://ubuntu-com-11779.demos.haus/advantage/subscribe
- Select AWS, Azure and Google Cloud in the first step, see that the copy in the box that appears below matches the comment in the copy doc.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5601
=> Remove mention of support from cloud options on /subscribe

webapp/views.py
- Removed unused context parameters
- Reduced the API calls from 3 to 1
- Added a comment to try and explain a "magic" number
- Go to https://ubuntu-com-11767.demos.haus/16-04
- Check it renders fine and is the same as production
Might help to resolve this error: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/24036/?query=is%3Aunresolved. But the single remaining notices API response is huge and is likely the culprit.
=> Refactor 16-04 API calls

templates/credentialing/index.html
- Exam links at [/credentialing](https://ubuntu-com-11784.demos.haus/credentialing) now point to the QA Open edX instance rather than the Production instance
- The links now also take care of SSO, so the user shouldn't have to click a "Log in" link after landing in Open edX
- Open the [demo](https://ubuntu-com-11784.demos.haus/credentialing)
- Click on the "Start" button for each exam
- Verify that you land on the Welcome section of the exam in Open edX
- Verify that you are on the QA instance (qa.cube.ubuntu.com)
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/630
=> Update Credentialing exam links to point to QA

templates/templates/docs/shared/_docs.html, templates/tutorials/index.html, webapp/app.py, webapp/views.py
Quota is again [reaching its limits](https://console.cloud.google.com/apis/api/customsearch.googleapis.com/quotas?authuser=0&project=ubuntu-search-1530889417216) in the past few days. [Due to high levels of spamming](https://logging.comms.canonical.com/search?rangetype=relative&fields=source%2Cmessage%2Cpath%2Cquerystring%2Cservice&width=1848&highlightMessage=&relative=172800&q=path%3A+%22%2Ftutorials%22+querystring%3A+q%3D*), disable search /server/docs and /tutorials search again, which look like they are the most spammed.
- Check https://ubuntu-com-11790.demos.haus/tutorials doesn't have search box anymore
- Check https://ubuntu-com-11790.demos.haus/server/docs doesn't have search box anymore
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11780
[QA …
=> Temporarily remove searches

templates/download/index.html, templates/download/iot/index.html, templates/pricing/shared/_enablement-strip.html
- Updates alternative download section to /download  
- Updates support platforms logo cloud on /iot
- Go to https://ubuntu-com-11793.demos.haus/download and compare against [copydoc](https://docs.google.com/document/d/1egsCcmFiz8czeHsvwoB9Jz815Ij5Urtf7Ngrru6Zd4o/edit#)
- go to https://ubuntu-com-11793.demos.haus/download/iot and see that the 'Supported platforms' sections look better than on the current live site. Design was based on this suggestion from @davegoddard42 : 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5602
=> Updates alternative download section to /download & updates support platforms logo cloud on /iot

templates/security/cve/cve.html, webapp/security/views.py
- Fix cve error for missing patches, tags, and bugs
- View the site locally in your web browser at: http://0.0.0.0:8001/security/CVE-2002-0391 or https://ubuntu-com-11801.demos.haus/security/CVE-2002-0391
- See that CVE template renders as expected
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11799
=> Fix cve error for missing patches, tags, and bugs

konf/site.yaml
- Send /advantage and /account to separate sentry dashboards
- Send /security to separate sentry dashboard too
- /security rule updated because single CVE pages urls structure is /security/<CVE_id> which right now would not be sent to the security service
=> ubuntu.com: Sentry schism

templates/certified/index.html
- Updates /certified homepage with certified hardware links for 'devices' and 'socs'
**Note: this request was made in the [issue](https://github.com/canonical-web-and-design/web-squad/issues/5609) not the [copy doc](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#heading=h.kiqaim38ehoe)**
- Go to https://ubuntu-com-11805.demos.haus/certified and check that the 'iot devices' & 'socs' section includes links for 'Certified for:'
- Check that when these links are pressed they go to the certified devices search and apply the appropriate filter ie. if you click `20.04 LTS` it should take you to https://ubuntu-com-11805.demos.haus/certified/devices?release=20.04%20LTS
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5609
=> Updates /certified homepage with certified hardware links for 'devices' and 'socs'

templates/account/invoices/index.html
- Fix invoice status problem.
- Make a purchase with a 4000 0000 0000 0341
- Go to the backoffice tool and cancel your payment
- purchase will have an invoice with a `void` status
- Staging will should your payment with the status `pending` (incorrectly)
- Demo will show your payment with status `Failed` (correctly)
- Also discovered old payments with status `done` will forever show `pending`, due to missing invoices - Now shows `Failed` (yes, both payment.status exists as well as payment.invoice.status)
- Also fixed label css class
=> Fix invoice status

templates/gcp/pro.html
- Added a link on `/gcp`
- Go to https://ubuntu-com-11812.demos.haus/gcp
- Check the `Upgrade your Ubuntu LTS to Pro >` link works properly 
- Compare page against [copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit#)
- 
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/5598
=> Add a link on `/gcp`

templates/security/cve/cve.html
- Update the cve bug check to be based on empty string rather than the length of array
-  http://0.0.0.0:8001/security/CVE-2022-29526 and make sure multiple bugs are listed
- http://0.0.0.0:8001/security/CVE-2022-33124 and make sure no bugs are listed 
- http://0.0.0.0:8001security/CVE-2022-31625 and make sure single bug is listed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11818
=> Show cve bugs even when there's only one

requirements.txt, templates/403.html, templates/templates/docs/shared/_docs.html, templates/tutorials/index.html, webapp/app.py, webapp/views.py
- Reenable tutorials and server docs search
- Use canonicalwebteam.search 1.2.2 to block spam requests
- Add 403 template
QA
--
Go to https://ubuntu-com-11811.demos.haus/search, https://ubuntu-com-11811.demos.haus/server/docs https://ubuntu-com-11811.demos.haus/tutorials and perform some searches.
Try searching for something spammy like "【Telegram：HX99.COM】蝶之毒华之锁全CG包". Get 403 forbidden.
Try searching from the command-line:
```
curl -I "https://ubuntu-com-11811.demos.haus/server/docs/search?q=【Telegram：HX99.COM】蝶之毒华之锁全CG包"
```
You should get 403 forbidden, because curl useragent is blocked ^.
=> Reenable search

templates/about/release-cycle.html
'slug' seems to be an internal ID and not something to be used on the web page.
Signed-off-by: Anthony Wong <anthony.wong@canonical.com>
=> Use release name instead of 'slug'

webapp/security/views.py
- Fixed broken CVE query filter
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cves or https://ubuntu-com-11839.demos.haus/security/cves and search for "CVE-2022-2347" and see that it does not error out
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11838
=> Fix broken CVE query filter

static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.test.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx, static/js/src/advantage/subscribe/react/components/Form/Version/Version.test.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts, static/sass/_pattern_card.scss
- Replaced the separate public cloud options with a generic one
- Added the public cloud options once the generic one is selected
- Removed the "Looking to add support to an existing VM" section
- Added a button styled link to lnk to each marketplace
- go to [/advantage/subscribe](https://ubuntu-com-11846.demos.haus/advantage/subscribe)
- select the public cloud option
- see that everything matches the wireframes
Fixes canonical-web-and-design/commercial-squad#643
Closed:
Open:
@wgx 
Mobile:
=> Create section 1: Product type

.github/PULL_REQUEST_TEMPLATE/TAKEOVER_PR.md, .github/pull_request_template.md
- Fix links to "QA steps" and "Commit guidelines" in PR templates
- Before this PR is merged, the links in the **Help** section below should return a 404 error
- Once this PR is merged, open a new PR and verify that the links in the **Help** section go to [QA steps](https://discourse.canonical.com/t/qa-steps/152) and [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)
=> Fix broken links in PR templates

static/sass/_pattern_footer.scss, static/sass/_pattern_lists.scss
- Fixed middot lists in the footer and meganav
- Visit https://ubuntu-com-11870.demos.haus/
- See that the middot list in the footer looks correct
- Open the Enterprise dropdown from the meganav, and see that the middot lists at the bottom of the content window aren't broken (compare to live)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11866
=> Remove local styles overriding Vanilla's middot list styles

static/sass/_pattern_blog-card.scss
- Fixed broken headings on tutorials and engage page cards
:information_source:  This will soon be replaced by [this pattern](https://github.com/canonical-web-and-design/vanilla-framework/issues/4495) in Vanilla, when it lands.
- Visit https://ubuntu-com-11868.demos.haus/tutorials
- See that all the card headings don't look broken (compare to live site)
- Visit https://ubuntu-com-11868.demos.haus/engage
- See that all the card headings don't look broken (compare to live site)
- Visit https://ubuntu-com-11868.demos.haus/blog
- See that the card headings still have category specific top border colors (compare to live site, should be no difference)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11855
=> reinstate blog-p-card__header fallback styles

README.md
- Removes one "the" from a sentence.
No issue reference because the problem is too small to justify creating one.
=> Update README.md for a grammar mistake

.github/workflows/cypress-main.yaml
- It seems the engage page not being loaded causes cypress test failure. Discourse can cause timeouts so I increased the timeout in cypress.. 
- There is no way to QA. Just need to merge and see if it works....
=> Increase cypress timeout

static/js/src/contributions.js, static/js/src/navigation.js, templates/templates/_navigation.html
**Improve navigation click events**
- The global nav id was not present so updated to target the parent
**Disable the contribution button if total is 0**
- Replaced the reserved variable name `submit` with `submitButton`
- Corrected the disable setting
- Go to /download/desktop/thank-you?version=22.04&architecture=amd64
- Cancel the download
- Set all the sliders to 0
- See the [Contribute with PayPal] button is disabled
- Move a slider and see it becomes enabled
=> Disable the contribution button if total is 0

templates/credentialing/index.html
- Change the Notification to the `information` type and the title to "Note"
- Replace "Focus on" to "Topics include" in Desktop exam description
- Go to https://ubuntu-com-11867.demos.haus/credentialing
- Verify that the Notification is now the [information](https://vanillaframework.io/docs/patterns/notification#information) type and the title is "Note"
- Verify that the text in the Desktop exam description has been changed to "Topics include package management..."
=> Update copy on /credentialing

entrypoint
Fixes https://github.com/canonical/Web-design-systems-squad/issues/56 :
> This should help with stability of ubuntu.com. We do need to run more than one worker, as even with gevent multithreading, the worker still sometimes restarts and while it's restarting, requests can't be handled at all.
> 
> Should help with https://portal.admin.canonical.com/C136508/.
`dotrun`. Check the site runs.
=> Expand to 2 gunicorn workers

templates/legal/contributors/agreement.html
Removed required on the org name in the CLA form when signing as an individual.
- Go to /legal/contributors/agreement
- Select "I am signing as an individual contributor."
- Compete the form and see it submits correctly
Fixes https://github.com/canonical/microk8s/issues/3345
=> Removed required on the org name in the CLA form

redirects.yaml, tests/test_routes.py, webapp/app.py, webapp/views.py
Remove and redirect canonical annoucement blogs
- Check that https://ubuntu-com-11459.demos.haus/blog/press-centre redirects to https://canonical.com/press-centre
- Check that the rest of https://ubuntu-com-11459.demos.haus/blog works
- Anything else that you may think of that can break blog
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5052
=> Remove and redirect canonical annoucement blogs

webapp/views.py
Check if the article has a group set before checking redirect condition
- Find a blog article with no group set
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/<atricle_slug>
- Make sure it does not 500
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11908#event-7087743195
=> Blog - 500 when article has no group

static/js/src/chart-data.js, templates/about/release-cycle.html
- Updates release-cycle graph for Kubernetes to match upstream
=> update K8s chart to match upstream

templates/certified/index.html, webapp/certified/views.py
The certified home page server section was displaying
incorrect numbers and was missing the Dell Technologies
vendor.
This change updates the home view to make the logic that builds up the server section match the logic that builds up all of the other form factor types. It also updates the template to use the same pattern as well as changes the match string to _Dell Technologies_ since _Dell_ is not used.
This updates the servers section of the home page so that it includes Dell and also fixes the counts.
View https://ubuntu-com-11912.demos.haus/certified  and verify that a link for Dell Technologies shows up in the server section of the page with a count of 89.
Fixes #11907
=> fix server section of certified home page

webapp/views.py
/engage/unlisted/whatever  type of pages will break the site, it should return 404 if the engage page doesn't exist.
- View the site locally in your web browser at: https://ubuntu-com-11918.demos.haus/engage/unlisted/whatever or any other unlisted engage pages that doesn't exist should return 404
Fixes https://github.com/canonical/ubuntu.com/issues/11729
=> Return 404 for not found unlisted engage pages

templates/desktop/organisations.html
- Fixed the warped image in the hero section of https://ubuntu-com-11926.demos.haus/desktop/organisations
- visit /desktop/organisations
- see that the image is not distorted
=> fix desktop/org image dimensions

templates/certified/model-details.html, tests/cassettes/TestCertification.test_model_details.yaml, webapp/certified/helpers.py, webapp/certified/views.py
Restore the utility function to create the download links
Check that the download button of these two pages:
s390x: https://ubuntu-com-11920.demos.haus/certified/201909-27363
ppc64le: https://ubuntu-com-11920.demos.haus/certified/201805-26248
Go to these
s390x: https://ubuntu.com/download/server/s390x
ppc64le: https://ubuntu.com/download/server/power
Fixes https://github.com/canonical/ubuntu.com/issues/11584
=> Fix certified download links

templates/engage/base.html, templates/engage/shared/_webinar-embed.html, webapp/app.py
- Added support for `webinar_date` metadata in engage pages, and a custom filter to check in the template whether the date has passed. If the date has passed, we show the webinar earlier in the page to help draw attention to it.
- Visit https://ubuntu-com-11931.demos.haus/engage/technical-intro-ubuntu-core22
- See that the Brightalk embed appears above the text content of the engage page
- Visit https://ubuntu-com-11931.demos.haus/engage?resource=webinar
- Select any other webinar
- See that the Brightalk embed appears below the text content of the engage page
- Find another webinar engage page where the webinar has already happened, e.g. https://ubuntu-com-11931.demos.haus/engage/intro-to-OSM-webinar
- The Brightalk embed should still appear _below_ the text content, because the …
=> Promote webinar embed on engage pages when webinar date has passed

navigation.yaml, templates/kubernetes/docs/1.24/components.md, templates/kubernetes/docs/1.24/release-notes.md, templates/kubernetes/docs/cdk-addons.md, templates/kubernetes/docs/encryption-at-rest.md, templates/kubernetes/docs/gpu-workers.md, templates/kubernetes/docs/how-to-addons.md, templates/kubernetes/docs/inclusive-naming.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/ipv6.md, templates/kubernetes/docs/metallb.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/supported-versions.md, templates/kubernetes/docs/using-vault.md
- Updated components to include latest images
- All bundle refs updated
- Release notes added
- updates to Vault
- Updates for charmed operators/addons
=> k8s 1.24ck1 updates

releases.yaml
- updated releases.yaml with the checksums for 22.04.1
- Run the site using the command ./run serve or dotrun
- http://0.0.0.0:8001/download/alternative-downloads
- http://0.0.0.0:8001/download/desktop
- See that they all point to 22.04.1
- The checksums should match the ones provided by Lukasz:
```
c396e956a9f52c418397867d1ea5c0cf1a99a49dcf648b086d2fb762330cc88d *ubuntu-22.04.1-desktop-amd64.iso
10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb *ubuntu-22.04.1-live-server-amd64.iso
680c2c1770b53d90e825fd9a40178f605af47acfff681ad5f68d38094d1c32eb *ubuntu-22.04.1-preinstalled-desktop-arm64+raspi.img.xz …
```
=> update releases.yaml for 22.04.1

requirements.txt, webapp/app.py, webapp/views.py
Add missing language engage page endpoint (works the same as thank-you page)
- Check that the engage pages with in languages other than English work now:
https://ubuntu-com-11940.demos.haus/engage/es/guia-para-la-implementacion-de-openstack
https://ubuntu-com-11940.demos.haus/engage/es/comparacion-de-la-plataforma-kubernetes-red-hat-openshift-suse-rancher-y-canonical-kubernetes
https://ubuntu-com-11940.demos.haus/engage/it/italian-2021-cloud-pricing-report
Finally, test a few other engage pages see that the others work:
e.g. https://ubuntu-com-11940.demos.haus/engage/developer-guide-to-operators
Reported by [Shereen on …
=> Add engage pages endpoint with language

redirects.yaml, templates/engage/unlisted/at&t-onboarding.html
- Added redirect for unlisted engage page
- Added page template as per [copy doc](https://docs.google.com/document/d/1QG0zxy9u_oGhXJUBsm3mNQy0l5dLwWOlDrheB_-BPH8/edit)
- View the site locally in your web browser at: https://ubuntu-com-11853.demos.haus/engage/AT&TProOnboarding 
- See that you are rerouted to https://ubuntu-com-11853.demos.haus/engage/unlisted/at&t-onboarding
- Check content against doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5631
=> Private engage page build - AT&T Onboarding Site

templates/credentialing/index.html
- Updated links on /credentialing to point to exams on the Production Open edX instance
- Go to https://ubuntu-com-11941.demos.haus/credentialing
- Click each Start button and verify that you land on cube.ubuntu.com (_not_ qa.cube.ubuntu.com)
Part of https://github.com/canonical/commercial-squad/issues/693
=> Update /credentialing links to point to Production.

webapp/views.py
- Handle not found Blog posts
- Go to a blog post that doesn't exist like https://ubuntu-com-11947.demos.haus/blog/pepe it should return 404. In contrast, https://ubuntu.com/blog/pepe would break with a 500
- Check that the rest of the blogs work https://ubuntu-com-11947.demos.haus/blog/
Fixes https://github.com/canonical/ubuntu.com/issues/11948
=> Handle not found WordPress posts

navigation.yaml, templates/download/risc-v/index.html, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html
Build new Risc-v download page
- Go to https://ubuntu-com-11942.demos.haus/download/risc-v
- Check [copy docs](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit#)
- Don't forget to check the marketo ID, tab functionality, meta title. 
- At the time writing there is no meta image
Fixes https://github.com/canonical/web-squad/issues/5814
=> Build new risc-v download page

templates/download/iot/index.html
- Fixed broken link on /download/iot
- visit https://ubuntu-com-11951.demos.haus/download/iot
- find the RISC-V link under "Supported Platform"
- the link should take you to /download/risc-v
=> fix link on download/iot

templates/ai/index.html, templates/ai/what-is-kubeflow.html, templates/shared/_charmed-kubeflow-beta-banner.html
- Added banner for charmed kubeflow beta
- Reused `date_has_passed` function to takedown banner
- Check banner shows on https://ubuntu-com-11944.demos.haus/ai, https://ubuntu-com-11944.demos.haus/ai/what-is-kubeflow
**The blog link won't work until release date (17-08-2022)**
Fixes https://github.com/canonical/web-squad/issues/5802
=> Add charmed kubeflow beta banner

templates/security/docker-images.html
- Updated "Explore the images" link as per [copy doc](https://docs.google.com/document/d/1zZibtjU141e4mBxo_0PtfYxJ6e5fyaaAdFZ6v945XAM/edit)
- View the site locally in your web browser at: https://ubuntu-com-11952.demos.haus/security/docker-images
- Click on the link and see that it has been updated correctly
Fixes https://github.com/canonical/web-squad/issues/5854
=> [Copy update] /security/docker-images

templates/index.html
Remove the Spanish homepage call out
- Check out the demo and see that the page works well
- Extra bonus points for setting your VPN to Spain and loading the homepage 
Fixes https://github.com/canonical/ubuntu.com/issues/11955
=> Remove the Spanish homepage call out

templates/edge-computing/index.html, templates/internet-of-things/smart-city.html
The engage page path for this [engage page](https://discourse.ubuntu.com/t/edge-infrastructure-implementation-the-open-source-way/24533) was changed, and the pages linked to that old URL are broken. This is the fix
- Check that https://ubuntu-com-11954.demos.haus/engage/edge-infrastructure works, and you can download the whitepaper
- Check that /edge-computing "Download the whitepaper" is linking to the correct engage page
=> Fix engage page links

webapp/views.py
For security, to avoid users injecting all sorts of weird characters in the URLs and ending up with 500s, santisize URL
- Test that https://ubuntu-com-11960.demos.haus/blog/ubuntu-22-04-lts-released%0A doesn't cause a 500 now
- Check that other blogs on https://ubuntu-com-11960.demos.haus/blog work.
Fixes https://github.com/canonical/web-squad/issues/5842
=> Sanitize blog slugs

navigation.yaml, templates/security/cve/index.html, templates/templates/_navigation.html, webapp/context.py
- Simplified the subnav across the site, so that:
- there are no more than 6 sub nav items present on any bubble
- the "Overview" item is not visible
- there are no sub-subnav/breadcrumb versions of the bubble nav, such as this (https://ubuntu.com/legal/terms):
- [Open this spreadsheet](https://docs.google.com/spreadsheets/d/1YeTZP9sr2WUX2-N7clirZtGuARD0PMirHk0Ty-WUKU0/edit#gid=987317135)
- Visit https://ubuntu-com-11957.demos.haus/
- Work through the list of bubbles, see that any item in the spreadsheet that has a red title is no longer visible on the site in the subnav
- See that the subnav does not look broken
Fixes https://github.com/canonical/web-squad/issues/5237
=> remove overview and breadcrumbs from bubble navigations

templates/legal/confidentiality-agreement.html
- Add JS to hide/show US state list when country is US on NDA form
- Go to https://ubuntu-com-11966.demos.haus//legal/confidentiality-agreement
- Check there is not a 'US State' input by default
- Fill out the form, making sure to select 'United States' as your country
- The 'US State' should appear upon selection of country
- Check the form successfully submits by checking the payload
Without country as US:
With country as US:
Fixes: https://github.com/canonical/web-squad/issues/5887
=> Add JS to hide/show US state list when country is US on NDA form

templates/download/desktop/index.html
- Replaced "Microsoft store" with "Microsoft Store." on download/desktop
Before:
After:
=> Replace "Microsoft store" with "Microsoft Store."

static/js/src/chart-data.js, templates/shared/_kernel-support-schedule.html
- Update the version for 14.04.5 LTS
- Add a version to 20.04.5. LTS
- Check the copy is correct
- Open the demo and go to /kernel/lifecycle#support-lts
- See that Ubuntu 20.04.5 LTS has a version now.
Fixes https://github.com/canonical/ubuntu.com/issues/11964
=> Correct the Kernel lifecycle versions

templates/security/index.html, tests/cypress/forms/forms_spec.js
- Remove duplicated `data-testid`
- Update cypress test for the required field on `/download/iot/intel-iotg`
How to run cypress test locally for forms on ubuntu.com 
1. Make sure you have marketo keys in your .env.local
2. Move this file `/tests/cypress/forms/forms_spec.js` into the `/tests/cypress/integration` folder.
(The cypress test for forms is only run once a day, so it is in the separate folder called `forms`. The other cypress tests are run every time a PR is made so they are in the `integration` folder.)
3. Run `ubuntu.com` locally 
4. Go to` package.json` and update `baseURL` of the “cypress:open” script to the url where ubuntu.com is currently running in your machine.
(i.g.)  "cypress:open": "cypress open --config-file tests/cypress/cypress.json --config …
=> Fix cypress test

templates/engage/thank-you.html, webapp/views.py
- Added custom thank-you text for engage pages thank you page
- Added Form only engage page
- Go to https://ubuntu-com-11978.demos.haus/engage/hpe-battle-card/thank-you and check that now we can show the custom text that appears in the [discourse `thank_you_text` metadata](https://discourse.ubuntu.com/t/hpe-sell-more-infrastructure-and-open-source-support/30098)
- Check that other engage pages on https://ubuntu-com-11978.demos.haus/engage are showing the default text as usual.
Fixes #11971
Fixes #11972  
=> Custom thank-you text for engage pages

releases.yaml
Update for the 20.04.5 release with the checksums
- Go to /download/alternative-downloads
- Check the content has 20.04.5 instead of 20.04.4
- Try the download (_might not be published yet but goes to where you expect_)
Fixes https://github.com/canonical/ubuntu.com/issues/11989
=> Update for the 20.04.5 release

templates/download/server/manual.html
- Updated Ubuntu Server download page according to the [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
- Visit the demo at https://ubuntu-com-11993.demos.haus/download/server
- Verify that the page content matches the [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
Fixes https://github.com/canonical/commercial-squad/issues/707
=> [Copy update] Ubuntu Server download page

static/sass/_layout-tutorial.scss, templates/security/cve/cve.html, templates/tutorials/tutorial.html
- Removed redundant subnav on CVE pages and tutorial guide (see issues for context)
- Added tutorial title to the page as a `h1` element
- View the site locally in your web browser at: https://ubuntu-com-11983.demos.haus/security/cves
- Click on any CVE (eg: https://ubuntu-com-11983.demos.haus/security/CVE-2021-46837)
- See that only 1 subnav exists
- Go to https://ubuntu-com-11983.demos.haus/tutorials/guidelines#1-overview
- See that only 1 subnav exists
Fixes https://github.com/canonical/ubuntu.com/issues/11982, https://github.com/canonical/ubuntu.com/issues/11985
=> Remove redundant subnav on cve pages and tutorials

static/js/src/tutorial-list.test.js, templates/certified/search-results.html, templates/certified/shared/category-search-results.html, templates/search.html, templates/templates/_navigation.html, templates/templates/docs/shared/_search-box.html, templates/tutorials/index.html
- Added "Submit" label to search input submit buttons that previously were missing an accessible label
- Visit https://ubuntu-com-11995.demos.haus/core/services/guide/custom-image
- Using the [WAVE extension](https://wave.webaim.org/extension/), see that the "Empty button" error is not present
- Compare to the live page to confirm that the error is present in production https://ubuntu.com/core/services/guide/custom-image
- Visit any of the URLs listed in [this spreadsheet](https://docs.google.com/spreadsheets/d/12PCiksNMTyIrb2jEbXkCrj4thtPg5eng5rYPexCAObE/edit#gid=0) (best to pick a few at random given there are 500 rows in that sheet) and confirm the same thing. There should always be one less error on the demo than there is on production.
Live:
Demo:
Fixes #11890
=> Add accessible label to all search submit buttons

static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx
UA: Improve cancel subscription dialog message.
- Go to `/advantage` and try to open the dialog to cancel one of your subscriptions.
- Make sure the message is generic and we are not displaying `The <strong>10 machines</strong> will stop receiving updates and` every time.
=> UA: Improve cancel subscription dialog message.

templates/credentialing/index.html, templates/credentialing/syllabus.html, webapp/app.py, webapp/shop/cube/syllabus.json, webapp/shop/cube/views.py
- Add syllabus for each microcertification
- Visit https://ubuntu-com-11996.demos.haus/credentialing
- Verify that the Syllabus button appears in each exam description
- Verify that clicking each Syllabus button takes you to the corresponding tab on https://ubuntu-com-11996.demos.haus/credentialing/syllabus
https://warthogs.atlassian.net/jira/software/c/projects/CRED/boards/776
Exam descriptions with Syllabus button:
Tabbed syllabus:
=> Added syllabus file and links in index

templates/desktop/flavours.html
- Updated Flavor screenshots to 22.04
- Check the /desktop/flavours page
https://github.com/canonical/web-squad/issues/5925
=> Update flavor screenshots to 22.04

templates/templates/navigation-download-h.html
- Adds RISC-V link to global nav as per [copydoc](https://docs.google.com/document/d/11pX5gxOE6UWljIGRBZdwuCL1MHzs4pNgxJpK0mcIqdQ/edit)
- Go to https://ubuntu-com-12009.demos.haus/, open the 'Download' drop-down of the top navigation.
- Check a link for 'RISC-V platforms' is visible in the correct column and links to  https://ubuntu-com-12009.demos.haus//download/risc-v
Fixes https://github.com/canonical/web-squad/issues/5913
=> Add RISC-V link to global nav

templates/openstack/why-openstack.html
- Build page on `/openstack/why-openstack`
- Compare page against [copy doc](https://docs.google.com/document/d/1StqylVToo1URkhLvNfl17vZ52H35fXCVOR1aMKG1aGU/edit#)
- Demo : https://ubuntu-com-11992.demos.haus/openstack/why-openstack
Fixes [#5823](https://github.com/canonical/web-squad/issues/5823)
=> Build why-openstack page

webapp/views.py
Redirect not found blogs to 404 page
- Check that https://ubuntu-com-12011.demos.haus/blog/this-article-is-invalid goes to 404
Fixes https://github.com/canonical/ubuntu.com/issues/12008
=> Redirect not found blogs to 404 page

templates/openstack/why-openstack.html
- Closing button tag was missing and added the closing button tag but the button still didn't work. so I just replaced   `button` tags with `a` tags. 
- Go to https://ubuntu-com-12017.demos.haus/openstack/why-openstack  and Find "Read case study" button. Click it and check the button works.
=> Fix broken button

templates/hpc/base_hpc.html, templates/hpc/use-cases.html
- Build page on `/hpc/use-cases`
- Compare page against [copy doc](https://docs.google.com/document/d/133bou6x0uCiZxezjjr6uroq73mSPM3MdSiWpS5WA1XM/edit#)
- Some assets are missing and I left comment about them in the copy doc. Demo has been shared with the PdM for feedback.
- Demo at https://ubuntu-com-12010.demos.haus/hpc/use-cases
Fixes [#5867](https://github.com/canonical/web-squad/issues/5867)
=> Build use-cases page

templates/wsl/index.html
- Updated the include on /wsl to use the updated blog tag
- Visit https://ubuntu-com-12037.demos.haus/wsl
- Or check out this branch, run `dotrun` and visit http://0.0.0.0:8001/wsl
- See that there are blogs listed under the "Latest Ubuntu WSL news from our blog ›" section
- See also the "our blog" link works
- Compare to live, where are there no posts and the "our blog" link 404s: https://ubuntu.com/blog/tag/wsl
Fixes https://github.com/canonical/web-squad/issues/5962
=> update blog tag on /wsl

konf/site.yaml, webapp/login.py
- added a variable to the staging and demo environments to change what `CANONICAL_LOGIN_URL` points to in those environments.
- Visit https://ubuntu-com-12040.demos.haus/login
- It should direct you to https://login.staging.ubuntu.com/
=> add demo and staging variables for login URL

templates/security/notices/usn.html
- Fixed broken references link
- View the site locally in your web browser at: http://0.0.0.0:8001/security/notices/USN-5583-2
- See that the "Related Notices" title is no longer a link
Fixes https://github.com/canonical/ubuntu.com/issues/12028
=> Fix broken references link

static/js/src/dynamic-forms.js
- fixes the closing contact modal when we mousedown inside modal then we release it on backdrop.
(this is a known issue in chrome)
- Click on the CTA to open the modal.
Fixes #11648 
=> fix: closing contact modal when we release mouse on backdrop

templates/core/index.html, templates/internet-of-things/index.html, templates/internet-of-things/smart-home.html
:warning: **don't merge yet**: we're waiting on a link to a press release before this can go live, we should have it on the 21st September :warning: 
- Updated the copy on /iot/smart-home based on the [copy doc](https://docs.google.com/document/d/1zwB-6Flt0Jm7XIxhWUWRJjKC1WCGVmVVNmPHtyOTHuE/edit#heading=h.bng9y130lz6e)
- Added a link to /smart-home from /core and /internet-of-things
- Visit https://ubuntu-com-12041.demos.haus/internet-of-things/smart-home
- See that the copy matches the new section in the copy doc
- Visit https://ubuntu-com-12041.demos.haus/internet-of-things
- See that the Smart home link works
- Visit https://ubuntu-com-12041.demos.haus/core
- See that the Smart home link works
Fixes https://github.com/canonical/web-squad/issues/5939
=> Update /iot/smart-home copy

templates/server/docs/document.html
- This change fixes server documentation navigation. Note that other docs may still be affected other than core and server
Fixes #12048 
=> fix expandable navigation in server docs

templates/core/docs/document.html, templates/server/docs/document.html, templates/templates/docs/shared/_docs.html
- Fixed server docs side nav expanding functionality in multiple places
- Visit:
- https://ubuntu-com-12050.demos.haus/ceph/docs
- https://ubuntu-com-12050.demos.haus/server/docs
- https://ubuntu-com-12050.demos.haus/core/docs
- https://ubuntu-com-12050.demos.haus/security/certifications/docs
- https://ubuntu-com-12050.demos.haus/security/livepatch/docs
- See that all the expandable nav sections work correctly i.e.
=> add side navigation js to shared docs template

templates/engage/shared/_de_thank-you.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_es_thank-you.html, templates/engage/shared/_fr_thank-you.html, templates/engage/shared/_it_thank-you.html, templates/engage/shared/_pt_thank-you.html, templates/engage/shared/_ru_thank-you.html, templates/engage/thank-you.html, webapp/views.py
This feature will block users from accessing the resource (e.g. a whitepaper) directly, instead it will send an email with the resource attached (pending work on marketo back-end).
This is triggered by the metadata `access_to_content` which is set in the discourse topic
- Check https://ubuntu-com-12042.demos.haus/engage
- Click on the "Test access to content" engage page.
- Fill out the form and click download
- Compare with design https://miro.com/app/board/uXjVOjU5hYI=/
Fixes https://github.com/canonical/web-squad/issues/5817
=> Engage pages access to content feature

templates/credentialing/index.html, templates/credentialing/syllabus.html, webapp/app.py, webapp/shop/cube/syllabus.json, webapp/shop/cube/views.py
- Add syllabus for each microcertification
Related:
- https://github.com/canonical/ubuntu.com/pull/11996
- https://github.com/canonical/ubuntu.com/pull/12023
- Visit https://ubuntu-com-12058.demos.haus/credentialing
- Verify that the Syllabus button appears in each exam description
- Verify that clicking each Syllabus button takes you to the corresponding tab on https://ubuntu-com-12058.demos.haus/credentialing/syllabus
https://warthogs.atlassian.net/browse/CRED-94
Tabbed syllabus:
=> Add Credentialling syllabus

templates/kubernetes/managed.html
- Updated a the datasheet linked to on /kubernetes/managed
- Visit https://ubuntu-com-12062.demos.haus/kubernetes/managed
- Click the "Read the datasheet" link in the hero strip
- See that it links to https://assets.ubuntu.com/v1/0041f679-Enterprise_Kubernetes+Datasheet_27.09.22.pdf, and not the one that's currently live (https://assets.ubuntu.com/v1/c5f59e1c-Enterprise_Kubernetes+Datasheet_16.09.21.pdf)
Fixes https://github.com/canonical/web-squad/issues/6006
=> update link to datasheet

templates/pro/index.html
- people are finding their way to /pro ahead of schedule, which currently leads to a 404:
- this PR adds a "Coming soon" page at /pro for a slightly better experience in the short term
- visit https://ubuntu-com-12067.demos.haus/pro
- see that the page shows "Coming soon", rather than a 404
=> add temp pro page

static/js/src/advantage/api/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/tests/factories/api.ts, tests/shop/advantage/test_helpers.py, webapp/shop/api/ua_contracts/helpers.py
- Add renewal status tag on user subscriptions
- Go to https://ubuntu-com-12012.demos.haus/
- Login
- Buy monthly/early subscription
- Check that renewal tag changes based on the auto-renewal setting
- Ask for help with testing the tag for renewals
Fixes #https://github.com/canonical/commercial-squad/issues/711
=> Add renewal status tag on user subscriptions

templates/engage/shared/_es_thank-you.html, templates/engage/shared/_pt_thank-you.html, templates/engage/shared/_ru_thank-you.html
- A few pages missing an `endif`.
- Check https://ubuntu-com-12068.demos.haus/engage/ES-Business-guide-to-hybrid-multicloud, fill out the form and make sure the page renders.
- Same with https://ubuntu-com-12068.demos.haus/engage/ru/enterprise-kubernetes-comparison
- Same with https://ubuntu-com-12068.demos.haus/engage/pt/vmware-para-o-openstack
- If you get a marketo error after submitting the form, it means marketo form doesn't work on demo, so test this PR locally, you may need to comment out line 832-831 (to skip submission to marketo).
=> Fix: thank you page missing closing endif

redirects.yaml
Got a request from Felicia to redirect to new blog post, so that Google results go to the right URL
- https://ubuntu-com-12074.demos.haus/blog/canonical-announces-ubuntu-22-04-lts-support-for-flexran-reference-software-2 should redirect to https://ubuntu-com-12074.demos.haus/blog/canonical-announces-ubuntu-22-04-lts-support-for-flexran-reference-software
Fixes #
=> Redirect old blog post to new blog post url

templates/security/index.html
- Add `u-hide--medium` on two images 
1. Go to https://ubuntu-com-12075.demos.haus/security 
2. Check images are hidden on medium/small screens
=> Add `u-hide--medium` class

templates/hpc/index.html
- updated the Canonical product logos on /hpc
- Visit https://ubuntu-com-12077.demos.haus/hpc
- See that the logos in the MAAS, Ubuntu, OpenStack, CharmHub and Kubernetes sections are consistent with each other and look good.
Fixes https://github.com/canonical/web-squad/issues/6019
=> update canonical logos on /hpc

templates/kubernetes/kubernetes-operations-survey.html
Updated the Kubernetes Operations survey as per [the brief](https://docs.google.com/document/d/17t6IVb9DzIj66136Iw08pOpWCof5qHz38B_Qg6K_RcY/edit)
- Go to https://ubuntu-com-12082.demos.haus/kubernetes/kubernetes-operations-survey
- Check that the "Take the survey" button brings up [this form](https://krzty8pox19.typeform.com/to/gAftOg2f) in a modal
- Check that the "Competition Terms & Conditions" link goes to https://pages.ubuntu.com/rs/066-EOV-335/images/Cloud%20Survey%202022%20Q4%20-%20Terms%20and%20Conditions%20-%20Canonical%2026.09.22%20.pdf
Fixes …
=> Update Kubernetes Operations survey

templates/desktop/developers.html, templates/desktop/index.html, templates/desktop/organisations.html, templates/download/desktop/index.html, templates/download/desktop/thank-you.html, templates/pricing/desktops.html, templates/shared/contextual_footers/_download_enterprise_support.html, templates/shared/contextual_footers/_download_helping_hands.html
- Updated copy referencing beta launch and update contextual footer links
- https://ubuntu-com-12085.demos.haus/pricing/desktops
- https://ubuntu-com-12085.demos.haus/desktop/organisations
- https://ubuntu-com-12085.demos.haus/desktop/developers
- https://ubuntu-com-12085.demos.haus/download/desktop
- https://ubuntu-com-12085.demos.haus/download/desktop/thank-you
- https://ubuntu-com-12085.demos.haus/download (addressed comments not beta related)
- Compare against beta related comments in docs listed on [spreadsheet](https://docs.google.com/spreadsheets/d/12AHtT35OfSDYH1kjZ0XzfrI88HTsUyD28sg_yCTe-ts/edit#gid=0) lines 19-25
Fixes …
=> Update copy referencing beta launch and update contextual footer links

templates/landscape/pricing.html
- updated instances of "Ubuntu Advantage" to "Ubuntu Pro" on /landscape/pricing, according to copy doc: https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit
- visit https://ubuntu-com-12086.demos.haus/landscape/pricing
- see that the page matches the copy doc
Fixes https://github.com/canonical/web-squad/issues/6025
=> update landscape pricing for pro launch

templates/legal/open-source-licences.html, webapp/app.py, webapp/views.py
Added an open-source package licences page which loads the data for each release from a static JSON file hosted on assets.
- VIsit https://ubuntu-com-11604.demos.haus/legal/open-source-licences
- Check that the first navigation item is selected and the table is populated
- Select other releases and check the navigation works and the table works when the json is correct.
- Impish and Focal desktop have broken source data at the moment
=> Open-source package licences page

templates/desktop/organisations.html, templates/pricing/desktops.html
- Updated an asset link on /desktop/organisations and /pricing/desktops, according to the copy docs:
- https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit
- https://docs.google.com/document/d/1xVtaZ7wr5sdBqye3Gc-XWXEpNqXaol8uDdMwJ_KyOO8/edit#
- Visit /desktop/organisations and /pricing/desktops
- See that the links to the datasheet have been updated to point to this asset: https://assets.ubuntu.com/v1/65ca4536-Ubuntu+Desktop+DS+06.09.22.pdf
Fixes https://github.com/canonical/web-squad/issues/6039
=> update whitepaper asset link on /pricing/desktops and /desktop/orgs

templates/engage/shared/_de_thank-you.html
- Fixed broken template syntax on DE engage thank you page
- Visit https://ubuntu-com-12092.demos.haus/engage/de/openstack-made-easy/thank-you
- You should see the page, rather than a 500 error (compare to live: https://ubuntu.com/engage/de/openstack-made-easy/thank-you)
Fixes https://github.com/canonical/ubuntu.com/issues/12091
=> fix broken de engage thank you page

templates/download/desktop/index.html
- Replace statically rendered latest-news strip with the dynamic latest news module
- Go to https://ubuntu-com-12098.demos.haus/download/desktop and scroll to the bottom where you will find the latest-news section
- Check that the articles being pulled are coming from [wordpress](https://admin.insights.ubuntu.com/wp-admin/edit.php?tag=ubuntu-desktop)
Fixes https://github.com/canonical/web-squad/issues/6034
=> Render latest news strip dynamically on /download/desktop

templates/advantage/table/_contract-name.html, templates/appliance/shared/_verify-checksums-pc.html, templates/appliance/shared/_verify-checksums.html, templates/credentialling/microcerts.html, templates/download/shared/_verify-checksums.html, templates/templates/_navigation.html
- Fixed the incorrect ID values for `aria-controls` attributes
- Check that the "Ubuntu", "Windows", and "macOS" tabs still work in the "Installation instructions" section on the following pages:
- https://ubuntu-com-12102.demos.haus/appliance/adguard/intel-nuc
- https://ubuntu-com-12102.demos.haus/appliance/lxd/intel-nuc
- https://ubuntu-com-12102.demos.haus/appliance/mosquitto/intel-nuc
- https://ubuntu-com-12102.demos.haus/appliance/nextcloud/intel-nuc
- …
=> Fix incorrect id value for aria-controls attributes

templates/pricing/pro.html, templates/shared/pricing/_ua-for-infrastructure.html
- Ubuntu pro price page changes.
- Go to: https://ubuntu-com-12100.demos.haus/pricing/pro
- Is the price showing $500? It should.
- Do you see any Apps Only column? You should not.
Fixes #https://github.com/canonical/web-squad/issues/6047
=> Ubuntu pro price changes

templates/advantage/index-no-login.html, webapp/shop/decorators.py
- Added two links to the beta discourse tutorial: https://discourse.ubuntu.com/t/ubuntu-pro-beta-tutorial/31018
- View the page at /pro, see that "Discover the step-by-step tutorial" and "Tutorials" both link to https://discourse.ubuntu.com/t/ubuntu-pro-beta-tutorial/31018
=> add discourse tutorial links

redirects.yaml
- redirect /pro/beta to https://discourse.ubuntu.com/t/ubuntu-pro-beta-tutorial/31018
- Visit /pro/beta
- See that you are redirected to https://discourse.ubuntu.com/t/ubuntu-pro-beta-tutorial/31018
=> add redirect for /pro/beta to discourse post

templates/advantage/base_advantage.html, templates/advantage/index-no-login.html
- Added a link to an as yet unpublished press release
- Visit https://ubuntu-com-12116.demos.haus/pro
- Find the "Read the press release" link, see that it points to https://ubuntu.com/blog/ubuntu-pro-beta-release
- It will 404 at the moment, it is due to be published at 13:55 UK time
=> add link to pro press release

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
change ua to pro in cli help text
Fixes #
=> copy change ua to pro in cli help text

navigation.yaml
- previously the subnav heading on /pro read "Support", now it reads "Pro"
- Go to /pro
- See "Pro" in the subnav
- Yay!
=> update pro subnav to read "Pro"

templates/advantage/index-no-login.html
- update the "Let's talk" link on u.c/pro to direct to https://ubuntu.com/contact-us/form?product=pro, rather than trigger a contact modal
- Visit /pro
- Find the "Let's talk" link and follow it
- It should lead you to https://ubuntu.com/contact-us/form?product=pro
=> update let's talk link

templates/templates/footer.html
- Add automotive link on the footer
- Go to https://ubuntu-com-12133.demos.haus/
- Scroll down to the footer
- Can you see the automotive link? [(docs)](https://docs.google.com/document/d/117orMiMtXPBwowp6sjJ1ygjROYjSLnUkvosac7nqmpw/edit)
Fixes #https://github.com/canonical/commercial-squad/issues/723
=> Add automotive link

templates/security/notices/usn.html
- Updated USN as per request (see issue for a link to the thread if needed):
- View the site locally in your web browser at: http://0.0.0.0:8001/security/notices/USN-5656-1 
- See that the text has been updated as requested
Fixes https://github.com/canonical/ubuntu.com/issues/12126
=> Update USN template

templates/account/index.html, templates/account/invoices/index.html
- Changed Invoice listings to now show Ubuntu Pro instead of Canonical UA
- Changes /account page to show Ubuntu Pro instead of Ubuntu Advantage for Infrastructure
- [/account](https://ubuntu-com-12136.demos.haus/account) should show Ubuntu Pro instead of Ubuntu Advantage for Infrastructure
- [/account/invoices](https://ubuntu-com-12136.demos.haus/account/invoices) should show Ubuntu Pro instead of Canonical UA in the dropdown as well as the invoice listing.
Fixes # …
=> change to Pro for /account and /account/invoices

templates/engage/shared/_de_thank-you.html, templates/engage/thank-you.html, webapp/views.py
As part of access to content, remove block so that it's still possible to access the thank-you page directly to download whitepapers.
- Go to https://ubuntu-com-12107.demos.haus/engage/test-access-to-content and fill up the form
- Check that the thank-you page shows the "email sent" message
- Go to any other whitepaper and check that you can access the /thank-you page without filling up the form
Fixes https://github.com/canonical/web-squad/issues/5818
=> Remove block access to content

templates/security/disa-stig.html
- DISA-STIG page has new link to [Supplemental Automation Content](https://public.cyber.mil/stigs/supplemental-automation-content/) and Advantage naming changed to Pro
- Copy doc: https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit?usp=sharing
- Visit [https://ubuntu-com-12140.demos.haus/security/disa-stig](https://ubuntu-com-12140.demos.haus/security/disa-stig)
- No mention of Ubuntu Advantage (changed to Ubuntu Pro and Ubuntu Pro on Public Clouds)
-  page has new link to [Supplemental Automation …
=> copy changes to add link and change adv to pro

templates/about/packages.html
- The "get started making a charm" is a private unlisted discourse topic, which is not accessible by search engines and people outside of the org, so replacing it with a public link.
- Also remove a stranger character that can't be rendered correctly.
- Go to https://ubuntu-com-12138.demos.haus/about/packages.
- Check that the problems mentioned in [the issue](https://github.com/canonical/ubuntu.com/issues/11786) are fixed:
- Strange character
- Inaccessible link at [Get started making a charm](https://discourse.juju.is/t/charm-writing/1260?_ga=2.57613417.231841935.1665062587-211299447.1665062587)
Fixes https://github.com/canonical/ubuntu.com/issues/11786
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148 …
=> Fix charm link

static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx, static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, webapp/shop/api/ua_contracts/builders.py
- Update is_expiring, is_grace_period and is_expired notifications
- Implement custom messages for subscription details
- Make all subscriptions disappear after a max of 90 days 
- Hard to QA since we no longer have monthly subscriptions.
- Some screenshots for proof:
Is expiring soon:
Grace period:
Expired:
Fixes #https://github.com/canonical/commercial-squad/issues/710
=> Implement renewal expiration notification

templates/security/disa-stig.html
- Fixed small typo "Pubic Clouds" to "public cloud"
- Doc: https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit#heading=h.pc9i27tqv0qt
- View the site locally in your web browser at: https://ubuntu-com-12146.demos.haus/security/disa-stig
- See that typo has been fixed and that copy matches the doc
=> Fix copy typo

templates/base_index.html
- Update centos logo on homepage as suggested in [this issue](https://github.com/canonical/ubuntu.com/issues/11953)
- Go to u.com homepage and check the logo is updated to the one in the issue
Fixes https://github.com/canonical/ubuntu.com/issues/11953
=> Update centos logo on homepage

tests/cypress/forms/forms_spec.js
- Pro page needs to be removed in cypress test as this link  "Join our free beta programme for Ubuntu Pro on prem" doesn't exist any more. 
https://discourse.canonical.com/t/how-to-run-cypress-test-locally-for-forms-on-ubuntu-com/558
=> Remove pro page on cypress test

templates/pro/beta.html
**note** The changes are not highlighted in the doc, I used the difference that can be viewed in dicourse between older and newer posts. Most of the changes can be seen between versions 9-10 of the [discourse post](https://discourse.ubuntu.com/t/ubuntu-pro-beta-tutorial/31018), but there are some other changes more recently.
- Updates /pro/beta based on [copydoc](https://docs.google.com/document/d/1GFVENQ9g5U4FSyqZHboXVEQ_RHKxRSwq3NC9PWrwURs/edit#)
- To QA you can use the copydoc but to make things easier I would check out the discourse post to see the difference.
Fixes https://github.com/canonical/ubuntu.com/issues/12176
=> Updates /pro/beta to match copydoc

static/js/src/dynamic-forms.js
- Moves focus inside modal when opened
- Traps focus inside modal
- Returns user to initial modal trigger when closed
- Go to a couple different modal forms and open them
- See that focus is automatically set within the modal
- Use `tab` and `shft+tab` to navigate around the modal, see that focus stays within the modal
- Navigate to the `close` button and press it, see that focus returns to the button pressed to initially open the modal
Fixes https://github.com/canonical/ubuntu.com/issues/12002
=> Move and trap focus in modal when opened 

static/sass/styles.scss, templates/aws/pro.html, templates/azure/pro.html
- Update /aws/pro for 22.04 based on [copydoc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#heading=h.rwz46gtc2v3z)
- Updates /azure/pro to follow the same `p-status-label--rounded` pattern for the 'latest' label as /aws/pro
- Go to https://ubuntu-com-12134.demos.haus/aws/pro and see that it matches the [copydoc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#heading=h.rwz46gtc2v3z)
- Compare 'status' chip the design, found at the bottom of [this page](https://docs.google.com/document/d/1uiJ00ycDhyBP_QOIwSV5Jc21I-h0eZft1dONsIAqOxA/edit#). Note, the one used in this PR is a new pattern that is being suggested to vanilla [here](https://github.com/canonical/vanilla-framework/issues/4574)
Status chip:
Fixes …
=> Update /aws/pro for 22.04

redirects.yaml
- Removed the redirect from /pro/beta to the discourse post
- Visit /pro/beta
- See that you are not redirected, and that the page matches the copy doc
=> remove /pro/beta redirect

templates/pro/index.html
- Change links to buttons (as per https://github.com/canonical/ubuntu.com/issues/12192)
- visit the /pro page, verify the ctas have been converted to buttons and Let's talk has changed to "Contact us"
Fixes https://github.com/canonical/ubuntu.com/issues/12192
=> update copy to make lets talk and requestbeta access CTAs more prominent

releases.yaml, templates/desktop/developers.html
Update desktop/developers
**Only 22.10 updates**
- Go to https://ubuntu-com-12166.demos.haus/desktop/developers and compare with [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#heading=h.b332hqeenxjz)
Fixes https://github.com/canonical/web-squad/issues/6083
Fixes https://github.com/canonical/web-squad/issues/6109
=> Update /desktop/developers for 22.10 release

templates/kernel/index.html
Instead of linking to a specific line number within the README in the ubuntu-cve-tracker repo (which may change over time), instead link to the nicer looking HTML page on people.canonical.com/~ubuntu-security/priority.html
Signed-off-by: Alex Murray <alex.murray@canonical.com>
Fixes # …
=> templates/kernel/index.html: Fix link to Ubuntu CVE priorities

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
- Add "Ubuntu Pro (esm-apps --beta) tutorial" link on free token
- Click "Free Personal Token" and check the "Ubuntu Pro (esm-apps --beta) tutorial" appears.
Fixes [#732](https://github.com/canonical/commercial-squad/issues/732)
=> Add tutorial link on free token

releases.yaml, templates/download/desktop/index.html
Updates for 22.10.
**Only 22.10 release updates**. I could not close the other comments, they were already addressed. Download links won't be ready until the release date
- Go to https://ubuntu-com-12174.demos.haus/download/desktop
- If demo doesn't build, please checkout this branch and `dotrun` it.
- Compare against [copy doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#)
Fixes https://github.com/canonical/ubuntu.com/issues/12161
=> Update desktop download page for 22.10 release

templates/download/index.html
- Added a Kinetic + Jammy combo asset on /download (thanks @lyubomir-popov for v quick turnaround on the asset itself)
- Visit https://ubuntu-com-12209.demos.haus/download
- See that the mascot asset features both the LTS (Jammy) and the latest release (Kinetic)
Fixes https://github.com/canonical/web-squad/issues/6129
=> Update mascot asset on /download

releases.yaml
- Updated releases.yaml with 22.10 checksums
- Check the checksums match the ones given in the original issue (several of the RISC-V checksums aren't included, we've been asked not to publish the 22.10 update for that page until the 25th, we're checking in with Felicia later today to clarify why that is)
- Visit /download/desktop and /download/server, find the 22.10 download CTAs, click them. They won't work yet because the images aren't live.
Fixes https://github.com/canonical/ubuntu.com/issues/12212
=> 22 10 checksums

templates/download/raspberry-pi/index.html
Update raspberry Pi dowload page for Ubuntu 22.10
- Go to https://ubuntu-com-12197.demos.haus/download/raspberry-pi and compare with [copy docs](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#)
Fixes https://github.com/canonical/ubuntu.com/issues/12162
=> Ubuntu 22.10 raspberry Pi page update

static/js/src/chart-data.js
Update charts with latest 22.10 version
- Go to https://ubuntu-com-12207.demos.haus/desktop/developers and check that it contains the new 22.10 Kinetic Kudu release
Fixes https://github.com/canonical/web-squad/issues/6121
=> Update charts for Ubuntu 22.10

releases.yaml, static/js/src/chart-data.js, templates/desktop/developers.html, templates/desktop/flavours.html, templates/download/desktop/index.html, templates/download/index.html, templates/download/raspberry-pi/index.html, templates/download/server/manual.html
- Test 22.10 download links on once we get checksums and signal to release:
- /download/raspberry-pi (desktop and server)
- /download/desktop (check also the checksums are correct)
- /download/server
Fixes #
=> 22.10 launch

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx, static/sass/styles.scss, templates/pro/index.html
- Updated links on /pro to point to /pro/beta rather than the Discourse post
- appled `p-button` to a "Contact us" link
- Visit https://ubuntu-com-12208.demos.haus/pro
- See that the "Contact us" link looks like a button
- Find the "Discover the step-by-step tutorial" link and click it
- See that you are taken to /pro/beta
- Revisit /pro
- Find the "Tutorials" link and click it
- See that you are taken to /pro/beta
=> Update Pro beta links to point to /pro/beta

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/PurchaseModal/components/ModalSteps/StepTwo.tsx, static/js/src/PurchaseModal/utils/utils.ts, static/js/src/advantage/offers/components/BuyButton.tsx, static/js/src/advantage/offers/components/Offer/Offer.tsx, static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/RenewButton.tsx, static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewalModal.tsx, static/js/src/advantage/subscribe/blender/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/blender/components/PaymentModal/PaymentModal.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/PaymentModal/PaymentModal.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts, tests/cypress/integration/advantage/subscribe_spec.js
- Add pro service description checkbox on step 2 of the payment modal
- Go to `/pro/subscribe`
- Click "Buy now" Button 
- Fill in the forms 
- Check three checkboxes are displaying
Fixes [#731](https://github.com/canonical/commercial-squad/issues/731)
=> Add pro service description checkbox

templates/security/cve/cve.html, webapp/security/views.py
- Fixed broken links for Xenial (Kinetic) and Xenial(Melodic) packages (see issue for context)
- View the site locally in your web browser at: https://ubuntu-com-12222.demos.haus/security/CVE-2021-37146
- See that the links to Launchpad, Ubuntu, and Debian have been replaced with a link to ROS ESM for relevant packages (in this case, just the first 2)
- Check that link works
Fixes https://github.com/canonical/ubuntu.com/issues/12154
=> Fix broken package links

static/js/src/contextual-menu.js
- Fixed an issue with the contextual menu JS that was preventing the contextual menu from showing since this update: https://github.com/canonical/ubuntu.com/pull/12102
- Visit https://ubuntu-com-12224.demos.haus/download/desktop
- Click any download CTA
- You should be taken to a thank you page, cancel the download
- Click "Verify your download"
- A contextual menu should appear with information on how to verify your download on the command line
Fixes https://github.com/canonical/ubuntu.com/issues/12218
=> get contextual menu by id rather than query selector

navigation.yaml, templates/aws/support.html
- Build page on `/aws/support`
- Add a support link to the aws bubble menu ubuntu.com/aws/support
-  Go to /aws/support
- Compare page against [Brief](https://docs.google.com/document/d/1vkuuWmJLBZak2oZKhcl6SWNUw1rb-onOqiChLpskS0s/edit), [Design](https://www.figma.com/file/HNEdP4oXC23OBdiZrChWai/%2Fpro-support-pages), [UX](https://miro.com/app/board/uXjVPMizhN8=/) and [Copy doc](https://docs.google.com/document/d/1j_gH-pU1ldCGSoJ8EwXPtSFqhdS1zEY8mXUAqSDxK2U/edit#)
Fixes [#6064](https://github.com/canonical/web-squad/issues/6064)
=> Build page on /aws/support

static/js/src/navigation.js
We missed a "UA", copy change to "Ubuntu Pro"
change user menu navigation item copy
=> We missed a "UA", copy change to "Ubuntu Pro"

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, webapp/shop/api/ua_contracts/helpers.py
- Make unactionable renewals not show the "not renewaed" label
- Go to https://ubuntu-com-12219.demos.haus/pro/dashboard?email=albert.kolozsvari%2Btester4@canonical.com
- The subscription should not show a label
Fixes #https://github.com/canonical/commercial-squad/issues/742
=> Fix label for renewals

templates/templates/docs/shared/_docs.html
This change allows users to navigate through documentation pages by clicking a previous or next page button, making navigation faster when reading sequentially. The buttons show the name of the previous and upcoming pages, and the links correspond to the adjacent pages, regardless of section, with section pages included.
Fixes #
Here are some examples:
The end of the Server Documentation [munin page](https://ubuntu-com-12132.demos.haus/server/docs/tools-munin) will show:
The …
=> Add previous and next buttons for doc navigation

templates/tutorials/index.html, webapp/views.py
The code duplication (in the template and views function) caused the `Ubuntu advantage` topic to duplicate
Refactored into one single place. Loops should be performant as `continue` should skip the queue if matched.
- Go to https://ubuntu-com-12235.demos.haus/tutorials
- Check that `Ubuntu advantage` topic is not duplicated and that it does display tutorials
Fixes https://github.com/canonical/web-squad/issues/5053
=> Fix list of tutorial topics/categories

templates/download/risc-v/index.html
- Updated the hero content of the RISC-V page based on the suggestions in [the copy doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit#heading=h.etjq4twyztv2)
- _Drive by_: to encode the dash in the sub-heading 
- Check the copy changes match [the copy doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit#heading=h.etjq4twyztv2)
Fixes https://github.com/canonical/web-squad/issues/6163
=> Update the hero content of the RISC-V download page

redirects.yaml
Redirect old borken tutorial to new
- Go https://ubuntu-com-12238.demos.haus/tutorials/electron-kiosk/ , it should redirect to https://mir-server.io/docs/make-a-secure-ubuntu-web-kiosk
Fixes https://github.com/canonical/ubuntu.com/issues/11847
=> Redirect broken tutorial

templates/tutorials/tutorial.html
- Made anchor link column smaller so that it doesn't affect pagination, see issue for context
- View the site locally in your web browser at: https://ubuntu-com-12247.demos.haus/tutorials/gpio-on-raspberry-pi#1-overview (or any other )
- See that the link does not extend to the space right above the pagination buttons
Fixes https://github.com/canonical/ubuntu.com/issues/12246
=> Fix anchor link column

redirects.yaml, templates/pro/index.html, templates/shared/forms/interactive/advantage-beta.html
- Added a check to see if the user is logged in on /pro. If they're logged in, they can trigger the contact modal and the fields will be pre-populated with their SSO info (and the email field will be disabled). If they're not logged in, they're directed to SSO, and then returned to the page with the modal already open.
- Visit https://ubuntu-com-12248.demos.haus/pro
- Make sure you're logged out of SSO
- Find the "Login to request beta access" CTA and click it
- You should be taken to SSO and asked to login
- Login
- When you've successfully logged in, you should be returned to /pro with the contact modal already populated (including a disabled email address field)
- Visit /pro again (without the #get-in-touch hash)
- See that the "Login to request beta access" CTA has been updated to …
=> Require SSO login for /pro beta signup form

templates/pro/index.html
- Add link on /pro based on [copydoc](https://docs.google.com/document/d/1In4NSnckAtL51_7D_AZCHa6TPnPGXqctXo-5rE77_aY/edit#)
- Compare against changes in copydoc
Fixes https://github.com/canonical/web-squad/issues/6180
=> Add link on /pro

konf/site.yaml, requirements.txt, templates/credentials/index.html, templates/shared/_credentials-contact-us-form.html, webapp/views.py
- Marketo is unreliable so we are also storing a backup in google spreadsheet
- Checkout /credentials
- Link to sign up form should be available
- Checkout /credentials/sign-up
- Filled out data should appear in [Marketo](https://engage-sj.marketo.com/?munchkinId=066-EOV-335#/classic/SL100906930B2LA1)
- Filled out data should appear in [Google Sheets](https://docs.google.com/spreadsheets/d/1L-e0pKXmBo8y_Gv9_jy9P59xO-w4FnZdcTqbGJPMNg0/edit?usp=sharing) 
Fixes # …
=> Cue beta signup spreadsheet

static/sass/_pattern_component-table.scss, templates/certified/model-details.html
- Added 22.04 column and updated sass file
- View the site locally in your web browser at: http://0.0.0.0:8001/certified/202204-30238
- See that the relevant column has been added to the table
Fixes https://github.com/canonical/ubuntu.com/issues/12250
=> Update table to include 22.04

templates/lxd/index.html
- Fixed missing space in command description.
- Updated the example command to show usage with the latest LTS version.
- View the site locally in your web browser at: http://127.0.0.1:8001/lxd
- See the updated commands and example usages.
N/A
=> Fix lxd command typo and update example to latest LTS

templates/model-driven-operations/index.html
- Replaced links as per [copy doc](https://docs.google.com/document/d/1G4sSrM-FQIL2c1Uj8PvW6oGUKcJ9HAK5TwnKhFa4sOY/edit#heading=h.g5a048d6b0vb)
- Confirm that the links have been replaced.
Fixes [canonical/workplace-engineering-squad/#871](https://github.com/canonical/workplace-engineering-squad/issues/871)
=> [copy update] u.c/model-driven-operations - replace links

navigation.yaml, static/js/src/navigation.js
I received a request from @lechsandecki via Mattermost to update the subnav on /pro and /support to:
Your subscriptions | Account users | Support | Pricing | Discourse
and to drop the "New" tag on Account users - this PR does both things.
- Visit https://ubuntu-com-12276.demos.haus/pro
- See that the subnav matches the list above
- Visit https://ubuntu-com-12276.demos.haus/support
- See that the subnav matches the list above
=> update /pro and /support subnavs

tests/cypress/forms/forms_spec.js
- Fix cypress test for `/credentials/sign-up`
https://discourse.canonical.com/t/how-to-run-cypress-test-locally-for-forms-on-ubuntu-com/558
=> Fix cypress test for /credentials/sign-up

templates/subscription-centre/base_subscription-centre.html, templates/subscription-centre/index.html, webapp/app.py, webapp/views.py
- Create python module to fetch user subscriptions
- Create folder/files where subscription centre will reside
- Make sure you have Marketo credentials in your `.env.local`
- using a test marketo accout (there is one called 'test' I recommend using, that's already filled in), fill in the user info field (on marketo) called '__prototype_interests' with a comma separated list. 
- Get the <leadId> from the url params
- Run the project and visit /subsciption-centre?id=(leadId)
- You should see the response that includes the comma separated list
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?modal=detail&selectedIssue=WD-229
=> Create python module to fetch user subscriptions

static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/blender/components/Form/Quantity/Quantity.tsx, static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx
- Store checkout states in local storage 
- Remove stored local storage after purchasing 
- Go to `/pro/subscribe`
- Select items
- Refresh page or log in and see the selected items remains as selected.
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-304
=> Store checkout states in local storage

templates/download/iot/intel-iot.html
- Fixes the links that had types on /intel-iot, see [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
Fixes https://github.com/canonical/web-squad/issues/6207
=> Fix link typo on /intel-iot

templates/shared/forms/interactive/advantage-beta.html
On the https://ubuntu.com/pro#get-in-touch form, the email field is disabled to avoid modification. A side effect is the creation of leads without email addresses as disabled form fields are not sent on form submission.
- Added a hidden duplicate email field when the user email is available from SSO.
- When submitting the /ubuntu.com/pro#get-in-touch form after SSO login, ensure the form submission data contains the email address.
=> Ubuntu Pro Upgrade form - Duplicated hidden email field

static/sass/styles.scss, subscriptions.yaml, templates/subscription-centre/index.html, webapp/views.py
- Add logic to python module pull in subscriptions.yaml tags
- Build /subscription-centre template and populate with user subscriptions
- Build 'unsubscribe' modal and associated JS
- Add SCSS class for `p-separator.is-shallow`
- Update subscriptions.yaml with missing data
- Check that all the tags are being pulled from subscriptions.yaml and rendered on /subscription-centre
- Check that the a user previously selected tags are selected on page load
- Check the page/modal are accessible
Fixes https://warthogs.atlassian.net/browse/WD-231
=> Build /subscription-centre template

webapp/views.py
- This adds the Marketo Munchkin cookie value to the form payload
- If not present, passing undefined is expected in that field.
Fixes #
=> Pass Marketo cookie value to form payload

static/js/src/accordion.js
- There was a use case on subscription center where opening large accordion panels would cause the view port to move, and make the contents of the accordion panel not visible. This adds logic to check and move the accordion panel into view when opened.
- Find an accordion, when opening panels with a lot of content the screenview should always keep the target panel in view.
- You can add more content to a individual panel to see the effect more clearly
=> Update accordion.js to move to target when panel is opened

static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx
Fixes canonical/commercial-squad#729 or https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-651
Co-authored-by: minkyngkm <min.kim@canonical.com>
- Disable infra support for 14.04 and  16.04
- Add tests
1. Go [here](https://ubuntu-com-12173.demos.haus/pro/subscribe)
2. Select full support
3. Go back up and select 14.04
4. "no support" should be selected and the other options should be disabled
same QA steps for 16.04
=> Disable infra support for 14.04 and 16.04

tests/shop/advantage/fixtures/account.json, tests/shop/advantage/fixtures/accounts.json, tests/shop/advantage/test_advantage_mapper.py, webapp/shop/api/ua_contracts/builders.py, webapp/shop/api/ua_contracts/primitives.py, webapp/shop/api/ua_contracts/schema.py
We had a bug in the backend between Nov 2020 and May 2021 that resulted in the creation of free contracts in some paid accounts. That is wrong, and we are cleaning this up in the backend already.
However, in order to be able to direct customers to get their correct free personal token, we need to make sure `/pro/dashboard` does not display these incorrect contracts.
As a general measure, this is a good idea regardless of this bug. As a kind of necessary pre-condition, this PR makes the account type available to the frontend code in general. The backend has had this attribute exposed for a long time now.
- Be sure to test on mobile, …
=> Ignores free contracts outside of personal accounts

templates/desktop/developers.html
- Fixed broken link on /desktop/developers
- Visit https://ubuntu-com-12303.demos.haus/desktop/developers
- Find the "Find out more about our retail partners"
- See that it takes you to https://canonical.com/partners/desktop
Fixes https://github.com/canonical/ubuntu.com/issues/12289
=> Fix broken retail partners link

package.json, static/sass/_pattern_table.scss, static/sass/styles.scss, templates/pricing/pro.html, templates/pro/index.html
Updated pricing page for Ubuntu pro according to design
Because the design is a radical change in layout and a lot of the content, the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#heading=h.l83dv5879ajz) will need to be revamped. So for this PR please use design only.
- Go to https://ubuntu-com-12268.demos.haus/pricing/pro and compare with [design](https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=2200%3A15152)
Fixes https://github.com/canonical/web-squad/issues/6115
Fixes https://github.com/canonical/web-squad/issues/2341
Fixes https://github.com/canonical/ubuntu.com/issues/5343
Fixes https://github.com/canonical/ubuntu.com/issues/12137
[QA …
=> Update pricing tables for Ubuntu Pro

static/sass/styles.scss, subscriptions.yaml, templates/subscription-centre/index.html, templates/templates/base.html, webapp/views.py
- Add functionality to unsubscribe button
- Small refactor of code
- Visit subscription-centre at [this url](https://pastebin.canonical.com/p/8JkdySRcjM/) (this is a test user)
- Check the test user already has some checkbox's checked when the page loads. If none are checked, check some and click 'Update preferences'. The page will reload and your chosen checkbox's should be checked.
- Next click the 'Unsubscribe' button, this will open a modal, click the second 'Unsubscribe' button. The page should refresh with all checkbox's unchecked
- You can check [the user on marketo](https://pastebin.canonical.com/p/79WVzZw2tF/) to see that the fields are no empty (the field to look for is called '__prototype_interests_'
Fixes https://warthogs.atlassian.net/browse/WD-360
=> Add functionality to unsubscribe button

templates/model-driven-operations/index.html
- Remove link on /model-driven-operations
- Check the link to "[Charmed Office Hours](https://discourse.charmhub.io/t/community-events/5295/8)" is removed from https://ubuntu-com-12308.demos.haus/model-driven-operations.
Fixes #12290
=> Remove link on /model-driven-operations

navigation.yaml, redirects.yaml, templates/blog/people-and-culture.html, webapp/app.py
- Added "People and culture" topic to the ubuntu.com blog
- Visit https://ubuntu-com-12307.demos.haus/blog
- See that "People and culture" appears on the subnav
- Click the link
- See that you're taken to /blog/people-and-culture (the copy in the hero strip comes from Hanna Neuborn)
Fixes https://github.com/canonical/web-squad/issues/6177
=> add "People and culture" blog topic

static/js/data/openstack-deployment-stats.json, templates/openstack/consulting.html, templates/openstack/index.html
- /openstack and /openstack/consulting
- copy updates
- graph updates
- Visit https://ubuntu-com-12317.demos.haus/openstack and https://ubuntu-com-12317.demos.haus/openstack/consulting
- Ensure the section "Number 1 platform for OpenStack implementation" has link text "OpenStack User Survey 2022" on all screen sizes.
- Ensure the graph has: 
- Ubuntu Server: 48%
- CentOS: 27%
- Red Hat Enterprise Linux: 12%
- Debian: 7%
- Other: 6%
- Check the above at all breakpoints
Fixes https://github.com/canonical/marketplace-tribe/issues/2944 
[QA …
=> Copy update: openstack/consulting (WD-757)

meganav.yaml, package.json, requirements.txt, static/sass/_global-settings.scss, static/sass/_pattern_navigation-dropdown.scss, templates/templates/_navigation.html, templates/templates/meganav/base.html, templates/templates/meganav/community.html, templates/templates/meganav/get-ubuntu.html, templates/templates/meganav/products.html, templates/templates/meganav/support.html, templates/templates/meganav/use-case.html, webapp/context.py, yarn.lock
- Added Products, Use Case, Community and Support sections to the meganav
- Visit https://ubuntu-com-12251.demos.haus/
- Open all of the dropdowns in the mega nav
- See that they work as expected:
- Dropdowns should animate open and closed (they will switch instantly when navigating from one dropdown to another)
- Some sections contain a side navigation, which should work
- Check the mobile view, see that it works
Fixes https://github.com/canonical/web-squad/issues/5983, https://github.com/canonical/web-squad/issues/5985, https://github.com/canonical/web-squad/issues/5986, https://github.com/canonical/web-squad/issues/5987
=> Add remaining meganav sections

templates/legal/ubuntu-pro-description/_base_legal_markdown.html
Set the copydoc link for the Ubuntu Pro legal page
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-pro-description
- Check the source and make sure the copydoc meta points at the link specified in the ticket.
Fixes https://github.com/canonical/commercial-squad/issues/750
=> Set the copydoc link for the Ubuntu Pro legal page

subscriptions.yaml, templates/subscription-centre/index.html
- Builds search/filter bar
- Removes '&' from list of names in subscriptions.yaml
**Todo** (in another PR, see [the issue](https://warthogs.atlassian.net/browse/WD-784))
- Placeholder text for search bar
- No results found text
- Visit the demo link https://ubuntu-com-12321.demos.haus/subscription-centre?id= use [this user's](https://pastebin.canonical.com/p/ZsRXXdkQh9/) id
- See that you can search for different tags in the search field and clicking the drop-down item will open the associated panel.
- Try and use the search without the use of a mouse
Fixes https://warthogs.atlassian.net/browse/WD-236
=> Build search for subscription-centre

build.js, static/js/src/accordion.js, static/sass/_pattern_active-reveal.scss, static/sass/styles.scss, templates/pricing/pro.html, templates/security/esm.html, templates/shared/forms/interactive/esm.html
-Building on top of @carkod 's update. Please see the relevant pr for details. This just replaces a table implementation with a (hopefully cleaner) div implementation.
Fixes #
=> Esm page update - div chart instead of a table

templates/download/iot/intel-iot.html
- updated the content on /download/iot/intel-iot according to the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- Visit https://ubuntu-com-12338.demos.haus/download/iot/intel-iot
- See that the content matches the copy doc
Fixes https://github.com/canonical/commercial-squad/issues/751
=> update intel-iot download page

static/sass/styles.scss, templates/subscription-centre/index.html, templates/templates/base.html, webapp/views.py
- Updates what fields the unsubscribe button updates
- This led to some minor refactors of the code
- Go to [the user's marketo](https://pastebin.canonical.com/p/cGw8JBDgnx/) and check the 'Unsubscribed' field is `false`, if it is `true`, change it to `false`
- Go to https://ubuntu-com-12335.demos.haus/subscription-centre?id= and use [this user's](https://pastebin.canonical.com/p/GDbFhyTdyV/) id and click 'unsubscribe'. You should be redirected to the u.com homepage and a notification message will appear.
- Go back to the [user's marketo](https://pastebin.canonical.com/p/cGw8JBDgnx/) and see the the 'unsubscribed' field is now `true`
Fixes https://warthogs.atlassian.net/browse/WD-678
=> Change what fields the unsubscribe button updates on marketo

static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
- On editing the subscriptions on Ubuntu Pro, the calculations on downsizing were incorrect. This PR fixes that
- Buy any subscription and go through the full payment flow
- Go back to /pro/dashboard and try to increase the number of machines to 5. Save it
- Now try to decrease it to 3. 
- It should calculate the difference in money correctly.  
Fixes https://github.com/canonical/commercial-squad/issues/739 …
=> Resizing calculations fix

static/sass/_pattern_subscribe.scss
-Reduce padding right so "Security coverage for critical, high and selected medium CVEs for:" don't overflow to the next line
- Scroll down to step 4 - What security coverage do you need? 
- Check "Security coverage for critical, high and selected medium CVEs for:" 
Fixes #https://warthogs.atlassian.net/browse/WD-790
=> Reduce padding right

navigation.yaml
- added "Forums" link to /landscape bubble subnav
- Visit /landscape
- See that the subnav includes "Forums"
- Click the link and see that you're taken to discourse
Fixes https://github.com/canonical/web-squad/issues/6274 / https://warthogs.atlassian.net/browse/LANDPM-474
=> feat(subnav): add link to landscape subnav LANDPM-474

templates/shared/contextual_footers/_support_landscape.html
- updated the copy for the landscape contextual footer to match the request in https://warthogs.atlassian.net/browse/LANDPM-477
- Visit:
- https://ubuntu-com-12347.demos.haus/support
- https://ubuntu-com-12347.demos.haus/pricing/consulting
- https://ubuntu-com-12347.demos.haus/support/community-support
- https://ubuntu-com-12347.demos.haus/security/docker-images
- See that the "Try Landscape for free" section matches the copy in the JIRA ticket, and that the link takes you to /landscape/install
Fixes https://github.com/canonical/web-squad/issues/6273 / https://warthogs.atlassian.net/browse/LANDPM-477
=> fix(copy): update try landscape contextual footer copy LANDPM-477

templates/security/esm.html
- Fix [test failing](https://github.com/canonical/ubuntu.com/actions/runs/3630198453) by adding `data-testid` on `/esm`
https://discourse.canonical.com/t/how-to-run-cypress-test-locally-for-forms-on-ubuntu-com/558
=> Add missing data-testid on /esm

static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx
- Display VAT error message when VAT number is wrong 
1. Go to /pro/subscribe
2. type any wrong number in VAT field
3. Click `Buy` button and see this error message displays at the top and also below the input field
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-669
=> Display VAT error message

static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx, static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.test.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts
- Add IoT devices option in the product selector
- Go to `/pro/subscribe`
- Click `IoT devices`
- R
-Please refer to the issue below and QA accordingly 
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-808
=> Add IoT devices option in the product selector

templates/openstack/compare.html
- Adds u-hide utility to images on /openstack/compare
- Go to https://ubuntu-com-12359.demos.haus/openstack/compare on mobile view, check that the images are not visible
Fixes https://github.com/canonical/ubuntu.com/issues/12292
=> Hide images on small screens on /openstack/compare

tests/cypress/forms/forms_spec.js
- fix: cypress marketo form interception
- define beforeEach/afterEach separately for each individual context
- add google analytics intercept (to make sure we don't submit events in tests)
=> fix: cypress marketo form interception

templates/about/release-cycle.html
The current template misses the 22.10 release and still includes 10.04 and 12.04. This PR aligns this to match what is visibly rendered in the SVG on the release page (https://ubuntu.com/about/release-cycle). Ideally this should be auto-generated, but currently is not.
=> Aligning text table with SVG rendering of same, dropped 10.04/12.04

webapp/certified/helpers.py
Fixes: https://warthogs.atlassian.net/browse/WD-974
- Check the download link is set to https://ubuntu.com/download/amd-xilinx on:
- http://localhost:8001/certified/202104-28895
- http://localhost:8001/certified/202008-28156
- http://localhost:8001/certified/202008-28113
- http://localhost:8001/certified/202008-28164
=> Change download link of all certified core xilinx devices

templates/download/desktop/thank-you.html
Updated the cancel PayPal URL to prevent confusion when a user cancels and returns to the site.
- Download a version of the download
- Click Contribute with PayPal
- Click the cancel and return to the site link
- See you no longer return to the thank you page
Fixes #3244
=> Update the cancel return URL from PayPal

templates/credentials/exit-survey.html, templates/shared/_credentials-exit-survey.html, webapp/app.py, webapp/shop/cube/views.py, webapp/views.py
- Go to [/credentials/exit-survey](https://ubuntu-com-12363.demos.haus/credentials/exit-survey)
- Fill out the form
- Filled-out data is stored in [this sheet](https://docs.google.com/spreadsheets/d/1L-e0pKXmBo8y_Gv9_jy9P59xO-w4FnZdcTqbGJPMNg0/edit?usp=sharing)
Fixes https://warthogs.atlassian.net/browse/CRED-248 …
=> Cred exit survey

navigation.yaml, redirects.yaml, templates/certified/index.html, templates/certified/why-certify.html, templates/credentials/index.html, webapp/app.py, webapp/certified/views.py
- moved the page at /certified/why-certified to /certified/why-certify
- updated any internal links to reflect the above change
- added a redirect
- visit https://ubuntu-com-12375.demos.haus/certified
- Click "Why certify?" in the subnav, you should be taken to https://ubuntu-com-12375.demos.haus/certified/why-certify
- try to visit https://ubuntu-com-12375.demos.haus/certified/why-certified
- you should be redirected to https://ubuntu-com-12375.demos.haus/certified/why-certify
Fixes [comment raised in JIRA](https://warthogs.atlassian.net/browse/WD-738?focusedCommentId=124087)
=> update /why-certified to /why-certify

.github/workflows/pr.yaml, templates/certified/desktops.html, templates/certified/devices.html, templates/certified/laptops.html, templates/certified/servers.html, templates/certified/socs.html
- Adds the `u-hide` utility style to various images under certified
- Go to https://ubuntu-com-12373.demos.haus/certified and visit each dedicated page (laptops, desktops, etc.) and check that the header images are hidden on small and medium screens.
Fixes https://github.com/canonical/ubuntu.com/issues/12369
=> Hide images for small and medium screens on /certified

redirects.yaml
- Changes a redirect for `/nvidia` from `/engage/ubuntu-at-nvidia-gtc-2021`  to `/engage/gtc_nvidia_2021`
- Go to https://ubuntu-com-12377.demos.haus/nvidia and check you are succesfully redirected to `/engage/gtc_nvidia_2021` and the engage page loads
Fixes https://github.com/canonical/ubuntu.com/issues/12360
=> Fix /nvidia redirect

templates/credentials/schedule-confirm.html, templates/credentials/schedule.html, webapp/shop/cube/views.py
- Update copy on exam confirmation page
- Replace "Linux Essentials" with "CUE: Linux"
- Go to https://ubuntu-com-12372.demos.haus/credentials/schedule
- Schedule an exam
- Verify that the copy on the confirmation page matches the [design](https://miro.com/app/board/uXjVOnK9PAI=/?moveToWidget=3458764540534640486&cot=14)
Fixes https://warthogs.atlassian.net/browse/CRED-250
=> Update copy for Credentials

templates/credentials/assessments.html, templates/credentials/provision.html, webapp/app.py, webapp/shop/api/trueability/api.py, webapp/shop/cube/views.py
- Implement instant provisioning for TA exams
- On `GET /credentials/provision`, the session is checked for a reservation UUID.
- If reservation UUID does not exist, check the API for a reservation and store its UUID if found.
- If reservation UUID exists, the reservation and assessment are fetched and the status is displayed to the user.
- On `POST /credentials/provision`, if there is no known reservation:
- An assessment is scheduled for 70 seconds in the future and the reservation UUID is stored as part of the session.
- The page automatically refreshes every 30 seconds to display the provisioning status.
- Determine country code based on user's time zone
- Go to https://ubuntu-com-12350.demos.haus/credentials/provision
- Click the Start button
- Wait for provisioning to finish
- Click …
=> Instant provisioning for TA exams

templates/security/esm.html
- Fixed two typos on /esm that inaccurately listed "Ubuntu Pro 16.04 LTS" as a thing that exists
- Visit /esm
- See that it addresses [the issue in the copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit?disco=AAAAmOQBiAk)
Fixes https://github.com/canonical/web-squad/issues/6293
=> fix ubuntu pro typos on /esm

templates/automotive/index.html
- Added Elektrobit logo to logo section
- Added YouTube embed to hero strip
- Updated the copy doc meta tag
- Visit https://ubuntu-com-12392.demos.haus/automotive
- See that the hero strip includes a YouTube embed
- See that the logo section below the "Snaps and App Store" includes an Elektrobit logo
- See that the changes address the requests in the copy doc: https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit#
Fixes https://warthogs.atlassian.net/browse/WD-803
[WD-803]: https://warthogs.atlassian.net/browse/WD-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add partner logo and youtube embed to /automotive WD-803

templates/appliance/shared/_base_appliance_index.html, templates/blog/product-cards/_raspberry-pi_2010-livestream.html, templates/ceph/index.html, templates/credentials/exam.html, templates/engage/base.html, templates/engage/unlisted/custom-ubuntu-pro-image-on-azure.html, templates/engage/unlisted/shell-onboarding.html, templates/hpc/index.html, templates/hpc/use-cases.html, templates/kubeconeurope2020/index.html, templates/managed/apps/index.html, templates/masters-conference/index.html, templates/security/livepatch.html, templates/shared/_share_this.html, templates/templates/_product.html, templates/templates/base.html, templates/templates/base_no_nav.html
- Added `title` attributes to all `iframe` elements
- Search the codebase for "<iframe", and see that all iframe elements it finds have an appropriate `title` attribute
Fixes https://github.com/canonical/ubuntu.com/issues/11891 as far as we're able to, many of the pages listed in the [spreadsheet given in the issue](https://docs.google.com/spreadsheets/d/1TwEIjvujOjqFcAr3IuEAb_VeFA6_dUZnnQyOFC59V1o/edit?usp=sharing) include a Bright Talk embed, and it isn't possible for us to add a title attribute to that.
=> add title attributes to iframe elements

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
Disable buy button when a value is missing
- Check `Buy now` button is disabled when a value is missing.
- Check `Buy now` button is active when all values are filled. 
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-668
[WD-668]: https://warthogs.atlassian.net/browse/WD-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Disable buy button when a value is missing

templates/certified/shared/_partners.html
- Updates the ASRock logo to the most recent one found [here](https://assets.ubuntu.com/v1/cae3c13c-asrockIndustrial.png) based on the changed request in [this jira issue](https://warthogs.atlassian.net/browse/WD-1171)
**Note**: part of the request was to have the name 'ASRock Incorporation iEP-5000G' updated to 'ASRock Industrial' on the detail page. Due to how these pages are built, removing the model number (iEP-5000G) is not practical and we agreed to keep it. The update to 'ASRock Industrial' has been requested and will be made on directly to the database.
- Go to /certified and /certified/why-certify and check the ASRock logo matches the one linked above
- Visit [this](/certified/202209-30659) hardware details page and check the vendor name is 'ASRock Industrial'
Fixes …
=> Update ASRock logo on /certified

templates/base_index.html, templates/engage/index.html, templates/engage/shared/_zh-TW_engage_form.html, templates/engage/shared/_zh-TW_thank-you.html, webapp/app.py, webapp/context.py, webapp/views.py
- Add language filter for Chinese (traditional) according to [the brief](https://docs.google.com/document/d/1sPw5bsPhZHaSOIdUAYhGaXK9Q0FSVAkimW-XeO_OhEE/edit#heading=h.meo0azuz09li)
- Translations will not be done according to TJ, so defaulting to English
- Phone number prefix, we are planning to use geolocation for it.
- Go to https://ubuntu-com-12408.demos.haus/engage
- Click on the language filter and select the new filter "Chinese (Traditional)" as requested in the brief
- Fill up the form with test data and submit.
Fixes https://github.com/canonical/web-squad/issues/6309
=> Add chinese tw language filter

konf/site.yaml
- Add TrueAbility variables to production configuration
- Once deployed to production, go to https://ubuntu.com/credentials/your-exams and ensure that your exams appear
=> [Bugfix] Add TrueAbility variables to production configuration

templates/download/iot/intel-iot.html
Changes from [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#).
- Replace Core 22 release notes with new link
- Add 12th Gen download link for Core 22
Fixes #12421
Open https://ubuntu-com-12421.demos.haus/download/iot/intel-iot, check the new links for the release notes and download match those mentioned in [the copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#).
=> 6315: New Core 22 release notes and 12th gen download link on /download/iot/intel-iot

webapp/app.py
- Go to [/credentials/exit-survey](https://ubuntu-com-12422.demos.haus/credentials/exit-survey)
- Check it does not show 405 error
Fixes #
=> Exit survey error fixed

konf/site.yaml
An error was being thrown when submitting the exit survey, apparently because the Google service account credentials were not stored in the deployment environment (see https://sentry.is.canonical.com/canonical/ubuntu-com/issues/30635/). This PR adds the credentials for the `/credentials` staging & prod pods in k8s.
- **Once merged**, visit https://staging.ubuntu.com/credentials/exit-survey
- Complete the survey and verify that it can be submitted successfully
=> Add Google service account creds to /credentials staging & prod

templates/about/release-cycle.html
Previously I submitted this [PR](https://github.com/canonical/ubuntu.com/pull/12395) to update the k8s release cycle information. This updated the chart, but I mistakenly forgot to update the table data that appears for small screen sizes. This PR adds the 1.26 table data for that table. Sorry about that. 
- Update kubernetes release table data for 1.26
Fixes # …
=> Update k8s table data

subscriptions.yaml, templates/subscription-centre/index.html, webapp/views.py
- Includes some of the updates detailed in the conversation on [this pr](https://github.com/canonical/ubuntu.com/pull/12345) I haven't tackled all of them in this PR as some require discussion or design input
- The comments I addressed are the following:
3. Spelling: Can "Cloud and Infrastructure" be changed to "Cloud & Infrastructure" so that it aligns with the other headers? Furthermore there is an "Ubutnu" in Ubuntu & Linux
6. Optin box: please change the text to: "I agree to receive information about Canonical’s products and services."
7. Can we hide the search bar for our MVP to go live? We're not really satisfied with it yet but might want to bring it back later on
8. Can we keep the subtitle we had in the old subscription center? (example: …
=> Update /subscription-centre with pdm suggestions

templates/training/contact-us.html, templates/training/index.html, templates/training/thank-you.html
- Add new section to /training for Snapcraft 101, based on [copydoc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
- Go to /training and compare against [copydoc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
- Click 'contact us' prompt and see a custom snapcraft 101 contact us page.
- Fill in the form and see you are directed to a custom snapcraft 101 thank you
Fixes https://github.com/canonical/web-squad/issues/6341
=> Add Snapcraft 101 to /training

templates/aws/workspaces.html
- Add workspaces tutorial video to /aws/workspaces,  based on [copydoc](https://docs.google.com/document/d/1qC22TM6KZTlxK3CScf-RQ4RUiMUhIBcjSWGur-dbYVA/edit#)
- Go to https://ubuntu-com-12442.demos.haus/aws/workspaces compare against copydoc
- Check the video plays when clicked and can be opened into full screen
Fixes https://warthogs.atlassian.net/browse/WD-1364
=> Add workspaces tutorial video to /aws/workspaces

navigation.yaml, templates/advantage/_table.html, templates/landscape/docs/document.html, templates/landscape/docs/search-results.html, templates/landscape/install.html, webapp/app.py
- Create discourse module to handle requests to /landscape/docs
- Create search module for landscape docs
- Update navigation.yaml to point toward /landscape/docs
- Update any other references to the old landscape docs to point toward u.com/landscape/docs
- Make sure you have the appropriate discourse & search api keys. These can be found in LastPass.
- Go to https://ubuntu-com-12447.demos.haus/landscape/docs and check that the content is the same content present https://discourse.ubuntu.com/t/landscape-documentation-home/23070 and that the navigation contains the same links
- Test the search works (this one work until is has been indexed by google)
Fixes https://warthogs.atlassian.net/browse/WD-1361
=> Host landscape docs on u.com using discourse module

templates/certified/model-details.html
- Add download button for un-certified xilinx boards details pages, based on [this conversation thread](https://chat.canonical.com/canonical/pl/hnpqjthn9fdd5xcfbxirbyu74e) and further conversations in matter most. The summarize, Felica wanted to include a download button in the detail section for Xilinx board that were not certified, this link would go to the general u.com/download/amd-xilinx page
- Go to  https://ubuntu-com-12445.demos.haus/certified/202008-28164
- There should be two boards described, the first one not certified, the second  certified. 
- Check that both boards descriptions reflect this difference.
- Check that both have a download button leading to /download/amd-xilinx (they should go to the same place)
- Find another board that is **not** certified and check that …
=> Add download button for un-certified xilinx boards details pages

.github/workflows/live-links.yaml, static/files/sitemap.xml, templates/legal/data-privacy/contact.md, templates/legal/data-privacy/index.html, templates/legal/data-privacy/newsletter.md, templates/legal/data-privacy/sso.md, templates/legal/data-privacy/webinar.md, templates/legal/ubuntu-pro-description/_toc.html
- Added to the ignore list for linkchecker to ignore the flag image which is a 3rd party package
- Updated the advantage links in the sitemap
- Updated a link to ico.org.uk across the site
- Check the changes will fix the errors reported here: https://github.com/canonical/ubuntu.com/actions/runs/3965586863/jobs/6795456091
=> Fix reported broken links on the site

templates/ai/index.html, templates/ai/services.html, templates/aws/workspaces.html, templates/ceph/consulting.html, templates/desktop/developers.html, templates/desktop/organisations.html, templates/download/desktop/index.html, templates/download/desktop/thank-you.html, templates/embedding/index.html, templates/landscape/index.html, templates/pricing/desktops.html
- There were two main requests from Oliver:
[ x ] update all the old support logos with the [new one](https://assets.ubuntu.com/v1/83e7ce7c-ubuntu-pro-circular.png)
[ x ] convert the link `Adopting a secure enterprise Linux desktop` on /download/desktop/thank-you to a button to match /download/desktop
- Check the above changes have been applied
=> Final ubuntu pro ga updates based on pdm suggestions

templates/kubernetes/docs/1.26/release-notes.md, templates/kubernetes/docs/1.26/upgrading.md, templates/kubernetes/docs/logging.md, templates/kubernetes/docs/operations.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/upgrading.md, templates/kubernetes/docs/vsphere-integration.md
- Release notes for 1.26+ck1
- changes for vsphere integrator/provider
- link updates
=> 1.26+ck1 docs changes

.github/workflows/live-links.yaml
- Remove the erroneous wildcard from the live link check. 
- Run the script local and check it runs and works
=> Fix the live links check

templates/pro/index.html
- Fix the condition so the button to request access is show when users have existing paid subscriptions.
- View the site locally in your web browser at: http://0.0.0.0:8001/pro
- Click "Login to learn more"
- Make sure the button shows if you have subscriptions on your account.
- Do the same with an account without subscriptions and make sure there are instructions on how to proceed, instead of the button to request access.
=> Show the request trial form when the users have paid contracts.

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
- visit [/pro/subscriptions](https://ubuntu-com-12480.demos.haus/pro/subscriptions)
- if you do not have an ubuntu pro subscription, buy one
- A button should appear saying "Attach a machine"
- It should not be a link
Fixes #
=> Fix magic attach button/link issue

static/sass/_pattern_cve.scss, templates/security/cve/cve.html
- Implemented impact score table 
- View the site locally in your web browser at: https://ubuntu-com-12462.demos.haus/security/CVE-2021-21311
- This CVE should have an impact score "view breakdown link" and it should take you to the table on the bottom
- Visit https://ubuntu-com-12462.demos.haus/security/CVE-2023-23605
- This CVE should have neither the aforementioned link, nor the table 
Fixes # https://warthogs.atlassian.net/browse/WD-1499
=> Add impact score table

templates/robotics/ros-esm.html
- Add the datasheet link to the hero section of the ROS ESM page
- **The rest of the page is not ready to be updated yet**
- Check the copy and link matches the request in the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-1788
=> WD-1788 Add the datasheet link to the hero section of the ROS ESM page

webapp/views.py
Getting some [sentry errors](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/10208/?query=is%3Aunresolved), but not sure when this happens, can't replicate locally or reproduce it. So I'm adding some additional error information to help troubleshoot this, if this happens again.
Basically test that everything is working as usual
- Test https://ubuntu-com-12493.demos.haus/engage forms are still doing the geolocation of international prefix correctly
- Test that homepage takeovers is working as usual (refresh a few times)
Fixes https://sentry.is.canonical.com/canonical/ubuntu-com/issues/10208/?query=is%3Aunresolved
=> Improve error handling for user-country.json

templates/shared/_18-04-eol-banner.html
- Updates 18-04 eol banner link to new blog post (they changed the name post-deployment, breaking the link we had set up)
- Go to https://ubuntu-com-12495.demos.haus/embedded or https://ubuntu-com-12495.demos.haus/robotics and check the link in the banner leads to https://canonical.com/blog/ubuntu-18-04-eol-for-devices
=> Update 18-04 eol banner link to new blog post

templates/support/community-support.html
Replace old Community Support link with new Discourse Docs generated page.
- Replaced link to old Community Support Discourse topic link with new Discourse docs generated Community Support page.
=> Update Community Support Link

navigation.yaml
- Fixed the broken navigation item
- Go to /pricing
- Click "Desktops" in the subnav
- Check it works now
=> Fixed the broken pricing desktops navigation item

templates/pro/tutorial.html
Change /pro/tutorial command to match latest version of Pro client.
- View the site locally in your web browser at: http://0.0.0.0:8001/pro/tutorial
- Check the last bit of text on step 1 is now:
```
Consider bypassing the update phasing and install the latest client version using the following command:
$ sudo apt install ubuntu-advantage-tools
```
=> Change /pro/tutorial command to match latest version of Pro client.

webapp/shop/decorators.py
As the title says, with this change URL parameters will be preserved during the login flow for shop pages. This is going to be handy for Ubuntu Pro pages where users login in the middle a flows and it's important to keep the URL parameters that are set before logging in.
- Go to https://staging.ubuntu.com/pro/dashboard?params=true
- Check that after SSO the parameters are gone.
- Go to https://ubuntu-com-12436.demos.haus/pro/dashboard?params=true
- Check that after SSO the parameters are kept.
=> Keep URL parameters after SSO authentication

redirects.yaml
Redirect /pricing/desktops to /pricing/desktop (which actually exists) to fix erroneous search results.
Fixes #12510 
QA
--
Go to https://ubuntu-com-12512.demos.haus/pricing/desktops, check you end up on https://ubuntu-com-12512.demos.haus/pricing/desktop.
For good measure, also check:
https://ubuntu-com-12512.demos.haus/advantage -> /pro
https://ubuntu-com-12512.demos.haus/pro/beta -> /pro/tutorial
https://ubuntu-com-12512.demos.haus/advantage/attach -> /pro/attach
=> Remove / prefixes; Fix /pricing/desktops 404

webapp/shop/advantage/views.py
Call get_user_subscriptions for pro marketplace only and capture the exception properly.
- @nottrobin to got to /pro and not see a 500.
Fixes #12511
=> /pro - call get_user_subscriptions for pro marketplace only

redirects.yaml
- Add a redirect to cover the Japanese version of the service terms
- Check the redirect works
=> Add redirect for UA JA legal page

static/sass/styles.scss, templates/download/desktop/thank-you.html, templates/download/intel-nuc-desktop.html, templates/download/server/s390x.html, templates/download/shared/_get-ebook-security.html, templates/download/shared/_get_ebook_maas.html, templates/engage/shared/_de_engage_form.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_es_engage_form.html, templates/engage/shared/_fr_engage_form.html, templates/engage/shared/_it_engage_form.html, templates/engage/shared/_pt_engage_form.html, templates/engage/shared/_ru_engage_form.html, templates/engage/shared/_zh-TW_engage_form.html, templates/legal/confidentiality-agreement.html, templates/legal/contributors/agreement.html, templates/legal/data-privacy/enquiry.html, templates/openstack/install.html, templates/security/cve/_version-and-status-row.html, templates/security/notices.html, templates/shared/_client-contact-us-form.html, templates/shared/_cloud-contact-us-form.html, templates/shared/_pro-contact-us-form.html, templates/shared/_telco-contact-us.html, templates/shared/forms/interactive/openstack.html, templates/shared/forms/interactive/robotics_ros.html
- I went through [this document](https://github.com/canonical/ubuntu.com/files/10677373/HTML.form.control.has.no.accessible.name.ods) provided through our a11y audit and updated the forms where appropriate. A lot of pages share the same form.
- There is one field in red which is not tackled in this PR and will require upstream changes, these changes can be found in [this issue](https://warthogs.atlassian.net/browse/WD-1894)
- I advise installing a a11y extension to help with the process, I used [wave](https://wave.webaim.org/) for this PR. This will allow you to check if a page is breaking any a11y rules. You can expect many rules to be broken as this PR only tackles form labels.
- Go to each individual page listed in the document above and check that there are no label/form related rules …
=> Add appropriate labels to all form elements

templates/engage/base.html
- Update engage page tempalate to hide header images on medium screens
- Go to any engage page and check images are hidden on both small and medium screens
Fixes https://github.com/canonical/ubuntu.com/issues/12406
=> Update engage page tempalate to hide header images on medium screens

templates/tutorials/tutorial.html
- This PR addressed the a11y issue raised in [this document](https://github.com/canonical/ubuntu.com/files/10708620/An.element.with.aria-hidden.true.contains.focusable.content.ods) all of these cases occurred in /tutorials and were all addressed by removing an aria-hidden label from the base template.
- Go to the of the links listed in the document (one or two will suffice as the root cause was in the tutorial.html template), for example https://ubuntu-com-12529.demos.haus/tutorials/how-to-build-your-own-ami-from-ubuntu-pro-using-packer#2-getting-everything-ready and check that the side navigation is accessible with your keyboard.
Fixes https://warthogs.atlassian.net/browse/WD-1571
=> Remove unnecessary aria-hidden label from side navigation in /tutorials

templates/pricing/pro.html, templates/pro/index.html
**_This PR is going to be merged and live at 1PM UK time on 14/02/2023_** 
- Added `Real-time kernel` on `/pro` and `/pricing/pro`
- Go to https://ubuntu-com-12536.demos.haus/pro and https://ubuntu-com-12536.demos.haus/pricing/pro
- Compare pages against copy docs below
- [/pro](https://docs.google.com/document/d/1In4NSnckAtL51_7D_AZCHa6TPnPGXqctXo-5rE77_aY/edit)
- [/pro/pricing](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#heading=h.h7757y94aupa)
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-2008
=> Copy update for pro pricing

static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx, templates/blog/article.html, templates/blog/newsletter-form.html, templates/certified/index.html, templates/certified/search-results.html, templates/certified/shared/category-search-results.html, templates/download/iot/intel-iot.html, templates/shared/contextual_footers/_download_iot_iotg_newsletter.html
- Using [this document](https://github.com/canonical/ubuntu.com/files/10695213/The.aria-controls.attribute.must.point.to.IDs.of.elements.in.the.same.document.1.ods) as reference I updated input fields to have appropriate aria-labels
- Fields highlighted green have been completed. Fields highlighted in orange, I could not identify any a11y issue related to aria-labelling. Fields in red are not tackled in this PR, these changes can be found in [this issue](https://warthogs.atlassian.net/browse/WD-1894)
- I advise installing an a11y extension to help with the process, I used [wave](https://wave.webaim.org/) for this PR. This will allow you to check if a page is breaking any a11y rules. You can expect many rules to be broken as this PR only tackles aria-labels.
- Many pages in the list …
=> Ensure all inputs across site have aria-labelling

templates/shared/_security-patching-logo-cloud.html
Update Anbox cloud logo on support page
- Go to https://ubuntu-com-12544.demos.haus/support check that Anbox cloud logo has been updated.
Fixes https://warthogs.atlassian.net/browse/WD-1247?atlOrigin=eyJpIjoiMDk4NzRiMzc0MjdjNGUwOGI4ZjQ2NjZkNTRiYmVmODQiLCJwIjoiaiJ9
=> Replace anbox cloud new logo

templates/telco/vnf.html
On the "/telco/vnf" page
- Updated the header illustration 
- Updated the illustration in the "Extendable Containers Layer" section
- Check https://ubuntu-com-12553.demos.haus/telco/vnf has the updated header image (reference linked issue and screenshots)
- [WD-1233](https://warthogs.atlassian.net/browse/WD-1233)
The new header illustration
The illustration in the "Extendable Containers Layer" section
[WD-1233]: https://warthogs.atlassian.net/browse/WD-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-1233 update illustrations in  `/telco/vnf`

templates/gcp/index.html
- add link Ubuntu Pro 22.04 LTS on GCP marketplace
- View the site locally in your web browser at: http://0.0.0.0:8001/gcp
- Make sure it matches the updates from https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit
Fixes WD-1967
=> Add link to Ubuntu Pro 22.04 LTS on GCP marketplace

templates/data/kafka/index.html, templates/data/spark/index.html, templates/shared/forms/interactive/spark.html
- driveby: Correction to scope of Apache Kafka offer
- feature: New page for Apache Spark offer
- feature: Contact form for Apache Spark offer
- feature: integration contact form / page / marketo
- note: adjusted copydoc to change one of the images which was using the old logo. Substituted the image in the page and the copydoc. 
- View the site locally in your web browser at: https://ubuntu-com-12552.demos.haus/data/spark 
https://warthogs.atlassian.net/browse/DATAPM-713, https://warthogs.atlassian.net/browse/WD-2075, https://warthogs.atlassian.net/browse/WD-2074
Sorry no screenshot, but you can run `./run` and navigate to `/data/spark` to …
=> Add page for Apache Spark solution offer

.github/workflows/openstack-charm-guide-docs-links.yaml
Ignore local JS errors in OpenStack docs because they are errors we can not control when scanning a 3rd party website
=> Ignore local JS errors in OpenStack docs

templates/observability/managed.html
Update logos observability page
Check https://ubuntu-com-12562.demos.haus/observability/managed according to https://warthogs.atlassian.net/browse/WD-1236?atlOrigin=eyJpIjoiMjZmMjRiNzQyYTVkNDlhZmFlZjdjZTU0NGM2YjE4YjMiLCJwIjoiaiJ9
=> WD-1231 Update observability managed logos

templates/16-04/_release-chart-1604.html, templates/16-04/index.html
- Updates the mobile view table on /16-04 to show the ESM deadline as 2026 (previously it showed 2024)
- Go https://ubuntu-com-12572.demos.haus/16-40 and check all reference to its ESM show 2026
Fixes https://github.com/canonical/ubuntu.com/issues/12541
=> Update /16-04 table mobile view ESM to 2026

templates/kubernetes/index.html
Update logos on k8s page
- Check https://ubuntu-com-12559.demos.haus/kubernetes logos have been updated according to [task/issue](https://warthogs.atlassian.net/browse/WD-1269?atlOrigin=eyJpIjoiYTRiZDcxNzI4NDQ1NDFlZmI5ZTIwYTFjNjVmMDYwM2EiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1269?atlOrigin=eyJpIjoiYTRiZDcxNzI4NDQ1NDFlZmI5ZTIwYTFjNjVmMDYwM2EiLCJwIjoiaiJ9
=> WD-1269 update k8s page logos

templates/pro/index.html
Added an "id" attribute with the value of "free" to the header element **Free for personal use** in the `/pro` page. This allows users to visit the page directly to the section with the id "free" by appending "#free" to the URL.
* Previously users had to visit https://ubuntu.com/pro and search for the text free with your web browser's search tool
* Now users can directly visit https://ubuntu.com/pro#free
Fixes #12516 
[QA …
=> Add id "free" to header in /pro page for anchor link

navigation.yaml
- fix for omission of the page /data/spark from the submenu
=> fix: adding /data/spark page to site navigation structure

templates/managed/apps/index.html
Update /managed/apps logos
- Check https://ubuntu-com-12561.demos.haus/managed/apps has the new [updated logos and layout](https://warthogs.atlassian.net/browse/WD-1237?atlOrigin=eyJpIjoiNTZlOWE3YjZiOTY4NGRhODgyNWE1YWJkZTg5MWExOTAiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1237?atlOrigin=eyJpIjoiNTZlOWE3YjZiOTY4NGRhODgyNWE1YWJkZTg5MWExOTAiLCJwIjoiaiJ9
=> WD-1269 update managed apps logos

templates/base_index.html
- Add links to Ubuntu Pro and real time kernel from homepage
-  See changes in this [copydocs](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.e9djv1qhxxm9)
- Make sure all updates look good!
Fixes [WD-2072](https://warthogs.atlassian.net/browse/WD-2072)
[WD-2072]: https://warthogs.atlassian.net/browse/WD-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-2072: Add links to Ubuntu Pro and real time kernel from homepage

templates/gcp/pro.html
Updated Google cloud pro pages.
- Compare https://ubuntu-com-12551.demos.haus/gcp/pro with [copy docs](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit)
Fixes https://warthogs.atlassian.net/browse/WD-1968?atlOrigin=eyJpIjoiNjI5ZjU5YzI3OGY2NDRiY2I0OTQzMmEwYmMwZGIwZGEiLCJwIjoiaiJ9
=> Update Google cloud pro page #WD-1968

static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, templates/pro/index.html
- Update GCP link
- select this
- link should send you here: https://console.cloud.google.com/marketplace/browse?q=ubuntu%20pro&filter=partner:Canonical%20Group&authuser=1
Fixes #https://warthogs.atlassian.net/browse/WD-2151
=> Update GCP link

Dockerfile
Another PR to make the renovate PR lighter: https://github.com/canonical/ubuntu.com/pull/12389
- Bumped to use ubuntu jammy and python 3.10
- Bumped to use node 18 LTS
Fixes [WD-1862](https://warthogs.atlassian.net/browse/WD-1862)
[WD-1862]: https://warthogs.atlassian.net/browse/WD-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Upgrade node 18 LTS and ubuntu jammy docker versions

templates/16-04/_release-chart-1604.html, templates/about/index.html, templates/about/release-cycle.html, templates/cpu-compatibility/index.html, templates/desktop/developers.html, templates/desktop/statistics.html, templates/openstack/why-openstack.html, templates/shared/_kernel-support-schedule.html, templates/shared/_release_schedule.html
Another PR to make the renovate PR lighter: https://github.com/canonical/ubuntu.com/pull/12389
- Upgrade CDNs for d3
- THis is the list of pages updated, make sure they look the same!
https://ubuntu-com-12580.demos.haus/16-04
https://ubuntu.com/16-04
https://ubuntu-com-12580.demos.haus/about
https://ubuntu.com/about
https://ubuntu-com-12580.demos.haus/about/release-cycle
https://ubuntu.com/about/release-cycle
https://ubuntu-com-12580.demos.haus/cpu-compatibility
https://ubuntu.com/cpu-compatibility
https://ubuntu-com-12580.demos.haus/desktop/developers
https://ubuntu.com/desktop/developers …
=> Upgrade d3 CDNs

.github/workflows/pr.yaml
The run-image job can take 6 hours to fail. Let's [limit][2] it to 15 minutes to limit the harm this can do.
Fixes https://github.com/canonical/ubuntu.com/issues/12558
[2]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
=> WD-2135: Limit run-image job to 15 minutes

.github/workflows/pr.yaml, requirements.txt, templates/400.html, templates/429.html, webapp/app.py
Review PR for https://github.com/canonical/canonicalwebteam.search/pull/33
- For QA, I set the limit to 3 times per minute, per endpoint.
- Go to https://ubuntu-com-12514.demos.haus/ search something in the search bar
- Once you are on that page, refresh a couple times or change the search term and you'll get the rate limit (set to 3/minute), after which you'll have to wait one minute to be able to search again.
Only the /search has `3/minute` limit applied, so for other endpoints you won't see th 429 until you reach `500/day`
Fixes #
=> Update search to include rate limits

static/js/src/chart-data.js, static/js/src/desktop-statistics.js, templates/desktop/statistics.html
- Updates chart-data.js to fill in missing data, this fixes the floating bar found on /kernel/lifecycle, specifically the 'All releases', 'All LTS releases', '20.04' tabs
- Updates margin sizing in desktop-statistics.js & inline width style in /desktop/statistics.html to fix the following graphs on /dektop/statistics: 'What language do they use?', 'Number of CPUs', 'Size of RAM (GB)', 'Physical disk (GB)', 'Partition type', 'What physical disks do people have?'
- Go to https://ubuntu-com-12584.demos.haus/kernel/lifecycle and see that the floating bar has moved to the appropriate column on the graphs detailed above. 
- Go to https://ubuntu-com-12584.demos.haus/desktop/statistics and see that the overflow issue is fixed on the graphs detailed above.
- Make sure to change screen size and …
=> Fix d3 graphs and data across site

static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx, static/js/src/advantage/subscribe/checkout/utils/helpers.ts
- Fix Free trial step. If a user has never made a purchase before then the checkout would show the free trial step even though the product is not triallable. Now we take both the `product.canBeTrialled` and the user account status when displaying that step.
- Have an clean account that has never made a UA purchase before therefore would be allowed to trial
- Go to https://staging.ubuntu.com/pro/subscribe
- Login
- Select a product that cannot be trialled
- Proceed to checkout, you will see the free trial step incorrectly
- Do the same with the demo, the free trial step will not be there
Fixes #https://warthogs.atlassian.net/browse/WD-2165
=> Fix free trial step

webapp/shop/cred/views.py
- Go to /credentials/redeem/{activationKey}?action={"schedule"/"take"}
- Should not show a confirmation view and directly take to the respective pages. 
Fixes #
=> Add redirects to schedule/provision from activate key view

releases.yaml, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-5.html
- Update releases.yaml file to include the new 22.04.2 release.
- Check that there are no mentions of 22.04.1
=> Update releases.yaml to add 22.04.2

templates/pro/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/pro
- Make sure it adds the call to action as specified on the ticket.
Fixes https://warthogs.atlassian.net/browse/WD-2179
=> Add secondary call to action in /pro

templates/templates/docs/shared/_docs.html
To bring ubuntu.com inline with other sites where the document title is pulled from the discourse topic title.
This will lead to duplicate titles until https://github.com/canonical/discourse-update-titles is run, so should be well coordinated on release.
Fixes https://warthogs.atlassian.net/browse/WD-2170
Go to:
https://ubuntu-com-12587.demos.haus/core/docs
https://ubuntu-com-12587.demos.haus/openstack/docs
https://ubuntu-com-12587.demos.haus/landscape/docs
https://ubuntu-com-12587.demos.haus/server/docs
https://ubuntu-com-12587.demos.haus/ceph/docs
https://ubuntu-com-12587.demos.haus/security/livepatch/docs
https://ubuntu-com-12587.demos.haus/security/certifications/docs
Check you see duplicate titles! Maybe try removing one of the duplicate titles, check it looks ok.
=> Add document title to document template

templates/credentials/provision.html, templates/credentials/schedule.html, webapp/shop/api/ua_contracts/api.py, webapp/shop/cred/views.py
- Instantly-provisioned exams are scheduled through the CS contracts service rather than directly using the TA API
~~**Note:** Instantly-provisioned exams are currently scheduled for 10 mins into the future to due to TA platform limitations. We will remove this window once TA has implemented the necessary patch.~~
- Obtain a CUE activation key using the Backoffice tool (or get one from Morgan)
- Visit https://ubuntu-com-12518.demos.haus/credentials/redeem/[activation-key] to redeem your key
- Visit https://ubuntu-com-12518.demos.haus/credentials/your-exams
- Verify that your exam is listed
- Click the "Take now" button
- Verify that the exam is built and that you are redirected to the exam environment
Fixes https://warthogs.atlassian.net/browse/CRED-289
[QA …
=> Use CS endpoints for instant provisioning

templates/credentials/your-exams.html, webapp/shop/cred/views.py
- Use user-friendly labels on your-exams
- Remove cancel button
- Sort exams by status (in progress, scheduled, not taken, complete)
- Visit https://ubuntu-com-12524.demos.haus/credentials/your-exams
Fixes https://warthogs.atlassian.net/browse/CRED-297
=> Cred UI tweaks

static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx, static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx, static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx, static/js/src/advantage/subscribe/checkout/utils/helpers.ts, static/js/src/advantage/subscribe/checkout/utils/types.ts, tests/cypress/integration/pro/checkout_spec.js, tests/cypress/support/pro/commands.js
- Make cancel button from `Taxes` and `UserInfoForm` components reset to the Fromik initailValues.
- Are tests passings?
- Edit `Taxes` or `UserInfoForm` sections, click cancel, are the values resetting?
Fixes #https://warthogs.atlassian.net/browse/WD-2173
=> Make cancel button use formik initial values

templates/appliance/hardware.html, templates/appliance/shared/_featured_appliances.html
- Updates logos on /appliance/hardware based on [the issue](https://warthogs.atlassian.net/browse/WD-1729)
- Go to https://ubuntu-com-12609.demos.haus/appliance/hardware and make sure the page matches the 'replacement' images found in the issue
Fixes https://warthogs.atlassian.net/browse/WD-1729
=> Update logos on /appliance/hardware

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx, tests/cypress/integration/pro/checkout_spec.js
- Show error and disable buy button when name and organisation name are the same
- Go to  https://ubuntu-com-12585.demos.haus/pro/subscribe
- Click `An organisation` in Your information section 
- Type the same value as Name field
- Check error message displays and buy button is disabled when name and organisation name are the same
Fixes https://github.com/canonical/commercial-squad/issues/755
=> Disable when name and organisation name are the same

templates/appliance/shared/_featured_appliances.html, templates/download/cloud/index.html, templates/download/iot/index.html, templates/pricing/shared/_enablement-strip.html
- `/download/iot`
- Replaced: 
- Ubunutu core logo
- Canonical LXD logo
- Ubuntu Certified logo 
- `/download/cloud`
- Replaced:
- Ubuntu cloud logo
- Navigate to https://ubuntu-com-12613.demos.haus/download/iot and compare with images in [WD-1712](https://warthogs.atlassian.net/browse/WD-1712)
- Navigate to https://ubuntu-com-12613.demos.haus/download/cloud and compare with the image in [WD-1714](https://warthogs.atlassian.net/browse/WD-1714)
- [WD-1712](https://warthogs.atlassian.net/browse/WD-1712)
- [WD-1714](https://warthogs.atlassian.net/browse/WD-1714)
[WD-1712]: https://warthogs.atlassian.net/browse/WD-1712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> WD-1712, WD-1714 Replace logos in `/download/*`

webapp/shop/cred/views.py
- Remove canonical_staff decorator from public credentials views
- Don't require a purchase account or product ID when redeeming an activation key
- With a non-Canonical account, verify that you do not get an unauthorized error for the following:
- https://ubuntu-com-12615.demos.haus/credentials/your-exams
- https://ubuntu-com-12615.demos.haus/credentials/schedule
- https://ubuntu-com-12615.demos.haus/credentials/provision
- https://ubuntu-com-12615.demos.haus/credentials/exam
=> Tweaks for Credentials on production

templates/base_index.html
- `data-testid` seems to be removed in `base_index.html` for some reason and because of that, cypress test for forms is failing on `/`
- Added `data-testid` in `base_index.html`
- All passed locally 
- https://discourse.canonical.com/t/how-to-run-cypress-test-locally-for-forms-on-ubuntu-com/558 if needed
Fixes https://github.com/canonical/ubuntu.com/actions/runs/4293744211
=> Add data-testid on base_index.html

static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx, webapp/shop/api/ua_contracts/builders.py
- Renewal button for is setting the wrong number of machines to the checkout. This one fixes it.
Fixes #https://warthogs.atlassian.net/browse/WD-2320
=> Fix renewal number of machines

templates/automotive/index.html
- Replace automotive car dashboard illustration
- Replace automotive car network illustration
- Replace automotive car chassi illustration
- Replace business software illustration
- Navigate to https://ubuntu-com-12623.demos.haus/automotive
- Compare with images in [WD-1730](https://warthogs.atlassian.net/browse/WD-1730).
- [WD-1730](https://warthogs.atlassian.net/browse/WD-1730)
[WD-1730]: https://warthogs.atlassian.net/browse/WD-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-1730]: https://warthogs.atlassian.net/browse/WD-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> WD-1730 replace illustrations with new logo in `/automotive`

static/sass/_pattern_heading-icon.scss, templates/server/index.html
- Update logos on /server based on [this issue](https://warthogs.atlassian.net/browse/WD-1725)
- Adds a class `p-heading-icon--long`, which is being discussed [here](https://github.com/canonical/vanilla-framework/issues/4678). Depending on the outcome of this conversation may be removed.
- Go to https://ubuntu-com-12630.demos.haus/server
- Check that the logo use the updated Ubuntu logo
Fixes https://warthogs.atlassian.net/browse/WD-1725
=> Update logos on /server

static/sass/styles.scss, templates/managed/index.html
- Replaced logos for Canonical OpenStack, Kubernetes and Ceph.
- Reformated the grid items to be cards and increased the row-gap.
- Navigate to https://ubuntu-com-12618.demos.haus/managed and reference [WD-1708](https://warthogs.atlassian.net/browse/WD-1708) and screenshot section.
- [WD-1708](https://warthogs.atlassian.net/browse/WD-1708)
Previous look:
New look:
[WD-1708]: https://warthogs.atlassian.net/browse/WD-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-1708]: https://warthogs.atlassian.net/browse/WD-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> WD-1708 replaces Canonical OpenStack, Kubernetes and Ceph logos in `/managed`

templates/pricing/pro.html
Correct price of managed ceph on bare metal to match what is on the copydoc.
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/pro
- Make sure the change matches what is on the copydoc.
=> Correct price of managed ceph on bare metal.

templates/appliance/vm.html
- Updates logos on /appliance/vm based on [this issue](https://warthogs.atlassian.net/browse/WD-1731)
- Go to https://ubuntu-com-12610.demos.haus/appliance/vm and check that it matches the 'replacement' image from the issue
Fixes https://warthogs.atlassian.net/browse/WD-1731
=> Update logos on /appliance/vm

templates/appliance/index.html
- Update logos on /appliance based on [this issue](https://warthogs.atlassian.net/browse/WD-1718)
- Go to https://ubuntu-com-12644.demos.haus/appliance and check the logos match the ones provided in the issue
Fixes https://warthogs.atlassian.net/browse/WD-1718
=> Update logos on /appliance

templates/pricing/devices.html
- Update logos on /pricing/devices based on [this issue](https://warthogs.atlassian.net/browse/WD-1717)
- Go to https://ubuntu-com-12645.demos.haus/pricing/devices and check it used the same logos as in the issue
Fixes https://warthogs.atlassian.net/browse/WD-1717
=> Update logos on /pricing/devices

templates/download/risc-v/index.html, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html, templates/download/risc-v/tab-5.html, templates/download/risc-v/tab-6.html
Add new Polarfire Risc-v tab
- Go to  https://ubuntu-com-12611.demos.haus/download/risc-v
- Click on the new Polarfire tab. Check against [copy docs](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit?disco=AAAArW4QcRQ)
- Only new  Microchip Polarfire change at the top
- New tab 5 for Microchip Polarfire. 
Fixes https://warthogs.atlassian.net/browse/WD-2154?atlOrigin=eyJpIjoiZmVlMTRlZDNmZDlmNGQzZWFlODdiYTYzNjM2ZjU5OWEiLCJwIjoiaiJ9
=> WD-1347 Add new Polarfire Risc-v tab

redirects.yaml
- Add a redirect to fix a blog slug rename 
- /blog/cloud-repatriation should redirect to: /blog/cloud-repatriation-reasons
=> Add blog slug renames redirects

static/js/src/static-forms.js, templates/kernel/real-time/contact-us.html
- This PR is heavily inspired/copied from https://github.com/canonical/ubuntu.com/pull/12612
- Add contact form 
- Missing: 
- View the site locally in your web browser at: http://0.0.0.0:8001/kernel/real-time/contact-us
Fixes WD-2344
=> WD-2344 - Add real-time contact form

templates/desktop/organisations.html
- Remove logos in the "Secure enterprise management with Ubuntu Pro Desktop" section.
- Logo replacements in the "Ubuntu delivers the best of open source" section.
- Update Ubuntu for Data science illustration.
- Check the demo here: https://ubuntu-com-12650.demos.haus/desktop/organisations
- Compare with the screenshots in the task [here](https://warthogs.atlassian.net/browse/WD-1710).
- [WD-1710](https://warthogs.atlassian.net/browse/WD-1710)
[WD-1710]: https://warthogs.atlassian.net/browse/WD-1710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-1710 `/desktop/organisations` logo replacements

templates/download/desktop/index.html
- Updated: 
- Ubuntu certified partners logo
- Secure enterprise management logo
- Canonical Multipass logo
- Canonical LXD logo
- Check out the demo here: https://ubuntu-com-12658.demos.haus/download/desktop
- Compare with screenshots in the issue here: https://warthogs.atlassian.net/browse/WD-1709
- [WD-1709](https://warthogs.atlassian.net/browse/WD-1709)
[WD-1709]: https://warthogs.atlassian.net/browse/WD-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-1709 `/download/desktop` logo updates

static/js/src/advantage/offers/components/Offer/Offer.test.tsx, static/js/src/advantage/offers/components/Offer/Offer.tsx, static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx, static/js/src/advantage/subscribe/checkout/utils/types.ts
- Display discount on checkout
- Go to /pro/offers
- Click an offer that provides a discount
- Check offer discount price displays in summary and total is correct
- Check the case when user is guest as well
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-1940
=> Display offer discount on checkout

static/js/src/tabotronic.js
- Check if tab content contains an D3 chart and trigger resize event if yes
- I added the check into tabtronic.js as this is only an issue that occurs when a d3 chart is held within tabs. This is because the d3 script check the size of the container that holds the chart, if the container is hidden that chart has a width of 0, so d3 will infer the size from the closest `col`
- Go to https://ubuntu-com-12662.demos.haus/kernel/lifecycle and check that the charts are the same size between tabs
Fixes https://github.com/canonical/ubuntu.com/issues/12590
=> Check if tab content contains an D3 chart and trigger resize event if yes

templates/contact-us/form/index.html, templates/landscape/pricing.html
- Updates copy on https://ubuntu-com-12670.demos.haus/landscape/pricing based on [copydoc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#)
- Adds a fallback form for when JS is no enabled
- Go to https://ubuntu-com-12670.demos.haus/landscape/pricing and compare against [copydoc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#)
- Disable JS and click a contact-us button, see that you are redirected to a static form with the same form id (4473) as the modal form.
Fixes https://warthogs.atlassian.net/browse/WD-2530
=> Update copy on /landscape/pricing

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx, static/js/src/advantage/subscribe/checkout/utils/helpers.ts, static/js/src/advantage/subscribe/checkout/utils/types.ts
- Disable buy button if editting user info
- Log in with account that has purchase history 
- Click Edit button in Your information section 
- Check buy button is disabled/active depending on the edit/save button 
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-2407
=> Disable buy button when user info is edit mode

static/sass/styles.scss
- Set `fieldset: visible` to stop the dropdown causing the field set to scroll for overflow, as can be seen in [this issue](https://github.com/canonical/ubuntu.com/issues/12625)
- Go to a contact-us form with a number input near the edge of a field set, ex. download/contact-us
- Check it does not need to be scrolled to see the full container
Before:
After:
Fixes https://github.com/canonical/ubuntu.com/issues/12625
=> Fix country-code dropdown not overlapping fieldsets

templates/engage/de_why-openstack.html, templates/templates/base.html
- Add block meta_lang to allow pages to change the lang of a specific page. The default is always english
- Update http://0.0.0.0:8001/engage/de/warum-openstack to have de lang set
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/de/warum-openstack
- Open inspector: make sure that `lang="de"`
- Go on any other page, the lang should be `en`
Fixes https://warthogs.atlassian.net/browse/WD-2625
=> Add meta lang block in jinja2 templates

webapp/shop/cred/views.py, webapp/shop/utils.py
When retrieving the user's first and last name from the user session, an error would be thrown if the user's profile didn't contain two names separated by a space in the "Full name" field of the [Ubuntu One account settings](https://login.ubuntu.com/) (see [error in Sentry](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/31953/?query=%2Fcredentials%2Fprovision)). We add a new function, `get_user_first_last_name()`, to safely parse this information, and return an empty string for the first and/or last name if not provided.
- Visit https://login.ubuntu.com/ and modify the "Full name" field under "Personal details" to contain only your first name (no last name), then save your settings
- Visit https://ubuntu-com-12683.demos.haus/credentials/your-exams and schedule or reschedule …
=> Fix bug when parsing first name and last name from Ubuntu One account

templates/templates/docs/shared/_docs.html
**This script can be added to other sites documentation pages when it is merged**
- When a select input has an 'onchange' listener attached to it, browsing the options using a keyboard will trigger the listener before the user can confirm their selection. this PR implements JS to allow the onchange function to work as normally but also allow people using keyboard navigation to browse the options and use the 'enter' or 'tab' key to confirm their option.
- This addresses the accessibility issues listed in [this document](https://github.com/canonical/ubuntu.com/files/10708064/select.lists.cannot.be.operated.from.the.keyboard.if.they.have.an.onchange.handler.that.performs.navigation.because.the.handler.fires.as.the.user.moves.the.selection.up.and.down.using.the.keyboard.ods)
- Go to one of …
=> Make select boxes with on change affects accessible

webapp/shop/cred/views.py
- Keys are not listed in /credentials/shop/manage
- test on local and set the environment to production
- go to /credentials/shop/manage
- Should see a list of keys 
Fixes #[CRED-346](https://warthogs.atlassian.net/browse/CRED-346)
[CRED-346]: https://warthogs.atlassian.net/browse/CRED-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> activation keys list is empty in /credentials/shop/manage

konf/site.yaml, templates/account/maintenance-check.html, templates/account/status.html, templates/advantage/index.html, webapp/app.py, webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/api/ua_contracts/helpers.py, webapp/shop/decorators.py, webapp/shop/views.py
- Implement maintenance feature. This is a semi-version, that will allow us to test just of the /pro/maintenance-check page. 
- Two new pages added: 
- /pro/status to check the status of the shop and future scheduled maintenances
- /pro/maintenance-check a page to help us test the semi-version
- Maintenance feature is controlled by the following env varaibles:
```ymal
- name: STORE_MAINTENANCE
value: false
- name: STORE_MAINTENANCE_START
value: 2023-03-16T21:00:00Z
- name: STORE_MAINTENANCE_END
value: 2023-03-17T00:00:00Z
```
- to turn the shop on `STORE_MAINTENANCE` must be `true` and now must be between the two dates
Full version compared to the semi-version will also:
- turn off /pro/subscribe
- Hide the Buy subscription button on /pro/dashboard
- Hide resizing features on …
=> Push shop in maintenanace

templates/credentials/index.html, templates/credentials/redeem.html, templates/credentials/self-study.html, webapp/shop/cred/syllabus.json, webapp/shop/cred/views.py
- Fix CUE exam names (CUE.01: Linux, CUE.02: Desktop, CUE.03: Server)
- Direct the user to /credentials/your-exams if there is an error redeeming an activation key
- Map "cue-linux-essentials" to "CUE.01: Linux" on /credentials/your-exams
- Visit https://ubuntu-com-12680.demos.haus/credentials
- Verify that the exams are titled "CUE.01: Linux QuickCert", "CUE.02: Desktop QuickCert", and "CUE.03: Server QuickCert"
- Visit https://ubuntu-com-12680.demos.haus/credentials/redeem/invalidkey
- Verify that "Go to your exams ›" links to https://ubuntu-com-12680.demos.haus/credentials/your-exams
Fixes https://warthogs.atlassian.net/browse/CRED-326
=> UI tweaks for Credentials

konf/site.yaml, webapp/shop/decorators.py
- Change to the full maintenance feature:
- `MAINTENANCE_URLS` is the list of urls that will show the maintenance view when maintenance is on.
- un-hardcode `is_in_maintenance` we make use of this value to hide specific features(fx: resizing, or buy buttons)
- Schedule it
=> Schedule shop for maintenance

static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, tests/shop/advantage/helpers.py, tests/shop/advantage/test_parsers.py, webapp/shop/api/ua_contracts/builders.py, webapp/shop/api/ua_contracts/parsers.py, webapp/shop/api/ua_contracts/primitives.py
- Update renewals to renew the number of machines from the renewal object rather than the number of machines they had before
Fixes https://warthogs.atlassian.net/browse/WD-2478
=> Change machine number for renewals

templates/legal/data-privacy/community-discourse.md, templates/legal/data-privacy/index.html
- Create new `/legal/data-privacy/community-discourse` page, based on [copydoc](https://docs.google.com/document/d/15DqAWthYZvF9aOeBu-O1UA_jjCplkl1lJsIeV_dER-g/edit#)
- Updates `/legal/data-privacy` to reflect the [copydoc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit)
- Go to https://ubuntu-com-12703.demos.haus/legal/data-privacy and navigate to https://ubuntu-com-12703.demos.haus/legal/data-privacy/community-discourse using the link on the page titled 'Ubuntu Community Discourse'
- Check that the page matches the [copydoc](https://docs.google.com/document/d/15DqAWthYZvF9aOeBu-O1UA_jjCplkl1lJsIeV_dER-g/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-2657
=> Add community dicourse page and link to privacy policy

templates/landscape/index.html
- Update copy on /landscape based on [copydoc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit)
- Updates an illustrations
- Check the https://ubuntu-com-12701.demos.haus/landscape matches the changes on the [copydoc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit)
- Check all illustrations use the newest Ubuntu logo
FIxes https://warthogs.atlassian.net/browse/WD-2448
=> Update copy on /landscape

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.tsx, static/js/src/advantage/tests/factories/api.ts, webapp/shop/api/ua_contracts/builders.py
- Show documentation for all entitlements on free subscriptions.
- Remove outdated reference to `esm-apps --beta`.
- Check free subscriptions have documentation links to all the features they are entitled too.
- Check we removed `--beta` from `esm-apps` command
=> Pro Dashboard - show full documentation for free subscriptions.

templates/pricing/pro.html
- Change "No support" text to "Self-Support".
- Change "Knowledge base access" to 'yes' for self-support customers.
- Go to /pricing/pro and check the copy changes are good.
Fixes #12465
=> Pro pricing: Change "No support" text to "Self-Support"

templates/certified/shared/_partners.html
- Added new logos [as requested](https://warthogs.atlassian.net/browse/WD-2758)
- View the site locally in your web browser at: https://ubuntu-com-12720.demos.haus/certified/why-certify
- See that the requested logos were added
Fixes https://warthogs.atlassian.net/browse/WD-2758
=> /certified/why-certify - Update logo list

.github/workflows/cypress-pr.yaml
- update dummy cypress account credentials
Fixes #
=> update dummy cypress account credentials

templates/credentials/index.html, templates/credentials/syllabus.html
- Update visuals for /credentials and /credentials/syllabus
- Visit https://ubuntu-com-12725.demos.haus/credentials
- Compare against [visual design](https://www.figma.com/file/ZTdYjh2H2nT9rRo9BYHv4G/CUE?node-id=113-2264&t=Y4r2FlET4SRQ33zB-0)
- Visit https://ubuntu-com-12725.demos.haus/credentials/syllabus
- Compare against [visual design](https://www.figma.com/file/ZTdYjh2H2nT9rRo9BYHv4G/CUE?node-id=153-919&t=Y4r2FlET4SRQ33zB-0)
Fixes https://warthogs.atlassian.net/browse/CRED-298
=> Update visuals for Credentials

templates/certified/shared/_partners.html
- Follow up of [this pr](https://github.com/canonical/ubuntu.com/pull/12720), stakeholder has asked to reorder the logos so that  Advantech / Aaeon / DFI are the first 3 logos in the second row.
- View the site locally in your web browser at: https://ubuntu-com-12732.demos.haus/certified/why-certify
- See that the requested change was made
=> Reorder logos

package.json, static/sass/_pattern_navigation.scss, static/sass/styles.scss, yarn.lock
[This PR](https://github.com/canonical/ubuntu.com/pull/12667) already exists, but I wanted to get the vanilla update live asap as it is required for [this PR](https://github.com/canonical/ubuntu.com/pull/12675) that is due to go live today
- Updates to vanilla-3.13.0. This is a separate PR
- Check the changes made to the nav
=> Update to vanilla-3.13.0

webapp/shop/api/ua_contracts/api.py
Commercial Systems has updated the path to list activation keys for a contract. The changes on our side will be deployed on Wed, Apr 5th. Given this page is Canonical-only, we don't see much point in `try` / `except` dances when back-porting from an older to a newer endpoint.
=> Update list activation keys for contract endpoint path

templates/pro/tutorial.html
Fixed Typo in step 5 of the  Ubuntu Pro tutorial Removed duplicated "now" 
Fixes #12738 
=> Fix typo remove duplicated "now" from Ubuntu Pro tutorial

templates/shared/_security-patching-logo-cloud.html, templates/support/index.html
-  Remove Kafka logo and mention on the /support page
- Go to https://ubuntu-com-12766.demos.haus/support
- Check Kafka logo and mention are removed on the page
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-3066
=> Remove kafka from /support

templates/desktop/flavours.html
Update of the Ubuntu desktop flavours page to include sections for new official flavours: Edubuntu and Ubuntu Cinnamon.
- Uploaded new flavour assets into asset manager.
- Updated flavour banner image with new flavour icons.
- Added new sections and associated content for new flavours - Edubuntu and Ubuntu Cinnamon
- Updated section classes to maintain page theming.
Fixes # https://warthogs.atlassian.net/browse/WD-3027
=> Update /desktop/flavours with new flavour information

templates/legal/partner-portal-terms.md, templates/legal/terms-and-policies/discourse-terms.md, templates/legal/terms-and-policies/index.html
- Added the discourse terms page to the legal section based on this [copy doc](https://docs.google.com/document/d/1Yv4bItPlNPS4oOSvUsUavT3qD6NmVrf_EjQNVFLx40w/edit#).
- Added a section linking to the page on the main terms and policies page based on this [copy doc](https://docs.google.com/document/d/1p3ZWroZ3nkw8XJJdPvPxSlWGYcLZLT8UbUVuppBcyHk/edit#heading=h.twzeocg9szb2).
- Find the legal section
- Click on Terms and policies in the secondary nav
- Scroll to the bottom and check the "Canonical Ubuntu Community Discourse Forum Terms of Service" box matches the copy doc above
- Click on it and check the page content matches the copy doc above
=> WD-3167 Add the discourse terms legal page

webapp/security/views.py
This avoids flooding the git service with two requests for every CVE page load.
- http://0.0.0.0:8001/security/CVE-2015-9541 still shows an entry for pyside2 in ROS ESM; the first request shows "Caching b/c of expires header. expires in 300 seconds", and subsequent requests show "The response is \"fresh\", returning cached response".
Fixes #12784.
=> Cache git.launchpad.net requests for ROS ESM package lists

templates/security/cve/cve.html
`/distros/ubuntu` has been obsolete since 2006.  Use `/ubuntu` instead.
- Check any CVE page; the Launchpad links point to `/ubuntu/+source/foo` rather than `/distros/ubuntu/+source/foo`, and still work.
=> Modernize Launchpad package URLs

templates/data/mongodb/index.html, templates/data/opensearch/index.html
- Updated the `/data/mongodb` and `/data/opensearch` marketo form IDs based on request in copy doc.
- [MongoDB copy doc](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit#)
- [OpenSearch copy doc](https://docs.google.com/document/d/17vCodr2uujQv591IlWmveh6_7OLyPK1KrXQb2ZSiceA/edit) 
This is related to these two recently merged PR (#12785, #12769)
- Check out the [MongoDB page](https://ubuntu-com-12811.demos.haus/data/mongodb) and compare it with [copy doc](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit#)
- Check out the [OpenSearch page](https://ubuntu-com-12811.demos.haus/data/opensearch) and compare it with [copy doc](https://docs.google.com/document/d/17vCodr2uujQv591IlWmveh6_7OLyPK1KrXQb2ZSiceA/edit)
Related to …
=> [copy update] update marketo form id on `/data/mongodb` and `/data/opensearch`

templates/hpc/index.html
Due to missing commas, /hpc page is failing
- Check https://ubuntu-com-12824.demos.haus/hpc works now
- Or checkout this PR and pull the code. Go to http://localhost:8001/hpc
Fixes https://github.com/canonical/ubuntu.com/issues/12822
=> Fix missing commas HPC page

static/sass/_pattern_tabs.scss, templates/download/risc-v/index.html, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html, templates/download/risc-v/tab-5.html, templates/download/risc-v/tab-6.html
- Applied redesign as per [mock-up](https://www.figma.com/file/WsMLgH1TXcU1mZ7YjqZRDY/u.com%2Fdownload%2Frisc-v?node-id=1-479&t=FINyqxY91oUUwEOf-0)
- Updated copy as per [doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12821.demos.haus/download/risc-v
- See that the requested copy changes were made and that the page matches the design
Fixes https://warthogs.atlassian.net/browse/WD-3078
=> [page refresh] /download/risc-v

templates/credentials/self-study.html
Cred: Add more materials for Linux resources
- View the site locally in your web browser at: http://0.0.0.0:8001/credentials/self-study
- Make sure the links specified on the ticket were added.
Fixes https://warthogs.atlassian.net/browse/CRED-385
=> Cred: Add more materials for Linux resources

webapp/app.py
Increase rate limit to 2000 per day.
- Check that search works:
- https://ubuntu-com-12831.demos.haus/server/docs
- https://ubuntu-com-12831.demos.haus/ceph/docs
- https://ubuntu-com-12831.demos.haus/security/livepatch/docs
- https://ubuntu-com-12831.demos.haus/security/certifications/docs
- https://ubuntu-com-12831.demos.haus/landscape/docs
- https://ubuntu-com-12831.demos.haus/robotics/docs
- https://ubuntu-com-12831.demos.haus/community/
- Not sure we can QA this to 2000 queries to make it fail, but we can already see the rate limit works.
=> Increase rate limit to 2000 per day

templates/blog/product-cards.html, templates/blog/product-cards/_ubuntu_18.04_end_of_support.html
- Added a new product card _ubuntu_18.04_end_of_support for pages with the tag "ubuntu 18.04"
Fixes #
=> Added new product card

templates/blog/product-cards.html, templates/blog/product-cards/_real-time_linux.html
- Specify the product card for blog posts with the "real-time Linux" tag.
- Check out any of these blog posts in the demo:
- [Real-time Ubuntu is now generally available | Ubuntu](https://ubuntu-com-12829.demos.haus/blog/real-time-ubuntu-is-now-generally-available)
- [Real-time Ubuntu 22.04 LTS Beta – Now Available | Ubuntu](https://ubuntu-com-12829.demos.haus/blog/real-time-ubuntu-released)
- [An intro to real-time Linux with Ubuntu | Ubuntu](https://ubuntu-com-12829.demos.haus/blog/real-time-linux-qa)
- [What is real-time Linux? Part I | Ubuntu](https://ubuntu-com-12829.demos.haus/blog/what-is-real-time-linux-i)
- [What is real-time Linux? Part II | Ubuntu](https://ubuntu-com-12829.demos.haus/what-is-real-time-linux-ii)
- [What is real-time Linux? Part III | …
=> WD-3147 - Add real-time kernel product card

static/js/src/chart-data.js, templates/about/release-cycle.html
- Adds k8s 1.27 release information to chart and table
Fixes #
=> Update k8s chart data for 1.27 release

static/js/src/chart-data.js, templates/about/openstack-release-cycle.html
- Update openstack-release-cycle chart data, based on the updated [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1483484944)
- Go to [the demo](https://ubuntu-com-12844.demos.haus/about/release-cycle#openstack-release-cycle) and check that the 'openstack-releases-cycle' chart matches the data in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1483484944)
- Check the data in 'cahrt-data.js' is accurate
Fixes https://warthogs.atlassian.net/browse/WD-3155
=> Update openstack-release-cycle chart data

templates/download/risc-v/index.html, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html, templates/download/risc-v/tab-5.html, templates/download/risc-v/tab-6.html, templates/download/risc-v/tab-7.html
- Updated copy as per [doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12842.demos.haus/download/risc-v
- Check each tab and see that the requested changes have been made
Fixes # Follow up of https://warthogs.atlassian.net/browse/WD-3078
=> [copy update] /download/risc-v

templates/kubernetes/docs/1.27/release-notes.md, templates/kubernetes/docs/release-notes.md
- Added two links to release notes
=> Add links for K8s preview 

templates/engage/shared/_en_engage_form.html, webapp/views.py
- Add country field to en whitepaper download forms
- Go to any whitepaper download page, for example: https://ubuntu-com-12847.demos.haus/engage/driving-open-source-together-with-canonical-and-intel
- With the network tab open, fill in the form and submit it.
- Check that the form submits correctly and has 'country' in the payload.
- Go to the associated marketo list and check the lead was recieved, in the example above it is: https://engage-sj.marketo.com/?munchkinId=066-EOV-335#/classic/SL100940043B2LA1
Fixes https://warthogs.atlassian.net/browse/WD-2703
=> Add country field to en whitepaper download forms

templates/download/iot/intel-iot.html
- Added the new "Add Real-time Ubuntu Beta optimised for Intel SoCs" content
- Updated the download links and some content
- Open the demo and go to /download/iot/intel-iot
- Ensure the copy matches [the copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-3412
=> WD-3412 - Add Real-time Ubuntu Beta optimised for Intel SoCs

templates/kernel/variants.html
Fixed typo by adding 20.04 to the list of FIPS kernels
Hope this isn't too small of a change. 
Please let me know if there is something I can do differently or better to contribute more effectively.
=> Typo: add 20.04 to FIPS kernel Variants

templates/templates/navigation-enterprise-h.html
- Remove `u-show--small` class from the lists that have both `p-list__item` and `u-show--small` classes
- Go to navigation on ubnutu.com on small screens and click "Enterprise"
- See the [issue](https://github.com/canonical/ubuntu.com/issues/12859) and check it's fixed. 
Fixes https://github.com/canonical/ubuntu.com/issues/12859
=> Remove `u-show--small` class

static/js/src/navigation.js
- Adds a hacky JS fix for 'Ubuntu Advantage' in global nav
- Check global nav doesn't reference Ubuntu Advantage
=> Add temp fix for 'Ubuntu Advantage' reference in global nav

navigation.yaml
- Added /landscape/managed link to subnav and remove "Forums" link
- View the site locally in your web browser at: http://0.0.0.0:8001/landscape
- See that the link is located between "Features" and "Pricing" and check that it routes correctly
- See that external link "Forums" has been removed from the subnav
=> Update /landscape subnav

templates/azure/index.html, templates/embedding/index.html, templates/landscape/index.html, templates/openstack/shared/_openstack_clients.html, templates/openstack/support.html, templates/security/index.html, templates/security/livepatch.html, templates/support/index.html
- Removed all Walmart logos from u.com
- Check out the [demo here](https://ubuntu-com-12880.demos.haus/) and make sure the pages updated correspond with the checklist on [the task](https://warthogs.atlassian.net/browse/WD-3926).
List of pages affect:
- [WD-3926](https://warthogs.atlassian.net/browse/WD-3926)
[WD-3926]: https://warthogs.atlassian.net/browse/WD-3926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [copy update] WD-3926 remove all walmart logos

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/checkout/hooks/useCalculate.tsx, static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx, static/js/src/advantage/subscribe/checkout/utils/helpers.ts, static/js/src/advantage/subscribe/checkout/utils/types.ts, templates/templates/base.html
- Add plausible on the checkout page
- Go to the /account/checkout page, fill in all fields properly and click buy button. 
- Go to https://plausible.io/ubuntu.com
- Check country, product, quantity,   total, buying-for, action are tracked properly under purchase prop on the plausible dashboard
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-3393
=> Add plausible on the checkout page 

templates/server/index.html
- Update the HPE logo
- Check out the [demo here](https://ubuntu-com-12882.demos.haus/server) and compare it with the asset specified in the [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit)
- [WD-3595](https://warthogs.atlassian.net/browse/WD-3595)
[WD-3595]: https://warthogs.atlassian.net/browse/WD-3595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [copy update] WD-3595 update HPE logo on `/server`

templates/legal/ubuntu-pro-description/ros-esm-service-description/index.html
- Remove ROS Support Scope section from `/legal/ubuntu-pro-description/ros-esm-service-description`
- Check out the [demo here](https://ubuntu-com-12887.demos.haus/legal/ubuntu-pro-description/ros-esm-service-description) and compare it with the changes requested on the [copy doc](https://docs.google.com/document/d/12OGV0hnxPvwY2pT8gbS2vHQp3icndJeaEyqc1G_oIoM/edit).
- [WD-3963](https://warthogs.atlassian.net/browse/WD-3963)
[WD-3963]: https://warthogs.atlassian.net/browse/WD-3963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [copy update] WD-3963 remove ROS Support Scope from `/legal/ubuntu-pro-description/ros-esm-service-description`

templates/managed/apps/index.html
- Add #success to return-url on landscape/managed as cypress check was failing
Fixes #
=> Add #success to return-url on landscape/managed

static/js/src/chart-data.js, static/js/src/chart.js, static/js/src/release-chart.js, static/js/src/tabbed-content.js, static/js/src/tabotronic.js, static/sass/_pattern_tabs.scss, templates/about/release-cycle.html, templates/core/features/index.html, templates/download/amd-xilinx/index.html, templates/download/risc-v/index.html, templates/download/risc-v/tab-2.html, templates/kernel/lifecycle.html, templates/openstack/install.html, templates/shared/_kernel-support-schedule.html
- Updates chart data on /kernel/lifecycle based on [spreadsheet data](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=281992953) & some other data for other charts that were broken
- Updates `createChart` to use the earliest and latest dates to scale the graph domain
- Updates tabbed-content.js to use the `u-hide` class instead of `hidden`
- Updates pages that used `tabbed-content.js` to work with refactor
- updates `_pattern_tabs.scss` to have a 'on-paper' vertical tab pattern
- Fixes tabs on `openstack/install`
- Each graph is build of a different tab in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=281992953), compare the data with each graph tab in [the …
=> Update chart data on /kernel/lifecycle

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
- Send additional data to marketo on checkout page
- Go to demo https://ubuntu-com-12884.demos.haus/pro/subscribe
- Buy products
- Check your info is in the list on marketo
- Check request body [here](https://pastebin.canonical.com/p/kSbW54Dt4B/) for marketo api if needed. 
- FYI : if name has first name+ last name, it goes to first name field and last name field each, 
if it has middle name or it's single name, it all goes to last name
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-3834
Before fix:
After fix: 
=> Send additional data to marketo on checkout page

requirements.txt
- Revert the discourse module to the last known working version
- Open the demo and check the docs set:
- /ceph/docs
- /server/docs
- /community/
- /core/docs/
- etc.
Fixes https://warthogs.atlassian.net/browse/WD-4214
=> WD-4214 Revert the discourse module to last known working version

templates/credentials/beta-activation.html, webapp/app.py, webapp/marketo.py, webapp/shop/cred/views.py
- Add form for setting activation keys in marketo
- Visit https://ubuntu-com-12910.demos.haus/credentials/beta/activation
- Enter one or more email addresses and one or more (fake) activation keys
- Verify in [Marketo](https://engage-sj.marketo.com/?munchkinId=066-EOV-335#/classic/SL100906930B2LA1) that the "Credentialing activation key" field has been set for the given email addresses
Fixes https://warthogs.atlassian.net/browse/WD-4215
=> Add form for setting activation keys in marketo

requirements.txt
The new version of cachecontrol might have introduced a dependency on
filelock, so we now need to install it.
See the demo works https://ubuntu-com-12924.demos.haus/
=> Attempt to fix builds by adding filelock dependency

webapp/shop/cred/views.py
- Call `get_annotated_contract_items()` to fetch exam contracts
- Catch exception and show error if exam reservation fails
- Support looking up the contract ID on both staging and production for /credentials/your-exams and /credentials/provision
- Make sure you have redeemed/activated at least one exam (on staging)
- Visit https://ubuntu-com-12899.demos.haus/credentials/your-exams
- Verify that the page loads and lists your exams
- Click on "Take now" on one of your exams
- Verify that your exam provisions without errors
Fixes https://warthogs.atlassian.net/browse/WD-4071
=> Fixes for instant provisioning

navigation.yaml, static/sass/styles.scss, templates/18-04/aws.html
- Built as per [doc](https://docs.google.com/document/d/1mZliSIg5yruIqcTbQwr_D2MNIonmlqnYdrUQzOmIqvE/edit#)
- Design is meant to match the rest of the pages in the 18-04 bubble, please compare against those
- View the site locally in your web browser at: https://ubuntu-com-12915.demos.haus/18-04/aws
- See that the copy matches the doc
- See that the design matches the other 18-04 pages
Fixes https://warthogs.atlassian.net/browse/WD-4155
=> Build /18-04/aws

static/js/src/chart-data.js, static/js/src/chart.js, static/sass/_pattern_chart.scss, templates/about/release-cycle.html
- Updated release chart to include pro as per [mock-up](https://www.figma.com/file/rnBVLtahrGV8NgTHV2Uqez/Release-illustration-draft-brief?type=design&node-id=0-1&t=ZFJKpT3pOQyJ05RS-0)
- Update copy in the Ubuntu release cycle section as per [doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
- View the site locally in your web browser at: https://ubuntu-com-12871.demos.haus/about/release-cycle
- See that the requested updates were made
Fixes # https://warthogs.atlassian.net/browse/WD-2642
=> Update chart.js to include Ubuntu Pro

navigation.yaml, templates/18-04/oci.html, tests/test_routes.py
- Built as per [doc](https://docs.google.com/document/d/1Kdq2tmLk4aA6wceyhS9gmmmyfCU8Ralw0MOts6HtmOM)
- Design is meant to match the rest of the pages in the 18-04 bubble, please compare against those
- Check https://ubuntu-com-12917.demos.haus/18-04/oci against [copy doc](https://docs.google.com/document/d/1Kdq2tmLk4aA6wceyhS9gmmmyfCU8Ralw0MOts6HtmOM)
Fixes https://warthogs.atlassian.net/browse/WD-4152
=> Build new Ubuntu 18.04 LTS OCI page

webapp/views.py
The Discourse-based MicroStack documentation was very recently given a face-lift due to the launch of MicroStack with Sunbeam. The "single-node" and "multi-node" install methods on https://ubuntu.com/openstack/install need to reflect that because the content is sourced from Discourse.
The new Discourse topic IDs on https://discourse.ubuntu.com/ are:
- single-node: [35230](https://discourse.ubuntu.com/t/single-node-quickstart/35230)
- multi-node: [35727](https://discourse.ubuntu.com/t/multi-node/35727)
=> Update OpenStack install methods

templates/openstack/openstack-cheat-sheet.html
- Updated cheat sheet pdf and visual as per ticket request
- View the site locally in your web browser at: https://ubuntu-com-12955.demos.haus/openstack/openstack-cheat-sheet
- See that the assets have been updated
Fixes https://warthogs.atlassian.net/browse/WD-3616
=> [Sunbeam GA launch] Update OpenStack cheat sheet

templates/data/opensearch/index.html
- Changed the heading text on `/data/opensearch`
- Check out the [demo here](https://ubuntu-com-12953.demos.haus/data/opensearch) and compare it with the text specified in the [task](https://warthogs.atlassian.net/browse/WD-4535) and the [copy doc](https://docs.google.com/document/d/17vCodr2uujQv591IlWmveh6_7OLyPK1KrXQb2ZSiceA/edit)
- [WD-4532](https://warthogs.atlassian.net/browse/WD-4535)
[WD-4532]: https://warthogs.atlassian.net/browse/WD-4532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [copy updated] WD-4535 update tagline on `/data/opensearch`

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, webapp/shop/api/ua_contracts/helpers.py
- Fix cancelled subscription bug
- This happens because the interface assumes that the users cancels a subscription using the interface, so down-sizing to 0. The condition based on which we'd set a subscription to cancelled is if the number of machines for next billing cycle == 0
- Using the backoffice tool changes the status of a subscription to `deactivated`, but leaves the number of machines for next billing cycle untouched, therefore subscription would still show as active on the u.c.
- Changed so we also take into account the status of the subscription when determining the if the subscription is cancelled or not
- Added Cancelled status indicator
- Have a fresh account
- Buy a product
- Cancel it using the backoffice tool
- Go to /pro/dashboard on staging, the Edit subscription …
=> Fix cancelled subscription bug

templates/engage/thank-you.html, webapp/views.py
Improve performance of engage pages.
I put some timestamps in various places before and after the submit, I found about 5 seconds difference between the start of the marketo endpoint and then return to the thank-you page. Another 5 secs roughly for rendering the thank-you page, so I focused on improving the rendering part of the thank-you page. Changing marketo/submit endpoint could bring breaking changes, so I tried not to do that, but the other 5 seconds delay is contained within this endpoint.
So this PR should decrease by half the time it takes to submit.
- Go to https://ubuntu-com-12911.demos.haus/engage, pick a whitepaper
- Fill in the form with test data and submit. Compare it with prod, it should be faster now …
=> Improve performance of engage pages submit

static/js/src/advantage/credentials/components/CredManage/CredManage.tsx, templates/credentials/redeem_with_form.html, webapp/shop/cred/views.py, webapp/shop/utils.py
- Add button that leads to /credentials/redeem with the activation key pre-populated
- If necessary, purchase activation key(s) for staging in Backoffice
- Visit https://ubuntu-com-12961.demos.haus/credentials/shop/manage
- Find an unassigned key in the list and click the "Redeem key" button
- Verify that you land on https://ubuntu-com-12961.demos.haus/credentials/redeem and that the key field is pre-populated
Fixes https://warthogs.atlassian.net/browse/WD-4070
=> Add redeem button for activation keys in management view

templates/pricing/devices.html
- Update 'Snap Craft' to 'Snapcraft' on /pricing/devices
- Ege has told me there is no need for a review as this is such a minor change. See issue below
Fixes https://warthogs.atlassian.net/browse/WD-4622
=> Typo fix on /pricing/devices

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
- Move GA event (checkout event) from `UserInfoForm.tsx` to `Checkout.tsx` 
- Add "gaEventTriggered" key in the local storage to prevent same user from being counted multiple times on the checkout page
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-4358
=> Update GA event

static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx, static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, tests/shop/advantage/test_helpers.py, webapp/shop/api/ua_contracts/builders.py, webapp/shop/api/ua_contracts/helpers.py
- Fix bug where trial would show that it's expiring even if auto-renewal is turned on for the subscription.
- Update renewal warnings.
- Get branch locally
- Buy a trial
- Edit: file `webapp/shop/api/ua_contracts/helpers.py` line 335
From: `"is_expiring": is_expiring,` to `"is_expiring": True,` so time wise the subscription should be expiring, but the auto-renewal logic overrides the `is_expiring` status to `False`, because subscription is set to auto renew.
- Expiration warning will not show up
Fixes #https://warthogs.atlassian.net/browse/WD-2659
Trial is expiring warnings now:
Trial is expired warnings now:
Trial is expiring warnings before:
Note: The top notification error message has been updated to point the user to check individual subscription to know how to fix the renewal …
=> Update Trial expiration

.env, konf/site.yaml, static/js/src/advantage/credentials/api/trueability.js, static/js/src/advantage/credentials/app.tsx, static/js/src/advantage/credentials/components/CredWebhookResponses/CredWebhookResponses.tsx, static/js/src/advantage/credentials/components/CredWebhookResponses/index.tsx, templates/credentials/your-badges.html, webapp/app.py, webapp/shop/api/credly/api.py, webapp/shop/api/trueability/api.py, webapp/shop/cred/views.py, webapp/shop/decorators.py
- Take the sample exam on TA 
- Pass the said exam
- After a few hours, a badge should appear in /credentials/your-badges page
- Visit https://app.trueability.com/m/ability_screens/4190/webhooks/202/test
- Response should be {"status":"badge_not_issued"}, 403
- This means that the website is accepting the webhooks
- Now call the [same endpoint](https://ubuntu-com-12946.demos.haus/credentials/assessment_passed) using cURL/Postman.  
`{
"assessment":{
"score":0.75,
"user":{ …
=> [WIP] WD-4072 Automate Badge Issuing using Credly

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, webapp/shop/api/ua_contracts/helpers.py
- Fix technical getting the `Cancelled` label incorrectly
- Login with user 1: buy a product
- Make user 2 a technical user of the account
- Login with user 2: you will not see cancelled label.
Fixes #https://warthogs.atlassian.net/browse/WD-4720
=> Fix techinical user error

navigation.yaml, templates/appliance/lxd/_next-steps.html, templates/appliance/lxd/index.md, templates/containers/index.html, templates/download/desktop/index.html, templates/industrial/index.html, templates/kubernetes/_install-lxd.html, templates/kubernetes/charmed-k8s.html, templates/kubernetes/docs/inclusive-naming.md, templates/kubernetes/docs/install-local.md, templates/kubernetes/docs/install-offline.md, templates/kubernetes/index.html, templates/legal/websites.html, templates/lxd/index.html, templates/lxd/install.html, templates/lxd/manage.html, templates/shared/contextual_footers/_cloud_lxd_vs_docker.html, templates/templates/navigation-developer-h.html
- added lxd/install and lxd/manage pages
- check /lxd, /lxd/install and /lxd/manage
Fixes WD-4823
=> Add pages to install and manage lxd

templates/lxd/install.html
- Update heading on lxd install page
- check the heading on /lxd/install second heading changed
=> Update lxd install page copy

templates/nvidia/index.html
- Added a link around the image as requested in the [copy doc](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit?disco=AAAA0iU6AU0)
- Go to /nvidia
- Scroll to the "Turnkey AI solutions for the enterprise powered by Canonical and NVIDIA" and check the image is clickable as requested in the copydoc
- Check for a11y issues
Fixes https://warthogs.atlassian.net/browse/WD-4878
=> WD-4878 - Clickable diagram on the Nvidia page

templates/credentials/your-exams.html, webapp/shop/cred/views.py
- Update visuals for /credentials/your-exams
- Visit https://ubuntu-com-12987.demos.haus/credentials/your-exams
- Check the visual design against the [design](https://www.figma.com/file/ZTdYjh2H2nT9rRo9BYHv4G/CUE?node-id=565%3A9375)
- If you have a scheduled exam, mouse over the information icon and verify that the tooltip appears
Fixes https://warthogs.atlassian.net/browse/WD-3905
=> Update visuals for /credentials/your-exams

static/js/src/navigation.js
- update link for lxd in meganav
- check meganav (product link on the top) for the lxd link, it should point to /lxd and not to the external linuxcontainers.org page
=> Update lxd link in meganav

navigation.yaml, redirects.yaml, templates/certified/desktops.html, templates/certified/devices.html, templates/certified/index.html, templates/certified/laptops.html, templates/certified/search-results.html, templates/certified/servers.html, templates/certified/shared/category-search-results.html, templates/certified/socs.html, templates/certified/why-certify.html, templates/core/features/secure-boot.html, templates/dell/index.html, templates/download/iot/intel-iot.html, templates/download/raspberry-pi/index.html, templates/internet-of-things/smart-displays.html, templates/robotics/index.html, webapp/app.py
UX improvements for /certified
https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?modal=detail&selectedIssue=WD-4286
Category pages “‹ Certified Hardware” s links to /certified:
- https://ubuntu-com-13004.demos.haus/certified/desktops
- https://ubuntu-com-13004.demos.haus/certified/laptops
- https://ubuntu-com-13004.demos.haus/certified/iot
- https://ubuntu-com-13004.demos.haus/certified/socs
-Remove the H2 header (e.g. “All certified desktops”), it’s redundant.
- Added H1 header to generic results page https://ubuntu-com-13004.demos.haus/certified?q=
- Change “Devices” in the bubble navigation for “IoT”. This change involves renaming all /certified/devices paths to /certified/iot
[QA steps](https://discourse.canonical.com/t/qa-steps/152) …
=> WD-4286 certified UX improvements

static/js/src/advantage/subscribe/react/UAPurchase.tsx, static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx, static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx, static/js/src/advantage/subscribe/react/components/Form/Form.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.test.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductUser/ProductUser.test.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductUser/ProductUser.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductUser/index.ts, static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx, static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts
1. Disable Ubuntu Pro in the step 4 "What security coverage do you need?" when server 14.04 is selected
2. Add public cloud instances and update copy doc according to this [doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit)
2. Add "Who will be using this subscription?" step according to this [figma](https://www.figma.com/file/FEK76z86SxEzzRUzSOcpKe/Pro-Shop-update---Personal-vs-Enterprise-subscription?type=design&node-id=20-8&mode=design)
- go to /pro/subscribe
1. 
- Select "myself"  in the Step 1 "Who will be using this subscription?" and check all other steps are not visible and in the summary it says "ubuntu pro", quantity 5, total free, button says register. 
- Select "my organisation" and check all other steps are working as it was before
2. 
- …
=> Update /pro/subscribe page 

static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts
- Match Pro Desktop infra with `uai-essential-desktop`
- Write some test code for product summary
- Go to /pro/subscribe 
- Select organisation - desktops - 14.04 LTS
- Check only Ubuntu Pro (Infra-only) is available
- Check product name is Ubuntu Pro desktop and price is $25 per machine in the product summary 
Fixes #
=> Match Pro Desktop infra with uai-essential-desktop

static/sass/_pattern_footer.scss
Some suggested improvements for the Ubuntu.com footer on small screens: 
- Reduced the size (font and line-height) of footer accordions to take up less space on small devices 
- Increased the size of 'back to top' button - to more closely resemble the other accordions and improve accessibility of this [touch target](https://accessibility.digital.gov/ux/touch-targets/#:~:text=Make%20touch%20targets%20at%20least,extend%20padding%20past%20the%20icon)
- Changed colour of 'back to top' button to help differentiate between itself and newly resized accordions. It might look better if the arrow image was also orange, but I couldn't access the svg to change it 
- Added left-side padding to secondary footer content, as previously it started against the border
- Adjusted all breakpoints so the above …
=> Adjust footer size on small screens

webapp/marketo.py
- When adding Credentials activation keys to Marketo, create the lead if it doesn't already exist in Marketo
-
Fixes https://warthogs.atlassian.net/browse/WD-4703
=> Create Marketo lead if it doesn't exist

static/js/src/risc-v.js, static/js/src/tabbed-content.js, static/sass/styles.scss, templates/download/risc-v/index.html, templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html, templates/download/risc-v/tab-5.html, templates/download/risc-v/tab-6.html, templates/download/risc-v/tab-7.html
- Applied redesign as per [mock-up](https://www.figma.com/file/WsMLgH1TXcU1mZ7YjqZRDY/u.com%2Fdownload%2Frisc-v?type=design&node-id=1-479&t=CjoQFe70UKFQNHyE-0)
- Added functionality for small screen dropdown select
- View the site locally in your web browser at: https://ubuntu-com-12870.demos.haus/download/risc-v
- Check against design
Fixes https://warthogs.atlassian.net/browse/WD-3875
=> /download/risc-v redesign

templates/contact-us/index.html, templates/legal/anbox-cloud-privacy-notice.html, templates/legal/data-privacy/contact.md, templates/legal/data-privacy/esxi.md, templates/legal/data-privacy/events.md, templates/legal/data-privacy/index.html, templates/legal/data-privacy/newsletter.md, templates/legal/data-privacy/online-competitions.md, templates/legal/data-privacy/online-purchase.md, templates/legal/data-privacy/partner-portal.md, templates/legal/data-privacy/recruitment.html, templates/legal/data-privacy/snap-store.md, templates/legal/data-privacy/snapcraft-nps.md, templates/legal/data-privacy/sso.md, templates/legal/data-privacy/survey.md, templates/legal/data-privacy/unilateral-nda.md, templates/legal/data-privacy/user-survey.md, templates/legal/data-privacy/webinar.md, templates/legal/livepatch-terms-of-service.html, templates/legal/motd.html, templates/legal/systems-information-notice.html
- Update the legal addresses across the site
- Check that the addresses are correctly now pointing to Canonical Group Limited. Our address is 5 New street Square, London, EC4A 3TW, United Kingdom
- And 4th floor, 201 Borough High St. London SE1 1JA, United Kingdom for correspondence 
- Check the odd copy doc matches
Fixes https://warthogs.atlassian.net/browse/WD-5114
=> WD-5114 - Update the legal addresses across the site

redirects.yaml, robots.txt, static/files/robots.txt, webapp/app.py, webapp/views.py
- Moved robots.txt to root folder
- Generate sitemaps for engage pages.
- https://ubuntu-com-13043.demos.haus/robots.txt Should 200 if you `curl` it (previously it was redirecting, you can check in prod)
- https://ubuntu-com-13043.demos.haus/engage/sitemap.xml should return now all links for engage pages
Fixes https://warthogs.atlassian.net/browse/WD-5037?atlOrigin=eyJpIjoiOWVjYjBiZjcyYzlhNDRjODkzZGVjOGU1ZTZlYzg5ZTQiLCJwIjoiaiJ9
=> Generate sitemaps and fix robots.txt path for analytics

templates/download/amd-xilinx/tab-3.html
- Update desktop to server on tab 3 of /download/amd-xilinx as per [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit#heading=h.r1pnhz6oolxo)
- [See demo](https://ubuntu-com-13053.demos.haus/download/amd-xilinx)
Fixes https://warthogs.atlassian.net/browse/WD-5189
=> Update desktop to server on tab 3 of /download/amd-xilinx

redirects.yaml, tests/cassettes/TestCertification.test_search_results.yaml, tests/test_certification.py, webapp/app.py, webapp/certified/views.py
At the moment[ https://ubuntu.com/certified?q=&category=Desktop](https://ubuntu.com/certified?q=&category=Desktop) and [Certified desktops | Ubuntu](https://ubuntu.com/certified/desktops)  look different. They shouldn’t. The former (the regular search page) should redirect to the latter (the category page).
Pretty URLs should take precedence, so queries like[ https://ubuntu.com/certified?q=Nvidia&category=Desktop](https://ubuntu.com/certified?q=&category=Desktop) should be redirected to[ https://ubuntu.com/certified/desktops?q=Nvidia](https://ubuntu.com/certified/desktops?q=Nvidia) (URL should remain unchanged when more than one category is selected)
When there is more than one category selected, URL structure should remain unchanged: …
=> Update /certified paths to favor pretty links

templates/engage/shared/_de_engage_form.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_es_engage_form.html, templates/engage/shared/_it_engage_form.html, templates/engage/shared/_pt_engage_form.html, templates/engage/shared/_ru_engage_form.html, templates/engage/shared/_zh-TW_engage_form.html, templates/legal/data-privacy/index.html
- Changes the link 'Ubuntu Community Discourse' to 'Ubuntu Community Discourse Privacy Notice' on /legal/data-privacy based on [copydoc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit). I believe this was the only change, the other changes appear to be live. As for the request from Sarah, lets see if she get's back to use quickly and if she does we can include that change also.
- Removes a class from a `<li>` on an engage form so it matches the rest of the list visually.
- [List additional steps to QA the new features or prove the bug …
=> Update link name on /legal/data-privacy

templates/ceph/index.html
- Remove wrongfully placed Ceph install link
- Check out [the demo here](url) and make sure the link shown in [the task](https://warthogs.atlassian.net/browse/WD-5374) is removed from the page.
- [WD-5374](https://warthogs.atlassian.net/browse/WD-5374)
[WD-5374]: https://warthogs.atlassian.net/browse/WD-5374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [copy update] WD-5374 remove ceph install link

static/js/src/chart-data.js, templates/about/openstack-release-cycle.html, templates/about/release_cycles/microstack-eol.html, templates/about/release_cycles/openstack-eol.html
- Fix the OpenStack release name convention for recent years (2023 - present)
- Check out [the demo here](url) and compare it with the requested change in this issue: #13000
- Make sure the new mappings are correct:
- OpenStack Antelope -> OpenStack 2023.1
- OpenStack Bobcat/B -> OpenStack 2023.2
- OpenStack C -> OpenStack 2024.1
- OpenStack D -> OpenStack 2024.2
- OpenStack E -> OpenStack 2025.1
- OpenStack F -> OpenStack 2025.2
- OpenStack G -> OpenStack 2026.1
- Ensure to check both the MicroStack and Charmed OpenStack chart
- Test on mobile screens as well
- #13000 
- [WD-5338](https://warthogs.atlassian.net/browse/WD-5338)
[WD-5338]: …
=> [copy update] WD-5338 Fix OpenStack release naming convention

static/js/src/advantage/api/enum.ts, static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, webapp/shop/api/ua_contracts/builders.py
- Created `key_activated` in subscription type 
- Added expiry message saying  "Contact OEM to renew and ensure service continuity." so it shows when subscription is expiring.  
- Go to `/webapp/shop/api/ua_contracts/helpers.pyhelpers.py` 
- Line 352 change  "is_expiring" to True
- 
- Run ubuntu.com locally
- Activate a key on /pro/activate
- Check expiry message
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-4619
=> Show expiry message for subscriptions activated by keys

navigation.yaml
- Remove support from sub-nav.
- Is the support button there on the subnav on /pro and /pro/dashboard? I don't think so!
Fixes #https://warthogs.atlassian.net/browse/WD-4639
=> Remove Support from navigation

webapp/shop/api/ua_contracts/helpers.py
- There are two Renewal statuses that mean that a Legacy subscription was renewed: done, closed.
- Before we only considered "closed".
- The logic we had was making it that Renewed (with status closed) Legacy subscriptions would no longer have the `will expire soon` notifications. As it was renewed.
- But Renewed (with the status done) Legacy subscriptions would still show `will expire soon` notifications. Now they behave as closed renewals.
- Hard to QA due to having to hard-code yourself expiring subscriptions. But here is a screenshot:
Bottom subscription no longer shows the expiring soon notification. 
Fixes #https://warthogs.atlassian.net/browse/WD-5535
=> Is expiring closed/done Renewal bug fix

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
- Some renewals are added to legacy purchases earlier than expected. Display the `Not renewed` label only if the renewal is also ready to be purchased : `statuses.is_renewable == true`
- Hard to QA, you need to View As user from a local environment. 
- But look, label "Not Renewed" disappears:
Prod: 
After the change:
Fixes #https://warthogs.atlassian.net/browse/WD-5368
=> Improve not renewed label logic

templates/engage/shared/_fr_engage_form.html
- Removed extra "comment" field from the /engage/fr form template, when we need this field, it should be added on an ad-hoc basis and not in the template mostly used for whitepapers.
Fixes #
=> Remove extraneous field from the /engage/fr form

templates/sitemap_index.xml
- Adds a link to the robotics sitemap to the sitemap_index
Fixes https://warthogs.atlassian.net/browse/WD-4765
=> Update sitemap_index.xml to include robotics sitemap

templates/azure/pro.html
- Go to https://ubuntu-com-13096.demos.haus/azure/pro
- Updated only the new "Upgrade Ubuntu LTS to Ubuntu Pro" with its blog link. The other comments look like discussion.
Fixes https://warthogs.atlassian.net/browse/WD-5828?atlOrigin=eyJpIjoiZjUzNWFjMGNjNzkwNGY2Yjg3OTViYmQ4ZTk3NGQ1Y2IiLCJwIjoiaiJ9
=> Update 'Upgrade Ubuntu LTS' title and blog link

redirects.yaml
- Go to https://ubuntu-com-13097.demos.haus/fan should redirect to https://github.com/canonical/ubuntu.com/issues/12927
Fixes https://github.com/canonical/ubuntu.com/issues/12927
=> Redirect for Ubuntu fan package doc URL

templates/credentials/index.html
- Added back information about the beta signups being closed for now on the index page of credentials 
- Change the `CONTRACTS_API_URL` in `.env.local` to production url
- visit [/credentials](http://0.0.0.0:8001/credentials)
- Verify that there is a line on the landing about the beta signups being closed.
Fixes [#WD-5943](https://warthogs.atlassian.net/browse/WD-5943)
=> [WD-5943] Added beta message to credentials index page

webapp/views.py
- Updated the engage page sitemap date format to match other passing sitemaps like the https://ubuntu.com/ceph/docs/sitemap.xml
- Open the demo and go to /engage/sitemap.xml
- See the date format is ISO 8601 (for example, `2023-08-22T21:22:53Z`)
Fixes https://warthogs.atlassian.net/browse/WD-5961
=> WD-5961 - Fix the engage sitemap date format

templates/openstack/install.html
- Update survery link on /openstack/tutorials based on [copydoc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#heading=h.4t7jro4ogj)
Fixes https://warthogs.atlassian.net/browse/WD-6016
=> Update survery link on /openstack/install

templates/shared/_pro-contact-us-form.html
Pro contact form now asks for number of machines wants to cover with their potential subscription.
Fixes https://warthogs.atlassian.net/browse/WD-6044
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us/form?product=pro
- Make sure the form asks for the number of machines the same way [this one does](https://ubuntu.com/security/esm#get-in-touch)
=> Pro contact form number of machines field

webapp/views.py
`acquisition_url` shows only hostname, Marketing requires this to be the full page URL. This is an attempt to achieve that using an alternative source.
- Go to https://jp-ubuntu-com-463.demos.haus/blog/accelerating-the-adoption-of-ai-in-banking-with-mlops-jp
- Submit the newsletter form on the right.
- Check ubuntu forms work too e.g. https://ubuntu-com-13089.demos.haus/blog/canonical-extends-commercial-openstack-offering-to-small-scale-cloud-environments-with-project-sunbeam fill up newsletter form on the right and that you don't get marketo sentry errors https://sentry.is.canonical.com/canonical/ubuntu-com/
- You should receive the acquisition URL now in Marketo.
Fixes https://warthogs.atlassian.net/browse/WD-5585?atlOrigin=eyJpIjoiMWZkM2Y1MWJmM2QyNDJlMDhiYjcyZDBiMjQyOWQ2ZTYiLCJwIjoiaiJ9 …
=> Fix acquisition URLs for jp/cn.ubuntu.com

templates/ai/roadshow.html
I updated the calendly link to a contact form https://ubuntu.com/ai/contact-us?product=ai-index
- Update in the copy the https://ubuntu.com/ai/contact-us?product=ai-index (from the Calendly one) and copy from _Book a meeting_ to _Get in touch_
Deployed and checked locally
=> Update CTA roadshow.html

templates/blog/article.html
Update the canonical URL for articles authored by Canonical
- Go to /blog
- Open an article by someone else then Canonical and view-source
- See that the `rel="canonical"` points to ubuntu.com/blog
- Go back and open an article from Canonical and view-source
- See that the `rel="canonical"` points to canonical.com/blog
There are some tags which might mix this up a little.
Fixes https://warthogs.atlassian.net/browse/WD-6198
=> WD-6198 - Update the canonical URL for articles authored by Canonical

static/sass/_layout-tutorial.scss, templates/tutorials/tutorial.html
In Vanilla 4 we removed circles from stepped list counters.
Tutorials had custom styles that used the stepped list counters and changed their colour for active tutorial step. This became broken in Vanilla 4.0, because there are no circles to highlight anymore.
As a workaround this PR recreates similar circle styling locally in ubuntu.com. 
But eventually this should be addressed while rebranding tutorials by changing stepped list to better component for side navigation.
- Go to any tutorial, make sure steps navigation doesn't look broken:
- …
=> Fix broken tutorials styling in Vanilla 4

static/js/src/chart-data.js
**I have shared the demo link with Brett and will wait for his approval before merging.**
- Updates the graphs `All releases`, `All LTS releases` and `22.04 LTS` with latest data from [the spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1844838308)
- Check that the data displayed in [the demo](https://ubuntu-com-13147.demos.haus/kernel/lifecycle) matches that in the spreadsheets and addresses the issues described in the original issue
Fixes https://warthogs.atlassian.net/browse/WD-5048
=> Update /kernel/lifecycle with most recent changes

navigation.yaml, static/sass/_pattern_ai.scss, templates/ai/index.html, templates/ai/mlflow.html, templates/ai/what-is-kubeflow.html
- Addressed stakeholder feedback:
- Fix typos, update Kubeflow title in subnav, update logos on landing to use base Vanilla, added missing links to MLflow logos (not all have links)
- View the site locally in your web browser at: https://ubuntu-com-13158.demos.haus/ai
- Click through the affected pages and make sure everything looks as expected
=> Final fixes for /ai bubble refresh

navigation.yaml, templates/confidential-computing/index.html, templates/shared/forms/interactive/confidential-computing.html
- Add a new page called "Confidential Computing" according to [copy doc](https://docs.google.com/document/d/1QGwS5CYlwXkaPibSFvcag6zLcUH5lNDUbM18hCqbOJM/edit#heading=h.n4yj7d5ptzm9) and [design](https://www.figma.com/file/zyG3Iyys2GlxxfqfQQT7bT/23.10-U.com---Confidential-computing?type=design&node-id=0%3A1&mode=dev)
- Add a new modal contact form for "Confidential Computing" according to [copy doc](https://docs.google.com/document/d/1F4QYakPaIAL5fcttOnegkldTiWQ_tRon9apfbradX08/edit#heading=h.6d3m0dei0nxs)
- Navigate to …
=> [WD-5855] new page for confidential computing

templates/download/amd/index.html
Update meta image
- Check https://ubuntu-com-13167.demos.haus/download/xilinx has the new meta image according to [copy docs](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- Go to https://www.opengraph.xyz/ and insert the URL into the bar, and you should see the new meta image. To compare, you can do the same with https://ubuntu.com/download/amd
Fixes https://warthogs.atlassian.net/browse/WD-6078 (follow-up)
=> Update meta for AMD download page

templates/ai/roadshow.html
- Fix the logo layout on the ai/roadshow page
- Go to /ai/roadshow and see the logo section is not vertically aligned.
=> Fix the logo layout on the ai/roadshow page

templates/certified/model-details.html, templates/download/amd/tab-3.html, templates/download/iot/index.html, templates/internet-of-things/index.html, templates/templates/navigation-download-h.html, tests/cypress/integration/navigation_spec.js, webapp/certified/helpers.py
Rename AMD-xilinx to AMD
- Check all instances of AMD-xilinx have been updated to amd. E.g. https://ubuntu-com-13170.demos.haus/certified/202202-29985
Fixes #
=> Rename all instances of AMD-xilinx to AMD

README.md
- For some Mac machines (with silicon chips) when you run `dotrun` to spin up local instance you get an error related to not being able to download/install Chromium. I added a step how to fix this issue that worked for me.
There is not issue for this, it's just a small addition to README
=> add to README steps to fix Chromium related error on Mac

templates/confidential-computing/base_confidential-computing.html, templates/confidential-computing/index.html
- Split confidential-computing template to base and index (addresses https://github.com/canonical/ubuntu.com/pull/13161#discussion_r1328580751)
- Add ordered list to one section (addresses https://github.com/canonical/ubuntu.com/pull/13161#discussion_r1328592223)
- Check Confidential Computing page at the following URL: `/confidential-computing` 
Addresses left over comments from previous PR https://github.com/canonical/ubuntu.com/pull/13161
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/ …
=> address left over comments from previous PR

templates/shared/_security-patching-logo-cloud.html
- Removed "Open Source Mano (OSM)" from the list of supported apps
- Navigate to the following URLs to check if "Open Source Mano (OSM)" is not in the list of supported apps:
- /support
- /engage/unlisted/at&t-onboarding
Closes https://warthogs.atlassian.net/browse/WD-6427
=> [WD-6427] remove OSM from the list of supported apps

templates/download/risc-v/tab-1.html, templates/download/risc-v/tab-2.html, templates/download/risc-v/tab-3.html, templates/download/risc-v/tab-4.html, templates/download/risc-v/tab-5.html, templates/download/risc-v/tab-6.html, templates/download/risc-v/tab-7.html
- Updated Ubuntu images to 23.10 on RISC-V download page
- Navigate to `/download/risc-v` and check that all tabs for different boards have links to download 23.10 image instead of 23.04
Closes https://warthogs.atlassian.net/browse/WD-6353
=> [WD-6353] change 23.04 to 23.10 on RISC-V download page

releases.yaml, templates/download/server/manual.html
- Updated latest release to Mantic Minotaur in `releases.yaml`
- Updated a mascot of the latest release in `/download/server`
- [Copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
- Navigate to `/download/server` and check that the `Alternative releases` section shows information about Mantic Minotaur 23.10 release.
Closes https://warthogs.atlassian.net/browse/WD-6300
=> [WD-6300] /get-ubuntu-server copy update

static/sass/_pattern_subscriptions.scss
- Fix subscription status chips broken on small screens
- Buy pro desktop with full support 
- Go to dashboard 
- Check the `auto-renewal on` label has fixed height on small screens
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?selectedIssue=WD-6295
=> Fix subscription status chips

static/sass/styles.scss, templates/ai/what-is-kubeflow.html, templates/pro/why-pro.html
- Build /why-pro page base on [copydoc](https://docs.google.com/document/d/1f1LU-xfBYt48UcJxYcNkW4mGB2u1spdjJrILJBGCI1Y/edit#heading=h.rocxkjlhnbpz) and [design](https://www.figma.com/file/mCV6YajRJtsnEsctbUNgI3/23.10-U.com---Why-Ubuntu-Pro?node-id=158%3A2342&mode=dev)
- Added some custom styling for the `p-divider` class to removed a divider from a specific block, issue create [here](https://github.com/canonical/vanilla-framework/issues/4877)
- Check out https://ubuntu-com-13182.demos.haus/pro/why-pro compare against [copydoc](https://docs.google.com/document/d/1f1LU-xfBYt48UcJxYcNkW4mGB2u1spdjJrILJBGCI1Y/edit#heading=h.rocxkjlhnbpz) and [design](https://www.figma.com/file/mCV6YajRJtsnEsctbUNgI3/23.10-U.com---Why-Ubuntu-Pro?node-id=158%3A2342&mode=dev)
Fixes …
=> Build /pro/why-pro page

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
- Added [Ubuntu Pro network requirements](https://canonical-ubuntu-pro-client.readthedocs-hosted.com/en/latest/references/network_requirements.html) to Documentation & tutorials on Pro Dashboard
- View the site locally in your web browser at: http://0.0.0.0:8001/pro/dashboard
- Check the new link shows in the documentation.
Fixes [#WD-6469](https://warthogs.atlassian.net/browse/WD-6469)
=> Add Pro network requirements documentation link to dashboard

static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
- Fixes card checkout error for new users
- Make a new account on checkout
- add vat number with something wrong and save
- and do everything right
- click buy button
- then you get error message with VAT number
- and then remove the wrong vat number and save
- and then click buy button
- Should not get any errors
Fixes #[WD-6481](https://warthogs.atlassian.net/browse/WD-6481)
[WD-6481]: …
=> fix for checkout error

templates/shared/contextual_footers/_openstack_documentation.html
https://github.com/canonical/ubuntu.com/issues/12841
Href value was corrected to https://charmhub.io/?q=OpenStack
How to test: 
1. https://ubuntu.com/openstack
2. Scroll to section: Open Detailed documentation
3. Hoover over Charmed OpenStack link - Does browser display following url https://charmhub.io/?q=OpenStack
4. Click on the Charmed OpenStack link - Did it send to https://charmhub.io page and OpenStack filter is active
=> #12841 Issue - Correct href value to https://charmhub.io/?q=OpenStack

templates/templates/_footer-copyright-and-legal.html
https://github.com/canonical/ubuntu.com/issues/12840
Href value adjusted to: 
`https://github.com/canonical/ubuntu.com/issues/new`
How to test:
1. Navigate to any Ubuntu.com/* page that contains _Report a bug on this site_ link in footer
2. Scroll down to footer and hover over the _"Report a bug on this site"_ link
3. Click on link
4. Observe if you were sent to _Ubuntu GitHub repository - create new issue_ view 
5. Observe if issue footer displays the `ubuntu.com/<page>` link of source from which you've arrived from - page where you clicked on _Report a bug on this site_ link
=> #12840 Issue - Correct href value

templates/download/risc-v/tab-3.html
- Change link for downloading QEMU preinstalled image on RISC-V download page
- Navigate to `/download/risc-v` page and check the link of the button `Download 23.10` in `Ubuntu Server preinstalled image` section of `QEMU emulator` tab
Closes https://warthogs.atlassian.net/browse/WD-6656
=> [WD-6656] change link for QEMU preinstalled image on RISC-V download page

templates/legal/ubuntu-pro-description/ja/_toc_ja.html
- Fixes broken HTML markup in a link in table of contents on JA version of the site
- Check demo at https://ubuntu-com-13194.demos.haus/legal/ubuntu-pro-description/ja
- Make sure there is no leaking markup in the table of contents
Before (https://ubuntu.com/legal/ubuntu-pro-description/ja):
After:
=> Fix unclosed link in table of contents

templates/account/forbidden.html, webapp/shop/advantage/views.py, webapp/shop/views.py
- Show access forbidden page on /account/checkout when signed in with a technical account 
Check these...
Forbidden pages tests:
- As `personal` (Free token only):
- As `technical`:  
- As `billing`:
Fixes #https://warthogs.atlassian.net/browse/WD-6480
=> Forbidden checkout on technical account

static/js/src/advantage/credentials/api/keys.js, static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx, static/js/src/advantage/credentials/components/CredKeyShop/CredKeyShop.tsx, static/js/src/advantage/credentials/components/CredWebhookResponses/CredWebhookResponses.tsx, static/js/src/advantage/credentials/utils/utils.ts, static/js/src/advantage/subscribe/blender/utils/utils.ts, templates/credentials/index.html, webapp/app.py, webapp/shop/cred/views.py
- Reopening the keys shop when the CUE Activation Keys go live in production.
- Go to /credentials
- There will be two buttons for individual exams and keys
- Change the CONTRACTS_API_URL to production in `.env.local`
- Restart dotrun
- Go to /credentials again
- There should be a text in italics as things are not in production yet 
Fixes [#WD-5840](https://warthogs.atlassian.net/browse/WD-5840)
=> Add link to CUE Activation Keys shop

static/js/src/advantage/users/hooks/useRequestAccountUsers.tsx, tests/cypress/integration/pro/checkout_spec.js
- Users with Free token only (without Purchase account) should not get the `Add account users` notification.
-  Use a fresh account. You should not see the notification.
- Use an account with a paid subscription, you should see the notification.
Fixes #https://warthogs.atlassian.net/browse/WD-6618
=> Hide notification for personal users

static/js/src/chart-data.js, templates/desktop/developers.html
- Add changes according to [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
- Add more space for the chart on the page
- On large screens designated 7 columns of the grid instead of 6 as before. This means that the text content on the left now has 5 columns. 
- On smaller screens remove centering utility classes so that now the chart takes the full width without any spacings from the sides.
- Navigate to /desktop/developers page and check changes there
Closes https://warthogs.atlassian.net/browse/WD-6255
[QA …
=> [WD-6255] /desktop/developers copy update

static/js/src/chart-data.js, templates/desktop/developers.html, templates/download/index.html, templates/download/iot/index.html
- Remove 22.10 release from charts on `/desktop/developers`, `/16-04` and `/16-04/azure`, since it's not supported anymore
- Replace Lobster mascot with Minotaur mascot on `/download` page
- Fix Raspberry Pi related text on `/download/iot` page
- Naviage to all above mentioned (in Done section) routes and check changes
Closes https://warthogs.atlassian.net/browse/WD-6707
=> [WD-6707] Minor changes on download pages

templates/download/desktop/index.html
- Fixed ubuntu download link
Fixes #
=> WD-6769 - fix dowload link

releases.yaml
- Updated the checksums for 23.10 release
- Check the downloads work and match the checksums
```
444c8a7b993cb6f103d7df1144954064889cbf7491b2415518d5dd0875e3a96f *ubuntu-23.10-desktop-amd64.iso
d2fb80d9ce77511ed500bcc1f813e6f676d4a3577009dfebce24269ca23346a5 *ubuntu-23.10-live-server-amd64.iso
228dc794edcbbdce0f60fa7e3aa0490d4524fe054644b6e81eee0be7ca924656 *ubuntu-23.10-desktop-legacy-amd64.iso
5ea4c792a0cc5462a975d2f253182e9678cc70172ebd444d730f2c4fd7678e43 *ubuntu-23.10-live-server-arm64.iso
cfe96609cc7bbc92495772d6676f2a066d16b058a61f4502161c3302dad6cabb *ubuntu-23.10-live-server-ppc64el.iso
c610dc499e3837d81befe6f47bee27f3b952a794c3eec3c026fa7cd5b25151b6 *ubuntu-23.10-live-server-riscv64.img.gz
7ac8166432f5d4ef3e3e3dbdb4b47323ab4816ad85db7cab0ffa62c1690fc15b …
```
=> WD-6442 - Update checksums for 23.10

templates/kubernetes/docs/index.md
- Reworked the landing page to standardise on diataxis layout.
=> Update K8s docs homepage

templates/pro/index.html
- Fix typos on pro page.
- View the site in web browser at: https://ubuntu-com-13243.demos.haus/pro
- Review for typos
=> Pro page: fix typos

templates/security/disclosure-policy.html
Please update Ubuntu's Disclosure Policy to be more inclusive.
Currently, the policy states that only "real names" will be credited for the discovery of vulnerabilities.
The term "real name" is ambiguous. It can be interpreted as meaning someones legal name. Requiring legal name can be used for discrimination. For this reason, [the Kernel recently changed their DCO requirements with](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d4563201f33a022fc0353033d9dfeb1606a88330): 
```
-using your real name (sorry, no pseudonyms or anonymous contributions.)
+using a known identity (sorry, no anonymous contributions.)
```
People around the world use Romanized identities on the internet. Individuals may associate *real name* to a *dead name*. There are many reasons to …
=> inclusive identities

static/js/src/landscape-saas-form.js, templates/landscape/pricing.html, templates/shared/forms/interactive/landscape-pricing-saas.html
- Fix custom fields not being passed through on submission
- View the site locally in your web browser at: https://ubuntu-com-13248.demos.haus/landscape/pricing
- Click on "Get Landscape SaaS" CTA
- Fill out and submit the form with the network tab on dev tools open
- See that the checkbox answers are included in the "Comments_from_lead_c" field
Fixes https://github.com/canonical/ubuntu.com/issues/13187 , https://warthogs.atlassian.net/browse/WD-6566
=> Fix form custom fields

releases.yaml, templates/download/alternative-downloads.html, templates/download/desktop/index.html
- Enabled (returned) 23.10 desktop image download button/link on two pages:
- /download/desktop
- /download/alternative-downloads
- Added new property called `desktop_version` in `releases.yml` since the latest Desktop image has a different version than all other 23.10 release images
- Updated the checksum for the latest desktop image
- Navigage to /download/desktop and check that the Download 23.10 button is enabled and the desktop image can be downloaded.
- Navigate to /download/alternative-downloads and check that Download 23.10 Desktop (64-bit) link exists and …
=> [WD-6779] enable 23.10 desktop download button/link

static/js/src/chart-data.js, templates/about/release_cycles/k8s-eol.html
Our support dates were a bit off.  Upstream k8s releases enter maintenance mode every 12(ish) months and always on the 28th:
https://kubernetes.io/releases/patch-releases
This PR aligns our `n-2` releases with the 12mo upstream dates and our `n-4` esm window with the respective 8mo period that follows.
- align current release support with upstream dates
- add 1.28 dates
Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/808
[QA …
=> adjust release-cycle dates for k8s 1.28

templates/templates/navigation-enterprise-h.html
- Updated link in Enterprise nav as per [doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit)
- View the site locally in your web browser at: https://ubuntu-com-13251.demos.haus/#enterprise
- See that the change has been made
Fixes https://warthogs.atlassian.net/browse/WD-6783
=> Update Enterprise nav link

templates/automotive/buyers-guide/index.html
- Added the new EB corbos Linux section to the automotive buyers guide page
- Go to /automotive/buyers-guide
- Check the new section is at the bottom
- Click it and check the content matches [the copy doc](https://docs.google.com/document/d/1NLnoNEP6cL46PotNGVuKLajehl-nfyBU4C8JT-FYMvQ/edit?disco=AAAA6__PTh4)
- Ensure the navigation between the sections work
Fixes https://warthogs.atlassian.net/browse/WD-6799
=> WD-6799 - Add EB corbos Linux to the automotive buyers guide

templates/kubernetes/docs/explanation-index.md, templates/kubernetes/docs/how-to-index.md, templates/kubernetes/docs/index.md, templates/kubernetes/docs/reference-index.md, templates/kubernetes/docs/tutorials-index.md
- Adds four pages to serve as the indexes for the diataxis sections
- corrects the index page to point at these
- 
=> Add K8s docs index pages

releases.yaml
- Reverted Core version as there is no Core 23
- View the site locally in your web browser at: https://ubuntu-com-13262.demos.haus/rapsberry-pi
- See that the version in the download link for the Ubuntu Core 22 has been updated
Fixes https://github.com/canonical/ubuntu.com/issues/13242
=> Revert core version

templates/landscape/index.html
- Changed text and asset in 'Take control of your infrastructure' section
- Updated text in 'Save time and improve security at scale' section
- Added webinars table
- Removed image
- Check out this feature branch and compare against [copydoc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit)
[WD-5991](https://warthogs.atlassian.net/browse/WD-5991)
Fixes #
[WD-5991]: https://warthogs.atlassian.net/browse/WD-5991?atlOrigin=eyJpIjoiNWRk …
=> WD-5991 - update /landscape page

templates/shared/forms/interactive/managed-observability.html
Remove fullName field and ass first&last name field on /observibility/managed contact-us form
https://docs.google.com/document/d/1i8PeYVXFbSZXnFqrHTDs7kyjwDPPfD97zXnkZKdlaDk/edit?disco=AAAANZSzF60&usp_dm=true#heading=h.a2otybczuqyf
https://warthogs.atlassian.net/browse/WD-6880
=> Remove fullName field and add first&last name field on /observibility/managed contact-us form

templates/shared/pricing/_openstack-packages.html
- Added link to https://ubuntu-com-13279.demos.haus/openstack/consulting according to [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit)
- [demo link](https://ubuntu-com-13279.demos.haus)
- Check whether the link is correct
[WD-6938](https://warthogs.atlassian.net/browse/WD-6938)
Fixes #
[WD-6938]: https://warthogs.atlassian.net/browse/WD-6938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> WD-6938 - add link to /openstack/consulting

templates/openstack/compare.html
- Update text and link in https://ubuntu-com-13280.demos.haus/openstack/compare according to [copydoc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit)
- [demo link](https://ubuntu-com-13280.demos.haus)
- Check whether text and link are correct
[WD-6939](https://warthogs.atlassian.net/browse/WD-6939)
Fixes #
[WD-6939]: https://warthogs.atlassian.net/browse/WD-6939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> WD-6939 - update text and link in /openstack/compare

templates/openstack/index.html
- Update link and text in https://ubuntu-com-13281.demos.haus/openstack according to [copydoc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit)
- [demo link](https://ubuntu-com-13281.demos.haus)
- Check whether link and text are correct
[WD-6935](https://warthogs.atlassian.net/browse/WD-6935)
Fixes #
[WD-6935]: https://warthogs.atlassian.net/browse/WD-6935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> WD-6935 - update link and text in /openstack

templates/legal/data-privacy/index.html
- Update cookie table at https://ubuntu-com-13277.demos.haus/legal/data-privacy according to [copydoc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit)
- [demo link](https://ubuntu-com-13277.demos.haus)
- Check the cookie table to be correct
[WD-6916](https://warthogs.atlassian.net/browse/WD-6916)
Fixes #
[WD-6916]: https://warthogs.atlassian.net/browse/WD-6916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> WD-6916 - add cells to the cookie table

templates/core/features/index.html, templates/core/index.html, templates/download/iot/intel-iot.html, templates/industrial/index.html
- Updated real-time links on /core, /download/iot, /core/features and /industrial
- https://ubuntu-com-13272.demos.haus/core -> [copy doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit#heading=h.ljeurx6cb36j), https://ubuntu-com-13272.demos.haus/download/iot -> [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit), https://ubuntu-com-13272.demos.haus/core/features -> [copydoc](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit#heading=h.gfn96hvf16o), https://ubuntu-com-13272.demos.haus/industrial -> [copydoc](https://docs.google.com/document/d/1QiU75g49lRKebt82oyLSxR3-PU96Sk87nqauAZ4vvIY/edit)
- Check out this feature branch [demo link](https://ubuntu-com-13272.demos.haus)
- …
=> WD-6860 - update real-time link

templates/contact-us/index.html
- Added security enquiries section to https://ubuntu-com-13285.demos.haus/contact-us
- [copydoc](https://docs.google.com/document/d/1LK7lJlhke8hKesVSglHxNSfUCDw0bfddzM4vezeXvBQ/edit)
- Check out this feature branch [demo link](https://ubuntu-com-13285.demos.haus/)
- Check security enquiries section according to copydoc
[WD-6948](https://warthogs.atlassian.net/browse/WD-6948)
Fixes #
[WD-6948]: https://warthogs.atlassian.net/browse/WD-6948?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> WD-6948 - add security section to /contact-us

requirements.txt
Bump canonicalwebteam.blog to 6.4.1
- Go to `/blog/people-and-culture` and check the page renders
- Navigate the blog in general and check there are no errors
=> Bump canonicalwebteam.blog to 6.4.1

templates/desktop/features.html
Fixed typo in desktop/features.html
Fixes #
=> Typo in desktop/features.html

requirements.txt
Bump canonicalwebteam.discourse to 5.4.5
- Go to `/tutorials/install-ubuntu-desktop-1804#1-overview` and check the tutorial renders.
=> Bump canonicalwebteam.discourse to 5.4.5

templates/aws/shared/_get_pro.html
- Updated links as per [doc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit)
- View the site locally in your web browser at: https://ubuntu-com-13322.demos.haus/aws
- Check against doc
Fixes  https://warthogs.atlassian.net/browse/WD-7091
=> Update aws pro links

templates/security/fips.html
- Updated the title and webinar link for the FIPS section based on [copydoc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit)
- Check that the demo is running at https://ubuntu-com-13323.demos.haus/security/fips
Fixes https://warthogs.atlassian.net/browse/WD-7071
=> Update FIPS title and webinar link

tests/test_views.py, webapp/views.py
- Shorten acquisition URLs on submitted forms as described by the task: [WD-6294](https://warthogs.atlassian.net/browse/WD-6294)
- The task is to ensure the acquisition URLs are not longer than 255 characters, if they are the `fbclid` and `gclid` parameters should be removed.
- Go to any page with a form and add any of these query parameters to the url: `?utm_source=facebook_ad&utm_medium=cpc&utm_campaign=7018e000000Lrr2AAC&fbclid=IwAR15h71YCzbtXmItLpTWGKvX6LGlbBNrsYAsoq-IEJiF9SYy_aDXgpsIqn0_aem_AbSMY4GVnRtIgih_p0mTaKvNZH6T3Qy73plm8KSqnZJXAsol_n1J440OjNsdU2s6-a0urWDolTPSE0nv3SYoY3jU` 
or 
`?utm_source=facebook_ad&utm_medium=cpc&utm_campaign=7018e000000Lrr2AAC&gclid=IwAR15h71YCzbtXmItLpTWGKvX6LGlbBNrsYAsoq-IEJiF9SYy_aDXgpsIqn0_aem_AbSMY4GVnRtIgih_p0mTaKvNZH6T3Qy73plm8KSqnZJXAsol_n1J440OjNsd …
=> fix: shorten form acquisition URLs - WD-6294

templates/download/amd/tab-2.html
- Changed asset in the second tab in https://ubuntu-com-13330.demos.haus/download/amd
- [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit#heading=h.9lw1gwsuva2l)
- [demo link](https://ubuntu-com-13330.demos.haus/)
- Check whether the asset is correct
[WD-7093](https://warthogs.atlassian.net/browse/WD-7093)
Fixes #
[WD-7093]: https://warthogs.atlassian.net/browse/WD-7093?atlOrigin=eyJpIjoiNWRkN …
=> WD-7093 - change asset in /download/amd

templates/kubernetes/docs/autoscaler.md, templates/kubernetes/docs/high-availability.md
- Replace diagrams which reference 'master'
- reword sections of HA docs
- small change for autoscaler page
=> K8s update HA page

templates/kubernetes/docs/explain-backups.md, templates/kubernetes/docs/shared/_side-navigation.md
- Added a page explaining the backup strategy for Kubernetes
=> K8s docs - Add backups strategy page

templates/kubernetes/docs/get-in-touch.md, templates/kubernetes/docs/how-to-contribute.md, templates/kubernetes/docs/shared/_side-navigation.md
- Adds new page for contributing
- Adds link for this to the get-in-touch page
- Adds Mattermost channel details
- Update the navigation accordingly
- Also follows request to use &hellip; in nav
=> K8s docs - Add contributing page and links

templates/kubernetes/docs/1.21/upgrading.md, templates/kubernetes/docs/index.md
- fixes two broken links and a typo
- 
=> K8s link fixes

templates/templates/navigation-enterprise-h.html, webapp/shop/cred/views.py
Removed a link to a non-existent page
- Go to https://ubuntu-com-13335.demos.haus/#enterprise
- Check that there is no "Juju experts" link in the "Consulting" row at the bottom of the menu
=> Remove dead link to jaas.ai/experts

requirements.txt, templates/download/iot/index.html
Added Mediatek logo and link to "Supported Platforms" section according to [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#heading=h.kqw4j3f3aj61)
- Navigate to /download/iot and check the "Supported platforms" section if it has Mediatek
- Check the layout of the section on different screen widths 
Closes https://warthogs.atlassian.net/browse/WD-7080
=> [WD-7080] add Mediatek to supported platforms on IoT page

static/js/src/dynamic-forms.js, webapp/shop/cred/views.py
- Remove unused GA events from dynamic-form.js as it is not registering in google analytics
Fixes #
=> Remove unused GA events from dynamic-form.js

templates/pricing/consulting.html
- Updated the download link in https://ubuntu-com-13337.demos.haus/consulting
- [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#heading=h.xv4ec899rw2v)
- [demo link](https://ubuntu-com-13337.demos.haus/)
-  Check download link to be correct
[WD-7158](https://warthogs.atlassian.net/browse/WD-7158)
Fixes #
[WD-7158]: https://warthogs.atlassian.net/browse/WD-7158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> WD-7158 - update link on /consulting

templates/kubernetes/docs/1.28/release-notes.md, templates/kubernetes/docs/release-notes.md
- Update release notes for 1.28+ck2
=> Kubernetes 1.28+ck2 updates

.github/workflows/rebase.yaml
- Add an automatic rebase ability to make it quicker to rebase when you need to apply latest changes from the main branch to your local branch. More details about the tool can be found [here](https://github.com/marketplace/actions/automatic-rebase).
TBH I'm not sure how this can be tested before merging it. 
After we merge it though, you can push your local branch to GH, create a PR and then type `/rebase` in the comments. This will trigger an automatic action to rebase your local branch. 
There is no issue, I just pushed it as a chore.
=> add rebase command to GH actions

templates/download/iot/index.html
- Squeeze Mediatek logo in "Supported platforms" section of /download/iot page
- Navigate to /download/iot, scroll down to "Supported platforms" section and check Mediatek logo if it has same dimension ratio as in the original logo [here](https://assets.ubuntu.com/v1/0ebb345c-MediaTek_logo.svg).
Fixes https://warthogs.atlassian.net/browse/WD-7080
=> [WD-7080] squeeze Mediatek logo a bit

ARCHITECTURE.md, README.md
- Updated some links in docs in README and ARCHITECTURE.
- Tackles part of the links reported in #13332 
Fixes #13332
=> fix(docs): update links in the documentation.

templates/contact-us/index.html, templates/shared/_cloud-contact-us-form.html, templates/shared/_pro-contact-us-form.html
- Removed phone numbers from the following pages:
- /contact-us
- /contact-us/form
- /<product>/contact-us, where <product> is one of:
- openstack
- support
- kubernetes
- security
- wsl
- managed
- containers
- download
- Check all the pages listed above ("Done" section) if the phone numbers do now show there anymore
Fixes https://warthogs.atlassian.net/browse/WD-7202
=> [WD-7202] remove support phone numbers

templates/templates/_vwo_smartcode.html, templates/templates/base.html
- Added VWO smartcode script to base template's head element. This way this script should be enabled globally for the whole website.
- Check all pages if they don't break
- Check if VWO smartcode functionality is working
Fixes https://warthogs.atlassian.net/browse/WD-7085
=> [WD-7085] add VWO smartcode script to base template's head

redirects.yaml
- Add redirect from /blog/howto-host-your-own-snap-store to /internet-of-things/appstore
- Navigate to /blog/howto-host-your-own-snap-store and check if it redirects to /internet-of-things/appstore
Fixes https://warthogs.atlassian.net/browse/WD-7314
=> [WD-7314] add a redirect from a blog post to another page

.github/workflows/rebase.yaml
- Apparently in order to be able to automatically re-run GH actions after a rebase command using a `/rebase` comment in PRs, we need to use a PAT that has `workflow` permission. The default GITHUB_TOKEN token doesn't have that permission and therefore GH actions fail.
- Created a PAT called `REBASE_TOKEN` with `workflow` permission in my settings. Whoever wants to use this command will need to add that PAT as well.
- Add `/rebase` comment to your PR and check GH actions that are triggered after that. They should succeed.
[QA …
=> use REBASE_TOKEN that has workflow permission for automatic rebase

templates/engage/shared/_en_engage_form.html
Add option to add partner's permission checkbox. This will dynamically add the checkbox if the engage page author adds the `partners_permission` to `true` in the [discourse engage page](https://discourse.ubuntu.com/t/event-the-future-of-telcom-edge-computing-intel-canonical-france-event/40069).
- Go to https://ubuntu-com-13349.demos.haus/engage/canonical-intel-telco-france-event check that partner's permission checkbox is there
Fixes https://warthogs.atlassian.net/browse/WD-6440
=> Add partner permission checkbox to engage pages

templates/shared/_pro-contact-us-form.html
- Updated contact us form for Pro
- Go to `/contact-us/form?product=pro`
- Renamed "LTS during extended support" to "LTS out of standard support"
- 18.04 is moved to “LTS during extended support”
[WD-6901](https://warthogs.atlassian.net/browse/WD-6901)
[WD-6901]: https://warthogs.atlassian.net/browse/WD-6901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update pro contact form

static/sass/styles.scss, templates/download/desktop/thank-you.html, templates/templates/_tag_manager.html, templates/templates/base.html
- Updated the first section in https://ubuntu-com-13353.demos.haus/download/desktop/thank-you
- [copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit)
- [demo link](https://ubuntu-com-13353.demos.haus/)
-  Check the first section on page
[WD-6807](https://warthogs.atlassian.net/browse/WD-6807)
Fixes #
[WD-6807]: https://warthogs.atlassian.net/browse/WD-6807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> WD-6807 - update /thank-you page, banner issue

templates/cloud/public-cloud.html
Few content changes from the [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit):
- Removed "View all certified public cloud partners" link
- Replaced link and text for Launch Ubuntu for Azure in "Ready to get started?" section
- Navigate to /cloud/public-cloud page and check if the above mentioned changed have been applied
Fixes https://warthogs.atlassian.net/browse/WD-6717
=> [WD-6717] remove one link and replace another one according to copy doc

templates/download/server/manual.html
- Go to /download/server
- Inspect the download button have the version in the GA event label now
Fixes https://github.com/canonical/ubuntu.com/issues/13274
Fixes https://warthogs.atlassian.net/browse/WD-7403
=> WD-7403 - Add the version of the server download GA event label

webapp/app.py, webapp/security/views.py
- Fixed false 500 when user tries to visit a notice with an incomplete id which matches an existing template name
Notices can have one of two prefixes: usn or lsn. When you visit `/security/notices` and click on any given notice in the list, the template that gets triggered is `/notices/lsn.html` or `/notices/usn.html`, respectively. This bug came about because we had some users try to visit `/security/notices/usn` which, because we actually do have a template with that name and we did not have a rule in place for it, was causing jinja errors. This PR changes the behavior so that when a user tries to visit `/security/notices/<prefix>` it correctly shows 404. 
- View the site locally in your web browser at: https://ubuntu-com-13361.demos.haus/security/notices/lsn
- See that you get 404
- …
=> Fix notice prefix error

templates/shared/_ubuntu_pro_on_public_cloud.html
- Updated AWS link in https://ubuntu-com-13363.demos.haus/download/cloud
- [copy doc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit)
- [demo link](https://ubuntu-com-13363.demos.haus/)
-  Check that the link is correct
[WD-7467](https://warthogs.atlassian.net/browse/WD-7467)
Fixes #
[WD-7467]: https://warthogs.atlassian.net/browse/WD-7467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-7467 - update aws link for cloud download

static/js/src/dynamic-forms.js, templates/shared/contextual_footers/_download_iot_iotg_newsletter.html
- When multiple forms are present in a page, update the UTMs based on which form is opened by using the form id to grab the target form first
- Flyby change: Make the email field in newsletter signup required
- Check out https://ubuntu-com-13370.demos.haus/download/contact-us?utm_source=google&utm_medium=cpc&utm_campaign=701N1000004GoRgIAK&utm_term=CustomIIOT&utm_content=YTvideo
- make sure the UTMs passed in the URL are present in the forms payload
Fixes https://warthogs.atlassian.net/browse/WD-7550
=> When multiple forms are present in a page, update the UTMs based on which form is opened

templates/download/desktop/thank-you.html
- Make the "I agree to receive information about Canonical’s products and services." checkox under e-mail address input field required for submitting an email. This is coming from [here](https://warthogs.atlassian.net/browse/WD-6669?focusedCommentId=344652).
- Navigate to /download/desktop/thank-you page, fill in your email address and click on "Subscribe now" button. It should ask you to check the checkbox as well.
Fixes https://warthogs.atlassian.net/browse/WD-7552 …
=> [WD-7552] make the checkbox on Thank You page mandatory to comply with GDPR

redirects.yaml
- Redirect EdgeX tutorial at `/tutorials/get-started-with-edgex-as-snaps` to IoT landing page at `/internet-of-things`
- Navigate to `/tutorials/get-started-with-edgex-as-snaps` and check that it redirects to `/internet-of-things`
Fixes https://warthogs.atlassian.net/browse/WD-7240
=> [WD-7240] redirect EdgeX tutorial page to the IoT landing page

templates/internet-of-things/smart-displays.html
- Fixed contact us link in https://ubuntu-com-13373.demos.haus/internet-of-things/smart-displays
- [copy doc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit#heading=h.odnh1uuyfmr1)
- [demo link](https://ubuntu-com-13373.demos.haus/)
-  Check that the link is correct
[Wd-7575](https://warthogs.atlassian.net/browse/WD-7575)
Fixes #
=> WD-7575 - update contact us link on iot smart displays

templates/real-time/index.html
- Added images in https://ubuntu-com-13359.demos.haus/real-time
- [figma design](https://www.figma.com/file/Cr1S07Ivk632jniBAG89S8/23.10-U.com---Real-time-Ubuntu?type=design&node-id=0-1&mode=design&t=QcxshpHOoI7PE0oV-0)
- [demo link](https://ubuntu-com-13359.demos.haus/)
-  Check that images and text are correct
[WD-7205](https://warthogs.atlassian.net/browse/WD-7205)
Fixes #
[WD-7205]: https://warthogs.atlassian.net/browse/WD-7205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-7205 - enrich /real-time page with images

static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
Remove description under product type physical on pro subscribe form.
- View the site locally in your web browser at: http://0.0.0.0:8001/pro/subscribe
- When you select "Physical servers with unlimited VMs" there is no help text under the option.
=> Remove description under product type physical on pro subscribe form.

static/js/src/navigation.js, webapp/app.py
- Updates the ids the GA events attach to
- Add a hash in the url (ubuntu.com/#products) depending on where in the navigation you are. This only applies to top level items.
Fixes https://warthogs.atlassian.net/browse/WD-7400
=> Update GA tracking and a location hash in the URL

templates/confidential-computing/index.html
- Add new sections in https://ubuntu-com-13376.demos.haus/confidential-computing
- [copy doc](https://docs.google.com/document/d/1QGwS5CYlwXkaPibSFvcag6zLcUH5lNDUbM18hCqbOJM/edit)
- [Figma wireframe](https://www.figma.com/file/zyG3Iyys2GlxxfqfQQT7bT/23.10-U.com---Confidential-computing?type=design&node-id=1-5002&mode=design&t=h2Hfzx7x9MKfXpRv-4)
- [demo link](https://ubuntu-com-13376.demos.haus/)
-  Check two new added sections
Fixes # [WD-7492](https://warthogs.atlassian.net/browse/WD-7492)
[WD-7492]: https://warthogs.atlassian.net/browse/WD-7492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> WD-7492 - add new section to /confidential-computing

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
- Fix the broken `Ubuntu Pro network requirements` link
- Click on `Ubuntu Pro network requirements` and it should redirect to the correct page
Fixes [WD-6499](https://warthogs.atlassian.net/browse/WD-6469)
[WD-6499]: https://warthogs.atlassian.net/browse/WD-6499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix broken network requirements link

navigation.yaml, templates/containers/chiselled/_base_chiselled.html, templates/containers/chiselled/index.html
[Copy doc](https://docs.google.com/document/d/1ZkQ-UFTwsPkMnQn8IEEjZOXMy40tkgBscw_-qq9K3nc/edit)
[Figma design](https://www.figma.com/file/YfNc8KmYqa2e7JgbFo6lXa/24.04-U.com---%2Fcontainers?type=design&node-id=96-2890&mode=design&t=B0iQTEU59HoXl9go-4)
- Add new page for Chiselled Ubuntu at `/containers/chiselled`
- Add `Chiselled Ubuntu` and `Chiselled and .NET` to navigation of `/containers`
- Existing `/containers/chiselled/dotnet` page opens from `Chiselled and .NET` navigation item
- New `/containers/chiselled` page opens from `Chiselled Ubuntu` navigation item
This PR does not contain the chart (horizontal bar chart) and the table/image from `Why use Chiselled Ubuntu containers` section, it will be delivered in a separate ticket
- Run the site using …
=> [WD-7268] add landing page for Chiselled Ubuntu without the chart and a table

templates/gcp/fips.html
- Fix typo in https://ubuntu-com-13387.demos.haus/gcp/fips
- [copy doc](https://docs.google.com/document/d/17Rr6Fdrr7xSPi1g2h7GMTztQUGYqz2hdbNUqK0uQihw/edit#heading=h.c6wjbvvp8mcm)
- [demo link](https://ubuntu-com-13387.demos.haus/)
-  Check the ubuntu version is correct
Fixes # [WD-7769](https://warthogs.atlassian.net/browse/WD-7769)
[WD-7769]: https://warthogs.atlassian.net/browse/WD-7769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-7769 - fix typo in gcp fips

templates/robotics/index.html
Updated buttons in "Bringing Ubuntu’s worldwide infrastructure to your robot" section in https://ubuntu-com-13390.demos.haus/robotics
- [demo link](https://ubuntu-com-13390.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1JNFk2C0shH3DapKuJM8X0QfAiD1RzHvXoydn8P9mEMg/edit#heading=h.fdlzz3sruhkt)
- Check that the buttons and links on them are correct
[WD-7771](https://warthogs.atlassian.net/browse/WD-7771)
Fixes #
[WD-7771]: https://warthogs.atlassian.net/browse/WD-7771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
=> WD-7771 - update buttons in /robotics

webapp/views.py
- Updated the blog redirection logic to append URL params.
- Go to https://ubuntu-com-13381.demos.haus/blog/chiselled-ubuntu-ga?utm_source=marketo&utm_medium=email&utm_campaign=newsletter-2023-48
- Ensure you are redirected to the Canonical blog
- Ensure UTMs from the original URL are still there
=> Pass along UTMs when doing a blog redirect

build.js, navigation.yaml, static/js/src/charts/chiselled-chart.js, templates/containers/chiselled/_base_chiselled.html, templates/containers/chiselled/index.html
- Landing page for chiselled Ubuntu
- Navigate to /containers/chiselled
Fixes https://warthogs.atlassian.net/browse/WD-7064
=> [WD-7064] Chiselled ubuntu

templates/confidential-computing/index.html
- Update image in "Intel TDX is available on Ubuntu for both the host and guest" section according to [copy doc](https://docs.google.com/document/d/1QGwS5CYlwXkaPibSFvcag6zLcUH5lNDUbM18hCqbOJM/edit).
- Navigate to /confidential-computing and check if the image has been updated and corresponds to the one specified in the copy doc.
Fixes https://warthogs.atlassian.net/browse/WD-7905
=> [WD-7905] update image on /confidential-computing page

templates/security/cve/index.html, webapp/security/helpers.py, webapp/security/views.py
- Added redesign as per [mock-up](https://www.figma.com/file/nUJEBpOPTW74RqDRuMQXxB/23.04-U.com---CVEs?node-id=949%3A22802&mode=dev)
The releases links will be handled in a separate PR, as will the advanced search link.
- View the site locally in your web browser at: https://ubuntu-com-13382.demos.haus/security/cves
- See that the page matches the design
Fixes https://warthogs.atlassian.net/browse/WD-5145
=> CVEs landing page redesign

templates/pricing/pro.html
- Update copy docs for pro pricing page
- Go to `/pricing/pro`
Fixes [WD-7929](https://warthogs.atlassian.net/browse/WD-7929)
[WD-7929]: https://warthogs.atlassian.net/browse/WD-7929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update copy docs for pro pricing

templates/ceph/install.html
- Fix `<section>` typo
Fixes #
=> Fix typo in ceph/install

templates/internet-of-things/index.html
Added missing images to /internet-of-things page
- [demo link](https://ubuntu-com-13392.demos.haus/internet-of-things)
- [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.arqqr1uv66j6)
- Check that images on /internet-of-things page are correct
[WD-7757](https://warthogs.atlassian.net/browse/WD-7757)
Fixes #
[WD-7757]: https://warthogs.atlassian.net/browse/WD-7757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-7757 - add missing images to /internet-of-things

templates/legal/data-privacy/partner-portal.md, templates/legal/partner-portal-terms.md
- Add changes to content in /legal/partner-portal-terms according to [copy doc](https://docs.google.com/document/d/1CqJbwC3KpEJeJaCUVjAIN0y6ZLmoc7gVlFyc-BeFMYw/edit)
- Add changes to content in /legal/data-privacy/partner-portal according to [copy doc](https://docs.google.com/document/d/1yuh7dL3jjkj21sKJCUhm_z00PKzH4vssY339wbp4U-s/edit#heading=h.2dlolyb)
Demo links to pages:
https://ubuntu-com-13413.demos.haus/legal/partner-portal-terms
https://ubuntu-com-13413.demos.haus/legal/data-privacy/partner-portal 
- Navigate to above mentioned pages and check the changes
Fixes …
=> [WD-7973] add small chages to content of legal pages for partner portal

templates/confidential-computing/index.html
- Replaced an image on /confidential-computing page according to [copy doc](https://docs.google.com/document/d/1QGwS5CYlwXkaPibSFvcag6zLcUH5lNDUbM18hCqbOJM/edit)
- Check if the new image is shown on the page, specifically if the typo "Ubuntu Kernal" is replaced with "Ubuntu Kernel".
Fixes https://warthogs.atlassian.net/browse/WD-7975
=> [WD-7975] replace image with a typo in /confidential-computing

requirements.txt, static/js/src/certified-search-results.js, tests/cassettes/TestCertification.test_filters_json.yaml, webapp/certified/views.py, webapp/handlers.py
- Parse query params for /certified
- Clean up code
- Fix filters not reloading on category pages when first hitting the page (changes in .js file)
- Check https://ubuntu-com-13405.demos.haus/certified/laptops?q=&category=Laptop&release=Core+22%22%3E%3Ciframe+onload%3Dalert%28%27REDACTED%27%29%3E&release=Core+20&release=Core+18&release=Core+22 this shouldn't open the alert window
- Do the same for [this one](https://ubuntu.com/certified/laptops?q=&category=Laptop&release=Core+22%22%3E%3Ciframe%20onload=%22javascript:document.body.innerHTML%20=%20atob(%27PGRpdiBjbGFzcz0icC1tb2RhbCIgaWQ9Im1vZGFsIj4gPHNlY3Rpb24gY2xhc3M9InAtbW9kYWxfX2RpYWxvZyIgcm9sZT0iZGlhbG9nIiBhcmlhLW1vZGFsPSJ0cnVlIiBhcmlhLWxhYmVsbGVkYnk9Im1vZGFsLXRpdGxlIiBhcmlhLWRlc2NyaWJlZGJ5PSJtb2RhbC1kZXNjcmlwdGlvbiI%2BIDxoZWFkZXIgY2xhc3 …
=> Parse query params for /certified

.github/.jira_sync_config.yaml
- Added a config file that will integrate GH with Jira so that new GH issues will automatically create tasks in Jira. This is done in a similar way as it is done in canonical.com: https://github.com/canonical/canonical.com/blob/main/.github/.jira_sync_config.yaml
Can be QA-ed only after merging since to test it you need a new GH issue or you need to close and re-open an existing one. 
Fixes https://warthogs.atlassian.net/browse/WD-8000
=> [WD-8000] add Jira integration config file

navigation.yaml, templates/telco/osm/index.html, templates/telco/shared/_telco-logo-section.html
Update [OSM](https://ubuntu-com-13421.demos.haus/telco/osm) page according to copy doc
- [demo link](https://ubuntu-com-13421.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1LQim0WRVdDZE9-ToFKSD52O7kgurMoytrgDDAPYnug8/edit#heading=h.xrvnk0etn33s)
- Check that links and text are correct according to copy doc
[WD-7790](https://warthogs.atlassian.net/browse/WD-7790)
Fixes #
[WD-7790]: https://warthogs.atlassian.net/browse/WD-7790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-7790 - uptade /telco/osm page

templates/templates/docs/shared/_docs.html
For documentation generated from Discourse
- updated the _Last updated_ footer to now read _This page was last modified_.
Fixes an issue where visitors to a documentation landing page might assume none of the documentation pages have been updated since the _Last updated_ text (when this is only referencing the index page).
cc @petesfrench
=> Replaced Last updated text to fix potential ambiguity.

templates/ai/roadshow.html
Update link and text in [roadshow](https://ubuntu-com-13429.demos.haus/ai/roadshow) page
- [demo link](https://ubuntu-com-13429.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1CA0GUU6yRB65yfDaKi1dgN8DED2bDAFI2h-swSVtMtg/edit)
- Check that links and text are correct according to copy doc
[WD-8006](https://warthogs.atlassian.net/browse/WD-8006)
Fixes #
[WD-8006]: https://warthogs.atlassian.net/browse/WD-8006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-8006 - update link in /ai/roadshow

templates/ai/index.html
- Add a space to the link text
- Encoded the spaces in the URL
- Check this change fixes this request: https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit?usp=drivesdk&disco=AAABDo70EZw
=> Fix typo in MLOps datasheet link

static/js/src/chart-data.js, templates/about/release-cycle.html, templates/about/release_cycles/openstack-eol.html
OpenStack 2023.2 is a non-SLURP which means users can upgrade from 2023.1 to 2023.3 without going through 2023.2. Therefore, 2023.2 will only be supported for 9 months.
Fixes #13239
=> Update OpenStack 2023.2 EOL to 9 months

templates/legal/data-privacy/index.html, templates/legal/data-privacy/support-portal.md, templates/legal/terms-and-policies/index.html, templates/legal/terms-and-policies/support-portal.md
- Add a Data Privacy and a Terms and Policies pages for Support Portal according to the following copy docs:
- https://docs.google.com/document/d/1x8vH0dabSF7en7KenZKKDlugFHjbKwtdonuKPbQUDiM/edit
- https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit
- https://docs.google.com/document/d/1ugZ-7R6qSYSKjofiPicy444c5zXho81J3Z_f-hpCcZc/edit
- https://docs.google.com/document/d/1p3ZWroZ3nkw8XJJdPvPxSlWGYcLZLT8UbUVuppBcyHk/edit
- Navigate to https://ubuntu-com-13426.demos.haus/legal/data-privacy and check if it has a new link that takes to Support …
=> [WD-7913] support portal legal pages

templates/legal/ubuntu-pro/index.html
- Bring back accidentally removed /legal/ubuntu-pro page
- Check if a page at /legal/ubuntu-pro exists and opens fine
Fixes https://warthogs.atlassian.net/browse/WD-8132
=> [WD-8132] bring back accidentally removed /legal/ubuntu-pro page

static/js/src/cve/cve.js, templates/security/cve/index.html, webapp/security/views.py
- Added links to filtered releases
- View the site locally in your web browser at: https://ubuntu-com-13425.demos.haus/security/cves
- Click each "By Ubuntu release" link and see that each shows the expected filtered table (styling updates to this list to come in a later PR)
Note: "Other releases" should just be the unfiltered CVE list, the table should match the current version with exception of 24.04
Fixes #https://warthogs.atlassian.net/browse/WD-7802
=> Update release links

templates/pro/attach/index.html, webapp/shop/advantage/views.py
- Added magic-attach-code as query param for /pro/attach
- Visit /pro/attach?magic-attach-code=<some code>
- Also ensure it works with default subscription selected
Fixes [#WD-8076](https://warthogs.atlassian.net/browse/WD-8076)
=> Wd 8076 add magic attach code as query param in pro attach

redirects.yaml, templates/robotics/community.html, webapp/context.py
- Replaced links in places where it was outputting 404 or 500. Used a [daily automated job](https://github.com/canonical/ubuntu.com/actions/workflows/live-links.yaml)'s output as a source of truth.
- Check that https://ubuntu-com-13451.demos.haus/server/docs/virtualization-introduction doesn't output 404
- Check that `More info about the TSC` link on https://ubuntu-com-13451.demos.haus/robotics/community opens a ROC2 page and doesn't output 404.
- Check that https://ubuntu-com-13451.demos.haus/iot/gateways doesn't output 500 and opens a page.
Fixes https://warthogs.atlassian.net/browse/WD-8151
[QA …
=> [WD-8151] fix broken links

requirements.txt, static/js/src/core.js, static/js/src/navigation.js, static/sass/_pattern_navigation.scss, templates/templates/meganav/base.html
This work addressed the following comments:
Keyboard navigation: focus after last link in dropdown
When we open, e.g., "Products", and then select a tab on the left sidebar, e.g. "Ubuntu OS", and then tab through all the links until the end, hitting tab after the last link on the right closes the dropdown and moves the focus to the next item on the top navigation (in this case "Use cases"). This is correct and the [intended behaviour](https://warthogs.atlassian.net/browse/WD-7516?focusedCommentId=349710).
However, when we open, e.g., "Products" and then tab through all the links without selecting a tab on the left sidebar, hitting tab after the last link on the right moves the focus past the whole navigation into the content, with the navigation remains open. The behaviour here should be …
=> Adds keyboard trapping for mobile

templates/engage/base.html
TL:DR;
Make paragraphs full width. Following [this discussion](https://chat.canonical.com/canonical/pl/77oyc3561ff5um3gjuiksgyash)
We already have the option to take [full width in Vanilla](https://vanillaframework.io/docs/base/typography#line-length) so design-wise this is ok to do, also the lists already take the full width, so there is no point keeping the 40em default width for paragraphs only, both stakeholders and I agree that it looks like a lot of useless space on the right, when there is no form. But in the case of engage pages, because the paragraphs are generated in Discourse, I can't add the classname to every single `p`. So I extended the same classname for wide use in engage pages. I'm all ears if you can think of a better option.
- Check an engage page that doesn't have a …
=> Limit width of list items

.github/workflows/live-links.yaml, templates/robotics/what-is-ros.html
- Replaced link in https://ubuntu-com-13460.demos.haus/robotics/what-is-ros according to [copy doc](https://docs.google.com/document/d/1yX2Ikcn1fgIKX3el8fKWQt7SGxSwY633TfW5V1lwUuc/edit)
- Added a link to ZoomInfo Privacy Policy page to ignore list of `check-links` GH action, because it's weirdly returning 403 when requesting through cURL (suggested by Ant [here](https://chat.canonical.com/canonical/pl/yi3ub35a138p5ba3n65fddr7eh))
- Navigate to https://ubuntu-com-13460.demos.haus/robotics/what-is-ros and click on `Get started with ROS 2` button. It should open a tutorial …
=> [WD-8235] replace a link in /robotics/what-is-ros
