static/js/src/advantage/offers/components/Offer/Offer.test.tsx
static/js/src/advantage/offers/components/Offer/Offer.tsx
static/js/src/advantage/offers/tests/factories/offers.ts
static/js/src/advantage/offers/types.ts
webapp/shop/api/ua_contracts/models.py
webapp/shop/api/ua_contracts/parsers.py

This PR is opened again as this [PR](https://github.com/canonical/ubuntu.com/pull/12525) has been closed when new checkout was released.
- Display offer discount
- Go to /pro/offers
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-1917

Display offer discount

---

templates/security/certifications.html
templates/security/index.html
templates/security/livepatch.html

Replace logos
- Check /security has the [new image](https://warthogs.atlassian.net/browse/WD-1728?atlOrigin=eyJpIjoiZGE4ODUzYmY2NTNiNDVmZTg5YTAxNDE3OGI0MTcwOWQiLCJwIjoiaiJ9)
- Check /security/livepatch has the [new image](https://warthogs.atlassian.net/browse/WD-1727?atlOrigin=eyJpIjoiZWFiMGY4ZDRiNTI5NDAwMDhhOTE2ZmVjYTkyZTkxMDEiLCJwIjoiaiJ9)
- Check /security/certifications has the [new image](https://warthogs.atlassian.net/browse/WD-1728?atlOrigin=eyJpIjoiYjQwZDJhZGNkZWIyNDA3ZGE1ZmY3MzAzZTE4YmU1NDQiLCJwIjoiaiJ9)
Closes https://warthogs.atlassian.net/browse/WD-1728?atlOrigin=eyJpIjoiYjQwZDJhZGNkZWIyNDA3ZGE1ZmY3MzAzZTE4YmU1NDQiLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1727?atlOrigin=eyJpIjoiZWFiMGY4ZDRiNTI5NDAwMDhhOTE2ZmVjYTkyZTkxMDEiLCJwIjoiaiJ9
Closes …

WD-1726 WD-1727 WD-1728  Replace logos

---

templates/credentials/index.html
templates/credentials/syllabus.html

- Update copy on /credentials (use QuickCert terminology)
- Visit https://ubuntu-com-12626.demos.haus/credentials
- Verify copy
- Visit https://ubuntu-com-12626.demos.haus/credentials/syllabus
- Verify that "microcertifications" is replaced with "QuickCerts"

Update copy for /credentials.

---

templates/ai/index.html
templates/ai/services.html
templates/ai/what-is-kubeflow.html
templates/shared/_charmed-kubeflow-beta-banner.html
tests/test_context.py
webapp/app.py
webapp/context.py

Add Kubeflow beta banner, [as per request](https://docs.google.com/document/d/19_9cUiyjxWXPvLaZc0_DOglsCQwlJFW8gET7sZt7IYI/edit)
- Check banner shows on
https://ubuntu-com-12620.demos.haus/ai 
https://ubuntu-com-12620.demos.haus/ai/what-is-kubeflow 
https://ubuntu-com-12620.demos.haus/ai/services
Fixes https://warthogs.atlassian.net/browse/WD-2205?atlOrigin=eyJpIjoiNmE0MzhkYmY1MmIxNDg3Y2FiZmM0MGYzMWEyYTkxMDgiLCJwIjoiaiJ9

WD-2205 Kubeflow 1.7 beta banner

---

templates/kubernetes/kubernetes-operations-survey.html

Copy update
- Check https://ubuntu-com-12636.demos.haus/kubernetes/kubernetes-operations-survey against [copy docs](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit)
Fixes https://warthogs.atlassian.net/browse/WD-2360?atlOrigin=eyJpIjoiMWNhZTUxMDlhNzJhNGM4MTgwNTg1ZDg5YjY0MzlmNTkiLCJwIjoiaiJ9

WD-2360 copy update

---

templates/nvidia/index.html

Update text according to [copy docs](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit)
- Check text [is updated](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#heading=h.1ksv4uv) on https://ubuntu-com-12635.demos.haus/nvidia
Fixes https://warthogs.atlassian.net/browse/WD-2408?atlOrigin=eyJpIjoiOGJiNWJjZDRkNzg5NDg0OGIxNGU5ZTdlNzc2ZDIyNDgiLCJwIjoiaiJ9

WD-2408 Ubuntu and Bluefield description update

---

redirects.yaml

Redirect /engage/openstack-made-easy to /engage/openstack-ebook
- Redirect https://ubuntu-com-12634.demos.haus/engage/openstack-made-easy to https://ubuntu-com-12634.demos.haus//engage/openstack-ebook
Fixes https://warthogs.atlassian.net/browse/WD-2362?atlOrigin=eyJpIjoiYTBlZjAzZmQxNWZmNGJlOGEwZDUyNjNmNzgxNzQ5MGMiLCJwIjoiaiJ9

WD-2362 Redirect engage page

---

templates/landscape/index.html

Copy update
- Check https://ubuntu-com-12622.demos.haus/landscape against [copy doc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit#heading=h.fmc57n38rjz9)
Fixes https://warthogs.atlassian.net/browse/WD-2337?atlOrigin=eyJpIjoiNDNmNzY4YzgyZDQxNDcwMDhmY2MzZGYwOWIzN2Q5NTUiLCJwIjoiaiJ9

WD-2337 Update /landscape page

---

templates/raspberry-pi/server.html

- Update logos on /raspberry-pi/server based on [this issue](https://warthogs.atlassian.net/browse/WD-1719)
- Fly-by changes on the page
- Update [illustrations library](https://docs.google.com/presentation/d/1FzVC4VpQ1oQTy3YUJ8SSNd5rutjr_yT7RoQ6Pe6JMpc/edit#slide=id.g6f6b77450_5_1)
- Go to raspberry-pi/server and check the logo in the header matches the on in the issue
- Make sure all large images are hidden on smaller screens
Fixes https://warthogs.atlassian.net/browse/WD-1719

Update logos on /raspberry-pi/server

---

navigation.yaml
static/sass/styles.scss
templates/cloud/cloud-computing.html

Build new /cloud/cloud-computing page
- Check https://ubuntu-com-12598.demos.haus/cloud/cloud-computing
- Compare with [copy docs](https://docs.google.com/document/d/1wx6pgPFq0qQLG-z5DsvNvqnFkyqjj7Oo0y9aemklycQ/edit#heading=h.39epm7m9taa2)
- Compare with [UX design](https://www.figma.com/file/VLfulegqAszHXlJRabBvsi/23.04-Ubuntu.com---%5BWD-1312%5D-u.c%2Fcloud%2Fcloud-computing?node-id=1%3A413&t=lijEmly7OS2JGwD7-0) plus [Visual design review](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=1538%3A4840&t=YvOhEb2CGg30XJCl-0)
In case where there are discrepancies between design and copy docs, text of copy docs should prevail.
Fixes https://warthogs.atlassian.net/browse/WD-1315 …

WD-1315 Cloud-computing page

---

templates/landscape/install.html

- Update copy on /landscape/install based on [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit)
- Go to https://ubuntu-com-12646.demos.haus/landscape/install and compare against the [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit)
Fixes https://warthogs.atlassian.net/browse/WD-2412

Update copy on /landscape/install

---

templates/edge-computing/index.html

- Update copy on /edge-computing based on [copydoc](https://docs.google.com/document/d/1DdOhFZyvaew0NWW2Uo-EtaB81wzCy-ApdRmanTinyVM/edit)
- Go to https://ubuntu-com-12648.demos.haus/edge-computing and compare against the [copydoc](https://docs.google.com/document/d/1DdOhFZyvaew0NWW2Uo-EtaB81wzCy-ApdRmanTinyVM/edit)
Fixes https://warthogs.atlassian.net/browse/WD-2367

Update copy on /edge-computing

---

templates/core/features/index.html
templates/core/index.html
templates/core/services/index.html

Replace logos for /core pages
Check:
- https://ubuntu-com-12641.demos.haus/core [new images](https://warthogs.atlassian.net/browse/WD-1720?atlOrigin=eyJpIjoiZGQyNmVmZGRiOWIxNGViNWFiMzgzMGI5MzhlNjlkNGUiLCJwIjoiaiJ9)
- https://ubuntu-com-12641.demos.haus/core/services [new images](https://warthogs.atlassian.net/browse/WD-1721?atlOrigin=eyJpIjoiZWIyMjY4MDVjNTYwNDRlNThmNGU2MThjNTY1YTEwMzciLCJwIjoiaiJ9)
- https://ubuntu-com-12641.demos.haus/core/features [new images](https://warthogs.atlassian.net/browse/WD-1722?atlOrigin=eyJpIjoiMTIyZThlNzY3NDhjNGUyZWE0M2Q0NTM2YmM0MDdmMTkiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1721?atlOrigin=eyJpIjoiZWIyMjY4MDVjNTYwNDRlNThmNGU2MThjNTY1YTEwMzciLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1720?atlOrigin=eyJpIjoiZGQyNmVmZGRiO …

WD-1721 WD-1720 WD-1722 Replace logos for /core pages

---

package.json
static/sass/_pattern_dell.scss
static/sass/styles.scss
templates/dell/index.html
yarn.lock

Build new Dell partners page
- Compare https://ubuntu-com-12535.demos.haus/dell with [copy doc](https://docs.google.com/document/d/1ZZQdZt2HFiLwjYYGsb-q7Zncdj0kdv0RBxFm7cz7Gu8/edit)
- Compare https://ubuntu-com-12535.demos.haus/dell with [design](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=909%3A3625&t=TN0zcJ1r28L9Ig7S-1)
Fixes https://warthogs.atlassian.net/browse/WD-1514?atlOrigin=eyJpIjoiNzk4MzIxZmNkYzIzNDkyOGE1YzBkZjgyN2E4NzM4ZWEiLCJwIjoiaiJ9

Revamp dell partners page

---

templates/gcp/pro.html

Update according to [copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit)
- Compare https://ubuntu-com-12668.demos.haus/gcp/pro with [copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit)
Fixes https://warthogs.atlassian.net/browse/WD-2510

WD-2510 GCP copy update

---

templates/engage/de_why-openstack.html
webapp/app.py

New OpenStack page based off https://ubuntu.com/openstack/why-openstack
- Compare https://ubuntu-com-12661.demos.haus/engage/de/warum-openstack with [copy doc](https://docs.google.com/document/d/1Nvam2qif5UPjTyUPWxhJo1XPiFDM-Eb5FxfSWCbNX8c/edit#heading=h.hf5huil04ges)
Fixes https://warthogs.atlassian.net/browse/WD-1319

WD-1319 German OpenStack page

---

static/sass/_pattern_strip.scss
static/sass/styles.scss
templates/silicon/base_silicon.html
templates/silicon/index.html

- Implement the silicon partners visual design
- Navigate to https://ubuntu-com-12595.demos.haus/silicon
- Compare the page to the [visual design](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=1240%3A4433&t=GI5An9beRmd8Yucb-4) and the [copy docs](https://docs.google.com/document/d/1nyiz4I1GqBiXe_SKpDzho3yv20LKyYpyhHh0fvvUrOI/edit)
- [Dev Task](https://warthogs.atlassian.net/browse/WD-2048)
- [Visual Design Task](https://warthogs.atlassian.net/browse/WD-1175)

WD-2048 create silicon partners page

---

templates/shared/contextual_footers/_download_cloud_ubuntu_advantage.html
templates/shared/contextual_footers/_server_contact_us.html
templates/shared/contextual_footers/_support.html
templates/shared/forms/_desktop_ua-shop.html

- Update `advantage` to `pro` in footers
Changes applied on these pages. 
- /download/cloud
- /data/kafka
- /data/spark
- /security/livepatch
- /server/hyperscale
- /server
- /desktop/partners
- /desktop/statistics
- /server/provisioning
- /internet-of-things/contact-us
- /desktop/contact-us
https://docs.google.com/spreadsheets/d/12MF-U2-jHaNilHXHc-JehaS4EMeewOS7k-Dsysbyfc4/edit#gid=0
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-2534

Update advantage to pro in footers

---

templates/kubernetes/managed.html

- Update logos on /kubernetes/managed
- Go to https://ubuntu-com-12687.demos.haus/kubernetes/managed and check that the logos match [the issue](https://warthogs.atlassian.net/browse/WD-1744)
Fixes https://warthogs.atlassian.net/browse/WD-1744

Update logos on /kubernetes/managed

---

templates/legal/modern-slavery-statement/_base_markdown.html
templates/legal/modern-slavery-statement/index.md

- Update modern slavery statement to 2023
- Check content matches the [copydoc](https://docs.google.com/document/d/10sgLW5On2HVNnoA6VF5LY2L3vUiNWm5kmg3EKAaNjN8/edit)
- Check the download works as expected
Fixes https://warthogs.atlassian.net/browse/WD-2376

Update modern slavery statement to 2023

---

konf/site.yaml

- ENV are missing on prod. This might fix it.

Fix pro env

---

templates/legal/nvidia-jetson-and-ubuntu.html

- Create nvida jetson and ubuntu announcement page
- Go to https://ubuntu-com-12699.demos.haus/legal/nvidia-jetson-and-ubuntu and acmapre against [copydoc](https://docs.google.com/document/d/1WI5m3vGyoPBLnXtGy0dBEGf61_eji4lkAV3OUOaMzZ4/edit)
Fixes https://warthogs.atlassian.net/browse/WD-2679

Create nvida jetson and ubuntu announcment page

---

templates/internet-of-things/nvidia/contact-us.html

- Update /nvidia/contact-us based on [copy changes](https://docs.google.com/document/d/1znVFFLSyTmDwCplvloGAlEI3p_dpGH8v82hbYzVfz0o/edit#)
- Go to https://ubuntu-com-12700.demos.haus/iot/nvidia/contact-us and compare against [copydoc](https://docs.google.com/document/d/1znVFFLSyTmDwCplvloGAlEI3p_dpGH8v82hbYzVfz0o/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-2727

Update /nvidia/contact-us based on copy changes

---

templates/cloud/hybrid-cloud.html
templates/cloud/public-cloud.html

- Updates logos based on these two issues:
https://warthogs.atlassian.net/browse/WD-1747
https://warthogs.atlassian.net/browse/WD-1745
- Go to /cloud/public-cloud and /cloud/hybrid-cloud and compare against the design in the issues
Fixes 
https://warthogs.atlassian.net/browse/WD-1747
https://warthogs.atlassian.net/browse/WD-1745

Update logos within the /cloud bubble

---

templates/cloud/hybrid-cloud.html

- Update logos on /cloud/hybrid-cloud based on [the issue](https://warthogs.atlassian.net/browse/WD-1745)
- Minor fly-bys
- Go to https://ubuntu-com-12702.demos.haus/cloud/hybrid-cloud compare to design in  [the issue](https://warthogs.atlassian.net/browse/WD-1745)
Fixes https://warthogs.atlassian.net/browse/WD-1745

Update logos on /cloud/hybrid-cloud

---

templates/pro/index.html

- Update meta_copydoc on /pro
- Go to https://ubuntu-com-12710.demos.haus/pro
- Inspect page and navigate to meta_copy doc/ if you have the extension open the copydoc
- check it is the [appropriate doc](https://docs.google.com/document/d/19TiW9yY6fDzSKL9NOfHSGg33myi-fBUwLcqudoUPv1M/edit?usp=drive_open&ouid=103693084562471184832)

Update meta_copydoc on /pro

---

templates/shared/_call-sales-long.html

Update phone number for South Korea
- Check https://ubuntu-com-12719.demos.haus/contact-us phone number is correct according to the [Jira task](https://warthogs.atlassian.net/browse/WD-1490?atlOrigin=eyJpIjoiOWViM2ExNmJhZTNhNGIzNWJjMjk4YTBjZGM5MDYxNjQiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1490?atlOrigin=eyJpIjoiOWViM2ExNmJhZTNhNGIzNWJjMjk4YTBjZGM5MDYxNjQiLCJwIjoiaiJ9

WD-1490 Add contact number for South Korea

---

templates/openstack/features.html

- Updated copy as per [doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
- See that requested changes were made
Fixes https://warthogs.atlassian.net/browse/WD-2856

[copy update] /openstack/features

---

templates/nvidia/index.html

Marketo form ID was not correct.
Fixes #

Marketo form ID fix - Update index.html

---

templates/openstack/what-is-openstack.html
templates/shared/contextual_footers/_openstack-detailed-documentation.html

- Updated copy as per [doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12722.demos.haus/openstack/what-is-openstack
Fixes https://warthogs.atlassian.net/browse/WD-2596

[copy update] /openstack/what-is-openstack

---

static/sass/_pattern_lists.scss
static/sass/styles.scss
templates/landscape/install.html

- Refresh /landscape/install based on [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#heading=h.yij8xaij9lcy)
- Removes unused styles
- Go to https://ubuntu-com-12675.demos.haus/landscape/install and check the content matches the [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#heading=h.yij8xaij9lcy)
Fixes https://warthogs.atlassian.net/browse/WD-2448

Refresh /landscape/install

---

templates/landscape/install.html

- Update /landscape/install install time bar chart changes based on [copydoc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit)
- Compare bar chart against new bar chart in copydoc
Fixes https://warthogs.atlassian.net/browse/WD-3029

Update /landscape/install install time bar chart changes

---

templates/openstack/tutorials.html

- Update openstack user server section on /openstack/tutorials based on [copydoc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#)
- Go to openstack/tutorials and compare against [copydoc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-2951

Update openstack user server section on /openstack/tutorials

---

templates/download/iot/intel-iot.html

- Update content as in [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#).
- Open the demo page [here](https://ubuntu-com-12749.demos.haus/download/iot/intel-iot) and compare changes with the ones in the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#).
- [WD-2994](https://warthogs.atlassian.net/browse/WD-2944)
[WD-2994]: https://warthogs.atlassian.net/browse/WD-2994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-2994 `/download/iot/intel-iot` copy doc update

---

templates/nvidia/index.html

- Implemented changes requested in [copy doc](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#).
- Open the demo [here](https://ubuntu-com-12750.demos.haus/nvidia) and compare with changes requested in [copy doc](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#)
- [WD-2881](https://warthogs.atlassian.net/browse/WD-2881)
[WD-2881]: https://warthogs.atlassian.net/browse/WD-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-2881 [copy update] for `/nvidia`

---

templates/base_index.html

- Updates / based on [copy changes](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.g8inespqhurp)
- Go to https://ubuntu-com-12704.demos.haus/ and compare against [copy changes](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.g8inespqhurp)
Fixes https://warthogs.atlassian.net/browse/WD-2654

Update / based on copy changes

---

templates/pricing/devices.html

- Update /pricing/devices with new content and pricing information based on [copydoc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
- go to https://ubuntu-com-12751.demos.haus/pricing/devices and compare against [copydoc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-2932

Update /pricing/devices with new content and pricing information

---

templates/desktop/developers.html
templates/desktop/organisations.html
templates/download/desktop/index.html
templates/download/desktop/thank-you.html
templates/shared/_pro_strip.html

- Break pro section being used in multiple pages out into a module
Check the included section in the following pages below
- /desktop/developers
- /desktop/organisations
- /download/desktop
- /download/desktop/thank-you
Fixes #https://github.com/canonical/ubuntu.com/issues/12057

Break pro section out into a module

---

templates/engage/fr_why-openstack.html
webapp/app.py
webapp/views.py

- Build French translation of /why-openstack based on [the copydoc](https://docs.google.com/document/d/1Ge_PwSvT8dtpaEkSBwp_TnVgoz_wvMCPg3A61m5eiuU/edit#)
- Go to https://ubuntu-com-12758.demos.haus/engage/fr/pourquoi-openstack and compare to [the copydoc](https://docs.google.com/document/d/1Ge_PwSvT8dtpaEkSBwp_TnVgoz_wvMCPg3A61m5eiuU/edit#)
- Compare against ubuntu.com/openstack/why-openstack
Fixes https://warthogs.atlassian.net/browse/WD-3054

Build French translation of /why-openstack

---

templates/download/iot/intel-iot.html

- Update copy and fix links on /downlaod/iot/intel-iot based on [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- Check that the download links work in the demo
- Check the copy changes match the copydoc
Fixes https://warthogs.atlassian.net/browse/WD-3143

Update copy and fix links on /downlaod/iot/intel-iot

---

webapp/app.py
webapp/context.py
webapp/handlers.py

- Move handlers to their own file to start making the app file smaller and more readable
- Make sure stuff still works!

refactor: move all handlers in their own file

---

navigation.yaml
static/sass/styles.scss
templates/data/mongodb/index.html
templates/shared/contextual_footers/_data_mongodb_signup.html
templates/shared/forms/interactive/data-mongodb.html
templates/shared/forms/interactive/data_mongodb.html
templates/silicon/index.html

- Create the MongoDB product page
- Create the MongoDB contact form
- Drivebys
- Check out the [demo](https://ubuntu-com-12769.demos.haus/data/mongodb) and compare it with [the design](https://www.figma.com/file/XAmHDBtr7cjQOeDrsE4TH7/23.04-u.com%2Fdata%3A-MongoDB-%26-OpenSearch?node-id=132-2316&t=wt8d2LQ4UdWxyWGj-4) and [copy docs](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit)
- [WD-2123](https://warthogs.atlassian.net/browse/WD-2123)
- [WD-2125](https://warthogs.atlassian.net/browse/WD-2125)
[WD-2123]: https://warthogs.atlassian.net/browse/WD-2123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

WD-2123 & WD-2125 - Create MongoDB product page & contact form

---

templates/cloud/multi-cloud.html

- Updated copy as per [doc](https://docs.google.com/document/d/1nWsDaRiUzaupjKDzu1ZqjlmxHGv2HCgW8oBBEacYFLs/edit#heading=h.evj3u5y98j9v)
- View the site locally in your web browser at: https://ubuntu-com-12778.demos.haus/cloud/multi-cloud
Fixes # https://warthogs.atlassian.net/browse/WD-3082

[copy update] /cloud/multi-cloud

---

templates/cloud/index.html

- Updates copy as per [doc](https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12780.demos.haus/cloud
Fixes https://warthogs.atlassian.net/browse/WD-3079

[copy update] /cloud

---

templates/cloud/private-cloud.html

- Updated copy as per [doc](https://docs.google.com/document/d/19g24YRYzF5dBpUKI1QzTG7fXKj1z0OvwgFll69dFoOs/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12781.demos.haus/cloud/private-cloud
Fixes https://warthogs.atlassian.net/browse/WD-3080

[copy update] /cloud/private-cloud

---

templates/credentials/index.html
webapp/shop/cred/syllabus.json

- Update syllabus for CUE: Linux
- Use Title Case for Section Headers
- Visit https://ubuntu-com-12793.demos.haus/credentials/syllabus?exam=CUE.01%3A%20Linux
- Verify against [copy](https://docs.google.com/document/d/1T1K7jyUa32-OURET6AjN2CD_c80TaUmj9EncYT70PNw/edit#)
- Visit https://ubuntu-com-12793.demos.haus/credentials/syllabus?exam=CUE.02%3A%20Desktop
- Check section headers for Title Case
- Visit https://ubuntu-com-12793.demos.haus/credentials/syllabus?exam=CUE.03%3A%20Server
- Check section headers for Title Case
Fixes https://warthogs.atlassian.net/jira/software/c/projects/CRED/boards/776?modal=detail&selectedIssue=CRED-384

Update syllabus for CUE: Linux

---

navigation.yaml
static/sass/styles.scss
templates/data/mongodb/index.html
templates/data/opensearch/index.html
templates/shared/contextual_footers/_data_opensearch_signup.html
templates/shared/forms/interactive/data-opensearch.html

- Create the OpenSearch product page
- Create the OpenSearch contact form
- Check out the [demo](https://ubuntu-com-12785.demos.haus/data/opensearch) and compare it with [the MongoDB page](https://ubuntu-com-12785.demos.haus/data/mongodb) (for design) and also the [copy docs](https://docs.google.com/document/d/17vCodr2uujQv591IlWmveh6_7OLyPK1KrXQb2ZSiceA/edit#)
- [WD-2898](https://warthogs.atlassian.net/browse/WD-2898)
[WD-2898]: https://warthogs.atlassian.net/browse/WD-2898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-2898 create opensearch product page and form

---

templates/cloud/hybrid-cloud.html

- Updated copy as per [doc](https://docs.google.com/document/d/1oIggNSXR5sfl0Ab35x2NIL7I858I7QdPCUXeQI8IIPc/)
- View the site locally in your web browser at: https://ubuntu-com-12782.demos.haus/cloud/hybrid-cloud
Fixes https://warthogs.atlassian.net/browse/WD-3081

[copy update] /cloud/hybrid-cloud

---

templates/legal/nvidia-jetson-and-ubuntu.html

- Updated copy as per [doc](https://docs.google.com/document/d/1WI5m3vGyoPBLnXtGy0dBEGf61_eji4lkAV3OUOaMzZ4/edit)
- View the site locally in your web browser at: https://ubuntu-com-12798.demos.haus/legal/nvidia-jetson-and-ubuntu
- See that the requested change was made
Fixes https://warthogs.atlassian.net/browse/WD-3142

[copy update] /legal/nvidia-jetson-and-ubuntu

---

templates/pricing/pro.html

- Implement copy update requested
- Check out the [demo here](https://ubuntu-com-12790.demos.haus/pricing/pro) and compare it with the update requested on the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#).
- [WD-3064](https://warthogs.atlassian.net/browse/WD-3064)
[WD-3064]: https://warthogs.atlassian.net/browse/WD-WD-3064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3064 `/pricing/pro` 

---

templates/observability/index.html
templates/shared/_latest_news_strip.html

- Updated copy as per [doc](https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit)
- View the site locally in your web browser at: https://ubuntu-com-12800.demos.haus/observability
Fixes https://warthogs.atlassian.net/browse/WD-2602

[copy update] /observability

---

static/js/src/advantage/subscribe/react/UAPurchase.tsx
static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
static/js/src/advantage/subscribe/react/components/Form/Form.tsx
static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
static/js/src/advantage/subscribe/react/components/Form/Version/Version.test.tsx
static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx

- Disable tab key on disabled area
- Tab through the page and check tab is not working on disabled area
Fixes https://github.com/canonical/ubuntu.com/issues/11916

Accessibility for disabled area on /pro/subscribe

---

templates/support/index.html

- Replace logos with logo section logos (edited for logo section)
- Go to /support
- Check the logo section (Be sure to test on mobile, tablet and desktop screen sizes)
Fixes #https://github.com/canonical/ubuntu.com/issues/12792

Update logo on /support

---

templates/pro/index.html

- Go to `/pro`
- Make sure the copy reflects the requested changes.
Fixes https://warthogs.atlassian.net/browse/WD-3331

Pro: Ubuntu Pro(Infra-Only) offers Real-time kernel.

---

releases.yaml
static/js/src/chart-data.js
static/sass/_pattern_strip.scss
templates/desktop/developers.html
templates/download/desktop/index.html
templates/download/index.html
templates/download/risc-v/index.html
templates/download/risc-v/tab-1.html
templates/download/risc-v/tab-2.html
templates/download/risc-v/tab-3.html
templates/download/risc-v/tab-4.html
templates/download/risc-v/tab-5.html
templates/download/risc-v/tab-6.html
templates/download/server/manual.html
templates/templates/navigation-download-h.html

- Preparation for release!
- http://0.0.0.0:8001/
Fixes:
- WD-3013
- WD-3012
- WD-3011
- WD-3010
- WD-3009
- WD-3008
- WD-3006

23 04 - release prep

---

webapp/shop/api/ua_contracts/api.py
webapp/shop/cred/views.py

- Admins can now access other user's your-exams page
- visit /credentials/your-exams?email=<test-email-id>
- You should be able to see the specified email's exams
Fixes https://warthogs.atlassian.net/browse/CRED-371

Debugging view for your-exams

---

navigation.yaml
templates/18-04/gcp.html

- Build the `/18-04/gcp` page
- Check out the [demo here](https://ubuntu-com-12802.demos.haus/18-04/gcp) and compare it with the [copy doc](https://docs.google.com/document/d/1d62l-BdsgXjs0PZ_JuxJ0u_xG7lUNqyFVBN-lCvSt00/edit#) and with the [Azure page](https://ubuntu-com-12802.demos.haus/18-04/azure) for design review.
- [WD-3110](https://warthogs.atlassian.net/browse/WD-3110)
[WD-3110]: https://warthogs.atlassian.net/browse/WD-3110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-3110 build `/18-04/gcp`

---

templates/core/features/index.html

- Update copy as per [doc](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12843.demos.haus/core/features
Fixes # https://warthogs.atlassian.net/browse/WD-3204

[copy update] /core/features

---

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx

- Fix renewal settings to show the correct total.
- Ask me
Fixes #https://warthogs.atlassian.net/browse/WD-3546

Fix renewal total cost

---

templates/ai/index.html

- Copy update for `/ai`
- Check out the [demo here](https://ubuntu-com-12846.demos.haus/ai) and compare the changes with the [copy docs here](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit#).
- [WD-3553](https://warthogs.atlassian.net/browse/WD-3553)
[WD-3553]: https://warthogs.atlassian.net/browse/WD-3553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] `/ai` copy update (WD-3553)

---

templates/data/mongodb/index.html

- Set the correct copy doc link in the meta for MongoDB
- Check the link is correct

Update the copydoc meta for MongoDB

---

templates/security/fips.html

- Updated as per [doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12856.demos.haus/security/fips
Fixes https://warthogs.atlassian.net/browse/WD-3659

[copy update] /security/fips

---

templates/data/kafka/index.html

- Updated page content based on requested copy update.
- Check out the [demo here](https://ubuntu-com-12852.demos.haus/data/kafka) and compare the make sure the changes requested in the [copy doc](https://docs.google.com/document/d/1bfo97XdFdKlzrMcMoRxiTdzt_bPVndx6j55IPsapuAE/edit) are implemented correctly.
- [WD-3587](https://warthogs.atlassian.net/browse/WD-3587)
[WD-3587]: https://warthogs.atlassian.net/browse/WD-3587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3587 `/data/kafka` heading copy update

---

static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx

- Update condition for enableReinitialisation
To check issue 
- Go to https://staging.ubuntu.com/pro/subscribe
- Log in with account that has previous purchase history
- Click `Buy now` button and check error message shows at the top
- Click `Edit` in the 1 step and change `country` and save.
- Click `Edit` button again 
- Click `Cancel`
- See the **previous country** shows 
After fix,
- Go to https://ubuntu-com-12757.demos.haus/pro/subscribe
- Do the same steps above
- See the **updated country** shows
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-3675

Update reinitialize condition

---

templates/aws/pro.html

- Copy update on /aws/pro
- Go to https://ubuntu-com-12863.demos.haus/aws/pro
- Compare page against [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#)
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-3432

Copy update on /aws/pro

---

templates/landscape/pricing.html

- Copy update for `/landscape/pricing`
- Check out the [demo here](https://ubuntu-com-12878.demos.haus/landscape/pricing) and compare it with the [copy doc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#).
- [WD-3785](https://warthogs.atlassian.net/browse/WD-3785)
[WD-3785]: https://warthogs.atlassian.net/browse/WD-3785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3785 copy update on `/landscape/pricing`

---

templates/managed/apps/kafka.html

- Updated Contact Us links on the page
- Check out the [demo here](https://ubuntu-com-12857.demos.haus/managed/apps/kafka) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#).
- [WD-3499](https://warthogs.atlassian.net/browse/WD-3499)
[WD-3499]: https://warthogs.atlassian.net/browse/WD-3499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3499 `/managed/apps/kafka` contact link update

---

templates/openstack/what-is-openstack.html

- Update a link on `/openstack/what-is-openstack`
- Check out [the demo](https://ubuntu-com-12883.demos.haus/openstack/what-is-openstack) and compare it with [the copy doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#).
- [WD-3503](https://warthogs.atlassian.net/browse/WD-3503)
[WD-3503]: https://warthogs.atlassian.net/browse/WD-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3503 replace link on `/openstack/what-is-openstack`

---

templates/download/iot/intel-iot.html

- Update realtime webinar link
- Check out the [demo here](https://ubuntu-com-12886.demos.haus/download/iot/intel-iot) and compare it with the changes requested on the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit).
- [WD-3787](https://warthogs.atlassian.net/browse/WD-3787)
[WD-3787]: https://warthogs.atlassian.net/browse/WD-3787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3787 update webinar link on `/download/iot/intel-iot`

---

templates/security/esm.html

- Updated table as per [doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#)
- View the site locally in your web browser at: https://ubuntu-com-12903.demos.haus/security/esm
- See that the requested changes were made
Fixes https://warthogs.atlassian.net/browse/WD-4077

[copy update] /security/esm

---

templates/shared/forms/interactive/esm.html

- Updates the form based on changes across these two copy docs (I have asked them to keep all the changes in the original)
https://docs.google.com/document/d/1FzITFuuU3CU28bhLuA4hbrAVrJDj2fyiAxM9tcVirhg/edit
https://docs.google.com/document/d/1L-2iFndRiHsnGXw2mKrq_uMafm6qQJ6i4BkMo-wDujs/edit#heading=h.rfco041tpedl
Fixes https://warthogs.atlassian.net/browse/WD-4067

Update form on /esm

---

templates/landscape/install.html
templates/landscape/managed.html

- [Updated copy as per [doc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#)
- Drive bys:
- Fixed section alignment in /landscape/managed to match [design](https://github.com/canonical/ubuntu.com/pull/12812#issuecomment-1523023623) 
- View the site locally in your web browser at: https://ubuntu-com-12916.demos.haus/landscape/install
- See that requested changed have been made
- View the site locally in your web browser at: https://ubuntu-com-12916.demos.haus/landscape/managed
- See that the page matches design  
Fixes https://warthogs.atlassian.net/browse/WD-3987

[copy update] /landscape/managed

---

navigation.yaml
templates/18-04/ibm.html

- Build the `/18-04/ibm` page
- Check out this [demo here](https://ubuntu-com-12919.demos.haus/18-04/ibm) and compare its content with the [copy doc](https://docs.google.com/document/d/1a32P199a-kmn1BgeI6kb_IVhbFGDah3hxTXPpfWepug/edit#) and also the design with the existing other existing [/18-04/* pages](https://ubuntu.com/18-04)
- [WD-4010](https://warthogs.atlassian.net/browse/WD-4010)
[WD-4010]: https://warthogs.atlassian.net/browse/WD-4010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Build `/18-04/ibm` page - WD-4010

---

templates/shared/pricing/_kubernetes-consulting.html
templates/shared/pricing/_openstack-packages.html
templates/training/index.html

- Update consulting pricing across the site
- Check that /openstack/consulting matches [the copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
- Check that /pricing matches [the copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#)
- Check that /training matches [the copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-4456

WD-4456 Update consulting pricing across the site

---

templates/security/cis.html

- Refresh the content based on the content in the [copy doc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#)
- Go to /security/cis
- Check the content matched the copy doc
Fixes https://warthogs.atlassian.net/browse/WD-3702

WD-3702 Update ubuntu.com/security/cis

---

templates/shared/forms/interactive/managed-apps.html

- Copy update on the "Free Deployment Assessment" form on `/managed/apps`
- Check out the [demo here](https://ubuntu-com-12932.demos.haus/managed/apps) and compare it with the changes on the [form copy docs](https://docs.google.com/document/d/1aRLC2oK8jK3im2zvuLBVF947-Rw8Km5JpCrPGrnMUcM/edit).
- [WD-3655](https://warthogs.atlassian.net/browse/WD-3655)
- Related to this PR: #12867 
[WD-3655]: https://warthogs.atlassian.net/browse/WD-3655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3655 align fields on managed apps assessment form

---

templates/aws/pro.html

- Copy update on `/aws/pro`
- Check out the [demo here](https://ubuntu-com-12937.demos.haus/aws/pro) and compare it with the changes on the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#).
- [WD-3799](https://warthogs.atlassian.net/browse/WD-3799)
[WD-3799]: https://warthogs.atlassian.net/browse/WD-3799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-3799 Update `/aws/pro`

---

templates/data/mongodb/index.html
templates/shared/forms/interactive/data-mongodb.html

- Add Job title and Company name to Mongodb form
- Return to success message
- Go to /data/mongodb#get-in-touch
- Fill it in and check the form submits back to a success message
Fixes https://warthogs.atlassian.net/browse/WD-4052

WD-4052 Add Job title and Company name to mongodb form

---

static/sass/styles.scss
templates/openstack/install.html

- Updated `/openstack/install` based on copy doc.
- Check out the [demo here](https://ubuntu-com-12912.demos.haus/openstack/install) and compare it with the changes on the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit).
- [WD-3622](https://warthogs.atlassian.net/browse/WD-3622)
[WD-3622]: https://warthogs.atlassian.net/browse/WD-3622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Sunbeam GA Launch] WD-3622 revamp `/openstack/install`

---

templates/pricing/pro.html

- Add USG harderning to 22.04 LTS in the pricing table for Pro
- Open the demo and go to /pricing/pro
- Check the change matches the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-4468

WD-4468 Add USG harderning to 22.04 LTS

---

templates/pricing/desktop.html

- Copy update on `/pricing/desktop`
- Check out the [demo here](https://ubuntu-com-12957.demos.haus/pricing/desktop) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/1xVtaZ7wr5sdBqye3Gc-XWXEpNqXaol8uDdMwJ_KyOO8/edit).
- [WD-4554](https://warthogs.atlassian.net/browse/WD-4554)
[WD-4554]: https://warthogs.atlassian.net/browse/WD-4554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4554update pricing table

---

webapp/shop/views.py

- Make the user trial status consistent between the product selector and the checkout
- The current rules they both abide are:
- user cannot have active / locked subscriptions
- user cannot have any subscriptions that have started as a trial
- list must have more that 0 day of trial available
If these conditions are fulfilled the the trial setting should show up and the user will be able to start a trial.
- Buy a subscription (not a free trial)
- Cancel subscription from the backoffice tool
- Go to product selector you will see the free trial, you will see the setting on the checkout too
- Buy a trial
- Cancel trial
- Trail will no longer be available
Fixes #https://warthogs.atlassian.net/browse/WD-4364

Fix trial status

---

templates/openstack/consulting.html
templates/openstack/managed.html

Update contact form URLs according to copy docs
Fixes https://warthogs.atlassian.net/browse/WD-4579
- Update https://ubuntu-com-12963.demos.haus/openstack/consulting contact us form according to [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit)
- Update https://ubuntu-com-12963.demos.haus/openstack/managed contact us form according to [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit)

Update contact us URL according to copy docs

---

templates/pricing/devices.html

- Copy update on `/pricing/devices`
- Check out the [demo here](https://ubuntu-com-12962.demos.haus/pricing/devices) a compare the changes to what was [requested in the task](https://warthogs.atlassian.net/browse/WD-4477) and the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit).
- [WD-4477](https://warthogs.atlassian.net/browse/WD-4477)
[WD-4477]: https://warthogs.atlassian.net/browse/WD-4477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4477 updates on `/pricing/devices`

---

templates/base_index.html

- Update the 18.04 EOS notice link on the home page
- Check out the [demo here](https://ubuntu-com-12956.demos.haus/) and compare it with the text specified in the [task](https://warthogs.atlassian.net/browse/WD-4552) and the [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.g8inespqhurp)
- [WD-4552](https://warthogs.atlassian.net/browse/WD-4552)
[WD-4552]: https://warthogs.atlassian.net/browse/WD-4552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4552 update eos for 18.04 notice link on `/`

---

templates/data/mongodb/index.html

- Changed the heading text on `/data/mongodb`
- Check out the [demo here](https://ubuntu-com-12952.demos.haus/data/mongodb) and compare it with the text specified in the [task](https://warthogs.atlassian.net/browse/WD-4532) and the [copy doc](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit)
- [WD-4532](https://warthogs.atlassian.net/browse/WD-4532)
[WD-4532]: https://warthogs.atlassian.net/browse/WD-4532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4532 update heading text on `/data/mongodb`

---

templates/about/openstack-release-cycle.html

Fix http://ubuntu.com/engage/de/warum-openstack
- https://ubuntu-com-12980.demos.haus/engage/de/warum-openstack Should be working now

Fix Warum Openstack Engage page

---

templates/ai/services.html
templates/shared/contextual_footers/_kubeflow_news_signup.html

- Fixes UTMs not being delivered in payload on /ai/services
- Go to https://ubuntu-com-12975.demos.haus/ai/services?utm_source=test&utm_medium=test&utm_campaign=test and submit the form. Check that the UTMs passed in url are appended to the payload

Fixes UTMs not being delivered in payload on /ai/services

---

static/files/sitemap.xml

- Remove deleted URLs from the sitemap 
- Check the code looks ok
Fixes https://github.com/canonical/ubuntu.com/actions/runs/5342758308/jobs/9684959568

Remove deleted URLs from the sitemap

---

templates/openstack/install.html

- Update primary CTA text
- Check out the [demo here](https://ubuntu-com-12977.demos.haus/openstack/install) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit).
- [WD-4704](https://warthogs.atlassian.net/browse/WD-4704)
[WD-4704]: https://warthogs.atlassian.net/browse/WD-4704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4704 update on `/openstack/install`

---

konf/site.yaml

Everything should now use the PS5 registry

Use PS5 registry

---

static/files/sitemap.xml

- Include the [https://ubuntu.com/robotics/docs](https://ubuntu.com/robotics/docs) in the sitemap.xml so we can find it from Google.

Update sitemap.xml with robotics docs

---

templates/download/iot/intel-iot.html

- Update intel iot page
- Check out the [demo here](https://ubuntu-com-12960.demos.haus/download/iot/intel-iot) and compare it with the changes requested on the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- [WD-4479](https://warthogs.atlassian.net/browse/WD-4479)
[WD-4479]: https://warthogs.atlassian.net/browse/WD-4479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4479 update on `/download/iot/intel-iot`

---

tests/cypress/support/pro/commands.js

- Some bizarre `TypeError` causing problems. Muting these problems for Cypress.
- Are checks passing?

Fix cypress

---

templates/hpc/index.html

- Add the new link in the [copy doc](https://docs.google.com/document/d/1d4E1IA2mEu72q277sihNSkl7QRKsU1ezwA3jVgJ0TCE/edit)
- Go to /hpc
- Click the new link and check it works
Fixes https://warthogs.atlassian.net/browse/WD-4808

WD-4808 Add "Download our Guide to HPC"

---

ARCHITECTURE.md
README.md

A document explaining a high-level view of the structure and functions within the ubuntu.com application.
Read it here: https://github.com/nottrobin/ubuntu.com/blob/architecture.md/ARCHITECTURE.md

Add ARCHITECTURE.md

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
static/js/src/advantage/subscribe/checkout/hooks/useCalculate.tsx
static/js/src/advantage/subscribe/checkout/hooks/useFinishPurchase.tsx
static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
static/js/src/advantage/subscribe/checkout/utils/helpers.ts
tests/cypress/support/pro/commands.js

- If user attempts to buy a product while trialling, it will throw a general error.
- This change will make it clearer why a purchase fails.
- Buy a trial subscription
- Attempt to buy another subscription
- Do you see the error message?
Fixes #https://warthogs.atlassian.net/browse/WD-4249

Cannot buy in trial

---

webapp/shop/schemas.py

- Fix parsing backend error
- Buy a product with this card `4000000000000341`
- Submit checkout form
- You will get an error
- Refresh page
- You will get the pending purchase error message
Fixes #https://warthogs.atlassian.net/browse/WD-4806

Fix validation error

---

static/sass/styles.scss
templates/hpe/index.html
webapp/app.py

Revamp u.com/hpe
- Check https://ubuntu-com-12959.demos.haus/hpe compare with [design](https://www.figma.com/file/WIizcxJW1PcpPpvjUX433B/23.10-U.com---HPE-partner-page?type=design&t=3uQAjLAhzdZ3fJag-0) and [copy docs](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit)
Fixes https://warthogs.atlassian.net/browse/WD-3609?atlOrigin=eyJpIjoiODUzMzI1MWFiMTc0NDcwN2EyNDkyYjU1YWNlYWZmNWQiLCJwIjoiaiJ9

Revamp HPE page

---

templates/about/release-cycle.html

-  Small typo fix
- Check the code.
Fixes https://github.com/canonical/ubuntu.com/issues/12999

Fix type on the OpenStack release cycle

---

navigation.yaml
static/sass/styles.scss
templates/containers/chiselled/_base_chiselled.html
templates/containers/chiselled/dotnet.html
templates/shared/forms/interactive/containers-chiselled-dotnet.html
templates/silicon/index.html

- Build Chiselled Ubuntu page and contact form
- Drive-bys on `/silicon`
- Check out [the demo here](https://ubuntu-com-12995.demos.haus/containers/chiselled/dotnet) and compare it with [the copy doc](https://docs.google.com/document/d/1fUG2SpbfdVDMAdbe7zfuzzvji4oWm-P18D85V2A3F8c/edit) and [the design](https://www.figma.com/file/Jgq60iLkA1su93S0ilHeY2/23.04-U.com---Chiselled-Ubuntu-and-.NET-containers-(WD-3141)?type=design&node-id=70-770&mode=design&t=ui6ZZ6Y6v4ScBZ25-0) 
- [WD-3946](https://warthogs.atlassian.net/browse/WD-3946)
[WD-3946]: …

Build Chiselled Ubuntu and .Net containers - WD-3946

---

templates/hpc/use-cases.html

- Add a new strip for high-performance computing guide to HPC
- Go to /hpc/use-cases
- Check that the new section matches the [copy doc](https://docs.google.com/document/d/1yG6svTYbKBgdGih5ASsWbRDWAMPcqIJVfpQ5LGoxRCE/edit)
Fixes https://warthogs.atlassian.net/browse/WD-4924

WD-4924 Add the high-performance computing guide to HPC

---

templates/containers/chiselled/dotnet.html

- Changes to the page title [requested here](https://warthogs.atlassian.net/browse/WD-3141?focusedCommentId=272716) and some changes to [the copy doc](https://docs.google.com/document/d/1fUG2SpbfdVDMAdbe7zfuzzvji4oWm-P18D85V2A3F8c/edit).
- Check out the [demo here](https://ubuntu-com-13022.demos.haus/containers/chiselled/dotnet) and compare it to the changes requested.
This is a quick fix for this PR #12995 which was merged recently.

quick fix to title and header on `/containers/chiselled/dotnet`

---

templates/data/mongodb/index.html

- Add download datasheet button
- Check out the [demo here](https://ubuntu-com-13013.demos.haus/data/mongodb) and compare it with the update requested in the [copy doc](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit).
- [WD-4596](https://warthogs.atlassian.net/browse/WD-4596)
[WD-4596]: https://warthogs.atlassian.net/browse/WD-4596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4596 add download datasheet button

---

static/js/src/advantage/credentials/components/CredManage/CredManage.tsx
templates/credentials/shop/index.html

- Update visuals for /credentials/shop/manage
- Visit https://ubuntu-com-12996.demos.haus/credentials/shop/manage
Fixes https://warthogs.atlassian.net/browse/WD-3906

Update visuals for /credentials/shop/manage

---

webapp/views.py

the API name of utm_content in Marketo is utmcontent and that cannot be changed

Update views.py - fix utm_content field

---

templates/core/index.html

- Updated two webinar links and content on the /core page
- Open the demo and go to /core
- Scroll to the Learn more section
- Check the webinar links and content match the [copydoc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit?disco=AAAAzWTTFY0)
- Check the links work
Fixes https://warthogs.atlassian.net/browse/WD-4995

WD-4995 - Update webinars on the core page

---

templates/landscape/pricing.html
templates/shared/forms/interactive/landscape-pricing-saas.html

- Build the landscape saas form
- Link form on landscape pricing page
- Check out the [landscape pricing page and the landscape saas form here](https://ubuntu-com-13005.demos.haus/landscape/pricing) and compare it with the changes requested in [the copy doc for the form](https://docs.google.com/document/d/1GudiHDU72RvHqBIiZVIU7a-EfEe2QP1IeEHiuF1k0CE/edit) and [the copy doc for the page.](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit)
- [WD-3790](https://warthogs.atlassian.net/browse/WD-3790)
- [WD-3792](https://warthogs.atlassian.net/browse/WD-3792)
[WD-3790]: …

Build landscape saas form

---

templates/templates/navigation-download-h.html

Update the ubuntu-cinnamon flavour link

---

templates/ceph/install.html

- Refreshes /ceph/install based on [copydoc](https://docs.google.com/document/d/1EmOtHjuEMKhVLQA7GwyrKfCzOKfc8UCEyh-p04-PxzA/edit)
- Check that [the demo](https://ubuntu-com-12976.demos.haus/ceph/install) content matches the [copydoc](https://docs.google.com/document/d/1EmOtHjuEMKhVLQA7GwyrKfCzOKfc8UCEyh-p04-PxzA/edit)
Fixes https://warthogs.atlassian.net/browse/WD-4453

Refresh /ceph/install

---

templates/lxd/index.html

- Update the "Cloud-like experience" paragraph
- Check out the [demo here](https://ubuntu-com-13042.demos.haus/lxd) and compare it with the change requested on the [copy doc](https://docs.google.com/document/d/1LJ6ajHYAmKdxSNDaD5kbriDod1t7RcmIwVJtevAeKFQ/edit).
- [WD-5110](https://warthogs.atlassian.net/browse/WD-5110)
[WD-5110]: https://warthogs.atlassian.net/browse/WD-5110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-5110 Update on `/lxd`

---

navigation.yaml
templates/ai/roadshow.html
templates/dell/index.html

- Build the ai/roadshow page
- Go to /ai/roadshow
- Check the copy matches the [copy doc](https://docs.google.com/document/d/1CA0GUU6yRB65yfDaKi1dgN8DED2bDAFI2h-swSVtMtg/edit)
Fixes https://warthogs.atlassian.net/browse/WD-5128

WD-5128 - Build the ai/roadshow page

---

static/sass/styles.scss
templates/download/iot/intel-iot.html

- Update copy on /download/iot/intel-iot based on [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- Check out the [demo](https://ubuntu-com-13049.demos.haus/) and compare against the [copydoc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
Fixes https://warthogs.atlassian.net/browse/WD-5232 …

Update copy on /download/iot/intel-iot

---

templates/ceph/index.html
templates/shared/_resources_ceph.html

- Copy revamp on `/ceph`
- Check out the [demo here](https://ubuntu-com-13052.demos.haus/ceph) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit#).
- [WD-4341](https://warthogs.atlassian.net/browse/WD-4341)
[WD-4341]: https://warthogs.atlassian.net/browse/WD-4341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4341 revamp on `/ceph`

---

templates/nvidia/index.html

- Copy update on `/nvidia`
- Check out [the demo here](https://ubuntu-com-13055.demos.haus/nvidia) and compare it with the changes requested on [the copy doc](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit).
- [WD-5191](https://warthogs.atlassian.net/browse/WD-5191)
[WD-5191]: https://warthogs.atlassian.net/browse/WD-5191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-5191 Update on `/nvidia`

---

redirects.yaml
robots.txt
static/files/robots.txt
webapp/app.py
webapp/views.py

Reverts canonical/ubuntu.com#13043 to see if it helps with [issues with keywords](https://chat.canonical.com/canonical/pl/htbbs9i4qigx8bfzkds9bccznc).

Revert "Generate sitemaps and fix robots.txt path for analytics"

---

templates/shared/forms/interactive/hpe.html

- Copy update on `/hpe` contact form
- Check out [the demo here](https://ubuntu-com-13059.demos.haus/hpe) and compare it with the update requested in [the copy doc](https://docs.google.com/document/d/1GtHoXJPGqTaxJxj1d9ul7hZukb_piUdBunXAwx7J28k/edit).
- [WD-5355](https://warthogs.atlassian.net/browse/WD-5355)
[WD-5355]: https://warthogs.atlassian.net/browse/WD-5355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-5355 Update /hpe contact form

---

.github/workflows/live-links.yaml
templates/cloud/private-cloud.html

- Removed a link to server docs and updated the copy doc
- Extended the ignore list to include `http://*.example.com`
Fixes https://github.com/canonical/ubuntu.com/actions/runs/5711837423/job/15474149655

Fix the errors reported from the live linkchecker

---

templates/hpe/index.html

- Fix links according to [copy doc](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit?usp=sharing)
- Check https://ubuntu-com-13056.demos.haus/hpe against [copy docs](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit?usp=sharing)
Fixes https://warthogs.atlassian.net/browse/WD-5354?atlOrigin=eyJpIjoiODI1OWE5NTZlNGUxNDk2Y2ExZDNhMGU0YTMzYjY1MDciLCJwIjoiaiJ9

WD-5354 Fix hpe links

---

templates/security/cve/_cve-table.html
templates/security/cve/cve.html

- Change product names to CVE pages
- Go to: /security/CVE-2023-2953 You might have to pull branch, I think demos don't have databases. Is the text different?
Fixes #https://warthogs.atlassian.net/browse/WD-5276

Change product name

---

templates/cloud/hybrid-cloud.html
templates/cloud/multi-cloud.html
templates/openstack/features.html

- Update https://ubuntu-com-13063.demos.haus/cloud/multi-cloud based on [copydoc](https://docs.google.com/document/d/1nWsDaRiUzaupjKDzu1ZqjlmxHGv2HCgW8oBBEacYFLs/edit#heading=h.evj3u5y98j9v)
- Update https://ubuntu-com-13063.demos.haus/openstack/features based on [copydoc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#heading=h.bc340jc7x07b)
- Update https://ubuntu-com-13063.demos.haus/cloud/hybrid-cloud based on [copydoc](https://docs.google.com/document/d/1oIggNSXR5sfl0Ab35x2NIL7I858I7QdPCUXeQI8IIPc/edit#heading=h.evj3u5y98j9v)
- Check out each of the demos above and check that they match the changes to the CTAs in the copydocs
Fixes https://warthogs.atlassian.net/browse/WD-5452

Update the /cloud bubbles top-strip CTAs

---

templates/ai/what-is-kubeflow.html
templates/ceph/what-is-ceph.html
templates/kubernetes/what-is-kubernetes.html
templates/openstack/compare.html

Update Canonical logos
- Update logos according to [copy doc](https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/edit) and a few more
https://ubuntu-com-13073.demos.haus/ceph/what-is-ceph
https://ubuntu-com-13073.demos.haus/ai/what-is-kubeflow (check "contributors to Kubeflow" section)
https://ubuntu-com-13073.demos.haus/kubernetes/what-is-kubernetes ("Key contributors")
https://ubuntu-com-13073.demos.haus/openstack/compare (first table)
Fixes #

Update Canonical logo

---

templates/pro/index.html

- Update meta description of /pro
Fixes #https://warthogs.atlassian.net/browse/WD-5259

Update /pro meta

---

static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
static/js/src/advantage/subscribe/checkout/hooks/useFinishPurchase.tsx
static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
templates/account/invoices/index.html

- Fix purchasing after cancelling. This one happens when you repurchase though the product selector the same product with the same quantity of a downsized to 0 subscription.
- Buy 3x Ubuntu Pro (pay for it, not trial)
- Cancel the subscription (downsize to 0)
- Buy 1x Ubuntu Pro from the store 
Fixes #https://warthogs.atlassian.net/browse/WD-4520

Fix purchasing after cancelling

---

templates/certified/shared/_partners.html
templates/industrial/index.html

- Update the Eurotech logo on pages.
- Also updated the logo on an extra page that wasn't listed in the Jira ticket.
- Check out the logo section here - https://ubuntu-com-13082.demos.haus/certified and make sure the logo has been updated
- Check out the logo section here - https://ubuntu-com-13082.demos.haus/certified/why-certify and make sure the logo has been updated
- Check out the logo section here - https://ubuntu-com-13082.demos.haus/industrial and make sure the logo has been updated
- [WD-5479](https://warthogs.atlassian.net/browse/WD-5479)
[WD-5479]: https://warthogs.atlassian.net/browse/WD-5479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

[copy update] WD-5479 update eurotech logo

---

templates/download/desktop/thank-you.html

- Update some text according to copy doc
- Make blogs dynamic
- Go to  https://ubuntu-com-13072.demos.haus/download/desktop/thank-you?version=23.04&architecture=amd64 and compare to [comments in copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit)
- Scroll down and check blogs work
Fixes https://warthogs.atlassian.net/browse/WD-5469?atlOrigin=eyJpIjoiMmZmZTQ2ZDk5NjhmNGU3OTljNGQ3MjgyYmI4YjY1ODgiLCJwIjoiaiJ9

Update download Ubuntu Desktop page

---

templates/legal/contributors/agreement.html

- Adds DC to the list of states as instructed by Neil Messenbird through MM:
"The only change I made was to add the extra state 'DC'"
[copydoc](https://docs.google.com/document/d/1MfgTzlAxiFE6VUW1qAPmrks2ui1zzsX5T7d-DZJlOAw/edit#heading=h.dwz8es61nwww)
Fixes https://warthogs.atlassian.net/browse/WD-5665

Update contributors agreement form US states dropdown

---

templates/blog/author.html

- Replace the Canonical author avatar with the COF
- Go to /blog/author/canonical
- Check the author avatar is the COF
- Check the blog for as real author and see there avatar remains a circle and works
Fixes https://warthogs.atlassian.net/browse/WD-5748

WD-5748 - Replace the Canonical author avatar with the COF

---

templates/blog/article.html

- Update the Canonical avatar on the article page
- Go to /blog and select an article authored by Canoncal
- See the avatar is the new Ubuntu logo

Update the Canonical avatar on the article page

---

templates/desktop/organisations.html
templates/pricing/desktop.html

- Updates /pricing/desktop based on [copydoc](https://docs.google.com/document/d/1xVtaZ7wr5sdBqye3Gc-XWXEpNqXaol8uDdMwJ_KyOO8/edit)
- Update /dektop/organisations cased on [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit)
- Go to https://ubuntu-com-13100.demos.haus/pricing/desktop and https://ubuntu-com-13100.demos.haus/dektop/organisations and compare against the copydocs
Fixes https://warthogs.atlassian.net/browse/WD-4970

Update datasheet on /pricing/desktop & /desktop/organisations

---

templates/18-04/azure.html

- Copy update on `/18-04/azure`
- Check out the [demo here](https://ubuntu-com-13101.demos.haus/18-04/azure) and compare it with the work requested on the [copy doc](https://docs.google.com/document/d/1O7RApX5BNPH13-3j-Wq-31RWz-pdpciNFea7ixL3kJI/edit).
- [WD-5827](https://warthogs.atlassian.net/browse/WD-5827)
[WD-5827]: https://warthogs.atlassian.net/browse/WD-5827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-5827 Update on /18-04/azure

---

static/js/src/advantage/subscribe/react/components/Form/Form.tsx
static/js/src/advantage/subscribe/react/utils/FormContext.tsx

Fixes https://warthogs.atlassian.net/browse/WD-6043
- View the site locally in your web browser at: http://0.0.0.0:8001/pro/subscribe
- Make sure the fixes listed on the ticket are implemented

Pro subscribe - Version section fixes

---

templates/18-04/azure.html

- Updated copy as per [doc](https://docs.google.com/document/d/1O7RApX5BNPH13-3j-Wq-31RWz-pdpciNFea7ixL3kJI/edit)
- View the site locally in your web browser at: https://ubuntu-com-13121.demos.haus/18-04/azure
- See that the requested changes were made
Fixes https://warthogs.atlassian.net/browse/WD-5972

[copy update] /18-04/azure

---

static/js/src/risc-v.js
static/js/src/tabbed-content.js
static/sass/styles.scss
templates/download/amd-xilinx/index.html
templates/download/amd-xilinx/tab-1.html
templates/download/amd-xilinx/tab-2.html
templates/download/amd-xilinx/tab-3.html
templates/download/risc-v/index.html

Reverts canonical/ubuntu.com#13103

Revert "WD-4158 Revamp amdxilinx "

---

static/sass/styles.scss
templates/ai/roadshow.html

- Copy update on `/ai/roadshow`
- Check out the [demo here](https://ubuntu-com-13117.demos.haus/ai/roadshow) and compare it with the changes requested in the [copy doc](https://docs.google.com/document/d/1CA0GUU6yRB65yfDaKi1dgN8DED2bDAFI2h-swSVtMtg/edit).
- [WD-5923](https://warthogs.atlassian.net/browse/WD-5923)
[WD-5923]: https://warthogs.atlassian.net/browse/WD-5923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-5923 - updates on /ai/roadshow

---

.env
konf/site.yaml
requirements.txt
templates/credentials/exam-no-agreement.html
templates/legal/confidentiality-agreement.html
webapp/app.py
webapp/shop/api/datastore.py
webapp/shop/cred/views.py

Fixes https://warthogs.atlassian.net/browse/WD-3763

Require completion of confidentiality agreement to take exams

---

templates/download/cloud/index.html
templates/shared/_ubuntu_pro_on_public_cloud.html

- Copy update on `/download/cloud`
- Check out [the demo here](https://ubuntu-com-13129.demos.haus/download/cloud) and compare it to the recent changes requested on [the copy doc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit)
- [WD-6025](https://warthogs.atlassian.net/browse/WD-6025)
[WD-6025]: https://warthogs.atlassian.net/browse/WD-6025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-6025 - Update on /download/cloud

---

templates/ceph/index.html

- Update illustrations on `/ceph`
- Check out [the demo](https://ubuntu-com-13123.demos.haus/ceph) here and make sure the illustrations specified in [the task](https://warthogs.atlassian.net/browse/WD-5428) are applied.
- [WD-5428](https://warthogs.atlassian.net/browse/WD-5428)
[WD-5428]: https://warthogs.atlassian.net/browse/WD-5428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-5428 - Update on `/ceph`

---

static/js/src/chart-data.js
templates/about/release-cycle.html

- Update to Kubernetes release cycle figure on `/about/release-cycle`
- Check out [the demo here](url) and compare it to the changes requested in the ["Charmed Kubernetes release cycle" section](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#heading=h.pyzmnshkigfs).
- [WD-6021](https://warthogs.atlassian.net/browse/WD-6021)
[WD-6021]: https://warthogs.atlassian.net/browse/WD-6021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update to Kubernetes release cycle figure

---

templates/security/certifications.html

- Copy update on `/security/certifications`
- Check out [the demo here](https://ubuntu-com-13136.demos.haus/security/certifications) and compare it with the changes requested in [the copy doc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit).
- [WD-6031](https://warthogs.atlassian.net/browse/WD-6031)
[WD-6031]: https://warthogs.atlassian.net/browse/WD-6031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-6031 - Update on `/security/certifications`

---

templates/openstack/consulting.html

- Update datasheet link on `/openstack/consulting`
- Check out [the demo here](https://ubuntu-com-13135.demos.haus/openstack/consulting) and make sure the data sheet attached in [the task](https://warthogs.atlassian.net/browse/WD-4929) is the right one in the link.
- Find copy doc [comment here](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit?disco=AAAAzy-f1wg)
- [WD-4929](https://warthogs.atlassian.net/browse/WD-4929)
[WD-4929]: https://warthogs.atlassian.net/browse/WD-4929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-4929 - Update on `/openstack/consulting`

---

package.json
static/js/src/ai-form.js
static/sass/_pattern_ai.scss
static/sass/styles.scss
templates/ai/index.html
templates/shared/forms/interactive/ai.html
yarn.lock

- Bumped Vanilla version to 4.1 
- Applied content and design changes to landing page as per [doc](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit) and [mock-up](https://www.figma.com/file/sGeCjFvA1kV9Kmvg2S2VBn/23.10-U.com---AI-bubble?node-id=248%3A1446&mode=dev)
- Built new form in the new style as per [copy doc](https://docs.google.com/document/d/1maC3tCmTAgY1G_0nd0aAzw5ZMNeZqbkyawCRMG5Rgxk/edit) and [mock-up](https://www.figma.com/file/sGeCjFvA1kV9Kmvg2S2VBn/23.10-U.com---AI-bubble?node-id=764%3A9597&mode=dev)
- View the site locally in your web browser at: https://ubuntu-com-13138.demos.haus/ai
- Check against design and doc
- Make sure all CTAs work as expected
- Fill out the form and make sure it submits to marketo
Fixes …

Refresh AI landing and add new form

---

templates/security/esm.html

- Copy update on `/security/esm`
- Check out [the demo here](https://ubuntu-com-13145.demos.haus/security/esm) and compare it with the updates requested in [the copy docs](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit)
- [WD-6220](https://warthogs.atlassian.net/browse/WD-6220)
[WD-6220]: https://warthogs.atlassian.net/browse/WD-6220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-6220 Update on /security/esm

---

templates/kubernetes/kubernetes-operations-survey.html

Remove survey according to copy doc
- Check https://ubuntu-com-13151.demos.haus/kubernetes/kubernetes-operations-survey against [copy doc](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit)
Fixes https://warthogs.atlassian.net/browse/WD-6030

WD-6030 K8s ops copy update

---

static/sass/styles.scss
templates/shared/forms/interactive/ai.html

- Fix modal and close button
Fixes #

Fix modal and close button

---

static/sass/styles.scss

Add closing tag

---

navigation.yaml
static/sass/styles.scss
templates/ai/mlflow.html

- Built new page as per [doc](https://docs.google.com/document/d/1kafEsmi8OpaCD-WK4XnIBMgMStHUJNhM86nBN91e4ZI/edit) and [mock-up](https://www.figma.com/file/sGeCjFvA1kV9Kmvg2S2VBn/23.10-U.com---AI-bubble?node-id=1338%3A6595&mode=dev)
- View the site locally in your web browser at: https://ubuntu-com-13149.demos.haus/ai/mlflow
Fixes https://warthogs.atlassian.net/browse/WD-6077

Build /ai/mlflow

---

templates/managed/index.html

- Update on `/managed`
- Check out [the demo here](https://ubuntu-com-13155.demos.haus/managed) and compare it with the updates requested by Rajan on [the copy doc](https://docs.google.com/document/d/19GoMudyrd9Zt1e7kfj-koL-Lt0RGYzWHRPuuKYUPvqw/edit).
- [WD-6241](https://warthogs.atlassian.net/browse/WD-6241)
[WD-6241]: https://warthogs.atlassian.net/browse/WD-6241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-6241 - update on `/managed`

---

static/js/src/chart.js
templates/about/release-cycle.html

- Copy updates on the Ubuntu release cycle.
- Check out [the demo here](https://ubuntu-com-13152.demos.haus/about/release-cycle) and compare it with the changes requested in [the copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
- [WD-6221](https://warthogs.atlassian.net/browse/WD-6221)
[WD-6221]: https://warthogs.atlassian.net/browse/WD-6221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-6221 - update on `/about/release-cycle`

---

templates/security/fips.html

- Change in the text at the bottom of the page according to [copy doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit)
https://warthogs.atlassian.net/browse/WD-6281

[WD-6281] add copy update for /security/fips page

---

templates/automotive/buyers-guide/_form.html

- simply update the automotive buyers guide pdf link
- Go to /automotive/buyers-guide
- full in the form and see it lands you on the PDF

Update the automotive buyers guide pdf link

---

konf/site.yaml

- Schedule shop maintenance for September 25, 3am to 6am.
- Go to /pro/status the notification should confirm

Schedule shop maintenance

---

templates/openstack/features.html

[Missed link to update](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit)
- Go to https://ubuntu-com-13178.demos.haus/openstack/features Check "Build your own production-grade cloud" CTA has the new link.
Fixes #

Update openstack features link

---

templates/real-time/base_real-time.html
templates/real-time/index.html
templates/shared/forms/interactive/real-time.html

- Build the real-time kernel page (`/real-time`)
- Check out the [demo here](https://ubuntu-com-13172.demos.haus/real-time) and compare it with [the design](https://www.figma.com/file/Cr1S07Ivk632jniBAG89S8/23.10-U.com---Real-time-Ubuntu?type=design&node-id=30-1306&mode=design&t=oK05jG8BKFjcI2Vg-0) and [the copy doc](https://docs.google.com/document/d/1g9G3r4eJRPGZy5Dyz_GJhUz_iqNn-5QUhG43scnBnUA/edit).
- [WD-5415](https://warthogs.atlassian.net/browse/WD-5415)
[WD-5415]: https://warthogs.atlassian.net/browse/WD-5415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-5415 - Build kernel real-time page at /real-time

---

konf/site.yaml

- Set shop to come down in Oct 2nd from 3am to 6am.
- Go to https://ubuntu-com-13186.demos.haus/pro/status you should see it scheduled.

Set show down in October 2nd

---

templates/landscape/install.html

- Updated according to [copy docs](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit)
- Check https://ubuntu-com-13179.demos.haus/landscape/install against [copy](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit)
Fixes https://warthogs.atlassian.net/browse/WD-6422

Remove juju install section and other copy updates

---

templates/landscape/managed.html

- Copy update on `/landscape/managed`
- Add meta image
- Check out [the demo here](https://ubuntu-com-13195.demos.haus/landscape/managed) and compare it with the changes requested in [the copy doc](https://docs.google.com/document/d/1MycPWcmMveCZxrGtn7ASc0myWNxPzLTciHfQIA6kPZ4/edit#heading=h.rzaw32crpetv).
- [WD-6242](https://warthogs.atlassian.net/browse/WD-6242)
[WD-6242]: https://warthogs.atlassian.net/browse/WD-6242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-6242 - update on `/landscape/managed`

---

.github/workflows/cypress-pr.yaml
tests/cypress/cypress.json
tests/cypress/integration/pro/checkout_spec.js
tests/cypress/integration/pro/subscriptions_spec.js
tests/cypress/support/commands.js

- Try different changes in Cypress settings to check if it helps with fixing failing CI pipelines
- Check the Cypress related CI pipelines

increase timeouts in Cypress tests to fix the failing pipeline issue

---

templates/openstack/compare.html

- Applied copy update as per [doc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit)
- View the site locally in your web browser at: https://ubuntu-com-13220.demos.haus/openstack/compare
Fixes https://warthogs.atlassian.net/browse/WD-6616

[copy update] /openstack/compare

---

templates/financial-services/index.html

- Updated the UA link to Pro in financial-services
- Check the code matches the request in the [copy doc](https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit?disco=AAAA6bwCke0)
Fixes https://warthogs.atlassian.net/browse/WD-6601

WD-6601 - Replace Advantage link with Pro on financial-services

---

static/sass/styles.scss
templates/pro/index.html

- Update /pro 
- Go to https://ubuntu-com-13104.demos.haus/pro
- Compare page against [Figma](https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?type=design&node-id=4091-20096&mode=design&t=KcoJMipE5vifQ0h8-0) and [copy doc](https://docs.google.com/document/d/1XidZq045nJDM5vzfB5KJCpH3AqOERvPOeayuqUKfNso/edit#heading=h.i6h9ir8nv0px) -> Page on Demo might be different from design on Figma as PdM requested some changes.
Fixes …

Update pro page 

---

templates/download/raspberry-pi/index.html

- Redesign the section according to [Figma](https://www.figma.com/file/wGMqsc7u32nWdKQQ9Rv8fP/Ubuntu.com-rebranding?type=design&node-id=1-786&mode=design&t=MKZwPwlqKzZc8g95-0)
[WD-6705](https://warthogs.atlassian.net/browse/WD-6705)
Fixes #
[WD-6705]: https://warthogs.atlassian.net/browse/WD-6705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-6705 - update /downloads/raspberry-pi

---

templates/desktop/developers.html
templates/download/index.html

- Added the logo section class to the AI image
- Updated the meta image mascot on the download page
- Open the demo and check the logos on the download/desktop page
- Enter the demo link to the /download page in https://www.opengraph.xyz/ and see the meta image is ok

Some small 23-10 release fixes

---

templates/data/mongodb/index.html

- Updated datasheet as per [doc](https://docs.google.com/document/d/1_JuxbWsqTeQRRmSL0sCpM3alabr06WX4Cb-tt1BBW_I/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/data/mongodb
- See that the link has been updated
Fixes https://warthogs.atlassian.net/browse/WD-6065

Update datasheet link

---

static/js/src/cve/cve.js
templates/security/cve/index.html

Issue #13093 & #12478 have been resolved and search works on enter press

Issue #13093 & #12478 resolved

---

templates/download/amd/index.html
templates/download/amd/tab-1.html
templates/download/amd/tab-2.html
templates/download/amd/tab-3.html
templates/download/amd/tab-4.html

- Applied copy updates as per [doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- Drive by: Fixed indentation where needed
- View the site locally in your web browser at: https://ubuntu-com-13226.demos.haus/download/amd
- Check each tab against requested changes
Fixes https://warthogs.atlassian.net/browse/WD-6572

[copy update] /download/amd

---

templates/kubernetes/docs/explain-cloud.md
templates/kubernetes/docs/how-to-clouds.md
templates/kubernetes/docs/how-to-cni.md
templates/kubernetes/docs/how-to-containers.md
templates/kubernetes/docs/how-to-ha.md
templates/kubernetes/docs/how-to-install.md
templates/kubernetes/docs/how-to-operate.md
templates/kubernetes/docs/how-to-security.md
templates/kubernetes/docs/shared/_side-navigation.md

- Add new diataxis navigation to the side menu
- Add index pages for the subtopics in the How to section

K8s new navigation

---

templates/pro/index.html

- Fix `a` tag is not wrapping text properly and it's causing Accessibility checks failing 
- Go to `/pro`
- Check accessibility check is passing

Fix a link

---

templates/internet-of-things/smart-displays.html

- Updated page according to [copydoc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/)
- Check whether the page is according to copy doc
[WD-6720](https://warthogs.atlassian.net/browse/WD-6720)
Fixes #
[WD-6720]: https://warthogs.atlassian.net/browse/WD-6720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-6720 - update /internet-of-things/smart-displays

---

templates/openstack/features.html

- Update text in https://ubuntu-com-13278.demos.haus/openstack/features according to [copydoc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit)
- [demo link](https://ubuntu-com-13278.demos.haus)
- Check whether link and text are correct
[WD-6937](https://warthogs.atlassian.net/browse/WD-6937)
Fixes #
[WD-6937]: https://warthogs.atlassian.net/browse/WD-6937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

WD-6937 - update text in /openstack/features

---

requirements.txt

- Bump the version of discourse module to v5.4.4
- Go to /landscape/docs/quickstart-deployment
- See that works

Bump the version of discourse module to v5.4.4

---

templates/download/mediatek-genio/index.html

Update the Mediatek Genio contact us link
- Open the demo and click the link

Update the Mediatek Genio contact us link

---

templates/openstack/what-is-openstack.html

- Updated vmware link and text at https://ubuntu-com-13293.demos.haus/openstack/what-is-openstack
- [copydoc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#heading=h.gueheetg08r2)
- Check out this feature branch [demo link](https://ubuntu-com-13293.demos.haus/)
- Check vmware link and text according to copydoc
[WD-7018](https://warthogs.atlassian.net/browse/WD-7018)
Fixes #
[WD-6863]: …

WD-7018 - update vmware link on /openstack/what-is-openstack

---

konf/site.yaml

Call google APIs over HTTP on credentials pods.

Call google APIs over HTTP on credentials pods

---

.eslintrc.js
static/js/src/certified-search-results.js
static/js/src/tests/intlTelInput.test.js
templates/certified/search-results.html
templates/certified/shared/_category-filters.html
templates/certified/shared/category-search-results.html
templates/certified/vendors/vendor.html
templates/download/desktop/thank-you.html
tests/cassettes/TestCertification.test_filters_json.yaml
tests/test_certification.py
webapp/certified/views.py

- Dynamically load filters on /certified pages
- Go to https://ubuntu-com-13088.demos.haus/certified?q=nvidia 
- Click on more than 1 category filter
- Select vendor and release
- Click apply, check that it works and results include the filters you selected.
- Check server, click on "Show all vendors", uncheck server and click on "Show all vendors", the new filters for vendors should update accordingly.
- Go to https://ubuntu-com-13088.demos.haus/certified?q=g5 
- Click on only one category filter
- Select vendor and release
- Click apply, check that it goes to the selected `certified/<category>` page
- Go to https://ubuntu-com-13088.demos.haus/certified/laptops and click on the "Desktop" category filter
It should take you to the general search page.
- Go to …

WD-4664 Certified filters 

---

static/js/src/dynamic-forms.js

- Updates `dynamic-form.js` to add a loading state and disable the submit button on form submission
- Go to https://ubuntu-com-13325.demos.haus/ and find any form, fill in and submit it
- See that the button has the [vanilla state](https://vanillaframework.io/docs/patterns/buttons) and is disabled
- Repeat for different forms across u.com
Fixes https://warthogs.atlassian.net/browse/WD-6608

Add loading state to modal form buttons

---

templates/base_index.html

- Update link on homepage based on [copydoc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)
- Check out demo https://ubuntu-com-13319.demos.haus/
Fixes https://warthogs.atlassian.net/browse/WD-7010

Update link on homepage

---

navigation.yaml
package.json
templates/automotive/resources.html
templates/shared/forms/interactive/newsletter-opt-in.html
yarn.lock

- Build /automotive/resources page based on [copydoc](https://docs.google.com/document/d/17ofQfYbMlTsjdpB3JJru5mckGeLFXMAxRbHvIL4TrOE/edit#heading=h.7etr2bdzumur) and [figma design](https://www.figma.com/file/u8mPLR8FH2j7p3YCxQBQQe/23.10-U.com---%2Fautomotive%2Fresources-(WD-4060)?type=design&node-id=0-1&mode=design&t=5FYZ6uwGduKHxLql-0)
- Go to https://ubuntu-com-13276.demos.haus/automotive/resources and compare against the copydoc and design
Fixes https://warthogs.atlassian.net/browse/WD-4062

Build /automotive/resources page

---

templates/shared/forms/interactive/storage.html

- Updated get in touch form at https://ubuntu-com-13292.demos.haus/ceph#get-in-touch
- [copydoc](https://docs.google.com/document/d/1Pfay_PfsE7Tw8gU82wENRCcCUEXbe2gf804uGzM_PqY/edit)
- Check out this feature branch [demo link](https://ubuntu-com-13292.demos.haus/)
- Check the form according to copydoc
[WD-6863](https://warthogs.atlassian.net/browse/WD-6863)
Fixes #
[WD-6863]: https://warthogs.atlassian.net/browse/WD-6863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

WD-6863 - update get in touch form

---

templates/containers/index.html

- Applied refresh as per [doc](https://docs.google.com/document/d/1OtyfNeA--EJgpgvDzqcbJ8jqa6d9H5H9xyxHNxcKXvc/edit#heading=h.eto59uxtlv76) and [design](https://www.figma.com/file/YfNc8KmYqa2e7JgbFo6lXa/24.04-U.com---%2Fcontainers?node-id=0%3A1&mode=dev) 
- View the site locally in your web browser at: https://ubuntu-com-13350.demos.haus/containers
Fixes https://warthogs.atlassian.net/browse/WD-6346

Apply /containers refresh

---

templates/ai/index.html

Update logos according to [copy docs](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit#heading=h.n4ma01lh3jac)
Logos: https://assets.ubuntu.com/manager?tag=kubeflow-page-logos
- Go to https://ubuntu-com-13345.demos.haus/ai and check logos are updated according to [copy doc](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit#heading=h.n4ma01lh3jac)
Fixes https://warthogs.atlassian.net/browse/WD-6585

Update logos on AI page

---

templates/internet-of-things/index.html

**Note: Waiting on images for the 'Our products' section, requested in the doc. can go live without**
- Refreshes /internet-of-things based on the [copydoc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit)
Fixes https://warthogs.atlassian.net/browse/WD-6519

Refresh /internet-of-things

---

templates/internet-of-things/appstore.html
templates/observability/managed.html
templates/openstack/features.html
templates/robotics/what-is-ros.html
templates/telco/osm/onboarding-network-functions.html

- Refresh /internet-of-things/appstore based on [copydoc](https://docs.google.com/document/d/1CKwmPDDtXOIgw-jSZFwzP-qLMc_rS_dUACpHQXlg0fA/edit)
Fixes https://warthogs.atlassian.net/browse/WD-6520

Refresh /internet-of-things/appstore

---

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx

- Update ubuntu.com links to point to new portal
Fixes #https://warthogs.atlassian.net/browse/WD-7849

Update links of the support portal

---

templates/support/contact-us.html

- Applied update as per [doc](https://docs.google.com/document/d/1rWgWFGtal7ddDAkIOKtA6M3wXKd7gX-ABQtyhwbqjyk/edit) (ignore the marketo id discussion, it wasn't within the scope of this ticket. I'll make a follow-up issue once we get an answer from marketing)
- View the site locally in your web browser at: https://ubuntu-com-13399.demos.haus/support/contact-us
- Check against doc
Fixes https://warthogs.atlassian.net/browse/WD-7895

/support/contact-us copy update

---

templates/telco/index.html
templates/telco/shared/_telco-logo-section.html

- Applied content refresh as per [doc](https://docs.google.com/document/d/1a3otoXCbXtddJG2HCnYIIHJiDxvG-pzFPtLobVB4-vw/edit)
- View the site locally in your web browser at: https://ubuntu-com-13395.demos.haus//telco
- Check against doc
Fixes https://warthogs.atlassian.net/browse/WD-6454

/telco content refresh

---

templates/telco/index.html

- Update CTAs to use modal and add diagram alt text, as per [doc](https://docs.google.com/document/d/1a3otoXCbXtddJG2HCnYIIHJiDxvG-pzFPtLobVB4-vw/edit)
- View the site locally in your web browser at: https://ubuntu-com-13404.demos.haus/telco 
- See that the CTAs in the hero and footer both route to a modal
- Check alt text against doc 
Fixes https://warthogs.atlassian.net/browse/WD-7944

/telco post release clean-up

---

requirements.txt
tests/cassettes/TestBlogNotice.test_blog_date_notice.yaml
tests/cassettes/TestRoutes.test_blog.yaml

- Revert the blog module update
- Open the demo and go to /blog
- Check the "Performance engineering on Ubuntu leaps" post is there

Revert the blog module update

---

templates/shared/forms/interactive/confidential-computing.html

lowercasing field attributes to avoid breaking marketo sync

Update confidential-computing form company field

---

templates/engage/index.html

Add fixed resource type list as agreed with stakeholders. This should fix duplications and redundant resource types.
- Go to https://ubuntu-com-13432.demos.haus/engage
- Play around with the resource type and make sure it filters the engage pages correctly.
Fixes https://warthogs.atlassian.net/browse/WD-5803?atlOrigin=eyJpIjoiNTRmNWYxMzc2NmI0NGYzNGI0N2IyOWNkYmNlMjVjY2UiLCJwIjoiaiJ9

Add fixed list of resource types

---

templates/automotive/resources.html

Update automotive link, as [per request in the copy doc](https://docs.google.com/document/d/17ofQfYbMlTsjdpB3JJru5mckGeLFXMAxRbHvIL4TrOE/edit).
- Check that https://ubuntu-com-13446.demos.haus/automotive/resources in the "Whitepapers" section the new link has been updated.
Fixes https://warthogs.atlassian.net/browse/WD-8012

Update link for automotive resources

---

templates/pro/index.html

- Updates 'defence' to 'defense' based on [copdoc](https://docs.google.com/document/d/1XidZq045nJDM5vzfB5KJCpH3AqOERvPOeayuqUKfNso/edit) comment
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?selectedIssue=WD-8179

Use american spelling of defense on /pro

---

templates/gov/index.html

- Update copy as per [doc](https://docs.google.com/document/d/1umM1XMEzqeXklPkyCjDr98Q-RvwCcNNXgwNwfLoynTo/edit#heading=h.h8lo4gnw0yf)
- View the site locally in your web browser at: https://ubuntu-com-13454.demos.haus/gov
Fixes https://warthogs.atlassian.net/browse/WD-8138

/gov copy updates

---

templates/managed/index.html

Redesign [managed services page](https://ubuntu-com-13445.demos.haus/managed) according to [figma](https://www.figma.com/file/Qj0DByXnYYUn8BMtbB2OiA/24.04-Managed?type=design&node-id=0-1&mode=design&t=vHKZ7F3He1R87Ah5-0) and [copy doc](https://docs.google.com/document/d/19GoMudyrd9Zt1e7kfj-koL-Lt0RGYzWHRPuuKYUPvqw/edit)
- [demo link](https://ubuntu-com-13445.demos.haus/managed)
- [copy doc](https://docs.google.com/document/d/19GoMudyrd9Zt1e7kfj-koL-Lt0RGYzWHRPuuKYUPvqw/edit)
- Check that the page is correct according to the design and copy doc …

WD-7763 - redesign /managed page

---

templates/robotics/index.html

- Apply copy update as per [doc](https://docs.google.com/document/d/1JNFk2C0shH3DapKuJM8X0QfAiD1RzHvXoydn8P9mEMg/edit)
- View the site locally in your web browser at: https://ubuntu-com-13462.demos.haus/robotics
Fixes https://warthogs.atlassian.net/browse/WD-8228

/robotics copy update

---

templates/shared/forms/interactive/supermicro.html
templates/supermicro/base_supermicro.html
templates/supermicro/contact-us.html
templates/supermicro/index.html
webapp/app.py

- A new page for Supermicro at https://ubuntu-com-13456.demos.haus/supermicro according to [copy doc](https://docs.google.com/document/d/192QGE7qzo8nQ-XkyhWIDckBkKHo8kf9rhAFgFVukTic/edit)
- A contact form for Supermicro page according to its [copy doc ](https://docs.google.com/document/d/1YO56CHFtMPccTKpizd9GG_aA5UEqGqdz7jlZ63KFnek/edit)
- [Figma design](https://www.figma.com/file/WN8pLY33ZFimTeTx56INuw/Ubuntu.com%2Fsupermicro---partner-page?type=design&node-id=1-953&mode=design&t=7vUc2oPOSqyyu30Z-0) of the page
- Navigate to https://ubuntu-com-13456.demos.haus/supermicro …

[WD-8035] supermicro page

---

static/js/src/navigation.js
static/sass/_pattern_navigation.scss

Fixes the following QA bugs:
When you navigate to the WSL page on small screens. The Menu no longer works.
When using the navigation go to All Canonical > About and click any of the links such as Blog and none of them work.
If you go to /ai and hit search it's black text if black background.
On small screen, none of the quick links work when clicked.
- Ensure the above bugs are fixed
Fixes https://warthogs.atlassian.net/browse/WD-8295

Minor bug fixes

---

static/js/src/advantage/subscribe/react/UAPurchase.tsx
static/js/src/advantage/subscribe/react/components/Form/Form.tsx
static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx

- Fix ubuntu pro iot devices selector
- Go to /pro/subscribe or  https://ubuntu-com-13470.demos.haus/pro/subscribe
- Select IoT and devices in the step 2
- Compare page against [copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit)
Fixes #https://warthogs.atlassian.net/browse/WD-8288

Fix ubuntu pro iot devices selector

---

static/sass/styles.scss
templates/desktop/index.html
templates/shared/contextual_footers/_desktop.html

- Applied refresh as per [design](https://www.figma.com/file/wLOtPeQhAiExhQCwKYhi3H/24.04-U.com---desktop-(rebranding)?node-id=65%3A2706&mode=dev) and [doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit)
- View the site locally in your web browser at: https://ubuntu-com-13468.demos.haus/desktop
- Check against design and doc
Fixes https://warthogs.atlassian.net/browse/WD-7617

Apply desktop landing refresh

---

templates/support/index.html

- Added content changes in https://ubuntu-com-13477.demos.haus/support according to [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
- Navigate to https://ubuntu-com-13477.demos.haus/support and check content changes
Fixes https://warthogs.atlassian.net/browse/WD-8305

[WD-8305] change content in few places on /support

---

.github/workflows/live-links.yaml

- Instructed the links on live check to ignore styles and there are some deciding issues internal to the project.
- Check the code change looks right and we will see tomorrow once merged.

Ignore checking the styles

---

templates/kubernetes/docs/1.22/upgrading.md
templates/kubernetes/docs/1.23/charm-docker-registry.md
templates/kubernetes/docs/auth.md

Fix a number of outdated links

Fix 404s in K8s

---

static/sass/styles.scss
templates/about/release_cycles/ubuntu-eol.html
templates/desktop/developers.html

**Note: There are separate PRs for the changes to the [D3 graphs ](https://warthogs.atlassian.net/browse/WD-8270)and for the logic needed to allow pagination in the [latest-news module](https://warthogs.atlassian.net/browse/WD-8426)**
- Applies the [content](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit) and [design](https://www.figma.com/file/wLOtPeQhAiExhQCwKYhi3H/24.04-U.com---desktop-(rebranding)?type=design&node-id=1-2&mode=design&t=Fb5N2muecteluj8U-0) changes
- Go to https://ubuntu-com-13491.demos.haus/desktop/developers
- Compare against design and copydoc
- Check on different sized screens
Fixes https://warthogs.atlassian.net/browse/WD-7733

Refresh desktop/developers

---

webapp/shop/cred/views.py

- Added sentry capture to capture exceptions masked in the backend
Fixes #

bug:added sentry capture to exception blocks for cred

---

templates/pro/index.html

I interpret 'PostrgreSQL' as a typo for 'PostgreSQL'.

edit index.html: replace PostrgreSQL -> PostgreSQL

---

templates/support/index.html

Update /support according to copy doc
- [demo link](https://ubuntu-com-13524.demos.haus/support)
- [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
[WD-8578](https://warthogs.atlassian.net/browse/WD-8578)
Fixes #
[WD-8578]: https://warthogs.atlassian.net/browse/WD-8578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8578 - copy update on /support

---

static/sass/styles.scss
templates/server/hyperscale.html
templates/server/index.html
templates/server/partial/_server-footer.html

*Please review [/server/hyperscale](https://github.com/canonical/ubuntu.com/pull/13521) first*
- Refreshes /server based on [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/24.04-U.com---server-(rebranding)?node-id=0%3A1&mode=dev) and [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit) changes
- Moves the footer into a template
- Fly by: Adds some spaces to style.scss
- Go to [the demo]()
- Check that it matches the [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/24.04-U.com---server-(rebranding)?node-id=0%3A1&mode=dev) and the [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit)
- Check the page on large, medium and small screens
- Check the code abides by …

Refresh /server page

---

static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx

- Copy update according to this [copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit)
- Compare page against [copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit)

Update pro selector page

---

meganav.yaml

- Incorporate early "uncontroversial" suggestions from PMs and marketing to the [meganav copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit).
Fixes #

Incorporate PMs feedback to meganav (day 1)

---

.github/workflows/robotics-docs-links.yaml

- Add a workflow to check links of the robotics documentation.
- The CI ran successfully on [my fork](https://github.com/Guillaumebeuzeboc/ubuntu.com/actions/runs/7724568560/job/21057212905).

feat(robotics-docs-links): add GH workflow

---

templates/server/index.html

*Please review [/server/hyperscale](https://github.com/canonical/ubuntu.com/pull/13521) first*
- Refreshes /server based on [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/24.04-U.com---server-(rebranding)?node-id=0%3A1&mode=dev) and [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit) changes
- Moves the footer into a template
- Fly by: Adds some spaces to style.scss
- Go to [the demo]()
- Check that it matches the [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/24.04-U.com---server-(rebranding)?node-id=0%3A1&mode=dev) and the [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit)
- Check the page on large, medium and small screens
- Check the code abides by …

Rebrand /server

---

static/sass/styles.scss
templates/server/hyperscale.html
templates/server/index.html
templates/server/partial/_server-footer.html

*this will act as the feature branch for the server updates*
- Refresh /server/hyperscale based on [copydoc](https://docs.google.com/document/d/1f56CCzH519lIVa4KvxDt0QpxYFMK-bMdVlKo4TvPSIk/edit) and [design](https://www.figma.com/file/Kw2SwMkH49tN54NbnKs5dt/U.com---server-(rebranding)?type=design&node-id=1-10&mode=design&t=ozrDP1wwHOGlBNCq-0)
- I used [this](https://docs.google.com/document/d/1kq0SPv-PAIfL9nHGxgNDpHhr5OplE2iNaZZiqG4RT48/edit#heading=h.qr5jy1sbfmj) as reference for the contextual footer
- Check [the demo](https://ubuntu-com-13521.demos.haus/server/hyperscale) matches the [copydoc](https://docs.google.com/document/d/1f56CCzH519lIVa4KvxDt0QpxYFMK-bMdVlKo4TvPSIk/edit) and design [design](https://docs.google.com/document/d/1f56CCzH519lIVa4KvxDt0QpxYFMK-bMdVlKo4TvPSIk/edit)
- …

Refresh /server/hyperscale

---

templates/blog/newsletter-form.html
templates/download/desktop/thank-you.html
templates/templates/base.html

Update newsletter signup form according to copy doc
- [demo link](https://ubuntu-com-13545.demos.haus/blog)
- [copy doc](https://docs.google.com/document/d/1VrmfcndrIT8E0K2cLqBpYPNhXECtte5fbLCNy8XcCaw/edit)
[WD-8434](https://warthogs.atlassian.net/browse/WD-8434)
Fixes #
[WD-8434]: https://warthogs.atlassian.net/browse/WD-8434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8434 - update newsletter signup form

---

templates/desktop/organisations.html

- Updated links flagged in https://github.com/canonical/ubuntu.com/pull/13541#discussion_r1483645929 as per [doc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit)
- See that the links are updated correctly 
Fixes #

/desktop/organisations copy update

---

webapp/views.py

- Updates `get_user_country_by_ip` def to use 'X-Forward-For' for fetching the user IP. This is to see if it will get around any proxys we have in place as currently the user IP is read from that instead of the actual user IP.
- Check that you IP is correctly identified in forms
Fixes https://warthogs.atlassian.net/browse/WD-1173

Fetch user IP with 'X-Forward-For'

---

templates/core/stories.html

Update /stories page according to copydoc
- [demo link](https://ubuntu-com-13578.demos.haus/core/stories)
- [copy doc](https://docs.google.com/document/d/1mXnYnpaCJznDLtYn9Q74aVeEI3iFxVOMzF0pdL7wdu0/edit?usp=sharing)
[WD-8723](https://warthogs.atlassian.net/browse/WD-8723)
Fixes #
[WD-8723]: https://warthogs.atlassian.net/browse/WD-8723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8723 - update /stories page

---

meganav.yaml

- Incorporate further feedback from PMs and marketing from [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit) (ignore open discussions).
Fixes #13569
Fixes #

Meganav content updates, week 2

---

templates/download/qualcomm-dragonboard-410c.html
templates/download/shared/_first-boot-setup.html

- Go to https://ubuntu-com-13588.demos.haus/download/qualcomm-dragonboard-410c
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?selectedIssue=WD-8800

WD-8800 Qualcomm dragonboard rebrand

---

templates/download/up-squared-iot-grove-server.html

- Go to https://ubuntu-com-13596.demos.haus/download/up-squared-iot-grove-server check against content on prod.
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?selectedIssue=WD-8801

WD-8801 Up squared IoT grove server rebrand

---

ARCHITECTURE.md
meganav.yaml
releases.yaml
templates/about/release_cycles/kernel-eol.html
templates/download/raspberry-pi/index.html
templates/download/risc-v/tab-1.html
templates/download/risc-v/tab-2.html
templates/download/risc-v/tab-3.html
templates/download/risc-v/tab-4.html
templates/download/risc-v/tab-5.html
templates/download/risc-v/tab-6.html

PR in preparation for 22.04.4. I will be releasing the images in a few hours.
Fixes #

Update releases.yaml for 22.04.4.

---

static/js/src/chart-data.js
templates/about/release_cycles/kernel-eol.html
templates/download/raspberry-pi/index.html
templates/shared/_kernel-support-schedule.html

- Replace all instances of 22.04.3 with .4

Update all instances of 22.04.3 with .4

---

templates/about/release_cycles/kernel-eol.html

- Fix the Kernel versions on release cycle page

Fix the Kernel versions on release cycle page

---

templates/legal/data-privacy/webinar.md

- Applied updates as per [doc](https://docs.google.com/document/d/1wMKqustrdcGK-yzGGe9we6nyHDvLUPukQaPpMA5T6wk/edit)
- View the site locally in your web browser at: https://ubuntu-com-13606.demos.haus/legal/data-privacy/webinar
Fixes https://warthogs.atlassian.net/browse/WD-9012

Copy update /legal/data-privacy/webinar

---

tests/playwright/helpers/mockData.ts
tests/playwright/helpers/utils.ts
tests/playwright/tests/pro/checkout.spec.ts

- This test can be running only locally. 
- Test checkout purchase
how to run tests locally
- Save [this credentials](https://pastebin.canonical.com/p/m3PyRkf38P/) in `.env.local`
- Go to `playwright.config.ts` and comment out `testIgnore: '**\/pro/**',`
- Command `dotrun`
- Command `yarn playwright test /tests/playwright/tests/pro/checkout.spec.ts --ui ` or `yarn playwright test /tests/playwright/tests/pro/checkout.spec.ts` (`yarn playwright test` if you want to run all the playwright tests)
- Check tests pass locally
Fixes #https://warthogs.atlassian.net/browse/WD-8055, https://warthogs.atlassian.net/browse/WD-7656

Playwright Test - checkout purchase

---

templates/legal/modern-slavery-statement/_base_markdown.html
templates/legal/modern-slavery-statement/index.md

Update modern slavery statement according to copy doc and pdf
- [demo link](https://ubuntu-com-13623.demos.haus/legal/modern-slavery-statement)
- [copy doc](https://docs.google.com/document/d/16q1jDEr_ArWdCnWzEVuXmC66deXeCnuEHy2G_jX0hqE/edit)
- Check that the page is correctly updated according to copy doc and pdf
[WD-9155](https://warthogs.atlassian.net/browse/WD-9155)
Fixes #
[WD-9155]: https://warthogs.atlassian.net/browse/WD-9155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9155 - update modern slavery statement

---

templates/internet-of-things/nvidia/contact-us.html

- Fixed typo as per [doc](https://docs.google.com/document/d/1znVFFLSyTmDwCplvloGAlEI3p_dpGH8v82hbYzVfz0o/edit)
- View the site locally in your web browser at: https://ubuntu-com-13625.demos.haus/internet-of-things/nvidia/contact-us
- See that the change has been implemented
Fixes https://warthogs.atlassian.net/browse/WD-9207

/iot/nvidia/contact-us typo fix

---

templates/support/index.html

Remove fabric from /support
- [demo link](https://ubuntu-com-13631.demos.haus/support)
- [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
[WD-9215](https://warthogs.atlassian.net/browse/WD-9215)
Fixes #
[WD-9215]: https://warthogs.atlassian.net/browse/WD-9215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9215 - remove fabric from /support

---

templates/ai/mlops.html

Update /ai/mlops page
- [demo link](https://ubuntu-com-13632.demos.haus/ai/mlops)
- [copy doc](https://docs.google.com/document/d/18AMX_-3zjBNUNGr0X5QtjKhsUzAc2k8VM1-opZEGh4k/edit)
[WD-9292](https://warthogs.atlassian.net/browse/WD-9292)
Fixes #
[WD-9292]: https://warthogs.atlassian.net/browse/WD-9292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9292 - update /ai/mlops

---

templates/pricing/devices.html

Update /pricing/devices page according to copy doc
- [demo link](https://ubuntu-com-13622.demos.haus/pricing/devices)
- [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit)
[WD-8881](https://warthogs.atlassian.net/browse/WD-8881)
Fixes #
[WD-8881]: https://warthogs.atlassian.net/browse/WD-8881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8881 - page refresh /pricing/devices

---

templates/landscape/install.html

Update /lanscape/install page
- [demo link](https://ubuntu-com-13634.demos.haus/landscape/install)
- [copy doc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#heading=h.ie7rncycaa0p)
[WD-9297](https://warthogs.atlassian.net/browse/WD-9297)
Fixes #
[WD-9297]: https://warthogs.atlassian.net/browse/WD-9297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9297 - update /landscape/install

---

templates/cloud/index.html

- Updated copy as per [doc](https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit) 
- View the site locally in your web browser at: https://ubuntu-com-13643.demos.haus/cloud
- See that the requested changes were made
Fixes https://warthogs.atlassian.net/browse/WD-9322

/cloud copy update

---

webapp/shop/api/trueability/api.py

- Change X_API-KEY to X-API-KEY

Fix( TA API): Change X_API-KEY to X-API-KEY

---

templates/kubernetes/index.html

- Applied refresh as per [design](https://www.figma.com/file/wGMqsc7u32nWdKQQ9Rv8fP/Ubuntu.com-rebranding?node-id=202%3A408&mode=dev) and [doc](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit)
- View the site locally in your web browser at: https://ubuntu-com-13638.demos.haus/k8s
Fixes https://warthogs.atlassian.net/browse/WD-8913

/k8s landing refresh

---

static/js/src/static-forms.js
templates/shared/_pro-contact-us-form.html
templates/shared/forms/_country.html

- Update Ubuntu Pro contact form according to [copy doc](https://docs.google.com/document/d/1X1Qx5cimbU7D_xQKnm3se9gRDFcRDEaX5fkGR42b3yU/edit)
- Go to https://ubuntu-com-13661.demos.haus/contact-us/form?product=pro and check against [copy doc](https://docs.google.com/document/d/1X1Qx5cimbU7D_xQKnm3se9gRDFcRDEaX5fkGR42b3yU/edit)
- Fill out and submit the form and make sure no errors appear
- For devs: check payload submits correctly with the new fields
Fixes https://warthogs.atlassian.net/browse/WD-8472

Update Ubuntu pro contact form

---

templates/credentials/index.html
templates/credentials/self-study.html
templates/credentials/syllabus.html
webapp/shop/cred/syllabus.json

- Check copy matches the document on `/credentials/syllabus` and `/credentials/study-guide`
Fixes https://warthogs.atlassian.net/browse/WD-9635

Copy updates to credentials syllabus and study guide

---

templates/credentials/exam-no-agreement.html
templates/credentials/your-exams.html

- Pre-fill cue email when redirecting to confidentiality agreement

Pre-fill cue email when redirecting to confidentiality agreement

---

templates/download/server/arm.html

- Check https://ubuntu-com-13668.demos.haus/download/server/arm against [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit)
- Check against design screenshot below
Fixes https://warthogs.atlassian.net/browse/WD-9427

Rebrand server arm download page wd 9427

---

templates/download/amd/tab-1.html

_To be merged March 19th_
- Applied copy changes as per [doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- **NOTE: Pdm accepted most of the suggested edits already, you can double check what she requested by seeing the edit history, specifically the March 13th version** 
- View the site locally in your web browser at: https://ubuntu-com-13663.demos.haus/download/amd
Fixes https://warthogs.atlassian.net/browse/WD-9530

/download/amd copy update

---

templates/support/index.html

- Compare with comments in [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
Fixes https://warthogs.atlassian.net/browse/WD-9819

WD-9819 copy update

---

Dockerfile
templates/download/server/arm.html
templates/download/server/s390x.html

- Check https://ubuntu-com-13671.demos.haus/download/server/s390x against [copy docs](https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit)
Fixes https://warthogs.atlassian.net/browse/WD-9483

WD-9843 Rebrand server s390x

---

templates/download/server/thank-you-s390x.html

Rebrand /download/server/thank-you-s390x - fix heading classes.
Last section will be redesigned separately
- [demo link](https://ubuntu-com-13692.demos.haus/download/server/thank-you-s390x)
- [figma](https://www.figma.com/file/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=522%3A29620&mode=dev)
[WD-9490](https://warthogs.atlassian.net/browse/WD-9490)
[WD-9490]: https://warthogs.atlassian.net/browse/WD-9490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9490 - update /download/server/thank-you

---

templates/credentials/redeem_with_form.html

- Updated Vanilla Framework to 4.9.0
- Updated Suru on [/credentials/redeem](https://ubuntu-com-13698.demos.haus/credentials/redeem)
Fixes [#WD-9914](https://warthogs.atlassian.net/browse/WD-9914)

Replaced old suru with new suru

---

templates/kubernetes/resources.html

- Updated copy as per [doc](https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit)
- View the site locally in your web browser at: https://ubuntu-com-13705.demos.haus/kubernetes/resources
- See that link routes to the correct engage page
Fixes https://warthogs.atlassian.net/browse/WD-10011

/k8s/resources update resource link

---

templates/download/mediatek-genio/index.html
templates/download/mediatek-genio/tab-1.html
templates/download/mediatek-genio/tab-2.html
templates/download/mediatek-genio/tab-3.html
templates/download/mediatek-genio/tab-4.html

Add tab to  /download/mediatek-genio
- [demo link](https://ubuntu-com-13703.demos.haus/download/mediatek-genio)
- [coopy doc](https://docs.google.com/document/d/1Tm3cVVkWkzriQQ7kgbgKfKoeGZaew1M5OMbpLPSDGIc/edit)
- Check that the page is correct according to copy doc
[WD-9953](https://warthogs.atlassian.net/browse/WD-9953)
[WD-9953]: https://warthogs.atlassian.net/browse/WD-9953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9953 - add new tab to /download/mediatek-genio

---

webapp/shop/api/ua_contracts/api.py
webapp/shop/decorators.py

- Send X-Forwarded-For in UA-Contracts API requests.
- Run this branch
- Check the logs and see that after a UA-Contracts request your machine's IP is logged.
Fixes #WD-9806

WD-9806: Send X-Forwarded-For to UA-Contracts

---

templates/support/index.html

- Add link to /support according to the [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
- Navigate to /support and check if the new link exists and it leads to where it needs to
Fixes https://warthogs.atlassian.net/browse/WD-10092

[WD-10092] add a link to /support page

---

templates/download/cloud/index.html

- Go to https://ubuntu-com-13723.demos.haus/download/cloud and check against [copy docs](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit#heading=h.g8qxciukhosl)
Fixes https://warthogs.atlassian.net/browse/WD-10193

WD-10193 Copy update for 24.04 release

---

static/sass/_pattern_buttons.scss
templates/download/index.html

- Updated laptop asset as per linked ticket
- View the site locally in your web browser at: https://ubuntu-com-13720.demos.haus/download
- See that the change has been made
Fixes https://warthogs.atlassian.net/browse/WD-10050

Update laptop asset /download

---

HACKING.md
README.md

- add information about linting and formatting to README

add information about linting and formatting to README

---

.djlintrc
templates/ai/services.html
templates/embedded/index.html
templates/internet-of-things/index.html
templates/pro/index.html
templates/shared/_pro-for-devices-banner.html

On  https://ubuntu-com-13726.demos.haus/internet-of-things  - changes in comments on the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.g8inespqhurp) to include a banner at the top of the page
On https://ubuntu-com-13726.demos.haus/embedded - changes in the [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit#heading=h.g8inespqhurp) to include the same banner as the iot page
On https://ubuntu-com-13726.demos.haus/pro - changes in the [copydoc](https://docs.google.com/document/d/1XidZq045nJDM5vzfB5KJCpH3AqOERvPOeayuqUKfNso/edit) to add a link at the bottom of the page
- Visit the above links and check the changes in the copydocs have been made
Fixes …

Adds pro for IoT banner

---

package.json
static/js/src/core.js
templates/base_index.html
templates/templates/base.html
yarn.lock

- Updated the coookie policy to v3.6.3
- View the demo in an incognito web browser
- **Before** accepting cookies, 
- Open developer tools and in the console type in `dataLayer`
- There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
- There should be a `{"consent", "update"}` object in the dataLayer

Updated cookie policy to v3.6.3

---

templates/credentials/sign-up.html
templates/shared/_credentials-contact-us-form.html
webapp/app.py
webapp/shop/cred/views.py
webapp/views.py

- Separate Marketo submission logic for credentials sign-up form 
- submit /credentials/sign-up
Fixes [#WD-10014](https://warthogs.atlassian.net/browse/WD-10014)

Wd 10014 credentials sign ups donot end up in marketo

---

templates/download/desktop/index.html
templates/download/shared/_downloads-resources.html
templates/download/shared/_secure-enterprise-management.html

- Applied copy updates as per [doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit)
- View the site locally in your web browser at: https://ubuntu-com-13722.demos.haus/download/desktop
- See that the needed changes have been made
Fixes https://warthogs.atlassian.net/browse/WD-10051

/download/desktop 24.04 copy updates

---

templates/desktop/developers.html

- Copy update
- Go to https://ubuntu-com-13748.demos.haus/desktop/developers and compare with [copy doc changes](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit) (remove image and hyphens)
- Changes to charts are automated and already [in the branch](https://github.com/canonical/ubuntu.com/pull/13734)
Fixes https://warthogs.atlassian.net/browse/WD-10162

WD-10162 copy update

---

releases.yaml
templates/download/server/manual.html

- Updated copy as per [doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
- Drive bys:
- Updated previous lts versions on releases.yaml and added server iso sizes 
Fixes https://warthogs.atlassian.net/browse/WD-10052

/download/server 24.04 updates

---

templates/certified/index.html

- Update image as described in  https://warthogs.atlassian.net/browse/WD-10166
- Go to https://ubuntu-com-13753.demos.haus/certified and check that the image has been updated according [Jira ticket](https://warthogs.atlassian.net/browse/WD-10166)
Fixes https://warthogs.atlassian.net/browse/WD-10166

WD-10166 Update certified image

---

templates/desktop/organisations.html

- Updates image as per [jira issue](https://warthogs.atlassian.net/browse/WD-10369)
- Formatting
- Go to desktop/organisations and see the image has been updated
Before:
After:
Fixes https://warthogs.atlassian.net/browse/WD-10369

Update image on /desktop/organisations

---

templates/download/server/thank-you-s390x.html

- Update new section "Get started with Ubuntu today"
- Update 24.04 link (not ready until 24.04 release)
- Check https://ubuntu-com-13750.demos.haus/download/server/thank-you-s390x against [copy updates](https://docs.google.com/document/d/1GptXtMfbgOjOmqb8DZCCTRwogkiP_cM95U9Z0gFSt7g/edit)
Fixes https://warthogs.atlassian.net/browse/WD-10160

WD-10160 Server download

---

templates/download/server/arm.html

- Updates links based on [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit)
- Go to download/server/arm and check the links are updated
Fixes https://warthogs.atlassian.net/browse/WD-10158

Copy update on /download/server/arm

---

templates/download/index.html

- Updated a laptop image at the top of the /download page
- Updated a meta_image with the Numbat one
- Updated content of the Core section according to [copy doc](https://docs.google.com/document/d/1egsCcmFiz8czeHsvwoB9Jz815Ij5Urtf7Ngrru6Zd4o/edit#heading=h.y9yb7esh2ujx)
- Navigate to https://ubuntu-com-13769.demos.haus/download
- Check that the changes that are listed above are in place
Fixes https://warthogs.atlassian.net/browse/WD-10516

[WD-10516] update image download

---

templates/training/index.html

- Updated copy as per [doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#heading=h.hartsr26sbq8)
- Ran djlint on target file
- View the site locally in your web browser at: https://ubuntu-com-13773.demos.haus/training
Fixes https://warthogs.atlassian.net/browse/WD-10508

/training copy update

---

templates/credentials/assessments.html
templates/credentials/base_cred.html
templates/credentials/base_exam.html
templates/credentials/beta-activation.html
templates/credentials/exam-no-agreement.html
templates/credentials/exam.html
templates/credentials/exit-survey.html
templates/credentials/index.html
templates/credentials/redeem.html
templates/credentials/redeem_with_captcha.html
templates/credentials/redeem_with_form.html
templates/credentials/schedule-confirm.html
templates/credentials/schedule.html
templates/credentials/self-study.html
templates/credentials/shop/index.html
templates/credentials/shop/keys.html
templates/credentials/shop/thank-you.html
templates/credentials/shop/webhook_responses.html
templates/credentials/sign-up.html
templates/credentials/syllabus.html
templates/credentials/thank-you.html
templates/credentials/your-badges.html
templates/credentials/your-exams.html
templates/legal/terms-and-policies/credentials-terms.html
webapp/shop/cred/views.py

- Update Emails for Credentials 
- Update style for schedule confirm page 
- Check emails have changed
- Try to schedule an exam
- The confirmation page should use the new suru
Fixes [#WD-10378](https://warthogs.atlassian.net/browse/WD-10378)

Wd 10378 update references to credentials canonical com to skills canonical com

---

static/sass/styles.scss
templates/core/services/index.html

- Go to https://ubuntu-com-13767.demos.haus/core/services and compare against [copy doc](https://docs.google.com/document/d/11z973-P-vuaVp7gCQpoQly0gzqNMYX7ETPVghEkDDsE/edit#heading=h.cgeassa57vhx) and design (screenshot below)
Fixes https://warthogs.atlassian.net/browse/WD-9628

WD-9628 Refresh core services

---

templates/kubernetes/docs/release-notes.md

adds space to fix rendering issue
- I added a blank line

Update K8s release notes

---

webapp/shop/cred/views.py

- Exam products were not showing as it expected a price for all the products. Fixed this error.
- Checkout [Credentials Shop](https://ubuntu-com-13782.demos.haus/credentials/shop)
Fixes [#WD-10584](https://warthogs.atlassian.net/browse/WD-10584)

WD-10584-exam-products-donot-show-up

---

static/sass/_pattern_navigation.scss

Rotate the back button chevron to face left

---

meganav.yaml

Fix yaml file formatting

---

templates/desktop/index.html

- Change YT video for 24.04 release on /desktop

[WD-10738] new desktop video

---

templates/gcp/pro.html

- Update copy on /gcp/pro based on [copydoc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit#heading=h.pmc79wve6nh5)
- Formatting (I've commented the copy changes)
- Go to https://ubuntu-com-13816.demos.haus/gcp/pro and check the changes match the [copydoc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit#heading=h.pmc79wve6nh5)
Fixes https://warthogs.atlassian.net/browse/WD-10793

Update copy on /gcp/pro

---

templates/azure/pro.html

- Copy update (only Jehudi's comments for 24.04 release)
- Go to https://ubuntu-com-13814.demos.haus/azure/pro and compare with [copy docs](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#heading=h.c6wjbvvp8mcm) (Jehudi's comments for 24.04 release updates)
Fixes https://warthogs.atlassian.net/browse/WD-10777

WD-10777 Copy update

---

navigation.yaml
templates/telco/index.html
templates/telco/shared/_telco-logo-section.html

- Updates based on changed in [copydoc](https://docs.google.com/document/d/1a3otoXCbXtddJG2HCnYIIHJiDxvG-pzFPtLobVB4-vw/edit)
- Updated UX in call with Juan :)
- Check the changes outlined in the [copydoc](https://docs.google.com/document/d/1a3otoXCbXtddJG2HCnYIIHJiDxvG-pzFPtLobVB4-vw/edit) are reflected in [the demo](https://ubuntu-com-13787.demos.haus/telco)
Fixes https://warthogs.atlassian.net/browse/WD-10363

Update /telco page

---

templates/azure/index.html

- Addressing comments in the copy docs for the 24.04 Azure release
- Go to https://ubuntu-com-13820.demos.haus/azure and compare to [copy doc changes](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit) 
Fixes https://warthogs.atlassian.net/browse/WD-10776?atlOrigin=eyJpIjoiODVkZDM5YTRjYzFjNGM5YWJhYTA4ZTc4NWI0MDI4MzgiLCJwIjoiaiJ9

WD-10776 Copy update for 24.04 Azure release

---

templates/download/cloud/index.html
templates/shared/_ubuntu_pro_on_public_cloud.html

- Updated copy as per [doc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit)
- View the site locally in your web browser at: https://ubuntu-com-13823.demos.haus/download/cloud
Fixes https://warthogs.atlassian.net/browse/WD-10866

/download/cloud copy update

---

navigation.yaml
static/sass/styles.scss
templates/core/features/index.html
templates/core/index.html
templates/core/services/index.html
templates/core/tabs.html

Feature branch for Core 24 release

---

templates/landscape/index.html
templates/landscape/install.html

- Updated copy as per docs linked below
- Ran djlint on /landscape/install
- View the site locally in your web browser at: https://ubuntu-com-13830.demos.haus/landscape and check against [doc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit)
- View  https://ubuntu-com-13830.demos.haus/landscape/install and check against [doc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#heading=h.nscizu2nycw8)
Fixes https://warthogs.atlassian.net/browse/WD-10794

/landscape copy updates

---

templates/cloud/cloud-computing.html
templates/support/index.html

- Updates based on [copydoc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit#heading=h.pkvhhqabnqfc) changes and [design](https://www.figma.com/file/YdmmtZxcCdEVJE4JmSqfeD/Ubuntu.com%2Fsupport?type=design&node-id=233-3065&mode=design&t=teXUetDya3yo2y4d-0)
- Go to /support
- Check that the copy changes match
- Check the design matches
Fixes https://warthogs.atlassian.net/browse/WD-10400

Update copy on /support

---

templates/openstack/install.html

- Updated copy as per [doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)
- Ran djlint
- View the site locally in your web browser at: https://ubuntu-com-13837.demos.haus/openstack/install
Fixes https://warthogs.atlassian.net/browse/WD-10910

/openstack/install copy update

---

templates/openstack/consulting.html

- Updates the link for 'Download PCB datasheet' as in the [copydoc](https://assets.ubuntu.com/v1/2f580210-PCB%20Datasheet%2022.04.2024.pdf)
- Go to https://ubuntu-com-13838.demos.haus/openstack/consulting and check the link
Fixes https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit

Update link on /openstack/consulting

---

templates/download/cloud/index.html
templates/shared/_ubuntu_pro_on_public_cloud.html
templates/shared/contextual_footers/_download_cloud_ubuntu_advantage.html

Update links for /download/cloud page
- Go to https://ubuntu-com-13829.demos.haus/download/cloud and compare with [copy doc comments](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit)
Fixes https://warthogs.atlassian.net/browse/WD-10907

WD-10907 Upload links

---

navigation.yaml
static/sass/styles.scss
templates/confidential-computing/ai.html
templates/shared/forms/interactive/confidential-computing.html

- Go to https://ubuntu-com-13812.demos.haus/confidential-computing/ai and check against [copy doc](https://docs.google.com/document/d/1TZ_jK3ReetAU2qA_YxfZL8i4j_lFidcF6F2Xup8R8Nc/edit)
- Also check against design review in the screenshot below
Fixes https://warthogs.atlassian.net/browse/WD-10145

WD-10146 Build new Confidential AI page

---

templates/openstack/tutorials.html

- Updates `/openstack/tutorials` based on [copydoc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit)
- Creates the individual topics for each tutorial
- Check the content on https://ubuntu-com-13840.demos.haus/openstack/tutorials matches the copydoc
- Check the links go to the right tutorial
Fixes https://warthogs.atlassian.net/browse/WD-10916

Refresh /openstack/tutorials

---

navigation.yaml
templates/credentials/faq.html
templates/credentials/syllabus.html
webapp/shop/cred/syllabus.json

- Update cred copy changes 
Fixes [#WD-10988](https://warthogs.atlassian.net/browse/WD-10988)

Wd 10988 copy updates may 1 2024

---

static/js/src/chart-data.js
templates/about/openstack-release-cycle.html
templates/about/release_cycles/microstack-eol.html
templates/about/release_cycles/openstack-eol.html
templates/credentials/syllabus.html

Update openstack chart on https://ubuntu.com/about/release-cycle#openstack-release-cycle
I don't see any comments in the spreadsheets, so will need to rely on an experienced reviewer to know if these changes are correct.
- Go to  https://ubuntu-com-13843.demos.haus/about/release-cycle#openstack-release-cycle
- Click on the Openstack tab
- and check the chart has the parts removed according to the [Jira ticket](https://warthogs.atlassian.net/browse/WD-10911?atlOrigin=eyJpIjoiNWJjMGNmN2VlNWFlNDQ2YThhZjkyOGZjMzJlYmNlZjIiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-10911?atlOrigin=eyJpIjoiNWJjMGNmN2VlNWFlNDQ2YThhZjkyOGZjMzJlYmNlZjIiLCJwIjoiaiJ9

WD-10911 Update Openstack chart

---

navigation.yaml
templates/managed/firefighting-support.html

[Design](https://www.figma.com/file/elTbjLdEYglzrRX01EvGd2/24.04-U.com---Firefighting-Support?type=design&node-id=40-1615&mode=design&t=iuq6Qzen1bUXU2Fd-0)
[Copydoc](https://docs.google.com/document/d/1sWNMmLoyOFUI9qZE3fqPhgZWJSpb-e6-juGrW7A5rr0/edit)
- Go to https://ubuntu-com-13845.demos.haus/managed/firefighting-support
- Compare content against [Copydoc](https://docs.google.com/document/d/1sWNMmLoyOFUI9qZE3fqPhgZWJSpb-e6-juGrW7A5rr0/edit)
- Check on different screen sizes
Fixes https://warthogs.atlassian.net/browse/WD-9794

Build /managed/firefighting-support page

---

templates/landscape/install.html

Update landscape install page according to copy doc
- [demo link](https://ubuntu-com-13860.demos.haus/landscape/install)
- [copy doc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit)
[WD-11096](https://warthogs.atlassian.net/browse/WD-11096)
[WD-11096]: https://warthogs.atlassian.net/browse/WD-11096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-11096 - update landscape install page

---

build.js
static/js/src/advantage/api/enum.ts
static/js/src/advantage/api/types.ts
static/js/src/advantage/distributor/Distributor.tsx
static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
static/js/src/advantage/distributor/components/ChannelOffersList/index.ts
static/js/src/advantage/distributor/components/InitiateButton/InitiateButton.tsx
static/js/src/advantage/distributor/components/InitiateButton/index.ts
static/js/src/advantage/distributor/hooks/useGetChannelOffersList.tsx
static/js/src/advantage/subscribe/checkout/utils/types.ts
static/sass/styles.scss
templates/account/forbidden.html
templates/pro/distributor/index.html
webapp/app.py
webapp/shop/advantage/views.py

- Build /pro/distributor page
- Block non channel users from accessing distributor pages
- Log in with channel user account
- Go to `/pro/distributor`
Fixes #https://warthogs.atlassian.net/browse/WD-10604, https://warthogs.atlassian.net/browse/WD-10786

Build /pro/distributor page

---

static/sass/styles.scss
templates/core/index.html

- Updated images as per [doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit)
- View the site locally in your web browser at: https://ubuntu-com-13864.demos.haus/core
- See that the images have been updated
Fixes https://warthogs.atlassian.net/browse/WD-11001

/core update images

---

templates/training/index.html

https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#heading=h.72dkmz13eth6
Fixes https://warthogs.atlassian.net/browse/WD-11215

Update copy on /training

---

static/js/src/advantage/distributor/DistributorShop.tsx
static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/index.ts
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/index.ts
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
static/js/src/advantage/distributor/utils/FormContext.tsx
static/js/src/advantage/distributor/utils/utils.ts
static/sass/_pattern_distributor.scss

- step 4 add subscription
- showing pre selected subscription when order initiated will be done by another pr.
- valid product list will be updated by another pr
- Initiate order
- on /pro/distributor/shop, in step 4, add products, check the added product shows as a card  and also check deleting works.
Fixes #https://warthogs.atlassian.net/browse/WD-10609

Wd 10609 step 4 add subscription

---

static/js/src/advantage/distributor/DistributorShop.tsx
static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/DistributorShopSummary.tsx
static/js/src/advantage/distributor/hooks/useGetChannelOffersList.tsx
static/js/src/advantage/distributor/utils/FormContext.tsx
static/js/src/advantage/distributor/utils/utils.ts
static/sass/_pattern_shop-cart.scss
templates/pro/distributor/index.html
tests/shop/advantage/fixtures/product-listings-channel.json
webapp/shop/advantage/views.py
webapp/shop/api/ua_contracts/advantage_mapper.py
webapp/shop/api/ua_contracts/models.py
webapp/shop/api/ua_contracts/parsers.py

- Create a mock product list and apply values in the summary section
1. Go to /pro/distributor
2. Initiate order
3. On /pro/distributor/shop, complete all steps and change values and check the change is applied in the summary section
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?selectedIssue=WD-10615

WP-10615 get product list

---

templates/download/amd/tab-2.html

- Applied copy changes on `/download/amd` according to [copy docs](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- Go to demo page: https://ubuntu-com-13867.demos.haus/download/amd
- Check with [copy docs](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- Check that download links are working and updated
Fixes [WD-11249](https://warthogs.atlassian.net/browse/WD-11249)
[WD-11249]: https://warthogs.atlassian.net/browse/WD-11249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update copy on /download/amd

---

templates/landscape/index.html

- Changed video icon to webinar icon as per [doc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit?disco=AAABNt0LY5A)
- Ran djlint
- View the site locally in your web browser at: https://ubuntu-com-13876.demos.haus/landscape
Fixes https://warthogs.atlassian.net/browse/WD-11229

Update icon and run djlint

---

webapp/context.py
webapp/security/views.py

Reverts canonical/ubuntu.com#13880

Revert "Add rate limiting to cves"

---

templates/legal/websites.html

- Add support portal on `/legal/websites`
- Go to  /legal/websites
- Check support portal is in the list
- Check the link works.
Fixes #https://warthogs.atlassian.net/browse/WD-11490?atlOrigin=eyJpIjoiZWMzZmNlZjZlYzBkNDYyZWJmZGYzZDI0ZDIwNGIxYWMiLCJwIjoiaiJ9

Add support portal on /legal/websites

---

templates/kubernetes/compare.html

- Updates content based on [copydoc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit)
- Go to https://ubuntu-com-13890.demos.haus/kubernetes/compare and check the appropriate spelling changes have been made
Fixes https://warthogs.atlassian.net/browse/WD-11515

Update copy on /kubernetes/compare

---

templates/ceph/index.html

- Changed occurance of "ROCKs" to "rocks"
- Please find [Demo](https://ubuntu-com-13888.demos.haus/ceph).
- Also the [copydoc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit) for the change.
[WD-11513](https://warthogs.atlassian.net/browse/WD-11513)
[WD-11513]: https://warthogs.atlassian.net/browse/WD-11513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-11513 Changed occurance of "ROCKs" to "rocks" in ceph

---

templates/core/features/index.html

- Apply copy update - [copy docs](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit)
- Go to https://ubuntu-com-13901.demos.haus/core/features, compare with copy doc
- Changes in meta tag and minor text update under security's strict confinement
Fixes [WD-11700](https://warthogs.atlassian.net/browse/WD-11700)
[WD-11700]: https://warthogs.atlassian.net/browse/WD-11700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update copy on /core/features 

---

templates/containers/chiselled/index.html

- Replace instance of Rocks -> rocks
- Go to https://ubuntu-com-13904.demos.haus/containers/chiselled and check [comment has been addressed](https://docs.google.com/document/d/1ZkQ-UFTwsPkMnQn8IEEjZOXMy40tkgBscw_-qq9K3nc/edit)
Fixes https://warthogs.atlassian.net/browse/WD-11517 (no instances found eventually)
Fixes https://warthogs.atlassian.net/browse/WD-11518

Update all instances of ROCKS to rocks

---

templates/kernel/real-time/contact-us.html

- Update Ubuntu LTS version to 24.04
- djlint formatting on the file
- Go to `/kernel/real-time/contact-us`
- Check that Ubuntu 24.04 LTS is shown on the release page
Fixes [WD-11714](https://warthogs.atlassian.net/browse/WD-11714)
[WD-11714]: https://warthogs.atlassian.net/browse/WD-11714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update copy for /kernel/real-time/contact-us

---

templates/core/index.html
templates/core/tabs.html

- Simple changes to index file in templates/core
- Changed link of Youtube Video
- Also the [copydoc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit) for the change.
- [Demo](https://ubuntu-com-13908.demos.haus/core)
- Check: the added youtube video should not show negative recommendations. 
Fixes # [11701](https://warthogs.atlassian.net/browse/WD-11701)

WD-11701 Copyupdates to templates/core

---

templates/security/fedramp.html

- Builds new page at `/security/fedramp` based on [copydoc](https://docs.google.com/document/d/1eJxGEthPLxG2CjFXTXLk6QF97DNh4VyZZ-AG2yIq8v4/edit) and [design](https://www.figma.com/design/Fpl0WCuOIJwG11s4PzxRnO/24.10-U.com---Security-%3E-FedRAMP?node-id=1-1002&t=JFXOqcXWXqtm6nGl-0)
- Go to https://ubuntu-com-13905.demos.haus/security/fedramp and compare against [copydoc](https://docs.google.com/document/d/1eJxGEthPLxG2CjFXTXLk6QF97DNh4VyZZ-AG2yIq8v4/edit) and [design](https://www.figma.com/design/Fpl0WCuOIJwG11s4PzxRnO/24.10-U.com---Security-%3E-FedRAMP?node-id=1-1002&t=JFXOqcXWXqtm6nGl-0)
- Check responsiveness on different screen sizes
Fixes https://warthogs.atlassian.net/browse/WD-11319 …

Build new page /security/fedramp

---

static/js/src/advantage/distributor/DistributorShop.tsx
static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DealRegistration/DealRegistration.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/DistributorShopSummary.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
static/js/src/advantage/distributor/components/InitiateButton/InitiateButton.tsx
static/js/src/advantage/distributor/utils/FormContext.tsx
static/js/src/advantage/distributor/utils/utils.ts

- Parse offer and display pre-selected items, currency, duration in the distributor shop
- Add offer state to context
1. Go to /pro/distributor
2. Initiate order
3. Check pre-selected items, currency, duration display in /pro/distributor/shop.
4. Change values in the shop and check the changes are applied in the summary section.
Fixes #https://warthogs.atlassian.net/browse/WD-11339

WD-11339 display pre selected items

---

static/js/src/advantage/distributor/Order.tsx
static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.tsx
static/js/src/advantage/distributor/components/DistributorBuyButton/index.ts
static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
static/js/src/advantage/distributor/components/Order/OrderDetail/OrderDetail.tsx
static/js/src/advantage/distributor/components/Order/OrderDetail/index.ts
static/js/src/advantage/distributor/components/Order/OrderSummary/OrderSummary.tsx
static/js/src/advantage/distributor/components/Order/OrderSummary/index.ts
static/js/src/advantage/distributor/utils/FormContext.tsx
static/js/src/advantage/distributor/utils/utils.ts
static/sass/_pattern_distributor.scss

- Build /pro/distributor/order page view
- /pro/distributor
- Initiate order 
- Complete steps on /pro/distributor/shop
- Click proceed button
- Check the order page displays properly
Fixes #https://warthogs.atlassian.net/browse/WD-10616

WD-10616 Build /pro/distributor/order page view

---

templates/core/features/index.html
templates/core/index.html

- Applied copy updates as per [/core doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit#heading=h.il7ddqhjlzrs) and [/core/features doc](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit)
- View the site locally in your web browser at: https://ubuntu-com-13916.demos.haus/core and https://ubuntu-com-13916.demos.haus/core/features
Fixes https://warthogs.atlassian.net/browse/WD-11783, https://warthogs.atlassian.net/browse/WD-11784

Core 24 final copy updates

---

templates/embedding/index.html

- Copy changes for /embedding
- Visit /embedding
- Make sure it matches the [copy doc](https://docs.google.com/document/d/1evAFIXbNztOd5yZee-uV8_OM-s6o27P46yXFaaeEhy0/edit)
- Also update suru to new one
Fixes [#WD-11910](https://warthogs.atlassian.net/browse/WD-11910)

WD-11910-copy-changes-for-embedding

---

templates/kubernetes/charmed-k8s.html

- Reupload, as I couldn't access previous account
- Created new account in Lastpass
- Test that the video works now https://ubuntu-com-13932.demos.haus/kubernetes/charmed-k8s compare to previous 
Fixes https://warthogs.atlassian.net/browse/WD-11959

Fix video on charmed k8s

---

templates/download/nvidia-jetson/index.html
templates/download/nvidia-jetson/tab-2-jetson-orin-nano.html
templates/download/nvidia-jetson/tab-3-jetson-orin-nx.html

- Refresh nvidia-jetson download page
- Go to https://ubuntu-com-13943.demos.haus/download/nvidia-jetson and check against [copy docs](https://docs.google.com/document/d/1DHLqBbo6xIHDp-Uc8ngo1t5-GJgeTdTVwBvZRIKyZ0Y/edit)
Fixes https://warthogs.atlassian.net/browse/WD-11777

WD-11786 Refresh nvidia-jetson download page

---

templates/containers/what-are-containers.html

-  Rebranded /containers/what-are-containers
- The work was been picked from here https://github.com/canonical/ubuntu.com/pull/13900 
- Please find the design here https://www.figma.com/design/vHVDziBUEWpxKdYG2lLIZN/What-are-containers?node-id=1-3755&t=u9BkaiaziFcyI5Ly-0
- [Demo](https://ubuntu-com-13931.demos.haus/containers/what-are-containers)
Fixes # [WD-8332](https://warthogs.atlassian.net/browse/WD-8332) …

WD-8332 Dev - Rebrand /containers/what-are-containers

---

redirects.yaml
templates/aws/index.html
templates/security/contact-us.html
templates/shared/_thank_you.html
templates/support/thank-you.html

- [Security contact-us copy update](https://warthogs.atlassian.net/browse/WD-12086)
- [Redirect for old blog](https://warthogs.atlassian.net/browse/WD-11924)
- Link fix for aws
- Go to https://ubuntu-com-13948.demos.haus/security/contact-us check [comments have been addressed](https://docs.google.com/document/d/1G65SrIDmNw4ZMtryTH8r1y_0Xtn9U0ns7T0_XH1j16E/edit)
- Go to https://ubuntu-com-13948.demos.haus/blog/intel-compute-stick-now-comes-with-ubuntu should redirect to https://ubuntu.com/download/iot/intel-iot
- Go to https://ubuntu-com-13948.demos.haus/aws and check that [comment has been addressed](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit?disco=AAABPDMgmic)
Fixes https://warthogs.atlassian.net/browse/WD-11924
Fixes …

Security copy updates

---

static/js/src/prepare-form-inputs.js

- Fixed missing input name
- View the site locally in your web browser at: https://ubuntu-com-13962.demos.haus/ai#get-in-touch or https://ubuntu-com-13962.demos.haus/engage/from-vmware-to-openstack (or any other form)
- Fill it out and see that the phone number is included in the payload
Fixes https://warthogs.atlassian.net/browse/WD-12005

Fix missing phone field on marketo submission

---

konf/site.yaml

Route /security/notices.json into a separate service

Route /security/notices.json into a separate service.

---

HACKING.md

- Basically copy/pasted what we already have in Discourse topic to HACKING.MD for the external community to know how we use formatting and linting in our projects.
- Open HACKING.MD and scroll down to the last section about formatting and linting.
Fixes https://warthogs.atlassian.net/browse/WD-12328

add information about formatting and linting to HACKING.MD

---

templates/download/amd/tab-1.html

- Check https://ubuntu-com-13949.demos.haus/download/amd against [copy doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
Fixes https://warthogs.atlassian.net/browse/WD-12069

Update install ubuntu on AMD with open-source section

---

templates/containers/chiselled/index.html

- Add new sections to '/containers/chiselled' based on [copydoc](https://docs.google.com/document/d/1ZkQ-UFTwsPkMnQn8IEEjZOXMy40tkgBscw_-qq9K3nc/edit) and [design](https://www.figma.com/design/YfNc8KmYqa2e7JgbFo6lXa/24.04-U.com---%2Fcontainers?node-id=440-3441&t=Snw41ddNHSYNRMvI-0)
- Go to https://ubuntu-com-13991.demos.haus/containers/chiselled
- Check content matches the [copydoc](https://docs.google.com/document/d/1ZkQ-UFTwsPkMnQn8IEEjZOXMy40tkgBscw_-qq9K3nc/edit)
- Check design matches the [design](https://www.figma.com/design/YfNc8KmYqa2e7JgbFo6lXa/24.04-U.com---%2Fcontainers?node-id=440-3441&t=Snw41ddNHSYNRMvI-0)
Fixes https://warthogs.atlassian.net/browse/WD-12561

feat: Add new sections to '/containers/chiselled'

---

templates/ai/consulting.html
templates/credentials/assessments.html
templates/credentials/base_cred.html
templates/credentials/base_exam.html
templates/credentials/beta-activation.html
templates/credentials/exam-no-agreement.html
templates/credentials/exam.html
templates/credentials/exit-survey.html
templates/credentials/faq.html
templates/credentials/index.html
templates/credentials/redeem.html
templates/credentials/redeem_with_captcha.html
templates/credentials/redeem_with_form.html
templates/credentials/schedule-confirm.html
templates/credentials/schedule.html
templates/credentials/self-study.html
templates/credentials/shop/index.html
templates/credentials/shop/thank-you.html
templates/credentials/shop/webhook_responses.html
templates/credentials/sign-up.html
templates/credentials/syllabus.html
templates/credentials/thank-you.html
templates/credentials/your-badges.html
templates/credentials/your-exams.html
templates/shared/_credentials-contact-us-form.html

- Update the Suru across the credentials bubble
- Small improvements across the content
- Navigation around the /credentials bubble using the files changed
- See how they look logged in and out
Fixes https://warthogs.atlassian.net/browse/WD-12033

WD-12033 - Update the Suru across the credentials bubble

---

templates/openstack/tutorials.html

- Applied copy updates as per [doc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit)
- View the site locally in your web browser at: https://ubuntu-com-13985.demos.haus/openstack/tutorials
Fixes https://warthogs.atlassian.net/browse/WD-12363

Copy update - /openstack/tutorials

---

templates/kernel/lifecycle.html

- Update copy on '/kernel/lifecycle' based on [copydoc](https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit)
- Go to https://ubuntu-com-14007.demos.haus/kernel/lifecycle
- Compare changes against [copydoc](https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit)
Fixes https://warthogs.atlassian.net/browse/WD-12650

chore: Update copy on '/kernel/lifecycle'

---

templates/credentials/index.html
webapp/shop/cred/views.py

- Add CTA for credentials buy
- Visit /credentials
- Should see CTA
Fixes #

remove the conditions and just add the buttons

---

templates/security/certifications.html

- Refreshed /security/certifications
- [Demo](https://ubuntu-com-13993.demos.haus/security/certifications)
- [Copydoc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit)
Fixes # [WD-11740](https://warthogs.atlassian.net/browse/WD-11740)
[WD-11740]: https://warthogs.atlassian.net/browse/WD-11740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-11740 Refreshed  /security/certifications

---

templates/real-time/index.html

Update link on /real-time
- [demo link](https://ubuntu-com-14022.demos.haus/real-time)
- [copy doc](https://docs.google.com/document/d/1g9G3r4eJRPGZy5Dyz_GJhUz_iqNn-5QUhG43scnBnUA/edit)
- Check that the link is correct according to copy doc
[WD-12770](https://warthogs.atlassian.net/browse/WD-12770)
[WD-12770]: https://warthogs.atlassian.net/browse/WD-12770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12770 - update link on /real-time

---

build.js
static/js/src/contact-forms.js
static/sass/_pattern_modals.scss
static/sass/styles.scss
templates/ai/thank-you.html
templates/aws/contact-us.html
templates/aws/thank-you.html
templates/ceph/thank-you.html
templates/contact-us/form/thank-you.html
templates/core/contact-us.html
templates/core/thank-you.html
templates/desktop/thank-you.html
templates/kernel/real-time/contact-us.html
templates/openstack/thank-you.html
templates/pricing/thank-you.html
templates/security/thank-you.html
templates/server/thank-you.html
templates/shared/_client-contact-us-form.html
templates/shared/_cloud-contact-us-form.html
templates/shared/_pro-contact-us-form.html
templates/shared/forms/interactive/aws.html
templates/shared/forms/interactive/esm.html
templates/shared/forms/interactive/general.html
templates/shared/forms/interactive/landscape.html
templates/shared/forms/interactive/pricing-infra.html
templates/shared/forms/interactive/storage.html
templates/support/thank-you.html
templates/templates/base.html

Updated multiple contact forms. Please see more details in the Jira ticket.  
- demos:
- https://ubuntu-com-13918.demos.haus/support/contact-us?product=support-overview
- https://ubuntu-com-13918.demos.haus/contact-us/form?product=pro
- https://ubuntu-com-13918.demos.haus/security/esm#get-in-touch
- https://ubuntu-com-13918.demos.haus/pricing/pro#get-in-touch
- https://ubuntu-com-13918.demos.haus/ceph/consulting#get-in-touch
- https://ubuntu-com-13918.demos.haus/core/contact-us
- https://ubuntu-com-13918.demos.haus/server/contact-us
- https://ubuntu-com-13918.demos.haus/openstack/contact-us
- https://ubuntu-com-13918.demos.haus/kernel/real-time/contact-us
- https://ubuntu-com-13918.demos.haus/aws/contact-us
- https://ubuntu-com-13918.demos.haus/aws#get-in-touch
- …

WD-10729 - update contact us forms

---

static/sass/_pattern_lists.scss
templates/pro/devices.html
templates/shared/forms/interactive/pro-devices.html
templates/templates/_footer-copyright-and-legal.html

- Build /pro/devices page and its contact form 
- Go to /pro/devices
- Compare page against [copy doc](https://docs.google.com/document/d/1i_3nPkSpCQJ4jfOwN380sdfuTxaiDuDIgDfk01wVPqo/edit)
- Check CTA button for the form
Fixes #https://warthogs.atlassian.net/browse/WD-11736

WD-11736 build /pro/devices page

---

templates/legal/data-privacy/index.html

- Update cookie information in '/legal/data-privacy' based on [copydoc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit)
- Go to legal/data-privacy and compare the changes against the [copydoc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit)
Fixes https://warthogs.atlassian.net/browse/WD-12997

feat: Update cookie information in '/legal/data-privacy'

---

static/js/src/prepare-form-inputs.js
static/sass/styles.scss
templates/ai/contact-us.html
templates/ai/data-science.html
templates/ai/thank-you.html
templates/shared/forms/interactive/ai-data-science.html

- build '/ai/data-science' page based on [copydoc](https://docs.google.com/document/d/1GdVmQD9EDf_ksN6r1qWTYSwvdynCzAE8wtKaEdtzDo8/) and [design](https://www.figma.com/design/sGeCjFvA1kV9Kmvg2S2VBn/23.10-U.com---AI-bubble?node-id=2668-10093&t=0bU85zbqKyAeSLdR-0)
- build new modal based on [form doc](https://docs.google.com/document/d/1dv-6XFaFXywPxEvD1fiklsLgic015H54ocesjArzs5E/edit)
- Added `margin-bottom: 1.25rem;` to the class `iti`, so the margins align with the rest of the form items. Also removes custom margin-top from the invalid number message
- Go to https://ubuntu-com-14050.demos.haus/ai/data-science
- Check the content matches the [copydoc](https://docs.google.com/document/d/1GdVmQD9EDf_ksN6r1qWTYSwvdynCzAE8wtKaEdtzDo8/)
- Check it visually matches the …

feat: build '/ai/data-science' page

---

templates/robotics/index.html
templates/robotics/what-is-ros.html
tests/cassettes/TestRoutes.test_blog.yaml

- fix broken engage ROS link
- previously `/engage/Deploying-ros-applications-Developer-guide`, replaced with `/engage/deploying-ros-applications-developer-guide`
- apply linting and formatting to affected files
Fixes [WD-13036](https://warthogs.atlassian.net/browse/WD-13036)
[WD-13036]: …

Fix broken engage ROS link

---

package.json
webapp/security/api.py

- Removed unused get_notices method
- Check that the demo works
- Open /security page and check it's working as expected

Cleanup notices

---

templates/credentials/schedule.html

- Dummy change made for force deployment to ubuntu.com

dummy change

---

templates/containers/chiselled/index.html

- Update cta
- Check https://ubuntu-com-14060.demos.haus/containers/chiselled against [comments in the copy doc](https://docs.google.com/document/d/1ZkQ-UFTwsPkMnQn8IEEjZOXMy40tkgBscw_-qq9K3nc/edit)
Fixes https://warthogs.atlassian.net/browse/WD-12652

WD-12652 Update link

---

templates/shared/_client-contact-us-form.html
templates/shared/forms/_desktop_help.html
templates/shared/forms/_desktop_ua-shop.html

- Apply static forms design for client contact us form
- Ensure payload is submitted to Marketo database correctly
- Go to demo /core/contact-us and /internet-of-things/contact-us
- Submit form, check that payload is submitted correctly on thank-you page
- Check on Marketo that form data is submitted correctly
Fixes [WD-13109](https://warthogs.atlassian.net/browse/WD-13109)
[WD-13109]: https://warthogs.atlassian.net/browse/WD-13109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refresh client contact us form

---

templates/confidential-computing/index.html

- Update outdated Intel TDX and Ubuntu version
- Reformat image tags
- Copy doc: https://docs.google.com/document/d/1QGwS5CYlwXkaPibSFvcag6zLcUH5lNDUbM18hCqbOJM/edit
- Go to https://ubuntu-com-14080.demos.haus/confidential-computing
- Check that Intel TDX and Ubuntu versions are updated according to copy doc
Fixes https://github.com/canonical/ubuntu.com/issues/14065 and [WD-13139](https://warthogs.atlassian.net/browse/WD-13139)
[WD-13139]: https://warthogs.atlassian.net/browse/WD-13139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Intel TDX and Ubuntu version

---

static/js/src/static-forms.js
templates/kernel/real-time/contact-us.html
templates/openstack/thank-you.html
templates/server/thank-you.html
templates/shared/_client-contact-us-form.html
templates/shared/_cloud-contact-us-form.html
templates/shared/forms/_desktop_help.html
templates/shared/forms/_desktop_ua-shop.html
templates/support/thank-you.html

- Apply redesign on `__cloud-contact-us.html`
- Remove unused variable in static-forms.js
- Fix thank you page bugs
- Check out these forms:
- [/server/contact-us](https://ubuntu-com-14079.demos.haus/server/contact-us)
- [/openstack/contact-us](https://ubuntu-com-14079.demos.haus/openstack/contact-us)
- [/support/contact-us?product=support-overview](https://ubuntu-com-14079.demos.haus/support/contact-us?product=support-overview)
- [/aws/contact-us](https://ubuntu-com-14079.demos.haus/aws/contact-us)
- Check that the forms adhere to the design in [Figma file](https://www.figma.com/design/mxftgCWDJ6s3LrlaedREkP/24.10-Static-forms?node-id=1-3&t=wJYqljxJE6kXFa8h-0)
- Submit forms and check that form payload is correct on submission
Fixes …

Refresh cloud contact us form

---

navigation.yaml
templates/base_index.html
templates/templates/footer.html

- Update footer nav on new landing page
- Go to https://ubuntu-com-14084.demos.haus/
- Scroll down to footer nav
- Check that the order of footer items adheres to [the copy docs](https://docs.google.com/document/d/117orMiMtXPBwowp6sjJ1ygjROYjSLnUkvosac7nqmpw/edit) and design matches [Figma](https://www.figma.com/design/Le4TTzyOFbcbqTPJ1tVoZT/U.com---Home-and-footer-(rebranding)?node-id=3902-13229&t=CkQVB6IPs1K6yACM-0)
Fixes [WD-13384](https://warthogs.atlassian.net/browse/WD-13384)
[WD-13384]: https://warthogs.atlassian.net/browse/WD-13384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …

Update landing page footer 

---

static/sass/_pattern_dell.scss
templates/ai/data-science.html
templates/ai/roadshow.html
templates/appliance/hardware.html
templates/base_index.html
templates/certified/index.html
templates/certified/shared/_partners.html
templates/confidential-computing/index.html
templates/desktop/developers.html
templates/desktop/index.html
templates/desktop/organisations.html
templates/download/desktop/index.html
templates/edge-computing/index.html
templates/gov/index.html
templates/industrial/index.html
templates/internet-of-things/appstore.html
templates/kubernetes/resources.html
templates/server/index.html

- Update new Dell logo throughout all pages
- Apply djlint formatting to modified files (source of big diff)
- List of copy docs: https://docs.google.com/document/d/1XWYk5IWx9US6ympIMNveRlgJOH_cyNCB1eQFHBsr4tA/edit
- Go to these websites and check that the Dell logos are updated accordingly as per copy doc
- https://ubuntu-com-14081.demos.haus/
- https://ubuntu-com-14081.demos.haus/desktop
- https://ubuntu-com-14081.demos.haus/desktop/developers
- https://ubuntu-com-14081.demos.haus/desktop/organisations
- https://ubuntu-com-14081.demos.haus/kubernetes/resources
- https://ubuntu-com-14081.demos.haus/server
- https://ubuntu-com-14081.demos.haus/certified
- https://ubuntu-com-14081.demos.haus/ai/roadshow
- https://ubuntu-com-14081.demos.haus/gov
- …

Update new Dell logo instances

---

templates/cloud/multi-cloud.html

Rebrand /cloud/multi-cloud. No content was changed, layout only
- [demo link](https://ubuntu-com-14082.demos.haus/cloud/multi-cloud)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/u.c%2Fcloud?node-id=31-1589&t=JDqOlKdc8TNDstzv-1)
[WD-12061](https://warthogs.atlassian.net/browse/WD-12061)
[WD-12061]: https://warthogs.atlassian.net/browse/WD-12061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12061 - rebrand /cloud/multi-cloud

---

templates/cloud/index.html

Rebrand /cloud No content was changed, layout only. 
- [demo link](https://ubuntu-com-14083.demos.haus/cloud)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/u.c%2Fcloud?node-id=0-1&t=GiTLYjpmq1sNNmhM-0)
[WD-12056](https://warthogs.atlassian.net/browse/WD-12056)
[WD-12056]: https://warthogs.atlassian.net/browse/WD-12056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12056 - rebrand /cloud

---

templates/cloud/hybrid-cloud.html

Rebrand /cloud/hybrid-cloud. No content was changed, layout only
- [demo link](https://ubuntu-com-14096.demos.haus/cloud/hybrid-cloud)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/24.10-u.c%2Fcloud?node-id=27-6057&t=z17uCr16KZkDDQRN-0)
[WD-12060](https://warthogs.atlassian.net/browse/WD-12060)
[WD-12060]: https://warthogs.atlassian.net/browse/WD-12060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12060 - rebrand /cloud/hybrid-cloud

---

templates/cloud/index.html

Rebrand /cloud No content was changed, layout only. 
- [demo link](https://ubuntu-com-14083.demos.haus/cloud)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/u.c%2Fcloud?node-id=0-1&t=GiTLYjpmq1sNNmhM-0)
[WD-12056](https://warthogs.atlassian.net/browse/WD-12056)
[WD-12056]: https://warthogs.atlassian.net/browse/WD-12056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD- 12056 rebrand /cloud 

---

templates/cloud/multi-cloud.html

Rebrand /cloud/multi-cloud. No content was changed, layout only
- [demo link](https://ubuntu-com-14082.demos.haus/cloud/multi-cloud)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/u.c%2Fcloud?node-id=31-1589&t=JDqOlKdc8TNDstzv-1)
[WD-12061](https://warthogs.atlassian.net/browse/WD-12061)
[WD-12061]: https://warthogs.atlassian.net/browse/WD-12061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12061. - rebrand /multi-cloud

---

templates/templates/footer.html

- Update footer based on copy doc https://docs.google.com/document/d/117orMiMtXPBwowp6sjJ1ygjROYjSLnUkvosac7nqmpw/edit
- Go to https://ubuntu-com-14106.demos.haus/
- Scroll down to footer links
- Check that the "Security" category is updated according to copy docs
Fixes [WD-13643](https://warthogs.atlassian.net/browse/WD-13643)
[WD-13643]: https://warthogs.atlassian.net/browse/WD-13643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Security section on footer

---

static/sass/styles.scss
templates/cloud/cloud-computing.html

Rebrand /cloud/cloud-computing. No content was changed, layout only
- [demo link](https://ubuntu-com-14103.demos.haus/cloud/cloud-computing)
- [figma](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/u.c%2Fcloud?node-id=31-1589&t=JDqOlKdc8TNDstzv-1)
[WD-12058](https://warthogs.atlassian.net/browse/WD-12058)
[WD-12058]: https://warthogs.atlassian.net/browse/WD-12058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12058 - rebrand /cloud-computing

---

templates/base_index.html
templates/containers/chiselled/index.html

- Updated two 404'ing links from the [linkcheck CI](https://github.com/canonical/ubuntu.com/actions/runs/10139929570/job/28034122123) 
- Check the new links work

Fix the 404ing links across the site

---

templates/landscape/index.html

- Add IoT section as per copy docs
- Copy doc: https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit
- Go to https://ubuntu-com-14110.demos.haus/landscape
- Scroll down to see the new IoT device management section
- Compare it with copy docs
Fixes [WD-13656](https://warthogs.atlassian.net/browse/WD-13656)
[WD-13656]: https://warthogs.atlassian.net/browse/WD-13656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add IoT section

---

templates/pro/index.html

- Copy docs: https://docs.google.com/document/d/1XidZq045nJDM5vzfB5KJCpH3AqOERvPOeayuqUKfNso/edit
- Add missing word
- Add new section
- Go to https://ubuntu-com-14112.demos.haus/pro
- Check that the updates from copy docs are reflected in the demo
Fixes [WD-13655](https://warthogs.atlassian.net/browse/WD-13655)
[WD-13655]: https://warthogs.atlassian.net/browse/WD-13655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Pro sections

---

static/js/src/advantage/distributor/Distributor.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Currency/Currency.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Duration/Duration.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
static/js/src/advantage/distributor/components/InitiateButton/InitiateButton.tsx
static/js/src/advantage/distributor/utils/FormContext.tsx
static/js/src/advantage/distributor/utils/utils.ts
static/js/src/advantage/offers/types.ts
static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
static/js/src/advantage/subscribe/react/components/Form/ProductUser/ProductUser.tsx
static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx
static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
static/js/src/advantage/subscribe/react/utils/FormContext.tsx
templates/pro/distributor/index.html
webapp/shop/api/ua_contracts/models.py
webapp/shop/api/ua_contracts/parsers.py

- Fix product listings version update bugs: The items included in the offer should use the version specified in the offer but for other products they are using the highest version.
Fixes #https://warthogs.atlassian.net/browse/WD-13729

Fix product listings version update bugs

---

meganav.yaml

- Update OpenStack description in meganav as requested by PM, in line with [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit)
Fixes #

Update OpenStack description in meganav

---

static/js/src/dynamic-forms.js
static/js/src/static-forms.js
static/sass/_pattern_contact-modal.scss
templates/shared/_client-contact-us-form.html
templates/shared/_pro-contact-us-form.html
templates/shared/forms/interactive/pricing-infra.html

- Apply redesign on `__pro-contact-us-form.html`
- Ensure that the form payload submits to Marketo successfully
- Added checkbox validation and toggle checkbox visibility functions to dynamic forms 
- Fix missing form payload error
- Check out these forms:
- [/contact-us/form?product=pro](https://ubuntu-com-14124.demos.haus/contact-us/form?product=pro)
- [/pricing/pro#get-in-touch](https://ubuntu-com-14124.demos.haus/pricing/pro#get-in-touch)
- Check that the fields are similar to the ones on prod: https://ubuntu.com/contact-us/form?product=pro
- Fill up form and submit
- Check that payload reflects input correctly
Fixes [WD-13105](https://warthogs.atlassian.net/browse/WD-13105) …

Refresh Pro contact us form

---

templates/legal/confidentiality-agreement.html

- Updated legal confidentiality agreement
- Most of the changes is just the formatting
- [Agreement](https://docs.google.com/document/d/0B8zvYdcwzBYOa294Zk1QTjBOZE0/edit?resourcekey=0-uV9FjHSjn2CZcD2mFCjRIg)
- [Demo](https://ubuntu-com-14141.demos.haus/legal/confidentiality-agreement)
- Visit the demo and please verify if the agreement on the page is the updated one.
Fixes # [WD-12653](https://warthogs.atlassian.net/browse/WD-13653) …

WD-13653 Update legal agreement

---

templates/automotive/index.html

- Copyupdate /automotive
- [Demo](https://ubuntu-com-14155.demos.haus/automotive)
- [Copydoc](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit)
Fixes # [WD-3948](https://warthogs.atlassian.net/browse/WD-13948)
[WD-3948]: https://warthogs.atlassian.net/browse/WD-3948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13948 Copyupdate /automotive

---

konf/site.yaml

- Added Credly env variables to production k8s secrets and as env variables
- CREDLY_TOKEN
- CREDLY_ORGANIZATION_ID
- When merged, check that the correct values are used for credly

Add credly values to production

---

meganav.yaml
templates/shared/forms/interactive/containers.html

- Updated ubuntu.com meganav IoT quick links
- [Demo](https://ubuntu-com-14154.demos.haus/)
- [Copydoc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit)
Fixes # [WD-13897](https://warthogs.atlassian.net/browse/WD-13897)
[WD-13897]: https://warthogs.atlassian.net/browse/WD-13897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …

WD-13897 Update ubuntu.com meganav IoT quick links

---

templates/shared/forms/interactive/containers.html

- Added a field to containers form.
- [Copydoc](https://docs.google.com/document/d/14DLnRamcE2su06Zh4zi9sEwJ_dpQFljH-iOVdKxjc7U/edit)
- [Demo](https://ubuntu-com-14153.demos.haus/containers#get-in-touch)
Fixes # [WD-12815](https://warthogs.atlassian.net/browse/WD-13815)
[WD-12815]: https://warthogs.atlassian.net/browse/WD-12815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …

WD-13815 Add a field to containers form

---

templates/azure/fips.html

Rebrand /azure/fips. No content was changed, layout only
- [demo link](https://ubuntu-com-14144.demos.haus/azure/fips)
- [figma](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-Azure-bubble?node-id=1-2233&t=5AOamUxpwm8vWNig-0)
[WD-12825](https://warthogs.atlassian.net/browse/WD-12825)
[WD-12825]: https://warthogs.atlassian.net/browse/WD-12825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12825 - rebrand /azure/fips

---

requirements.txt
webapp/app.py

- Updates to the newest version of search module
- Check out the branch locally and update the request limit to a low number (1 or 2) and check the rate gets limited.
- Check the search works
Fixes https://warthogs.atlassian.net/browse/WD-12317

Bump canonicalwebteam.search

---

static/sass/_pattern_lists.scss
templates/aws/workspaces.html

- Refresh /aws/workspaces based on [Figma design](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=34-4124&m=dev)
- Reformat using djlint
- Go to https://ubuntu-com-14162.demos.haus/aws/workspaces
- Check that page design matches Figma
Fixes [WD-12849](https://warthogs.atlassian.net/browse/WD-12849)
[WD-12849]: https://warthogs.atlassian.net/browse/WD-12849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rebrand /aws/workspaces page

---

static/sass/_pattern_cve.scss
templates/security/cve/index.html

Fix an issue with table scrolling the whole screen on mobile
- [demo link](https://ubuntu-com-14167.demos.haus/security/cves)
- Check that the ptable is scrolled correctly
[WD-13748](https://warthogs.atlassian.net/browse/WD-13748)
Fixes #14127 
[WD-13748]: https://warthogs.atlassian.net/browse/WD-13748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13748 - fix scrolling issue on CVEs

---

static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.test.tsx
static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/AddSubscriptions.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Currency/Currency.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DealRegistration/DealRegistration.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Duration/Duration.test.tsx
static/js/src/advantage/distributor/utils/tests/utils.test.ts
static/js/src/advantage/offers/tests/factories/channelOffers.ts
static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts

- Added some tests for the distributor store pages
- Check tests pass
Fixes #https://warthogs.atlassian.net/browse/WD-13407

Add some tests for distributor store pages

---

templates/core/index.html
templates/core/tabs.html

Fixed images on /core page
- [demo link](https://ubuntu-com-14169.demos.haus/core)
- Check that the images are full width of the grid
[WD-13068](https://warthogs.atlassian.net/browse/WD-13068)
Fixes #14053 
[WD-13068]: https://warthogs.atlassian.net/browse/WD-13068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13068 - fix images on  /core to be full width

---

templates/azure/thank-you.html
templates/shared/_thank_you_footer.html

Rebrand /azure/thank-you. No content was changed, layout only
- [demo link](https://ubuntu-com-14174.demos.haus/azure/thank-you)
- [figma](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=120-4710&t=WOaNUpdi7g9kYqma-0)
[WD-12835](https://warthogs.atlassian.net/browse/WD-12835)
[WD-12835]: https://warthogs.atlassian.net/browse/WD-12835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12835 - rebrand /azure/thank-you

---

templates/real-time/index.html

- Update copy on /real-time based on [copydoc](https://docs.google.com/document/d/1g9G3r4eJRPGZy5Dyz_GJhUz_iqNn-5QUhG43scnBnUA/edit)
- there appeared so be some design changes, which I ignored as this is a copy update
- Go to https://ubuntu-com-14178.demos.haus/real-time and compare the content changes to the [copydoc](https://docs.google.com/document/d/1g9G3r4eJRPGZy5Dyz_GJhUz_iqNn-5QUhG43scnBnUA/edit)
Fixes https://warthogs.atlassian.net/browse/WD-14172

chore: Update copy on /real-time

---

templates/pricing/pro.html

- Updated 'yes' to green checkbox and 'no' to show nothing.
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/pro
- Make sure all 'yes' are replaced with green checkboxes.
Fixes [WD-14151](https://warthogs.atlassian.net/browse/WD-14151)
[WD-14151]: https://warthogs.atlassian.net/browse/WD-14151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14151 - Update 'yes' to green checkboxes on /pricing/pro

---

templates/download/nvidia-jetson/tab-1-jetson-agx-orin.html
templates/download/nvidia-jetson/tab-2-jetson-orin-nano.html
templates/download/nvidia-jetson/tab-3-jetson-orin-nx.html

- Update copy on /nvidia-jetson based on [copydoc](https://docs.google.com/document/d/1DHLqBbo6xIHDp-Uc8ngo1t5-GJgeTdTVwBvZRIKyZ0Y/edit)
- Open [the demo](https://ubuntu-com-14196.demos.haus/) and check against the copydoc
Fixes https://warthogs.atlassian.net/browse/WD-14229

chore: Update copy on /nvidia-jetson

---

webapp/shop/cred/views.py

- visit /credentials/keys/list
- should not give error
Fixes #

add more checks to keys list

---

templates/download/amd/index.html
templates/download/amd/tab-1.html
templates/download/amd/tab-2.html

- Fix tab pages ids to include the correct tab title into the id

fix /download/amd tab ids

---

.github/workflows/live-links.yaml
templates/containers/what-are-containers.html
templates/internet-of-things/management.html

- Broken links across the website
- Check that all the links reported here are fixed: https://github.com/canonical/ubuntu.com/actions/runs/10485409492/job/29041490128
Fixes https://github.com/canonical/ubuntu.com/actions/runs/10485409492/job/29041490128
Also fixes [WD-14340](https://warthogs.atlassian.net/browse/WD-14340)
[WD-14340]: https://warthogs.atlassian.net/browse/WD-14340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Broken links across the website

---

templates/security/compliance-automation.html

- Update copy on /security/compliance-automation
- Open [the demo](https://ubuntu-com-14214.demos.haus/)
- Compare to [the copydoc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit)
Fixes https://warthogs.atlassian.net/browse/WD-14282

chore: Update copy on /security/compliance-automation

---

static/sass/_pattern_lists.scss
static/sass/styles.scss
templates/aws/fips.html
templates/azure/sql.html

- Applied redesign as per [doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit) and [figma](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=34-1807&m=dev)
- Drive by:
- I've implemented a different version of the WIP matrix mentioned [here](https://github.com/canonical/vanilla-framework/issues/5293) that works better with screen readers. If design approves, I'll update /azure/fips as well  
- View the site locally in your web browser at: https://ubuntu-com-14208.demos.haus/aws/fips
- Compare against doc and design 
Fixes https://warthogs.atlassian.net/browse/WD-12839

feat: /aws/fips redesign

---

templates/aws/index.html

- Applied changes as per [doc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit) and [design](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=0-1&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14223.demos.haus/aws
Fixes https://warthogs.atlassian.net/browse/WD-12837

feat: /aws redesign

---

templates/aws/thank-you.html
templates/azure/thank-you.html
templates/shared/_thank_you_footer.html

- Updated layout as per [design](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=120-4373&t=dB5awKtto9RGhIvA-0)
- View the site locally in your web browser at: https://ubuntu-com-14224.demos.haus/aws/thank-you
- Check against design
Fixes https://warthogs.atlassian.net/browse/WD-12847

feat: /aws/thank-you redesign

---

templates/gcp/thank-you.html

- Updated layout as per [design](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=120-4373&t=EIUTqI2SI0zuN7Og-0)
- View the site locally in your web browser at: https://ubuntu-com-14225.demos.haus/gcp/thank-you
- Check against design
Fixes https://warthogs.atlassian.net/browse/WD-12857

feat: /gcp/thank-you redesign

---

templates/case-study/esa.html

- Rename /esa-case-study to /esa
- Fix images that were previously not spanning the entire width
- Update case study content to match the existing case study pdf
- Go to https://ubuntu-com-14241.demos.haus/case-study/esa
- Check that the content matches with the [existing case study](https://pages.ubuntu.com/rs/066-EOV-335/images/European%20Space%20Agency%20Case%20Study%20April%202024%20.pdf?version=0&_ga=2.92179231.488299421.1724640435-905304663.1722502159&_gl=1*yz04o6*_gcl_au*OTk2MTIyNDYwLjE3MjMxOTI5NjU.)
- Check that images span the entire width of the image container
Fixes [WD-14513](https://warthogs.atlassian.net/browse/WD-14513) …

Fix image width and update case study content

---

releases.yaml

We are not yet released but staging the changes with checksums.
Fixes #

Prepare for release of 24.04.1

---

templates/cloud/public-cloud.html
templates/download/cloud/tabs/_azure.html
templates/download/cloud/tabs/_ibm-cloud.html
templates/download/cloud/tabs/_oracle-cloud.html
templates/shared/_partner-logos.html
webapp/app.py

-  Rebranded /cloudpublic-cloud
-  [Design](https://www.figma.com/design/NpI2wzW86XXPWxsSeomYfy/24.10-u.c%2Fcloud?node-id=182-957&t=DFnFIxrcFDnDvRuH-0)
-  [Copydoc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#heading=h.6lhihgdcnq6v)
-  [Demo]()
Fixes # [WD-12057](https://warthogs.atlassian.net/browse/WD-12057)
[WD-12057]: https://warthogs.atlassian.net/browse/WD-12057?atlOrigin=eyJpIjoiNWRkNTljNzY …

WD-12057 dev rebrand /cloud/public-cloud

---

templates/desktop/organisations.html

- Update datasheet link on '/desktop/organisations', see [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
- Open [the demo](https://ubuntu-com-14281.demos.haus/)
- Compare to the [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-14820

chore: Update datasheet link on '/desktop/organisations'

---

templates/base_index.html

- Update the dell logo 
before
after
- on the main page, control + F and find "The professional developer’s preference"
- Check the blue dell logo has been replaced with the white one
Fixes #https://warthogs.atlassian.net/browse/WD-14808

WD-14808 Update the dell logo

---

templates/azure/index.html

- Applied changes as per [doc](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit) and [design](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-ubuntu.com%2Fazure?node-id=251-1946&node-type=canvas&t=c1gK4qgVqbBBn9vl-0)
- View the site locally in your web browser at: https://ubuntu-com-14292.demos.haus/azure
Fixes https://warthogs.atlassian.net/browse/WD-12821

feat: /azure redesign

---

static/sass/_pattern_matrix.scss
templates/internet-of-things/management.html

- refreshed /internet-of-things/management
- [Design](https://www.figma.com/design/CmTm8vAUKUILc3Hu4EzSws/Internet-of-Things?node-id=2-2278&node-type=rounded_rectangle&m=dev)
- [Copydoc](https://docs.google.com/document/d/1C-1ywVzBHkc4I3f-G7Rpy-epaXdbPisbolHUC1Jb7cE/edit)
- [Demo](https://ubuntu-com-14288.demos.haus/internet-of-things/management)
[WD-13585](https://warthogs.atlassian.net/browse/WD-13585)
Fixes # …

WD-13585 refresh  /internet-of-things/management

---

templates/desktop/organisations.html

- Copy doc update /desktop/organisations
- View the site in your web browser at: https://ubuntu-com-14300.demos.haus/desktop/organisations
- Make sure that the suggested changes in [this document](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit) are applied to the page and resolve them
Fixes [WD-14833](https://warthogs.atlassian.net/browse/WD-14833)
[WD-14833]: https://warthogs.atlassian.net/browse/WD-14833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy update /desktop/organisations

---

templates/certified/search-results.html

- Fix `certified.spec.ts` failing 
- Check playwright tests pass on checks

Fix certified.spec.ts failing

---

templates/gcp/index.html

- Apply rebranding for /gcp
- Go to https://ubuntu-com-14303.demos.haus/gcp
- Check redesign against [Figma](https://www.figma.com/design/vz3yAG1nYI7r5gc3SpTUOw/24.10-ubuntu.com%2Fgcp-(Google-Cloud)?node-id=53-1836&node-type=frame&t=S7rOdhg9essH1CBn-0)
- Check that content matches with [copy doc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit)
- Remember to check on medium and small screens
Fixes [WD-12851](https://warthogs.atlassian.net/browse/WD-12851)
[WD-12851]: https://warthogs.atlassian.net/browse/WD-12851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

feat: /gcp rebranding

---

templates/ai/data-science.html

- Make changes from the copy doc to the /ai/data-science page.
- Go to [https://ubuntu-com-14302.demos.haus/ai/data-science](https://ubuntu-com-14302.demos.haus/ai/data-science).
- Check that the changes from the [copy doc](https://docs.google.com/document/d/1GdVmQD9EDf_ksN6r1qWTYSwvdynCzAE8wtKaEdtzDo8/edit#heading=h.n4ma01lh3jac) have been made.
Fixes https://warthogs.atlassian.net/browse/WD-14946

Make copydoc changes to the Data Science page.

---

templates/azure/pro.html

- Applied redesign as per [doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit) and [design](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-ubuntu.com%2Fazure?node-id=282-1394&node-type=frame&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14315.demos.haus/azure/pro
Fixes https://warthogs.atlassian.net/browse/WD-12829

feat: /azure/pro redesign

---

templates/gcp/pro.html

- Apply rebranding for /gcp/pro
- [Copy docs](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit)
- [Figma](https://www.figma.com/design/vz3yAG1nYI7r5gc3SpTUOw/24.10-ubuntu.com%2Fgcp-(Google-Cloud)?node-id=54-3218&node-type=instance&m=dev)
- Go to https://ubuntu-com-14312.demos.haus/gcp/pro
- Check that design matches Figma and content matches copy docs
- Check with medium and small screens
Fixes [WD-12855](https://warthogs.atlassian.net/browse/WD-12855)
[WD-12855]: https://warthogs.atlassian.net/browse/WD-12855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

feat: /gcp/pro rebranding

---

templates/gcp/pro.html

Rebrand /gcp/pro

---

templates/azure/pro.html

Rebrand /azure/pro

---

templates/openstack/what-is-openstack.html

- View the site in your web browser at: https://ubuntu-com-[PR].demos.haus/openstack/what-is-openstack
- Make sure that the suggested changes in [this document](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#heading=h.c45r73q8oci4) are applied to the page and resolve them.
Fixes [WD-14940](https://warthogs.atlassian.net/browse/WD-14940)
[WD-14940]: https://warthogs.atlassian.net/browse/WD-14940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy doc update what-is-openstack

---

templates/confidential-computing/ai.html

- update the copy based on the [copydoc](https://docs.google.com/document/d/1TZ_jK3ReetAU2qA_YxfZL8i4j_lFidcF6F2Xup8R8Nc/edit)
Fixes [#WD-14731](https://warthogs.atlassian.net/browse/WD-14731)

copy: update /confidential-computing/ai. WD-14731

---

templates/openstack/what-is-openstack.html

- Copydoc update comment by requester: https://warthogs.atlassian.net/browse/WD-14940?focusedCommentId=583033
- Copydoc link: https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit
- View the site in your web browser at: https://ubuntu-com-14340.demos.haus/openstack/what-is-openstack
- Check if the youtube video player looks and works as expected and is responsive in all the display sizes.
Fixes [WD-14940](https://warthogs.atlassian.net/browse/WD-14940?atlOrigin=eyJpIjoiMmQwYzg0MzIxOTU5NDE0NTgxNzgyZWE4Y2QwZGNjYWQiLCJwIjoiaiJ9)
[WD-14940]: https://warthogs.atlassian.net/browse/WD-14940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

feat(openstack): Replace youtube URL with embed

---

templates/legal/ubuntu-pro/personal/_markdown.html
templates/legal/ubuntu-pro/personal/index.md

Copy update legal ubuntu pro
- [Demo](https://ubuntu-com-14334.demos.haus/legal/ubuntu-pro/personal)
- [Copydoc](https://docs.google.com/document/d/1b2TSeqGfBsmZMepXGEGkEWyTDo0M5aHmyqaQIzEZfPs/edit)
Fixes # [WD-15200](https://warthogs.atlassian.net/browse/WD-15200)
[WD-15200]: https://warthogs.atlassian.net/browse/WD-15200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-15200 Copy update legal ubuntu pro

---

templates/security/livepatch.html

- Changed text according to WD-15113 Copy Updates (https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit)
- Quick link: http://localhost:8001/security/livepatch
- Navigate to http://localhost:8001/security/livepatch and observe the changes.
Fixes #

feat: [WD-15113] Copy update for ubuntu>security>livepatch

---

templates/about/release-cycle.html

- Updated copy based on [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#heading=h.s6x9gb573nib)
- Go to https://ubuntu-com-14335.demos.haus/about/release-cycle and see the paragraph matches the [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#heading=h.s6x9gb573nib) for maintenance and security updates
Fixes https://warthogs.atlassian.net/browse/WD-15202

WD-15202-Update-https-ubuntu.com-about-release-cycle

---

templates/certified/model-details.html

Fixed Space Bug
- [Demo](https://ubuntu-com-14349.demos.haus/certified/202207-30472) 
Fixes #14289 
Issue [WD-14874](https://warthogs.atlassian.net/browse/WD-14874)
Issue
Fixed 
[WD-14874]: https://warthogs.atlassian.net/browse/WD-14874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14874 Fixed Space Bug

---

templates/case-study/base_case-study.html
templates/case-study/esa.html
templates/case-study/grundium-ubuntu-pro-for-devices.html
templates/macros/_macros-cta.jinja
templates/macros/_macros-hero.jinja
templates/macros/_macros-highlights.jinja
templates/macros/_macros-image.jinja
templates/macros/_macros-quote.jinja
templates/macros/_macros-text-list.jinja
templates/macros/_macros-text.jinja

- Create new case study using macros
- Wrap default CTA in `cta_content` block, added a new macro for CTA
- Update quote macros with Vanilla's changes
- Go to https://ubuntu-com-14338.demos.haus/case-study/grundium-ubuntu-pro-for-devices
- Check that content matches [copy doc](https://docs.google.com/document/d/1wM1vo24SFowPaAnxWV9wfU-w6PVDq7RczM_5ZOb8OZM/edit#heading=h.eto59uxtlv76) and [design](https://www.figma.com/design/rEDsQqLe8SfnvoxCcXJYLr/Case-studies?node-id=1-1276&node-type=frame&t=ji6rTzF77DDB3pM2-0) 
- Go to https://ubuntu-com-14338.demos.haus/case-study/esa
- Check that the footer CTA is default "Contact Us" and the quotes are rendering as expected
Fixes [WD-14824](https://warthogs.atlassian.net/browse/WD-14824)
[QA …

Create new Grundium case study

---

templates/pricing/consulting.html
templates/shared/pricing/_data-solutions.html
templates/shared/pricing/_maas-deployment.html

- Apply copy changes as per [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit)
- Waiting for stakeholders to update link for datasheet - [comment here](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit?disco=AAABV9RHsng)
- Go to https://ubuntu-com-14348.demos.haus/pricing/consulting
- Check that content matches [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit)
Fixes [wd-15203](https://warthogs.atlassian.net/browse/WD-15203)

Apply copy updates for /pricing/consulting

---

templates/download/intel-nuc.html

- Update /download/intel-nuc copy for 24.10 release [copydoc](https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit)
- Ran djlint, I have left comments for my changes
- Open [the demo](https://ubuntu-com-14364.demos.haus/download/intel-nuc)
- Check the changes match the [copydoc](https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit)
Fixes https://warthogs.atlassian.net/browse/WD-15446

chore: Update /download/intel-nuc copy for 24.10 release

---

templates/case-study/grundium-ubuntu-pro-for-devices.html

- Remove "chip" from paragraph as requested [here](https://warthogs.atlassian.net/browse/WD-14824?focusedCommentId=587466)
- Remove "chip" from the last paragraph
Fixes #

Update case study paragraph

---

templates/case-study/grundium-ubuntu-pro-for-devices.html

- Add symbol to paragraph as requested [here](https://warthogs.atlassian.net/browse/WD-14824?focusedCommentId=588202) 
Fixes #

Update grundium case study

---

static/files/forms-data.json
static/js/src/dynamic-forms.js
static/sass/styles.scss
templates/aws/base_aws.html
templates/aws/index.html
templates/templates/base.html

Added a banner for form submission. Banner text agreed with UX
REMOVE FORM FROM /AWS BEFORE MERGE
- Check that the banner is correctly added and can be used for form submission
[WD-13873](https://warthogs.atlassian.net/browse/WD-13873)
[WD-13873]: https://warthogs.atlassian.net/browse/WD-13873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13873 - add banner for form submission

---

templates/pricing/thank-you.html

- Rebase /pricing/thank-you based on [figma design](https://www.figma.com/design/vxxQijDub9nQrU3ZAYcXri/Pricing?node-id=0-1&node-type=canvas&t=zWIbN8ZHdZbmYrFX-0)
- Check [the demo](https://ubuntu-com-14347.demos.haus/) matches the design
- Check page is navigable with keyboard
Fixes https://warthogs.atlassian.net/browse/WD-12870

refactor: Rebrand /pricing/thank-you

---

templates/download/server/manual.html

- Update /download/server for 24.10 update 
- Fix JS for tabs
- Go to https://ubuntu-com-14363.demos.haus/download/server
- Compare page against [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
- QA all the tabs are working properly (Check tabs are working fine when page is refreshed as well)
Fixes #https://warthogs.atlassian.net/browse/WD-14862

WD-14862 update /download/server for 24.10 update

---

static/sass/styles.scss
templates/pricing/desktop.html

- Rebrand /pricing/desktop based on the [figma design](https://www.figma.com/design/vpzDGzFRgFK0hgvUdQvCPe/Pricing-Bubble?node-id=4-5405&node-type=frame&t=g4qtPfAPE20pE5xw-0)
- There were also some minor content changes I picked up from the design but haven't been updated in the [copydoc](https://docs.google.com/document/d/1xVtaZ7wr5sdBqye3Gc-XWXEpNqXaol8uDdMwJ_KyOO8/edit#heading=h.47boiqcqz61m). 
- Check out [the demo](https://ubuntu-com-14366.demos.haus/pricing/desktop)
- Check that it matches the [figma design](https://www.figma.com/design/vpzDGzFRgFK0hgvUdQvCPe/Pricing-Bubble?node-id=4-5405&node-type=frame&t=g4qtPfAPE20pE5xw-0)
- Check that it meets accessibility standards
- Test on all screen sizes
Fixes https://warthogs.atlassian.net/browse/WD-12864
[QA …

refactor: Rebrand /pricing/desktop

---

static/sass/_pattern_table.scss
templates/pricing/pro.html

- Rebrand /pricing/pro based on [figma design](https://www.figma.com/design/vxxQijDub9nQrU3ZAYcXri/Pricing?node-id=0-1&node-type=canvas&t=zWIbN8ZHdZbmYrFX-0)
- Make tables more accessible
- Check that [the demo](https://ubuntu-com-14346.demos.haus/pricing/pro) matches the design
- Check that the page is accessible with keyboard and screen reader
Fixes https://warthogs.atlassian.net/browse/WD-12868

refactor: Rebrand /pricing/pro

---

templates/download/cloud/index.html
templates/summit/_base_summit.html
templates/summit/index.html

- Go to the below demo link and check if there are no regressions, check responsiveness on different devices (mobile, tablet, etc.)
- https://ubuntu-com-14316.demos.haus/summit
Fixes [WD-15079](https://warthogs.atlassian.net/browse/WD-15079)
[WD-15079]: https://warthogs.atlassian.net/browse/WD-15079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add ubuntu summit 24 page

---

templates/security/cves/about.html

- Update copy as per [doc](https://docs.google.com/document/d/1fsKWdmAEv4QEoVPsZEwff3fYG3a6RkD5-BCkk13LxPQ/edit)
- View the site locally in your web browser at: https://ubuntu-com-14394.demos.haus/security/cves/about#priority
Fixes https://warthogs.atlassian.net/browse/WD-14903

/security/cves/about copy update

---

templates/legal/trademarks/index.md

- Copy update on /lega/trademarks
- Go to https://ubuntu-com-14393.demos.haus/legal/trademarks
- Compare page against https://docs.google.com/document/d/1o4P7HEIop3o4oibUH8rbj6mxIBmHakt-djZlpcpTW-I/edit
Fixes #https://warthogs.atlassian.net/browse/WD-15673

Copy update on /lega/trademarks

---

templates/confidential-computing/ai.html

- Updated copy as per [doc](https://docs.google.com/document/d/1TZ_jK3ReetAU2qA_YxfZL8i4j_lFidcF6F2Xup8R8Nc/edit?disco=AAABV6Fzha0)
- Drive by:
- Ran djlint to format image template 
- View the site locally in your web browser at: https://ubuntu-com-14395.demos.haus/confidential-computing/ai
- See that the link has been updated
Fixes https://warthogs.atlassian.net/browse/WD-14735

/confidential-computing/ai copy update

---

templates/landscape/pricing.html

- Updated [/landscape/pricing](https://ubuntu-com-14406.demos.haus/landscape/pricing) page - see [copy doc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit)
- Open this: [demo page](https://ubuntu-com-14406.demos.haus/landscape/pricing)
- Check that the changes in the [copy doc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit) are implemented
Fixes [WD-15769](https://warthogs.atlassian.net/browse/WD-15769) …

fix(copy): Update https://ubuntu.com/landscape/pricing [WD-15769]

---

templates/legal/companies.html

- Updated copy as per [doc](https://docs.google.com/document/d/1y1wPpmeS_BhbRXRdoUJmaTPIMHC_72UzqZG36oP0yWw/edit?tab=t.0)
- View the site locally in your web browser at: https://ubuntu-com-14413.demos.haus/legal/companies
Fixes https://warthogs.atlassian.net/browse/WD-15775

/legal/companies copy update

---

templates/ai/roadshow.html
templates/automotive/resources.html

- Fix broken sections in /ai/roadshow and /automotive/resources
- Go to https://ubuntu-com-14423.demos.haus/ai/roadshow and https://ubuntu-com-14423.demos.haus/automotive/resources
- Check that the sections do not overlap
Fixes [WD-15877](https://warthogs.atlassian.net/browse/WD-15877) and https://github.com/canonical/ubuntu.com/issues/14420
[WD-15877]: https://warthogs.atlassian.net/browse/WD-15877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix deprecated use of p-rule

---

templates/case-study/grundium-ubuntu-pro-for-devices.html
templates/case-study/sbi-bits.html
templates/macros/_macros-image.jinja
webapp/views.py

- Create new case study for SBI BITS
- Update image macro and make caption as an optional parameter 
- Update alt text for Grundium logo
- Go to https://ubuntu-com-14424.demos.haus/case-study/sbi-bits
- Check that content matches [design](https://www.figma.com/design/wFUlTyglezhNoKYUR3CJ5A/SBI-Bits-case-study?node-id=54-818&node-type=frame&t=cogYtWECKuHIrGke-0) and [copy doc](https://docs.google.com/document/d/1tzLuweh3wM6P38O7U3HFEjb7jnXd1_IWSvM-uUkeiQo/edit?tab=t.0)
Fixes [WD-15699](https://warthogs.atlassian.net/browse/WD-15699)
[WD-15699]: https://warthogs.atlassian.net/browse/WD-15699?atlOrigin=eyJpIjoiNWR …

Create SBI BITS case study

---

navigation.yaml

- Update the Landscape login URL to get [the linkchecker](https://github.com/canonical/ubuntu.com/actions/runs/11475089717/job/31932247819) to pass

fix(links): Update the Landscape login URL

---

static/sass/_pattern_tube-line.scss
templates/20years/index.html

- Refresh social wall on /20years
- Go to /20years
- Compare page against https://docs.google.com/document/d/1vlENASSxNJdnK5tRuNYEZGVbh_qrVN0lhon8SOYo6A0/edit?tab=t.0
Fixes #https://warthogs.atlassian.net/browse/WD-15739?focusedCommentId=599065&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-599065

Refresh social wall on /20years

---

templates/20years/index.html

- Fix poster link
- Change yr to year
- Go to https://ubuntu-com-14450.demos.haus/20years
- Go to "Access the poster" and check the link works

Fix poster link

---

konf/site.yaml

Route requests to `/security/api/*.json` into a dedicated service

Route notice api detail requests to their own service

---

templates/case-study/grundium-ubuntu-pro-for-devices.html

- Updated wording in `/case-study/grundium-ubuntu-pro-for-devices`.
- View the site locally in your web browser at: http://0.0.0.0:8001/ (or open demo)
- Go to http://0.0.0.0:8001/case-study/grundium-ubuntu-pro-for-devices
- Check that the updated wording matches the [copy doc](https://docs.google.com/document/d/1wM1vo24SFowPaAnxWV9wfU-w6PVDq7RczM_5ZOb8OZM/edit?tab=t.0)
https://warthogs.atlassian.net/browse/WD-15822

/case-study/grundium-ubuntu-pro-for-devices copy update

---

templates/azure/index.html

- Updated the /azure page
- Go to https://ubuntu-com-14456.demos.haus/azure
- Compare to [copy doc](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-16058

chore: Refresh Azure page

---

templates/aws/workspaces.html

Copy update ubuntu workspaces
- [Copydoc](https://docs.google.com/document/d/1qC22TM6KZTlxK3CScf-RQ4RUiMUhIBcjSWGur-dbYVA/edit?tab=t.0#heading=h.c6wjbvvp8mcm)
- [Demo](https://ubuntu-com-14484.demos.haus/aws/workspaces)
Fixes # [WD-16975](https://warthogs.atlassian.net/browse/WD-16975)
[WD-16975]: https://warthogs.atlassian.net/browse/WD-16975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

WD-16975 Copy update ubuntu workspaces

---

templates/ceph/index.html
templates/openstack/features.html
templates/pricing/pro.html

- Updates content for some relating to ceph and some spelling changes
- Compare [/ceph copydoc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit?tab=t.0#heading=h.kea8i4rtzrx) to [the /ceph demo](https://ubuntu-com-14482.demos.haus/ceph) (note: The diagram changes and footer changes will be handled in the rebranding)
- Compare [/pro/pricing copydoc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit?tab=t.0) to the [/pro/pricing demo](https://ubuntu-com-14482.demos.haus/pricing/pro)
- Compare [/openstack/features copydoc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit?tab=t.0) to [/openstack/features features demo](https://ubuntu-com-14482.demos.haus/openstack/features)
Fixes …

chore: Update content for ceph

---

templates/16-04/_release-chart-1604.html
templates/18-04/_release-chart-1604.html
templates/18-04/aws.html
templates/18-04/azure.html
templates/18-04/gcp.html
templates/18-04/ibm.html
templates/18-04/index.html
templates/18-04/oci.html
templates/account/checkout.html
templates/advantage/subscribe/index.html
templates/automotive/developers.html
templates/aws/fips.html
templates/azure/index.html
templates/base_index.html
templates/ceph/index.html
templates/desktop/index.html
templates/engage/unlisted/shell-onboarding.html
templates/internet-of-things/smart-city.html
templates/telco/openran.html

- update 'Extended security maintenance' to 'Expanded security maintenance' across site to align with the branding change reflected at https://ubuntu.com/security/esm
- I used find and replace and although I was careful I could have made a mistake. Please check the code.
Fixes https://warthogs.atlassian.net/browse/WD-16372

feat: update 'Extended security maintenance' to 'Expanded security maintenance' across site

---

static/files/sitemap.xml

- Add /summit to sitemap.xml
- Open https://ubuntu-com-14493.demos.haus/static/files/sitemap.xml and search for /summit
Fixes https://github.com/canonical/ubuntu.com/issues/14476

feat(/summit): Add /summit to sitemap.xml

---

templates/kubernetes/docs/tutorials-index.md

K8s docs update tutorial page

---

static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts

This reverts commit d7f5941cf79466114ac027293fed7762f6465b36. (PR https://github.com/canonical/ubuntu.com/pull/14462)

Revert "Restrict channel user from editing billing details"

---

.github/.jira_sync_config.yaml

- Specify a new Jira epic link for 25.04 GH issues in Jira integration configuration file

Update Jira epic in .jira_sync_config.yaml file

---

static/js/src/dynamic-forms.js
static/js/src/static-forms.js

- Remove "name" attribute on radio field
- Fixes failing marketo submission
- Go to any static forms e.g https://ubuntu-com-14510.demos.haus/contact-us/form?product=pro
- Fill up form and submit
- Check that payload submission does not have "how-many-machines" field and form submission goes through Marketo successfully
Fixes #

Fix radio field bug for static forms

---

konf/site.yaml

Route all security API paths to the same service

Route all security API staging paths to the same service

---

templates/case-study/lucid-aws-fedramp-compliance-case-study.html

- Copy update on /case-study/lucid-aws-fedramp-compliance-case-study
- Go to  https://ubuntu-com-14533.demos.haus/case-study/lucid-aws-fedramp-compliance-case-study
- Compare page against [copy doc](https://docs.google.com/document/d/11NbG_hLg0zZdMAzkOLXaS4ItOUfsRF31VAA1-093m_g/edit?tab=t.0)
Fixes #https://warthogs.atlassian.net/browse/WD-17502

Copy update on /case-study/lucid-aws-fedramp-compliance-case-study

---

package.json
static/sass/styles.scss
templates/internet-of-things/appstore.html
templates/internet-of-things/shared/_latest-news-iot.html
templates/internet-of-things/shared/_try-ubuntu-core.html
templates/shared/contextual_footers/_iot_newsletter_signup.html
yarn.lock

- Applied redesign as per [doc](https://docs.google.com/document/d/1CKwmPDDtXOIgw-jSZFwzP-qLMc_rS_dUACpHQXlg0fA/edit?tab=t.0) and [design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=0-1&node-type=canvas&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14523.demos.haus/internet-of-things/appstore
Fixes https://warthogs.atlassian.net/browse/WD-16630

feat: /internet-of-things/appstore redesgin

---

templates/pro/devices.html

- Apply changes as per [doc](https://docs.google.com/document/d/1i_3nPkSpCQJ4jfOwN380sdfuTxaiDuDIgDfk01wVPqo/edit?tab=t.0)
- View the site locally in your web browser at: https://ubuntu-com-14543.demos.haus/pro/devices
- Check against doc 
Fixes https://warthogs.atlassian.net/browse/WD-17395

feat: /pro/devices copy update

---

static/sass/styles.scss
templates/internet-of-things/index.html

- Applied changes as per [doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit?tab=t.0#heading=h.kbutqxr7kac7) and [design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=1-9092&node-type=instance&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14537.demos.haus/iot
Fixes https://warthogs.atlassian.net/browse/WD-16628

feat: /iot redesign

---

templates/internet-of-things/management.html

- Redesigned ubuntu.com/internet-of-things/management
- View the site locally in your web browser at: https://ubuntu-com-14529.demos.haus/internet-of-things/management
- Match the website with Design and Copydoc.
- [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-15306&t=4kUhsH39i1i4UsV9-1)
- [Copydoc](https://docs.google.com/document/d/1C-1ywVzBHkc4I3f-G7Rpy-epaXdbPisbolHUC1Jb7cE)
Fixes #[16635](https://warthogs.atlassian.net/browse/WD-16635)

WD-16635 Redesigned internet-of-things/management

---

templates/case-study/esa.html

Update /case-study/esa meta description.
[Doc](https://docs.google.com/document/d/1jc5DY4-9pDYQC04Egdt0If4_jrYn1mIBDwhJfILO46w/edit?tab=t.0)
Fixes [#WD-17387](https://warthogs.atlassian.net/browse/WD-17387)

copy: update /case-study/esa meta description. WD-17387

---

templates/internet-of-things/smart-city.html

- Redesigned ubuntu.com/internet-of-things/smart-city
- View the site in your web browser at: https://ubuntu-com-14534.demos.haus/internet-of-things/smart-city
- Match the website with Design and Copydoc.
- [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-16261&t=4kUhsH39i1i4UsV9-1)
- [Copydoc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY)
Fixes #[16645](https://warthogs.atlassian.net/browse/WD-16645)

WD-16645 Redesigned internet-of-things/smart-city

---

static/sass/styles.scss
templates/internet-of-things/gateways.html

- Rebranded /internet-of-things/gateways
- There may be some changes to content, please refer copydoc
- [Demo](https://ubuntu-com-14536.demos.haus/internet-of-things/gateways)
- [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=0-1&node-type=canvas&m=dev)
- [Copydoc](https://docs.google.com/document/d/18ffTcNolrtJS9AvjMfa8KW94uLfC0KzmHtTe-jMYmlo/edit?tab=t.0)
- This is a big page, please look for incorrect links and content dicrepancies.
Fixes # [WD-16643](https://warthogs.atlassian.net/browse/WD-16643)
[If relevant, please include a …

WD-16643 Rebrand /internet-of-things/gateways

---

templates/openstack/support.html

- Changed the word `Canonical` to `Charmed` 
- Go to https://ubuntu-com-14564.demos.haus/openstack/support and check if you can verify the change according to the [copy doc](https://docs.google.com/document/d/1mHaZQ_VZnISTUEpYKiVK-Ejr5ne8lVevpxEc0LpXYKI/edit?tab=t.0#heading=h.nz682z8glukq)
Fixes #https://warthogs.atlassian.net/browse/WD-17581

chore: openstack/support page copy update

---

templates/embedded/index.html
templates/internet-of-things/shared/_latest-news-iot.html

- Rebranded ubuntu.com/embedded
- View the site in your web browser at: https://ubuntu-com-14544.demos.haus/embedded
- Match the website with Design and Copydoc.
- [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-15115&node-type=frame&t=usaNja4yG3s3e7ZI-0)
- [Copydoc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo)
Fixes #[16633](https://warthogs.atlassian.net/browse/WD-16633)

WD-16633 Rebranded embedded

---

templates/shared/forms/interactive/internet-of-things.html

- Removed pagination
- Converted to single page
- Cleanup
- Check the old modal here first: https://ubuntu.com/internet-of-things#get-in-touch
- Check the new modal at: https://ubuntu-com-14555.demos.haus/internet-of-things#get-in-touch
- Check that modal form is a single page without pagination.
- Submit the form to make sure it's working.
Fixes #[WD-17646](https://warthogs.atlassian.net/browse/WD-17646)
[WD-17646]: https://warthogs.atlassian.net/browse/WD-17646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-17646 Removed pagination from modal form and converted to single page

---

templates/shared/forms/interactive/embedded.html

- Removed pagination
- Conversion to single page
- Cleanup
- Check the old modal here first: https://ubuntu.com/embedded#get-in-touch
- Check the new modal at: https://ubuntu-com-14567.demos.haus/embedded#get-in-touch
- Check that modal form is a single page without pagination.
- Submit the form to make sure it's working.
Fixes #[WD-17753](https://warthogs.atlassian.net/browse/WD-17753)
[WD-17753]: https://warthogs.atlassian.net/browse/WD-17753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-17753 Iot embedded modal form - removed pagination + conversion to single page

---

templates/gcp/index.html

- [copydoc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit?tab=t.0)
- Check out [the demo](https://ubuntu-com-14562.demos.haus/gcp)
- Compare to content changes in the [copydoc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-17456

chore(/gcp): Update content

---

templates/security/docker-images.html

Updated the copy on /security/docker-images
- Go to https://ubuntu-com-14565.demos.haus/security/docker-images
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/1zZibtjU141e4mBxo_0PtfYxJ6e5fyaaAdFZ6v945XAM/edit?tab=t.0#heading=h.b4oh6xkbn2jq) have been made
Fixes https://warthogs.atlassian.net/browse/WD-17711

chore: Update security docker images page

---

templates/hpe/index.html

- Modified HPE page according to this [copydoc](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit?pli=1&tab=t.0).
- View the site locally in your web browser at: https://ubuntu-com-14578.demos.haus/hpe
- Check that the modifications match the copydoc and designs.
- Designs are available [here](https://www.figma.com/design/WIizcxJW1PcpPpvjUX433B/23.10-U.com---HPE-partner-page?node-id=1-647&t=2iAuUh5CkMeuMIji-0).
Fixes [WD-17695](https://warthogs.atlassian.net/browse/WD-17695)
[WD-17695]: https://warthogs.atlassian.net/browse/WD-17695?atlOrigin=eyJpIjoiNWRkNTljN …

Copy update: hpe

---

templates/download/server/thank-you.html
templates/download/shared/_server_weekly_news.html

- Apply copy updates
- Make CLI cheatsheet download link gated
- Go to https://ubuntu-com-14584.demos.haus/download/server/thank-you?version=24.04.1&architecture=amd64&lts=true
- Check that it matches [copy doc](https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit?tab=t.0)
- Click on `Download the CLI cheat sheet` CTA button
- Submit form, check that it redirects to CLI pdf
Fixes [WD-17869](https://warthogs.atlassian.net/browse/WD-17869)
[WD-17869]: https://warthogs.atlassian.net/browse/WD-17869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …

feat: Apply copy update on /server/download/thank-you

---

templates/observability/what-is-observability.html

- Rebranded page
- View the site  in your web browser at: https://ubuntu-com-14588.demos.haus/observability/what-is-observability
- Check that it matches the following:
- [Design](https://www.figma.com/design/BycwGsYlyy6sYR6oD60O76/25.04-Observability-Rebranding?node-id=1-5699&t=btTQoadAeJLMzT0A-0)
- [CopyDoc](https://docs.google.com/document/d/1eoqDQzFiRJY2u_EO4JBuLBLqae4K3nrEf3qd88KHw0Y/edit)
Fixes #[WD-16847](https://warthogs.atlassian.net/browse/WD-16847)
[WD-16847]: https://warthogs.atlassian.net/browse/WD-16847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-16847 Rebranded /observability/what-is-observability

---

templates/landscape/features.html

- Rebranded page
- Updated assets
- View the site  in your web browser at: https://ubuntu-com-14576.demos.haus/landscape/features
- Check that it matches the following:
- [Design](https://www.figma.com/design/btsxPLFKGPWDlbQ4rjR4jZ/25.04-Landscape-Rebranding?node-id=4015-1335&t=gnl4MqHIyDU2tB58-0)
- [CopyDoc](https://docs.google.com/document/d/1AM3pioDfZapMw_HpQOYei2k7IfiChu0YN8Iwp7JzWRY/edit?tab=t.0#)
Fixes #[WD-16836](https://warthogs.atlassian.net/browse/WD-16836)
[WD-16836]: https://warthogs.atlassian.net/browse/WD-16836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-16836 Rebranded /landscape/features page

---

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx

- Fix the failing JS tests
- Check all the tests pass
Fixes #

fix js tests

---

webapp/handlers.py

- Updated  CSP
- Open https://ubuntu-com-14605.demos.haus/
- check if there is a CSP error ddisplayed in the terminal.
Fixes [#WD-17993](https://warthogs.atlassian.net/browse/WD-17993)

fix: add jspm to the CSP

---

.github/workflows/playwright.yaml
package.json
playwright.config.ts
tests/playwright/tests/certified.spec.ts

- Fixed playwright test failing
- Upgraded playwright version in `package.json`
- Updated tests in `certified.spec.ts`
- Check all Github checks pass

Fix playwright test failing

---

webapp/handlers.py

- Add CSP rule to allow form scripts

Fix tfaforms CSP rule

---

templates/case-study/lucid-aws-fedramp-compliance-case-study.html

- Updated the copy for: https://ubuntu.com/case-study/lucid-aws-fedramp-compliance-case-study
- Navigate to https://ubuntu-com-14621.demos.haus/case-study/lucid-aws-fedramp-compliance-case-study
- Verify that the copy changes match what is requested in the [copy doc](https://docs.google.com/document/d/11NbG_hLg0zZdMAzkOLXaS4ItOUfsRF31VAA1-093m_g/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-17879

chore(WD-17879): updated copy for fedramp case-study

---

templates/desktop/wsl/index.html

- Fix type (WWSL)
- Add latest WSL news section
- View the site locally in your web browser at: https://ubuntu-com-14635.demos.haus/desktop/wsl
- Make sure that the typo is fixed
- Make sure that the new latest news section is shown properly
Fixes WD-17999

Copy update: Ubuntu WSL

---

templates/base_index.html
templates/support/index.html

- Updated to links that were reported to be broken via [Links on live #1761](https://github.com/canonical/ubuntu.com/actions/runs/12705130915/job/35415630001)
- Check the new links lead to good pages with reasonable content
Fixes https://github.com/canonical/ubuntu.com/actions/runs/12705130915/job/35415630001

fix(links): Fix various broken links across the website

---

templates/16-04/index.html
templates/ai/roadshow.html
templates/automotive/developers.html
templates/azure/confidential-computing.html
templates/azure/index.html
templates/base_index.html
templates/ceph/index.html
templates/certified/why-certify.html
templates/credentials/faq.html
templates/credentials/self-study.html
templates/desktop/organisations.html
templates/desktop/wsl/index.html
templates/download/qualcomm-iot.html
templates/download/server/thank-you-s390x.html
templates/embedding/faqs.html
templates/engage/unlisted/shell-onboarding.html
templates/gcp/fips.html
templates/gov/index.html
templates/hpc/use-cases.html
templates/internet-of-things/index.html
templates/internet-of-things/management.html
templates/legal/terms-and-policies/credentials-terms.html
templates/managed/index.html
templates/openstack/what-is-openstack.html
templates/robotics/ros-esm.html
templates/security/cves/index.html
templates/shared/_resources_ceph.html
templates/solutions/open-source-security/cyber-resilience-act/index.html
templates/support/index.html
templates/telco/cnf.html

- Replace all local links with relative ones to clean things up and prevent local and demo links from jumping out into the real world.
- Check the code changes are correct and will not cause any issues

chore(links): Convert all local links to relative links

---

static/js/src/dynamic-forms.js
templates/observability/index.html
templates/shared/forms/interactive/observability-contact-us.html

- Removed pagination
- Cleanup
- Check the old modal here first: https://ubuntu.com/observability#get-in-touch
- Check the new modal at: https://ubuntu-com-14627.demos.haus/observability#get-in-touch
- Check that modal form is a single page without pagination.
- Submit the form to make sure it's working.
Fixes #[WD-18039](https://warthogs.atlassian.net/browse/WD-18039)
[WD-18039]: https://warthogs.atlassian.net/browse/WD-18039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-18039 Removed pagination from Observability contact modal

---

templates/openstack/consulting.html
templates/shared/pricing/_openstack-packages.html

- Open [demo](https://ubuntu-com-14645.demos.haus/openstack/consulting)
- Or run the website locally and go to http://0.0.0.0:8001/openstack/consulting
- Compare with [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/)
https://warthogs.atlassian.net/browse/WD-18148

copy update: openstack/consulting

---

static/js/src/cookie-policy-with-callback.js
static/js/src/prepare-form-inputs.js
webapp/views.py

- Add `utms` cookie that stores multiple utm URL parameters into one string
- On form submission, check for `utm` cookie and include it in enrichment payload (contact info on Marketo)
- Go to demo
1. If no utms cookie present and URL has utm params, **Set cookie**
- Add cookie to URL param e.g `/ai?utm_term=example&utm_medium=another_example&utm_fail=test_fail`
- Check that `utms` cookie is added and has the string of concatenated utm e.g `utm_term:example&utm_medium:another_example&utm_fail:test_fail`
- Go to any form on the page, make sure not to end the session
- Submit the form and check that enrichment payload has utm values on Marketo. Example: 
2. If utms cookie present and URL has utm params, **Update cookie**
- Add cookie to URL param e.g …

feat: Implement utms cookie to store utm parameters in a session

---

templates/dell/powerflex.html

- Open [demo](https://ubuntu-com-14639.demos.haus/dell/powerflex).
- OR: run the project locally with `dotrun` and go to: http://0.0.0.0:8001/dell/powerflex
- Compare the page against the [design](https://www.figma.com/design/S6KvNUt0agl0bcbp6wjhnB/24.10-Ubuntu.com%2Fpartners?node-id=2932-4029&t=hQDSFDzLIfwLlvoR-0) and the [copydoc](https://docs.google.com/document/d/1Ep9mXvFXf9a1IE0TVJCfcbnAUTqtDOL9XE93pvK1V_A/edit?tab=t.0#heading=h.n4yj7d5ptzm9).
https://warthogs.atlassian.net/browse/WD-17694

new page: dell/powerflex

---

.github/workflows/performance-check.yaml

- Add Page Speed Insights as a Github Action
- Check the [code matches](https://github.com/JakePartusch/psi-action) what you would expect as a basic self-running workflow.

build(performance): Add Page Speed Insights as a Github Action

---

templates/kubernetes/_k8s-on-openstack.html
templates/kubernetes/charmed-k8s.html

- Applied page redesign as per [doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit?tab=t.0) and [figma](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=555-8988&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14651.demos.haus/kubernetes/charmed-k8s
Fixes https://warthogs.atlassian.net/browse/WD-12875

feat: /kubernetes/charmed-k8s redesign

---

.github/workflows/performance-check.yaml

- Remove the IDs from the performance check

build(performance): Remove ID's from performance-check

---

webapp/views.py

- Redirected to corresponding host
- Open any form, like [u.com/internet-of-things#get-in-touch](https://ubuntu-com-14682.demos.haus/internet-of-things#get-in-touch)
- Submit the form and verify redirect is working as expected.
Fixes #[WD-18060](https://warthogs.atlassian.net/browse/WD-18060)
[WD-18060]: https://warthogs.atlassian.net/browse/WD-18060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-18060] Redirect to corresponding host upon marketo form submission, w.r.t., relative and absolute return urls

---

.github/workflows/pr.yaml
templates/case-study/sbi-bits.html

Capitalize all instances of “Legacy Support”
- Compare with [copy doc](https://docs.google.com/document/d/1tzLuweh3wM6P38O7U3HFEjb7jnXd1_IWSvM-uUkeiQo/edit?tab=t.0)
https://warthogs.atlassian.net/browse/WD-18576

copy update:/case-study/sbi-bits

---

templates/ceph/index.html

- update video link
- View the site locally in your web browser at: https://ubuntu-com-14680.demos.haus/ceph
- Make sure that the suggested changes from the [copy doc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit?tab=t.0) are applied
Fixes WD-18205

Copy update ceph page

---

templates/gcp/fips.html

- Copy update according to [this doc](https://docs.google.com/document/d/17Rr6Fdrr7xSPi1g2h7GMTztQUGYqz2hdbNUqK0uQihw/edit?tab=t.0)
- Check the [demo](https://ubuntu-com-14717.demos.haus/gcp/fips) (or checkout branch)
- Compare the changes from the [copy doc](https://docs.google.com/document/d/17Rr6Fdrr7xSPi1g2h7GMTztQUGYqz2hdbNUqK0uQihw/edit?tab=t.0)
- Ensure all links work as expected
Fixes [WD-19050](https://warthogs.atlassian.net/browse/WD-19050)
[WD-19050]: https://warthogs.atlassian.net/browse/WD-19050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

copy update: /gcp/fips

---

templates/ai/consulting.html

- Remove AI consulting pricing as requested in the latest [copy doc](https://docs.google.com/document/d/1Zj9agFHVT5pEXapazCcoh_o2v0jEU1Oe7BmdvDbDGrg/edit?tab=t.0) comments.
- Open [demo](https://ubuntu-com-14719.demos.haus/ai/consulting). Or run the project locally and go to http://localhost:8001/ai/consulting
- Check that there's no pricing, as requested in the [copy doc](https://docs.google.com/document/d/1Zj9agFHVT5pEXapazCcoh_o2v0jEU1Oe7BmdvDbDGrg/edit?tab=t.0)
https://warthogs.atlassian.net/browse/WD-19045

copy update: remove AI consulting pricing

---

konf/site.yaml
static/js/src/canonical-cla/contexts/SignForm.tsx

- add production missing API url for Canonical CLA

add production missing API url for Canonical CLA

---

templates/security/cis.html

- Applied redesign as per [doc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit?tab=t.0) and [design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=466-14238&p=f&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14732.demos.haus/security/cis
Fixes https://warthogs.atlassian.net/browse/WD-12038

feat: /security/cis redesign

---

templates/edge-computing/index.html

- Rebranded u.com/edge-computing page
- Check out the [demo](https://ubuntu-com-14731.demos.haus/edge-computing) in your web browser
- Make sure the page content and design matches the [copydoc](https://docs.google.com/document/d/1DdOhFZyvaew0NWW2Uo-EtaB81wzCy-ApdRmanTinyVM/edit?tab=t.0) and [figma design](https://www.figma.com/design/n3Pm4P8GGD9QPNxvrXD3QL/25.04-Edge-Computing-Rebranding)
Fixes #[WD-16596](https://warthogs.atlassian.net/browse/WD-16596)
[WD-16596]: https://warthogs.atlassian.net/browse/WD-16596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-16596] feat: Rebrand u.com/edge-computing page

---

templates/aws/fips.html

- Update aws/fips with changes requested in this [copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit)
- https://ubuntu-com-14744.demos.haus/aws/fips
- check changes match copy doc
Fixes [WD-19281](https://warthogs.atlassian.net/issues/WD-19281)
[WD-19281]: https://warthogs.atlassian.net/browse/WD-19281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: /aws/fips copy update

---

templates/base_index.html

- Update homepage from the copy doc found [here](https://warthogs.atlassian.net/browse/WD-19404)
- Check that the copy updates are correctly applied
https://warthogs.atlassian.net/browse/WD-19404

Update homepage WD-19404

---

static/files/sitemap.xml
templates/security/vex.html

- /security/vex
- visit [/security/vex](https://ubuntu-com-14755.demos.haus/security/vex)
- compare with design: https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=1865-5429&t=IPBks6FjL7Lv0pCU-1
- compare with copy doc: https://docs.google.com/document/d/1blB3R7DMlx44T1VTNJcLwlMJVAuP6Kk8j6M7CgxnGRs/edit?tab=t.0
Fixes [#WD-18749](https://warthogs.atlassian.net/browse/WD-18749)

build vex page

---

templates/appliance/index.html

- Rebranded appliance landing page.
- View the site in your web browser using this [demo](https://ubuntu-com-14757.demos.haus/appliance)
- Verify the page matches the following
- [Copydoc](https://docs.google.com/document/d/1Fcr5b5Rn06AB89D6DGPmoIgXLxLalijMhwnu_IyUxV4/edit?tab=t.0)
- [Figma Design](https://www.figma.com/design/POgmRw4Rpq1hlgaD9DN8mS/ubuntu.com%2Fappliance?node-id=100-3420&t=wLiYpgwYMwapOk1y-1)
Fixes #[WD-16574](https://warthogs.atlassian.net/browse/WD-16574)
[WD-16574]: https://warthogs.atlassian.net/browse/WD-16574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-16574] Rebranded /appliance

---

.github/workflows/performance-check.yaml

- Set the performance checks to execute weekly and report into the channel if they fail.
- Check the code looks good

fix(ci): Perf checks weekly cron report

---

static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx

- Copy update on /pro/subscribe
- Compare page against [copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?tab=t.0)
Fixes #https://warthogs.atlassian.net/browse/WD-19414

Copy update on /pro/subscribe

---

templates/security/platform-security.html

- Create new platform security page based on this [copy doc](https://docs.google.com/document/d/1c1l_IfbrtF-b6JN0IDZiSHe2YWdLrLo_NQ-1Ajvf5Qk/edit?tab=t.0) and this [design](https://www.figma.com/file/pc4AcZqcXvWJqrm4t1x1y6?type=design&node-id=94%3A63&mode=dev)
- go to `/security/platform-security`
- verify page matches design and copy doc
Fixes [WD-17175](https://warthogs.atlassian.net/browse/WD-17175)
[WD-17175]: https://warthogs.atlassian.net/browse/WD-17175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(new page): /security/platform-security

---

templates/masters-conference/index.html

- Fix the video links on the master's conference page
- Updated to use the hero pattern
- Go to /masters-conference
- See the hero looks the same but more modern
- Check all the videos load (unlike production)
Fixes https://warthogs.atlassian.net/browse/WD-19466

fix: Masters conferences videos

---

templates/azure/fips.html

- Compare with [copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit?tab=t.0#heading=h.c6wjbvvp8mcm)
https://warthogs.atlassian.net/browse/WD-19440

azure/fips: update content

---

templates/templates/_getfeedback.html

- Fixed Reference error in all webpages  
- Go to any webpage
- Should not see `aws:194 Uncaught ReferenceError: na is not defined`
Fixes [#WD-19645](https://warthogs.atlassian.net/browse/WD-19645)

fix reference error

---

templates/appliance/hardware.html
templates/appliance/shared/_certified-appliances.html

- Rebrand /appliance/hardware
- View the site in your web browser using this [demo](https://ubuntu-com-14776.demos.haus/appliance/hardware)
- Verify the page matches the following:
- [Copydoc](https://docs.google.com/document/d/179RBNgtGr5Y8CkkYaUa6sdFaaTJTTvs_VCTr6UzECFo/edit)
- [Figma Design](https://www.figma.com/design/POgmRw4Rpq1hlgaD9DN8mS/ubuntu.com%2Fappliance)
Fixes #[WD-16583](https://warthogs.atlassian.net/browse/WD-16583)
[WD-16583]: https://warthogs.atlassian.net/browse/WD-16583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-16583] Rebranded /appliance/hardware page

---

templates/security/fedramp.html

- Make sure that the [copy docs](https://docs.google.com/document/d/1eJxGEthPLxG2CjFXTXLk6QF97DNh4VyZZ-AG2yIq8v4/edit?tab=t.0) requested change is applied
Fixes WD-19724

copy update security - FedRAMP

---

templates/desktop/organisations.html

- Copy update on authd section of desktop/organisations
- Go to [/desktop/organisations](http://0.0.0.0:8001/desktop/organisations) and scroll down to authd section
- Compare against the [copy doc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit?usp=sharing)
[WD-19452](https://warthogs.atlassian.net/browse/WD-19452)
[WD-19452]: https://warthogs.atlassian.net/browse/WD-19452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

copy update: authd section in desktop/organisations

---

templates/base_index.html

Copy update.
Copy doc: https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?tab=t.0#heading=h.wpnl3gi6thy5
- Or check the demo: https://ubuntu-com-14834.demos.haus/
- Check updated "CRA" copy and link agains copy doc
Fixes [WD-19956](https://warthogs.atlassian.net/browse/WD-19956)
[WD-19956]: https://warthogs.atlassian.net/browse/WD-19956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …

WD-19956: update security copy

---

.github/workflows/performance-check.yaml

- Add API token for the perf-checks CI
- Rename the check
- Check the code looks good

fix(performance): Add API token for the perf-checks CI

---

templates/containers/chiseled/index.html

- Fixed broken links
- View the site  in your web browser at: https://ubuntu-com-14855.demos.haus/containers/chiseled
- Click on the "Learn about using chisel in production" link and verify it works
- Click on the "Get started today" link and verify it works
Fixes broken links reported [here](https://github.com/canonical/ubuntu.com/actions/runs/13829234282/job/38689692868)

chore: fix broken links

---

templates/openstack/contact-us.html
templates/shared/_openstack_contact_us.html
templates/shared/forms/_industry.html
templates/training/contact-us.html

- As per ticket discussion, updated this form template to match [marketo fields ](https://na-sjg.marketodesigner.com/m#FOP1251)
- View the site locally in your web browser at: https://ubuntu-com-14843.demos.haus/openstack/contact-us?product=openstack
- See that submission goes through
Fixes https://warthogs.atlassian.net/browse/WD-19702

feat: Align fields with marketo for form 1251

---

static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.test.tsx
static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx
static/sass/_pattern_distributor.scss
static/sass/styles.scss

- Update distributor offer table columns
- Go to https://ubuntu-com-14869.demos.haus/pro/distributor
- Log in with a channel account
Fixes #https://warthogs.atlassian.net/browse/WD-20346

Update distributor offer table columns

---

requirements.txt
webapp/app.py

- Use form-generator Pypi package, see [repo](https://github.com/canonical/canonicalwebteam.form-generator)
- Open the demo to a form generator modal form, ex. https://ubuntu-com-14874.demos.haus/aws#get-in-touch
- Check the form works as expected
- Check another form ex. https://ubuntu-com-14874.demos.haus/embedded#get-in-touch
Fixes https://warthogs.atlassian.net/browse/WD-20470

feat: Use form-generator Pypi package

---

.github/workflows/live-links.yaml

fix: Remove action trigger from PR

---

templates/templates/footer.html

Update solutions section of footer with new links.
Rename open source security link.
- Check content matches the copydoc.
Fixes #https://warthogs.atlassian.net/browse/WD-20473

Update solutions section of footer.

---

meganav.yaml
navigation.yaml
static/sass/styles.scss
templates/summit/_base_summit.html
templates/summit/call-for-collaboration.html
templates/summit/index.html
templates/summit/shared/_latest-blogs_summit.html

- Dev create /summit/call-for-collaboration
- [Demo](https://ubuntu-com-14886.demos.haus/summit/call-for-collaboration)
- [Copydoc](https://docs.google.com/document/d/1pjIpFWL7yu6Jc2gZGqCRvckd4clPVrLtGpRwTaw9-CY/edit?tab=t.0)
- [Figma](https://www.figma.com/design/jnBr57W2MnYiCg8QYxC8el/25.04-ubuntu.com%2Fsummit?node-id=3283-5019&p=f&t=vw3zMSZbYcMLGCZI-0#-1)
Fixes # [WD-17875](https://warthogs.atlassian.net/browse/WD-17875) …

WD-17875 Dev create /summit/call-for-collaboration

---

templates/openstack/index.html

- Updated link as per [doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?tab=t.0)
- Check against doc
Fixes https://warthogs.atlassian.net/browse/WD-20584

copy update: https://ubuntu.com/openstack

---

templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
templates/desktop/organisations.html

- JIRA Issue: https://warthogs.atlassian.net/browse/WD-20691
- Navigate to ubuntu.com/desktop/organizations and verify that the correct copydoc updates have been made according to the google doc.
Fixes - Copy Doc: https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit?tab=t.0
N/A

[WD-20691] - COPYDOC: Update /desktop/organizations

---

static/js/src/advantage/distributor/components/ChannelOffersList/ChannelOffersList.tsx

- Added a search functionality to 
- Visit [/pro/distributor](https://ubuntu-com-14931.demos.haus/pro/distributor)
- Expect a search bar to appear in the offers table
- Expect search to work
Fixes [#WD-20351](https://warthogs.atlassian.net/browse/WD-20351)

add search to distibutor store

---

navigation.yaml
templates/20-04/aws.html

- Build page on /20-04/aws
- Go to  https://ubuntu-com-14935.demos.haus/20-04/aws
- Compare page against [Figma](https://www.figma.com/design/ZAihKxF2wmj9wvoPSnPKmY/Commercial--Ubuntu-Pro?node-id=5430-1154&t=bYwFO6x2SlwFuQn2-0)
Fixes #https://warthogs.atlassian.net/browse/WD-19972

Build page on /20-04/aws

---

navigation.yaml
templates/pro/free-trial.html

Open demo: https://ubuntu-com-14926.demos.haus/pro/free-trial
Compare with [design](https://www.figma.com/design/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=5484-3403&t=c7QmlQCLtZhLFQ9y-1)
Compare with [copy doc](https://docs.google.com/document/d/1USgQJcUKNz3iZYeNVeICVqGz879rlG5ztEtVxPWm8bc/edit?usp=sharing)
https://warthogs.atlassian.net/browse/WD-20094

new pro/free-trial page

---

templates/download/iot/intel-iot.html

- Copy update on /download/iot/intel-iot
- Go to [/download/iot/intel-iot](http://localhost:8001/download/iot/intel-iot)
- Ensure changes match the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit?tab=t.0)
[WD-21209](https://warthogs.atlassian.net/browse/WD-21209)
[WD-21209]: https://warthogs.atlassian.net/browse/WD-21209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy update on /download/iot/intel-iot

---

templates/download/server/power.html

- Apply changes from the [copy doc](https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit) to the page, except the one for the button as that one will be applied automatically later (pls read my comment in the copy doc)
- Open the demo page at https://ubuntu-com-14965.demos.haus/download/server/power
- Check that the change from the copy doc (except the download button) are applied
Fixes https://warthogs.atlassian.net/browse/WD-20898

[WD-20898] Copy update /download/server/power

---

releases.yaml
templates/download/raspberry-pi/index.html

- Apply copy updates as per [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit?tab=t.0)
- Go to https://ubuntu-com-14967.demos.haus/download/raspberry-pi
- See that content matches copy updates
Fixes [WD-20896](https://warthogs.atlassian.net/browse/WD-20896)
[WD-20896]: https://warthogs.atlassian.net/browse/WD-20896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Apply raspberry pi copy updates

---

releases.yaml
templates/download/raspberry-pi/index.html

Reverts canonical/ubuntu.com#14967

Revert "Apply raspberry pi copy updates"

---

releases.yaml
templates/download/raspberry-pi/index.html

- Apply copy updates as per [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit?tab=t.0)
- Go to https://ubuntu-com-14970.demos.haus/download/raspberry-pi
- See that content matches copy updates
Fixes [WD-20896](https://warthogs.atlassian.net/browse/WD-20896)
[WD-20896]: https://warthogs.atlassian.net/browse/WD-20896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Apply copy update for /download/raspberry-pi

---

templates/containers/index.html
templates/containers/shared/_container-portfolio-tabs.html

- Apply changes as per [doc](https://docs.google.com/document/d/1OtyfNeA--EJgpgvDzqcbJ8jqa6d9H5H9xyxHNxcKXvc/edit?tab=t.0#heading=h.eto59uxtlv76) and [design](https://www.figma.com/design/YfNc8KmYqa2e7JgbFo6lXa/ubuntu.com%2Fcontainers?node-id=748-4225&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14948.demos.haus/containers
Fixes https://warthogs.atlassian.net/browse/WD-20057

feat: /containers page refresh

---

package.json
templates/ceph/pricing-calculator.html
yarn.lock

- add /ceph/pricing-calculator as per [copydoc](https://docs.google.com/spreadsheets/d/1cn5daIlWGpKF5557ERFY4Ok4_0IlJKTDbZjRXcXyhjk/edit?gid=471278338#gid=471278338) and [design](https://www.figma.com/design/ulUyOFdQ7CNy0whuJ4S2FM/Ceph-Bubble)
- go to `/ceph/pricing-calculator`
- select desired storage requirements
- compare the values with results from the spreadsheet copydoc, should be an exact match for all cases
Fixes [WD-19250](https://warthogs.atlassian.net/browse/WD-19250)
[WD-19250]: https://warthogs.atlassian.net/browse/WD-19250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: ceph pricing calculator

---

templates/desktop/wsl/index.html
templates/download/raspberry-pi/index.html

- Updated hero layout as per [doc]() and [design](https://www.figma.com/design/wLOtPeQhAiExhQCwKYhi3H/Ubuntu.com-desktop?node-id=878-5161&p=f&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14984.demos.haus/desktop/wsl
Fixes https://warthogs.atlassian.net/browse/WD-21383

copy update: /desktop/wsl download links and hero image

---

templates/download/desktop/index.html

- Dev - Refresh /download/desktop to show ARM build
- update copy and assets
- View update via https://ubuntu-com-14995.demos.haus/download/desktop
- Be sure to test on mobile, tablet and desktop screen sizes 
- Check against [doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit?tab=t.0) and [design](https://www.figma.com/design/cVGimTPHky4h3BPXfrT6GB/Ubuntu.com-download?node-id=1-30&p=f&m=dev)
[Jira ticket](https://warthogs.atlassian.net/browse/WD-20676)
[Copy doc](#)
[Screenshot](https://drive.google.com/file/d/1gb2TQAlpIfIz8xKT_mvLWGPX-jJSEdl-/view?usp=drive_link)

Dev - Refresh /download/desktop to show ARM build

---

templates/desktop/flavours.html

- Updates based on the changes in the [copydoc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit?tab=t.0)
- Check out [the demo](https://ubuntu-com-14997.demos.haus/desktop/flavours)
Fixes https://warthogs.atlassian.net/browse/WD-21467

Update /desktop/flavours for 25.04 release

---

meganav.yaml
releases.yaml
static/js/src/chart-data.js
templates/about/release_cycles/releases-table.html
templates/desktop/flavours.html
templates/desktop/wsl/index.html
templates/download/desktop/index.html
templates/download/raspberry-pi/index.html
templates/download/risc-v/allwinner-nezha.html
templates/download/risc-v/index.html
templates/download/risc-v/microchip-curiosity.html
templates/download/risc-v/microchip-polarfire.html
templates/download/risc-v/milk-v-mars.html
templates/download/risc-v/pine64-star64.html
templates/download/risc-v/qemu-emulator.html
templates/download/risc-v/sifive-unmatched.html
templates/download/risc-v/sipeed-licheerv.html
templates/download/server/arm.html
templates/download/server/manual.html
templates/download/server/power.html
templates/download/server/s390x.html
templates/shared/_kernel-release-diagram.html

- Made 25.04 release updates throughout website, see jira ticket for full page list
- View the site locally in your web browser at: https://ubuntu-com-14940.demos.haus/
Fixes https://warthogs.atlassian.net/browse/WD-20893

25.04 release changes

---

templates/managed/firefighting-support.html

Copy update firefighting-support
- View the site locally in your web browser at: https://ubuntu-com-15015.demos.haus/managed/firefighting-support
- Make sure that the [copy docs](https://docs.google.com/document/d/1sWNMmLoyOFUI9qZE3fqPhgZWJSpb-e6-juGrW7A5rr0/edit?tab=t.0) changes are applied
Fixes # [WD-21486](https://warthogs.atlassian.net/browse/WD-21486)
[WD-21486]: https://warthogs.atlassian.net/browse/WD-21486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

copy update firefighting-support

---

templates/templates/_tag_manager.html

- removed unused legacy tag manager code

remove unused initialization script from tag manager

---

templates/core/index.html
templates/core/services/index.html
templates/embedded/index.html
templates/internet-of-things/appstore.html
templates/internet-of-things/index.html
templates/internet-of-things/smart-displays.html
templates/robotics/index.html
templates/robotics/what-is-ros.html
templates/shared/_20-04-eol-banner.html

- Create a shared banner
- Add it to all the static pages listed in the [Jira ticket](https://warthogs.atlassian.net/browse/WD-20477)
- Open the demo and check all the pages listed have the banner where you would expect it.
- Check the link works
Fixes https://warthogs.atlassian.net/browse/WD-20477

WD-20477 - 20.04 EOL banner across static pages

---

templates/confidential-computing/index.html

- Update google colud logo in confidential computing
https://warthogs.atlassian.net/browse/WD-21719?linkSource=email

Update google clud logo in confidential computing WD-21719

---

templates/download/mediatek-genio/tab-1.html
templates/download/mediatek-genio/tab-2.html
templates/download/mediatek-genio/tab-3.html
templates/download/mediatek-genio/tab-4.html

Updated download links for all the tabs.
[Doc](https://docs.google.com/document/d/1Tm3cVVkWkzriQQ7kgbgKfKoeGZaew1M5OMbpLPSDGIc/edit?tab=t.0)
Fixes [#WD-21545](https://warthogs.atlassian.net/browse/WD-21545)

copy: update ubuntu.com/download/mediatek-genio download links. WD-21545

---

.github/workflows/sitemap.yaml

- Remove redundant environment variables and failure message
Fixes #

fix: Sitemap github action

---

templates/containers/container-build-service.html

- Made copy update to last CTA `your custom your container build` -> `your container build`
- View the demo in your web browser at: https://ubuntu-com-15062.demos.haus/containers/container-build-service
- Check that the changes match the [copydoc](https://docs.google.com/document/d/14qW4-vU2Eipd1jwwI55OKIwxzrnpaAC0uo0p7dlFxiQ/edit?tab=t.0#heading=h.eto59uxtlv76)
Fixes [WD-21717](https://warthogs.atlassian.net/browse/WD-21717)
[WD-21717]: https://warthogs.atlassian.net/browse/WD-21717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: cta copy update on /containers/container-build-service

---

templates/download/renesas-iot/tab-1-renesas-rz-g2l.html

-  Copy update changes to Renesas-iot page
- [Demo](https://ubuntu-com-15072.demos.haus/download/renesas-iot)
- [Copydoc](https://docs.google.com/document/d/1-S_loqM0YLcaMR4WG7Tal0765cBoIa_0ssOI3NAtw4E/edit?tab=t.0)
Fixes # [21874](https://warthogs.atlassian.net/browse/WD-21874)

WD-21874 Copy update changes to Renesas-iot page

---

package.json
static/sass/_pattern_blog-card.scss
static/sass/_pattern_lists.scss
static/sass/_pattern_modals.scss
static/sass/_pattern_navigation-dropdown.scss
static/sass/_settings_colors.scss
yarn.lock

- refactor: Run sass-migrator
- Check the project builds and runs

refactor: Run sass-migrator

---

static/js/src/certified-search-results.js

- Use `e.target` to extract checkbox data
- Go to https://ubuntu-com-15095.demos.haus/certified/servers?q=dell&vendor=Asus&vendor=Cisco+Systems
- Click 'Show all vendors', see that the checkboxes are not reset
Fixes https://warthogs.atlassian.net/browse/WD-22063

fix: Urls params are not stored on checkbox click

---

templates/desktop/developers.html

- Copy Update: /desktop/developers
- View the site at https://ubuntu-com-15119.demos.haus/desktop/developers
- Compare against copy doc: https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit?tab=t.0
Fixes [WD-22182](https://warthogs.atlassian.net/browse/WD-22182)
https://ubuntu.com/desktop/developers
https://ubuntu-com-15119.demos.haus/desktop/developers
[WD-22182]: https://warthogs.atlassian.net/browse/WD-22182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-22182 Copy Update - Ubuntu Desktop for Developers Link

---

templates/shared/contextual_footers/_ua_further_reading.html

- Display latest articles in pro dashboard page
- Go to at: https://ubuntu-com-15121.demos.haus/pro/dashboard
- Scroll down to the **Further reading** section
Fixes [WD-21655](https://warthogs.atlassian.net/browse/WD-21655)
**Before:**
**After:**
[WD-21655]: https://warthogs.atlassian.net/browse/WD-21655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-21655] Refresh /pro/dashboard

---

static/sass/styles.scss
templates/training/index.html

Updated the training page in line with the [design](https://www.figma.com/design/u295OIYk2TyZUlaghczwo5/ubuntu.com-training?node-id=36-5465&m=dev).
- Go to https://ubuntu-com-15128.demos.haus/training
- Ensure the updated page is in line with the design on mobile, tablet and desktop screen sizes.

[WD-21625] Refresh /training

---

templates/security/index.html

- Security index page copy update
- View the site in your web browser at: https://ubuntu-com-15177.demos.haus/security
- Ensure updates match [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI)
Fixes WD-22632

[WD-22632] Security index page copy update

---

templates/security/fedramp.html

- Updated text according to ticket.
[[WD-22495]](https://warthogs.atlassian.net/browse/WD-22495)
[WD-22495]: https://warthogs.atlassian.net/browse/WD-22495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

text changes

---

templates/robotics/what-is-ros.html
templates/shared/contextual_footers/_robotics_further_reading.html

- Rebranded robotics/what-is-ros page
- View the site in your web browser at: https://ubuntu-com-15167.demos.haus/robotics/what-is-ros
- Verify the page matches [copydoc](https://docs.google.com/document/d/1yX2Ikcn1fgIKX3el8fKWQt7SGxSwY633TfW5V1lwUuc/edit?tab=t.0) and [figma](https://www.figma.com/design/xxxrpexajIgaq6cyY0UfSu/ubuntu.com%2Frobotics?node-id=0-1&t=efeOoCM8ugd9GeJs-1)
Fixes #[WD-17773](https://warthogs.atlassian.net/browse/WD-17773)
Before:
After:
[WD-17773]: https://warthogs.atlassian.net/browse/WD-17773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …

[WD-17773] feat: Rebrand robotics/what-is-ros

---

templates/desktop/flavors.html

- Update based on [copydoc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit?tab=t.0)
- Check out [the demo](https://ubuntu-com-15190.demos.haus/desktop/flavours) and make sure it matches the changes in the [copydoc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-22693?linkSource=email

feat: Update logos on /desktop/flavours

---

templates/macros/_vf_rich-horizontal-list.jinja
templates/security/security-standards.html

- Apply [copy doc ](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit?tab=t.0)suggested changes
- View the site in your web browser at: https://ubuntu-com-15194.demos.haus/security/security-standards
- Make sure the suggested changes from the [copy doc ](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit?tab=t.0)are applied
Fixes [WD-22638](https://warthogs.atlassian.net/browse/WD-22638)
[WD-22638]: https://warthogs.atlassian.net/browse/WD-22638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BAU security standards

---

templates/summit/call-for-collaboration.html

- Copy update on /summit/call-for-collaboration
- Go to https://ubuntu-com-15220.demos.haus/summit/call-for-collaboration
- Compare page against [copy doc](https://docs.google.com/document/d/1pjIpFWL7yu6Jc2gZGqCRvckd4clPVrLtGpRwTaw9-CY/edit?tab=t.0)
Fixes #https://warthogs.atlassian.net/browse/WD-22825

Copy update on /summit/call-for-collaboration

---

templates/security/cmmc/index.html

- Changed the order of the case studies. More details [in this comment](https://docs.google.com/document/d/1IbVBPtZZ0zLtT1C5j70cUrSx2bvP1KWtvSJObQKqFb8/edit?tab=t.0#heading=h.q1jqggn706nf).
[Doc](https://docs.google.com/document/d/1IbVBPtZZ0zLtT1C5j70cUrSx2bvP1KWtvSJObQKqFb8/edit?tab=t.0)`
Fixes [#WD-22655](https://warthogs.atlassian.net/browse/WD-22655) …

copy: update https://ubuntu.com/security/cmmc. WD-22655

---

templates/toolchains/java.html

- created a /toolchains/java page
- goto https://ubuntu-com-15232.demos.haus/toolchains/java
- compare with copydoc: https://docs.google.com/document/d/1ShgZyjn6pBG-L5iVd-MEIwc1JRVhaSeUFoImo5iWO-k/edit?tab=t.0
- compare with figma: https://www.figma.com/design/fuZyFcBGmhqBzslI7lAZWc/canonincal.com-toolchains?node-id=8-3314&t=PUb2Xw3WsUVdz66M-1

WD-22392/toolchains-java

---

templates/toolchains/index.html

- Adds /toolchains page
- Go to https://ubuntu-com-15215.demos.haus/toolchains
- Check that the page matches [the design](https://www.figma.com/design/fuZyFcBGmhqBzslI7lAZWc/canonical.com-toolchains?node-id=8-3314&p=f)
- Check that the page matches [the copy doc](https://docs.google.com/document/d/18RIA7sr9oR11g3t2i8sJ3DphOUx7kuh2KsdPFAHta6U/edit?tab=t.0)
- **PLEASE NOTE**: Only `/templates/toolchains/index.html` needs review. The other changes are rebased from #15211 
Fixes https://warthogs.atlassian.net/browse/WD-22388

chore: Add toolchains page

---

static/sass/_pattern_blog-card.scss
templates/blog/article.html
templates/blog/blog-card.html

- Rebranded blog/article page
- View the site in your web browser at: https://ubuntu-com-15246.demos.haus/blog/effective-infrastructure-automation-to-reduce-data-center-costs
- Verify the page matches [figma](https://www.figma.com/design/CB22O7EPgyiUQheHVpOHQ9/ubuntu.com-blog?node-id=254-49429)
- Go to https://ubuntu-com-15246.demos.haus/blog
- Scroll down and select random blog articles (that exist on ubuntu.com) and verify they also match the design.
Fixes #[WD-21617](https://warthogs.atlassian.net/browse/WD-21617)
[WD-21617]: https://warthogs.atlassian.net/browse/WD-21617?atlOrigin=eyJpIjoiN …

[WD-21717] feat: Rebranded blog/article page

---

templates/robotics/community.html

- Rebranded robotics/community page
- View the site in your web browser at: https://ubuntu-com-15172.demos.haus/robotics/community
- Verify the page matches [copydoc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit?tab=t.0) and [figma](https://www.figma.com/design/xxxrpexajIgaq6cyY0UfSu/ubuntu.com-robotics?node-id=108-3584&p=f&t=EPCFzg9qEqbwRCfu-0)
Fixes #[WD-17778](https://warthogs.atlassian.net/browse/WD-17778)
[WD-17778]: https://warthogs.atlassian.net/browse/WD-17778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

[WD-17778] feat: Rebrand robotics/community page

---

templates/security/livepatch.html

- Update datasheet link based on [copydoc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit?tab=t.0#heading=h.ei5ieuk7ybyq)
- Open [demo](https://ubuntu-com-15275.demos.haus/security/livepatch)
- Check that the changes match the [copydoc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit?tab=t.0#heading=h.ei5ieuk7ybyq)
Fixes https://warthogs.atlassian.net/browse/WD-22197

copy(/security/livepatch): Update datasheet link

---

konf/site.yaml

- Added Maas discourse API keys
- Check that the demo runs without error

feat: add maas charmhub keys

---

templates/16-04/index.html

- Applied redesign as per [doc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit?tab=t.0) and [design](https://www.figma.com/design/CQEhQbDyCwqUyLDSsds8fL/ubuntu.com-16-04?node-id=0-1&p=f&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-15280.demos.haus/16-04
Fixes https://warthogs.atlassian.net/browse/WD-18470

feat: /16-04 rebrand

---

templates/blog/article.html
templates/blog/newsletter-form.html
templates/shared/_default-contact-us-form.html

This commit introduces several HTML5 enhancements:
- **Contact Form (`_default-contact-us-form.html`):**
- Added `autocomplete` attributes (given-name, family-name, organization, organization-title, email, tel) to respective input fields for improved browser autofill.
- Added `inputmode="tel"` to the phone number field to aid mobile usability.
- **Blog Newsletter Form (`newsletter-form.html`):**
- Added `autocomplete="email"` to the email input field.
- **Blog Article Page (`article.html`):**
- Changed the author bio section wrapper from `div` to `aside` for better semantic representation of tangential content.
- Changed the newsletter signup section wrapper from `div` to `aside` for better semantic representation.
- Standardized and improved `aria-label` attributes on social media …

Add HTML5 features and improve semantics/ARIA

---

templates/download/amd/tab-1.html
templates/download/amd/tab-2.html

- Made updates according to [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0#heading=h.9lw1gwsuva2l)
- Open the demo, at https://ubuntu-com-15305.demos.haus/download/amd
- Check the [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0#heading=h.9lw1gwsuva2l) and confirm the updates
Fixes [WD-23324](https://warthogs.atlassian.net/browse/WD-23324)
[WD-23324]: https://warthogs.atlassian.net/browse/WD-23324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …

feat: copy update on /amd/download

---

static/sass/styles.scss
templates/community/_base_community.html
templates/community/docs/document.html
templates/community/index.html
templates/macros/_vf-latest-news.jinja
templates/templates/docs/shared/_docs.html
webapp/app.py
webapp/views.py

- Build community landing page, based on the [copydoc](https://docs.google.com/document/d/170WJDDZmmoMAuSlfQon5EvZl_qpUQEVw_r3cQNAP3Bs/edit?tab=t.0) and [figma](https://www.figma.com/design/NtIK22CtDUTO8iQWoaUWlq/ubuntu.com-community?node-id=149-5021&m=dev) 
- Setup up connection with Discourse
- Add setting for 3 items in latest-news patern
- Create u-clamp class for limiting text to two lines
- Open the [demo](https://ubuntu-com-15273.demos.haus/community)
- Compare against the [copydoc](https://docs.google.com/document/d/170WJDDZmmoMAuSlfQon5EvZl_qpUQEVw_r3cQNAP3Bs/edit?tab=t.0) and [figma](https://www.figma.com/design/NtIK22CtDUTO8iQWoaUWlq/ubuntu.com-community?node-id=149-5021&m=dev) 
Fixes https://warthogs.atlassian.net/browse/WD-17323

Build community portal landing page

---

templates/16-04/azure.html
templates/16-04/form-data.json

- Applied redesign as per [doc](https://docs.google.com/document/d/1V99KwimN8Hla8L_CikNc6I0amqj99cSrBsVlAjIkBqE/edit?tab=t.0#) and [design](https://www.figma.com/design/CQEhQbDyCwqUyLDSsds8fL/ubuntu.com-16-04?node-id=2-3147&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-15282.demos.haus/16-04/azure
Fixes https://warthogs.atlassian.net/browse/WD-18472

feat: /16-04/azure

---

templates/download/amd/tab-1.html
templates/download/amd/tab-2.html

- Updated copy according to [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0)
- Open the [demo](https://ubuntu-com-15309.demos.haus/)
- Check that the [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0) changes have been addressed.
Fixes [WD-23324](https://warthogs.atlassian.net/browse/WD-23324)
[WD-23324]: https://warthogs.atlassian.net/browse/WD-23324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-23324: copy update

---

templates/azure/base_azure.html
templates/azure/confidential-computing.html
templates/shared/forms/interactive/azure.html

Updates copy on /azure/confidential-computing and fixes issue where forms opened on wrong page
- Go to https://ubuntu-com-15297.demos.haus/azure/confidential-computing
- Check that the page reflects the [changes requested in the copy doc](https://docs.google.com/document/d/1sVaQQlm6LHyRf-Q3VSVTmqGRi0SV7gwBVczCTPWq3CE/edit?tab=t.0)
- Click "Don’t see what you’re looking for? Contact us to learn more" and check that the form opens in a modal on the same page
- Click Contact us to discuss your use case" and check that the form opens in a modal on the same page
Fixes https://warthogs.atlassian.net/browse/WD-23267

chore: Update azure confidential computing page

---

templates/confidential-computing/ai.html
templates/confidential-computing/index.html

- Apply copy updates to the confidential computing pages
- Go to /confidential-computing and check the copy change requests are match the [copy doc](https://docs.google.com/document/d/1QGwS5CYlwXkaPibSFvcag6zLcUH5lNDUbM18hCqbOJM/edit?tab=t.0).
- Go to /confidential-computing/ai and check the copy change requests are match the [copy doc](https://docs.google.com/document/d/1TZ_jK3ReetAU2qA_YxfZL8i4j_lFidcF6F2Xup8R8Nc/edit?tab=t.0).
Fixes https://warthogs.atlassian.net/browse/WD-23271

WD-23271 Apply copy updates to the confidential computing pages

---

templates/legal/ubuntu-pro-description/ros-esm-service-description.md

- Copy updates based on https://docs.google.com/document/d/12OGV0hnxPvwY2pT8gbS2vHQp3icndJeaEyqc1G_oIoM/edit?tab=t.0#
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-pro-description/ros-esm-service-description
- Check against [copy doc](https://docs.google.com/document/d/12OGV0hnxPvwY2pT8gbS2vHQp3icndJeaEyqc1G_oIoM/edit?tab=t.0#)
[WD-23563](https://warthogs.atlassian.net/browse/WD-23563)
[WD-23563]: https://warthogs.atlassian.net/browse/WD-23563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy update for ros esm service description

---

meganav.yaml

- Add canonical.com/solutions/automation to meganav
- Check out [the demo](https://ubuntu-com-15363.demos.haus/) and open the meganav.
- Navigate to the solutions category and ensure "Automation" is part of the list
- Linked to [this comment](https://warthogs.atlassian.net/browse/WD-23188?focusedCommentId=824601) as part of the BAU task.
- Main PR on canonical.com: canonical/canonical.com#1801
- DO NOT MERGE UNTIL THIS PR IS CLOSED.

[BAU] WD-23241 - Feat: add canonical.com/solutions/automation to meganav

---

templates/summit/call-for-collaboration.html

Updated deadline and punctuation in line with copy doc.
- Compare with [copy doc](https://docs.google.com/document/d/1pjIpFWL7yu6Jc2gZGqCRvckd4clPVrLtGpRwTaw9-CY/edit?tab=t.0).
https://warthogs.atlassian.net/browse/WD-23943

Copy update: /summit/call-for-collaboration

---

templates/download/alternative-downloads.html
templates/download/shared/_footer.html

- Copy update [JIRA](https://warthogs.atlassian.net/browse/WD-23887)
- copy doc: https://docs.google.com/document/d/1VhmFVE3dK81mE3zcC9FVA6f5SGJ-DHan7WWlrlfRcvo/edit?tab=t.0
- Review the page: https://ubuntu-com-15362.demos.haus/download/alternative-downloads
- Compare with updates in the copydoc
Fixes WD-23887

 WD-23887 Copy updates for alternate-downloads page

---

static/js/src/openstack-deployment-chart.js
templates/macros/_vf-latest-news.jinja
templates/openstack/consulting.html
templates/shared/contextual_footers/_cloud_newsletter.html
templates/shared/contextual_footers/_openstack_managed.html
templates/shared/pricing/_openstack-packages.html

- Rebranding Openstack Consulting page
- Updated UI designs
- Updated images
- Better UX
- [copy docs](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit?usp=sharing)
- [figma](https://www.figma.com/design/vH19y2J2YqwUfksebSUvTW/ubuntu.com-openstack?node-id=817-5374&p=f&m=dev)
- Check out the [demo](https://ubuntu-com-15356.demos.haus/openstack/consulting)
- Check that page matches figma
- Check page across
- Mobile
- Tablet
- Desktop
Fixes # https://warthogs.atlassian.net/browse/WD-22922

[Rebrand] Openstack Consulting Page

---

navigation.yaml
requirements.txt
static/sass/styles.scss
templates/community/events.html
templates/community/index.html
templates/community/uwn.html
webapp/app.py
webapp/views.py

- Build /community/uwn
- Open [the demo](https://ubuntu-com-15361.demos.haus/community/uwn)
Fixes https://warthogs.atlassian.net/browse/WD-17328

feat: Build /community/uwn

---

.github/workflows/deploy.yaml

- Fix pack charm
- Verify the pack and deploy action is successful.

fix: Pack charm from charm directory

---

templates/shared/_20-04-eol-banner.html

Change banner text on 20.04 EOL.
- Check out this page on the [demo here](https://ubuntu-com-15403.demos.haus/internet-of-things).
- Make sure the notification banner change matches the text proposed in the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit?tab=t.0).
- [WD-24156](https://warthogs.atlassian.net/browse/WD-24156)
[WD-24156]: https://warthogs.atlassian.net/browse/WD-24156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[copy update] WD-24156 - Change banner text on 20.04 EOL

---

templates/appliance/hardware.html
templates/ceph/what-is-ceph.html
templates/containers/shared/_container-portfolio-tabs.html
templates/credentials/faq.html
templates/desktop/developers.html
templates/desktop/index.html
templates/embedded/index.html
templates/internet-of-things/gateways.html
templates/internet-of-things/management.html
templates/internet-of-things/smart-city/index.html
templates/internet-of-things/smart-home/index.html
templates/landscape/features.html
templates/landscape/index.html
templates/landscape/managed/index.html
templates/pro/why-pro.html
templates/security/livepatch.html
templates/support/index.html
templates/toolchains/java.html
templates/toolchains/spring.html

- Consolidate image loading attributes to either "auto" or "lazy" for consistency across templates
- Check out the demo
- View the demo link
Fixes #https://warthogs.atlassian.net/browse/WD-24334

Fix image loading attribute values

---

templates/security/standards/pci-dss.html

- Added new whitepaper to [/security/pci-dss](https://ubuntu-com-15430.demos.haus/security/pci-dss) page
- Go to [/security/pci-dss](https://ubuntu-com-15430.demos.haus/security/pci-dss)
- Look for the "Whitepapers" tab (towards the bottom of the page, under "Resources")
- Check that there is a new whitepaper, as requested in the [copy doc](https://docs.google.com/document/d/1537vHkYSGRGpN4m39xduTx1ClHLJI9yVdhgtHFMxqTQ/edit?tab=t.0#heading=h.f3squhh5cshr) - [Jira issue](https://warthogs.atlassian.net/browse/WD-24518)
Fixes …

fix(pci-dss): add new whitepaper to /security/pci-dss [WD-24518]

---

templates/openstack/consulting.html

- Update download link as per [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit?tab=t.0#)

copyupdate: update openstack datasheet link

---

package.json

- Remove unused `test-links` script
Fixes [WD-21822](https://warthogs.atlassian.net/browse/WD-21822)
[WD-21822]: https://warthogs.atlassian.net/browse/WD-21822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove unused test-links script

---

templates/download/qualcomm-iot/tabs/evaluation-kit-tab.html
templates/download/qualcomm-iot/tabs/rb3-gen2-lite-tab.html
templates/download/qualcomm-iot/tabs/rb3-gen2-tab.html

- Updated links on /download/qualcomm-iot page as per copy update
- Go to https://ubuntu-com-15497.demos.haus/download/qualcomm-iot
- Compare with [copy doc](https://docs.google.com/document/d/1BP2T63R6kdnUFQFIZcbXbTIgY-9fQVgVRLsSUU5Rvx8/edit?tab=t.0)
[WD-25587](https://warthogs.atlassian.net/browse/WD-25587)
[WD-25587]: https://warthogs.atlassian.net/browse/WD-25587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy update for links on /download/qualcomm-iot

---

templates/ceph/consulting.html

- Implemented the changes requested in [copy doc](https://docs.google.com/document/d/1LK8mut0O30Zk60mmbgCPFiQ2COR-BUnJnbASMMdyycU/edit?tab=t.0#heading=h.9hj53q7l3qpr)
- Visit https://ubuntu-com-15498.demos.haus/ceph/consulting
- Compare with https://ubuntu.com/ceph/consulting
- Confirm the copy doc changes
Fixes #[WD-25669](https://warthogs.atlassian.net/browse/WD-25669)
Before:
After:
[WD-25669]: https://warthogs.atlassian.net/browse/WD-25669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-25669: Copy Update /ceph/consulting

---

templates/security/cmmc/index.html

- update page as per [copy-doc](https://docs.google.com/document/d/1IbVBPtZZ0zLtT1C5j70cUrSx2bvP1KWtvSJObQKqFb8/edit?tab=t.0)
- match with copy-doc
Fixes WD-25631

copy-update: cmmc 2.0

---

templates/security/cmmc/index.html

- update link per [copy-doc](https://docs.google.com/document/d/1IbVBPtZZ0zLtT1C5j70cUrSx2bvP1KWtvSJObQKqFb8/edit?tab=t.0)
Fixes #

update free trial link

---

templates/summit/call-for-collaboration.html

- Updated as per [ticket](https://warthogs.atlassian.net/browse/WD-26065)
- Drive by: Updated copydoc link
- View the locally in your web browser at: https://ubuntu-com-15528.demos.haus/summit/call-for-collaboration
- Verify all the changes in this [ticket](https://warthogs.atlassian.net/browse/WD-26065) are applied.
Fixes #[WD-26065](https://warthogs.atlassian.net/browse/WD-26065)
[WD-26065]: https://warthogs.atlassian.net/browse/WD-26065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-26065] feat: update summit/call-for-collaboration

---

templates/toolchains/index.html

- Fixed a link for .NET according to [this comment](https://docs.google.com/document/d/1JhVoqA6RyDu3pBzIarrqdY0RgweBLDdHAfeqgAmBDNk/edit?disco=AAABpsZYlZc) from the copy doc
- Changed the link to a copy doc, since the previous one was located in the wrong place on Google Drive, and had an incorrect name as well
- Refactored the whole codebase to utilize Vanilla patterns as much as possible
- Open the page at https://ubuntu-com-15531.demos.haus/toolchains
- Check that the comments from the [copy doc ](https://docs.google.com/document/d/1JhVoqA6RyDu3pBzIarrqdY0RgweBLDdHAfeqgAmBDNk/edit?tab=t.0)are applied
- Check that the sections look correct
Fixes https://warthogs.atlassian.net/browse/WD-25995 …

[WD-25995] fix links and refactor the page to use patterns

---

templates/ai/data-science.html
templates/ai/index.html
templates/aws/outposts.html
templates/aws/pro.html
templates/aws/thank-you.html
templates/azure/ebook/index.html
templates/azure/fips.html
templates/azure/private-offer.html
templates/azure/thank-you.html
templates/blog/product-cards/_ai-solutions.html
templates/blog/product-cards/_desktop_ubuntu-desktop-for-organisations.html
templates/blog/product-cards/_desktop_ubuntu-for-desktops.html
templates/blog/product-cards/_financialservices-awerness.html
templates/blog/product-cards/_raspberry-pi_2010-livestream.html
templates/blog/product-cards/_server_scale-out-with-ubuntu-server.html
templates/blog/product-cards/_wsl_ubuntu-on-windows.html
templates/ceph/thank-you.html
templates/cloud/cloud-computing.html
templates/cloud/hybrid-cloud.html

- Replace static image tags with image template function for better image loading and optimisation.
- Check out the demo link
- https://ubuntu-com-15532.demos.haus/ai/data-science
- https://ubuntu-com-15532.demos.haus/ai
- https://ubuntu-com-15532.demos.haus/aws/outposts
- https://ubuntu-com-15532.demos.haus/aws/pro
- https://ubuntu-com-15532.demos.haus/aws/thank-you
- https://ubuntu-com-15532.demos.haus/azure/ebook
- https://ubuntu-com-15532.demos.haus/azure/fips
- https://ubuntu-com-15532.demos.haus/azure/private-offer
- https://ubuntu-com-15532.demos.haus/azure/thank-you
- https://ubuntu-com-15532.demos.haus/ceph/thank-you
- https://ubuntu-com-15532.demos.haus/cloud/cloud-computing
For blog cards
- https://ubuntu-com-15532.demos.haus/blog/ubuntu-20-04-end-standard-support-for-devices
- …

refactor: improve image loading across multiple pages

---

templates/base_index.html

- Adds link 'Access a 30-day free trial'
- Compare against the [copydoc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?tab=t.0)
Fixes https://warthogs.atlassian.net/browse/WD-26283?actionerId=557058%3Af58131cb-b67d-43c7-b30d-6b58d40bd077&sourceType=assign

feat: Add link to Pro free trial on homepage

---

templates/download/renesas-iot/tab-1-renesas-rz-g2l.html
templates/download/renesas-iot/tab-2-renesas-rz-g2lc.html
templates/download/renesas-iot/tab-3-renesas-rz-g2ul.html

- [Copy doc](https://docs.google.com/document/d/1-S_loqM0YLcaMR4WG7Tal0765cBoIa_0ssOI3NAtw4E/edit?tab=t.0)
- Go to /download/renesas-iot
- Verify the changes in the 3 tabs against the copy doc 
Fixes #https://warthogs.atlassian.net/browse/WD-26046

feat: add new sections to Renesas tabs

---

konf/site.yaml

- Added marketo secret so that demos can submit forms
- Open the demo and fill in some forms, see that they submit as expected. 
Fixes  [WD-26514](https://warthogs.atlassian.net/browse/WD-26514)
[WD-26514]: https://warthogs.atlassian.net/browse/WD-26514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add MARKETO secret to demos

---

templates/toolchains/java.html

- Update logo and remove dataset in /toolchains/java
- [Visit /toolchains/java](https://ubuntu-com-15577.demos.haus/toolchains/java)
- [Copy doc](https://docs.google.com/document/d/1ShgZyjn6pBG-L5iVd-MEIwc1JRVhaSeUFoImo5iWO-k/edit?tab=t.0)
Fixes [#WD-26365](https://warthogs.atlassian.net/browse/WD-26365)

update logo and remove the dataset

---

templates/openstack/install.html

- Revamped the current OpenStack install page
- Used new copydoc document
- View the site locally in your web browser at: http://localhost:8001/openstack/install
Fixes https://warthogs.atlassian.net/browse/WD-24782

revamp: https://ubuntu.com/openstack/install (WD-24782)

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx

- Updated `onPayClick` 
- Go to `/pro/distributor`
- Initiate an offer and try to purchase
- Check that everything working fine
- Check that this fix won't break other shops 
Fixes #https://warthogs.atlassian.net/browse/WD-26679

Prevent duplicate submissions 

---

templates/desktop/index.html

- Copy update on the desktop page
- Visit [/desktop](https://ubuntu-com-15617.demos.haus/desktop)
- Copy doc https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit?tab=t.0
Fixes [#WD-26527](https://warthogs.atlassian.net/browse/WD-26527)

copy updates on /desktop

---

templates/download/server/thank-you.html
templates/download/shared/_server_weekly_news.html

- change CLI cheat sheet pdf to a new version
- Or go to the [demo](https://ubuntu-com-15682.demos.haus/download/server/thank-you?version=24.04.3&architecture=amd64&lts=true)
[Google doc](https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit?tab=t.0)
[Jira ticket](https://warthogs.atlassian.net/browse/WD-27718)
Before:
After:

copy: update /download/server/thank-you CLI cheat sheet

---

templates/download/server/s390x.html

- Updated the form options.
- [Demo](https://ubuntu-com-15683.demos.haus/download/server/s390x)
- [Copydoc](https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit?tab=t.0)
Fixes # https://warthogs.atlassian.net/browse/WD-27639

Copyupdate: (WD-27639) updated the form options

---

templates/openstack/index.html

- Remove broken link as per [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?disco=AAABsSGAlPA)
- Go to ubuntu-com-15692.demos.haus/openstack
- Search for "one of the top contributors"
- See that the link is removed
Fixes [WD-27908](https://warthogs.atlassian.net/browse/WD-27908)
[WD-27908]: https://warthogs.atlassian.net/browse/WD-27908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove broken link

---

templates/summit/index.html

Update featured speaker listings.
Fixes #

Update featured speaker list

---

templates/blog/article.html
templates/blog/author.html

- Add checks for blog authors to fix `UndefinedError`
- Run this branch locally (demos are currently down)
- Make sure you have VPN on to access blogs
- Go to `/blog/openstack-weekly-update-august-31-2017`
- See that the blog loads without error
Fixes [WD-28080](https://warthogs.atlassian.net/browse/WD-28080) and [Sentry error](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/99759/?query=is%3Aunresolved)
[WD-28080]: https://warthogs.atlassian.net/browse/WD-28080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add checks for blog author
