requirements.txt
static/js/src/core.js
static/sass/_pattern_navigation-dropdown.scss
static/sass/_pattern_navigation.scss

These are the issues that have been fixed:
Two other visual bugs:
The padding of the menu button needs to be adjusted in bubbles on mobile, should match that of "Canonical Ubuntu" next to it. (Please check that whatever you do here doesn't affect the button on the home, which has different padding)
There's an alignment issue between navigation and the third column in rebranded pages. This looks OK in the [/data bubble](https://canonical.com/data) and [microk8s.io](https://microk8s.io/). In the example below, "Products" and "Your subscriptions" should align with "Ubuntu Pro" in the hero; see how it does in the Data bubble below that.
Little visual bug on mobile
I noticed a visual bug persists on mobile: see the darker rectangle.
- Check out this feature branch and see that the above issues …

Fix alignment on bubble and remove black box on mobile

---

.github/workflows/playwright.yml
.github/workflows/pr.yaml
Dockerfile

- Switched dotrun to pip version rather than snap for CI
- Updated the checkout GHA

Use dotrun pip instead of snap

---

templates/kubernetes/docs/1.16/charm-docker-registry.md
templates/kubernetes/docs/1.17/charm-docker-registry.md
templates/kubernetes/docs/1.18/charm-docker-registry.md
templates/kubernetes/docs/1.19/charm-docker-registry.md
templates/kubernetes/docs/1.19/upgrading.md
templates/kubernetes/docs/1.20/charm-docker-registry.md
templates/kubernetes/docs/1.20/upgrading.md
templates/kubernetes/docs/1.21/charm-docker-registry.md
templates/kubernetes/docs/1.22/charm-docker-registry.md

- broken links relating to Docker (in deprecated charm docs)
- broken links relating to Juju upgrades

Fixes more 404s

---

releases.yaml

- The UC22 raspi image checksums were out-of-date, so updated those.
Fixes #13336

Update checksums for UC22 raspi images.

---

static/sass/_pattern_navigation.scss
templates/templates/meganav/base.html

- Fixes the align of headings for secondary links in mobile view. ex. products > ubuntu OS > scroll down
- Add in the 'by industry' that was missing under 'use cases' on mobile
Fixes #

Fix p-muted-heading alignment

---

.github/workflows/pr.yaml

Fix lint-python flake8 version
- Check that `lint-python` passes

Use dotrun for flake8 version consistency

---

templates/nvidia/index.html

Add 2 sources to /nvidia page
- [demo link](https://ubuntu-com-13501.demos.haus/nvidia)
- [copy doc](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit)
- Check that the links and text are correct
[WD-8502](https://warthogs.atlassian.net/browse/WD-8502)
Fixes #
[WD-8429]: https://warthogs.atlassian.net/browse/WD-8429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-8502]: https://warthogs.atlassian.net/browse/WD-8502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

WD-8502 - add sources to nvidia page

---

templates/aws/pro.html

Update feature coverage table on /was/pro
- [demo link](https://ubuntu-com-13500.demos.haus/aws/pro)
- [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit)
- Check that the table is correct according to the copy doc
[WD-8429](https://warthogs.atlassian.net/browse/WD-8429)
Fixes #
[WD-8429]: https://warthogs.atlassian.net/browse/WD-8429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8429 - update aws pro coverage table

---

static/js/src/chart-data.js
static/js/src/release-chart.js
static/js/src/support-chart.js
static/sass/_pattern_chart.scss
templates/about/release_cycles/ubuntu-eol.html
templates/about/release_cycles/ubuntu-small-eol.html
templates/desktop/developers.html
templates/shared/_release_schedule.html

- Creates a new function `createSupportChart` that creates a graph based on the design [found in this figma file](https://www.figma.com/file/wLOtPeQhAiExhQCwKYhi3H/24.04-U.com---desktop-(rebranding)?type=design&node-id=871-2991&mode=design&t=6JDKoP4OfQHU60Eo-0). A screenshot comparison can be found below.
- Updates where this graph was used previously to work with the new graph (this means adding a place for the key to attach)
- Go to /desktop/developers and see that the graph matches the design
- Check that it works on medium and large screens and becomes a table on small screens
- Check the other pages where it is used and see that it doesn't break or anything (ie. /about/releases)
Fixes https://warthogs.atlassian.net/browse/WD-8270
Desgin:
D3 reproduction:

Update ubuntu lts security support graph with new design

---

static/js/src/navigation.js
static/sass/_pattern_navigation.scss
templates/templates/meganav/base.html

- There was a bug where secondary links in mobile view and all links in global nav weren't working weren't working due to changes in class name. This PR addresses those.
- Open the demo on a mobile screen
- Go to 'Products' > 'Ubuntu OS' and check that the secondary links at the bottom work:
- Go to 'All Canonical' > 'About' and check that any of the links there work:
- Check the same links work on desktop view.
Fixes https://warthogs.atlassian.net/browse/WD-8530

Fix secondary links bug

---

.github/workflows/live-links.yaml

Added an ignore rule to the link links checker to ignore the Lenovo permanent redirect to the same page.
Check that this will resolve the remaining error in the latest live links action.

Ignore 301 redirection loop from linkchecker

---

static/js/src/support-chart.js
templates/desktop/developers.html

- Fixes an incorrect class name that caused a misalignment
BEFORE:
AFTER:
Fixes #

Fix logo misalignment

---

templates/templates/base.html

- Reinstated script accidentally deleted in https://github.com/canonical/ubuntu.com/pull/13466/
- View the site locally in your web browser at: https://ubuntu-com-13510.demos.haus/
- Inspect the page and see that you no longer get `ReferenceError: getPrimaryParentLanguage is not defined` as compared to prod and that takeovers load as expected 
Fixes https://warthogs.atlassian.net/browse/WD-8551

Reinstate infer language script

---

templates/about/release-cycle.html

Update text on /release-cycle according to copy doc
- [demo link](https://ubuntu-com-13512.demos.haus/about/release-cycle#ubuntu)
- [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
- Check that the links and text are correct
[WD-8531](https://warthogs.atlassian.net/browse/WD-8531)
Fixes #
[WD-8531]: https://warthogs.atlassian.net/browse/WD-8531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8531 - update text on /about/release-cycle

---

templates/about/release-cycle.html

Update image on /release-cycle according to copy doc
- [demo link](https://ubuntu-com-13516.demos.haus/about/release-cycle#ubuntu)
- [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
- Check that the image is correct
[WD-8565](https://warthogs.atlassian.net/browse/WD-8565)
Fixes #
[WD-8565]: https://warthogs.atlassian.net/browse/WD-8565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8565 - update image on /about/release-cycle

---

static/js/src/navigation.js
static/sass/_pattern_navigation.scss
templates/templates/_navigation.html

- adds functionality that calculate the view port size taking into account the size of the url bar
- fly by fix on links that also contained buttons not working
- Test that all links are visible on mobile view, these are the places it was reported:
-- on iOS it stops on Industrial, so that Robotics and Telco are left invisible below. You can hold and scroll down to expose both Robotics and Telco, but as soon as you release your finger they will hide again.
-- on Android it stops on Robotics and there is no way to see Telco that is hidden below. Holding and scrolling down doesn't do anything.
This is a bug that doesn't allow to click on items that are overflown.
- go to get ubuntu > desktop and check the top link works it clicked as does the download button
Fixes  [the comment …

Add functionality to account for height differences on mobile caused by the url navigation

---

webapp/shop/cred/views.py

- Expired contracts no longer show schedule button 
- Buy any exam
- Wait for a month for it to expire
- Should see an expired status and no schedule button
Fixes [#WD-7967](https://warthogs.atlassian.net/browse/WD-7967)

Wd 7967 expired contracts still show the schedule button

---

templates/internet-of-things/index.html

Update /internet-of-things page according to copy doc
- [demo link](https://ubuntu-com-13518.demos.haus/internet-of-things)
- [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit)
- Check that the links and text are correct
[WD-8067](https://warthogs.atlassian.net/browse/WD-8067)
Fixes #
[WD-8067]: https://warthogs.atlassian.net/browse/WD-8067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8067 - page update for iot

---

static/sass/_pattern_navigation.scss

- Ensure the navigation stays inline with content:
- Check the navigation logo stays inline with the content on the left hand side
- Check the mobile view, reduced navigation view and secondary

Minor tweeks to some alignments between medium and small screens

---

navigation.yaml

- Remove "Support" from sub-navigation item from /pricing bubble since the page it used to open before does not exist anymore (/pricing/infra)
- Navigate to https://ubuntu-com-13540.demos.haus/pricing and check if "Support" sub-navigation item does not exist
Fixes https://warthogs.atlassian.net/browse/WD-8623

[WD-8623] remove Support sub-navigation item from /pricing bubble

---

templates/desktop/developers.html
templates/desktop/flavours.html
templates/desktop/organisations.html
templates/desktop/partial/_desktop-latest-news.html

- Applied updates as per [doc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit) and [design](https://www.figma.com/file/wLOtPeQhAiExhQCwKYhi3H/24.04-U.com---desktop-(rebranding)?node-id=483%3A13939&mode=dev)
Drive by:
- Added latest news partial to revamped pages in the bubble
- Applied me screen layout for resources section across the bubble (Lyubo clarified that this should be the case)
- View the site locally in your web browser at: https://ubuntu-com-13541.demos.haus/desktop/organisations
Fixes https://warthogs.atlassian.net/browse/WD-7741

/desktop/organisations refresh

---

static/js/src/navigation.js

- Adds a function 'handleUrlHash', that on load, will check if the url has a hash (ex. #products) and open the corresponding dropdown
- Go to  and see that nothing opens
- Go to https://ubuntu-com-13546.demos.haus/#products and see that the 'products' dropdown opens
- Go to https://ubuntu-com-13546.demos.haus/download/desktop#use-case and see that the 'use-case' dropdown opens
- Go to https://ubuntu-com-13546.demos.haus/#made-up-hash and see that nothing opens
- check normal functionality is retained
Fixes https://warthogs.atlassian.net/browse/WD-8727

Open target meganav dropdown based on url hash on load

---

templates/kubernetes/charmed-k8s.html

- Changed text in one of the links at /kubernetes/charmed-k8s according to [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit)
- Open https://ubuntu-com-13587.demos.haus/kubernetes/charmed-k8s, scroll down to "Model driven Kubernetes" section and check the text of the link
Fixes https://warthogs.atlassian.net/browse/WD-8852

[WD-8852] replace lint text in charmed-k8s page

---

templates/kubernetes/install.html

- Updates /kubernetes/install based on the [copydoc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit)
- Go to 
- Compare against the  [copydoc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit) and resolve comments as you go 
Fixes https://warthogs.atlassian.net/browse/WD-8850

Update copy on kubernetes/install

---

templates/legal/ubuntu-pro-service-terms/index.md

- Updated copy as per [comment](https://docs.google.com/document/d/1aeqs6k-jgTf8xu3bOcloYpRgvIy7DuGjwyk7TLeTcqw/edit?disco=AAABGaTPkZI), follow-up of https://github.com/canonical/ubuntu.com/pull/13579
- View the site locally in your web browser at: https://ubuntu-com-13589.demos.haus/legal/ubuntu-pro-service-terms
- See that the typo has been fixed
Fixes #

Ubuntu Pro service terms typo

---

templates/download/alternative-downloads.html
templates/download/shared/_footer.html

- Refreshes https://ubuntu-com-13573.demos.haus/download/alternative-downloads based mostly on the current [live site](https://ubuntu.com/download/alternative-downloads) but with some changes applied from the [copy doc](https://docs.google.com/document/d/1VhmFVE3dK81mE3zcC9FVA6f5SGJ-DHan7WWlrlfRcvo/edit) and applying the [new design](https://www.figma.com/file/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=1%3A4&mode=dev)
- implements a side navigation 
- Go to https://ubuntu-com-13573.demos.haus/download/alternative-downloads heck the content matches the [live site](https://ubuntu.com/download/alternative-downloads) and the changes in [copy doc](https://docs.google.com/document/d/1VhmFVE3dK81mE3zcC9FVA6f5SGJ-DHan7WWlrlfRcvo/edit)
- Check the side navigation works. It …

Refresh /download/alternative-downloads

---

templates/desktop/developers.html

Remove image from /developers
- [demo link](https://ubuntu-com-13593.demos.haus/desktop/developers)
- Check that the image after "the developer's choice" is removed
[WD-9003](https://warthogs.atlassian.net/browse/WD-9003)
Fixes #
[WD-9003]: https://warthogs.atlassian.net/browse/WD-9003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9003 - remove image from /developers

---

templates/internet-of-things/smart-displays.html

Update screenplay logo on /smart-displays
- [demo link](https://ubuntu-com-13591.demos.haus/internet-of-things/smart-displays)
- [copy doc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit)
- Check that the logo is correctly updated according to copy doc
[WD-8974](https://warthogs.atlassian.net/browse/WD-8974)
Fixes #
[WD-8974]: https://warthogs.atlassian.net/browse/WD-8974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-8974 - update screenly logo on /smart-displays

---

templates/hpe/index.html

- Replaced TNM logo with a smaller one to align with other logos in https://ubuntu-com-13595.demos.haus/hpe page
- Navigate to https://ubuntu-com-13595.demos.haus/hpe and check if TNM logo is aligned in size with other logos at "Proven results from collaborative solutions" section
Fixes https://warthogs.atlassian.net/browse/WD-9029

[WD-9029] replace TNM logo with a smaller one to align with other logos in /hpe

---

static/js/src/static-forms.js
static/sass/styles.scss
templates/download/intel-nuc.html
templates/download/shared/_first-boot-setup.html
templates/download/shared/_login.html
templates/shared/forms/_desktop-security.html

- Rebrand Intel NUC page
- Check https://ubuntu-com-13580.demos.haus/download/intel-nuc against [copy docs](https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit) content should be almost the same as [prod](https://ubuntu.com/download/intel-nuc)
Fixes https://warthogs.atlassian.net/browse/WD-8798

Intel NUC rebrand WD-8795

---

package.json
static/js/src/navigation.js
static/sass/_global-settings.scss
static/sass/_pattern_navigation-dropdown.scss
static/sass/_pattern_navigation.scss
static/sass/styles.scss
templates/templates/_navigation.html
templates/templates/meganav/base.html
yarn.lock

- Bump to [vanilla-4.7.0](https://vanillaframework.io/docs/whats-new)
- removes an unused class
- Check that nothing is broken after upgrading vanilla

Bump to vanilla-4.7.0

---

templates/download/intel-iei-tank-870.html
templates/download/raspberry-pi-core.html
templates/download/shared/_resources.html

- Applied refresh as per [design](https://www.figma.com/file/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=185%3A650&mode=dev), [doc](https://docs.google.com/document/d/1Ig906jbgB39QHw61uHMvIsRbSBUjchJBDkMZl0WzlWM/edit), and [live page](https://ubuntu.com/download/raspberry-pi-core)
- Content should match the live site unless otherwise flagged on the doc
- Drive by:
- Reinstate commits made in https://github.com/canonical/ubuntu.com/pull/13576/files for `/download/intel-iei-tank-870` which were lost during rebase  
- View the site locally in your web browser at: https://ubuntu-com-13600.demos.haus/download/raspberry-pi-core
- Check against design, live site, and doc
Fixes …

Refresh /download/raspberry-pi-core

---

webapp/shop/cred/views.py

Credentials: Convert confidentiality agreement config var to bool before comparison.
- View the site locally in your web browser at: http://0.0.0.0:8001/credentials/exam?id=1
- The page should render
- Set env var to true
- Restart the site using the command `./run serve` or `dotrun`
- The agreement page should show.

Credentials: Convert confidentiality agreement config var to bool before comparison

---

templates/download/server/arm.html

- Added Ubuntu Server for 64k page size image download to https://ubuntu-com-13614.demos.haus/download/server/arm and made a few copy update changes according to the [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit).
- Navigate to https://ubuntu-com-13614.demos.haus/download/server/arm and check if the changes correspond to the above mentioned copy doc and if the images download correctly.
Fixes https://warthogs.atlassian.net/browse/WD-9067

[WD-9067] add Ubuntu Server for 64k page size image download to /download/server/arm

---

navigation.yaml

- Removed robotics topic from blog subnav as per linked ticket
Fixes https://warthogs.atlassian.net/browse/WD-9040

Remove robotics topic from blog subnav

---

static/js/src/chart-data.js
templates/about/release_cycles/kernel-eol.html
templates/shared/_kernel-support-schedule.html

- After yesterday's release of 22.04.4 version of Ubuntu there were changes made in several places, including Kernel charts at /about/release-cycle#ubuntu-kernel-release-cycle and /kernel/lifecycle. But it was not done correctly, as in 22.04.3 should not be replaced by 22.04.4, it needs to be added as a separate release instead. And this is what was fixed by this PR.
- Removed kernel versions 6.2 and 5.19 from all kernel charts and tables because their lifecycle has finished.
- Navigate to https://ubuntu-com-13615.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle and check if the chart and the table have 22.04.4 release that corresponds to 6.5 kernel version. Also check that 6.2 and 5.19 versions of kernel do not show.
- Navigate to …

[WD-9102] fix Kernel charts and tables for 22.04.4 release

---

tests/playwright/tests/pro/checkout.spec.ts

- This test can be running only locally. 
- Test to show correct VAT when country changes
how to run tests locally
- Save [this credentials](https://pastebin.canonical.com/p/m3PyRkf38P/) in `.env.local`
- Go to `playwright.config.ts` and comment out `testIgnore: '**\/pro/**',`
- Command `dotrun`
- Command `yarn playwright test /tests/playwright/tests/pro/checkout.spec.ts --ui ` or `yarn playwright test /tests/playwright/tests/pro/checkout.spec.ts` (`yarn playwright test` if you want to run all the playwright tests)
- Check tests pass locally
Fixes #https://warthogs.atlassian.net/browse/WD-8053

Playwright Test - Checkout show correct VAT

---

tests/playwright/tests/pro/checkout.spec.ts

- This test can be running only locally. 
-  Test values change is not applied when cancel button is clicked on edit mode in the VAT section and customer information section.
how to run tests locally
- Save [this credentials](https://pastebin.canonical.com/p/m3PyRkf38P/) in `.env.local`
- Go to `playwright.config.ts` and comment out `testIgnore: '**\/pro/**',`
- Command `dotrun`
- Command `yarn playwright test /tests/playwright/tests/pro/checkout.spec.ts --ui ` or `yarn playwright test /tests/playwright/tests/pro/checkout.spec.ts` (`yarn playwright test` if you want to run all the playwright tests)
- Check tests pass locally
Fixes #https://warthogs.atlassian.net/browse/WD-8054

Playwright Test - Click cancel reset fields

---

tests/playwright/helpers/utils.ts
tests/playwright/tests/pro/users.spec.ts

- This test can be running only locally.
- Test adding and deleting users on /pro/users 
how to run tests locally
- Save [this credentials](https://pastebin.canonical.com/p/m3PyRkf38P/) in `.env.local`
- Go to `playwright.config.ts` and comment out `testIgnore: '**\/pro/**',`
- Command `dotrun`
- Command `yarn playwright test /tests/playwright/tests/pro/users.spec.ts --ui ` or `yarn playwright test /tests/playwright/tests/pro/users.spec.ts` (`yarn playwright test` if you want to run all the playwright tests)
- Check tests pass locally
Fixes #https://warthogs.atlassian.net/browse/WD-8057

Playwright test - users spec for /pro/users

---

templates/kubernetes/what-is-kubernetes.html

Add a new section to "Try our newest Canonical Kubernetes distribution" /kubernetes/what-is-kubernetes
Note: links at the bottom of the section will be released on March 6th together with k8s-bubble-refresh feature
- [demo link](https://ubuntu-com-13618.demos.haus/kubernetes/what-is-kubernetes)
- [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit)
- Check that the section is correct according to copy doc
[WD-8891](https://warthogs.atlassian.net/browse/WD-8891)
Fixes #
[WD-8891]: …

WD-8891 - add new section to kubernetes/what-is-kubernetes

---

templates/kubernetes/resources.html

Add a new section to "Try our newest Canonical Kubernetes distribution" /kubernetes/resources
Note: links at the bottom of the section will be released on March 6th together with k8s-bubble-refresh feature
- [demo link](https://ubuntu-com-13617.demos.haus/kubernetes/resources)
- [copy doc](https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit#heading=h.wlkvcxbum9h0)
- Check that the section is correct according to copy doc
[WD-8849](https://warthogs.atlassian.net/browse/WD-8849)
Fixes #
[WD-8849]: …

WD-8849 - add new section to kubernetes/resources

---

templates/landscape/install.html

- Changed HOSTNAME variable name to HOST_NAME.
Fixes #13444 

chore: change HOSTNAME variable name to HOST_NAME

---

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
static/js/src/tabbed-content.js

- Hide free personal token if active paid subscriptions exist on `/pro/dashboard`
- Check free personal token displays when no subscription exists
- Check free personal token is hidden when valid paid subscriptions exist (start date <= now and end date >= now) 
- Check free personal token displays again when valid paid subscriptions doesn't exist. 
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?selectedIssue=WD-9026

Hide free token if active subscriptions exist

---

templates/download/shared/_server_weekly_news.html

- Replaced URL to PDF datasheet in /download/server Thank You page according to [copy doc](https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit).
- Navigate to /download/server
- Download an image of Ubuntu
- On the opened Thank You page click on "Download the pro tips" button
- In a modal fill in the form and click on "Download the pro tips" button
- Check if the downloaded PDF corresponds to the one specified in the [copy doc](https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit).
Fixes https://warthogs.atlassian.net/browse/WD-9255

[WD-9255] replace URL for datasheet in /download/server/thank-you

---

templates/ai/mlflow.html

Update /ai/mlflow page
- [demo link](https://ubuntu-com-13633.demos.haus//ai/mlflow)
- [copy doc](https://docs.google.com/document/d/1kafEsmi8OpaCD-WK4XnIBMgMStHUJNhM86nBN91e4ZI/edit)
[WD-9293](https://warthogs.atlassian.net/browse/WD-9293)
Fixes #
[WD-9293]: https://warthogs.atlassian.net/browse/WD-9293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9293 - update /ai/mlflow page

---

templates/engage/base.html
templates/engage/shared/_de_thank-you.html
templates/engage/shared/_es_thank-you.html
templates/engage/shared/_fr_thank-you.html
templates/engage/shared/_it_thank-you.html
templates/engage/shared/_pt_thank-you.html
templates/engage/shared/_ru_thank-you.html
templates/engage/shared/_zh-TW_thank-you.html
templates/engage/thank-you.html
webapp/views.py

Because of a bug, engage pages authors added `resource_url` even when there was no need for one, which is the case of engage pages when used as `contact_form_only`. This is the fix of `views.py`.
The rest of the templates changes are to remove redundant stuff, with the fix they are not needed anymore. Also to ensure the correct text shows.
- Go to https://discourse.ubuntu.com/t/campaign-ubuntu-pro-for-redis/36455 and remove the value https://ubuntu.com of the `resource_url` metadata.
- Now go to https://ubuntu-com-13624.demos.haus/engage/redis-ubuntu-pro-1-month-trial, fill out the form with test data, the page should work. This doesn't work in prod if the discourse topic `resource_url` is not empty.
Check everything else works fine:
- Check that any other non- `contact_form_only` works, …

Make resource_url optional for contact_form_only engage pages

---

templates/aws/pro.html

Added CTA button to /aws/pro
- [demo link](https://ubuntu-com-13642.demos.haus/aws/pro)
- [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit)
[WD-9157](https://warthogs.atlassian.net/browse/WD-9157)
Fixes #
[WD-9157]: https://warthogs.atlassian.net/browse/WD-9157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9157 - add CTA button to /aws/pro

---

templates/ai/index.html

- Copy update [/ai page](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit#heading=h.clco0x7p21f)
- Go to https://ubuntu-com-13626.demos.haus/ai and check the link for "Read more about Edge AI" has been added.
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932

WD-9266 Update /ai page

---

static/js/src/static-forms.js

The form was not sending the Comments_from_lead__c field. This happened because other forms were building this field dynamically from multiple question and removing text for the forms that have only one question for Comments_from_lead__c. This issue is fixed in this PR.
- [demo link](https://ubuntu-com-13641.demos.haus/support/contact-us)
- Check that the form sends correct fields to market
[WD-9049](https://warthogs.atlassian.net/browse/WD-9049)
Fixes #
[WD-9049]: https://warthogs.atlassian.net/browse/WD-9049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …

WD-9049 - fix contact form field not being sent

---

templates/download/server/download.html
templates/download/shared/_server_weekly_news.html
templates/download/shared/_verify-checksums.html
templates/shared/_download-ubuntu-thank-you-pro-section.html
templates/shared/_server-download-newsletter.html

- Rebrand content and design of /download/server
- Go to https://ubuntu-com-13629.demos.haus/download/server and choose to download Ubuntu server directly.
- Check the thank you page (click on the Download Ubuntu Server 22.04.4 LTS) with[ copy docs](https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit) and design below
- Test the 2 forms, the newsletter signup and the CLI cheatsheet.
Fixes https://warthogs.atlassian.net/browse/WD-9163

WD-9163 Rebrand ubuntu server thank-you

---

build.js

Fixed broken links in the [Links on live](https://github.com/canonical/ubuntu.com/actions/runs/8168377162)
- [demo link](https://ubuntu-com-13648.demos.haus/ceph/install)
- Check that the error about missing file does not happen
[WD-9175](https://warthogs.atlassian.net/browse/WD-9175)
Fixes #
[WD-9175]: https://warthogs.atlassian.net/browse/WD-9175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9175 - fix broken link on u.com

---

webapp/security/views.py

- Added a validity check for the notice_id
- We keep getting [strange requests](https://sentry.is.canonical.com/canonical/ubuntu-security/issues/32551/events/4182935/) that should throw 404s but are instead throwing 503s I believe because of the special characters. If we validate the provided notice_id before we make a call to the api it 404s correctly. 
- View the site locally in your web browser at: https://ubuntu-com-13650.demos.haus/security/notices/vbdb%0A.json.json
- See that you get 404
- Now visit https://ubuntu-com-13650.demos.haus/security/notices/USN-6679-8 
- This is a valid `notice_id` string, but the notice actually does not exist. Confirm that the previous behavior for this case is unaffected and also returns 404 
Fixes https://warthogs.atlassian.net/browse/WD-9449

Check notice id string before calling api

---

static/files/robots.txt

- Added an instruction to robots.txt to exclude /server/docs/search* page since it's dynamic and doesn't need to be indexed by Google.
- Can be QA-ed after deployment by checking logs in Google Search Console. Currently there are a lot of 5xx and 403 errors coming from the page as Google is trying to index all the different search queries.

add an instruction to robots.txt to exclude docs search page

---

templates/credentials/schedule.html
webapp/shop/api/ua_contracts/api.py
webapp/shop/cred/views.py

- Overhaul of the your exams page logic
- go to /credentials/your-exams
- Check all exams have correct status and actions
Fixes #

Wd 8766 Your Exams page logic overhaul

---

navigation.yaml

Remove Roadshow from u.com/ai navigation
- [demo link](https://ubuntu-com-13653.demos.haus/ai)
- Check that the item is removed
[WD-9428](https://warthogs.atlassian.net/browse/WD-9428)
Fixes #
[WD-9428]: https://warthogs.atlassian.net/browse/WD-9428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9428 - remove roadshow from ai navigation

---

templates/download/nvidia-jetson/tab-1-jetson-agx-orin.html
templates/download/nvidia-jetson/tab-2-jetson-orin-nano.html

- Updated broken download links
- View the site locally in your web browser at: https://ubuntu-com-13662.demos.haus/download/nvidia-jetson
- Click download links on both tabs and see that they download correctly
Originally reported on [MM](https://chat.canonical.com/canonical/pl/bcp33mcgx7n7bjygtjyon15xec)

Update broken download links

---

static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
static/js/src/advantage/subscribe/react/components/Form/Form.tsx
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
static/sass/_pattern_subscribe.scss
static/sass/styles.scss
templates/advantage/subscribe/index.html

- updated /pro/subscribe page
- checkout /pro/subscribe
- Should match the visuals [here](https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?type=design&node-id=558%3A5908&mode=design&t=Ix81wAC44BDZwiMr-1)
Fixes #[WD-8751](https://warthogs.atlassian.net/browse/WD-8751)
[WD-8751]: https://warthogs.atlassian.net/browse/WD-8751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …

Wd 8751 update the pro subscribe page visuals

---

meganav.yaml

Apply agreed updates in line with [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit) (please ignore open comment threads/suggestions)
- Add a “Data & AI” category under Products
- Add also a "Developer tools" category
- Drop Juju and Snapcraft categories
- Edit Ubuntu Desktop description
- Add MicroStack
- Update WSL links to /desktop/wsl
Fixes #
[QA …

Add Data & AI to meganav > Products

---

Dockerfile
static/js/src/contributions.js
static/sass/styles.scss
templates/download/desktop/thank-you.html
templates/shared/_server-download-newsletter.html

- Go to https://ubuntu-com-13649.demos.haus/download/desktop, choose a version
- You'll be redirected to the thank-you page which is what we're changing here, compare with [copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit) and design screenshot below.
- Check different screen sizes
- To test the "Thank you for your contribution", so you don't have to pay an actual donation, you can just go to https://ubuntu-com-13649.demos.haus/download/desktop/thank-you
Fixes https://warthogs.atlassian.net/browse/WD-9160

WD-9160 Rebrand Ubuntu desktop thank-you

---

meganav.yaml

- Changed Quick Links section of the "Ubuntu for IoT" part of the navigation according to the [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit).
- Click on "Get Ubuntu" in the top navigation
- Select "Ubuntu for IoT" from the left side of the navigation
- Check the "Quick Links" section on the right if it's the same as suggested in the [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit).
Fixes https://warthogs.atlassian.net/browse/WD-9573

[WD-9573] change quick links for Ubuntu for IoT navigation

---

templates/credentials/exam.html
webapp/shop/cred/views.py

Force HTTPS on Trueability exam iframe.
- Load an exam and make sure the iframe source is an https link.

Force HTTPS on Trueability exam iframe.

---

konf/site.yaml
templates/credentials/your-exams.html
webapp/shop/cred/views.py

- Add notification in your-exams page if you haven't signed the agreement.
- Enable agreement in staging, production and disable in demos.
- Go to your exams page and check the notifications shows up before you sign the agreement.

Show agreement notification in your-exams

---

templates/managed/apps/index.html

- Remove OSM logo from /managed/apps page according to the [copy doc](https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit).
- Navigate to [managed/apps](https://ubuntu-com-13676.demos.haus/managed/apps) and check that Mano logo is removed
Fixes https://warthogs.atlassian.net/browse/WD-9663

[WD-9663] remove OSM from the list in /managed/apps

---

webapp/shop/cred/views.py

Remove scheduling guards for event.

Remove scheduling guards for event.

---

templates/server/index.html

- point to correct JS to render the chart on /server
- Navigate to [/server](https://ubuntu-com-13683.demos.haus/server)
- Scroll down to "Security support for Ubuntu releases" section
- Check that the chart renders on bigger screens
Fixes https://warthogs.atlassian.net/browse/WD-9841

[WD-9841] point to correct JS to render the chart on /server

---

templates/download/amd/_working_commercial_section.html
templates/download/amd/tab-1.html
templates/download/amd/tab-2.html
templates/download/amd/tab-3.html

Add 'Are you working on a commercial project?' section to /download/amd
- [demo link](https://ubuntu-com-13684.demos.haus/download/amd)
- [copy doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- Check that the section is added correctly
[WD-9834](https://warthogs.atlassian.net/browse/WD-9834)
[WD-9834]: https://warthogs.atlassian.net/browse/WD-9834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9834 - add section to /download/amd

---

static/js/src/chart-data.js

- makes the changes to the graphs outlined in [the issue](https://warthogs.atlassian.net/browse/LANDPM-753)
- Check in [the demo](https://ubuntu-com-13688.demos.haus/kernel/lifecycle) that the appropriate graph changes (above) have been made
- Check it doesn't mess up other graphs ie. openstack, ubutnu releases etc
Fixes https://warthogs.atlassian.net/browse/WD-9799

Re-order kernel-lifecycle chart data

---

static/js/src/advantage/users/components/ExplainingTable.tsx

- Remove support portal seats column on pro account management page
- Go to `/pro/users`
- Check that support portal seats column is removed
Fixes [WD-9527](https://warthogs.atlassian.net/browse/WD-9527?focusedCommentId=434989&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-434989)
[WD-9527]: https://warthogs.atlassian.net/browse/WD-9527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove support portal seats column

---

templates/download/server/thank-you-s390x.html

Rebrand /download/server/thank-you-s390x
Contextual footer ('Get started with Ubuntu today...) will be rebranded in a separate task
- [demo link](https://ubuntu-com-13686.demos.haus/download/server/thank-you-s390x)
- [figma](https://www.figma.com/file/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=522%3A29620&mode=dev)
[WD-9490](https://warthogs.atlassian.net/browse/WD-9490)
[WD-9490]: https://warthogs.atlassian.net/browse/WD-9490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9490 - rebrand /download/server/thank-you-s390x

---

templates/engage/thank-you.html

As a quick fix it was chosen to remove 'resend it' link. Separate maintenance ticket will be created to investigate other solutions.
- [demo link](https://ubuntu-com-13691.demos.haus/engage/run-ai-at-scale)
- [copy doc](https://docs.google.com/document/d/1T5AdArzT5nZfur3wDTNPlb74bNCIW_leFhdmoaQ72DE/edit#heading=h.hkikdgm7ujct)
- Check that the page is correct according to copy doc
[WD-9396](https://warthogs.atlassian.net/browse/WD-9396)
[WD-9396]: https://warthogs.atlassian.net/browse/WD-9396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9396 - update engage pages form resubmit

---

templates/download/server/power.html

- Compare https://ubuntu-com-13678.demos.haus/download/server/power against [copy docs](https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit)
- Compare against design screenshot below
Fixes https://warthogs.atlassian.net/browse/WD-9164
[
](url)

WD-9167 Rebrand server power 

---

static/sass/_pattern_cve.scss
templates/security/cve/cve.html
webapp/security/views.py

- Applied redesign as per [mock-up](https://www.figma.com/file/nUJEBpOPTW74RqDRuMQXxB/23.04-U.com---CVEs?node-id=949%3A23161&mode=dev)
The JS functionality to toggle unmantained releases will be handled in a separate pr, as will further styling updates to the status table. "Other references" will also be handled separately as this field needs additional refactoring to satisfy the design.
- https://ubuntu-com-13679.demos.haus/security/CVE-2022-28737
- https://ubuntu-com-13679.demos.haus/security/CVE-2023-5678
- https://ubuntu-com-13679.demos.haus/security/CVE-2011-1497
- Check against design, noting known discrepancies listed in future work above 
Fixes …

Single CVE page

---

static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
templates/credentials/redeem_with_form.html
templates/credentials/schedule.html
webapp/shop/cred/views.py

- Remove colons from exam names
Fixes [#WD-9913](https://warthogs.atlassian.net/browse/WD-9913)

WD-9913 Update dropdown selections & branding on /schedule, /redeem, /your-exams, /shop for consistency

---

templates/shared/contextual_footers/_ua_got_questions.html

- Updated a reference to 'advantage' to reference 'pro', as specified in the [copydoc](https://docs.google.com/document/d/1So3n5HEpBX39xxEkkChnve09gKSr9TgYUcbfdOTCevk/edit#heading=h.u0ba418n7g4n)
- Check change in code
Fixes https://warthogs.atlassian.net/browse/WD-10021

Change mention of advantage to pro in contextual footer template

---

templates/hpe/index.html

- Fix the way blog post's title is rendered at /hpe page's last section for blog posts
- Navigate to https://ubuntu-com-13716.demos.haus/hpe
- Scroll all the way down
- Check if the blog posts' titles show correctly, without any code like on the screenshot below
Fixes https://warthogs.atlassian.net/browse/WD-10110

[WD-10110] add 'safe' instruction to blog post's title on /hpe

---

static/js/src/dynamic-forms.js
static/sass/styles.scss
templates/download/nvidia-jetson/index.html
templates/shared/forms/interactive/kernel-beta-signup.html
templates/shared/forms/interactive/nvidia-jetson.html
templates/thank-you.html

- Creates modal form based on the design of https://ubuntu.com/ai#get-in-touch (see [figma](https://www.figma.com/file/sGeCjFvA1kV9Kmvg2S2VBn/23.10-U.com---AI-bubble?type=design&node-id=248-1446&mode=design&t=SMx52yK27AMAlSAb-0)) and the content of https://ubuntu.com/internet-of-things/nvidia/contact-us (see [copydoc](https://docs.google.com/document/d/1znVFFLSyTmDwCplvloGAlEI3p_dpGH8v82hbYzVfz0o/edit#heading=h.dxn10eelvkoc))
- A little change to how dynamic forms works, it now check if it is a single page modal and updates the comments from lead on submit instead of 'next page' as it does usually.
- updates some specific styling to be generic across 50-50 modals
- updates a thank-you page to accept 'product' param (it isn't used here though)
- Go to …

Create modal form for nvidia-jetson

---

static/js/src/chart-data.js

- Updates bar chart colours based on [figma design](https://www.figma.com/file/koBN9oI6CGTjR7ucgB0lcJ/Kernel-release-cycle?type=whiteboard&node-id=0-1&t=u5TEhPMThSR8pHfx-0) and UX advice 
- https://ubuntu-com-13714.demos.haus/kernel/lifecycle
- https://ubuntu-com-13714.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle
Fixes https://warthogs.atlassian.net/browse/WD-10071

Update kernel release chart colours

---

navigation.yaml

- Added docs links to /aws, /azure, and /gcp subnavs as per ticket 
- https://ubuntu-com-13717.demos.haus/aws
- https://ubuntu-com-13717.demos.haus/azure
- https://ubuntu-com-13717.demos.haus/gcp
- See that all have available "Docs" links in the subnav and that they route to the urls specified in the ticket
Fixes https://warthogs.atlassian.net/browse/WD-10049

Add docs links to subnavs 

---

releases.yaml
templates/download/server/choose.html
templates/download/server/download.html
templates/download/server/manual.html
templates/download/server/multipass.html
templates/shared/_download-ubuntu-thank-you-pro-section.html
templates/shared/_server-download-newsletter.html

- Applied rebrand as per [doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit) and [mock-up](https://www.figma.com/file/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=906%3A7906&mode=dev)
- View the site locally in your web browser at: https://ubuntu-com-13704.demos.haus/download/server
- Please make sure each download still works as expected
Fixes https://warthogs.atlassian.net/browse/WD-8497

Rebrand /download/server pages

---

static/sass/styles.scss
templates/ai/what-is-kubeflow.html

Update /ai/what-is-kubeflow design according to figma and copy doc
Need confirmation from Andreea 
- [demo link](https://ubuntu-com-13711.demos.haus/ai/what-is-kubeflow)
- [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit)
- [figma](https://www.figma.com/file/sGeCjFvA1kV9Kmvg2S2VBn/23.10-U.com---AI-bubble?node-id=248%3A1446&mode=dev)
- Check that the page is correct according to the demo and copy doc
[WD-6314](https://warthogs.atlassian.net/browse/WD-6314)
[WD-6314]: https://warthogs.atlassian.net/browse/WD-6314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-6314 - rebrand /ai/what-is-kubeflow

---

navigation.yaml
static/js/src/chart-data.js
static/js/src/dynamic-forms.js
static/js/src/release-chart-old.js
static/sass/styles.scss
templates/download/nvidia-jetson/index.html
templates/hpe/index.html
templates/shared/forms/interactive/ai.html
templates/shared/forms/interactive/nvidia-jetson.html
templates/thank-you.html
webapp/shop/api/ua_contracts/api.py
webapp/shop/decorators.py

- Adds tooltips as detailed in the [figma design](https://www.figma.com/file/koBN9oI6CGTjR7ucgB0lcJ/Kernel-release-cycle?type=whiteboard&node-id=38-230&t=ZtnhVUJoZCfe8TFk-0)
- Check that the tooltips match the key in the following charts:
https://ubuntu-com-13713.demos.haus/about/release-cycle (check all the tabs)
https://ubuntu-com-13713.demos.haus/kernel/lifecycle
Fixes https://warthogs.atlassian.net/browse/WD-9302

Add tooltip to release chart bars

---

.djlintrc
.github/workflows/pr.yaml
requirements.txt

- Added djLint support to ubuntu.com similarly to canonical.com
- Set up djLint in your codebase as described in Discourse topic here: https://discourse.canonical.com/t/configuring-editors-for-formatting-and-linting/188
- Open any Jinja template and format it
- Check that the formatting was performed by running `git diff` on that file
- Check for red marks in the file if there are any that require manual fix
- If there were red marks check that they disappear after fixing and saving changes

add djlint formatter support to u.com

---

templates/support/index.html

Add button to /support
- [demo link](https://ubuntu-com-13735.demos.haus/support)
- [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit)
- Check that the page is correct according to copy doc
[WD-10215](https://warthogs.atlassian.net/browse/WD-10215)
[WD-10215]: https://warthogs.atlassian.net/browse/WD-10215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-10215 - add contact button to /support

---

static/js/src/chart-data.js
templates/about/release_cycles/releases-table.html
templates/server/index.html

Updated release charts for 24.04
- [demo link](https://ubuntu-com-13734.demos.haus/)
- View the site on the demo
- Go to [/server](https://ubuntu-com-13734.demos.haus/server), [/about/release-cycle](https://ubuntu-com-13734.demos.haus/about/release-cycle) and [/desktop/developers](https://ubuntu-com-13734.demos.haus/desktop/developers) and check that the chart has 24.04 added and 23.04 removed
[WD-10165](https://warthogs.atlassian.net/browse/WD-10165)
[WD-10165]: https://warthogs.atlassian.net/browse/WD-10165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-10165 - update release charts for 24.04

---

templates/engage/index.html
templates/engage/shared/_kr_engage_form.html
templates/engage/shared/_kr_thank-you.html

- Add Korean engage templates
- Add Korean to the lang dropdown on the /engage page
- Go to https://ubuntu-com-13737.demos.haus/engage/2024-automotive-trends-kr
- Check it works correctly
Fixes https://warthogs.atlassian.net/browse/WD-10249

WD-10249 Add Korean engage templates

---

templates/shared/_pro-for-devices-banner.html

- pdm requested the link also appear in the heading ('Ubuntu Pro for Devices') of the notification
- also fixed an issue with the banner appearing dark on /embedded
- Go to https://ubuntu-com-13736.demos.haus/internet-of-things and https://ubuntu-com-13736.demos.haus/embedded and see there is a clickable link under [Ubuntu Pro for Devices](https://canonical.com/blog/ubuntu-pro-for-devices), this is the same link as under [Read the press release to learn more](https://canonical.com/blog/ubuntu-pro-for-devices).
- See how on [ubuntu.com/embedded](https://ubuntu.com/embedded) the notification is dark background and on [the demo](https://ubuntu-com-13736.demos.haus/embedded) its not

Update link in iot pro banner

---

releases.yaml
templates/download/raspberry-pi/index.html

- Update Raspi download page for 24.04 release
- Go to https://ubuntu-com-13738.demos.haus/download/raspberry-pi and compare changes in the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#heading=h.486pnd5pwc1e)
- Download links won't download because we still don't have the ISOs
- Check it matches the design in the screenshot below
Fixes https://warthogs.atlassian.net/browse/WD-10056

WD-10056 Raspi copy update

---

templates/download/server/arm.html

- Add missing "and" word in one of the section's title
- Navigate to https://ubuntu-com-13741.demos.haus/download/server/arm
- Scroll down to second section and check its title if it's the same as specified in the [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit#heading=h.aqoxcz2ugemk)
Fixes https://warthogs.atlassian.net/browse/WD-10347

[WD-10347] add missing word in section title at /download/server/arm

---

static/js/src/chart-data.js
templates/about/release_cycles/k8s-eol.html

- remove EOL k8s releases (only 1.25+ is currently supported)
- add 1.29 dates
Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/837

adjust release-cycle dates for k8s 1.29

---

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx

-  Hide cost of legacy subscriptions in the dashboard, as the values are wrong and are confusing customers.
- Check if price for legacy subscriptions are not showing
- Check if the cost for all the other subscriptions are there
Fixes [#WD-10260](https://warthogs.atlassian.net/browse/WD-10260)

Pro - Hide cost for legacy subscriptions

---

templates/download/desktop/index.html
templates/download/raspberry-pi/index.html
templates/download/server/manual.html

- Turn Desktop link into button and update copy on /download/desktop, based on A/B test results
- Remove "ISO image" from the labels next to download CTAs, based on heatmaps
- Apply minor consistency tweaks (use paragraphs instead of lists, conditionals)
https://ubuntu-com-13759.demos.haus/download/desktop
https://ubuntu-com-13759.demos.haus/download/server
https://ubuntu-com-13759.demos.haus/download/raspberry-pi
Fixes #
[QA …

/download copy changes from UX research

---

templates/download/desktop/index.html
templates/download/desktop/thank-you.html
templates/download/server/manual.html
templates/download/server/thank-you.html
webapp/views.py

Added the word "LTS" at the end of the title of the Thank You page for downloading desktop and server images. It will only add it if the release is actually LTS. For interim and non-LTS releases that word will not be added.
- Navigate to either /download/desktop or /download/server
- Click on download button
- On redirected Thank You page check that it shows "LTS" at the end of the title
Fixes https://warthogs.atlassian.net/browse/WD-10461

[WD-10461] add lts

---

templates/desktop/developers.html

Removed releases table [according to request](https://warthogs.atlassian.net/browse/WD-10408)
- Go to  https://ubuntu-com-13760.demos.haus/desktop/developers and check that the table below the "Security support
" graph is no longer showing. Compare with prod https://ubuntu.com/desktop/developers
- Test that on mobile it doesn't show https://ubuntu-com-13760.demos.haus/desktop/developers
Fixes https://warthogs.atlassian.net/browse/WD-10408

Remove releases table for larger screens

---

templates/download/cloud/index.html
templates/download/raspberry-pi/index.html
templates/download/risc-v/index.html
templates/download/risc-v/tab-1.html
templates/download/risc-v/tab-2.html
templates/download/risc-v/tab-3.html
templates/download/risc-v/tab-4.html
templates/download/risc-v/tab-5.html
templates/download/risc-v/tab-6.html

Removed word "certified" from "Raspberry Pi Zero 2 W" line for 24.04 LTS release on /download/raspberry-pi page according to the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit).
I will highlight the actual change with the comment, the rest is formatting by djLint.
- Navigate to https://ubuntu-com-13768.demos.haus/download/raspberry-pi
- Scroll down to "Supported devices" section
- Check that it says "Yes" next to "Raspberry Pi Zero 2 W" line for 24.04 LTS release
Fixes https://warthogs.atlassian.net/browse/WD-10513

[WD-10513] update download raspberry pi

---

templates/credentials/schedule.html

- Cannot select timezone in credentials exam scheduler
- Try to schedule an exam or simply go to /credentials/schedule?contractItemID=<any random string>
- Verify that there is a dropdown for selecting timezones
Fixes [#WD-10580](https://warthogs.atlassian.net/browse/WD-10580)

WD-10580-time-zone-on-schedule-page-no-longer-selectable

---

templates/desktop/index.html

Replace Ubuntu background desktop image on u.com/desktop
- [demo link](https://ubuntu-com-13776.demos.haus/desktop)
- Check that the image is correctly updated
[WD-10546](https://warthogs.atlassian.net/browse/WD-10546)
[WD-10546]: https://warthogs.atlassian.net/browse/WD-10546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-10546 - change desktop background image

---

templates/base_index.html

- Updated link as per [doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)
- View the site locally in your web browser at: https://ubuntu-com-13781.demos.haus/
- See that the link no longer 404s
Fixes https://github.com/canonical/ubuntu.com/issues/13752 , https://warthogs.atlassian.net/browse/WD-10665

Update broken link on landing

---

static/sass/_pattern_navigation.scss

- The little white strip that appears on the left of the selected page in the secondary nav was mis-aligned (see screenshots), this pr fixes this.
- Go to a page with a secondary nav, ex. https://ubuntu-com-13792.demos.haus/desktop/organisations
- Open the secondary nav and see the highlight page no longer looks broken
Fixes https://warthogs.atlassian.net/browse/WD-10558
Before:
After:

Fix secondary nav selected items marker being mis-aligned

---

releases.yaml
templates/desktop/wsl.html
templates/download/alternative-downloads.html
templates/download/desktop/index.html
templates/download/raspberry-pi/index.html
templates/download/server/manual.html

Received a request from Oliver to fix the following:
- change amount of RAM from 2 to 4 on /download/raspberry-pi page
- Change the size of Core 22 from 263GB to 263MB on /download/raspberry-pi page
- Change link text to "Ubuntu 24.04 LTS deep dive >" on /download/desktop
- Added link to Ubuntu 22.04 on /download/alternative-downloads
- Change Rust version from 1.78 to 1.75 on /download/server
- Change the amount of free hard drive space from 2.5GB to 5GB on System Requirements tab on /download/server
Check that all above mentioned changes are in place

24.04 release quick changes

---

static/sass/_pattern_navigation.scss

- Removes some styling that was overriding the padding needed for section headings in the meganav (see screenshots)
- Go to [the demo](https://ubuntu-com-13794.demos.haus/) on mobile size screen
- Open the menu and click 'use-cases'
- See their is the appropriate padding for the heading 'By solution'
Fixes https://warthogs.atlassian.net/browse/WD-10559
Before:
After:

Fix meganav use-cases section headings

---

templates/kubernetes/docs/how-to-cos-lite.md
templates/kubernetes/docs/how-to-operate.md

- Add instructions for COS Lite to address request from field
Reminder - the content of these docs has already been reviewed and approved by the K8s team.

K8s docs - Add COS Lite

---

static/js/src/chart-data.js
templates/about/release_cycles/kernel-eol.html

- Update kernel chart at /about/release-cycle according to the [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=550510389)
- Check if the chart has the latest 24.04 release data
Fixes https://warthogs.atlassian.net/browse/WD-10663

[WD-10663] add 24.04.0 LTS release to Kernel chart

---

releases.yaml
templates/download/desktop/index.html
templates/download/raspberry-pi/index.html
templates/download/risc-v/tab-1.html
templates/download/risc-v/tab-2.html
templates/download/risc-v/tab-3.html
templates/download/risc-v/tab-4.html
templates/download/risc-v/tab-5.html
templates/download/risc-v/tab-6.html

- Updated checksums for 24.04 release according to https://paste.ubuntu.com/p/P2xqsW3Pnd/
- Updated sizes for new LTS images in releases.yaml
- Changed links for RISC-V according to https://docs.google.com/document/d/1CfhMbNC-LQtsY_gEm1jG3Vpo9MaY15kwulASMs1aCVQ/edit
- Navigate to 
- /download/desktop
- /download/server
- /download/raspberry-pi
- /download/risc-v
, and check that:
- the images download
- checksums correspond
- sizes are shown
Fixes https://warthogs.atlassian.net/browse/WD-10167

[WD-10167] update checksums for 24.04 LTS, add sizes for new Ubuntu images

---

releases.yaml

The variable is not used in ubuntu.com but referred by other variants such as jp.ubuntu.com. Let's fix it anyway so the merge in the future can be easier.
- Fix the URL
Fixes #

Fix noble release notes URL

---

static/js/src/advantage/offers/types.ts
tests/shop/advantage/fixtures/channel-offer.json
tests/shop/advantage/fixtures/channel-offers.json
tests/shop/advantage/test_parsers.py
webapp/shop/api/ua_contracts/models.py
webapp/shop/api/ua_contracts/parsers.py

- Update Offer model and types according to the changes in [ua_contracts](https://github.com/canonical/ua-contracts/blob/d32984c23db25bb09858ca59b939cb2dbb3d493f/docs/contracts.yaml#L2614-L2721)
- Add test to parse [channel offer](https://github.com/canonical/ua-contracts/blob/develop/docs/howtos/work-with-offers.md#channel-offers). 
1. Checkout this branch and run 
2. Go to `/webapp/shop/advantage/views.py` 
- for normal offer, 
- line 573, replace `account.id` to account id on [here](https://pastebin.canonical.com/p/ztMSjGWM7n/)
- for channel offer
- line 573, replace `account.id` to account id on [here](https://pastebin.canonical.com/p/ztMSjGWM7n/)
- line 562  replace "canonical-ua" to "canonical-pro-channel"
4. Go to `/static/js/src/advantage/offers/components/OffersList/OffersList.tsx …

Update offer model and types

---

static/js/src/chart-data.js

- Added ESM support for 22.04.1 LTS on 5.15 kernel version in Kernel chart at /about/release-cycle (it was only added to the table by mistake)
- Navigate to /about/release-cycle and open Ubuntu Kernel tab
- Check that there is a bar for ESM support on line that stands for 5.15 kernel version and 22.04.1 LTS Ubuntu release
Fixes https://warthogs.atlassian.net/browse/WD-10663

[WD-10663] fix ESM date on the kernel chart

---

navigation.yaml
static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx

- Add link to Pro documentation on /pro navigation and /pro/dashboard
- Go to `/pro`
- Click on Docs and see that it redirects to https://documentation.ubuntu.com/pro/
- Go to Support and Documentation section, see that `Ubuntu Pro documentation` is at the top of list and redirects to https://documentation.ubuntu.com/pro/
Fixes [WD-10726](https://warthogs.atlassian.net/browse/WD-10726)
[WD-10726]: https://warthogs.atlassian.net/browse/WD-10726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add link to Pro documentation

---

templates/about/release_cycles/releases-table.html

- Fixed the dates for Noble Numbat release on /about/release-cycle page's Ubuntu tab
- Navigate to /about/release-cycle
- By default Ubuntu tab is open
- Check the Noble Numbat support dates in the table below the chart
- Standard support should be from Apr 2024 till Apr 2029
- Extended Pro support should be from Apr 2029 till Apr 2034

fix dates in the release cycle table at /about/release-cycle

---

navigation.yaml
package.json
static/sass/styles.scss
templates/core/index.html
templates/core/tabs.html
yarn.lock

Update core home page according to figma and copy doc
- [demo link](https://ubuntu-com-13754.demos.haus/core)
- [copy doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit)
- [figma](https://www.figma.com/file/5kDdBtPRqthyPz263YV91U/24.04-Ubuntu-Core-rebrand?type=design&node-id=711-3453&mode=design&t=3k9mbyENz2DBU0hh-0)
- Check that the page is correct according to the demo and copy doc
[WD-9618](https://warthogs.atlassian.net/browse/WD-9618)
[WD-9618]: https://warthogs.atlassian.net/browse/WD-9618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-9618 - update core home page

---

static/sass/_pattern_navigation.scss

- The padding in the meganav secondary nav was different on each side, this PR makes it the same.
- Go to a page in the demo with a secondary nav, ex: https://ubuntu-com-13791.demos.haus/support
- Inspect the secondary nav items and see they have the same padding on each side
Fixes https://warthogs.atlassian.net/browse/WD-10551
Before:
After:

Standarise the padding of secondary navigaiton items in the meganav

---

meganav.yaml
templates/templates/meganav/navigation-nojs.html

- Updates the `meganav.yaml` to include the 24.04 changes in the [copydoc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit#heading=h.xn1ukikvpexx)
This bit:
- Adds 'is-dark' to to no js navigation to fix links appearing as black on black
- Check the links match those in the [copydoc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit#heading=h.xn1ukikvpexx)
Fixes https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit#heading=h.xn1ukikvpexx

Update meganav yaml to include 24.04 links

---

webapp/shop/cred/views.py

- Surface status for exams directly from TA 
- Handle errors fetching info from TA
- Break TA API calls locally
- Visit /credentials/your-pages
- Check if page still loads 
- Fix TA calls
- Check if the exam status is the same as TA
Fixes #

WD-10785-cred-surface-ta-exams-status-instead-of-resorting-to-mapping

---

static/js/src/image-download.js
webapp/views.py

**Context**: Ubuntu download mirrors are not being hit, for example when you download from https://ubuntu.com/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true it always downloads from releases. This aims to fix that.
- Fetch the users location on the client side and passes it to the mirror fetching function. As opposed to getting the location on the backend which I think was causing the problem. This should also be more consistent.
- Go to https://ubuntu-com-13831.demos.haus/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true
- This will trigger a download, check the download location is from a mirror that is close to your country
Fixes https://warthogs.atlassian.net/browse/WD-8090 …

Try getting the user location client side

---

navigation.yaml
templates/core/features/index.html
templates/core/index.html

Updates navigaton from:
`Services, Success stories, Features, Docs`
To: 
`Features, Success Stories, Services, Docs`
- Updates the `Read the Ubuntu Core datasheet` link in https://ubuntu-com-13839.demos.haus/core and https://ubuntu-com-13839.demos.haus/core/features. see [core copydoc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit#heading=h.il7ddqhjlzrs) and [core/features copydoc](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit)
- Go to https://ubuntu-com-13839.demos.haus/core and check the navigation is explained above
- Check the datasheet links on both /core and /core/features
Fixes https://warthogs.atlassian.net/browse/WD-10917 …

Update navigation in core bubble

---

static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
static/js/src/advantage/credentials/utils/utils.ts
static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx

- Name of exam in /credentials/shop changed along with price display
- go to /credentials/shop
- Try to purchase the free exam 
Fixes [#WD-10929](https://warthogs.atlassian.net/browse/WD-10929)

WD-10929-fix-exam-names-in-shop

---

static/sass/_pattern_navigation-dropdown.scss

Button applies active styling to parent when clicked on.
If reviewer has any ideas, I'm all ears. The more things I try the weirder it gets, I'm not sure anymore if I should treat it as a bug or as missing feature, so left a [comment in the Vanilla channel](https://chat.canonical.com/canonical/pl/mtycdaw7jpfjfr9w3n6zbnk69c)
- Currently this PR treats it as a bug, so it overrides that additional background
- If it's not a bug, another possibility is to add the new background on top of it.
This seems inherited from Vanilla https://codepen.io/carkod/pen/qBwGbWo  I can’t change it at that level, so I can only override it on u.com
[Reported in Vanilla](https://github.com/canonical/vanilla-framework/issues/5068)
- Go to https://ubuntu-com-13826.demos.haus/ and click on "Get ubuntu".
- When you …

Fix button active

---

package.json
templates/desktop/index.html
yarn.lock

- Updates to latest Vanilla 4.11
- Updates the divider class name in equal heights row component from `has-1st-divider` to `has-divider-1` (as per change in Vanilla 4.11)
- As a drive-by updates the HTML structure of the equal heights row component
**NOTE:** The reason for the drive-by HTML changes was combining multiple component class names on single element. This is a bad practice. Even if it works now, may potentially break in future if both components affect the same CSS properties. As a rule of thumb a single HTML element should not have class names coming from 2 different components. Ideally there should be only one `p-…` class name on element, if there are multiple, they should be from same component `p-the-same-…`.
- Run the site using the command …

Update to Vanilla 4.11 (and fix equal heights component)

---

templates/credentials/syllabus.html

- Remove duplicate tabs from /credentials/syllabus
- Go to /credentials/syllabus
- There should only be one line of tabs
Fixes [#WD-11185](https://warthogs.atlassian.net/browse/WD-11185)
From:
To:

Removed duplicate tab from syllabus page

---

static/js/src/chart-data.js
static/js/src/release-chart-old.js
static/js/src/release-chart.js

- Change colour in release chart for LTS from black to orange
- Visit /about/release-cycle and look at the chart
Fixes [WD-11189](https://warthogs.atlassian.net/browse/WD-11189)
From:
To:
[WD-11189]: https://warthogs.atlassian.net/browse/WD-11189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

change to orange

---

templates/core/index.html

Added a `rel=0` parameter to YouTube URL link to prevent videos from other channels to show up in suggestions after the video reaches the end. The solution comes from this [SO thread](https://stackoverflow.com/a/36327162/6379181).
- Navigate to /core
- Play the YouTube embedded video till the end
- Check all the suggestion videos that pop-up and check if all of them come from Canonical YT channel
Fixes https://warthogs.atlassian.net/browse/WD-11117

[WD-11117] add a parameter to YT video URL link to prevent unnecessary suggestions

---

templates/security/index.html

- Removes 'is-dark' from suru
- Go to https://ubuntu-com-13863.demos.haus/security and see the button doesn't look broken

Fix button styling on /security

---

static/js/src/advantage/distributor/app.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Currency/Currency.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Currency/index.ts
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Duration/Duration.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/Duration/index.ts
static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/TechnicalUserContact.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/TechnicalUserContact/index.ts
static/js/src/advantage/distributor/utils/FormContext.tsx
static/js/src/advantage/distributor/utils/utils.ts

- Added step 2. 3. 5 on the distributor shop page
- Initiate order
Fixes #https://warthogs.atlassian.net/browse/WD-10607, https://warthogs.atlassian.net/browse/WD-10608,  https://warthogs.atlassian.net/browse/WD-10610

WD-10607 add step 2. 3. 5 on the distributor shop page

---

static/js/src/release-chart-old.js

"mouse over the black bar that is labeled standard security maintenance in the legend, and you get a tooltip that has the dates right but describes it as expanded.
similarly the dark aubergine bar has a tooltip that says "standard security maintenance
for ubuntu main: 2020-2030" so again the date is right for the bar but the description is wrong."
- Go to [issue](https://github.com/canonical/ubuntu.com/issues/13844) and check the descibed bug has been fixed
Fixes https://github.com/canonical/ubuntu.com/issues/13844

Fix labels on release charts

---

templates/training/index.html

- Changes 'ON' to 'on'
Fixes #

Fix /training typo

---

static/js/src/advantage/distributor/DistributorShop.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/DistributorShopSummary.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopSummary/index.ts
static/js/src/advantage/distributor/components/DistributorShopForm/PaymentButton/PaymentButton.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/PaymentButton/index.ts
static/js/src/advantage/distributor/utils/FormContext.tsx

- Added summary section 
- Initiate order
- on /pro/distributor/shop, complete all steps and check the summary 
Fixes #https://warthogs.atlassian.net/browse/WD-10613

WD-10613 add summary section 

---

templates/internet-of-things/smart-displays.html

Add new link to screely section
- Go to https://ubuntu-com-13872.demos.haus/internet-of-things/smart-displays and [check Lizzi's comment has been addressed](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit) in this PR
Fixes https://warthogs.atlassian.net/browse/WD-10989

Add link to smart displays screenly section

---

webapp/app.py
webapp/context.py
webapp/security/views.py

- Added rate limiting to the security and notices APIs
- Open the demo at https://ubuntu-com-13880.demos.haus/security/cves and open any cve page
- Also open https://ubuntu-com-13880.demos.haus/security/notices and open any notice
- Both should open normally
Fixes [WD-11323](https://warthogs.atlassian.net/browse/WD-11323)
[WD-11323]: https://warthogs.atlassian.net/browse/WD-11323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add rate limiting to cves

---

templates/download/risc-v/index.html
templates/download/risc-v/milk-v-mars.html
templates/security/index.html

To be deployed 27th of May
- Add new tab to the navigation
- Add content to the tab
- Go to https://ubuntu-com-13861.demos.haus/download/risc-v, click on Milk-V tab and compare with [copy doc comments](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit)
- Check navigation item shows for both large and small screens
- Check content (Milk-V tab) is added correctly
- Check links are correct
Fixes https://warthogs.atlassian.net/browse/WD-10765

Add Milk-V tab

---

templates/download/index.html

- Update download link for Core - [copy docs](https://docs.google.com/document/d/1egsCcmFiz8czeHsvwoB9Jz815Ij5Urtf7Ngrru6Zd4o/edit#heading=h.o0ts125bxkxo)
- Go to `/download`
- Click on Core hyperlink, should redirect to `/download/core`
Fixes [WD-11634](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?assignee=712020%3A55efc110-e0f6-401a-bcb0-b48a794b6dae&selectedIssue=WD-11634)
[WD-11634]: https://warthogs.atlassian.net/browse/WD-11634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update core download link

---

redirects.yaml
webapp/certified/views.py

- Changed "nVidia" to "NVIDIA"
- View the site locally in your web browser at: https://ubuntu-com-13898.demos.haus/certified/vendors/nVidia
- See that you are redirected and the url now reads `.../NVIDIA` instead
- Check that the capitalization is correct in the hero, vendor filter, and results table
Fixes# https://warthogs.atlassian.net/browse/WD-11476

Change nVidia to NVIDIA and add corresponding redirect

---

static/js/src/takeover-tracking.js

fix: Fire control_or_variant tracking event on window load

---

templates/ceph/install.html

- Changed occurance of "ROCKs" to "rocks" in ceph/install.html
- Also the [copydoc](https://docs.google.com/document/d/1EmOtHjuEMKhVLQA7GwyrKfCzOKfc8UCEyh-p04-PxzA/edit) for the change.
- [Demo](https://ubuntu-com-13892.demos.haus/ceph/install)
[WD-11514](https://warthogs.atlassian.net/browse/WD-11514)
[WD-11513]: https://warthogs.atlassian.net/browse/WD-11513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

WD-11514 Modified "Rock" to "rock" and linted the /ceph/install.html

---

static/js/src/chart-data.js
templates/about/release_cycles/k8s-eol.html

- Added Kubernetes 1.30 release and support lifecycle dates
- Go to `/about/release-cycle#canonical-kubernetes-release-cycle`
- Check that Kubernetes 1.30 is present on chart and table with the correct dates:
- release date: April 2024
- end of n-2 support in April 2025
- end of n-4 support in December 2025
Fixes [WD-11377](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?assignee=712020%3A55efc110-e0f6-401a-bcb0-b48a794b6dae&selectedIssue=WD-11377)
[WD-11377]: https://warthogs.atlassian.net/browse/WD-11377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add k8s 1.30 to support lifecycle

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx

When a customer tries to renew a subscription for now a deprecated product, the `ubuntu.com` website gets a similar error from the Ubuntu Pro backend: `missing one-off product listing for renewal product: "uaia-essential-virtual": product listing not found` The current front-end code does not handle this error message correctly, so the opaque `Sorry, there was an unknown error with your credit card` error message is shown on UI. This PR handles the case of a missing offering correctly and proposes the customer choose another product.
It is too late to show such an error at checkout. I believe some validation should be added before going to checkout to ensure that the product is among `ValidProducts`. However, even despite this consideration, this PR is still relevant to handle integration …

[Fix] Handle deprecated products on checkout

---

templates/security/certifications.html
templates/security/index.html
templates/shared/_cra-banner.html

_Go live date June 3rd_
- Add CRA banners to `/security` and `/security/certification` pages
- Go to demos for `/security`, check that changes are updated as per [copy docs](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit)
- Go to demos for `/security/certification`, check that changes are updated as per [copy docs](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit)
Fixes [WD-11271](https://warthogs.atlassian.net/browse/WD-11271)
[WD-11271]: https://warthogs.atlassian.net/browse/WD-11271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

Add CRA banners to security and certs pages

---

templates/account/forbidden.html
webapp/shop/advantage/views.py

- Blocked channel user from accessing regular pro shop
- Blocking regular users from accessing distributor shop will be done by a separate PR ([ticket](https://warthogs.atlassian.net/browse/WD-10786)). 
- Login with channel account
- Go to `/pro/subscribe`, `/account/checkout`, `/pro/dashboard`
- Check forbidden page shows 
- Login with normal account
- Check `/pro/subscribe` page accessible
Fixes #https://warthogs.atlassian.net/browse/WD-10782

Block channel user from accessing regular pro shop

---

templates/shared/_download-newsletter.html

Fixed styling for usage options to /download/desktop/thank-you newsletter signup form
- [demo link](https://ubuntu-com-13914.demos.haus/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true)
- Check that the checkboxes are correct according to [figma](https://www.figma.com/design/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=1416-2569&m=dev)
[WD-11786](https://warthogs.atlassian.net/browse/WD-11786)
[WD-11786]: https://warthogs.atlassian.net/browse/WD-11786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-11786 - fix chexboxes on newsletter form

---

static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.test.tsx
static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
static/js/src/advantage/subscribe/react/components/Form/Form.tsx
static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx
static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx
static/js/src/advantage/subscribe/react/utils/FormContext.tsx
static/js/src/advantage/subscribe/react/utils/utils.ts

- Remove 14.04 from and add 24.04 to the Ubuntu Pro Shop
- Visit /pro/subscribe
- Make sure 14.04 is not there anymore 
- Make sure the content for 24.04 is in line with [the copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit)
- Try to purchase the server or desktop subscription for 24.04
- Ensure purchase goes through and that the new subscription shows up in the dashboard 
Fixes [#WD-11765](https://warthogs.atlassian.net/browse/WD-11765) …

WD-11765-remove-14-04-and-add-24-04-to-the-pro-shop

---

static/js/src/advantage/subscribe/react/components/Form/Form.tsx

- Add LTS to 16.04 below product selector
- visit /pro/subscribe
- Point 2 subheading should say 
"Ubuntu Pro is available for Ubuntu 16.04 LTS and higher".
Fixes #

WD-11828-add-lts-to-16-04-in-pro-product-selector

---

static/js/src/advantage/api/types.ts
static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
static/js/src/advantage/tests/factories/api.ts
webapp/shop/api/ua_contracts/builders.py
webapp/shop/api/ua_contracts/models.py
webapp/shop/api/ua_contracts/parsers.py
webapp/shop/api/ua_contracts/primitives.py

- Blocked by missing attribute from ua-contracts API
- Hardcoded maxTracking value for now to show "+" in front of active machines number
- See "+" in front of active machines number
Fixes [WD-10492](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?selectedIssue=WD-10492)
[WD-10492]: https://warthogs.atlassian.net/browse/WD-10492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show plus sign when maximum tracking is reached

---

templates/containers/chiselled/index.html
templates/engage/base.html

- Go to https://ubuntu-com-13910.demos.haus/engage/exploring-edge-computing-in-automotive and check that the image is not stretching anymore.
Fixes https://warthogs.atlassian.net/browse/WD-7416
Previous:
Fix:

Fix image stretching text

---

templates/base_index.html
webapp/app.py
webapp/views.py

- As a follow-up of [Sam's work](https://github.com/canonical/ubuntu.com/pull/13636), move to the timezone system for takeovers instead of IP addresses.
- Remove IP address geolocation
- Go to https://discourse.ubuntu.com/t/takeover-french-business-guide-to-multicloud/34968
- Edit the post and set `target_country` to your country code
- Go to the [demo homepage](https://ubuntu-com-13899.demos.haus/), reload a bunch of time until you see that takeover.
- Please if you not in too much of a hurry, revert back the Discourse takeover change.
Fixes https://warthogs.atlassian.net/browse/WD-7175

Switch from ip to tz for takeovers.

---

konf/site.yaml

- Added Marketo secrets to /credentials
- 
Fixes #

Add secrets for marketo to credentials

---

templates/aws/index.html
templates/aws/pro.html
templates/aws/shared/_get_pro.html

- 2 copy updates, updating AWS links
- Refactor `_get_pro` section, so that we can reuse it in multiple pages.
- Go to https://ubuntu-com-13924.demos.haus/aws and [check copy doc comments are addressed](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit#heading=h.wmtx864far5b)
- Go to https://ubuntu-com-13924.demos.haus/aws/pro and [check copy doc comments are addressed](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit)
Fixes https://warthogs.atlassian.net/browse/WD-11844
Fixes https://warthogs.atlassian.net/browse/WD-11846

Update AWS links

---

templates/engage/base.html

- Add discourse topic url to meta to make it easier to find. [Here is some more context](https://chat.canonical.com/canonical/pl/mdkat5rry7d6bcgsbowj698ebc)
- Go to https://ubuntu-com-13298.demos.haus/engage/guide-to-micro-clouds right click and view source code
- Check there is new meta tag called `discourse-url` 
Fixes [WD-11357](https://warthogs.atlassian.net/browse/WD-11357)
[WD-11357]: https://warthogs.atlassian.net/browse/WD-11357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add discourse url to engage page

---

templates/shared/_download-newsletter.html

Fixed data sent for usage options to /download/desktop/thank-you newsletter signup form
- [demo link](https://ubuntu-com-13935.demos.haus/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true)
- Check that the data sent according to the expectation
[WD-11786](https://warthogs.atlassian.net/browse/WD-11786)
[WD-11786]: https://warthogs.atlassian.net/browse/WD-11786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-11786 - different language answers in desktop download form

---

package.json
yarn.lock

- Bump cookie-policy to v3.6.4
- Check out 
- Delete cookies so you get the cookie policy pop up
- Accept nothing and check that in cookies there exists `_cookies_accepted=essential`
- Repeat with only accept 'performance', only accepting 'functional' and finally 'all'
Fixes https://warthogs.atlassian.net/browse/WD-11997?atlOrigin=eyJpIjoiMjZiZWI5N2FjYzI3NGMyZDg4YjM1ZTM4YzkyZjk3YzkiLCJwIjoiaiJ9

chore: Bump cookie-policy to v3.6.4

---

templates/credentials/dashboard.html
webapp/app.py
webapp/login.py
webapp/shop/api/trueability/api.py
webapp/shop/cred/views.py
webapp/shop/decorators.py

- Created a `@credentials-group` decorator that restricts views to only the credentials group on Lunchpad
- Login as user who is in the lp credentials group
- Go to /credentials/dashboard
- Page should be visible
- Logout and login as someone not in credentials group
- Go to /credentials/dashboard
- Page should be visible
Fixes #

WD-12132-create-decorator-to-restrict-views

---

static/js/src/dynamic-forms.js
static/js/src/kernel-form.js

- Replaced legacy Google Analytics scripts with dataLayer.push() scripts.
- Upon the respective dyanmic form events, the dataLayer array contains the values specified in the code.

GROWENG-3818 changing legacy google analytics event to datalayer push

---

static/sass/styles.scss
templates/base_index.html
templates/takeovers/_test_template.html

Added a new takeover template. DO NOT MERGE until takeover removed from main page
- [demo link](https://ubuntu-com-13958.demos.haus/)
- [figma](https://www.figma.com/design/Le4TTzyOFbcbqTPJ1tVoZT/U.com---Home-and-footer-(rebranding)?node-id=0-1&m=dev)
- Check that the takeover is according to the design
[WD-11694](https://warthogs.atlassian.net/browse/WD-11694)
[WD-11694]: https://warthogs.atlassian.net/browse/WD-11694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-11694 - add new takeover template

---

templates/download/server/manual.html
templates/download/server/thank-you.html

- Moves where the GA event is triggered from the '/thank-you' page to the original '/download/server' page. This is done by moving the target class `js-download-option`
- Go to https://ubuntu-com-13965.demos.haus//download/server
- Open dev console and log 'dataLayer'
- Check that this object exists in the 'dataLayer':
`{
"event": "NonInteractiveGAEvent",
"eventCategory": "www.ubuntu.com-impression-download-option",
"eventAction": "Display option",
"eventLabel": "Get Ubuntu Server",
"gtm.uniqueEventId": 19
}`
- Click `Download` to navigate to the '/thank-you' page and check the object doesn't exist in the 'dataLayer' there
Fixes https://warthogs.atlassian.net/browse/WD-11960

bug: Move GADownloadImpressionsEvents trigger on /download/server from thank-you page to download page

---

templates/aws/index.html

- Updated copy as per [doc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit?disco=AAABPDMgmic)
- View the site locally in your web browser at: https://ubuntu-com-13971.demos.haus/aws
- See that the requested change 
Fixes https://warthogs.atlassian.net/browse/WD-12253

/aws fix Ubuntu version typo

---

requirements.txt

- Bump canonicalwebteam.discourse to 5.5.0
- Go to https://ubuntu-com-13978.demos.haus/ceph/docs
- Use chrome dev tools to see that the anchor link in heading don't have trailing numbers

chore: Bump canonicalwebteam.discourse to 5.5.0

---

webapp/security/api.py
webapp/security/views.py

- Reinstate order param as per sec. api revert https://github.com/canonical/ubuntu-com-security-api/pull/159
- View the site locally in your web browser at: https://ubuntu-com-13992.demos.haus/security/notices/rss.xml
- See that recent (25th June) notices are shown
Fixes https://warthogs.atlassian.net/browse/WD-12492, https://github.com/canonical/ubuntu.com/issues/13983

Reinstate notice order param

---

releases.yaml
templates/download/raspberry-pi/index.html

- Applied updates as per [doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit)
- View the site locally in your web browser at: https://ubuntu-com-13986.demos.haus/download/raspberry-pi
- Click on the relevant download CTA and see that the correct version is downloaded
Fixes https://warthogs.atlassian.net/browse/WD-12461

Update /download/raspberry-pi copy and Core 24 checksums

---

static/js/src/advantage/subscribe/checkout/app.tsx
static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.test.tsx
static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
static/js/src/advantage/subscribe/checkout/utils/types.ts
templates/credentials/redeem_with_form.html
templates/credentials/shop/index.html
webapp/app.py
webapp/shop/advantage/views.py
webapp/shop/api/credly/api.py
webapp/shop/api/ua_contracts/api.py
webapp/shop/api/ua_contracts/models.py
webapp/shop/api/ua_contracts/schema.py
webapp/shop/cred/exams.json
webapp/shop/cred/views.py
webapp/shop/schemas.py

- Credentials now uses coupons to make the products freely available to everyone instead of a 0 price product
- visit /credentials/shop
- Purchase an exam
- Exam should be priced at 0 and should be purchased successfully
- visit /credentials/redeem
- Redeem enter an activation key
- See that the dropdown is populated with valid exam products
- Redeem the key
- Check if exam is redeemed and visible in `/credentials/your-exams`  
Fixes #WD-12322 …

Wd 12322 modify credentials shop to use the new products and coupons

---

webapp/views.py

- Some countries are missing timezone values, but they have country aliases that has the same timezone values
- Check if country has missing timezone and get the timezone from their respective aliases
- Added fallback country (GB) for invalid timezone queries
- Check out https://ubuntu-com-14000.demos.haus/
- For valid timezones, check that the country code and country shown is as expected. 
Query:
- `/user-country-tz.json?tz=Asia/Kuala_Lumpur`
- `/user-country-tz.json?tz=America/Mendoza`
- For invalid timezones, the fallback value should be **{ "country": "United Kingdom",  "country_code": "GB" }**.
Query:
- `/user-country-tz.json?tz=Etc/GMT-8`
- `/user-country-tz.json?tz=test`
Fixes [WD-12073](https://warthogs.atlassian.net/browse/WD-12073) …

Fix missing timezone errors

---

static/js/src/cve/cve.js
static/sass/_pattern_cve.scss
templates/security/cve/_cve-table.html

- Apply blur effect and display "Show more packages" only if there are more than 6 packages
- Fix JS errors from missing footer actions by adding a check
- Go to `/security/cves?q=39331`
- Toggle detailed view and see that it works (previous JS errors was preventing this)
- Check that `CVE-2024-39331` detailed view shows without the blur effect and hides "Show more packages" button
Fixes [WD-12714](https://warthogs.atlassian.net/browse/WD-12714)
[WD-12714]: https://warthogs.atlassian.net/browse/WD-12714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix CVE detailed view bug

---

templates/base_index.html

- Updated notification banner copy as per [doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#heading=h.g8inespqhurp)
_Note: Suggested change for "Energise your engineers" is not relevant for this pr_
- View the site locally in your web browser at: https://ubuntu-com-14005.demos.haus/
- See that the banner copy has been updated as requested
Fixes https://warthogs.atlassian.net/browse/WD-12531

Update homepage notification banner

---

templates/download/server/arm.html

- Fix broken link on '/download/server/arm', based on [copydoc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit)
- Go to /download/server/arm
- Compare the changes in the [copydoc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit) to demo
Fixes https://warthogs.atlassian.net/browse/WD-12715

bug: Fix broken link on '/download/server/arm

---

templates/security/cve/_status-fields.html
webapp/security/views.py

- Removed the empty status option which is not needed anymore
- Add missing order param
- View the site locally in your web browser at: https://ubuntu-com-14010.demos.haus/security/cves
- Filter by Ubuntu version and see that the "any" option is just a placeholder
Fixes https://sentry.is.canonical.com/canonical/ubuntu-security/issues/76522/?query=is%3Aunresolved, https://warthogs.atlassian.net/browse/WD-12658

Add missing param and disable empty status option

---

package.json
templates/download/iot/intel-iot.html
yarn.lock

Rebrand intel-iot page.
- [demo link](https://ubuntu-com-13970.demos.haus/download/iot/intel-iot)
- [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- [figma](https://www.figma.com/design/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=1702-5346&m=dev)
- Check that the page is correctly updated according to copy doc and figma
[WD-10435](https://warthogs.atlassian.net/browse/WD-10435)
[WD-10435]: https://warthogs.atlassian.net/browse/WD-10435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-10435 - intel iot page rebrand

---

templates/download/iot/intel-iot.html

Add logo to intel-not page
- [demo link](https://ubuntu-com-14015.demos.haus/download/iot/intel-iot)
- [figma](https://www.figma.com/design/cVGimTPHky4h3BPXfrT6GB/24.04-U.com---download-(rebranding)?node-id=1693-6726&t=z6oMayhly8e9P4zj-0)
- Check that the logo is correctly added
[WD-12783](https://warthogs.atlassian.net/browse/WD-12783)
[WD-12783]: https://warthogs.atlassian.net/browse/WD-12783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12783 - add intel logo to intel-iot page

---

templates/ai/what-is-kubeflow.html

Update link on /what-is-kubeflow
- [demo link](https://ubuntu-com-14023.demos.haus/ai/what-is-kubeflow)
- [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit)
- Check that the link is correct according to copy doc
[WD-12794](https://warthogs.atlassian.net/browse/WD-12794)
[WD-12794]: https://warthogs.atlassian.net/browse/WD-12794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12794 - update link on /what-is-kubeflow

---

templates/16-04/index.html
webapp/app.py
webapp/views.py

- Hard coded USN and CVE numbers for xenial
- Removed recent notices list
- Removed call to notices endpoint from this page
These values have been incorrect for some time and it was decided that we don't really need to show the exact number of USNs that were addressed for this release after the ESM phase, a general value will suffice for the purposes of this page. We also decided to remove the recent notices table so that this page does not need to make a call to the notices endpoint at all.   
- View the site locally in your web browser at: https://ubuntu-com-14026.demos.haus/16-04
- See that the above changes have been made and that remaining links work as expected
Fixes https://github.com/canonical/ubuntu-com-security-api/issues/56, https://warthogs.atlassian.net/browse/WD-12901

Set generic USN and CVE values and remove api call

---

templates/security/cve/_version-and-status-row.html
templates/security/cve/index.html

- Removed default empty values for `version` and `priority` param
- View the site locally in your web browser at: https://ubuntu-com-14027.demos.haus/security/cves
- Click search and see that empty version and priority values are not passed by default and that the CVE list remains unchanged
- Using the form, search for the package "mysql" and see that you get 1359 results
- Do the same thing but for package "ssh" and see that you get 139 results
Fixes https://github.com/canonical/ubuntu.com/issues/14020, https://warthogs.atlassian.net/browse/WD-12819

Remove empty values from CVE filter params

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
webapp/shop/cred/exams.json
webapp/shop/cred/views.py

- Remove card requirement if product value is 0
- Create a new account on Ubuntu One
// Positive QA
- visit /credentials/shop
- Click on buy
- Check that the checkout shows all the values correctly
- Click on Buy Now
-  Verify that the purchase goes through
// Negative QA
- visit /pro/subscribe
- Purchase any product
- Verify the price is right
- Verify that card is required for purchasing
- Verify that the purchase goes through
Fixes #

remove credit card requirement if product price is 0

---

webapp/shop/cred/views.py

- Allow users with non-canonical email domain to view shop
- Sign up with a non canonical.com email domain and visit `credentials/shop`
- You should see products and be able to buy the exam
Fixes [Jira](https://warthogs.atlassian.net/browse/WD-12792)

allow non canonical users to view shop

---

package.json
requirements.txt
yarn.lock

- Bump discourse module 5.6.1
- Vanilla 4.14.0
- Go to https://ubuntu-com-14036.demos.haus/ceph/docs
- Hover over a h2/h3 and see that the [vanilla anchor link](https://vanillaframework.io/docs/patterns/links#anchor-link) style works
- Click the link and see it adds the anchor to the url
Fixes

Bump discourse module 5.6.1 & Vanilla 4.14.0

---

templates/certified/index.html
templates/embedded/index.html

Update 10 to 12 year support on /embedded and /certified pages
- [demo link](https://ubuntu-com-14037.demos.haus/)
- copy doc: [certified](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#heading=h.ml1wyj4mfeh7), [embedded](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit)
- Check that the section is correct according to copy doc
Fixes #13964
[WD-12895](https://warthogs.atlassian.net/browse/WD-12895)
[WD-12895]: https://warthogs.atlassian.net/browse/WD-12895?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12895 - update 10 to 12 years support

---

webapp/shop/cred/views.py

- Remove canonical_staff decorator from thank you view
- Purchase an exam and it should show you thank you page after purchase goes through
Fixes [Jira](https://warthogs.atlassian.net/browse/WD-12985)

remove canonical_staff decorator from thank you page

---

static/sass/_pattern_navigation.scss

Fix search icon position in the nav bar
- [demo link](https://ubuntu-com-14045.demos.haus/)
- Check that the icon is correctly showing
[WD-13010](https://warthogs.atlassian.net/browse/WD-13010)
[WD-13010]: https://warthogs.atlassian.net/browse/WD-13010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13010 - fix search icon on u.com

---

templates/credentials/your-exams.html

- Open NDA form in a new tab
- Upon submitting NDA form and coming back to `your-exams` screen
- It should let user take the exam without asking for NDA again
Fixes [Jira](https://warthogs.atlassian.net/browse/WD-12995)

fix NDA before taking exam

---

.env
konf/site.yaml
webapp/security/api.py
webapp/security/views.py

- Added a redirect for `/security/updates/.*` that sends traffic for usn updates to a dedicated service
- This PR should first be tested on staging, and only after [this](https://github.com/canonical/ubuntu-com-security-api/pull/161) has been merged to staging as well
- Declared the security api url as an env variable
- Check that the demo runs
- After merging to staging, test insertions on `/security/updates/*`
- Test that CVEs and Notices can be accessed on staging.ubuntu.com
Before merging

Redirected usn updates traffic to separate service

---

templates/credentials/exam.html

- Make exam iFrame scrollable for testing in staging
Fixes [Jira](https://warthogs.atlassian.net/browse/WD-13016)

set scrolling to yes for testing

---

static/js/src/advantage/credentials/components/CredExamShop/CredExamShop.tsx
static/js/src/advantage/offers/components/PaymentButton/PaymentButton.test.tsx
static/js/src/advantage/offers/components/PaymentButton/PaymentButton.tsx
static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx
static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx
static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx
static/js/src/advantage/subscribe/blender/components/PaymentButton/PaymentButton.test.tsx
static/js/src/advantage/subscribe/blender/components/PaymentButton/PaymentButton.tsx
static/js/src/advantage/subscribe/checkout/app.tsx
static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
static/js/src/advantage/subscribe/checkout/components/ConfirmAndBuy/ConfirmAndBuy.tsx
static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.test.tsx
static/js/src/advantage/subscribe/checkout/components/FreeTrial/FreeTrial.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
static/js/src/advantage/subscribe/checkout/utils/helpers.ts
static/js/src/advantage/subscribe/checkout/utils/types.ts
static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx

- This PR was part of #13889. I separated one commit into this PR because #13889 is getting larger.
- The `/account/checkout` page seems to be used by both the pro shop and the credential shop, but it also needs to be used for the distributor store as well. Since the distributor store handles multiple products with different quantities, I updated the `shopCheckoutData` to support multiple products on the `/account/checkout` page.
- Ensure purchases in the pro shop and credential shop work properly (Ensure the purchase processes in the pro shop and credential shop are not broken due to this PR)

Update checkout data

---

konf/site.yaml
package.json
templates/security/_notice-brief.html
webapp/security/api.py
webapp/security/views.py

- Should **only** be reviewed after https://github.com/canonical/ubuntu-com-security-api/pull/163 has been merged
- Load notices on the `/security/notices` page from a new datasource `get_page_notice`
- This returns a smaller notice, _without_ the `cves` and `packages` fields which are not required on this page, and have a significant effect on page speed, especially when a `notice` has hundreds of `cves`.
- Check that the demo runs
- Open https://ubuntu-com-14041.demos.haus/security/notices and click through the pagination
- Pages should open quickly without timeouts

Use smaller notices on notices page

---

webapp/shop/cred/views.py

- Remove canonical_staff decorator on shop
- visit `credentials/shop` as non canonical user and the shop should show up

allow non canonical users access to shop

---

templates/security/certifications.html

- Updated logos as per [doc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit)
- View the site locally in your web browser at: https://ubuntu-com-14071.demos.haus/security/certifications
Fixes https://warthogs.atlassian.net/browse/WD-12916

Update logos on /security/certifications 

---

templates/kernel/index.html

- Build new banner for the RTF guide based on [copydoc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit) which is sort of also the design
- Go to https://ubuntu-com-14067.demos.haus/kernel and compare the content against the design
- Make sure the button and image act as links
- Check when using a screen reader the description on the links makes sense
Fixes https://warthogs.atlassian.net/browse/WD-12929

feat(/kernel): Build new banner for the RTF guide

---

templates/credentials/index.html

- Enable purchase button on credentials home page `credentials/`
- Ensure there is a green _Buy an exam now!_ button on home page of credentials

enable buy button on credentials home

---

templates/desktop/wsl/index.html

- Copy doc: https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#
- Go to https://ubuntu-com-14076.demos.haus/desktop/wsl
- Scroll to the bottom and click on "Landscape WSL Integration"
- Check that the redirect link works
Fixes [WD-13258](https://warthogs.atlassian.net/browse/WD-13258)
[WD-13258]: https://warthogs.atlassian.net/browse/WD-13258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update WSL link

---

templates/openstack/consulting.html

- Update new pdf link
- Go to https://ubuntu-com-14077.demos.haus/openstack/consulting
- Click on "Download PCB datasheet" pdf
- Check that the updated pdf link works
Fixes [WD-12099](https://warthogs.atlassian.net/browse/WD-12099)
[WD-12099]: https://warthogs.atlassian.net/browse/WD-12099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update PCB datasheet

---

requirements.txt
tests/test_login.py

- Bumps to the latest version of [flask-base](https://github.com/canonical/canonicalwebteam.flask-base) 2.0.0
Removes 'localhost' ref in some tests - [2.3.3](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-3)
- Go around the pro
Fixes https://warthogs.atlassian.net/browse/WD-13081

chore: Bump flask-base to test Flask 2.3.3

---

.github/workflows/pr.yaml
templates/kubernetes/charmed-k8s.html
templates/kubernetes/compare.html
templates/kubernetes/resources.html

- Fix broken thumbnail link for webinars
- Copy doc https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit
- Go to https://ubuntu-com-14086.demos.haus/kubernetes/resources
- Scroll to the "Videos and Webinars" section
- Check that the "[How to accelerate Kubernetes deployment in the enterprise](https://ubuntu-com-14086.demos.haus/engage/kubernetes-deployment-enterprise-whitepaper)" link opens to its relevant engage page
- Check that all thumbnail images are loaded 
Fixes [WD-13394](https://warthogs.atlassian.net/browse/WD-13394)
[WD-13394]: …

Fix broken thumbnail links

---

navigation.yaml
templates/templates/_footer_item.html

-  In navigation.yaml: Ceph, Server and Kubernetes should remain Canonical Ceph, Ubuntu Server and Canonical Kubernetes, please revert
-  In the footer: Server should be Ubuntu Server, Ceph and Kubernetes are correct.
- Go to /
- Check that footer title links are correct as per comment suggestions
Fixes [WD-13396](https://warthogs.atlassian.net/browse/WD-13396)
[WD-13396]: https://warthogs.atlassian.net/browse/WD-13396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Address UX comments for footer nav

---

meganav.yaml
static/files/sitemap.xml

- Add /pro/devices to sitemap.xml and meganav
- Go to https://ubuntu-com-14091.demos.haus/
- Go to meganav: Products > IoT and Edge
- See that Ubuntu Pro Devices is listed and redirects to /pro/devices correctly
- Check against [meganav copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit#heading=h.56uhd6l1cqzh)
Fixes [WD-13520](https://warthogs.atlassian.net/browse/WD-13520)
[WD-13520]: https://warthogs.atlassian.net/browse/WD-13520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Ubuntu Pro Devices to sitemap and meganav

---

templates/certified/model-details.html

- On "Notes", show line breaks where appropriate. Previously Jinja2 templates ignored the newline symbols.
- Apply djlint formatting on the affected file
- Check out https://ubuntu-com-14094.demos.haus/certified/202307-31886
- Go to https://certification.canonical.com/certificates/2405-15681/
- Check that the "Notes" in demo shows line breaks where the C3 site does
Fixes #13870 and  [WD-11285](https://warthogs.atlassian.net/browse/WD-11285)
[WD-11285]: https://warthogs.atlassian.net/browse/WD-11285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Show line breaks on Certified Hardware pages

---

README.md

- Remove old Ubuntu logo on README.md and replace with plain text "ubuntu.com"
- Remove Cypress test badge
- The Cypress test for forms were removed in this PR #12921 
- Clone this branch
- Preview the README.md locally
- See that it uses the new Canonical Ubuntu logo
- Check that Cypress / main badge is removed
Fixes #12872 and [WD-13489](https://warthogs.atlassian.net/browse/WD-13489)
[WD-13489]: https://warthogs.atlassian.net/browse/WD-13489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Ubuntu logo on README.md and remove test badge

---

templates/legal/font-licence/index.html

- Update list number to match plain text version
- Plain text version: https://assets.ubuntu.com/v1/81e5605d-ubuntu-font-licence-1.0.txt
- Go to https://ubuntu-com-14095.demos.haus/legal/font-licence
- Scroll to `Permissions & Conditions`, check that list numbering (e.g 2.a.i) matches the list numbering in the plain text version
Fixes #14068 and [WD-13146](https://warthogs.atlassian.net/browse/WD-13146)
[WD-13146]: https://warthogs.atlassian.net/browse/WD-13146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update list numbering to match plain text version

---

webapp/shop/cred/views.py

- Fix UAContractsUserHasNoAccount error on credentials shop
- Create a new account
- Try to visit /credentials/shop
- Should not see error
Fixes #WD-13587

Store should check for cube purchase account and not ua purchase account

---

static/js/src/contributions.js

- Recreated #13998 
- Refactored sendContributionFormAnalytics function not to send multiple GAEvent pushes to the dataLayer but to send one push with the data as key-value pairs within that push in order to respect GA4 event parameter data model
- Visit https://ubuntu-com-14030.demos.haus/download/desktop/thank-you?version=24.04&architecture=amd64&lts=true
- Click on contribution with various contribution amount settings (including 0)
- Check the value of the dataLayer array in the console whether the "contribution" event object in the array appears and whether it has the correct data

 GROWENG-3933 refactor dataLayer.push for GA4 structure #13998 

---

templates/security/cve/index.html

- Add description to CVE per copy update request
- https://docs.google.com/document/d/1IJyzz5hi90UJwzJ4zJuVLpLAFEvqgreSAPasJvluaAs/edit
- Note from requester on copy doc forms: Please IGNORE the first suggested edit from Juan, this is an older request from last year. The ONLY requested change to the page is the edit from me below Juan’s.
- Go to https://ubuntu-com-14109.demos.haus/security/cves
- Check that the additional paragraph is added to the CVE description as per copy docs
Fixes [WD-13666](https://warthogs.atlassian.net/browse/WD-13666)
[WD-13666]: …

Add description to CVE

---

templates/templates/_footer_item.html

- Fix broken href links on mobile footer navigation
- Add the paths to their respective hrefs
- Go to https://ubuntu-com-14111.demos.haus/
- Go on mobile view
- Scroll to footer, click on footer links and see that it redirects as expected
Fixes [WD-13667](https://warthogs.atlassian.net/browse/WD-13667)
[WD-13667]: https://warthogs.atlassian.net/browse/WD-13667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add href to mobile footer navigation

---

konf/site.yaml

- Switched the backend for `security/page/notices.json` to the regular security-api backend. 
- This prevents search from competing for resources with regular notices

Redirect page traffic to regular api backend

---

templates/base_index.html

- Changed the logo for google cloud on homepage(ubuntu.com) as part of copyupdate.
- [copydoc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?disco=AAABSVcibVg)
- [Demo](https://ubuntu-com-14119.demos.haus/)
Fixes # [WD-13707](https://warthogs.atlassian.net/browse/WD-13707)
[WD-13707]: https://warthogs.atlassian.net/browse/WD-13707?atlOrigin=eyJpIjoiNWRkNTl …

WD-13707 Changed the logo for google cloud on homepage

---

templates/containers/chiselled/index.html

- Corrected link at /containers/chiselled
- [Copydoc](https://docs.google.com/document/d/1ZkQ-UFTwsPkMnQn8IEEjZOXMy40tkgBscw_-qq9K3nc/edit)
- [Demo](https://ubuntu-com-14118.demos.haus/containers/chiselled)
Fixes # [WD-13710](https://warthogs.atlassian.net/browse/WD-13710)
[WD-13710]: https://warthogs.atlassian.net/browse/WD-13710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13710 Corrected link at /containers/chiselled

---

static/js/src/dynamic-forms.js
templates/shared/forms/interactive/aws.html
templates/shared/forms/interactive/esm.html
templates/shared/forms/interactive/general.html
templates/shared/forms/interactive/landscape.html
templates/shared/forms/interactive/pricing-infra.html
templates/shared/forms/interactive/storage.html

**Note: all affected forms are using the same design as the dynamic form in [pricing-infra.html](https://github.com/canonical/ubuntu.com/blob/f35ba7aa510f5b0bee8ebfa7493f98394656936b/templates/shared/forms/interactive/pricing-infra.html). 
Only difference is the required fields in the contact section thus only QA review is needed** 
- Apply redesign on dynamic forms
- Add fieldset sections that adhere with UX and fix missing payload 
- Make sure that the required fields in the forms are similar to Marketo
- Go to each of the affected forms below
- Fill up the form, submit and check that the payload consolidates form inputs correctly
- Check that the form is submitted to Marketo correctly
Affected forms:
Fixes [WD-13791](https://warthogs.atlassian.net/browse/WD-13791)
[If relevant, please …

Add fieldset sections to fix missing payload on dynamic forms

---

meganav.yaml

-  Added /pro/devices to featured meganav 
- [Copydoc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit)
- [Demo](https://ubuntu-com-14137.demos.haus/)
Fixes # [WD-13803](https://warthogs.atlassian.net/browse/WD-13803)
[WD-13803]: https://warthogs.atlassian.net/browse/WD-13803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

WD-13803 Add /pro/devices to featured meganav

---

navigation.yaml
static/js/src/advantage/distributor/Distributor.tsx
templates/templates/_navigation.html
webapp/app.py

- Update navigation for /pro/distributor pages
- Display Register new deal in a new tab
- Go to /pro/distributor 
- Check navigation items are correct and the urls are working fine. 
- Check Docs, Discourse, and "Register new deal" button opens in an new tab
Fixes #https://warthogs.atlassian.net/browse/WD-13834

WD-13834 update navigation for /pro/distributor pages

---

templates/desktop/flavours.html

- Added screenshot images to asset manager
- Updated img src for each respective flavour 
As part of:
https://warthogs.atlassian.net/browse/DESPM-1969

Update flavour screenshots for Noble release

---

konf/site.yaml

- Use the service `ubuntu-com-security-api-notices` for `/security/notices.json`
- Use the service `ubuntu-com-security-api` for the rest of `/security` endpoints

Use the security notices api service

---

templates/case-studies/base_case-studies.html
templates/case-studies/index.html
templates/case-studies/templates/_macros-text.jinja

- Add macros for text section
- Import macro on index and build an example of the text section with base template
- Go to https://ubuntu-com-14143.demos.haus/case-studies
- See that text section design matches with [Figma](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV/24.10-Case-study-template?node-id=1-716&t=ocgEedog4898THvX-0)
Fixes [WD-13119](https://warthogs.atlassian.net/browse/WD-13119)
[WD-13119]: https://warthogs.atlassian.net/browse/WD-13119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WD-13120]: …

Add macros for text section

---

templates/case-studies/base_case-studies.html
templates/case-studies/index.html
templates/case-studies/templates/_macros-highlights.jinja
templates/case-studies/templates/_macros-text-list.jinja

- Added macros for text + list and highlights section
- Added examples for macros usage
- Go to https://ubuntu-com-14148.demos.haus/case-studies
- See that text + list and highlights section design matches with [Figma](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV/24.10-Case-study-template?node-id=1-716&t=ocgEedog4898THvX-0)
Fixes [WD-13120](https://warthogs.atlassian.net/browse/WD-13120) and [WD-13121](https://warthogs.atlassian.net/browse/WD-13121)
[WD-13120]: https://warthogs.atlassian.net/browse/WD-13120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Add macros for text list and highlights section

---

templates/credentials/faq.html

- Update the FAQ page for Credentials 
- visit [/credentials/faq](https://ubuntu-com-14151.demos.haus/credentials/faq)
- compare with copy doc
Fixes #WD-13922

WD-13922-copy-update-for-faq-page-on-credentials

---

templates/case-studies/index.html
templates/case-studies/templates/_macros-hero.jinja
templates/case-studies/templates/_macros-text-list.jinja
templates/case-studies/templates/_macros-text.jinja

- Add macros for hero section
- Import macro on index and build an example of the hero section with base template
- Go to https://ubuntu-com-14138.demos.haus/case-studies
- See that hero section design matches with [Figma](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV/24.10-Case-study-template?node-id=1-716&t=wlZAf1AkHWJJl0TN-0)
- See if there is any improvements to be done with the macro file: `_macros-hero.jinja` especially for image import. I am limiting the logo size as per the Figma design for now.
Fixes [WD-13118](https://warthogs.atlassian.net/browse/WD-13118)
[WD-13118]: …

Add macros for hero section

---

templates/aws/support.html

- Slightly rebrand /aws/support page according to [Figma design](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=180-2883&t=5odA2wi6MxzUZxQg-0)
- Navigate to https://ubuntu-com-14152.demos.haus/aws/support and check if the page looks like in the design
Fixes https://warthogs.atlassian.net/browse/WD-12845

[WD-12845] rebrand u.com/aws/support

---

templates/kubernetes/_install-linux.html

- Removes `is-dark` class from a div and pre elements to make text visible
No issue created

Removed is-dark class from code block

---

templates/templates/_footer-copyright-and-legal.html

Fix link positions according to the request in the GitHub issue
- [demo link](https://ubuntu-com-14168.demos.haus/)
- Check that the links are on the correct distance from hr
[WD-13675](https://warthogs.atlassian.net/browse/WD-13675)
Fixes #14113 
[WD-13675]: https://warthogs.atlassian.net/browse/WD-13675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13675 - fix links in the footer

---

static/sass/_pattern_lists.scss
templates/azure/ebook/index.html
templates/azure/private-offer.html
templates/azure/shared/_how-ubuntu-pro-helps-you.html

Rebrand /azure/private-offer. No content was changed, layout only
- [demo link](https://ubuntu-com-14156.demos.haus/azure/private-offer)
- [figma](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-Azure-bubble?node-id=1-6057&t=gyQr0wjIOwcXzRPS-0)
[WD-12827](https://warthogs.atlassian.net/browse/WD-12827)
[WD-12827]: https://warthogs.atlassian.net/browse/WD-12827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12827 - rebrand /azure/private-offer

---

navigation.yaml

Added /data-science to /ai navigation
- [demo link](https://ubuntu-com-14170.demos.haus/ai)
- Check that the images data science tab is on navigation
[WD-13371](https://warthogs.atlassian.net/browse/WD-13371)
[WD-13371]: https://warthogs.atlassian.net/browse/WD-13371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-13371 -  add /data-science to navigation

---

meganav.yaml

Remove Ubuntu Pro for devices from navigation
- [demo link](https://ubuntu-com-14171.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit)
- Check that the tab is not shown in navigation
[WD-14066](https://warthogs.atlassian.net/browse/WD-14066)
[WD-14066]: https://warthogs.atlassian.net/browse/WD-14066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14066 - remove pro devices from meganav

---

templates/base_index.html

Updated dell logo on home page
- [demo link](https://ubuntu-com-14172.demos.haus/)
- [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)
- Check that the logo is white
[WD-14096](https://warthogs.atlassian.net/browse/WD-14096)
[WD-14096]: https://warthogs.atlassian.net/browse/WD-14096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14096 - update dell logo on home page

---

static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx

- Added link to [Free Trial Contact Form](https://ubuntu.com/engage/Ubuntu-Pro-1-month-trial) on the Free Trial Available button.
- View the site locally in your web browser at: http://0.0.0.0:8001/pro/subscribe
- Scroll down to the "**Buy Now**" button and click the Free trial available button. You should be redirected to the free trial contact form.
- Try logging out if you can't see the "Free trial available" button.
Fixes [WD-14152](https://warthogs.atlassian.net/browse/WD-14152)
[WD-14152]: …

WD-14152 - Add link to free trial contact form in /pro/subscribe

---

templates/azure/support.html

Rebrand /azure/support. No content was changed, layout only
- [demo link](https://ubuntu-com-14175.demos.haus/azure/support)
- [figma](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=120-4710&t=WOaNUpdi7g9kYqma-0)
[WD-12833](https://warthogs.atlassian.net/browse/WD-12833)
[WD-12833]: https://warthogs.atlassian.net/browse/WD-12833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12833 - rebrand /azure/support

---

webapp/views.py

- Updated engage pages to use new version of `get_index`
https://github.com/canonical/canonicalwebteam.discourse/commit/49eee8f8a4ba2b398667a3623a45763370bd917b
- Open the demo at [https://ubuntu-com-14189.demos.haus/engage/sitemap.xml](https://ubuntu-com-14189.demos.haus/engage/sitemap.xml)
- Also check [https://ubuntu-com-14189.demos.haus/openstack/resources/](https://ubuntu-com-14189.demos.haus/openstack/resources/)
and confirm that there are no 500 errors

Fix engage sitemap 500

---

meganav.yaml

-  Update meganav reference from Multipass to MicroCloud based on [copydoc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit)
- Open [the demo]()
- Open 'products' and then 'featured'
- See 'Multipass' has been removed and 'MicroCloud' is in its place
Fixes https://warthogs.atlassian.net/browse/WD-14183

chore: Update meganav reference from Multipass to MicroCloud

---

templates/azure/ebook/index.html
templates/azure/private-offer.html
templates/azure/shared/_azure-logo-strip.html
templates/azure/shared/_how-ubuntu-pro-helps-you.html

Rebrand /azure/ebook. No content was changed, layout only
- [demo link](https://ubuntu-com-14186.demos.haus/azure/ebook)
- [figma](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-Azure-bubble?node-id=1-2&t=e0pNuFr29DP74s75-0)
[WD-12823](https://warthogs.atlassian.net/browse/WD-12823)
[WD-12823]: https://warthogs.atlassian.net/browse/WD-12823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12823 - rebrand /azure/ebook

---

templates/security/cve/cve.html

- This addresses an issue of CVE pages not having a link back to LSN's
- Loop through notice_ids and if an LSN exists, add it to the list of references
- DJLint
- Go to https://ubuntu-com-14212.demos.haus/security/notices/LSN-0104-1 (or any LSN)
- Scroll down to 'References' and click any internal link, for example https://ubuntu-com-14212.demos.haus/security/CVE-2023-6270
- Again scroll down to 'References' and see there is a link back to the original notices page, https://ubuntu-com-14212.demos.haus/security/notices/LSN-0104-1 
Fixes https://warthogs.atlassian.net/browse/WD-14292

feat: Add lsn notices to list of references

---

static/sass/styles.scss
templates/case-study/example.html
templates/macros/_macros-hero.jinja
templates/macros/_macros-highlights.jinja
templates/macros/_macros-image.jinja
templates/macros/_macros-quote.jinja
templates/macros/_macros-text-list.jinja
templates/macros/_macros-text.jinja

- Use Vanilla defined macros for hero section
- Go to https://ubuntu-com-14166.demos.haus/case-study/example
- [Figma design](https://www.figma.com/design/AeIJ3GsqnJCHtiBYhkTuTV/24.10-Case-study-template?node-id=1-716&t=43Yuf8LEb6wYh1pC-0)
Fixes [WD-14166](https://github.com/canonical/ubuntu.com/pull/14166)
[WD-14166]: https://warthogs.atlassian.net/browse/WD-14166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Align macros usage with Vanilla standards

---

templates/engage/shared/_de_engage_form.html
templates/engage/shared/_en_engage_form.html
templates/engage/shared/_es_engage_form.html
templates/engage/shared/_it_engage_form.html
templates/engage/shared/_pt_engage_form.html
templates/engage/shared/_ru_engage_form.html
templates/engage/shared/_zh-TW_engage_form.html

- Remove "RichText" hidden field on engage forms
- Fix djlint errors throughout the forms
- Go to https://ubuntu-com-14228.demos.haus/engage/iot-management-landscape
- Check that payload does not include "RichText"
Fixes [WD-14468](https://warthogs.atlassian.net/browse/WD-14468)
[WD-14468]: https://warthogs.atlassian.net/browse/WD-14468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove unused fields on engage forms

---

templates/core/services/thank-you.html
templates/core/thank-you.html
templates/shared/_thank_you_footer.html

Rebrand /core and /core/services thank-you pages. No content was changed, layout only
- [demo link](https://ubuntu-com-14232.demos.haus/core/thank-you)
- [figma](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-AWS-bubble?node-id=120-4373&t=Op4AXNfuaK7SqOU2-0)
[WD-12753](https://warthogs.atlassian.net/browse/WD-12753)
[WD-12753]: https://warthogs.atlassian.net/browse/WD-12753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12753 - rebrand /core and /core/services thank-you pages

---

templates/download/risc-v/allwinner-nezha.html
templates/download/risc-v/microchip-curiosity.html
templates/download/risc-v/microchip-polarfire.html
templates/download/risc-v/milk-v-mars.html
templates/download/risc-v/qemu-emulator.html
templates/download/risc-v/sifive-unmatched.html
templates/download/risc-v/sipeed-licheerv.html
templates/download/risc-v/starfive-visionfive.html

- Updates links for downloading Ubuntu 24.04.1 image for Risc-V
Navigate to https://ubuntu-com-14245.demos.haus/download/risc-v and check that it downloads new images for Ubuntu 24.04.1
Fixes https://warthogs.atlassian.net/browse/WD-14593

[WD-14593] update download links for Risc-V for 24.04.1

---

templates/core/features/full-disk-encryption.html

Rebrand /core/features/full-disk-encryption page. No content was changed, layout only
- [demo link](https://ubuntu-com-14239.demos.haus/core/features/full-disk-encryption)
- [figma](https://www.figma.com/design/5kDdBtPRqthyPz263YV91U/24.04-Ubuntu-Core-rebrand?node-id=1970-4967&t=6F9qsf1L0Y031BcA-0)
[WD-12747](https://warthogs.atlassian.net/browse/WD-12747)
[WD-12747]: https://warthogs.atlassian.net/browse/WD-12747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12747 - rebrand /core/features/full-disk-encryption

---

templates/core/features/recovery.html

Rebrand /core/features/recovery page. No content was changed, layout only
- [demo link](https://ubuntu-com-14238.demos.haus/core/features/recovery)
- [figma](https://www.figma.com/design/5kDdBtPRqthyPz263YV91U/24.04-Ubuntu-Core-rebrand?node-id=2005-3267&t=6F9qsf1L0Y031BcA-0)
[WD-12749](https://warthogs.atlassian.net/browse/WD-12749)
[WD-12749]: https://warthogs.atlassian.net/browse/WD-12749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12749 - rebrand /core/reatures/recovery

---

templates/core/features/secure-boot.html

Rebrand/core/features/secure-boot. No content was changed, layout only
- [demo link](https://ubuntu-com-14231.demos.haus/corr/features/secure-boot)
- [figma](https://www.figma.com/design/5kDdBtPRqthyPz263YV91U/24.04-Ubuntu-Core-rebrand?node-id=2059-5756&t=U9LzuKHiOBXHYUmO-0)
[WD-12751](https://warthogs.atlassian.net/browse/WD-12751)
[WD-12751]: https://warthogs.atlassian.net/browse/WD-12751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12751 - rebrand /core/features/secure-boot

---

templates/core/features/full-disk-encryption.html
templates/core/features/ota-updates.html

Rebrand /core/features/ota-updates page. No content was changed, layout only
- [demo link](https://ubuntu-com-14237.demos.haus/core/features/ota-updates)
- [figma](https://www.figma.com/design/5kDdBtPRqthyPz263YV91U/24.04-Ubuntu-Core-rebrand?node-id=1988-6058&t=PydHk0u9B31FTQKp-0)
[WD-12745](https://warthogs.atlassian.net/browse/WD-12745)
[WD-12745]: https://warthogs.atlassian.net/browse/WD-12745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12745 - rebrand /core/features/ota-updates

---

templates/download/risc-v/qemu-emulator.html

- Updated link as per [doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit)
- View the site locally in your web browser at: https://ubuntu-com-14250.demos.haus/download/risc-v and click on the QEMU emulator tab
- Check that the update was made
Fixes https://warthogs.atlassian.net/browse/WD-14459

copy update: Update /download/risc-v download link

---

templates/engage/base.html
webapp/views.py

- Add "Related posts" section to individual engage pages
- Allows stakeholders to choose top 3 posts to show in the related section
- Added `related_urls` field to the [engage template](https://discourse.ubuntu.com/c/design/engage-pages/51) on discourse.u.com 
- Go to https://ubuntu-com-14246.demos.haus/engage/azure-ubuntu-pro-fips-whitepaper
- Scroll down to see the "Related Posts" section
- Check that it is similar to the `related_urls` added to the [discourse post](https://discourse.ubuntu.com/t/staying-compliant-while-delivering-innovation-in-government-services/19960)
- Related Posts section only shows when stakeholders add `related_urls`, otherwise the section will not exist
Fixes [WD-13259](https://warthogs.atlassian.net/browse/WD-13259) …

Reinstate related engage pages

---

templates/engage/base.html

- Change related engage pages section to "Additional Resources"
- Requested from https://warthogs.atlassian.net/browse/WD-13259?focusedCommentId=564853
- Go to https://ubuntu-com-14260.demos.haus/engage/azure-ubuntu-pro-fips-whitepaper
- See that the bottom section name is changed to "Additional Resources"
Fixes #

Update engage page section name

---

templates/gcp/fips.html

Rebrand  /gcp/fips. No content was changed, layout only
- [demo link](https://ubuntu-com-14249.demos.haus/gcp/fips)
- [figma](https://www.figma.com/design/vz3yAG1nYI7r5gc3SpTUOw/ubuntu.com%2Fgcp%2Ffips?node-id=1-3103&node-type=FRAME&t=p9GnMvla4VmAGUIl-0)
[WD-12853](https://warthogs.atlassian.net/browse/WD-12853)
[WD-12853]: https://warthogs.atlassian.net/browse/WD-12853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12853 - rebrand /gcp/fips

---

templates/templates/base.html

- I have updated the inline font references to match those in Vanilla and removed the preload attribute from lesser used font types (greek, cryllic)
- Go https://ubuntu-com-14216.demos.haus/ to and see there are no font related errors in the console
Fixes https://warthogs.atlassian.net/browse/WD-14349
https://github.com/canonical/ubuntu.com/issues/10312

chore: Update to use dynamic fonts and don't preload fonts

---

templates/support/community-support.html

- Removed stale link (see discussion in ticket) and updated the [doc](https://docs.google.com/document/d/1vrnljXUx71ZZhz3cQ6NupUNw6yNqW2OWkyY8Ozx2bqw/edit) to reflect the change 
- Ran djlint
- View the site locally in your web browser at: https://ubuntu-com-14256.demos.haus/support/community-support
- See that the link has been removed 
Fixes https://github.com/canonical/ubuntu.com/issues/13655, https://warthogs.atlassian.net/browse/WD-9502

Remove stale link at /community/community-support

---

templates/engage/base.html

- Add optional CTA button on engage page banners
- Go to [engage page template](https://discourse.canonical.com/t/engage-pages-and-takeovers-v2/358) on discourse
- Check that the `show_cta_on_banner` doc is added 
- Create a "New Topic" on discourse engage pages [here](https://discourse.ubuntu.com/c/design/engage-pages/51)
- See that `show_cta_on_banner` shows up on the template
- Go to https://ubuntu-com-14252.demos.haus/engage/microk8s-nvidia-tech-stack
- See that the primary CTA button shows up on banner and that the [original discourse post](https://discourse.ubuntu.com/t/simplifying-kubernetes-across-the-clouds/22260) sets `show_cta_on_banner` to true
- Go to https://ubuntu-com-14252.demos.haus/engage/redhat-openstack-comparison-whitepaper
- See that the primary CTA button doesnt …

Add optional CTA button for engage pages

---

navigation.yaml
webapp/app.py

- Add invoice menu in the navigation
- Check Invoice exist in the navigation and the page shows properly on `/pro/distributor/invoice`
Fixes #https://warthogs.atlassian.net/browse/WD-14641?atlOrigin=eyJpIjoiODUxNDhhM2I5YjE1NDM5OWEzNzljNmU4ZWEyNjA0MjEiLCJwIjoiaiJ9

Add invoice menu in the navigation

---

static/js/src/dynamic-forms.js
templates/shared/forms/interactive/ai.html
templates/shared/forms/interactive/kafka.html

- Previously `commentsFromLead` wasn't being added to the payload
- Added a check to add `commentsFromLead` to payload if value isn't empty
- Run linter on `/templates/shared/forms/interactive/kafka.html`
- Go to https://ubuntu-com-14259.demos.haus/managed/apps/kafka
- Click on the `Get in touch` button
- Fill up forms and submit
- Check that the `Comments_from_lead__C` in payload isn't empty
- Check that the submission went through Marketo successfully
Fixes [WD-14649](https://warthogs.atlassian.net/browse/WD-14649)
[WD-14649]: https://warthogs.atlassian.net/browse/WD-14649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

Include comments message in payload

---

static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx

- Remove preview call from the purchase hook
- Need to make sure purchases are working properly in all checkout (pro, credentials, distributor) 
Fixes #https://warthogs.atlassian.net/browse/WD-14644

Remove preview call from the purchase hook

---

static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/AdditionalNotes/AdditionalNotes.tsx
static/js/src/advantage/subscribe/checkout/components/AdditionalNotes/index.ts
static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
static/js/src/advantage/subscribe/checkout/utils/types.ts
static/sass/_pattern_checkout.scss

- Add PO number in the checkout
- Initiate an order
- Go to checkout 
- Check Additional notes section shows in the step 4 
- Additional notes should show only in the distributor store checkout
Fixes #https://warthogs.atlassian.net/browse/WD-14642?atlOrigin=eyJpIjoiNGQyYTgxOTlhYTgyNDNkNDkxZmY4OGZmZjY0ZmYwODciLCJwIjoiaiJ9

Add PO number in the checkout

---

static/js/src/dynamic-forms.js
templates/shared/forms/interactive/real-time.html

- Remove name attributes on fields that do not need to be included in the payload
- Add js-formfield to sections that need to be consolidated into `Comments_from_lead__c`
- Go to https://ubuntu-com-14253.demos.haus/real-time
- Click on `Get in touch` to invoke the contact modal
- Submit the form, check that the radio items are under `Comments_from_lead__c` with the field title and value
- Check on marketo that the form submits as expected
Fixes [WD-14614](https://warthogs.atlassian.net/browse/WD-14614)
[WD-14614]: https://warthogs.atlassian.net/browse/WD-14614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …

Fix /real-time dynamic forms

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/utils/helpers.ts

- Prevent user navigation on checkout page.
- Go to https://ubuntu-com-14273.demos.haus/pro/subscribe
- Scroll to the bottom and click on the **Buy now** button
- Fill in the form and click the **Buy now** button
- Reload the page after you see the loading icon on the button
- Check if you get a confirmation alert
Fixes [WD-14757](https://warthogs.atlassian.net/browse/WD-14757)
[WD-14757]: https://warthogs.atlassian.net/browse/WD-14757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-14757] Prevent user navigation on checkout page

---

static/js/src/navigation.js
static/sass/_pattern_navigation.scss

*note: this is very much a hack to make it work. The actual fix is to migrate to using the Vanilla patterns we recently developed and are using on c.com. But this will take a long time*
- Adjusts CSS and JS to allow the search to be visible when triggered.
- open [the demo](https://ubuntu-com-14285.demos.haus/) on medium/small screen size
- Click the search icon, the search bar should appear
- Open [the demo in a bubble page](https://ubuntu-com-14285.demos.haus/desktop)
- repeat above process
Fixes https://warthogs.atlassian.net/browse/WD-14826
https://github.com/canonical/ubuntu.com/issues/14282

fix: Show search on search icon click on medium and small screens

---

static/files/sitemap.xml

- Add the new [/20years](https://ubuntu.com/20years) page to the [sitemap](https://ubuntu.com/static/files/sitemap.xml)
- Open the sitemap
- Check the new page exists

fix(20years): Add the new page to the sitemap

---

webapp/views.py

- Fixes this Sentry error https://sentry.is.canonical.com/canonical/ubuntu-com/issues/86589/events/5125836/
- Sets the fallback acquisition_url to https://ubuntu.com
Fixes [WD-14683](https://warthogs.atlassian.net/browse/WD-14683)
[WD-14683]: https://warthogs.atlassian.net/browse/WD-14683?atlOrigin=eyJpIjoiNWRkN …

Add fallback URL for referrer

---

releases.yaml

Not ready yet, but staged all the checksums.
Fixes #

Prepare for 22.04.5

---

templates/aws/outposts.html

Rebrand  /aws/outposts.
- [demo link](https://ubuntu-com-14276.demos.haus/aws/outposts)
- [copy doc](https://docs.google.com/document/d/1aXtrGHw7AcZ_qrov3kJahRtgsmbNx7eH5aWFlIySpfE/edit)
- [figma](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-ubuntu.com%2Faws?node-id=292-4378&node-type=CANVAS&t=x3XTatpQwVH96832-0)
- Check that the page is correct according to figma and copy doc
[WD-12841](https://warthogs.atlassian.net/browse/WD-12841)
[WD-12841]: https://warthogs.atlassian.net/browse/WD-12841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-12841 - rebrand /aws/outposts

---

releases.yaml
templates/download/raspberry-pi/index.html

- Added download section for Ubuntu 24.10 to [/download/raspberry-pi](https://ubuntu-com-14290.demos.haus/download/raspberry-pi) page (click link for a demo)
- Open this: [demo page](https://ubuntu-com-14290.demos.haus/download/raspberry-pi)
- Check that the changes in the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit) are implemented
Fixes [WD-14863](https://warthogs.atlassian.net/browse/WD-14863) …

Update ubuntu.com/download/raspberry-pi with 24.10 download section [WD-14863]

---

static/sass/_pattern_navigation.scss

Fix "Account" dropdown on nav to be aligned with the button
- [demo link](https://ubuntu-com-14313.demos.haus/)
- Check that the dropdown is aligned with the button
[WD-14746](https://warthogs.atlassian.net/browse/WD-14746)
[WD-14746]: https://warthogs.atlassian.net/browse/WD-14746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14746 - fix account nav item to be aligned

---

requirements.txt
webapp/app.py

- Upgrade canonicalwebteam.search to 2.1.1
- Removed the custom `request_limit` configurations. These are now handled by the search module
- Go to https://ubuntu-com-14314.demos.haus/
- Search something
- See rate limit is hit (currently set to 1, so you can search 1 time before hitting it)
**Note:** In some cases you get an extra search. So you will be able to search 2 times before hitting the rate limit of 1 per day. However, in our current use case of the rate limiter this is not a problem, so can be ignored.
Fixes https://warthogs.atlassian.net/browse/WD-15010

chore: Upgrade canonicalwebteam.search to 2.1.1

---

templates/gcp/index.html

- Update LTS links for /gcp
- Go to https://ubuntu-com-14317.demos.haus/gcp
- Check that the LTS links are all available and matches with the new links provided in [copy doc](https://docs.google.com/document/d/1Gvt9tNFDZkqkBcP0k79C6ueTJCmNZvwoXQoU19WEa8E/edit)
Fixes #

Update LTS links for /gcp

---

templates/ai/what-is-kubeflow.html

Changed links according to copy doc
- [demo link](https://ubuntu-com-14305.demos.haus/ai/what-is-kubeflow)
- [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?pli=1)
- Check that the page is correct according to copy doc
[WD-14962](https://warthogs.atlassian.net/browse/WD-14962)
[WD-14962]: https://warthogs.atlassian.net/browse/WD-14962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14962 - update links on /what-is-kubeflow

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx

- disable buy button while loading and also loading should show as soon as button is clicked
- Visit /pro/subscribe
- Select any product and proceed to checkout
- Fill in details 
- Open the network tab in Inspect panel
- Double click on the buy button
- It should send only one purchase request in the background
- The buy button should be disabled while the request is processing
- Try the same steps in /credentials/shop
- Also try to make errors and check the buy button recovers from the errors and is not stuck in loading state. 
Fixes …

disable button while loading

---

templates/templates/base.html

- Check markup of any website on ubuntu.com and check if lang attribute is correctly set and valid.
Fixes #

fix(a11y): Fix broken lang attribute

---

templates/security/cves/cve.html

- Reinstated status description for "ignored" statuses
- Hid releases switch and removed notification for CVEs with no unmaintained releases
- https://ubuntu-com-14329.demos.haus/security/CVE-2024-7254 and see that the "Show unmaintained releases" and corresponding notification has been removed (compared against [prod](https://ubuntu.com/security/CVE-2024-7254) )
- https://ubuntu-com-14329.demos.haus/security/CVE-2024-38630 and see that the status description is rendered next to "ignored" statuses (compared against [prod](https://ubuntu.com/security/CVE-2024-38630))
Fixes # https://warthogs.atlassian.net/browse/WD-14901, https://warthogs.atlassian.net/browse/WD-14911

bug: fix missing status description for ignored status and update switch functionality  

---

static/js/src/chart-data.js
templates/about/release_cycles/k8s-eol.html

- Updates kubernetes release chart and table to include 1.31 and remove 1.25
- Navigate to https://ubuntu.com/about/release-cycle#canonical-kubernetes-release-cycle and check that the table and chart are updated
Fixes #

WD-14967: updates kubernetes release chart and table

---

static/js/src/chart-data.js
templates/shared/_kernel-release-diagram.html

- [Copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#heading=h.yy70h36s0ivx) - **this PR only includes the changes for [Ubuntu kernel tab](https://ubuntu-com-14337.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle)**
- Updates kernel support graph and table according to [this sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit?gid=550510389#gid=550510389)
- Also removes kernel version 6.5 as it is no longer supported
- Check that the dates, kernel versions and Ubuntu versions on the graph and table match those in the spreadsheet
Fixes [WD-15102](https://warthogs.atlassian.net/browse/WD-15102)
[WD-15102]: https://warthogs.atlassian.net/browse/WD-15102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

copy update: kernel support

---

webapp/shop/api/ua_contracts/api.py

- Simple endpoint method change
- Purchase an exam at /credentials/shop
- Schedule exam
- Scheduling should work normally
Fixes #

change get to post for schedule api endpoint

---

templates/containers/chiselled/dotnet.html

- UI overlap buxfix
- [Demo](https://ubuntu-com-14345.demos.haus/containers/chiselled/dotnet)
Fixes # [WD-15300](https://warthogs.atlassian.net/browse/WD-15300)
Previously
Fixed
[WD-15300]: https://warthogs.atlassian.net/browse/WD-15300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-15300 ui overlap fix and minor upgrades

---

static/js/src/main.js
static/js/src/search.js
templates/search.html
templates/templates/_navigation.html

This work aims to add a basic honeypot field to our search to catch automated attacks
- Adds a honeypot input field to the navigation search form and search.html search form
- Creates search.js, a script responsible for catching and redirecting submission to the honey pot field. This is made globally available through main.js
The follow QA steps should be complete for the navigation search & the search found under /search
- Make a regular search submission and see everything goes through as normal and the is only one query string present in the url `q=`
- Using the inspection tool, find the honey pot field. It is an input with the name 'search'. Add something to the value of this field.
- Add a value to the regular search field (this is required) and submit
- You should be redirected to …

feat: Implement a honeypot field on our main search

---

templates/download/server/download.html
templates/download/server/thank-you.html

- Added link to download the CLI Cheat sheet for server thank-you page.
- [Demo](https://ubuntu-com-14352.demos.haus/download/server/thank-you)
Fixes #14333 
Issue [WD-15253](https://warthogs.atlassian.net/browse/WD-15253?atlOrigin=eyJpIjoiNTM1ZmQyOGRhZTM0NDVjNTllODkxMWQzNDkwYzZhN2UiLCJwIjoiaiJ9)
[WD-15253]: https://warthogs.atlassian.net/browse/WD-15253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …

WD-15253 fix the download cheat sheet

---

redirects.yaml

- shortned URL for blogpost
- Check if https://ubuntu-com-14354.demos.haus/blog/cups-remote-code-execution redirects to https://ubuntu-com-14354.demos.haus/blog/cups-remote-code-execution-vulnerability-fix-available 
Fixes # [WD-5383](https://warthogs.atlassian.net/browse/WD-15383)
[WD-5383]: https://warthogs.atlassian.net/browse/WD-5383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-15383 shortned URL for blogpost

---

static/js/src/chart-data.js
templates/about/release_cycles/releases-table.html

- This replaces the passed interim release 23.10 with the new release 24.10 on the Ubuntu releases graph and table
- Navigate to https://ubuntu-com-14360.demos.haus/about/release-cycle#ubuntu
- Check that the new interim Ubuntu release (24.10) is in the chart and the table and that the old interim release has been removed
- Ensure all details are correct (release dates and spelling)
- [WD-14869](https://warthogs.atlassian.net/browse/WD-14869)
Before:
After:
[WD-14869]: https://warthogs.atlassian.net/browse/WD-14869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-14869 - Add new interim release 24.10 and discard 23.10

---

templates/pricing/index.html

- Rebrand to match the [figma design](https://www.figma.com/design/vxxQijDub9nQrU3ZAYcXri/Pricing?node-id=0-1&node-type=canvas&t=d56gqalDTAh6lMNY-0)
- Although this is not supposed to update the content, I noticed one change was missing. 'Storage' > 'Ceph and Swift Storage'. I have highlighted it in the [copydoc](https://docs.google.com/document/d/1iOM6oBqsTkptsst3yG-U3sGaYLQqs27go_8yJQdhMBE/edit#heading=h.8p0ngpm6ijf0)
- Added `aria-labels` to links
- Removed marketo forms setup as it was not needed
- Go to [the demo link](https://ubuntu-com-14328.demos.haus/pricing)
- Compare against the design
- Test the content works on all screen sizes
- Test the links with a screen reader
Fixes https://warthogs.atlassian.net/browse/WD-12860

refactor: Rebrand /pricing

---

static/js/src/advantage/distributor/components/DistributorShopForm/DistributorShopForm.tsx
static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx
static/js/src/advantage/subscribe/react/components/Form/Form.tsx
static/sass/_pattern_distributor.scss
static/sass/_pattern_subscribe.scss

There was an issue with `@extend p-heading--2` with the pro bubbles  ( more info at this thread https://chat.canonical.com/canonical/channels/vanilla/ieodmzrrwbnazy4oi4q8yj3y6o )
- Remove `.product-selector h2` in `_pattern_subscribe.scss` and `_pattern_distributor.scss`
- Replace counter with vanila's vertical-stepped lists
- Go to https://ubuntu-com-14373.demos.haus/pro/subscribe and https://ubuntu-com-14373.demos.haus/pro/distributor/shop
- The pages look the same as they did before, even after the changes
Fixes #https://warthogs.atlassian.net/browse/WD-12509

WD-12509 Remove @extend p-heading--2 on the pro shops

---

templates/blog/article.html

Fix notice in old blog posts so it reads "years" instead of "year s"
Demo: https://ubuntu-com-14380.demos.haus/blog/ubuntu-20-04-survey-results
Fixes WD-15536

WD-15536 Remove space from old blog posts' notice

---

static/js/src/tabbed-content.js
templates/download/desktop/index.html
templates/download/shared/_more-from-canonical.html
templates/download/shared/_secure-enterprise-management.html

Update ubuntu.com/download/desktop with 24.10 download section.
- View the site locally in your web browser at: https://ubuntu-com-14350.demos.haus/download/desktop and check against [copy doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit)
Fixes [#WD-14861](https://warthogs.atlassian.net/browse/WD-14861)

Update ubuntu.com/download/desktop with 24.10 download section. WD-14861

---

templates/kubernetes/docs/quickstart.md

- Fixes a simple typo in the command for installing Juju 

Fix typo in Juju command

---

templates/credentials/index.html

- Fix the link for Get Certification button
- Make sure Get Certification button takes user to shop

Fix link in credentials index.html

---

templates/download/risc-v/allwinner-nezha.html
templates/download/risc-v/microchip-curiosity.html
templates/download/risc-v/microchip-polarfire.html
templates/download/risc-v/milk-v-mars.html
templates/download/risc-v/qemu-emulator.html
templates/download/risc-v/sifive-unmatched.html
templates/download/risc-v/sipeed-licheerv.html
templates/download/risc-v/starfive-visionfive.html

- Updates ubuntu.com/download/risc-v with secondary 24.10 download options
- View the site locally in your web browser at: http://0.0.0.0:8001/download/risc-v
- Check that the links are correct for each board

WD-14867: adds secondary download links

---

templates/pro/devices.html

- Update page based on [copy doc](https://docs.google.com/document/d/1i_3nPkSpCQJ4jfOwN380sdfuTxaiDuDIgDfk01wVPqo/edit)
- Go to https://ubuntu-com-14379.demos.haus/pro/devices
- Check that content matches copy doc
Fixes [WD-15475](https://warthogs.atlassian.net/browse/WD-15475)
[WD-15475]: https://warthogs.atlassian.net/browse/WD-15475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Apply copy update for /pro/devices

---

static/files/sitemap.xml
templates/azure/confidential-computing.html

Add new /azure/confidential-computing page according to the copy doc and figma
- [demo link](https://ubuntu-com-14365.demos.haus/azure/confidential-computing)
- [copy doc](https://docs.google.com/document/d/1sVaQQlm6LHyRf-Q3VSVTmqGRi0SV7gwBVczCTPWq3CE/edit#heading=h.3hmfjtayfrqm)
- [figma](https://www.figma.com/design/MinLlXouBnEDqaoAL3bTWC/24.10-ubuntu.com%2Fazure?node-id=543-1498&node-type=frame&t=GMkgEW8xbup8LJql-0)
- Check the site on the demo
- Check that the page is correct according to copy doc and figma
[WD-14793](https://warthogs.atlassian.net/browse/WD-14793)
[WD-14793]: https://warthogs.atlassian.net/browse/WD-14793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …

WD-14793 - add new /azure/confidential-computing page

---

static/js/src/prepare-form-inputs.js
templates/pricing/contact-us.html
templates/shared/_default-contact-us-form.html

- Create a contact-us form, this uses the default form template
- Check [the form](https://ubuntu-com-14387.demos.haus/pricing/contact-us) submits and goes to the same place as the other pricing contact us forms
Fixes https://warthogs.atlassian.net/browse/WD-15540 

feat: Create /pricing/contact-us

---

templates/desktop/flavours.html

- added 24.10 edubuntu image on `/desktop/flavours`
- Go to https://ubuntu-com-14396.demos.haus/desktop/flavours 
- Check if the new 24.10 image from the [copy doc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit) is updated
Fixes #https://warthogs.atlassian.net/browse/WD-14870

chore: add 24.10 edubuntu image on /desktop/flavours

---

templates/credentials/schedule.html
templates/credentials/shop/index.html
webapp/shop/cred/exams.json
webapp/shop/cred/views.py

- Remove coupon for CUE.01 Linux exam
- Go to /credentials/shop
- Price should be 100$
- proceed to checkout. 
- The price should be 100$ everywhere. VAT is yet to be determined.
Fixes [#WD-15553](https://warthogs.atlassian.net/browse/WD-15553)

remove coupon and discount for cred exams

---

templates/summit/index.html

Update speaker list section with current session information and associated links.
- Updated multiple featured speaker affiliation, name, photo and associated links.
- Changed "Full speaker list" link to "Full timetable" now that it's published.
Fixes # CT-1214

Update speaker list section

---

templates/desktop/flavours.html

- replaced ubuntu desktop flavours images on `/desktop/flavours`
- Go to https://ubuntu-com-14400.demos.haus/desktop/flavours
- Check if the images from [copy doc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit) are updated correctly
- **note**: `Edubuntu` image update is done in another PR.
Fixes #https://warthogs.atlassian.net/browse/WD-14870

chore: add desktop flavours images on /desktop/flavours

---

templates/security/livepatch.html

- Added section per [doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit?tab=t.0) and [design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/24.10-Ubuntu.com%2Fsecurity?node-id=74-44&node-type=canvas&t=1ou0VCTDq0kWJVTp-0)
- View the site locally in your web browser at: https://ubuntu-com-14402.demos.haus/livepatch
Fixes https://warthogs.atlassian.net/browse/WD-15117

feat: add resources section for /security/livepatch

---

templates/containers/index.html

- Fix suru section by importing the suru from Vanilla directly
- Update `p-rule` usage
- Go to https://ubuntu-com-14404.demos.haus/containers
- Check that the suru is showing in hero and does not have scroll behaviour
- Scroll down and check that sections do not overlap with one another
Fixes [WD-15771](https://warthogs.atlassian.net/browse/WD-15771)
[WD-15771]: https://warthogs.atlassian.net/browse/WD-15771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix broken sections in /containers

---

templates/summit/index.html

- Use [canonicalwebteam.image-template](https://github.com/canonical/canonicalwebteam.image-template) to optimise the images.
- Converted incompatible images from svg format to png. See https://github.com/canonical/canonicalwebteam.image-template/issues/4
- Check if all images are rendering well and there are no bottlenecks.
Ref #14316 

fix: Optimize summit website images

---

templates/download/risc-v/sifive-unmatched.html
templates/download/risc-v/starfive-visionfive.html
templates/download/server/manual.html

- Applied fixes for issues flagged in this [thread](https://chat.canonical.com/canonical/pl/nboi8oorkbb8dpe8z3u5djsdacc)
- View the site locally in your web browser at: https://ubuntu-com-14408.demos.haus/download/server and see that release notes links point to the correct url
- View the site locally in your web browser at: https://ubuntu-com-14408.demos.haus/download/risc-v and see that unmatched tab and starfive 2 tab have the correct links for 24/10
Fixes #

Release fixes

---

templates/certified/index.html
templates/certified/why-certify.html

- Add buttons on `templates/certified/index.html` and `templates/certified/why-certify.html` to direct users to the certification programme documentation on the certification website (https://certification.canonical.com/)
- (Drive-by) fix typo
Fixes #[CDOC-154](https://warthogs.atlassian.net/browse/CDOC-154)
* URL: http://0.0.0.0:8001/certified
* URL: http://0.0.0.0:8001/certified/why-certify …

Add links to certification programme docs on Certified page

---

templates/download/desktop/index.html
templates/download/risc-v/sifive-unmatched.html
templates/download/server/manual.html

- Fix type on /download/desktop/thank-you and /download/server/thank-you
- Fix link on /download/risc-v

fix typos on download thank-you pages, fix link on risc-v page

---

templates/download/server/arm.html

- Fix the link for 64k 24.10 ARM image
- Download 64k 24.10 ARM image on /download/arm and check if it downloads an image

fix the link for 64k 24.10 arm image

---

static/js/src/advantage/users/utils.ts

- Remove upper limit in email validation for `/pro/users`
- Go to [/pro/users](https://ubuntu-com-14414.demos.haus/pro/users)
- Try adding a new user with the email `test@long-domain.global`
- The user should be successfully added
Fixes [WD-15818](https://warthogs.atlassian.net/browse/WD-15818)
Before:
After:
[WD-15818]: https://warthogs.atlassian.net/browse/WD-15818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-15818] Email address rejected when trying to add users via the Pro dashboard

---

templates/training/index.html

- Add a new Mongo DB section to `/training`
- View the site locally in your web browser at: http://0.0.0.0:8001/ (or open demo)
- Go to http://0.0.0.0:8001/training
- Check that the new Mongo DB section is there and it matches the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit?tab=t.0)
https://warthogs.atlassian.net/browse/WD-15792

/training copy update

---

templates/kernel/index.html

- Updated link https://people.canonical.com/~ubuntu-security/priority.html -> https://ubuntu.com/security/cves/about#priority as per linked ticket (I searched the codebase and this seems to be the only instance)
- View the site locally in your web browser at: https://ubuntu-com-14415.demos.haus/kernel
- Scroll to the "Kernel security" section and see that the "high and critical" link routes correctly 
Fixes https://warthogs.atlassian.net/browse/WD-2706

/kernel copy update

---

templates/about/release_cycles/releases-table.html

- Removed "LTS" from "24.10 (Oracular Oriole)"
- View the site locally in your web browser at: https://ubuntu-com-14417.demos.haus/about/release-cycle
- See that the typo has been fixed 
Fixes https://github.com/canonical/ubuntu.com/issues/14416

/about/release-cycle copy update

---

requirements.txt

- Bump discourse version to 5.7.3
Fixes #

chore: Bump discourse version to 5.7.3

---

templates/engage/index.html

- When one filter is applied, disable the other field options
- The [data query explorer](https://github.com/canonical/ubuntu.com/blob/3aa78f2090452cde1fd01ca65394f0658b3bad07/templates/engage/index.html#L142) on Discourse is limited to one field filtering at the moment, and the frontend does not reflect that which may confuse users.
- Go to https://ubuntu-com-14444.demos.haus/engage
- Select a filter, check that the other selections are disabled
- Clear filters, and see that all filters are enabled again
Fixes [WD-15843](https://warthogs.atlassian.net/browse/WD-15843)
[WD-15843]: …

Disable multiple fields filtering on engage pages

---

templates/desktop/index.html

Have added the class p-section to both the sections for adding the required padding-bottom of 4rem.
Fixes #14426 

Fixes #14426

---

templates/pricing/devices.html

- Adds a `<hr>` below the images in the section 'Add-ons to board enablement services' as per @mattea-turic's request
- Open the [demo](https://ubuntu-com-14446.demos.haus/pricing/devices)
- Check the bar is visible only on large and medium screens

style: Add highlight bar below images

---

static/js/src/advantage/distributor/DistributorShop.tsx

- Fix a typo on the error page for distributor.

Typo on error page

---

static/js/src/cookie-policy-with-callback.js
templates/templates/_tag_manager.html
templates/templates/base.html
webapp/views.py

- Implemented “user_id” feature to send universally unique identifiers to Google Analytics as described [here](https://warthogs.atlassian.net/browse/WD-14908)
- Added functionality to pass value on form submission
- View the site locally in your web browser at: https://ubuntu-com-14440.demos.haus/ (or any page)
- If you have not set cookie preferences:
- Before accepting any cookies open dev tools, log `document.cookie` and see that `user_id` does not exist
- Accept either all or performance cookies and do the same as above, this time ensuring that `user_id` is now present
- Go to any form and fill it out (https://ubuntu-com-14440.demos.haus/ai#get-in-touch for example)
- Go to the enrichment form on maketo: https://engage-sj.marketo.com/?munchkinId=066-EOV-335#/mktform/4198/overview/detai …

Implement user_id and pass it in marketo submission

---

templates/base_index.html

- Turned on the switch that will enable A/B tests for two different layouts of takeovers that were implemented before in the scope of this epic: https://warthogs.atlassian.net/browse/WD-11543
- Navigate to the landing page at https://ubuntu-com-14467.demos.haus/
- Remember the layout of the takeover shown on the top of the page
- Check the value of the `control_or_variant` cookie in dev console
- if it's `control`, change it to `variant`
- if it's `variant`, change it to `control`
- This change happens automatically in the background by splitting users into two groups so that each group only sees their version of the takeover layout. But for testing purpose you need to change it manually.
- Refresh the page
- Check that the layout of the takeover has changed
Fixes …

[WD-16659] enable AB tests for takeovers on the landing page

---

static/js/src/dynamic-forms.js
templates/kernel/real-time/contact-us.html
templates/shared/_client-contact-us-form.html
templates/shared/_default-contact-us-form.html
templates/shared/_pro-contact-us-form.html
templates/shared/forms/interactive/aws.html
templates/shared/forms/interactive/esm.html
templates/shared/forms/interactive/general.html
templates/shared/forms/interactive/landscape.html
templates/shared/forms/interactive/pricing-infra.html
templates/shared/forms/interactive/storage.html

- Add check for machinesInput
- Fixes the javascript error that was previously looping through an empty instance
To test for modal:
- Go to https://ubuntu-com-14465.demos.haus/case-study/esa or any page with a dynamic form modal
- Scroll down and click on "Contact Us", modal should pop up
- Close the modal and see that it behaves as expected
To test that radio attributes are removed correctly:
- Go to https://ubuntu-com-14465.demos.haus/aws#get-in-touch or any of the affected pages (see file diff)
- Fill up the form and submit
- Check that payload includes radio "How many machines..." as intended
Fixes [WD-16656](https://warthogs.atlassian.net/browse/WD-16656) …

Fix radio modal bug for dynamic forms

---

templates/security/oval.html

- Update copy to remove references to "OCI".
- View the site locally in your web browser at: http://0.0.0.0:8001/security/oval
- Visit https://ubuntu-com-14472.demos.haus/security/oval
- Check that the references to "OCI" have been replaced.
https://warthogs.atlassian.net/browse/WD-16658

WD-16658 - copy: replace references to 'OCI'

---

templates/ai/mlops.html
templates/ai/what-is-kubeflow.html
templates/azure/index.html
templates/shared/_azure-banner.html

Updated a series of pages to have a small banner that invites people to sign up for Managed Kubeflow on Azure.
[Doc 1](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?tab=t.0#heading=h.m90kfgudav7e), [doc 2](https://docs.google.com/document/d/18AMX_-3zjBNUNGr0X5QtjKhsUzAc2k8VM1-opZEGh4k/edit?tab=t.0), [doc 3](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit?tab=t.0#)
- Make sure to test on mobile, tablet and desktop screen sizes
Fixes [#WD-16533](https://warthogs.atlassian.net/browse/WD-16533) …

copy: add Azure banner to multiple pages. WD-16533

---

static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts

- Restrict distributor store users from editing billing details
- Check out this feature branch or go to the demo link
- Go to /pro/distributor, /pro/subscribe and /credentials
- Purchase an item for each shop
- Distributor users should not be able to edit their tax and billing address info (Only card number)
- Pro/credential users should be able to edit as before.
Fixes #https://warthogs.atlassian.net/browse/WD-16449
before
after
before
after

Restrict channel users from editing billing details

---

Dockerfile
package.json
templates/ceph/managed.html
webapp/app.py
yarn.lock

- Rebranded /ceph/managed.
- Added support for Vanilla Macros.
- Bumped versions for Vanilla and SCSS.
- The Vanilla and SCSS version has been updated in this PR, please look for abnormalities/irregularities across the site.
- [Copydoc](https://docs.google.com/document/d/1Ff3TDYBsukagu85dNZuK0FDdPRSjXEwS6Tv6JphXUvY/edit?tab=t.0)
- [Design](https://www.figma.com/design/ulUyOFdQ7CNy0whuJ4S2FM/Ceph-Bubble?node-id=21-6589&node-type=instance&m=dev)
- [Demo](https://ubuntu-com-14470.demos.haus/ceph/managed)  
Fixes # [WD-16351](https://warthogs.atlassian.net/browse/WD-16351) …

Rebrand /ceph/managed

---

templates/aws/workspaces.html
templates/azure/shared/_how-ubuntu-pro-helps-you.html

- Fixed copy discrepancies as per [doc](https://docs.google.com/document/d/1qC22TM6KZTlxK3CScf-RQ4RUiMUhIBcjSWGur-dbYVA/edit?tab=t.0)
- Added medium col classes to improve layout on medium screens
- Removed `remove-first-hr` class which doesn't actually exist
- View the site locally in your web browser at: https://ubuntu-com-14478.demos.haus/aws/workspaces
- Check against doc and see that medium cols now show up as expected
Originally flagged in [MM](https://chat.canonical.com/canonical/pl/wnxa7c6p1prg5d97196gakafir)

Fix copy and remove/update stale classes

---

templates/templates/docs/shared/_docs.html

- Fix bug where `aria-expanded` was not being applied to side navigation items within docs. Leading to the where you are in the navigation not being clear.
- Go to https://ubuntu-com-14483.demos.haus/landscape/docs/upgrade-landscape and see that the side-navigation expands to show you the page you are on. For reference you can check out https://ubuntu.com/landscape/docs/upgrade-landscape to see how it currently works (or doesn't work)
Fixes https://warthogs.atlassian.net/browse/WD-16358

fix: Show where you are in docs navigation

---

templates/base_index.html

- Changed CTA color on the Pro section on the u.c homepage to green (positive)
- Visit https://ubuntu-com-14491.demos.haus/
- Make sure the CTA color is green.
Fixes [WD-17037](https://warthogs.atlassian.net/browse/WD-17037)
Before
After
[WD-17037]: https://warthogs.atlassian.net/browse/WD-17037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change CTA color to positive (green)

---

static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx
static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx

- Fix typo in expiry notification
Remove one "to" from "Click on Renew subscription **to to** ensure service continuity."
Fixes #https://warthogs.atlassian.net/browse/WD-16915

Fix typo in expiry notification

---

templates/ceph/consulting.html
templates/ceph/shared/_ceph-users.html
templates/shared/_resources_ceph.html

- Rebrand /ceph/consulting
- Update shared sections in Ceph bubble for **resources** and **users**
- Go to https://ubuntu-com-14473.demos.haus/ceph/consulting
- Compare with [design](https://www.figma.com/design/ulUyOFdQ7CNy0whuJ4S2FM/Ceph-Bubble?node-id=13-3904&node-type=instance&m=dev)
- There are no content changes, only redesign
Fixes [WD-16345](https://warthogs.atlassian.net/browse/WD-16345)
[WD-16345]: https://warthogs.atlassian.net/browse/WD-16345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rebrand /ceph/consulting

---

static/js/src/advantage/react/components/Subscriptions/Landscape/Landscape.test.tsx
static/js/src/advantage/react/components/Subscriptions/Landscape/Landscape.tsx

- Change button to signup for landscape saas
- There should be a landscape saas button 
- Should link to https://landscape.canonical.com/create-new-account
Fixes [#WD-16537](https://warthogs.atlassian.net/browse/WD-16537)

copy changes for landscape

---

templates/base_index.html

inital loading of hompage was loading around 9MB of resources.
By lazy loading images we can reduce the intial loading by 5-6 MB.
Partially Fixes: #14443
before
after

ui: add Lazy loading for images>1MB

---

static/sass/styles.scss
templates/templates/_footer_item.html

- This addresses an [issue reported on github](https://github.com/canonical/ubuntu.com/issues/14371) by @lyubomir-popov  about excess padding between footer items
- Check that the space between footer items is meets @lyubomir-popov requirements
- Check on all screen sizes
Fixes https://warthogs.atlassian.net/browse/WD-15498
https://github.com/canonical/ubuntu.com/issues/14371

style: Remove excess padding between footer items

---

static/js/src/cookie-policy-with-callback.js

- fix: Init cookie-policy even if cookies have been set already
- Open [the demo](https://ubuntu-com-14497.demos.haus/)
- Accept your preferred cookie-policy setttings
- Refresh the page and scroll to the very bottom
- Click 'Manage your tracker settings'
- The cookie-policy modal should open and you will be able to change your preferences
- Make sure to check with different combinations of cookie-policy preferences and check they are being stored
*it is a known bug that the cookie is not update until the page is refreshed. There is an issue to fix it [here](https://warthogs.atlassian.net/browse/WD-17163)*
Fixes https://warthogs.atlassian.net/browse/WD-16366

fix: Init cookie-policy even if cookies have been set already

---

templates/ceph/thank-you.html

- Rebrand /ceph/thank-you page
- Go to https://ubuntu-com-14505.demos.haus/ceph/thank-you
- Check that it matches design
- No content change from original
- [Design](https://www.figma.com/design/FoWXkNxxdri9EgSsLdtTrH/24.10-ubuntu.com%2Faws?node-id=120-4373&node-type=canvas&m=dev)
Fixes [WD-16353](https://warthogs.atlassian.net/browse/WD-16353)
[WD-16353]: https://warthogs.atlassian.net/browse/WD-16353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rebrand /ceph/thank-you page

---

templates/base_index.html

- Turn off the switch that is used for showing different layouts for takeovers on the home page.
- Open the demo link at https://ubuntu-com-14506.demos.haus/
- Make sure that the layout of the takeover is correct
- Open cookies from the dev console
- Change the value of "control_or_variant" cookie to "variant" (if it's not that already)
- Refresh the page and check if the takeover layout has not changed
Fixes https://warthogs.atlassian.net/browse/WD-17261
The layout that is expected to see:
Alternative layout that should not render anymore:

[WD-17261] switch off the A/B for takeovers

---

webapp/security/views.py

- Fixed spacing typo
- Go to demo down at the /ubuntupro to see the tooltip and correction [demo](https://ubuntu-com-14502.demos.haus/security/CVE-2024-48990)
Fixes #14499 
The issue is here

WD-17171 Tooltip for ubuntu pro button has a typo

---

templates/shared/_pro-contact-us-form.html

- Add CMMC, NIS2 and Cyber Essentials to Pro contact form
- go to /contact-us/form?product=pro
- Scroll down to the section titled "Do you have specific compliance or hardening requirements?" 
- The new options should appear there
- Fill in the form
- Verify the submission on marketo for form 1257
- Copy doc link: https://docs.google.com/document/d/1X1Qx5cimbU7D_xQKnm3se9gRDFcRDEaX5fkGR42b3yU/edit?tab=t.0
Fixes [#WD-17096](https://warthogs.atlassian.net/browse/WD-17096)
[QA steps](https://discourse.canonical.com/t/qa-steps/152) …

add more options to Pro contact form

---

templates/credentials/sign-up.html
templates/credentials/thank-you.html
webapp/app.py
webapp/shop/cred/views.py

- Customise the thank you message for tester and sme sign up form
- Go to `credentials/sign-up?type=sme` and submit the form
- Make sure that the thank you page shows up with the following message: "Once our next exam is ready for community contributions, we’ll review applications and contact candidates with the appropriate profile."
- Go to `credentials/sign-up?type=tester` and submit the form
- Make sure that the thank you page shows up with the following message: "Once our next exam enters the testing phase, we’ll review applications and contact qualified testers with …

customise credentials thank you page for each sign up form

---

package.json
templates/ceph/components/benefits-table.html
templates/ceph/index.html
yarn.lock

- Applied redesign as per [doc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit?tab=t.0) and [design](https://www.figma.com/design/ulUyOFdQ7CNy0whuJ4S2FM/Ceph-Bubble?node-id=13-5965&node-type=frame&m=dev)
- Drive by:
- Bump Vanilla version 
- View the site locally in your web browser at: https://ubuntu-com-14498.demos.haus/ceph
Fixes https://warthogs.atlassian.net/browse/WD-16343

feat: /ceph redesign

---

static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx

- Remove `Free trial available` hyperlink. 
- Change copy to `Free trial on checkout`.
- Go to https://ubuntu-com-14516.demos.haus/pro/subscribe
- Verify that the hyperlink is removed and the copy is updated
Fixes [WD-17303](https://warthogs.atlassian.net/browse/WD-17303)
[WD-17303]: https://warthogs.atlassian.net/browse/WD-17303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-17303] Updating the "Free Trial Available" badge on Pro store page

---

templates/security/compliance-automation.html

- Updated the link according to copydoc
- [Copydoc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit?disco=AAABV8SLRr4)
- Go to [demo](https://ubuntu-com-14512.demos.haus/security/compliance-automation)
Fixes #14309 

Update compliance-automation.html link

---

meganav.yaml

Replace 'Charmhub' with 'AI & MLOps' in meganav featured products section.
[Doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit?tab=t.0)
Fixes [#WD-17137](https://warthogs.atlassian.net/browse/WD-17137) …

copy: replace 'Charmhub' with 'AI & MLOps' in meganav. WD-17137

---

static/js/src/dynamic-forms.js

- Country code now gets displayed beside phone number in modal forms
- visit #getintouch forms and check if you could see the extensions for country.
eg. https://ubuntu-com-14517.demos.haus/kubernetes#get-in-touch
Fixes #14509 
Previous
Now

Fixed phone modal for country code

---

static/sass/_pattern_lists.scss
static/sass/styles.scss
templates/ceph/install.html
templates/ceph/shared/_containerized-deployment.html
templates/ceph/shared/_large-scale-deployment.html
templates/ceph/shared/_latest-news-ceph.html
templates/ceph/shared/_multi-node-deployment.html
templates/ceph/shared/_single-node-deployment.html
templates/download/shared/_latest-blogs_download.html

- Applied redesign as per [doc](https://docs.google.com/document/d/1EmOtHjuEMKhVLQA7GwyrKfCzOKfc8UCEyh-p04-PxzA/edit?tab=t.0) and [design](https://www.figma.com/design/ulUyOFdQ7CNy0whuJ4S2FM/Ceph-Bubble?node-id=16-4455&node-type=frame&m=dev)
- Drive by:
- Fixed the djlint toggle setting not placed correctly on `/_latest-blogs_download.html`
- View the site locally in your web browser at: https://ubuntu-com-14511.demos.haus/ceph/install
Fixes https://warthogs.atlassian.net/browse/WD-16347

feat: /ceph/install redesign

---

navigation.yaml
templates/ai/mlops-workshop.html

- Build page on /ai/mlops-workshop
- Go to [/ai/mlops-workshop](https://ubuntu-com-14474.demos.haus/ai/mlops-workshop)
- Compare page against [copy doc](https://docs.google.com/document/d/1g06uHWdy2ohYq-tKCEsdlD2EohZQ8OHSWO3i8U5vUDc/edit?tab=t.0#heading=h.cgkadc5nutp) and [design](https://www.figma.com/file/sGeCjFvA1kV9Kmvg2S2VBn?type=design&node-id=2826%3A10723&mode=dev)
Fixes #https://warthogs.atlassian.net/browse/WD-16670

Build page on /ai/mlops-workshop

---

templates/shared/_pro-contact-us-form.html

- Just a simple typo fix
- Visit /contact-us/form?product=pro
- The section titled "Do you have specific compliance or hardening requirements?"
- The option should be CMMC instead of CMMS
Fixes [#WD-17354](https://warthogs.atlassian.net/browse/WD-17354)

change cmms to cmmc

---

templates/robotics/community.html

- Update the answers URL on the ROS website to the Stack Exchange website.
- Updated the [copy doc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit?tab=t.0) for the page
- Check the old link doesn't work anymore
- Check the new link works
- Check this aligns with the recommendation on the [ROS discourse](https://discourse.ros.org/c/general/8) header
Fixes https://github.com/canonical/ubuntu.com/actions/runs/12134872496

fix(links): Fix the link to ROS questions

---

templates/embedding/faqs.html

- Updates the meta copydoc to the correct link https://docs.google.com/document/d/1xWrM0D4LkWdJh9EiAUuXgbYKqh15BnNcQpXqTlZCuYA/edit?tab=t.0
- Check the link in the meta_copydoc block matches the one above/ the one mention by Sophie in [her comment](https://chat.canonical.com/canonical/pl/sg9r6bqf43gi58pfzoi75bf3ww)

fix(/embedding/faqs): Update meta_copydoc link

---

konf/site.yaml
templates/security/notices/usn.html

- Route security API requests to single service
- The new API only returns related_notices as a lis of IDs, so we updated the template of the notice detail page
- Check `/notices/USN-7135-1.json` to make sure links to related notices still work

Route security API requests to single service

---

webapp/shop/api/ua_contracts/advantage_mapper.py

- client IP not being forwarded to UA contracts backend
- Client IP should be forwarded to the backend. 
- Visit /pro/attach
- Verify by spamming the endpoint and checking if it rejects responses
Fixes [#https://warthogs.atlassian.net/browse/WD-17439](https://warthogs.atlassian.net/browse/WD-17439)

Client IP not being forwarded during magic attach

---

templates/internet-of-things/contact-us.html
templates/internet-of-things/index.html

- Changed form redirect url so that the user is redirected to /internet-of-things#contact-form-success instead of /internet-of-things/thank-you page.
- View the site in your web browser at: https://ubuntu-com-14545.demos.haus/internet-of-things/
- Make sure you keep javascript enabled.
- Scroll down to the Contact Our Team button and click on it. This should open up the contact form in a modal.
- Fill out the form and submit. You should be redirected to u.com/internet-of-things#success and see the notification on top of page.
- Now disable javascript (from the dev tools)
- Scroll down to the Contact Our Team button and click on it. This should take you to the static contact-us page.
- Fill out the form and submit. ou should be redirected to u.com/internet-of-things#success and see the …

WD-17582 Redirect to success notification instead of thank-you page.

---

templates/dell/index.html
templates/hpe/index.html
templates/supermicro/index.html

- Update chip buttons to anchor tags for a11y
- Go to https://ubuntu-com-14551.demos.haus/dell, https://ubuntu-com-14551.demos.haus/hpe, https://ubuntu-com-14551.demos.haus/supermicro
- Scroll to find chip tags
- Click on them and check that they redirect as expected
Fixes [WD-17631](https://warthogs.atlassian.net/browse/WD-17631) and https://github.com/canonical/ubuntu.com/issues/12660
[WD-17631]: https://warthogs.atlassian.net/browse/WD-17631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update chip buttons to anchor tags

---

templates/internet-of-things/management.html

- Use modal form on iot/management
- View the site in your web browser at: https://ubuntu-com-14548.demos.haus/internet-of-things/management
- Find the three contact buttons, namely `Get in touch`, `Get in touch to discuss your device management needs ›`, `Get in touch`
- First, with JavaScript enabled, click on the three buttons to see a contact form opening up in a modal.
- Secondly, with JavaScript disabled, click on the three buttons to get redirected to iot/contact-us static page.
- Submit both forms to verify form's successful submission.
Fixes #[17586](https://warthogs.atlassian.net/browse/WD-17586)

Use modal form on iot/management

---

templates/openstack/index.html

- Update Charmed OpenStack index page based on requested copy update.
- Navigate to [/openstack](https://ubuntu-com-14552.demos.haus/openstack) and make sure the changes requested in the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?tab=t.0#heading=h.dq2j5y35fa3h) are reflected.
- [WD-17580](https://warthogs.atlassian.net/browse/WD-17580)
[WD-17580]: https://warthogs.atlassian.net/browse/WD-17580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-17580 - Copy Update: charmed openstack index page

---

static/js/src/tabbed-content.js
templates/download/amd/_wiki_notification.html
templates/download/amd/index.html
templates/download/amd/tab-1.html
templates/download/amd/tab-2.html

[Copy docs update](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0) to include Ubuntu 24.04 LTS.
- View the site locally in your web browser at: https://ubuntu-com-14507.demos.haus/download/amd
- Make sure that the new changes to the [copy docs](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0) are applied
Fixes WD-17126

Download AMD: add 24.04 LTS

---

templates/landscape/base_landscape.html
templates/landscape/index.html

- Rebranded /landscape landing page
- [Demo](https://ubuntu-com-14540.demos.haus/landscape)
- [Design](https://www.figma.com/design/btsxPLFKGPWDlbQ4rjR4jZ/25.04-Landscape-Rebranding?node-id=0-1&node-type=canvas&m=dev)
- [Copydoc](https://docs.google.com/document/d/1Q5KPVOn3yaexgSbkZHmXHmWzT5WG3ocYAPthweMwDz4/edit?tab=t.0)
Fixes # [WD-16834](https://warthogs.atlassian.net/browse/WD-16834)
[WD-16834]: …

Rebrand /landscape

---

templates/internet-of-things/smart-home.html

- Redesigned ubuntu.com/internet-of-things/smart-home
- View the site in your web browser at: https://ubuntu-com-14530.demos.haus/internet-of-things/smart-home
- Match the website with Design and Copydoc.
- [Design](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-16452&t=4kUhsH39i1i4UsV9-1)
- [Copydoc](https://docs.google.com/document/d/1zwB-6Flt0Jm7XIxhWUWRJjKC1WCGVmVVNmPHtyOTHuE)
Fixes #[16647](https://warthogs.atlassian.net/browse/WD-16647)

WD-16647 Redesigned internet-of-things/smart-home

---

templates/templates/small-footer.html

- Update footer to span full width
- Go to a tutorial page, e.g https://ubuntu-com-14557.demos.haus/tutorials/build-your-cloudformation-templates-with-the-latest-ubuntu-ami#1-overview
- Scroll down to footer
- Check that footer spans throughout the page
Fixes [WD-17657](https://warthogs.atlassian.net/browse/WD-17657)
[WD-17657]: https://warthogs.atlassian.net/browse/WD-17657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update footer to span full width

---

navigation.yaml
templates/pro/thank-you.html
templates/pro/tutorial.html
templates/shared/forms/interactive/advantage-beta.html
templates/shared/forms/interactive/pro-devices.html

- Reported by failing links on live check https://github.com/canonical/ubuntu.com/actions/runs/12271620104/job/34238813073
- Updated all occurrences of https://discourse.ubuntu.com/c/ubuntu-pro to https://discourse.ubuntu.com/c/project/ubuntu-pro/116
- Go to https://ubuntu-com-14558.demos.haus/
- Check that affected pages link to the Discourse forum
- Check that the nav on https://ubuntu-com-14558.demos.haus/pro links to the Discourse forum
Fixes #

fix: update broken Ubuntu Pro discourse links

---

templates/download/amd/tab-1.html
templates/download/amd/tab-2.html

- update links on /download/amd
https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0
- Go to [/download/amd](https://ubuntu-com-14563.demos.haus/download/amd)
- Check that the links have changed as per the copy doc updates.
https://warthogs.atlassian.net/browse/WD-17707

feat: update links on /download/amd

---

templates/internet-of-things/smart-displays.html

- Apply rebranding on /internet-of-things/smart-displays
- No changes to content, only design
- Go to https://ubuntu-com-14538.demos.haus/internet-of-things/smart-displays
- Check that design matches [Figma](https://www.figma.com/design/1CdIT6TV3ASf55GsnQcwXg/Internet-of-Things?node-id=2001-15688&node-type=frame&m=dev)
- No changes to design
Fixes [WD-16639](https://warthogs.atlassian.net/browse/WD-16639)
[WD-16639]: https://warthogs.atlassian.net/browse/WD-16639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rebrand /iot/smart-displays

---

templates/security/cves/_cve-card.html

"Affected package" (singular) for CVEs that affect a simple package
[Demo](https://ubuntu-com-14561.demos.haus/security/cves?version=noble&version=jammy&version=focal&version=bionic&version=xenial&version=trusty&version=oracular&offset=10)
Currently:

Fix summarised status copy for CVEs that affect a single package

---

templates/base_index.html

- Removes a line of code that was assigning 'is-loading' after the rest of the code had executed leading to a visual bug
- Open [the demo](https://ubuntu-com-14566.demos.haus/)
- See that the takeover shows on _all_ screen sizes
Fixes [Bug reported here](https://chat.canonical.com/canonical/pl/d3c7sde8b38xbq6oa6jzrbjjdo)

bug: Fix issue where 'is-loading' class was not removed from loaded takeovers

---

templates/shared/forms/interactive/smart-home.html

- Removed pagination
- Conversion to single page
- Cleanup
- Check the old modal here first: https://ubuntu.com/internet-of-things/smart-home#get-in-touch
- Check the new modal at: https://ubuntu-com-14571.demos.haus/internet-of-things/smart-home#get-in-touch
- Check that modal form is a single page without pagination.
- Submit the form to make sure it's working.
Fixes #[WD-17783](https://warthogs.atlassian.net/browse/WD-17783)
[WD-17783]: https://warthogs.atlassian.net/browse/WD-17783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-17783  smart-home modal form - removed pagination + conversion to single page

---

templates/download/nvidia-jetson/tab-2-jetson-orin-nano.html
templates/download/nvidia-jetson/tab-3-jetson-orin-nx.html

Updated link
- Go to /download/nvidia-jetson
- Check tabs 2 & 3
Fixes #[WD-17752](https://warthogs.atlassian.net/browse/WD-17752)
[WD-17752]: https://warthogs.atlassian.net/browse/WD-17752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update link in nvidia-jetson

---

templates/kubernetes/docs/1.31/release-notes.md
templates/kubernetes/docs/release-notes.md

This PR adds the release notes for Charmed Kubernetes 1.31+ck1 bug fix release as a follow up to https://github.com/charmed-kubernetes/kubernetes-docs/pull/870
Fixes #

[K8s docs] Add release_1.31+ck1 release notes

---

static/files/forms-data.json
static/js/src/dynamic-forms.js
templates/aws/base_aws.html
templates/aws/index.html
templates/aws/outposts.html
templates/aws/pro.html
templates/aws/support.html
templates/shared/forms/form-fields.html
templates/shared/forms/form-template.html
webapp/app.py

- Use form template for modals in the `/aws` bubble
- Added `childrenPaths` entry on `forms-data.json`, this allows children pages to use the same form template
- e.g /aws modal is used in /aws/outposts, /aws/pro, /aws/support
- **Note: update forms documentation when this is merged**
- Add inputType to forms-data: radio, checkbox, checkbox-visibility
- The inputType is read in form-fields.html and adds javascript classes where appropriate
- Added placeholder to long text input
- Run djlint on form-fields.html
- Fixed duplicated intlTelInput for forms
- Go to https://ubuntu-com-14575.demos.haus/aws, click on CTA button and see that modal pops up
- Fill up form and submit, check payload and that the submission goes through Marketo successfully
- Repeat for 
- …

fix: Fix form generator bugs and use template on /aws bubble

---

templates/legal/data-privacy/index.html

- Mentioned recaptcha cookies in the data privacy page
Copy doc: https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit?tab=t.0
- View the site locally in your web browser at: http://localhost:8001/legal/data-privacy
WD-17842

mention recaptcha cookies in data privacy page

---

package.json
templates/16-04/index.html
templates/20-04/base_20-04.html
templates/20-04/index.html
templates/base_index.html
templates/embedded/index.html
templates/financial-services/index.html
templates/hpc/index.html
templates/observability/index.html
templates/openstack/resources.html
templates/shared/_latest_news_strip.html
templates/wsl/index.html
yarn.lock

- Build /20-04 page based off of [copydoc](https://docs.google.com/document/d/1lzxAL9Wt24m5-p5qG9y190rOg3FY5zVdKLYLlBoBcLU/edit?tab=t.0) and [figma design](https://www.figma.com/design/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=5107-21524&node-type=canvas&t=e97GwrAiLwPAWxc0-0)
- Added some features to `_latest_news_strip.html`
- Bumped vanilla to `4.18.4`
- Check out [demo link](https://ubuntu-com-14559.demos.haus/20-04)
- Check the design matches the [figma design](https://www.figma.com/design/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=5107-21524&node-type=canvas&t=e97GwrAiLwPAWxc0-0)
- Check the content matches the [copydoc](https://docs.google.com/document/d/1BSlOqwe--4MoVvAEok6WssBfEfwiRSXN1dNWCoUffdY/edit?tab=t.0#heading=h.mgfeqagpepfl)
- Check there is …

feat: Build /20-04 page

---

templates/landscape/managed.html

- Rebranded page
- View the site  in your web browser at: https://ubuntu-com-14580.demos.haus/landscape/managed
- Check that it matches the following:
- [Design](https://www.figma.com/design/btsxPLFKGPWDlbQ4rjR4jZ/25.04-Landscape-Rebranding?node-id=4015-2226&t=2riHUPsatn9YCZDu-0)
- [CopyDoc](https://docs.google.com/document/d/1MycPWcmMveCZxrGtn7ASc0myWNxPzLTciHfQIA6kPZ4/edit?tab=t.0#)
Fixes #[WD-16838](https://warthogs.atlassian.net/browse/WD-16838)
[WD-16838]: https://warthogs.atlassian.net/browse/WD-16838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-16838 Rebranded /landscape/managed page

---

webapp/handlers.py

Added security headers.
- Content-Security-Policy: Restrict resources (e.g., JavaScript, CSS, Images) and URLs
-  Referrer-Policy: Limit referrer data for security while preserving full referrer for same-origin requests
- Cross-Origin-Embedder-Policy: allows embedding cross-origin resources
- Cross-Origin-Opener-Policy: enable the page to open pop-ups while maintaining same-origin policy
- Cross-Origin-Resource-Policy: allowing cross-origin requests to access the resource
- X-Permitted-Cross-Domain-Policies: disallows cross-domain access to
resources
Read more from [here](https://docs.google.com/document/d/15ajij_jStQ4oUTEo7pT4TgaW5zRH4SOMaW9TDyy0dGE).
- Open : https://ubuntu-com-14411.demos.haus/
- Verify no security header error is shown in the console.
- Verify all the images, videos, …

feat: add security headers

---

templates/landscape/features.html

- Corrected the incorrect links returning 404 for contact us in landscape/features
- Go on [/landscape/features](https://ubuntu-com-14597.demos.haus/landscape/features) and check if the links are working correctly.
Fixes # [WD-17891](https://warthogs.atlassian.net/browse/WD-17981)
[WD-17891]: https://warthogs.atlassian.net/browse/WD-17891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-17891 fix(links): Corrected the incorrect links

---

static/js/src/advantage/distributor/components/DistributorBuyButton/DistributorBuyButton.test.tsx
static/js/src/advantage/distributor/components/DistributorShopForm/AddSubscriptions/SubscriptionCard.tsx/SubscriptionCard.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx
static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts

-  Restrict channel users from editing billing information
**Pro shop & Credential users** 
1. Log in as Pro user (normal user)
2. Select products from the pro shop (/pro/subscribe)
3. Click the checkout button to land on the checkout page
4. On the check out page
7. Edit the information or save the information, and check the purchase is working properly.
**Distributor users**
1. Log in as a channel user (distributor user)
2. Go to /pro/distributor
3. Click the checkout button to land on the checkout page.
4.  On the check out page
7. Edit the information or save the information, and check the purchase is working properly.
Fixes #https://warthogs.atlassian.net/browse/WD-16449

Wd-16440 Restrict channel users from editing billing information

---

templates/base_index.html
templates/templates/_tag_manager.html

- Added a null check for the user-id cookie
- Updated the user-country endpoint (_which was change 10 months ago_) 
**1. Added a null check for the user-id cookie**
- Go to https://ubuntu.com
- Open the Application tab in the inspector and remove the user_id cookie
- Refresh the page and see a console error regarding `getCookie()[2]`
- Open the console and see you do not see this error anymore
**2. Updated the user-country endpoint**
- Go to https://ubuntu.com and open the console
- See that you see a 404 accessing the user-country.json endpoint
- Open the demo and see this is not the case

fix(js): Fix several JS errors reported from the sites homepage

---

templates/support/index.html

- Corrected link
- Check if link works properly
- [Copydoc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit?tab=t.0#)
- [Demo](https://ubuntu-com-14628.demos.haus/support)

Corrected Link on Ubuntu Support

---

templates/download/shared/_server_weekly_news.html

- Add "the" to the form field in the server weekly newsletter form  
- visit /download/server/thank-you
- Click on "Download the CLI cheatsheet" button 
- Check if the form has a checkbox that says "I would like to receive news from the Ubuntu newsletter and occasional updates from Canonical by email"
- Copy Link: https://docs.google.com/document/d/1bC2b3bVylJFTuGpIcFzCph7GDp89_c4ixQRhEZiGUeE/
Fixes [#WD-17971](https://warthogs.atlassian.net/browse/WD-17971) …

WD-17971-add-a-the-on-the-form-text-at-download-server-thank-you

---

templates/download/mediatek-genio/contact-us.html
templates/internet-of-things/nvidia/contact-us.html

- Remove `name` attributes on "Which Nvidia platforms..." and "Tell us more about your project" to exclude them in the payload on /iot/nvidia/contact-us
- Add `js-formfield` and `js-remove-radio-names` to fieldsets on /download/mediatek-genio/contact-us
- Run djlint on both files
- Go to https://ubuntu-com-14641.demos.haus/internet-of-things/nvidia/contact-us
- Submit form
- Check that `Comments_from_lead__c` in payload concatenated results for NVIDIA platform and About Project
- Repeat for https://ubuntu-com-14641.demos.haus/download/mediatek-genio/contact-us
Fixes [WD-18062](https://warthogs.atlassian.net/browse/WD-18062) and [WD-17008](https://warthogs.atlassian.net/browse/WD-17008) …

fix: Fix payload attributes on /iot/nvidia/contact-us and /download/mediatek-genio/contact-us

---

templates/shared/forms/interactive/automotive.html

- Fixed half-width automotive form
- Open the demo at https://ubuntu-com-14648.demos.haus/automotive and click `Contact Canonical`
- The inputs should fill the width
Fixes [WD-18102](https://warthogs.atlassian.net/browse/WD-18102)
[WD-18102]: https://warthogs.atlassian.net/browse/WD-18102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: form inputs should fill width

---

templates/embedding/faqs.html

- Rebranded /embedding/faqs page.
- Open this [demo](https://ubuntu-com-14626.demos.haus/embedding/faqs) in your web browser.
- Make sure to test on mobile, tablet and desktop.
- Make sure the page matches the [Figma design](https://www.figma.com/design/10NU0NGNkXEHrdhWGXW7xg/25.04-Embedding-Rebranding?node-id=11-766&t=uAlXm46LIvlk1bPb-1) and [Copydoc](https://docs.google.com/document/d/1xWrM0D4LkWdJh9EiAUuXgbYKqh15BnNcQpXqTlZCuYA/edit?tab=t.0)
Fixes #[WD-16602](https://warthogs.atlassian.net/browse/WD-16602)
[WD-16602]: https://warthogs.atlassian.net/browse/WD-16602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rebrand embedding/faqs page

---

templates/embedding/base_embedding.html
templates/embedding/index.html
templates/shared/forms/interactive/embedding.html

- Rebranded /embedding/landing page.
- Open this [demo](https://ubuntu-com-14620.demos.haus/embedding) in your web browser.
- Make sure to test on mobile, tablet and desktop.
- Make sure the page matches the [Figma design](https://www.figma.com/design/10NU0NGNkXEHrdhWGXW7xg/25.04-Embedding-Rebranding?node-id=1-1093&t=uAlXm46LIvlk1bPb-1) and [Copydoc](https://docs.google.com/document/d/1evAFIXbNztOd5yZee-uV8_OM-s6o27P46yXFaaeEhy0/edit?tab=t.0#)
Fixes #[WD-16600](https://warthogs.atlassian.net/browse/WD-16600)
[WD-16600]: https://warthogs.atlassian.net/browse/WD-16600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-16600 Rebrand embedding/landing page

---

templates/observability/managed.html
templates/observability/what-is-observability.html

- Rebranded /observability/managed page.
- Open this [demo](https://ubuntu-com-14607.demos.haus/observability/managed) in your web browser.
- Make sure to test on mobile, tablet and desktop.
- Make sure the page matches the [Figma design](https://www.figma.com/design/BycwGsYlyy6sYR6oD60O76/25.04-Observability-Rebranding?node-id=1-5805&t=Srn4jnJoOzXaY1Tu-1) and [Copydoc](https://docs.google.com/document/d/1N11otwvy2TWoK4j9e8iYJLNLYQyWbIPL82GVkm8WHhE/edit?tab=t.0)
Fixes #[WD-16849](https://warthogs.atlassian.net/browse/WD-16849)
[WD-16849]: https://warthogs.atlassian.net/browse/WD-16849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-16849 Rebranded /observability/managed page

---

meganav.yaml
yarn.lock

- Updated spelling in meganav (BE -> AE) - see [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit?tab=t.0)
- Open this: [demo page](https://ubuntu-com-14657.demos.haus/)
- Open the meganav
- Check that the changes in the [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit?tab=t.0) are implemented
Fixes [WD-18260](https://warthogs.atlassian.net/browse/WD-18260) …

fix(spelling): update BE->AE in meganav [WD-18260]

---

requirements.txt
templates/blog/article.html
tests/test_blog_notice.py

- Fixes and adds the meta_description coming from wp blogs.
-  Visit https://ubuntu-com-14644.demos.haus/blog/what-is-iot-device-management and see if value of `meta_description` is "Is that even a good meta""

added meta_decription from blogs

---

static/js/src/tutorial.js

- Find and scroll to header anchors in the page, instead of displaying a blank page
- Open the demo at [/tutorials/install-ubuntu-desktop#1-overview](https://ubuntu-com-14658.demos.haus/tutorials/install-ubuntu-desktop#1-overview)
- Click on any header with an anchor
- The page should scroll to, and center this header instead of a blank page
- Try other anchors, e.g https://ubuntu-com-14658.demos.haus/tutorials/install-ubuntu-desktop#manual-partitioning
- [WD-18201](https://warthogs.atlassian.net/browse/WD-18201)
- https://github.com/canonical/ubuntu.com/issues/14634
[WD-18201]: https://warthogs.atlassian.net/browse/WD-18201?atlOrigin=eyJpIjoiNWRkNTljNzY …

fix: blank page when opening anchors

---

templates/kubernetes/install.html

- Rebranded kubernetes/install
- Open this [demo](https://ubuntu-com-14659.demos.haus/kubernetes/install) in your web browser.
- Make sure to test on mobile, tablet and desktop.
- Make sure the page matches the [Figma design](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=1-1925&m=dev) and [Copydoc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit?tab=t.0)
Fixes #[WD-12879](https://warthogs.atlassian.net/browse/WD-12879)
[WD-12879]: https://warthogs.atlassian.net/browse/WD-12879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-12879] Rebrand kubernetes/install page

---

templates/kubernetes/resources.html
templates/macros/_macros-resource.jinja
templates/shared/forms/interactive/kubernetes.html
yarn.lock

- Rebrands /kubernetes/resources based on [the copydoc](https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit?tab=t.0) and [figma design](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=0-1&p=f&t=BOvAzB2thrZyele5-0)
- Creates a new macro `_macros-resource.jinja` to help handle the build of the individual resource. My thinking here is that it will be a lot easier to update the content and make changes to the design
- Open [the demo](https://ubuntu-com-14665.demos.haus/kubernetes/resources)
- Compare against [the figma design](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=0-1&p=f&t=BOvAzB2thrZyele5-0)
- Compare against [the copydoc …

feat(/kubernetes/resources): Rebranding

---

static/sass/styles.scss
templates/kubernetes/compare.html

- applied redesign as per [doc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit?tab=t.0) and [design](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=428-8718&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14660.demos.haus/kubernetes/compare
Fixes https://warthogs.atlassian.net/browse/WD-12877

feat: /kubernetes/compare redesign

---

requirements.txt
templates/base_index.html
templates/templates/base.html
webapp/app.py

- add `Flask-Squeeze` package to compress js and css
- defer one of the JS files that is not needed immediately
- lazy load all images on the home page that are not visible initially
- Compare JS and CSS files sizes of the demo instance and production and check that it has significantly decreased.

add compression of js/css assets

---

requirements.txt
webapp/app.py

- This is the next step after [this PR](https://github.com/canonical/ubuntu.com/pull/14672), doing the assets compression on the flask-base level.
- Check that the resources on the demo and production are the same. You can do that by using Network tab of the dev console. For example, compare the sizes of `styles.css` on the demo and on production, and check that it didn't become bigger.

upgrade to flask-base 2.1.0 that does the assets comression

---

templates/legal/companies.html

- Add Canonical Services Spain Limited and Canonical Support Services Ireland Limited to our public companies page
- Go to /legal/companies
- Check the two new companies are there

fix(content): Add two company addresses to the legal section

---

static/sass/_pattern_navigation.scss

- Fixed onhover
- Open this [demo](https://ubuntu-com-14686.demos.haus/) on tablet or mobile screen size
- Open the meganav by clicking the 'menu'
- Navigation to the bottom layer of any navigation item. ex. 'Products' > 'Featured'.
- Hover your mouse over the dropdown items
- Verify hover effect is applied
Fixes #[WD-15094](https://warthogs.atlassian.net/browse/WD-15094)
[WD-15094]: https://warthogs.atlassian.net/browse/WD-15094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-15094] fix: onhover not working on tablet/mobile meganav

---

templates/shared/forms/form-fields.html
templates/shared/forms/form-template.html

- Pass an optional formId prop when including form-template.html. If it is passed, it will be used for the formId submitted to marketo, otherwise the one specified in form-data.json will be used.
Fixes #[WD-18686](https://warthogs.atlassian.net/browse/WD-18686)
[WD-18686]: https://warthogs.atlassian.net/browse/WD-18686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-18686] Introduced an optional formId prop to form-template.html

---

templates/aws/fips.html

- Compare with [copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit?tab=t.0)
https://warthogs.atlassian.net/browse/WD-18368

copy update: /aws/fips

---

templates/kubernetes/index.html

- Apply rebranding for /kubernetes landing page
- Go to https://ubuntu-com-14683.demos.haus/kubernetes
- Check against [copy doc](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit?tab=t.0) and [Figma](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=0-1&p=f&m=dev)
- Toggle the switch in "Kubernetes Discoverer" and check that it updates card details as expected
Fixes [WD-12944](https://warthogs.atlassian.net/browse/WD-12944)
[WD-12944]: https://warthogs.atlassian.net/browse/WD-12944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

feat: Rebrand /kubernetes index page

---

static/sass/_pattern_navigation.scss
templates/security/fips.html
templates/security/form-data.json
templates/shared/forms/form-fields.html
templates/shared/forms/form-template.html

- Applied redesign per [doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit?tab=t.0) and [design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=669-2956&p=f&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14694.demos.haus/security/fips
Fixes https://warthogs.atlassian.net/browse/WD-12035, https://github.com/canonical/ubuntu.com/issues/14633

feat: /security/fips redesign

---

templates/kubernetes/what-is-kubernetes.html

- Rebrand /kubernetes/what-is-kubernetes
- Go to https://ubuntu-com-14677.demos.haus/kubernetes/what-is-kubernetes
- Check against [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit?tab=t.0) and [Figma](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=605-9862&m=dev)
Fixes [WD-12891](https://warthogs.atlassian.net/browse/WD-12891)
[WD-12891]: https://warthogs.atlassian.net/browse/WD-12891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Apply rebranding for /kubernetes/what-is-kubernetes

---

package.json
templates/security/cc.html
yarn.lock

- Rebrand /security/cc
- Upgrade vanilla version
- [Demo](https://ubuntu-com-14692.demos.haus/security/cc)
- [Design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=435-5255&p=f&m=dev)
- [Copydoc](https://docs.google.com/document/d/1JLnHR9Xuuc1t6ojrnBuMWir5XABgf1L7WVpGGtlLaBo/edit?tab=t.0)
Fixes # [Wd-12036](https://warthogs.atlassian.net/browse/WD-12036)

WD-12036 Dev Rebrand /security/cc

---

redirects.yaml

- Add redirect rules for static case studies that have been migrated from u.com to c.com
- Go to https://ubuntu-com-14704.demos.haus/case-study/esa
- See that it redirects to the case study on c.com
- Repeat for 
- https://ubuntu-com-14704.demos.haus/case-study/sbi-bits
- https://ubuntu-com-14704.demos.haus/case-study/grundium-ubuntu-pro-for-devices
- https://ubuntu-com-14704.demos.haus/case-study/ubuntu-pro-support-for-games-developer
Fixes [WD-18974](https://warthogs.atlassian.net/browse/WD-18974)
[WD-18974]: https://warthogs.atlassian.net/browse/WD-18974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …

Add redirects for static case studies

---

redirects.yaml

- Add redirect link for static case study
- Go to https://ubuntu-com-14706.demos.haus/case-study/lucid-aws-fedramp-compliance-case-study/
- See that it redirects to the case study on c.com
Fixes 

fix: Add redirect for static case study

---

redirects.yaml
templates/containers/chiseled/index.html
templates/kubernetes/charmed-k8s.html
templates/support/index.html

- Fix broken links reported on ["Links on live"](https://github.com/canonical/ubuntu.com/actions/runs/13130367860) 
- Drive-by: Refactor redirect rules for case study
- Go to https://ubuntu-com-14707.demos.haus/containers/chiseled
- Scroll to "Using chisel in Rockcraft" and "Install package slices into a rock"
- Click on the links and see that it redirects to a working doc page
- Go to https://ubuntu-com-14707.demos.haus/support
- Scroll to "Rocks", click and see that the link works
Fixes [WD-18982](https://warthogs.atlassian.net/browse/WD-18982)
[WD-18982]: …

fix: Fix reported broken links 

---

templates/security/oval.html

- Added ID to headers as requested
- Go to https://ubuntu-com-14712.demos.haus/security/oval#how-we-use-oval
- See that the page scrolls to the respective header section
- Repeat with the other ID hashes
Fixes #12487 and [WD-18981](https://warthogs.atlassian.net/browse/WD-18981)
[WD-18981]: https://warthogs.atlassian.net/browse/WD-18981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add header ID to /security/oval

---

static/sass/_pattern_cve.scss
templates/security/cves/cve.html

- Added line wrapping for "Other references" links 
- View the site locally in your web browser at: https://ubuntu-com-14720.demos.haus/security/CVE-2024-12084
- See that this is not happening:
Reported on [MM](https://chat.canonical.com/canonical/pl/aid9zr8uw7ro9faf4qj5zgcabh)

fix: Add line wrapping to references links

---

requirements.txt
static/sass/styles.scss
templates/security/disa-stig.html

- Redesign [/security/dis-stig](https://ubuntu-com-14702.demos.haus/security/disa-stig) to match the [figma design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=911-5131&t=KfUtcoGP63SEgk98-0)
- Some minor content/spelling changes 
- Created `no-full-stop` modifier class for use on `p-stepped-list`
- Open [the demo](https://ubuntu-com-14702.demos.haus/security/disa-stig)
- Compare against the [figma design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=911-5131&t=KfUtcoGP63SEgk98-0)
- Compare against the [copydoc](https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit?tab=t.0)
- Check the page on all screen sizes
Fixes https://warthogs.atlassian.net/browse/WD-12037

feat(/security/disa-stig): Page redesign

---

templates/security/disclosure-policy.html

- Applied redesign as per [doc](https://docs.google.com/document/d/1WdamniXOHemuPzl6vESYD9StPgh4-PepbqdVHYrzbuI/edit?tab=t.0) and [design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=851-3406&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14723.demos.haus/security/disclosure-policy
Fixes https://warthogs.atlassian.net/browse/WD-12040

feat: /security/disclosure-policy rebrand

---

templates/containers/index.html

- Update the “[Learn about Chiselled Ubuntu](https://ubuntu.com/blog/combining-distroless-and-ubuntu-chiselled-containers)” link as specified in the [copy doc](https://docs.google.com/document/d/1OtyfNeA--EJgpgvDzqcbJ8jqa6d9H5H9xyxHNxcKXvc/edit?tab=t.0)
- Go to https://ubuntu-com-14729.demos.haus/containers
- Click on "Learn about Chiselled Ubuntu" and see that it redirects to the blog
Fixes [WD-19154](https://warthogs.atlassian.net/browse/WD-19154)
[WD-19154]: https://warthogs.atlassian.net/browse/WD-19154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update chiselled link

---

templates/base_index.html

- Update the phrasing used for a link as requested in this [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?tab=t.0)
Check that the phrasing of the link has been updated as requested in the copy doc.
Open [demo](https://ubuntu-com-14730.demos.haus/) and scroll to the "Energise your engineers" section. The first link in that section should now be changed to "Download our guide to adopting Linux securely in your enterprise"
https://warthogs.atlassian.net/browse/WD-19133

copy-update: update the phrasing used for the "adopting secure enterprise linux desktop" link

---

templates/kubernetes/docs/index.md

- Add links to Canonical Kubernetes on the landing page for Charmed Kubernetes

K8s docs update landing page update with link to Canonical Kubernetes

---

static/js/src/chart-data.js
templates/about/release_cycles/releases-table.html

- Updated "end of support" dates for 18.04 and 20.04 as per [sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit?disco=AAABeA61apo) 
- View the site locally in your web browser at: https://ubuntu-com-14738.demos.haus/about/release-cycle#ubuntu
- See that the chart and table have been updated 
Fixes https://warthogs.atlassian.net/browse/WD-19280

Update Ubuntu release chart 

---

templates/security/docker-images.html
templates/security/oval.html

- Rebrand /security/oval based on [Design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=722-22966&m=dev), no changes in copy doc
- Drive-by: Update /security/docker-images to use `p-cta-block` classes where necessary
- Note: Waiting for chart placeholder from design
- Go to https://ubuntu-com-14734.demos.haus/security/oval
- Check that design matches Figma
Fixes [WD-12041](https://warthogs.atlassian.net/browse/WD-12041)
[WD-12041]: https://warthogs.atlassian.net/browse/WD-12041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Apply rebranding for /security/oval

---

navigation.yaml

- Remove 'Charmed Kubernetes' from the /kubernetes secondary-nav
- Go to /kubernetes
- See the is no 'Charmed Kubernetes' in the secondary nav
Fixes https://warthogs.atlassian.net/browse/WD-19220

feat: Remove 'Charmed Kubernetes' from the /kubernetes secondary-nav

---

requirements.txt
templates/base_index.html

- updated the images we were pulling directly from the asset manager to use the image-template (and this cloudinary)
- render the decoration images as jpeg (see example below)
- Bump the version of the image-template
- Check that the logos are the same in [the demo](https://ubuntu-com-14713.demos.haus/) as they are on [the live page](https://ubuntu.com/)
- Check no quality is lost and all alt text is retained
Fixes https://warthogs.atlassian.net/browse/WD-19037

feat: Use image template for logo on u.com

---

templates/contact-us/newsletter-opt-in.html

- Add appropriate returnURL to /contact-us/newsletter-opt-in so it doesn't fail
- Go to https://ubuntu-com-14749.demos.haus/contact-us/newsletter-opt-in
- Fill in the form and submit
- See it succeeds and redirects back the the sign-up page
Fixes https://warthogs.atlassian.net/browse/WD-19388

fix(/contact-us/newsletter-opt-in): Add appropriate returnURL

---

static/sass/_pattern_cve.scss
templates/security/cves/_pagination.html

- Commented out the options to get more than 20 notices on a single page since that is not supported by api yet.
- We will check if it possible to get 20+ results on singel page and update it accordingly.
- Please visit demo(https://ubuntu-com-14747.demos.haus/security/cves?q=) and see at the bottom for "Results per page" and it should show only 2 options for 10 and 20.
Fixes  # [WD- 19371](https://warthogs.atlassian.net/issues/WD-19371)
#14746  …

Commented the pagination for CVEs

---

requirements.txt
templates/engage/_article-card.html
templates/engage/index.html
webapp/views.py

- Add multiple filters functionality on engage page index
- Users can now search up to three filters simultaneously. Previously this was set at one
- Go to https://ubuntu-com-14740.demos.haus/engage
- Select one filter from the dropdown
- See that page loads, select another filter. 
- Repeat and see that page loads according to selected filters.
Fixes [WD-16129](https://warthogs.atlassian.net/browse/WD-16129)
[WD-16129]: https://warthogs.atlassian.net/browse/WD-16129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add multiple filters functionality on engage pages

---

webapp/app.py

- Excluded non-english language tags from blogs
- [Demo](https://ubuntu-com-14761.demos.haus/cloud/public-cloud)
- Check that we only see english blogs on page such as [/cloud/public-cloud](https://ubuntu-com-14761.demos.haus/cloud/public-cloud) ,  [/hpe](https://ubuntu-com-14761.demos.haus/hpe), [/supermicro](https://ubuntu-com-14761.demos.haus/supermicro)
Fixes # [WD-19441](https://warthogs.atlassian.net/browse/WD-19441) …

WD-19441 exclude non-english language tags from blogs

---

releases.yaml
templates/desktop/wsl/index.html

- Updated 24.04.2 checksums
- Updated /desktop/wsl cta as per [doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit?tab=t.0#heading=h.lt3ybzv5m9is)
- View the site locally in your web browser at: https://ubuntu-com-14771.demos.haus/download/server, and https://ubuntu-com-14771.demos.haus/download/desktop and see that both download as expected
-  https://ubuntu-com-14771.demos.haus/desktop/wsl and see that the main CTA has been updated and that the download works as expected
Fixes https://warthogs.atlassian.net/browse/WD-19524

Update checksums for 24.04.2

---

templates/appliance/about.html

- Rebranded /appliance/about
- View the site in your web browser using this [demo](https://ubuntu-com-14760.demos.haus/appliance/about)
- Make sure the page matches the following:
- [Copydoc](https://docs.google.com/document/d/1UM4K9n9SFNiWdmKIBnPGCsjLQrPSOnqZHMNIMwQ2CZI/edit?tab=t.0)
- [Figma Design](https://www.figma.com/design/POgmRw4Rpq1hlgaD9DN8mS/ubuntu.com%2Fappliance?node-id=100-3421)
Fixes #[WD-16576](https://warthogs.atlassian.net/browse/WD-16576)
[WD-16576]: https://warthogs.atlassian.net/browse/WD-16576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-16576] Rebranded /appliance/about page

---

.github/workflows/blog-links.yaml

- Update the blog check which reports in the Marketing channel to weekly instead of daily.
- Check the cron change is correct

fix(ci): Update broken links to weekly

---

templates/download/desktop/thank-you.html

- Reintroduced the verification widget for checking desktop downloads
- Download the desktop iso
- Click "verify download"
- See that is now displayed how to verify the download
Fixes https://github.com/canonical/ubuntu.com/issues/14711
Fixes https://warthogs.atlassian.net/browse/WD-19019

WD-19019 - fix: add checksums to verify desktop download

---

meganav.yaml
navigation.yaml
templates/kubernetes/documentation.html
templates/kubernetes/form-data.json

- Build /kubernetes/documentation page based on [copydoc](https://docs.google.com/document/d/1oBsYFMqGY1sRMUeuy7ue_oDSHpHqYaua-Z33fGRxx8Y/edit?tab=t.0) and [figma](https://www.figma.com/design/l4wd5ry1KQ6fHbrWptvQbE/24.04-Kubernetes-bubble?node-id=0-1&p=f&t=RGGAnXltDyWYZEQU-0)
- Check out [the demo](https://ubuntu-com-14764.demos.haus/kubernetes/documentation)
- Check the content matches
- Check on all screen sizez
- *note* - the link to `/kubernetes/charmed-k8s/docs` won't work until [this PR](https://github.com/canonical/ubuntu.com/pull/14750) is merged
Fixes https://warthogs.atlassian.net/browse/WD-19219

feat: Build /kubernetes/documentation page

---

static/js/src/dynamic-forms.js
static/js/src/prepare-form-inputs.js
templates/aws/form-data.json
templates/shared/forms/form-fields.html
webapp/handlers.py

- Add support for "other" option with textarea using js.
- Remove names from checkboxes for fieldSets named "checkbox" or "checkbox-visibility"
- Drive by: updated form on /aws to include missing inputType for checkbox fieldsets.
- Drive by: added a missing filter named "slug"
- Open this [demo/iot/smart-city#get-in-touch](https://ubuntu-com-14689.demos.haus/internet-of-things/smart-city#get-in-touch) in your browser.
- Verify the form opens up.
- Fill in the form and make sure to select any/all checkboxes/ radios with "Other" option.
- Submit the form to make sure it works.
- Monitor the payload from devtools to make sure the names are stripped from checkboxes.
- Verify form submission in Marketo if possible and have access.
Also do the same as above for …

[WD-18697] feat: Add "other" option with textarea for radio and checkbox inputs in form generator on u.com

---

templates/macros/_macros-resource.jinja
templates/security/compliance-automation.html
templates/shared/_cra-banner.html

- Apply rebranding for /security/compliance-automation based on design changes
- No changes made to the content
- [Figma](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=1617-5856&m=dev)
- [Copy doc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit?tab=t.0) 
- Go to https://ubuntu-com-14767.demos.haus/security/compliance-automation
- Check that design matches Figma
- Try on small and medium screens
Fixes [WD-18751](https://warthogs.atlassian.net/browse/WD-18751)
[WD-18751]: https://warthogs.atlassian.net/browse/WD-18751?atlOrigin=eyJpIjoiNWRk …

feat: Rebrand /security/compliance-automation

---

templates/shared/forms/interactive/smart-city.html

- Remove "name" attributed from checkbox input
- Show and hide "Other" checkbox text input when selected 
- Go to https://ubuntu-com-14785.demos.haus/iot/smart-city#get-in-touch
- Select "Other" checkbox, see that text input shows up on select
- Fill up form, submit and see that it goes through Marketo successfully
Fixes [WD-19633](https://warthogs.atlassian.net/browse/WD-19633)
[WD-19633]: https://warthogs.atlassian.net/browse/WD-19633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: /iot/smart-home form payload submission

---

templates/landscape/form-data.json
templates/landscape/index.html
templates/landscape/managed/form-data.json
templates/landscape/managed/index.html
templates/shared/forms/form-fields.html

- Added two forms, one for "managed" and one for "landing, features, compare"
- Moved "templates/landscape/managed.html" to "templates/landscape/managed/index.html"
- Open the [demo](https://ubuntu-com-14685.demos.haus/landscape) in your browser
- Navigate to the following pages
- Landing
- Features
- Managed
- Compare
- Click on "Contact us" buttons
- Make sure the form is visible
- Submit the forms and make sure they work.
Fixes #[WD-18634](https://warthogs.atlassian.net/browse/WD-18634)
[WD-18634]: https://warthogs.atlassian.net/browse/WD-18634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-18634] Ref: use form generator on landscape bubble

---

static/js/src/chart-data.js
templates/about/release_cycles/k8s-eol.html
templates/about/release_cycles/k8s-lts.html

- Copy update on /about/release-cycle#canonical-kubernetes-release-cycle
- Go to [/about/release-cycle#canonical-kubernetes-release-cycle](http://localhost:8001/about/release-cycle#canonical-kubernetes-release-cycle)
- Compare against the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit?disco=AAABeENlIWs)
[WD-19328](https://warthogs.atlassian.net/browse/WD-19328)
[WD-19328]: https://warthogs.atlassian.net/browse/WD-19328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy update on /about/release-cycle#canonical-kubernetes-release-cycle

---

static/js/src/prepare-form-inputs.js
templates/embedded/form-data.json
templates/embedded/index.html
templates/shared/forms/form-fields.html

- Added 'setupOtherInputs' method from c.com to setup fields that require additional input.
- Added form-data.json for embedded form
- Updated form-fields.html to reflect 'other-input'
- Added a slug filter
- Open the [demo](https://ubuntu-com-14684.demos.haus/embedded#get-in-touch) in your browser
- Fill all the fields and submit the form
- Make sure the form submission works and also verify from Marketo side if possible.
- Try a few times with different submissions.
- Make sure the form is redirected to contact-success-banner.
Fixes #[WD-18591](https://warthogs.atlassian.net/browse/WD-18591)
[WD-18591]: https://warthogs.atlassian.net/browse/WD-18591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-18591] Ref: Use form generator on "u.com/embedded"

---

templates/engage/index.html
templates/engage/shared/_tr_engage_form.html
templates/engage/shared/_tr_thank-you.html

- Added Turkish language filter.
- Added turkish engage form template and thank-you template.
- Check the demo [here](https://ubuntu-com-14766.demos.haus/engage/ubuntu-security-in-turkish) and see if the form renders in Turkish, also try out turkish filter on engage [homepage](https://ubuntu-com-14766.demos.haus/engage/) 
Fixes # [WD19462](https://warthogs.atlassian.net/browse/WD-19462)

WD-19462 Added turkish language support for engage forms

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx

- `userInfo` always exists for both first-time buyers and existing users, so first-time buyers will always get undefined in the address on line 303 if checking `userInfo`
- Get the address from form values always instead of checking `userInfo` and prevent sending `undefined` values
- Go into the local branch and console.log address and check the values (for both first-time buyers and existing users)
Fixes #https://warthogs.atlassian.net/browse/WD-18214

Prevent undefined values from being sent for the address

---

templates/containers/chiseled/index.html

- Removed html suffix from docs link
- Open the [demo](https://ubuntu-com-14803.demos.haus/containers/chiseled) and scroll to the documentation section.
- Click `Install packages slices into a rock`

fix: update link

---

templates/security/osv.html

Add Security OSV page
- View the site locally in your web browser at: https://ubuntu-com-14765.demos.haus/security/osv
- Make sure that the page matches the [copy docs](https://docs.google.com/document/d/1pWZXod5oXtI5In9FHnM0gBs1OY8g7J_3ioeivBZ6KZA/edit?tab=t.0) and the [figma design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=1865-4608&m=dev)
Fixes WD-18848

Security OSV page

---

templates/security/esm.html

- Applied refresh as per [doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit?tab=t.0) and [design](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=1950-19833&m=dev)
- View the site locally in your web browser at: https://ubuntu-com-14795.demos.haus/security/esm
Fixes https://warthogs.atlassian.net/browse/WD-12043

feat: /security/esm refresh 

---

templates/aws/form-data.json
templates/kubernetes/form-data.json
templates/shared/forms/form-fields.html

- Add first name, last name and email as default active contact fields on form generator
- Remove duplicated contact fields on affected forms
- Go to /aws#get-in-touch and /k8s#get-in-touch
- See that first name, last name and email are present
- Submit form, check payload and see that it goes through Marketo successfully
Fixes [WD-19672](https://warthogs.atlassian.net/browse/WD-19672)
[WD-19672]: https://warthogs.atlassian.net/browse/WD-19672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add names and email as default active contact fields

---

templates/about/release-cycle.html

- Replace the OpenStack release cycle tab with shorter paragraph and link.
- Update to US English.
https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit?tab=t.0
- Go to [/about/release-cycle#openstack-release-cycle](https://ubuntu-com-14817.demos.haus/about/release-cycle#openstack-release-cycle).
- Under OpenStack tab at the bottom check that the content has a short paragraph (see the copy doc) and link to a Read The Docs page.
https://warthogs.atlassian.net/browse/WD-19544

feat: update openstack release cycle tab

---

templates/download/desktop/thank-you.html
templates/templates/_getfeedback.html
templates/templates/_navigation.html
templates/templates/_notifications.html
templates/templates/_tag_manager.html
templates/templates/base.html

- Fixed several HTML validation errors across the base templates. _Left the `Info: Trailing slash on void elements` warnings as I believe that is our coding standards, based on linting_
- Removed some unnecessary piece
- Copy the source code of the demo homepage into https://validator.w3.org/nu/#textarea
-  See there are ~120 issues
- Do the same for production and see its ~160 issues

fix(a11y): Refactor the HTML validator issues on the base templates

---

requirements.txt
templates/security/vulnerabilities/vulnerability-detailed.html
webapp/views.py

- Updates the cache on vulnerability pages to `max-age=900, stale-while-revalidate=1200, stale-if-error=3600`
- Adds a fallback to the vulerability_detailed.html in case the proper format has not been used
- Use the latest version of discourse module (still a [pr](https://github.com/canonical/canonicalwebteam.discourse/pull/207))
- Open [the demo](https://ubuntu-com-14789.demos.haus/security/vulnerabilities)
- Go to any specific vulnerability
- Make an update to it [in discourse](https://discourse.ubuntu.com/c/project/security-vulnerabilities/308)
- _without_ refreshing, re-visit the page the see if the update is visible within  the caching parameters above
Fixes https://warthogs.atlassian.net/browse/WD-19706

Implement a specific cache policy for vulnerabilities & use latest discourse module branch

---

templates/sitemap_index.xml

- Removed link from sitemap index, was missed in [this pr](https://github.com/canonical/ubuntu.com/pull/14823)
- View the site locally in your web browser at: https://ubuntu-com-14829.demos.haus/sitemap.xml and see that `https://ubuntu.com/server/docs/sitemap.xml` is not listed
Fixes [link checker](https://github.com/canonical/ubuntu.com/actions/runs/13693409020)

chore: Remove stale link from sitemap index

---

requirements.txt
webapp/app.py

- Published sitemaps-repo on test PyPi - [package here](https://test.pypi.org/project/canonicalwebteam.sitemaps-parser/1.0.0/)
- Update `requirements.txt` to use the package
- Note: The package is currently on test pypi. It will be migrated outside of test before this feature branch is merged
- Check that [ubuntu-com-14827.demos.haus](https://ubuntu-com-14827.demos.haus/) loads
- Go to https://ubuntu-com-14827.demos.haus/sitemaps_parser
- See that it shows JSON field of directory tree
Fixes [WD-19979](https://warthogs.atlassian.net/browse/WD-19979)
[WD-19979]: …

feat: Update requirements to import pypi package

---

webapp/views.py

- Add new "Event" resource type
- View the site locally in your web browser at: https://ubuntu-com-14833.demos.haus/engage
- See that "Event" appears as an option under the resource type filter and see that it filters as expected
Fixes https://warthogs.atlassian.net/browse/WD-20034

feat: Add new resource type filter on /engage overview

---

templates/pricing/pro.html

- Remove "swift" from Ceph section.
- Updated Ubuntu version for "NIST-certified FIPS crypto-modules"
- Add free pro section (this will need a design review as I couldn't find any examples of tables behind accordions).
https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit?tab=t.0#heading=h.2yomf46629v0
- Go to [/pricing/pro](https://ubuntu-com-14756.demos.haus/pricing/pro).
- See that Ubuntu Pro for personal users section has been added at the top.
- Click 'Ubuntu Pro for personal users' and the table should appear.
- Look for the "NIST-certified FIPS crypto-modules" text in the "Security and compliance" table and check that the muted text has been updated to "24.04".
- Scroll down and check that "swift" has been removed from the Ceph section (halfway down …

feat: refresh /pricing/pro

---

package.json
yarn.lock

- Bump vanilla version to 4.21.1
- View the site locally in your web browser at: https://ubuntu-com-14835.demos.haus/
- This version shouldn't introduce any breaking changes, but click through a couple pages to double check nothing looks broken 
Fixes https://warthogs.atlassian.net/browse/WD-19622

chore: Bump vanilla version

---

templates/templates/docs/shared/_docs.html

- Added scroll-margin to h2 and h3
- View the site in your web browser at: 
- https://ubuntu-com-14836.demos.haus/landscape/docs/install-landscape-client
- https://ubuntu-com-14836.demos.haus/landscape/docs/install-fips-hardened-landscape-server
- Click on different headers on both pages and verify the text is scrolled into view properly
Fixes #[WD-8780](https://warthogs.atlassian.net/browse/WD-8780)
[WD-8780]: https://warthogs.atlassian.net/browse/WD-8780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-8780]  fix: docs link scroll margin for same page links

---

templates/base_index.html

- Replaced img tags with image module
- View the site locally in your web browser at: https://ubuntu-com-14849.demos.haus/
- Verify the replaced images are showing correctly.

chore: Use image module on ubuntu home page

---

templates/server/index.html

- Fixed a broken link
- View the site  in your web browser at: https://ubuntu-com-14853.demos.haus/server
- Scroll down to the section named "Infrastructure and applications foundation"
- Click on the "[2020 HackerEarth Developer Survey](https://www.hackerearth.com/recruit/developer-survey)" link
- It should take you to hackerearth.com correctly.
Fixes #[WD-19716](https://warthogs.atlassian.net/browse/WD-19716)
[WD-19716]: https://warthogs.atlassian.net/browse/WD-19716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-19716] fix: replace broken link

---

requirements.txt
webapp/views.py

- Added a field called "is_static" on the new case-studies at canonical.com/case-study
- Passed this field as a separate param
- View the site  in your web browser at: https://ubuntu-com-14848.demos.haus/engage
- Verify the engage pages are loading normally
- Make sure they don't include the static case-studies (case-studies that are hosted statically at canonical.com)
Fixes #[WD-19941](https://warthogs.atlassian.net/browse/WD-19941)
[WD-19941]: https://warthogs.atlassian.net/browse/WD-19941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-19941] Exclude new(static) case-studies from engage page

---

templates/security/notices/usn.html
webapp/security/views.py

- we need the "Available with Ubuntu Pro" tag for the pocket "esm-infra-legacy" as we have for "esm-infra";
- esm-infra-legacy pocket already exists in https://github.com/canonical/ubuntu-com-security-api and is being pushed by the security team for a while;
- without this tag there is no indication that an update is placed in a different place and could be mislead our users
- for now, I don't see a need to add this pocket in other places like Entitlements and in the list of products in the ubuntu advantage category, this feels like a commercial discussion which I don't want to drive here in this PR
- Be sure to test on mobile, …

security web: add esm-infra-legacy pockets WD-17330 WD-19534

---

templates/appliance/adguard/index.md
templates/appliance/lxd/index.md
templates/appliance/mosquitto/index.md
templates/appliance/nextcloud/index.md
templates/appliance/openhab/index.md
templates/appliance/plex/index.md
templates/appliance/shared/_base_appliance_index.html

- Rebranded the following pages according to the [Figma design](https://www.figma.com/design/POgmRw4Rpq1hlgaD9DN8mS/ubuntu.com%2Fappliance?node-id=382-8512&t=j9cqoh28OiR3eBaA-1):
- [/appliance/adguard](https://ubuntu-com-14856.demos.haus/appliance/adguard)
- [/appliance/plex](https://ubuntu-com-14856.demos.haus/appliance/plex)
- [/appliance/lxd](https://ubuntu-com-14856.demos.haus/appliance/lxd)
- [/appliance/mosquitto](https://ubuntu-com-14856.demos.haus/appliance/mosquitto)
- [/appliance/openhab](https://ubuntu-com-14856.demos.haus/appliance/openhab)
- [/appliance/nextcloud](https://ubuntu-com-14856.demos.haus/appliance/nextcloud)
- Run the site using the command ./run serve or dotrun
- …

[WD-16587] rebrand /appliance/adguard and other similar pages

---

static/files/sitemap_tree.xml
templates/sitemap_children.xml
templates/sitemap_template.xml

- Refactor sitemap templates to reduce redundant code
- Update `sitemap_tree.xml` with new template, removing unnecessary new lines
- Go to `sitemap_tree.xml` file on GH file changes
- See that the file does not have redundant new lines
Fixes #

chore: Refactor sitemap templates

---

templates/internet-of-things/smart-displays.html

- Swap Ubuntu Frame and Core images
- Go to /internet-of-things/smart-displays
- Scroll down to "Get started now with Ubuntu Core and Frame"
- See that the images for Ubuntu Core and Frame are in the correct section
Fixes [WD-20418](https://warthogs.atlassian.net/browse/WD-20418) and #14864 
[WD-20418]: https://warthogs.atlassian.net/browse/WD-20418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Swap frame and core images

---

templates/containers/chiseled/index.html

- Update chiseled doc link with working link
- Broken link reported here https://github.com/canonical/ubuntu.com/actions/runs/13917651784/job/38943545779
- Go to /containers/chiseled
- Scroll down to "Get started now and ship with chiseled Ubuntu"
- Click on it, see that it redirects to [docs](https://documentation.ubuntu.com/chisel/en/latest/tutorial/getting-started/?_ga=2.248922628.2004906391.1742270386-1966056870.1729153128&_gl=1*tyk574*_gcl_au*MTE2NzUzMTQ3Ni4xNzM3MzU5MDc0) successfully
Fixes #

fix: Update chiseled doc link

---

konf/site.yaml
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx

- Fixed wrong data being shown for free Pro subscriptions on shop
- Be sure to test on mobile
*Fix only for mobile*
- Visit [/pro/subscribe](https://ubuntu-com-14860.demos.haus/pro/subscribe)
- Select myself as the user in the first section
- It should show the price as free and quantity as 5
Fixes [#WD-20369](https://warthogs.atlassian.net/browse/WD-20369)
Old:
New:

fix incorrect data being shown for free Pro on subscribe

---

templates/containers/chiseled/index.html

- Update broken link for chiseled docs
- Go to /containers/chiseled
- Scroll down to "Create a chiseled Ubuntu base image for C/C++..."
- Click on link, see that it redirects to the docs and not 404
Fixes [broken link report](https://github.com/canonical/ubuntu.com/actions/runs/13941081506/job/39017886532)

fix: Update broken link for chiseled docs

---

webapp/certified/helpers.py

This change adds a special condition in the `get_download_url` to check whether the platform in question is NVIDIA Jetson. If this is the case, it returns https://ubuntu.com/download/nvidia-jetson
Fixes [C3-1048](https://warthogs.atlassian.net/browse/C3-1048)
It changes where the "Download" button on the following three configuration points to. Previously it was pointing to: "https://ubuntu.com/download/core" while now it is "https://ubuntu.com/download/nvidia-jetson"
* …

Add custom download URL for NVIDIA Jetson platforms

---

templates/download/qualcomm-iot/tabs/rb3-gen2-lite-tab.html
templates/download/qualcomm-iot/tabs/rb3-gen2-tab.html

- Update urls as per this [ticket](https://warthogs.atlassian.net/browse/WD-20460)
- go to `/download/qualcomm-iot`
- links for "image installation instructions" are updated for both tabs as per copy update
Fixes [WD-20460](https://warthogs.atlassian.net/browse/WD-20460)
[WD-20460]: https://warthogs.atlassian.net/browse/WD-20460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: update qualcomm links

---

.github/workflows/pr.yaml

Note: revert changed HTML files before merging
- Replace `tj-actions/changed-files` with `git diff` actions to track changed files in a PR
- Introduced minor changes to template files for `git diff` to track changes
- Go to GH actions (either from the checks below or [this link](https://github.com/canonical/ubuntu.com/actions/runs/13941058447/job/39017825278))
- Go to `lint-jinja` action and expand it
- See that it displays the changed files as expected
Fixes [WD-20401](https://warthogs.atlassian.net/browse/WD-20401)
[WD-20401]: https://warthogs.atlassian.net/browse/WD-20401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

chore: Use git diff to get changed files

---

.github/workflows/live-links.yaml

- Updated `live-links.yaml` cron job to ignore warnings and errors 471, 500, 503, 504, 400
- Tried to use negative matching to ignore non-404 files but it did not work as expected, it could be due to how `linkchecker` searches for matches [here](https://github.com/linkchecker/linkchecker/blob/master/linkcheck/checker/urlbase.py)
- Go to `live-links` action [here](https://github.com/canonical/ubuntu.com/actions/runs/13966763934/job/39098831580?pr=14722)
- Check that it does not report any failing links
- Go to [today's cron job](https://github.com/canonical/ubuntu.com/actions/runs/13964030095/job/39090439112), see that it reports 471
- Compare it with this PR's `live-links` action and see that the 471 error is not reported
Fixes [WD-19063](https://warthogs.atlassian.net/browse/WD-19063) …

chore: Update linkchecker to report 404 errors only

---

templates/ai/index.html

- Update `Get the AI consulting datasheet` to match copydoc
- Go to https://ubuntu-com-14885.demos.haus/ai
- Go to `Get the AI consulting datasheet` link and see that it links to the same URL provided in copy doc
Fixes [WD-20437](https://warthogs.atlassian.net/browse/WD-20437)
[WD-20437]: https://warthogs.atlassian.net/browse/WD-20437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Update AI datasheet link

---

requirements.txt
templates/certified/model-details.html
tests/cassettes/TestCertification.test_note_rendering.yaml
tests/test_certification.py
webapp/certified/helpers.py
webapp/handlers.py

**NOTE: This PR resolves a security issue found on the website.**
The hardware certification team introduces Markdown support in certificate notes (initially in https://github.com/canonical/hexr/pull/575). The same support is introduced here.
While working on this PR, I noticed that if a note contains raw HTML code the current production code on the `ubuntu.com` website renders it, even if it's a script. For example, if a note contains `<script>alert("Hello!")</script>`, an alert will appear:
This security issue is fixed in this PR, and raw HTML code gets escaped (see screenshots for more)
- Be sure to test on mobile, tablet and …

Add markdown support for certification notes and escape raw-html content

---

templates/legal/data-privacy/enquiry.html

- Remove unexpected `endblock` that was throwing a [Sentry error](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/99862/?query=is%3Aunresolved)
Fixes #

fix: Remove unexpected block

---

templates/pricing/pro.html

- Add small text update to the /pricing/pro page
- visit https://ubuntu-com-14893.demos.haus/pricing/pro
- make sure the text exists from the ticket below
Fixes #https://warthogs.atlassian.net/browse/WD-20376

Update text on Pro pricing page

---

.github/workflows/pr.yaml
templates/training/index.html

- Remove the needed `outer_block` and `footer_extra`
- Fix lint-jinja
- Go to https://ubuntu-com-14896.demos.haus/training and see that it loads correctly
- See lint-jinja passes
Fixes https://warthogs.atlassian.net/browse/WD-20319
https://warthogs.atlassian.net/browse/WD-20568

fix: Use standard jinja formatting on /training and fix lint-jinja

---

.github/workflows/pr.yaml

- Add git `--diff-filter` to track ACMR actions 
- **A**dded, **C**reated, **M**odified, **R**enamed
- Allows`lint-jinja` action to run on these ACMR tracked files only
- See that `lint-jinja` action passes
- Previously throwing an error due to renamed file not being tracked correctly
Fixes #

chore: Add git diff-filter

---

templates/legal/_base_legal_markdown.html
templates/shared/contextual_footers/_further_reading.html

- Fix the broken formatting of the contextual footer further reading section
- Remove the space between legal content and the contextual footer
1. Open the demo
2. Go to the legal pages 
3. See the contextual footer loads the further reading content

WD-20581 fix: contextual footer further reading section

---

meganav.yaml
navigation.yaml
static/sass/styles.scss
templates/summit/_base_summit.html
templates/summit/index.html
templates/summit/shared/_latest-blogs_summit.html

- Redesigned ubuntu.com/summit page.
- Added custom animations according to framer [demo](https://adaptable-luxury-619824-34344745f.framer.app/).
- Added common blog section.
- [Demo](https://ubuntu-com-14872.demos.haus/summit)
- [CopyDoc](https://docs.google.com/document/d/1lj-xPVQjWqo2J_eZ-3ldKhJHj6RQ0Cwmk_Mr4QA4UTY/edit)
- [Figma](https://www.figma.com/design/jnBr57W2MnYiCg8QYxC8el?node-id=3283%3A7064&type=design&fuid=1375015922030380968)
- Check if the carousel is working fine and images in topic gets magnified on hover. …

WD-16854 Redesign ubuntu.com/summit

---

templates/20years/index.html

-  Add [this preview image](https://assets.ubuntu.com/v1/41824d95-Ubuntu-20-Years-Social-Share.png) to /20years
- https://ubuntu-com-14906.demos.haus/20years
- Inspect the page, go to the 'Elements's' tab
- Use crt+f to find `og:image`
- See that is match the images mentioned above
Fixes https://warthogs.atlassian.net/browse/WD-14918

feat: Add preview image to /20years

---

templates/templates/footer.html

- Adds ` u-no-margin--bottom` to the `hr`'s above the 'Section' and 'Solutions' headings in the footer
- Open https://ubuntu-com-14905.demos.haus/
- Scroll down to the footer
- See the'Section' and 'Solutions' headings in the footer have the save spacing above as all the other headings
Fixes https://warthogs.atlassian.net/browse/WD-19400

fix: Adjust spacing above footer headings

---

webapp/shop/api/trueability/api.py

- The trueability api tries to fetch the wrong endpoint on retry. This PR fixes that.
** Blocking trueabillity to force retries **
- run the following command or add this to your local /etc/hosts file `127.0.0.1 app.trueability.com localhost` at the end of the block `127.0.0.1 localhost`
- This will redirect all the calls to localhost 80 which should not have any app running on it.
- ** Remember to remove this at the end of the QA or you'll be left with a very broken hostfile **
- Another way on ubuntu is to use `ufw` which is a wrapper for `iptables`
- Run `sudo ufw deny out to 66.151.49.1 port 80`
- Run `sudo ufw deny in from 66.151.49.1 port 80`
- Remember to run allow rules on both to remove them
** Run the app and try to go to pages which call app.trueability.com **
- Check out this …

fix wrong path on retry for Trueability API

---

konf/site.yaml
webapp/shop/api/trueability/api.py

- Add HTTP_PROXY and HTTPS_PROXY for /credentials
- Visit [/credentials/your-exams](https://ubuntu-com-14875.demos.haus/credentials/your-exams)
- Page should load
- This means the proxy is correctly overwritten to the ps6 squid proxy  
----
USERS WITH ACCESS TO THE DEMO K8S
- `kubectl get pods`
- check the pod with the name ubuntu-com-demos-14875 
- kubectl describe pod <pod_name>
- should have the HTTP_PROXY and HTTPS_PROXY set to `http://squid.ps6.internal:3128` 
*** Cannot test the staging changes without merging or running konf locally***
Fixes [#WD-20463](https://warthogs.atlassian.net/browse/WD-20463)

Wd 20463 migrate app 3 trueablity com to app trueability com

---

static/js/src/static-forms.js

- Make sure button is reset to original state even when page is loaded from cache
- Fix bug where spinner was visible on deafult buttons
- Go to https://ubuntu-com-14908.demos.haus/engage/ubuntu-security-in-turkish
- Fill in and submit the form
- See that the spinner is visible on the white button
- After you are redirect to the thank-you page, hit the back button
- See the button is in its original stage (no spinner)
-  Repeat with a green buttoned form, ie. https://ubuntu-com-14908.demos.haus/contact-us/form?product=generic-contact-us
Fixes https://warthogs.atlassian.net/browse/WD-14853
https://warthogs.atlassian.net/browse/WD-19708

fix: Make sure button is reset to original state even when page is loaded from cache

---

templates/certified/shared/_partners.html
templates/pro/devices.html

- Updated Aaeon logo with the new one according to the [copy doc](https://docs.google.com/document/d/1i_3nPkSpCQJ4jfOwN380sdfuTxaiDuDIgDfk01wVPqo/edit?tab=t.0)
- Alternatively, view the [demo](https://ubuntu-com-14913.demos.haus)
- Check the following pages to verify the updated logo
- /pro/devices
- /certified 
- /certified/why-certify 
Fixes https://warthogs.atlassian.net/browse/WD-20639
Before:
After:

Update partner logos on /pro/devices

---

templates/appliance/adguard/_next-steps.html
templates/appliance/lxd/_next-steps.html
templates/appliance/mosquitto/_next-steps.html
templates/appliance/nextcloud/_next-steps.html
templates/appliance/openhab/_next-steps.html
templates/appliance/plex/_next-steps.html
templates/appliance/shared/_appliance-os-tabs.html
templates/appliance/shared/_install_instructions_raspberry-pi.html
templates/appliance/shared/_raspberry-pi.html
templates/appliance/shared/_steps_pi_imager_ubuntu.html
templates/appliance/shared/_steps_pi_imager_windows.html
templates/appliance/shared/_steps_pi_prep-sd-card.html
templates/appliance/shared/_steps_pi_thats-it.html
templates/appliance/shared/_what_you_will_need_pi.html

- Applied redesign for lxd templates as per [mock-up](https://www.figma.com/design/POgmRw4Rpq1hlgaD9DN8mS/ubuntu.com%2Fappliance?node-id=964-10029&m=dev)
- Updated footer designs for remaining footers
- View the site locally in your web browser at: https://ubuntu-com-14914.demos.haus/appliance/nextcloud/raspberry-pi
- Check against mock-up (content itself should not change)
- For the footer templates, please check the following:
-   https://ubuntu-com-14914.demos.haus/appliance/adguard/raspberry-pi
- https://ubuntu-com-14914.demos.haus/appliance/openhab/raspberry-pi
- https://ubuntu-com-14914.demos.haus/appliance/lxd/raspberry-pi
- https://ubuntu-com-14914.demos.haus/appliance/plex/raspberry-pi
- …

feat: Apply design updates to rasp-pi appliance templates and remaining appliance footers

---

templates/download/desktop/thank-you.html
templates/download/raspberry-pi/thank-you.html
templates/download/server/thank-you.html

- If there is no version in the query params do not attempt to download anything and provided a link to the download page
- Go to https://ubuntu-com-14902.demos.haus/download/server/thank-you
- See that no download attempts to start/no redirect is made
- See that in the place of the normal 'if the download doesn't start..' text, it states 'you have not selected an image to download.' and offers a link back to [the download page](https://ubuntu-com-14902.demos.haus/download/server)
- Go to [the download page](https://ubuntu-com-14902.demos.haus/download/server) and attempt to download a version of ubuntu server
- see it functions as normal 
- repeat with:
https://ubuntu-com-14902.demos.haus/download/server/thank-you
https://ubuntu-com-14902.demos.haus/download/raspberry-pi/thank-you
Fixes …

fix: Handle hitting '/download/server/thank-you' without a defined version

---

templates/appliance/_base-appliance.html
templates/appliance/shared/_install_instructions_vm_macos.html
templates/appliance/shared/_install_instructions_vm_ubuntu.html
templates/appliance/shared/_install_instructions_vm_windows.html
templates/appliance/shared/_intel-nuc.html
templates/appliance/shared/_raspberry-pi2.html
templates/appliance/shared/_steps-multipass-find-ip-macos.html
templates/appliance/shared/_steps-multipass-find-ip-windows.html
templates/appliance/shared/_steps_multipass_macos.html
templates/appliance/shared/_steps_pi_imager_macos.html
templates/appliance/shared/_steps_vm_intro.html
templates/appliance/shared/_steps_vm_thats-it.html
templates/appliance/shared/_verify-checksums.html
templates/appliance/shared/_vm.html
templates/appliance/shared/_what_you_will_need_pi2.html

- Applied design updates to remaining appliance templates as per [mock-up](https://www.figma.com/design/POgmRw4Rpq1hlgaD9DN8mS/ubuntu.com%2Fappliance?node-id=964-10972&m=dev)
- https://ubuntu-com-14917.demos.haus/appliance/plex/raspberry-pi2
- https://ubuntu-com-14917.demos.haus/appliance/plex/vm
- Check against design. There should be no content changes
Fixes https://warthogs.atlassian.net/browse/WD-16589

feat: update remaining vm and rasp-2 appliance templates

---

navigation.yaml
templates/20-04/azure.html
templates/20-04/base_20-04.html

- Adds 20.04 Azure page
- Updates navigation to change 20.04 into a bubble
[Figma](https://www.figma.com/design/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=5404-2785&t=BTyitwg6qFagNJCP-1)
[Copy doc](https://docs.google.com/document/d/1qlz7QbmUGHouIvq95XuJbQkhzitzG7UupBKq_Bl2zfg/edit?tab=t.0)
- View the site on demo server https://ubuntu-com-14918.demos.haus/20-04/azure
- Compare agains copy doc and design listed above
- Verify that navigation correctly has 20.04 as a bubble, with Azure being a subpage
Fixes WD-20062

WD-20062: Add /20-04/azure page 

---

templates/aws/support.html

- Corrected typo ; "Azure" to "AWS"
- [Demo](https://ubuntu-com-14923.demos.haus/aws/support)
#14907 
Fixes # [WD-20631](https://warthogs.atlassian.net/browse/WD-20631)
[WD-20631]: https://warthogs.atlassian.net/browse/WD-20631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-20631 Typo correction

---

templates/security/disa-stig.html

- Updated Ubuntu.com/security/dis-stig
- Navigate to ubuntu.com/security/disa-stig and verify that the correct copydoc updates have been made according to the google doc.
Fixes #
Fixes - Copy Doc: https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit?tab=t.0
Jira - https://warthogs.atlassian.net/browse/WD-20814
N/A

[WD-20814] COPYDOC: Update security/disa-stig

---

templates/kubernetes/form-data.json
templates/shared/_default-contact-us-form.html
templates/shared/forms/interactive/ai.html
templates/shared/forms/interactive/managed-services.html
templates/shared/forms/interactive/robotics_ros.html

Adds the 'country' field to the following forms:
https://ubuntu-com-14928.demos.haus/robotics/ros-esm#get-in-touch
https://ubuntu-com-14928.demos.haus/kubernetes/install#get-in-touch
https://ubuntu-com-14928.demos.haus/ai#get-in-touch
https://ubuntu-com-14928.demos.haus/openstack/contact-us
https://ubuntu-com-14928.demos.haus/landscape/compare#get-in-touch
https://ubuntu-com-14928.demos.haus/blog/cloud-instance-initialisation-with-cloud-init
http://ubuntu-com-14928.demos.haus/managed#get-in-touch
https://ubuntu-com-14928.demos.haus/openstack/contact-us
https://ubuntu-com-14928.demos.haus/training/contact-us?product=openstack-training-onsite
- Open the above forms and ensure they have the 'country' input with appropriate `name` attribute
Fixes https://warthogs.atlassian.net/browse/WD-20914

fix: Include 'country' field on forms where it was missing

---

templates/base_index.html

- Set `srcset` for takeover image
- Switched to auto loading for takeover images
- View the site locally in your web browser at: https://ubuntu-com-14930.demos.haus/
- See that the correct takeover image is shown
Fixes #

fix: Set scrset for takeover images and switch to auto loading

---

templates/kubernetes/charmed-k8s/docs/1.28/release-notes.md
templates/kubernetes/charmed-k8s/docs/1.29/release-notes.md
templates/kubernetes/charmed-k8s/docs/1.30/release-notes.md
templates/kubernetes/charmed-k8s/docs/1.31/release-notes.md
templates/kubernetes/charmed-k8s/docs/1.32/release-notes.md
templates/kubernetes/charmed-k8s/docs/release-notes.md

Updating release  notes for charmed-kubernetes 1.32+ck1
* the same release notes for 1.31, 1.30, 1.29, and 1.28
Fixes # [LP#2104056](https://bugs.launchpad.net/bugs/2104056)

Update release notes for Charmed Kubernetes 1.32+ck1

---

templates/robotics/ros-esm.html

- updated datasheet url
- fixed typo (standardizsed -> standardized)
- goto https://ubuntu-com-14932.demos.haus/robotics/ros-esm
- check datasheet (should have updated design compared to https://ubuntu.com/robotics/ros-esm)
- check typo (ctrl+f standardizsed)
WD-19307

[WD-19307] fix typo, update datasheet url

---

templates/desktop/organisations.html

Updates the Ubuntu Pro logo on [desktop/organisations](https://ubuntu.com/desktop/organisations) to be higher quality, per [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit?tab=t.0)
- Open [`desktop/organisations`](https://ubuntu-com-14922.demos.haus/desktop/organisations) and verify that the Ubuntu pro logo has been updated
Fixes [WD-20901](https://warthogs.atlassian.net/browse/WD-20901)
Before
After …

WD-20901 - Update Pro logo on `desktop/organisations`

---

navigation.yaml
static/files/sitemap.xml
templates/security/assurances.html

- Build new page `/security/assurances`.
- Navigate to [/security/assurances](https://ubuntu-com-14920.demos.haus/security/assurances)
- Ensure the design is aligned with the [Figma file](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com%2Fsecurity?node-id=2757-3653&t=4tnWGFT7lXNRP8N7-0).
- Ensure the page content aligns with the [copy doc](https://docs.google.com/document/d/1hQ-n0FrjzQGAOUzIAshzxwhu5PpBC2ClBJMNSMO90Zo/edit?tab=t.0).
- [WD-19392](https://warthogs.atlassian.net/browse/WD-19392)
[WD-19392]: https://warthogs.atlassian.net/browse/WD-19392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

WD-19392 - Feat: build /security/assurances page

---

templates/download/server/arm.html

- adjusted referenced technologies for ubuntu server ARM
- access `/download/server/arm` and verify everything looks in order
https://warthogs.atlassian.net/browse/WD-20897

adjust referenced technologies for ubuntu server ARM

---

.github/workflows/percy-baseline.yaml

- Percy has a strategy where it compares the snapshots for the pull requests with common base commit in the main branch and for that reason it needs builds for all commits in main and hence the workflow.
- Workflow to update the percy baseline main branch.
- This is set for auto approval which mean that any build from main branch will be auto approved on Percy platform.
- This would work when the workflow is actually in main branch so I have tested it on my [fork](https://github.com/immortalcodes/ubuntu.com) .
- [Here](https://github.com/immortalcodes/ubuntu.com/actions/ru …

Feat: Percy workflow for baseline build

---

templates/kubernetes/charmed-k8s/docs/upgrading.md

Update the upgrading page with links to the latest release note upgrade instructions. This page was overlooked in previous release notes updates.

[K8s docs] Update version info on upgrading doc

---

templates/about/release-cycle.html

- Update https://ubuntu.com/about/release-cycle#openstack-release-cycle
- A Ceph tab was added with the appropriate copies
- View update via http://0.0.0.0:8001/about/release-cycle#canonical-ceph-release-cycle
[Copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit?usp=sharing)
[Jira ticket](https://warthogs.atlassian.net/browse/WD-20930?linkSource=email)
Fixes #
View [screenshot](https://drive.google.com/file/d/1DS3jDu-f1Y3ytPf8ekoDYxlUJiV43W1Y/view?usp=sharing) …

copy update: [WD-20930] add copy for canonical ceph release cycle tab

---

static/js/src/chart-data.js
templates/about/release_cycles/releases-table.html
templates/shared/_kernel-release-diagram.html

- Add **Ubuntu 25.04 Plucky Puffin** in release graph and table for Ubuntu
- Add **Kernel 6.14** and **6.11 - 24.04.2 LTS (HWE)** in the release graph and table for Ubuntu kernel
[**Copy doc**](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit?disco=AAABgB1dGHA&tab=t.0)
- Visit: https://ubuntu-com-14942.demos.haus/about/release-cycle
- Click into the **Ubuntu kernel** tab
Fixes [WD-21032](https://warthogs.atlassian.net/browse/WD-21032)
**Before:**
**After:**
**Before:**
**After:**
[WD-21032]: https://warthogs.atlassian.net/browse/WD-21032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

[WD-21032] Ubuntu 25.04 copy update - about/release-cycle

---

templates/landscape/docs/document.html

- Add a 'deprecated' warning notification to /landscape/docs based on the specification in the [jira ticket](https://warthogs.atlassian.net/browse/WD-18358). **Note** - I used this approach as the fix is only until June, when the entirety of `/landscape/docs` will be decommissioned 
- Go to any `/landscape/docs` page, ex. https://ubuntu-com-14936.demos.haus/landscape/docs
- See there is a notification with the text from the Jira ticket, eg.
"Important: We have a new documentation website <link>! You’re viewing an old version of the documentation. Please use the new documentation site for the most up-to-date content. This site will redirect to our new documentation in June 2025."
- See it is sticky when you scroll and closes when you click the 'x'.
- See it is on all `/landscape/docs` …

feat: Add a 'deprecated' warning notification to /landscape/docs

---

templates/20-04/aws.html

- Updated marketplace listings on https://ubuntu.com/20-04/aws according to the [copy doc](https://docs.google.com/document/d/15Zmi9XqCoo00UU4DOIzhSPENVdGsdAt6nTBpZTeKa3g/edit?tab=t.0)
- Alternatively, view the [demo](https://ubuntu-com-14961.demos.haus/)
- Navigate to `/20-04/aws`
- Check the following links to point to expected pages (PFA screenshot)
- `Contact us to purchase annual subscription tokens` should work (2 places)
- `Launch a new instance of Ubuntu 22.04 LTS on AWS` should not point to Pro version
- `Launch a new instance of Ubuntu 24.04 LTS on AWS` should not point to Pro version
Fixes …

copy update: links to marketplace listings

---

navigation.yaml
templates/20-04/gcp.html

- Add 20-04/gcp page WD-20906
- Check the new page at https://ubuntu-com-14963.demos.haus/20-04/gcp
Fixes https://warthogs.atlassian.net/browse/WD-20906
Copy: https://docs.google.com/document/d/1-fuCPmr0dYcHaVz3YMjezNT3LYiO7WG5ErKF-YAeXHI/edit?tab=t.0
Design: https://www.figma.com/design/ZAihKxF2wmj9wvoPSnPKmY/Commercial--Ubuntu-Pro?node-id=5921-3544&t=dG4wxLZY6hIu0bPW-0

Add 20-04/gcp page WD-20906

---

templates/download/server/thank-you.html
templates/download/shared/_server_weekly_news.html

- Updated link for cli cheatsheet
- View the site locally in your web browser at: https://ubuntu-com-14973.demos.haus/server/download
- Download a new iso, and on the thank you page, click the cli cheatsheet link and fill out the form. It should download [this](https://assets.ubuntu.com/v1/5809ba46-(Updated)%20Ubuntu%20Server%20CLI%20cheat%20sheet%2002.07.2024%20update.pdf) file.
Fixes [WD-16269](https://warthogs.atlassian.net/browse/WD-16269)
[WD-16269]: https://warthogs.atlassian.net/browse/WD-16269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update ubuntu server cli cheatsheet

---

releases.yaml
templates/download/server/manual.html

- Updates to the ubuntu.com/download/server page.
Navigate to /download/server in the demo server. Check that the copy doc matches the page
[Copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit)
[Demo server](https://ubuntu-com-14925.demos.haus/download/server)
[Jira ticket](https://warthogs.atlassian.net/browse/WD-20895)

copy update: [WD-20895] update download/server page

---

templates/credentials/schedule.html

- Fixed jinja errors in scheduling template
- visit /credentials/your-exams
- Try to schedule an exam
- Should work
Fixes [#WD-21397](https://warthogs.atlassian.net/browse/WD-21397)

fix template errors

---

templates/security/notices/usn.html

- we want to add "Available with Ubuntu Pro" message for the pockets 'fips', 'fips-updates' and 'realtime'.
- those are known pockets in https://github.com/canonical/ubuntu-com-security-api and started to get published recently.
- an example: https://ubuntu.com/security/notices/USN-7408-3
- the CVE website already show the relevant information, example: https://ubuntu.com/security/CVE-2024-26928 (look for linux-aws-fips)
- Check if USN with FIPS or Realtime contain "Available with Ubuntu Pro", examples of such cases:
- https://ubuntu.com/security/notices/USN-7383-2 …

WD-21345: usn.html: add FIPS and Realtime pockets

---

releases.yaml

- Add plucky images checksums.
Fixes # do we have an issue for this?

releases: add plucky checksums

---

meganav.yaml
templates/download/desktop/index.html
templates/download/raspberry-pi/index.html
templates/download/server/manual.html

- Updated logo wrapping and aligned all to be hidden only on small screens
- Updated the download Ubuntu quick links as per [doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit?disco=AAABhxz6ACA)
- View the site locally in your web browser at: https://ubuntu-com-15005.demos.haus/#download-ubuntu
- See that desktop guide has been updated as per doc
-  Go to https://ubuntu-com-15005.demos.haus/download/server, https://ubuntu-com-15005.demos.haus/download/desktop, and https://ubuntu-com-15005.demos.haus/download/raspbery-pi
- See that all plucky logos are wrapped in the same way and are hidden on small screens 
Fixes [review comments](https://github.com/canonical/ubuntu.com/pull/14940#issuecomment-2812216943)

Final fixes

---

templates/download/desktop/index.html

- Fix download link version
- View the site locally in your web browser at: https://ubuntu-com-15011.demos.haus/download/desktop
- Click on the amd version of 25.04 and see that the correct version is download
Fixes #15010

Fix download link

---

tests/test_sitemap.py

- Implement testing for directory parser
- Added 3 tests:
- `/sitemap_tree.xml` returns a valid XML response
- `/sitemap_parser` returns a valid JSON response
- urls in JSON response are present in the `sitemap_tree.xml`
- See that `test-python` [action](https://github.com/canonical/ubuntu.com/actions/runs/14510528905/job/40707985346?pr=15001) passes
Fixes [WD-17184](https://warthogs.atlassian.net/browse/WD-17184)
[WD-17184]: https://warthogs.atlassian.net/browse/WD-17184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test: Implement testing for sitemaps

---

static/js/src/chart-data.js

- Fixed the release name
- View the site in your web browser at: https://ubuntu-com-15018.demos.haus/about/release-cycle#canonical-kubernetes-release-cycle
- Verify the chart is correct.
Fixes #[WD-21541](https://warthogs.atlassian.net/browse/WD-21541)
Before
After
[WD-21541]: https://warthogs.atlassian.net/browse/WD-21541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-21541] fix: Kubernetes LTS release chart showing incorrect color order

---

templates/download/iot/intel-iot.html

- Copy update on `/download/iot/intel-iot` or https://ubuntu-com-15025.demos.haus/download/iot/intel-iot
- Removed Intel core ultra (series 2) 
- Compare page against [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit?tab=t.0#heading=h.6fd05dg360az)
Fixes #https://warthogs.atlassian.net/browse/WD-21551

Copy update on /download/iot/intel-iot

---

static/js/src/chart-data.js
static/js/src/release-chart-manager.js
static/js/src/release-chart-old.js

- Updated k8s LTS support charts
- View the site in your web browser at: https://ubuntu-com-15020.demos.haus/about/release-cycle#canonical-kubernetes-release-cycle
- Verify the chart is correct and up-to-date with this [discussion](https://chat.canonical.com/canonical/pl/8h6pi6tt4bgkux7oeq4qfe7a6h) and this [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit?tab=t.0)
Quote: 
> It should be one year for the black line, and 9 years for the red line, and then we can add the legacy support with 2 years

chore: update k8s LTS support timelines

---

templates/pro/free-trial.html

- feat: Link and copy update for pro/free-trial
- check the page at https://ubuntu-com-15021.demos.haus/pro/free-trial for the new CTA label and link target
Fixes [WD-21538](https://warthogs.atlassian.net/browse/WD-21538?linkSource=email)
[Copy doc](https://docs.google.com/document/d/1USgQJcUKNz3iZYeNVeICVqGz879rlG5ztEtVxPWm8bc/edit?tab=t.0)
[WD-21538]: https://warthogs.atlassian.net/browse/WD-21538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Link and copy update for pro/free-trial

---

.github/workflows/live-links.yaml

- We are going to add link checkers to more projects and therefore we need a more specific name for the GH action to clarify which project it belongs to.

Update live-links.yaml: make the name more specific

---

templates/download/core/index.html

- Updated duration
- Verify the Ubuntu core 24 has EOL 10 years, ending in 2034.
- Find copydoc for verification [here](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit?tab=t.0)
Fixes [WD-21500](https://warthogs.atlassian.net/browse/WD-21500)
Fixes #15008
[WD-21500]: https://warthogs.atlassian.net/browse/WD-21500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-21500] copy update /download/core

---

static/sass/_pattern_navigation.scss

- Removed unused and repetitive styles for navbar search toggle button.
- View the site locally in your web browser at: https://ubuntu-com-15038.demos.haus/
- Make sure you set the screen size to medium, i.e., < 1250px
- Hover search icon, verify the padding is equal on both sides
- Click search icon, it will toggle the visibility of close icon.
- Hover close icon, verify the padding is equal on both sides.
Fixes #[WD-20510](https://warthogs.atlassian.net/browse/WD-20510)
Fixes #14882
[WD-20510]: https://warthogs.atlassian.net/browse/WD-20510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-20510] fix: incorrect padding on search and close icon on medium screens

---

templates/confidential-computing/index.html

Refreshing the confidential computing page for a couple copy changes, adding a couple sections, and adding an image to the hero. 
Design prototype: https://www.figma.com/design/zyG3Iyys2GlxxfqfQQT7bT/23.10-U.com---Confidential-computing?node-id=333-1633&t=vvaIO2f4CieuXvN6-0
- View the site locally in your web browser at: http://0.0.0.0:8001/confidential-computing
Available at https://ubuntu-com-15026.demos.haus/confidential-computing
Fixes # https://warthogs.atlassian.net/browse/WD-20315

feat: redesigned the confidential computing page

---

templates/certified/index.html

- Updated the link href to the StableReleaseUpdates documentation. The wiki site has been deprecated and replaced by a collection on ubuntu.com. 
Fixes [CDOC-204](https://warthogs.atlassian.net/browse/CDOC-204)
No change
[CDOC-204]: https://warthogs.atlassian.net/browse/CDOC-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

Fix: update deprecated link to SRU documentation

---

static/sass/styles.scss
templates/security/index.html

- Refresh `/security` based on [figma](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com-security?node-id=3533-3259&t=g5SwBpWREZrvfclS-0) and [copydoc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit?tab=t.0)
- Creates a new `p-list__item is-ticked is-muted` variant. Similar to the regular [Vanilla ticked list](https://vanillaframework.io/docs/patterns/lists#ticked-with-horizontal-divider), but with the tick icon being `#666666`. 
- Open [the demo](https://ubuntu-com-15031.demos.haus/security)
Fixes https://warthogs.atlassian.net/browse/WD-20752

feat: Refresh /security

---

templates/security/security-standards.html

Change FIPS notification link for /security/security-standards according to [this comment](https://warthogs.atlassian.net/browse/WD-19955?focusedCommentId=741745)
Fixes #

copy: change FIPS notification link for /security/security-standards

---

templates/credentials/your-exams.html
webapp/shop/cred/views.py

- Check if user is banned by calling preview purchase API on your-exams page
- Ban a user and make sure they do not see action buttons on your-exams page and an error message
Fixes [WD-21518](https://warthogs.atlassian.net/browse/WD-21518)
[WD-21518]: https://warthogs.atlassian.net/browse/WD-21518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-21518: check if user is banned on your-exams page

---

static/js/src/dynamic-forms.js

- Fixed: scroll glitches when closing contact modal
- Chore: add aria-expanded label to button when modal is opened
- drive by: Clear event listeners on closing contact modal
- Check out this branch
- Run the project using `dotrun`
- View the site in your web browser at: http://0.0.0.0:8001/aws
- Follow the issue reproduction steps outlined [here](https://warthogs.atlassian.net/browse/WD-21391) and verify the bug is resolved and not re-producible.
- Verify the `aria-expanded` attribute is added to contact button when modal is opened
- Try opening/closing/scrolling/submitting the form and make sure everything works as expected.
Fixes #[WD-21391](https://warthogs.atlassian.net/browse/WD-21391)
Fixes #[WD-21454](https://warthogs.atlassian.net/browse/WD-21454)
[QA …

[WD-21391] fix: scrolling issues when closing contact modal and add aria-expanded label to contact button

---

static/sass/_pattern_navigation.scss

- Fixed the styling of the navbar search & close icon positioning.
- Be sure to test on mobile, tablet and desktop screen sizes.
Fixes https://chat.canonical.com/canonical/pl/o5w8ko4irpbn7rbg7z1ppuhs4a
Fixes https://chat.canonical.com/canonical/pl/ohzwhdkhqtn63j4maecipt36fw

Center search toggle icon in navigation dropdown

---

templates/base_index.html

- Update two links in the core section.
- Go to https://ubuntu-com-15053.demos.haus/
- Scroll down to to the "Ultra secure things" section.
- Check that the subheading matches the copy doc: https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?tab=t.0#heading=h.mfi239m5io9u.
https://warthogs.atlassian.net/browse/WD-21770?linkSource=email

feat: update core section links

---

templates/credentials/schedule.html
webapp/shop/cred/constants.py
webapp/shop/cred/views.py

- When scheduling CUE.02 Desktop exam, the schedule confirmation showed CUE.01 Linux (incorrect name)
- This PR fixes that & also prevents beta exams from being proctored
- Buy CUE.02 Desktop exam and schedule it
- You should see CUE.02 Desktop in exam confirmation thank you screen
- Make sure CUE.01 Linux still shows CUE.01 on thank you page 
Fixes [WD-21511](https://warthogs.atlassian.net/browse/WD-21511)
[WD-21511]: …

WD-21511 WD-21512: show correct exam names when scheduling

---

static/js/src/chart-data.js
static/js/src/release-chart-old.js
templates/shared/_kernel-release-diagram.html

- Add missing legacy dates for kernel release graph and table
- Check out the [kernel release graph and table here](https://ubuntu-com-15061.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle).
- Make sure the date for the Legacy Support on the kernel release graph and table matches [what is in the copy doc](https://docs.google.com/document/d/1ozdBTb7M5TJExdETYjWWpKn-_hdANXCKxjL6GzobnxE/edit?tab=t.0).
- [WD-21716](https://warthogs.atlassian.net/browse/WD-21716)
[WD-21716]: https://warthogs.atlassian.net/browse/WD-21716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-21716 - Copy Update - Add missing legacy date for kernel releases

---

konf/site.yaml

- Moved the notices endpoints to their own service `ubuntu-com-security-api-notices`

Separate USN endpoint services

---

templates/download/qualcomm-iot/index.html
templates/download/qualcomm-iot/tabs/rb3-gen2-lite-tab.html
templates/download/qualcomm-iot/tabs/rb3-gen2-tab.html

- Updated the contents of the Qualcomm tabs for the new release
Copy doc: https://docs.google.com/document/d/1BP2T63R6kdnUFQFIZcbXbTIgY-9fQVgVRLsSUU5Rvx8/edit?tab=t.0
Figma: https://www.figma.com/design/cVGimTPHky4h3BPXfrT6GB/Ubuntu.com-download?node-id=1990-17189&m=dev
- Demo: https://ubuntu-com-15033.demos.haus/download/qualcomm-iot
- Review the contents of the tabs agains copydoc and Figma design (design only shows one of them, but they only differ in device name)
Fixes https://warthogs.atlassian.net/browse/WD-21405

Update Qualcomm tabs content for 24.04 public beta

---

templates/support/community-support.html

- Update deprecated Ubuntu Forums link to Ubuntu Discourse
- [Copy doc](https://docs.google.com/document/d/1vrnljXUx71ZZhz3cQ6NupUNw6yNqW2OWkyY8Ozx2bqw/edit?tab=t.0)
- Go to /support/community-support
- Click on "Ubuntu Discourse" and see that it links to Discourse as expected
Fixes [WD-21943](https://warthogs.atlassian.net/browse/WD-21943) https://github.com/canonical/ubuntu.com/issues/15027 [WD-21552](https://warthogs.atlassian.net/browse/WD-21552)
[WD-21943]: https://warthogs.atlassian.net/browse/WD-21943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

chore: Update community help link

---

build.js
static/js/src/account-billing.js
static/sass/_pattern_invoices.scss
static/sass/styles.scss
templates/account/invoices/_edit_billing_form.html
templates/account/invoices/_edit_billing_modal.html
templates/account/invoices/index.html
webapp/shop/schemas.py
webapp/shop/views.py

- `/account/invoices`: let users update their billing details (customer info)
See [design](https://www.figma.com/design/GXrVXEGISyJVJbGk4V7PoD/25.04-Pro-Dashboard-Updates?node-id=501-6579&m=dev)
- Go to `account/invoices`
- Click `Edit billing details`
- Modify the form
- Click save
---
- Click save
---
---
---
Check that the overall behaviour looks alright (the modal behaves as it should, etc.)
https://warthogs.atlassian.net/browse/WD-20699

pro: edit billing details from invoices page

---

templates/kubernetes/charmed-k8s/docs/1.30/upgrading.md
templates/kubernetes/charmed-k8s/docs/1.31/upgrading.md
templates/kubernetes/charmed-k8s/docs/1.32/upgrading.md
templates/kubernetes/charmed-k8s/docs/ceph.md
templates/kubernetes/charmed-k8s/docs/certs-and-trust.md
templates/kubernetes/charmed-k8s/docs/cni-cilium.md
templates/kubernetes/charmed-k8s/docs/encryption-at-rest.md
templates/kubernetes/charmed-k8s/docs/equinix.md
templates/kubernetes/charmed-k8s/docs/gatekeeper.md
templates/kubernetes/charmed-k8s/docs/how-to-cos-lite.md
templates/kubernetes/charmed-k8s/docs/install-existing.md
templates/kubernetes/charmed-k8s/docs/install-local.md
templates/kubernetes/charmed-k8s/docs/install-manual.md
templates/kubernetes/charmed-k8s/docs/install-offline.md
templates/kubernetes/charmed-k8s/docs/keepalived.md
templates/kubernetes/charmed-k8s/docs/logging.md
templates/kubernetes/charmed-k8s/docs/metallb.md
templates/kubernetes/charmed-k8s/docs/multiple-networks.md
templates/kubernetes/charmed-k8s/docs/proxies.md
templates/kubernetes/charmed-k8s/docs/quickstart.md
templates/kubernetes/charmed-k8s/docs/scaling.md
templates/kubernetes/charmed-k8s/docs/security.md
templates/kubernetes/charmed-k8s/docs/storage.md
templates/kubernetes/charmed-k8s/docs/upgrading.md
templates/kubernetes/charmed-k8s/docs/using-vault.md
templates/kubernetes/charmed-k8s/docs/vsphere-integration.md

After the rework of the Juju docs, there were many broken links in Charmed Kuberentes. This PR updates those links.

[K8s Docs] Update k8s doc links

---

templates/about/release-cycle.html

- Update "Skype" to "Firefox" as per [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit?tab=t.0#heading=h.s6x9gb573nib)
- Go to /about/release-cycle
- See that "Skype" is replaced with "Firefox"
Fixes #15077

chore: Update deprecating snap

---

webapp/shop/cred/views.py

- Integrate paginated TA response for assessment reservations GET API
- Ensure you can see all your exams on `/credentials/your-exams`
Fixes [WD-22009](https://warthogs.atlassian.net/browse/WD-22009)
[WD-22009]: https://warthogs.atlassian.net/browse/WD-22009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

integrate ta paginated response in your-exams view

---

templates/security/vulnerabilities/vulnerability-detailed.html
webapp/app.py

- Remove `/templates/templates/...` directory from sitemap
- Remove `/security/vulnerabilities/vulnerability-detailed.html` from sitemap
- Go to https://ubuntu-com-15086.demos.haus/sitemap_tree.xml
- Search for `/templates`, see that they are not indexed
- Repeat step 2 with `/security/vulnerabilities/vulnerability-detailed`
Fixes [WD-21815](https://warthogs.atlassian.net/browse/WD-21815)
[WD-21815]: https://warthogs.atlassian.net/browse/WD-21815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Remove templates from sitemap

---

templates/shared/forms/interactive/hpe.html

Update two emails on the contact us modal, triggered from the CTA, on the /hpe page. 
Updated according to : https://docs.google.com/document/d/1GtHoXJPGqTaxJxj1d9ul7hZukb_piUdBunXAwx7J28k/edit?tab=t.0#heading=h.47b8yg16cwy2
- View the site locally in your web browser at: http://0.0.0.0:8001/hpe
Or also on the demo @ https://ubuntu-com-15087.demos.haus/hpe#get-in-touch
Fixes # https://warthogs.atlassian.net/browse/WD-21954

copy: update contact form emails for /hpe

---

requirements.txt
static/sass/styles.scss
templates/security/vulnerabilities/vulnerability-detailed.html
webapp/views.py

- Bump canonicalwebteam.discourse to 6.2.0
- Introduces a class 'p-table--wide-table' to make tables horizontally scroll able (this can be reviewed later, once the discourse work is merged) 
- Adds a body class the vulnerabilities pages 'vulnerabilities-details'
- Go to this [Discourse post](https://discourse.ubuntu.com/t/test-topic/59821) and find the table with the string '[style=p-table--wide-table]' above it
- Find the corresponding table in [the demo](https://ubuntu-com-15050.demos.haus/security/vulnerabilities/test-topic). See the string, '[style=p-table--wide-table]', has been removed
- Inspect the table element and see it is wrapped in a div with the class 'p-table--wide-table'
Fixes https://warthogs.atlassian.net/browse/WD-20353

chore: Bump canonicalwebteam.discourse to 6.2.0

---

templates/kubernetes/charmed-k8s/docs/1.31/release-notes.md
templates/kubernetes/charmed-k8s/docs/1.32/release-notes.md
templates/kubernetes/charmed-k8s/docs/release-notes.md

Updating release notes for charmed-kubernetes `1.32+ck2` and `1.31+ck3`.
Fixes #

docs: add release notes for 1.32 and 1.31 bugfixes

---

templates/automotive/index.html

- Add certification image and link
- Update logo cloud images
[Demo](https://ubuntu-com-14966.demos.haus/automotive)
Check out this feature branch
Run the site using the command ./run serve or dotrun
View the site locally in your web browser at: http://0.0.0.0:8001/
Be sure to test on mobile, tablet and desktop screen sizes
[List additional steps to QA the new features or prove the bug has been resolved]
Fixes #[WD-20515]
- Some logo assets should be resized to fit logo cloud. (see screenshots)
- A ticket is apparently already assigned for this.
[WD-20515]: https://warthogs.atlassian.net/browse/WD-20515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-20515] copy update: ubuntu.com/automotive

---

navigation.yaml

- Updated pricing navigation to exclude "Consulting" according to the [copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit?tab=t.0)
- Alternatively, view the [demo](https://ubuntu-com-15102.demos.haus/)
- Navigate to /pricing/pro
- Check that the navigation bar only contains "Desktops" and "Devices"
Fixes https://warthogs.atlassian.net/browse/WD-22067?linkSource=email

copy update: update pricing nav

---

templates/internet-of-things/index.html

- add the Renesas logo to iot section on /internet-of-things page
- View update via https://ubuntu-com-15104.demos.haus/internet-of-things
- Be sure to test on mobile, tablet and desktop screen sizes 
- Check against [doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit?tab=t.0) and [jira ticket](https://warthogs.atlassian.net/browse/WD-21940#icft=WD-21940)
[jira ticket](https://warthogs.atlassian.net/browse/WD-21940#icft=WD-21940)

chore: add the Renesas logo to iot page

---

templates/desktop/developers.html

- Update the developer page links to pdfs that were giving a 404.
Copy doc: https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit?tab=t.0
- Go to [/desktop/developers](https://ubuntu-com-15101.demos.haus/desktop/developers)
- Scroll down to "Developers love Ubuntu, organisations trust it".
- Click on the two "Source: ..." links below the charts and they should take you to pdfs.
https://warthogs.atlassian.net/browse/WD-22122?linkSource=email

fix: replace developer pdf links that were 404ing

---

static/sass/_pattern_cve.scss
templates/security/cves/_cve-card.html

- Fixed icon alignment 
- View the site locally in your web browser at: https://ubuntu-com-15117.demos.haus/security/cves
- See that icon is right-aligned 
Fixes #https://warthogs.atlassian.net/browse/WD-22225
before:
after:

fix: Fix icon placement

---

package.json
static/sass/styles.scss
templates/kernel/lifecycle.html
templates/shared/_kernel-release-diagram.html
templates/shared/_kernel-support-schedule.html
yarn.lock

- Rebranded kernel/lifecycle page
- View the site in your web browser at: https://ubuntu-com-15115.demos.haus/kernel/lifecycle
- Verify the page matches [copydoc](https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit?tab=t.0) and [figma](https://www.figma.com/design/lIQtR9xJy9gLGIAIcTFAjm/ubuntu.com-kernel?node-id=46-3700)
Fixes #[WD-17831](https://warthogs.atlassian.net/browse/WD-17831)
Before:
After:
[WD-17831]: https://warthogs.atlassian.net/browse/WD-17831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-17831] feat: Rebrand kernel/lifecycle page

---

templates/core/index.html
templates/core/stories.html
templates/internet-of-things/form-data.json
templates/internet-of-things/index.html
templates/internet-of-things/smart-city/index.html

- Replaced all instances of /digital-signage to /smart-displays
- View the site locally in your web browser at: https://ubuntu-com-15125.demos.haus/
- Make sure the following links work and redirect to https://ubuntu-com-15125.demos.haus/internet-of-things/smart-displays
- https://ubuntu-com-15125.demos.haus/internet-of-things/digital-signage
- https://ubuntu-com-15125.demos.haus/internet-of-things/digital-signage#get-in-touch
Fixes #[WD-22279](https://warthogs.atlassian.net/browse/WD-22279)
[WD-22279]: https://warthogs.atlassian.net/browse/WD-22279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

[WD-22279] chore: Replace all instances of /digital-signage with /smart-displays

---

webapp/views.py

- Adding the original form ID to the enrichment form submission
- Submit any form
- Check if the original form ID is in the payload to form 4198
- Check if the original form ID is received in Marketo for form 4198
GROWENG-6275

original form ID to enrichment form

---

templates/download/amd/tab-1.html
templates/download/amd/tab-2.html
templates/download/amd/tab-3.html

- Change links and text in 2 tabs in `download/amd` page
- Navigate to /download/amd in the demo server. Check that the copy doc matches the page
[Copy doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit?tab=t.0)
[Demo server](https://ubuntu-com-15071.demos.haus/download/amd)
Fixes #
[WD-21918 Jira ticket](https://warthogs.atlassian.net/browse/WD-21918)

update links on 24.04 of ubuntu.com download amd

---

static/js/src/advantage/credentials/dashboard/constants.ts
webapp/shop/decorators.py

- Add 24.10 credly badge to dashboard for issuance
- Go to `/credentials/dashboard/exams/results`
- In the column **Issue Badge** you should be able to see CUE.01 Linux 24.10
Fixes [WD-15705](https://warthogs.atlassian.net/browse/WD-15705)
[WD-15705]: https://warthogs.atlassian.net/browse/WD-15705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-15705: add 24.10 exam to badge issue menu in dashboard

---

templates/credentials/schedule.html
webapp/shop/cred/views.py

- On error while exam scheduling, the form values of the scheduling form will now get preserved
- Buy and schedule an exam
- Choose a date and time which causes error (schedule the exam for within 30 minutes from now to produce)
- The date, timezone, time values should be preserved upon error
Fixes [WD-20560](https://warthogs.atlassian.net/browse/WD-20560), [WD-21375](https://warthogs.atlassian.net/browse/WD-21375)
[WD-21375]: …

WD-21375 WD-20560: preserve form values on error for exam scheduling and check expired contracts

---

webapp/shop/cred/views.py

- Use form id 6254 is on staging and 3801 if on production for sending data to Marketo
- Go to `/credentials/sign-up?type=tester` or `/credentials/sign-up?type=sme`
- Fill the form and submit
- It should submit without error
Fixes [WD-22437](https://warthogs.atlassian.net/browse/WD-22437)
[WD-22437]: https://warthogs.atlassian.net/browse/WD-22437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

WD-22437: use different form id for staging and production for marketo sign ups

---

templates/containers/what-are-containers.html

There is a section that explains: "Containers vs. virtual machines" and another for "Docker vs. LXD" but the corresponding diagrams appear to be swapped. This update switches the diagrams to align their their correct section. 
Original image placement:
Images places with corresponding headings:

Swap image arrangement

---

templates/security/fedramp.html

- Add video with lazy loading
- Go to https://ubuntu-com-15162.demos.haus/security/fedramp
- Compare the content with the [copy doc](https://docs.google.com/document/d/1eJxGEthPLxG2CjFXTXLk6QF97DNh4VyZZ-AG2yIq8v4/edit?tab=t.0)
- Compare the content with [figma](https://www.figma.com/design/pc4AcZqcXvWJqrm4t1x1y6/ubuntu.com-security?node-id=4492-13573&t=RnfS06pskMc0IqMh-0)
Fixes #[WD-22246](https://warthogs.atlassian.net/browse/WD-22246) …

feat: fedramp page refresh, add video with lazy loading

---

static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx
static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.test.tsx

- Updated label on /pro/subscribe buy button
- Visit /pro/subscribe
- The CTA button label should have changed
- pressing the button should still redirect to /account/checkout
Fixes [#WD-21953](https://warthogs.atlassian.net/browse/WD-21953)

[WD-21953] Update CTA label on /pro/subscribe

---

meganav.yaml
templates/hpc/_hpc-contact-us-form.html
templates/shared/_default-contact-us-form.html
templates/shared/_openstack_contact_us.html
templates/shared/forms/_desktop_help.html

- Replaced https://ubuntuforums.org links with https://discourse.ubuntu.com.
- Updated the links in the meganav.
- View the site locally in your web browser at: https://ubuntu-com-15153.demos.haus/
- Check that the support links are working, 
Fixes https://github.com/canonical/ubuntu.com/issues/15096

feat: replaced ubuntuforums with discourse

---

templates/download/risc-v/deepcompute-fml13v01.html
templates/download/risc-v/deepcomputing-fml13v01.html
templates/download/risc-v/index.html

- Added DeepComputing FML13V01 board to the risc-v download page.
- Visit /download/risc-v
- Ensure the DeepComputing tab works as expected
Fixes https://warthogs.atlassian.net/browse/WD-22206

feat: Add DeepComputing FML13V01 to risc-v download page

---

meganav.yaml
package.json
static/sass/styles.scss
templates/kernel/form-data.json
templates/kernel/index.html
templates/kernel/lifecycle.html
templates/kernel/variants.html
templates/shared/_kernel-release-diagram.html
templates/shared/_kernel-support-schedule.html
yarn.lock

- This is the feature branch for kernel bubble rebranding
- Following pages are included in this rebrand
- index
- lifecycle (and a modal form)
- variants
- View the site  in your web browser at: https://ubuntu-com-15174.demos.haus/kernel
- Go through all the pages, make sure all the links work and everything looks good.
Fixes #[WD-17822](https://warthogs.atlassian.net/browse/WD-17822)
[WD-17822]: https://warthogs.atlassian.net/browse/WD-17822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-17822] feat: rebrand kernel bubble

---

templates/legal/ubuntu-pro-service-terms/2024-12-10.md

- legal/ubuntu-pro-service-terms: update from copy doc
- check [legal/ubuntu-pro-service-terms](https://ubuntu-com-15202.demos.haus/legal/ubuntu-pro-service-terms) was updated in regard to the update from [copy doc](https://docs.google.com/document/d/1aeqs6k-jgTf8xu3bOcloYpRgvIy7DuGjwyk7TLeTcqw/edit?tab=t.0)
- check the older version from December 2024
Fixes [WD-22812](https://warthogs.atlassian.net/browse/WD-22812)
[WD-22812]: …

legal/ubuntu-pro-service-terms: update from copy doc. fixes 

---

templates/credentials/shop/index.html
webapp/shop/cred/exams.json
webapp/shop/cred/views.py

- Open desktop exam for internal users
- Refactor the logic for disabling exam for prod and staging environment for better readability
- Go to `staging.ubuntu.com/credentials/shop` or `ubuntu.com/credentials/shop` as internal user and you will see two enabled exams
- Go to above as non-internal user, for production you will see only one exam (cue.01) and for staging you will see two exams
Fixes [WD-22786](https://warthogs.atlassian.net/browse/WD-22786) …

WD22786: open desktop exam for production for internal users

---

templates/security/esm.html

- armhf added in "Architectures supported with ESM" for 24.04
- naavigate to https://ubuntu-com-15199.demos.haus/security/esm
- find the table "What is covered?", armhf architecture should be there for 24.04

armhf added in "Architectures supported with ESM" for 24.04

---

templates/legal/_base_legal_markdown.html
templates/legal/index.md

- Injected HTML into the legal homepage to align with [the design](https://www.figma.com/design/1GHlOSRJZsDHGWF9FnXoyc/ubuntu.com-legal?node-id=0-1&p=f&m=dev)  
- Visit /legal
- Check that the page matches the design

Redesigned the legal overview page

---

static/js/src/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
static/js/src/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
static/js/src/canonical-cla/utils/address.ts

- Replaced single address field with separate fields for street address, city, state/province, and postal/ZIP code in IndividualContactForm and OrganizationContactForm.
- Introduced formatAddress utility to format the address for submission.
- Updated form validation schemas to reflect new address structure.
Fixes [LP-2683](https://warthogs.atlassian.net/browse/LP-2683)
[LP-2683]: https://warthogs.atlassian.net/browse/LP-2683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(Canonical CLA): Update contact forms to use structured address fields

---

static/js/src/canonical-cla/components/ContactDetailsForm/IndividualContactForm.tsx
static/js/src/canonical-cla/components/ContactDetailsForm/OrganizationContactForm.tsx
webapp/handlers.py

- Updated the country name retrieval to use the common name when available, enhancing consistency in the country list.
- Updated the country dropdown label to add 'Region'
- Check out the demo link [here](https://ubuntu-com-15223.demos.haus/legal/contributors/agreement?type=individual)
- Locate the drop-down list option of the "Country" field that check that country name are represented correctly for example `Taiwan` instead of `Taiwan, Province of China`.
Issue: #15221 
Fixes # [23085](https://warthogs.atlassian.net/browse/WD-23085)

Use common names for countries in CLA

---

templates/kubernetes/index.html

- Update spectro cloud logo on /kubernetes page
- Go to[ demo](https://ubuntu-com-15226.demos.haus/kubernetes)
- Scroll down to `Integrated cluster management platforms` section and check the logos and ensure the new logo is shown
[Copy docs](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit?tab=t.0)
Before
After

Copy update: update spectro cloud logo

---

templates/summit/call-for-collaboration.html

This reverts commit 11bb84af208c265e1afd02949c5e30f95cc48e86, reversing changes made to aa34cb9d940eaf45fc1515508952627535b441b9.
The PdM requested to revert the page and make it live with the `/summit` page. 
https://warthogs.atlassian.net/browse/WD-22825?focusedCommentId=810846
- Go to [/summit/call-for-collaboration](https://ubuntu-com-15242.demos.haus/summit/call-for-collaboration)
- Check page has been reverted

Revert "Merge pull request #15220 from minkyngkm/WD-22825"

---

.github/workflows/live-links.yaml
.github/workflows/performance-check.yaml

- Update linkchecker to exclude 401 and 403 status codes in error checks
- Run perf check action on main repo only
- Ensure it introduces no additional code other than updating link checker config
Fixes # [23130](https://warthogs.atlassian.net/browse/WD-23130) [WD-23183](https://warthogs.atlassian.net/browse/WD-23183)
[WD-23183]: https://warthogs.atlassian.net/browse/WD-23183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update linkchecker to exclude 401 and 403 status codes in error checks

---

webapp/shop/cred/exams.json

- Disable CUE.02 exam in production for all users (internal and external)
- Go to [ubuntu-com-15257.demos.haus/credentials/shop](https://ubuntu-com-15257.demos.haus/credentials/shop) and make sure you only see CUE.01 exam enabled
Fixes [WD-23223](https://warthogs.atlassian.net/browse/WD-23223)
[WD-23223]: https://warthogs.atlassian.net/browse/WD-23223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

WD-23223: disable cue.02 exam in production

---

requirements.txt
templates/search.html
webapp/app.py

- Apply rebranding on search page
- Go to https://ubuntu-com-15216.demos.haus/search
- Check that design matches [Figma](https://www.figma.com/design/RIeBDWnFQVtYOQltavDcXf/Search--ubuntu.com-and-canonical.com-?node-id=1-84&p=f&m=dev)
- Perform searches for no result and result pages
Fixes [WD-17811](https://warthogs.atlassian.net/browse/WD-17811)
[WD-17811]: https://warthogs.atlassian.net/browse/WD-17811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Rebrand search page

---

templates/test.html
webapp/handlers.py

- Add `frame-ancestors` to prevent clickjacking
- Added https://ubuntu-com-15263.demos.haus/test route to QA blank iframe
- Fixes `X-Frame-Options` vulnerability [here](https://securityheaders.com/?q=ubuntu.com&followRedirects=on)
- Go to any page e.g https://ubuntu-com-15263.demos.haus/
- Go to **Network** tab, reload page
- Click on the first main request of the page
- Look into **Response Headers** section and check `Content-Security-Policy: ...frame-ancestors 'none'` is present
- Go to https://ubuntu-com-15263.demos.haus/test
- Check that there is a errored blank iframe
Fixes [WD-23225](https://warthogs.atlassian.net/browse/WD-23225) …

security: add frame-ancestors to CSP to prevent clickjacking

---

navigation.yaml
templates/summit/index.html

- Update ubuntu.com/summit page.
[Demo](https://ubuntu-com-15266.demos.haus/summit)
[Doc](https://docs.google.com/document/d/1lj-xPVQjWqo2J_eZ-3ldKhJHj6RQ0Cwmk_Mr4QA4UTY/edit?tab=t.0)
Figma designs were not provided.
Fixes [#WD-22824](https://warthogs.atlassian.net/browse/WD-22824)

copy: update ubuntu.com/summit. WD-22824

---

webapp/shop/cred/exams.json

- Enable CUE.02 Desktop exam for production access
- Go to [ubuntu.com/credentials/shop](ubuntu.com/credentials/shop) and you should see CUE.01 and CUE.02 exams with CUE.02 at a discounted price of zero dollars (only internal users should be able to buy CUE.02)

fix: enable production access for CUE.02 desktop exam

---

webapp/views.py

- Only overwrite the country field on enrichment forms with IP address if the form does not have a Country formfield
- Go to any form that has Country field, e.g https://ubuntu-com-15269.demos.haus#get-in-touch
- Select a different country from the pre-selected dropdown
- Submit form, check payload
- See that country code reflects the chosen country
- Check that the same country code is submitted to Marketo successfully
- Repeat with a form that does not have Country field, e.g https://ubuntu-com-15269.demos.haus/download/mediatek-genio/contact-us
- Check on Marketo that the Country field is submitted as the country of IP address
Fixes [WD-23224](https://warthogs.atlassian.net/browse/WD-23224)
[QA …

fix: update country from IP address if not provided in form field

---

webapp/app.py
webapp/views.py
yarn.lock

Exposes the endpoint [/engage/metadata.json](https://ubuntu-com-15235.demos.haus/engage/metadata.json). Which displays the metadata for all engage pages.
Included in the metadata is:
- active
- author (currently not available)
- form_id
- path
- resource_url
- topic_name
- webinar_code
- type
- tags
- Visit [/engage/metadata.json](https://ubuntu-com-15235.demos.haus/engage/metadata.json) and see if display the aforementioned data
Fixes https://warthogs.atlassian.net/browse/WD-22500

feat(api): Expose endpoint for engage page metadata

---

templates/support/index.html

The copy update WD-22487 included miscellaneous changes on the page along with specific changes to the SLA section. However, the SLA updates are only applicable from June 30th. It was requested that we omit these changes from the previous PR for this copy update (#15175), and merge everything else. This was completed. This current PR is a separate one specifically for the SLA changes, and **_should not be merged until June 30th_**.
- Copy update for SLA section on /support
- Go to https://ubuntu-com-15176.demos.haus/support
- Ensure changes match the [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit?tab=t.0#heading=h.6gxmmp5wr2i8)
[WD-22487](https://warthogs.atlassian.net/browse/WD-22487)
[QA …

Copy update for SLA section on /support

---

requirements.txt

Bump flask-base to 2.6.0
- Updated flask base to 2.6.0. This automates loading of prefixed env variables.
- Check that the demo runs

Bump flask-base to 2.6.0

---

templates/contact-us/form-data.json
templates/security/cmmc/form-data.json
templates/security/form-data.json
templates/shared/forms/form-fields.html

- update `/security` field IDs from `jobTitle` to `title`
- fly-by work: 
- update `inputName` for homepage form, fixes [this Sentry error](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/101278/?query=is%3Aunresolved%20marketo)
- add `slug` to form template field labels
- Go to /security#get-in-touch
- Submit form, see that there are no error banners and `#contact-form-fail` in the path
Fixes [WD-23403](https://warthogs.atlassian.net/browse/WD-23403)
[WD-23403]: https://warthogs.atlassian.net/browse/WD-23403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

fix: update /security jobtitle form IDs

---

templates/blog/article.html
tests/test_blog_notice.py

- Trims whitespace in the old blogpost notification "year" pluralizer
- Open a blog post >= 2 years old, like [regex basics](https://ubuntu-com-15292.demos.haus/blog/regex-basics)
- Verify that "years" is displayed in the notification at top of the post
- Open a blog post older than 1 year, but less than 2 years old - like [Canonical's recipe for HPC](https://ubuntu-com-15292.demos.haus/blog/canonicals-recipe-for-high-performance-computing)
- Verify that "year" is displayed in the notification at top of the post
Fixes #15291 
[QA …

remove space between "year" and "s" in old blog article age notifications

---

templates/security/standards/form-data.json

- Added required fields for copydoc.
- Open the demo at: https://ubuntu-com-15314.demos.haus/security/standards
- Check that the form matches the copydoc
Fixes [WD-23206](https://warthogs.atlassian.net/browse/WD-23206)
[WD-23206]: https://warthogs.atlassian.net/browse/WD-23206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: added required fields 

---

templates/robotics/ros-esm.html

-  Updated /robotics/ros-esm.html
- Added extra docs button
- Added extra docs link
- Visit /robotics/ros-esm.html
- Ensure the additional links are present as described in the issue below
Fixes; https://warthogs.atlassian.net/browse/WD-23489

feat(copy): /robotics/ros-esm.html

---

webapp/shop/cred/views.py

- Check all contract items for reason, if it is `purchase_made`
- If it is, then get the accountID from that contract item
- If none of the items have the above reason, it is assumed they do not have a purchase account and are since not banned
- In an account with no purchases in cue marketplace, redeem a key for a CUE exam
- Navigate to your-exams and you should see that exam
Fixes [WD-23640](https://warthogs.atlassian.net/browse/WD-23640)
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/1 …

WD-23640: check for contract item's reason for purchase account's existence

---

templates/tutorials/tutorial.html

- Removes a # that is currently lingering in the tutorials template, causing a random "#" on the page on tutorials, such as [this one](https://ubuntu.com/tutorials/getting-started-with-microk8s-on-ubuntu-core)
- Open a tutorial
- Verify the hashtag that is shown on production is no longer there
Fixes https://chat.canonical.com/canonical/pl/33686rxeipnn3qhgqfcs9apudc

remove unexpected hashtag in the tutorials template

---

templates/download/risc-v/deepcomputing-fml13v01.html

- Adds link to download deepcomputing image at `/download/risc-v`
- Go to https://ubuntu-com-15327.demos.haus/download/risc-v
- Go to DeepComputing FML13V01 tab
- Check the new `Download` link is there as per [copy doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit?tab=t.jpjwa9vat62f)
Fixes [WD-23652](https://warthogs.atlassian.net/browse/WD-23652)
[WD-23652]: https://warthogs.atlassian.net/browse/WD-23652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add link to download deepcomputing image

---

static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx

- Check if product is free while making purchase
- Create a new account without a CC
- Purchase CUE.02 exam
- It should not throw any error
Fixes [WD-23710](https://warthogs.atlassian.net/browse/WD-23710)
[WD-23710]: https://warthogs.atlassian.net/browse/WD-23710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-23710: checkout error for zero price value products

---

templates/support/index.html

Remove footnote after "business hours" as requested. See [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit?tab=t.0#heading=h.f8sfjt722b10)
- Open demo: https://ubuntu-com-15338.demos.haus/support
- Compare with [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit?tab=t.0#heading=h.f8sfjt722b10), particularly the SLA table. 
Fixes #

/support: copy update

---

templates/pro/linux-patch-management-with-pro/bar-chart.html

- Fix numbers in packages chart in /pro/linux-patch-management-with-pro
- Visit [/pro/linux-patch-management-with-pro](https://ubuntu-com-15340.demos.haus/pro/linux-patch-management-with-pro)
Fixes [#WD-23792](https://warthogs.atlassian.net/browse/WD-23792)
Before:
After:

fix numbers in chart at /

---

navigation.yaml
static/js/src/advantage/linux-patch-management/components/CVESelector.tsx
static/js/src/advantage/linux-patch-management/components/CVETable.test.tsx
static/js/src/advantage/linux-patch-management/components/CVETable.tsx
static/js/src/advantage/linux-patch-management/components/ProContent.tsx
templates/pro/linux-patch-management-with-pro/bar-chart.html
templates/pro/linux-patch-management-with-pro/index.html

- Update navigation items
- Add description to hero section
- Prefix `LTS` to release labels
- Fix copydoc link
- Fix number of packages in bar chart
- Go to https://ubuntu-com-15348.demos.haus/pro/linux-patch-management-with-pro
- Install the [Ubuntu Copy Docs](https://chromewebstore.google.com/detail/ubuntu-copy-docs/cmljegnknolilmjdconnapgllmefigfl) extension if you don't have it already
Fixes [WD-23819](https://warthogs.atlassian.net/browse/WD-23819)
[WD-23819]: https://warthogs.atlassian.net/browse/WD-23819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-23819] CVE coverage page copy updates

---

templates/security/cves/index.html

- Removed security api link (no copy doc for this page)
- View the site locally in your web browser at: https://ubuntu-com-15355.demos.haus/security/cves
- See that the "Security API" link has been removed
Suggested [here](https://chat.canonical.com/canonical/pl/eioa1apbkig3tk7h9zna5rn19c)

chore: Remove sec api link

---

templates/macros/_vf_pricing-block.jinja
templates/openstack/managed.html
templates/openstack/support.html
templates/security/cmmc/index.html
templates/security/vulnerability-management.html

- Implement single Pricing Block component
- Introduced changes to the pricing block pattern locally, upstream to Vanilla once this is merged
- Changes:
- Pricing block takes up entire `grid-row` if there is only one component
- Added `include_hr` param to show/hide `hr` above the title
- Make `title_text` an optional param
- Remove shallow section padding if `title_text` or `section_description` is absent
- Go to https://ubuntu-com-15365.demos.haus/openstack/managed
- Check that the single pricing block matches [Figma](https://www.figma.com/design/vH19y2J2YqwUfksebSUvTW/ubuntu.com-openstack?node-id=817-8294&m=dev)
Fixes [WD-23371](https://warthogs.atlassian.net/browse/WD-23371) …

feat: implement single Pricing Block component

---

.github/workflows/playwright.yaml
playwright.config.ts
static/js/src/dynamic-forms.js
static/js/src/static-forms.js
templates/kernel/real-time/contact-us.html
templates/shared/_default-contact-us-form.html
templates/shared/_pro-contact-us-form.html
templates/shared/forms/interactive/aws.html
templates/shared/forms/interactive/esm.html
templates/shared/forms/interactive/general.html
templates/shared/forms/interactive/landscape.html
templates/shared/forms/interactive/pricing-infra.html
templates/shared/forms/interactive/storage.html
templates/tests/_static-client-form.html
templates/tests/_static-default-form.html
templates/tests/_thank-you.html
tests/playwright/helpers/commands.ts
tests/playwright/helpers/form-fields.ts
tests/playwright/helpers/mockData.ts
tests/playwright/tests/forms.spec.ts
tests/playwright/tests/pro/checkout.spec.ts
tests/playwright/tests/static-forms.spec.ts
webapp/app.py

Note: Re-include certified tests before merging
- Implement testing for static contact forms
- Added dedicated forms for testing, using static form templates: `_client-contact-us.html`, `_default-contact-us.html`
- Implemented reusable helper functions to fill up form fields, can be reused when testing modals/form generator forms
- Tests included:
- Form ID validation
- Form submission validation
- ~Email validation~
- Radio field handling
- Required checkbox validation
- Fly-by: 
- Disable submit button on static & dynamic form initialisation if `js-required-checkbox` is present in the form
- Fix typo from `pindividual-developers` -> `individual-developers`
- Add `_radio_` prefix to fields on `_default-contact-us.html`
- See that …

test: implement playwright tests for static contact forms

---

templates/shared/forms/form-fields.html

- Added `autocomplete` attribute depending on the type of field
-  First name (given-name)
-  Last name (family-name)
- Email (email)
- Phone number (tel)
- Company/Company name (organization)
- Job title (organization-title)
- Open any form, for example https://ubuntu-com-15378.demos.haus/internet-of-things#get-in-touch
- Verify the autocomplete fields work in personal information section
Fixes #[WD-23441](https://warthogs.atlassian.net/browse/WD-23441)
[WD-23441]: https://warthogs.atlassian.net/browse/WD-23441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-23441] feat: add autocomplete attributes to form elements in form-generator template

---

templates/base_index.html

- Fixed the overflowing CTA
- View the site locally in your web browser at: https://ubuntu-com-15384.demos.haus/
- Verify the affected CTA (Learn more about cloud optimization) is not overflowing on medium/smaller screen sizes
Fixes #[WD-23251](https://warthogs.atlassian.net/browse/WD-23251)
[WD-23251]: https://warthogs.atlassian.net/browse/WD-23251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-23251] fix: CTA link overflow on u.com homepage

---

konf/site.yaml

- Added paths to the new /security/flat/notices.json endpoint
Fixes #

Add new endpoint path

---

requirements.txt

- Bump version for image template module
- View the site locally in your web browser at: https://ubuntu-com-15391.demos.haus/blog/linux-foundation-openstack
- Make sure the images are loading fine
- Check different random pages on https://ubuntu-com-15391.demos.haus and make sure the image-template module is working fine and the images are loading successfully.
- Fixes #[WD-24160](https://warthogs.atlassian.net/browse/WD-24160)
[WD-24160]: https://warthogs.atlassian.net/browse/WD-24160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: broken images on blog articles

---

static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.test.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx

- Avoid users from pressing the buy button when cc details are being updated
- Also add label to cc about the ability to delete it later
- Login using an account which already has a 
- Select a product at /pro/subscribe
- Proceed to checkout
- Fill out the form
- Change the network speed to 3g to exaggerate the effects
- Click on edit to edit the credit card details
- Could also  
- Click on save
- Save button should go into loading state
-  While the cc is being saved, submit the form after completing the necessary details
- The submit button should be disabled till the …

Wd 24133 avoid users from pressing the buy button when cc details are being updated

---

webapp/shop/cred/syllabus.json

- Updated content of /credentials/exam-content to match [copy doc](https://docs.google.com/document/d/1bnA-f5m2zvZLh8NB2eR51s--7DarJTmWLXjWShK6378/edit?tab=t.0#heading=h.jz78yovdsvhq)
- Visit https://ubuntu-com-15400.demos.haus/credentials/exam-content
- Navigate to "Using Ubuntu Desktop" tab
- Compare the content of the page with the [copy doc](https://docs.google.com/document/d/1bnA-f5m2zvZLh8NB2eR51s--7DarJTmWLXjWShK6378/edit?tab=t.0#heading=h.jz78yovdsvhq)
Fixes #[WD-24292](https://warthogs.atlassian.net/browse/WD-24292)
Before:
After:
[WD-24292]: https://warthogs.atlassian.net/browse/WD-24292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

WD-24292: Update ubuntu.com/credentials/exam-content

---

templates/templates/_tag_manager.html

The event listener was changed from 'load' to 'DOMContentLoaded' to ensure GTM initializes earlier in the page lifecycle. Also added a 2-second delay to prevent potential race conditions.
- Check out the [demo](https://ubuntu-com-15412.demos.haus/) link
- Check the console and ensure `dataLayer` is present and has the load event in them
Fixes # https://warthogs.atlassian.net/browse/WD-24532

fix: change GTM initialization from 'load' to 'DOMContentLoaded`

---

konf/site.yaml

- This PR redirects traffic to specific flat/notices pods in the security api.
- To be merged after https://github.com/canonical/ubuntu-com-security-api/pull/221
- Staging has been deployed, test it at https://staging.ubuntu.com/security/flat/notices.json
Fixes [WD-24490](https://warthogs.atlassian.net/browse/WD-24490)
[WD-24490]: https://warthogs.atlassian.net/browse/WD-24490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: added konf config for flat notices

---

static/js/src/advantage/linux-patch-management/utils/helpers.ts

- Fix the missing datasheet in /pro/linux-patch-management-with-pro
- Visit [Pro CVE page](https://ubuntu-com-15423.demos.haus/pro/linux-patch-management-with-pro)
- Table of CVEs should be visible
- The section with the search and filtering of packages is also visible
Fixes [#WD-24562](https://warthogs.atlassian.net/browse/WD-24562)

fix link to data sheet

---

webapp/views.py

- Redirect to referrer URL on failed form submissions
- Go to https://canonical-com-1845.demos.haus/openstack#get-in-touch 
- Submit form
- See that it redirects to https://canonical-com-1845.demos.haus/openstack#contact-form-fail instead of ubuntu.com
Fixes [WD-24539](https://warthogs.atlassian.net/browse/WD-24539)
[WD-24539]: https://warthogs.atlassian.net/browse/WD-24539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: redirect to referrer for failed submissions

---

meganav.yaml
navigation.yaml
templates/frame/base_frame.html
templates/frame/form-data.json
templates/frame/index.html
templates/internet-of-things/smart-displays.html
webapp/handlers.py

Blocked by https://github.com/canonical/canonical.com/pull/1823
- Migrated and Rebranded the Mir Server Ubuntu Frame page from mir-server.io/ubuntu-frame to /frame
- Check out the [demo page](https://ubuntu-com-15395.demos.haus/frame)
- Cross-check implementation against
- [Figma](https://www.figma.com/design/daTnm6OGHWmBFc0FZ67IYP/ubuntu.com-frame?node-id=12-4102&m=dev)
- [Copydocs](https://docs.google.com/document/d/1P4xOahtq6VVY6llAAAmQ4cX7ip4zzNXxXciuZ9joxMw/edit?tab=t.0)
- Check against
- Mobile
- Tablet
- Desktop
PR is also related to [#1813](https://github.com/canonical/canonical.com/pull/1823)
Fixes # [WD-18820](https://warthogs.atlassian.net/browse/WD-18820) …

[Rebrand & Migrate] Ubuntu frame 

---

releases.yaml

- Updated release checksums based on provided links in ticket
- Check that the 24.04.3 links work as expected on the following pages: 
Fixes https://warthogs.atlassian.net/browse/WD-24635

Update point release checksums

---

redirects.yaml
templates/frame/index.html

- Fix mir-server link redirects
- Fix image on Ubuntu/frame
- Check out [demo](https://ubuntu-com-15438.demos.haus/frame) link image displays well compared to https://ubuntu.com/frame
- Check [tutorials/secure-ubuntu-kiosk](https://ubuntu-com-15438.demos.haus/tutorials/secure-ubuntu-kiosk) redirects to https://canonical.com/mir/docs/make-a-secure-ubuntu-web-kiosk
- Check [tutorials/electron-kiosk/](https://ubuntu-com-15438.demos.haus/tutorials/electron-kiosk/) redirects to https://canonical.com/mir/docs/make-a-secure-ubuntu-web-kiosk
Fixes #

fix: ubuntu/frame image & mir-server.io links

---

templates/security/fedramp.html

- Change text in "Patching security vulnerabilities" section of /security/fedramp
- Check that the copy doc matches the page
- Navigate to `/security/fedramp` in the demo server. 
- Check that the copy doc matches the page
[Demo server](https://ubuntu-com-15455.demos.haus/security/fedramp)
[Copy doc](https://docs.google.com/document/d/1eJxGEthPLxG2CjFXTXLk6QF97DNh4VyZZ-AG2yIq8v4/edit?usp=sharing)
Fixes #
[WD-24743 Jira ticket](https://warthogs.atlassian.net/browse/WD-24743)

copy: update patching security vulnerabilities text in /security/fedramp

---

navigation.yaml
static/js/src/advantage/api/contracts.js
static/js/src/advantage/manage-subscription.js
static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx
static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx
static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
static/js/src/advantage/react/hooks/index.ts
static/js/src/advantage/react/hooks/useHasPaymentMethod.test.tsx
static/js/src/advantage/react/hooks/useHasPaymentMethod.ts
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.test.tsx
static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx
static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx
static/js/src/ua-payment-methods.js
static/sass/styles.scss
templates/account/payment-methods/_confirm-remove-modal.html
templates/account/payment-methods/index.html
templates/advantage/index.html
tests/shop/advantage/test_api.py
webapp/app.py
webapp/shop/api/ua_contracts/api.py
webapp/shop/schemas.py
webapp/shop/views.py

- Update "payment methods" page to allow removing the payment method
- If removed, show warning notification on Pro dashboard and disable renewal and resize features
- Use singular: "Payment method", as there's only one
- Open demo or run site locally
- Go to /account/payment-methods
- Remove the credit card
- Compare with [design](https://www.figma.com/design/GXrVXEGISyJVJbGk4V7PoD/25.04-Pro-Dashboard-Updates?node-id=8-3942&p=f&t=f9UtOJUOG1kzNobH-0)
https://warthogs.atlassian.net/browse/WD-18327
Note: This PR is copy of https://github.com/canonical/ubuntu.com/pull/14670
Making dup because CLA checks failing

Credit card management updates deux

---

konf/site.yaml
tests/test_routes.py
webapp/handlers.py

Staging pages, especially security CVEs are being indexed by google ahead of the main website.
- Added env variable `FLASK_ENV` to distinguish between production and other environments. This env variable is automatically injected into the charm config so it seemed like a good candidate for this use.
- Returned [`X-Robots-Tag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Robots-Tag) header as `none` when not on production.
- Open the [demo](https://ubuntu-com-15467.demos.haus/), and with developer tools open, in the network tab check for the `X-Robots-Tag` header and see that it is set to `none`
Fixes [WD-25019](https://warthogs.atlassian.net/browse/WD-25019) …

Disable robots index on staging

---

templates/download/core/index.html
templates/download/desktop/index.html
templates/download/raspberry-pi/thank-you.html
templates/download/risc-v/allwinner-nezha.html
templates/download/shared/_verify-checksums.html

- Finds places where the values from [releases.yaml](https://github.com/canonical/ubuntu.com/blob/main/releases.yaml) could be used and updates them
- Tracked in this [spreadsheet](https://docs.google.com/spreadsheets/d/1faYkCW0aNgqro3kC7mp51qoOuAA2de7uwLVHeb4Ut7U/edit?gid=21472837#gid=21472837) under the tab 'Places old keys could be used'
- Open the demo and the spreadsheet
- Visit each of the pages that a variable has been applied and check there are no errors and that the links match those on live _and_ work
- Check that the places that have been updated are logical (ie. if it says something about lts but then a key for latest is used, this would be bad)
Fixes https://warthogs.atlassian.net/browse/WD-24271

Update codebase with pre-existing releases.yaml values

---

templates/confidential-computing/base_confidential-computing.html
templates/confidential-computing/form-data.json
templates/confidential-computing/index.html
webapp/views.py

- Implement modal with requested "Comment" field
- Add `is-paper` class and format file
- Fly-by work: Allow hash value to persist on successful form submission 
- Go to https://ubuntu-com-15461.demos.haus/confidential-computing#get-in-touch
- See that "What do you want to talk to us about" field is present
- Fill up form, submit
- See that it redirects to https://ubuntu-com-15461.demos.haus/confidential-computing#contact-form-success
Fixes [WD-24787](https://warthogs.atlassian.net/browse/WD-24787)
[WD-24787]: https://warthogs.atlassian.net/browse/WD-24787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

feat: update /confidential-computing modal

---

webapp/views.py

- Adds a flash to successful form submissions. This avoids a bug [here](https://github.com/canonical/ubuntu.com/blob/main/templates/templates/_notifications.html#L60) where the absence of a message was causing it to tell the user it has failed
- Check out this branch locally (demos will not work with marketo right now)
- Go to `http://0.0.0.0:8001/engage/what-is-ubuntu-pro` in incognito mode
- Fill in the form and submit it
- See no 'Failed form' message
Fixes https://warthogs.atlassian.net/browse/WD-25744

fix: Flash a message on successfull form submissions to avoid false negatives

---

templates/azure/base_azure.html
templates/azure/confidential-computing/form-data.json
templates/azure/confidential-computing/index.html
templates/azure/form-data.json
templates/azure/index.html
templates/azure/pro.html
templates/azure/sql.html
templates/azure/support.html
webapp/app.py

The form being used on all pages in the Azure bubble is a form specific form confidential computing
- Creates a new modal form to be shared between all Azure bubble pages (except `/azure/confedential-computing`) based on the form found at https://ubuntu.com/azure/contact-us
- Migrates the `confedential-computing` form (which was being used on all the Azure bubble pages) to use the form generator and only use it for `/azure/confedential-computing`
Fly by:
- Adds some basic error handling for the form generator
- Formatting
For Azure bubble
- Open to the demo to https://ubuntu-com-15491.demos.haus/azure
- Check the form has the same content as the form at https://ubuntu.com/azure/contact-us
- Check it submits successfully and goes through to Marketo. Repeat for the other affected pages: …

Migrate Azure bubble to use form generator

---

templates/templates/_notifications.html

- Removes the fallback message as this was resolving to true in many cases and causing the failed message to display.
- Check out this branch locally (demos will not work with marketo right now)
- Go to `http://0.0.0.0:8001/engage/what-is-ubuntu-pro` in incognito mode
- Fill in the form and submit it
- See no 'Failed form' message
Fixes https://warthogs.atlassian.net/browse/WD-25744

fix: Remove fallback message in failed form notification

---

redirects.yaml

- Redirect /legal to canonical.com/legal
- Open https://ubuntu-com-15515.demos.haus/legal
- See you are redirect to https://canonical.com/legal
https://warthogs.atlassian.net/browse/WD-26006

feat: Add missing /legal redirect

---

static/js/src/advantage/subscribe/checkout/app.tsx
static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx
static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx
static/js/src/advantage/subscribe/checkout/hooks/postPurchase.tsx
static/js/src/advantage/subscribe/checkout/hooks/usePreview.tsx
static/js/src/advantage/subscribe/checkout/utils/types.ts
static/js/src/advantage/subscribe/react/components/PaymentButton/PaymentButton.tsx
webapp/shop/advantage/views.py
webapp/shop/api/ua_contracts/advantage_mapper.py
webapp/shop/schemas.py

- Add referral links for Pro shop
- Visit /pro/subscribe?referral_id=1234
- Click on buy button 
- Check the localStorage which should have the referral_id stored in the product metadata
- In the checkout proceed to pay
- Check the purchase request
- Should have referral Id in the request body  
- To verify that the purchase has the metadata stored correctly. visit 
https://contracts.staging.canonical.com/v1/purchases/{{purchaseID}}/details and search for `1234`. PurchaseID can be seen from the backoffice or the /account/invoices page
Fixes …

[WD-21294] Pro shop - add referral links for sales

---

.github/workflows/sitemap.yaml

- Updated sitemap secrets on the repository
- Explicitly declare env variables on GH actions
- See that [`generate sitemap action`](https://github.com/canonical/ubuntu.com/actions/runs/17259504351/job/48977674188?pr=15533) passes
Fixes [WD-26152](https://warthogs.atlassian.net/browse/WD-26152)
[WD-26152]: https://warthogs.atlassian.net/browse/WD-26152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: add explicit env variable

---

redirects.yaml

- Added redirect for blog post
- Verify that https://ubuntu-com-15547.demos.haus/blog/charmed-aether-sd-core-beta-release-announcement redirects to  https://canonical.com/solutions/telco 
Fixes # https://warthogs.atlassian.net/browse/WD-25993

Feat: Added redirect for blog post

---

templates/20years/index.html
templates/advantage/_table.html
templates/advantage/blender/index.html
templates/appliance/shared/_base_appliance_index.html

- Replace static image tags with image template function for better image loading and optimisation.
- Check out the demo links
- https://ubuntu-com-15539.demos.haus/20years
- https://ubuntu-com-15539.demos.haus/appliance/lxd
- https://ubuntu-com-15539.demos.haus/blender
Fixes # https://warthogs.atlassian.net/browse/WD-25999

use image template on /20years & /appliance

---

konf/site.yaml
templates/credentials/base_cred.html

- Add maintenance window to credentials
- Update maintenance window message
- Locally, update the CRED_MAINTENANCE = true and set CRED_MAINTENANCE_START and CRED_MAINTENANCE_END so that current time falls in the window
- Take a look at credentials pages, you should see a banner notifying the maintenance window
Fixes [WD-26284](https://warthogs.atlassian.net/browse/WD-26284)
[WD-26284]: …

fix(WD-26284): add maintenance window

---

secondary-navigation.yaml

- updated nav for /ai
- Visit [demo](https://ubuntu-com-15557.demos.haus/ai) and see if it matches
Fixes # https://warthogs.atlassian.net/browse/WD-26149

Feat: Updated nav for /ai

---

konf/site.yaml

Deployments seem to be failing due to a [key mismatch](https://jenkins.canonical.com/webteam/job/ubuntu.com/1774/consoleFull) on kubernetes
- Use single global env variable for marketo, as they are the same. This should also help prevent any duplicate key references in the final deployment yaml.
- Check that the demo deployment succeeded
- View the demo locally in your web browser at: https://ubuntu-com-15571.demos.haus/
Fixes [WD-26402](https://warthogs.atlassian.net/browse/WD-26402)
[WD-26402]: https://warthogs.atlassian.net/browse/WD-26402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …

Use global MARKETO_API_URL env

---

templates/20-04/index.html

Add a link to pro free trial on 20.04 page.
- View the site locally in your web browser at: http://0.0.0.0:8001/20-04
- Check there is a link to `/pro/free-trial` as per the copydoc
Fixes https://warthogs.atlassian.net/browse/WD-26271

Add a link to pro free trial on 20.04 page.

---

templates/400.html
webapp/views.py

- Display error page with message for invalid marketo ID submission
- View the site  in your web browser at: https://ubuntu-com-15613.demos.haus/internet-of-things/appstore
- Scroll down to newsletter signup
- Enter your email and submit the form
- Verify it displays 400 error page, with custom message
Fixes #[WD-23405](https://warthogs.atlassian.net/browse/WD-23405)
[WD-23405]: https://warthogs.atlassian.net/browse/WD-23405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-23405] feat: show error page if marketo ID is invalid

---

templates/kernel/real-time/contact-us.html

- Add missing country field
- Go to https://ubuntu-com-15614.demos.haus/kernel/real-time/contact-us
- See that country field is present in the form
- Fill up form and see that it goes through as expected
Fixes [WD-26958](https://warthogs.atlassian.net/browse/WD-26958)
[WD-26958]: https://warthogs.atlassian.net/browse/WD-26958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add country field to /kernel/real-time/contact-us form

---

konf/site.yaml

- Add `MARKETO_API_URL` to `site.yaml` as it is being used as an env variable (currently production is deployed on PS5 )
- Go to `/credentials/sign-up` and make sure it is working correctly
Fixes [WD-26947](https://warthogs.atlassian.net/browse/WD-26947)
[WD-26947]: https://warthogs.atlassian.net/browse/WD-26947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(WD-26947): add marketo api url to site.yaml

---

templates/sitemap_index.xml
webapp/app.py
webapp/security/views.py

- Dynamically generate sitemap for /security/vulnerabilities
- Verify vulnerabilities sitemap at https://ubuntu-com-15621.demos.haus/security/vulnerabilities/sitemap.xml
Fixes #[WD-27000](https://warthogs.atlassian.net/browse/WD-27000)
[WD-27000]: https://warthogs.atlassian.net/browse/WD-27000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-27000] feat: dynamically generated vulnerabilities sitemap

---

templates/kubernetes/index.html

Remove logo as requested in the [ticket](https://warthogs.atlassian.net/browse/WD-27023).
- Check [demo](https://ubuntu-com-15625.demos.haus/kubernetes#:~:text=public%20cloud%20to-,edge,-Bootstrap%0Ayour%20Kubernetes)
- The logo is not there 
https://warthogs.atlassian.net/browse/WD-27023

[WD-27023] Copy update: /kubernetes

---

templates/download/risc-v/allwinner-nezha.html
templates/download/risc-v/deepcomputing-fml13v01.html
templates/download/risc-v/index.html
templates/download/risc-v/microchip-curiosity.html
templates/download/risc-v/microchip-polarfire.html
templates/download/risc-v/milk-v-mars.html
templates/download/risc-v/pine64-star64.html
templates/download/risc-v/qemu-emulator.html
templates/download/risc-v/sifive-unmatched.html
templates/download/risc-v/sipeed-licheerv.html
templates/download/risc-v/starfive-visionfive.html

- Remove the 25.04 download links from the RISC-V download page.
[Doc](https://docs.google.com/document/d/1kkJeq9HdH3iWV35HwihcJd3CxZw9Jy21W66lJl8VbWs/edit?tab=t.eaza04uc1o36#heading=h.kmwms8mtcb3m)
[Demo](https://ubuntu-com-15615.demos.haus/download/risc-v)
Fixes [#WD-26752](https://warthogs.atlassian.net/browse/WD-26752) …

copy: update /download/risc-v for Ubuntu 25.10 release

---

webapp/views.py

- Fixed marketo form submissions failing for new lead creations
- Open Incognito browser (different browser from everyday usage, if possible)
- Go to https://ubuntu-com-15637.demos.haus/download/server/thank-you?version=24.04.3&architecture=amd64&lts=true
- Click on "Download the CLI cheat sheet" button
- Fill in the form and submit
- Verify the form submission is successful, and cheat sheet is visible
Fixes #[WD-26079](https://warthogs.atlassian.net/browse/WD-26079)
[WD-26079]: https://warthogs.atlassian.net/browse/WD-26079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WD-26079] fix: marketo forms failing for new creations

---

static/js/src/tutorial-list.js
static/js/src/tutorial-list.test.js
webapp/views.py

Topic preselection in tutorials was failing when URL parameters had different casing than the stored category values. For example, ?topic=OpenStack wouldn't preselect the "openstack" option in the dropdown.
- Fixes a case where the tutorials page have topics with none lowercase text such as Cloud or AWS e.tc
- Check out the demo and check that [/tutorials?topic=openstack](https://ubuntu-com-15669.demos.haus/tutorials?topic=openstack) and [/tutorials?topic=Openstack](https://ubuntu-com-15669.demos.haus/tutorials?topic=Openstack) works
- Compare that with https://ubuntu.com/tutorials?topic=openstack and https://ubuntu.com/tutorials?topic=Openstack
Fixes # https://github.com/canonical/ubuntu.com/issues/11374
https://warthogs.atlassian.net/browse/WD-27640
[If relevant, please include a …

Make sure tutorial topics are case-insensitive 

---

package.json
yarn.lock

- update @canonical/latest-news dependency to 2.0.0 which added Cloudinary CDN support for images and Implements image lazy loading option
- Check out this page with latest news: https://ubuntu-com-15668.demos.haus/desktop/developers
- [/16-04](https://ubuntu-com-15668.demos.haus/16-04#:~:text=Latest%20from%20our%20blog%C2%A0%E2%80%BA)
- [/azure](https://ubuntu-com-15668.demos.haus/azure#:~:text=Latest%20from%20our%20blog%C2%A0%E2%80%BA)
- Scroll to the bottom (section before the footer)
- Check that news load
- Check that the package upgrade features are present by inspecting the cards and seeing that
- the image have `loading="lazy"`
- the image use cloudinary to route the assets URL
- Be sure to test on mobile, tablet …

build: update @canonical/latest-news dependency to 2.0.0

---

webapp/constants.py

- add tracking-api.g2.com to CSP allowlist
- Check out the [demo](https://ubuntu-com-15678.demos.haus/)
- Open dev tools
- Check that the console has no errors `Content-Security-Policy: The page’s settings blocked a script` about tracking-api.g2.com
Fixes # https://warthogs.atlassian.net/browse/WD-27681

Add tracking-api.g2.com to CSP allowlist

---

navigation.yaml

- Upgrade navigation link from 18.04 upgrade to 20.04 upgrade
- Check out the support section on the meganav in the [demo](https://ubuntu-com-15681.demos.haus/) (under quick links).
- Make sure the link and text are updated per this [comment in the copy doc](https://docs.google.com/document/d/1DCNvYHfC7AbOcqflTBaVd571iKAP_PaTfnqTENVEDVw/edit?disco=AAABrUkkx-E).
- [WD-27088](https://warthogs.atlassian.net/browse/WD-27088)
[WD-27088]: https://warthogs.atlassian.net/browse/WD-27088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-27088 - Copy update: Upgrade navigation link from 18.04 upgrade to 20.04 upgrade

---

templates/download/qualcomm-iot/tabs/development-board-tab.html

Updated two links under the "RUBIK Pi 3 development board" tab.
(copy doc: https://docs.google.com/document/d/1BP2T63R6kdnUFQFIZcbXbTIgY-9fQVgVRLsSUU5Rvx8/edit?tab=t.0)
- View the site locally in your web browser at: http://0.0.0.0:8001/download/qualcomm-iot
https://warthogs.atlassian.net/browse/WD-27903

chore(qualcomm-iot): adapted two links on the Rubik Pi3 tab

---

templates/toolchains/java.html

- copy: toolchains/java wording on ubuntu pro and support period
- [copydoc](https://docs.google.com/document/d/1ShgZyjn6pBG-L5iVd-MEIwc1JRVhaSeUFoImo5iWO-k/edit?tab=t.0)
- check the page on [toolchains/java in the demo server](https://ubuntu-com-15693.demos.haus/toolchains/java)
Fixes [WD-27261](https://warthogs.atlassian.net/browse/WD-27261)
[WD-27261]: https://warthogs.atlassian.net/browse/WD-27261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmND …

copy: toolchains/java wording on ubuntu pro and support period

---

templates/download/contact-us.html
templates/download/form-data.json
tests/test_marketo.py

- Migrated all static download forms to form generator
- Uncommented error failure block that was previously thrown by `/download/contact-us.html`
- Checkout this branch locally
- Run `dotrun test-marketo`, see that all tests pass
- Go to https://ubuntu-com-15687.demos.haus/download/contact-us
- Submit form and see that it goes through Marketo successfully
- Repeat with all other download forms
- https://ubuntu-com-15687.demos.haus/download/contact-us?product=supported-platforms
- https://ubuntu-com-15687.demos.haus/download/contact-us?product=qualcomm-iot
- https://ubuntu-com-15687.demos.haus/download/contact-us?product=renesas-iot
Fixes [WD-27755](https://warthogs.atlassian.net/browse/WD-27755) and [WD-26789](https://warthogs.atlassian.net/browse/WD-26789)
[If relevant, please include a …

refactor: Migrate /download/contact-us forms to form generator

---

static/js/src/release-chart-old.js

Updated release cycle diagram legend at `/security/esm` according to:
- [WD-28062](https://warthogs.atlassian.net/browse/WD-28062)
- [Copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit?tab=t.0)
- View the site locally in your web browser at: http://0.0.0.0:8001/security/esm
[WD-28062]: https://warthogs.atlassian.net/browse/WD-28062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Copy update to /security/esm diagram legend

---

templates/download/server/thank-you-s390x.html

- Added a resource link (webinar) to match copytext.
- Changed resources' class to col-2 so all 4 fit neatly on one row.
- Navigate to /download/server/thank-you-s390x for 25.10
- Check that a 4th resource is added (Webinar), to match [this copytext](https://docs.google.com/document/d/1GptXtMfbgOjOmqb8DZCCTRwogkiP_cM95U9Z0gFSt7g/edit?tab=t.0)
Fixes # [WD-27722](https://warthogs.atlassian.net/browse/WD-27722)
[WD-27722]: …

fix: (WD-27722) Update u.com/download/server/thank-you-s390x for 25.10

---

templates/robotics/index.html

- Updated the Hero image classname
- Check [/robotics](https://ubuntu-com-15676.demos.haus/robotics)
- Compare that to prod https://ubuntu.com/robotics
Fixes #

fix: robotics page image container class

---

templates/download/server/manual.html

- Update Questing Quokka mascot image with [new image](https://assets.ubuntu.com/v1/fe84bc06-questing_quokka_mascot_circle_bg.svg)
- Go to https://ubuntu-com-15707.demos.haus/download/server
- See the mascot image with a black background

feat: Update Questing Quokka mascot image with black background version

---

navigation.yaml

- Removed "cloud native operations report" from meganav
- View demo: https://ubuntu-com-15710.demos.haus/
- Click on "Products" in the top nav, then click on "Kubernetes" subsection, then ensure that there are only 5 secondary links and that "Cloud native operations report" is not one of them
- Copy doc here: https://docs.google.com/document/d/1Y0dxbuar0UAPSCfILtP7fsEX-83yDh7Ha637FA9Wbik/edit?disco=AAABr6Uiqcg
[WD-29304](https://warthogs.atlassian.net/browse/WD-29304)
[WD-29304]: https://warthogs.atlassian.net/browse/WD-29304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WD-29304 (remove "cloud native operations report" from meganav)

---

templates/security/notices/usn.html

- Added missing support tag to table
- View the site locally in your web browser at: http://0.0.0.0:8001security/notices/USN-6895-1
- See that the supported release (Jammy) has the LTS mention whereas the unsupported release (Mantic) does not
Fixes https://warthogs.atlassian.net/browse/WD-29364

chore: Add release support tag to usn table

---

webapp/shop/cred/views.py

- Previously, when clicking "Your Exams" button on non-staging environment, it would redirect to the exam page rather than the P360's session check-in page
- This PR checks, regardless of the environment, if a P360 session exists and if it does, it redirects there. If not, it redirects to the exam page
- Purchase an exam using /credentials/shop
- Schedule the exam
- Visit /credentials/your-exams and click the "Take Exam" button when it appears
- This should redirect to P360 check-in session
- Proceed with the check-in and in the end you should be able to take the exam …

fix(WD-28107): redirect to P360 session when clicking "Take Exam" button
