canonical/ubuntu.com

- templates/engage/apparmor-intro.html
- templates/engage/shared/_header.html
- Created a new /engage/apparmor-intro page for apparmor
- Created a copy doc
- Tweaked the header include to have a width and a max-width and max-height
- View the site locally in your web browser at: [/engage/apparmor-intro](http://0.0.0.0:8001/engage/apparmor-intro)
- Compare to the [copy doc](https://docs.google.com/document/d/1ZfQbS1J85QBKURHpvHy75Pv4Jp0GU55aIM5OhF7n1fg/edit) and test the form
Fixes #4836
> Create apparmor engage page

- templates/takeovers/_french_vmware-to-os.html
* traditionnelle -> traditionnel on french takeover
> traditionnelle -> traditionnel

- static/sass/_layout-legal-pages.scss
- templates/legal/shared/_uasd_toc_new.html
- templates/legal/ubuntu-advantage-service-description/index.md
- Updated the ua service description page
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit#)
Fixes #4792
> [UA-I] updates for /uasd page

- templates/esm/index.html
- Copy updates for /esm
- View the site locally in your web browser at: [/esm](http://0.0.0.0:8001/esm)
- Compare to the [copy doc](https://docs.google.com/document/d/1BK-XXECYJJllG8jIe3WN3X8EMo_3wBBa03nlzYDP8xE/edit#)
Fixes #4879
> [UA4I] Update /esm

- templates/openstack/features.html
- updated storage section
- View the site locally in your web browser at: [/openstack/features](http://0.0.0.0:8001/openstack/features)
- compare to the [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Fixes #4797
> [UA-I] update /openstack/features

- templates/livepatch/index.html
- templates/shared/_call-sales.html
- Added call sales include on /livepatch
- View the site locally in your web browser at: [/livepatch](http://0.0.0.0:8001/livepatch)
- Compare to the [copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit)
Fixes #4877
> [UA4I] Update copy on /livepatch

- templates/openstack/storage.html
- Copy updates on the /openstack/storage page
- View the site locally in your web browser at: [/openstack/storage](http://0.0.0.0:8001/openstack/storage)
- Compare to the [copy doc](https://docs.google.com/document/d/1iw2SWNmoj4GZ2pUh0yB8gbtVXK0oXfyEaXT44bQbPlI/edit)
Fixes #4796
> [UA4I] Update /openstack/storage page

- templates/kubernetes/docs/monitoring.md
Changed some text on the monitoring page
- View the site locally in your web browser at: [http://0.0.0.0:8001/kubernetes/docs/monitoring.md](http://0.0.0.0:8001/kubernetes/docs/monitoring.md)
> Update the K8s docs for monitoring per 1.14 changes

- templates/shared/pricing/_kubernetes-consulting-add-ons.html
- templates/shared/pricing/_kubernetes-consulting.html
- templates/shared/pricing/_landscape.html
- templates/shared/pricing/_livepatch.html
- templates/shared/pricing/_maas-support.html
- templates/shared/pricing/_storage-support.html
- templates/shared/pricing/_ua-for-infrastructure.html
- templates/shared/pricing/_ua-server-support-add-ons.html
- templates/support/plans-and-pricing.html
- View the site locally in your web browser at: [/support/plans-and-pricing](http://0.0.0.0:8001/support/plans-and-pricing)
- Compare to the [copy doc](https://docs.google.com/document/d/1FS1slJOfWXLmPob1eXrQ32DU4s6WP4oyGoT3t5E4W8Y/edit#)
Fixes #4873
> [UA-I] updates for /support/plans-and-pricing page 

- templates/engage/14-04-esm.html
Updated copy to remove EOL references and register CTA, as webinar is happening now and will move to on-demand availability
> ESM webinar landing page updates

- templates/legal/shared/_appendix-support-scope.html
- templates/legal/shared/_appendix-support-scope.md
Remove the dates from the ESM content
> Remove the dates from the ESM content

- templates/legal/shared/_appendix-support-process.md
- templates/legal/ubuntu-advantage-service-description/new.md
Order the content in the Service initiation section to fix numbered lists in UASD
- Go to /legal/ubuntu-advantage-service-description#appendix-support-process-service-initiation
- Check the numbers are ordered correctly
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4918
> Order the content to fix numbered lists in UASD

- templates/embedded/base_embedded.html
- templates/embedded/index.html
- Created a quick demo of the /embedded page
- View the site locally in your web browser at: [/embedded](http://0.0.0.0:8001/embedded)
- Compare to the [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit#heading=h.c6wjbvvp8mcm)
Fixes #4864
> Draft of the new /embedded page

- static/sass/_layout-whitepapers.scss
- static/sass/_pattern_desktop-statistics.scss
- templates/whitepapers/beta/robotics.html
- templates/whitepapers/beta/shared/form.html
- templates/whitepapers/robotics/index.html
Add the robotics beta whitepaper
- Go to /whitepapers/robotics and check it all works
- Go to /whitepapers/beta/robotics and check it all works
Super-seeds: https://github.com/canonical-websites/www.ubuntu.com/pull/4847/
> Add the beta whitepaper

- templates/embedded/index.html
- templates/whitepapers/robotics/index.html
Quick fixes to the whitepaper and embedded page.
> Fix whitepaper and embedded tweak

- static/sass/_pattern_desktop-statistics.scss
- templates/embedded/index.html
Re-order the embedded page
- Go to /embedded and see the nav is further up
> Update the embedded page

- templates/desktop/developers.html
- Update the What's new section
**Note: this will not look 100% correct until the template variables are updated**
- View the site locally in your web browser at: [/desktop/developers](http://0.0.0.0:8001/desktop/developers)
- Compare to the [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#)
Fixes #4925
> Update /desktop/developers/ for 19.04

- templates/legal/index.html
updated Modern Slavery Statement pdf
- View the site locally in your web browser at: [http://0.0.0.0:8001/legal](http://0.0.0.0:8001/legal)
- click on 'Modern slavery statement' link and make sure opens the new [PDF](https://assets.ubuntu.com/v1/47d72a70-Modern+Slavery+Statement+2019.pdf)
Fixes [#4973](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4973)
> updated Modern Slavery Statement pdf

- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/release-notes.md
Updated release-notes docs
Updated manual-install docs
> Kubernetes Bugfix release 20190423

- templates/openstack/shared/_openstack_clients.html
- templates/security/index.html
- templates/support/index.html
- templates/telecommunications/index.html
- Updated the at&t logo
-  http://0.0.0.0:8001/support
-  http://0.0.0.0:8001/livepatch
-  http://0.0.0.0:8001/security
-  http://0.0.0.0:8001/telecommunications
-  http://0.0.0.0:8001/openstack
-  http://0.0.0.0:8001/rfp
- See that the new logo is in use
Fixes #4907
> Update at&t logo

- navigation.yaml
- templates/pricing/infra.html
- templates/shared/pricing/_maas-pricing.html
- templates/shared/pricing/_openstack-kubernetes-lma.html
- templates/shared/pricing/_ua-advanced-storage.html
- templates/shared/pricing/_ua-for-infrastructure.html
- Built /pricing/infra page as per [copydoc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit)
- **Note** I built new table includes because they'd changed a lot but haven't deleted the old ones yet
- View the site locally in your web browser at: [http://0.0.0.0:8001/pricing/infra](http://0.0.0.0:8001/pricing/infra)
- Check that page matches the [copydoc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit)
Fixes #5010
> 5010: Build /pricing/infra page

- templates/livepatch/index.html
Rebuild the livepatch page.
Search for more conflicts and found only this one.
- Go to /livepatch
- Check it matches [the copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit#)
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5017
> Rebuild the livepatch page for ua4i

- templates/pricing/index.html
- templates/pricing/infra.html
- templates/pricing/thank-you.html
- templates/shared/forms/interactive/_pricing-infra.html
- templates/shared/pricing/_maas-pricing.html
- templates/shared/pricing/_openstack-kubernetes-lma.html
- templates/shared/pricing/_ua-advanced-storage.html
- templates/shared/pricing/_ua-for-infrastructure.html
- Add a dynamic contact us form
- Add a thank-you page
- Remove contextual footer from section per Thibaut
- Fixed up rows and contact-us buttons on /pricing/infra
- View the site locally in your web browser at: [http://0.0.0.0:8001/pricing/infra#get-in-touch](http://0.0.0.0:8001/pricing/infra#get-in-touch)
- Test the form
- Compare to the [copy doc](https://docs.google.com/document/d/1sxbuM21CkBwFI722hUwE6p4P4R5EoXvNT9NMcuqrCT4/edit#heading=h.jsqxpsz4c39k)
Fixes #5011
> Add /pricing/infra contact-us form

- templates/openstack/storage.html
Rebuild the openstack storage page for ua4i
- Go to /openstack/storage
- Check it matches the [copy doc](https://docs.google.com/document/d/1iw2SWNmoj4GZ2pUh0yB8gbtVXK0oXfyEaXT44bQbPlI/edit#)
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5020
> Rebuild the openstack storage page for ua4i

- navigation.yaml
- templates/pricing/consulting.html
- Build the pricing/consulting page
- Add to the navigation
- Go to /pricing/consulting
- Check that is matches the [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#)
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5012
> Ua4i consulting

- templates/shared/_case-study-itstrategen.html
- templates/support/index.html
- Updated /support page to latest [copydoc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit)
- View the site locally in your web browser at: [http://0.0.0.0:8001/support](http://0.0.0.0:8001/support)
- Check the copy matches the [copydoc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit)
Fixes #5015
> 5015: Refresh /support page for UA-I update

- templates/kubernetes/index.html
- Update /kubernetes page for UA-I
- NOTE: the copy doc has an outstanding question for @Khutch25 but I have temp copy in place
- Compare to the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#)
Fixes #5042
> UA-I update /kubernetes page

- templates/server/index.html
- Update /server for UA-I
- View the site locally in your web browser at: [http://0.0.0.0:8001/server](http://0.0.0.0:8001/server)
- Compare to the [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#heading=h.6alb6mc7cvu9)
Fixes #5019
> ua-i update /server

- templates/openstack/features.html
Rebuild the openstack features page for ua4i
- Go to /openstack/features
- Check it matches [the copydoc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5018
> Rebuild the openstack features page for ua4i

- templates/engage/hiri-case-study.html
Build hiri landing page
- View the site locally in your web browser at: [/engage/hiri-case-study](http://0.0.0.0:8001/engage/hiri-case-study)
- Check [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4941) compliant
- Check [brief](https://docs.google.com/document/d/1nVAMTjUPiZwxoH9ysh06fbGACcPUNVu0QhYusaOKfIA/edit#) compliant
- Check [copydoc](https://docs.google.com/document/d/1B5ek9Mfina_c9rrnuUS9kgr1kzo-jqlcqoibIvEV9oU/edit#) compliant
Fixes [#4943](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4943)
> 4943 hiri landing page

- templates/kubernetes/index.html
- templates/pricing/consulting.html
- templates/pricing/index.html
- templates/pricing/infra.html
- templates/shared/pricing/_ua-advanced-storage.html
- templates/shared/pricing/_ua-for-infrastructure.html
Update links and final fixes
- Check the changes are correct
> Update links and final fixes

- templates/support/index.html
- Remvoed partially added matrix row
- View the site locally in your web browser at: [http://0.0.0.0:8001/support](http://0.0.0.0:8001/support)
- Compare to the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit)
> Fix /support table

- templates/legal/ubuntu-advantage-service-description/index.md
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit?ts=5cc6e867#)
Fixes #5055
> Update /uasd for UA-I

- templates/engage/lxd-whitepaper.html
- templates/index.html
- templates/takeovers/_lxd-takeover.html
Add LXD takeover and landing page
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) and [/engage/lxd-whitepaper](http://0.0.0.0:8001/engage/lxd-whitepaper)
- Make sure it complies with the [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5027) and [more design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5029)
-Make sure it complies with the [brief](https://docs.google.com/document/d/1zR-aMuCZJJXlmRXBK-XG2AQ8iOf6T10hhnS8tBYqjsI/edit#) and [copydoc](https://docs.google.com/document/d/1gcCaCuOdNBV8pqajXVCdAAxOT …
> 5029 lxd takeover and landing page

- static/sass/_layout-legal-pages.scss
- templates/legal/shared/_uasd_toc_new.html
- templates/legal/ubuntu-advantage-service-description/index.md
- rebuild /uasd from scratch
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit#)
Fixes #5070
> Update uasd page from scratch

- templates/index.html
> Remove 19.04 takeover

- templates/support/index.html
- Update UA datasheet on /support
- View the site locally in your web browser at: [http://0.0.0.0:8001/support](http://0.0.0.0:8001/support)
- Compare to the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit?ts=5cca902f)
Fixes #5084, #5078
> Update UA datasheet on /support

- templates/pricing/infra.html
- templates/shared/pricing/_openstack-kubernetes-lma.html
- templates/shared/pricing/_ua-advanced-storage.html
- templates/shared/pricing/_ua-for-infrastructure.html
- Updated the pricing/infra page
- View the site locally in your web browser at: [http://0.0.0.0:8001/pricing/infra](http://0.0.0.0:8001/pricing/infra)
- Compare to the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
Fixes #5090
> Update /pricing/infra page

- templates/legal/shared/_uasd_toc_new.html
- templates/legal/ubuntu-advantage-service-description/index.md
- Updated more text changes
- Try and compare to the changes in the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit#)
Fixes #5092
> Update text of /uasd

- templates/openstack/managed.html
Copy doc text changes
- View the site locally in your web browser at: [/openstack/managed](http://0.0.0.0:8001/openstack/managed)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit)
Fixes #1120
> Copy doc changes

- templates/ai/consulting.html
Minor [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit?usp=drivesdk) changes
- View the site locally in your web browser at: [/ai/consulting](http://0.0.0.0:8001/ai/consulting)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit?usp=drivesdk)
Fixes #5102
> Add copy doc changes

- requirements.txt
- templates/blog/article.html
**DEPENDS ON** https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/40/files
- Check out `blog/canonical-announces-support-for-ubuntu-on-windows-subsystem-for-linux-2` and make sure that the article page appears correctly
Fixes https://github.com/canonical-web-and-design/base-squad/issues/519
> Adds basic article page

- templates/legal/ubuntu-advantage-service-description/index.md
- More text updates for the service description
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit#heading=h.z1fa5mflx2ob)
Fixes #5112
> More /uasd changes

- templates/openstack/index.html
- Update CTAs on /openstack
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack](http://0.0.0.0:8001/openstack)
- Compare to the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit)
Fixes #5115
> Update CTAs on /openstack

- templates/security/certifications.html
Update page to match [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit)
- View the site locally in your web browser at: [/security/certifications](http://0.0.0.0:8001/security/certifications)
- Make sure the text matches the [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit) 
Fixes #5114
> Add changes from copy doc

- navigation.yaml
- templates/legal/data-privacy/esxi.md
Add /legal/data-privacy/esxi page
- View the site locally in your web browser at: [/legal/data-privacy/esxi](http://0.0.0.0:8001//legal/data-privacy/esxi)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/1I1PtxFqV1KNsnnxJlo-Q9V7JDvkbmsAxAvVk4Nf9aLQ/edit#)
Fixes #5131
> Add /legal/data-privacy/esxi page

- static/js/navigation.js
Pressing the back button closes the menu
- Click one of the top menu items then hit the back button. You should see the url changing and the menu closing.
Fixes #3920
> 3920 opening the menu breaks the back button

- templates/download/cloud/index.html
Remove highlighted cards
- View the site locally in your web browser at: [/download/cloud](http://0.0.0.0:8001/download/cloud)
- Make sure all the cards look the same and match the [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5105)
Fixes #5105
> Remove highlighted cards

- navigation.yaml
- requirements.txt
- static/sass/_pattern_blog-suru.scss
- static/sass/styles.scss
- templates/blog/blog-card.html
- templates/blog/internet-of-things.html
- templates/blog/pagination.html
- webapp/templatetags/utils.py
Improved blog/internet-of-things
Add navigation
Add template pagination
- View the site locally in your web browser at: [/blog/internet-of-things](http://0.0.0.0:8001/blog/internet-of-things)
- Make sure the page looks similar to [https://blog.ubuntu.com/internet-of-things](https://blog.ubuntu.com/internet-of-things)
- Make sure the filters work
- Make sure the pagination works
Fixes #5117 
Fixes #5121
> 5117 improve IoT template

- templates/ai/consulting.html
Update /ai/consulting to match [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit)
- View the site locally in your web browser at: [/ai/consulting](http://0.0.0.0:8001/ai/consulting)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit)
Fixes #5150
> Update /ai/consulting copy 

- navigation.yaml
- templates/blog/blog-card.html
- templates/blog/desktop.html
- templates/blog/internet-of-things.html
Improve the template blog/desktop
- View the site locally in your web browser at: [/blog/desktop](http://0.0.0.0:8001/blog/desktop)
- Make sure it looks and behaves similar to https://blog.ubuntu.com/desktop
Fixes #5118
> 5118 improve blog desktop template

- templates/blog/cloud-and-server.html
Improved blog/cloud-and-server
- View the site locally in your web browser at: [/blog/cloud-and-server](http://0.0.0.0:8001/blog/cloud-and-server)
- Ensure the page looks and behaves similarly to https://blog.ubuntu.com/cloud-and-server
Fixes #5119
> 5119 Improve cloud and server page

- templates/takeovers/_takeover-help.html
- templates/takeovers/shared/_takeover.html
Add takeover template
Add takeover template help page
- View the site locally in your web browser at: [/takeovers/_takeover-help](http://0.0.0.0:8001/takeovers/_takeover-help/)
- Go to the page and make sure you it is clear enough.
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5158
> Create takeover template

- .gitignore
- navigation.yaml
- requirements.txt
- templates/blog/archives.html
- templates/templates/_navigation.html
- webapp/templatetags/utils.py
Implemented blog/archives template
- View the site locally in your web browser at: [/blog/archives](http://0.0.0.0:8001/blog/archives)
- Ensure the page looks and behaves similarly to https://blog.ubuntu.com/archives
- Ensure the heading changes appropriately when a group filter is applied: http://0.0.0.0:8001/blog/archivesblog/archives?group=canonical-announcements
Fixes #5130
> 5130 implement blog archive

- package.json
- static/sass/_layout-documentation.scss
- static/sass/_layout-legal-pages.scss
- static/sass/_pattern_contact-modal.scss
- static/sass/_pattern_desktop-statistics.scss
- static/sass/_pattern_lists.scss
- static/sass/_pattern_navigation.scss
- static/sass/_pattern_separator.scss
- static/sass/_pattern_table.scss
- static/sass/_vanilla-placeholders.scss
- static/sass/styles.scss
- yarn.lock
- Upgrade vanilla version to 2.0.0-alpha
- rename spacing variables to match new names in vanilla
- include chevron that was taken out of vanilla
> vf2.0alpha: initial setup

- requirements.txt
- templates/blog/blog-card-large.html
- templates/blog/press-centre.html
Improved /blog/press-centre template to match https://blog.ubuntu.com/press-centre
- View the site locally in your web browser at: [/blog/press-centre](http://0.0.0.0:8001/blog/press-centre)
- Ensure the page looks and behaves similarly to https://blog.ubuntu.com/press-centre
Fixes #5120
> 5120 improve blog press centre

- requirements.txt
- templates/blog/archives.html
- templates/blog/author.html
- templates/blog/blog-card.html
Added author template
- View the site locally in your web browser at: [/blog/author/canonical](http://0.0.0.0:8001/blog/author/canonical)
- Ensure /blog/author/canonical looks similar to https://blog.ubuntu.com/author/canonical
- Ensure /blog/author/alexmurray looks similar to https://blog.ubuntu.com/author/alexmurray
Fixes #5135
> 5135 implement author page

- templates/desktop/index.html
Remove reference to Unity's LIM
- View the site locally in your web browser at: [/desktop](http://0.0.0.0:8001/desktop)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit#heading=h.j00cl08ux1et)
Fixes #3099
> Remove reference to Unity's LIM

- requirements.txt
- templates/blog/cloud-and-server.html
- templates/blog/desktop.html
- templates/blog/filters.html
- templates/blog/index.html
- templates/blog/internet-of-things.html
Add blog filter dropdown to /blog
- Ensure the filters dropdown behaves similarly to https://blog.ubuntu.com/
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1128
> 1128 add filters to blog index

- .github/stale.yml
Add config for “[Stale](https://github.com/probot/stale)” Github app
- Sanity check the config file
This runs on an hourly basis so within an hour of this landing, this will comment on quite a few issues as flagging them as stale.
> Add config for “Stale” Github app

- templates/download/desktop/thank-you.html
Update design and copy changes
- View the site locally in your web browser at: [/download/desktop/thank-you](http://0.0.0.0:8001/download/desktop/thank-you)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit#heading=h.1n027vkfftdm) and [design](https://github.com/canonical-web-and-design/web-squad/issues/848)
Fixes #2722
> Change to suit copy doc

- templates/ai/install.html
- templates/kubernetes/features.html
- templates/kubernetes/index.html
- templates/kubernetes/install.html
- templates/kubernetes/managed.html
- templates/kubernetes/partners.html
- templates/shared/contextual_footers/_download_more_info_enterprise.html
- templates/takeovers/_improving_productivity_kubernetes.html
- Updated Canonical and Ubunut Kubernetes to Charmed Kubernetes
- http://0.0.0.0:8001/ai/install.html
- http://0.0.0.0:8001/kubernetes/features.html
- http://0.0.0.0:8001/kubernetes/index.html
- http://0.0.0.0:8001/kubernetes/install.html
- http://0.0.0.0:8001/kubernetes/managed.html
- http://0.0.0.0:8001/kubernetes/partners.html
- Compare to the copy docs
- [ai install](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit#heading=h.x0g38awprz5e)
- [partners](https://docs.google.com/document/d/1vRlHxWr7pxstx5pOtqXWrIviX …
> Make use of name Charmed Kubernetes consistent

- templates/internet-of-things/index.html
Updated image for brand store on IoT section.
- Visit `/internet-of-things` and notice there is an image from limenet.snapcraft.io
- #winning
Fixes #3901
> Update image for app store

- static/sass/_pattern_blog-card.scss
- static/sass/_pattern_blog-featured.scss
- static/sass/_pattern_blog-suru.scss
Fix scss linter warnings (scss linter warnings will cause tests to fail as of [this PR](https://github.com/canonical-web-and-design/www.ubuntu.com/pull/5188))
- Run `./run test`
- See that the tests pass
> fix scss lints

- templates/download/iot/installation-media.html
> 32m -> 32M

- templates/blog/index.html
- templates/blog/internet-of-things.html
- templates/blog/newsletter-form.html
- templates/download/desktop/thank-you.html
- templates/shared/forms/_form-validation.html
Add newsletter signup form
- Make sure the form works and it behaves/looks the same as the one on https://blog.ubuntu.com/
Fixes #5122
> 5122 Add newsletter signup form

- requirements.txt
QA
--
`./run`, check the site runs fine.
> Explicitly require pyyaml 5.1 (needed for FullLoader)

- .github/stale.yml
per discussion with @anthonydillon
> Update stale to focus on ignored issues

- templates/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots.html
Add SRC landing page
- View the site locally in your web browser at: [/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots](http://0.0.0.0:8001/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots)
- Make sure it complies with the [brief](https://docs.google.com/document/d/1xhjiRveHItibFEqhZJdG_FYbgYVhWmZG2LAXYyzkyCk/edit?ts=5ced4c72)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1162
> Add SRC landing page

- templates/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots.html
Add title to the SRC page
- View the site locally in your web browser at: [/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots](http://0.0.0.0:8001/engage/autonomous-more-profitable-farming-using-AI-and-lightweight-robots)
- Make sure the page has a title
> Add title to the SRC page

- static/sass/_pattern_blog-topic.scss
- static/sass/styles.scss
- templates/blog/topics/maas.html
- webapp/urls.py
Add maas topic page
- View the site locally in your web browser at: [/blog/topics/maas](http://0.0.0.0:8001/blog/topics/maas)
- Make sure it looks and behaves like https://blog.ubuntu.com/topics/maas
Fixes #5156
> Add maas topic page

- package.json
- yarn.lock
Update vanilla to 2.0.0-beta in package.json.
Verify ./run downloads the beta release.
> update vanilla to beta

- templates/templates/footer.html
Footer: Fix grid classes so rows are direct parents of cols.
- Open any page and ensure footer columns work as expected.
> Footer: Remove unneeded classes

- templates/core/index.html
Update u.c/core page to match copy doc
- View the site locally in your web browser at: [/core](http://0.0.0.0:8001/core)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#heading=h.2ukzins7kdk5)
Fixes #5227
> Update u.c/core page to match copy doc

- templates/engage/starting-with-ai.html
- templates/takeovers/_starting-with-ai-takeover.html
- Updated image and text of the ai takeover
- Compare to the [brief](https://docs.google.com/document/d/1wc1YEeCDYplEv0HKJz59jGuh-OZ8tJoQ6cbJKKVk9tc/edit#)
Fixes #5241
> Update design of ai takeover and engage page

- templates/kubernetes/features.html
Update /kubernetes/features to suit copy doc
- View the site locally in your web browser at: [/kubernetes/features](http://0.0.0.0:8001/kubernetes/features)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#)
Fixes #5228
> Update /kubernetes/features to suit copy doc

- templates/download/desktop/index.html
Update the recommended RAM to 4GB
Update the copy doc link for download/desktop
- Check the update matches [the copy doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#)
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5246
> Update the recommended RAM to 4GB

- templates/engage/microsoft-active-directory.html
- templates/index.html
- templates/takeovers/_active-directory_takeover.html
Add Microsoft active directory takeover and engage page
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) and [/engage/microsoft-active-directory](http://0.0.0.0:8001/engage/microsoft-active-directory)
- Go to u.c and refresh the page until you see the Microsoft Active Directory takeover
- Click on "Download the whitepaper" to access the landing page
- Make sure it complies with the [design](https://github.com/canonical-web-and-design/web-squad/issues/1198)
- Make sure it complies with the [brief](https://docs.google.com/document/d/1mj6nl2MKIn8gSGnwkX8e4YR …
> Microsoft active directory takeover and engage

- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/release-notes.md
- updated links for latest version of CDK bundle
- added release notes for hotfix release
> Add release notes for CDK hotfix

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/TAKEOVER_ISSUE.md
- .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/TAKEOVER_PR.md
- Add front-matter to gh templates, they don't seem to work otherwise
> Add front-matter to gh templates

- static/js/core.js
- static/sass/_pattern_navigation.scss
- static/sass/_vanilla-placeholders.scss
Fix spacing issues with the secondary nav
- Verify secondary nav looks ok
> Secondary nav fixes

- templates/download/desktop/thank-you.html
- templates/templates/_tag_manager.html
* Re-enable anti-flicker snippet for Optimize experiments on /download/desktop/thank-you
> Re-enable optimize anti-flicker snippet

- templates/takeovers/_starting-with-ai-webinar_takeover.html
Change AI takeover subtitle to "Explore what AI can do for your business and what you need to get up and running."
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) 
- Check the AI takeover title is `Explore what AI can do for your business and what you need to get up and running.` as per [brief](https://docs.google.com/document/d/1TOfGfuNOGfAjNQEPyOJ0G6JRznwsb-FUe4xL378CG0Q/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1285
> Change AI takeover subtitle

- requirements.txt
- templates/blog/author.html
- templates/blog/pagination.html
Added paginated list of author's posts
- Run `./run`
- Visit [/blog/author/canonical](http://0.0.0.0:8001/blog/author/canonical)
- See that it looks similar to https://blog.ubuntu.com/author/canonical
> Update author page with paginated list of all author's posts

- templates/engage/de/openstack-security-de.html
- templates/index.html
- templates/takeovers/_german_openstack_security_takeover.html
German language engage page and takeover request for webinar
> OpenStack security webinar de page, takeover updates

- templates/kubernetes/_get_ebook.html
- templates/kubernetes/install.html
- templates/shared/contextual_footers/_cloud_bootstack.html
- templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
- Updated /kubernetes/install page
- Download the branch
- Go to http://0.0.0.0:8001/kubernetes/install
- See that the page matches the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1256
> Update /kubernetes/install page

- templates/pricing/infra.html
- templates/shared/pricing/_ua-advanced-storage.html
- Updated the /pricing/infra page for the new Storage chagnes
- Download this branch
- Look at http://0.0.0.0:8001/pricing/infra
- Compare to the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit)
- *Note, the 'Security maintenance and support' table is updated in #5346*
Fixes #5345
> Update pricing/infra for Storage product updates

- requirements.txt
Fix blog feeds
- `./run`
- /blog/feed
- Make sure it's xml
> Bump blog to version 2.0.9

- templates/pricing/consulting.html
- templates/shared/pricing/_kubernetes-consulting.html
- Updates to match copy doc
- View the site locally in your web browser at: [/pricing/consulting](http://0.0.0.0:8001/pricing/consulting)
- Compare to [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY)
Fixes #5388
> Updates to match copy doc

- templates/kubernetes/managed.html
I have updated the copy doc url for this web page. 
Make sure the copy doc url link is correct. 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5317
> Update copy doc url - managed/kubernetes

- templates/kubernetes/docs/container-runtime.md
- templates/kubernetes/docs/index.md
- templates/kubernetes/docs/release-notes.md
- templates/kubernetes/docs/using-vault.md
fixes the table header - sorry I missed this one in last PR
> fix containerd table in k8s docs

- requirements.txt
Make sure that blog has a 404 page with a template.
127.0.0.1:8000/blog/qdsfdsqf
> Bump blog to 2.0.12

- templates/support/thank-you.html
- Update /support/thank-you page copy
- View the site locally in your web browser at: http://0.0.0.0:8001/support/thank-you
- Compare to the [copy doc](https://docs.google.com/document/d/1Vya-1Uq7bqJ7SFQ36j9-REp1iDT3rFENjYyCzuY02r4/edit#)
Fixes #5413
> Update /support/thank-you page

- .github/pull_request_template.md
removing this 
```
---
name: Default Pull Request
about: Default PR
title: ''
labels: ''
assignees: ''
---
```
> Remove un-needed front-matter

- templates/blog/product-cards.html
Added two more product cards (kubernetes and openstack) to utilise with real-time personalization cards via Marketo. Created corresponding groups in wordpress.
> Update to product cards

- templates/takeovers/_ubuntu-lime-telco_takeover.html
Updated text on the lime takeover
- Please ensure the changes are reflected on the takeover.
Fixes #5439
> Updated text on the lime takeover

- templates/engage/edge-month.html
Updated edge month engage page to match the [copy doc](https://docs.google.com/document/d/1D_CuxaO_II0Jh9jRO9mYgRnO1J99s3DY-Iq78fPpvTc/edit).
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/edge-month
- Ensure that the content matches the copy doc.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1433
> Update edge month engage page to match the copy doc

- templates/engage/casestudy-imsevolve.html
- created a u.c version of https://app-sjg.marketo.com/#LP5768A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-imsevolve
> [Engage] Add IMS Evolve case study page

- templates/engage/casestudy-azlogica.html
- created a u.c version of https://app-sjg.marketo.com/#LP4758A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-azlogica
> [Engage] Add Azlogica case study page

- templates/engage/cloud-fray.html
- created a u.c version of https://app-sjg.marketo.com/#LP5496A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cloud-fray
> Add How to face the challenges of becoming a cloud operator engage page

- templates/engage/whitepaper-containers.html
- created a u.c version of https://app-sjg.marketo.com/#LP5628A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/whitepaper-containers
> [Engage] Add containers whitepaper page

- templates/engage/whats-new-ubuntu-14-04-lts.html
- created a u.c version of https://app-sjg.marketo.com/#LP5750A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/whats-new-ubuntu-14-04-lts
> [Engage] Add Whats new in Ubuntu 14.04 LTS page

- templates/support/index.html
- renamed and uploaded the new pdf to the asset server
- updated the link on the /support page
- updated the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit)
- See that the new datasheet is linked to from the banner
Fixes #5483
> Update the UA datasheet

- templates/engage/essential-guide-big-data-solutions.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/essential-guide-big-data-solutions
Fixes #5500
> [Engage] Update metadata syntax for essential guide for big data page

- templates/shared/contextual_footers/_telco_further_reading.html
- templates/telecommunications/index.html
- Update /telecommunications page
- Compare it to the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#heading=h.cc10rmxh86i7)
Fixes #5491
> Update /telecommunications page

- templates/takeovers/_bt_announcement.html
- update link to blog post
- See that the link on the bt strip works
> Update bt link

- static/sass/_pattern_blog-suru.scss
- static/sass/_pattern_strip.scss
- templates/blog/cloud-and-server.html
- templates/blog/desktop.html
- templates/blog/internet-of-things.html
- templates/internet-of-things/index.html
Added a new suru strip pattern to the code base and used it in the header of the internet-of-things page.
- Go to /internet-of-things
- Check it matches [the design](https://github.com/canonical-web-and-design/web-squad/issues/1459)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1311
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1459
> Build: Overview Default suru strip - /iot

- templates/engage/finserv-multi-cloud.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/finserv-multi-cloud
Fixes #5543
> [Engage] Update metadata syntax for finserv multi cloud page

- templates/engage/451-automotive.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/451-automotive
Fixes #5522
> [Engage] Update metadata syntax for 451 automotive page

- templates/internet-of-things/index.html
Update the IoT hero illustration
- Check the illustration matches the one from [the design](https://github.com/canonical-web-and-design/web-squad/issues/1459)
Fixes #
> Change the IoT illustration

- templates/engage/microsoft-active-directory.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/microsoft-active-directory
Fixes #5539
> [Engage] Update metadata syntax for Microsoft active directory page

- templates/index.html
- Remove BT strip
- Make sure BT strip is removed
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1486
> Remove BT strip

- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/desktop/index.html
Added suru strip to desktop index page.
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1458)
Fixes canonical-web-and-design/web-squad#1458
> Add Suru background strip to desktop index page

- redirects.yaml
- requirements.txt
- webapp/urls.py
Add local rss feed
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/feed
- Test that the feed doesn't have Japanese, Chinese or kf-news items
Fixes #5635
> Add local rss feed

- templates/engage/index.html
- templates/engage/maas-hardware-testing.html
- templates/index.html
- templates/takeovers/_maas-hardware-testing_takeover.html
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) and [/engage/maas-hardware-testing](http://0.0.0.0:8001/engage/maas-hardware-testing)
- Go to the home page and refresh until you see Maas takeover
- Ccompare to the [design](https://github.com/canonical-web-and-design/web-squad/issues/1441)
- Compare to the [brief](https://docs.google.com/document/d/1xyNrWYsYcvux_gYtoWw39XD9cP4QmiAYJnDlLuV8CvE)
- Make sure it has a card on [/engage](http://0.0.0.0:8001/engage)
- Test it on …
> 5008 Maas automated hardware testing

- releases.yaml
- Make sure both pretty displays and URLs all reference .3 now instead of .2
Fixes #5642
> Update version and checksums for 18.04.3

- templates/internet-of-things/gateways.html
- Rebuild /internet-of-things/gateways page
- View the site locally in your web browser at: [/internet-of-things/gateways](http://0.0.0.0:8001/internet-of-things/gateways)
- Compare to [copy doc](https://docs.google.com/document/d/18ffTcNolrtJS9AvjMfa8KW94uLfC0KzmHtTe-jMYmlo)
Fixes #5655
> Rebuild /iot/gateways page

- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/release-notes.md
Updates release notes and bundle links for latest k8s release
> New K8s release

- templates/search.html
Fixes #5711
QA
--
Grab the search cred from [the dashboard](https://console.cloud.google.com/apis/credentials?project=ubuntu-search-1530889417216) (ping me if you don't have access)
`./run --env SEARCH_API_KEY={key}`
Go to `http://localhost:8001/search`, check you don't see an error.
Fixes #5711
> Fix search error

- webapp/app.py
Fix the download view
- Go and download something and it should work
- Check /download/blah/thank-you 404s
Fixes https://github.com/canonical-web-and-design/base-squad/issues/683
> Fix download view

- .circleci/config.yml
- navigation.yaml
- redirects.yaml
- static/files/sitemap.xml
- templates/templates/_navigation-developer-h.html
- templates/templates/_navigation-enterprise-h.html
- templates/templates/footer.html
- webapp/app.py
Remove resources section from the site
- /resources and see it redirects to blog
Fixes https://github.com/canonical-web-and-design/base-squad/issues/684
>   Remove resources

- templates/advantage.html
- webapp/app.py
QA
--
Go to {demo}/advantage. Login. See you get account info returned on the page!
> Authenticate with API and get accounts

- static/sass/_pattern_takeovers.scss
- static/sass/styles.scss
- templates/takeovers/_template.html
- templates/takeovers/templates.html
- created a template and scss for the new takeover templates
- View the site locally in your web browser at: http://0.0.0.0:8001/takeovers/templates
- Compare to the design [here](https://github.com/canonical-web-and-design/web-squad/issues/1556)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1610
large
small
> New grad template for takeovers

- templates/engage/shared/_header-case-study.html
- templates/engage/shared/_header.html
- templates/takeovers/shared/_takeover.html
- templates/templates/base.html
- Updated logic for testing for http in the change to jinja2
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/apparmor-intro
- See that there is a header image
> Fix logic for http tests

- webapp/context.py
Currently, a problem with the insights feed will bring down the homepage. Not good. This fixes it.
QA
--
It's a bit tricky to test, but we can do it like this:
```
echo "127.0.0.1 admin.insights.ubuntu.com" | sudo tee -a /etc/hosts
python3 -m venv env3
source env3/bin/activate
pip3 install -r requirements.txt
./entrypoint 0.0.0.0:8001
```
Now go to http://0.0.0.0:8001 and see that the homepage works, even though all the blog posts are missing.
Now do:
```
sudo sed -i '/admin.insights.ubuntu.com/d' /etc/hosts
```
> Make feed more resilient

- templates/financial-services/index.html
Updated /financial-services to match [copy doc](https://docs.google.com/document/d/1o9s_MFaiZZIS26tusRi0ALNrcqUihhTSZgxS55oHZj4)
- Visit /financial-services
- Ensure that it matches the copy doc, the design looks good, and the links are correct
Fixes #5749
> /financial-services copy update

- templates/advantage/index.html
- webapp/views.py
Added the token from the account to the show instructions section.
- Open the "show instructions" accordion 
- Check that is displays a token
Fixes https://github.com/canonical-web-and-design/base-squad/issues/672
> Display free UA token

- .env
- entrypoint
> Properly enable FLASK_DEBUG in development; use only one worker in development

- static/sass/styles.scss
- templates/advantage/_table.html
- templates/advantage/index.html
- webapp/views.py
Make the services enabling guidelines dynamic based on the personal accounts affordences.
- Login
- See your token 
- See that it lists the services you have available
- Click on them to see the commands to enable and disable them
Fixes https://github.com/canonical-web-and-design/base-squad/issues/708
> Dynamic instructions

- static/sass/styles.scss
- templates/advantage/_table.html
- templates/advantage/index.html
Apply the designs for the signed out and signed in pages.
_This does not cover the enterprise subscriptions section yet_
- Check it matched [the design]( https://github.com/canonical-web-and-design/web-squad/issues/1555)
Fixes https://github.com/canonical-web-and-design/base-squad/issues/677
> Apply design to the personal section of the UA dashboard

- templates/livepatch/index.html
Updated the livepatch page to match the copy doc.
- Check the copy matches the [copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit#)
Fixes https://github.com/canonical-web-and-design/base-squad/issues/712
> Update the livepatch page

- templates/kubernetes/docs/operations.md
Added clarification for kubectl configuration
> Doc fix: clarification for kubectl configuration

- static/sass/styles.scss
- templates/advantage/index.html
- templates/livepatch/index.html
Updated the advantage and livepatch pages to match the design feedback.
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage and http://0.0.0.0:8001/livepatch
- Check that design is happy
> Advantage design changes

- templates/advantage/index.html
> Changes “esm” to “esm-infra” in instructions

- templates/advantage/index.html
Add google analytic events to the interactions
- If you have the GA browser plugin you can see the events triggering otherwise just check there are no console errors and trust me.
> Add google analytic events to the interactions

- HACKING.md
- README.md
- Updated the readme and the hacking pages for github users
- look at the files, perhaps hit the ... and try and look at a preview.
- the key thing is the text... does it make sense, it is something helpful and usefule.
> Update the readme and hacking pages

- templates/desktop/features.html
Copy update on /desktop/features in the 'An open source operating system' block
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/features
- Compare to the [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit#heading=h.28j9rzo0ew1w)
Fixes #5776
> Copy update on /desktop/features

- templates/desktop/partners.html
- Update hero on `/desktop/partners`
- View the site locally in your web browser at: [/desktop/partners](http://0.0.0.0:8001/desktop/partners)
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1580)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1581
> Update /desktop/partners hero

- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/desktop/organisations.html
- Update hero on `/desktop/organisations`
- View the site locally in your web browser at: [/desktop/organisations](http://0.0.0.0:8001/desktop/organisations)
- compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1576)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1577
> Update /desktop/organisations hero

- templates/engage/vmware-to-charmed-openstack.md
- Edit vmware engage page
- compare to [copy doc](https://docs.google.com/document/d/13aUs6sT_Z4kTv1-KiISD22yqh_1VOw9xLLqEMftJZyU/edit# )
> Edit vmware engage

- templates/desktop/developers.html
- Update hero on `/desktop/developers`
- View the site locally in your web browser at: [/desktop/developers](http://0.0.0.0:8001/desktop/developers)
- compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1578)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1579
> Update desktop/developers hero

- static/sass/_pattern_strip.scss
- templates/desktop/features.html
- updated hero with suru
-resized image from hero (laptop)
- Check if matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1574)
Fixes #1575
> desktop/features - applied suru headings

- static/sass/_pattern_strip.scss
- templates/desktop/statistics.html
- Update hero on `/desktop/statistics`
- View the site locally in your web browser at: [/desktop/statistics](http://0.0.0.0:8001/desktop/statistics)
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1582)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1583
> Update /desktop/statistics hero

- templates/advantage/index.html
Applied some design and UX tweaks to the layout of the advantage page.
- Check the logged out page looks ok
- Login and check that page also looks ok with more content visible above the fold.
> Advantage design tweaks

- static/sass/styles.scss
- templates/shared/contextual_footers/_cloud_nfv.html
- templates/telecommunications/index.html
- A very large update to /telecommunications
- Compare to the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#heading=h.t5nt9uvsqry)
- Provide design guidence - images, layout, double quotes, etc...
Fixes #5756
> Update text of /telecommunications page

- templates/templates/base.html
Reorder the head for performance
- Check the head matches:
```
<meta charset />
<meta name="viewport" />
<title>
preconnect/dns-prefetch
<script>// Inline JS</script>
<link rel="stylesheet" />
<style>/* Inline CSS */</style>
preload
<script src=""></script>
prefetch/prerender
```
> Reorder the head for performance

- templates/templates/base.html
> Remove preconnects from HTML

- templates/kubernetes/docs/logging.md
- templates/kubernetes/docs/monitoring.md
Updated the monitoring and logging pages due to new graylog charm
> k8sdocs- Update graylog

- templates/pricing/index.html
- Update /pricing layout to `col-6`
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing
- See that it is 6 col, not 4
> Update /pricing layout

- static/js/latest-news.js
- static/sass/_pattern_strip.scss
- static/sass/styles.scss
- templates/advantage/_table.html
- templates/advantage/index.html
- templates/shared/contextual_footers/_ua_further_reading.html
- templates/shared/contextual_footers/_ua_got_questions.html
- templates/shared/contextual_footers/_ua_legal.html
- webapp/views.py
Addressed some of the feedback on the advantage page.
- See the page looks ok
- Login and check that works
- Check the page looks ok
> Address advantage feedback

- templates/download/shared/_get_ebook_maas.html
- templates/engage/ubuntu-lime-telco.html
- templates/openstack/managed.html
- templates/security/index.html
- templates/support/index.html
- templates/takeovers/_ubuntu-lime-telco_takeover.html
- templates/telecommunications/index.html
Replace svgs with base64
- best buy logo
- http://0.0.0.0:8001/security
- http://0.0.0.0:8001/support
-maas ebook
- http://0.0.0.0:8001/download/server/thank-you
- http://0.0.0.0:8001/download/server/provisioning
- uct
- http://0.0.0.0:8001/openstack/managed
- lime telco
- http://0.0.0.0:8001/telecommunications
- http://0.0.0.0:8001/engage/ubuntu-lime-telco
Fixes #5892
> Replace svgs with base64

- templates/advantage/index.html
Add checks for entitlements
- Login and check its all ok
> Add checks for entitlements

- templates/advantage/index.html
Add checks for entitlements MORE
- I'll check with the reporter.
> Add checks for entitlements MORE

- templates/support/index.html
- Update datasheet on /support
- See that the datashet is downloadable and from October
Fixes #5920
> Update datasheet on /support

- templates/engage/domotz-case-study.md
- templates/engage/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/domotz-case-study and http://0.0.0.0:8001/engage
- Compare to the [copy doc](https://docs.google.com/spreadsheets/d/1miXa60Om0J6zDWZ1sbFYUU9mpAwzAxABtO0J1USfDZc/edit#gid=1271849439) - note, I tweaked the heading text a bit to fit better
Fixes #1662
> Create Domotz case study page

- templates/desktop/developers.html
- Update "What's new in 19.10" section  for /desktop/developers
- Text update from @matthewpaulthomas in the 'With Ubuntu, you’re in good company' section
- *note, it will say 19.04 until the variables are merged*
- Compare to the [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#)
Fixes #5854
> Update "What's new in 19.10" section  for /desktop/developers

- static/sass/styles.scss
- templates/advantage/_table.html
- templates/advantage/index.html
- templates/kubernetes/index.html
- templates/openstack/managed.html
- templates/shared/pricing/_ua-for-infrastructure.html
- templates/templates/_navigation-enterprise-h.html
Address points from the QA
- Login
- Check you see a free token and all looks good
WIth subscriptions
With subscriptions and table open
> Address points from the QA

- templates/download/index.html
Update the mascot on /download page
- Compare to the [design](https://user-images.githubusercontent.com/36884067/66812729-5af2bb00-ef2b-11e9-99a5-af80b0610b7c.png) 
https://github.com/canonical-web-and-design/web-squad/issues/1824
> Update the mascot on /download page

- templates/pricing/devices.html
Update /pricing/device table as it no longer reflected the master sheet
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices
- Compare to the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.rwbaxe2u0uk2)
> Update /pricing/device table

- templates/legal/contributors/faq.html
- templates/legal/data-privacy/2013-03-25/index.html
- templates/legal/data-privacy/2016-02-08/index.html
- templates/legal/developer-terms-and-conditions/2016-04-06.html
- templates/legal/developer-terms-and-conditions/2018-07-23.html
- templates/legal/developer-terms-and-conditions/index.html
- templates/legal/font-licence/differences.html
- templates/legal/font-licence/faq.html
- templates/legal/font-licence/index.html
- templates/legal/intellectual-property-policy/2013-05-14.html
- templates/legal/intellectual-property-policy/index.html
- templates/legal/ua-miracle-tc-ja.html
- templates/legal/ua-miracle-tc.html
- Corrected sidebar col/card markup on certain legal pages to prevent them containing excessive whitespace, in line with [existing examples](https://ubuntu.com/legal/terms).
- Visit the following pages and see that cards in the sidebar are reasonably sized (as opposed to https://ubuntu.com/legal/font-licence/faq):
Fixes #5948
> fix broken col/card layout on /legal pages

- templates/download/server/thank-you-s390x.html
- templates/kubernetes/index.html
Update look of resource row on thank-you-s390x
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you-s390x
> Update look of resource row on thank-you-s390x

- templates/download/server/thank-you-s390x.html
- templates/kubernetes/index.html
Fix resources row again
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you-s390x
- See that the page looks more modern
> Fix resource rows

- templates/internet-of-things/robotics.html
- added contact us to banner
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/robotics
- Compare to the [copy doc](https://docs.google.com/document/d/1cDxhPCQbHA0r6n9JXNmO50ANLPZhCFdgwATX6f90guU/edit#
)
Fixes #5986
> Add contact-us cta to /internet-of-things/robotics

- navigation.yaml
- templates/kubernetes/docs/multiple-networks.md
- templates/kubernetes/docs/shared/_side-navigation.md
- templates/kubernetes/docs/upgrade-notes.md
Adds a new page for multiple networks
Adds update about upgrading etcd
> K8sDocs - Add multiple networks and minor updates

- templates/advantage/index.html
- webapp/views.py
- Update commands on /advantage
- Make sure the command list has been updated as mentioned in [the issue](https://github.com/canonical-web-and-design/web-squad/issues/1850)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1850
- Error when personal_account data cannot be retrieved - **You will not be able to see this state**
> Update ua messages good

- templates/advantage/base_advantage.html
- Fix missing js file error
- Check if the demo works
> Fix missing js file error

- Dockerfile
The exiting image was giving us some trouble with SSO
so we rolled back to a simpler version until we can find
the root cause of the issue
> Revert dockerfile to simpler version

- templates/kubernetes/install.html
- Update `/kubernete/install` page
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1708)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1759
> Update kubernetes/install page

- templates/kubernetes/features.html
- Update `/kubernete/features` page
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1706)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1757
> Update kubernetes/features page

- templates/kubernetes/partners.html
- Update `/kubernetes/partners` page
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/partners
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1709)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1760
> Update kubernetes/partners page

- templates/kubernetes/managed.html
- update `/kubernetes/managed`
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1707) and [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1758
> Update /kubernetes/managed page

- templates/pricing/devices.html
- Update `/pricing/devices` page
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices
- Compare to [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
Fixes #6034
> Add more get in touch buttons

- templates/kubernetes/docs/validation.md
> Fix broken link on K8s validation page

- templates/engage/index.html
- templates/engage/wellcome-sanger-case-study.md
- Add `/engage/wellcome-sanger-case-study` page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/wellcome-sanger-case-study
- Compare to [brief](https://docs.google.com/spreadsheets/d/1I6mV4Zj9JIeE38bAOKDthJnsBg336wFQF7NonNldG9E/edit#gid=0), [design](https://github.com/canonical-web-and-design/web-squad/issues/1873) and [copy doc](https://docs.google.com/document/d/1Q3qm-OpMojw1f2hoK7fOW2MZGacC2BJz8d5DsuRjHyA/edit)
Fixes #6005
> Add welcome sanger engage page

- templates/internet-of-things/index.html
- templates/shared/pricing/_smart-start-prices.html
- Update `/iot` page
- View the site locally in your web browser at: http://0.0.0.0:8001/iot
- Compare to [copy](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.c3ugpbbmbux2)
Fixes #6035
> Update /iot page

- templates/kubernetes/docs/cni-canal.md
- templates/kubernetes/docs/cni-flannel.md
- fixed some typos
- updated a link
> [Docs] - minor updates to K8s pages

- static/sass/_pattern_strip.scss
- templates/_docs/strips.html
- templates/blog/featured-articles.html
- Added a new suru type for use on the featured posts section of the blog index
- See that the featured section suru matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1877#issuecomment-550279581).
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1877
> add new suru type for featured blog posts section

- templates/openstack/index.html
Update /engage/vmware-to-openstack to /engage/vmware-to-charmed-openstack
- See that the three links have been updated
Fixes #6082
> Update webinar link

- .circleci/config.yml
- Change python tests CircleCI endpoint to match the package.json endpoint
- Include `test-site` check using the `entrypoint` script
- Make sure in this PR that CircleCI has a check called "test-python"
- Make sure in this PR that CircleCI has a check called "test-site" and it pass
> Tests changes

- Dockerfile
- requirements.txt
- webapp/views.py
Reverts canonical-web-and-design/ubuntu.com#6096. Merged by accident.
> Revert "Implement GeoIP directly on the /download/*/thank-you pages"

- templates/dell/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/dell
- See that the dell laptop image has been replaced as [requested](https://github.com/canonical-web-and-design/ubuntu.com/issues/6128)
Fixes #6128
> Update dell laptop image on /dell

- templates/telecommunications/index.html
- Update OSM section on `/telecommunications` page
- Compare to [copy](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#) and accept/resolve changes if they were done
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6138
> Update OSM section on /telecommunications page

- webapp/views.py
Fix the attached machine count in the advantage dashboard
- Check the code as its difficult to QA
> Fix the attached machine count

- templates/kubernetes/docs/docker-registry.md
- templates/kubernetes/docs/operations.md
- changed instructions for using registries
> [Docs] updates to k8s registry docs

- templates/pricing/index.html
- Update `/pricing` page
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing
- compare to [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/5903)
Fixes #5903
> Update /pricing page

- templates/blog/topics/snapcraft.html
- Update hero section on `/blog/topics/snapcraft`
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/topics/snapcraft
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1893)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1894
> Update /blog/topics/snapcraft hero section

- static/sass/_pattern_strip.scss
- templates/esm/index.html
- Update `/esm` page with light ITstrategen strip
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1938)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1939
> Update /esm ITstrategen strip

- templates/blog/topics/design.html
- Update hero section on `/blog/topics/design`
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/topics/design
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1887)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1888
> Update /blog/topics/design hero section

- templates/internet-of-things/contact-us.html
- templates/internet-of-things/thank-you.html
- templates/shared/_thank_you.html
1. Add automotive to contact-us and thank-you
2. Updated copy docs
- http://0.0.0.0:8001/internet-of-things/contact-us?product=automotive https://docs.google.com/document/d/1-WTp-Zf29CA5fiMV0A1rCyaNPF6xAYzZu6BThUXUSlk/edit#heading=h.496weqrnqii0 [copy doc](https://docs.google.com/document/d/1Se-fD5hhb7EaR75jd_1D-JkADmg6aLjUs7_bScATvwE/edit#)
- http://0.0.0.0:8001/internet-of-things/thank-you?product=automotive [copy doc](https://docs.google.com/document/d/1-WTp-Zf29CA5fiMV0A1rCyaNPF6xAYzZu6BThUXUSlk/edit#heading=h.496weqrnqii0
)
- See that it looks …
> Add automotive to contact-us and thank-you

- templates/templates/_navigation-enterprise-h.html
Update enterprise dropdown with an array of updates
- Compare to the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit#
)
> Update enterprise dropdown

- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/release-notes.md
Update k8s docs for ck2 release
> [Docs] Update links and notes for K8s ck2 release

- templates/blog/topics/maas.html
- Update hero section on `/blog/topics/maas`
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/topics/maas
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1891)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1892
> update /blog/topics/maas hero section

- templates/blog/topics/juju.html
- Update hero section on `/blog/topics/juju`
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/topics/juju
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1889)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1890
> Update /blog/topics/juju hero section

- templates/blog/desktop.html
- Update `/blog/desktop` hero
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/desktop
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1881)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1882
> Update /blog/desktop hero

- static/sass/_pattern_strip.scss
- templates/_docs/strips.html
- templates/blog/cloud-and-server.html
- templates/blog/desktop.html
- templates/blog/internet-of-things.html
- templates/blog/press-centre.html
- templates/blog/topics/design.html
- templates/blog/topics/juju.html
- templates/blog/topics/maas.html
- templates/blog/topics/robotics.html
- templates/blog/topics/snapcraft.html
- Add new design to /blog pages
- View the site locally in your web browser at: http://0.0.0.0:8001//blog
- Make sure all blog pages hero look new
> Blog header updates

- templates/engage/build-smart-devices-with-mir-whitepaper.md
- templates/engage/index.html
- Add 'build-smart-devices-with-mir-whitepaper` engage page
- Add whitepaper card to `/engage`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/build-smart-devices-with-mir-whitepaper
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1181)
- Compare to [copy](https://docs.google.com/document/d/11E9O_mVN_U63ZLsZOvwsdXAyNtpRv0aF8_VWBDfrnRc/edit#)
P.S. PDF is not ready yet
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1182
> Add mir engage page

- templates/aws/pro.html
Updated the datasheet to the latest version https://assets.ubuntu.com/v1/feafb61c-Ubuntu_Pro_AWS_04.11.19.pdf
Updated the datasheet to https://assets.ubuntu.com/v1/feafb61c-Ubuntu_Pro_AWS_04.11.19.pdf
-  Check https://ubuntu.com/aws/pro against the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit)
- Resolve changed comments
Fixes #6223
> Update the datasheet

- static/sass/_utility_vertically-center.scss
- static/sass/styles.scss
- templates/masters-conference/_base-masters-conference.html
- templates/masters-conference/brendan-gregg.html
- Added /masters-conference/brendan-gregg page
- View the site locally in your web browser at: http://0.0.0.0:8001/masters-conference/brendan-gregg
- See that the page matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/2016#issuecomment-561615816) and the [copy doc](https://docs.google.com/document/d/1BXbsNMORvI7aW3qBgix7-VN7kbc6WizxiraacNFC7_w/edit#)(page 3 onwards)
Fixes #6177
> Masters main

- navigation.yaml
- templates/legal/data-privacy/index.html
- templates/legal/data-privacy/survey.md
Built survey data privacy page
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy/survey
- Check that the page matches the [copy doc](https://docs.google.com/document/d/164IVIF3f8Prh7MTl8gTDal0jaPJt15PxdhMKToFhMu8)
Fixes #2153
> Build survey data privacy page

- templates/engage/index.html
- templates/engage/sbi-casestudy.md
Build SBI case study engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/sbi-casestudy
- Check that it matches the [copy doc](https://docs.google.com/document/d/1ky7FmqiSEBi_fDMo3d2p7oeIrFhvSCCCJmohd6rc6uQ)
Fixes #6175
> Build SBI case study page

- templates/download/kvm.html
- Made a very small update to match the [copy doc](https://docs.google.com/document/d/1FHIArLpuAyLe2gnDwymefvzc4Lg8dSGvN8QAl8wX18Q/edit#heading=h.y5kr0riv2frn)
- View the site locally in your web browser at: http://0.0.0.0:8001/download/kvm
- See that that the page matches the [copy doc](https://docs.google.com/document/d/1FHIArLpuAyLe2gnDwymefvzc4Lg8dSGvN8QAl8wX18Q/edit#heading=h.y5kr0riv2frn)
Fixes #6246
> update /download/kvm copy

- templates/about/index.html
- made small copy tweak, per [copy doc](https://docs.google.com/document/d/1NvYOhOJzdY5ypifTPs73vH5Nb7rFABRWMzjXyDUQt_U/edit#heading=h.e22tbypocit5)
- View the site locally in your web browser at: http://0.0.0.0:8001/about
- See that the page matches the [copy doc](https://docs.google.com/document/d/1NvYOhOJzdY5ypifTPs73vH5Nb7rFABRWMzjXyDUQt_U/edit#heading=h.e22tbypocit5)
Fixes #6247
> update /about copy

- templates/internet-of-things/robotics.html
- updated title and image, in line with [copy doc](https://docs.google.com/document/d/1cDxhPCQbHA0r6n9JXNmO50ANLPZhCFdgwATX6f90guU/edit#heading=h.bkqx69rf2p)
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/robotics
- See that the page matches the [copy doc](https://docs.google.com/document/d/1cDxhPCQbHA0r6n9JXNmO50ANLPZhCFdgwATX6f90guU/edit#heading=h.bkqx69rf2p)
Fixes #6249
> update /internet-of-things/robotics copy

- templates/masters-conference/index.html
Updated the YoutTube video under Extended BPF: A new way to understand software.
Update the youtube video in the  Extended BPF: A new way to understand software section to https://www.youtube.com/watch?v=rwtt5-_8eeI
- Check it against the [copy doc](https://docs.google.com/document/d/1BXbsNMORvI7aW3qBgix7-VN7kbc6WizxiraacNFC7_w/edit#)
Fixes #2170
> Updated the YoutTube video

- templates/download/flavours.html
Update the Lubuntu logo
- View the site locally in your web browser at: http://0.0.0.0:8001/download/flavour
- Check that the Lubuntu logo looks good
> Update the Lubuntu logo

- templates/index.html
Removed 2 takeovers below:
{% include "takeovers/_private-cloud-build-takeover.html" %}
{% include "takeovers/_1910_takeover.html" %}
> Changed the takeovers in rotation

- templates/download/flavours.html
Update the links to secure links for other flavours of Ubuntu
- Check the links work
> Point to secure sites for other flavours

- templates/engage/index.html
- converted engage index entry elements to `article`s
- See that the page layout isn't broken
Fixes #6295
> convert engage entries to articles

- navigation.yaml
- templates/kubernetes/docs/cis-compliance.md
- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/ldap.md
- templates/kubernetes/docs/logging.md
- templates/kubernetes/docs/monitoring.md
- templates/kubernetes/docs/release-notes.md
- templates/kubernetes/docs/shared/_side-navigation.md
- templates/kubernetes/docs/snap-coherence.md
- templates/kubernetes/docs/storage.md
- various edits
-new CIS compliance page
- new snap coherence page
> Docs updates for k8s 1.17 release:

- templates/kubernetes/docs/index.md
Simple increment on the K8s version in docs
> Update version in Kubernetes docs

- static/js/formValidation.js
- templates/download/desktop/thank-you.html
- templates/download/server/thank-you.html
- templates/download/shared/_server_weekly_news.html
- templates/download/shared/_verify-checksums.html
Add the server weekly mailing list to the server thank you page
- Make sure the copy matches [the copydoc](https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit)
- Check the design matches [the design](https://user-images.githubusercontent.com/36884067/69065492-c5f64c80-0a17-11ea-84c7-ca3a6c573173.jpg)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1748
> Update server download

- static/js/formValidation.js
- templates/whitepapers/beta/shared/form.html
- templates/whitepapers/shared/form.html
Now that formValidation is built into the main package with is loaded on all pages. I have renamed the functions to not clash with the global functions.
- Go to `/whitepapers/robotics` and fill in the form and see it works
- Go to `/whitepapers/beta/robotics` and fill in the form and see it works
> Fix the whitepaper form

- static/sass/_pattern_navigation.scss
- templates/legal/contributors/agreement.html
- Added github username to contributor agreement form per request from legal
- Updated the [copy doc](https://docs.google.com/document/d/1MfgTzlAxiFE6VUW1qAPmrks2ui1zzsX5T7d-DZJlOAw/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/contributors/agreement
- See that the form submits and there are no errors
> Added github username to contributor agreement form

- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/release-notes.md
Updated links and notes for new bugfix release
> k8s bugfix release docs update

- templates/advantage/index.html
Add logged in event to the advantage page
- Check the code looks good.
> Add logged in event to the advantage page

- static/js/latest-news.js
Update the latest-new.js to the same version used on maas.io
- Go to the following pages and check that the "Further reading" section loads blog posts
- https://ubuntu-com-canonical-web-and-design-pr-6433.run.demo.haus
- https://ubuntu-com-canonical-web-and-design-pr-6433.run.demo.haus/about
- https://ubuntu-com-canonical-web-and-design-pr-6433.run.demo.haus/advantage
- https://ubuntu-com-canonical-web-and-design-pr-6433.run.demo.haus/community
- https://ubuntu-com-canonical-web-and-design-pr-6433.run.demo.haus/contact-us
- …
> Update latest news code

- templates/download/raspberry-pi.html
> Fix sddm for lubuntu installation

- static/sass/_pattern_ubuntu_intro.scss
- templates/base_index.html
Update the homepage with the new illustrations
- Check that the illustrations in the 'Ubuntu is an open source software operating system that runs from the desktop, to the cloud, to all your internet connected things' section are the same as [the copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit)
- Check that the illustrations have a hover state
Fixes #6446
> Update homepage illustrations

- releases.yaml
- static/js/chart.js
- static/js/chartData.js
- templates/about/release-cycle.html
Update /about/release-cycle page
- Compare to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) and [data doc](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=550510389) - look at both the charts and the table on small screens.
Fixes [#2224](https://github.com/canonical-web-and-design/web-squad/issues/2224)
> Update /about/release-cycle page

- requirements.txt
Bump version of discourse docs to latest version
Fixes #6471
> Bump version of discourse docs to latest version

- templates/openstack/install.html
- templates/shared/contextual_footers/_cloud_bootstack.html
- templates/shared/contextual_footers/_download_cloud_buy_landscape.html
- templates/shared/contextual_footers/_openstack_documentation.html
Update /openstack/install page
- Compare to [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc)
Fixes #6320
> Update /openstack/install page

- static/sass/_pattern_ubuntu_intro.scss
- templates/kubeflow/index.html
- templates/kubeflow/shared/_learn-more.html
Updated the illustrations on /kubeflow
- Check that the illustrations on the page match the [copy doc](https://docs.google.com/document/d/1mJq8PxH8FVRVF9i1Xzh0f6M73eyjqZE4NaKYHRcRAKM/edit#)
Fixes #6465
> Update illustrations on kubeflow page

- templates/kubernetes/index.html
- templates/shared/_training.html
Updated the illustrations on /kubernetes
- Check that the illustrations match the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#)
Fixes #6447
> Update kubernetes illustrations

- static/sass/_pattern_ubuntu_intro.scss
- templates/base_index.html
- templates/kubeflow/index.html
Update icons on the homepage and /kubeflow
- Check that the icons under "Ubuntu is an open source software operating system that runs from the desktop, to the cloud, to all your internet connected things" look OK
- Go to /kubeflow
- Check that the icons under "Develop your AI Models on Ubuntu" look OK
Fixes #6505
> Update illustrations on homepage and kubeflow page

- templates/automotive/index.html
Updated the title from "Commerical" to "Secure"
- Review [the copy doc ](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#heading=h.c6wjbvvp8mcm)and accept the change if correct
Fixes #6515
> Copy update on /automotive

- templates/pricing/infra.html
- Update suru banner and contact us illustrations on /pricing/infra
- Compare and resolve comments in the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#heading=h.l83dv5879ajz)
Fixes #6529
> Update illustrations on /pricing/infra

- templates/esm/index.html
Updated illustrations on /esm per comments in [copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#heading=h.b4oh6xkbn2jq)
- See that the images on the page match those referenced in the copy doc
- Accept the relevant comments when happy
Fixes #6523
> update illustrations on /esm

- templates/support/community-support.html
- Update illustations and text of /support/community-support/ page
- View the site locally in your web browser at: http://0.0.0.0:8001/support/community-support
- Compare and resolve comments in the [copy doc](https://docs.google.com/document/d/1vrnljXUx71ZZhz3cQ6NupUNw6yNqW2OWkyY8Ozx2bqw/edit#)
Fixes #6524
> Update illustations and text of /support/community-support/ page

- templates/aws/pro.html
Changed the word "nano" to "large".
- Review the relevant section on the [copy doc}(https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#) and accept the correct changes. 
Fixes #6575
> Copy change on /aws/pro

- static/sass/_pattern_navigation.scss
Fix misaligned search button
- Focus in the search bar and type something
- Check that the clear search button is right aligned next to the submit button
Fixes #6472
> Fix misaligned search clear button

- templates/openstack/what-is-openstack.html
Update illustrations of /openstack/what-is-openstack
- Check that the illustrations have bee updated as per [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6591)
Fixes #6591
> Update what is openstack page

- templates/openstack/consulting.html
Update illustrations on /openstack/consulting
- Check that the changes referenced in [this comment](https://github.com/canonical-web-and-design/ubuntu.com/issues/6500#issuecomment-583321968) have been done
Fixes #6500
> Update illustrations on openstack consulting page

- templates/download/cloud/index.html
Update hero on /download/cloud
- View the site locally in your web browser at: http://0.0.0.0:8001/download/cloud
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6611) were made
Fixes #6611
> Update /download/cloud hero

- templates/download/raspberry-pi/index.html
Updated Raspberry Pi logo
Fixes #6619
> Update Raspberry Pi logo on download/raspberry-pi

- templates/download/iot/index.html
Update /download/iot
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6613) have been made
Fixes #6613
> Update /download/iot page

- templates/shared/pricing/_openstack-kubernetes-lma.html
- Updated text on /pricing/infra
- Compare to the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
Fixes #6616
> Updated text on /pricing/infra

- templates/download/server/power.html
Add suru to /download/server/power hero
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/power
- Check that the hero has suru
Fixes #6624
> Update download server power page

- templates/kubernetes/docs/aws-integration.md
- templates/kubernetes/docs/gcp-integration.md
- templates/kubernetes/docs/hacluster.md
- templates/kubernetes/docs/ldap.md
- templates/kubernetes/docs/openstack-integration.md
> k8s docs updates

- templates/download/server/arm.html
Update illustrations on /download/server/arm
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/arm
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6617) have been made
Fixes #6617
> Update download arm illustrations

- templates/download/server/index.html
- templates/download/shared/_multipass-install.html
Add suru, logos and adjust spacing on /download/server
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6615) have been made
Fixes #6615
> Update download server page

- templates/internet-of-things/gateways.html
Updated /gateways illustratons according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6680#issue-566419231)
- View the site locally in your web browser at: http://0.0.0.0:8001/gateways
- See that the items in the [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6680#issue-566419231) have been properly addressed
Fixes #6680
> update /gateways illustrations

- templates/internet-of-things/digital-signage.html
- templates/internet-of-things/index.html
- templates/shared/contextual_footers/_devices_newsletter_signup.html
Updated illustrations according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6666)
- Check that the updates mentioned in the [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6666) have been addressed
Fixes #6666
> update /iot/digital-signage illustrations

- .github/workflows/cypress.yml
- yarn.lock
Run a job on PR for now just to test. 
This should run the cypress test suite. 
- github action should not fail
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2360
> Run github action cypress everyday at 7am

- static/sass/styles.scss
Add utility for making an element inline
Check that a class of `.u-inline` has been added
> Add inline utility class

- templates/core/build.html
- webapp/app.py
- webapp/views.py
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2372
QA
--
Go to `/core/build`, see the beautiful message asking you to login.
Try logging in, see you end up back at build, and the message is miraculously gone!
Check `/core/build` and `/advantage` return `cache-control: private`.
> Handle login context in /code/build

- templates/core/build.html
Update the copy from the [copy doc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#)
- Check that the copy mostly matches the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2367
> Image builder copy update

- templates/advantage/index.html
- webapp/views.py
Conditionally display end date on contract
- You can't QA probably
- Check code is swiss
> Conditionally display end date on contract

- templates/esm/index.html
> Add image template to esm

- templates/kernel/index.html
> Add image template to kernel page

- templates/openstack/index.html
Add image tempalte to /openstack
- Make sure the images load
> Add image template to openstack

- templates/download/iot/index.html
- templates/download/iot/installation-media.html
Download/iot section
- http://0.0.0.0:8001/download/iot
- http://0.0.0.0:8001/download/iot/installation-media
> Add image template tag to /download/iot section

- .circleci/config.yml
Fix linkchecker that is failing because of images with height defined
- Make linkchecker work again
> Ignore h_* url in linkchecker

- templates/download/iot/index.html
Fix 500
- `./run`
- http://0.0.0.0:8001/download/iot#core
should work
> Fix jinja2 typo

- templates/engage/linux-enterprise-whitepaper.md
- Add image height and width to linux enterprice engage page
- http://localhost:8001/engage/linux-enterprise-whitepaper
> Add image height and width to linux enterprice engage page

- templates/engage/kata-containers-webinar.md
- Added the image width and height values
- http://localhost:8001/engage/kata-containers-webinar
> Add image sizes to kata containers engage page

- templates/engage/sbi-casestudy.md
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/sbi-casestudy
> Add image sizes to /engage/sbi-casestudy

- templates/engage/microsoft-active-directory.html
- Image tag added
- http://localhost:8001/engage/microsoft-active-directory
> Add image template tag to MS active directory page

- templates/engage/interana-casestudy.md
- Add image size attibutes to interana
- http://localhost:8001/engage/interana-casestudy
> Add image size attibutes to interana

- templates/engage/casestudy-azeti.html
- templates/engage/casestudy-azlogica.html
- templates/engage/casestudy-botsandus.html
- templates/engage/casestudy-cinergy.html
- /engage/casestudy-azeti
- /engage/casestudy-azlogica
- /engage/casestudy-botsandus
- /engage/casestudy-cinergy
Check the images are still there
> [Image module] /engage pt3

- templates/shared/_case-study-allan-gray.html
- templates/shared/_case-study-itstrategen.html
- Added the image tag to some included templates
- http://0.0.0.0:8001/support - ITstrategen and Allan Grey sections
> Add image template tag to some shared templates

- templates/engage/451-cloud-economics.html
- templates/engage/ai-edge-webinar.md
- templates/engage/ai-gettingstarted.html
- templates/engage/ai-ml-ubuntu.html
- /engage/451-cloud-economics
- /engage/ai-edge-webinar
- /engage/ai-gettingstarted
- /engage/ai-ml-ubuntu
You definitely know the deal by now
> [Image module] /engage pt2

- templates/engage/casestudy-city-network.html
- templates/engage/casestudy-commercetools.html
- templates/engage/casestudy-imsevolve.html
- templates/engage/casestudy-innovapos.html
- /engage/casestudy-city-network
- /engage/casestudy-commercetools
- /engage/casestudy-imsevolve
- /engage/casestudy-innovapos
Check the images are still there
> [Image module] /engage pt4

- requirements.txt
- templates/security/_notice-brief.html
- webapp/app.py
- webapp/models.py
- webapp/security/fixtures/releases.yaml
- webapp/security/fixtures/usn/116-1.json
- webapp/security/fixtures/usn/186-2.json
- webapp/security/fixtures/usn/2945-1.json
- webapp/security/fixtures/usn/3512-1.json
- webapp/security/fixtures/usn/516-1.json
- webapp/security/fixtures/usn/612-2.json
- webapp/security/load_fixtures.py
- webapp/views.py
It's WIP
Please consider
- Are you OK with using marshmallow?
- I feel like it would be good to split USN into it's own files.
> WIP: USN API

- static/js/imageBuilder.js
Make the snap search real but limited to 12.
- Scroll to the snap search and search for something
- See that renders the result and allows you to select them.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2382
> Image builder snap search

- templates/openstack/index.html
- templates/shared/pricing/_openstack-packages.html
Updated the copy on /openstack
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#)
Fixes #6852
> Update copy on /openstack

- templates/openstack/consulting.html
Update copy on /openstack/consulting
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
Fixes #6853
> Update copy on /openstack/consulting

- templates/kubernetes/managed.html
- templates/shared/pricing/_kubernetes-managed.html
Update copy on /kubernetes/managed
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit)
Fixes #6855
> Update copy on /kubernetes/managed

- templates/openstack/managed.html
Update copy on /openstack/managed
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#)
Fixes #6854
> Update copy on /openstack/managed

- static/js/tutorial-list.js
- static/js/tutorial.js
- templates/tutorials/base_tutorials.html
- templates/tutorials/index.html
- templates/tutorials/tutorial.html
- webpack.config.js
Move inline tutorial-related JS to the build pipeline
- Check that the sorting/filtering works as expected
- Click that the side navigation links and the prev/next arrows at the bottom of each section and check that it works as expected
Fixes #6657
> Add tutorials js to build pipeline

- templates/kubernetes/docs/ldap.md
- templates/kubernetes/docs/storage.md
Update ldap policy
Add notes for CephFS
> Updates for K8s docs

- requirements.txt
> Bump flask-base to 0.4.1

- .eslintrc.js
- static/js/src/chart.js
- static/js/src/chartData.js
- static/js/src/forms.js
- static/js/src/latest-news.js
- static/js/src/navigation.js
- static/js/src/release-chart.js
- static/js/src/scratch.js
- static/js/src/tutorial.js
Fix most linting issues in JS files
- Run `./run exec yarn lint-js`
- Check that there are no linting errors except in the following files:
- formValidation.js
- dynamic-contact-form.js
- desktopStatistics.js
Fixes #6869
> Fix eslint errors

- templates/kernel/index.html
- Update the copy of the /kernel overview page
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit#)
Fixes #6890
> Update /kernel overview page

- .eslintrc.js
- static/js/src/dynamic-contact-form.js
Fix eslint errors on static/js/src/dynamic-contact-form.js
- Run `./run exec ./node_modules/.bin/eslint static/js/src/dynamic-contact-form.js`
- Check that there are no eslint errors/warnings
- Check some pages with forms to make sure they still work
- [/robotics](http://localhost:8001/robotics)
- [/automotive](http://localhost:8001/automotive)
- [/aws](http://localhost:8001/aws)
- [/ceph](http://localhost:8001/ceph)
- [/containers](http://localhost:8001/containers)
- [/core](http://localhost:8001/core)
- …
> Fix linting errors for dynamic contact form js

- package.json
- yarn.lock
Add prettier
- Make a change to a JavaScript file
- Stage that change and commit the change
- Check that prettier runs and formats only the changed file
Fixes #6882
> Add prettier

- navigation.yaml
- templates/ceph/index.html
- templates/ceph/what-is-ceph.html
- Created /ceph/what-is-ceph page
- Updated /ceph overview
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph/what-is-ceph and http://0.0.0.0:8001/ceph
- Compare to the [what is copy doc](https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/edit#) ad the [overview copy doc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit#)
Fixes #6896 and #6897
https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/edit#
> Add new what-is-ceph page, update overview

- static/js/src/dynamic-contact-form.js
- yarn.lock
Make `captchaCallback` global
- Try different forms with captcha:
- http://0.0.0.0:8001/download/server/thank-you
- http://0.0.0.0:8001/openstack#get-in-touch
- http://0.0.0.0:8001/core/contact-us
- http://0.0.0.0:8001/engage/anbox-cloud-gaming-whitepaper
- Check that the captcha is there and works as expected
Fixes #6922
> Make captchaCallback global

- templates/openstack/managed.html
- Update BootStack on /openstack/managed page
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#)
Fixes #6913
> Update BootStack on /openstack/managed page

- templates/openstack/consulting.html
- Update BootStack on /openstack/consulting page
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
Fixes #6912
> Update BootStack on /openstack/consulting page

- templates/openstack/index.html
- Update managed to Managed in 2 places
- Compare to and resolve the comments in the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit)
Fixes #6911
> Change to Managed OpenStack on /openstack page

- templates/ceph/index.html
Updated copy on /ceph
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit#) have been done and resolve comments
Fixes #6929
> Update copy on /ceph

- templates/desktop/developers.html
- Update /desktop/developers illustrations
- See that it complies with the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6948)
Fixes #6948
> update /desktop/developers illustrations

- .gitignore
- HACKING.md
- README.md
- package.json
- requirements.txt
- yarn.lock
Convert this project, as per the instructions in
https://github.com/canonical-web-and-design/dotrun/blob/readme-flask-base/README.md#converting-existing-projects
QA
--
Follow the updated instructions in the README.md of this branch. Check the site runs etc.
> Enable & document dotrun

- package.json
QA
--
`dotrun`, see pretty colours.
> Get colors in concurrently output

- static/js/src/latest-news.js
- templates/base_index.html
- templates/templates/_navigation.html
- templates/templates/base_no_nav.html
- templates/templates/footer.html
Fix HTML validation errors on the homepage
- Enter the demo URL into https://validator.w3.org/
- You should see no errors or warnings
Fixes #6727
> Fix HTML validation errors

- templates/kubernetes/docs/install-manual.md
- templates/kubernetes/docs/release-notes.md
updates doc links to point to correct bundle
> use correct k8s bundle

- static/js/src/core.js
- static/js/src/forms.js
- static/js/src/navigation.js
- static/js/src/scratch.js
- static/js/src/tabotronic.js
- static/js/src/tutorial-list.js
Run prettier over all JS files
- Check that the site builds
> Run prettier on all JS files

- static/js/src/tutorial-list.js
- static/js/src/tutorial-list.test.js
Add tests for /static/js/src/tutorial-list.js
- Run `./run exec yarn test-js static/js/src/tutorial-list.test.js
- Check that the tests pass
> Add tutorial list JS tests

- .circleci/config.yml
Add JS testing as a build step
> Add JS test command to build steps

- templates/engage/developer-desktop.html
Changes the text from 240 to 100+ and updated [the copy doc](https://docs.google.com/document/d/1bqD9QKDj6ZfRkn-vbDrHHE_Zrk81cA5hFLRHZYFzzSA/edit)
- Code review required.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6982
> To many countries claimed in engage page

- templates/templates/_navigation-developer-h.html
- templates/wsl/base_wsl.html
- templates/wsl/index.html
- Added /wsl page, based on the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/wsl
- See that the page matches the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#) and looks good
Fixes #6185
> 6185 build wsl page

- static/js/imageBuilder.js
- templates/core/build.html
Update the thank you page
- Make a selection and click build
- See that you land on a page that matches [the copy doc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#) and [the design](https://github.com/canonical-web-and-design/web-squad/issues/2370#issuecomment-590955286)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2363
> Update the thank you page

- templates/security/index.html
Remove internal link back to usn for soft launch
> Remove internal link for soft launch

- webapp/security/models.py
There was some confusion in the foreign keys.
This is a fix :)
> Fix foreign keys type

- webapp/security/alembic/versions/e8760725610a_firstmigration.py
Not cool. But we again forgot the migration script... sorry for the spam
> Fix migration script

- webapp/security/alembic/versions/e8760725610a_firstmigration.py
- finish all the cleaning
- `./run`
- Make sure site sill works
> Remove imports

- templates/core/build.html
Update the board images.
- Check the board images load and look ok
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7014
> Update the raspberry pi image

- static/sass/_pattern_calculator.scss
This is a superficial change, to trigger a new build that hopefully pulls in latest styles to live site.
> update calculator tooltip css selector

- static/sass/_pattern_buttons.scss
- templates/core/build.html
- webapp/views.py
Updated the Marketo form id and pass the user details.
- Trigger a build but ensure to opt in which the checkbox
- **Marketo is not showing it but I need to check with Lucia how to test this for realz**
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2432
> Update Marketo post for image builder

- Dockerfile
This reverts commit ad6236bfecada98925ad359c31df78ba09cdeff7.
The number of checks has been updated https://bugs.launchpad.net/launchpad/+bug/1867649
> Revert "Temp: Remove mirror list to fix mirror issues"

- templates/kubernetes/docs/openstack-integration.md
Add correction to OpenStack overlays
> Add updates for OpenStack/K8s docs

- static/js/src/imageBuilder.js
- templates/core/build.html
- Restyle the login section
- Fix the disable overlap
- Always display Got an app that isn’t in the Snap Store
- Conditionally display email in build page
- Update the footer content 
- Check I have addressed al lthe comment here: https://github.com/canonical-web-and-design/ubuntu.com/pull/6695#issuecomment-600053523
> Image builder address design review comments

- templates/openstack/compare.html
- Made copy updates to /openstack/compare
- Check the page against the [copydoc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit#heading=h.2qe5hqoifc4q)
Fixes #2505
> Copy updates to /openstack/compare

- templates/containers/index.html
- templates/internet-of-things/gateways.html
- Minor fixes on /containers/
- Minor fixes on /internet-of-things/gateways
> Grammar and punctuation on Containers and Gateways

- requirements.txt
> Pin httpretty

- templates/download/server/s390x.html
- templates/download/shared/_get-ebook-security.html
- templates/download/shared/_get_ebook_maas.html
- templates/engage/_base_engage_markdown.html
- templates/engage/events.html
- templates/engage/shared/_de_engage_form.html
- templates/engage/shared/_en_engage_form.html
- templates/engage/shared/_es_engage_form.html
- templates/engage/shared/_fr_engage_form.html
- templates/kubernetes/_get_ebook.html
- templates/rfp/index.html
- templates/shared/_client-contact-us-form.html
- templates/shared/_cloud-contact-us-form-german.html
- templates/shared/_cloud-contact-us-form.html
- templates/whitepapers/beta/shared/form.html
- templates/whitepapers/shared/form.html
- Changed 'Phone number' to 'Mobile/cell phone number' for all forms and in German, French, Spanish as well.
- NOTE **I did not update the copy docs**
- View the site locally in your web browser a few example pages:
- http://localhost:8001/engage/ - select a few and try other languages 
- http://localhost:8001/kubernetes/
- http://localhost:8001/rfp/
- http://localhost:8001/openstack/contact-us
Fixes #7068
> Change phone to mobile phone

- webapp/security/models.py
- webapp/security/schemas.py
- webapp/security/views.py
- Models and schema (no API yet)
- No QA really, just want to make sure the models are correct and I am creating the relationships correctly because, once this is run, we'll start messing the db if it is not correct.
Fixes #7072
> Build db models

- templates/openstack/features.html
- Update storage section on /openstack/storage
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/storage
- Compare to the [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#heading=h.49tyzukwvabb)
Fixes #7090
> Update storage section on /openstack/storage

- navigation.yaml
- templates/managed-apps/_base_managed-apps.html
- templates/managed-apps/contact-us.html
- templates/managed-apps/index.html
- templates/managed-apps/thank-you.html
- templates/shared/forms/interactive/_managed-apps.html
- templates/templates/_navigation-enterprise-h.html
- templates/templates/footer.html
- Created new /managed-apps page
- Created new modal contact us page
- Created js fallback contact-us and thank-you pages
- Added managed apps to the footer, enterprise mega menu (also added the tco calculator)
- http://0.0.0.0:8001/managed-apps - see the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit#)
- http://0.0.0.0:8001/managed-apps#get-in-touch - see the [copy doc](https://docs.google.com/document/d/1N1S1J1oYVAzp2rs5PF-u8re9GE6c8xpyi17FrzVeOgM/edit)
- http://0.0.0.0:8001/managed-apps#enterprise - see the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit#)
- …
> Add new /managed-apps page

- package.json
We had a broken build and bumping seemed to fix it
> Bump @babel/preset-env to 7.8.7

- templates/ceph/what-is-ceph.html
Updated the copy on /ceph/what-is-ceph
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph/what-is-ceph
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/edit) have been done and resolve the comments
Fixes #7101
> Update copy on what is ceph page

- templates/openstack/compare.html
Added images to /openstack/compare
- Check that the images on the page match [the copy doc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2504
> Add images to openstack compare pagex

- templates/managed-apps/index.html
- Copy updates and new aws logo on /managed-apps
- Compare to the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit#)
Fixes #7109
> Copy updates and new aws logo on /managed-apps

- README.md
- docker-compose.yaml
- package.json
QA
--
Follow postgres instructions in the readme
Go to /security/notices, see it works.
> Switch to using postgres in local dev

- templates/managed-apps/index.html
As highlighted by linkchecker:
https://github.com/canonical-web-and-design/ubuntu.com/runs/554200077?check_suite_focus=true
> Fix managed apps 404

- webapp/views.py
- Add renewal object to context
- Should work as usual
> Add renewal to context

- navigation.yaml
- templates/robotics/base_robotics.html
- templates/robotics/index.html
- templates/robotics/what-is-ros.html
Build /robotics/what-is-ros page
- View the site locally in your web browser at: http://0.0.0.0:8001/robitcs/what-is-ros
- Check that it matches [the copy doc](https://docs.google.com/document/d/1yX2Ikcn1fgIKX3el8fKWQt7SGxSwY633TfW5V1lwUuc/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2571
> Build what is ROS page

- .github/workflows/external-links.yaml
- .github/workflows/live-links.yaml
Try running "External links" on PR so we can check it runs properly.
It probably won't work on this branch 'cos this is on my fork, but just checking this is still the case.
> Rename to external links

- templates/robotics/what-is-ros.html
- Update /robotics/what-is-ros banner and images
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/what-is-ros
- See that it looks like described in #7131
Fixes #7131
> Update /robotics/what-is-ros banner and images

- templates/legal/contributors/agreement.html
- Remove broken captcha, replaced with google recaptcha
- This is nearly 100% form assembly code, I just removed all the styles
- The form submits fine, but the errors are a bit odd; however, getting a working form up is more important right now.
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/contributors/agreement
- Test that the form submits
Fixes #7120
> Remove broken captcha, replaced with google recaptcha

- navigation.yaml
- templates/robotics/community.html
- templates/robotics/index.html
- New /robotics/community page
- Minor error fix on /robotics page
- Compare to the [copy doc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit?ts=5e4fe92c#) and the design of the top bit
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2570
> New /robotics/community page

- templates/robotics/community.html
- templates/robotics/index.html
- updated logos, meta data
- Compare to the [copy doc](https://docs.google.com/document/d/1JNFk2C0shH3DapKuJM8X0QfAiD1RzHvXoydn8P9mEMg/edit#heading=h.razhg7hxjuw7)
> Update /robotics page

- templates/robotics/index.html
- removed some odd pasted code.
> Odd extra code in a link

- templates/robotics/what-is-ros.html
- Update /robotics/what-is-ros images
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/what-is-ros
- See that the images are openrobots and canonical in the banner and then ROS in the row below
> Update /robotics/what-is-ros images

- templates/managed-apps/index.html
- Update text for /managed-apps
- See the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit?ts=5e8f4962#)
> Update text for /managed-apps

- releases.yaml
- Initial update of releases.yaml
- For now, you will see that that LTS release and previous LTS release has been updated, but the pages still show the Latest release, that needs to be fixed in later PRs
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2617
> Initial update of releases.yaml

- templates/openstack/install.html
- Add resource to /openstack/install
- Compare to the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit) and resolve all comments
Fixes #7179
> Add resource to /openstack/install

- templates/openstack/index.html
- Update resources on /openstack
- Note, bottom resource row is fixed in another PR, ok to resolve
- Compare to the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit
) and resolve all comments
Fixes #7181
> Update resources on /openstack

- templates/openstack/consulting.html
- templates/shared/_resources_openstack.html
- Update resources on /openstack/consulting
- Compare to the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#) and resolve all comments
Fixes #7180
> Update resources on /openstack/consulting

- static/js/src/latest-news.js
Check if an article has a feature image before accessing it
- Check the blogs load.
> Check if an article has a feature image before accessing it

- .github/workflows/external-links.yaml
(Completely untested, but seems like the problem.)
> external-links: fix threads argument

- templates/engage/fr/migrer-de-vmware-a-openstack.md
Update the /engage/fr/migrer-de-vmware-a-openstack h1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/migrer-de-vmware-a-openstack
- See that the title is in French
> Update the /engage/fr/migrer-de-vmware-a-openstack h1

- templates/kernel/index.html
- Update /kernel page for 20.04
- Compare to the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit) and resolve all comments
Fixes #7188
> Update /kernel page for 20.04

- templates/legal/ubuntu-advantage-service-description/index.md
- templates/shared/pricing/_ua-for-infrastructure.html
- Updated the Ubuntu Advantage service description comments
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit?ts=5e8efd57#) and resolve all comments that have a +canonical-editors@c.c request on them
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2623
> Update /uasd page

- templates/livepatch/index.html
- updated the title
- updated the starting image of the video
- View the site locally in your web browser at: http://0.0.0.0:8001/livepatch
- Compare to the [copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit
) and resolve all comments
Fixes #7192
> Update title of /livepatach for 20.04

- templates/openstack/managed.html
Updated managed openstack copy
- Compare with [copydoc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#)
Fixes #7178
> Copy update managed openstack

- templates/ceph/index.html
Updated ceph page
- Compare to [copydoc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit)
Fixes #7139
> 7139 ceph copy

- templates/desktop/features.html
- Text updates only
- **Still needs images updated**
- View the site locally in your web browser at: http://0.0.0.0:8001/destkop/features
- Compare to the [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit#) and resolve all comments
Fixes #7161
> Focal updates for /desktop/features

- requirements.txt
- webapp/views.py
Making use of the new Launchpad.create_system_build_webhook
QA
--
``` bash
dotrun clean
dotrun
```
Go to http://0.0.0.0:8001/core/build, build things, ask Robin what to do next.
> Create webhooks for image builds

- templates/desktop/index.html
- templates/shared/contextual_footers/_desktop_flavours.html
- Text updates to the /download page only
- **still needs images**
- Compare to the [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit#heading=h.p4z8er2l4p9m) and resolve all comments
Fixes #7158
> Focal updates to the /desktop page

- templates/download/index.html
- Update /download for 20.04
- Note - not sure I like the design for the 2 notices in the banner
- Compare to the [copy doc](https://docs.google.com/document/d/1egsCcmFiz8czeHsvwoB9Jz815Ij5Urtf7Ngrru6Zd4o/edit#) and resolve all comments
Fixes #7165
> Update /download for 20.04

- templates/desktop/organisations.html
- Text changes (minor) only
- **Needs updated images**
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/organisations
- Compare to the [copy doc](https://docs.google.com/document/d/1q3_fQB3PUGbREsbCC4FnmHrpgn9nIWtMwyhDC6CXhNE/edit#heading=h.oiylzglmjlnq) and resolve all comments
Fixes #7162
> 20.04 updates to /desktop/organisations

- templates/desktop/developers.html
- templates/shared/contextual_footers/_desktop_download.html
- Text updates to page only
- **Needs new images**
- Compare to the [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#) and resolve all comments
Fixes #7160
> 20.04 updates to /desktop/developers

- .github/workflows/pr.yaml
> Fix dotrun in CI

- templates/desktop/developers.html
- Update /destkop/developer images
- View the site locally in your web browser at: http://0.0.0.0:8001/destkop/developer
- See that the screenshot and the laptop have been updated per the issue
Fixes #7255
> Update /destkop/developer images

- static/sass/styles.scss
- templates/desktop/index.html
- Update images on /desktop
- See that the images match the attached issue
Fixes #7254
> Update images on /desktop

- templates/kubernetes/managed.html
Removed a sentence as per the copy doc.
R
- Review against the [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit?ts=5e9ea184) and accept correct changes.
Fixes #
> Removed some a sentence.

- .github/workflows/cypress.yaml
- .github/workflows/master-links.yaml
- .github/workflows/pr.yaml
- Dockerfile
- entrypoint
- requirements.txt
- Update talisker v0.18.0
- Update docker image to focal
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag ubuntu.com .`
-  `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key --env DATABASE_URL=sqlite:///usn.sqlite3 ubuntu.com`
- http://0.0.0.0:8006/
- Play around with the site and make sure it works well
> Update to focal

- templates/desktop/developers.html
- templates/desktop/index.html
Update two images that @anthonydillon thought looked smushed
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop and http://0.0.0.0:8001/desktop/developers
- See that the images in Visuall stunning on desktop over view and developer hero look better
> Update 2 images in /desktop and /desktop/developers

- templates/download/desktop/index.html
- Update Windows 8 to 10 on /download/desktop
- Updated [copy doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit)
Fixes #7329
> Update Windows 8 to 10 on /download/desktop

- templates/ceph/what-is-ceph.html
- Made the CTA on the What is Ceph page a positive button
- Run the site using the command `./run serve` or `dotrun
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph/what-is-ceph
- See that the "Get in touch" button is green
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2658
> Update the CTA in the hero of the What is Ceph page to a positive button

- static/sass/styles.scss
- templates/security/cve/cve.html
Updated the design of the CVE priority and CVSS score
- Run `dotrun exec python3 webapp/security/fixtures/releases.py`
- Run `dotrun exec python3 webapp/security/fixtures/load_sample_cve.py`
- Run `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/CVE-2020-10535
- Check that the priority badge and CVSS score look the same as in the screenshot: https://usercontent.irccloud-cdn.com/file/opPg0czI/image.png
> Update design of CVE priority and CVSS status

- static/js/src/imageBuilder.js
- templates/build/index.html
- webapp/app.py
- webapp/views.py
To avoid duplication.
QA
--
`dotrun`, go to `/build`, kick off a build, check it all works as expected.
> Pass through board_architectures

- static/js/src/imageBuilder.js
- templates/build/index.html
Check all ticked issues are resolved: https://github.com/canonical-web-and-design/ubuntu.com/pull/6695#issuecomment-600053523
> Image builder addressing review points

- templates/build/index.html
Update the copy from review
- Check the copy matches the suggested changes in [the doc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit?ts=5ea7f038)
> Update the copy from review

- .stylelintrc
- package.json
- static/sass/takeovers/_1710-release.scss
- static/sass/takeovers/_1804-release.scss
- static/sass/takeovers/_ai-webinar.scss
- static/sass/takeovers/_enterprise-kubernetes.scss
- static/sass/takeovers/_financial-services.scss
- static/sass/takeovers/_kubernetes-month.scss
- static/sass/takeovers/_kubernetes-webinar.scss
- static/sass/takeovers/_openstack-queens.scss
- static/sass/takeovers/_private_cloud_economics.scss
- static/sass/takeovers/_rigado-webinar.scss
- static/sass/takeovers/_ubuntu-product-month.scss
- static/sass/takeovers/_vmware-to-os.scss
- yarn.lock
- Update the stylelint config to use the same plugins as Vanilla
- Check that the CSS linting passes: `dotrun exec yarn run lint-scss`
- Check that the CSS builds: `dotrun exec yarn run build-css`
> Update stylelint config plugins to match vanilla

- webapp/views.py
By posting an error to sentry whenever signatures don't match.
> Debug webhook signatures

- webapp/views.py
Fixes https://sentry.is.canonical.com/canonical/ubuntu-com/issues/9627/, I hope
> Fix sentry reporting

- templates/shared/forms/interactive/_managed-apps.html
- Updated the managed apps contact form from the [copydoc](https://docs.google.com/document/d/1N1S1J1oYVAzp2rs5PF-u8re9GE6c8xpyi17FrzVeOgM/edit#)
- View the site locally in your web browser at: http://localhost:8001/managed-apps#get-in-touch
- Submit the form (and check that the data is received - don't use a canonical email)
Fixes #7384
> Update contact form for managed apps

- webapp/security/views.py
QA
--
``` bash
rm usn.sqlite3
dotrun exec python3 webapp/security/fixtures/releases.py
dotrun exec python3 webapp/security/fixtures/load_sample_cve.py
dotrun
```
Go to `/security/cve`. Enter an ID of a valid CVE, e.g. "CVE-2020-9064". Check you end up on  http://0.0.0.0:8001/security/cve-2020-9064.
Now enter an CVE number that's not in our database - e.g. "CVE-2020-9069". Check you see an empty results page.
> Redirect from /security/cve?q={id} to CVE page

- templates/base_index.html
Add LTS to the default takeover
> Add LTS to the default takeover

- .env
- Dockerfile
- templates/advantage/index.html
- templates/core/build/index.html
- webapp/app.py
- webapp/login.py
- webapp/views.py
This will fix issues for people with old login sessions who visit /advantage and see no data.
QA
--
Go to the old code:
```
git checkout eeb7500aa2a35d9c9a09b3f250c235fd0e4ee7d6
sed -i '/ADVANTAGE/d' .env  # Remove staging from .env
dotrun
```
Go to `localhost:8001/advantage`, if you're logged in, log out and back in again, see your key.
Now change the code back to this branch:
```
git checkout .env
git checkout fix-advantage-login-issue
```
Go to `localhost:8001/advantage`, you should be logged out now (rather than logged in but seeing empty data). Login, see your keys.
> Use user_info everywhere

- templates/kubernetes/features.html
- Update text on /kubernetes/features page
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/features
- Compare to the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#) and resolve all comments
Fixes #7434
> Update text on /kubernetes/features page

- templates/masters-conference/index.html
Update the Ubuntu masters page content
- Check the content matches [the copy doc](https://docs.google.com/document/d/1Z63eMCe9o4Onk2ezPFLPDTbI-uJezAOzI-aSpXmZ5lc/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2697
> Update the Ubuntu masters page content

- webapp/app.py
- webapp/security/auth.py
- webapp/security/fixtures/usns.py
- webapp/security/views.py
Add an endpoint to allow update of security notices
Ping me and lets do a pair QA
> Add endpoint to update security notices

- templates/engage/azure-webinar.md
"Learn morew" -> "Learn more"
- Check CTA on Azure WBN page, on mobile: [/engage/azure-webinar](https://ubuntu-com-canonical-web-and-design-pr-7486.run.demo.haus/engage/azure-webinar)
> Learn morew

- templates/templates/footer.html
- Add appliance section to the footer
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance
- Look at the footer in the above link
> Add appliance section to the footer

- templates/security/index.html
Updated the copy on /security
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#) have been made
- Resolve the comments
Fixes #7527
> Update copy on security page

- templates/engage/fr/utiliser-gpgpus-avec-kubernetes.html
Updated the copy on /engage/fr/utiliser-gpgpus-avec-kubernetes
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/utiliser-gpgpus-avec-kubernetes
- Check that the page matches [the copy doc](https://docs.google.com/document/d/11wv7ic0Wx-GQqzoDwYGsyu6IkLR2la7_NUSpHfk9Hew/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2764
> Update gpgpus french page

- navigation.yaml
- templates/templates/_navigation.html
Improve the navigation of appliance
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance
- Click through the appliance pages and check the navigation is :ok_hand:
> Improve the navigation of appliance

- templates/kubeflow/index.html
Updated the copy on /kubeflow
- Check that the changes requested by Rui Vasconcelos in [the copy doc](https://docs.google.com/document/d/1mJq8PxH8FVRVF9i1Xzh0f6M73eyjqZE4NaKYHRcRAKM/edit#) have been made and please resolve comments
Fixes #7537
> Update copy on kubeflow page

- templates/kubernetes/index.html
- Update /kubernetes resources and microk8s block
- Compare to the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#), there are two sections marked +canonical-editors
Fixes #7577
> Update /kubernetes resources

- templates/managed/_base_managed-apps.html
- templates/managed/index.html
- templates/managed/kafka.html
- templates/shared/forms/interactive/aws.html
- templates/shared/forms/interactive/azure.html
- templates/shared/forms/interactive/bootstack.html
- templates/shared/forms/interactive/embedded.html
- templates/shared/forms/interactive/general.html
- templates/shared/forms/interactive/kubeflow.html
- templates/shared/forms/interactive/kubernetes.html
- templates/shared/forms/interactive/managed-apps.html
- templates/shared/forms/interactive/managed-kafka.html
- templates/shared/forms/interactive/masters-conference.html
- templates/shared/forms/interactive/openstack.html
- templates/shared/forms/interactive/partner-dell.html
- templates/shared/forms/interactive/pricing-infra.html
- templates/shared/forms/interactive/robotics.html
- templates/shared/forms/interactive/storage.html
- templates/shared/forms/interactive/support-openstack.html
- templates/shared/forms/interactive/support.html
- Created a managed kafta modal form
- Created a [script to build](https://intl.transitionelement.com/modal/index.cgi?title=Canonical%E2%80%99s+Managed+Kafka&description=Apache+Kafka%2C+managed+by+the+open+source+experts.&q1=What+version+of+Kafka+are+you+running%3F&q1-answers=1.x%0D%0A2.x&q1-code=version+of+kafka&q1-other=&q2=Where+are+you+running+it%3F&q2-answers=Amazon+Web+Services%0D%0AMicrosoft+Azure%0D%0AGoogle+Cloud%0D%0AKubernetes%0D%0AOpenStack%0D%0AOracle%0D%0AVMWare%0D%0ACisco%0D%0AOther+public+cloud%0D%0AOther+on-premises%0D%0A&q2-code=where-are-you+running+kafka&q2-other=&q3=And+are+you+using+any+other+apps+with+it%3F&q3-answers=ElasticSearch%0D%0AOpen+Source+Mano%0D%0AInfluxDB%0D%0APostgreSQL%0D%0AGraylog%0D%0AGrafana%0D%0AMongoDB%0D%0AMySQL%0D%0APrometheus%0D%0ACassandra&q3-c …
> Add modal managed kafka page

- templates/openstack/what-is-openstack.html
- Add button to /openstack/managed in header on /openstack/what-is-openstack
- Compare and resolve comments in the [copy doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#)
Fixes #7591
> Add button in header on /openstack/what-is-openstack

- templates/wsl/index.html
- Update copy and ctas on /wsl
- View the site locally in your web browser at: http://0.0.0.0:8001/wsl
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#)
Fixes #7594
> Update copy and ctas on /wsl

- templates/engage/eu-kubernetes-event.md
[- Check the copy against the copy doc and accepts the correct changes](https://docs.google.com/document/d/1VYYmd6kS0eWApEpbVCgTUq0NOHUTEeRWVj7ujtFEsHs/edit)
Fixes #7623 
> Changed CTA text from "register" to "Watch now"

- templates/appliance/shared/_intel-nuc.html
- templates/appliance/shared/_raspberry-pi.html
- templates/appliance/shared/_steps_nuc_first_boot.html
- templates/appliance/shared/_steps_nuc_flash_usb.html
- templates/appliance/shared/_steps_nuc_install_appliance.html
- Update intel nuc install instructions
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex/intel-nuc
- Compare to the [copy doc](https://docs.google.com/document/d/1gb03YbX5ZQ_oO74M36b3ybCPwqq29d8Q17c6KaguW18/edit) and resolve comments
> Update intel nuc install instructions

- templates/about/release-cycle.html
- Clarify ESM timeframe on /about/release-cycle
- Compare to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)
Fixes #7566
> Clarify ESM timeframe on /about/release-cycle

- templates/kubernetes/docs/hacluster.md
- templates/kubernetes/docs/monitoring.md
- fix image link
- correct rendering problem on HAcluster page
> minor fixes

- .env
- webapp/advantage.py
- webapp/app.py
- webapp/views.py
Reverted contract API and Stripe config variables back to prod environments
> update contract and stripe config variables to prod environments

- templates/managed/kafka.html
- Align page title tag with copy doc
> Update /managed/kafka title tag

- templates/engage/snapd-whitepaper.md
Update snapd whitepaper mkto form id
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7659
> Update snapd whitepaper mkto form id

- static/js/src/dynamic-contact-form.js
- templates/shared/forms/interactive/embedded.html
Updated the contact form which is used on /internet-of-things and /core
- View the site locally in your web browser at: http://0.0.0.0:8001/core#get-in-touch
- Check that the form has been updated according to [the brief](https://docs.google.com/document/d/1jHS5waINlWyiPREDp5UTZPaQK_leiTgDZUT3iR-nq_0/edit#) and [the copy doc](https://docs.google.com/document/d/19sCToE5woNjc2SmzbvOprp31Y97TOzHJJIY2L8BFi2o/edit#heading=h.d2zk43f61757)
- Click that the form works
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things#get-in-touch
- Check that the form has been updated according to [the brief](https://docs.google.com/document/d/1jHS5waINlWyiPREDp5UTZPaQK_leiTgDZUT3iR-nq_0/ …
> Update contact form for iot and core pages

- templates/managed/index.html
- Update copy on /managed
- Compare and resolve comments in [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit#)
Fixes #7678
> Update copy on /managed

- templates/legal/terms-and-policies/contact-us.html
- This form was 500'ing... so I updated with some UGLY form assembly code.
- Don't look to hard at it
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies/contact-us
- See that the form submits
> Update /legal/terms-and-policies/contact-us form with new form assembly code

- templates/public-cloud/index.html
Updated the copy on /public-cloud
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#) and resolve the comments
Fixes #7695
> Update copy on /public-cloud page

- templates/appliance/about.html
Update appliance about page content
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/about
- Check the content matches [the copy doc](https://docs.google.com/document/d/1UM4K9n9SFNiWdmKIBnPGCsjLQrPSOnqZHMNIMwQ2CZI/edit#)
> Update appliance about page content

- requirements.txt
To avoid versioned_static from breaking the site.
QA
--
clean then run the site. Check everything, especially /download/server.
> Update to flask-base 0.6.2

- templates/appliance/about.html
- Update about page content
- Apply design
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/about
- Ensure the copy matches [the copy doc](https://docs.google.com/document/d/1UM4K9n9SFNiWdmKIBnPGCsjLQrPSOnqZHMNIMwQ2CZI/edit#)
- Check the page looks like [the design](https://app.zeplin.io/project/5eb3d16a91c4117789940141/screen/5ee2140d0dbd73b3d0f5e17d)
> Update about page content

- templates/appliance/adguard/index.md
- templates/appliance/mosquitto/index.md
- templates/appliance/nextcloud/index.md
- templates/appliance/openhab/index.md
- templates/appliance/plex/index.md
- templates/appliance/shared/_base_appliance_index.html
- Update appliance yaml
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/ and check each appliance
- Compare to the [copy docs](https://drive.google.com/drive/folders/1s872nhzjZxz5-WYGnnEUxysyRFgoA1p2)
> Update appliance yaml

- navigation.yaml
- static/js/src/appliance.js
- static/js/src/desktop-statistics.js
- static/js/src/tabotronic.js
- static/sass/_pattern_card.scss
- static/sass/styles.scss
- templates/appliance/hardware.html
- templates/appliance/shared/_featured_appliances.html
Build the appliance hardware page
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/hardware
- Check the copy matches [the doc](https://docs.google.com/document/d/179RBNgtGr5Y8CkkYaUa6sdFaaTJTTvs_VCTr6UzECFo/edit#)
- Check it matches [the design](https://app.zeplin.io/project/5eb3d16a91c4117789940141/screen/5ee2140b4b123fb826c6ef8d)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7710
> Appliance hardware

- templates/appliance/adguard/_next-steps.html
- Update adguard next steps
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/adguard/vm
- Compare to the [copy doc](https://docs.google.com/document/d/1ZqSQdPuQ3EYhNuzoaeln6tCivLq27Zwaj5sdPNpHOno/edit?ts=5ee7b3e7)
> Update adguard next steps

- templates/appliance/shared/_steps-multipass-find-ip-macos.html
- templates/appliance/shared/_steps-multipass-find-ip-windows.html
- Update windows and macos instructions
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex/vm
- Compare to the [copy sheet](https://docs.google.com/spreadsheets/d/1eZD3zISXBSNwAwkxlIRtV1UqP8GKPi0YAis8IRLZ9Po/edit?ts=5ee76828#gid=1141575055)
> Update windows and macos instructions

- templates/engage/msvoss-win-t-shirt.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/msvoss-win-t-shirt
- Content is roughly here: https://docs.google.com/forms/d/1JJsu__wQregWFUzJNVWOfetSi6i85nqSjAyaDukFPHo/prefill and from an email
> H1 Win an Ubuntu t-shirt at the Microsoft European Open Source Virtual Summit (can be shortened to MSVOSS)
> 
> Rest of the copy (credits to @Anastasia Valti )
> https://docs.google.com/forms/d/e/1FAIpQLSexqEVi8AG16ExVSa2K4sAZY7SzSXqQwUkkh9mcveJES1Qe8Q/viewform
> 
> With a link to our T&Cs: 
> I agree to receive …
> Create msft t-shirt engage form

- templates/appliance/index.html
Fix appliance links
- Check the code.
> Fix appliance links

- templates/templates/footer.html
- Moved Managed section in footer as it was under the random, non-sections in the right column
- View the site locally in your web browser at: http://0.0.0.0:8001/ go to the footer
- See that it looks better than live
Fixes #7781
> Moved Managed section in footer

- templates/appliance/index.html
> Snap Store not Snapstore

- templates/engage/index.html
- templates/engage/scaling-securely-ubuntu-azure.md
Add Azure engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/scaling-securely-ubuntu-azure
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1g9siqN4yYDmqEj1KNn33qopS0bkV-mjCw30-3TgLJ-U/edit?ts=5ed8ae32#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/1gZU31uAkU2AAVerDeK1UyV1nkmRS8RLe-LdIVl8aVho/edit)
Fixes #7719
> Azure whitepaper engage page

- static/sass/styles.scss
- templates/gov/base_gov.html
- templates/gov/contact-us.html
- templates/gov/form.html
- templates/gov/index.html
- templates/gov/thank-you.html
- Add /gov page
- Add /gov contact form
- View the site locally in your web browser at: http://0.0.0.0:8001/gov
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1umM1XMEzqeXklPkyCjDr98Q-RvwCcNNXgwNwfLoynTo/edit#)
- Check that the form matches [the copy doc](https://docs.google.com/document/d/1B-2oVj3NU8PYvPWohVYKrYkNFCOUlHS3b31c4J5l_Gk/edit#heading=h.tk4y6g6el1tm) and works as expected
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2847, https://github.com/canonical-web-and-design/web-squad/issues/2848
> Add /gov page and contact form

- templates/aws/index.html
- templates/azure/index.html
- templates/engage/ai-ml-ubuntu.html
- templates/engage/fr/utiliser-gpgpus-avec-kubernetes.html
- templates/kubeflow/consulting.html
- templates/kubeflow/features.html
- templates/kubernetes/features.html
- templates/kubernetes/index.html
- templates/kubernetes/managed.html
- templates/openstack/consulting.html
- templates/openstack/features.html
- templates/openstack/index.html
- templates/openstack/managed.html
- templates/shared/forms/interactive/bootstack.html
- templates/shared/forms/interactive/kubeflow.html
- templates/shared/forms/interactive/kubernetes.html
- templates/shared/forms/interactive/openstack.html
- templates/shared/forms/interactive/support-openstack.html
- templates/shared/pricing/_kubernetes-consulting-add-ons.html
- templates/shared/pricing/_openstack-packages.html
- templates/templates/navigation-enterprise-h.html
- Replace GPGPU with GPU
- **NOTE** - I have not updated the copy docs, but will over the next few days
- See that GPGPU was changed to GPU correctly
Fixes #7769
> Replace GPGPU with GPU

- templates/public-cloud/index.html
Updated the copy on /public-cloud
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit)
Fixes #7789
> Update public cloud page copy

- templates/shared/forms/interactive/managed-kafka.html
Updated the contact form for managed kafka
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/kafka#get-in-touch
- Check that it matches [the copy doc](https://docs.google.com/document/d/1ExHVIv4GkX7AJUueAt7os1ryawAWO7Zj2HymU0o31YA/edit#) and check that it works
Fixes #7791
> Update managed kafka contact form

- templates/gov/index.html
Updated the copy on /gov
- View the site locally in your web browser at: http://0.0.0.0:8001/gov
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1umM1XMEzqeXklPkyCjDr98Q-RvwCcNNXgwNwfLoynTo/edit#) and resolve the comments
Fixes #7811
> Update copy on gov page

- static/js/src/dynamic-contact-form.js
- templates/shared/forms/interactive/managed-apps.html
Updated the contact form for managed apps
- View the site locally in your web browser at: http://0.0.0.0:8001/managed#get-in-touch
- Compare the form to [the copy doc](https://docs.google.com/document/d/1N1S1J1oYVAzp2rs5PF-u8re9GE6c8xpyi17FrzVeOgM/edit#) and check that it works
Fixes #7790
> Update managed apps contact form

- requirements.txt
- webapp/app.py
- webapp/views.py
Use the new version of the blog module.
This is WIP until the PR is merged, the new version published, and `requirements.txt` has been switched over to use that published version.
QA
--
Run the site, go to `/blog`, `/blog/press-centre`, `/blog/internet-of-things` etc. Check everything looks the same as live at https://ubuntu.com/blog.
> Switch to canonicalwebteam.blog v6

- templates/azure/pro.html
Update the Azure Pro content
- Check the changes match [the copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit)
- Design check that page looks ok on all screens sizes
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7840
> Update the Azure Pro content

- templates/masters-conference/index.html
- Update /masters-conference page post event
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1Z63eMCe9o4Onk2ezPFLPDTbI-uJezAOzI-aSpXmZ5lc/edit)
Fixes #7867
> Update /masters-conference page post event

- webapp/security/schemas.py
Update the USN ID regex, to allow upload of older ones.
- Ask me so we can pair on it.
> Update USN ID regex in marshmallow shcema

- static/js/src/form-validation.js
- static/js/third-party/serialize.js
- templates/templates/base.html
- Removed hotlink to serialize.js
- Add serialize.js to third party js directory
- Include serialze.js as a module in the build pipeline
- View the site locally in your web browser at: http://localhost:8001/whitepapers/beta/robotics
- Fill out the form and check that it works
> Move serialize JS to module for performance

- templates/advantage/subscribe.html
- webapp/advantage.py
- webapp/views.py
Get UA product listings from the contracts API
Talk with me Scott 😛 
Fixes #
> Get UA product listings from the contracts API

- .github/workflows/pr.yaml
QA
--
See the `validate-deploy` check pass.
> Validate deployment config

- templates/engage/at&t-azure-webinar.html
- Added a break to the sub heading
> Added a break to the sub heading

- templates/aws/index.html
- Update copy to match copy doc.
- View the site locally in your web browser at: http://0.0.0.0:8001/aws
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit#)
Fixes #7951
> Ubuntu on AWS copy update

- templates/azure/pro.html
- Update copy to match copy doc.
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit?usp=drivesdk)
Fixes #7948
> Ubuntu Pro for Azure copy update

- templates/aws/pro.html
- Update copy to match the recent changes to the copy doc.
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit?usp=drivesdk)
Fixes #7950
> Ubuntu pro amazon copy update

- .github/workflows/cypress.yaml
- .github/workflows/external-links.yaml
- .github/workflows/live-links.yaml
- .github/workflows/master-links.yaml
Added conditional to avoid scheduled cronjobs to run in our forks.
> GitHub Action conditionals for main repo

- templates/azure/index.html
- Update copy and logos on /azure
- View the site locally in your web browser at: http://0.0.0.0:8001/azure
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit)
Fixes #7982
> Update copy and logos on /azure

- static/sass/_pattern_strip.scss
- templates/automotive/index.html
Update the automotive page
- Check that the content matches [the copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#)
- Check it matches [the design](https://user-images.githubusercontent.com/65166314/87928171-47f1b600-ca7c-11ea-9cc4-45bba031ed84.png)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2946
> Update the automotive page

- templates/azure/pro.html
Ungated the Simple VM provisioning with cloud-init ebook to https://assets.ubuntu.com/v1/a60c04fd-Optimized+Scaling+In+The+Cloud.pdf?_ga=2.120134024.1619985575.1595233389-125046274.1557910907
Fixes #
> Ungated the ebook

- webapp/security/views.py
Make package filter by exact name instead of using `LIKE`.
Display only packages of the cve that match the search criteria.
Before it was displaying all cve packages as long as one package matches the criteria.
1. Prepare local database (optional; if you have no CVE data on local):
```bash
docker-compose down # reset db
docker-compose up -d 
dotrun # to run the migrations
dotrun exec python3 scripts/create-releases.py # to populate release table
dotrun # serve the website
```
In a new terminal; Run the importer:
```bash
git clone -b test-status-component-field git@github.com:albertkol/ubuntu-cve-tracker.git # fetch testing branch
``` …
> Fix CVE package filter

- templates/engage/redhat-openstack-comparison-whitepaper.md
Added #register-section to header button
- Check on mobile to see if the button takes you to the register section
> Added #register-section to header button

- templates/desktop/index.html
s/enterprisese/enterprises on /desktop
Sanity check code change
> s/enterprisese/enterprises on /desktop

- .github/workflows/cypress.yaml
- package.json
- tests/cypress/forms_spec.js
- yarn.lock
Fixed Cypress GitHub action and added Cypress to the project
See that the GitHub action runs and that there is output from the test runner
> Enable Cypress

- templates/wsl/index.html
- Changed a header text and added 4 blog posts
- View the site locally in your web browser at: http://0.0.0.0:8001/wsl
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#)
Fixes #8049
> Update copy and add blog to /wsl

- templates/engage/redhat-openstack-comparison-whitepaper.md
The PDF had been updated so I changed the TY page link to the updated one.
- Check the form takes you to https://pages.ubuntu.com/rs/066-EOV-335/images/Comparing%20OpenStack_12.08.20.pdf
Fixes [#3041](https://github.com/canonical-web-and-design/web-squad/issues/3041)
> Updated the TY link

- templates/engage/charmed-openstack-adoption-whitepaper.md
- Add new pdf to /engage/charmed-openstack-adoption-whitepaper
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/charmed-openstack-adoption-whitepaper
- Fill in the form and see that you get redirected to https://pages.ubuntu.com/rs/066-EOV-335/images/Canonical_OpenStack_adoption_deployment.pdf
Fixes [#3021](https://github.com/canonical-web-and-design/web-squad/issues/3021)
> Add new pdf to /engage/charmed-openstack-adoption-whitepaper

- templates/index.html
Removed US k8s takeover
Fixes #
> Removed US k8s takeover

- templates/openstack/index.html
- templates/shared/pricing/_openstack-packages.html
Update copy on /openstack
- Check that the page has been updated according to [the copydoc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#) and resolve the comments in the doc
Fixes #3066
> Update copy on OpenStack page

- templates/openstack/features.html
Updated the copy on /openstack/features
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#) and resolve the comments in the doc
Fixes #3067
> Update copy on OpenStack features page

- templates/openstack/managed.html
Updated the copy on /openstack/managed
- Check that the page has been updated according to [the copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#) and resolve the comments
Fixes #3068
> Update copy on OpenStack managed page

- templates/kubernetes/docs/shared/_side-navigation.md
remove duplicate entry for tigera (it is already in CNI section)
> update k8s docs nav

- templates/openstack/compare.html
Updated /openstack/compare page copy
- Check that the page has been updated according to [the copy doc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit) and resolve the comments
Fixes #3070
> Update OpenStack compage page copy

- templates/shared/pricing/_kubernetes-managed.html
- Update pricing on /kubernetes/managed
- Compare and resolve comments in the [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit)
Fixes #8144
> Update pricing on /kubernetes/managed

- templates/security/cve/index.html
Comment out CVE component field
- Check that there is no component field in the search
> Comment out CVE component field

- templates/kubeconeurope2020/index.html
- Make /kubeconeurope2020 evergreen
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1qZGlO8ecig760hXn-8DG3fw52LNHfTM7WKwAHu_DpXc/edit?ts=5f3feb29#)
Fixes #8152
> Make /kubeconeurope2020 evergreen

- .env
- .github/workflows/cypress.yaml
- package.json
- static/js/src/advantage/contracts-api.js
- static/js/src/advantage/set-modal-info.js
- static/js/src/advantage/tests/fixtures/order-data.js
- static/js/src/ua-payment-modal.js
- static/js/src/ua-product-selector.js
- templates/advantage/_stripe-modal.html
- templates/advantage/index.html
- templates/advantage/subscribe.html
- tests/cassettes/TestRoutes.test_advantage.yaml
- webapp/advantage.py
- webapp/app.py
- webapp/views.py
- yarn.lock
Added ability to purchase UA products when logged in via SSO
- we don't have the ability to checkout as a guest yet - CS team are working on it
- when you're redirected to /advantage, you won't be able to see how many machines you have available to attach, that's coming in https://github.com/canonical-web-and-design/ubuntu.com/pull/8140
- Go to /advantage/subscribe
- If you're not already logged in via SSO, there'll be a prompt below the header asking you to do so - do so
- (if you _are_ logged in, there won't be a prompt)
- Use the form to select a product
- AWS and Azure should prevent you from being able to progress through the form, as should selecting "Other" in the version section
- Add the product to the basket, and click "Buy now"
- Using test cards from …
> Advantage shop payments

- webapp/app.py
- webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py
- webapp/security/models.py
- webapp/security/schemas.py
`black` had an update which flagged new issues in some files. This PR fixes them.
> Fix file formatting

- webapp/security/views.py
Fix filter by version pagination. This is because the filter by name and filter by version/status did not work together when counting the number of results. 
Browse to: 
https://ubuntu.com/security/cve?q=&package=thunderbird&priority=&version=focal&status=released
You will see 
_1 – 20 of 572 results_ 
But only 12 CVEs will be listed on the first page. 
1. Fetch changes
```bash
git checkout fix-filter-by-version-pagination
```
2. Run website 
```bash
dotrun
```
3. Browse to
`/security/cve?q=&package=thunderbird&priority=&version=focal&status=released`
You will see 20 CVEs listed on the first page.
> Fix pagination after version filter

- appliances.yaml
- Updated appliance SHA256 checksum
- Check the checksums match the [cdimages checksums](http://cdimage.ubuntu.com/ubuntu-core/appliances/SHA256SUMS)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8200
> Updated appliance SHA256 checksum

- templates/internet-of-things/thank-you.html
Update the small copy change in the copy doc. 
- Check the code matches [the copy doc](https://docs.google.com/document/d/1-WTp-Zf29CA5fiMV0A1rCyaNPF6xAYzZu6BThUXUSlk/edit).
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3156
> Update the IoT contact thank you content

- webapp/security/views.py
Reduce the number of queries done on the CVE page. From 25 down to 4, with an over 50% speed improvement. (I did not take before and after screenshots so you will have to take my word for it.) 
Two big changes: 
1) `total_results = cves_query.count()` -> removed
`cve_query` is already a massive query which used to be executed twice: 
- One time to get the total results found 
- One time to apply the `limit` and the `offset` on the results
Now we do it all in one, selecting the CVEs and the `count(*)`.
2) Load `CVE.statuses` one time forever, so every time we do `cve.statuses`, the values are already there. This reduced the number of queries by 20. 
1. Have the CVEs imported
2. Fetch changes
```bash
git checkout optimize-filter
```
3. Play with the filters on …
> Optimise CVE filters

- templates/base_index.html
Update the homepage content
- Check the copy matches the [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8236
> Update the homepage content

- templates/managed/index.html
- Updated the copy on the /managed page.
- Check the content matches the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit#heading=h.qp7hfvggs6wp)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3074
> Update the /managed page

- templates/engage/case-study-gmo-pepabo.md
- templates/engage/index.html
Add new engage page
- View the site locally in your web browser at: http://localhost:8001/engage/case-study-gmo-pepabo
- Check that the page matches [the brief](https://docs.google.com/spreadsheets/d/1H7dMhhbCp4iSe0T0rhOlaQipA-M0gvHjxn-hPpNaXjQ/edit#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/1xPBMAm96THxMkeNu3yH3DCN_mzFQ7LWsRqw63KySA2M/edit)
Fixes #8112
> Add GMO pepabo engage page

- static/sass/print.scss
- Fix line height
- Remove contents sidebar
- Fix margin on table in ol
- In print preview can't remove first page break, so first page is blank
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- View print preview to see changes. First page should appear blank with only Canonical link. 
Issue #8201
> Fix print page layout

- .github/workflows/pr.yaml
Fix a CI issue with pip that was blocking the merge os PR's
Make sure CI passes
> Fix lint-python CI step

- templates/internet-of-things/edgex.html
Make the EdgeX newsletter monthly instead of weekly
- Check the code has changed correctly
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8295
> Make the EdgeX newsletter monthly instead of weekly

- templates/index.html
- Update list of live takeovers
- Reload the homepage and see that only three are running (per this [sheet](https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit#gid=564832475)) 
- [Event] Telco VEVT
- [Whitepaper] Enterprise K8s challenges
- [Whitepaper] Redhat comparision
> Update list of live takeovers

- templates/security/esm/index.html
Reverts canonical-web-and-design/ubuntu.com#8250
Request from Marketing.
> Revert "Add notification banner to ESM page"

- konf/site.yaml
- Redirect apps.ubuntu.com to snapcraft.io
> Update redirect to snapcraft.io

- templates/security/cve/cve.html
- Update patches and tag messages.
Fixes #8189
> Update patches and tags

- templates/security/livepatch/index.html
- Change security/livepatch hero for consistency
- View the site locally in your web browser at: http://0.0.0.0:8001/security/livepatch and check it is as shown [here](https://github.com/canonical-web-and-design/web-squad/issues/3186)
Fixes [#3187](https://github.com/canonical-web-and-design/web-squad/issues/3187)
> Rebuild livepatch hero

- templates/managed/kafka.html
Update managed kafka
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/kafka
- Check the copy matchs the [copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#)
- Check it matches [the design](https://user-images.githubusercontent.com/1413534/92820570-03bacc00-f3c2-11ea-831d-d0096019517d.png)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3075
> Update managed kafka

- webapp/security/views.py
- Releases no longer needed at all, since we do not create releases through this endpoint
- Only update cves/statuses/packages if needed. We use a bool for each to find out if there are any changes coming from the data, if not do not update anything
- Delete only `cve.statuses` that we do not find in the cve data we receive; before we were deleting everything the inserting again which was too heavy and results in time outs. 
From my tests:
```
Before:
1st run - Insert round - Time: 7m0.526s
2nd run - Update round - Time: 7m32.567s
After:
1st run - Insert round - Time: 6m36.694s
2nd run - Update round - Time: 5m50.945s
```
> Update bulk cve update

- templates/internet-of-things/edgex.html
- Remove PROVEN IN THE FIELD strip
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/edgex
- Compare to the [copy doc](https://docs.google.com/document/d/17tvfJBC5VncEVWkEsbyW_slAFFSoWV3jQUN7sa8nkOs/edit?ts=5f6333b9#) and resolve comment
Fixes #[3204](https://github.com/canonical-web-and-design/web-squad/issues/3204)
> Remove PROVEN IN THE FIELD strip

- templates/openstack/install.html
- Update /openstack/install with updated instructions
- Thanks to @bovi and #8271
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)
Fixes #8271
> Update /openstack/install with updated instructions

- templates/legal/data-privacy/online-purchase.md
- Copy update - Online purchase page
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy/online-purchase
- Check page matches [copy doc](https://docs.google.com/document/d/1ZSNnMiLJl6SGSV0D_cr6MJAwpkf6xzbKYJdTL9MxLHc/edit#heading=h.75k0ordixf1t.)
Fixes [#3202](https://github.com/canonical-web-and-design/web-squad/issues/3202)
> Copy update - Privacy notice - Online purchase

- run
Update the version of Black to the latest
- Run `./run clean`
- Run `./run` and check the site works as expected
- Run `./run test` and check the tests pass
> Update the docker image to 1.6.8

- templates/download/server/step2.html
Check that it aligns with [the copy doc](https://docs.google.com/document/d/12kr3JvN3ALMdr5IPOheMwOaf-ygvEulFo5D7x-0ag0k/edit).
> Removed text on server/download for MAAS step

- requirements.txt
Update blog version to fix bug. 
Browse to https://ubuntu.com/blog/the-ubuntu-community-contributes-towards-saving-the-iberian-lynx
Get 500
Browse to: https://ubuntu-com-8318.demos.haus/blog/the-ubuntu-community-contributes-towards-saving-the-iberian-lynx
Get 200
> Update blog to version 6.2.4

- templates/smart-start/base_smart-start.html
- templates/smart-start/contact-us.html
- templates/smart-start/thank-you.html
- Add static contact us form and thank-you page
- Go to demo https://ubuntu-com-8334.demos.haus/smart-start/contact-us
- Fill out the form
Fixes #8257
> [Smart Start] Static contact form and thank you page

- webapp/views.py
- Fall back to shopify if the shop is not enabled, meaning there are no product listings.
- Also made associating products and listings slightly more efficient.
- Check that you are redirected to the subscribe page as usual on staging, and everything works, meaning you are able to select and buy a product.
- Then connect the app to a ua-contracts service without listings. When clicking to purchase a subscriptions you should be redirected to buy.ubuntu.com.
> Fall back to shopify if the shop is not enabled

- .env
- webapp/views.py
Sets Stripe environment to staging, to match contract API environment
> set stripe env to staging

- templates/download/server/choose.html
Fix link to multipass on download/server
> Fix link to multipass on download/server

- templates/kubernetes/docs/1.19/release-notes.md
Fix link in release notes pointing to wrong milestone
> K8sdocs - Update release-notes.md

- webapp/app.py
- webapp/security/schemas.py
- webapp/security/views.py
- Add create and delete endpoint for release
Fixes #7271
> Add release endpoints

- templates/engage/thank-you.html
- Support resources coming from ubuntu assets
- Check that https://ubuntu-com-8430.demos.haus/engage/redhat-openstack-comparison-whitepaper/thank-you allows you to download the resource
> Support resources coming from ubuntu assets

- templates/download/index.html
- Fix download page.
Go to: https://ubuntu-com-8449.demos.haus/download
It has to work.
Fixes #8448
> Fix download page image

- tests/cassettes/TestRoutes.test_engage_index.yaml
- tests/test_routes.py
- webapp/views.py
- Filter languages for related pages
- Add test for engage pages
- Check with the demo that https://ubuntu-com-8447.demos.haus/engage/vmware-to-charmed-openstack/thank-you does not show languages other than English
- Check that the github checks pass
Fixes #8440
> Filter languages for related pages

- templates/legal/data-privacy/snap-store.md
- Update `/legal/data-privacy/snap-store`
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy/snap-store
- Check page against [copy doc](https://docs.google.com/document/d/1rEyCOZWoKKJRPIg5jhANfWVibZJ9QVfqj4MkeNIJp4M/edit#)
Fixes #8444
> Copy update - Snap store data privacy page

- templates/telco/index.html
- Rebuild /telco page 
- View the site locally in your web browser at: http://0.0.0.0:8001/telco
- Check the page against the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit)
- Check all the links link to correct pages
- Check design
Fixes [#3231](https://github.com/canonical-web-and-design/web-squad/issues/3231)
> Rebuild /telco

- templates/openstack/install.html
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)
Fixes #8511
> Update /openstack/install for beta microstack

- Dockerfile
> Lock dependencies

- templates/managed/kafka.html
- templates/shared/pricing/_managed-pricing.html
- Copy update `/managed/kafka`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/kafka
- Check page against [copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#heading=h.c6wjbvvp8mcm) 
Fixes #8421
> Copy update /managed/kafka page

- templates/telco/index.html
- Add link to datasheet under "The entire NFV stack" section, and fix subheading sizes.
- Increase size of micro cloud image
- Split bullet point list into two columns in "Best NFV performance" section
- Add "Get in touch" button
- View the site locally in your web browser at: http://0.0.0.0:8001/telco
- Check changes mentioned above against [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#)
Fixes [#3343](https://github.com/canonical-web-and-design/web-squad/issues/3343)
> Update /telco page 

- templates/server/index.html
- Copy docs [updates](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#)
- Click on the demo https://ubuntu-com-8546.demos.haus/server and make sure the copy updates are correct.
Fixes #8501
> Update 'What's new' section on /server

- navigation.yaml
Check you see the navigation item for Server on the raspberry-pi section.
> Add Raspberry Pi server to navigation.yaml

- navigation.yaml
- static/sass/styles.scss
- templates/raspberry-pi/desktop.html
Create Raspberry Pi desktop page
- For some reason there is no demo link.. so fetch changes and `dotrun`
- Go to `/raspberry-pi/desktop`
- Compare to: https://user-images.githubusercontent.com/42238722/96727778-59b06580-13ab-11eb-95f5-8a27d5a55aa3.png
Fixes #8473
> Raspberry pi desktop

- templates/robotics/what-is-ros.html
- templates/shared/contextual_footers/_iot_newsletter_signup.html
- Copy update on `/robotics/what-is-ros`
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/what-is-ros
- Check the page against [copy doc](https://docs.google.com/document/d/1yX2Ikcn1fgIKX3el8fKWQt7SGxSwY633TfW5V1lwUuc/edit?ts=5f7af517#heading=h.vbzgtki4500k) and [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/8429)
Fixes #8429
> Copy update /what-is-ros

- navigation.yaml
- templates/managed/cassandra.html
- templates/managed/index.html
- templates/managed/kafka.html
- templates/shared/forms/interactive/managed-cassandra.html
- Build new `/managed/cassandra` page
- Add to secondary nav 
- Add contact form at `shared/forms/interactive/managed-cassandra`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/cassandra
- Check page against [copy doc](https://docs.google.com/document/d/1iYMH1ISY4uDtr3ZzH0f_hnEzvqaeufO43z__cMxs0vQ/edit?ts=5f71f2cb#heading=h.xj070le8yswb)
- Check modal form against [form doc](https://docs.google.com/document/d/11QCRbr4aqRGEYXhU-9ob3Y4tYYLhrubJWimiaYFRVco/edit#)
Fixes [#3360](https://github.com/canonical-web-and-design/web-squad/issues/3360)
> Build /managed/cassandra

- templates/advantage/index.html
- templates/shared/_call-sales-long.html
- Update list of phone numbers
- Also fixes the list in an /advantage error state
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us
- Compare to the numbers in this [copy doc](https://docs.google.com/document/d/1LK7lJlhke8hKesVSglHxNSfUCDw0bfddzM4vezeXvBQ/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3377
> Update list of phone numbers

- static/sass/styles.scss
- templates/takeovers/_cassandra-webinar-takeover.html
- templates/takeovers/_fips_certification_cis_compliance.html
- templates/takeovers/_kubernetes-enterprise-whitepaper-takeover.html
- templates/takeovers/_redhat-openstack.html
- templates/takeovers/_template.html
- Change image header on mobile for some of the takeovers. 
- Go to https://ubuntu-com-8520.demos.haus
- Look at the takeover does the image header look good on large, medium and small? Some of the take over use the stacked image design: https://vanillaframework.io/docs/patterns/heading-icon#stacked
Fixes #8509
> Change takeover image on mobile

- templates/support/index.html
- Rebuild `/support` page
- Check page against [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit#)
Fixes [#3365](https://github.com/canonical-web-and-design/web-squad/issues/3365)
> Copy update on /support

- templates/index.html
Removed Managed risk takeover
- Check the takeover is down
Fixes #
> Removed Managed risk takeover

- templates/smartstart/index.html
- Fix [design request](https://github.com/canonical-web-and-design/ubuntu.com/pull/8636#issuecomment-720400024)
- View the site locally in your web browser at: http://0.0.0.0:8001/smartstart
- Check quote is in separate section as requested [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/8636#issuecomment-720400024)
[PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/8636#issuecomment-720400024)
> Move quote to separate section

- templates/pricing/devices.html
- templates/pricing/shared/_enablement-strip.html
- templates/shared/pricing/_smart-start-prices.html
- Copy update on /pricing/devices
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices
- Check page against [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
Fixes [#3388](https://github.com/canonical-web-and-design/web-squad/issues/3388)
> Copy update on /pricing/devices

- static/files/sitemap.xml
- Updated the sitemap.xml
- View the site locally in your web browser at: http://0.0.0.0:8001/sitemap.xml
- paste the sitemap xml in a tool like https://xmlgrid.net/sitemapView.html to validay
> Updated sitemap

- templates/managed/index.html
- Update link and logos on `/managed`
- Check page against [copy doc](https://docs.google.com/document/d/1UUutFXnvld18JAstywiZ7v-eD4ft3zmcI3-ZVPL2V-o/edit?ts=5faaa87a#)
Fixes [#3451](https://github.com/canonical-web-and-design/web-squad/issues/3451)
> Copy update on /managed

- templates/cloud/index.html
- Update CTA as requested on copy doc
- Fix `u-hide--small` classes on images
- View the site locally in your web browser at: http://0.0.0.0:8001/cloud
- Check CTA now reads 'Optimise your cloud costs' and is correct link as per [copy doc](https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit#)
- Check images aren't visible on small screens
Fixes [#8747](https://github.com/canonical-web-and-design/ubuntu.com/issues/8747)
> Copy update on /cloud

- templates/masters-conference/index.html
- Add new Ubuntu Masters 4 section to `/masters-conference`
- Check against [copy doc](https://docs.google.com/document/d/1Z63eMCe9o4Onk2ezPFLPDTbI-uJezAOzI-aSpXmZ5lc/edit#)
Fixes [#3453](https://github.com/canonical-web-and-design/web-squad/issues/3453)
> Copy update on /masters-conference

- tests/test_views.py
- webapp/views.py
> Sum all contract allowances regardless of metric

- templates/managed/kafka.html
- Update meta title on /managed/kafka
Fixes #8720
> Update Kafka meta title

- templates/kubernetes/docs/ldap.md
added a flag to snap install for keystone (snap isn't promoted yet)
> K8sDocs Update ldap.md

- templates/kubernetes/what-is-kubernetes.html
- update the copy on what is kubernetes as per the copydoc
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/what-is-kubernetes
Fixes #8753
> Update what is kubernetes copy

- templates/core/index.html
- Update download link on /core
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit?ts=5fb25771#)
Fixes #8800 and https://github.com/canonical-web-and-design/web-squad/issues/3464
> Update download link on /core

- templates/kubeflow/index.html
- See that the banner buttons and the bottom button's have been updated
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1mJq8PxH8FVRVF9i1Xzh0f6M73eyjqZE4NaKYHRcRAKM/edit?ts=5fb64285#)
Fixes #8790
> Update /kubeflow ctas

- templates/cube/index.html
- webapp/app.py
- webapp/views.py
Create home view and simple template for cube.
- dotrun
- browse http://0.0.0.0:8001/cube and make sure it renders.
Fixes #
> [Cube] - Initial view

- templates/engage/_article-card.html
- templates/engage/base.html
- templates/engage/index.html
- tests/cassettes/TestRoutes.test_active_page_returns_200.yaml
- tests/cassettes/TestRoutes.test_active_page_returns_adds_no_meta_with_preview_flag.yaml
- tests/cassettes/TestRoutes.test_engage_index_with_preview_flag_sees_inactive_pages.yaml
- tests/cassettes/TestRoutes.test_engage_index_without_preview_flag_cannot_see_inactive_page.yaml
- tests/cassettes/TestRoutes.test_inactive_page_returns_302.yaml
- tests/cassettes/TestRoutes.test_inactive_page_returns_page_with_preview_flag.yaml
- tests/test_routes.py
- webapp/views.py
These are the rules:
1. If you go on `/engage`. By default you will see no inactive pages. To see the inactive pages you have to go to `/engage?preview`. This will set the meta `robot` to `noindex`.
2. If you go to an inactive engage page you will be redirected to its discourse page. If you can visit the page if you add the flag `?preview`. This will set the meta `robot` of the page to `nofollow`.
3. If you are `/engage?preview` all inactive pages will have their URL changed to `<URL>?preview`
For the sake of the QA I made `/engage/it/deployment-azienda-manuale` `active = false`. It will not affect prod in any way because the feature is not live yet.
1. Go to https://ubuntu-com-8761.demos.haus/engage
You will not see **Cinque strategie per accelerare l'implementazione di Kubernetes …
> Add preview feature for inactive engage pages

- templates/robotics/base_robotics.html
- templates/shared/forms/interactive/robotics_ros.html
- Create campaign ROS contact us modal based on this [brief](https://docs.google.com/document/d/1YU2CBh2pDtT6guLqWBAcPpMAMt57vQdQlT0eQA4gKu4/edit)
- *Note, this form is temporary, so I left the older form on the site*
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics#get-in-touch
- Refer to the [copy doc](https://docs.google.com/document/d/1vDbdFBrG6tWDUb5z5ltny_7d-GZU78wS8K7Nru2BSj8/edit#)
Fixes #8807
> Create campaign ROS contact us modal

- templates/masters-conference/index.html
- some text updates to buttons, new section subheading (the date) + column layout, thanks!
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1Z63eMCe9o4Onk2ezPFLPDTbI-uJezAOzI-aSpXmZ5lc/edit?ts=5fbe3c20#heading=h.3n9txn55nx4l)
Fixes #8821
> Update Masters 4 section of /masters-conference

- webapp/security/schemas.py
- Change NoticeSchema to allow LSNs too.
> Allow LSNs

- static/sass/_pattern_active-reveal.scss
- static/sass/styles.scss
- templates/security/esm.html
- templates/security/thank-you.html
- templates/shared/forms/interactive/esm.html
Add ESM contact form
Add ESM product title to thank you page
- View the site locally in your web browser at: http://0.0.0.0:8001/security/esm#get-in-touch
- Check the form matches [the copy doc](https://docs.google.com/document/d/1FzITFuuU3CU28bhLuA4hbrAVrJDj2fyiAxM9tcVirhg/edit#)
- Submit the form and see that it hits https://ubuntu.com/security/thank-you?product=esm
- Which when you jump on back to this branch http://0.0.0.0:8001/security/thank-you?product=esm see it looks ok 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8823
> Add ESM contact form

- templates/shared/pricing/_ua-for-infrastructure.html
- Check changes against the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit?ts=5fc6261a#) and accept correct changes
> Change storage from 48 to 72

- templates/shared/pricing/_openstack-kubernetes-lma.html
- Check changes against the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit?ts=5fc6261a#) and accept correct changes
> Updated price to 5475

- navigation.yaml
- templates/azure/fips.html
- Create Azure Fips page. Check against this spec: https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit#
Go to https://ubuntu-com-8841.demos.haus/azure/fips check page against spec.
Fixes #8771
> Build Azure Fips page

- templates/shared/forms/interactive/azure.html
- Update js form for Azure pages. The form follows this specs: https://docs.google.com/document/d/1GbPw_OOy84ez5B3EFqH_P26nV85qo3-iv1kHE2PjSEc/edit
- Go to https://ubuntu-com-8844.demos.haus/azure/fips#get-in-touch check the form against the spec
Fixes #8772
> Update Azure js contact form

- templates/robotics/what-is-ros.html
- Move button up a strip on /robotics/what-is-ros
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/what-is-ros
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1yX2Ikcn1fgIKX3el8fKWQt7SGxSwY633TfW5V1lwUuc/edit?ts=5fc6819b#)
Fixes [#3538](https://github.com/canonical-web-and-design/web-squad/issues/3538)
> Move button up a strip

- konf/site.yaml
**This PR can only be merged after https://github.com/canonical-web-and-design/konf/pull/4**
- Ingress rule for security API
- Follow the QA steps in the Konf repo: https://github.com/canonical-web-and-design/konf/pull/4
> Security API ingress rule

- HACKING.md
- konf/site.yaml
- templates/cube/microcerts.html
- webapp/api/cube.py
- webapp/views.py
List the courses available on the edex platform on the microcerts page.
- follow the instructions in `HACKING.MD` to work in CUBE
- dotrun
- go to `/cube/microcerts`, login and see a list of courses
> List available courses on microcerts page

- konf/site.yaml
- Regex for proxy locations
- Check staging.ubuntu.com is working as usual, I deployed this config there to check.
> Regex for proxy locations

- templates/advantage/_ubuntu_version_select.html
- Update LTS description as per the [copydoc](https://docs.google.com/document/d/10ldSK8T0Tc-QK7OVZmbs_p-rOH8ujphZGzhfO0QaOi8/edit) 
- View the site in your web browser at: https://ubuntu-com-8912.demos.haus/advantage/subscribe
- Make sure it follows the copydoc
Fixes [#3586](https://github.com/canonical-web-and-design/web-squad/issues/3586)
> Update LTS description

- navigation.yaml
- templates/aws/fips.html
- Add AWS Fips page following this spec: https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit#
- Go to https://ubuntu-com-8908.demos.haus/aws/fips compare to the spec.
Fixes #8851
> Add AWS Fips page

- templates/aws/base_aws.html
- templates/azure/base_azure.html
- templates/shared/forms/interactive/aws.html
- templates/shared/forms/interactive/azure.html
- Edit AWS js contact form following https://docs.google.com/document/d/1YyCKB1rTnjxqgdECPJczHBHGGZEjQvkLOJkaRtCyFpU/edit#heading=h.ej2dyxv6np5f
- Go to: https://ubuntu-com-8909.demos.haus/aws#get-in-touch compare against file
Fixes #8850
> Edit AWS js contact form

- templates/managed/index.html
Fix stuckstack link
- Check https://ubuntu-com-8923.demos.haus/managed
- Check that the link goes to the correct engage page `/engage/stuckstack-ebook`
Fixes #8921
> Fix stuckstack link

- templates/aws/pro.html
- Change /aws/pro page following https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit?ts=5fc8eff1#
Makes two changes to the _What’s in Ubuntu Pro?_ section.
Adds the _Compliance made easy_ section.
- https://ubuntu-com-8924.demos.haus/aws/pro compare with file
Fixes #3582
> Update AWS pro page

- templates/advantage/_ubuntu_version_select.html
From this 
To This 
- View the site at: https://ubuntu-com-8915.demos.haus/advantage/subscribe
> Remove 'service' to prevent wrapping on large screens

- templates/sitemap.xml
- webapp/app.py
- webapp/security/views.py
- Create index notice sitemap.
- Go to https://ubuntu-com-8943.demos.haus/security/notices/sitemap-0.xml
Fixes #8884
> Create offset notice sitemap

- templates/sitemap_index.xml
- templates/sitemap_index_template.xml
- webapp/app.py
- webapp/security/views.py
- Create notice sitemap.
- Go to https://ubuntu-com-8944.demos.haus/security/notices/sitemap.xml
Fixes #8886
> Create notices sitemap

- webapp/app.py
- webapp/security/views.py
- Create offset CVE sitemap.
Fixes #8885
> Create offset CVE sitemap

- templates/sitemap_index.xml
- webapp/app.py
- webapp/security/views.py
- Create CVE sitemap
Fixes #8885
> Create CVE sitemap

- templates/security/esm.html
- Update `/security/esm` with visual changes suggested 
- View demo at: https://ubuntu-com-8938.demos.haus/security/esm
- Check against design suggested [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/8933#issue-767775011) 
Fixes #8933
> Update esm hero with small visual changes

- templates/sitemap.xml
> Fix CVE sitemap

- webapp/views.py
Fix thank you pages when language is empty
Test:
https://ubuntu-com-8949.demos.haus/engage/azure-ubuntu-pro-fips-whitepaper/thank-you
https://ubuntu-com-8949.demos.haus/engage/451-research-microk8s-high-availability/thank-you
> Fix thank you pages when language is empty

- templates/cube/microcerts.html
- webapp/cube/api.py
- webapp/cube/mappings/courses.yaml
- webapp/cube/views.py
Fetch the status for each course from the edx API.
- dotrun
- go to `cube//microcerts`
- check all courses have the correct status defined.
> Show status of each microcert for user

- webapp/security/views.py
> Fix sitemap CVE url

- webapp/cube/views.py
This CUBE edx API will live under a sub-domain of ubuntu.com but requests to it still need proxying, so we configure the session manually to avoid it loading the configurations from environment variables, since those default to not proxy requests for ubuntu.com sub -domains and that is  the intended behaviour for most of our apps.
- make sure `https://ubuntu-com-8984.demos.haus/cube/microcerts` loads.
> Cube EDX API proxy settings

- webapp/cube/views.py
Get the user enrollments and use them to fix the logic that calculates the status of the course for the authenticated user.
When you are unenrolled from a course you can still have a grade in the system for it, so we need an extra check.
- dotrun
- go to `/cube/microcerts`
- make sure your courses statuses look correct
> Get user enrollments

- static/js/src/chart-data.js
- Fix Prettier
- Do checks pass?
> Add missing commas

- webapp/app.py
Reverts canonical-web-and-design/ubuntu.com#8994
> Revert "Remove the engage takeover on the homepage"

- templates/download/server/choose.html
- templates/download/server/step1.html
- templates/download/server/step2.html
- Updated the order to Multipass -> Manual -> MAAS
- Move the CTA button below the option buttons
- Update the content across the three pages
- Added anchors to the manual download page
- Go to the demo and go to /download/server.
- Check the content matches the [copy doc](https://docs.google.com/document/d/12kr3JvN3ALMdr5IPOheMwOaf-ygvEulFo5D7x-0ag0k/edit)
- Click through the steps checking the content
- Ensure the download works
- Ensure all navigation works
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3608
> Update the server download journey

- templates/azure/pro.html
- Update copy on /azure/pro
- 
- Compary to the [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit?ts=5fd78370#heading=h.d9su6619fb5y)
Fixes [#3591](https://github.com/canonical-web-and-design/web-squad/issues/3591)
> Update copy on /azure/pro

- templates/wsl/index.html
- Update copy on /wsl page
- View the site locally in your web browser at: http://0.0.0.0:8001/wsl
- Compare to the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#heading=h.aotv6bdab26f)
Fixes [#3609](https://github.com/canonical-web-and-design/web-squad/issues/3609)
> Update copy on /wsl

- templates/aws/pro.html
- Fix copy and layout on /aws/pro
- Compare to the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit?ts=5fd783a0#)
Fixes [#3592](https://github.com/canonical-web-and-design/web-squad/issues/3592)
> Fix copy and layout on /aws/pro

- templates/financial-services/index.html
- Update finacial services page following: https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit#
- Go to https://ubuntu-com-9024.demos.haus/financial-services check against the docs
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3612
> Update financial services page

- static/js/src/scratch.js
- templates/internet-of-things/edgex.html
- templates/security/notices/lsn.html
- templates/security/notices/usn.html
- webapp/security/models.py
- webapp/security/views.py
- Create LSN template compare to https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#heading=h.bbi2iqqwhp35 to confirm that everything is correct
1. Have the database with an LSN
2. Go to your ubuntu.com repo and run:
```bash
docker-compose down # this resets your databse
docker-compose up -d # NOTE: do not run `dotrun`
docker exec -i db psql -U postgres -d postgres < ~/Downloads/backup.sql # replace with correct path
dotrun # run site
```
3. Browse to http://0.0.0.0:8001/security/notices/LSN-0000-0 and compare to the image in the docs
Fixes #9005
> Create LSN template

- webapp/app.py
> Disable homepage takeovers again

- HACKING.md
- konf/site.yaml
- templates/cube/microcerts.html
- webapp/cube/api.py
- webapp/cube/mappings/courses.yaml
- webapp/cube/views.py
Get a list of assertions from badgr to know what badges a certain user has and use those assertions to work out if I user has passed courses or is already CUBE certified.
- Pair with me to QA
> Get list of assertions for user from Badgr

- templates/security/cve/cve.html
Index all CVEs, regardless of status
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9003
Hard to QA (we'd have to populate the CVEs in the demo) - maybe a code review is good enough?
> Index all CVEs, regardless of status

- webapp/advantage.py
- Added yearly and active filters to the subscription call to make sure we are not looking at cancelled subscriptions
Not too sure how to QA this honestly. The ticket mentions cancelling an active subscription on the UA shop but I don't think we can do this yet via the web interface? (@sowasred2012 Is that right?) So I guess just go to the link, log in and try to make a purchase
- https://ubuntu-com-9015.demos.haus/advantage/subscribe?test_backend=true
Fixes #9004
> Update subscription call to use filters

- templates/security/certifications.html
- Copy update on `/security/certifications`
- View page at: https://ubuntu-com-9087.demos.haus/security/certifications
- Check updates against [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit)
Fixes #9082
> Copy update on /security/certifications

- templates/security/oval.html
- Copy update for /security/oval
- View page at: https://ubuntu-com-9099.demos.haus/security/oval
- Check changes agains [copydoc](https://docs.google.com/document/d/1hBG6NIfBIrixIV753fsOiEymmeuFIF-KOhiDkV68PRY/edit#)
Fixes #9086
> Copy update for /security/oval

- templates/kubernetes/docs/1.18/upgrading.md
- templates/kubernetes/docs/1.19/upgrading.md
- templates/kubernetes/docs/1.20/upgrading.md
- templates/kubernetes/docs/install-local.md
- templates/kubernetes/docs/upgrade-notes.md
- templates/kubernetes/docs/upgrading.md
Updates instructions for upgrading etcd
Fixes this lp bug - https://bugs.launchpad.net/charm-etcd/+bug/1913227
https://bugs.launchpad.net/charm-etcd/+bug/1913227
> K8sdocs updates for etcd issue

- navigation.yaml
- static/sass/_pattern_strip.scss
- templates/core/stories.html
- Build new page at `/core/stories`
- NOTE - waiting on correct svgs and design review - padding on some images means alignemnt is slightly off
- View page at: https://ubuntu-com-9110.demos.haus/core/stories
- Check against [copy doc](https://docs.google.com/document/d/1mXnYnpaCJznDLtYn9Q74aVeEI3iFxVOMzF0pdL7wdu0/edit#heading=h.6hx4umk9oda9)
Fixes [#3667](https://github.com/canonical-web-and-design/web-squad/issues/3667)
> Build new /stories page for core

- navigation.yaml
- templates/core/features/index.html
- Build new page at `/core/features`
- View the page at: https://ubuntu-com-9112.demos.haus/core/features
- Check against [copydoc](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit#heading=h.2rlj58ccsw9y)
Fixes [#3666](https://github.com/canonical-web-and-design/web-squad/issues/3666)
> Build new features page for /core

- templates/templates/navigation-developer-h.html
- Added Flutter to the "Develop on Ubuntu" list
Fixes #
> Added Flutter to the "Develop on Ubuntu" list

- navigation.yaml
- templates/core/features/index.html
- templates/core/features/secure-boot.html
- Build new `/core/features/secure-boot` page
- View page at: https://ubuntu-com-9119.demos.haus/core/features/secure-boot
- Compare against [copy doc](https://docs.google.com/document/d/1ltH7T2boIJ7VcUni4Kmc0XGlmmxWAf5u82LEwkEGP24/edit#)
- Waiting to merge `/core/features` first 
Fixes [#3640](https://github.com/canonical-web-and-design/web-squad/issues/3640)
> Build new /core/features/secure-boot page

- navigation.yaml
- templates/core/features/full-disk-encryption.html
- Build /core/features/full-disk-encryption page
- View page at: https://ubuntu-com-9127.demos.haus/core/features/full-disk-encryption
- Check against[ copydoc](https://docs.google.com/document/d/1kekmNSjenq31imR4_HaJgkq51SptBjnIjVIpuj1mmX0/edit)
Fixes [#3641](https://github.com/canonical-web-and-design/web-squad/issues/3641)
> Build /core/features/full-disk-encryption page

- templates/ai/what-is-kubeflow.html
Fix typos in the what is kubeflow page.
> Small typos in the what is kubeflow page

- templates/openstack/features.html
Removed the external link class from the blog link on OpenStack features page.
> Removed external from blog like

- Dockerfile
- navigation.yaml
- templates/core/features/recovery.html
- Build `/core/features/recovery` page
- View page at: https://ubuntu-com-9129.demos.haus/core/features/recovery
- Check against [copydoc](https://docs.google.com/document/d/1VpsLUf-cODyuKe7xqxW27cDIGorQHgWd95tFqMnClsg/edit#)
Fixes [#3642](https://github.com/canonical-web-and-design/web-squad/issues/3642)
> Build /core/features/recovery page

- navigation.yaml
- templates/core/features/index.html
- templates/core/features/ota-updates.html
- Build new page at `/core/features/ota-updates`
- Add link to `/core/features`
- View page at: https://ubuntu-com-9162.demos.haus/core/features/ota-updates
- Check page against [copy doc](https://docs.google.com/document/d/1CftibGyQdcto7E-tUnpwZOXMJsvOegAqk0FyoL3kQEA/edit#heading=h.53wrd6jzb1es)
- Check link to OTA on `/core/features`
Fixes #9123
> Build OTA updates page

- static/js/src/ua-payment-modal.js
- Fixed a bug where the backend would be called with an outdated address
- https://ubuntu-com-9222.demos.haus/advantage/subscribe?test_backend=true
- log in
- Make a purchase
- Make another purchase and try to replace the address somehow
- Watch the request logs
Fixes #9194
> Update customerInfo object before API call

- templates/security/notices/lsn.html
- webapp/security/views.py
- Change the layout for the LSN a bit.
- Have a database.
- Browse to http://0.0.0.0:8001/security/notices/LSN-0074-2 no errors show up, page looks ok.
> Change LSN layout

- templates/templates/navigation-enterprise-h.html
- Update links in Enterprise menu 
- View page at: https://ubuntu-com-9238.demos.haus
- Select Enterprise drop down from navigation
- Check links aganst [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit?ts=602658ab#)
Fixes #9236
> Copy update - Enterprise menu

- templates/security/certifications.html
- Copy update `/security/certifications`
- View page at: https://ubuntu-com-9237.demos.haus/security/certifications
- Check page against[ copy doc ](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit?ts=6022deeb#)
Fixes #9235
> Copy update /security/certifications

- templates/security/cve/cve.html
- webapp/security/alembic/versions/3e0a3f15abb9_add_cve_mitigation_column.py
- webapp/security/models.py
- webapp/security/schemas.py
- webapp/security/views.py
- Add mitigation field to CVE.
- Have a database
- Fetch changes and `dotrun`
- Go to http://0.0.0.0:8001/security/CVE-2020-28374 
- You should get a 200 and see the mitigation section
Fixes #9017
> Add mitigation field for CVE

- navigation.yaml
- static/js/src/advantage/contracts-api.js
- static/js/src/ua-payment-methods.js
- static/sass/styles.scss
- templates/advantage/payment-methods/_card-logo.html
- templates/advantage/payment-methods/index.html
- webapp/advantage.py
- webapp/app.py
- webapp/views.py
- webpack.config.entry.js
- added the /advantage/payment-methods page
- added an endpoint for updating payment method
- go here https://ubuntu-com-9248.demos.haus/advantage/payment-methods?test_backend=true
- login
- Verify that it display your default payment method (if you don't have one, go [here](https://ubuntu-com-9248.demos.haus/advantage/subscribe?test_backend=true)  and make a purchase with a [dummy card](https://stripe.com/docs/testing) )
- Change it to another one (4242 4242 4242 424242.... or 5555 5555 5555 444444...)
- Verify that it updated correctly
Fixes #3792
> Build payment method management

- webapp/app.py
- webapp/views.py
Fixes #7592
QA
--
Go to `/templates/sdfgsdfg` on the demo. Check you see a 404, not a 500. Go to `/templates/navigation-developer-h`, check it loads.
> Ensure /templates/dfgdfg 404s

- webapp/app.py
Swap topic index id
- View the site locally in your web browser at: https://ubuntu-com-9273.demos.haus
- Check new topic index https://discourse.ubuntu.com/t/about-the-openstack-category/20990
Fixes #9247
> Change OpenStack docs index post

- tests/cassettes/TestCube.test_microcerts_authenticated.yaml
- webapp/cube/content/cube.yaml
Update mappings to use the prod issuer IDs
Use the demo to make sure /cube/microcerts is still working
> CUBE: Update mappings to use the prod issuer IDs

- konf/site.yaml
Deploy a service in k8s dedicated to serve CUBE requests.
- `konf production konf/site.yaml` and check the output looks good
- repeat for `konf staging konf/site.yaml`
- try to apply the config in microk8s and see the service deployed.
> CUBE: Split into it's own k8s service

- webapp/security/views.py
- Fix error, because is_hidden is not defaulting to false correctly.
> Add is_hidden default to false

- webapp/advantage.py
- webapp/app.py
- webapp/views.py
- Add cancel subscription.
- `DELETE /advantage/subscribe`:
```json
{
"account_id": "account_id",
"product_listings": [
"product_listing_id_1", "product_listing_id_2",
],
"previous_purchase_id": "previous_purchase_id",
}
```
Not easy to test until we have a form that allows us to buy monthly products.
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/3793
> Add cancel subscription

- templates/ai/index.html
- Updated copy in subheading CTA's and one in the body
- View the site locally in your web browser at: http://0.0.0.0:8001/ai
- Please compare the changes against the [copy doc](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit?ts=5fb6b19b#) and accept corrected comments
Fixes [#3840](https://github.com/canonical-web-and-design/web-squad/issues/3840)
> Copy update - /ai

- templates/aws/fips.html
- Copy update on `/aws/fips`
- Check against the [copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit?ts=6037c15e#). Comments left in copy doc to make review easier (apart from in the hero), so please resolve as you review
Fixes #9319
> Copy update on /aws/fips

- webapp/advantage.py
- webapp/views.py
- Add auto-renewal endpoint:
`POST /advantage/set-auto-renewal`
```
{
"should_auto_renew": true/false
}
```
> Add auto renewal endpoint

- templates/financial-services/index.html
- Update hero, 'Drive business agility' and 'Software strategy acceleration' sections
- Check page against new [design](https://user-images.githubusercontent.com/36884067/109687240-f5808800-7b7a-11eb-88c2-39032f7be79b.jpg)
Fixes #9221
> Update /financial-services page design

- static/sass/styles.scss
- templates/advantage/subscribe/index.html
This branch contains work from https://github.com/canonical-web-and-design/ubuntu.com/pull/9055 and adds [CSS smooth scroll behaviour](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior).
> Test smooth scrolling

- templates/security/notices/lsn.html
- templates/security/notices/usn.html
- webapp/security/views.py
- Update LSN page template
- Have a database
- Go to http://0.0.0.0:8001/security/notices/LSN-0074-2 :
- loads without errors
- you will not find Support Information anymore
- versions will be listed in Software Description sections after the name
- Go to http://0.0.0.0:8001/security/notices/USN-4342-1 :
- loads without errors
Fixes #9358
> Update LSN template
