navigation.yaml
- add the core install page for the pi to the nav
- View the site locally in your web browser at: [/download/iot/raspberry-pi-2-3-core](http://0.0.0.0:8001/download/iot/raspberry-pi-2-3-core)
- See that the page has a secondary nav
=> Add raspberry pi 2 or 3 core page to nav

templates/kubernetes/docs/aws-integration.md, templates/kubernetes/docs/certs-and-trust.md, templates/kubernetes/docs/encryption-at-rest.md, templates/kubernetes/docs/gcp-integration.md, templates/kubernetes/docs/gpu-workers.md, templates/kubernetes/docs/hacluster.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/operations.md, templates/kubernetes/docs/using-vault.md
The CDK charms are now published as `charmed-kubernetes` in the charm store. This updates the docs to deploy from that bundle rather than canonical-kubernetes.
=> CDK charm changes

templates/download/alternative-downloads.html
Add lts to alt server installer link
- View the site locally in your web browser at: [/download/alternative-downloads](http://0.0.0.0:8001/download/alternative-downloads)
- see that the alt server links read better
=> Add lts to alt server installer link

static/js/chartData.js, templates/about/release-cycle.html
- removed spaces in dates for desktop/server
- added esm for 20.04 lts
- View the site locally in your web browser at: [/about/release-cycle](http://0.0.0.0:8001/about/release-cycle)
- see that esm appears in the 'Long term support and interim releases' chart and that esm is on the 20.04 bar for 'Ubuntu kernel release cycle'
Fixes #4985
=> Add esm to 20.04 and fix whitespace date bug

templates/index.html
Reinstall all hidden takeovers
- Refresh the homepage a few times and check different takeovers load
=> Reinstall all hidden takeovers

templates/openstack/storage.html
- Updated link in FAQ block
- Removed CTA that was to that same link
- View the site locally in your web browser at: [/openstack/storage](http://0.0.0.0:8001/openstack/storage)
- See that there is just the faq box and it links to a real page
- Note, the copy doc is based on the UA-I release
Fixes #4993
=> Update blog link on /openstack/storage page

templates/index.html
- Removed the 451 financial services whitepaper takeover from rotation
- Removed the german k8s webinar takeover from rotation
- Updated the [master content tracker](https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit?ts=5cc05f70#gid=564832475)
- Left the files on the site for now
- Reload the page until your are satisfied you do not see the takeovers
Fixes #4991
=> Remove old takeovers from rotation

templates/templates/_navigation-community-h.html
- Fixed link to locos to use /teams
- Removed link to google+
- Updated the [copy doc](https://docs.google.com/document/d/1TgsBJdGgsP4KrGiz5kU5QYkdGSlKqhAVnZGnCJgshYY/edit)
- View the site locally in your web browser at: [http://0.0.0.0:8001/#community](http://0.0.0.0:8001/#community)
- See that the links to locos go to the teams
- See there is no Google+ link
Fixes #3927
=> Update community dropdown

templates/download/iot/index.html
Add matrix to the Supported platforms section on /download/iot
- View the site locally in your web browser at: [/download/iot](http://0.0.0.0:8001/download/iot)
- See that the section looks good
Fixes #4974
=> Add matrix to supported on /download/iot

templates/shared/_insights_news_strip.html, templates/shared/contextual_footers/_cloud_further_reading.html, templates/shared/contextual_footers/_desktop_further_reading.html, templates/shared/contextual_footers/_further_reading.html, templates/shared/contextual_footers/_iot_further_reading.html, templates/shared/contextual_footers/_security_further_reading.html, templates/shared/contextual_footers/_telco_further_reading.html
Exclude cn lang blog posts from the feeds across the site.
- Check that homepage has no CN posts
=> Exclude cn lang blog posts

templates/engage/openstack-security-webinar.html
Add openstack security webinar landing page
- View the site locally in your web browser at: [/engage/openstack-security-webinar](http://0.0.0.0:8001/engage/openstack-security-webinar)
- Make sure it matches the [brief](https://docs.google.com/document/d/1Qg3sgDrvH9w_sgJpb2fp5lyOA5R-xhGZM3aKcyuQT68/edit?ts=5cbee163#heading=h.1v2sl7iz5yrb)
Fixes [#1100](https://github.com/canonical-web-and-design/web-squad/issues/1100)
=> Add openstack security webinar landing page

templates/engage/openstack-security-whitepaper.html
Add openstack security whitepaper page
- View the site locally in your web browser at: [/engage/openstack-security-whitepaper](http://0.0.0.0:8001/engage/openstack-security-whitepaper)
- Make sure complies with the [brief](https://docs.google.com/document/d/1Qg3sgDrvH9w_sgJpb2fp5lyOA5R-xhGZM3aKcyuQT68/edit?ts=5cbee163#)
Fixes [#1099](https://github.com/canonical-web-and-design/web-squad/issues/1099)
=> Add openstack security whitepaper page

templates/index.html, templates/takeovers/_openstack_security_takeover.html, templates/takeovers/_openstack_takeover.html
Create a new 'OpenStack Security' takeover
- Open [http://0.0.0.0:8001/](http://0.0.0.0:8001/) and refresh the page until the OpenStack takeover comes up
- Make sure [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4938) is ok
- Make sure is compliant with the [brief](https://docs.google.com/document/d/1Qg3sgDrvH9w_sgJpb2fp5lyOA5R-xhGZM3aKcyuQT68/edit#)
Fixes [#4940](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/4940)
=> Create new openstack security takeover page

templates/download/server/power.html
- Removed point releases for 14.04 and 16.04 netbook links
- Updated the [copy doc](https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit#)
- View the site locally in your web browser at: [/download/server/power](http://0.0.0.0:8001/download/server/power)
- See that the 14.04 and 16.04 netbook links go to a page that has the generic series netbook link
Fixes #3746
=> Fixed power netboot image links

templates/download/flavours.html, templates/download/server/power.html
- Updated link to dervitatives to flavors
- Updated the [copy doc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit)
- View the site locally in your web browser at: [/download/flavours](http://0.0.0.0:8001/download/flavours)
- See that the link has been updated
Fixes #3226
=> Update link to wiki in /download/flavours page

templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md
Some links updated to reference the correct version of the kubernetes bundle in
install-manual.md
release-notes.md
Merge if happy!
=> Fix Kubernetes bundle refs

package.json, scripts/get-mirrors-rss, webapp/views.py
Fixes https://github.com/canonical-web-and-design/base-squad/issues/459
Download mirror list at build time
- `./run`
- make sure new directory created with the list of mirrors: `$PROJECT/etc/ubuntu-mirrors-rss.xml`
- If you run again, the script **shouldn't** download again the mirrors
- `./run clean`
- Make sure `$PROJECT/etc/` is deleted
=> Download mirror list on build

templates/download/iot/index.html
- Updated look of the lead Raspberry Pi strip and changed the board
- View the site locally in your web browser at: [/download/iot](http://0.0.0.0:8001/download/iot)
- See that the strip looks like #5004
Fixes #5003, #5004
=> Update raspberry pi strip on /download/iot

entrypoint, redirects.yaml, requirements.txt, webapp/settings.py, webapp/testrunner.py
- uses sync workers instead of gevent (https://docs.gunicorn.org/en/stable/design.html)
- upgrades to Django 2.2 LTS (https://www.djangoproject.com/weblog/2019/apr/01/django-22-released/)
- removes unsupported `django-unslashed` middleware
Fixes https://github.com/canonical-web-and-design/base-squad/issues/454
=> Update to Django2

templates/shared/forms/interactive/_kubeflow.html, templates/shared/forms/interactive/_pricing-infra.html
- Add power and z to kubeflow contact-us
- Add other box drop-down to pricing/infra contact-us
- [http://0.0.0.0:8001/](http://0.0.0.0:8001/ai/install#get-in-touch)
- [http://0.0.0.0:8001/ai/install#get-in-touch](http://0.0.0.0:8001/pricing/infra#get-in-touch)
- Compare to the [kubeflow copy doc](https://docs.google.com/document/d/1PSLBJWNqWfonEfQFrWvJ4NpqCHcBoDR2wWmk8IldbOg/edit)
Fixes #5054
=> Add power and z to kubeflow contact-us

templates/openstack/index.html, templates/pricing/consulting.html, templates/shared/pricing/_kubernetes-consulting-add-ons.html, templates/shared/pricing/_kubernetes-consulting.html, templates/shared/pricing/_openstack-packages.html
- Update includes and use them to update /openstack, /openstack/consulting, and /kubernetes to be the same as /pricing/consulting
- http://0.0.0.0:8001/openstack
- http://0.0.0.0:8001/openstack/consulting
- http://0.0.0.0:8001/kubernetes
Fixes #5059
=> Update consulting to use includes

.github/PULL_REQUEST_TEMPLATE.md
Update PR Template to point at updated QA link
- Check code and ensure new link is correct to fix the step above ^
=> Update PR Template to point at updated QA link

templates/legal/shared/_uasd_toc_new.html
Remove japanese UASD box from /uasd
- View the site locally in your web browser at: [/legal/ubuntu-advantage-service-description](http://0.0.0.0:8001/legal/ubuntu-advantage-service-description)
- Make sure the box to the Japanese translation is removed [issue #5063](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5063)
[Fixes #5063](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5063)
=> Remove border of the Japanese translation card

templates/download/index.html
Change copydoc link
- View the site locally in your web browser at: [/download](http://0.0.0.0:8001/download)
- Make sure the [copydoc](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5035) link has been updated
[Fixes #5035](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5035)
=> Change copydoc link

templates/engage/devops-iot-webinar.html, templates/index.html, templates/takeovers/_devops-iot-webinar_takeover.html
Add devops iot webinar takeover and landing page
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) and [/engage/devops-iot-webinar](http://0.0.0.0:8001/engage/devops-iot-webinar)
- Go to the [home page](http://0.0.0.0:8001/) and refresh until this takeover comes up
- Go to [/engage/devops-iot-webinar](http://0.0.0.0:8001/engage/devops-iot-webinar) and check the landing page
- Make sure it complies with the [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5021)
- Make sure it complies with the …
=> Add devops iot webinar takeover and landing page

templates/index.html
Replace old takeovers with new takeovers
- Refresh the page and make sure the old takeovers are replaced with the new ones as per [#1117](https://github.com/canonical-web-and-design/web-squad/issues/1117)
[Fixes #1117](https://github.com/canonical-web-and-design/web-squad/issues/1117)
=> 1117 replace old takeovers with new takeovers

templates/engage/cloud-init-whitepaper.html, templates/index.html, templates/takeovers/_cloud-init-takeover.html
Add cloud-init takeover and landing page
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001) and [/engage/cloud-init-whitepaper](http://0.0.0.0:8001/engage/cloud-init-whitepaper)
- Refresh the [home page](http://0.0.0.0:8001) until you see the cloud-init takeover and then click the button to check the landing page
- Make sure complies with the [design](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5024)
- Make sure complies with the [brief](https://docs.google.com/document/d/1sPg4mSovCx1J0DpvBo818ulCFCgPhTRxSz8BRFF62w8/edit)
Fixes #5026
=> Add cloud-init takeover and landing page

templates/financial-services/index.html, templates/openstack/consulting.html, templates/openstack/contact-us.html, templates/openstack/index.html, templates/openstack/thank-you.html, templates/shared/contextual_footers/_consulting_packages.html, templates/telecommunications/index.html
- Rename Foundation Cloud Build to Private Cloud Build
- http://0.0.0.0:8001/financial-services/
- http://0.0.0.0:8001/openstack/consulting
- http://0.0.0.0:8001/openstack/contact-us
- http://0.0.0.0:8001/openstack/
- http://0.0.0.0:8001/openstack/thank-you
- http://0.0.0.0:8001/telecommunications/
- See that the name has been changed
Fixes #5075
=> Rename Foundation Cloud Build to Private Cloud Build

templates/legal/shared/_uasd_toc_new.html, templates/legal/ubuntu-advantage-service-description/index.md
- Updated the /uasd per Stephan's updates
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit?ts=5cca1067#)
- See if the links to definitions make sense
Fixes #5079
=> Clean-up and link definitions in /uasd

templates/desktop/developers.html
- Updated snapcraft links on /desktop/developers page
- Check that the snapcraft links are as per the [copydoc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
Fixes #5088
=> Update snapcraft links on /desktop/developers page

templates/download/alternative-downloads.html, templates/download/server/arm.html, templates/livepatch/index.html, templates/security/index.html
- Remove promotional references to 14.04 (Trusty Tahr) as it is EOL-
- http://0.0.0.0:8001/security [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit)
- http://0.0.0.0:8001/downloads/alternative-downloads [copy doc](https://docs.google.com/document/d/1VhmFVE3dK81mE3zcC9FVA6f5SGJ-DHan7WWlrlfRcvo/edit#heading=h.l92e027zu9m)
- http://0.0.0.0:8001/livepatch [copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit) - just from meta description
- http://0.0.0.0:8001/download/server/arm [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit#)
- …
=> Remove promotional references to 14.04 (Trusty Tahr) as it is EOL

navigation.yaml, templates/ai/consulting.html
Add ai/consulting page
- View the site locally in your web browser at: [/ai/consulting](http://0.0.0.0:8001/ai/consulting)
- Got to the page and make sure it complies with the [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit#heading=h.qo896jpcbdg0)
Fixes #5083
=> Add ai/consulting page

static/js/chart.js, static/js/release-chart.js, templates/shared/_release_schedule.html
Update release chart on /server page
- View the site locally in your web browser at: [/server](http://0.0.0.0:8001/server)
- Make sure the graph on [/server](http://0.0.0.0:8001/server) under "A release schedule you can depend" matches the graph on [https://www.ubuntu.com/about/release-cycle](https://www.ubuntu.com/about/release-cycle) under the "Long term support and interim releases"
[Fixes #5058](https://github.com/canonical-web-and-design/www.ubuntu.com/issues/5058)
=> Update release chart on /server page

navigation.yaml, templates/kubernetes/docs/auth.md, templates/kubernetes/docs/shared/_side-navigation.md
Added new page to navigation.yaml and docs nav
Added /kubernetes/docs/auth page 
- Agree that it is great
=> Add auth page for Kubernetes docs

templates/desktop/organisations.html
Change release table on /desktop/organisations
- View the site locally in your web browser at: [/desktop/organisations](http://0.0.0.0:8001/desktop/organisations)
- Make sure the table is updated to match [https://www.ubuntu.com/about/release-cycle](https://www.ubuntu.com/about/release-cycle)
Fixes #5101
=> Change release table

templates/legal/ubuntu-advantage-service-description/index.md, templates/pricing/infra.html, templates/security/certifications.html, templates/shared/pricing/_ua-for-infrastructure.html
- Update the service decription to use the first table on /pricing/infra as well as some quick fixes
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit#heading=h.z1fa5mflx2ob)
Fixes #5097 and fixes #5096
=> More updates to /uasd

templates/shared/pricing/_kubernetes-consulting.html
Remove canal from /pricing/consulting
- View the site locally in your web browser at: [http://0.0.0.0:8001/pricing/consulting](http://0.0.0.0:8001/pricing/consulting)
- Compare to the [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#)
Fixes #5110
=> Remove canal from /pricing/consulting

requirements.txt, templates/blog/cloud-and-server.html, templates/blog/desktop.html, templates/blog/internet-of-things.html, templates/blog/press-centre.html, webapp/urls.py, webapp/views.py
**Depends on** https://github.com/canonical-web-and-design/www.ubuntu.com/pull/5071
- Updates to blog module 1.5.1 https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/40 
- Create a dummy template for `cloud-and-server` (see blog module for more info on which groups are available)
**Template are in an early state, and styling was not part of this PR**
- `./run`
- go to `http://localhost:8001/blog/cloud-and-server` and make sure only articles from that group are shown
- go to `http://localhost:8001/blog/cloud-and-server?category=case-studies` and make sure only articles from that group+category are shown
Fixes https://github.com/canonical-web-and-design/base-squad/issues/455
Fixes https://github.com/canonical-web-and-design/base-squad/issues/456
=> Group pages

templates/index.html, templates/takeovers/_1904-webinar_takeover.html
Add Ubuntu 19.04 webinar takeover
- Go to home page and refresh until you see the Ubuntu 19.04 webinar takeover
- Check the [design](https://github.com/canonical-web-and-design/web-squad/issues/1083)
- Make sure the text matches [this](https://github.com/canonical-web-and-design/web-squad/issues/1124)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1124
=> 1124 ubuntu 19.04 takeover and webinar

static/sass/_pattern_footer.scss, templates/templates/footer.html
Display "sectors" heading in the footer correctly for small screen sizes
- Go to the home page and resize the widow to 550px wide and than make it bigger to 650px wide. Make sure the style of the "sector" heading in the footer remains consistent.
Fixes #4904
=> Change sector heading in footer style

templates/takeovers/_1904-webinar_takeover.html, templates/takeovers/_cloud-init-takeover.html, templates/takeovers/_iot-devops_takeover.html, templates/takeovers/_openstack_security_takeover.html
* Skipping global takeovers for non-en users users who have localized ones
- If it's not already the case :eyes: , change your browser language to French.
- Visit the demo site and refresh the homepage multiple times.
- You should only see takeovers in your favourite language.
=> Skip global takeovers for fr and de users

templates/templates/base.html
- add logic to NOT load shared/forms/_form-validation.html for the path /whitepapers
- View the site locally in your web browser at: [http://0.0.0.0:8001/whitepapers/robotics](http://0.0.0.0:8001/whitepapers/robotics)
- See that the form works and the content is revealed
- Go to http://0.0.0.0:8001/#get-in-touch
- See that the form works
Fixes #5127
=> Add logic to including form validation

templates/index.html
Change back to iot devops webinar takeover
- See that the whitepaper version has been replaced by the webinar version
=> Change back to iot devops webinar takeover

templates/legal/data-privacy/index.html
Add link to ESXi page on data privacy page
- View the site locally in your web browser at: [/legal/data-privacy](http://0.0.0.0:8001/legal/data-privacy)
- Make sure it complies with the [copy doc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit)
Fixes #5132
=> Add link to ESXi page on data privacy page

templates/download/iot/index.html
Updated logos for:
- Artik
- Intel JOULE
- Raspberry Pi
- Snapdragon
- Tank
- Up2
- View the site locally in your web browser at: [/download/iot](http://0.0.0.0:8001/download/iot)
- Ensure the logos listed above aren't of low resolution.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1098
=> Update low res logos on /download/iot page

templates/server/hyperscale.html
Remove partners logo sections
- View the site locally in your web browser at: [/server/hyperscale](http://0.0.0.0:8001/server/hyperscale)
- Make sure the hardware and software partners sections are removed
Fixes #5138
=> Remove partners logo sections

templates/internet-of-things/index.html
Change learn how to make a snap link
- View the site locally in your web browser at: [/internet-of-things](http://0.0.0.0:8001/internet-of-things)
- Make sure the "Learn how to make a snap" link takes you to https://snapcraft.io/first-snap
Fixes #5100
=> Change learn how to make a snap link

templates/index.html
Replace IoT DevOps webinar takeover with the whitepaper takeover
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) 
- Refresh the home page until the IoT DevOps whitepaper takeover comes up. Make sure the IoT DevOps webinar takeover is not shown anymore.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1137
=> Replace IoT DevOps webinar takeover with the whitepaper takeover

templates/engage/fr/openstack-made-easy.html
With the recent form work, this one was turned into a contact form, hence had 1) wrong fields 2) wrong return URL
* Reverted to the previous form
- Go to `/engage/fr/openstack-made-easy`, fill the form, ensure you can download the ebook
=> Fix openstack made easy french form

redirects.yaml
Came out an Ubuntu Advantage Client CLI user experience review in Lyon.
This is a prerequisite route for fixing UA Client in issue
https://github.com/CanonicalLtd/ubuntu-advantage-client/issues/502
Fixes: #5163
=> Add a redirect for ubuntu.com/cc-eal for better search result hits

static/sass/_global-settings.scss, templates/templates/_navigation.html, templates/templates/footer.html
The new grid is a bit more strict. Anything placed inside (with or without col-* classes), needs to span a number of columns. I've set the default behaviour to 12, i.e. full width of the grid.
In cases where an item needs to be as wide as its content, using a .row is not ideal. Instead, I propose a .u-fixed-width class, which sets max-width and paddings matching .row, but doesn't force the content inside to span any number of columns. This could be useful for tabs, menus etc. and can be placed on the pattern div, which can reduce nesting.
- Run through the following [QA …
=> vf2.0alpha: subnav fix

templates/index.html
- Add LXD takeover and landing page live in place of the Cloud-Init whitepaper takeover.
- Remove the OpenStack and ESM takeovers from the rotation.
- Make sure lxd takeover is available
- Make sure Cloud-init, OpenStack & ESM takeovers are removed
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1158#event-2358582842
=> Update live takeovers

package.json, static/sass/_layout-whitepapers.scss, static/sass/_pattern_desktop-statistics.scss, static/sass/print.scss
- Added `--max-warnings=0` to sass-lint task
- Disabled sass-lint on certain lines where exceptions needed to be made
- Run the tests using the command `./run test`
- See that the tests pass
- In any sass file, violate a sass-lint rule by setting `background-color: #000` (which violates the no color literals rule)
- Run `./run test` again
- See that the tests fail
Fixes #4153
=> 4153: Update sass-lint to fail if there are any warnings

templates/openstack/install.html
- Removed out-of-date instructional video from `/openstack/install#workstation-deployment`
- Removed line of text from the adjacent copy that referred to the above video
- View the site locally in your web browser at: [/openstack/install#workstation-deployment](http://0.0.0.0:8001/)
- See that there is no video when compared to https://www.ubuntu.com/openstack/install#workstation-deployment
- Ensure that the text matches the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)
Fixes #3074
=> 3074 remove install open stack video

templates/about/index.html
Reduced width of graph image on `/about`
- View the site locally in your web browser at: [/about](http://0.0.0.0:8001/about)
- See that the width of the graph has been reduced to match the second screenshot below.
Fixes #5181 
Original:
Updated:
=> 5181: Reduce width of graph image on about page

static/sass/_pattern_footer.scss, static/sass/_pattern_lists.scss, static/sass/_pattern_navigation.scss, static/sass/styles.scss
- Fixed alignment of mid-dots in lists on blog pages
- See that mid-dots are vertically centered on these lists:
- pagination
- legal links in footer
- list of links at the bottom of the Enterprise dropdown, in the top navigation
- Visit [/blog/archives](http://0.0.0.0:8001/blog/archives)
- See that the mid-dots on the lists of months are vertically centered
Fixes #5148 
Pagination:
Footer:
Enterprise dropdown:
=> 5148 fix middot alignment

templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md
Updates links to the latest k8s bundles and adds notes for the latest bugfix release
=> K8s-docs update for bugfix release

requirements.txt, templates/blog/pagination.html, webapp/templatetags/utils.py
Updated pagination template so non-pagination related query params are persisted when navigating via pagination links
- View the site locally in your web browser at: [/blog/archives](http://0.0.0.0:8001/blog/archives)
- Click "2018" in the right-hand list of links, then click "2" in the list of pagination links
- See that the page contains a second set of posts from 2018, and the url ends with `?year=2018&page=2`
Fixes #5204
=> 5204 persist query params on pagination links

static/sass/styles.scss
Add `font-display: swap` attribute to font loading.
> The font swap period occurs immediately after the font block period. During this period, if the font face is not loaded, any element attempting to use it must instead render with a fallback font face. If the font face successfully loads during the swap period, the font face is then used normally.
Ref: https://developers.google.com/web/updates/2016/02/font-display
- Throttle the network on Chrome DevTools using a mobile emulator and observe fast font …
=> Add font-display attribute to font loading

templates/templates/base.html
Add `preconnect` tag to gstatic.com
- Run a performance audit with Chrome DevTools and verify this is no longer a recommendation.
=> Add preconnect tag to gstatic.com

redirects.yaml
Fixes https://github.com/canonical-web-and-design/www.ubuntu.com/issues/1805#event-2358680518
QA
--
Check `/404` and `/500` go to homepage rather than displaying the 404 or 500 page.
Also check things like `/a-fake-page` still show 404 page.
=> Redirect /404 and /500 to homepage

static/js/dynamic-contact-form.js, templates/shared/forms/interactive/_bootstack.html, templates/shared/forms/interactive/_embedded.html, templates/shared/forms/interactive/_general.html, templates/shared/forms/interactive/_kubeflow.html, templates/shared/forms/interactive/_kubernetes.html, templates/shared/forms/interactive/_openstack.html, templates/shared/forms/interactive/_pricing-infra.html, templates/shared/forms/interactive/_robotics.html, templates/shared/forms/interactive/_support.html
* Adds the notion of product context to modal forms and pass it to Marketo
* Modal contact forms now inherit the product parameter of the button they are triggered from
* If no parameter is set, the path of the page is passed instead, in the "pathlvl1-pathlvl2-etc" format.
- Click on any contact button, if it triggers a modal form, inspect and ensure it has a hidden "product-context" field set
- Navigate to `/ai`, click on the "Call the experts" button at the top page, inspect and ensure the form has its hidden "product-context" field set to `ai-index`
- Navigate to `/download/iot/raspberry-pi-2-3`, click on the …
=> Add product context handling to forms

static/sass/_pattern_blog-card.scss, templates/blog/blog-card.html, templates/blog/featured-articles.html, templates/blog/index.html, templates/blog/newsletter-form.html, templates/blog/singular-category.html
- Ensured a group label is always present in a blog card header (defaults to "Ubuntu" if one isn't returned from the API)
- Added logic from blog.ubuntu.com to ensure a category label is always present in a blog card footer
- When a newsletter card is shown, ensured the blog cards on the same row display their post excerpts to reduce the amount of white space
- Updated newsletter card template to more closely match the one on blog.ubuntu.com
- Ensure that blog cards on the same row as the newsletter display their …
=> 5123 improve blog card template

templates/openstack/training.html
- updated copy on /openstack/training per the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit)
- added new image in header
- View the site locally in your web browser at: [/openstack/training](http://0.0.0.0:8001/openstack/training)
- Ensure that the page matches the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1207
There's also been [a request](https://docs.google.com/a/canonical.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ …
=> 1207 Update /openstack/training copy

.gitignore, templates/engage/451-automotive.html, templates/index.html, templates/takeovers/_451-automotive_takeover.html
- added 451 Automotive takeover and landing page
- Refresh the page until you see the 451 takeover
- Ensure it complies with the [design](https://github.com/canonical-web-and-design/web-squad/issues/1172#issuecomment-497369012), and matches the [copy doc](https://docs.google.com/document/d/1muBF3nUj_tYCdHR7B5I5hO-kboBwdcpGnihNhqYiwXM)
- Follow the "Watch the webinar" link to the landing page
- Ensure it also matches the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1177
=> 451 automotive takeover landing

templates/blog/topics/juju.html, webapp/urls.py
Add Juju topic page
- View the site locally in your web browser at: [/blog/topics/juju](http://0.0.0.0:8001/blog/topics/juju)
- Make sure it looks and behaves similar to https://blog.ubuntu.com/topics/juju
Fixes #5155
=> Add Juju topic page

templates/blog/topics/robotics.html, webapp/urls.py
- Added /blog/topics/robotics template
- View the site locally in your web browser at: [/blog/topics/robotics](http://0.0.0.0:8001/blog/topics/robotics)
- Ensure the page looks and behaves similarly to https://blog.ubuntu.com/topics/robotics
Fixes #5157
=> 5157: Implement robotics topic page

static/sass/_pattern_blog-topic.scss, static/sass/styles.scss, templates/blog/topics/snappy.html, webapp/urls.py
Add snappy topic page
- View the site locally in your web browser at: [/blog/topics/snappy](http://0.0.0.0:8001/blog/topics/snappy)
- Make sure it looks and behave similar to https://blog.ubuntu.com/topics/snappy
Fixes #5153
=> Add snappy topic page

templates/engage/North-Americas-first-autonomous-runway-snowplough-case-study.html
Add Northstar landing page
- View the site locally in your web browser at: [/engage/North-Americas-first-autonomous-runway-snowplough-case-study](http://0.0.0.0:8001/engage/North-Americas-first-autonomous-runway-snowplough-case-study)
- Make sure it complies with the [brief](https://docs.google.com/document/d/171v3o0-5sS_3Lii-KzwiYv83Uz2iRQATl6cknYF7qKE/edit?ts=5ced49ee#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1164
=> Add Northstar landing page

templates/engage/starting-with-ai.html, templates/templates/_extra_metadata.html, templates/templates/base.html, webapp/templatetags/utils.py
This pull request is a proposal for a new way to handle metadata for pages such as engage pages, where having an extra layer of metadata for social sharing is critical.
Currently we surface things such as page description through template blocks, but when the content needs to duplicated across tags, this doesn't scale, especially since Django doesn't allow duplicating blocks in the extended template.
This proposal introduces:
*  an "extends_with_args" template tag, that wraps around "extends" and allows setting context variables from extension pages.
* an `_extra_metadata.html` which makes use of these args to build social sharing metadata for Twitter, FB, etc.
* an example (`/engage/starting-with-ai`)
The benefits of this approach is that it doesn't conflict with our existing template …
=> [RFC] Extra metadata handling for engage pages

package.json, static/sass/_global-settings.scss, static/sass/_layout-documentation.scss, static/sass/_layout-legal-pages.scss, static/sass/_pattern_contact-modal.scss, static/sass/_pattern_desktop-statistics.scss, static/sass/_pattern_lists.scss, static/sass/_pattern_navigation.scss, static/sass/_pattern_separator.scss, static/sass/_pattern_table.scss, static/sass/_vanilla-placeholders.scss, static/sass/styles.scss, templates/base_index.html, templates/templates/_navigation.html, templates/templates/footer.html, yarn.lock
Example of how to correctly order grid classes and align / vertically center utilities so they don't interfere with each other.
- Find strip containing "The number one platform for containers"
- Ensure it works as expected.
=> Example for upgrade guide: Correct markup structure (grid and centering utilities)

navigation.yaml, templates/templates/_navigation.html, webapp/context_processors.py
- added Vanilla's contextual menu pattern to blog navigation for topics
- Click "Topics" in the navigation, ensure that you can see the dropdown list of topics, and that each of the links works
Fixes #5210
=> 5210 add topics dropdown to blog navigation

templates/engage/microsoft-active-directory.html, templates/index.html, templates/takeovers/_active-directory_takeover.html
- Changed the headline to work better 'How to integrate Ubuntu with Active Directory'
- Hid the takeover as it has been delayed to the 13 June 2019
- See that the h1 has change and that there is a nbsp on the work 'Active Directory'
=> Update Active Directory takeover and engage page headlines

templates/community/index.html
Update links on /community
- View the site locally in your web browser at: [http://0.0.0.0:8001/community](http://0.0.0.0:8001/community)
- see that the link to the insights.u.c now goes to blog.u.c and that the links to community.u.c now use discourse.u.c
Fixes #5270
=> Update links on /community

templates/shared/_cloud-contact-us-form.html
Add https links for ask ubuntu and ubuntuforums
- View the site locally in your web browser at: [http://0.0.0.0:8001/ai/contact-us](http://0.0.0.0:8001/ai/contact-us)
- See that https is used for ask ubuntu and ubuntuforums
Fixes #5273
=> Add https links for ask ubuntu and ubuntuforums

templates/desktop/organisations.html
The hero image was removed by mistake. I added it back.
- Check if the image is there
- View the site locally in your web browser at: /desktop/organisations
=> fixed hero (added image back)

templates/openstack/training.html
Updated /openstack/training per the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY)
- Ensure that the page matches the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1252
=> update training copy per the copy doc

templates/shared/_thank_you_footer.html
- Send people interested in landscape to the site instead of /support
- View the site locally in your web browser at: [/server/thank-you](http://0.0.0.0:8001/server/thank-you)
- Compare to the [copy doc](https://docs.google.com/document/d/1XWmMQlhgqHeDrMepfxDzeDvXSwTMUbXW8s78bBOsfDw/edit)
Fixes #5282
=> Move link to landscape.c.c on /server/thank-you

templates/download/server/provisioning.html
Updated MAAS provisioning screenshots
- View the site locally in your web browser at: [/download/server/provisioning](http://0.0.0.0:8001/download/server/provisioning)
- See that the screenshots have been updated from the (out of date) screenshots currently on the [live site](https://www.ubuntu.com/download/server/provisioning)
Fixes #3077
=> 3077: update maas provisioning screenshots

templates/engage/451-automotive.html, templates/engage/ai-gettingstarted.html, templates/index.html, templates/takeovers/_starting-with-ai-webinar_takeover.html
- Add Getting Started with AI takeover and landing page
- Add mobile CTA to [/engage/451-automotive](http://0.0.0.0:8001/engage/451-automotive) landing page as it was missing
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/), [/engage/451-automotive](http://0.0.0.0:8001/engage/451-automotive) and [/engage/ai-gettingstarted](http://0.0.0.0:8001/engage/ai-gettingstarted)
- Compare to [brief](https://docs.google.com/document/d/1TOfGfuNOGfAjNQEPyOJ0G6JRznwsb-FUe4xL378CG0Q/edit#)
- Check design
Fixes https://github.com/canonical-web-and-design/web-squad/issues/ …
=> Add Getting Started with AI takeover and landing page

requirements.txt, webapp/settings.py, webapp/wsgi.py
- Add sentry
- Add service name to logs
- In .env file add those 2 lines:
```
SENTRY_DSN=<ASK_TOTO>
TALISKER_NETWORKS=172.17.0.1
```
- http://0.0.0.0:8001/_status
- http://0.0.0.0:8001/_status/test/sentry
- Should get an issue on sentry
- Check the logs and make is at the end of every line: `service=ubuntu.com`
=> Add logging

static/js/forms.js, templates/shared/forms/_state.html
- Reduced the amount of JS controlling the state/province field on contact forms
- View the site locally in your web browser at: [/contact-us/form](http://0.0.0.0:8001//contact-us/form)
- Select Canada from the country dropdown, see that a dropdown labelled "Provinces" appears below, and contains Canadian provinces
- Select United States of America from the country dropdown, see that a dropdown labelled "States" appears below, and contains American states
Fixes #5290
=> 5290: refactor state form js

templates/index.html
Remove starting with AI webinar takeover as it is not supposed to be live yet
=> Remove starting with AI webinar takeover

templates/index.html
Make sure the whitepaper AI takeover is replaced by webinar AI takeover.
=> Remove AI whitepaper takeover and replace with webinar

templates/download/shared/_get-ebook-security.html, templates/engage/fr/openstack-made-easy.html, templates/engage/shared/_de_engage_form.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_fr_engage_form.html, templates/rfp/index.html, templates/whitepapers/beta/shared/form.html, templates/whitepapers/shared/form.html
- removed unused stateCountry.js from many forms where country/state fields weren't included
- fixes `$ is not defined` errors on those pages
- added state field to /download contact form, ala https://github.com/canonical-web-and-design/ubuntu.com/pull/5298
- View the site locally in your web browser at: [/download/iot/intel-joule-desktop/](http://0.0.0.0:8001/download/iot/intel-joule-desktop)
- See that the state field is present in the contact form and displays the appropriate options when selecting either "United States of America" or "Canada"
- Visit the following pages, open dev tools in your …
=> Remove stateCountry.js

templates/download/desktop/thank-you.html
* Re-added this line. Marketo rejects forms without a `formVid`, people who have subscribed in the last day or two (since the line was removed) on this page, won't receive their newsletters.
=> Fix newsletter form on /download/desktop/thank-you

templates/index.html
- Make sure you can see the active directory takeover and not 19.04 takeover
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1262
=> Replace 19.04 takeover with active directory

templates/engage/ubuntu-lime-telco.html, templates/index.html, templates/takeovers/_ubuntu-lime-telco_takeover.html
- added Lime telco takeover and landing page
- View the site locally in your web browser at: [http://0.0.0.0:8001](http://0.0.0.0:8001)
- Refresh the page until you see a takeover featuring the Lime Systems logo, see that it matches the [brief](https://docs.google.com/document/d/1Dzzfmkaq7_m2Y4ySjkqXcHVDjcYAEsNPbbwz6J64B5I/edit#)
- Click the CTA to visit the landing page, see that it matches the [designs](https://github.com/canonical-web-and-design/web-squad/issues/1174#issuecomment-501216906) and the [copy doc](https://docs.google.com/document/d/126V5e7cQ7ICiP0MAZlrTNsZ_xHknG5VTtcj_T-cUrwM/edit?ts …
=> 1179: add lime telco landing page and takeover

navigation.yaml, requirements.txt, templates/blog/article.html, templates/blog/author.html, templates/blog/index.html, templates/blog/newsletter-form.html, templates/blog/product-cards.html, templates/blog/tag.html, webapp/context_processors.py, webapp/templatetags/utils.py
- updated blog post template to match current blog e.g. https://blog.ubuntu.com/2019/04/09/speed-up-your-ros-snap-builds
- added tag template to match current blog e.g https://blog.ubuntu.com/tag/robotics
- View the site locally in your web browser at: [/blog/speed-up-your-ros-snap-builds](http://0.0.0.0:8001/blog/speed-up-your-ros-snap-builds)
- Ensure that the page looks and behaves similarly to https://blog.ubuntu.com/2019/04/09/speed-up-your-ros-snap-builds
- Click any of the tag links in the top of the page, and see that the page you then see looks and behaves similarly to …
=> 5250 improve blog post template

requirements.txt, webapp/settings.py, webapp/urls.py
remove `django_prometheus` dependency to use talisker prometheus instead
- `./run --env TALIKSER_NETWORKS=172.17.0.1`
- navigate on the site
- access `/_status/metrics`
- make sure some metrics are logged
=> Remove django_prometheus to use talisker default

templates/download/shared/_verify-checksums.html
“sha256sum” is usually available on Linux systems, but usually not on macOS/BSD.
“shasum -a 256” does the same thing and is usually available on all three.
1. Click “Download” in the top-level navigation
2. Click any of the four desktop/server download buttons
3. Wait for the download to complete
4. Copy the verification command and verify that it now works (macOS) or still works (Ubuntu)
Fixes #5307.
=> “sha256sum” > “shasum -a 256” to work on macOS/BSD

templates/blog/blog-card.html
- Ensured that excerpt text is visible on blog cards if it doesn't have a featured image to display
- Run `./run`
- Visit [/blog/tag/brand](http://0.0.0.0:8001/blog/tag/brand)
- See that "Ubuntu Brand Guidelines get their own site" and "Ubuntu Orange is #dd4814" posts have an excerpt and don't have an image.
- Visit [/blog/tag/front-end](http://0.0.0.0:8001/blog/tag/front-end)
- See that "A seachange in front-end best practice (but not for a while)" post has an excerpt and doesn't have an image.
Fixes #5327
=> ensure blog card excerpt is visible if there is no image

.circleci/config.yml, templates/shared/_insights_news_strip.html, templates/templates/_navigation-community-h.html, templates/templates/_navigation-developer-h.html, templates/templates/_navigation-enterprise-h.html, templates/templates/global-nav.html
- Changed appropriate dropdown navigation links from blog.ubuntu.com to u.c/blog
- Global nav links aren't updated yet, that will be resolved when [this PR](https://github.com/canonical-web-and-design/global-nav/pull/117) on the global-nav repo is merged
- Updated homepage links from blog.ubuntu.com
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) 
- Click the following links and ensure they take you to the appropriate pages:
- Homepage:
- Any of the posts in the "Latest news from our blog" section
- The post featured under "Spotlight"
- "View more from …
=> 5323 update blog links on nav and homepage

templates/templates/footer.html
Change press centre link in the footer nav  to point to /blog/press-centre
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/) 
- Click Press centre link at the bottom of the page and make sure it takes you to [/blog/press-centre](http://0.0.0.0:8001/blog/press-centre)
Fixes #5324
=> Change press centre link in the footer nav

templates/templates/_extra_metadata.html, templates/templates/base.html, templates/templates/base_no_nav.html
Fixes #5317
Seems like template `{% block %}` doesn't work when it's in partial, not in main template.
So moving out copydoc meta block back to template to make it work again.
- ./run or https://ubuntu-com-canonical-web-and-design-pr-5335.run.demo.haus/
- visit couple of pages with [Ubuntu Copy Docs](https://github.com/canonical-web-and-design/ubuntu-copy-docs) plugin
- make sure plugin correctly links to copydocs again
=> Move copydoc meta block out of partial

templates/contact-us/form/thank-you.html, templates/containers/thank-you.html, templates/download/server/thank-you-s390x.html, templates/download/server/thank-you.html, templates/internet-of-things/thank-you.html, templates/openstack/thank-you.html, templates/server/thank-you.html, templates/templates/_extra_metadata.html, templates/templates/base.html
Drop "www" from explicit and implicit canonical URLs and from `og:url`.
* On any page, ensure the canonical URL starts with "https://ubuntu.com"
* On a recent engage page, such as `/engage/ubuntu-lime-telco`, ensure the `og:title` tag starts with "https://ubuntu.com"
=> Drop www from canonical URLs and og:url

templates/templates/footer.html
Add blog navigation in the footer
- View the site locally in your web browser at:  [http://0.0.0.0:8001/](http://0.0.0.0:8001/) 
- Make sure the Blog navigation is present in the footer and it looks like [this](https://github.com/canonical-web-and-design/ubuntu.com/issues/5322)
Fixes #5322
=> Add blog navigation in the footer

templates/blog/article.html, templates/templates/base.html
Include canonical link to snapcraft.io for blogs tagged `snapcraft.io`.
Also, fix canonical links for other pages for new domain `ubuntu.com` (rather than `www.ubuntu.com`)
=> Point to snapcraft.io as canonical link

templates/templates/_navigation-developer-h.html
A drive-by fix of an oddity I noticed while designing the developer desktop survey results page…
In the “Developer” mega-menu, 6/8 of the headings — including 3/4 of the “muted” headings — are links.
This change makes the mega-menu slightly more consistent — 7/8 and 4/4 — by moving the tutorials link to the “Tutorials” heading. It also resolves the visual weirdness of this link being the only one in the mega-menu that starts part-way through a sentence.
An alternative solution would be to no longer make _any_ of the headings links, i.e. 0/8 and 0/4. That would be more work, but would also solve the problem that 3/7 of the heading links are duplicated by one of the links below it.
=> Makes “Tutorials” a link in “Developer” mega-menu

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Based on a support request to get the default one working
> Stacey Burns (GitHub Developer Support)Jun 20, 6:49 AM UTCHey 
> Peter,
> Thanks for contacting GitHub Support!I believe the template named pull_request_template.md should display as the default template. Let us know if you have any trouble setting it up. We'd be more than happy to further assist.
> Cheers
> Stacey
=> lowercase pull request name

templates/legal/ubuntu-advantage-service-description/index.md, templates/shared/pricing/_ua-for-infrastructure.html
- Updated the /uasd page
- Download this branch
- Go to http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- See that the page is good
- Compare the page to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit)
Fixes #5344
=> Updated /uasd with new Ceph storage details

templates/blog/article.html, templates/blog/author.html, templates/blog/blog-card-header.html, templates/blog/blog-card.html, templates/blog/newsletter-form.html, templates/blog/product-cards.html
Pages on ubuntu.com/blog should match blog.ubuntu.com as much as possible, but there are a few intentional differences, listed below:
/blog/tag/brand or /blog/tag/front-end
=> QA u.c/blog

redirects.yaml
This is so we can trivially redirect blog.ubuntu.com -> ubuntu.com/blog,
and blog.ubuntu.com/search URLs will also redirect properly.
QA
--
`./run`, go to http://0.0.0.0:8001/blog/search?q=hello, check you end up at http://0.0.0.0:8001/search?q=hello (even though you'll see a 500 error)
=> Redirect /blog/search to /search

requirements.txt
I'm trying to fix this error:
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/2172/
As a first step, I think we should at least try to install the dependency versions that Talisker wants, crucially prometheus_client 0.4.2 rather than 0.7.0. So I'm just moving Talisker to the top of the dependency list. For a fuller explanation see 02a4a80f
QA
--
```
.,/run --env TALISKER_NETWORKS=172.17.0.1
```
Go to http://127.0.0.1, click around a bit. Go to http://127.0.0.1/_status/metrics, check you successfully see prometheus metrics.
=> Move Talisker to top of dependencies

navigation.yaml, templates/legal/shared/_uasd_toc.html
- Added the Japanese uasd page as a hidden navigation element, so it gets a secondary nav if you get to the page
- Update the p-card on the english page to use a better translation
- download this branch
- go to http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- click on the link to the Japanese translation (http://0.0.0.0:8001/legal/ubuntu-advantage-service-description/ja)
- see there is a secondary nav
Fixes #5354
=> Add menu for the uasd Japanese translation

templates/legal/shared/_uasd-toc-ja.html
Add link to the english page on the UASD japanese page
- View the site locally in your web browser at: [/legal/ubuntu-advantage-service-description/ja](http://0.0.0.0:8001/legal/ubuntu-advantage-service-description/ja)
- Make sure there is link to the english version
=> Add link to the english page on the UASD japanese page

templates/blog/newsletter-form.html, templates/download/desktop/thank-you.html
- Add Robotics option to the newsletter sign-up form on /download/desktop/thank-you
- Add Robotics option to the newsletter sign-up form on all /blog pages
- View the site locally in your web browser at:[/download/desktop/thank-you ](http://0.0.0.0:8001/download/desktop/thank-you)
- Go to [/download/desktop/thank-you?country=&version=18.04.2&architecture=amd64](http://0.0.0.0:8001/download/desktop/thank-you?country=&version=18.04.2&architecture=amd64) and make sure the sign-up form contains Robotics as an option
- Go to any blog page (i.e. [/blog](http://0.0.0.0:8001/blog) or …
=> Add Robotics options to the newsletter sign-up form

templates/ai/consulting.html
- Added whitepaper section to footer on /ai/consulting, per the copy doc
- Updated blog links to point to u.c/blog
- View the site locally in your web browser at: [/ai/consulting](http://0.0.0.0:8001/ai/consulting)
- See that the page matches the [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk)
- Check that "AI, ML, & Ubuntu: Everything you need to know." and "How to build and deploy your first AI/ML model on Ubuntu" links take you the relevant posts on u.c/blog
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5365
=> add link to AI whitepaper in footer of /ai/consulting template

templates/openstack/storage.html
- Remove `FAQ` section from /openstack/storage
- Delete https://blog.ubuntu.com/2015/05/18/ubuntu-advantage-storage-factsheet post 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1293
=> Remove link to blog post & remove blog post

templates/server/hyperscale.html
- add empty `p` tag above list to trigger additional margin on the list's `h3` tag, per [suggested solution](https://github.com/canonical-web-and-design/ubuntu.com/issues/5309#issuecomment-502029058).
- View the site locally in your web browser at: [/server/hyperscale](http://0.0.0.0:8001/server/hyperscale)
- See that there is more space between "Here’s why Ubuntu is the best answer to the scale-out challenge:" and the paragraphs above it, compared to https://ubuntu.com/server/hyperscale
Fixes #5309
=> 5309: increase space above list section, using suggested solution

templates/500.html, webapp/templatetags/utils.py
- `extends_with_args` tag can take template variables, added a check to make sure the variable exists, and if it doesn't, return an empty string instead of an error
- fixed grammar mistake on 500 page
- View the site locally in your web browser at: [/blog/minimal-ubuntu-released](http://0.0.0.0:8001/blog/minimal-ubuntu-released)
- Ensure that you see the post "Minimal Ubuntu, on public clouds and Docker Hub", and not a 500 error page
Fixes #5378 and #5379
=> 5378: extends_with_args: if variable doesn't exist, return empty string

templates/security/index.html
- changed the "Watch the Ubuntu security webinar" link to `.p-link--inverted`
- View the site locally in your web browser at: /security
**Steps:**
- go to /security and scroll down to 'Talk to a member of our team' section.
- make sure the "Watch the Ubuntu security webinar" link is not broken and it appears as `.p-link--inverted`
how it looks like:
how it should look like:
=> change default link to inverted

templates/security/certifications.html
- updated copy on /security/certifications in line with the copy doc
- View the site locally in your web browser at: [/security/certifications](http://0.0.0.0:8001/security/certifications)
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit#)
Fixes #5383
=> Update /security/certifications per the copy doc

templates/openstack/index.html
- Updated /openstack in to match the copy doc
- View the site locally in your web browser at: [/openstack](http://0.0.0.0:8001/openstack)
- See that the page matches the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1307
=> 1307: update openstack overview per the copy doc

navigation.yaml, templates/kubernetes/docs/aws-integration.md, templates/kubernetes/docs/backups.md, templates/kubernetes/docs/ceph.md, templates/kubernetes/docs/cni-calico.md, templates/kubernetes/docs/cni-canal.md, templates/kubernetes/docs/cni-flannel.md, templates/kubernetes/docs/cni-overview.md, templates/kubernetes/docs/container-runtime.md, templates/kubernetes/docs/custom-loadbalancer.md, templates/kubernetes/docs/gcp-integration.md, templates/kubernetes/docs/high-availability.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/metallb.md, templates/kubernetes/docs/openstack-integration.md, templates/kubernetes/docs/overview.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/scaling.md, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/troubleshooting.md, templates/kubernetes/docs/upgrade-notes.md, templates/kubernetes/docs/upgrading.md, templates/kubernetes/docs/using-vault.md
Includes all the updates to docs for the 1.15 release of Kubernetes
This includes new pages:
- cni-overview
- cni-flannel
- cni-calico
- cni-canal
- container-runtime
- custom-loadbalancer
- openstack-integration
=> New pages and updates to docs for 1.15 release

requirements.txt
- Updated version of blog module used to 2.0.10
- /blog/archives was returning a 500 error unless a 'year' query parameter was present, version 2.0.10 of the blog module resolves this
- Run the site using the command `./run clean && ./run serve`
- View the site locally in your web browser at: [/blog/archives](http://0.0.0.0:8001/blog/archives)
- Ensure that you see the archives page, and not a 500 error
=> Fix /blog/archives 500 error

templates/kubernetes/docs/cni-calico.md, templates/kubernetes/docs/cni-canal.md, templates/kubernetes/docs/cni-flannel.md, templates/kubernetes/docs/release-notes.md
The tables on cni-flannel, cni-canal and cni-calico weren't rendering properly due to differences in the markdown engine
this also fixes a minor typo
=> Fix typo and some tables in k8s docs

templates/engage/edge-month.html
- Changed webinar CTA text from 'Watch the webinar' to 'Register for the webinar'
- View the site locally in your web browser at: [/engage/edge-month](http://0.0.0.0:8001/engage/edge-month)
- See that the green CTAs all read "Register for the webinar"
=> Update copy on /engage/edge-month CTAs

requirements.txt
Fixes:
- Bad category name: https://ubuntu.com/blog?category=asdfasdfasdf
- Page with string: https://ubuntu.com/blog?page=asdf
- Exceptions where failing: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/2443/?query=is%3Aunresolved
=> Bump blog to v2.0.11

templates/engage/fr/esm.html, templates/engage/fr/esm_1404.html, templates/engage/fr/openstack-made-easy.html
Updated the following /engage/fr/ pages to make them more consistent with other engage pages:
- /engage/fr/esm_1404
- /engage/fr/esm
- /engage/fr/openstack-made-easy
- Run `./run`
- Visit [/engage/fr/esm_1404](http://0.0.0.0:8001/engage/fr/esm_1404)
- See that the page matches the [copy doc](https://docs.google.com/document/d/1T4Ar7n4Jwypecr96Wv5SQjdNdsISNkRHBU4DTxseHo0/edit#)
- Visit [/engage/fr/esm](http://0.0.0.0:8001/engage/fr/esm)
- See that the page matches the [copy doc](https://docs.google.com/document/d/14owLexmd5yn9g9Opq2oYAw-oxG2k2YKLgEi9bGqzzMg/edit)
- Visit [/engage/fr/openstack-made-easy](http://0.0.0.0:8001/engage/fr/openstack-made-easy)
- See that the page matches the [copy doc](https://docs.google.com/document/d/16u6gbZGqzIyJgjlOOks3DyW0fhIB …
=> ESM blog post engage page in French

templates/ai/install.html, templates/download/iot/_flash-image.html, templates/download/iot/_setup-ubuntu-sso.html, templates/download/iot/installation-media.html, templates/download/iot/intel-iei-tank-870.html, templates/download/iot/intel-joule-desktop.html, templates/download/iot/intel-joule.html, templates/download/iot/intel-nuc-desktop.html, templates/download/iot/intel-nuc.html, templates/download/iot/kvm.html, templates/download/iot/orange-pi-zero.html, templates/download/iot/qualcomm-dragonboard-410c.html, templates/download/iot/raspberry-pi-2-3-core.html, templates/download/iot/raspberry-pi-2-3.html, templates/download/iot/raspberry-pi-compute-module-3.html, templates/download/iot/samsung-artik-5-10-server.html, templates/download/iot/samsung-artik-5-10.html, templates/download/iot/up-squared-iot-grove-server.html, templates/download/server/provisioning.html, templates/kubernetes/install.html, templates/kubernetes/managed.html, templates/livepatch/index.html, templates/openstack/install.html, templates/openstack/managed.html
- Removeed the p-list-step__bullet as it does not appear to be required and it seems to add an extra number on mobile.
- http://0.0.0.0:8001/ai/install
- http://0.0.0.0:8001/download/iot/installation-media
- http://0.0.0.0:8001/download/iot/intel-iei-tank-870
- http://0.0.0.0:8001/download/iot/intel-joule-desktop
- http://0.0.0.0:8001/download/iot/intel-joule
- http://0.0.0.0:8001/download/iot/intel-nuc-desktop
- http://0.0.0.0:8001/download/iot/intel-nuc
- http://0.0.0.0:8001/download/iot/kvm
- http://0.0.0.0:8001/download/iot/orange-pi-zero
- http://0.0.0.0:8001/download/iot/qualcomm-dragonboard-410c
- http://0.0.0.0:8001/download/iot/raspberry-pi-2-3-core
- …
=> Remove p-list-step__bullet

redirects.yaml
This should fix images in old blog posts like this one:
https://ubuntu.com/blog/consortium-garr-creates-countywide-federated-canonical-openstack-cloud
(As well as adding other fixes)
QA
--
`./run`
Even though http://127.0.0.1:8001/blog/consortium-garr-creates-countywide-federated-canonical-openstack-cloud itself will still look broken, this is because insights.ubuntu.com gets redirect to live.
To test this out, go to http://127.0.0.1:8001/blog/wp-content/uploads/dc41/GAAR2.png, see that you end up at a real image.
Also check others redirect to useful places:
- http://127.0.0.1:8001/blog/admin
- http://127.0.0.1:8001/blog/event/mobile-world-congress-2018/
- http://127.0.0.1:8001/blog/event/mobile-world-congress-2018
=> Port redirects from blog.ubuntu.com

templates/kubernetes/index.html, templates/kubernetes/managed.html, templates/pricing/consulting.html
- /kubernetes page (update links to new pdf 'Upstream K8s options...' + 'AI/ML add-on...' sections)
- /kubernetes/managed (update link to new pdf in hero + resources sections)
- /pricing/consulting 'Kubeflow' name changed to 'Kubeflow Machine Learning Starter'
- View the site locally in your web browser at: [/kubernetes](http://0.0.0.0:8001/kubernetes)
- go to [/kubernetes](http://0.0.0.0:8001/kubernetes) and make sure the links to the datasheet in the  'Upstream K8s options...' + 'AI/ML add-on...' sections give you [this pdf](https://github.com/canonical-web-and-design/web-squad/files/3320837/DS_K …
=> K8s Services datasheet + page changes

templates/kubernetes/docs/cni-calico.md, templates/kubernetes/docs/index.md, templates/kubernetes/docs/metallb.md, templates/kubernetes/docs/overview.md, templates/kubernetes/docs/storage.md, templates/kubernetes/docs/using-vault.md
- Added note about MetalLB on cni-calico page
- Added note about Calico BGP on MetalLB page
- Added section on Vault docs describing how to transition to Vault from EasyRSA 
- Fixed ambiguity in storage page
- various updates of CDK to Charmed Kubernetes
=> K8s docs misc updates

templates/esm/index.html, templates/livepatch/index.html, templates/pricing/index.html, templates/pricing/infra.html, templates/support/index.html
- added links to buy.u.c on pricing and /pricing/infra
- made use of the _call_sales include on three pages
- http://0.0.0.0:8001/pricing
- http://0.0.0.0:8001/pricing/infra
- http://0.0.0.0:8001/livepatch
- http://0.0.0.0:8001/esm
- Compare to the copy docs: [pricing](https://docs.google.com/document/d/1iOM6oBqsTkptsst3yG-U3sGaYLQqs27go_8yJQdhMBE/edit#) and [infra](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
Fixes #5410
=> Add buy.u.c cta back to /pricing and /pricing/infra

requirements.txt
Fixes https://sentry.is.canonical.com/canonical/ubuntu-com/issues/2469/?query=is%3Aunresolved
Fixes 500 when requesting a unexisting tag: https://ubuntu.com/blog/tag/snapasdadsfasf
Should return 404 page
- `./run` 
- access:  `/blog/tag/asdfasdfasdf`
- Should get a 404
=> Bump blog to v2.0.13

requirements.txt
Fix author not found that was returning a 500 instead of a 404.
- `./run`
- http://0.0.0.0:8001/blog/author/aaaaaaaaaaaaaaaaaaaaaaa
- should get a 404 page
=> Bump blog to v2.0.14

navigation.yaml, templates/kubernetes/docs/backups.md, templates/kubernetes/docs/shared/_side-navigation.md
Adds some updates to the K8s Backups page
Adds the backup page to main navigation
=> K8s backups documentation updates

templates/training/_base_training.html, templates/training/contact-us.html, templates/training/index.html, templates/training/thank-you.html
- Fix-up /training page contact-us by
- creating a base template
- moving the non-js contact-us and thank-you pages/forms in from openstack and trimming them to the right products
- adding the right forms back to the training page for the js modals
- See that the page looks ok and the modals open with js and statically with no js
Fixes #5276
=> Fix-up /training page contact-us

templates/kubernetes/index.html, templates/openstack/index.html, templates/shared/_training.html
12## Done
- Add training strips to /kubernetes and /openstack
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes and http://0.0.0.0:8001/openstack
- See that there is an include for training on both pages and compare to the [openstack copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#) and [kubernetes copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#)
NOTE: I have asked @anasereijo to provide an illustration, but this is ok for now.
Fixes …
=> Add training strips to /kubernetes and /openstack

templates/core/index.html, templates/download/iot/index.html, templates/takeovers/_ubuntu-core-18-takeover.html
- Add anchor to on /download/iot for /core links
- See that the links on /core now go to an anchor on http://0.0.0.0:8001/download/iot#core
Fixes #5403
=> Add anchor to on /download/iot for /core links

templates/download/iot/intel-iei-tank-870.html, templates/download/iot/intel-nuc.html
* Update tank and nuc UC18 images location
- Ensure download and checksum links on [/download/iot/intel-nuc](https://ubuntu-com-canonical-web-and-design-pr-5429.run.demo.haus/download/iot/intel-nuc) and [/download/iot/intel-iei-tank-870](https://ubuntu-com-canonical-web-and-design-pr-5429.run.demo.haus/download/iot/intel-iei-tank-870) are working
=> Update Nuc and Tank870 UC18 images locations

templates/download/iot/installation-media.html
- Updated the mac dd command to use 32m (lower case) from 32M
- Added the copy doc url to the page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot/installation-media
- Compare to the [copy doc](https://docs.google.com/document/d/1GEJ-raGZDkcFeedEk_Ja_4DJYzqjeUa-GIHVDV7r7Vo/edit)
Fixes #5334
=> Change 32M to 32m for macs

templates/templates/_navigation-developer-h.html
- Linked the “Deb, snap, and charm packages” navigation item to the Packages page
- Open the “Developer” mega-menu
- In the “Develop on Ubuntu” section, click “Deb, snap, and charm packages”
- Observe that you are now on the “Ubuntu Packages and Repositories” page
None, this is a drive-by of something I discovered while investigating [Ubuntu-design#120](https://github.com/CanonicalLtd/Ubuntu-design/issues/120)
=> Links “Deb, snap, and charm packages” to Packages page

templates/takeovers/_edge-month_takeover.html
Changed text in the edge month takeover.
- Make sure this is reflected in the takeover.
Fixes: https://github.com/canonical-web-and-design/web-squad/issues/1369
=> Change text of edge month takeover

templates/templates/_navigation-developer-h.html
- Changed “PaddPaddle” to the correct spelling “PaddlePaddle”
- Changed the link target from the Chinese http://www.paddlepaddle.org/ to the English http://en.paddlepaddle.org/ (since this is ubuntu.com and not cn.ubuntu.com)
- Open “Developer”
- in the “AI & MACHINE LEARNING” section, choose “PaddlePaddle”
None, this is a drive-by of another problem discovered while investigating [Ubuntu-design#120](https://github.com/CanonicalLtd/Ubuntu-design/issues/120)
=> Corrects PaddlePaddle link and text

templates/engage/casestudy-city-network.html
- created a u.c version of https://app-sjg.marketo.com/#LP5346A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-city-network
=> Add City Network OpenStack cloud hosting case study engage page

templates/engage/451-cloud-economics.html
- created a u.c version of https://app-sjg.marketo.com/#LP6252A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/451-cloud-economics
=> Add 451 cloud economics engage page

templates/engage/essential-guide-big-data-solutions.html
- created a u.c version of https://app-sjg.marketo.com/#LP5586A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/essential-guide-big-data-solutions
=> Add essential guide for telecoms adopting big data solutions engage page

templates/engage/openstack-telco-clouds.html
- created a u.c version of https://app-sjg.marketo.com/#LP5434A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-telco-clouds
=> Add OpenStack for telcos engage page

templates/engage/nfv-sdn-openstack.html
- created a u.c version of https://app-sjg.marketo.com/#LP5475A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/nfv-sdn-openstack
=> Add NVF and SDN on Openstack engage page

templates/engage/cto-guide-sdn-nfv-vnf.html
- created a u.c version of https://app-sjg.marketo.com/#LP5616A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cto-guide-sdn-nfv-vnf
=> Add CTO's guide to SDN, NFV & VNF engage page

templates/shared/_insights_news_strip.html, templates/shared/contextual_footers/_cloud_further_reading.html, templates/shared/contextual_footers/_desktop_further_reading.html, templates/shared/contextual_footers/_further_reading.html, templates/shared/contextual_footers/_iot_further_reading.html, templates/shared/contextual_footers/_security_further_reading.html, templates/shared/contextual_footers/_telco_further_reading.html, webapp/settings.py
Added `3408` to the list of excluded tag IDs on the blog
Tricky to QA, since there are as yet no posts to exclude, but could verify that the additional ID matches the relevant tag in [WP admin](https://admin.insights.ubuntu.com/wp-admin/term.php?taxonomy=post_tag&tag_ID=3408)
=> exclude kubeflow news from u.c/blog

templates/engage/low-latency-report.html
- created a u.c version of https://app-sjg.marketo.com/#LP5624A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/low-latency-report
=> Add low latency and real time kernels for telco and NFV engage page

templates/engage/telco-cloudification-ebook.html
- created a u.c version of https://app-sjg.marketo.com/#LP5612A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/telco-cloudification-ebook
=> Add Carrier Cloudification engage page

templates/engage/openstack-made-easy.html
- created a u.c version of https://app-sjg.marketo.com/#LP5655A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-made-easy
=> Add OpenStack made easy engage page

templates/download/iot/installation-media.html
- Changed `xzcat` to `gunzip`
- Various other style and brevity fixes on the page
- Go to http://0.0.0.0:8001/download/iot/installation-media
Might fix #5200 — needs testing
=> Copyedits and changes “xzcat” to “gunzip”

static/sass/styles.scss, templates/blog/article.html
- Center align and max-width for wordpress figures
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/deploying-kubernetes-at-the-edge-part-i-building-blocks
- See that the figures are center aligned and fit in the column
Fixes #5443
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/441217/61111730-21b93380-a482-11e9-8fc3-568e5a03ce7e.png)|
|![image](https://user-images.githubusercontent.com/441217/61111665-fdf5ed80-a481-11e9-9e9c-f10390d08434.png)|
|![image](https://user-images.githubusercontent.com/441217/61111706-0fd79080-a482-11e9-9316-8c9815b6b2 …
=> Center align and max-width for wordpress figures

templates/engage/casestudy-rocketchat.html
- created a u.c version of https://app-sjg.marketo.com/#LP5777A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-rocketchat
=> [Engage] Add Rocket.Chat case study page

templates/engage/casestudy-cinergy.html
- created a u.c version of https://app-sjg.marketo.com/#LP5402A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-cinergy
=> [Engage] Add Cinergy case study page

templates/engage/casestudy-nexiona.html
- created a u.c version of https://app-sjg.marketo.com/#LP4910A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-nexiona
=> [Engage] Add Nexiona case study page

templates/engage/casestudy-botsandus.html
- created a u.c version of https://app-sjg.marketo.com/#LP5959A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-botsandus
=> [Engage] Add BotsAndUs case study page

templates/engage/casestudy-commercetools.html
- created a u.c version of https://app-sjg.marketo.com/#LP5326A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-commercetools
=> [Engage] Add Commercetools case study page

templates/engage/stuckstack-ebook.html
- created a u.c version of https://app-sjg.marketo.com/#LP5282A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/stuckstack-ebook
=> Add How to escape from StuckStack ebook engage page

templates/engage/casestudy-itstratagen.html
- created a u.c version of https://app-sjg.marketo.com/#LP5353A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-itstratagen
=> Add ITstrategen case study engage page

templates/engage/edge-month.html, webapp/views.py
* Created a "page_utms" context var with a string in the `?utm_...&utm_...` format for when links require page UTMs inheritance to pass them to the target.
* Example use on `/engage/edge-month`
- Ensure webinar links on `/engage/edge-month` inherit utm_source, utm_medium and utm_campaign of the page.
=> Set a page_utms context var when links need inheritance of parent page UTMs

templates/engage/ebook-maas.html
- created a u.c version of https://app-sjg.marketo.com/#LP5480A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ebook-maas
=> [Engage] Add server provisioning eBook page

templates/engage/private-cloud.html
- created a u.c version of https://app-sjg.marketo.com/#LP5742A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/private-cloud
=> [Engage] Add private cloud eBook page

templates/engage/casestudy-innovapos.html
- created a u.c version of https://app-sjg.marketo.com/#LP4877A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-innovapos
=> [Engage] Add InnovaPOS case study page

templates/engage/casestudy-azeti.html
- created a u.c version of https://app-sjg.marketo.com/#LP4899A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-azeti
=> [Engage] azeti case study page

templates/engage/whitepaper-iot-security.html
- created a u.c version of https://app-sjg.marketo.com/#LP4943A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/whitepaper-iot-security
=> [Engage] Add IoT security whitepaper page

static/sass/styles.scss, templates/download/server/thank-you.html, templates/download/shared/_verify-checksums.html
- Moved the verify checksum into a `<details>` tag so people can see more of the page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop/thank-you?version=18.04.2&architecture=amd64 and http://0.0.0.0:8001/download/server/thank-you?version=18.04.2&architecture=amd64
- See that the accordian works and the details visible
closed 
open
=> Moved the verify checksum into an accordian

templates/engage/casestudy-sensape.html
- created a u.c version of https://app-sjg.marketo.com/#LP5880A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-sensape
=> Add Sensape case study engage page

templates/engage/public-cloud.html
- created a u.c version of https://app-sjg.marketo.com/#LP5720A1LA1
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/public-cloud
=> [Engage] Add public cloud on Ubuntu OpenStack eBook page

templates/shared/forms/interactive/_bootstack.html, templates/shared/forms/interactive/_embedded.html, templates/shared/forms/interactive/_general.html, templates/shared/forms/interactive/_kubeflow.html, templates/shared/forms/interactive/_kubernetes.html, templates/shared/forms/interactive/_openstack.html, templates/shared/forms/interactive/_pricing-infra.html, templates/shared/forms/interactive/_robotics.html, templates/shared/forms/interactive/_support-openstack.html, templates/shared/forms/interactive/_support.html
* Replace "email address" by "work email" in interactive forms to improve data quality. Testing has demonstrated it doesn't hurt conversion.
- Ensure interactive contact forms ask you for your "Work email" on the last page
=> Email address -> Work email in interactive forms

templates/engage/multi-cloud-guide.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/multi-cloud-guide
Fixes #5499
=> [Engage] Update metadata syntax for multi cloud guide page

templates/engage/hiri-case-study.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/hiri-case-study
Fixes #5501
=> [Engage] Update metadata syntax for Hiri case study page

templates/engage/451-cloud-economics.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/451-cloud-economics
Fixes #5502
=> [Engage] Update metadata syntax on 451 cloud economics page

templates/engage/14-04-esm.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/14-04-esm
Fixes #5503
=> [Engage] Update metadata syntax for 14-04 ESM page

templates/engage/events.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/events
Fixes #5504
=> [Engage] Update metadata syntax for events page

templates/index.html, templates/takeovers/_bt_announcement.html
- Added a new small strip for the BT blog post
- See that the strip is there under the takeover and goes to the blog post (which isn't live yet)
Fixes #1329
=> Add a new strip for BT on the homepage

templates/takeovers/_bt_announcement.html
s/SG/5G/
- see that it says 5G not SG
=> Fix typo on BT strip

templates/engage/vmware-to-openstack.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/vmware-to-openstack
Fixes #5493
=> [Engage] Update metadata syntax for VMware to Openstack page

templates/engage/core18-security.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/core18-security
Fixes #5494
=> [Engage] Update metadata syntax for core18 security page

templates/engage/openstack-telco-clouds.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-telco-clouds
Fixes #5496
=> [Engage] Update metadata syntax for openstack telco clouds page

templates/engage/openstack-security-webinar.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-security-webinar
Fixes #5495
=> [Engage] Update metadata syntax for openstack security webinar page

templates/engage/iot-devops.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/iot-devops
Fixes #5498
=> [Engage] Update metadata syntax for IoT devops page

templates/engage/casestudy-city-network.html, templates/templates/_extra_metadata.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/casestudy-city-network
Fixes #5497
=> [Engage] Update metadata syntax for city network case study page

templates/engage/deploy-ai-ml-model.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/deploy-ai-ml-model
Fixes #5527
=> [Engage] Update metadata syntax for deploy AI/ML model page

templates/engage/modern-cloud.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/modern-cloud
Fixes #5530
=> [Engage] Update metadata syntax for modern cloud page

templates/engage/devops-iot-webinar.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/devops-iot-webinar
Fixes #5531
=> [Engage] Update metadata syntax for DevOps IoT webinar page

templates/engage/openstack-made-easy.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-made-easy
Fixes #5532
=> [Engage] Update metadata syntax for OpenStack made easy page

templates/engage/industrial-drones-case-study.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/industrial-drones-case-study
Fixes #5533
=> [Engage] Update metadata syntax for industrial drones case study page

templates/engage/financial-services-month.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/financial-services-month
Fixes #5534
=> [Engage] Update metadata syntax for financial services month page

templates/engage/cto-guide-sdn-nfv-vnf.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cto-guide-sdn-nfv-vnf
Fixes #5535
=> [Engage] Update metadata syntax for CTO's guide to SDN, NFV and VNF page

templates/engage/openstack-security-whitepaper.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-security-whitepaper
Fixes #5536
=> [Engage] Update metadata syntax for OpenStack security whitepaper page

templates/engage/low-latency-report.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/low-latency-report
Fixes #5537
=> [Engage] Update metadata syntax for low latency report page

templates/engage/de/vmware-to-openstack.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/de/vmware-to-openstack
Fixes #5544
=> [Engage] Update metadata syntax for DE VMware to OpenStack page

templates/engage/de/openstack-made-easy.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/de/openstack-made-easy
Fixes #5545
=> [Engage] Update metadata syntax of DE OpenStack made easy page

templates/engage/snap-deltas.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/snap-deltas
Fixes #5546
=> [Engage] Update metadata syntax for snap deltas page

templates/engage/19-04-webinar.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/19-04-webinar
Fixes #5547
=> [Engage] Update metadata syntax for 19.04 webinar page

templates/engage/future-proof-iot.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/future-proof-iot
Fixes #5538
=> [Engage] Update metadata syntax for future proof IoT page

templates/engage/telco-cloudification-ebook.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/telco-cloudification-ebook
Fixes #5529
=> [Engage] Update metadata syntax for telco cloudification page

templates/engage/iot-business-model.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/iot-business-model
Fixes #5526
=> [Engage] Update metadata syntax for IoT business model page

templates/engage/cloud-init-whitepaper.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cloud-init-whitepaper
Fixes #5525
=> [Engage] Update metadata syntax for Cloud-init page

templates/engage/ai-ml-ubuntu.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ai-ml-ubuntu
Fixes #5548
=> [Engage] Update metadata syntax for AI and ML with Ubuntu page

templates/engage/_heading-help.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/_heading-help
Fixes #5523
=> [Engage] Update metadata syntax for heading help page

templates/engage/cloud-economics.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cloud-economics
Fixes #5521
=> [Engage] Update metadata syntax for cloud economics page

templates/engage/ubuntu-18-10.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ubuntu-18-10
Fixes #5520
=> [Engage] Update metadata syntax for Ubuntu 18.10 page

templates/engage/devops-cicd-webinar.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/devops-cicd-webinar
Fixes #5519
=> [Engage] Update metadata syntax for DevOps CI/CD page

templates/engage/fr/openstack-made-easy.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/openstack-made-easy
Fixes #5518
=> [Engage] Update metadata syntax for FR OpenStack made easy page

templates/engage/fr/vmware-to-openstack.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/vmware-to-openstack
Fixes #5516
=> [Engage] Update metadata syntax for FR VMware page

templates/engage/fr/esm.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/esm
Fixes #5515
=> [Engage] Update metadata syntax for FR ESM page

templates/engage/iot-disk-encryption.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/iot-disk-encryption
Fixes #5514
=> [Engage] Update metadata syntax for IoT disk encryption page

templates/engage/edge-month.html
- Changed the button text from _Register for the webinar_ to _Watch the webinar_
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5611
=> Button text to "Watch the webinar"

templates/engage/de/what-can-you-do-with-kubernetes.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/de/what-can-you-do-with-kubernetes
Fixes #5542
=> [Engage] Update metadata syntax for DE what can you do with Kubernetes page

templates/engage/shift-to-app-store-experience.html, templates/index.html, templates/takeovers/_shift-to-app-store_takeover.html
- added "Shift to app store" takeover & engage page
- removed "Lime telco" takeover
- Refresh the page until you see the app store takeover
- Ensure it matches the [designs](https://github.com/canonical-web-and-design/web-squad/issues/1352#issuecomment-509298944) and the [copy doc](https://docs.google.com/spreadsheets/d/1t9l_YknhiZ25YGOQqXJCs0b7KVo3eHaSfvi-KRAT8_0/edit?ts=5d0a5ff9#gid=2113339190)
- Follow the CTA to the engage page
- Ensure it matches the [copy doc](https://docs.google.com/document/d/1MsQpa3ik8w-jVAmPdsQIz0w_XteBs …
=> Shift to app store takeover & engage page

templates/engage/ITstrategen-case-study.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ITstrategen-case-study
Fixes #5510
=> [Engage] Update metadata syntax for ITstrategen case study page

templates/engage/evolving-software.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/evolving-software
Fixes #5509
=> [Engage] Update metadata syntax for evolving software page

templates/engage/robot-operating-system-choice.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/robot-operating-system-choice
Fixes #5508
=> [Engage] Update metadata syntax for robot OS choice page

templates/engage/fingbox-case-study.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fingbox-case-study
Fixes #5524
=> [Engage] Update metadata syntax for Fingbox case study page

templates/engage/developer-desktop.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/developer-desktop
Fixes #5507
=> [Engage] Update metadata syntax for developer desktop page

templates/engage/northstar.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/northstar
Fixes #5505
=> [Engage] Update metadata syntax for Northstar case study page

templates/engage/ubuntu-core-and-kura.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ubuntu-core-and-kura
Fixes #5506
=> [Engage] Update metadata syntax for Ubuntu Core and Kura page

templates/engage/kernel-telco-nfv.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/kernel-telco-nfv
Fixes #5517
=> [Engage] Update metadata syntax for kernel telco NFV page

templates/engage/lxd-whitepaper.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/lxd-whitepaper
Fixes #5513
=> [Engage] Update metadata syntax for LXD whitepaper page

static/sass/_pattern_strip.scss, templates/internet-of-things/robotics.html
Added bottomed suru strip and image to IoT robotics page.
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/robotics
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1461)
Fixes canonical-web-and-design/web-squad#1461
=> Add bottomed suru strip to IoT robotics page

webapp/urls.py
Slug change from snappy to snapcraft in blog
- http://127.0.0.1:8000/blog/topics/snappy
should work
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5487
=> Change slug snappy to snapcraft for topic page

.sass-lint.yml, static/sass/_pattern_strip.scss, templates/embedded/index.html
Add the half and half reverse strip to the hero of embedded
- View the site locally in your web browser at: http://0.0.0.0:8001/embedded
- Make sure the new hero matches [the design](https://github.com/canonical-web-and-design/web-squad/issues/1464)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1464
=> Add half-and-half-reverse-suru strip

templates/shared/contextual_footers/_iot_developers.html
- Corrects broken link to Ubuntu Core on IoT page.
- Removes external-link class since the replacement page is on ubuntu.com.
1. Check out this feature branch
1. Run the site using the command `./run serve`
1. Go to http://0.0.0.0:8001/internet-of-things
1. In the footer choose “Try Ubuntu Core”
Fixes #5484.
=> Updates Ubuntu Core link

static/sass/_pattern_strip.scss, templates/internet-of-things/gateways.html
Added topped suru strip to IoT gateways page.
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1462)
Fixes canonical-web-and-design/web-squad#1462
=> Add topped suru strip to IoT gateways page

templates/kubeflow/consulting.html
- Changed the  Read our consulting datasheet to Download the Getting started with AI whitepaper 
- Moved the  Read our consulting datasheet down the page
- Compare this to the changes in the the [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5618
=> Adding whitepaper and moving a link

templates/takeovers/_shift-to-app-store_takeover.html
* UTMs are cool
- Ensure UTMs are the on the shift to appstore takeover
=> Added UTMs to "shift to app store" takeover

static/sass/_pattern_strip.scss, templates/internet-of-things/digital-signage.html
Added image Suru strip to IoT digital signage page.
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1460)
Fixes canonical-web-and-design/web-squad#1460
=> Add image Suru strip to IoT digital signage page

static/sass/_pattern_strip.scss, templates/internet-of-things/appstore.html
Added half-and-half Suru strip to IoT digital signage page.
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/appstore
- Ensure that the design matches the [specification](https://github.com/canonical-web-and-design/web-squad/issues/1463)
Fixes canonical-web-and-design/web-squad#1463
=> Add half-and-half suru strip to IoT Appstore page

templates/download/desktop/thank-you.html, templates/download/server/thank-you.html, templates/download/shared/_verify-checksums.html
- Add suru header and vanilla's accordian pattern to the server and desktop download thank-you pages
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop/thank-you?version=18.04.2&architecture=amd64 and http://0.0.0.0:8001/download/server/thank-you?version=18.04.2&architecture=amd64
- **Cancel the download**
- See that it matches the [design](#1308) except that it uses vanilla 1.8's accordian
Fixes [1308](https://github.com/canonical-web-and-design/web-squad/issues/1308)
=> Update design of server and desktop download pages

templates/download/iot/intel-joule.html
Fixed broken "Ubuntu" hyperlink in the "Step 3- Flash the USB Drives" section of the download/iot/intel-joule page.
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot/intel-joule
- Ensure the the Ubuntu link leads to the correct tutorial.
Fixes #5471
=> Fix broken link

templates/openstack/index.html
Updated Real architectural flexibility, full automation section to match copy doc.
- Ensure that the page matches the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit)
Fixes #5627
=> Update content to match copy doc

navigation.yaml
- Simplify /legal secondary menu
- View the site locally in your web browser at: http://0.0.0.0:8001/legal
- See that the seconary menu is as simple as possible and that the overview page give access to the subfiles
- See that the subfiles all have a simple seconary nav
Fixes #5632
example of 3rd level page that has simple menu
example of terms and conditions menu overview has no seconary
=> Simplify /legal secondary menu

static/sass/_pattern_strip.scss, templates/internet-of-things/index.html
- Update iot index with new illustrations
- Add logo cloud back
- Update text on top half of the page
- Compare to the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#) and the [design](https://github.com/canonical-web-and-design/web-squad/issues/1417)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1417 and https://github.com/canonical-web-and-design/web-squad/issues/1434
=> Update iot index with new illustrations

package.json, static/sass/_layout-documentation.scss, static/sass/_layout-legal-pages.scss, static/sass/_pattern_contact-modal.scss, static/sass/_pattern_desktop-statistics.scss, static/sass/_pattern_lists.scss, static/sass/_pattern_navigation.scss, static/sass/_pattern_separator.scss, static/sass/_pattern_table.scss, static/sass/_vanilla-placeholders.scss, yarn.lock
- updated version of Vanilla to 2.2.0
- changed out-of-date spacing variable names to their new analogues, according to [this doc](https://assets.ubuntu.com/v1/d4964abe-Vanilla+2+spacing+variables.pdf?_ga=2.30419519.1642800135.1565004285-833517530.1561371934)
- removed reference to `$px` variable and replaced with `1px` where necessary
- Verify that the updated `$spv-` and `$sph-` variable names are correct as per the [upgrade guide](https://assets.ubuntu.com/v1/d4964abe-Vanilla+2+spacing+variables.pdf?_ga=2.30419519.1642800135.1565004285-833517530.1561371934)
- See that `./run` runs successfully
Fixes #5644 & #5649
=> Update vanilla version and spacing variables

templates/kubernetes/contact-us.html, templates/kubernetes/thank-you.html, templates/shared/pricing/_kubernetes-consulting-add-ons.html, templates/shared/pricing/_kubernetes-consulting.html
- Combines the “Contact us” and “Thanks for enquiring” headings for the three Kubernetes consulting plans, since they now share one contact button
- Corrects the Kubernetes consulting contact form to use the combined heading
- Corrects the Kubernetes AI/ML contact form to use the Kubernetes AI/ML heading
- Go to http://0.0.0.0:8001/kubernetes
- Right-click each “Get in touch” button and choose “Open in New Tab”/“Open in New Window”
- Observe that the contact forms say “Contact us about Kubernetes consulting” and “Contact us about Kubernetes with AI/ML”, rather than the incorrect “Contact us about Ubuntu Advantage”
Fixes _part of_ #5641.
=> Corrects Kubernetes “Contact us” page headings

templates/index.html
- Replace Edge takeover with Maas takeover
- Make sure Edge takeover was replaced with Maas takeover
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1533
=> Replace Edge takeover with Maas

templates/engage/data-pipelines-kubeflow.html, templates/engage/index.html, templates/engage/shared/_header.html, templates/index.html, templates/takeovers/_data-pipelines-kubeflow.html, templates/takeovers/index.html
- Add deepsense.ai webinar takeover and landing page
- Added index of takeovers at http://0.0.0.0:8001/takeovers/
- Added page to the http://0.0.0.0:8001/enage page
- View the site locally in your web browser at: http://0.0.0.0:8001/ and http://0.0.0.0:8001/engage/data-pipelines-kubeflow
- Here is the [brief](https://docs.google.com/spreadsheets/d/1JAqg2L3QlH6aTVva2GzinyxN5pBR6iKBQbaF8fQZaEc/edit#gid=2113339190) and the [copy doc](https://docs.google.com/document/d/1Ie6XPTPIyj7ZE08or7Qf9WVi96D-PTIPslopw2X8yBc/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1499
=> Add deepsense.ai webinar takeover and landing page

templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/operations.md, templates/kubernetes/docs/quickstart.md
Rewritten Quickstart page
Rewritten Install page
slight change to operations page
These changes remove references to conjure-up as an installer.
=> K8sdocs - remove conjure up

templates/internet-of-things/robotics.html
- Minor copy updates to the banner on robotics page
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/robotics
- Compare to the [copy doc](https://docs.google.com/document/d/1cDxhPCQbHA0r6n9JXNmO50ANLPZhCFdgwATX6f90guU/edit) only the banner and logo cloud start changed
Fixes #5664
=> Update banner on /iot/robotics

static/sass/_pattern_strip.scss, templates/download/index.html
Update design of /download page
- Compare to the design in the issue #5615 *Note, multipass isn't ready yet*
Fixes #5615 
large
mobile
=> Update design of /download page

static/sass/styles.scss, templates/desktop/developers.html, templates/desktop/features.html, templates/desktop/index.html, templates/desktop/organisations.html, templates/desktop/partners.html, templates/desktop/statistics.html, templates/download/cloud/index.html, templates/download/desktop/index.html, templates/download/desktop/thank-you.html, templates/download/iot/index.html, templates/download/iot/installation-media.html, templates/download/iot/intel-iei-tank-870.html, templates/download/iot/intel-joule-desktop.html, templates/download/iot/intel-joule.html, templates/download/iot/intel-nuc-desktop.html, templates/download/iot/intel-nuc.html, templates/download/iot/kvm.html, templates/download/iot/orange-pi-zero.html, templates/download/iot/qualcomm-dragonboard-410c.html, templates/download/iot/raspberry-pi-2-3-core.html, templates/download/iot/raspberry-pi-2-3.html, templates/download/iot/raspberry-pi-compute-module-3.html, templates/download/iot/samsung-artik-5-10-server.html, templates/download/iot/samsung-artik-5-10.html, templates/download/iot/up-squared-iot-grove-server.html, templates/embedded/index.html, templates/esm/index.html, templates/financial-services/index.html, templates/shared/_release_schedule.html
- updated grid layouts on /desktop, /download, /embedded, /esm and /financial-services pages in line with Vanilla 2's new grid patterns (see point 2 of [the upgrade guide](https://ubuntu.com/blog/vanilla-framework-2-0-upgrade-guide))
- Check that the grid/column layouts on these pages look correct/not broken:
- /desktop
- /desktop/contact-us
- /desktop/developers
- /desktop/features
- /desktop/organisations
- /desktop/partners
- /desktop/statistics
- /desktop/thank-you
- /download
- /download/cloud
- /download/desktop
- …
=> Grid updates pt2 

requirements.txt
Bump blog module version
- Make sure all blog menus work properly.
**QA needs to be done locally since the blog API is no longer accessible from outside the our network**
=> Bump canonicalwebteam.blog to 2.3.0

templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md
Updates links to point to current Charmed Kubernetes bundle
=> k8s- change bundle ref

templates/engage/developing-android-on-ubuntu.md, templates/takeovers/_developing-android-on-ubuntu.html
- Fix suru background on android takeover and engage page as the new markdown version doesn't parse {{ ASSET_SERVER_URL }}
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/developing-android-on-ubuntu?
- See that you can see the suru background asset image on the header
=> Fix suru background on android takeover and engage page

templates/openstack/storage.html, templates/shared/forms/interactive/_storage.html
Add modal form for /openstack/storage
- View the site locally in your web browser at:http://0.0.0.0:8001/openstack/storage#get-in-touch
- Compare to [copy doc](chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=storage%20-%20Google%20Docs&pos=0&uri=https://docs.google.com/document/d/1Pfay_PfsE7Tw8gU82wENRCcCUEXbe2gf804uGzM_PqY/edit#) and test the output
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1409
=> Add modal contact-us form for /openstack/storage

redirects.yaml, requirements.txt, webapp/urls.py
Added feed endpoints to the blog section of the site.
- `/blog/feed/`
- `/blog/author/<author_name>/feed`
- `/blog/group/<group_slug>/feed`
- `/blog/topic/<topic_slug>/feed`
- Go to some different groups, topics and author pages and make sure the feed versions of it contain the same articles.
Fixes #
=> Add feeds endpoints for authors, groups and topics

templates/engage/data-pipelines-kubeflow.html, templates/takeovers/_data-pipelines-kubeflow.html
- Updated the background of the takeover and engage header from white to blue.
- View the site locally in your web browser at: http://0.0.0.0:8001/ and http://0.0.0.0:8001/engage/data-pipelines-kubeflow
- See that it follows the design and looks ok on mobile.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1539
=> Change color on datapipelines takeover

templates/engage/enterprise-snap-management.md, templates/engage/index.html, templates/index.html, templates/takeovers/_enterprise-snap-management.html, templates/takeovers/index.html
- Added takeover, engage page for Enterprise Snap Management whitepaper
- View the site locally in your web browser at: http://0.0.0.0:8001 and compare the takeover to the design and the [brief](https://docs.google.com/spreadsheets/d/1v8nou3GCqfXIPVBgAdGwMO8gzGgaduHBFEuR9YG62d0/edit#gid=877682240)
- compare the engage page - http://0.0.0.0:8001/engage/enterprise-snap-management -  to the design and the [copy doc](https://docs.google.com/document/d/1iSLsV7PD7BhF0OhxfD8KpfdQzDscxvO7UToLF7h_1vU/edit)
- see that the takeover is on the [index page](http://0.0.0.0:8001/takeovers) and the engage page on …
=> Add enterprise snap management whitepaper and takeover - 28 August 2019

templates/esm/index.html
- Remove install commands and menu from /esm
- Removed the internal menu as the page is smaller
- See that the menu and instructions are removed, the copy doc is not a good reference as it is ready for a future release.
Fixes #5698
=> Remove install commands and menu from /esm

static/js/chartData.js, templates/about/release-cycle.html
- Update the /about/release-cycle
- added kernel version numbers that were missing
- removed 18.10
- expired some k8s versions
- Fixed up the [sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1712489059) that drives it.
- See that it matches the dates in the sheet
Fixes [#1541](https://github.com/canonical-web-and-design/web-squad/issues/1541)
=> Update the /about/release-cycle

templates/kubeflow/consulting.html, templates/kubeflow/features.html, templates/kubeflow/index.html, templates/kubeflow/install.html, templates/kubeflow/shared/_learn-more.html
- Updated the text for a 'Learn more about AI/ML and Kubeflow' section, made it an include and added it to the overview, features and install page
- Updated all the copy docs
- http://0.0.0.0:8001/kubeflow/
- http://0.0.0.0:8001/kubeflow/features
- http://0.0.0.0:8001/kubeflow/install
- http://0.0.0.0:8001/kubeflow/consulting
- Compare to the [copy doc](https://docs.google.com/document/d/1DT5nCRSJH-OkvDmlyKh6vVhofeHPHZJHTTBDNu44wCY/edit#heading=h.bmctssm2s32g)
- Fixes https://github.com/canonical-web-and-design/web-squad/issues/1544
- Fixes …
=> Add learn more to all kubeflow section

requirements.txt
Show most recent entries first in feeds endpoints.
- `./run`
- Go to feeds endpoints and make sure the most recent entries come first.
=> List feeds from most recent to oldest

templates/download/server/thank-you.html, templates/download/shared/_get_ebook_maas.html
- Added a card for microk8s on the /download/server/thank-you page
- Added some bottom margin to the recaptcha box
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you
- Compare to the [copy doc]()
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1542
=> Add microk8s to server download thankyou page

package.json, yarn.lock
Bump the version of lodash to resolve its critical severity alert
- Run `./run clean`
- Run `./run build` and see there are no errors
- Run `./run server` and check the site looks ok
=> Bump the version of lodash to resolve its critical severity alert

templates/engage/hiri-case-study.html
Fix the Hiri case study engage page
- Go to https://ubuntu.com/engage/hiri-case-study and see it 500
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/hiri-case-study
- Check the page loads fine
Fixes https://sentry.is.canonical.com/canonical/ubuntu-com/issues/3718/
=> Fix the Hiri case study engage page

templates/kubeflow/install.html
- Update the /kubeflow/install page per the copy doc
- Compare to the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit?ts=5d6618d1)
Fixes #5715
=> Update kubeflow install instructions

templates/index.html
- Replace AI data pipelines takeover with Enterprise Snaps
- See that enterprise snap management replaces data pipelines
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1568
=> Swap homepage takeovers

requirements.txt, templates/search.html, webapp/app.py
Implement /search in Flask.
**NB:** This currently points to `v0.2.0a6` of the `canonicalwebteam.search` module. Testing this PR will be a QA of https://github.com/canonical-web-and-design/canonicalwebteam.search/pull/2. Please review that PR at the same time - please let me know once that's approved, so I can publish `v0.2.0` and switch this branch to use that version.
QA
--
`./run`, go to:
Check they all work the same as on live. Check the last two only shows results from docs.ubuntu.com/core, with a note saying so.
=> /search in Flask

templates/engage/_base_engage_markdown.html
* Removing " | Ubuntu and Canonical Legal" from engage page titles when written in md.
- Ensure /engage/developing-android-on-ubuntu page title ends with " | Ubuntu" and not " | Ubuntu and Canonical Legal | Ubuntu"
=> Engage pages in Markdown - removing extraneous bit of title

templates/templates/_navigation-developer-h.html
- Updated links to multipass.run and jaas.ai
- View the site locally in your web browser at: http://0.0.0.0:8001/#developer
- Compare to the [copy doc](https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit?ts=5d66a9f7#)
Fixes #5725
=> Update developer dropdown

templates/internet-of-things/gateways.html
Fix typo on iot/gateways - 'ocker' to 'Docker'
- See that the typo if fixed
Fixes #5721
=> Fix typo on iot/gateways

templates/shared/pricing/_ua-for-infrastructure.html
- added `safe` filter to /pricing/infra template so html elements are correctly escaped
- Visit /pricing/infra, see that the text: "Minimums and exclusions apply. Please refer to the service description for full details." contains a link.
Fixes #5729 
Broken:
Fixed:
=> escape html correctly on /pricing/infra

templates/contact-us/index.html
Added contact form modal js to /contact-us
- previously, clicking the "Contact Us" CTA in the footer of the page would just bring the user back to the same page
- Visit /contact-us, click "Contact us" in the footer, see that a modal with a contact form appears and can be successfully completed
Fixes #5732 
=> fix contact modal launcher in footer of /contact-us

requirements.txt
=> Fix 404ing groups by upgrading blog to v3.0.1

templates/engage/_base_engage_markdown.html, templates/legal/ubuntu-advantage-service-description/index.md, templates/templates/base.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/developing-android-on-ubuntu
- See that twitter cards have titles, images and descriptions
=> Add context for passing markdown variables to base.html

webapp/app.py, webapp/login.py, webapp/macaroons.py, webapp/views.py
Tidy up `app.py` to make it more readable by exporting views into
`views.py` and `login.py`.
QA
--
Check things still work - `/`, `/blog`, `/advantage`.
=> Restructure views

static/sass/_pattern_takeovers.scss, templates/takeovers/_template.html, templates/takeovers/templates.html
- added snapcraft, dark and k8s varients for the takeover templates
- added examples and some help for the new include
- View the site locally in your web browser at: http://0.0.0.0:8001/takeovers/templates
- See that the examples match the designs and the template works as described
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1560
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1558
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1561
=> Add colour variations of the takeovers

requirements.txt
Update to the latest version of
[templatefinder](https://pypi.org/project/canonicalwebteam.templatefinder/)
so that template statements inside Markdown files will be resolved.
This fixes e.g. https://ubuntu.com/legal/ubuntu-advantage-service-description
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5743
QA
--
Go to https://ubuntu-com-canonical-web-and-design-pr-5750.run.demo.haus/legal/ubuntu-advantage-service-description, see a table.
=> Parse markdown files with template parser

static/sass/_pattern_takeovers.scss, static/sass/styles.scss, templates/engage/_base_engage_markdown.html, templates/engage/vmware-to-charmed-openstack.md, templates/index.html, templates/takeovers/_vmware-to-charmed-openstack.html
- created a takeover
- created the engage page
- extended the engage template for webinars
- extended new takeover banners for engage pages
- View the site locally in your web browser at: http://0.0.0.0:8001/ and http://0.0.0.0:8001/engage/vmware-to-charmed-openstack
- Compare to the [brief](https://docs.google.com/spreadsheets/d/1-wWL1DZZ1i1czQVuqrKDCXsqiUQi7dIh9gxPB3aBos8/edit#gid=877682240)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1571
=> Add vmware takeover and engage page

templates/openstack/install.html
Copy doc change; 16.04 -> 18.04
Copy change "16.04" to "18.04
- View the site locally in your web browser at: http://0.0.0.0:8001/ and [/openstack/install](https://ubuntu-com-canonical-web-and-design-pr-5759.run.demo.haus/openstack/install)
- Check this against the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#)
Fixes #5755
=> Copy update install.html

templates/shared/_notice_default.html
Since the recent Vanilla update, notices using u-vertical-center have been rendering incorrectly (switch your browser to jp and head to the homepage to test). This fixes it by using the p-heading-icon class instead.
* Switch notices to use p-heading-icon class
- Switch your browser to japanese and ensure the homepage notice is on a single line.
=> Fix notices styling

webapp/app.py
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5763
QA
--
Go to e.g. `/engage/fr/openstack-made-easy?utm_campaign=mordor` and inspect the source - see that the `utm_campaign` hidden field is populated.
=> Add back campaign params to context

templates/takeovers/_template.html, templates/takeovers/_vmware-to-charmed-openstack.html
As documented in index.html, our takeover logic ensures takeovers with a `lang` attribute are only displayed to users who have their browsers explicitly set to a locale starting with \<lang>\. For global takeovers such as this one, there should be no `lang`.
* Removed `lang` attribute from the new vmware takeover
* Removed the `lang="en"` fallback in the template. (Note that ``"lang=""` would simply hide the takeover for everyone)
- Try various browser languages, ensure the vmware takeover is always part of the loop.
=> Adjust lang setting on the new takeover template

requirements.txt
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5767
QA
--
Go to the demo at https://ubuntu-com-canonical-web-and-design-pr-5770.run.demo.haus/legal/ubuntu-advantage-service-description, check there's no ugly variable below the table.
=> Fix raw template variable in UASD legal page

templates/advantage/index.html, webapp/login.py
Logout doesn't redirect back to the site properly.
Here I've changed the logic of the `/logout` view, so it also can accept a `return_to` paramter, and so the "Sign out" link on `/advantage` now passes a `return_to` parameter to bring you back to `/advantage`.
This is because in general I don't think it's sensible for `/logout` to send you back to the page you came from. In many cases the page you came from would only be available with authentication, and so you'd end up in a redirect loop.
If you want the user to come back to the existing page, you should explicitly set `return_to`, otherwise the user will be sent to the homepage, which I think is sensible.
QA
--
Don't QA this yet.
=> Improve logout

templates/advantage/index.html
Add a terms and conditions link to the token section of the page
- See the terms and condition sentence looks beautiful
Fixes https://github.com/canonical-web-and-design/base-squad/issues/705
=> Add a terms and conditions link to the token section of the page

static/js/core.js
Remove the login option from the global navigation.
- Check there are no JS errors
- See there is no login in the global navigation
=> Remove the login from the global navigation

static/sass/_pattern_takeovers.scss, templates/engage/get-started-with-ai-part-2.md, templates/engage/index.html, templates/index.html, templates/takeovers/_get-started-with-ai-part-2.html, templates/takeovers/index.html
- Create takeover and engage page for getting started with ai webinar part 2 http://0.0.0.0:8001/engage/get-started-with-ai-part-2
- Added the takeover to http://0.0.0.0:8001/takeovers
- Added the engage page to http://0.0.0.0:8001/engage
- View the site locally in your web browser at: http://0.0.0.0:8001/ and http://0.0.0.0:8001/engage/get-started-with-ai-part-2
- See that it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1641) and the [brief](https://docs.google.com/spreadsheets/d/1zHx_YF7akq8ypjDZVOOK8vXryqW-FyeIjIv6EsH4b5k/edit#gid=877682240)
Fixes …
=> Create takeover and engage page for getting started with ai webinar

templates/410.html
See how https://ubuntu.com/gomobile shows 500? This should fix that.
The error is here in sentry: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/3748/?query=is%3Aunresolved
QA
--
Go to `/gomobile`, see a 410 page (rather than a 500).
=> Fix 410 template syntax error

static/sass/_pattern_strip.scss, templates/esm/index.html
Rebuild the ESM page without links to advantage for now.
- See that the copy matches [the copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit)
- Check it matches [the design](https://user-images.githubusercontent.com/36884067/64698699-4722e780-d49b-11e9-9dd0-d2af30f81352.jpg)
Fixes https://github.com/canonical-web-and-design/base-squad/issues/707
=> Build the ESM page ready for the advantage release

static/js/dynamic-contact-form.js
- Add g-recaptcha to the modals
- Go to any page that has a modal an make sure the modal has g-recaptcha
=> Add recaptcha to modals

templates/templates/base.html
added a prefix to the og:image meta data - https://stackoverflow.com/questions/29769054/linkedin-not-picking-up-ogimage
- see that there is no image found on https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fubuntu.com%2Fblog%2Fdesign-and-web-team-summary-17-september-2019
- View the site locally in your web browser at:http://0.0.0.0:8001/blog/design-and-web-team-summary-17-september-2019
- Look at the code and see the og image meta tag looks like `<meta prefix="og: http://ogp.me/ns#" property="og:image" content="https://admin.insights.ubuntu.com/wp-content/uploads/f680/Design-and-Web-Tea …
=> Add prefix for meta image for LinkedIn

templates/templates/base.html
- added prefix to all og tags
- updated the canonical url and the og:url
- View the site locally in your web browser at: http://0.0.0.0:8001/ and other pages
- See that all og: meta data has a prefix and the canonical and og:url is correct
=> Update og metadata and current url"

.env, webapp/app.py, webapp/login.py, webapp/views.py
This defaults the API URL to https://contracts.canonical.com/, but makes it overrideable with the ADVANTAGE_API environment variable.
I then set `ADVANTAGE_API=https://contracts.staging.canonical.com/` in `.env`, so that local development (and demos) will use the staging API, but when released to production it will use the production API.
**NB: This local development state is intended to be *temporary*, so we should undo it as soon as we are able to**
QA
--
`./run`, check it's using the staging API.
`docker build -t ubuntu-com . && docker run -ti -p 8001:80 ubuntu-com`, check it's using the production API.
=> Make advantage API overrideable, and set to staging in local development

templates/download/server/s390x.html, templates/download/server/thank-you-s390x.html
- Added the z15/LinuxONE III option in drawers
- Fixed the vanilla cols on the page
- Fixed the thank-you page look
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/s390x and http://0.0.0.0:8001/download/server/thank-you-s390x
- Compare to the [copy doc](https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit#)
Fixes #1702
=> Update drawers and look of s390x pages

templates/download/iot/installation-media.html
- Updated the mac gunzip command to use the `-c` flag
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot/installation-media
- See that the command reads `sudo sh -c 'gunzip -c ~/Downloads/< image file > | sudo dd of=< drive address > bs=32m'`
Fixes #5803
=> Update iot installation media mac gunzip command

templates/shared/pricing/_ua-for-infrastructure.html
- Updated pricing table
- 24x5 instead of 'office hours'
- Added MAAS
- Removed part of a footnote
- Compare to the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#) and please reslove the edit suggestions and comments.
Fixes #5780
=> Updated pricing table

static/sass/_pattern_lists.scss, templates/templates/footer.html
- Added an RSS social icon to the footer with a hover state
- See that the icon is there, turns oranage on hover, links to /blog/feed
Fixes #5799
=> Add rss icon to the footer

templates/kubernetes/install.html
- Updated links to new juju docs
- See that the link to docs.juju... has been updated and in the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1710
=> Update links to new juju docs

static/sass/_pattern_strip.scss, templates/telecommunications/index.html
- Fixed the contact us button in the banner by removing the z-index from the suru pattern
- See that a modal contact us opens with the top button
=> Fix the contact us button in the banner

templates/pricing/infra.html, templates/shared/pricing/_ua-for-infrastructure.html
- removed bold on support hours
- removed footnotes from office hours and desktop.
- made the {{ extra }} logic better
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description and http://0.0.0.0:8001/pricing/infra
- See that the bold has been removed, ndashes replace hyphens, extra footer is only on /infra, footnotes are removed - [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
Fixes #5848
=> Update pricing table

templates/kubeflow/install.html
Fixed a broken command in the kubeflow tutorial
I tested in my local browser and it works well:
I tested the copy/paste and the version is obtained correctly.
Issue not opened, here's an example of the problematic behavior
Fixes #
With the updated command
=> kubeflow tutorial: fix broken command

templates/kubernetes/docs/release-notes.md
Corrcted the date and inserted a new link into the release notes.
=> K8sdocs-Fix release notes for 1.16

static/sass/_pattern_strip.scss, templates/desktop/statistics.html
- tweaked `p-strip--suru-image` pattern to smooth out suru lines 
- added `is-deep` class to /desktop/statistics
- the same suru is applied to the header strips on /desktop/statistics and /internet-of-things/digital-signage, but the former has a lot less content than the latter, which reduced the height of strip and made the suru looked pixellated. Adding `is-deep` remedies that problem.
- Visit [/desktop/statistics](http://0.0.0.0:8001/desktop/statistics) and [/internet-of-things/digital-signage](http://0.0.0.0:8001/internet-of-t …
=> Smooth suru

templates/engage/ubuntu-lime-telco.html
- Updated the subheading on /engage/ubuntu-lime-telco per @matthewpaulthomas's [suggestion](https://github.com/canonical-web-and-design/ubuntu.com/issues/5332).
- the takeover mentioned in the issue is no longer in rotation and, in any case, its subheading has been changed since the issue was created.
- Visit: http://0.0.0.0:8001/engage/ubuntu-lime-telco
- See that the subheader makes sense in context (i.e. champions open source, not proprietary technology)
Fixes #5332
=> update semantic error on lime telco engage page

static/js/latest-news.js
Rendered the blog titles as HTML on the client.
- Open `base_index.html` line 60 and add limit as an option to the blog feed, as seen below:
```javascript
fetchLatestNews(
{
limit: 5,
articlesContainerSelector: "#latest-articles",
articleTemplateSelector: "#articles-template",
spotlightContainerSelector: "#spotlight",
spotlightTemplateSelector: "#spotlight-template",
gtmEventLabel: "ubuntu.com homepage"
}
)
```
- When reload the homepage and see the rendered blog titled "Deploying Kubernetes Locally – MicroK8s"
Fixes …
=> Render the blog titles as HTML

templates/engage/deeptech.md, templates/engage/index.html, templates/index.html, templates/takeovers/_deep-tech-webinar-takeover.html, templates/takeovers/index.html
- added Deep Tech takeover and engage page
- Refresh the page until you see a takeover with the title "Accelerating deep tech with Ubuntu"
- See that the takeover matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1751#issuecomment-537438531) and the [brief](https://docs.google.com/spreadsheets/d/1z7Dojp0ZXFgLFz9oPwNopvNPdMifTPRUoI-WtckGE84/edit#gid=2113339190)
- Follow the link on the takeover to the engage page
- See that the page matches the …
=> Deep tech webinar takeover & engage

templates/_docs/strips.html, templates/download/index.html
Optimise Disco Dingo pictogram as it's on `/download` - most traffic-ed page.
=> Optimise Disco Dingo SVG pictogram

templates/desktop/developers.html, templates/desktop/partners.html, templates/download/server/thank-you.html, templates/engage/14-04-esm.html, templates/financial-services/index.html, templates/kubernetes/index.html, templates/kubernetes/managed.html, templates/openstack/index.html, templates/pricing/index.html, templates/public-cloud/index.html, templates/security/index.html, templates/shared/contextual_footers/_maas-faq.html, templates/templates/_navigation-community-h.html
'Cos trailing slashes mean redirects. Bad for performance.
I used this magic incantation:
``` bash
find templates -name '*.html' -exec sed -i -E 's|href="([^:]+)/"|href="\1"|g' {} \;
```
QA
--
Either with `./run` or on the demo - go to some pages where I changed links, check the links still work.
=> Remove trailing slashes from local links

static/sass/styles.scss
Add a `font-display:optional` override
- Throttle your connection and test for font fallback
=> Add a font-display:optional override

templates/download/cloud/index.html
- Corrects the AWS and Azure image link targets, fixing #5877.
- Provides `alt` text for all the linked images, since a link with no text is an accessibility problem.
- Replaces the heading text with the images, now that they have `alt` text, avoiding repetition and matching the copydoc.
- View the site locally in your web browser at: http://0.0.0.0:8001/download/cloud
- Follow each of the public-cloud logo links and check that they go to a sensible place.
Fixes #5877.
=> Corrects links, adds alt=, removes redundant headings

templates/templates/base.html
Remove `meta_image` string rendered in base template
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/openstack-made-easy
- Verify the `meta_image` string no longer renders in the template
Fixes #5904
=> Remove meta_image string rendered in base template

templates/kubernetes/docs/release-notes.md
Update the release notes for 1.16-ck1 release
=> Update CK release notes

navigation.yaml, templates/pricing/devices.html, templates/pricing/index.html
- Added a new page at /pricing/devices, based on this [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.l83dv5879ajz)
- Added a card for the page to /pricing
- Visit: http://0.0.0.0:8001/pricing/devices
- See that the page matches the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.l83dv5879ajz), and is laid out correctly.
Fixes #5865
=> Add devices pricing page

templates/engage/shared/_header.html
Updated variable check in engage page header template to prevent broken image from rendering alt text.
- Visit [http://0.0.0.0:8001/engage/openstack-security-whitepaper](/engage/openstack-security-whitepaper), see that no alt text is present in the header (compare it to https://ubuntu.com/engage/openstack-security-whitepaper)
=> update variable check in engage header to prevent broken image

.env, templates/advantage/index.html
Switch to prod API and fix some incorrect commands
- Login and see your free token
=> Switch to production API

templates/engage/index.html, templates/engage/yahoo-japan-case-study.md, templates/templates/base.html
- New Yahoo! Japan case study engage page.
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/yahoo-japan-case-study and http://0.0.0.0:8001/engage
- Compare it to the [brief](https://docs.google.com/spreadsheets/d/1txCEDcgszYy43FEnxEc2lV3EG6vcYpJSnO878T-s5VU/edit#gid=1595677042) and the [copy doc](https://docs.google.com/document/d/1WHnbQO6m6B4puJr8Vc3WxPC9BBJ0E7pvkTXSJUKvCM0/edit)
- Test the form
Fixes #5807
=> Add Yahoo Japan case study

templates/kubernetes/docs/kata.md
Adds example use case for Kata containers in Kubernetes docs
=> Adds an example for using Kata containers

templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md
The revision of the k8s bundle has changed. This updates the relevant links
=> k8s bundle link fix

requirements.txt, static/sass/styles.scss, templates/base_index.html, templates/desktop/developers.html, templates/templates/base.html
As per https://github.com/canonical-web-and-design/canonicalwebteam.image-template/pull/34 - reviewing this branch reviews that PR, so please go and approve that branch. Then I'll get it published and update here.
Fixes https://github.com/canonical-web-and-design/canonicalwebteam.image-template/issues/35
QA
--
`./run`
Go to homepage.
Inspect an image lower down the page, check its markup shows the native syntax.
=> Use native lazy loading if it's available

templates/takeovers/_template.html
- Add a div around the text to keep it verically tight, but centred
- Find the 'An intro to edge computing' takeover and see it is grouped better
Fixes #5884
original
new
=> Keep takeover text vertically tight

static/sass/styles.scss, templates/advantage/_table.html, templates/advantage/index.html, templates/shared/contextual_footers/_ua_further_reading.html, templates/shared/contextual_footers/_ua_legal.html
- Set the further reading contextual footer limit to 3
- Remove the margin from the expanding table panels
- Login
- Scroll to the footer and see only 3 further reading articles are loaded
- If you have paid accounts then open the expanding panels and see there is no margin-bottom
=> Advantage design review

templates/server/index.html
- Update "What's new in 19.10" section on /server
- Compare to the [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#) - *note, it will say 19.04 because the variable PR still hasn't been merged!*
Fixes #5924
=> Update "What's new in 19.10" section on /server

templates/legal/ubuntu-advantage-service-description/index.md
- Corrects “a suitable Ubuntu Advantage support.” to “a suitable Ubuntu Advantage support contract.” 
Fixes #5937
=> Adds missing word “contract”

templates/download/server/arm.html, templates/download/server/power.html, templates/download/server/thank-you-s390x.html
Updated the download server arm and power pages for 19.10
- http://0.0.0.0:8001/download/server/arm
- http://0.0.0.0:8001/download/server/power
- http://0.0.0.0:8001/download/server/thank-you-s390x
- Compare to the copy docs: [arm](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit#), [power](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit#) and [s390z](https://docs.google.com/document/d/1GptXtMfbgOjOmqb8DZCCTRwogkiP_cM95U9Z0gFSt7g/edit#heading=h.cay0nqac462u)
Fixes #5851
=> Update download server arm and power pages for 19.10

navigation.yaml, templates/advantage/index.html, templates/legal/ubuntu-advantage/index.html, templates/legal/ubuntu-advantage/personal/_markdown.html, templates/legal/ubuntu-advantage/personal/index.md
- Adds the new Terms of Service page at `/legal/ubuntu-advantage/personal`, fixing #5931.
- Adjusts the links on `/advantage` to match.
- The terms are just for the Personal subscription — for which you must have chosen “Register” at some point — not for UA subscriptions in general. Therefore on `/advantage` the legal text only makes sense above “Register”, not above “Sign in”.
- Adds a card for the UA-Personal terms to `/legal/ubuntu-advantage`.
- Drive-by: Adds the UA customer terms page to the `/legal/ubuntu-advantage` ribbon navigation too.
This is the first time I’ve actually added a page, so I have probably missed something.
Go to [/legal/ubuntu-advantage](https://ubuntu-com-canonical-web-and-design-pr-5930.run.demo.haus/legal/ubuntu-advantage) and verify:
- ribbon navigation “UA …
=> Adds UA-I (Personal) Terms of Service page

static/sass/styles.scss, templates/desktop/developers.html, templates/download/desktop/index.html, templates/download/index.html, templates/download/iot/index.html, templates/download/iot/raspberry-pi.html, templates/download/server/arm.html, templates/download/server/index.html, templates/download/server/power.html, templates/engage/19-10-webinar.md
- Use label pattern for experimental in feature list on /desktop/developer
- Add `u-no-padding--top` to the first p in each download box to align with the Download button on `/download/desktop` and `/download/server`
- Replace the inline styles with class on the /download page as does not look good on small screens
- /download/iot the Ubuntu Core button removed the chevron
- Spliting the Install Ubuntu Server box into its own strip on download/iot/raspberry-pi to add some space
- Check done comments look ok
=> Small QA issues for 19.10

templates/search.html
- Fixed broken search input layout by implementing Vanilla's search box pattern
- Run the site using the command `./run --env SEARCH_API_KEY=[insert your search api key]`
- View the site locally in your web browser at: http://0.0.0.0:8001/search?q=vanilla
- In Chrome, see that the layout of the search input bar is not broken, and that the search form works
Fixes #5898 
Old:
New:
=> fix broken /search form layout in Chrome, implement vanilla search box pattern

templates/download/iot/raspberry-pi.html
Add 64 bit for Raspberry Pi
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot/raspberry-pi
=> Add 64 bit for Raspberry Pi

templates/index.html
* Removed regional takeovers to give full exposure to 19.10 in FR and DE
- Switch your browser to FR or DE, ensure you see the 19.10 takeover on each homepage refresh
=> Removing regional takeovers for release week

templates/download/flavours.html
Update lubuntu logo
- View the site locally in your web browser at: http://0.0.0.0:8001/download/flavours
- See there is a new lubuntu logo
Fixes #3161
=> Update lubuntu logo on /download/flavours

navigation.yaml, templates/templates/_footer_item.html, templates/templates/_navigation-download-h.html, templates/templates/footer.html
- Removed some dup-sectors in the footer
- Expanded security in the footer
- Fixed the text and link for the raspberry pi 2,3 and 4 in the download mega menu
- Check the footer and the download menu
Partially Fixes #5935
=> Fix footer and rapsberry-pi menu

templates/templates/base.html
- Use single apple-touch-icon
- Use single favicon
- See that the icons are simplier.
=> Use single apple-touch-icon

templates/templates/footer.html
Add pricing section to the footer
- See that there is a pricing section in the footer
Fixes #5973
=> Add pricing section to the footer

templates/takeovers/_1910_takeover.html
Added UTM parameter and value to webinar link on 19.10 takeover
- Click the "Register for the webinar" link in the 19.10 takeover, and see that the url contains the UTM information mentioned in [this issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/5975)
Fixes #5975
=> update 1910 engage webinar cta with UTM value

templates/core/index.html, templates/internet-of-things/appstore.html, templates/internet-of-things/digital-signage.html, templates/security/index.html
Removes `<span hidden>` text from ubuntu.com pages.
This text was reportedly intended “for screen readers to get more context”. This was mistaken, because [`hidden` text is is deliberately ignored by screen readers](http://stevefaulkner.github.io/HTML5accessibility/tests/hidden-2016.html), just as it is by browsers.
If the text would have been useful for screenreaders, the appropriate fix would have been to change `hidden` to [`class="u-off-screen"`](https://docs.vanillaframework.io/utilities/off-screen/).
However, in all these cases the text would not be useful for screenreaders, because it’s immediately preceded by a heading that provides the same context: `<h4 class="p-heading-icon__title">White paper</h4>`, `<h4 class="p-heading-icon__title">Case study</h4>`, and so on. So the better …
=> Removes ineffective and redundant hidden text

static/js/formValidation.js
- made `CaptchaCallback` function available again to recaptcha script tag
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/the-future-of-mobile-connectivity
- Open your browser's dev tools, see that there are no messages related to recaptcha in the console.
- Fill out the newsletter form, see that the recaptcha box is present and working, then submit the form.
Fixes #5984
=> make CaptchaCallback function available to recaptcha script

templates/engage/case-study-acuris.md, templates/engage/index.html
- Created /engage/case-study-acuris according to [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/5927) and [brief](https://docs.google.com/spreadsheets/d/17SMISc4VP9sCkED9cjK-La-ww8pW74teAFwT3CKQk1k/edit#gid=1271849439)
- Added /engage/case-study-acuris card to /engage index
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/case-study-acuris
Fixes #5927
=> add acuris case study

renovate.json
This field was added when ubuntu.com was still running on the old infra. https://github.com/canonical-web-and-design/ubuntu.com/pull/4584
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/4906
- Not much to qa since no impact on the site itself
=> Remove compatibility field renovate

templates/blog/article.html
- added safe filter to meta title on blog articles
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/chromium-in-ubuntu-deb-to-snap-transition
- In the browser tab, see that the title of the page contains an em dash, and not "&#8211" (compare to [live u.c](https://ubuntu.com/blog/chromium-in-ubuntu-deb-to-snap-transition))
Fixes #5928
=> add safe filter to blog article meta title

static/sass/_pattern_table-of-contents.scss, static/sass/styles.scss, templates/about/release-cycle.html
- Added short table of contents to /about/release-cycle
- See that there is a table of contents that links to three different sections on the page
Fixes #5990
=> add table of contents to /about/release-cycle

static/js/core.js
- Remove login from the global nav
- Check that the login in the global nav is removed
=> Remove the login from the global nav

static/js/dynamic-contact-form.js, templates/shared/forms/interactive/_bootstack.html, templates/shared/forms/interactive/_embedded.html, templates/shared/forms/interactive/_general.html, templates/shared/forms/interactive/_kubeflow.html, templates/shared/forms/interactive/_kubernetes.html, templates/shared/forms/interactive/_openstack.html, templates/shared/forms/interactive/_pricing-infra.html, templates/shared/forms/interactive/_robotics.html, templates/shared/forms/interactive/_storage.html, templates/shared/forms/interactive/_support-openstack.html, templates/shared/forms/interactive/_support.html
* Adds UTM params to get-in-touch form data
- Go to https://ubuntu-com-canonical-web-and-design-pr-6003.run.demo.haus/internet-of-things/robotics?utm_campaign=foo
- Click on the "Get to market faster" button
- Ensure the source of the form contains "foo" in the utm_campaign hidden field
=> Add UTM params to get-in-touch form data

templates/engage/shared/_header.html, yarn.lock
- Allow html in the engage header template with `| safe`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/nfv-sdn-openstack
- See that there is no `<br />` like on live
Fixes #6019
=> Allow html in engage header

templates/advantage/_table.html, templates/advantage/index.html
- In signed-out state:
- Specified 14.04 LTS above “Register” button
- Specified 14.04 LTS in enterprise subscription feature table
- In signed-in states:
- Specified 14.04 LTS above `ua` commands
- Review page contents both signed out and signed in
Fixes [Ubuntu-design#199](https://github.com/CanonicalLtd/Ubuntu-design/issues/199)
=> Specifies 14.04 LTS for /advantage

templates/templates/footer.html
Add a resources link to the footer for SEO from engage
- Scroll to the footer and see the new resources link
- Click and check the /engage page loads
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6026
=> Add a resources link to the footer for SEO from engage

templates/kubernetes/install.html
- Fix typo on `/kubernetes/install`
- Check the phrase containing `the stable 1.14 version` makes sense
Fixes #5971
=> Fix typo on /kubernetes/install page

templates/support/index.html
- Update datasheet on /support
- See that the datasheet is downloadable and from October containing 48TB storage [see issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/5920)
Fixes #5920
=> Update UA-I datasheet to show 48TB

static/sass/_vanilla-placeholders.scss
- Slightly increased line-height of `p-p--small`
- Click any of the dropdowns in the main nav, see that the paragraph copy below the headings within have a greater line height than they currently do on the [live site](https://ubuntu.com/)
Fixes #5947
=> fix line height of p-p--small

static/sass/_pattern_table-of-contents.scss, templates/legal/data-privacy/_older-versions.html, templates/legal/data-privacy/_toc.html, templates/legal/data-privacy/index.html, templates/legal/ubuntu-advantage-service-description/_base_legal_markdown.html, templates/legal/ubuntu-advantage-service-description/_toc.html
- added sticky tables of content to /legal/ubuntu-advantage-service-description and /legal/data-privacy
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description and http://0.0.0.0:8001/legal/data-privacy
- See that the tables of content on each page use the [Vanilla pattern](https://docs.vanillaframework.io/patterns/table-of-contents/)
Fixes #5993
=> add (sticky) vanilla table of contents to /legal pages

templates/templates/base.html
- Remove external JS libs used to support legacy IE6-8 browsers
- De-prioritise Google Tag Manager
- Ensure no failings tests or errors
=> Remove redundant js

templates/training/contact-us.html, templates/training/index.html, templates/training/thank-you.html
- Update /training page and add MAAS course to the training page and the contact-us and thank-you page
- Removed the modal forms as they do not reflect the correct marketo forms
- See that the OpenStack operations course has a pdf and the maas section has been added correctly
- Resolve comments in the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
Fixes #5942
=> Update /training page and add MAAS course

templates/legal/ubuntu-advantage-service-description/_base_legal_markdown.html, templates/templates/footer.html
- Table of contents for /uasd page was using the incorrect include
- Removed modal from footer's contact us, request from legal.
- View the site locally in your web browser at: http://0.0.0.0:8001/uasd
- See that the toc is the correct one for the page.
Fixes #6048
=> Update toc for /uasd page

templates/templates/base.html
Removed the other way of doing lazy loading which was sometimes beating the native version. Slightly changed the order of the scripts.
- Check all the images load in the four sections below the feed
- Refresh a bunch of times and check the images load fine
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6040
=> Fix the lazy loading images race condition

static/sass/styles.scss, templates/engage/_base_engage_markdown.html, templates/engage/base_engage.html, templates/engage/shared/_header.html, templates/templates/base.html
- Implement `no-nav v2` for `/engage` pages
- Click on any engage page and check if main navigation is replaced by Ubuntu logo
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1867)
- Go to http://0.0.0.0:8001/engage/whitepaper-containers and check if the logo is dark
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1868
=> Add no-nav v2

templates/engage/_base_engage_markdown.html, templates/engage/index.html, templates/engage/kata-containers-webinar.md, templates/index.html, templates/takeovers/_kata-containers.html, templates/takeovers/index.html
- added kata containers engage page and takeover
- Refresh the page until you see the kata containers takeover
- Compare it to the [brief](https://docs.google.com/spreadsheets/d/1UTIqPG9KSnnBr_r403jzCLD4JhcAmya_axqA2H60kds/edit#gid=2113339190) and [design](https://github.com/canonical-web-and-design/web-squad/issues/1937#issuecomment-548414064)
- Follow the CTA to the engage page
- Compare it to the [brief](https://docs.google.com/spreadsheets/d/1UTIqPG9KSnnBr_r403jzCLD4JhcAmya_axqA2H60kds/edit#gid=2113339190) and …
=> Kata containers engage page and takeover

static/js/navigation.js, templates/templates/base.html
Check the nav exists before adding event listeners.
- Go to https://staging.ubuntu.com/engage/451-cloud-economics and see the recapture is not working
- Go to /engage/451-cloud-economics in the demo and see it does
=> Check the nav exists before adding event listeners

webapp/api/advantage.py, webapp/app.py, webapp/auth.py, webapp/login.py, webapp/views.py
Moved API calls into a separate file, so we can add some extra logic to detect expired macaroons.
Add an handler to clear session and re-login when we detect an expired macaroon.
- Make sure `/advantage` still works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6056
=> Refactor to better handle expired tokens

templates/blog/tag.html
- Add tag name to `/blog/tag/<tag_name>` pages title
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/tag/server
- Make sure the tag name is displayed in the window tab like “GNOME | Ubuntu”, “IBM | Ubuntu”, or “Snaps | Ubuntu”
Fixes #6062 
- Before
- After
=> Add tag name to /blog/tag/<tag_name> pages title

webapp/api/advantage.py, webapp/views.py
Capture advantage API exceptions in Sentry
- Set SENTRY_DSN=`<askme>`
- Go to `/advantage` and login
- Swap to use the staging contracts API
- Go to `/advantage`
- See you have a new exception logged in sentry
=> Capture advantage API exceptions in Sentry

templates/takeovers/_kata-containers.html
* Removing locale from kata takeover.
* The Locale parameter acts as a restrictive filter for takeover display. It should only be set if the takeover is not for a global audienc. Eg. a takeover in french should have its locale set to "fr", a takeover in english should have an empty locale value.
- Change your browser lang to german
- Ensure you can see the Kata takeover.
=> Removed locale from kata takeover

templates/takeovers/_1910_takeover.html
- Switch buttons on Ubuntu19.10 takeover
- Make sure the `Get Ubuntu` button is below the `Register for webinar link`
Fixes #6073
=> Switch Ubuntu 19.10 takeover buttons

templates/engage/dell-openstack-reference-architecture.md
- Create dell openstack reference architecture engage page
- **Note** I have not added a link to the /engage index
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/dell-openstack-reference-architecture
- Read the page to see if it makes sense, test the form
Fixes #6009
=> Create dell openstack reference architecture engage page

templates/engage/dell-k8s-reference-architecture.md
- New Dell k8s reference architecture engage page
- **Note** I didn't add it to the engage index
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/dell-k8s-reference-architecture
- See that it looks ok and the form works.
Fixes #6066
=> New Dell k8s reference architecture engage page

requirements.txt, templates/blog/index.html, webapp/views.py
- Display 11 blog posts per page (and not hide any)
- Check if you see the third blog post which is currently not visible on https://ubuntu.com/blog
- Go to http://0.0.0.0:8001/blog?page=2, compare to https://ubuntu.com/blog?page=2 and check there are no posts left out
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1956
=> Display 11 blog posts per page

templates/openstack/consulting.html
- uploaded datasheet to assets
- updated copy doc
- updated datasheet on /openstack/consulting
- See there is the new datasheet
Fixes #6093
=> Updated datasheet on /openstack/consulting

templates/contact-us/form/index.html
- Add form for kubecon meetings
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us/form?product=kubecon19-SD
- See that the form has kubecon information
- See that filling in the form goes to https://ubuntu.com/blog/ubuntu-kubecon-americas-2019 as the thankyou page
=> Add form for kubecon meetings

static/sass/_pattern_strip.scss, templates/_docs/strips.html, templates/blog/topics/robotics.html
- Created a blog-header suru, added it to /blog/topics/robotics
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/topics/robotics
- See that the suru matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1802#issuecomment-550346588)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1875
=> add blog-header suru to /robotics

templates/blog/internet-of-things.html, templates/blog/topics/robotics.html
- added blog header suru to /blog/internet-of-things
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/internet-of-things
- See that the header strip matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1879#issuecomment-550351474).
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1880
=> IOT header suru

templates/blog/cloud-and-server.html
- added blog header suru to /blog/cloud-and-server
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/cloud-and-server
- See that the header strip matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1883#issuecomment-550282448).
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1884
=> add blog header suru to /blog/cloud-and-server

Dockerfile
- The site was downloading directly from release.ubuntu.com.
- From a bad revert we forgot to add the file list that was downloaded from launchpad.
- `./run build`
- ` docker build --build-arg TALISKER_REVISION_ID=test --tag ubuntu.com .`
- ` docker run -ti -p 8004:80 ubuntu.com`
- go on http://localhost:8004/download/server/thank-you?version=18.04.3&architecture=amd64&country=CA
- make sure that the download doens't come from releases.ubuntu.com
=> Add mirror list to dockerfile build

templates/advantage/index.html
- Add information notification to the ESM dropdown
- Changed the commands too
- Check the screenshot looks ok
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5967
=> Update the messaging in the ESM drop down

templates/livepatch/index.html
- Replaced the contact us illustration with the updated version
- The illustration is now `col-5` and the text is `col-7`
Fixes #6111 
how it should look like
=> Contact us illustration and column width updated

templates/engage/_base_engage_markdown.html, templates/engage/index.html, templates/engage/private-cloud-build-webinar.md, templates/index.html, templates/takeovers/_private-cloud-build-takeover.html, templates/takeovers/index.html
- Added private cloud build takeover and webinar
- Refresh the page until you see a takeover with the title "Lessons learned from 100+ Private Cloud Builds"
- See that it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1976#issuecomment-552889722) and the [brief](https://docs.google.com/spreadsheets/d/1dV2RFXNnpLnZBo_Gx_iuyv3qwhppGSyXE3_3dweLbQY/edit#gid=2113339190)
- Click the CTA to visit the engage page
- See that it matches the [design](https://github.com/canonical-web-and-design/web-squad/iss …
=> Private cloud takeover

webapp/views.py
Add cache-control headers to advantage page
- Check `Cache-Control` is set to `no-cache`
Fixes #6081
=> Add headers to advantage page

templates/blog/press-centre.html
Added new blog header suru to /blog/press-centre
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/press-centre
- See that the header strip matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/1885#issuecomment-553453856).
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1886
=> add blog-header suru to /blog/press-center

Dockerfile, requirements.txt, webapp/views.py
IS are replacing the existing Apache+Squid front-end for ubuntu.com with their new Content-cache. As they do this, they'd like to kill [the redirects they're maintaining there](https://pastebin.canonical.com/p/3TXyyNkWkg/).
The most important part of this is a redirect that uses Apache GeoIP to add `?country=XX` to URLs for `/download/*/thank-you` pages, so that people get directed to a local mirror.
We [haven't quite decided](https://docs.google.com/document/d/1YoCt1iKuveK-NvheICwHXfSv-W5OV5fUcRiad5x9FnY/edit#bookmark=id.fuigb9egut1d) whether this should be handled in the app or not - but in anticipation of them being okay with it being in the app, this is the solution I would go for.
QA
--
Do:
``` bash
mkdir etc
wget http://launchpad.net/ubuntu/+cdmirrors-rss -O …
```
=> Implement GeoIP directly on the /download/*/thank-you pages

requirements.txt
Update canonicalwebteam.blog to 4.0.2 to fix an issue with the blog feeds
https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/128
- Run the site using the command `./run clean && ./run serve`
- Ensure that http://0.0.0.0:8001/blog/feed/ works
- Ensure that http://0.0.0.0:8001/blog/author/agentofchange/feed/ works
https://github.com/canonical-web-and-design/canonicalwebteam.blog/issues/127
=> Fix feed issue with articles without category

templates/engage/private-cloud-build-webinar.md, templates/takeovers/_private-cloud-build-takeover.html
- made sure the phrase "private cloud builds" always uses lowercase.
- Refresh the page until you see the private cloud build takeover.
- See that the phrase "private cloud builds" is always in lowercase.
- Click the CTA, which will take you to the engage page.
- See that the phrase "private cloud builds" is always in lowercase.
Fixes #6129
=> fix case inaccuracy on "private cloud builds"

redirects.yaml, webapp/app.py, webapp/views.py
The Apache+Squid frontend of ubuntu.com will soon be replaced
with the new content-cache, which means redirects defined there will
go away:
https://pastebin.canonical.com/p/3TXyyNkWkg/
Many of these redirects are now redundant, so we won't be preseving them:
- /index_kylin has been removed
- The /phone section has been removed
- The old-style /download URLs with "bits" and "release" are 5 years old now, so we won't preserve them
- /getubuntu/releasenotes pages for <16.04 are no longer supported and mostly no longer exist
- /target= and /ibmz are no longer referenced on the public internet
We're not quite sure how we're going to preserve the geolocation
?country= in the /download/*/thank-you pages. One proposal is in
https://github.com/canonical-web-and-design/ubuntu.com/pull/6124
So, …
=> Port redirects from the legacy Apache frontend

templates/engage/index.html, templates/engage/linux_security_webinar.md, templates/index.html, templates/takeovers/_linux-security_takeover.html, templates/takeovers/index.html
- Add Ubuntu Security takeover
- Add Ubuntu Security engage
- View the site locally in your web browser at: http://0.0.0.0:8001/ & http://0.0.0.0:8001/engage/linux_security_webinar
- Compare to [design](https://github.com/canonical-web-and-design/web-squad/issues/1979) and [brief](https://docs.google.com/spreadsheets/d/1nTvUth-4li92PzKm2HF9FLjw-MwCfHVGVct-yYT-rbk/edit#gid=2113339190)
- Test the engage page on  http://debug.iframely.com/ and https://cards-dev.twitter.com/validator
- Check the takeover is added to http://0.0.0.0:8001/takeovers
- Check the engage page is added to …
=> Add ubuntu security takeover and engage

templates/esm/index.html, templates/livepatch/index.html
Add links to advantage on the ESM and livepatch pages.
- Go to /esm and check it matches [the copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit)
- Go to /livepatch and check it matches  [the copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5965
=> Add links to advantage

static/sass/styles.scss, templates/advantage/index.html
- Added a small amount of padding above the Sign in button
- Make the expanded cell white, rather than dark grey, so that it is seamless with the expansion. (Unexpanded cells can still be dark grey on hover.)
- In a FIPS cell expansion, start with a Vanilla caution: “Older versions of software are used for FIPS-certified packages. Use them only if your organisation requires it.”
- Similarly in a CC-EAL cell expansion, start with a Vanilla caution: “Older versions of software are used for CC-EAL-certified packages. Use them only if your organisation requires it.”
- Run through the following [QA …
=> Simplify row expansion and add FIPS + EAL warnings

static/js/chart.js, static/js/chartData.js, templates/about/release-cycle.html
- Add Kubernetes 1.16 to the chart on `/about/release-cycle`
- Replace `CDk` with `CK` 
- Make sure Kubernetes 1.16 is added to the chart. Check mobile app as well
- See that `CDK` is replaced with `CD`
Fixes #5866
=> Update Kubernetes release chart

templates/index.html, templates/takeovers/_kubecon19.html
- Add a KubeCon19 notice to the homepage
- Compare to the [brief doc](https://docs.google.com/document/d/163wevrv2xmezH8PEmbRZRVhER1NOo64jFQesXkiNXW8/edit?ts=5dd2108c#)
=> Add kubecon19 banner

templates/index.html
- Remove `Kata containers takeover` from home page
- Make sure `kata containers takeover` is not there anymore
Fixes https://github.com/canonical-web-and-design/web-squad/issues/1988
=> Remove kata containers takeover

templates/livepatch/index.html
Update the link to livepatch portal instead of advantage.
- Check the link which states Free for personal use goes to livepatch portal 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6145
=> Update the livepatch link

navigation.yaml, requirements.txt, static/sass/_layout-documentation.scss, templates/docs/base_docs.html, templates/docs/document.html, templates/templates/_navigation.html, templates/templates/footer.html, templates/templates/header_noscript.html, webapp/app.py, webapp/context.py
- Add the discourse-docs module
- Add documentation templates
- Rename `navigation` object to `get_navigation` as there was a clash with the docs module
- Extended the navigation feature to persist to the child nodes also 
- Go to /server/docs
- Check the page renders correctly and matches [the discourse content](https://discourse.ubuntu.com/t/introduction/11322)
- Click through a number of pages and make sure they load correctly
- Do a brief check that the blog navigation still works as expected
- Check a few other sections to …
=> Add server documention

templates/internet-of-things/appstore.html
- Update the title and h1 of the /iot/appstore page per content meeting
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/appstore
- Compare to the [copy doc](https://docs.google.com/document/d/1CKwmPDDtXOIgw-jSZFwzP-qLMc_rS_dUACpHQXlg0fA/edit#heading=h.dfrcx0l5a0jf
)
=> Update title of /internet-of-things/appstore page

templates/advantage/index.html
Extend the definition of free personal subscription to the logged in view.
- Login and check the explanation of free and community contracts is available in both
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6068
=> Define of "free personal subscription" when logged in

templates/openstack/install.html, templates/shared/contextual_footers/_download_documentation.html, templates/shared/contextual_footers/_download_server_guide.html, templates/templates/_navigation-enterprise-h.html
- Updated command in OpenStack install instructions
- Updated links to Ubuntu Server docs
- Added Ubuntu Server docs to the dropdown navigation
- Compare to the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#heading=h.q81t5vetlzyd)
Fixes #6137
=> Update /openstack/install command + update server docs links

templates/download/iot/installation-media.html
Fix spacing in code examples on the IOT installation media page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot/installation-media
- Check that the code examples referenced in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6116) match the suggested format i.e. removing spaces between angle brackets
Fixes #6116
=> Fix spacing in code examples on the IOT installation media page

templates/templates/base.html
Add preconnect for Cloudinary which will have a positive performance impact when loading images served on Cloudinary.
- View source and see that `<link rel="preconnect" href="https://res.cloudinary.com">` is present beneath the `<title>` tag
Fixes #5883
=> Add preconnect for Cloudinary

templates/security/certifications.html
- Updated link target, now that the DoD has reorganised their site
- Changed “Read” to “Download”, to indicate that it will be a download
- Removed external-link icon, since it’s a download (see discussion in #5269)
None
=> Corrects STIG link

static/js/chart.js, static/js/release-chart.js
- Reduce year axis to every other year when labels begin to overlap
- Update breakpoint variable so graph doesn't try to render when table is viewed instead causing errors in the console
- Resize the browser and see that when the labels on the year axis on the release charts start to get close to each other they change to every other year, before they turn into tables
Fixes #6139
=> Fix bugs in eol charts

templates/download/desktop/thank-you.html
On /download/desktop/thank-you, changes “Do you want to upgrade your OS?” link from “Installation instructions” to “How to upgrade”.
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop/thank-you?country=
Fixes #5361.
=> “Installation instructions” > “How to upgrade”

templates/public-cloud/index.html
- Updated /public-cloud based on the [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#heading=h.gec9pmwcxl6m)
- Check that the page matches the copy doc, and the page looks good.
Fixes #6215
=> update /public-cloud based on copy doc changes

requirements.txt, webapp/views.py
**This is a replay of https://github.com/canonical-web-and-design/ubuntu.com/pull/6096**
---
IS are replacing the existing Apache+Squid front-end for ubuntu.com with their new Content-cache. As they do this, they'd like to kill [the redirects they're maintaining there](https://pastebin.canonical.com/p/3TXyyNkWkg/).
The most important part of this is a redirect that uses Apache GeoIP to add `?country=XX` to URLs for `/download/*/thank-you` pages, so that people get directed to a local mirror.
We [have the go-ahead](https://docs.google.com/document/d/1YoCt1iKuveK-NvheICwHXfSv-W5OV5fUcRiad5x9FnY/edit#bookmark=id.fuigb9egut1d) to handle this in the app, and then simply prevent those pages from being caced with `cache-control: no-cache`.
QA
--
Do:
``` bash
mkdir etc
wget …
```
=> Use MaxMind GeoIP database to calculate country

templates/aws/pro.html
Update the link on the hero CTA
- check that the launch Ubuntu Pro button in the hero good to AWS and not open the contact model
=> Update link on the AWS pro page

templates/public-cloud/index.html
Updated the public cloud page copy and changed the datasheet.
- Removed the bullet points from the top of the page
- Changed the datasheet to https://assets.ubuntu.com/v1/feafb61c-Ubuntu_Pro_AWS_04.11.19.pdf
- Removed the section at the end of the page
- Check https://ubuntu.com/public-cloud against the [copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit?ts=5de57c60#) and accepting my suggestions if correct
Fixes #6225
=> Updated the public cloud page

navigation.yaml, templates/automotive/base_automotive.html, templates/automotive/index.html, templates/templates/_navigation-enterprise-h.html
- Built the automotive page
- Added the link to the IoT navigation
- Added the link to the enterprise menu under IoT and sectors
- See that the copy matches the [copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#)
- See that the page matches [the design](https://user-images.githubusercontent.com/36884067/70165219-6efca280-16ba-11ea-8944-79389b6b491b.jpg)
- See that in the enterprise menu there is a link to automotive in the IoT section and the sectors section
Fixes #6174 …
=> Build automotive page

templates/aws/pro.html
Removed mention of landscape from Ubuntu Pro from the matrix
Removed mention of landscape from Ubuntu Pro 3x3 table
- Compare the demo with the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#) and accept the changes that are correct.
Fixes #6227
=> Remove mention of landscape from Ubuntu Pro

package.json, templates/public-cloud/index.html
- Fix typo in the partners logo heading
- Apply image template to thumbnail images
**Note:** The image template won't work with the partners logos because we don't know the dimensions of the images. See [this issue](https://github.com/canonical-web-and-design/canonicalwebteam.image-template/issues/38).
- See that the images load for the following sections:
- Fast service deployment with Juju
- The best management and support
- Developers' favourite
- Ready to get started
Fixes #6221
=> Apply image template to public cloud page

templates/security/index.html
Changed the link of the sec page to https://ubuntu.com/engage/linux_security_webinar
Change the link for the "Watch the Ubuntu security webinar" to https://ubuntu.com/engage/linux_security_webinar on ubuntu.com/security
- Check the changes against the [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit) and accept all changed.
Fixes #
=> Changed the link to other sec takeover

templates/download/raspberry-pi.html
As requested by Lukasz Zemczak. This prepares for the imminent release of 19.10.1 of the Raspberry pi images.
=> Update image links for new raspberry pi image

templates/index.html, templates/takeovers/_template.html, templates/takeovers/_ubuntu-masters-takeover.html
Build masters takeover
- Refresh the page until you see the takeover with the heading "Ubuntu Masters: the masters speak"
- See that the takeover matches [the design](https://user-images.githubusercontent.com/36884067/70227054-d4e43b00-1749-11ea-9722-ae7c13f10eff.jpg)
- See that the copy matches [the brief](https://docs.google.com/document/d/1vbdQVEmoEzkh8j6dNYA0d1wtCnllOCHwCQ1GHlnhJhA/)
Fixes #6178
=> Build masters takeover

navigation.yaml, templates/engage/index.html, templates/engage/wslconf.html, templates/legal/data-privacy/events.md, templates/legal/data-privacy/index.html
- Built WSLConf enage page
- Built events data privacy page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/wslconf
- Check that the page matches the [copy doc]
(https://docs.google.com/document/d/1X_sAqWQZZVj73I6aY-oILDN4d5FuYTZTXebv6JQoLjQ)
- Click the signup button and see that there is a modal that allows you to register for the conference
- Disable JS and see that there is a "Register on eventbrite" button which takes you to the eventbrite page in another tab
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy/events
- Check that …
=> Build WSLConf engage page

templates/automotive/index.html
- updated copy doc meta url to correct one
- using the copy doc [browser extension](https://github.com/canonical-web-and-design/ubuntu-copy-docs), see that the link to the copy doc is correct
Fixes #6256
=> update /automotive copy doc link

templates/templates/footer.html
Fix the button padding in the footer
- Scroll to the footer and see the contact us button has the same padding
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6245
=> Fix the button padding in the footer

templates/automotive/index.html
- added illustration per [copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#)
- see that the header now includes the illustration shown in the [copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#)
Fixes #6257
=> add header illustration

static/sass/styles.scss, templates/internet-of-things/index.html
- Add the automotive tile to the IoT page
- Replaced images on the IoT page with the [image template](https://github.com/canonical-web-and-design/canonicalwebteam.image-template)
- See that the tiles (digital signage, robotics, gateways, automotive) match [the design](https://user-images.githubusercontent.com/36884067/70456589-4bfd3480-1aa6-11ea-9d38-f975e03b29e6.jpg)
Fixes #2150
=> Add automotive tile to IoT page

static/sass/styles.scss
Remove the override which is making images far to large.
- View the site locally in your web browser at: http://0.0.0.0:8001/download/flavours and http://0.0.0.0:8001/desktop/features
- see that the matrix images look better then the live versions of the site.
=> Remove the matrix image override

templates/internet-of-things/contact-us.html, templates/internet-of-things/thank-you.html
- added a networking specific contact us & thank you page to /internet-of-things/contact-us
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/contact-us?product=networking
- See that the page has copy referring specifically to networking
- Visit /internet-of-things/thank-you?product=networking
- See that the page has copy referring specifically to networking
Fixes #6262
=> add networking as a product to /internet-of-things contact us page

static/sass/styles.scss, templates/advantage/index.html, webapp/views.py
- Added expandable information to the contract name
- Display the account name as a table header.
- It's unlikely you have enterprise contracts to test
- Check the code and screenshot is ok
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6155
=> Add contract details to the expanding name

templates/engage/_base_engage_markdown.html, templates/engage/index.html, templates/engage/vmware-to-charmed-openstack.md, templates/index.html, templates/takeovers/index.html
- Updated /engage/vmware-to-charmed-openstack to match [copy doc](https://docs.google.com/document/d/13aUs6sT_Z4kTv1-KiISD22yqh_1VOw9xLLqEMftJZyU/edit#)
- Refresh the page until you see the VMWare to Charmed Openstack takeover, click the CTA, see that the page matches the [copy doc](https://docs.google.com/document/d/13aUs6sT_Z4kTv1-KiISD22yqh_1VOw9xLLqEMftJZyU/edit#), and that both CTAs work
Fixes #6090
=> Vmware engage update

templates/engage/cyberdyne.md, templates/engage/index.html
- added /engage/cyberdyne according to the [design](https://github.com/canonical-web-and-design/web-squad/issues/2159#issuecomment-567041059) and [copy doc](https://docs.google.com/document/d/17JI-RzetZYq5GZF9COAuh-uHG2yHI2pGy25ePdfA9Qk/edit).
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cyberdyne
- See that the page matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/2159#issuecomment-567041059) and [copy doc](https://docs.google.com/document/d/17JI-RzetZYq5GZF9COAuh-uHG2yHI2pGy25ePdfA9Qk/edit).
- Test the page on …
=> Cyberdyne engage

templates/download/server/index.html
- Added multipass info to /download/server, according to [design option A](https://github.com/canonical-web-and-design/ubuntu.com/issues/5277#issuecomment-566149547) and the [copy doc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit#)
- Includes a "Download" CTA that goes to the relevant install page for your OS on multipass.run/docs (if JS is disabled, just goes to multipass.run/docs)
- See that the pages matches the [design](https://github.com/canonical-web-and-design/ubuntu.co …
=> add multipass download info to /download/server

templates/engage/_article-card.html, templates/engage/index.html
- moved re-used markup on /engage into a partial, making it easier to add new entries.
- See that the page looks identical to https://ubuntu.com/engage
=> use article card template on engage index

templates/download/desktop/index.html, templates/download/server/index.html, templates/download/shared/_multipass-install.html
Added multipass download link to page as per the [copy doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#heading=h.9lozrwd819is).
Added the multipass download strip from /download/server to the download/desktop page
- Compare it to the copy doc and accept the changed content
Fixes #
=> Added multipass download link to page

templates/engage/index.html, templates/engage/intro-to-microk8s-webinar.md, templates/index.html, templates/takeovers/_intro-to-microk8s.html, templates/takeovers/index.html
added /engage/intro-to-microk8s-webinar and associated takeover
- Refresh the page until you see the "Intro to MicroK8s" takeover
- See that it matches the [brief](https://docs.google.com/spreadsheets/d/1FB-iCI2NIXbgENH4U8svB6MMI4FQjmAp3DnfJ5Ug9Ak/edit#gid=1271849439)
- Click the CTA to take you the engage page
- See that it matches the [copy doc](https://docs.google.com/document/d/1FCaFi5ZuP_pPMF2POu3ySaB00yt60Qo-nrNJZ9jwhFw/edit)
- Test the engage page on https://cards-dev.twitter.com/validator, see that it pulls through the …
=> add intro to microk8s takeover and engage page

templates/engage/index.html, templates/engage/linux-enterprise-whitepaper.md, templates/index.html, templates/takeovers/_linux-enterprise.html, templates/takeovers/index.html
added /engage/linux-enterprise-whitepaper and associated takeover
- Refresh the page until you see the "Ubuntu Desktop for the enterprise" takeover
- See that it matches the [brief](https://docs.google.com/spreadsheets/d/1NLbSg_HAaLEknFNk30CJ2kwqxjaL7iUuw-fZQW3YGfM/edit#gid=1595677042) and the [design](https://github.com/canonical-web-and-design/web-squad/issues/2162#issuecomment-567103222)
- Click the CTA to take you the engage page
- See that it matches the [copy doc](https://docs.google.com/document/d/1rycA9y7Sx5bdwbRMtfBVU9nAkz …
=> add linux enterprise whitepaper engage page

templates/engage/vmware-to-charmed-openstack.md
Updated meta description on /engage/vmware-to-charmed-openstack
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/vmware-to-charmed-openstack
- Inspect the page, see that the meta description is "Migrate from VMware to Charmed OpenStack to reduce costs and increase infrastructure efficiency."
=> update meta description

templates/esm/index.html
Reduce 5 free machines to 3 for UA on ESM
- Check it matches [the copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#)
Fixes: https://github.com/canonical-web-and-design/ubuntu.com/issues/6312
=> Reduce 5 free machines to 3 for UA on ESM

templates/core/index.html
Add Download Ubuntu Core to contextual footer in core
Update the links to `https`
- Check it matches the [copy doc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6313
=> Add Download Ubuntu Core to contextual footer in core

templates/templates/_navigation-enterprise-h.html
- Added Ceph to the enterprise dropdown
- Compare to the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit)
Fixes #6329
=> Add ceph to enterprise dropdown

templates/containers/contact-us.html, templates/kubeflow/contact-us.html, templates/kubernetes/contact-us.html, templates/openstack/contact-us.html, templates/training/contact-us.html
Fix the malformed with for the inclusion of forms across the site
- Go to following pages and see the form submits and you end up on the thank you page
- /containers/contact-us 
- /kubeflow/contact-us
- /kubernetes/contact-us
- /openstack/contact-us
- /training/contact-us
=> Fix the malformed with for the inclusion of forms

templates/ceph/index.html
- Update heading on /ceph page
- Add '2' weeks
- See that the heading 'Ceph is better on Ubuntu' is now 'Ceph storage done right' from the [copy doc](https://docs.google.com/document/d/17VnBygL00hXjLSECXMo3bF7KOCT5oZGFBLo6Qd6rF3A/edit#heading=h.4h5l8ixjazx1) and 'Built in weeks...' is 'Built in 2 weeks...' 
Fixes #6331
=> Update heading on /ceph page

templates/download/shared/_verify-checksums.html
Use the `system` variable to dynamically set the "help on installing" tutorial link instead of always pointing to server. I had to add a conditional as the system for server is "live-server" and we need "server".
- Go to /download/desktop/thank-you?country=US&version=18.04.3&architecture=amd64
- Check the "Help on installing" link points to the desktop tutorial and returns to the correct thank you page.
- Go to /download/server/thank-you?version=18.04.3&architecture=amd64
- Check the "Help on installing" link points to the server …
=> Fix the install help link on the download thank you page

static/sass/_pattern_strip.scss
- fixed `.p-strip-suru-half-top` on small screens
- View the page on a small screen, see that the suru isn't broken.
Fixes #6340 
**Fixed:**
**Broken:**
=> fix typo in suru pattern

static/js/dynamic-contact-form.js, templates/shared/contextual_footers/_iot_newsletter_signup.html
Make the checkbox id unique.
Remove the recapture from the foot newletter sign up
- Go to http://0.0.0.0:8001/internet-of-things/gateways
- Scroll to the bottom and hit "Get in touch"
- Fill in the form and on the final step check both the "I agree to receive information about Canonical’s products and services." check box and recapture works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6336
=> Fix the opt-in checkbox in the dynamic contact us form

templates/engage/index.html, templates/engage/microk8s-451research.md, templates/index.html, templates/takeovers/_451-microk8s.html, templates/takeovers/index.html
- Added MicroK8s/451 Research takeover and engage page
- Refresh the page until you see a takeover with the title "Kubernetes for IoT developers", check it matches the [brief](https://docs.google.com/spreadsheets/d/1UFVnl9Cr2FwlyMJeqfu2VGWCediSNqOHKbL9WjNcCmo/edit#gid=2113339190) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2189#issuecomment-571974257)
- Click the CTA to go to the engage page
- Check it matches the [copy doc](https://docs.google.com/document/d/1ItdW6aLf2v8IHLm8jgEIgtWHK0Tqa9aUkUIDFUePa …
=> 451 microk8s takeover

static/sass/styles.scss
Removed the top margin of the contextual menu in the breadcrumb navigation to avoid it being overlapped by the main navigation
- Hover over `topics` in the breadcrumb navigation
- See that the contextual menu is not partially covered by the main navigation
Fixes #6345
https://user-images.githubusercontent.com/501889/72150818-645eb880-339e-11ea-8f51-8b37cae9ca35.png
=> Prevent breadcrumb contextual menu overlap

templates/esm/index.html
- See that it links to the /advtange page and compare to the [copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit)
Fixes #6347
=> Update link to /advantage page on /esm

templates/index.html
- Takedown linux security takeover
- See that the linux security takeover is no longer in rotation
=> Takedown linux security takeover

templates/openstack/install.html
Command installs from 'edge' channel while expected output is displayed from 'beta' channel.
=> Update expected command output.

Dockerfile
We've agreed to use `BUILD_ID` instead of `TALISKER_REVISION_ID` for the docker build arg.
QA
--
``` bash
DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=fish --tag ucom .
docker run -ti -p 8777:80 ucom
```
Check http://localhost:8777 works.
Run:
``` bash
$ curl -I http://localhost:8777
X-VCS-Revision: fish
```
^ Check the build ID is there
=> Switch to BUILD_ID in the docker build

static/js/tutorials.js, static/sass/_layout-tutorial.scss, templates/tutorials/tutorial.html
Add feedback section to final step in tutorial page
- Go to `/tutorials` and click through to a tutorial
- Go to the last section of the tutorial
- See that there is the same smiley face feedback section as the current tutorials site
- Click the options and see that they are sending the correct events (this chrome extension can help with that: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en)
Fixes #6360
=> Add feedback section to tutorial page

requirements.txt, static/sass/_layout-tutorial.scss, templates/templates/small-footer.html
Gave minimum height to tutorial section on dropbox so footer is positioned at the bottom edge of the screen
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials/tutorial-install-ubuntu-desktop
- Find a section of the tutorial which has a short amount of content, less than your viewport height
- See that the footer is positioned at the bottom edge of the screen
Fixes #6372
=> Add min height to tutorial section

static/js/tutorials.js
Fix loading of tutorial page with timeout parameter to run the scroll after the event loop
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials/tutorial-install-ubuntu-desktop
- Check that the page loads scrolled to the top so the header and navigation are visible
- Navigate between sections using both the side nav and the arrows at the bottom of each section
- Check that the page always loads scrolled to the top so the header and navigation are visible
Fixes #6359
=> Fix loading of tutorial page

templates/security/certifications.html
- Change "comming Autumn 2019" to "in progress."
- Compare to the [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit#)
Fixes #6339
=> Tweak 18.04 certification status

static/sass/_layout-tutorial.scss
Prevent wide pre section from stretching out the parent flex column
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials/install-microk8s-on-a-mac-using-multipass#testing-add-ons
- See that the width of the tutorial section column (with the title `5. Validating the charm) doesn't extend beyond the site's width
Fixes #6377
=> Prevent wide pre section stretching out the parent

templates/tutorials/index.html, webapp/app.py
Fix pagination so that it doesn't link to a final blank page and whilst on last page disables the "next page" button
- Use the pagination to get to the last page
- Check that the final page still has some cards
- Check that the "next page" button in the pagination is disabled
Fixes #6389, #6390
=> Fix tutorials pagination

templates/tutorials/index.html
Allow HTML in tutorial cards
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials?topic=community
- Check that the card for "How to write a tutorial" is rendered HTML properly
Fixes #6395
=> Allow HTML in tutorial cards

static/sass/_layout-tutorial.scss
Remove left padding on tutorial section in tablet view
- Resize the browser to tablet
- Check that the padding is even both sides of the tutorial section
Fixes #6388
=> Remove padding from tutorial in tablet view

templates/tutorials/tutorial.html
Add fallback to tutorial duration so if no duration exists it defaults to 0
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials/deploy-clustered-redis#well-done
- See that the remaining time at the end of the tutorial is 0
Fixes #6418
=> Add fallback for tutorial time remaining

templates/tutorials/tutorial.html
Fix page jump on tutorial page
- Click through to a tutorial page
- Make sure the content doesn't scroll down to the beginning of the tutorial
Fixes #6407
=> Fix tutorial page jump on load

static/sass/styles.scss, templates/tutorials/index.html
- Remove shallow style for tutorial cards section
- Remove margins from search filters
- Remove dark text on card muted headings
- Check that the section wrapping the tutorial cards is not shallow
- Check that there are no bottom margins on the search filters
- Check that the text colour on the card topic headings is mid gray
Fixes #6402, #6401, #6403
=> Fix tutorials style issues

templates/security/index.html
Replaced aubergine background (it was an image) with a suru template.
Fixes #2219
=> /security added suru to hero section

navigation.yaml, templates/kubernetes/docs/ldap.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/supported-versions.md
-   Adds supported versions page
-   Minor updates to other pages
=> Updates for k8s docs

templates/takeovers/_ubuntu-masters-takeover.html
Update the Ubuntu Masters takeover text
- OPTION 4
Title: 200 billion requests per day, 6 data centres... 5 people
Text: Hear Adobe's Joe Sandoval met massive requirements with a lean approach
Call to action: Watch the keynote
Link for CTA: https://www.youtube.com/watch?v=IUgODRm9Soc&list=PLwFSk464RMxmYizQiyu-yNJ9ZtEISJYqN&index=7&t=580s
Secondary call to action (optional): Read more about our Ubuntu Masters event
Link for secondary CTA: ubuntu.com/masters-conference
=> Update the Ubuntu Masters takeover text

templates/internet-of-things/robotics.html
Added a link to https://multipass.run/ in the text.
Added a link to https://multipass.run/ in the text.
- Check the page against the [page](https://ubuntu.com/internet-of-things/robotics) and [copy doc](https://docs.google.com/document/d/1cDxhPCQbHA0r6n9JXNmO50ANLPZhCFdgwATX6f90guU/edit#) and accept the changes.
Fixes #6428
=> Added a link to multipass

templates/templates/_navigation.html, templates/tutorials/tutorial.html
This supports #0 style hashes in the tutorials, by
redirecting them to the appropriate section.
I've also changed the format of the section IDs to {num}-{description}
to avoid clashin with IDs in the global nav, and I've updated the global
nav JavaScript to handle IDs it doesn't recognise more gracefully.
QA
--
Go to https://ubuntu-com-canonical-web-and-design-pr-6432.run.demo.haus/tutorials/deploy-clustered-redis#0, see that you end
up at https://ubuntu-com-canonical-web-and-design-pr-6432.run.demo.haus/tutorials/deploy-clustered-redis#1-welcome and it works.
=> Support old hash links

static/sass/_global-settings.scss
Switch to using the subset font via Vanilla.
- Check the live site has download 431kb of fonts
- Check this branch loads 143kb of fonts
=> Switch to the subset font

templates/tutorials/tutorial.html
Update the tutorial section pagination links with the correct fragment identifiers
- Go to a tutorial
- Use the pagination at the bottom of each section to navigate the tutorial
- Check that the correct section is shown each time
Fixes #6439
=> Fix tutorial pagination

static/sass/_layout-tutorial.scss, templates/tutorials/tutorial.html
Add hover state to tutorial feedback icons
- Navigate to the last step of the tutorial
- Hover over the icons under the "Was this tutorial useful?" section
- Check that the positive response is green when hovered
- Check that the neutral response is orange when hovered
- Check that the negative response is red when hovered
Fixes #6416
=> Add hover state to tutorial feedback icons

templates/engage/anbox-cloud-gaming-whitepaper.md, templates/index.html, templates/takeovers/_anbox-takeover.html, templates/takeovers/index.html
Added anbox gaming takeover and white paper engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/ and see the takeover
- View the engage page http://0.0.0.0:8001/engage/anbox-cloud-gaming-whitepaper
Fixes #6375
=> Anbox takeover and engage page

templates/index.html
> 09:58 <davidcalle> In this case, let's maybe try to get back to 3 takeovers, we have been between 4 and 5 for several months now
> 09:59 <SarahD> +1
> 10:00 <davidcalle> Maybe: Anbox, MicroK8s, VMware
> 10:00 <davidcalle> To cover 2 big topics + 1 shiny thing
> 10:01 <SarahD> Official marketing terminology
> :nerd_face:
> 10:01 <sewaddle> that sounds good to me
> 10:06 <sewaddle> shall we do that?
> 10:07 <SarahD> yep fine with me
- See that there are just anbox, microk8s and vmware takeovers live
=> Change takeover rotation

templates/tutorials/tutorial.html
Prevent tutorial breadcrumb from wrapping unnecessarily
- Resize your viewport to mobile size (~320px wide)
- Check that the breadcrumb of the tutorial title doesn't wrap unnecessarily i.e. unless it spans more that the viewport width
Fixes #6422
=> Prevent tutorial page breadcrumb wrapping

templates/tutorials/index.html
Only show tutorials hero on first page
- Check that the first page has the suru hero/header
- Click through the pagination to other pages and check that there is no suru hero/header
Fixes #6406
=> Only show tutorial hero on first page

templates/index.html
Include ubuntu masters takeover in the rotation.
=> Changed takeover rotation

templates/kubeflow/consulting.html, templates/kubeflow/features.html, templates/kubeflow/index.html, templates/kubeflow/install.html
Add suru to top of Kubeflow pages
- Check that the Kubeflow homepage and all it's subpages have a suru at the top of the page
Fixes #6453
=> Add suru to kubeflow pages

templates/kubernetes/managed.html
removed `is-deep` from hero strip
- /kubernetes/managed
[Fixes](https://github.com/canonical-web-and-design/ubuntu.com/issues/6459)
=> padding fixed

templates/tutorials/index.html, webapp/app.py
Sort tutorials by least difficult as default
- Check that the tutorials are sorted by least difficult by default
- Check that changing the "Sorted by" menu does what you'd expect
Fixes #6400
=> Sort tutorials by difficulty

static/sass/_layout-tutorial.scss
Override `h3` styles inside tutorial sections with the styles of `h5`
- Check that the headings *within* a tutorial are using the same styles as `p-heading--five`
Fixes #6409
=> Add style override for tutorial headings

templates/kubernetes/managed.html, templates/openstack/managed.html, templates/shared/_trusted-managed-service-provider.html
- Added trusted managed service provider section to /kubernetes/managed and /openstack/managed
- See that the page matches the [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit#)
- Visit http://0.0.0.0:8001/openstack/managed
- See that the page matches the [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#)
Fixes #6355 & #6356
=> Trusted managed service provider section

navigation.yaml, templates/automotive/index.html, templates/kubeflow/what-is-kubeflow.html
Add "What is Kubeflow?" page
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?pli=1#heading=h.tjha1bhkvpeu)
Fixes #2226
=> Add new kubeflow page

templates/templates/_navigation-enterprise-h.html
Add anbox-cloud.io to the enterprise dropdown in 2 places
- View the site locally in your web browser at: http://0.0.0.0:8001/server#enterprise
- Compare to the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit?ts=5e2ee865#) and resolve the comments
=> Add anbox-cloud.io to the enterprise dropdown

static/sass/_pattern_footer.scss, templates/templates/_footer-copyright-and-legal.html
Make the legal information, data privacy and report a bug on this site links display inline on tablet view and up
- Resize the viewport to tablet size (~768px)
- Check that the legal information, data privacy and report a bug on this site links are displayed inline
Fixes #6357
=> Display footer links inline on tablet and up

templates/kubernetes/_get_ebook.html, templates/kubernetes/install.html
Update illustrations on /kubernetes/install page
- Check that the illustrations on the page are the same as in the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#heading=h.mj4mzhhwhrtm)
Fixes #6457
=> Update kubernetes install illustrations

navigation.yaml, templates/kubeflow/features.html, templates/kubeflow/shared/_learn-more.html, templates/templates/footer.html
Update kubeflow features page illustrations
Add kubeflow to the footer as it was oddly missing
- View the site locally in your web browser at: http://0.0.0.0:8001/kubeflow/features
- Compare to the [copy doc](https://docs.google.com/document/d/1DT5nCRSJH-OkvDmlyKh6vVhofeHPHZJHTTBDNu44wCY/edit) and resolve the comments
Fixes #6467
=> Update kubeflow features page illustrations

templates/kubeflow/consulting.html, templates/kubeflow/shared/_learn-more.html
Updated the illustrations on /kubeflow/consulting
- Check that the illustrations on the page match [the copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit)
Fixes #6470
=> Update illustrations on kubeflow consulting page

templates/kubeflow/consulting.html
Remove extra spacing on kubeflow consulting page
- Check that the spacing between text is less than on the live site
Fixes #6469
=> Remove extra spacing on kubeflow consulting page

templates/legal/ubuntu-advantage-service-description/index.md, templates/shared/pricing/_ua-for-infrastructure.html
- Update the text of the /legal/ubuntu-advantage-service-description page
- View the site locally in your web browser at: http://0.0.0.0:8001/uasd
- Compare to the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit#)
Fixes #6482
=> Update the Ubuntu Advantage Service Description

webapp/app.py, webapp/views.py
- *only* catch explicitly 401s, re-raise all other `http_errors`
- limit the `try: except` block to just the bit that we think should return 401
- send a bit more data to sentry for us to debug when people do hit 401 errors
`./run`
- Go to http://0.0.0.0:8001/advantage and log in
- Switch to using staging API
- Reload http://0.0.0.0:8001/advantage
- Log in again
- Check it all works as expected
=> Improve error handling for 401s

templates/kubernetes/features.html
Updated the illustrations on /kubernetes/features
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/features
- Check that the illustrations match the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#)
Fixes #6455
=> Update kubernetes fetaures page illustrations

templates/kubernetes/partners.html
Update illustrations on /kubernetes/partners
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/partners
- Check that the illustrations on the page are the same as the [copy doc](https://docs.google.com/document/d/1vRlHxWr7pxstx5pOtqXWrIviXtdPvW2gd3-mNeYQKp0/edit#heading=h.oqi22mc8fijl)
Fixes #6458
=> Update illustrations on kubernetes partners page

navigation.yaml
- Added /robotics to IoT sub nav
- Added IoT sub nav to /robotics
- Check that /robotics is in the sub nav
- Go to /robotics
- Check that the sub nav from /internet-of-things is on the page
Fixes #2256
=> Add robotics to IoT sub nav and sub nav to robotics page

templates/kubernetes/managed.html, templates/openstack/managed.html
Remove the shared/_trusted-managed-service-provider.html partial from /kubernetes/managed and /openstack/managed
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/managed and http://0.0.0.0:8001/openstack/managed
- See that the section has been removed per comments in the [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit?ts=5e2efd6b#heading=h.fghanvvlxzai)
@anasereijo should I change the strips background?
=> Remove the shared/_trusted-managed-service-provider.html partial

static/sass/_layout-tutorial.scss, templates/tutorials/tutorial.html
Bumped each heading level down one in tutorials sections to fix hierarchy issues
- Click through to a tutorial, change heading tags in the browser console to see that each heading uses the style of the heading level below it
Fixes #6480
=> Change tutorial section heading sizes

templates/kubeflow/install.html
Updated the illustrations on /kubeflow/install
- Check that the illustrations are the same as in the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit#heading=h.pt6iw0mepowo)
Fixes #6468
=> Update illustrations on kubeflow install page

templates/openstack/what-is-openstack.html
Move the openstack diagram at the top of the page to it's own section and made it full width.
- See that the diagram at the top of the page has it's own section and is full width
Fixes #6463
=> Move openstack diagram to own section

templates/embedded/index.html
- Update banner illustration on /embedded page
- View the site locally in your web browser at: http://0.0.0.0:8001/embedded
- See that the illustrations has been updated per the [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit#) and accept them please
Fixes #6513
=> Update banner illustration on /embedded page

templates/livepatch/index.html
- Remove anchor on /advatage link on livepatch page
- View the site locally in your web browser at: http://0.0.0.0:8001/livepatch
- See that the button 'Get Ubuntu Advantage' no longer has a anchor
Fixes #6110
=> Remove anchor on /advatage link on livepatch page

templates/kubeflow/features.html
- Remove asset server resizing to increase screenshot legibility
- View the site locally in your web browser at: http://0.0.0.0:8001/kubeflow/features
- Compare to live and see that the screenshots are a bit clearer
Fixes #6466
=> Remove asset server resizing to increase screenshot legibility

templates/containers/contact-us.html, templates/containers/thank-you.html, templates/engage/ai-ml-ubuntu.html, templates/kubeflow/features.html, templates/kubeflow/index.html, templates/legal/ubuntu-advantage-service-description/index.md, templates/rfp/index.html, templates/takeovers/takeunders/_ubuntu-product-month.html, templates/templates/_navigation-developer-h.html
- Rename 'the Charmed Distribution of Kubernetes' or 'the Canonical Distribution of Kubernetes' or 'CDK' to Charmed Kubernetes
- https://ubuntu.com/containers/thank-you - not in copy doc, logic in code
- https://ubuntu.com/containers/contact-us - not in copy doc, logic in code
- [Developer mega menu](https://ubuntu.com/#developer) - [copy doc](https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit)
- https://ubuntu.com/engage/ai-ml-ubuntu  - [copy doc](https://docs.google.com/document/d/1YVPlQYT3jvxb6Yp5OShSiUsmKBPOYOm_fNLJHNsQ6tQ/edit)
- https://ubuntu.com/rfp  - [copy doc](https://docs.google.com/document/d/1OA_Eg1200fHpt7YYkE4qubiWf …
=> Rename CDK to Charmed Kubernetes

templates/pricing/consulting.html
- Add suru banner to /pricing/consulting
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/consulting
- Compare to and resolve the comment in the [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#heading=h.bf26y8ax9nwu)
Fixes #6530
=> Add suru banner to /pricing/consulting

static/sass/_layout-tutorial.scss, templates/tutorials/tutorial.html
Fix the appearance of tutorial step counter when section title is long
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorials/tutorial-burn-a-dvd-on-windows
- Check that the number next to section 3 in the side navigation is a circle
Fixes #6547
https://user-images.githubusercontent.com/554953/73726697-9e00b600-46f5-11ea-84bb-8ef0ad8248a4.png
=> Fix counters on tutorial steps

HACKING.md, navigation.yaml, templates/templates/_navigation.html, templates/tutorials/tutorial.html
Show the title "Tutorials" next to the Ubuntu logo on a tutorial page
- Resize to a mobile viewport width (320px)
- Check that the orange nav with the Ubuntu logo has the text "Tutorials" next to it (see screenshot)
- Check that the same text is present in the orange nav (see screenshot)
- Check on desktop view and make sure the breadcrumb nav isn't duplicated
Fixes #6553
https://user-images.githubusercontent.com/501889/73737022-b8f51980-4739-11ea-80bf-78b2a8e7b5e8.png
=> Show tutorial next to logo on tutorial page

navigation.yaml, templates/_docs/strips.html, templates/kernel/base_kernel.html, templates/kernel/index.html
Add /kernel index page
- See that the page matches the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit)
**Note:** 
- The meta description is missing from the copy doc
- There is a link to a whitepaper in the copy doc which doesn't exist so isn't in this page for now
- There are links to other /kernel pages which don't exist yet so aren't in this page for now
Fixes #5683
=> Build kernel index page

templates/livepatch/index.html, templates/pricing/devices.html, templates/shared/_call-sales.html, templates/shared/pricing/_smart-start-prices.html
- Update illustrations and minor text updates on /pricing/devices
- Updated call sales include to optionally have a border and fixed up /livepatch to use it
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices and http://0.0.0.0:8001/livepatch
- Compare to the [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
Fixes #6531
=> Update illustrations and minor text updates on /pricing/devices

templates/shared/_case-study-itstrategen.html, templates/support/index.html
- Update /support illustrations
- Removed tabs
- NOTE *the call-sales strip will be white when #6549 is merged*
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#heading=h.l3kjw0agnasv)
Fixes #6527
=> Update /support illustrations

static/sass/styles.scss, templates/tutorials/tutorial.html
- Remove scroll to top behaviour when changing tutorial steps
- See that the page jumps straight to the first section of the tutorial
- Click through the steps of the tutorial and see that each one jumps to that section in the browser
Fixes #6554
=> Remove smooth scroll when changing tutorial steps

requirements.txt
Fixes #6566
QA
--
Make sure `SEARCH_API_KEY` is in `.env.local`. If you don't have the key, get it from https://console.cloud.google.com/apis/credentials?project=ubuntu-search-1530889417216. Ask @nottrobin for access.
Now `./run`, go to http://0.0.0.0:8001/search?q=kernel, experience success.
=> Update search to fix error

static/sass/_pattern_strip.scss, static/sass/_pattern_takeovers.scss, templates/templates/_navigation.html
Fix the navigation error in Edge browser
Provide fallback for browsers that do not support background-blend-mode
- Visit the homepage in the Edge 18
- See that the navigation works
- See that the suru strips look better across the site
Fixes #6541
=> Fix the navigation error in Edge browser

navigation.yaml, templates/kernel/index.html, templates/kernel/variants.html
- Add missing paragraph tags around intro copy on /kernel
- Add /kernel/variant
- View the site locally in your web browser at: http://0.0.0.0:8001/kernel/variant
- Check that it matches the [copy doc](https://docs.google.com/document/d/1UVxrF8raNb5Pggj05P0ar_OzV_uwhrTRHv9XRiuM4zs/edit#heading=h.atr230qlrn8h)
Fixes #5685
=> Build kernel variants page

templates/engage/_base_engage_markdown.html, templates/engage/de/migration-von-vmware-zu-openstack.md, templates/engage/es/vmware-a-charmed-openstack.md, templates/engage/index.html, templates/engage/shared/_de_engage_form.html, templates/engage/shared/_es_engage_form.html, templates/index.html, templates/takeovers/_vmware-to-charmed-openstack_german.html, templates/takeovers/_vmware-to-charmed-openstack_spanish.html, templates/takeovers/index.html
- Added German and Spanish versions of the VMWare To Charmed OpenStack takeover and engage pages.
- Also added a Spanish version of the engage form
- Set your browser language to German and refresh the page until you see a takeover with the title "Migration von VMware zu OpenStack". See that it matches the [brief](https://docs.google.com/spreadsheets/d/17rhx6XrSyrr3lUA0HUwIww3xz0cgrdKry1VoCVJchjg/edit#gid=2113339190)
- Follow the CTA on the takeover to the engage page. See that it matches the [copy …
=> ES & DE VMware to OpenStack takeover & engage pages

templates/download/raspberry-pi/index.html
- Fixed typo on /download/raspberry-pi
- On the raspberry-pi 18.04.3 64 bit version
Fixes #6583
=> Fix typo - arm64 vs arm63

templates/support/index.html
- Removed `?w=500` from two screenshots to allow higher res versions to be displayed instead.
- Inspect the screenshots in the "Systems management and security at scale" and "Apply critical kernel patches without rebooting" and see that the original size of each is a lot larger than 500px wide.
Fixes #6528
=> use hi res screenshots on /support

templates/support/index.html
- switched out img elements for image module in order to provide the most appropriate resolution image for a given user
- View the page on both a standard resolution screen and a hi-res/retina screen, see that the screenshots in the "Systems management and security at scale" and "Apply critical kernel patches without rebooting" sections are of good quality.
=> use image module on /support screenshots

templates/engage/de/migration-von-vmware-zu-openstack.md
- Fixed incorrect Marketo form ID on /engage/de/migration-von-vmware-zu-openstack, to match the form ID given in [the brief](https://docs.google.com/spreadsheets/d/17rhx6XrSyrr3lUA0HUwIww3xz0cgrdKry1VoCVJchjg/edit?disco=AAAAI7jLcDg&ts=5e3c5210&usp_dm=true)
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/de/migration-von-vmware-zu-openstack
- Inspect the page, see that the form element has an id of `mktoForm_3507`
=> use correct mkto form on DE vmware engage page

templates/engage/ai-edge-webinar.md, templates/engage/index.html, templates/index.html, templates/takeovers/_ai-edge-webinar.html, templates/takeovers/index.html
- Build AI edge webinar engage page
- Add AI edge engage webinar page to /engage
- Build AI edge webinar takeover
- Add AI edge webinar takeover to /takeovers
- Add AI edge webinar takeover to homepage
- Refresh until you see the takeover titled "Artificial Intelligence at the edge in a 5G world"
- Check that the takeover matches the [brief](https://docs.google.com/spreadsheets/d/11RDq5vNUpgdy3UU_51d-QtGiptq5Fgz_tdOFbgx3zec/edit?ts=5e3d4646#gid=2113339190)
- Go to /takeovers
- Check that the "Artificial Intelligence at the edge …
=> Build AI edge webinar takeover and engage page

templates/engage/_base_engage_markdown.html, templates/engage/dell-kubernetes-webinar.md, templates/engage/index.html, templates/index.html, templates/takeovers/_dell-kubernetes-webinar.html, templates/takeovers/index.html
Created takeover and engage page for Dell K8s webinar
- Refresh the page until you see a takeover with the title "A decision maker's guide to Kubernetes data centre deployments", see that it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/2302#issuecomment-583410319) and the [brief](https://docs.google.com/spreadsheets/d/1T9BEfgdYrkMuxMbJm_KZWwYoMH7eZYPq8eotk6MrUag/edit#gid=1271849439).
- Follow the CTA to the engage page, see that it matches the …
=> build Dell K8s webinar takeover and engage page

templates/download/raspberry-pi/index.html
- Updated the 19.10 pi 2 image to the pi 3 iso
> You'll want the target to be:
> 
> http://cdimage.ubuntu.com/releases/19.10.1/release/ubuntu-19.10.1-preinstalled-server-armhf+raspi3.img.xz
> 
> Which will also work on the Raspberry Pi 2.
> 
- See that the correct image is downloaded on the thank-you page
Fixes #6594
=> Update the 19.10 Rasp Pi image

templates/openstack/index.html, templates/shared/_resources_openstack.html
Update illustrations on /openstack
- Check that the updated illustrations match those outlined in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6590)
Fixes #6590
=> Update illustrations on openstack page

templates/openstack/managed.html
Added suru to the top of the openstack/managed hero
- Check that the hero has the suru at the top of it
Fixes #6498
=> Update hero of openstack/managed

templates/kubeflow/install.html
Update hero illustration on /kubeflow/install
- Check that the hero illustration has been updated as per [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6600)
Fixes #6600
=> Update kubeflow install hero image

templates/openstack/features.html
Add suru to top of /openstack/features
- Check that the is a suru at the top of the page
Fixes #6499
=> Add suru to openstack features page

requirements.txt, templates/tutorials/tutorial.html
Add GA events to tutorial poll
- View the site locally in your web browser at: http://0.0.0.0:8001/tutorial/basic-snap-usage
- At the bottom of the first section there is a poll
- Install the Google Analytics debugger browser extenstion [Chrome](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) or [Firefox](https://addons.mozilla.org/en-GB/firefox/addon/ga-debugger/)
- Choose answers for each poll and check that a GA event is despatched with the following data:
**eventCategory:** survey
**eventAction:** The title of the poll e.g. How will you use …
=> Add GA to tutorial poll

templates/index.html
- removed "From VMware to Charmed OpenStack" takeover
- Refresh at least five times, see that none of the takeovers in rotation have the title "From VMware to Charmed OpenStack"
Fixes #6609
=> remove vmware to charmed openstack (en) takeover

templates/download/iot/index.html
Update rasberry pi logo on /download/iot
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot
- Check that the raspberry pi logo is correct
Fixes #6620
=> Update raspi logo on /download/iot

templates/download/server/s390x.html
Add empty column between content on /download/server/s390x
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/s390x
- Check that there is an empty column between the main content and form
Fixes #6625
=> Add empty col between content on download s390x

templates/download/iot/index.html, templates/download/shared/_verify-checksums.html
- Until RPi tutorials are published on /tutorials, hide the link to them on the RPi download thank you page.
- Removed external link icon on the same link.
- Select any version of Raspberry Pi, see that you are taken to a thank you page (cancel the download), and see that there is no link to an installation tutorial ("help on installing") next to "verify your download".
- Visit /download/desktop/thank-you?version=19.10&architecture=amd64 (or any other download thank you page that isn't RPi related), see that …
=> Fix linkchecker errors

releases.yaml
Swapped out 18.04.3 checksum variable for 18.04.4
- Click the link to download 18.04.4, see that you are taken to a thank you page, and the download triggers
- Repeat the process for /download/raspberry-pi and /download/server
Fixes #6532
=> Update checksums for 18.04.4

static/sass/styles.scss, templates/download/cloud/index.html, templates/download/server/provisioning.html
Update /download/server/provisioning
Drive by: Fix hero image size in /download/cloud
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/provisioning
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6630) have been made
Fixes #6630
=> Update server provisioning page

.circleci/config.yml, .env, requirements.txt, static/sass/_pattern_buttons.scss, templates/security/_notice-brief.html, templates/security/_subscribe.html, templates/security/notice.html, templates/security/notices.html, webapp/app.py, webapp/database.py, webapp/models.py, webapp/views.py
Implement views to fetch security notices from a database.
This work includes adding all the necessary boilerplate to connect to the database.
Fixes #6324
Fixes #6322 
Fixes #6323 
Fixes #2196
=> Get security notices from the database

requirements.txt, webapp/app.py
Set cache-control headers for the whole site
Use flask-base 0.4.0 so that all pages get 5 minute cache.
Also set homepage and blog list page to 1 minute cache.
QA
--
Check cache-control headers with curl:
``` bash
$ curl -I https://ubuntu-com-canonical-web-and-design-pr-6661.run.demo.haus/
Cache-Control: public, max-age=60, stale-while-revalidate=90
$ curl -I https://ubuntu-com-canonical-web-and-design-pr-6661.run.demo.haus/blog
Cache-Control: public, max-age=60, stale-while-revalidate=90
$ curl -I https://ubuntu-com-canonical-web-and-design-pr-6661.run.demo.haus/openstack
Cache-Control: public, max-age=300, stale-while-revalidate=360
$ curl -I https://ubuntu-com-canonical-web-and-design-pr-6661.run.demo.haus/blog/topics/design
Cache-Control: public, max-age=300, …
```
=> Set cache-control headers for the whole site

templates/legal/anbox-cloud-privacy-notice.html, templates/legal/anbox-cloud-terms-of-service.html, templates/legal/terms-and-policies/index.html
- Added terms page
- Added privacy notice page
- Updated terms list
- http://0.0.0.0:8001/legal/terms-and-policies
- http://0.0.0.0:8001/legal/anbox-cloud-terms-of-service
- http://0.0.0.0:8001/legal/anbox-cloud-privacy-notice
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6605
=> Add two legal pages for anbox cloud and add them to the terms and policies list page

templates/download/desktop/index.html, templates/download/shared/_multipass-install.html
Update /download/desktop
- Check that the page matches [the design](https://user-images.githubusercontent.com/36884067/74351157-a66c8700-4dae-11ea-857f-f408eaac5409.png)
Fixes #6634
=> Update illustrations on /download/desktop

static/js/navigation.js, templates/templates/_navigation.html, templates/templates/base.html, webpack.config.js
- Hardlinked navigation JS to avoid it being blocked due to errors in the main JS bundle
- Replaced `fetch` with `XMLHttpRequest` so it works in IE 11
- Replaced `forEach` on node lists with the array slice method so it works in IE 11
- Click on the main navigation and check that the dropdowns are shown
- Click on the faded area beneath the dropdowns and check that it closes the dropdowns
- Load the page with a dropdown hash in the URL e.g. ubuntu.com/#download and check that the appropriate dropdown is shown
Fixes #6655
=> Fix main navigation dropdowns for IE11

templates/internet-of-things/index.html
Updated /internet-of-things illustrations according to [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6639)
- See that the page complies with the comments in the [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6639)
Fixes #6639
=> update /internet-of-things illustrations

webapp/app.py
This is kinda nuts, but Squid won't cache anything with max-age of 60 or less.
http://squid-web-proxy-cache.1019090.n4.nabble.com/Objects-with-values-below-60-second-for-Cache-Control-max-age-are-not-cached-td4679079.html
``` bash
$ curl -I https://ubuntu.com
HTTP/1.1 200 OK
Date: Fri, 14 Feb 2020 15:28:44 GMT
Server: openresty/1.15.8.2
Strict-Transport-Security: max-age=15768000
Content-Type: text/html; charset=utf-8
Content-Length: 61602
Vary: Accept-Encoding
Cache-Control: public, max-age=60, stale-while-revalidate=90
X-View-Name: canonicalwebteam.templatefinder.templatefinder.template_finder
X-VCS-Revision: 1581691608-619d565
X-Request-Id: 4660f9eea4ef839f99dc3a4a4249e540
Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect, …
```
=> Squid needs max-age > 60

templates/download/intel-nuc.html
Fixed links to the, now local, tutorials
- View the site locally in your web browser at: http://0.0.0.0:8001/download/intel-nuc
- See that the links for creating media work
Fixes #6663
=> Update tutorial links on /download/intel-nuc

templates/engage/_base_engage_markdown.html, templates/engage/build-smart-devices-with-mir-whitepaper.md, templates/engage/case-study-acuris.md, templates/engage/cyberdyne.md, templates/engage/deeptech.md, templates/engage/dell-kubernetes-webinar.md, templates/engage/developing-android-on-ubuntu.md, templates/engage/index.html, templates/engage/interana-casestudy.md, templates/engage/kata-containers-webinar.md, templates/engage/sbi-casestudy.md, templates/engage/wellcome-sanger-case-study.md, templates/engage/yahoo-japan-case-study.md
Added /engage/interana-casestudy
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/interana-casestudy
- See that the page matches the [copy doc](https://docs.google.com/document/d/1o5K--Dtnrm_3er0Ux3mRf2yGFt8vFDCizrtQZ4m4mfU/edit?ts=5e42cc49) and the [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/6671#issuecomment-586937377)
- Test the engage page on https://cards-dev.twitter.com/validator, see that an appropriate title, description and image are pulled through.
- Visit /engage, see that the engage page is listed there (last entry)
Fixes #6672
=> add interana case study

templates/engage/index.html
Hidden the Interana engage page from the engage index - I hadn't realised that [the PDF](https://github.com/canonical-web-and-design/ubuntu.com/issues/6673) for the thank you page wasn't done yet, I just noticed it when checking on staging.
Go to /engage and see that there is no mention of "interana"
=> hide interana case study from engage index

package.json, static/js/core.js, static/sass/styles.scss, templates/templates/base.html, yarn.lock
- Included a polyfill.io script tag that handles all the JS IE11 otherwise can't 
- Open to suggestions on this, I'm not convinced it's a long term fix, mostly because:
- it's another network request
- I'm pretty sure we could setup webpack/babel to do it for us
- we could just (within reason) not write JS that requires polyfilling/heavy babel configuration
- but it does what we need in the short term. Plus, the polyfill.io API is smart enough to only return polyfills for browsers that need them, so for most users this script will only be a few bytes in size, and basically empty.
- Updated the version of `cookie-policy` to one that doesn't include ES6 syntax
- View [the demo](https://ubuntu-com-canonical-web-and-design-pr-6689.run.demo.haus/openstack/managed) in Browserstack, IE11
- Try …
=> fix forms in IE11

templates/community/index.html
- Remove a reference to the old “Insights” name
- Remove external link class
N/A
=> Community page: Blog migrated from external site to internal display

templates/internet-of-things/networking.html
Updated /internet-of-things/networking illustrations according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6688)
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/networking
- See that the points in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6688) have been properly addressed
Fixes #6688
=> update /iot/networking illustrations

package.json, tests/cypress/cypress.json, tests/cypress/navigation_spec.js, yarn.lock
- Integrate cypress in ubuntu.com test suite
- Add first simple test
- Add configuration to avoid cypress to generate default files
- In another terminal run `PORT=8001 yarn run cypress:run`
- Make sure tests pass.
- In another terminal run `PORT=8001 yarn run cypress:open`
- Have fun with the interface that can run the tests that cypress provides
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2361
=> Integrate cypress

templates/automotive/index.html
Updated /automotive illustrations according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6687)
- See that the items in the [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6687) have been properly addressed
Fixes #6687
=> update /automotive illustrations

requirements.txt, webapp/app.py, webapp/views.py
This makes use of our store-api module to return results from
api.snapcraft.io/api/v1/snaps/search. It also simplifies filtering
by architecture (?arch=)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2374
QA
--
Get the site running, then:
- Go to http://0.0.0.0:8001/snaps, see a 400 (can't be bothered to handle no query for now)
- Go to http://0.0.0.0:8001/snaps?q=toto, see 6 snaps returned
- Go to http://0.0.0.0:8001/snaps?q=toto&arch=i386, see 3 snaps returned
=> Add /snaps search endpoint

redirects.yaml
`ua help` refers to https://ubuntu.com/cis-audit, which does not exist. But `/fips`, `/cc-eal`, and `/cis` all redirect to `/security/certifications`. So it looks like the `/cis` redirect was mistaken.
Discovered while investigating #6710.
=> Changes “cis/?” to “cis-audit/?”

templates/kubernetes/managed.html
=> Add image_template to the /kubernetes/managed page

templates/kubernetes/features.html
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/features
=> Add image_template to the /kubernetes/features page

templates/kubernetes/index.html, templates/shared/_training.html
=> Add image_template to /kubernetes view page

templates/internet-of-things/appstore.html
Add image template to /internet-of-things/appstore
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/appstore
- Check the images load
=> Add image template to iot appstore

templates/aws/index.html, templates/aws/pro.html, templates/aws/thank-you.html
- Added image template to /aws pages
- http://0.0.0.0:8001/aws
- http://0.0.0.0:8001/aws/pro
- http://0.0.0.0:8001/aws/thank-you
- Check that all the images load as expected
=> Add image template to /aws pages

templates/ceph/index.html, templates/ceph/thank-you.html
Replaced images on /ceph and /ceph/thank-you with image_template module
- See that the images are still there (compare to ubuntu.com/ceph)
- Visit /ceph/thank-you and see that the smile image is still there
=> [Image module] /ceph

templates/containers/index.html, templates/containers/shared/_whitepaper.html
- View the site locally in your web browser at: http://0.0.0.0:8001/containers
=> Add image_template to /containers page

templates/shared/_thank_you.html
- View the site locally in your web browser at: http://0.0.0.0:8001/containers/thank-you
=> Add image_template to the /shared/_thank_you.html

templates/core/index.html, templates/core/thank-you.html
Replaced images on /core and /core/thank-you with image_template module
- See that the images are still there (compare to ubuntu.com/core)
- Visit /core/thank-you and see that the smile image is still there
=> [Image module] /core

templates/desktop/developers.html
Add image template to /desktop/developers
=> Add image template to desktop developers

templates/desktop/index.html
Add image template to desktop index page
- Check that the images below the fold are lazy loaded
=> Add image template to desktop index page

templates/desktop/features.html
Add image template to /desktop/features
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/features
=> Add image template to desktop features

templates/desktop/organisations.html
Add image template to /desktop/organisations
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/organisations
=> Add image template to desktop organisations

templates/desktop/partners.html
Add image template to /desktop/partners
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/partners
- Check that the image loads
=> Add image template to desktop partners

templates/desktop/statistics.html
Add image template to /desktop/statistics
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/statistics
=> Add image template to desktop statistics

templates/download/flavours.html, templates/download/index.html, templates/download/iot/_install-snaps-strip.html, templates/download/raspberry-pi-compute-module-3.html, templates/download/shared/_get-ebook-security.html, templates/download/up-squared-iot-grove-server.html
Replaced images with the image_template module on:
- /download
- /download/flavours
- /download/raspberry-pi-2-3-core
- /download/raspberry-pi-compute-module-3
This PR covers a lot of pages, because the following ones all use one or both of the `download/shared/_get-ebook-security.html` and `download/iot/_install-snaps-strip.html` partials, which contain the only images on those pages:
- /download/intel-iei-tank-870
- /download/intel-nuc-desktop
- /download/intel-nuc
- /download/kvm
- /download/orange-pi-zero
- /download/qualcom-dragonboard-410c
- /download/up-squared-iot-grove-server
- Run through the following [QA …
=> [Image module] /download

templates/download/cloud/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/download/cloud
=> Add image_template to the /download/cloud page

templates/download/desktop/index.html, templates/download/shared/_multipass-install.html
=> Add image_template to /download/desktop

templates/download/raspberry-pi/index.html, templates/download/raspberry-pi/thank-you.html
Replaced images with the image_template module on:
- /download/raspberry-pi
- /download/raspberry-pi/thank-you
- See that the images are still there (compare to ubuntu.com/download/raspberry-pi)
- Repeat for /download/raspberry-pi/thank-you
=> [Image module] /download/raspberry-pi

templates/download/server/arm.html
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/arm
=> Add image_template to /download/server/arm

templates/download/server/provisioning.html, templates/download/shared/_get_ebook_maas.html
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/provisioning
=> Add image_template to /download/server/provisioning

templates/download/server/thank-you-s390x.html
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you-s390x
=> Add image_template to /download/server/thank-you-s390x

templates/embedded/index.html
Replaced images with the image_template module on /embedded
- View the site locally in your web browser at: http://0.0.0.0:8001/embedded
- See that the images are still there (compare to ubuntu.com/embedded)
=> [Image module] /embedded

templates/robotics.html
Replaced images on /robotics with image_template module
- See that the images are still there (compare to ubuntu.com/robotics)
=> [Image module] /robotics

templates/financial-services/index.html
Add image template to /financial-services
=> Add image template to financial services

templates/internet-of-things/digital-signage.html
Add image template to /internet-of-things/digital-signage
=> Add image template to IoT digital signage

templates/internet-of-things/gateways.html
Add image template to /internet-of-things/gateways
=> Add image template to iot gateways

templates/kubeflow/consulting.html
Add image template to /kubeflow/consulting
=> Add image template to kubeflow consulting

templates/kubeflow/index.html
Add image template to /kubeflow
=> Add image template to kubeflow page

templates/kubeflow/install.html
Add image template to /kubeflow/install
=> Add image template to kubeflow install page

templates/kubernetes/_get_ebook.html, templates/kubernetes/install.html
- View the site locally in your web browser at: http://0.0.0.0:8001//kubernetes/install
=> Add image_template to the /kubernetes/install page

templates/legal/contributors/index.html, templates/legal/contributors/thank-you.html
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/contributors/ and http://0.0.0.0:8001/legal/contributors/thank-you
=> Add image_template to pages under /legal/contributors/

templates/legal/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/legal
=> Add image_template to the /legal overview page

templates/legal/terms-and-policies/index.html, templates/legal/terms-and-policies/thank-you.html
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies/ and http://0.0.0.0:8001/legal/terms-and-policies/thank-you
=> Add image_template to the /legal/terms-and-policies pages

templates/legal/ubuntu-advantage/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
=> Add image_template to the /legal/ubuntu-advantage page

templates/internet-of-things/gateways.html
- Updated the meta data
- Moved the copy docs around - note, lots of updates not approved
- Removed link to thinger on the snapstore
- See the link to thinger has been removed
Fixes #6564
=> Remove link to thinger in the snapstore, fixed meta info

templates/server/hyperscale.html
- View the site locally in your web browser at: http://0.0.0.0:8001/server/hyperscale
=> Add image_template to the /server/hyperscale page

templates/dell/index.html, templates/dell/thank-you.html
- Added the image template tag to all images in the /dell section
- View the site locally in your web browser at: http://0.0.0.0:8001/dell
- http://0.0.0.0:8001/dell/thank-you
- Check that the images load properly
=> Add image template tag to /dell section

templates/support/community-support.html, templates/support/index.html, templates/support/thank-you.html
- Added image template tag to support
- http://0.0.0.0:8001/support
- http://0.0.0.0:8001/support/community-support
- http://0.0.0.0:8001/support/thank-you
=> Add image template tag to support pages

templates/_docs/engage_pages.html, templates/engage/_base_engage_markdown.html, templates/engage/anbox-cloud-gaming-whitepaper.md, templates/engage/de/migration-von-vmware-zu-openstack.md, templates/engage/dell-kubernetes-webinar.md, templates/engage/es/vmware-a-charmed-openstack.md, templates/engage/microk8s-451research.md
- Replaced images with the image_template module
- Added `heaeder_image_width` and `header_image_height` to the yaml
- Updated the [docs](http://0.0.0.0:8001/_docs/engage_pages)
- Try the engage pages from the homepage and see they are using the image template (inspect them)
- Try an older engage page from /engage and see that this work the old way
=> Update engage template to use image_template

templates/masters-conference/index.html
=> Add loading auto for image_template tag

templates/contact-us/index.html
- Added image template tag to the contact us page
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us
- See the canonical logo is loaded
=> Add image template to /contact-us section

static/sass/styles.scss, templates/automotive/index.html
Add image template to /automotive
- Make sure the images load
=> Add image template to automotive

templates/download/raspberry-pi-compute-module-3.html
…module-3
For some reason, the image_template module doesn't work with the two photos embedded in the install guide, so have reverted them back to image tags.
- View the site locally in your web browser at: http://0.0.0.0:8001/download/raspberry-pi-compute-module-3
- See that the two photos in the guide are there
=> Fix /download/rpi-compute-module-3 images

templates/kubeflow/features.html
Add image template to /kubeflow/features
- View the site locally in your web browser at: http://0.0.0.0:8001/kubeflow/features
=> Add image template to kubeflow features page

templates/kubeflow/what-is-kubeflow.html
Add image template to /kubeflow/what-is-kubeflow
=> Add image template to what is kubeflow page

templates/server/index.html
=> Add image_template to /server overview page

templates/public-cloud/index.html
=> Add lazy load to /public-cloud

templates/openstack/what-is-openstack.html
Add image template to /openstack/what-is-openstack
=> Add image template to what is openstack

templates/pricing/devices.html, templates/pricing/thank-you.html
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices and http://0.0.0.0:8001/pricing/thank-you
=> Add image_template to the pricing section

templates/openstack/shared/_openstack_clients.html
Add image template to openstack shared
- Check that the client logo images load
=> Add image template to openstack shared

templates/training/index.html
=> Add image_template to /training

templates/livepatch/index.html, templates/shared/_call-sales.html
- View the site locally in your web browser at: http://0.0.0.0:8001/livepatch
=> Add image_template to the /livechat page

templates/kubeflow/shared/_learn-more.html
Add image template to kubeflow shared partial
- Check that the icons in the "Learn more about AI/ML and Kubeflow" section load
=> Add image template to kubeflow shared

templates/blog/article.html, templates/blog/blog-card-upcoming.html, templates/blog/blog-card.html, templates/blog/internet-of-things.html, templates/blog/topics/juju.html, templates/blog/topics/maas.html, templates/blog/topics/robotics.html, templates/blog/topics/snapcraft.html
- updated /blog pages with image_template module where possible:
- /blog
- /blog/the-state-of-robotics-january-2020 (includes a robotics illustration below the post)
- /blog/internet-of-things
- /blog/topics/maas
- /blog/topics/juju
- /blog/topics/robotics
- /blog/topics/snapcraft
- on blog cards, images aren't always a uniform size, but they already use a cloudinary URL, so have just added the loading attribute to those images in the partial
- See that the images load, repeat for all the pages listed above
=> [Image module] /blog

templates/openstack/features.html
Add image template to /openstack/features
=> Add image template to openstack features

templates/shared/_resources_openstack.html
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack and look at the resources section
=> Add image_tag to the _resources_openstack include

templates/kubeflow/install.html
- Modified kubeflow install instructions. Verified and tested that it works on my laptop.
- Ran webserver locally and change looks good. 
Fixes #6327 
Output of microk8s.enable kubeflow:
```
davecore@davecore-laptop:~$ microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...
Deploying Kubeflow...
Kubeflow deployed.
Waiting for operator pods to become ready.
Waited 0s for operator pods to come up, 27 remaining.
Waited 15s for operator pods to come up, 27 remaining.
Waited 30s for operator pods to come up, 25 remaining.
Waited 45s for operator pods to come up, 24 remaining.
Waited 60s for operator pods to come up, 22 remaining.
Waited 75s for operator pods to come up, 22 remaining.
Waited 90s for operator pods …
```
=> Use microk8s.enable kubeflow instead

.github/workflows/cypress.yml
Since this job runs every morning. We would like to get a notification from our bot when the job is failing.
Fixes #6704
=> Send message on failure

templates/shared/pricing/_kubernetes-enterprise-support.html, templates/shared/pricing/_kubernetes-managed.html, templates/shared/pricing/_landscape.html, templates/shared/pricing/_maas-pricing.html, templates/shared/pricing/_maas-support.html, templates/shared/pricing/_storage-support.html, templates/shared/pricing/_ua-desktop-support.html, templates/shared/pricing/_ua-for-infrastructure-ja.html, templates/shared/pricing/_ua-for-infrastructure-physical.html, templates/shared/pricing/_ua-for-infrastructure-virtual.html, templates/shared/pricing/_ua-for-infrastructure.html, templates/shared/pricing/_ua-server-support.html
Replaced images with the image_template module, mostly the aubergine ticks
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/infra to see most of them
=> Add image_template to the /shared/pricing includes

templates/templates/_navigation.html
Applied valid labels to the Clear and Search buttons in the header search field.
- View the site locally in your web browser at: http://0.0.0.0:8001/ and check that the new labels in the search field do not show up
- View the same page in a text-only browser or screenreader, and check that the search field buttons now have “Clear” and “Search” labels
Fixes #6728
=> Changes <button> alt= attributes to labels

templates/shared/forms/interactive/_aws.html, templates/shared/forms/interactive/_bootstack.html, templates/shared/forms/interactive/_embedded.html, templates/shared/forms/interactive/_general.html, templates/shared/forms/interactive/_kubeflow.html, templates/shared/forms/interactive/_kubernetes.html, templates/shared/forms/interactive/_openstack.html, templates/shared/forms/interactive/_partner-dell.html, templates/shared/forms/interactive/_pricing-infra.html, templates/shared/forms/interactive/_robotics.html, templates/shared/forms/interactive/_storage.html, templates/shared/forms/interactive/_support-openstack.html, templates/shared/forms/interactive/_support.html
- Replaced images with the image_template module
- Removed empty and unused _ua-support include
- View the site locally in your web browser at: http://0.0.0.0:8001/#get-in-touch
- Try a few modal forms and see that it still works, I don't think the thank-you modal even shows
=> Add image_template to modal forms, remove unused partial

templates/openstack/consulting.html
Add image template to /openstack/consulting
=> Add image template to openstack consulting

templates/openstack/managed.html
Add image template to /openstack/managed
=> Add image template to openstack managed

templates/engage/yahoo-japan-case-study.md
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/yahoo-japan-case-study
=> Add image sizes to /engage/yahoo-japan-case-study

templates/openstack/install.html
Add image template to /openstack/install
=> Add image template to openstack install

templates/about/index.html
Add image-module to /about
- View the site locally in your web browser at: http://0.0.0.0:8001/about
=> Add image-module to /about

templates/internet-of-things/gateways.html
- Remove thinger snap from gateway page.
=> Remove thinger from gateway

templates/engage/wslconf.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/wslconf
=> Add image_template to /engage/wslconf

templates/engage/cyberdyne.md
Add image template to /engage/cyberdyne
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/cyberdyne
=> Add image template to cyberdyne template

templates/engage/14-04-esm.html, templates/engage/19-10-webinar.md, templates/engage/451-automotive.html, templates/engage/casestudy-rocketchat.html, templates/engage/shared/_header.html
- Updated shared header partial to use image template
- Updated: 
- /engage/14-04-esm
- /engage/casestudy-rocketchat (this is good for testing the partial)
- /engage/19-10-webinar
- /engage/451-automotive
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/14-04-esm
- See that images are still present in the header
- Repeat for the other three pages in the list above
=> [Image module] /engage pt1

templates/tutorials/tutorial.html
Add image template to tutorials feedback
- On the last step check that the feedback icons load
=> Add image template to tutorial feedback

templates/engage/private-cloud-build-webinar.md
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/private-cloud-build-webinar
=> Added image sizes to the /engage/private-cloud-build-webinar page

templates/engage/intro-to-microk8s-webinar.md
- Add image size attributes to intro to microk8s engage page
- http://localhost:8001/engage/intro-to-microk8s-webinar
=> Add image size attributes to intro to microk8s engage page

templates/engage/vmware-to-charmed-openstack.md
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/vmware-to-charmed-openstack
=> Update image size on vmware-to-charmed-openstack engage page

templates/engage/get-started-with-ai-part-2.md
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/get-started-with-ai-part-2
=> Update image sizes on /engage/get-started-with-ai-part-2 pae

templates/engage/whitepaper-containers.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/whitepaper-containers
=> Add image sizes to /engage/whitepaper-containers

templates/engage/whats-new-ubuntu-14-04-lts.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/whats-new-ubuntu-14-04-lts
=> Add image sizes to /engage/whats-new-ubuntu-14-04-lts

templates/engage/apparmor-intro.html
Add image template to /engage/apparmor-intro
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/apparmor-intro
=> Add image template to apparmor engage page

templates/engage/deeptech.md, templates/engage/dell-k8s-reference-architecture.md
Add image template to /engage/dell-k8s-reference-architecture
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/dell-k8s-reference-architecture
=> Add image template to dell k8s

templates/engage/deeptech.md
Add image template to /engage/deeptech
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/deeptech
=> Add image template to deep tech engage page

templates/engage/domotz-case-study.md
Add image template to /engage/domotz-case-study
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/domotz-case-study
=> Add image template to domotz engage
