templates/engage/dell-openstack-reference-architecture.md
Add image template to /engage/dell-openstack-reference-architecture
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/dell-openstack-reference-architecture
=> Add image template to dell ref engage

templates/engage/case-study-acuris.md
Add image template to /engage/case-study-acuris
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/case-study-acuris
=> Add image template to acuris engage page

templates/engage/ubuntu-lime-telco.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ubuntu-lime-telco
=> Add image_template to /engage/ubuntu-lime-telco

templates/engage/wellcome-sanger-case-study.md
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/wellcome-sanger-case-study
=> Update /engage/wellcome-sanger-case-study banner with image sizes

package.json
Removing cypresss from dependencies. Since it downloads a lot of stuff that we don't need when deploying.
=> Remove cypress

templates/engage/whitepaper-iot-security.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/whitepaper-iot-security
=> Add image_template to /engage/whitepaper-iot-security page

static/js/imageBuilder.js, static/sass/styles.scss, templates/core/build.html
Disable the steps one at a time as you step through them.
- See that step 2 and 3 are disabled until you select a board
- Once the board is selected it enabled the OS
- Once the OS is selected the snaps list is enabled.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2385
=> Disable step by step

templates/_image-testing/index.html, templates/_image-testing/jpg/index-lazy.html, templates/_image-testing/jpg/index.html, templates/_image-testing/png/index-lazy.html, templates/_image-testing/png/index.html, templates/_image-testing/svg/index-lazy.html, templates/_image-testing/svg/index.html, templates/templates/image-testing_base.html
Add image testing pages to run tests comparing native image tags versus using the image template module.
- Check pages at /_image-testing
- Sanity check code
=> Add image testing pages

templates/download/shared/_get-ebook-security.html, templates/download/shared/_get_ebook_maas.html
Updated the layout of two ebook strip partials
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/provisioning
- See that the layout looks OK and complies with the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6676)
- Visit /download/intel-iei-tank-870
- See that the layout looks OK and complies with the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6676)
Fixes #6676 
Before:
After:
=> update ebook layouts

static/js/chartData.js, static/js/release-chart.js, templates/about/index.html, templates/about/release-cycle.html, yarn.lock
- Replaced image of releases with d3 chart
- View the site locally in your web browser at: http://0.0.0.0:8001/about
- Wee that the chart appears and is a table on small screens
Fixes #6694
=> Update chart on /about page

templates/security/notices.html, webapp/security/views.py
Small improvements related to pagination for the security notices page.
- Make sure pagination works fine, and that weird page parameter values don't cause unexpected behaviour.
=> Usn pagination improvements

requirements.txt, templates/security/_subscribe.html, webapp/app.py, webapp/security/views.py
Add rss and atom feeds for security notices.
- Add the sqlite database to the root of the project(ask me)
- Open `http://localhost:8001/security/notices/rss.xml` and `http://localhost:8001/security/notices/atom.xml` with and RSS reader and make sure they work.
=> Add feeds endpoints for security notices

.gitignore, requirements.txt, templates/core/build.html, webapp/app.py, webapp/views.py
I've bastardised the markup in `templates/core/build.html` just to
illustrate how to POST the form to my view function. So
@anthonydillon please fix it up.
This makes use of the brand spanking new
[canonicalwebteam.launchpad](https://github.com/canonical-web-and-design/canonicalwebteam.launchpad)
module, where I mostly copied the code from snapcraft.io.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2375
QA
--
You need the `LAUNCHPAD_TOKEN` and `LAUNCHPAD_SECRET` environment variables defined in `.env.local` file. You can find the values for this in the shared Lastpass folder.
Then do `./run`.
Go to `/core/build` and click "Build image". Hopefully a horribly
garish success page.
=> Trigger the build when submitting /core/build

static/js/imageBuilder.js, templates/core/build.html
Remove the summary section
- Make a section and see there is no summary at the bottom
- Check it matched [the copy doc](https://docs.google.com/document/d/1Hw_8dWAAUpHHm5Z_XNUVJaSVE5k5i2Vt6WANcJYUZvY/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2401
=> Remove the summary section

.eslintrc.js, package.json, yarn.lock
Add eslint to the build process
- Run `./run exec yarn lint-js`
- Check that it runs eslint on the js
- Check that only warnings are shown and no errors
Fixes #6867 6867
=> Add eslint

templates/download/shared/_multipass-install.html
- Removed closing section tag
- See that the "Multipass for instant Ubuntu VMs" strip is displayed correctly
Fixes #6846
=> Remove erroneous closing tag

templates/engage/anbox-cloud-webinar.md, templates/engage/index.html, templates/index.html, templates/takeovers/_anbox-cloud-webinar.html, templates/takeovers/_template.html, templates/takeovers/index.html
Added /engage/anbox-cloud-webinar and associated takeover
- Refresh the page until you see a takeover with the title "An introduction to Anbox Cloud", see that it complies with the [design](https://github.com/canonical-web-and-design/web-squad/issues/2400#issuecomment-590848140) and the [brief](https://docs.google.com/spreadsheets/d/19HsZx5SCw9nKq2AXklGAvHJoFp2DJ-g6cEe0vP7JWCw/edit#gid=2113339190)
- @pmahnke the brief mentions this takeover should be added as the 4th takeover, but obviously there's already a similar takeover for …
=> add anbox cloud webinar takeover and engage

templates/security/_notice-brief.html, templates/security/notice.html
Wherever we display a release tag append `LTS` if the release is LTS.
- Make sure `LTS` shows where appropriate
=> Security notices: display if a release is LTS

templates/telecommunications/index.html
- Updated illustrations according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6490)
- Replaced image tags with the image module
- See that the illustrations mentioned in the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6490) are present
Fixes #6490
=> Update /telecommmunications illustrations

templates/security/index.html
- Updated /security illustrations according to the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6492#issuecomment-583320652)
- Replaced image tags with image_module
- See that the points from the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6492#issuecomment-583320652) have been addressed
Fixes #6492
=> update illustrations on /security

templates/engage/index.html, templates/engage/smart-start-webinar.md, templates/index.html, templates/takeovers/_smart-start-webinar.html, templates/takeovers/index.html
- Added a smart start takeover and engage page
- Check the smart start takeover appears, follow it to the engage page
[Brief](https://docs.google.com/spreadsheets/d/1BHbx3SYPCJrGij5wc7kzH5Y-KN4QqACEdd8iJzb_KAs/edit#gid=0)
Fixes #6765
=> Add smart start takeover

templates/legal/websites.html, templates/templates/_navigation-community-h.html, templates/templates/_tag_manager.html
Fix up links to tutorials
-  Sanity check link changes
=> Fix up links to tutorials

.eslintrc.js, package.json, yarn.lock
Remove the only warn eslint plugin to surface errors in the codebase
- Make a change to a JS file such as adding a variable that isn't used
- Stage the file and try to commit it
- Check that eslint runs and shows you the error
Fixes #6887
=> Remove only warn eslint plugin

templates/kubernetes/managed.html, templates/shared/pricing/_kubernetes-managed.html
- Update to Managed OpenStack on /kubernetes/manages page
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit#)
Fixes #6914
=> Update to Managed OpenStack on /kubernetes/manages page

templates/legal/ubuntu-advantage-service-description/index.md
Change descriptor and link to point to docs pages rather than wiki
Fixes charmed-kubernetes/kubernetes-docs#339
=> Update UA description to point to docs page for K8s supported versions

static/js/imageBuilder.js, static/sass/_pattern_card.scss, templates/core/build.html
Restyle the snap selection section
- Select your board and OS
- Check the snap selection functions by searching then adding and removing some snaps
- Check it matches [the design](https://app.zeplin.io/project/5e33f5075368883e5da9d0bf/screen/5e4fe76ec1b203753a5fa78b)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2402
=> Restyle the snap selection section

templates/templates/base.html, templates/whitepapers/beta/shared/form.html, templates/whitepapers/shared/form.html, webpack.config.js
- Added navigation.js back to main bundle
- Removed unused event listener polyfill for IE 6 -8
- Removed global link to serialize.js as is linked to on pages that use it
- Check that the main navigation dropdowns work in modern browsers and IE 11
- Check that the forms on the following two pages work in IE 11
- [http://0.0.0.0:8001/whitepapers/beta/robotics](http://0.0.0.0:8001/whitepapers/beta/robotics)
- [http://0.0.0.0:8001/whitepapers/robotics](http://0.0.0.0:8001/whitepapers/robotics)
Fixes #6925
=> Tidy up scripts

static/js/src/image-download.js, templates/download/desktop/thank-you.html, templates/download/server/thank-you.html, webpack.config.js, yarn.lock
- Moved as much as possible of the JS that handles the downloading of a given desktop/server image to the build pipeline
- Select a download, see that you're taken to the thank you page and that the download dialog appears automatically, and that there are no console errors.
- Repeat the process for /download/server
Fixes #6883
=> move image download js to build pipeline

templates/engage/index.html, templates/engage/private-cloud-cost-analysis-webinar.md, templates/index.html, templates/takeovers/_cloud-cost-analysis.html, templates/takeovers/index.html
Added private cloud cost analysis takeover and engage page
- Refresh until you see the "Hosted private cloud infrastructure: a cost analysis" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1Yg_sHVjaGh4snje5TltN6SFH0PDyhTEWllnaaEkKmnw/edit#gid=877682240) and [the design](https://github.com/canonical-web-and-design/web-squad/issues/2405)
- Check that it matches [the copy doc](https://docs.google.com/document/d/1Ju0tF-bvFns_91a37MP6LQ6-pTDuHqbeYI_QxXftPK0/edit), …
=> Add cloud cost analysis takeover and engage page

static/sass/styles.scss, templates/server/index.html
Updated the illustrations on /server
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6935) have been made
Fixes #6935
=> Update server page illustrations

templates/containers/index.html, templates/containers/shared/_whitepaper.html
- Updated illustrations according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6934#issue-574062314)
- View the site locally in your web browser at: http://0.0.0.0:8001/containers
- See that the items in the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6934#issue-574062314) have been addressed correctly
Fixes #6934
=> update illustrations on /containers

templates/templates/base.html, templates/whitepapers/beta/shared/form.html, templates/whitepapers/shared/form.html
- Made the serialize js library available globally
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/starting-with-ai
- Submit the form and check that it submits properly
- Go to http://0.0.0.0:8001/download/server
- Choose a download and submit the form on that page
- Check that the form submits properly
=> Make serialize available globally

templates/support/index.html
- Added illustration to /support hero strip
- See that [the brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6928) has been met
Fixes #6928
=> add illustration to /support hero strip

templates/server/hyperscale.html
- Updated illustrations according to [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6937#issue-574092441)
- View the site locally in your web browser at: http://0.0.0.0:8001/server/hyperscale
- See that the items in the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6937#issue-574092441) have been addressed correctly
Fixes #6937
=> update illustrations on /server/hyperscale

templates/training/index.html
Update the illustrations on /training
- Check that the changes requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6954) have been made
Fixes #6954
=> Update illustrations on /training page

navigation.yaml, static/sass/styles.scss, templates/_docs/content_strips.html, templates/_docs/index.html
- Add new content strips page to docs
- Add new page to docs navigation
- Add card for new page on docs homepage
- View the site locally in your web browser at: http://0.0.0.0:8001/_docs/content_strips
- Check that page includes the sections requested in [the issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/6952)
- Check that the new page appears in the breadcrumb navigation
- Check that a card for the new page appears on /_docs
Fixes #6952 
Fixes #6950
=> Add content strips page to docs section

templates/desktop/organisations.html
- Update the illustration for the "Ubuntu is at the forefront of safety and reliability" section of /desktop/organisations
- Removed the empty attributes property from an instance of the image template
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/organisations
- Check that the illustration under "Ubuntu is at the forefront of safety and reliability" matches [this one](https://assets.ubuntu.com/v1/d127abd7-safety+reliability.svg)
Fixes #6947
=> Update illustration on /desktop/organisations

templates/security/certifications.html
- Update /security/certifications illustrations
- See that it complies with the [brief](https://github.com/canonical-web-and-design/ubuntu.com/issues/6953)
Fixes #6953
=> update illustrations on /security/certifications

templates/kubeflow/index.html
- changed two `h1` elements to `h2`
- See that the "NVIDIA and Canonical accelerate AI everywhere" and "Partner with us" headings are `h2` elements, not `h1`
Fixes #6949
=> correct heading heirarchy on /kubeflow

templates/shared/contextual_footers/_cloud_further_reading.html, templates/shared/contextual_footers/_desktop_further_reading.html, templates/shared/contextual_footers/_further_reading.html, templates/shared/contextual_footers/_iot_further_reading.html, templates/shared/contextual_footers/_security_further_reading.html, templates/shared/contextual_footers/_telco_further_reading.html, templates/shared/contextual_footers/_ua_further_reading.html
- Fixed invalid markup in "Further reading" markup. 
- The issue suggested changing it from a `ul` to a `div` and updating the JS to wrap its output in a `ul`, but the simplest solution seemed to be to wrap the offending `i` spinner element in a `li`, which is then removed anyway when the script completes.
- Moved repeated "Further reading" markup to a shared partial.
- See that the "Further reading" list in the footer renders correctly (compare to ubuntu.com/advantage) and test it on https://validator.w3.org/ to see …
=> move repeated "further reading" markup to shared partial

templates/aws/thank-you.html, templates/dell/index.html, templates/desktop/developers.html, templates/desktop/features.html, templates/desktop/organisations.html, templates/desktop/partners.html, templates/download/iot/index.html, templates/internet-of-things/appstore.html, templates/internet-of-things/digital-signage.html, templates/internet-of-things/gateways.html, templates/server/index.html, templates/support/community-support.html, templates/support/index.html, templates/support/thank-you.html
- removed empty `attrs={"foo": ""}` from image modules
- View the site locally in your web browser at: http://0.0.0.0:8001/aws/thank-you
- See that the page is not broken/doesn't return a template error, and that images are rendered correctly.
- Repeat for:
- /dell
- /desktop/developers
- /desktop/features
- /desktop/organisations
- /desktop/partners
- /download/iot
- /internet-of-things/appstore
- /internet-of-things/digital-signage
- /internet-of-things/gateways
- /server
- /support/community-support
- /support
- /support/thank-you
Fixes #6747
=> remove emtpy attribute values from image modules

static/js/src/contextual-menu.js, templates/advantage/index.html, templates/download/shared/_verify-checksums.html, templates/templates/_navigation.html, webpack.config.js
- moved repeated contextual menu js to build pipeline
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/topics/design
- Hover over "topics" in the secondary navigation, see that it behaves identically to ubuntu.com/blog/topics/design
- Visit /download/desktop/thank-you?country=GB&version=19.10&architecture=amd64
- Click "verify your download", see that the checksum dropdown appears
=> move repeated contextual dropdown js to build pipeline

templates/engage/index.html
Added /engage/interana-casestudy card to /engage, it was removed previously as we didn't have the PDF.
- See that the last card in the list has the title "ESM maintains Interana's system security while upgrading".
- Click the link, and on the engage page, fill out the form and see that you are taken to a thank you page where you can download a relevant PDF.
Fixes #6672
=> add interana engage page to /engage

templates/engage/index.html, templates/engage/smart-card-whitepaper.md
Added /engage/smart-card-whitepaper
- See that there is a card at the bottom of the list with the title "Smart card login on Ubuntu".
- Follow the link to the engage page, see that it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/2322#issuecomment-588281479) and the [copy doc](https://docs.google.com/document/d/1wVIC2R2OlqKTXgS97QsIi5txwKlpXpynX4bbWTXgXxo/edit?ts=5e42db44)
- Test the page on https://cards-dev.twitter.com/validator, see that it pulls through a relevant title, description …
=> add smart card whitepaper engage page

static/sass/_layout-tutorial.scss
Fixed header being hidden when navigating tutorial steps (tested on Chrome, Safari and Firefox)
- Click the link of any tutorial, see that the header is visible (without scrolling) when you land on the page, and that it remains visible when you use the side navigation to select different steps.
- **Test it on Chrome, Firefox, and any other browser you've got**
Fixes #6974
=> fix header being hidden when navigating tutorial steps

templates/security/index.html
Fix a funky conflict in the template for security :)
- `./run`
- http://0.0.0.0:8001/security/certifications 
- There should be a normal icon on the security notices link.
=> Fix conflict in template

.eslintrc.js, package.json, tests/cypress/cypress.json, tests/cypress/forms_spec.js
~~This PR needs to be merged before: https://github.com/canonical-web-and-design/ubuntu.com/pull/6886~~
- Add cypress form testing.
- `yarn add cypress` (I don't want to install it as a dependencies since it downloads a lot from different  sources when we build)
- In another terminal:
- `yarn add cypress`
- `PORT=8001 yarn run cypress:run` <-  should run test tests
- `PORT=8001 yarn run cypress:open`  <- if you want some swag with a browser open
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2406
=> Add marketo form testing

templates/engage/index.html, templates/engage/securing-ros-on-robotics-platforms-whitepaper.md
Added "Securing ROS robotics platforms" engage page
**Can't merge until we get the PDF and it's been uploaded**
- At the bottom of the page, see that there is a card with the title "Securing ROS robotics platforms", then follow the link to the engage page
- See that the engage page matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/2325) and the [copy doc](https://docs.google.com/document/d/156Oa3Oz3RiUQcFLTKNqtfKXiuFtzZm0fRMsrv6XV5Wc/edit?pli=1).
Fixes #6646
=> add "Securing ROS robotics platforms" engage page

webapp/app.py
- To get a first draft of the notices we are disabling the api for now.
- run `./run --env FLASK_APP=webapp.app:app exec flask routes`
- There should be no POST routes for `/security/notices`
=> Disable notices API

.github/workflows/cypress.yml, README.md
Rename the CI check to "Cypress checks" so it looks good on a badge,
and then add the badge to the README.
=> Rename cypress check, add badge to README

Dockerfile
**Temporary fix.**
It seems that a high priority mirror doesn't have the image 19.10. For now I am disabling the mirror list so we avoid adding conditionals in the codebase. **This is a simple fix.**
- `DOCKER_BUILDKIT=1 docker build --build-arg BUILD_ID=test --tag ubuntu.com . `
- `docker run --env DATABASE_URL=sqlite:/// -ti -p "8006:80" ubuntu.com`
- http://0.0.0.0:8006/download/desktop/thank-you?version=19.10&architecture=amd64
- ubuntu should download from releases.ubuntu.com
=> Temp: Remove mirror list to fix mirror issues

templates/core/build-error.html, templates/core/build.html, webapp/views.py
The build error page should now have a 400 status.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2410
QA
--
Run the site with `dotrun` (if it fails, try `dotrun clean` then `dotrun` again).
Now go to `/core/build`, and kick off a build. You should see the success page.
Now open up the network tab, select "HTML" (Firefox) or "Doc" (Chrome), to filter out the noise. Refresh the page, click "resubmit", hopefully you might see an error page with a 400 status. If not, try refreshing again quickly.
=> 400 build error page

static/js/src/tco-calculator.js, templates/tco-calculator/index.html
- Managed service yearly operational costs previously weren't taking into account a support cost, and since each managed service host comes with Ubuntu Advantage Advanced by default, that cost is 1500 per host.
- Fill out the calculator with the figures and options mentioned in [the issue](https://github.com/canonical-web-and-design/web-squad/issues/2478), and see that the total matches what Tytus is expecting, and compare it to ubuntu.com/tco-calculator to see the difference.
Fixes …
=> add support cost to managed service cost calculator

package.json
Fixes the missing global-nav JS issue.
- `DOCKER_BUILDKIT=1 docker build . -t ubuntu.com`
- `docker run -ti -p 8001:80 --env DATABASE_URL="sqlite:///" ubuntu.com`
- Check `http://localhost:8001/static/js/build/global-nav.js`
Fixes #
=> Add copy global nav step to build-js

templates/engage/developing-android-on-ubuntu.md, templates/engage/enterprise-snap-management.md
- 2 engage pages didn't have the asset server url 
- http://0.0.0.0:8001/engage/developing-android-on-ubuntu
- http://0.0.0.0:8001/engage/enterprise-snap-management
- See that the banner images appear
=> Add asset server url to engage pages

static/js/src/chart-data.js, templates/about/release-cycle.html
- Fixed grammar and typos
- Added 1.19 to k8s chart
- Added tech review bits to the OpenStack chart
- Compare text changes to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) and data changes to the [sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1483484944)
Fixes #6975
=> Update release chart for openstack

templates/engage/domotz-case-study.md
- As requested by domotz, this PR add's a link to the domotz homepage (https://domotz.com) in the first paragraph of the enage page case study.
- Visit http://0.0.0.0:8001/engage/domotz-case-study
- Click the "Domotz" link in the first paragraph
- Make sure it goes to https://domotz.com
=> Add link to domotz homepage from case study

webapp/app.py
QA
--
```
dotrun
```
```
$ curl -sI http://192.168.1.170:8001/templates/_navigation-community-h | grep -i access-control
Access-Control-Allow-Origin: discourse.ubuntu.com
```
=> Allow discourse.ubuntu.com to request /templates

templates/engage/_base_engage_markdown.html, templates/engage/case-study-rigado.md, templates/engage/index.html
- Added an engage page for the rigado case study
- Removed max widths and heights for hero images in engage pages where the height and width are provided with parameters
- Click on the rigado case study (last on the page)
- Check the page in all browsers, check the form, etc.
[Design issue](https://github.com/canonical-web-and-design/web-squad/issues/2379)
Fixes #6702
=> 6702 rigado engage

templates/tco-calculator/index.html
- Added the correct URL for the TCO calculator copydoc
- See that the meta tag has the correct [copydoc](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit#)
Fixes #2507
=> Correct meta tag URL for TCO calculator copydoc

navigation.yaml
- Add TCO calculator to the secondary nav for /kubernetes and /openstack sections
- http://0.0.0.0:8001/openstack and see "TCO calculator" in secondary nav
- http://0.0.0.0:8001/kubernetes and see "TCO calculator" in secondary nav
Fixes #2506
=> Add TCO calculator to the secondary nav for /kubernetes and /openstack sections

templates/index.html, templates/shared/_notice_default.html
- Add a notification to the ubuntu.com homepage linking to Mark's blog post
- Add logic to add `&nbsp;&rsaquo;` for local links and `p-link--external` for external ones
- See that the notification appears for english and the normal ones appear for chinese or japanese language (chrome://settings/langages)
=> Add covid update to homepage banner

templates/security/cve/base_cve.html, templates/security/cve/cve.html, templates/security/cve/index.html, webapp/app.py, webapp/security/views.py
- Setup views 
- Front-end: feel free to change template names. just update the views with the new name.
- Run the site using the command `./run serve` or the dotrun snap
- Visit `/security/cve` it should go to the list page
- Visit `/security/cve-2019-1234` should go to the detail cve page.
- Visit `/security/cve-231231231231` should go to 404
Fixes #7023
=> Handle CVE routes

templates/engage/index.html, templates/engage/pre-kubecon-event.md, templates/index.html, templates/takeovers/_nl-pre-kubecon.html, templates/takeovers/index.html
- Build pre-Kubecon takeover
- Build pre-Kubecon engage page
- Refresh the page until you see the "Virtual event: MicroK8s & Kubernetes" takeover
- Check that the takeover matches [the brief](https://docs.google.com/spreadsheets/d/1uDmHeijZ4qvWwRvWumZvw7h4iUnlk67OLsaz4E_BecY/edit#gid=2113339190)
- Click the CTA in the takeover and check that it takes you to /engage/pre-kubecon-event
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1Ov_JCaTymV3_OY-_sACJNbfbEUetUjkB28T83kJZZ7U/edit#)
- Check that the …
=> Pre-Kubecon takeover and engage page

navigation.yaml, templates/templates/_navigation-developer-h.html
Add a link to /security/cve in /security secondary navigation, footer and Developer mega menu
- Check that there is a link to "CVEs" in the secondary navigation and that it takes you to the "CVE reports" page
- Check that there is a link to "CVEs" in the footer underneath the "Security" heading and that it takes you to the "CVE reports" page
- Check that there is a link to "CVEs" in the horizontal "Security" section at the bottom of the "Developer" mega menu and that it takes you to the "CVE reports" page
- Check that the …
=> 7060 add cve to navigation

templates/index.html, templates/takeovers/_nl-pre-kubecon.html
- added `lang="nl"` to the   takeovers/_nl-pre-kubecon.html takeover
- See that the takeover does not appear until you change your language setting to dutch
=> Add lang="nl" to the dutch takeover

templates/tco-calculator/_base_tco_calculator.html, templates/templates/_navigation.html
- Like hide_nav on /engage, I added hide_subnav to hide the secondary nav in the _navigation.html partial
- This should stop people from going to the tco page from OpenStack and the nav showing the Kubernetes bubble
- See that there is no secondary nav even thought the page is in both the /openstack and /kubernetes bubble.
=> Add hide_subnav variable to hide the secondary nav from pages where set

static/sass/styles.scss, templates/openstack/compare.html
- Check at all screen sizes including expanding the accordions
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2574
=> Give the openstack comparison table scroll overflow and remove padding from expanded cells

static/js/src/tco-calculator.js, templates/tco-calculator/index.html
- Update text and default value of hosts on tco-calculator
- Compare to the [copy doc](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit#) and note that the current 'Number of hosts' is 12, but matches the values of X-3 on the live site.
Fixes #7095
=> Update text and default value of hosts on tco-calculator

templates/engage/index.html, templates/engage/ubuntu-core-security-audit.md
Built ubuntu core security audit engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ubuntu-core-security-audit
- Check that the page matches [the brief](https://docs.google.com/spreadsheets/d/1p_0IXORPQYA4-0wFciTVFGrDLcB8Hu615hz3PYsxm4I/edit#gid=1271849439) and [the design](https://github.com/canonical-web-and-design/web-squad/issues/2453)
- Check that the form works
- Check that this page is included at the bottom of /engage
Fixes #7006
=> Add core security audit engage page

templates/engage/ubuntu-core-security-audit.md
Change language of engage page form to english
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/ubuntu-core-security-audit
- Check that the form is in english
=> Change language of form in core security audit engage page

templates/engage/charmed-openstack-adoption-whitepaper.md, templates/engage/index.html, templates/index.html, templates/takeovers/_charmed-openstack-adoption.html, templates/takeovers/index.html
Built charmed openstack adoption takeover and engage page
- Reload the page until you see the takeover with the heading "A guide to a successful OpenStack adoption and deployment"
- Check that the CTA takes you to /engage/charmed-openstack-adoption-whitepaper
- Check that the form on the engage page works
- Check that the takeover and engage page match [the brief](https://docs.google.com/spreadsheets/d/16TXgQqDczbvzs1vyTAJIbA32VEcHy9QVVe5jFKt3Xis/edit#gid=2113339190) and [the design](https://github.com/canonical-web-and-design/web-squad/issues/2502)
- Test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or …
=> Build charmed openstack adoption takeover and engage page

.github/workflows/external-links.yaml, .github/workflows/live-links.yaml, .github/workflows/master-links.yaml, README.md, templates/legal/launchpad-terms-of-service.html, templates/security/certifications.html, templates/shared/_cloud-contact-us-form-german.html, templates/shared/forms/_desktop_help.html
I've added the following scheduled checks, and added badges for them to the README.
- "Links in master": Check internal links against master branch
- Run daily at 7:10
- "Links on live": Check internal links on https://ubuntu.com
- Run daily at 7:20
- "External links": Check external links from https://ubuntu.com
- Run weekly at 7:30 on Monday
The "external links" check fails and shows many existing 404s. I can't fix them all in this branch, so we should address this when we can. Fortunately we'll be reminded every Monday ;)
I've fixed about a million 404s from tutorials and server docs, and I've fixed some from this codebase, but there are definitely quite a few more.
QA
--
Don't think this can really be QAed, more than reading the code. We'll just have to see how it goes when we merge …
=> Add linkchecker tests

static/sass/styles.scss, templates/advantage/index.html, webapp/views.py
- Updated the layout of /advantage based on the feedback received below. When a renewal is due to expire soon, there is now information to that effect in the table indicating how many days are left. This PR doesn't provide a way for the user to do anything about it, that will come with the [Stripe integration work](https://github.com/canonical-web-and-design/ubuntu.com/issues/6202).
**QAing this is dependent on you having some subscriptions on the staging contracts service**
- Check out this branch, or visit the demo link
- Visit /advantage
- Log out, if you aren't already logged out
- See that the page looks good
- Click the sign in button at the top of the page
- If you have subscriptions associated with your account that have "effective to" dates, see that there is warning information …
=> UA renewal info markup

templates/engage/index.html, templates/engage/ubuntu-core-security-audit.md, templates/index.html, templates/takeovers/_rule4-core-cybersecurity.html, templates/takeovers/index.html
- Added a new takeover for the Rule4 core cybersecurity report
- Modified the existing engage page to remove the form and add a direct link to the PDF
- Fixed some incorrect markup on the /engage page
- Refresh until you get the "Ubuntu Core: a cybersecurity analysis" takeover
- Check that the takeover looks good at all viewports
- Click the CTA
- Check that the engage page looks good and that the "Download report" button works
- Check the last row on http://0.0.0.0:8001/engage is displaying correctly
Fixes …
=> Add rule4 takeover.

templates/index.html
I removed   451-microk8s, smart-start-webinar and anbox-cloud-webinar
Fixes #
=> Removed takeovers from rotation

webapp/api/advantage.py, webapp/app.py, webapp/views.py
In every endpoint send the session so we can  authenticate the user. 
- Add endpoints:
- Set payment method for account
```
Returns what is returned by the API: 
POST /advantage/payment-method
{
"stripe_method_id": "<STRIPE_METHOD_ID>",
"account_id": "<ACCOUNT_ID>"
}
```
- Accept renewal
```
POST      /advantage/renewals/{renewal_id}/process-payment
```
- Get renewal (returns what is returned by https://github.com/CanonicalLtd/ua-contracts/blob/develop/docs/contracts.yaml#L2187 )
```
GET     /advantage/renewals/{renewal_id}
```
Basically the flow that we need:
- setup an payment method linked to an account (via modal or whatever) -> so one POST to the first api  (`/advantage/payment-method`)
- Open a renewal that needs to be processed
- Accept the renewal (or press pay) …
=> Add endpoints for renewals

requirements.txt, webapp/views.py
QA
--
```
dotrun serve &
curl http://localhost:8001/getubuntu/releasenotes?ver=12.04.4
curl http://localhost:8001/getubuntu/releasenotes  # no arguments
curl http://localhost:8001/getubuntu/releasenotes?ver=18.04
```
^ Check curl always wants to redirect you somewhere sensible.
=> Use ubuntu-release-info

templates/public-cloud/index.html
- Updated the /public-cloud page to include Azure
[Copydoc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#)
*Note for design*: I've taken some liberties with the styling of the row that contains "Ubuntu Pro on public cloud" as the content on the right-hand column has increased significantly. Feel free to suggest alternative layouts.
Fixes #2589
=> Add Azure to public cloud page

navigation.yaml
Added subnav to /azure
- View the site locally in your web browser at: http://0.0.0.0:8001/azure and see the subnav
- Test the links
=> Add subnav for azure

templates/masters-conference/index.html
- Updated the /masters-conference page with the upcoming virtual event
- Compare to the [copy doc](https://docs.google.com/document/d/1Z63eMCe9o4Onk2ezPFLPDTbI-uJezAOzI-aSpXmZ5lc/edit#heading=h.vcxakwtmfdmp)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2532
=> Updated the /masters-conference page with the upcoming virtual event

requirements.txt, webapp/views.py
v20.2 of ubuntu-release-info incorporates [this PR](https://github.com/powersj/ubuntu-release-info/pull/3) to provide full_codename, so we don't need to use regex.
QA
--
`dotrun`, go to e.g. http://0.0.0.0:8001/getubuntu/releasenotes?os=ubuntu&ver=17.04.4&lang=en and check it still redirects you to the right release notes.
=> Update ubuntu-release-info to get full_codename

templates/index.html, templates/takeovers/_ubuntu-masters-virtual-202004.html, templates/takeovers/index.html
- Create the ubuntu masters virtual event takeover
- Added it to the homepage
- Added it to the /takeover page
- View the site locally in your web browser at: http://0.0.0.0:8001/ or the bottom of http://0.0.0.0:8001/takeovers
- Compare to the [copy doc](https://docs.google.com/document/d/1Rj_FAPxxyx0SPP5qMOZJpgPCMhK81SBTHz5ZsY6n2z0/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2531
=> Ubuntu masters virtual conference takeover

templates/advantage/index.html, webapp/views.py
- Added extra conditions for opening the table cells if a subscription is passed
- Added a login redirect if a subscription ID is provided but the user is not authenticated
- Logout of SSO
- Visit http://0.0.0.0:8001/advantage?subscription=<id>
- You should be redirected to login
- Log in
- You should be redirected to http://0.0.0.0:8001/advantage?subscription=<id>
- While logged in visit http://0.0.0.0:8001/advantage?subscription=<id>
Try ID: cAM3HMVaKsoTuMVdhGK5lWnQej0GlnuqufQNI0tlz58s
Fixes: …
=> Handle UA renewal urls

static/js/src/latest-news.js, templates/robotics/community.html
- Updated latest-news script to allow for article images
- Added article images to /robotics/community
- Scroll down to the 'Recent news' section and see that the blog posts have their associated images displayed
Fixes #7175
=> Add blog images to /robotics/community

.env, requirements.txt, webapp/app.py, webapp/security/auth.py, webapp/security/views.py
This adds an "authorization_required" decorator for securing API endpoints for the security section, and applies it to a POST endpoint at /security/notices.
This will expect to be provided with a valid macaroonbakery macaroon, and if it doesn't find one, will return a macaroonbakery JSON data structure to ask the client to forward the user to api.jujucharms.com/identity to login.
This should be all we need to allow clients to authenticate with our API. All the clients need is the small amount of code you can see in [my gist](https://gist.github.com/nottrobin/8e89667066815a263021a5d3ba248e22), the important part of which is:
``` python3
client = httpbakery.Client(cookies=MozillaCookieJar(".login"))
if os.path.exists(client.cookies.filename):
client.cookies.load(ignore_discard=True) …
```
=> Security API authentication & proof of concept

templates/download/server/power.html
- Update download server power page
- Move to live server image
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/power
- Compare to the [copy doc](https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit) and change the releases.yaml variables to see if the page changes
Fixes #7171
=> Update download server power page

templates/download/server/arm.html
- Update download server arm page
- Moved to the live server version
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/arm
- Compare to the [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit) and change the releases.yaml variables to see the page change
Fixes #7172
=> Update download server arm page

templates/download/server/thank-you-s390x.html
- Update the thank-you-s380x page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you-s390x
- Compare to the [copy doc](https://docs.google.com/document/d/1GptXtMfbgOjOmqb8DZCCTRwogkiP_cM95U9Z0gFSt7g/edit#) and change the release.yaml to see the page change
Fixes #7210
=> Update the thank-you-s380x page

templates/download/server/s390x.html
- Update the download server s390x page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/s390x
- Compare to the [copy doc](https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit)
Fixes #7170
=> Update the download server s390x page

templates/download/raspberry-pi/index.html
- Update raspberry pi download page
- Compare to the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit) and change the release.yaml variables to see the page change
Fixes #7168
=> Update raspberry pi download page

templates/telecommunications/index.html
- Add resources to /telecommunications page, made many primary ctas into buttons
- Compare to the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#) and resolve comments in there
Fixes #7177
=> Add resources to /telecommunications page

templates/engage/_base_engage_markdown.html, templates/engage/index.html, templates/engage/managed-apps-webinar.md, templates/index.html, templates/takeovers/_managed-apps.html, templates/takeovers/index.html
- Added managed apps takeover and engage page
- There is no content for the engage page so the content pane is hidden and the embed has all the content
- View the site locally in your web browser at: http://0.0.0.0:8001/ and refresh until you see the "Maintaining business focus..." takeover
- Check the design, copy and test in all viewports
Fixes #7133
=> Add managed apps takeover and engage page

navigation.yaml, templates/kubernetes/docs/azure-integration.md, templates/kubernetes/docs/backups.md, templates/kubernetes/docs/charm-openstack-integrator.md, templates/kubernetes/docs/cis-compliance.md, templates/kubernetes/docs/cni-multus.md, templates/kubernetes/docs/cni-overview.md, templates/kubernetes/docs/docker-registry.md, templates/kubernetes/docs/install-local.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/keepalived.md, templates/kubernetes/docs/multiple-networks.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/storage.md, templates/kubernetes/docs/upgrade-notes.md, templates/kubernetes/docs/upgrading.md
Update docs for 1.18 release
Add page for Multus
Add page for Azure integration
N.B. The text changes for these docs [have been reviewed already]( https://github.com/charmed-kubernetes/kubernetes-docs/tree/master)
=> K8s 1.18 release docs

templates/index.html, templates/takeovers/_ibm_athena_release.html, templates/takeovers/index.html
- Add IBM Athena release takeover
- View the site locally in your web browser at: http://0.0.0.0:8001/ and http://0.0.0.0:8001/takeovers
- Refer to the [brief for copy](https://docs.google.com/document/d/1nycVKZMjLmyC8xMtAJVRRgAUUaOlyVVa6CbU_2hkq04/edit)
Fixes #7119
=> Add IBM Athena release takeover - release 3pm(1500h) 14 April 2020

webapp/views.py
- If a subscription ID is present ensure that subscription is the first item in the table
- Visit http://0.0.0.0:8001/advantage and note the top subscription
- Visit http://0.0.0.0:8001/advantage?subscription=cAM3HMVaKsoTuMVdhGK5lWnQej0GlnuqufQNI0tlz58s the top subscription should now be different
Fixes #7157
=> Move requested subscription to the top of the table

templates/kubernetes/docs/index.md
update front page of docs to 1.18
=> bump k8s version

templates/security/certifications.html
Updated come content on the certs page
- Check against the [copydoc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit#)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html
Fixes #7220
=> Copy updates to security certifications page

.github/pull_request_template.md
I found myself writing `dotrun` in the QA instructions every time, and since people are already using it, I guess this needs to be updated.
=> Update PR template with dotrun

templates/legal/data-privacy/index.html, templates/legal/data-privacy/online-competitions.md
Added competition privacy notice to the legal section
- View the site locally in your web browser at: http://localhost:8001/legal/data-privacy
- See the link to "Online competitions privacy notice" and click it
- Compare the page with the [copydoc](https://docs.google.com/document/d/1vy3Ta47YBWoKtvpbJyk01iYv3czAQMWz54G-UErA9zE/edit#)
Fixes #7223
=> Add online competition privacy notice to legal section

templates/managed-apps/index.html
- on managed-apps page, replace MongoDb icon with text 'MongoDB Community Edition
(non SSPL)' per Katherine O
- See really ugly text instead of the logo
=> Replace MongoDB logo with text community edition

templates/index.html
Removed  takeovers/_cloud-cost-analysis.html.
I added takeovers/_ubuntu-masters-virtual-202004.html again so that it appears in the rotation more, although I am unsure if this works?
Fixes #
=> Updated takeovers

webapp/api/advantage.py, webapp/app.py, webapp/views.py
When a payment fails, the user can attempt to pay with updated payment method details, in which case we need to post to this endpoint in order for the ua-contracts service to use the new payment method on the current payment.
=> add renewals invoice endpoint

templates/masters-conference/index.html
Fixes #7273 
Updating the UM times and corrected the copy doc.
Updated the UM times and corrected the copy doc.
- Check the changes against the [copy doc](https://docs.google.com/document/d/1Z63eMCe9o4Onk2ezPFLPDTbI-uJezAOzI-aSpXmZ5lc).
*Note; I have told Katie not to include the secondary time in the copy doc.
=> Updated the UM times and corrected the copy doc.

templates/engage/fr/migrer-de-vmware-a-openstack.md
> Clotilde MoullecNew+canonical-editors@canonical.com - the marketo form for the engage page (https://ubuntu.com/engage/fr/migrer-de-vmware-a-openstack) needs to be updated to this asap. Thank you!
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/migrer-de-vmware-a-openstack
- See that the form submits
=> Update marketo form id

templates/kubernetes/index.html, templates/kubernetes/managed.html, templates/managed-apps/index.html
- Updated https://ubuntu.com/managed-apps and https://ubuntu.com/kubernetes to use the correct Google Cloud Platform logo.
(The correct logo is already used on https://ubuntu.com/download/cloud, so I am using that asset.)
=> Update Google Cloud Platform logo

webapp/api/advantage.py
A successful payment returns a 200 response with no body from the ua-contracts service, which was causing a 500 on our side when we tried to parse the body.
=> handle payment success response from ua-contract service

templates/takeovers/index.html
Fix the inclusion of _ibm_athena_release.html on takeovers
- Check the page does not 500
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7288
=> Fix the inclusion of _ibm_athena_release.html on takeovers

templates/desktop/partners.html
- Updated desktop/partners copy
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/partners
- Check the [copy](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit#)
*NOTE* The laptop image at the bottom of the page isn't ready yet and will be added in another branch
Fixes #7163
=> Copy update for desktop/partners. Add new logos

templates/server/index.html
- Updated /server landing page
- Compare with the [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#)
Fixes #7193
=> Update server landing page for 20.04

static/sass/styles.scss, templates/desktop/organisations.html
- Update images on /desktop/organisations
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/organisations
- See that the banner and laptop images are as recommended in the attached issue
Fixes #7257
=> Update images on /desktop/organisations

static/sass/styles.scss, templates/security/cve/_pagination.html, templates/security/cve/cve.html, templates/security/cve/index.html, webapp/security/fixtures/load_sample_cve.py, webapp/security/views.py
- Add basic search to /security/cve
- Add pagination to /security/cve
- Run the following commands
- `dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres` (exit command once site is ready)
- `dotrun exec python3 webapp/security/fixtures/load_sample_cve.py`
- `dotrun`
- Add the query string `?limit=1` to the URL and check that there is working pagination
- Enter `cve` in the search box and submit the form and check that there is a result
- Enter `gitlab` in the package field and submit the form and check that there is a result
- Change the priority in the dropdown and submit the form and check that there is a result
- Enter the same …
=> CVE search and pagination

requirements.txt, webapp/app.py, webapp/views.py
**Depends on https://github.com/canonical-web-and-design/canonicalwebteam.launchpad/pull/18**
This submits the form to Marketo to send the email to the user.
Also:
- Add secrets to webhooks when creating them
- Verify the secret when triggering the webhook
- Change metadata on builds: Store "_board" and "_name" instead of
"_full_name"
Marketo expects a `imageBuilderDownloadlink`, but I can't see any way
to get this download URL from
[the build object in the API](https://launchpad.net/+apidoc/devel.html#build).
QA
--
```bash
dotrun clean
dotrun
```
Now try triggering the build endpoint:
```bash
$ curl -i -X POST --data '{"action": "created", "livefs": "/~imagebuild/+livefs/ubuntu/bionic/ubuntu-cpc", "livefs_build": "/~imagebuild/+livefs/ubuntu/bionic/ubuntu-cpc/+build/211926", "status": …
```
=> Add /core/build/notify endpoint

templates/download/raspberry-pi/index.html
- Add Raspberry Pi tutorial notice to /download/raspberry-pi
- Updated copy doc
- Got to [/download/raspberry-pi](https://ubuntu-com-canonical-web-and-design-pr-7270.run.demo.haus/download/raspberry-pi), ensure the notice works well on desktop/mobile
=> Add Raspberry Pi tutorial notice to /download/raspberry-pi

templates/desktop/features.html
- Update images on /desktop/features
- redid the wide desktop, email, libre office images.
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/features
- See that the images look correct
Fixes #7256
=> Update images on /desktop/features

templates/download/shared/_server_weekly_news.html
- Update server guide pdf and thumbnail
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you
- See that the pdf has been updated and there is a new thumbnail
Fixes #7298
=> Update server guide pdf and thumbnail

templates/download/alternative-downloads.html, templates/download/server/index.html, templates/templates/_navigation-download-h.html
- Remove traditional installer from server downloads
- The copy docs have been updated as well
- http://0.0.0.0:8001/download/alternative-downloads
- http://0.0.0.0:8001/download/alternative-downloads#download
- See that it no longer mentions the traditional installer
Fixes #7308
=> Remove traditional installer from server downloads

requirements.txt, static/js/src/imageBuilder.js, templates/core/build.html, webapp/views.py
- Upgraded the store-api module to the latest.
- Map the board and os to derive the arch and filter snap searches based on it.
- If the selection changes which results in a different arch the snap list is clearer for safety.
- Sign in and select a board and OS
- You should see a sentence above the search with lets you know the arch you have selected and warn that searches are filtered on this.
- Search for something and add a few snaps
- Then make a different selection, one resulting in different architecture and see that snap lists clear.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2395
=> Search based on the selected architecture

templates/server/index.html
Removed a line from the features list
- See that the line marked for removal in the [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit?ts=5e9f41db) is no longer present
=> Remove nftables list item

templates/shared/pricing/_ua-for-infrastructure.html
- Update cis link in /pricing/infra
- See that the link on 'CIS Benchmark' goes to http://0.0.0.0:8001/security/certifications#cis
Fixes #7219
=> Update cis link in /pricing/infra

releases.yaml, templates/download/raspberry-pi/index.html
- Update iso names for raspberry pi, they are now all the same for pi 2,3,4, so I removed the raspi2 or raspi3 names for raspi and updated the checksums
- See that all the buttons go to 'ubuntu-20.04-preinstalled-server-arm64+raspi.img.xz' for 64 bit and 'ubuntu-20.04-preinstalled-server-armhf+raspi.img.xz' for 32 bit
=> Update iso names for raspberry pi

templates/download/alternative-downloads.html
- Add live installer to /download/alternative-downloads
- View the site locally in your web browser at: http://0.0.0.0:8001/download/alternative-downloads
- Compare to the [copy doc](https://docs.google.com/document/d/1VhmFVE3dK81mE3zcC9FVA6f5SGJ-DHan7WWlrlfRcvo/edit?ts=5ea09cb4#)
=> Add live installer to /download/alternative-downloads

templates/security/_notice-brief.html, templates/security/notice.html, templates/security/notices.html, webapp/security/models.py
Add a property to the model that returns the current support tag for an ubuntu release.
- dotrun clean
- dotrun
- dotrun ./webapp/security/fixtures/releases.py
- go to security/notices and see that the dropdwon shows the right support tag for each release
=> Add a property for the release support tag

entrypoint, scripts/clear-database.py
DB migration errors have caused a lot of difficulties with
QAing. This should improve things by prompting the user
to erase the database when migration errors are encountered.
QA
--
```
git checkout cve
rm usn.sqlite3
git checkout handle-db-migration-errors  # back to this branch
dotrun serve
```
^ this should now error on DB migration and prompt you to delete your database. If you choose "y", it should successfully run the site.
=> Handle db migration errors

navigation.yaml, templates/security/cve/index.html, templates/templates/_navigation-developer-h.html
- Added a "Clear filters" button to the CVE search
- Commented out links to /security/cve for soft launch
- Run the following commands
- If you get an error saying something is already running on that port: `sudo kill -9 `sudo lsof -t -i :5432``
- `dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres`
- `export DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres`
- `alembic upgrade head`
- `dotrun exec python3 webapp/security/fixtures/load_sample_cve.py`
- If you have an error here you may need to drop the database schema. To do that follow the steps in this comment: https://github.com/canonical-web-and-design/ubuntu.com/pull/7242#issuecomment-616435249
- `dotrun`
- View the site locally in your web …
=> Add clear filter button to CVE search

releases.yaml, templates/download/alternative-downloads.html
- Update /download/alternative-downloads with named older releases to help POWER, ARM and LinuxONE people file older releases more easily
- View the site locally in your web browser at: http://0.0.0.0:8001/download/alternative-downloads
- See that the 'Past releases and other flavours' mentions these other release types and lists the main older releases.
Fixes #7319
=> Update /download/alternative-downloads with named older releases

templates/download/raspberry-pi/index.html
- Sentence case Pi on /download/raspberry-pi
- Updated the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit)
- View the site locally in your web browser at: https://ubuntu.com/download/raspberry-pi
- `s/it onto your pi and away you go./it onto your Pi and away you go./`
=> Sentence case Pi on /download/raspberry-pi

releases.yaml, templates/download/shared/_verify-checksums.html
- Update 20.04 desktop and server checksums, handle no checksums
- Currently, the raspi images do not have them, so I made the verify partial put instructions on how to get them instead.
- working version - http://0.0.0.0:8001/download/server/thank-you?version=20.04&architecture=amd64
- alternate message - http://0.0.0.0:8001/download/raspberry-pi/thank-you?version=20.04&architecture=arm64+raspi - which will 404 for now, but you can see what the URL will be
Partially fixes #7201
=> Update 20.04 desktop and server checksums, handle no checksums

releases.yaml
- Add raspi checksums to the releases.yaml
- View the site locally in your web browser at: http://0.0.0.0:8001/download/raspberry-pi/thank-you?version=20.04&architecture=armhf+raspi
- See that the checksums are in the verify modal.
=> Add raspi checksums

templates/openstack/consulting.html
I changed the datasheet on [/openstack/consulting](https://ubuntu.com/openstack/consulting) in two places to https://assets.ubuntu.com/v1/d4766546-Private-Cloud-Build_Datasheet.pdf.
- Compare the demo page to the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
=> Updated the datasheet on /openstack/consulting

templates/download/server/arm.html, templates/download/server/power.html
- Remove netboot option from /download/arm and /download/power
- Updated the copy docs
- **Note - we should redesign these pages**
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/power and http://0.0.0.0:8001/download/server/arm
- See that the netboot box has been removed
=> Remove netboot option from /download/server/arm and /download/server/power

templates/kubernetes/index.html, templates/kubernetes/managed.html
- Check that the datasheet URL is updated to `https://assets.ubuntu.com/v1/b5f9ae49-Enterprise_Kubernetes_Datasheet.pdf` on:
- /kubernetes: 
- in 'Upstream K8s options...' > Charmed Kubernetes > 'Charmed Kubernetes Datasheet'
- in 'AI/ML add-on...' > 'Download the Enterprise Kubernetes datasheet' at bottom
- /kubernetes/managed
- in hero section
- in Resources section
Fixes #7292
=> Update enterprise k8s datasheet links

templates/desktop/developers.html
- Change the Gnome version used by 20.04 LTS.
-  Check the version is 3.36 instead of 1.36.
=> Fix the gnome version

releases.yaml
- Update raspi checksums
- View the site locally in your web browser at: http://0.0.0.0.:8001/download/raspberry-pi/thank-you?version=20.04&architecture=arm64+raspi and http://0.0.0.0.:8001/download/raspberry-pi/thank-you?version=20.04&architecture=armhf+raspi
- See that they match the checksum here: http://cdimage.ubuntu.com/releases/20.04/release/SHA256SUMS
Fixes #7343
=> Update raspi checksums

static/sass/styles.scss, templates/security/cve/cve.html
Replace the CVE status corner ribbon with a card style
- Run `dotrun exec python3 webapp/security/fixtures/releases.py`
- Run `dotrun exec python3 webapp/security/fixtures/load_sample_cve.py`
- Run `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/CVE-2019-1010262 and http://0.0.0.0:8001/security/CVE-2020-7629
- Check that the 'Not in Ubuntu' and 'Rejcted' look like the screenshot: https://usercontent.irccloud-cdn.com/file/UIG9Nihs/image.png
=> CVE page status

static/js/src/latest-news.js
Fix bug where blog post thumbnails aren't displayed
- Check that the posts in the "Recent news" section have thumbnails
=> Fix bug with blogpost thumbnails not being displayed

Dockerfile
We need gpg installed to be able to encrypt the user's
data to attach to the build.
``` bash
docker build -t ib .
docker run -ti -p 8888:80--env DATABASE_URL=sqlite:///something --env LAUNCHPAD_TOKEN={thetoken} --env LAUNCHPAD_SECRET={thesecret} ib
```
Go to http://localhost:8888/build, kick off a build, check it successfully is kicked off.
=> Install gpg

static/js/src/imageBuilder.js, templates/build/index.html, webapp/views.py
- The search wasn't filtering by architecture at all (it was using the wrong parameter name)
- Remove the need for the client-side to have the whole architectures mapping
- Improve the wording for the architecture warning notice
QA
--
`dotrun`, go to `/build`, play around with searching for snaps, changing boards etc. Try to break the state of the page.
=> Fix board architectures search

templates/azure/pro.html
Update the copy to reflect the 20.04 release on /azure/pro
- Check that Lech's requested changes in [the copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit) have been actioned (please resolve the comments)
Fixes #7354
=> Update links to 20.04 on /azure/pro

templates/public-cloud/index.html
Update azure link on /public-cloud from 18.04 to 20.04
- Make sure the change requested by Lech in [the copy doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit) has been actioned (please resolve the comment)
Fixes #7355
=> Update public cloud page copy with 20.04 link

templates/azure/index.html
Update links to 18.04 with 20.04 on /azure page
- View the site locally in your web browser at: http://0.0.0.0:8001/azure
- Check that the changes requested by Lech in [the copy doc](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit#heading=h.rwz46gtc2v3z) have been actioned (please resolve comments)
Fixes #7356
=> Update 18.04 links to 20.04 links on azure page

templates/build/index.html
Remove autocomplete and reset from the search field
- View the site locally in your web browser at: http://0.0.0.0:8001/build
- Sign in
- Select and board and OS
- Search for something and see you do not see a autocomplete popover
- See that the reset or clear is not there. 
Fixes the comments here: https://github.com/canonical-web-and-design/ubuntu.com/pull/6695#issuecomment-620590768
=> Remove autocomplete and reset from the search field

static/js/src/dynamic-contact-form.js, static/js/src/navigation.js
- Keep URL UTM params in localstorage
- Resurface them in forms
- Prevent takeover UTMs from being stored (special case we don't need/want covered for now)
- ...some unintended JS cleanup (thanks vscode?)
- Open the localstorage inspector of your browser
- Add `?utm_source=foo` to any ubuntu.com URL
- Ensure `utm_source` = `foo` is stored in localstorage
- Open a form (/engage page with a whitepaper or a dynamic contact form)
- Ensure the form source loads with hidden fields matching the UTM ones stored in …
=> Store session UTMs in localstorage, resurface them on form fills

templates/public-cloud/index.html
- Updated the laptop image on the public cloud page
- See the image in the "developers' favourite" section
Fixes #7191
=> Update public cloud page laptop image

templates/desktop/index.html
Updated logo cloud on /desktop
- Check that the logo cloud under the hero uses [this image](https://assets.ubuntu.com/v1/741b30ec-desktop-logos.png)
Fixes #7368
=> Update logo cloud on desktop page

templates/managed-apps/index.html
Add Cassandra logo and copy in "How Canonical Managed Apps work" section
Fixes #7369
=> Add cassandra logo and copy in How Canonical Managed Apps work

Dockerfile, requirements.txt, webapp/views.py
Introduces image_format=ubuntu-image when calling build API. Also requires
auth_consumer separately from username.
QA
--
`dotrun`, go to `/build`, submit a build, check it works fine.
=> Fix builds by using launchpad v0.5.1

webapp/app.py
Remove proxy trust from level 2 to 1. Which is by defualt on flask base.
=> Remove proxy trust to use default from flask base

templates/build/index.html
Remove classic os from the build selection
- View the site locally in your web browser at: http://0.0.0.0:8001/build
- See there is no classic os options
- I have left the logic there for the future
=> Remove classic os from the selection

templates/managed-apps/index.html
- Undo today's text change on /managed-apps
- See that it matches the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit?ts=5ea9ad20#)
Fixes #7376
=> Undo text change on /managed-apps

templates/engage/20.04-webinars.html
- Change order of 20.04 webinars - Desktop on top now
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/20.04-webinars
- See that Nilay's is on top and Tytus on the bottom
=> Change order of 20.04 webinars

templates/aws/index.html, templates/aws/shared/_get_pro.html
- Update /aws for 20.04
- View the site locally in your web browser at: http://0.0.0.0:8001/aws
- Compare to the [copy doc](https://docs.google.com/document/d/1lkH-MSPmgjCMP4gI0FW29YIKVDvBuddxA63iQhmsYIU/edit#) and resolve all comments
Fixes #7382
=> Update /aws for 20.04

templates/azure/pro.html
- Update /azure/pro page for 20.04
- Compare to the [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#) and resolve all comments
Fixes #7380
=> Update /azure/pro page for 20.04

templates/aws/pro.html
- Update /aws/pro for 20.04
- Compare to the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#) and resolve all comments
Fixes #7381
=> Update /aws/pro for 20.04

templates/engage/index.html, templates/engage/moving-to-opensource-whitepaper.md
- Added a new engage page from this [brief](https://docs.google.com/spreadsheets/d/1bkM14vEn8noJcQVphj9B_iGV6suh6NYoJncmG-5e_D4/edit#gid=1271849439)
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/moving-to-opensource-whitepaper
Fixes #7338
=> Add moving to open source whitepaper engage page

webapp/views.py
- Removed the opt out conditional as the build is operational and the opt out is for marketing so it should be set in marketo.
- Change the init value of status to Null [which is a special key reserved for this in Marketo](https://nation.marketo.com/t5/Product-Discussions/String-Field-to-Null-Value/m-p/54287#M23509).
- Go to https://ubuntu.com/core/build
- Fill in the build and ensure you select the checkbox for marketing
- See that you get an email almost straight away with the previous status
- Go to: https://app-sjg.marketo.com/#SL100892270B2LA1
- Click the ID by your name
- Search for "Image Builder Status" and see its what you got in your email. __This is due to empty string not overriding the status value__
- Go to this branches demos at /core/build
- Complete a different build
- …
=> Post NULL Image build status value initially

templates/public-cloud/index.html
- Updated the aws link from the [copydoc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit)
- Check the link and link copy
Fixes #7383
=> Update aws link to 20.04

templates/base_index.html
Update the default takeover with the LTS with a fresh gradient.
- Turn off JS in inspector settings and refresh
- See the takeover says 20.04 LTS instead of 19.10
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7400
=> Update the default takeover with the LTS

static/js/src/cve/cve-search.js, static/js/src/cve/cve-search.test.js, static/js/src/cve/cve.js, templates/security/cve/cve.html, templates/security/cve/index.html, webpack.config.js
Made CVE search form work as intended
Drive by: formatted the date strings on a CVE page
``` bash
rm usn.sqlite3
dotrun exec python3 webapp/security/fixtures/releases.py
dotrun exec python3 webapp/security/fixtures/load_sample_cve.py
dotrun
```
- Go to `/security/cve` and put a valid CVE ID (e.g. CVE-2020-10535) in the search field
- Check that the package and priority fields are disabled
- Check that the search button has turned into a button which takes you to the CVE page
- Enter a term from the CVE description into the search field e.g. any part of the following string assuming you used the example CVE ID above:
> GitLab 12.8.x before 12.8.6, when sign-up is enabled, allows remote attackers to bypass email domain
- Check that the CVE containing that …
=> CVE search form

static/js/src/latest-news.js, templates/base_index.html
- Hide the latest news section when no js on homepage
- See the "Latest news sections is there and works fine"
- Disable `js` and reload the page
- See a link to our blog
=> Hide latest news section when no js on homepage

templates/engage/moving-to-opensource-whitepaper.md
- Updated the hero and meta image for /engage/moving-to-opensource-whitepaper
- View the site locally in your web browser at: http://localhost:8001/engage/moving-to-opensource-whitepaper
- See the updated here and meta image
Fixes #7404
=> Change hero image and meta for move to open source takeover

requirements.txt, webapp/views.py
By using the new version of create_update_system_build_webhook.
Also:
- Send imageBuilderId to Marketo
- Correct the downloadUrl
QA
--
`dotrun`, check you can still create builds fine.
The rest is pretty hard to QA. Contact me if you're really keen.
=> Reset webhook secret

templates/download/server/provisioning.html
I added <a href="https://maas.io/install" class="p-link--external">https://maas.io/install</a> to the copy.
- Compare the demo(/download/server/provisioning) to the [copy doc](https://docs.google.com/document/d/12GXYcP9WrOgoso6Sf3bQql6nALRUzpdlcRW3Gbu-npM/edit) and accept the correct changes.
Fixes #
=> Added link to download/server/provisioning

templates/kubeflow/what-is-kubeflow.html
- Change cta link on /kubeflow/what-is-kubeflow page
- Cleaned up the copy doc
- Fixed some grammar 
- Compare to the [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit#) and resolve all comments
Fixes #7433
=> Change cta link on /kubeflow/what-is-kubeflow page

templates/openstack/consulting.html
- Update /openstack/consulting page copy, title, meta description and h1
- Compare to the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#) and resolve all comments
Fixes #7432
=> Update /openstack/consulting page copy

templates/security/certifications.html
- Add STIG 18.04 checklist link to /security/certifications
- Compare to the [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit#) and resolve all comments
Fixes #7440
=> Add STIG 18.04 checklist link to /security/certifications

templates/security/certifications.html
- Replace s/LTSand/LTS and/
- View the site locally in your web browser at: http://0.0.0.0:8001/security/certification
- See that there is a space now.
=> Add a space in /security/certification

templates/security/certifications.html
Update copy on /security/certifications
- Check that the requested changes in [the copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit) have been made and resolve the comments
Fixes #7442
=> Update copy on /security/certifications

templates/appliance/_base-appliance.html, templates/appliance/about.html
- Added base template for /appliance
- Added first pass of /appliance/about
[COPYDOC](https://docs.google.com/document/d/1UM4K9n9SFNiWdmKIBnPGCsjLQrPSOnqZHMNIMwQ2CZI/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/about
Fixes #7412
=> WIP: Add appliance base and first pass of about page

templates/appliance/index.html
Add the appliance homepage
- View the site locally in your web browser at: http://0.0.0.0:8001/applance
- Check it matches [the copy doc](https://docs.google.com/document/d/1Fcr5b5Rn06AB89D6DGPmoIgXLxLalijMhwnu_IyUxV4/edit#)
- Check it matches [the design](https://app.zeplin.io/project/5eb3d16a91c4117789940141/screen/5eb40ad3e0674e7503f6ce42)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7411
=> Add the appliance homepage

templates/templates/_navigation-developer-h.html, templates/templates/_navigation-enterprise-h.html
Added appliance to the menus based on the information from Rhys:
> rhys-davies: ant for the moment let's list it under Enterprise/IoT and Developer/make-devices with the intention of giving it its own place later
Removed "Drones and autopilots" based on @matthewpaulthomas request.
- Open both menus and see the links work
Fixes #7431
=> Added appliance to the menus

templates/templates/_navigation-enterprise-h.html
- Removes duplicate “Embedded Linux with Ubuntu” link from the “Enterprise” mega-menu
- Open the “Enterprise” mega-menu
- Look at the “Internet of Things” section
None. This issue did not exist in [the copydoc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit).
[Discovered while looking at @lyubomir-popov’s mockups of the new link colour.]
=> Removes duplicate “Embedded Linux with Ubuntu” link

static/js/src/dynamic-contact-form.js, templates/appliance/_base-appliance.html, templates/appliance/governance.html, templates/shared/forms/interactive/_appliance.html
- Create the appliance modal contact
- Add the invoke class to the link in the governance page
- Remove the thank you hack
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance#get-in-touch
- Check that the modal matches the [copy doc](https://docs.google.com/document/d/1DLkSZGAuOQYZqBg02r2pVGT6rfXK_0aBpoEEMrngnDk/edit#heading=h.s5zvgb70wqn)
- Clicking the contact Canonical link in the governance page invoked to modal
Fixes #7458
=> Create the appliance modal contact

navigation.yaml, webapp/app.py
Initiate a discourse-docs instance for the appliance section.
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/docs
- Check that the docs index renders but there is currently no navigation
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7418
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7419
=> Add docs instance for appliance bubble

navigation.yaml, templates/appliance/tutorials.html
- Built the appliance tutorial page linking to the existing tutorials
- Added the page to the naviagiton
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/tutorials
- Check it matches the [copy doc](https://docs.google.com/document/d/1CgtFLYJqHJIrRbkvqFzvUoIBsgeWUD9o6gV3bbUOdqU/edit#heading=h.c417a2j3hga) _as much as it makes sense_
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7421
=> Appliances tutorials

templates/engage/eu-kubernetes-event.md, templates/engage/index.html, templates/engage/pre-kubecon-event.md, templates/index.html, templates/takeovers/_eu-kubernetes-event.html, templates/takeovers/index.html
Add takeover and engage page for EU kubernetes event
- Reload the page until you see the "Kubernetes From Cloud to Edge" takeover
- Check the takeover matches [the brief](https://docs.google.com/spreadsheets/d/1A5DO1jxYXbkQ4Ule1lhxo9s25_UukK3maokZs9c1NCY/edit#gid=1271849439)
- Click through to the engage page and check that it matches [the copy doc](https://docs.google.com/document/d/1VYYmd6kS0eWApEpbVCgTUq0NOHUTEeRWVj7ujtFEsHs/edit#)
=> Add pre-kubecon takeover and engage page

templates/engage/azure-webinar.md, templates/engage/index.html, templates/index.html, templates/takeovers/_azure-webinar-takeover.html, templates/takeovers/index.html, webapp/app.py, webapp/security/views.py, webapp/views.py
Add takeover and engage page for Azure webinar
- Reload the page until you see the "Leveraging open source with Ubuntu Pro on Azure:" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1QH2O8NiiJnRYSYnOQz4IOZLK83hx-bAptwzJL_FJ2ko/edit#gid=2113339190)
- Click through to the engage page and check that it matches [the brief]
- Test the engage page on [https://socialdebug.com/](https://socialdebug.com/) or [http://debug.iframely.com/](http://debug.iframely.com/) and …
=> 7466 azure webinar and engage page

templates/support/index.html
- Added link to free Ubuntu Advantage
- Added detail on certifications
- Updated Ubuntu Advantage for AWS and Azure
- Compare to the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#) and resolve all comments
Fixes #7477
=> Update copy on /support

templates/security/certifications.html
- updated the certification page copy and added a contact modal
- Check that the contact modal works and that the [copy] matches
Fixes #7478
=> Update certs page copy and add contact modal

webapp/advantage.py, webapp/app.py, webapp/login.py, webapp/views.py
- CONTRACTS_API_URL to override https://contracts.canonical.com
- CANONICAL_LOGIN_URL to override https://login.ubuntu.com
QA
--
Try:
``` bash
CANONICAL_LOGIN_URL=https://login.staging.ubuntu.com dotrun serve
```
Go to http://localhost:8001/advantage, login, see you get sent to `https://login.staging.ubuntu.com` (where you probably don't have an account).
Try:
``` bash
CONTRACTS_API_URL=https://contracts.staging.canonical.com dotrun serve
```
Go to http://localhost:8001/advantage, login, see you are seeing staging data.
=> Provide environment variables for overriding URLs

templates/engage/eu-kubernetes-event.md
Changed "Innovating and scaling efficiently, with Charmed Kubernetes and MicroK8s" as it was spelt "Kuberenetes"
=> Fixed type on pre-Kubecon event subtitle

static/js/src/renewals/set-modal-info.js, static/js/src/renewals/tests/fixtures/payment-methods.js, static/js/src/renewals/tests/set-modal-info.test.js, templates/advantage/_stripe-modal.html, webapp/advantage.py, webapp/app.py, webapp/views.py
- Changed date format in the renewal modal to match what was already in the subscription tables
- Added "(if required)" to VAT field
- Changed "Starts:" to "Will continue from:"
- Visit /advantage in the demo
- Login
- If you don't have test contracts up for renewal, ask Scott to set you up with one
- Open the renewal modal, see that the points [here](https://github.com/canonical-web-and-design/web-squad/issues/2597#issuecomment-627841020) have been addressed
=> Renewals ux tweaks

static/js/src/cve/cve-search.js, static/js/src/cve/cve-search.test.js, static/js/src/cve/cve.js, templates/security/cve/index.html
Fix CVE search so it doesn't 404 if CVE doesn't exist
- Search for a cve ID that doesn't exist e.g. CVE-1234-1234
- Submit the form and check that the page has 0 results and you don't go to a 404 page
=> Fix CVE search redirect

static/sass/_pattern_cve.scss, static/sass/styles.scss, templates/security/cve/cve.html, templates/security/cve/index.html
Add priority icons to CVE pages and CVE table
- Delete the `usn.sqlite3` file
- Run `dotrun exec python3 webapp/security/fixtures/releases.py`
- Clone [the CVE tracker repo](https://github.com/carkod/ubuntu-cve-tracker/tree/load-cve) and checkout the `load-cve` branch
- Create a virtual environment: `python3 -m venv venv`
- Activate the virtual environment: `. venv/bin/activate`
- Install dependencies: `pip install requests cvss macaroonbakery`
- In the `ubuntu-cve-tracker` repo change into the `scripts` directory
- Run: `python upload-cve.py ../active`
- You will be asked to authenticate via a browser and be presented with a link
- The CVEs will then be uploaded which may take a few minutes
- View …
=> Add cve priority icons

appliances.yaml, navigation.yaml, templates/appliance/adguard/index.html, templates/appliance/adguard/raspberry-pi.html, templates/appliance/plex/index.html
- Build the Adguard appliance page
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/adguard
- Check it matched the [copy doc](https://docs.google.com/document/d/1-OETrr26H36YpewFgSlCxOaSXSf3QoWpKZV5lc8ONbs/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7427
=> Build the Adguard appliance page

templates/appliance/adguard/index.html, templates/appliance/plex/index.html, templates/appliance/shared/_download_widget.html
Add the JS to link to the download page
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex
- Check that the download button goes to the raspberry-pi thank you page
- Check that when you change the select the link changes
- Try out the /appliance/adguard page
Fixes #7497
=> Add the JS to link to the download page

templates/appliance/adguard/pc.html, templates/appliance/plex/pc.html, templates/appliance/shared/_install_instructions_intel-nuc.html, templates/appliance/shared/_install_instructions_pc.html, templates/appliance/shared/_pc.html, templates/appliance/shared/_steps_pc_thats-it.html, templates/appliance/shared/_steps_setup-kvm.html
- Created a template for PC install instructions
- Added this to Plex and AdGuard
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/adguard/pc and http://0.0.0.0:8001/appliance/plex/pc
- See that it works for the above pages and the [copy doc](https://docs.google.com/document/d/1G8IJoHrhd1RP3dHqyiasteMxPrxCwW5Sf0Vh3AY2SHQ/edit#)
Fixes #7496
=> Add appliance PC setup page

appliances.yaml, templates/appliance/adguard/index.html, templates/appliance/index.html, templates/appliance/openhab/_start-using.html, templates/appliance/openhab/index.html, templates/appliance/openhab/intel-nuc.html, templates/appliance/openhab/raspberry-pi.html, templates/appliance/plex/index.html
Create the OpenHab appliance pages.
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/openhab
- Check it matches the [copy doc](https://docs.google.com/document/d/14sEgchP6BUjnUtJt67XJ-fKl7k8dAevaf5EJac9Pmyc/edit#)
- Go to the instructions page: http://0.0.0.0:8001/appliance/openhab/raspberry-pi
- Check it matches the [copy doc](https://docs.google.com/document/d/19BL4l1m7F_jE-GkMGxg19KG1SsZtqzjLAFuyLngSy9Y/edit)
- Check it matches [the design](https://app.zeplin.io/project/5eb3d16a91c4117789940141/screen/5ebd0f192d60fe1b8e8aa73c)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7426
=> Create the OpenHab appliance pages

navigation.yaml, templates/appliance/adguard/pc.html, templates/appliance/openhab/pc.html
- Add PC install page for openhab
- Add openhab to the navigation
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/openhab/pc
- See that the page looks like the others, but with openhab branding
=> Add /appliance/openhab/pc page

templates/engage/index.html, templates/engage/snapd-whitepaper.md, templates/index.html, templates/takeovers/_snapd-takeover.html, templates/takeovers/index.html
Built the takeover and engage page for core and snaps whitepaper
- Reload the page until you see the "Solving the software update challenge for IoT devices" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1UYzDr_lRCTESFY9TodAZw_CLqR48ADfdwXmEH9nCZ-w/edit#gid=2113339190)
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1UYzDr_lRCTESFY9TodAZw_CLqR48ADfdwXmEH9nCZ-w/edit#gid=1271849439)
Fixes #7340
=> Build core and snaps takeover and engage page

templates/legal/ubuntu-advantage-service-description/_toc.html
- update the toc on the Ubuntu Advantage Service Description doc
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- See that the TOC has all the h2's from the page
=> Fix /uasd table of contents

webapp/security/models.py
Fix the order by so it does not error when the backend is PostgreSQL
- Make sure the page renders
=> Fix error in order_by so it works in PostgreSQL

templates/contact-us/form/index.html, templates/legal/ubuntu-advantage-service-description/_toc.html
- Add a ossa flavour of the contact-us form for an upcoming webinar
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us/form?product=ossa
- Compare to the [copy doc](https://docs.google.com/document/d/1X1Qx5cimbU7D_xQKnm3se9gRDFcRDEaX5fkGR42b3yU/edit)
=> Thibauts form

templates/wsl/index.html
Updated to ubuntu.com/wsl
1.  Changed IDE -> IDEs
2. Added <p><a class="p-link--external" href="https://www.brighttalk.com/webcast/6793/410412">Register for the “Kubernetes on Windows with WSL2” webinar</a></p>
- Check the demo against the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit?ts=5ec21850)
=> Slight copy change and addition of link on /WSL

templates/tco-calculator/index.html
- "TCO calculator" -> "Private cloud TCO calculator"
- Ensure the [page](https://ubuntu-com-canonical-web-and-design-pr-7516.run.demo.haus/tco-calculator) matches the [copy doc](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit#heading=h.c6wjbvvp8mcm)
=> Update /tco-calculator page title

templates/index.html, templates/takeovers/_moving-to-opensource-whitepaper.html
Add takeover for "Embracing the open source mandate" engage page
- Refresh until you get the "Embracing the open source mandate" takeover
Fixes #2761
=> Add open source mandate takeover

templates/download/raspberry-pi/index.html, templates/download/raspberry-pi/thank-you.html, templates/download/shared/_verify-checksums.html, webapp/views.py
- Updated copy on the raspi download page
- Added an 18.04 row
- Added support for a patch number in download URL generation
- Changed checksum link to cdimages
- View the site locally in your web browser at: http://0.0.0.0:8001/download/raspberry-pi and check the download links work.
- Go through to the thank you page of one of the 18.04 links and ensure that the checksum works
- Check some of the non-pi download pages
Fixes #2758
=> Add 20.04 row to RasPi page. Change SHA256SUMS link to cdimages. Add support for patch numbers in download link generation

templates/engage/fr/utiliser-gpgpus-avec-kubernetes.html
Added GPGPUS Kubernetes engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/utiliser-gpgpus-avec-kubernetes
- Check that the page matches [the copy doc](https://docs.google.com/document/d/11wv7ic0Wx-GQqzoDwYGsyu6IkLR2la7_NUSpHfk9Hew/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2750
=> Add GPGPUS K8s engage page

templates/engage/fr/managed-apps.html
Add French managed apps engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/managed-apps
- Check that page matches [the copy doc](https://docs.google.com/document/d/1JiT1isBEh4a-UGL4yR4yJe4cvpg94dA8MhKGuv22whg/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2749
=> Add French managed apps engage page

templates/engage/eu-kubernetes-event.md
Updated the copy on /engage/eu-kubernetes-event
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/eu-kubernetes-event
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/1VYYmd6kS0eWApEpbVCgTUq0NOHUTEeRWVj7ujtFEsHs/edit?ts=5ec29694#) have been made
- Resolve the comments
Fixes #7532
=> Update copy on k8s event engage page

templates/training/index.html
Updated copy on /training
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#) have been made
- Resolve the comments
Fixes #7526
=> Update copy on training page

templates/security/_notice-brief.html, templates/security/notice.html, webapp/security/views.py
Remove the `USN-` prefix in templates, since the prefix should actually be part of the ID stored in the database.
- load notices into the db(ask me for help if you dont know how to)
- dotrun
- go to `localhost:8001/security/notices`
- make sure there it all renders fine
=> Remove 'USN-' prefix from templates

templates/desktop/features.html
- Corrected typo: "Shortcut" -> "Shotcut"
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/features
- See that "Shotcut" is correctly spelled
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html
Fixes #7514
=> Correct the name of Shotcut from 'Shortcut'

static/js/src/core.js
- Make cookie message last 10 seconds, it was mistakenly 1 second
- View the site locally in an *incognito* web browser at: http://0.0.0.0:8001/
- See that the cookie message lasts longer
=> Make cookie message last 10 seconds

templates/core/build/index.html, templates/download/raspberry-pi/thank-you.html
- Corrected references to Pi 4 using micro USB
- View the site locally in your web browser at: http://0.0.0.0:8001/download/raspberry-pi/thank-you?version=20.04
- See the correct USB-C reference for the Pi 4
- http://localhost:8001/build
- Select a build
- See the instructions correctly reference USB-C for the Pi 4
Fixes #7515
=> Correct references to micro USB for Pi 4 to USB-C

templates/contact-us/form/index.html
- Update OSSA contact-us form id
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-form?product=ossa
- See that the form id is now '1257'
=> Update OSSA form id

templates/engage/_base_engage_markdown.html, templates/engage/eu-kubernetes-event.md
- Updated the meta description of /engage/eu-kubernetes-event
- Show the cta button on all sizes on /engage/eu-kubernetes-event
- View the site locally in your web browser at: http://0.0.0.0:8001engage/eu-kubernetes-event
- Check that the cta button is visible on desktop sized viewports
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2763#issuecomment-631515275
=> Update eu k8s event page

templates/public-cloud/index.html
- Updating the programme name from 'Certified Public Cloud' to 'Public Cloud'
- See that the logo cloud still loads
=> Update partner programme name

templates/kubeflow/install.html, templates/kubeflow/shared/_learn-more.html
- updated kubeflow install instructions
- Compare it to the [copy](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit#)
Fixes #7525
=> Copy updates to kubeflow install page

requirements.txt
Revert template finder to fix contact us modals
- Check http://0.0.0.0:8001/shared/forms/interactive/_general loads
- Click contact us and see modal
Fixes #
=> Revert template finder version

.github/workflows/cypress.yaml
- Add build step for cypress test
- This will make faster the start of the server handled by the cypress action that was taking too long to start (because of building and installing deps)
=> Add build step for cypress testing

tests/test_views.py, webapp/views.py
- Make renewals renewable only when actionable and current.
- Create non-actionable renewals, or renewals whose start date is in the future, or end date in the past: the button to renew should not be shown.
- It should be still possible to renew renewals that are both actionable and with start <= now <= end.
=> Hide renewals when not actionable or current

templates/index.html, templates/takeovers/_ubuntu-masters-roblox.html
- Created a takeover in the style of the previous Masters one for the Roblox webinar
[copy](https://docs.google.com/document/d/1_xbVloqalCo5di05VDWaLX19HkNuo2L8UoeKk5LI5z8/edit) (I shortened the H1 and moved it into the subtitle)
[Design for last takeover](https://github.com/canonical-web-and-design/web-squad/issues/2017)
- Refresh until you see the "From bare metal to the edge" takeover
Fixes #2698
=> Add ubuntu masters roblox takeover

templates/engage/fr/canonical-ajoute-containerd-a-ubuntu-kubernetes.html
Add french Ubuntu k8s engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr/canonical-ajoute-containerd-a-ubuntu-kubernetes
- Check that the page matches [the copy doc](https://docs.google.com/document/d/12j3_XhZkNwAy7WTgpe9t5THJU84EtaA1VEyQ86VOgOI/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2751
=> Add ubuntu k8s french engage page

navigation.yaml, templates/managed/kafka.html
Built /managed/kafka page
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/kafka
- Check that it matches [the copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/) and [the design](https://camo.githubusercontent.com/dfa9acbc9e0cd45b918d11b26b655981cc3e5424/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565623933333839653062346366643037636136326232362f34313765656466342d633565362d346562652d393935382d353635323331373734376665)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2755
=> Add kafka page

templates/engage/fr/guide-du-DSI-pour-les-operations-multicloud.md, templates/engage/index.html, templates/index.html, templates/takeovers/_cio-guide-to-multipass-fr.html, templates/takeovers/index.html
- Built takeover and added to /takovers
- Built engage page and added to /engage
- Change your browsers language settings to French
- Refresh until you see the "Choisir une architecture cloud rentable" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1GdeDl3mV-8RyqknFRZ0Kk8dbKzSKxHyL5qQyNcWy0gg/edit#gid=2113339190)
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1GdeDl3mV-8RyqknFRZ0Kk8dbKzSKxHyL5qQyNcWy0gg/edit#gid=1271849439)
Fixes #7451
=> Add CIO french engage page

templates/engage/eu-kubernetes-event.md
- Updated the title and meta description of the eu-kubernetes-event engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/eu-kubernetes-event
- See that the title and meta description match the [brief](https://docs.google.com/spreadsheets/d/1A5DO1jxYXbkQ4Ule1lhxo9s25_UukK3maokZs9c1NCY/edit?ts=5ec78e52#gid=1271849439)
=> Update title and meta description on /engage/eu-kubernetes-event

templates/engage/eu-kubernetes-event.md
- Update time of /engage/eu-kubernetes-event event
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/eu-kubernetes-event
- See that it is 4-6pm not 5-7pm now
=> Update time of /engage/eu-kubernetes-event event

Dockerfile, templates/engage/eu-kubernetes-event.md, templates/kubernetes/index.html, templates/templates/navigation-download-h.html
- Added a "Mac and Windows" entry to the download mega menu, server section.
- Copy doc updated
- Ensure the [menu item](https://ubuntu-com-canonical-web-and-design-pr-7575.run.demo.haus/#download) is present and links to multipass.run
=> Added multipass to download menu

webapp/views.py
Fix GeoIp issue when IP behind proxy/content-cache to dispatch users on the ubuntu image mirror list
- Using: `X-Real-IP` with a fallback on remote addr
- This X-Real-IP is provided by nginx
- Find an IP that is in another country and run:
```
curl --request GET \
--url 'http://127.0.0.1:8001/download/desktop/thank-you?version=20.04&architecture=amd64' \
--header 'x-real-ip: {{ THE IP }}'
```
make sure that the mirrors that you get are for your country
=> Use X-Real-Ip as Ip location

webapp/views.py
https://sentry.is.canonical.com/canonical/ubuntu-com/issues/10208/
- Fix issue if ip has no country linked. Redirect to releases.ubuntu.com
- Try to access with the header: x-real-ip set to what is in the sentry error
=> Fix if IP has no linked country

templates/openstack/consulting.html
- Add comma to h1 on /openstack/consulting
- Compare and resolve the comment in the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
Fixes #7570
=> Add comma to h1 on /openstack/consulting

templates/managed/index.html, templates/shared/pricing/_managed-pricing.html
- Add pricing strip and updated a webinar on the /managed page
- Compare to and resolve comments on the [copy doc](https://docs.google.com/document/d/17zJ4vTutqVpn0XzUI784BHdJov8cGW1ttDwIjsvcEzE/edit#heading=h.7gedeuoq6tmt)
Fixes #7563
=> Add pricing and webinar to /managed

templates/tco-calculator/index.html
- Update copy on /tco-calculator with a link in the banner and a button for contact after the caclulator
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit#)
Fixes #7579
=> Update copy on /tco-calculator

templates/engage/index.html, templates/engage/kafka-in-production.md, templates/index.html, templates/takeovers/_kafka-in-production_takeover.html, templates/takeovers/index.html
- Add new Kafka webinar takeover and engage page
- http://0.0.0.0:8001/
- http://0.0.0.0:8001/engage/kafka-in-production
- http://0.0.0.0:8001/engage
- http://0.0.0.0:8001/takeovers
- Compare to the [brief](https://docs.google.com/spreadsheets/d/1yKQdNwBwL_c41SSjekkZu823FEKEuvnIeIvqzEs0hMY/edit) and [design](https://github.com/canonical-web-and-design/web-squad/issues/2775)
Fixes #7557
=> Add new Kafka webinar takeover and engage page

templates/advantage/index.html
- Moved the “Sign out” button inline, next to your address
- View the UA page at http://0.0.0.0:8001/advantage
- Sign in
Partially addresses a couple of comments from the UA workshop:
- [“signout seems very prominent”](https://miro.com/app/board/o9J_ks1W8HE=/?moveToWidget=3074457348194383923&cot=11)
- [“non-standard location for identity, sign-out”](https://miro.com/app/board/o9J_ks1W8HE=/?moveToWidget=3074457348046666018&cot=2)
Before:
After:
=> Moves “Sign out” next to the address

static/sass/_pattern_renewal-modal.scss, webapp/views.py
- If a user is required to perform 3DS authentication on a renewal payment, but leaves the page for whatever reason, show the "Renew" button, rather than a "Renewal is processing..." message with a disabled button.
- If you don't have any subscriptions, ask Scott to set you up with one
- Proceed through the renewal process by clicking "Renew...", then filling out the details using 4000000000003220 as the card number
- expiry date can be anything in the future
- Click "Save payment details", and on the next modal screen click "Pay"
- A 3DS modal should appear, when it does, reload the page
- When the page …
=> Mark renewals as renewable if a user reloads the page during 3DS auth

static/js/src/renewal-modal.js, static/js/src/renewals/contracts-api.js, webapp/advantage.py, webapp/app.py, webapp/views.py
- Pass name value to the ua contracts service when posting to customer info endpoint
- If you don't have any subscriptions, ask Scott to set you up with one
- Proceed through the renewal process by clicking "Renew...", then filling out the details using 4242 4242 4242 4242 as the card number
- expiry date can be anything in the future
- Open the network tab in your browser's dev tools
- Click "Save payment details", and see that a post request to "customer-info" occurs
- Check the params of …
=> Set name when passing customer info to UA contracts service

static/js/src/renewal-modal.js, templates/advantage/_stripe-modal.html
- Updated copy in the modal to reflect reality: we aren't storing payment method details.
- Login in with SSO
- If you don't have test contracts, ask Scott to set you up with one
- Trigger the renewals modal by clicking "Renew..." in the relevant subscription
- Using 4242 4242 4242 4242 as the card number, and any future expiry date, fill out the form
- See that the green CTA reads "Continue"
- Click it, and see that the copy that appears in the bottom left reads "Checking details..."
Fixes #7602
=> Remove copy implying we're storing renewals payment method details

templates/templates/navigation-community-h.html
- Added Ubuntu masters to "Learn" of Community menu.
- Check the demo [against the copy doc ](https://docs.google.com/document/d/1TgsBJdGgsP4KrGiz5kU5QYkdGSlKqhAVnZGnCJgshYY/edit#)and accepts correct changes.
Fixes #7607
=> Added Ubuntu masters to "Learn" of Community menu

static/js/src/renewal-modal.js, templates/advantage/_stripe-modal.html
- added a t&c checkbox the user needs to check before payment can be processed
- set equal widths on buttons in the modal footer
- Login with SSO
- If you don't have any subscriptions, ask Scott to set you up with one
- On the subscription, click "Renew...", fill out the payment method details and click "Continue"
- See that the "Pay" button is disabled
- Click the t&c checkbox
Fixes #7612
=> renewals: add terms checkbox before user can complete payment

templates/advantage/_stripe-modal.html
Added "excluding VAT" to total amount in renewal modal
- Login with SSO
- If you don't have any subscriptions, ask Scott to set you up with one
- On the subscription, click "Renew...", see that below the total to pay there is a small piece of text that reads "Excluding VAT"
Fixes #7619
=> renewals: add "excluding VAT" note

package.json, templates/templates/base.html, yarn.lock
Update the cookie policy to version 2.1.0
- Clear your cookies and refresh
- Check the cookie-policy look the same as you would expect
- Open the inspector hit Network tab and filter for fonts
- Hard refresh the page and see there are only 4 ubuntu subset fonts downloaded
- Check live loads 5 ubuntu fonts, one called: `e8c07df6-Ubuntu-L_W.woff2`
=> Update the cookie policy to version 2.1.0

templates/aws/pro.html
- Remove 'Q1' from text
- See that 'Q1' has been removed as in the [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#)
Fixes #7625
=> Update copy on /aws/pro

templates/managed/kafka.html
- SEO updates to /managed/kafka
- Add webinar
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/kafka
- Compare to the [copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#) and resolve comments
Fixes #2782
=> SEO updates to /managed/kafka

templates/engage/index.html, templates/engage/ml-dell-webinar.md, templates/index.html, templates/takeovers/_202006-ml-dell-webinar.html, templates/takeovers/index.html
- Add dell webinar takeover and engage page
- http://0.0.0.0:8001/
- http://0.0.0.0:8001/takeover
- http://0.0.0.0:8001/engage/ml-dell-webinar
- http://0.0.0.0:8001/engage
- Compare to the [design issue](https://github.com/canonical-web-and-design/web-squad/issues/2773) and the [brief](https://docs.google.com/spreadsheets/d/14ijDOFOsUSTfOW7ZiuU92eyezZehEPHDyZfLATuDuu4/edit?ts=5ebe8a0e#gid=2113339190)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7556
=> Add dell webinar takeover and engage page

redirects.yaml
This [this sentry error](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/8009/).
QA
--
In the demo, or locally, go to `/templates/_navigation-download-h.html`, see it redirects to the proper place.
=> Redirect those underscore urls

static/sass/styles.scss, templates/advantage/index.html, webapp/views.py
- Added a list of contact numbers for cases where a renewal is present but not actionable
- Ask Scott to set you up with test data
- Find the subscription, expand the row and see that you are presented with a notification and a list of contact numbers
Fixes #7605
=> Show contact numbers if renewal is not actionable

webapp/app.py
Instead of the CachedSession from canonicalwebteam.http.
This is because we're getting timeout errors in Sentry,
because the CachedSession has a timeout of (.5, 3) by default.
We should no longer explicitly time out API calls, as
the combination of the content-cache in front of our sites
and the fact that we use gsync gevent workers in production
should mean that there's no problem with request waiting for
the API calls to complete.
Also, using a Talisker session allows us to get more information
about these API requests in Graylog.
This should fix Sentry errors like this one: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/9582/
In the demo, or running locally, go to `/tutorials` and `/server/docs` and check they both still work fine.
=> Use Talisker session for docs calls

Dockerfile
Add babelrc to the docker build
- Check the code looks right
- Run `docker build --build-arg TALISKER_REVISION_ID=test --tag ubuntu.com .`
- Run `docker run -ti -p "8006:80" --env SECRET_KEY=secret_key --env DATABASE_URL=sqlite:///usn.sqlite3 ubuntu.com`
- Go to http://localhost:8006/static/js/build/renewal-modal.min.js?v=4d60482
- Check that `regeneratorRuntime` appears twice
=> Add babelrc to the docker build

appliances.yaml, templates/appliance/shared/_install_instructions_raspberry-pi.html, templates/appliance/shared/_raspberry-pi.html, templates/appliance/shared/_steps_pi_boot-raspberry-pi.html, templates/appliance/shared/_steps_ssh-keys_ubuntu.html, templates/appliance/shared/_steps_ssh-keys_windows.html, templates/appliance/shared/_steps_sso.html
- Update raspberry pi install instructions
**I turned off automatic downloads for the review**
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex/raspberry-pi
- Compare to the [copy doc](https://docs.google.com/document/d/1H_4L-kqKx6HJ0_3krpzdDVZ24pdVm5jb0evLMT6mcuo/edit) and resolve comments
=> Update raspberry pi install instructions

templates/engage/azure-cloud-init-whitepaper.md, templates/engage/index.html
- Add new engage page /engage/azure-cloud-init-whitepaper
- Added that to the /engage index
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/azure-cloud-init-whitepaper and http://0.0.0.0:8001/engage
- Compare to the [brief](https://docs.google.com/spreadsheets/d/1bKzg4oiVxvRqSMHVzuHxjQwgJJoFUZPNPN2CNdksMno/edit#gid=0) and resolve comments
Fixes #7564
=> Add new engage page /engage/azure-cloud-init-whitepaper

templates/shared/forms/interactive/bootstack.html, templates/shared/forms/interactive/openstack.html
- Added a phone field to OpenStack modal forms
- Ensure the Phone form field is in
- https://ubuntu-com-canonical-web-and-design-pr-7652.run.demo.haus/openstack#get-in-touch
- https://ubuntu-com-canonical-web-and-design-pr-7652.run.demo.haus/openstack/managed#get-in-touch
- Submit a form on each, once you've tested, ping davidcalle on IRC to verify outcome
=> Add phone field to OpenStack modal forms

templates/appliance/shared/_base_appliance_index.html
- Update design of appliance index pages based on the latest copy
- Left in the bottom 'Build your own appliance' strip for now
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex
- Compare to the [copy doc](https://docs.google.com/document/d/14sEgchP6BUjnUtJt67XJ-fKl7k8dAevaf5EJac9Pmyc/edit#)
=> Update design of appliance index pages

appliances.yaml, templates/appliance/nextcloud/_next-steps.html, templates/appliance/nextcloud/index.md, templates/appliance/nextcloud/intel-nuc.html, templates/appliance/nextcloud/pc.html, templates/appliance/nextcloud/raspberry-pi.html
- Initial addition of the /appliance/nextcloud page as well as install pages
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/nextcloud and the download pages
- At the bottom of the install instructions see the text is from [this doc](https://docs.google.com/document/d/12m4WT3ZvlfAuBQ6tT-0ARAQeYGFMaSWhBEzs-9l3ww8/edit)
- For the main page, see the data is from [this doc](https://docs.google.com/document/d/1APNIgG9i07O7ZHwgoppi8PQhp1Wbw3PKwP5zA95fZ5I/edit#heading=h.h48ugxmkjc4v)
=> Initial addition of the /appliance/nextcloud page

navigation.yaml, static/sass/styles.scss, templates/kubernetes/what-is-kubernetes.html
- Build new /kubernetes/what-is-kubernetes page
- Added it to the navigation
- **NOTE** - needs update of top diagram
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/what-is-kubernetes page
- Compare to the [design](#7551) and the [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#)
Fixes #7552
=> Build new /kubernetes/what-is-kubernetes page

templates/appliance/index.html
- Update /appliance overview text and layout
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance
- Updated based on the revised [copy doc](https://docs.google.com/document/d/1Fcr5b5Rn06AB89D6DGPmoIgXLxLalijMhwnu_IyUxV4/edit#heading=h.oq1bqfd7kna3)
=> Update /appliance overview text and layout

appliances.yaml, templates/appliance/shared/_intel-nuc.html, templates/appliance/shared/_raspberry-pi.html, templates/appliance/shared/_steps-multipass-launch.html, templates/appliance/shared/_steps_multipass_macos.html, templates/appliance/shared/_steps_multipass_ubuntu.html, templates/appliance/shared/_steps_vm_thats-it.html
- Added ports and alias (for the appliance name) in the yaml
- Used these in the install pages
- Updated links to the downloads and checksums
- Stopped autodownloading for now.
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex/vm
- See that the download pages look ok.
=> Add port and appliance alias

templates/index.html
Added  {% include "takeovers/fr/_french_vmware-to-os.html" %}
- Added the French VM to OS to FR takeovers
- Added  {% include "takeovers/fr/_french_vmware-to-os.html" %}
- Change browser language to FR and make sure takeover appears in rotation.
=> Added the French VM to OS to FR takeovers

templates/kubeflow/index.html
- Change text per Nvidia from GPGPU to GPU on /kubeflow
- Compare and resolve comments in the [copy doc](https://docs.google.com/document/d/1mJq8PxH8FVRVF9i1Xzh0f6M73eyjqZE4NaKYHRcRAKM/edit#)
Fixes #7676
=> Change GPGPU to GPU on /kubeflow

templates/openstack/what-is-openstack.html
- Make what is openstack page title less redundant:
- "What is Openstack | OpenStack | Ubuntu" -> "What is OpenStack | Ubuntu"
=> Make "what is openstack" page title less redundant

templates/security/certifications.html
- Realigned certification logos to the top of the body text, rather than the center of the section.
- Fixed “cerification” typo.
- View the page locally in your web browser at: http://0.0.0.0:8001/security/certifications
- Observe the improved alignment, especially in the FIPS section
Fixes #7670.
Before:
After:
=> Improves certification logo alignment; fixes typo

templates/engage/fr/index.html, templates/engage/index.html
Added index page for French engage pages (/engage/fr)
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/fr
- Check that there is a page and that it contains the cards for French engage pages
=> Add French engage index page

templates/index.html, templates/takeovers/_ubuntu-masters-takeover-202006.html, templates/takeovers/index.html
- Added takeover for Ubuntu Masters
- Removed takeover for Roblox
- Reload the page until you see the "Join the Ubuntu Masters conference" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1TVm1w1iyosZtUw8iFlaRCeFV1zbbca_rk1caV-0wssU/edit#gid=2113339190)
- Check that the "From bare metal to the edge" takeover has been removed
- Check that the new takeover is at the bottom of /takeovers
Fixes #7684
=> Add Ubuntu Masters takeover

templates/about/packages.html
- Remove cut error and copy updates for /about/packages
- View the site locally in your web browser at: http://0.0.0.0:8001/about/packages
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/12PIhHMZZNzwLYCN1sLb1DSX2BejIy6b9-lhupghzNbY/edit#)
Fixes #7691
=> Remove cut error and copy updates for  /about/packages

templates/download/shared/_server_weekly_news.html, templates/shared/forms/interactive/aws.html, templates/shared/forms/interactive/azure.html, templates/shared/forms/interactive/embedded.html, templates/shared/forms/interactive/general.html, templates/shared/forms/interactive/kubeflow.html, templates/shared/forms/interactive/kubernetes.html, templates/shared/forms/interactive/managed-apps.html, templates/shared/forms/interactive/managed-kafka.html, templates/shared/forms/interactive/masters-conference.html, templates/shared/forms/interactive/partner-dell.html, templates/shared/forms/interactive/pricing-infra.html, templates/shared/forms/interactive/robotics.html, templates/shared/forms/interactive/storage.html, templates/shared/forms/interactive/support-openstack.html, templates/shared/forms/interactive/support.html
- Add a phone field to /download/server/thank-you page
- And all other modal forms
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/thank-you and the other sections #get-in-touch forms 
- See that they all have a required telephone field
=> Add a phone field to /download/server/thank-you page

templates/blog/blog-card.html
After [reading this post](https://www.sarasoueidan.com/blog/keyboard-friendlier-article-listings/) I decided to implement the fix on our blog too.
- Tab to the main content
- Tab through the articles and see they do not focus on the duplicated link on the image
=> Prevent tabbing to images in the blog list

scripts/create-usns.py, templates/security/notice.html, webapp/security/schemas.py, webapp/security/views.py
Update notice packages schema so we accept package links instead of guessing them.
- `dotrun exec alembic upgrade head`
- `wget https://usn.ubuntu.com/usn-db/database.json`
- `snap install jq` if you don't already have it
- `jq '."4363-1" | { (.id): .}' database.json > 4363-1.json`
- dotrun
- dotrun exec ./scripts/create-usns.py 4363-1.json
- Make sure http://localhost:8001/security/notices/4363-1 renders and the packages look similar to https://usn.ubuntu.com/4363-1/
Fixes #7542
=> Update notice package schema to contain package links

templates/appliance/adguard/intel-nuc.html, templates/appliance/mosquitto/intel-nuc.html, templates/appliance/nextcloud/intel-nuc.html, templates/appliance/openhab/intel-nuc.html, templates/appliance/shared/_intel-nuc.html, templates/appliance/shared/_steps_nuc_install_appliance.html, templates/appliance/shared/_steps_nuc_thats-it.html
- Update intel-nuc appliance instructions on /appliance/<appliance>/intel-nuc pages
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/adguard/intel-nuc
- Compare to the text in the [sheet](https://docs.google.com/spreadsheets/d/1eZD3zISXBSNwAwkxlIRtV1UqP8GKPi0YAis8IRLZ9Po/edit#gid=1733381881)
Fixes #7707
=> Update intel-nuc appliance instructions

templates/appliance/shared/_install_instructions_vm_macos.html, templates/appliance/shared/_install_instructions_vm_ubuntu.html, templates/appliance/shared/_install_instructions_vm_windows.html, templates/appliance/shared/_steps-multipass-find-ip-macos.html, templates/appliance/shared/_steps-multipass-find-ip-ubuntu.html, templates/appliance/shared/_steps-multipass-find-ip-windows.html, templates/appliance/shared/_steps-multipass-launch.html, templates/appliance/shared/_steps_multipass_macos.html, templates/appliance/shared/_steps_multipass_ubuntu.html, templates/appliance/shared/_steps_multipass_windows.html, templates/appliance/shared/_steps_vm_thats-it.html, templates/appliance/shared/_vm.html
- Update vm appliance instructions on /appliance/<appliance>/vm pages
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/adguard/vm
- Compare to the text in the [sheet](https://docs.google.com/spreadsheets/d/1eZD3zISXBSNwAwkxlIRtV1UqP8GKPi0YAis8IRLZ9Po/edit#gid=1733381881)
Fixes #7706
=> Update /appliance/<appliance>/vm instructions

templates/blog/article.html, templates/blog/product-cards.html
- Added a custom Managed OpenStack notice on all blog posts tagged "BootStack"
- Ensure the notice is present at the top of blog posts tagged with "BootStack", eg.
- [/blog/the-enterprise-deployment-game-plan-why-multi-cloud-is-the-future](https://ubuntu-com-canonical-web-and-design-pr-7720.run.demo.haus/blog/the-enterprise-deployment-game-plan-why-multi-cloud-is-the-future)
- [/blog/a-unified-openstack-for-a-scalable-open-infrastructure](https://ubuntu-com-canonical-web-and-design-pr-7720.run.demo.haus/blog/a-unified- …
=> Add Managed OpenStack notice on BootStack blog posts

templates/download/desktop/thank-you.html, templates/download/server/thank-you.html
Fix path to image downloader script
- Click download and see that it works as expected
Fixes #7726
=> Fix path to image download script

static/js/src/chart-data.js, static/sass/_pattern_chart.scss, templates/about/release-cycle.html
Updated the OpenStack release cycle chart to match the spreadsheet
- Check that the OpenStack release cycle chart data matches [the google sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1483484944)
- Check that the table in small screen view is also up to date
Fixes #7654
=> 7654 update openstack release table

templates/engage/index.html, templates/engage/migrating-to-20.04.md, templates/index.html, templates/takeovers/_2004-migration-takeover.html, templates/takeovers/index.html
- Add 20.04 migration webinar takeover
- Add 20.04 migration engage page
- Reload the page until you see the "Migrating your infrastructure to Ubuntu 20.04 LTS" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1Ko-fZ4njx6NRB6OIJS00-ujOULr-sg-CtN11xoUm2P0/edit#gid=2113339190)
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1Ko-fZ4njx6NRB6OIJS00-ujOULr-sg-CtN11xoUm2P0/edit#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/1-K3MlEPYdA1ChVs81pjqnQ4UpU_al2fOHToXqhZLgys/edit)
Fixes #7704
=> Focal migration webinar and engage page

webapp/advantage.py
Spotted in a call with Francesco & Will - currently if a macroon needs to be refreshed and is causing an authentication issue, the 401 response we get from ua-contracts is being swallowed, and the user will see the logged in view, but only the "Your free subscription" section, without a machine ID. Any enterprise subscriptions they have won't be visible.
This PR raises adds `raise_for_status` on the accounts API call, so we can prompt the user to login again.
- Check out `master` branch
- Edit line 355 of webapp/views.py, from `flask.session["authentication_token"]` to an empty string (`""`), to simulate an invalid auth
- See that the logged in view is …
=> raise 401 statuses when getting accounts from ua-contracts service

templates/robotics/index.html
- Corrects “setup” (noun) to “set up” (verb)
- Capitalises company names in alt= text, and corrects a copy-paste error
None
[Misspelling noticed in screenshot on [vanilla-framework#1917](https://github.com/canonical-web-and-design/vanilla-framework/issues/1917).]
=> “setup” > “set up”; fixes alt= text

templates/about/release-cycle.html
- Update /about/release-cycle security status block to offer different commands based on which version of Ubuntu you might be running.
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle 
- Compare to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
Fixes #7663
=> Update /about/release-cycle security status block

navigation.yaml, templates/appliance/index.html, templates/appliance/portfolio.html, templates/appliance/shared/_base_appliance_index.html, templates/appliance/shared/_featured_appliances.html, templates/appliance/shared/_join_the_community.html
- Update /appliance homepage text and design
- Add /appliances/portfolio page
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance and http://0.0.0.0:8001/appliance/portfolio
- Copy docs for [overview](https://docs.google.com/document/d/1Fcr5b5Rn06AB89D6DGPmoIgXLxLalijMhwnu_IyUxV4/edit#heading=h.oq1bqfd7kna3) and [portfolio](https://docs.google.com/document/d/1DABafCPzl9WwOmHX8ejkkiUEKXI2fTlF7UXNB0Xhlo0/edit#heading=h.tf6nbxjryj9q) pages
Fixes #7709
=> Update /appliance homepage text and design and add /appliances/portfolio page

templates/takeovers/takeunders/_openstack-ebook.html
Updated link on OpenStack card on the homepage
- Click the "OpenStack costs increasing?" link in the red card towards the bottom of the page
- Check that you are taken to http://0.0.0.0:8001/engage/private-cloud-cost-analysis-webinar
Fixes https://github.com/canonical-web-and-design/master-epics/issues/162
=> Update link on OpenStack card on homepage

templates/security/cve/index.html
Removed icons for DNE and not-affected statuses in the CVE table
- Run DB:
```
docker-compose up
```
```
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres exec alembic upgrade head
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres exec python3 scripts/create-releases.py
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres serve
```
In yet another terminal:
```
git clone -b load-cve …
```
=> Remove icons from DNE and not-affected CVE status

navigation.yaml
Add apps link to secondary navigation on /openstack and /kubernetes
- Go to /openstack and check that there is an `apps` link in the secondary navigation that takes you to /managed
- Go to /kubernetes and check that there is an `apps` link in the secondary navigation that takes you to /managed
Fixes #7745
=> Add apps link to OpenStack and k8s pages

appliances.yaml, templates/appliance/adguard/_next-steps.html, templates/appliance/mosquitto/_next-steps.html, templates/appliance/nextcloud/_next-steps.html, templates/appliance/openhab/_next-steps.html, templates/appliance/plex/_next-steps.html, templates/appliance/shared/_install_instructions_vm_macos.html, templates/appliance/shared/_intel-nuc.html, templates/appliance/shared/_raspberry-pi.html, templates/appliance/shared/_steps_multipass_macos.html, templates/appliance/shared/_vm.html
- Update ALL of the next steps and multipass instructions
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/<appliance>/vm
- Compare to the copy docs:
- [adguard](https://docs.google.com/document/d/1ZqSQdPuQ3EYhNuzoaeln6tCivLq27Zwaj5sdPNpHOno/edit?ts=5ee76bbd)
- [plex]()
- [openhab](https://docs.google.com/document/d/19BL4l1m7F_jE-GkMGxg19KG1SsZtqzjLAFuyLngSy9Y/edit?ts=5ee76bcd)
- [nextcloud](https://docs.google.com/document/d/12m4WT3ZvlfAuBQ6tT-0ARAQeYGFMaSWhBEzs-9l3ww8/edit?ts=5ee76bd8)
- [mosquitto](https://docs.google.com/document/d/1nkWQ7c9uV7MAic8jbb5Ao …
=> Update next steps and multipass instructions

templates/security/cve/index.html
Removed the release name and the Ubuntu string from CVE table header
- Check that the table headers only have the Ubuntu versions and support tag, e.g. 18.04 LTS, 18.10 etc.
Fixes #7749
=> Remove Ubuntu string and release name from CVE table

templates/appliance/shared/_appliance-advert-strip.html, templates/appliance/shared/_featured_appliances.html, templates/download/flavours.html, templates/download/iot/index.html, templates/download/raspberry-pi/index.html, templates/download/server/index.html, templates/pricing/devices.html, templates/pricing/shared/_enablement-strip.html, templates/templates/navigation-download-h.html
- Add strips to promote /appliances around site
- Added to the download mega menu
- Added some text from /pricing/devices to /download/iot
- http://0.0.0.0:8001/download/flavours
- http://0.0.0.0:8001/download/iot
- https://0.0.0.0:8001/#download
- Compare to the copy docs:
- [/download/server](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit?ts=5ee7d8c0#)
- [/download/flavours](https://docs.google.com/document/d/1M5nkigcS …
=>  Add strips to promote /appliances around site

navigation.yaml, static/js/src/tabotronic.js, templates/appliance/_base-appliance.html, templates/appliance/about.html, templates/appliance/hardware.html, templates/appliance/shared/_intel-nuc.html, templates/appliance/shared/_raspberry-pi.html, templates/appliance/shared/_raspberry-pi2.html, templates/appliance/shared/_vm.html, templates/security/cve/index.html, webpack.config.entry.js
- Fixed the virtual machines menu item
- Muted the free strip on the about page
- Fixed a typo in the `tabotronic.js`
- Added the appliance JS file to build with webpack
- Updated the paths to the JS dist folder 
- View the site locally in your web browser at: http://0.0.0.0:8001/appliances/about
- Check the Free section is much more subtle with no button
- Go to /appliance/openhab/intel-nuc
- Check the instruction tabs work
=> Appliance fix instrctions

templates/appliance/portfolio.html
Fixed typo in a link
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/portfolio
- Find the "see our community page" link, make sure it doesn't lead to a 404
Fixes #7768
=> fix appliance link typo

templates/appliance/adguard/index.md, templates/appliance/mosquitto/index.md, templates/appliance/nextcloud/index.md, templates/appliance/openhab/index.md, templates/appliance/plex/index.md, templates/appliance/shared/_base_appliance_index.html
- multipass logo is too small on small screens on /appliance/ pages
- hit area for raspberry pi is too small on /appliance/ pages
- all maintained until dates should be in 2030
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex (for example)
- See that the multipass logo looks ok on small screens
- See that the image of the pi on that page is clickable
- See that the maintenance date is now in 2030
Fixes #7761
Fixes #7774
Fixes #7775
=> Fix post-release /appliance snags

templates/appliance/shared/_vm.html, templates/appliance/vm.html
- Update the multipass version in the link
- Disable the download on vm
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/openhab/vm
- Check the download is not triggered and the title does not state it will be automaticly downloaded
- Go to /appliance/vm
- Check the multipass download links point to 1.3.0
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7777
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7778
=> Update multipass links

webapp/context.py
- This is an attempt at fixing the currently broken [/managed](https://ubuntu.com/managed) nav. When adding /managed to the /kubernetes and /openstack nav, the current nav building logic considers that /managed is part of /kubernetes, therefore shows the /kubernetes nav in the /managed section.
- The logic now looks for a section path match with the current path before building the navigation.
- **This change needs testing for corner cases I'm not necessarily aware of :)**
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7784
- Run through the following [QA …
=> Add section path matching to 2nd nav generation (fixes /managed nav)

templates/security/cve/cve.html
Update the release labels on the CVE page status table
- Run DB:
```
docker-compose up
```
```
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres exec alembic upgrade head
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres exec python3 scripts/create-releases.py
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres serve
```
In yet another terminal:
```
git clone -b load-cve git@github.com:carkod/ubuntu-cve-tracker
pip3 install requests …
```
=> Update CVE release labels on CVE page

templates/security/notice.html, webapp/security/views.py
- Check if a notice has release_packages before trying to build the payload.
- Add checks on the templates so we don't display empty sections. 
- docker-compose up -d
- Update an existing notice(keep ID) and set release_packages to `None` **1***
- Browse the `localhost:8001/security/notices/<id_of_the_notice_you_kept>` and make sure it does not 500
**1*** - I ran `dotrun exec flask shell` and then inside it the following commands
```
from webapp.security.database import db_session
from webapp.security.models import Notice
notice = db_session.query(Notice).get("ID you kept")
notice.release_packages = None
db_session.add(notice)
db_session.commit()
```
=> Check if notice as release packages before iterating

templates/legal/terms-and-policies/contact-us.html
- Add recaptcha to /legal/terms-and-policies/contact-us page
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies/contact-us
- See that google recaptcha has been added per legal team request
Fixes #7762
=> Add recaptcha to /legal/terms-and-policies/contact-us page

templates/appliance/shared/_steps_multipass_macos.html, templates/appliance/shared/_steps_multipass_windows.html, templates/appliance/vm.html
- Update links to multipass downloads to the new links so we don't have to update the site when multipass releases new versions
- http://0.0.0.0:8001/appliance/adguard/vm#macos
- http://0.0.0.0:8001/appliance/adguard/vm#windows
- http://0.0.0.0:8001/appliance/vm
- See that it goes to a new multpass.run link that redirects to the latest release
=> Update links to multipass downloads to the new links

templates/appliance/community.html, templates/appliance/index.html, templates/appliance/portfolio.html
Find all occurrences of "https://discourse.ubuntu.com/c/appliances" and replace them with "https://discourse.ubuntu.com/c/appliance"
Fixes #7788
=> Fix the appliance link

templates/index.html
- Removed the AI Dell webinar form takeover rotation
Fixes #
=> Removed the AI Dell webinar form takeover rotation

templates/security/notice.html
Remove the `CVE-` prefix from links to CVE pages.
- docker-compose up -d
- Go to http://0.0.0.0:8001/security/notices and then select one of the notices and make sure cve links look good
=> Remove 'CVE-' prefix from CVE links in notice page

scripts/delete-usns.py, webapp/app.py, webapp/security/views.py
Adds an endpoint to delete security notices.
-  Run the site using the command `./run serve` or `dotrun`
- Browse http://0.0.0.0:8001/security/notices and pick a notice.
- `dotrun exec ./scripts/delete-usns.py <ID>`
- Go back to `/security/notices` and make sure the notice was deleted.
https://github.com/canonical-web-and-design/web-squad/issues/2910
=> Add an endpoint to delete security notices

static/sass/styles.scss, templates/advantage/index.html
- added commands for attaching free subscription to a dropdown/tooltip
- See that "Your free subscription" has a CTA that opens a dropdown/tooltip with instructions on attaching machines.
Fixes #6086
=> hide free subscription instructions in dropdown

scripts/create-usns.py, webapp/security/schemas.py
Validate that notice ID's match `r"USN-\d{4}-\d{1,2}"`.
Also update the `create-usns.py` script to post `USN-` prefixed ID's.
- docker-compose up -d
- `dotrun` or `./run`
- `dotrun exec ./scripts/create-usns.py database.json` let it create a couple notices and `CTRL-C`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/notices and see notices are prefixed.
=> Validate notice ID matches expected pattern

static/sass/_pattern_navigation.scss, templates/templates/_navigation.html
- Fix "Public cloud" from wrapping in the secondary nav
- See that the word doesn't wrap like on live.
Fixes #7796
=> Fix "Public cloud" from wrapping in the secondary nav

templates/security/cve/index.html
- Hide CVE table if no search results
- Fix total results count on last page of results
- Search with part of a CVE ID e.g. `CVE-2020`
- Check that the results count matches the displayed results e.g 1 - 3 or 3 results rather than 1 - 20 or 3 results
Fixes #7785
=> Fix cve search

templates/security/notices.html
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7808
- Check the links now point to the URL's specified on the issue.
=> Add missing links to security notices index page

templates/security/notice.html, webapp/security/views.py
Remove duplicate package descriptions from the `Packages` section in notice detail page.
- `wget https://people.canonical.com/~ubuntu-security/usn/database.json`
- `jq '."4401-1" | { (.id): .}' database.json > /tmp/4401-1.json`
- `dotrun exec ./scripts/create-releases.py`
- `dotrun exec ./scripts/create-usns.py /tmp/4401-1.json`
- See the duplicates in https://ubuntu.com/security/notices/USN-4401-1
- View the site locally in your web browser at: http://0.0.0.0:8001/security/notices/USN-4401-1 and make sure it displays no duplicates.
=> Avoid displaying duplicate package descriptions

templates/download/iot/_setup-ubuntu-sso.html
"Setup" is a noun, "set up" is a verb
=> "Set up" not "Setup"

webapp/app.py, webapp/views.py
Adds the endpoint to post advantage subscriptions.
For now it's just a dummy endpoint to speed up frontend work.
- curl -X POST --header "Content-Type: application/json"   --data '{"customer_id":"xyz","products":"xyz"}' `http://0.0.0.0:8001/advantage/subscribe`
Fixes #
=> Add endpoint to post advantage subscriptions

templates/engage/index.html, templates/engage/kubernetes-event-us.md, templates/index.html, templates/takeovers/_us-kubernetes-event.html, templates/takeovers/index.html
Add takeover and engage page for US k8s event
- Reload the page until you see the "Kubernetes From Cloud to Edge" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/18vsAl7oYtIJSSPuuMJUXipgUn9ZjveWt7F9B5rGS87o/edit#gid=2113339190)
- Click through to the engage page and check that it matches [the brief](https://docs.google.com/spreadsheets/d/18vsAl7oYtIJSSPuuMJUXipgUn9ZjveWt7F9B5rGS87o/edit#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/1LClShZkNAZYCHhXah452SEFYdwetyPstodwRL0Y9ZV8/edit)
Fixes #7818
=> Add kubernetes event takeover and engage page

static/js/src/navigation.js
- Only get UTMs from localstorage when they are present
- This allows a fallback on URL params as opposed to an empty value when localstorage is not available (eg. some mobile webviews don't enable it, causing a lack of form/campaign attribution)
- Go to /engage/vmware-to-charmed-openstack?utm_source=foobar
- Ensure your local storage contains that value
- Empty and disable localstorage for that domain in your browser
- Go back to the page, ensure the form source contains the `utm_source` field with the expected value
=> Only get UTMs from localstorage when they are present

scripts/create-usns.py, webapp/security/views.py
Adds `release_codenames` to `NoticeSchema` context on the update endpoint.
- `jq '."4147-1" | { (.id): .}' database.json > 4147-1.json`
- `dotrun exec ./scripts/create-usns.py 4147-1.json` should return a `200`
- Browse http://localhost:8001/securtity/notices/USN-4147-1
- Change the `title` value in `4147-1.json`
- `dotrun exec ./scripts/create-usns.py --update 4147-1.json` should return a `200`
- Browse http://localhost:8001/security/notices/USN-4147-1 and see the updated title.
=> Fix the endpoint to update notices

static/sass/_pattern_cve.scss, templates/security/cve/cve.html, templates/security/cve/index.html
Updated the visual design of the CVE tables to make them easier to understand
- Check that the table matches the screenshots
- Click through to a CVE and check that the table matches the screenshots
More context on the design: https://github.com/canonical-web-and-design/web-squad/issues/2913#issuecomment-648907977
Fixes #7825
=> Update colors on CVE tables

templates/advantage/index.html
Move FIPS and CC-EAL2 and CIS under under a Certifications column
- Make sure there is a `Certifications` column on the contracts table and that when you expand it the content matches the [specification document](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/), including that we are linking to the right place
Fixes #6154
Fixes #6710
=> Move FIPS and CC-EAL2 and CIS under under a Certifications column

templates/templates/navigation-enterprise-h.html
- Fix url for jaas.ai on enterprise mega menu
- See that the link to 'Multi cloud operations with Juju' now goes to https://jaas.ai not https://jaas.ai.com
=> Fix url for jaas.ai on enterprise mega menu

.env, static/js/src/renewals/error-handler.js, static/js/src/renewals/tests/error-handler.test.js, static/js/src/renewals/tests/fixtures/error-responses.js, templates/advantage/_stripe-modal.html, webapp/advantage.py
Display a useful error to the user if they've submitted an invalid VAT number during a renewal purchase.
- Login with SSO
- If you don't have any contracts with renewals, ask Scott to set you up with one
- Open the row of the expiring contract, and click "Renew"
- Fill out the payment method form, using the following card details:
- card number: 4000008260000000
- expiry: 4/24
- CVC: 123
- postcode: SE1 0HS
- Select United Kingdom from the country dropdown
- Fill out the revealed VAT with an invalid number …
=> Handle VAT validation error

templates/advantage/index.html
- moved sign out button on /advantage to its own row
- See the "Sign out" button is no longer in line with the "you are signed in as XYZ" text
- Resize the window, see that there is space between the button and the line above
Fixes #7831
Old:
New:
=> move /advantage signout button to its own row

templates/engage/at&t-azure-webinar.html, templates/engage/index.html
Add the private AT&T Ubuntu Pro webinar
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/at&t-azure-webinar
- Check the content matches the [copy doc](https://docs.google.com/document/d/1-JgNxLM2BU2EK64NYqtocC6qdERD1QtDvB73dUh8HaA/edit)
- Check that the meta data is correct [from the doc](https://docs.google.com/spreadsheets/d/1vbSP1Lw2OX4BEzLHYS88TMT4XMZe9O5EiBYt00JEwhw/edit#gid=1271849439)
- Check it matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/2924)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7817
=> Add the AT&T Ubuntu Pro webinar

templates/kubeflow/install.html, templates/kubeflow/shared/_learn-more.html
- Copy updates and link updated on the /kubeflow/install page
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit#)
Fixes #7866
=> Copy and link updated to /kubeflow/install page

templates/appliance/shared/_intel-nuc.html, templates/appliance/shared/_raspberry-pi.html, templates/appliance/shared/_steps_install_openssh_windows.html, templates/appliance/shared/_steps_ssh-keys_windows.html, templates/appliance/shared/_steps_sso_windows.html
- Added step 'Install OpenSSH' and fixed up the Windows ssh steps
- Added fixed the ssh windows command
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex/raspberry-pi2 and http://0.0.0.0:8001/appliance/plex/intel-nuc
- See that it matches the windows sections of Pi and PC on the [google sheet](https://docs.google.com/spreadsheets/d/1eZD3zISXBSNwAwkxlIRtV1UqP8GKPi0YAis8IRLZ9Po/edit?ts=5ee0fad1#gid=1141575055)
Fixes #7864
=> Fixup Windows appliance instructions

webapp/app.py
- Allow mega menu pages to be pulled from all sites via javascript
- Update this pastebin file locally to pull from wherever you run the demo - https://pastebin.canonical.com/p/8jP7XjKSXH/
- See that the mega menu works
=> Open cors to all sites for mega menu

templates/kubernetes/docs/operations.md, templates/kubernetes/docs/quickstart.md, templates/kubernetes/docs/troubleshooting.md
Removed an unused link and some stale text from examples relating to conjureup
Fixes #7886
=> K8sdocs Remove stale conjure-up refs

templates/templates/navigation-enterprise-h.html
- Update #enterprise menu
- add 'Government' to sectors
- remove redundant 'Support' row
- Add 'Openstack' to features
- Add 'What is kubernetes'
- See that it matches and resolve comments in the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit)
Fixes #7890
=> Update #enterprise menu

navigation.yaml, templates/legal/motd.html, templates/legal/terms-and-policies/index.html
- Added /legal/motd page
- Added card linking to /legal/motd to /legal/terms-and-policies
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies
- Check that there is a card towards the bottom for "MOTD information"
- Click through to the MOTD page and check that it matches [the copy doc](https://docs.google.com/document/d/1pe_72kC7bClPqlgHU6maSMHYhAAuQdfCcNvAo-lDYVg/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2943 and https://github.com/canonical-web-and-design/web-squad/issues/2942
=> Add motd legal page

templates/legal/websites.html, templates/templates/navigation-developer-h.html
- We are retiring conjure-up.io, this is part of that work
- Also updated /legal/websites to be more current
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/websites
- Compare the list to the [sheet](https://docs.google.com/spreadsheets/d/19V5BOEkR_OkKu0P8UFNk-e9DaYSrC18TaznlXheSFjY/edit#gid=0)
Fixes #7885
=> Remove conjure-up.io from nav and update list of /legal/websites

package.json, static/sass/_global-settings.scss, yarn.lock
- Update to Vanilla framework v2.14.0
- Change the font-display to fallback (issue raised to amend the default https://github.com/canonical-web-and-design/vanilla-framework/issues/3157) 
- Hard refresh and see the font load into place
- If you throttle your browser you should not see the font swap
=> Update to Vanilla framework v2.14.0

templates/openstack/what-is-openstack.html
- Add webinar to /openstack/what-is-openstack
- Compare to and resolve the comment in the [copy doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#)
Fixes #7899
=> Add webinar to /openstack/what-is-openstack

templates/server/index.html
- Add webinar to /server
- Fixed spelling mistake
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#)
Fixes #7895
=> Add webinar to /server

templates/kernel/index.html
- Add webinar to /kernel page
- Compare to and resolve the comments in the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit)
Fixes #7893
=> Add webinar to /kernel page

templates/openstack/features.html
- Add webinar to /openstack/features
- Compare to and resolve comments in [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Fixes #7897
=> Add webinar to /openstack/features

templates/engage/index.html, templates/engage/smart-start-whitepaper.md
Add the smart start whitepaper engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/smart-start-whitepaper
- Check the content matches [the copy doc](https://docs.google.com/document/d/1XSGcMXhCT7FbGtLhlOLTDZBFTqz_dhW8ber72pmbpUM/edit)
- Check it matches [design](https://github.com/canonical-web-and-design/web-squad/issues/2918)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7812
=> Add the smart start whitepaper engage page

templates/masters-conference/index.html
- Add a space to /masters-conference
- View the site locally in your web browser at: http://0.0.0.0:8001//masters-conference
- See that there is a space s/The open (source)road to smarter robots/The open (source) road to smarter robots/
=> Add a space to /masters-conference

templates/appliance/shared/_install_instructions_intel-nuc.html, templates/download/intel-nuc-desktop.html, templates/download/intel-nuc.html
- Updated link to update Intel NUC bios
`s/http://www.intel.com/content/www/us/en/support/boards-and-kits/000005850.html/https://www.intel.com/content/www/us/en/support/articles/000033300/intel-nuc.html/`
- View the site locally in your web browser at: http://0.0.0.0:8001/download/intel-nuc-desktop. http://0.0.0.0:8001/download/intel-nuc.html and all the appliance nuc pages 
- See that the link works and is on the above pages
Fixes #7876
=> Update nuc bios update link

templates/appliance/index.html
- Reduce the vertical space at the top of the appliance page
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance
- See that the space has been reduced in the hero strip
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7904
=> Reduce the vertical space at the top of the appliance page

templates/azure/pro.html
- Revert /azure/pro to promote 18.04 first
- Updated per the [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#heading=h.lobrtzkut7aw)
Fixes #7912
=> Revert /azure/pro to promote 18.04 first

templates/engage/index.html, templates/engage/intro-to-anbox-cloud-whitepaper.md
Anbox whitepaper engage page
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/intro-to-anbox-cloud-whitepaper
- Check the page matched [the design](https://github.com/canonical-web-and-design/ubuntu.com/issues/2921)
- Check it matches [the copy doc](https://docs.google.com/spreadsheets/d/1DgSWaHKFsQRfdUiqWTCxvMIFlb3VozF3QPEOS-Zw_cE/edit#gid=738287198)
- Check the form submits and goes to the anbox thank you page which you can download the whitepaper from.
**No takeover or addition to the engage list required**
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7813
=> Anbox whitepaper engage page

package.json, static/js/src/polyfills.js, templates/templates/base.html, webpack.config.entry.js, yarn.lock
- replaced polyfills being pulled from polyfill.io (`URL`, `URLSearchParams`, `forEach` and `closest`) with our own where possible, and with build packages where it was less practical.
- Visit https://www.browserstack.com and launch IE11
- Visit https://ubuntu-com-canonical-web-and-design-pr-7915.run.demo.haus//tutorials/how-to-sdcard-ubuntu-server-raspberry-pi
- View the console, see that are no JS errors, and click through the navigation links on the tutorial, see that the page behaves as expected.
=> remove inline polyfill script

templates/blog/product-cards.html
- Adds a "What is Kubernetes" info card to blog posts tagged with "kubernetes"
- Drive-by img alt param fixing
- Ensure blog posts linked from [/blog/tag/kubernetes](https://ubuntu-com-canonical-web-and-design-pr-7918.run.demo.haus/blog/tag/kubernetes) show a "What is Kubernetes?" card on the right col.
=> Adds "What is Kubernetes" blog card

navigation.yaml, templates/kubernetes/docs/security.md, templates/kubernetes/docs/shared/_side-navigation.md
Adds a single page on Security to K8s docs
=> Add security page for K8s docs

templates/legal/motd.html
- Update motd.canonical.com to motd.ubuntu.com
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/motd
- See that the link now works
=> Update link on /lega/motd

deploy/site.yaml
Update ubuntu.com deploy settings to add Nginx rules to proxy requests for `ubuntu.com/wp-content/*` through to `admin.insights.ubuntu.com/wp-content/*`
Short story if you have `microk8s` configured to run `ubuntu.com`:
- git checkout this branch
- run `./qa-deploy production <path/to/ubuntu.com/repo>/deploy/site.ymal`
- `sudo vi /etc/hosts` and add `127.0.1.1	staging.ubuntu.com` and `127.0.1.1	ubuntu.com`
- run `curl -I --insecure https://ubuntu.com/wp-content/uploads/2e4c/dell-xps-2004.jpg` should return 200
- run `curl -I --insecure https://staging.ubuntu.com/wp-content/uploads/2e4c/dell-xps-2004.jpg` should return 200
- try the links in the browser too to confirm again that everything works: `https://ubuntu.com/wp-content/uploads/2e4c/dell-xps-2004.jpg` and …
=> Add new nginx proxy

static/js/src/chart-data.js
- Made ESM be autbergine and Extended support for customers green to match what other charts do
- See that ESM is aubergine on the page and that Extended support for customers is green
Fixes #7877
=> Change colours on OpenStack chart to match others

templates/security/notice.html
Reduced scrolling required on USN pages by:
- Making the spacing between the summary and the Releases section consistent with the other sections.
- Increasing the title + summary section width from `col-8` to `col-12`, consistent with (most) other sections.
- Visit any individual notice page
none
Before | After
-|-
=> Reduces whitespace around USN title + summary

templates/templates/footer.html
Changed the LinkedIn link in the footer
- Check that the LinkedIn icon in the footer goes to the Canonical company page
Fixes #7937
=> Update linkedin link in footer

templates/public-cloud/index.html
- On /public-cloud, the Get in touch CTA is currently linking to the wrong contact form. Since we don't have a public-cloud specific one, this fallbacks to the generic form.
- Ensure the /public-cloud "Get in touch" CTA keeps you on the page and shows a generic modal contact form as opposed to an OpenStack one.
=> Link /public-cloud main CTA to the right contact form

templates/appliance/shared/_join_the_community.html
- Fixed text on the appliance pages
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/nextcloud
- See that s/Our Discourse forum for NextCloud is the best place news views/Our Discourse forum for NextCloud is the best place **for** news **and** views/
Fixes #7952
=> Fix copy on discourse appliance cta

templates/index.html
Removed ubuntu masters takeover
Removed ubuntu masters takeover
=> Removed ubuntu masters takeover

static/js/src/chart-data.js, templates/about/release-cycle.html
- Fix OpenStack chart key text
- See that the dark aubergine now says 'Extended Security Maintenance (ESM)'
=> Fix OpenStack chart key text

static/js/src/cve/cve.js, templates/security/cve/index.html, webapp/security/views.py
Add component search field
- Check that the search form has a field for "Component" and that the options match [the UX spec](https://docs.google.com/document/d/1VuAElUpFay7MBFNmE3NhSyY9TkXiqHcA1ZHQ11AYO-Q/edit#heading=h.aoek8nxke7k9)
- Check that submitting the form puts a `component=` query parameter in the URL (this won't have any effect on the results until https://github.com/canonical-web-and-design/ubuntu.com/issues/7926 is done)
Fixes #7927
=> Add CVE component search field

templates/advantage/index.html, webapp/views.py
- UA contracts can be renewed for short window after they've expired, so if an expired contract has a valid renewal, show it on the page along with the renew button, and highlight the fact that it has expired
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage or look at the nice GIF
Fixes #7971
=> if a contract has expired, but has a renewal, allow users to renew

templates/ceph/document.html
- Restore discourse docs "edit" link and update date
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph/docs
- Check that above mentioned things appear
=> Restore discourse docs "edit" link and update date

static/js/src/cve/cve-search.js, static/js/src/cve/cve.js, templates/security/cve/_cve-table.html, templates/security/cve/_status-fields.html, templates/security/cve/_version-fields.html, templates/security/cve/index.html, webapp/security/views.py
- Move CVE table to partial to make template more legible
- Add CVE search fields for Ubuntu version and status
- Check that there are search fields for Ubuntu version and status
- Check that you are able to add and remove rows
- Submit the form and check that the appropriate fields are still selected
- **Note:** The results won't be affected until the backend is completed in https://github.com/canonical-web-and-design/ubuntu.com/issues/7928
Fixes #7929
=> Add CVE search Ubuntu version and status fields

templates/index.html, templates/takeovers/_intro-to-anbox-cloud-whitepaper.html, templates/takeovers/index.html
- Add Anbox whitepaper takeover
- Compare to the [brief](https://docs.google.com/spreadsheets/d/1DgSWaHKFsQRfdUiqWTCxvMIFlb3VozF3QPEOS-Zw_cE/edit#gid=2113339190)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2990
=> Add Anbox whitepaper takeover

templates/takeovers/index.html
Fix include to takeover which was causing the /templates page to 500
- Check that the page loads
=> Fix broken /takeovers page

templates/security/cve/cve.html
Add bug links to CVE pages
- View the site locally in your web browser at: http://localhost:8001/security/cve-2019-16935
- Run DB:
```
docker-compose up
```
```
dotrun exec python3 scripts/create-releases.py
dotrun
```
In yet another terminal:
```
git clone -b load-cve git@github.com:carkod/ubuntu-cve-tracker
```
You may have to uncomment line 60 in …
=> Add bug links to CVE pages

templates/kubernetes/docs/1.18/components.md
the markdown parser on u.c expects a blank line before the list
Added two blank lines to components doc page
- see that the images list renders as a <ul>
=> Fix rendering for k8s docs container image list

templates/ceph/index.html
- Updated the benefits of Ceph diagram on /ceph
- See that there is a new image shows OpenStack Stein as being associated with Ceph Mimic.
Fixes #7979
=> Updated the benefits of Ceph diagram on /ceph

static/sass/styles.scss, templates/templates/base.html
- Fixed the page jump as the page loads
- Removed an SCSS comment that was causing a linting error
- Load the page and compare the experience to ubuntu.com
- The page should no longer jump when the global nav loads
=> Fix page jump as global nav loads

templates/security/cve/cve.html
Add Debian, NVD and Launchpad links to CVE pages
- View the site locally in your web browser at: http://localhost:8001/security/cve-2019-16935
- Run DB:
```
docker-compose up
```
```
dotrun exec python3 scripts/create-releases.py
dotrun
```
In yet another terminal:
```
git clone -b load-cve git@github.com:carkod/ubuntu-cve-tracker
```
You may have to …
=> Add links to Debian, NVD and Launchpad to CVE page

templates/engage/kubernetes-event-us.md
Update the link in the hero of Kubernetes event
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/kubernetes-event-us
- Click in the "Register now" button at the top and see it jumps to the BrightTalk webinar embed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7995
=> Update the link in the hero of Kubernetes event

templates/engage/_article-card.html, templates/engage/gsi-webinar-series.html, templates/engage/index.html, templates/index.html, templates/takeovers/_gsi-webinar-series-takeover.html, templates/takeovers/index.html
- Add gsi webinar takeover and engage page
- Fix up /engage to not require a group to add the class (it was always a bit odd as it used groups that were unrelated to the engage pages, just borrowing blog classes)
- Shortened a few engage descriptions
- Fixed a few that were the wrong type
- View the site locally in your web browser at: http://0.0.0.0:8001/, http://0.0.0.0:8001/takeovers, http://0.0.0.0:8001/engage/gsi-webinar-series and http://0.0.0.0:8001/engage
- Compare to the [brief](https://docs.google.com/spreadsheets/d/11lbp6jOe_HCdl2vNkqk0_lsV8bWHOjBp6S84xaZVcRg/edit#gid=1595677 …
=> Add gsi webinar takeover and engage page

static/js/src/desktop-statistics.js, static/js/src/imageBuilder.js, static/js/src/release-chart.js, static/js/src/utils/debounce.js
Consolidated the various debounce functions into one module that can be imported into any file.
- Consider adding a `console.log` to the function returned by the debounce util
- Progress through the form and type something into the snap search box, see that it doesn't start searching while you're actively typing.
- Visit /kernel/lifecycle and /desktop/statistics
- Resize the window, see that the charts are being resized correctly, but not constantly
- (if you added the console log, see that there is a …
=> create debounce util module

templates/engage/index.html, templates/engage/redhat-openstack-comparison-whitepaper.md, templates/index.html, templates/takeovers/_redhat-openstack.html, templates/takeovers/index.html
Add openstack redhat comparison engage page and takeover
- Reload the page until you see the "Comparing Red Hat OpenStack Platform and Canonical's Charmed OpenStack" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1DMozJ7XFMOFppwEOADCq52uSryWAVYqS4sdGyq9Mpkc/edit#gid=2113339190)
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1DMozJ7XFMOFppwEOADCq52uSryWAVYqS4sdGyq9Mpkc/edit#gid=1271849439) and [the copy …
=> Redhat takeover and engage page

webapp/security/alembic/versions/8e9386e7a94b_add_component_column_to_status_table.py, webapp/security/models.py, webapp/security/schemas.py, webapp/security/views.py
Add `component` column to `status` table.
1. Check out this feature branch:
```bash
git remote add albert-fork git@github.com:albertkol/ubuntu.com.git  # get my fork
git checkout add-component-to-cve  # checkout the branch
```
2. Reset database
```bash
```
3. Run migration and serve website
```bash
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres exec alembic upgrade head
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres exec python3 scripts/create-releases.py
dotrun --env DATABASE_URL=postgres://postgres:pw@localhost:5432/postgres serve
```
4. In another terminal
If you do not have the project yet:
```bash
git clone -b test-status-component-field …
```
=> Make CVEs support components

templates/engage/redhat-openstack-comparison-whitepaper.md
Changed the PDF download link to https://pages.ubuntu.com/rs/066-EOV-335/images/Comparing%20OpenStack_24.07.20.pdf
Fixes #3011
=> Updated the download link

static/js/src/chassis-animation.js, templates/automotive/_chassis_animation.html, templates/automotive/index.html, webpack.config.entry.js
Update the Canonical and Ubuntu logos at the bottom of the page
Refactored the JS to use the utility `debounce`
- Scroll down to the animation and check that works still
- Continue down to the last section
- Check the logos match [the copydoc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#heading=h.65z06dpsvyz9)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8003
=> Automotive corp logo

templates/security/cve/_cve-table.html
The page with throw a 500, if a package is missing a status on a release.
0. Do not fetch my changes yet.
1. Reset local database
```bash
```
2. Run migration and serve website
```bash
dotrun exec python3 scripts/create-releases.py # to populate release table
dotrun # serve the website
```
3. In another terminal
If you do not have the project yet:
```bash
git clone -b test-status-component-field git@github.com:albertkol/ubuntu-cve-tracker.git # fetch testing branch
```
or if you already have the project just fetch the fork
```bash
git remote add albert-fork git@github.com:albertkol/ubuntu-cve-tracker.git  # get my fork
git checkout test-status-component-field  # checkout the testing branch
```
4. Run …
=> Fix CVE page for missing status

templates/advantage/index.html, webapp/advantage.py
The contracts API was updated in [this PR](https://github.com/CanonicalLtd/ua-contracts/pull/1078) to include a new means of sending the payment method ID when a customer enters their payment details on the renewals modal. 
The change was made so that we have the ability to fetch information about a customer's payment method if we require it (ID, expiry date, brand, last 4 digits etc) e.g. to allow a user to set and update payment methods for use in later purchases.
A subsequent PR introduced [backwards compatibility](https://github.com/CanonicalLtd/ua-contracts/pull/1090) with the previous schema, and once both this and the updated contract API are live, we can remove the outdated `paymentMethodID` parameter. …
=> update /advantage customer info API call

package.json, yarn.lock
- Update global-nav to the v2.4.3
- Run `./run clean`
- Shrink screen to small screen
- See that the border on the body is not visible over the navigation.
| Before | After | 
| --- | --- |
| ![Screenshot from 2020-07-30 23-41-51](https://user-images.githubusercontent.com/1413534/88981685-6e0a2800-d2be-11ea-9c41-dfd62f96e1bf.png) | ![image](https://user-images.githubusercontent.com/1413534/88981567-24b9d880-d2be-11ea-80e6-63046c004ef3.png) |
=> Update global-nav to the v2.4.3

templates/appliance/shared/_featured_appliances.html, templates/blog/article.html, templates/blog/author.html
Some pages that we are monitoring with [Calibre](https://calibreapp.com) have scores below 100 because there are images without `alt` attributes. This PR addresses that, and where appropriate replaces `img` tags with the image template.
- Check that on the following pages the openhab, plex, nextcloud, adguard, and mosquitto all load and have empty `alt` attributes:
- /appliance
- /appliance/hardware
- /appliance/portfolio
- /appliance/vm
- /download/iot
- /download/raspberry-pi
- /download/server
- Check that the avatar on a [blog post page](http://localhost:8001/blog/dell-xps-13-developer-edition-with-ubuntu-20-04-lts-pre-installed-is-now-available) has an empty `alt` attribute
- Click through to …
=> Fix images to improve Calibre score

templates/security/cve/cve.html
Fix single CVE page so that if status is missing for a package, the table does not get messed up.
```bash
git remote add albert-fork git@github.com:albertkol/ubuntu.com.git  # get my fork if you don't have it
git checkout fix-cve-page-for-missing-status  # checkout the branch
```
- Run website
```bash
dotrun
```
- browse to: `/security/CVE-2020-8834` check the table
Fixes #
This is what it looks now:
=> Fix single CVE page

templates/engage/charmed-openstack-adoption-whitepaper.md, templates/engage/index.html
- Updated title of /engage/charmed-openstack-adoption-whitepaper to match the [copy doc](https://docs.google.com/document/d/1MDI2eg5DKHoytmUdXUCziQexEGiXRDml2TnqOwstBYQ/edit)
- Changed the meta image to reflect the new title
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/charmed-openstack-adoption-whitepaper
- Ensure that the page title matches the one in the copy doc, and that the meta image appropriately reflects the new title
- Navigate to http://0.0.0.0:8001/engage and ensure that the new title is reflected there as well
Fixes #8013
=> [Engage] Update title and meta image of openstack adoption whitepaper

static/js/src/dynamic-contact-form.js, static/js/src/navigation.js
- Reverting https://github.com/canonical-web-and-design/ubuntu.com/pull/7367 and https://github.com/canonical-web-and-design/ubuntu.com/pull/7834 as they are not sturdy enough and seem to be causing UTM confusion in some cases (notably mobile webviews) and disrupting Marketing workflows. To be reworked at a later time.
- UTMs in forms are now back to only being pulled from current URL.
- Open a modal contact form on [a page with `utm_campaign=foo`](https://ubuntu-com-8034.demos.haus/openstack?utm_campaign=foo#get-in-to …
=> Revert using localstorage to store UTMs

templates/engage/kubernetes-event-us.md
- Update time and Tim's name
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/kubernetes-event-us
- Compare and resolve the [copy doc](https://docs.google.com/document/d/1LClShZkNAZYCHhXah452SEFYdwetyPstodwRL0Y9ZV8/edit?ts=5f243f38)
Fixes #8024
=> Update time and Tim's name on /engage/kubernetes-event-us

templates/blog/product-cards.html
- Add Bosch rtp to blog posts tagged "Bosch"
- Ensure the RTP box on the right of the [Bosch blog post](https://ubuntu-com-8038.demos.haus/blog/bosch-rexroth-adopts-ubuntu-core-and-snaps-for-app-based-ctrlx-automation-platform) shows an IoT message
=> Add Bosch rtp to blog posts tagged "Bosch"

templates/appliance/shared/_install_instructions_vm_macos.html, templates/appliance/shared/_install_instructions_vm_ubuntu.html, templates/appliance/shared/_install_instructions_vm_windows.html, templates/appliance/shared/_intel-nuc.html, templates/appliance/shared/_raspberry-pi.html, templates/appliance/shared/_raspberry-pi2.html, templates/appliance/shared/_steps-multipass-find-ip-macos.html, templates/appliance/shared/_steps-multipass-find-ip-ubuntu.html, templates/appliance/shared/_steps-multipass-find-ip-windows.html, templates/appliance/shared/_steps-multipass-launch.html, templates/appliance/shared/_steps_install_openssh_windows.html, templates/appliance/shared/_steps_multipass_macos.html, templates/appliance/shared/_steps_multipass_ubuntu.html, templates/appliance/shared/_steps_multipass_windows.html, templates/appliance/shared/_steps_nuc_first_boot.html, templates/appliance/shared/_steps_nuc_flash_usb.html, templates/appliance/shared/_steps_nuc_install_appliance.html, templates/appliance/shared/_steps_nuc_thats-it.html, templates/appliance/shared/_steps_pi_boot-raspberry-pi.html, templates/appliance/shared/_steps_pi_prep-sd-card.html, templates/appliance/shared/_steps_pi_ssh-in.html, templates/appliance/shared/_steps_pi_thats-it.html, templates/appliance/shared/_steps_setup-kvm.html, templates/appliance/shared/_steps_ssh-keys_macos.html, templates/appliance/shared/_steps_ssh-keys_ubuntu.html, templates/appliance/shared/_steps_ssh-keys_windows.html, templates/appliance/shared/_steps_sso.html, templates/appliance/shared/_steps_sso_windows.html, templates/appliance/shared/_steps_vm_thats-it.html, templates/appliance/shared/_verify-checksums.html
- Replace auto-downloading of appliance images with a download button so people who visit the page do not have to keep stopping the download
- Updated the [copy sheet](https://docs.google.com/spreadsheets/d/1eZD3zISXBSNwAwkxlIRtV1UqP8GKPi0YAis8IRLZ9Po/edit#gid=0)
- Removed extra `<hr>` on instructions as vanilla must have added line now.
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/plex/raspberry-pi2, http://0.0.0.0:8001/appliance/plex/raspberry-pi and http://0.0.0.0:8001/appliance/plex/intel-nuc
- See that the download doesn't automatically start and …
=> Remove automatic appliance downloads

templates/engage/desktop-authentication-whitepaper.md, templates/engage/index.html
- Built "Optimised authentication methods for Ubuntu Desktop" engage page
- Added a link to the page on /engage/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/desktop-authentication-whitepaper
- Ensure that the content and metadata matches the [brief](https://docs.google.com/spreadsheets/d/1hcCt87AyGOo2emRTdRJ6AlB3yS0XRfmPr4qR4BxPXbk/edit#gid=1271849439), [copy doc](https://docs.google.com/document/d/1V7rE4urAmP_AWEOPMGut27kaJOeip3kfkEqJHZf7wQg/edit) and [design](https://github.com/canonical-web-and-design/web-squad/issues/3019)
- Navigate to …
=> [Engage] Build desktop authentication page

templates/managed/index.html, templates/managed/kafka.html
- Change meta titles on managed apps and kafka page to match the [issue](https://github.com/canonical-web-and-design/web-squad/issues/3031)
- Ensure that the new meta title is reflected
- Navigate to http://0.0.0.0:8001/managed.kafka and do the same
Fixes web-squad#3031
=> Change meta titles on managed apps and kafka page

releases.yaml
- Updated the releases.yaml with 20.04.1 and the correct checksums
- http://0.0.0.0:8001/download/desktop
- See that the thank-you page points to 20.04.1 and the verify your checksums has the new numbers
Fixes #8037
=> Update releases.yaml for Ubuntu 20.04.1 release

templates/engage/_base_engage_markdown.html, templates/engage/shared/_de_engage_form.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_es_engage_form.html, templates/engage/shared/_fr_engage_form.html, templates/engage/shared/_pt_engage_form.html
- Adding FB conversion events on form submit for /engage/ pages
Why? With the progressive removal of ty pages for whitepapers, we need to have a way to register conversion events at the back of FB ads.
- The fbq() function is provided by GTM
- Hard to test, but here is a screenshot of the event being received in Facebook
=> Add engage pages forms conversion events

navigation.yaml
- Update the contact us navigation title to fix the container.
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us
- See that the navigation section tag fits
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/89654911-41a76a80-d8c1-11ea-8785-eccd7a15e7fc.png) | ![image](https://user-images.githubusercontent.com/1413534/89654812-23416f00-d8c1-11ea-9dcc-9e195b23d804.png) |
=> Update the Contact us navigation tag

navigation.yaml
Removed /apps from Openstack nav
=> Removed /apps from Openstack nav

templates/robotics/community.html
- Move 'Keep up on the State of Robotics' and 'Recent news' up
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit?ts=5f2d0d58#heading=h.o5srtkczcpn)
Fixes #8061
=> Move strips up the page on /robotics/communtiy

templates/ceph/index.html, templates/ceph/what-is-ceph.html, templates/shared/_resources_ceph.html
- Resources row for /ceph and /what-is-ceph
- Small resources related changes: link to PDF for top of page case studies, webinar link in what-is hero)
- Ensure pages match their copy docs and that new links are working
=> Add Ceph resources row + misc resources changes

requirements.txt, templates/blog/blog-card.html, webapp/app.py
Replaces `admin.insights.ubuntu.com/wp-content/uploads` with `ubuntu.com/wp-content/uploads`. 
Additionally it enables the cloudinary service for our images again.
Check out the image url, it will be converted to a cloudinary url, and instead of `admin.insights.ubuntu.com/wp-content` the img url will show `ubuntu.com/wp-content`.
Browse to the blog to check the thumbnails:
https://ubuntu-com-7940.demos.haus/blog
Browse to an article:
https://ubuntu-com-7940.demos.haus/blog/dell-xps-13-developer-edition-with-ubuntu-20-04-lts-pre-installed-is-now-available
Browse to another article:
https://ubuntu-com-7940.demos.haus/blog/design-and-web-team-summary-20th-july-2020
Everything should look exactly like on prod.
Fixes #2995
=> Replace Wordpress class with BlogAPI class

static/js/src/cve/cve-search.js, static/js/src/cve/cve.js, templates/security/cve/_version-and-status-row.html, templates/security/cve/index.html
On a CVE search, if both the version and status are set to "Any" on any of the rows the "+" button should be disabled, otherwise it should be enabled.
- Run the site: `docker-compose up -d && dotrun`
- Go to http://localhost:8001/security/cve
- Check that both the "+" and "-" buttons are disabled next to the version/status fields
- Change the value of either field so that at least one isn't set to any
- Check that the "+" button is now enabled
- Add some more rows and play around with the values
- If any row has both value set to "Any" then all "+" buttons should be disabled
- Submit a search with and without fields set to "Any" and check that the "+" buttons behave as above
Fixes #8020
=> Disable CVE add row button if any is selected for both status and value

webapp/security/views.py
Some of the older CVE's don't have a publish date.
The database accepts Nulls but we need to show them at the bottom
of the list instead of showing them at the top.
- Try and import the two CVE's i referenced in #8045 
- Go to http://localhost:8001/security/cve and make sure `CVE-2006-2192` shows last.
- Checkout master and see it shows at the top.
Fixes #8045
=> Move CVE's with no publish date to the end of the list.

templates/shared/forms/interactive/telco.html, templates/telecommunications/index.html
- Added telco specific contact us form
- **Note: the copy doc wants radio buttons for the first question, but the script doesn't allow it.**
- View the site locally in your web browser at: http://0.0.0.0:8001/telecommunications#get-in-touch
- Compare to the [copy doc](https://docs.google.com/document/d/1GszC6D1EU0_cHXIsOL1HlPtoMuB1XplCK8J2poqyLQk/edit#)
- See that the form submits
Fixes #8010
=> Add telco modal form

templates/kubernetes/docs/1.18/release-notes.md, templates/kubernetes/docs/auth.md, templates/kubernetes/docs/certs-and-trust.md, templates/kubernetes/docs/charm-docker-registry.md, templates/kubernetes/docs/charm-kubeapi-load-balancer.md, templates/kubernetes/docs/charm-kubernetes-master.md, templates/kubernetes/docs/install-local.md, templates/kubernetes/docs/snap-refresh.md, templates/kubernetes/docs/storage.md
Updates for K8s docs. Mainly release notes for 1.18ck1
=> K8sdocs: Updates  for 1.18ck1

templates/kubernetes/docs/1.18/release-notes.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md
=> K8s docs add 1.18ck2 release

templates/engage/data-lake_2_server_webinar.md, templates/engage/index.html, templates/index.html, templates/takeovers/_data-lake_2_server_webinar.html, templates/takeovers/index.html
- Create data lake webinar engage page
- takeover here: http://0.0.0.0:8001/
- takeover index: http://0.0.0.0:8001/takeover
- engage page: http://0.0.0.0:8001/engage/data-lake_2_server_webinar
- engage index: http://0.0.0.0:8001/engage/
- Compare to the design and the [copy doc](https://docs.google.com/document/d/1A9BYXs8Wb-95ahpNJZ-KDloY3ni0v2kIA3O-OB81cW8/edit#)
Fixes #8056
=> Create data lake webinar engage page

requirements.txt
Update blog module to hot fix bug when `width="100%"` is set for image.
Browse to: https://ubuntu.com/blog/top-10-linux-apps-for-entertainment-and-leisure
It throws a 500.
Browse to: https://ubuntu-com-8083.demos.haus/blog/top-10-linux-apps-for-entertainment-and-leisure
Confirm that it works.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8078
=> Blog module update

releases.yaml, templates/download/raspberry-pi/index.html, templates/download/raspberry-pi/thank-you.html, webapp/views.py
- Updated releases.yaml
- Got rid of the versionPatch hack
- http://0.0.0.0:8001/download/alternative-downloads
- See that all the downloads are for either 18.04.5 or 16.04.7
Fixes #8079
=> Updates for 18.04.5 and 16.04.7 point releases

releases.yaml, templates/download/alternative-downloads.html
- Remove eoan by adding a past_eol_date boolean
- View the site locally in your web browser at: http://0.0.0.0:8001/download/alternative-downloads#bittorrents
- See that Eoan is removed from the bittorrents section
=> Remove eoan from /download/alternative-downloads#bittorrents

navigation.yaml, templates/security/oval.html
- Build the oval page
- Added it to the navigation
- View the site locally in your web browser at: http://0.0.0.0:8001/security/oval
- Compare to the [design](https://user-images.githubusercontent.com/65166314/90130821-04c8f100-dd63-11ea-9b28-e05c2dfab573.png) and the [copy doc](https://docs.google.com/document/d/1hBG6NIfBIrixIV753fsOiEymmeuFIF-KOhiDkV68PRY/edit#heading=h.4vy8ll249k4p)
Fixes [#2900](https://github.com/canonical-web-and-design/web-squad/issues/2900)
=> Initial version of the /security/oval page

templates/legal/confidentiality-agreement.html
- Update NDA pdf on /legal/confidentiality-agreement
- Created and uploaded the pdf
- Updated the copy doc
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/confidentiality-agreement
- See that it links to the new pdf per the [copy doc](https://docs.google.com/document/d/123_RbbqhDzsiWrLQkl1c_1aqr2uT6hKeq0LuNDl21Ms/edit)
=> Update NDA pdf on /legal/confidentiality-agreement

templates/download/alternative-downloads.html
- found a few http://releases.ubuntu.com and updated to https
- View the site locally in your web browser at: http://0.0.0.0:8001/download/alternative-downloads
- See that `https` is used for releases.ubuntu.com
=> Update releases.ubuntu.com to https

static/js/src/cve/cve-search.js, static/js/src/cve/cve-search.test.js, static/js/src/cve/cve.js
Disable Ubuntu version in dropdown if already selected in a previous row
Check out this feature branch
```
dotrun exec python3 scripts/create-releases.py
dotrun
```
In the directory containing ubuntu.com:
```
git clone -b test-status-component-field git@github.com:albertkol/ubuntu-cve-tracker
```
- Go to http://localhost:8001
- Select an Ubuntu version and add a new row
- Check that the previously selected version is disabled in the new row
- Change the previously selected version and check that it is now enabled in the new row
- Try a few combinations, the …
=> Disable version if previously selected in CVE search

appliances.yaml, templates/download/alternative-downloads.html, templates/download/desktop/thank-you.html, templates/download/intel-iei-tank-870.html, templates/download/iot/index.html, templates/download/kvm.html, templates/download/qualcomm-dragonboard-410c.html, templates/download/raspberry-pi-core.html, templates/download/raspberry-pi/thank-you.html, templates/download/server/arm.html, templates/download/server/power.html, templates/download/server/thank-you-s390x.html, templates/download/shared/_verify-checksums.html, templates/legal/websites.html
- According to [RT#107875](https://rt.admin.canonical.com/Ticket/Display.html?id=107875) cdimage is now https, so updated all links to that
- appliances.yaml
- https://0.0.0.0:8001/download/alternative-downloads.html
- https://0.0.0.0:8001/download/desktop/thank-you.html
- https://0.0.0.0:8001/download/intel-iei-tank-870.html
- https://0.0.0.0:8001/download/iot/index.html
- https://0.0.0.0:8001/download/kvm.html
- https://0.0.0.0:8001/download/qualcomm-dragonboard-410c.html
- https://0.0.0.0:8001/download/raspberry-pi-core.html
- https://0.0.0.0:8001/download/raspberry-pi/thank-you.html
- https://0.0.0.0:8001/download/server/arm.html
- …
=> Update cdimage links to https

templates/kubeconeurope2020/index.html
- s/Kubecon/KubeCon/g
- Added T&C for the contest
- Added ID for the page
- Added youtube live chat (currently hidden) that we can show once we know the link
- View the site locally in your web browser at: http://0.0.0.0:8001/kubeconeurope2020#contest
- Compare to the [copy doc](https://docs.google.com/document/d/1qZGlO8ecig760hXn-8DG3fw52LNHfTM7WKwAHu_DpXc/edit#), see that the `#contest` anchor works and that the T&Cs pdf loads
=> Update kubecon form section and spelling of KubeCon

templates/kernel/variants.html
- Fixed typo in /kernel/variants
None
[Noticed while researching [vanilla-framework#3190](https://github.com/canonical-web-and-design/vanilla-framework/issues/3190).]
=> “varient” > “variant”

templates/download/flavours.html
- Update Kylin link on /download/flavours
- View the site locally in your web browser at: http://0.0.0.0:8001/download/flavours
- See that the link now works
Fixes #8094
=> Update Kylin link on /download/flavours

templates/templates/_footer_item.html
Remove `small` tag from footer sitemap links to keep font-size consistent
- Check that the links in the footer site map are all the same font-size
Fixes #8091
=> Remove small tag around footer links for consistent sizing

templates/kubeconeurope2020/index.html
- Turn on livechat on /kubeconeurope2020
- See that the livechat is working for ubuntu.com domain (will not work on demo)
=> Turn on livechat on /kubeconeurope2020

templates/0_docs/takeovers.html, templates/base_index.html, templates/takeovers/_gsi-webinar-series-takeover.html, templates/takeovers/_template.html
- Adds the notion of timezones to takeovers
- Target India only for the GSI takeover ("Kolkata" is the timezone city name for all of India)
- Ensure you are **not in India** and that takeovers work as expected, you should not see the GSI webinar takeover.
- Change the timezone value of the GSI takeover (templates/takeovers/_gsi-webinar-series-takeover.html) to something matching your location.
- You target a timezone based on any portion of its IANA timezone name …
=> Takeovers geo targeting using timezones

templates/security/cve/_cve-table.html, webapp/security/views.py
Enable component filter.
Display only packages of the cve that match the search criteria.
1. Have the latest CVEs imported in your local database. `CVE-2020-8834` should be the most recent cve on `/security/cve`
2. All the packages should have the component `main` right now. We have to create a `universe` component to test the filter.
```bash
docker exec -it db psql -U postgres # go to the databse
```
```SQL
UPDATE status SET component='universe' WHERE cve_id='CVE-2020-8834' AND release_codename='focal' AND package_name='linux' 
```
3. Fetch my branch changes: 
```bash 
git checkout search-cves-by-component
```
4. Browse to `/security/cve`. Filter by component, you should only see one row.
Fixes #7926
=> Search cves by component

templates/robotics/community.html, templates/robotics/index.html, templates/robotics/what-is-ros.html
- Clean up /robotics page titles
- Add question mark to what is page title (because it worked well for Ceph)
- Ensure page titles are nice and tidy
=> Clean up robotics page titles

templates/kubeconeurope2020/index.html
- changed email to work email
- phone to moble phone
- used title case on labels
- See that the labels have been updated
=> Change to work email and mobile number on /kubeconeurope2020

templates/kubeconeurope2020/index.html
- See that it uses a new video id
=> New video chat id on /kubeconeurope2020

templates/security/cve/index.html
Added "Any" placeholder to the CVE package search field
- Check that the "Package" field in the search form has a placeholder of "Any"
Fixes #8097
=> Add Any placeholder to CVE package field

templates/security/cve/_cve-table.html, templates/security/cve/cve.html
Display link to ESM for apps and ESM for infra for statuses with the respective components.
1. Have the latest CVEs imported in your local database. `CVE-2020-8834` should be the most recent cve on `/security/cve`
2. All the packages should have the component `main` right now. We have to create some `esm-apps` and `esm-infra` components for testing.
```bash
docker exec -it db psql -U postgres # go to the databse
```
```SQL
UPDATE status SET component='esm-infra' WHERE cve_id='CVE-2020-8834' AND release_codename='precise' AND package_name='linux';
UPDATE status SET component='esm-apps' WHERE cve_id='CVE-2020-8834' AND release_codename='trusty' AND package_name='linux';
```
3. Fetch my branch changes: 
```bash 
git checkout cve-display-component
```
4. Browse to …
=> Display esm-apps and esm-infra for CVE

templates/contact-us/index.html
- Remove bluefin fax number from site and [copy doc](https://docs.google.com/document/d/1LK7lJlhke8hKesVSglHxNSfUCDw0bfddzM4vezeXvBQ/edit#)
- Scanned other sites and didn't find the number
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us
- See that the fax number is no longer listed
Fixes #8076
=> Remove bluefin fax number

templates/legal/confidentiality-agreement.html, templates/legal/data-privacy/index.html, templates/legal/data-privacy/online-competitions.md, templates/legal/data-privacy/unilateral-nda.md
- Drive by: Fix heading on /legal/data-privacy/online-competitions
- Add Unilateral NDA data privacy page
- Add NDA page to data privacy page
- Update confidentiality agreement page
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy/unilateral-nda
- Check that the page matches [the copydoc](https://docs.google.com/document/d/1MzxiuSwLvT440Ew5-3aPsFHo2zy2QVt1ZEJJpVEaZho/edit?ts=5f33e3f5#)
- Go to /legal/data-privacy and check that it has been updated according to [the copy doc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X …
=> Create unilateral nda privacy notice page

templates/security/oval.html
Removed Ubuntu OVAL's coverage section
- Check the demo against the [copy doc](https://docs.google.com/document/d/1hBG6NIfBIrixIV753fsOiEymmeuFIF-KOhiDkV68PRY/edit) and accept correct changes
=> Removed Ubuntu OVAL's coverage

templates/openstack/consulting.html
Updated the copy on /openstack/consulting
- Check that the page has been updated according to comments from Tytus in [the copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#) and resolve the comments
Fixes #3069
=> Update copy on OpenStack consulting page

templates/shared/pricing/_openstack-packages.html
Added missing fullstop on /openstack
- Search the page for the string "Design and Deployment of a secure, carrier grade, feature rich OpenStack custom architecture" and check that it ends with a fullstop
=> Add missing fullstop on openstack pages

static/js/src/renewal-modal.js
If processing a renewal payment takes a long time (> 30 seconds), we reload the page and show a processing label on the relevant subscription. We weren't sending a related event to GA however, and we want more visibility over if/how often that is happening.
This isn't easily QA-able, we only send events in production to try to keep the data there clean. However, you can [see in GA](https://analytics.google.com/analytics/web/#/report/content-event-events/a1018242w108544136p159562819/_u.date00=20200808&_u.date01=20200819&_r.drilldown=analytics.eventCategory:advantage,analytics.eventAction:renewal&explorer-table.plotKeys=%5B%5D/) the other events being sent by the same `sendGAEvent()` function called here, so I'm confident this works.
=> send GA event when payment processing takes a while

templates/security/cve/index.html
Changed text around CVE search results
- Check that the page title is "CVEs | Ubuntu"
- Check that the main heading is "CVE reports"
- Check that there is a "Search" subheading
- Do a search (it can be an empty search if you have no CVEs)
- Check that the page title is "CVE search results | Ubuntu"
- Check that the main heading is "CVE search results"
- Check that there is no "Search" subheading
Fixes #8100
=> Change text around CVE search

templates/security/certifications.html
- added `u-align--center` to the bottom few strips' logos
- See that all the logos align top to bottom on the page
=> Centre align logos on /security/certifications

templates/blog/product-cards.html
- Add Ceph-related card on all blog posts tagged with "ceph"
- Ensure blog posts listed in [/blog/tag/ceph](https://ubuntu-com-8135.demos.haus/blog/tag/ceph) contain a Ceph-related card, and that it provides a good experience on mobile
=> Add Ceph blog card

templates/shared/pricing/_maas-pricing.html
- Remove MAAS monthly pricing
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
=> Remove MAAS monthly pricing (see /pricing/infra)

templates/kubeconeurope2020/index.html
- Update youtube chat id on /kubeconeurope2020
=> Update youtube chat id on /kubeconeurope2020

templates/security/oval.html
Updated the copy on /security/oval
- View the site locally in your web browser at: http://0.0.0.0:8001/security/oval
- Check that the change requested by Lech in [the copy doc](https://docs.google.com/document/d/1hBG6NIfBIrixIV753fsOiEymmeuFIF-KOhiDkV68PRY/edit#) has been made and resolve the comment
Fixes #8146
=> Update oval page copy

templates/shared/pricing/_openstack-kubernetes-lma.html, yarn.lock
- Update managed k8s, openstack and ceph pricing
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
Fixes #8145
=> Update managed k8s, openstack and ceph pricing

templates/kubeflow/consulting.html
Added mavencode logo to /kubeflow/consulting
- Check that the mavencode logo has been added as requested in [the copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit#) and resolve the comment
Fixes #8141
=> Add mavencode logo to kubeflow consulting page

webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py, webapp/security/models.py, webapp/security/schemas.py, webapp/security/views.py
Adds tags and patches columns to cve. 
1. [Terminal 1]: Reset your database 
```bash
dotrun
```
2. [Terminal 2]: Populate database
If you do not have the `ubuntu-cve-tracker` repo locally:
```bash
git clone -b send-cve-patches git@github.com:albertkol/ubuntu-cve-tracker.git # fetch testing branch
```
If you already have the project just fetch the fork
```bash
git remote add albert-fork git@github.com:albertkol/ubuntu-cve-tracker.git  # get my fork
git checkout send-cve-patches  # checkout the testing branch
```
3. [Terminal 2]: Run importer
```bash …
```
=> Add patches and tags to cve

templates/engage/index.html, templates/engage/telco-virtual-event.md, templates/index.html, templates/takeovers/_telco-virtual-event.html, templates/takeovers/index.html
Added Telco virtual event takeover and engage page
- Reload the page until you see the "Transforming telco infrastructure" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1XAStuaJ_TlaVfvVZY6BGkwQgl64bLSFuCz7meRzRYME/edit#gid=2113339190)
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1XAStuaJ_TlaVfvVZY6BGkwQgl64bLSFuCz7meRzRYME/edit#gid=1271849439) and [the copy doc](https://docs.google.com/document/d/1xiyF0Kx6ISWiVp4gLrEY …
=> Telco vevt takeover engage page

templates/download/flavours.html
Fix for Issue#8166 Ubuntu Kylin download link reports 404 Not Found for English language
Fixes #8166
=> Update Ubuntu Kylin link

webapp/security/alembic/versions/570b8ff188c4_update_cve_component_field.py, webapp/security/models.py, webapp/security/schemas.py
Update component to be nullable and have the enum type of only "main" and "universe".
Before it would have also "esm-infra" and "esm-apps" but that will be shifted to a new column called `pocket`.
0. [Terminal 1]: Fetch PR changes
```bash
git checkout cve-component-update
```
1. [Terminal 1]: Reset your database 
```bash
dotrun
```
2. [Terminal 2]: Fetch changes
```bash
git remote add albert-fork git@github.com:albertkol/ubuntu-cve-tracker.git  # get my fork
git checkout test-component  # checkout the testing branch
```
3. [Terminal 2]: Run importer
```bash
time …
```
=> Update component to main or universe

templates/security/cve/_cve-table.html, webapp/security/alembic/versions/88f1398da6c1_add_cve_pocket_column.py, webapp/security/models.py, webapp/security/schemas.py, webapp/security/views.py
CVE add pocket column. It can be one of 'security', 'updates', 'esm-infra', 'esm-apps'.
It is optional and nuallable.
0. Fetch changes of this branch:
```bash
git checkout cve-add-pocket-column
```
1. [Terminal 1]: Reset your database 
```bash
dotrun
```
2. [Terminal 2]: Fetch changes
```bash
git remote add albert-fork git@github.com:albertkol/ubuntu-cve-tracker.git  # get my fork
git checkout test-pocket  # checkout the testing branch
```
3. [Terminal 2]: Run importer
```bash
```
If you browse to `/security/cve` you will see the …
=> CVE add pocket column

templates/security/cve/_status-fields.html, templates/security/cve/_version-fields.html, templates/security/cve/cve.html, webapp/security/models.py, webapp/security/views.py
Enable version-status filter.
Display only packages of the cve that match the search all the version-status criteria.
1. Have CVEs imported in your local database.
2. Fetch my changes:
```bash
git checkout search-cves-by-component
```
3. Browse to `/security/cve`. Play with the version-status filter.
Fixes #7928
=> Search cves by version status

konf/site.yaml, webapp/views.py
- Launchpad username can be set now as an env variable.
- Launchpad auth consumer can be set now as an env variable.
- Check the image builder functionality is working as expected with the Launchpad staging account.
=> Remove hardcoded Launchpad account for image builder

templates/security/notice.html, webapp/security/schemas.py
Add pocket check for USN `release_packages` and display it.
3rd commit (_For testins: Add random pocket_) is only for testing purposes and will be removed after QA.
1. Fetch changes
```bash
git checkout request-usn-pocket
```
2. Make sure you have CVEs imported
3. Run website 
```bash
dotrun
```
4. In a new terminal. Run notice import (You can stop it after 5-ish notices):
```bash
dotrun exec python3 scripts/create-usns.py database.json
```
5. Browse to: `/security/notices/USN-3895-1` if any of those packages patches are only for `infra` or `apps` it will be displayed.
Fixes #7933
Fixes #7925
=> Request usn pocket

templates/shared/pricing/_openstack-packages.html
- Add datasheet to /openstack page
- Ant can you re-approve, I had to redo it.
- Compare to the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#) and resolve comments
Fixes #8161
=> Add datasheet to /openstack page

templates/security/cve/cve.html, webapp/security/models.py
Display tags and patches.
1. Fetch changes
```bash
git checkout display-patches-and-tags
```
2. Make sure you have cves imported
3. Launch website
```bash 
dotrun
```
4. Browse to:
`/security/CVE-2012-4542` 
`/security/CVE-2019-16935`
`/security/CVE-2020-8834`
Check that the tags show up and look good. Check that the patches show up nicely with links with different formats.
Fixes #8160
=> Display patches and tags

static/js/src/chart-data.js, templates/about/release-cycle.html
The delayed release of Kubernetes 1.19 has a knock-on effect for the support chart on https://ubuntu.com/about/release-cycle
This fixes the dates on that chart
=> Update K8s release chart

templates/engage/telco-virtual-event.md
- Update the time of the event
- Remove Greg from the speaker list
- Check it matches [the copy doc](https://docs.google.com/document/d/1xiyF0Kx6ISWiVp4gLrEYtwyaMo5iKPU01Vxq3SSb5lU/edit#).
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8198
=> Update time on Telco VEVT Sept 2020 event

templates/openstack/managed.html, templates/shared/contextual_footers/_cloud_bootstack.html, templates/shared/contextual_footers/_k8s_managed.html
- Fixed grammar on OpenStack managed footer
- Created a k8s managed footer
- Used k8s managed footer on /openstack/managed
- See that it doesn't refer to the page it self with the K8s footer instead
Fixes #8151
=> Fix contextual footer on /openstack/managed

templates/kubeflow/install.html
- Add install video to the Kubeflow install page
- Check that the changes make [the copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit?ts=5f4e5feb#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8203
=> Add install video to the Kubeflow install page

templates/engage/index.html, templates/engage/kubernetes-deployment-enterprise-whitepaper.md, templates/index.html, templates/takeovers/_kubernetes-enterprise-whitepaper-takeover.html, templates/takeovers/index.html
Added takeover and engage page for enterprise kubernetes
- Reload the page until you see the "Five strategies to accelerate Kubernetes in the enterprise" takeover
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1dboZFvt4v3-xxru2_0ub3uLYQIPT3ouOWcxfjHuKHug/edit#gid=2113339190)
- Check that it matches [the brief](https://docs.google.com/spreadsheets/d/1dboZFvt4v3-xxru2_0ub3uLYQIPT3ouOWcxfjHuKHug/edit#gid=1271849439) and [the copy …
=> Add takeover and engage page for enterprise kubernetes

templates/engage/kubernetes-deployment-enterprise-whitepaper.md
Add webinar to the enterprise kubernetes engagement
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/kubernetes-deployment-enterprise-whitepaper
- Check there is a secondary webinar CTA
- Click it to see the embedded webinar
- Check it matches [the brief](https://docs.google.com/document/d/1vDjaIyerf_5TB3y1wP93kU8gOtd8PMYsNVJYMfne_4k/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3110
=> Add webinar to the enterprise kubernetes engagement

templates/engage/gsi-webinar-series.html, templates/engage/index.html, templates/takeovers/_gsi-webinar-series-takeover.html
- Update the copy based on a request in [the copy doc](https://docs.google.com/document/d/1ZweTXyHO9kIU9aE8pw2_Ni_NoBShM_KseY5H2XtGueg/edit).
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/gsi-webinar-series
- Check the word has changed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8214
=> Update powerful to scalable in the GSI engagement

templates/core/build/index.html, templates/core/index.html, templates/internet-of-things/appstore.html, templates/internet-of-things/digital-signage.html, templates/internet-of-things/gateways.html, templates/internet-of-things/index.html, templates/internet-of-things/networking.html, templates/shared/forms/interactive/internet-of-things.html
- Build the new internet-of-things modal
- Apply it to /core and /internet-of-things sections
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things#get-in-touch
- See that the contact modal matches the [copydoc](https://docs.google.com/document/d/1t8k61sE5AopyvsXuMoyNDAghdnrjH4TlRdDGT4tqAes/edit#)
- Jump to /core#get-in-touch and see its the same.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3126
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3127
=> Build the new internet-of-things modal

navigation.yaml, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/snaps.md, templates/kubernetes/docs/supported-versions.md
Update supported versions: https://github.com/charmed-kubernetes/kubernetes-docs/pull/460
Add reference page for K8s snaps: https://github.com/charmed-kubernetes/kubernetes-docs/pull/453
=> K8sDocs: Add k8s snap reference page

webapp/advantage.py, webapp/app.py, webapp/views.py
Add a new endpoint to we can get a preview of the purchase we are about to make(useful to get things like VAT to show the user)
- Replace the current JS call to `/advantage/purchase` by `/advantage/purchase/preview` and see it returns a similar response without actually making the purchase.
Fixes #8186
=> Add new purchase preview endpoint for shop

.env, static/js/src/ua-product-selector.js, templates/advantage/subscribe.html, tests/cassettes/TestRoutes.test_advantage.yaml, webapp/advantage.py, webapp/app.py, webapp/views.py
- Added a check to make sure a user is an admin on one of their accounts
- The product selection form now scrolls between steps
- If the user is not logged in, or doesn't have an account with admin permissions, prevents the user being able to select a product
- Temporary, until guest checkout can be implemented
- Prevents tabbing to inputs within `u-disable` sections
- Assuming you are not signed in, the form should be disabled
- You should also not be able to tab to any of the inputs
- Follow the link to login with SSO, and do so
- When you are returned to the page, you should see the first section of the form …
=> Advantage shop polish

templates/base_index.html
- Removed extra closing tag breaking the #main-content div where it shouldn't
- Ensure the #main-content div on the homepage contains everything that's between nav areas (mega menu, footer)
- Ensure link clicks in main-content are received as GA events ( :heavy_check_mark:  Yes, they are now)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8221
=> Remove extraneous closing tag on index

static/js/src/ua-payment-modal.js
For shop & renewals, added a check to see whether we're using the Stripe prod or test environment (Stripe key in prod begins with "pk_live", and in test it's "pk_test"), and prevent GA events from being fired outside of production.
Also updated the event action, so we know whether the transaction was a renewal or a purchase.
- Install and activate the [GA debugger](https://addons.mozilla.org/en-GB/firefox/addon/ga-debugger/)
- Open your browser's console
- Select a product, add it to cart, and open the payment modal
- The console should show no GA activity when you open the modal
=> Check Stripe env when attempting to send GA events on /advantage

webapp/security/auth.py
Add `canonical-security-web` group to the list of groups allowed to make
api calls.
Make the life the of the token longer. This way the import of the data
will be able to go uninterrupted for longer.
Fixes #8216
=> Change user auth config

templates/engage/index.html, templates/engage/it/da-vmware-a-openstack.md, templates/engage/shared/_it_engage_form.html, templates/index.html, templates/takeovers/index.html, templates/takeovers/it/_da-vmware-a-openstack.html
- Build the engage page
- Build the takeover page
- Add them to all three indexes
- Added IT engage form
**Blocked** Waiting for the TY page content to be updated: https://pages.ubuntu.com/CY20_DC_OpenStack_IT_Whitepaper_VMwaretoOpenstack_LPWhitepaperVMwaretoOpenStackES-TYvanilla.html
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/it/da-vmware-a-openstack and check the content matches [the copy doc](https://docs.google.com/spreadsheets/d/1wBLTslfNHJrEK4mwhIitXj_2qWtlf4JAoZJjefe0fe4/edit#gid=1833127475) and [brief](https://docs.google.com/spreadsheets/d/1lY3C-8GJ4oboM8dyozvnKtib6p_EVD3F3VzMWR58hFc/edit#gid=2113339190)
- Change your browser lang to "it" and refresh the …
=> Build IT da-vmware-a-openstack engagment

templates/blog/article.html
Remove sticky from the newsletter sign up on the blog
- **Join the VPN**
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/canonical-enables-linux-desktop-app-support-with-flutter
- See the Newsletter sign up card stays put and allows people with smaller screens to submit.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8231
=> Remove sticky from the newsletter sign up on the blog

static/js/src/dynamic-contact-form.js
Correctly send form submission GA event
- Install [the browser extension "Google Analytics Debugger"
- Click the envelope icon in the extension tray to turn it out
- Open the your browser console
- Refresh and you should see a bunch of events. Clear them.
- Click contact us button and see the form opens and triggers an `open` event
- Click close X and see it triggers a single "interactive-forms" event of "close"
- Click on the contact button again 
- Set your console to Persist
- Click through the form and fill out the final contact us form
- Once you land on the thank you ensure there was a single "interactive-forms" event of …
=> Correctly send form submission GA event

templates/index.html
- Removed Anbox introduction takeover
=> Removed Anbox introduction takeover

redirects.yaml
- Redirect initial messed up blog post URL to new URL (because already posted on social :( )
- Ensure the redirect works (won't work on the demo)
=> Kubernetes 1.19 blog redirect

templates/legal/contributors/agreement.html, templates/legal/contributors/index.html
Replace Launchpad username with Github username the legal copy
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/contributors/agreement
- Check the copy changes match the [copy doc](https://docs.google.com/document/d/1MfgTzlAxiFE6VUW1qAPmrks2ui1zzsX5T7d-DZJlOAw/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3165
=> Replace Launchpad username with Github username the legal copy

konf/site.yaml
- Proxy Wordpress API
1. Connect to the Canonical VPN
2. Add `127.0.0.1 ubuntu.com` to your `/etc/hosts` file
3. If you know what you are doing: `konf production konf/site.yaml --local-qa | microk8s.kubectl apply -f -`. If not read and follow the QA steps of this [other PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/7909) 
4. `curl -I --insecure https://ubuntu.com/wp-json/wp/v2/posts\?tags\=3110\&per_page\=12\&page\=1\&tags_exclude\=3\&_embed\=true` should return a 200 status code.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3155
=> Proxy Wordpress API

konf/site.yaml
- Change path for the blog API to `/blog/wp-json/wp/v2/`
=> WordPress API under /blog

tests/test_views.py, webapp/views.py
- When presenting a renewal to a user, sort the array of renewals by their `start` property, and return the earliest starting one to the view.
- In VS Code (or whichever editor you're using), open /tests/test_views.py
- Switch the values on lines 223 and 230 (`start_yesterday` and `start_last_week`)
- In your console, run `dotrun exec npm run test-python`
- See that that one test fails
- Undo your changes, and run the test again, it should pass
=> if a contract has multiple renewals, return earliest one

templates/security/notice.html, webapp/security/models.py, webapp/security/views.py
Add two new hybrid notices for Notice:
1) `related_notices`: to fetch related notices of the current notice
2) `package_list`: to fetch an array of all the packages part of the
notice
1. Fetch changes
```bash
git checkout display-related-notices
```
2. Have notices imported
3. Launch website (`dotrun`) and browse to `/security/notices/USN-4328-1` and scroll down you will see the Related Notices section.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2576
=> Display related notices

webapp/security/views.py
- Add an extra query condition to reduce the number of `CVE.statuses` before
the more complex conditions get applied.
0. Do not fetch the changes yet
1. Go to `/security/cve` play with the version-status filters. You will notice it takes 1-2 seconds (on local) to get the page loading
2. Fetch the changes
```bash
git checkout optimise-cve-filter
```
3. Go to `/security/cve` play with the version-status filter. It should still work and the results should be return in less than half a second.
=> Optimise CVE filter

webapp/security/views.py
CVEs are ordered desc by `published` date. Some old CVEs do not have a
published date, so null gets inserted in the database. When these get
ordered NULL values are listed at the top.
This change will list the NULL values at the end.
0. Do not fetch changes.
1. Have the CVEs imported. 
2. Update some CVEs to have published date NULL
```bash
docker exec -it db psql -U postgres
```
And run:
```sql
UPDATE cve SET published=NULL WHERE id='CVE-2012-0937'; 
UPDATE cve SET published=NULL WHERE id='CVE-2012-1191'; 
UPDATE cve SET published=NULL WHERE id='CVE-2012-1148'; 
```
3. Browse to `/security/cve`. You will see these cves at the top.
4. Fetch changes:
```bash
git checkout cve-fix-order-if-published-null
```
5. Browse to `/security/cve`. You will not see these cves at …
=> Fix CVE order

templates/esm/index.html
Add notification banner to ESM page
- Check the second strip is a shallow notification banner
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3162
=> Add notification banner to ESM page

templates/security/cve/cve.html
Display cve packages sources on the cve page.
FX: 
https://people.canonical.com/~ubuntu-security/cve/2020/CVE-2020-8834.html You can see `source` under every package
https://ubuntu.com/security/CVE-2020-8834 does not have it
1. Fetch changes 
```bash
git checkout add-cve-package-source
```
2. Browse to `/security/CVE-2020-8834` you will see the source listed under the name of the package.
Fixes #8264
=> Display cve package sources

webapp/security/views.py
Optimise the number of queries executed by the endpoint.
Two changes:
1) Load all releases one time. Just like we do with packages.
2) If a CVE already exists and is fetched from the database we fetch
it's statuses too now. Later on when we do `cve.statuses` we do not need
to query the database again.
1. Fetch changes:
```bash
git checkout optimise-bulk-import
```
2. Refresh local database
```bash
dotrun
```
3. Re-import CVEs let it run for a few seconds, stop and re-run it (so you test both insert CVE and update CVEs)
Fixes #8191
=> Edit bulk import

.env, tests/cassettes/TestRoutes.test_advantage.yaml, tests/test_views.py, webapp/advantage.py, webapp/app.py, webapp/views.py
**⛔ revert API environment back to prod before merging ⛔**
- if a contract has info on its machine allowance, present it to the user on /advantage as "X/Y" where X is the number of attached machines, and Y is the number of machines they have paid for.
- Login
- If you don't have contract staging data already, talk to Scott and he'll set you up with what you need
- See that under "attached", you can see how many machines you have, and how many have been attached.
and/or: 
- see that the tests pass, and that the screenshot looks good
=> Show machine allowances on /renewals when possible

navigation.yaml
- Re-add overview of secondary nav on /security
- Check overview is visible
Fixes #8307
=> Re-add overview on /security 

templates/security/_notice-brief.html
- Add cves to the usn listings. Spec: https://docs.google.com/document/d/183fLUXOLL17_baS617aX7Sj133n4lLfS6-rLhXXv9I0/edit#heading=h.z80bvqisakj6
**1)** Import the notices (root of the ubuntu.com repo):
Terminal 1 (root of the ubunut.com repo):
```bash
dotrun
```
Terminal 2 (root of the ubunut.com repo): 
```bash
python3 scripts/create-usns.py database.json # path to your database.json file might be somewhere else
```
Leave it only for 10-15 seconds. You only need a few notices in the database to QA these changes.
**2)** Fetch the changes:
```bash
git checkout display-cve-in-usn-listings
```
**3)** Browse to `/security/notices`. You will see the cves listed for each usn just above the ubuntu releases.
Fixes #2255
=> Add cves in usn listings

konf/site.yaml, requirements.txt, templates/smart-start/base_docs.html, templates/smart-start/document.html, webapp/app.py
- Add new discourse module with authentication
- Open the demo and navigate to `/docs`
- Might want to review the other `/docs` just in case, as there has been some renaming. i.e. `/server/docs`, `/tutorials`, `/ceph/docs`
Fixes #8254 #8255
=> SMART START guide

templates/takeovers/es/guía-implementación-openstack.html
- Add lang=es to takeover
- Check Spanish takeover doesn't show unless language is changed to Spanish
Fixes #8315
=> Add lang=es to Spanish takeover

webapp/security/views.py
If same release+package combination is provided twice it might cause a bug. This will prevent it.
=> Fix detele status on bulk upload

static/js/src/navigation.js, templates/download/server/choose.html, templates/download/server/download.html, templates/download/server/step1.html, templates/download/server/step2.html
- Track impressions of new /download/server options
- Option 1: Google Analytics
- Filter location and page (/download/server) on yourself in Google Analytics -> Combo tracker -> Real time
- Navigate through /download/server options, go to "Events (last 30 min)" - to view non-interaction events, such as impressions - ensure "Display option" events are received
- Option 2: Google Analytics Debugger on Chrome
- Install and activate the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics …
=> /download/server Impressions tracking

templates/download/desktop/thank-you.html, tests/test_routes.py, webapp/views.py
- Do not assume the thank-you page will recieve an archtecture. 
- Added a test to ensure this view continues to function. 
- Added a missing closing div to the template
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop/thank-you
- See that you are thanked for your contribution
- Go to /download and ensure both dekstop and server downloads work as expected
- Check the tests pass
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8329
=> Fix desktop contributions

templates/index.html, templates/takeovers/_cassandra-webinar-takeover.html, templates/takeovers/index.html
- Build Cassandra webinar takeover
- Add to `templates/takeovers/index.html`
- Add to `templaltes/index.html`
- Check takeover matches description in [issue](https://github.com/canonical-web-and-design/web-squad/issues/3210#event-3788809503) 
- NOTE: Changed CTA from "Register" to "Register for the webinar", as this was requested in previous webinar takeover PR. 
Fixes [#3210](https://github.com/canonical-web-and-design/web-squad/issues/3210#event-3788809503)
=> Build Cassandra webinar takeover

templates/download/shared/_server_weekly_news.html
Changed the button text to "Download the pro tips" on the /server/download/thankyou modal (https://ubuntu.com/download/server#)
=> Changed the button text to "Download the pro tips"

webapp/app.py, webapp/security/models.py, webapp/security/views.py
Get notice:
`/security/api/notices/<notice_id>`
- returns notice with id `<notice_id>`
- `400` if no notice found with the id
`/security/api/notices`
- accepts two get parameters: `limit`, `offset`
These will paginate the results returned.
Offset defaults to 0.
Limit defaults to 20.
0) Have notices imported
1) Fetch changes
2) Browse to routes and see that you get 200
Fixes #7916
=> Add endpoint to read notices

templates/download/server/arm.html, templates/download/server/choose.html, templates/download/server/provisioning.html, templates/download/server/step1.html, templates/download/server/step2.html
- Improve titles and descriptions on the /download/server section
- Updated the copy docs as well
- See that the /download/server pages have the same meta data (and in the [copy doc](https://docs.google.com/document/d/12kr3JvN3ALMdr5IPOheMwOaf-ygvEulFo5D7x-0ag0k/edit#))
```
{% block title %}Get Ubuntu Server | Download{% endblock %}
{% block meta_description %}Get Ubuntu Server one of three ways; by using Multipass on your desktop, using MAAS to provision machines in your data centre or installing it …
```
=> Improve titles and descriptions on the /download/server section

webapp/security/views.py
- When CVE's data has no published date it errors out. This fixes it.
=> Fix bulk CVE update when published date is None

requirements.txt
Sharpen blog images by applying the `e_sharpen` flag in Cloudinary.
Open in a tab: https://ubuntu.com/blog
Open in a tab: https://ubuntu-com-8353.demos.haus/blog
If you keep switching between the tabs you will see that the demo one has sharper images. Or you can inspect element and see the `e_sharpen` flag on the cloudinary url.
=> Sharpen blog images

templates/takeovers/_fips_certification_cis_compliance.html
- Remove "environments" from subtitle as requested by @Khutch25 
- Check "FIPS certification and CIS compliance with Ubuntu" takeover doesn't have the word environments in the subtitle.
=> Remove environments from takeover

templates/download/cloud/index.html, templates/public-cloud/index.html, templates/shared/_ubuntu_pro_on_public_cloud.html
- Update /download/cloud copy
- Created an include from a strip on /public-cloud and used it on both pages
- Updated logos
- View the site locally in your web browser at: http://0.0.0.0:8001/download/cloud
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit?ts=5f6b774e#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3213
=> Update /download/cloud copy

.env, .github/workflows/cypress.yaml, static/js/src/advantage/contracts-api.js, static/js/src/advantage/error-handler.js, static/js/src/advantage/set-modal-info.js, static/js/src/advantage/tests/error-handler.test.js, static/js/src/advantage/tests/set-modal-info.test.js, static/js/src/ua-payment-modal.js, static/js/src/ua-product-selector.js, static/sass/_pattern_renewal-modal.scss, templates/advantage/_stripe-modal.html, templates/advantage/index.html, templates/advantage/subscribe.html, templates/advantage/table/_contract-name.html, templates/advantage/table/_renewal-actions.html, tests/cassettes/TestRoutes.test_advantage.yaml, webapp/advantage.py, webapp/app.py, webapp/security/alembic/versions/10c24cb270ff_add_cve_patch_column.py, webapp/security/models.py, webapp/security/schemas.py, webapp/views.py
Implemented a VAT/purchase preview endpoint that returns a VAT total (when applicable) and actual total and presents it to the user during the payment modal journey.
- Whilst logged in, make a product selection, add it to the cart, and click "Buy Now" and QA the following two flows:
- In the payment modal, select United Kingdom (VAT is always applicable)
- After a short wait, VAT and total should appear below the form
- Change the country to United States (VAT is not applicable)
- After a short …
=> Advantage shop VAT

webapp/security/views.py
Change the notice import to only import unique cve ids.
This way if a notice has the same cve id duplicated it will only import
it one time.
Fixes #7946
=> Change the notice import

templates/download/kvm.html
The Install Ubuntu Core on KVM guide does not work with UC20 (it's a more process complex). This is a small fix to make it explicit that these instructions will install UC18, rather than _any_ Ubuntu Core release, which still works and is still obviously supported.
- updated intro sentence
- updated image download step
=> Ubuntu Core on KVM guide: tweaks to make it clear we're installing UC18

templates/advantage/table/_contract-name.html
- Added a check to make sure the `daysTillExpiry` property exists on a contract before deciding whether to apply a "new" label.
- Visit /advantage, login with SSO, and see that you can see a list of contracts, rather than a template error
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8380
=> Fix expiry date/new label bug on /advantage

webapp/security/views.py
Change USN search by detail to also find results if `notice.id` or `notice.cves.id` matches the search criteria.
- have cves and notices imported
- fetch changes
- launch website `dotrun`
- browse to `/security/notices` try to search by cve.id, notice.id; It will work.
Fixes #7947
=> Update USN search by details

templates/takeovers/_security-webinar-series.html
- Wrong URL on security series CTA
- Security series takeover link works
=> Update security series takeover CTA URL

templates/engage/index.html, templates/engage/trilio-backup-recovery.md, templates/index.html, templates/takeovers/_trilio-backup-recovery.html, templates/takeovers/index.html
- Build engage page and add to `/engage.index.html`
- Build takeover and add to `/index.html` and `/takeovers/index.html`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/trilio-backup-recovery and http://0.0.0.0:8001/takeovers
- Check the pages match the [copy doc](https://docs.google.com/document/d/11iCopqnoLv_jBuOncrELAS7uo1DiKWggAEe-lCubbeM/edit?ts=5f55f52f), [brief](https://docs.google.com/spreadsheets/d/1e10lwtgEgvUZ7TeVaM8sYmqBtMwu1p5Y1iwRi3Ukz_g/edit#gid=1271849439) and [design](https://github.com/canonical-web-and-design/web-squad/issues/3225)
- Test …
=> Trilio webinar - takeover and engage page

templates/training/contact-us.html, templates/training/index.html, templates/training/thank-you.html
- Add Kubeflow section to `/training` with link to PDF
- Change 'Train with Ubuntu' illustration to match copy doc
- Check page matches [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit?ts=5f6c7e7a#heading=h.7gh8c2ema0rv) and check PDF/contact us links. 
Fixes 
[#3220](https://github.com/canonical-web-and-design/web-squad/issues/3220)
[#3221](https://github.com/canonical-web-and-design/web-squad/issues/3221) …
=> Copy update Kubeflow training

templates/security/certifications.html
- Replace with transparent logos
- See the CSEC and CIS logos are now transparent
Fixes #8385
=> Replace with transparent logos on /security/certifications

templates/kubernetes/docs/1.19/components.md, templates/kubernetes/docs/supported-versions.md
- Fix broken link
- update bundle rev number
Fixes #
=> K8sdocs 1.19 fixes

navigation.yaml
- The legal team asked that we hide "Survey" in secondary nav from /legal/data-privacy
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy
- See that 'Survey' has been hidden
[before]
[after]
=> Hide "Survey" in secondary nav from /legal/data-privacy

static/js/src/ua-product-selector.js, templates/advantage/subscribe.html
- Made it impossible to add fractional quantities of a product
- Log in with SSO
- Start the product selection, when you get to the quantity input, try to type a number with a decimal point i.e 0.2, 1.7 etc etc etc
- See that the decimal point is automatically removed
Fixes #8397
=> UA shop: prevent decimal place being added to quantity input

templates/kubeflow/what-is-kubeflow.html
- Rebuild `kubeflow/what-is-kubeflow` page
**Known differences**
- Centre aligned pachyderm logo following Vanilla convention. (Confirmed this is ok with @meralonso )
- _Kubeflow operators_ and _Visit Charmed-Kubeflow.io_ links missing as site isn't live yet
- Check page matches [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit#) and [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/8261)
- Check all the links link to the …
=> Rebuild what is kubeflow

templates/security-series/index.html
- Update navigation of /security-series to make it clearer how the series is organised
- View the site locally in your web browser at: http://0.0.0.0:8001/security-series
- Compare to the [copy doc](https://docs.google.com/document/d/1A7JDBRZ_tuEvteE1pVA9_rV-oJUq1_DuT7GmO6zVCXM/edit#)
=> Update navigation of /security-series

templates/kubeflow/what-is-kubeflow.html
- Added links from `/kubeflow/what-is-kubeflow` to live http://charmed-kubeflow.io
- Check _Kubeflow operators_ and _Visit Charmed-kubeflow.io_ links redirect to  http://charmed-kubeflow.io as seen in [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit#)
[#8262 ](https://github.com/canonical-web-and-design/ubuntu.com/issues/8262)
=> Add charmed-kubeflow links

requirements.txt
Fix blog article thumbnails and image pixelation.
https://ubuntu.com/blog
Check the thumbnails, they will have slightly different sizes.
https://ubuntu-com-8409.demos.haus/blog
Check the thumbnails, you will notice they all have the same size(330x185) and cover the whole width of the block.
https://ubuntu.com
Check Spotify logo. It should look good.
Part of: https://github.com/canonical-web-and-design/canonicalwebteam.blog/pull/153
=> Update blog to 6.3.1 and image-template to 1.3.1

webapp/app.py
Create authenticated session for authenticated endpoints (to avoid sharing pre set headers in the session)
- visit some pages (engage pages, blog)
=> Create authenticated session for authenticated endpoints

appliances.yaml, templates/appliance/lxd/_next-steps.html, templates/appliance/portfolio.html, templates/appliance/shared/_featured_appliances.html, templates/download/index.html, webapp/app.py, webapp/views.py
- Add LXD to appliance homepage and portfolio
- Add a tutorial to next setup
- Made the portfolio page build from the application.yaml
- Fixed side of the mascot on /download
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance, http://0.0.0.0:8001/appliance/lxd/intel-nuc and http://0.0.0.0:8001/appliance/portfolio 
- See that LXD replaces Mosquitto on the /appliance page
- See that LXD is on the /appliance/portfolio page
- See that the 'Getting started' section text is updated per the [copy doc](https://docs.google.com/document/d/1B39LSVUaj9DY_W-v2v76DyNFKyzXZn …
=> Add LXD to appliance homepage and portfolio

webapp/security/views.py
- Make search by description check for both `CVE.description` and `CVE.ubuntu_description`.
- Go to https://ubuntu.com/security/cve?q=was+discovered+that+jsoup+improperly&package=&priority=&version=&status=
You will see no CVE listed
- Have CVEs imported
- `dotrun` and go to http://0.0.0.0:8001/security/cve?q=was+discovered+that+jsoup+improperly&package=&priority=&version=&status=
You will see one CVE listed: CVE-2015-6748 
Fixes #8419
=> CVE search by description update

webapp/security/views.py
- Make cve table releases be ordered in ascending order.
- have the data imported in the databse
- fetch changes
- go to `/security/cve`
- look at the table head. The releases will be ordered in ascending order.
Fixes #8424
=> Reverse order of release

templates/training/index.html
- Add covid notice to /training page
- Compare to the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit?ts=5f7ffa38#)
=> Add covid notice to /training page

static/js/src/cve/cve.js, static/sass/_pattern_cve.scss, templates/security/cve/_cve-table.html, templates/security/cve/index.html
Add tool-tip to give details on CVE status and priority.
We have no texts for the following statuses:
needs triage, needed, deferred, ignored, released, DNE
Right now cells with those statuses will show no status explanation in the tool-tip.
`Not vulnerable` and `Does not exist` do not show any priority explanation in the tool-tip because it does not show a priority icon in the cell.
`Does not exist` does not display the information icon since it's missing status explanation and has no priority icon
- Have CVEs imported
- `dotrun`
- Browse to `/security/cve` hover over statuses
Fixes #7763
=> Add information tool-tip for CVE statuses

templates/kubernetes/docs/1.19/components.md
Added a single blank line (the markdown processor is very particular)
- Check images  on 1.19/components are rendered as a list
Fixes #8450
=> K8sDocs: fix rendering of image list

templates/kubernetes/docs/1.19/release-notes.md, templates/kubernetes/docs/release-notes.md
- removed TODO from release notes
=> K8sDocs: Remove todo, which has been done

templates/blog/product-cards/_kubeflow_jaas-bundle.html, templates/kubeflow/index.html
- Changed secondary CTA on /kubeflow
- Changed a blog product card
- Go to any ["kubefllow" tagged blog post](https://ubuntu-com-8446.demos.haus/blog/data-science-workflows-on-kubernetes-with-kubeflow-pipelines-part-2), refresh until you see the "Run Kubeflow anywhere, easily" product card next to the post
- Ensure the [/kubeflow](https://ubuntu-com-8446.demos.haus/kubeflow) page matches the copy doc
=> Add charmed-kubeflow links throughout the Kubeflow journey

templates/security-series/index.html
- Updated the BrightTalk webinar link for the Best practices for securing open source webinar to this link: https://www.brighttalk.com/webcast/6793/445555
- Removed the '|' and add a comma and a space between CISO, CTO in the 'Team based webinars' section
- Replaced the AppArmor icon with the multi-cloud security icon for the 'Securing open source across multi-cloud environments' webinar in the 'IoT & Device security' section
- Check the changes against the copy doc
=> Security series updates

templates/engage/shared/_de_thank-you.html, templates/engage/shared/_fr_thank-you.html, templates/engage/shared/_pt_thank-you.html
Fix the engage page thank you pages
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/de/openstack-made-easy/thank-you
- See that page does not 500
- Go to https://ubuntu.com/engage/de/openstack-made-easy/thank-you and see it returns a 500
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8456
=> Fix the engage page thank you pages

templates/base_index.html
When randomly browsing the [W3C validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fubuntu.com%2F), I noticed there were a few typos on the Ubuntu website. This PR fixes the most obvious `clas` typo, and based on other image rows, I removed the redundant div.
WDYT?
=> Remove typos from the base index template

templates/legal/terms-and-policies/index.html, templates/legal/terms-and-policies/snap-store-terms.html
- Add Snap Store terms of service to `legal/terms-and-policies/snap-store-terms`
- Add blurb box on `/legal/terms-and-policies` 
**Known difference**:
- Privacy notice link in _13. Personal data_ links to privacy page which has not yet been updated.
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies/snap-store-terms and check against [copy doc](https://docs.google.com/document/d/1liRDdiO4JIIV43hqNckIk0ONGYW5MeaLuW-4U2HZky4/edit#)
- Check new Snap Store blurb box on http://0.0.0.0:8001/legal/terms-and-policies 
Fixes …
=> Add Snap Store terms of service

templates/openstack/install.html
- Update text on /openstack/install
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)
Fixes #8479
=> Update text on /openstack/install

templates/appliance/shared/_base_appliance_index.html
- Using pixels instead of percents seems to fix the icons from being clipped on /applaince/<app> pages
- View the site locally in your web browser at: http://0.0.0.0:8001/appliance/adguard
- See that the multipass, nuc and pi icons look ok
Fixes #8461
=> Use px instead of pct for icon sizes

templates/shared/forms/interactive/internet-of-things.html
- Replace work email with email on iot and /core modal contact us forms
- View the site locally in your web browser at: http://0.0.0.0:8001/core#get-in-touch and https://0.0.0.0:8001/internet-of-things#get-in-touch
- See that it says 'Email' not 'Work email' on the second page and compare and accept the comment in the [copy doc](https://docs.google.com/document/d/1t8k61sE5AopyvsXuMoyNDAghdnrjH4TlRdDGT4tqAes/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3274
=> Replace work email with email on iot and /core modal contact us forms

templates/internet-of-things/appstore.html
- Add video to hero on `/internet-of-things/appstore`
- View the site locally in your web browser at: http://0.0.0.0:8001//internet-of-things/appstore
- Check video added from [copy doc](https://docs.google.com/document/d/1CKwmPDDtXOIgw-jSZFwzP-qLMc_rS_dUACpHQXlg0fA/edit#heading=h.az7bmia5r3fh) and working correctly - hero section
Fixes [#3179](https://github.com/canonical-web-and-design/web-squad/issues/3179)
=> Add video to hero on IoT/appstore

templates/download/desktop/thank-you.html
- Make going to /download/desktop/thank-you without a download show contribution form
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop/thank-you
- See that if you go to the page without a download, it offers the chance to contribute
Fixes #8478
=> On /download/desktop/thank-you show contribution form if no download

templates/advantage/_stripe-modal.html
- Changed the reference to “invoice” to “receipt” in the payment dialog.
- Buy or renew a subscription
- Check that the payment dialog says “Email my receipt to:”
Fixes #8507.
=> “invoice” > “receipt”

templates/advantage/subscribe/index.html
- Set maximum UA purchase to 1000 machines.
- Try to buy for more than 1000 machines
Fixes #8393.
=> Maximum 1000 machines

releases.yaml, templates/download/alternative-downloads.html, templates/download/server/choose.html, templates/shared/contextual_footers/_download_helping_hands.html, templates/shared/contextual_footers/_download_server_guide.html, templates/shared/contextual_footers/_download_server_installation.html
- Update releases.yaml to include 20.10
- Added latest release block to /download/server
- Updated the Alternate blocks to make sense
- Updated the contextual footer text
- Compare to the [server copy doc](https://docs.google.com/document/d/12kr3JvN3ALMdr5IPOheMwOaf-ygvEulFo5D7x-0ag0k/edit)
Fixes #8503
=> Update releases.yaml and /download/server to include 20.10

templates/engage/base.html
- Change logic and correct CTA to accomodate for youtube webinars
- Check the demo for the /engage/raspberry-pi-livestream and make sure the Youtube video appears.
- Check that the 2 CTA buttons show up
- You can also browse other engage pages see if there is anything wrong.
=> Change logic and correct CTA for youtube webinars

templates/index.html, templates/takeovers/_2010-takeover.html
- The 20.10 takeover
- You can look at the [brief, but it is messy](https://docs.google.com/spreadsheets/d/1ad28yxJA7Mfc83kynYPC--Uo8WcJ5peN63D2F2Yntv0/edit?ts=5f85c02a#gid=2113339190)
Fixes #8471
=> 20.10 takeover

scripts/create-usns.py, templates/list_endpoints.py, webapp/views.py
Download mirrors are broken because the path to the mirrors file is incorrect.
This bug was introduced in https://github.com/canonical-web-and-design/ubuntu.com/pull/8073, and brought to our attention in https://rt.ubuntu.com/Ticket/Display.html?id=34579.
On the demo, go to /download/desktop, download a version of Ubuntu, see that you download from a mirror rather than releases.ubuntu.com.
=> Fix path for download mirror list

templates/download/raspberry-pi/index.html, templates/download/raspberry-pi/thank-you.html
- Update /download/raspberry-pi for 20.10
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#)
Fixes #8475
=> Update /download/raspberry-pi for 20.10

releases.yaml, templates/desktop/developers.html
- Add what's new in 20.10
- Please double check the Groovy Gorilla in the ymal file
- Browse to: https://ubuntu-com-8544.demos.haus/desktop/developers
- You will see the new "What's new in 20.10" section
- Please confirm the url at the bottom of the section is correct
Fixes #8502
=> Add 20.10 what's new on /desktop/developers

navigation.yaml, templates/raspberry-pi/_base_raspberry-pi.html, templates/raspberry-pi/index.html
- Build `/raspberry-pi` page
**Known difference**:
- Waiting on link for "Follow the tutorial"
- View the site locally in your web browser at: http://0.0.0.0:8001/raspberry-pi
- Check page against [copy doc](https://docs.google.com/document/d/1XS8KyKQnQdgY9NJfxHMs_9ql4sPOTRj0yweunMPoOdM/edit#heading=h.alvyav8qzr5r)
Fixes #8472
=> Build Raspberry Pi page

templates/download/index.html
- Add mascots to /download
- See the mascot
Fixes #8505
=> Add mascots to /download

templates/raspberry-pi/index.html, templates/takeovers/_2010-takeover.html
- Update link on /raspberry-pi to livestream
- Add the download button
- Update CTA on homepage takeover
- View the site locally in your web browser at: http://0.0.0.0:8001/raspberry-pi
- Compare to the [copy doc](https://docs.google.com/document/d/1XS8KyKQnQdgY9NJfxHMs_9ql4sPOTRj0yweunMPoOdM/edit#)
Fixes #8562
=> Update link on /raspberry-pi to livestream

templates/download/index.html
- Add webinar notice on /download
- See and test the link in the webinar
=> Add webinar notice on /download

templates/download/shared/_everywhere.html
- Add rasp-pi to _everywhere partial only seen currently on /download/desktop
-See that the text matches [this sheet](https://docs.google.com/spreadsheets/d/18mzFvEOSHr_2lluz14lbmEr-if6b4mrEUz1oI75qfOY/edit#gid=2034135081)
=> Add rasp-pi to /download/desktop

templates/blog/product-cards.html, templates/blog/product-cards/_raspberry-pi_2010-livestream.html
- Added the Rapsberry Pi livestream blog product card
=> Added the Rapsberry Pi livestream blog product card

templates/download/raspberry-pi/index.html
- Remove pi desktop 32bit from /download/raspberry-pi
- Updated [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#)
- There is no 32-bit version of the desktop
=> Remove pi desktop 32bit from /download/raspberry-pi

templates/shared/pricing/_openstack-kubernetes-lma.html
- Managed OpenStack on bare metal and Combination price changed
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/infra#managed
- Compare the managed pricing to the [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
=> Update managed pricing on /pricing/infra

static/sass/_pattern_renewal-modal.scss
- Layed the three modal sections (header, main and footer) using flex and removed the percentage height of the viewport
- Make a selection and Add it to the basket
- Click Buy now
- Check the modal on all screen sizes works as expected and only has a single scrollbar in the main content.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8248
=> Remove the double scroll bar on the purchase modal

templates/raspberry-pi/desktop.html
- Fix text for download link on Raspberry Pi for Desktop page.
- Go to: https://ubuntu-com-8569.demos.haus/raspberry-pi/desktop
- Look at the text of the button. It should be: Download Raspberry Pi Ubuntu Desktop
- Just like it says in the doc: 
https://docs.google.com/document/d/14WEwUuwaKGMaR5FlsJJZttkAn0iCqUuXhRQLMWurpQ4/edit#
=> Fix download text for desktop Raspberry Pi

templates/base_index.html, templates/takeovers/_2010-takeover.html
- Updating the 20.10 takeover and adding notice
- pi link goes to livestream engage page
- notice added to 20.10 webinar
- See that the links work and looks ok (note engage page doesn't work locally)
=> Updating the 20.10 takeover and adding notice

releases.yaml
- Update checksums for 20.10
- See that they appear in the verify boxes of the download thank you pages (test desktop 20.10, server 20.10, raspberry-pi desktop  20.10, raspberry-pi server  20.10 pi 2 and pi 4)
Fixes #8535
=> Update checksums for 20.10

templates/base_index.html, templates/download/index.html, templates/download/server/choose.html
- Add &rsquo; to homepage and /download on the notice
- and http://0.0.0.0:8001/download
- see that `s/'/&rsquo;/`
=> Add &rsquo; to homepage and /download

templates/legal/ubuntu-advantage-service-description/index.md
- Update meta description on /uasd page
- View the site locally in your web browser at: http://0.0.0.0:8001/uasd
- Look at the source of the page to see the description now reads "Detailed description and explanation of the benefits and services you receive as an Ubuntu Advantage customer."
Fixes #8355
=> Update meta description on /uasd page

static/js/src/contextual-menu.js, static/js/src/cve/cve.js
- Pass listened to element instead of target for contextual menu interaction
- Upgrade the keyboard event handling to the modern approach
- Lint the `cve.js` file
- Login and scroll to the "Your free personal subscription" strip
- Click the "Get your free token" contextual menu button and see it works as expected.
- Now click directly on the chevron icon (which on live errors) and see it works the same
- Check other chevrons across the table continue to work as expected
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8524
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8383
=> Advantage shop free token menu

templates/index.html, templates/takeovers/_security-cloud-computing.html, templates/takeovers/index.html
- Build takeover - Security, cloud native & confidential computing
- Add to `/index.html` and `/takeovers/index.html`
- Check takeover including CTA 
Fixes [#3362](https://github.com/canonical-web-and-design/web-squad/issues/3362)
=> Build takeover - cloud native and computing

templates/takeovers/_2010-takeover.html
- The live chat isn't live, changed the text to 'Watch the Raspberry Pi Ubuntu Desktop intro video ›'
- [See that the homepage takevoer now reads 'Watch the Raspberry Pi Ubuntu Desktop intro video ›'
Fixes #8595
=> Update takeover cta text

static/js/src/advantage/set-modal-info.js, static/js/src/ua-payment-modal.js
- Changed “Subtotal:” to “For this period:” when a purchase is prorated.
- With at least one existing subscription, select another and choose “Buy now”
- I have not tested this, and there are probably better ways to implement it.
- It seems brittle to me that the way to select the label is with the `u-text-light` class. I was expecting it to be something more semantic, like a `<th>`.
Addresses #8392
=> Use “For this period:” for subtotal when purchase is prorated

templates/engage/base.html
- Remove hardcoded youtube id with variable for engage pages
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/raspberry-pi-livestream
- See that the video id at the bottom of the page is `0pT4-RcTERU`
=> Remove hardcoded youtube id with variable for engage pages

templates/advantage/_stripe-modal.html
Unstack the purchase button on small screens
= Login
- Add a product to the cart
- Click the Buy now button
- Check the Cancel and Continue buttons in the modal footer look ok
- Shrink the screen and check grid alignment works
- Continue through the process and see it all works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8516
=> Unstack the purchase button on small screens

templates/index.html, templates/takeovers/_manage-risk-service-providers.html, templates/takeovers/index.html
- Build takeover
- Add to `index.html`
- Add to `takeovers/index.html`
- Check takeover and CTA link 
Fixes [#3364](https://github.com/canonical-web-and-design/web-squad/issues/3364)
=> Build takeover for manage risk with service providers

templates/base_index.html, templates/download/index.html
- Add engage page using [discourse](https://discourse.ubuntu.com/t/ubuntu-20-10-what-s-new/19050)
- Add to meta data mapping [table](https://discourse.ubuntu.com/t/about-the-engage-pages-category/17229)
- Update webinar link to new engage page at `/engage/ubuntu-20.10`
- Check link 'Find out what's new in Ubuntu 20.10 in our webinar' is correct
- Check engage page at [ubuntu.com/engage/ubuntu-20.10](https://ubuntu.com/engage/ubuntu-20.10) against [brief
](https://docs.google.com/spreadsheets/d/1snpchFhM7eA8ou-rIHuLWAVwRxzNIKupZ0lZ2rzxqbM/edit#gid=1271849439)
Fixes [#3381](https://github.com/canonical-web-and-design/web-squad/issues/ …
=> Ubuntu 20.10 engage page 

templates/takeovers/_2010-takeover.html
- Changed the secondary CTA to Learn more about Ubuntu Desktop on Raspberry Pi and linking to /raspberry-pi
=> Change the secondary CTA on 20.10 takeover

templates/engage/base.html
- For engage pages, you had to have a blank form-id to not present a form. It would print a broken form if you skipped the value, so I added a check for the existence as well.
- See that the form works for a webinar and for a whitepaper, see that the logic makes sense
Would have fixed #8607
=> Allow missing form-id in engage pages

static/js/src/advantage/contracts-api.js, static/js/src/ua-payment-modal.js, static/js/src/ua-product-selector.js, static/sass/_pattern_renewal-modal.scss, templates/advantage/_stripe-modal.html, templates/advantage/subscribe/index.html, tests/test_advantage.py, webapp/advantage.py, webapp/app.py, webapp/views.py
- When purchasing without an account, allow specifying an account/company name.
- When already having an account, prevent the user from providing a different one.
- Implemented an API client method for getting an account for purchasing if it exists, without creating it.
- Improved test coverage around UA API client.
- Purchase as a guest, as a new user (with no UA accounts) and as an existing UA user.
- When not having an account, you should be able to set an account name.
- When returning later, the account name should be there.
- Now try a renewal, just to check that the stripe form is still working for that use case as well.
- Bonus: when purchasing again in the same day, the price is not prorated by the second anymore (not a fix in this branch, but nice to double check that's …
=> advantage guest purchases: provide account/comany name

static/js/src/ua-payment-modal.js, templates/advantage/_stripe-modal.html
For logged in users, we can validate any VAT number they input at the same time we make the call to get their VAT total (for guest users, this validation can only occur when they've clicked "Continue" and their account has been created).
- Make sure you're logged in
- Select a product, add it to your cart, and click "Buy" to launch the payment modal
- Fill out the card and address details, and select United Kingdom as your country
- Type some nonsense into the VAT number field
- See that, after a …
=> Validate VAT number on input change for logged in users

templates/advantage/_stripe-modal.html, templates/advantage/index.html, templates/advantage/subscribe/index.html
Add "We’ll also send setup instructions to this address." below the email field when making a purchase (but not when making a renewal).
- Select a product, add it to cart and click "Buy Now"
- You should see the line of text below the email field.
Fixes #8536
=> UA: inform the user how they'll receive setup instructions

templates/download/server/choose.html
Remove LTS from the latest server download button
- Check the button "Download Ubuntu Server 20.10" does not have LTS in it
=> Remove LTS from the latest server download button

templates/blog/product-cards/_raspberry-pi_2010-livestream.html
- The youtu.be url doesn't seem to work, reverting the embed form
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/build-a-raspberry-pi-desktop-with-an-ubuntu-heart
- See that the video in the side bar works
=> Add embed youtube link as the other form has a x-origin error

templates/managed/cassandra.html
- Change header image on /managed/cassandra
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/cassandra
- Check new header image is cassandra eye logo from issue
Fixes [#8260](https://github.com/canonical-web-and-design/ubuntu.com/issues/8620)
=> Change header image cassandra page

templates/security/disclosure-policy.html, templates/security/index.html
- Build new disclosure policy page at `/security/disclosure-policy`
- Add section to link to it from /security
- View the site locally in your web browser at: http://0.0.0.0:8001/security/disclosure-policy
- Check against [copy doc](https://docs.google.com/document/d/1WdamniXOHemuPzl6vESYD9StPgh4-PepbqdVHYrzbuI/edit#)
- Check new section on /security against [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit)
Fixes #8615
=> Add /security/disclosure-policy page

templates/raspberry-pi/index.html
- Update cta on /raspberry-pi
- View the site locally in your web browser at: http://0.0.0.0:8001/raspberry-pi
- Compare to and resolve comment on the [copy doc](https://docs.google.com/document/d/1XS8KyKQnQdgY9NJfxHMs_9ql4sPOTRj0yweunMPoOdM/edit?ts=5f980681#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3384
=> Update cta on /raspberry-pi

templates/download/raspberry-pi/index.html
- Add updated tutorials to /download/raspberry-pi page
- Compare to the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit?ts=5f9941c0)
Fixes #8617
=> Add updated tutorials to /download/raspberry-pi page

webapp/views.py
See #8626 
This will handle invalid renewal state (or invalid parsing) gracefully and send an exception sentry instead of displaying a 500 page on `/advantage` in this case.
=> Don't 500 on invalid renewal

package.json, webpack.config.js, yarn.lock
- Removes terser
- See that the js builds fine and the source maps
=> Remove terser

navigation.yaml, package.json, yarn.lock
Added "Your subscriptions", linking to /advantage, to /support subnav
-See that there is a link to "Your subscriptions" in the subnav
- Follow the link and check you arrive at /advantage, and the subnav is still present
- On any page, see that "Your subscriptions" is present in the "Support" section of the footer navigation
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8600
=> add /advantage link to /support subnav

static/js/src/contributions.js
- Make contributions GAevent
- To clean up the e-commerce space for the Ubuntu Advantage shop, I am moving the contribution data to normal ga events
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop/thank-you
- See that it pushes GA events instead of e-commerce events
=> Make contributions GAevent

templates/advantage/_table.html, templates/advantage/index.html
- Changed positive “Purchase a subscription”, at the bottom of /advantage, to neutral “Buy a subscription”.
- Added another “Buy a subscription” button alongside “Sign in”, fixing #8634.
- Removed unnecessary margin fiddling.
[Copy doc updated](https://docs.google.com/document/d/1K65n3NpZCh7EWDXKLhG31seGJ2jKbW6lqw3BwV2mlnU/edit#heading=h.nleu1cdig11l).
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage while signed out
Fixes #8634.
=> More prominent “Buy a subscription”

templates/takeovers/_security-cloud-computing.html
- Change CTA from 'Register for the webinar" to "Watch the webinar" on security cloud computing takeover as requested in this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/8579)
- Check 'Security, cloud native & confidential computing' takeover has correct CTA 
Requested in this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/8579#issuecomment-719477746)
=> Change CTA on takeover

templates/takeovers/_template.html, templates/takeovers/index.html, webapp/app.py
Show information about active takeovers on the takeover index page
- See that you see the active counts at the top and an active indicator on the takeovers
=> Show information about active takeovers on the takeover index page

static/js/src/advantage/ecom-analytics-events.js, static/js/src/ua-payment-modal.js, static/js/src/ua-product-selector.js
Added ecom analytics events for:
- Adding/removing items from the cart
- Proceeding to checkout
- Adding payment details
- Confirming purchase
- A successful purchase
- Trigger the events by:
- Adding a product
- Removing a product
- Adding another product
- Proceeding to checkout
- Filling out payment details and clicking "Continue"
- card info: 4242 4242 4242 4242, 04/24, 242, 42424
- Clicking "Pay" on the second screen of the payment modal
- Verify that the events were sent to GA/GTM
Fixes …
=> Add ecom analytics to UA shop

package.json, yarn.lock
- Pin vanilla to 2.18.0 to not have a navigation alignment regressoin
- See that the logo aligns with the global nav
=> Pin vanilla to 2.18.0

templates/download/raspberry-pi/index.html
- Add pi 400 to /download/raspberry-pi
- Compare to the [copy doc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#)
=> Add pi 400 to /download/raspberry-pi

templates/kubeflow/what-is-kubeflow.html
- Increase logo size on `/kubeflow/what-is-kubeflow`
- Check logo sizes in 'contributors to kubeflow' section and 'What's inside Kubeflow?' section fix comment in [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit#)
Fixes [#3390](https://github.com/canonical-web-and-design/web-squad/issues/3390)
=> Increase logo size on /what-is-kubeflow

templates/index.html, templates/takeovers/es/_redhat-openstack-comparacion-manual.html, templates/takeovers/index.html
- Build takeover and add to `/index.html` and `/takeovers/index.html`
- Build [engage page](https://ubuntu.com/engage/es/redhat-openstack-comparacion-manual) on discourse
- Add engage page to index
- Check first Spanish takeover is not visible when language is English. Change browser language to Spanish and check takeover is visible. 
- Check [engage page](https://ubuntu.com/engage/es/redhat-openstack-comparacion-manual) and takeover against [brief](https://docs.google.com/spreadsheets/d/1oswntN5H7Xf9vOAzHcX1waxwSxTzeHhWQUXOcqkivdg/edit#gid=1271849439)
- Test the engage page on http://debug.iframely.com/ and …
=> Redhat takeover and engage page 

templates/blog/product-cards/_kubeflow_what-is-kubeflow.html
- Update the What is Kubeflow product card link, now that the /what-is-kubeflow page has been refreshed.
- Go to any Kubeflow blog post, ensure the "What is Kubeflow" card on the right pane is pointing at the expected page
=> Change "What is Kubeflow" blog product card link to /kubeflow/what-is-kubeflow

templates/index.html, templates/takeovers/_template.html, templates/takeovers/index.html
- Fix wrong parameter name and remove unused locale
- Check that the Spanish takeovers are not showing when your browser has English language
=> Fix wrong parameter name and remove unused locale

templates/internet-of-things/digital-signage.html
Add smartstart link to digital-signage
- Check there is a button to smartstart in the intro as of the [copydoc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8667
=> Add smartstart link to digital-signage

templates/internet-of-things/index.html
Add smartstart link to internet-of-things
- Check it matched the [copy docs](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8663
=> Add smartstart link to internet-of-things

templates/templates/navigation-enterprise-h.html
- Click the enterprise menu and see the smartstart link is there.
- Matches the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8661
=> Add smartstart to the enterprise menu

templates/advantage/subscribe/index.html, webapp/views.py
Noticed while doing some QA after a while of not having looked at the demo for a period of time, in which my macaroon auth seemed to have expired.
In /subscribe/index.html, we write the value of `account.id` and `account.name` to variables we can use in js. If a user is not logged in, we set `account` to `None`, so `id` and `name` return false/an empty string. 
If a user _is_ logged in, those values can be set as expected, unless their macaroon has expired. Line [724](https://github.com/canonical-web-and-design/ubuntu.com/blob/advantage-shop/webapp/views.py#L724) of views.py catches the error that this raises, and renders the /subscribe/index.html template, but in this instance `account` is never set (even as `None`), so trying to access `id` and `name` raises [an …
=> UA shop: account check

konf/site.yaml
We keep making authenticated API calls even if the endpoints are public
This might cause an outage due to the limit of requests from discourse
- Make sure site deploys well to demo
=> Remove secrets for discourse

templates/engage/base.html
- Fix copy doc link
- Go to inspector check that copy doc appears
Fixes #8671
=> Fix copy doc link

static/js/src/renewal-modal.js
Sentry flagged an [error](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/11588/events/477753/) that the CS team and I investigated, which revealed two small bugs, one for each team. 
In our case, on a payment attempt after a failed payment, we were retrieving the last invoice in an array of invoices attached to the renewal. In fact, the invoices are ordered by most recently updated, so we need to retrieve the first invoice in the array.
On the CS team side, the bug is that when one invoice is updated, all invoices are updated with the same date. It may take some time for the API to be updated with their fix, otherwise we could just loop over those dates and find the most recent, but they've [guaranteed](https://github.com/CanonicalLtd/ua-contracts/pull/1407/files#diff-4ce018d5 …
=> get first invoice in renewal invoice array, not the last

templates/advantage/index.html, templates/appliance/index.html, templates/base_index.html, templates/download/desktop/thank-you.html, templates/engage/shared/_de_thank-you.html, templates/engage/shared/_es_thank-you.html, templates/engage/shared/_fr_thank-you.html, templates/engage/shared/_it_thank-you.html, templates/engage/shared/_pt_thank-you.html, templates/engage/thank-you.html, templates/server/hyperscale.html, tests/cassettes/TestRoutes.test_blog.yaml
- Fix engage thank-you pages and `<space>&nbsp;`
- View the site locally in your web browser at: http://0.0.0.0:8001/engage/es/kubernetes-despliegue-empresa-manual/thank-you and http://0.0.0.0:8001/engage/pt/vmware-para-o-openstack/thank-you
- See that the a accute (á) works and 'Whitepaper' are capitalised
Fixes #8659
see a acute
see capitalised whitepaper
=> Fix engage thank-you pages and <space>&nbsp;

.github/workflows/pr.yaml, webapp/app.py
- Cleanup leftovers of authentication
- Remove unnecessary files that came from authentication
- Check that everything works e.g. `/engage`, `/takeovers`, `/advantage` anything that comes to your mind that may affect sessions
Fixes #8664
=> Authentication clean-up

navigation.yaml, templates/templates/footer.html, templates/templates/navigation-enterprise-h.html
- Add ceph and smartstart to footer
- Add ceph/docs to secondary
- Added ubuntu pro, security and hardware certification to the #enterprise menu
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph/docs
- See that ceph and smartstart are in the footer
- See that 'Docs' is in the ceph secondary nav
Fixes #8669
[secondary nav]
[footer]
[enterprise menu]
=> Add ceph and smartstart to footer

templates/base_index.html
- Update GPU enablement link on homepage
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit?ts=5fa543b9#)
Fixes #8689
=> Update GPU enablement link on homepage

templates/aws/index.html
- Changed the copy on the AWS page according to the comments on the copy doc
Fixes #8695
My first PR 🥳
=> Change copy on AWS page

konf/site.yaml
Set up the ubuntu.com ingress to listen for buy.ubuntu.com.
This domain will be pointed at the ubuntu.com cluster once
https://portal.admin.canonical.com/C128440
is completed, so this is ready for when that happens.
Visitors coming from buy.ubuntu.com will be redirected to
/advantage.
Not sure how to QA. You could do it using microk8s, but I can't remember exactly how the tooling for this works right now.
=> Redirect buy.ubuntu.com to /advantage

navigation.yaml, templates/aws/outposts.html
- Build `aws/outposts`
- View the site locally in your web browser at: http://0.0.0.0:8001/aws/outposts
- Check page matches [copy doc](https://docs.google.com/document/d/1aXtrGHw7AcZ_qrov3kJahRtgsmbNx7eH5aWFlIySpfE/edit#), and follows the design of [ubuntu.com/aws](https://ubuntu.com/aws)
- Banner image design [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/8704#issuecomment-724621254)
Fixes #8705
=> Build /aws/outposts page

static/js/src/ua-payment-modal.js, templates/advantage/_stripe-modal.html, webapp/views.py
Added a marketo form to the payment modal, that triggers on successful payment.
- Select a product, add it to cart, checkout and use these card details with any address:
- 4242 4242 4242 4242, expiry: 04/24, CVC: 242, ZIP: 42424
- Open the network tab in dev tools
- Click "Continue", then check the Ts & Cs box, then click "Pay"
- In the network tab, you should see a post request to "https://app-sjg.marketo.com/index.php/leadCapture/save2"
- for Marketo gurus: verify that the form is sending the …
=> UA shop: add marketo form

navigation.yaml
- Remove TCO calculator from /kubernetes secondary nav
- Compare against [live site](https://ubuntu.com/kubernetes) and check TCO calculator is no longer visible on secondary nav
Fixes [#3439](https://github.com/canonical-web-and-design/web-squad/issues/3439)
=> Remove TCO calculator from /kubernetes secondary nav

templates/internet-of-things/digital-signage.html
- Copy update on `/internet-of-things/digital-signage`
- Check page against [copy doc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit?ts=5fa2a0a6#)
Fixes [#3423](https://github.com/canonical-web-and-design/web-squad/issues/3423)
=> Copy update on digital signage

templates/security-series/index.html
- Fix links for webinars in the past from "Register for the webinar" to "Watch on-demand"
- Add aws and azure sections
- View the site locally in your web browser at: http://0.0.0.0:8001/security-series
- Check page against [copy doc](https://docs.google.com/document/d/1A7JDBRZ_tuEvteE1pVA9_rV-oJUq1_DuT7GmO6zVCXM/edit#) 
- **Note** - some events have happened since copy doc was edited so check date of event, if event has happened link should say "Watch on-demand", if event is in the future link should say "Register for the webinar"
Fixes …
=> Copy update on /security-series

templates/internet-of-things/index.html
- Copy update `/internet-of-things`
**Known difference** - SMART START price guide was updated 8 days ago but the screen shot on the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit?ts=5fa29fb1#heading=h.anmejk5zc0mp) is the old version. Confirmed the updated version is to be used. 
- Check page against [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit?ts=5fa29fb1#heading=h.anmejk5zc0mp)
Fixes …
=> Copy update on IoT page

package.json, templates/shared/_thank_you.html, templates/shared/_thank_you_footer.html, templates/support/contact-us.html, templates/support/index.html, templates/support/thank-you.html, yarn.lock
- Add education discount on /support
- Add education variation to the contact-us and thank-you pages
- Update thank-you footer
- Update cookie policy to 3.0.6
- http://0.0.0.0:8001/support#education
- http://0.0.0.0:8001/support?product=education-discount
- http://0.0.0.0:8001/support/thank-you?product=education-discount
- Compare to and resolve comments in the copy docs - [support](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit#), [contact-us](https://docs.google.com/document/d/1rWgWFGtal7ddDAkIOKtA6 …
=> Add education discount on /support

templates/kubernetes/docs/1.19/components.md, templates/kubernetes/docs/1.19/release-notes.md
A few updates on versions of charms for 1.19
=> K8sdocs-1.19 version updates

package.json, static/js/src/appliance.js
- Remove pre-commit hook requiring `dotrun,` so changes to `scss,` `js` and `python` files can be committed if you're not using the `dotrun` script
- Run the site using the command `./run` ONLY 
- Make a change to a python, scss or js file, and try to commit
- There should be no failing pre-commit hook and the commit should be successful
Fixes #8733
=> Remove pre-commit hook requiring dotrun 

.env, .github/workflows/pr.yaml, konf/site.yaml, templates/advantage/maintenance.html, tests/test_routes.py, webapp/decorators.py, webapp/views.py
Adds a maintenance mode for /advantage and /advantage/subscribe; enabled if the `STORE_MAINTENANCE` env variable is set to `true`.
(The sequel to [Charmhub's maintenance mode](https://github.com/canonical-web-and-design/charmhub.io/pull/594))
- See that the page informs you that maintenance is happening
- Visit /advantage/subscribe and see that the same thing happens
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8710
=> UA shop: maintenance mode

navigation.yaml, redirects.yaml, static/sass/styles.scss, templates/cloud/_base-cloud.html, templates/cloud/index.html, templates/shared/contextual_footers/_cloud_engage_further_reading.html
- Build new `/cloud` page
- Remove existing redirect to `/public-cloud`
- Build and add [meta image](https://assets.ubuntu.com/v1/b0824086-twitter_wide_banner+%288%29.jpeg)
- View the site locally in your web browser at: http://0.0.0.0:8001/cloud
- Check page against [copy doc](https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit#heading=h.66vg7hr2fr50) and [design](https://github.com/canonical-web-and-design/ubuntu.com/issues/8593#issuecomment-724596636)
Fixes #8594
=> Build /cloud page

templates/managed/cassandra.html
- Update meta title and added meta image on `/managed/cassandra`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/cassandra
- Check the source, meta title should be "Managed Cassandra on Ubuntu | Multi-Cloud and On-Premise"
Fixes [#3450](https://github.com/canonical-web-and-design/web-squad/issues/3450)
=> Update meta title and add meta image

templates/security/index.html, templates/shared/_education-discount.html, templates/support/index.html
- Made partial out of eduction strip on support
- Add education discount strip to /security
- Add webinar strip to /sercurity
- View the site locally in your web browser at: http://0.0.0.0:8001/security#education and http://0.0.0.0:8001/support#education
- Compare to and approve comments in the [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit?ts=5fabbf60#)
Fixes #8721
webinar
education
=> Add education discount and webinar to /sercurity

templates/download/raspberry-pi/index.html
- See that there is a new pi logo
- See that the h1 has a bread on large and medium screens
- See that the 400 heading is inline
Fixes #8749
=> Update images on /download/raspberry-pi

tests/test_views.py, webapp/views.py
If a user has multiple renewals, filter out any with "closed" status so we can surface any that are open.
- See that the Python tests pass.
=> filter out "closed" status renewals

navigation.yaml, templates/c/contact-us.html, templates/financial-services/_base_financial-services.html, templates/financial-services/contact-us.html, templates/financial-services/index.html, templates/financial-services/thank-you.html, templates/shared/_thank_you.html
- Added 'Get in touch' CTA to top of /financial-services
- Created /financial-services/contact-us and /financial-services/thank-you
- I didn't change the modal form, just the form-id
- View the site locally in your web browser at: http://0.0.0.0:8001/financial-services and  http://0.0.0.0:8001/financial-services/contact-us and http://0.0.0.0:8001/financial-services/thank-you
- Compare to the copy doc for [index](https://docs.google.com/document/d/1o9s_MFaiZZIS26tusRi0ALNrcqUihhTSZgxS55oHZj4/edit#), [contact-us](https://docs.google.com/document/d/1CG04ASLyc_Q8rtoKwBXQk3YfT5B_Mbdv5B1iZNlY …
=> Add contact-us pages and cta to /financial-services

navigation.yaml, static/sass/_pattern_ratings.scss, static/sass/styles.scss, templates/kubernetes/compare.html
- Build new `/kubernetes/compare` page 
- Add meta image
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/compare
- Check page against [copy doc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit?ts=5faa80b7)
**NOTE**: A new pattern was made for the ratings meter, as the l-tutorials-meter which is used on the tutorials page 1) has a very specific class name and 2) doesn't allow for ratings which aren't whole numbers.  Should we combine these two patterns somehow using a more generic class name? …
=> Build /kubernetes/compare page

requirements.txt
This is a demo
- Navigate in the different sections that use the discourse docs module and check the `/sitemap.xml` eg. `/server/docs/sitemap.xml`
=> sitemap.xml autogenerated for discourse module 

templates/kubernetes/docs/upgrading.md
Adds some additional text to clarify commands for etcd upgrade steps
=> K8sDocs add clarifications for etcd upgrade

navigation.yaml
- Remove Pricing from /support secondary nav
- See that the link 'Pricing' was removed from the secondary nav
Fixes #8787
=> Remove Pricing from /support secondary nav

static/js/src/chart-data.js, static/js/src/chart.js, static/js/src/release-chart.js, templates/about/release-cycle.html
- Update the release charts for Kernel and OpenStack
- Added a kernel version (thanks @steverydz) axis
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle#ubuntu-kernel-release-cycle
- See that the data looks like the [sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=550510389)
Fixes #8765
=> Update the release charts for Kernel and OpenStack

static/js/src/chart.js
- Only move chars with versions right
- See that all charts align properly
=> Only move chars with versions right

templates/managed/cassandra.html, templates/managed/kafka.html
On both the Kafka and Cassandra pages:
- Move the webinar content below the logo cloud
- Replace the image with a `portalplayer` of the BrightTalk webinar
- Added "webinar" id to each section
- Updated the link to say its linking to BrightTalk.
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/kafka#webinar
- Check that the webinar works in place
- Check the webinar is not at the bottom of the page anymore
- Check they match the request in [the copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#heading=h.aelhh61rh94) 
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/cassandra#webinar
- Check that the …
=> Update the webinars on both the Kafka and Cassandra managed pages

templates/base_index.html, templates/shared/_latest_news_strip.html, templates/telco/index.html, templates/wsl/index.html
- Create horizontal latest news strip for the hompage, /telco and /wsl
- View the site locally in your web browser at: http://0.0.0.0:8001, http://0.0.0.0:8001/telco and http://0.0.0.0:8001/wsl
- See that there is a horizontal strip of news at the top of the homepage, /telco and bottom of /wsl and that the links and text make sense
Fixes #8776
=> Create horizontal latest news strip for the homepage, /telco and /wsl

static/js/src/ua-payment-modal.js
Increased maximum waiting time during payment processing from 30 to 60 seconds.
There are three messages presented to the user over time while a payment is processing, one after two seconds, another after a further two seconds, and a third after a further 11 seconds. We then waited another 15 seconds before sending the user to /advantage. This PR increases that final wait to 45 seconds, rather than 15, for a total of 60.
Fixes #8811
=> UA shop: increase the amount of time we wait for a payment to process

templates/training/contact-us.html, templates/training/index.html, templates/training/thank-you.html
- Update /training with new Landscape course and Kubeflow pdf including the contact-us and thank-you pages
- http://0.0.0.0:8001/training
- http://0.0.0.0:8001/training/contact-us?product=landscape-training-onsite
- http://0.0.0.0:8001/training/thank-you?product=landscape-training-onsite
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit?ts=5fbbe101#)
Fixes #8816
=> Update /training with new Landscape course and Kubeflow pdf

templates/kubeflow/what-is-kubeflow.html
- Updated a few links
- Used the new illustration
- Compare to and resolve comments in the [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?ts=5fb7b3eb#)
Fixes #8795
=> Update ctas and image in /kubeflow/what-is-kubeflow

navigation.yaml, templates/cube/index.html, webapp/app.py, webapp/views.py
- Hard code CUBE landing page from wireframe
- Design hasn't been done yet so this is a draft only
- Add secondary nav for cube bubble
- View the site locally in your web browser at: http://0.0.0.0:8001/cube
- Check against [wireframe](https://app.zeplin.io/project/5f5268731d98b38800528395/screen/5fa2d5661e336e12728b56a3)
Fixes #8825
=> Build draft CUBE landing page

static/js/src/tutorial-list.js, static/js/src/tutorial-list.test.js, templates/tutorials/index.html, webapp/views.py
- Added support for searching tutorials using google API in `views.py`
- Uncommented the search bar and added an event listener so it would update the query parameters on change
- Added a "No results found" state
- Check [design](https://app.zeplin.io/project/5df26dadead180a5c29b569d/screen/5dfa10d6d30a77171fd01cbe)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3448
=> 3448 build tutorials search

templates/cube/index.html, templates/cube/microcerts.html, webapp/views.py
Render different content for logged in users on `/cube/microcerts`
- dotrun
- go to `/cube/microcerts` and see you get a page with a button to login
- login and see the microcerts page
- make sure when you are logged in the cache-control headers are `Cache-Control: private`
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3499
=> Show microcerts only if you are logged in

templates/base_index.html
- To reduce the chance you see a flash of the gorilla while the homepage loads, I have turn on lazy loading
- Turn off JS and see that the 20.10 takeover loads
- Turn on JS and see less flash than on live.
=> Lazy load the default takeover image

templates/download/raspberry-pi/index.html
- Add row for headings on /download/raspberry-pi
- Check that the images and heading stay aligned at various screen widths
Fixes #8749
[v. wide]
[tablet]
=> Fix alignment of headings on large screens on /download/raspberry-pi
