- templates/download/server/arm.html
* commented out link to certified systems
1. go to /download/server/arm and see there is no link to see certified systems currently 
2. compare to the [copy doc](https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit)
[trello card](https://trello.com/c/uqBnz5Dl)
> comment out link

- templates/templates/footer.html
updated File a bug link to github
look in the footer and click on the bug link to see that it now goes to github
Fixes #659 and [trello card](https://trello.com/c/6Wl3OpTE)
> move bug link to github

- templates/index.html
- templates/takeovers/takeunders/_low-latency-report.html
Add new Low latency report takeunder as per doc
Compare the doc with the takeunder. Check S/M/L 
Card: https://trello.com/c/o809gaub
Doc: https://docs.google.com/document/d/1tQUZX8cOTPk3yRoyUCyg_UrMriAA6XAx-RbIFNO7fbI/edit?ts=5767bdfc#
> Low latency report takeunder

- templates/index.html
- templates/takeovers/takeunders/_cio-report.html
Add CIO report takeunder
Check the takeunder matches the copy doc and check it in s/m/l
Card: https://trello.com/c/xlsx3zY8
Doc: https://docs.google.com/document/d/1a5UTemZU_ODxRAxfqbvPT-ljqfzFx6qo2EQn1cEgBCA/edit?ts=5767bc71#
> Add CIO report takeunder

- static/css/section/_homepage.scss
- templates/index.html
Reinstate old MAAS takeover to become generic
Check the takeover in s/m/l
Already had design approval from Yaili
Flickr screen shot of original: https://www.flickr.com/photos/mahnke/24367777672/in/album-72157632132960058/
Card: https://trello.com/c/FGRxMWCV
> MAAS takeover

- templates/index.html
Activate generic bootstack takeover
Make sure the current takeover is bootsatck
> Bootstack takeover

- templates/legal/ubuntu-advantage/service-description.html
Update Ubuntu Advantage service description
Make sure the page correlates with the recent highlighted changes in the doc
Card: https://trello.com/c/RvL7lYrp
Doc: https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit
Fixes: https://github.com/ubuntudesign/www.ubuntu.com/issues/757
> Update Ubuntu Advantage service description

- templates/download/cloud/index.html
* added a closing div and closing section tag
* re-indented
1. go to /download/cloud and see that it renders better
> closing a div and section tag on /download/cloud

- templates/legal/bootstack/service-description.html
Bootstack service description update
Go to /legal/bootstack/service-description
Check that the copy of section 2.7 matches the update in issue #766 
Fixes #766
> Copy update to bootstack service description

- templates/legal/ubuntu-advantage/service-description.html
Two small copy changes as outlined in the issue
Make sure /legal/ubuntu-advantage/service-description has changed as per issue https://github.com/ubuntudesign/www.ubuntu.com/issues/765 
Fixes #765
> uasd amends

- templates/download/ubuntu-flavours.html
Changed the link from lubuntu.net to lubuntu.me.
Ensure that the link goes to lubuntu.me instead of lubuntu.net.
Fixes #780
> Fix the Lubuntu link

- templates/about/about-ubuntu/flavours.html
Changed the link from wiki.ubuntu.com/Lubuntu to lubuntu.me.
Ensure that the link goes to lubuntu.me instead of wiki.ubuntu.com/Lubuntu.
> Correct the Lubuntu link to lubuntu.me on ubuntu.com/about/about-ubuntu/flavours

- static/css/_scratch.scss
Reduced padding of /download/cloud aubergine-hero at small screen
view /download/cloud at all viewports - see that the aubergine-hero has less padding
Fixes #624
> reduce padding for aubergine-hero at smaller viewports

- static/css/section/_cloud.scss
- templates/cloud/shared/_guest-list.html
Added a Softlayer box to /cloud/public-cloud
Go to /cloud/public-cloud
Fixes #787
> Add softlayer as a public cloud provider

- templates/cloud/shared/_events_overview.html
* updated the /cloud overview events
[trello card](https://trello.com/c/nr4NfLKy)
> update events on /cloud page

- templates/index.html
- templates/takeovers/takeunders/_ua-store.html
Add UA store takeunder
Check takunder matches copy doc, check in various seen sizes etc
Card: https://trello.com/c/uJeglvlK
Doc: https://docs.google.com/document/d/1gLel5RfcLlqbbOcIKAp93FRZeNC7sEy-GrCuswYobPI/edit
> Ua store takeunder

- templates/cloud/shared/_events_overview.html
* updated the /cloud overview events
[trello card](https://trello.com/c/CfrxiOfW)
> update /cloud events - 11 August 2016

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_autopilot-devops.html
Added a new homepage takeover with styling.
View the homepage at all viewports and check [copy](https://docs.google.com/document/d/1I1CL0JGhjb3Rt9Y6aAa42fyc-aEsjXKwX7TZWtWMjHY/edit?ts=5774f612#) and [design](https://www.dropbox.com/sh/98wuz88iwztl2ff/AAAOdzi-jTIQn62ScKB6-R15a?dl=0).
[Card](https://trello.com/c/sNBocKSL/1568-autopilot-homepage-takeover-build)
> new autopilot devops homepage takeover

- static/css/_scratch.scss
- templates/internet-of-things/digital-signage/index.html
On /internet-of-things/digital-signage
- stopped the boxes from being links
- hid titles (kept for accessibility)
- added new links
- moved "Get in touch" link up the page
```make run```
Check against copydoc: https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit#
Card: https://trello.com/c/KqX6m6Xz/1562-digital-signage-updates-build
> updated to digital signage layout and content

- static/css/section/_cloud.scss
- templates/cloud/index.html
- templates/cloud/shared/_events_overview.html
- templates/cloud/training/index.html
* BEMed the classes for news and events to enforce consistency
* updated perl script that builds events to use new classes
* updated js script that builds news to use new classes
2. update the feed to 'http://www.stmgrts.org.uk/taleo/insights_main.xml' to test
3. see that the fonts are consistent between both news and events
Fixes #809 
* ![large screen](https://cloud.githubusercontent.com/assets/441217/17847112/34015de2-6844-11e6-8abc-75aceb4ce347.png)
* 
*
> Fix cloud events

- templates/templates/base.html
‘White space’ change to test deployment scripts
> White space change to test deployment scripts

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_linux-25th.html
Linux 25th birthday takeover
Check the homepage at all sizes
> Linux 25th birthday takeover

- static/js/partners.js
- Removed the YUI and replaced with ES5
- Moved and functioned some logic
- Go to `http://localhost:8001/server`
- You will get a XOR error
- Change line 17 of partners.js to:
`var feedURI = 'http://www.stmgrts.org.uk/taleo/partners.json';` and you should see the feed come through successfully
> Remove YUI dep from partners.js

- templates/tablet/devices.html
* updated link to bq for the tablet on /tablet/devices
1. go to /tablet/devices
2. click on the Buy link
3. see that it goes to the correct page on the BQ site
Fixes #836
> update bq m10 link

- static/css/section/_footer.scss
- static/css/section/_local.scss
- static/css/section/_morph.scss
- static/css/section/_phone.scss
- static/js/scratch.js
- templates/cloud/partners/index.html
- templates/internet-of-things/partners.html
- templates/legal/contributors/submit.html
- templates/server/index.html
- Stepped through the scratch.js removing the requirement of YUI and converting to ES5
- Removed any functions not used
- Add some CSS that is required and fixed a few issues
Sorry this is a long one and will require a thorough QA with the console open checking for errors.
> Tidy up scratch

- webapp/views.py
* Our GSA box has to be updated, so I updated the name and ips
1. run the www.staging.ubuntu.com (it currently has this branch on it)
2. compare searches with live
3. see that they are the same or better
[trello card](https://trello.com/c/ryHRAaz2)
> Gsa update

- templates/cloud/shared/_events_overview.html
* updated the /cloud overview events
[trello card](https://trello.com/c/eUQb54KW)
> update events on /cloud

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_nextcloud_takeover.html
Add new Nextcloud takeover
Check the takeover in s/m and l
Card: https://trello.com/c/Mo9nrFpZ
Doc: https://docs.google.com/document/d/1xMTbFdLr7dhlrfxgdnZjxLIFHuNMpjwWON6Ma8Loa_4/edit?ts=57d675e9
> Nextcloud takeover

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/takeunders/_autopilot-takeunder.html
Add new Autopilot takeunder
Check the takeunder in s/m/l
Card: https://trello.com/c/zqwWhIRY
Doc: https://docs.google.com/document/d/1KwzatLlCFPwUXiDSr68BPlgnKuyi5RBoeA7kNi5qy8U/edit?ts=57d010a1#heading=h.meo0azuz09li
> Autopilot takeunder

- templates/index.html
- templates/takeovers/takeunders/_autopilot-takeunder.html
Reinstate ua store takender and move new autopilot takeunder t the right
Check in s/m/l
Card: https://trello.com/c/zqwWhIRY
> reinstate us store takeunder

- templates/takeovers/_nextcloud_takeover.html
Make the word box uppercase in the takeover
> Make box uppercase

- static/css/section/_management.scss
- templates/management/index.html
- templates/management/landscape-features.html
- templates/management/return-on-investment.html
* cleaned up _management.scss
* BEMed the stats_panels on /management and /management/return-on-investment
* made some whitespace (autoindents - sorry) changes
* added a 'clear' to inventory cta on /management/landscape-features
1. go through all the /management pages and see that they look the same as live
2. check code for sanity
> clean up of _management.scss

- templates/download/alternative-downloads.html
- templates/download/desktop/index.html
- templates/download/server/index.html
- templates/download/ubuntu-kylin.html
- templates/shared/contextual_footers/_download_documentation.html
- templates/templates/base.html
Prepare download section for 16.10
Code review only really, the 16.10 download copy isn’t ready yet
> Prepare download section for 1610

- static/css/section/_desktop.scss
- templates/desktop/education.html
- templates/desktop/features.html
- templates/desktop/government.html
* linted and tidied up the _desktop.scss
1. go to every page in the /desktop section and see that it looks the same as live
> lint and tidy of desktop scss

- templates/internet-of-things/digital-signage/index.html
Add two new partners
Add new webinars and case studies row
Check the new parts of the page in s/m/l
Allready had design sign off
Card: 
Brief: https://docs.google.com/document/d/1WIW36BiwT8EHXSVA5fQAU7ZsYpWkIFIDHS3EsffoGIw/edit#
Doc: 
https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit
> Digital signage

- templates/phone/_devices.html
Copy updates on /phone/devices
Check copy updates against the [copydoc](https://docs.google.com/document/d/1fuktWHXOV6iX5ZmdWzzHnkJoCfveca3mioQxeBYlJI8/edit#)
> copy updates for phone devices page

- static/css/section/_cloud.scss
- templates/cloud/_nav_secondary.html
- templates/cloud/kubernetes.html
- templates/shared/contextual_footers/_cloud_juju_containers.html
new page build for kubernetes
Check the secondary nav in /cloud for the new 'kubernetes' link and check the page against the [copydoc](https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit#)
> Kubernetes

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_kubernetes_takeover.html
New Kubernetics takeover
Cross reference the doc/design and takeover to make sure everything matches. Check s/m/l
Doc: https://docs.google.com/document/d/1AdGZRBb2goFe7kGDSmWFfM1Y0XA4OVbrdnPNkyXPh_Q/edit?ts=57e4cf64
Design: https://www.dropbox.com/home/00_web_team/_ubuntu.com/takeovers/Kubernetes%2027.09.16/Exports
> Kubernetes takeover

- static/css/section/_homepage.scss
- templates/takeovers/_kubernetes_takeover.html
New Kubernetics takeover
Cross reference the doc/design and takeover to make sure everything matches. Check s/m/l
Doc: https://docs.google.com/document/d/1AdGZRBb2goFe7kGDSmWFfM1Y0XA4OVbrdnPNkyXPh_Q/edit?ts=57e4cf64
Design: https://www.dropbox.com/home/00_web_team/_ubuntu.com/takeovers/Kubernetes%2027.09.16/Exports
> Remove no-border class

- templates/download/server/index.html
* removed border on the row-grey
1. go to /download/server and see that the border has been removed.
Fixes #872
> remove border bottom on row-grey

- templates/cloud/shared/_events_overview.html
* updated the /cloud overview events
[trello card](https://trello.com/c/omIN5Lr4)
> update /cloud events

- static/css/section/_cloud.scss
- templates/cloud/training/index.html
- Updated the training page
- Fixed broken CSS
- Go to `/cloud/training` and check it at all viewports
- Confirm the [correct copy](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
> add a new training course and fix/restructure styling of the training page

- templates/cloud/training/index.html
Some additions to the training courses on offer.
See that the new course appears on /cloud/training at that it matches the [copydoc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
> add server admin training

- static/js/cloud.js
- static/js/forms.js
> Fix errors in period calculations

- static/css/section/_things.scss
- templates/internet-of-things/digital-signage/index.html
* general clean-up of the _things.scss file
* on /internet-of-things/digital-signage - with Yaili's help
* made hero image not-for-small
* let case study images be the full 300px wide
1. go to /internet-of-things and see that all pages look the same on all screen sizes - except for the /internet-of-things/digital-signage changes mentioned above
> things scss cleanup

- static/css/section/_tablet.scss
* general tidy of the tablet.scss
1. look at the pages in the tablet section on all screen sizes and see that it is the same as live.
> tablet section scss restructure and cleanup

- static/css/section/_phone.scss
* added '&' to make .the-video.show work correctly
1. go to /phone and click the button to watch the video
2. see the video appear
> display video on /phone again

- static/css/core-print.scss
- static/css/section/_things.scss
- templates/internet-of-things/_nav_secondary.html
- templates/internet-of-things/robotics.html
- templates/phone/index.html
Add /internet-of-things/robotics page
Cross ref demo page with copy doc
Demo page: http://www.ubuntu.com-robotics.demo.haus/internet-of-things/robotics
Copy doc: https://docs.google.com/document/d/19YhXUvtlrYLtObVtgfBZJxqudUL1Nfbad5B_0TXvo2Q/edit#
> Add /internet-of-things/robotics page

- static/css/section/_tv.scss
- templates/tv/commercial-info.html
- templates/tv/experience.html
* tidy of the tv section
* some clean-ups of broken things that are in live
1. go to /tv
2. see that the site looks ok S/M/L
> scss clean-up and html tidy for tv

- templates/cloud/openstack/index.html
- Amended chart to reflect new stats
- Updated copy and link to PDF
- Check new chart is correct
- Cross ref copy changes
- Check that PDF can be downloaded
https://docs.google.com/document/d/12z6QEGpqMVbNPJOd5aUfn0VnXQ0Sa5YriEBLA7VGNwI/edit
> Update cloud/openstack for 16.10

- templates/desktop/ubuntu-kylin.html
- Fixed up whitespace inconsistencies
- Made copy changes for 16.10 release
- Pull down changes
- Cross-ref copy changes with copy doc
Note: the layout of this page will look out of whack but @grahambancroft is fixing that upstream.
Copy doc: https://docs.google.com/document/d/1eJVoek0vT_vT4vy1Quw0NaBqm1fR9K2Dw8korIT2pKc/edit#
Trello:
https://trello.com/c/lTDdTeIk
> 16.04 changes to /desktop/ubuntu-kylin

- templates/legal/ubuntu-advantage/service-description.html
* updated the internal links on the Ubuntu Advantage service description
1. go to /legal/ubuntu-advantage/service-description#appendix-1 and see that the links work as requested in #931 
Fixes #931
> updated internal links per bug

- static/css/section/_things.scss
- templates/internet-of-things/robotics.html
Uncommeted and updated the content of the content of the case study block on /internet-of-things/robotics and styled.
Navigate to http://localhost:8001/internet-of-things/robotics
Check that the case studies row works at all viewports and matches the [copydoc](https://docs.google.com/document/d/19YhXUvtlrYLtObVtgfBZJxqudUL1Nfbad5B_0TXvo2Q/edit#).
> Robotics case studies

- templates/download/ubuntu-kylin.html
copy changes for 16.10
cross ref with copy doc: https://docs.google.com/document/d/1rbyD8r8t8PVAczVm2MTrLEB7RQPUQO6amfYuetGJP3Y/edit
Trello:
https://trello.com/c/ISoTcVLo
> 16.10 changes for /download/ubuntu-kylin

- static/css/section/_desktop.scss
- templates/desktop/developers.html
Updated copy from Google Doc
- Run code
- Cross ref with copy doc
Copy doc: https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#
Trello: https://trello.com/c/dBAQM9zF
> Update /desktop/developer copy for 16.10

- templates/download/desktop/index.html
- Amend copy on /download/desktop to reflect copy doc
Cross ref changes with copy doc: https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit
Trello: https://trello.com/c/pRu2a6wf
> Update /download/desktop copy for 16.10

- templates/download/server/index.html
Updated copy /download/server for 16.10
Cross reference with copy doc changes
gDoc: https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit
Trello: https://trello.com/c/kr3r0tf2
> Update copy /download/server for 16.10

- templates/download/server/power8.html
Change copy to reflect 16.10 changes in copy doc
Cross ref with copy doc changes
gDoc: https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit
Trello: https://trello.com/c/4lSxxOKf
> 16.10 copy changes for /download/server/power8

- templates/download/server/linuxone.html
Update copy on /download/server/linuxone for 16.04
Cross ref changes with copy doc
Copy doc: https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit
> Update copy changes on /download/server/linuxone for 16.04

- static/css/section/_homepage.scss
Styled the insights row on the homepage to have consistent padding.
View the homepage insights row and check that the padding looks reasonable at all screens.
> fixed the padding and margin of the insights row on the homepage

- templates/index.html
Change copy for homepage cloud section
Cross reference with copy doc.
gDoc: https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit
> Change copy for homepage cloud section 16.10

- templates/download/server/index.html
Add version point to /download/server - 16.10
Cross ref with copy doc
gDoc: https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit
> Add version point to /download/server - 16.10

- templates/download/server/power8.html
Used to say 16.10 but should say 16.04 LTS
Cross ref with copy doc.
gDoc: https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit
> Tweak version in power8 section

- templates/desktop/developers.html
- copy change
- switch row backgrounds so white edges aren't visible
Cross ref with copy doc
gDoc: https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit
> Tweaks: Desktop developer

- templates/download/server/power8.html
Update Power8 sentence which was a little awkward to parse.
Copy: https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit
> Update wording on power8 page

- static/css/section/_desktop.scss
- templates/desktop/developers.html
Fix up offset image in desktop/developers
- Go to /desktop/developers
- Scroll to What's New 16.10
- Confirm that laptop image is offset
> Fix up offset image in desktop/developers

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_1610.html
New 1610 takeover
Check the homepage at all viewports:
- [designs](https://www.dropbox.com/work/00_web_team/_ubuntu.com/takeovers/16.10%2010.2016/Exports)
- [copy](https://docs.google.com/document/d/18uuYjIGUcmoeMHs4Tv_yoIBr3CgbBmVD1eOzkwkf8Zk/edit#)
> 1610 takeover

- templates/desktop/developers.html
Add image to snaps row in /desktop/developer
- go to /desktop/developer
- scroll to 'Snaps are the new apps'
- check that image in row behaves as expected
> Add image to snaps row in /desktop/developer

- static/css/section/_desktop.scss
- templates/templates/_contextual_footer.html
Repostion map
Fix contextual footer
> Desktop review

- templates/download/ubuntu-kylin.html
Fix up padding spacing download/ubuntu-kylin
Check /download/ubuntu-kylin across breakpoints
Fixes #1005
> Fix up padding spacing download/ubuntu-kylin

- static/css/section/_contextual_footer.scss
Fix context footer in cloud and server
Check that cloud and server have the new style thin hr
> Fix context footer

- static/css/section/_desktop.scss
- static/css/section/_homepage.scss
- static/css/section/_local.scss
- static/css/section/_server.scss
- templates/cloud/index.html
- templates/cloud/snappy.html
- templates/desktop/developers.html
- templates/desktop/education.html
- templates/desktop/snappy.html
- templates/download/alternative-downloads.html
- templates/download/cloud/index.html
- templates/download/desktop/index.html
- templates/download/server/index.html
- templates/download/shared/_get_ebook.html
- templates/download/ubuntu-kylin.html
- templates/phone/developers.html
- templates/phone/features.html
- templates/phone/index.html
- templates/phone/partners.html
- templates/server/management.html
- templates/support/plans-and-pricing.html
Fixes:
- https://github.com/ubuntudesign/www.ubuntu.com/issues/989
- https://github.com/ubuntudesign/www.ubuntu.com/issues/990
- https://github.com/ubuntudesign/www.ubuntu.com/issues/991
- https://github.com/ubuntudesign/www.ubuntu.com/issues/994
- https://github.com/ubuntudesign/www.ubuntu.com/issues/995
- https://github.com/ubuntudesign/www.ubuntu.com/issues/996
- https://github.com/ubuntudesign/www.ubuntu.com/issues/997
- https://github.com/ubuntudesign/www.ubuntu.com/issues/998
- https://github.com/ubuntudesign/www.ubuntu.com/issues/999
- https://github.com/ubuntudesign/www.ubuntu.com/issues/1000
- https://github.com/ubuntudesign/www.ubuntu.com/issues/1001
- https://github.com/ubuntudesign/www.ubuntu.com/issues/1002
- https://github.com/ubuntudesign/www.ubuntu.com/issues/1003
- …
> Fix a bunch of review points for 16.10 release

- templates/support/index.html
* s/Manage desktops and servers with Landscape/Manage desktops, servers and virtual machines with Landscape/
1. go to /support and see that the text has been updated
[trello card](https://trello.com/c/8NgJJ7Wt)
> updated /support text per Udi

- templates/cloud/contact-us.html
* Tom noticed the /cloud/contact-us wasn't full width
1. go to  /cloud/contact-us and notice that it is full 
Fixes #1020
> make cloud contact-us full width

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/takeunders/_ods-2016.html
New takeunder on the homepage
Behold the new takeunder on the right-hand side of the homepage and see that it is good.
[Copy](https://docs.google.com/document/d/1q1YWNHOxdDkQSZUnflWCCC-U3FWwKvQnDZFu-aKYIQw/edit#)
> ODS 2016 takeunder

- templates/server/livepatch.html
Corrected the /server/livepatch command
Check the copy change against the [copydoc](https://docs.google.com/document/d/1ObUSvkDcWOe01pmhh_Aryqxs87D8X2khbJbn3RgqZE0/edit)
> Corrected livepatch command

- static/css/section/_server.scss
- templates/server/livepatch.html
Copy updates and restyling for the install steps on the /server/livepatch page
Check `/server/livepatch`
> restyle and correct the install steps and fixed the hero spacing

- static/css/section/_cloud.scss
- static/css/section/_cookie_policy.scss
- static/css/section/_desktop.scss
- static/css/section/_download.scss
- static/css/section/_footer.scss
- static/css/section/_homepage.scss
- static/css/section/_local.scss
- static/css/section/_navigation.scss
- static/css/section/_phone.scss
- static/css/section/_tablet.scss
- static/css/section/_tv.scss
- static/css/styles.scss
- templates/templates/base.html
* refactored _local.scss
* created _navigation.scss for header items in local
* created _cookie_policy.scss for cookie items in local
* moved section specific code to local scss files
1. go through the site, specially the header in S/M/L
> Local scss clean up

- static/css/section/_homepage.scss
- templates/index.html
- templates/support/index.html
- templates/takeovers/_livepatch.html
Created a homepage takeover for live patching.
Check that the homepage takeover renders in all viewports and that matches the [copy](https://docs.google.com/document/d/1c0Nse3mevYyMdJ9a7Bnd2XjBPRYiNA2Pm7rfcmJjDJ8/edit?ts=57b451b8)
> live patch takeover

- static/css/section/_homepage.scss
- templates/takeovers/_livepatch.html
Updated the livepatch screenshot with one @pmahnke crafted to be a better resolution
Check the homepage at all viewports and behold that the image resizes without jagged pixels
> updated the livepatch screenshot

- static/css/section/_local.scss
- static/css/section/_things.scss
- static/js/scratch.js
- templates/internet-of-things/robotics.html
- Updated the video on /internet-of-things/robotics
- Changed the JS for showing/hiding the video
Go to `/internet-of-things/robotics` and click the CTA in the hero to view the video at all viewports.
> Robotics video fix

- static/css/section/_internet-of-things.scss
- templates/internet-of-things/digital-signage/index.html
General tidying up of issues raised in this card:
https://trello.com/c/JFQKPOjk/1998-make-iot-digital-signage-full-width
Check the digital signage page in all viewports
> full-width updates for digital signage

- templates/internet-of-things/_nav_secondary.html
- templates/internet-of-things/gateways.html
- templates/internet-of-things/robotics.html
* updates to /iot/robotics
* updates to /iot/gateways
-[ ] didn't link to Ubuntu Core in 'From prototype to production'
-[ ] didn't link to Ubuntu Core in 'Industry-leading security'
-[ ] does MS want the video inline?
-[ ] grid of logo/products?
-[ ] remove link to more partners? and h6?
-[ ] didn't look at contextual footer
-[ ] no visual guidance yet
-[ ] no logos in 'SOFTWARE INNOVATION FOR EVERY INDUSTRY' section
> updates from MS

- templates/internet-of-things/gateways.html
minor updates to gateways page, mostly merging the work on edge-gateways from yesterday
Check in s/m/l
> gateways amends

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_core.html
New homepage takeover 
Check the homepage takeover, visually, and compare to the [copydoc](https://docs.google.com/document/d/10e7MDM58mye49dVFXuLgNs4NESxy22v1ssRlUALGK9A/edit?ts=5810e1a2#)
> Core takeover

- templates/core/base_core.html
- templates/core/index.html
First pass at /core content, no images
Compare the page with the doc
Doc: https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#heading=h.l0zjvm8x0uec
> Add /core content

- templates/core/index.html
add images to core page
add contextual footer content
Check against the doc
Card: https://trello.com/c/R5o8eMHr
Doc: https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#
> add core images

- static/css/section/_internet-of-things.scss
- static/css/section/_local.scss
- templates/internet-of-things/robotics.html
updated /iot/robotics page per the [copy doc](https://docs.google.com/document/d/1g8XpVzDkAdFETrfZvOf5Q6WlYwHCBYQ8Y6TgTlyTEYc/edit#)
* see that the page matches (for the most part) the copy doc
> add robots to robotics page

- templates/core/index.html
add logos to core page
add desktop only Features image
Check against the doc and check in s/m/l
Card: https://trello.com/c/R5o8eMHr
Doc: https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#
> Core updates

- templates/core/index.html
Design review tweaks
check s/m/l
> Design review tweaks

- templates/internet-of-things/index.html
Updated the hero image on /internet-of-things
See the hero image on  /internet-of-things
> update iot image

- templates/internet-of-things/digital-signage/index.html
- templates/internet-of-things/gateways.html
Add mobile hero image to digital-signage and gateways
Check these in s/m/l
> add mobile images

- templates/internet-of-things/index.html
Fixed link on /internet-of-things
Check that the link in the "Snaps for security" row is correct
> changed protocol of link on iot overview

- templates/core/index.html
Change link in 'Want to make your own Ubuntu Core device?’ section and add image back to 'The smallest Ubuntu’ section
> Update link and add image

- templates/core/index.html
- templates/shared/contextual_footers/_core_contribute.html
- templates/shared/contextual_footers/_core_learn_more.html
Add core contextual footer
s per https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit
> add contaxtual footer

- templates/takeovers/_core.html
Changed the takeover copy
Check the copy is changed and that it goes over two lines.
See IRC for Peter's request
> copy update for homepage takeover

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/JTNWk6c5)
> update /cloud overview events

- templates/download/cloud/index.html
Copy and small design changes for cloud downloads page.
Check `/download/cloud` against the [copydoc](https://docs.google.com/document/d/1y3uaLNn7dxZKcLq2OmVJ96o3NOqn4OTJflty2GmxV9I/edit#heading=h.o4bk4cipn29o) and see if the new content styles work.
> first pass of new content

- templates/internet-of-things/index.html
- swapped out the image on the hero
- Enlarged and swapped the side of the image in the core row
- look at `/internet-of-things` in all viewports
> update for hero image and restyle of core row

- static/css/section/_cloud.scss
- templates/cloud/openstack/managed-cloud/index.html
Updated to match copy doc
Cross ref with: https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit
http://www.ubuntu.com-managed-cloud-demo.demo.haus/cloud/openstack/managed-cloud
> /cloud/openstack/managed-cloud update

- static/css/section/_cloud.scss
- templates/cloud/openstack/managed-cloud/index.html
* updated the look of the page per design review
1. go to /cloud/openstack/managed-cloud
2. see that it conforms to the feed back in the [trello card](https://trello.com/c/NBnDx4Zu)
[trello card](https://trello.com/c/NBnDx4Zu)
> design feedback on managed-cloud

- templates/support/plans-and-pricing.html
> 2 terabytes -> 3 terabytes

- templates/shared/_ubuntu_advantage_cloud_per_node.html
Trivial change to accompany the previous one.
> Another trivial change - 2->3

- static/css/section/_phone.scss
* fix med+ cropping on scopes text on /phone
1. go to /phone
2. see that the scopes text isn't cropped
Fixes #1105
> remove margin-top on scopes-text

- templates/cloud/public-cloud.html
- templates/cloud/shared/_guest-list.html
- Updated copy
- Switched out png logos for svgs on guest grid list
- Pull down code
- Navigate to /cloud/public-cloud
- Cross ref with gDoc changes - https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#
Trello: https://trello.com/c/wuKXuMlP
> Update copy on /cloud/public-cloud

- webapp/lib/feeds.py
Remove lambda for flake8 linting, and use better variables.
Fixes #1095
RSS items should still load the same, with homepage spotlight not being included in the main feed.
> Clean up feed filter code

- templates/base_index.html
- templates/templates/base.html
* updated the meta title of the ubuntu.com homepage to incorporate IoT and Server.
* I also updated the [copy doc](https://drive.google.com/open?id=1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU)
1. go to www.ubuntu.com and look at the meta description and title
2. see that it says 'The leading operating system for PCs, tablets, phones, IoT devices, servers and the cloud' for the title and 'Ubuntu is an open source software platform that runs everywhere from IoT devices, the smartphone, the tablet and the PC to the server and the cloud.' for the desciption.
Fixes #1117
> update homepage title

- templates/shared/contextual_footers/_core_contribute.html
- templates/shared/contextual_footers/_core_learn_more.html
* added some words to the contextual footer on /core, it looked empty
1. go to /core
2. see that the copy is the same as in the [copy doc](https://docs.google.com/document/d/1kq0SPv-PAIfL9nHGxgNDpHhr5OplE2iNaZZiqG4RT48/edit#)
> added some context for the contextual footer on /core

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/d4PEBTPh
> update /cloud page events

- templates/server/livepatch.html
Added a pictogram to the contact row of the live patch page
Go to `/server/livepatch` and look at the last row in all viewports.
> add image to contact row

- templates/internet-of-things/gateways.html
Corrected link to case study on /internet-of-things/gateways
- Go to /internet-of-things/gateways
- Click on 'Read the Whitepaper' under Eclipse case study
- Check that correct PDF loads
Fixes: #1138
> Correct link on /internet-of-things/gateways

- static/css/_scratch.scss
- static/css/section/_support.scss
- templates/support/index.html
List of small visual tweaks: https://trello.com/c/MeC4M0Rz
Check page across screenshots. Joansa has already signed off the demo.
https://trello.com/c/MeC4M0Rz
> /support visual tweaks

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_advantage.html
- templates/takeovers/takeunders/_cio-report.html
A continuation of work partially reviewed in: #1143 
New homepage takeover and swapped-out takeunder
Look at the homepage takeover and the right-hand takeunder at all viewports.
> Takeover advantage

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_advantage.html
Add Advantage homepage takeover
- Pull code
- Check takeover in mobile / tablet / desktop
- Compare with screenshot below
Trello: https://trello.com/c/U4BCoLZI
Demo: http://www.ubuntu.com-takeover-advantage.demo.haus/
https://www.dropbox.com/s/37g14t26vqnt7xu/takeover_support.jpg?dl=0
> Add Advantage homepage takeover

- templates/core/index.html
* update diagram of core vs classic on /core page with large and mobile images
1. go to /core and see that the image looks good on L/S
[trello card](https://trello.com/c/6yAS0yVj)
> update core vs classic images on /core

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/uz2JlQNB)
> update cloud events

- static/css/section/_mobile.scss
- static/css/styles.scss
- templates/mobile/features.html
- templates/shared/contextual_footers/_mobile_further_reading.html
- templates/shared/contextual_footers/_mobile_partners_developers.html
Added a new /mobile/features page Frankenstein'd from the mobile and phone sections
Go to `/mobile/features`, check in-browser and check content against the [copydoc](https://docs.google.com/document/d/1GPaGkVm2j0bY_zt2Z6TsCPisUGbt6y1oaJWLSLVzTpo/edit#)
> add new mobile features page

- static/css/section/_cloud.scss
- templates/cloud/kubernetes.html
* added a logo cloud with a funky Local host with icon and text (needs design review)
* added a vimeo video
1. go to http://www.ubuntu.com-update-kubernetes-with-logos.demo.haus/cloud/kubernetes
2. see the new logo cloud section
3. see the new video
4. make sure it looks good in S/M/L
[trello card](https://trello.com/c/HezAAfDf)
[copy doc](https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit#)
> update kubernetes page with logos and video

- static/css/section/_mobile.scss
- templates/mobile/developers.html
- templates/shared/contextual_footers/_mobile_developer.html
Added new mobile developers page
Check `/mobile/developers` for the usual browser issues and check against [the copydoc](https://docs.google.com/document/d/1VLDzB9lFhAcaDkk0ZPYa-DPuRQOuXaS8EsjR1u64Z0U/edit#heading=h.ytqjh78bnjst)
> Mobile developers

- static/css/section/_mobile.scss
- templates/mobile/partners.html
Added a new mobile partners page
Check the `/mobile/partners` page in browser at all viewports and check it against the [copydoc](https://docs.google.com/document/d/1kf_dm2alpBcDAxX3t8TeV1SndCbtCB4lzaQzcUPHSug/edit#heading=h.6sx4vafy85fs)
> add mobile partners page

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/N1PuE6Ir)
> update cloud overview page events

- templates/mobile/developers.html
- corrected capitalisation of Node.js
- removed erroneous border
Check that the changes are visible on `/mobile/developers`
> remove border and correct Node.js capitalisation

- static/css/section/_mobile.scss
- templates/mobile/devices.html
- templates/mobile/shared/_devices_newsletter.html
New mobile devices page and associated styling
Check `/mobile/devices` in all viewports and check it against the [copydoc](https://docs.google.com/document/d/1l_P2yEVeF6tIvSsm7LAO9ds9nf_ZenKhwlOe3xZybBc/edit#)
> Mobile devices

- static/css/section/_mobile.scss
- static/js/scratch.js
- templates/mobile/index.html
New mobile overview page
Note: the hero animation isn't included in this PR and will be submitted separately
- check /mobile in all viewports
- check the [copy](https://docs.google.com/document/d/1LAeOVEqyel9fUoqM9IYuToOEXTGZfdN-J2xc5YIm-Fw/edit)
- test the video playback in the "Life at your fingertips" row
> Mobile overview

- templates/desktop/partners.html
* update quote on /desktop/partners
1. go to /desktop/partners
2. see that the left most quote is updated
[trello card](https://trello.com/c/UrGnzlTN)
[copy doc](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit#)
> update quote on /desktop/partners

- static/css/section/_local.scss
- static/css/section/_mobile.scss
- static/js/scratch.js
- templates/mobile/index.html
- Added the mobile overview hero animation
- Updated the js to trigger on mobile section
- Added the whitepace to the mobile stylesheet to make it consistent
- Added some overrides for the hero on smaller screens
- Pull down this branch and run with `make run`
- Go to http://127.0.0.1:8001/mobile
- Check that the phone is in the hero
- Scroll or click on the animation should trigger the animation
- Check it plays ok
- Check small viewports are ok switching to a static image
> Add mobile hero animation

- templates/mobile/index.html
- templates/templates/footer.html
- Updated content to match copy doc
- Reorder two sections to match copy doc content order
- Pull down this branch and run `make run`
- Go to http://127.0.0.1:8001/mobile
- Check that the content is the same as the copy doc
- Check the order is also correct
> Update the mobile overview page content

- templates/legal/_nav_tertiary.html
- templates/legal/terms-and-policies/index.html
- templates/legal/terms-and-policies/livepatch-terms-of-service.html
* added new livepatch terms of service doc
* added new livepatch section on index page for terms and conditions
* added page to third level nav
1. go to /legal/terms-and-policies/livepatch-terms-of-service
2. compare copy and links with [copy doc- page](https://docs.google.com/document/d/1b2TSeqGfBsmZMepXGEGkEWyTDo0M5aHmyqaQIzEZfPs/edit?ts=5832fdf8#heading=h.4c1nm5ki0fn2)
3. go to /legal/terms-and-policies
4. see the new livepatch section and that it matches with [copy doc - index](https://docs.google.com/document/d/1p3ZWroZ3nkw8XJJdPvPxSlWGYcLZLT8UbUVuppBcyHk/edit)
[trello](https://trello.com/c/KA3GCI3N)
> add livepatch terms of service

- templates/mobile/partners.html
Tiny punctuation change.
See that the colon in the hero of /mobile/partners is now a full stop.
> Remove colon, add full stop

- templates/cloud/kubernetes.html
* s/Getting Started/Getting started/
1. go to /cloud/kubernetes
2. see that it says 'Getting started'
> Sentence case on /cloud/kubernetes

- templates/mobile/index.html
Made the hero on the /mobile page vertically align the image at medium viewports.
Got to /mobile and view it at all viewports.
> mobile overview medium-viewport vertical aligning in hero

- templates/download/shared/_get_ebook.html
Use correct jquery version with closure
@karlwilliams knows
> Fix ebook download

- templates/shared/_ubuntu_advantage_server.html
Fix bug 1206 Error in Ubuntu Advantage for servers
Make sure the change noted in the doc has been changed in the page
Doc: https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit
Fix #1206
> Fix bug 1206 Error in Ubuntu Advantage for servers

- templates/cloud/thank-you.html
- templates/cloud/training.html
Updated the cloud training details
Browser QA and compare the content to the [copydoc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#)
> Clout training

- templates/mobile/developers.html
Copy update on /mobile/developers
See that the change on /mobile/developers matches the [copydoc](https://docs.google.com/document/d/1VLDzB9lFhAcaDkk0ZPYa-DPuRQOuXaS8EsjR1u64Z0U/edit)
> copy update on /mobile/developers

- static/css/section/_cloud.scss
- templates/cloud/index.html
- Added a new office hours row and link to the /cloud page
- Corrected the names of some products/companies
Check `/cloud` against [the copydoc](https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit#)
> add office hours row and correct some product names on /cloud

- static/css/section/_cloud.scss
- templates/cloud/index.html
Reverts ubuntudesign/www.ubuntu.com#1226
> Revert "add office hours row and correct some product names on /cloud"

- static/css/section/_morph.scss
* Fixed phone overlay graphic on homepage
- View homepage on small screens
- Scroll to 'Multiple devices, one experience ›'
- Ensure that text doesn't not overlay the phone graphic as you can currently see in Production
Fixes: #1222
> 1222 - Fix phone overlay graphic

- static/css/section/_cloud.scss
- templates/cloud/openstack/managed-cloud.html
Updated the hero image on the managed cloud page
Go to `/cloud/openstack/managed-cloud` and check that the hero image looks good at all viewports.
> managed cloud hero image update

- templates/download/desktop/index.html
- templates/download/server/index.html
* lts was spelled lst on two page
* look at GTM events on /download/server and /download/desktop and see they are fixed
> fix typo on variable name

- templates/download/ubuntu-kylin.html
* reordered kylin download GA tracking to be inline with other sections
* check that /download/ubuntu-kylin tracking looks ok
> fix kylin tracking

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/takeunders/_mwc-2017.html
Updated the old MWC takeunder with this year's content
Check the homepage at all viewports
> Mwc takeunder

- static/css/_global-settings.scss
- static/css/_scratch.scss
- static/css/section/_cloud.scss
- static/css/section/_cookie_policy.scss
- static/css/section/_desktop.scss
- static/css/section/_download.scss
- static/css/section/_footer.scss
- static/css/section/_homepage.scss
- static/css/section/_internet-of-things.scss
- static/css/section/_legal.scss
- static/css/section/_local.scss
- static/css/section/_mobile.scss
- static/css/section/_morph.scss
- static/css/section/_navigation.scss
- static/css/section/_server.scss
- static/css/section/_support.scss
- static/css/section/_tv.scss
Change the name of the SASS setting variable to match the naming used in templates.
QA
--
Run the site, check all CSS looks fine, especially links to assets.ubuntu.com in CSS.
> Change $asset-server to $asset-server-url

- templates/download/server/provisioning.html
Added javscript for in-page downlaoding of an ebbok - copied wholesale from `download/shared/_get_ebook.html`
Go to `/download/server/provisioning` and fill in the form, see that a zip downloads and you are sent, down the page, to the instructions.
> copied ebook download from autopilot

- templates/index.html
- templates/takeovers/takeunders/_maas-ebook.html
Added a MAAS ebook takeunder
- Go to the homepage
- See that the left-hand takeunder has changed
- Confirm the [copy](https://docs.google.com/document/d/18A70jOqlp7ibBCtnmf11iUJhjb6t-Y-76ev0HWZ2SqE/edit)
> maas ebook takeunder

- templates/download/server/provisioning.html
Updated the MAAS ebook download landing page ID to fix miscategorisation in the backend
Check that everything still functions on `/download/server/provisioning`
> update landing page ID

- .travis.yml
- scripts/generate_ia_csv.py
- scripts/generate_ia_txt.py
- templates/list_endpoints.py
- webapp/dev_settings.py
- webapp/lib/gsa.py
QA
---
Check test passes.
Run the site and check it still works.
> Implement travis with flake8

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/I2pcAYpv)
> update the events on the /cloud overview page

- static/css/section/_homepage.scss
Updated the z-index tweaks on the homepage
Check that the link in the "For all your things ›" row works and that the homepage isn't broken at any viewports
Fixes #1292
> fix z-index issues on the homepage

- templates/cloud/openstack/index.html
- templates/cloud/shared/_openstack-pie-chart.html
- templates/cloud/shared/_openstack_clients.html
Updated the content of the /cloud/openstack page
Check content against the [copydoc](https://docs.google.com/document/d/12z6QEGpqMVbNPJOd5aUfn0VnXQ0Sa5YriEBLA7VGNwI/edit#)
> Conjure up openstack

- templates/takeovers/takeunders/_maas-ebook.html
Corrected the title case use in the ebook takeunder
Check that the ebook takeunder has the correct capitalisation
> fix case for ebook takeunder title

- static/css/section/_cloud.scss
- static/css/section/_download.scss
- static/css/section/_local.scss
- templates/cloud/index.html
- templates/cloud/shared/_openstack-aws-pie-chart.html
- templates/download/_nav_tertiary.html
- templates/download/cloud/conjure-up.html
- templates/download/cloud/index.html
- templates/download/shared/_get_ebook.html
New download page for conjure up
Check `/download/cloud/conjure-up` in browser.
[copy](https://docs.google.com/document/d/1TXnoE_RZCgms1K3beJNjzYLNzZEIjfeuNYg_zhkYQTA/edit#)
[wireframe](https://drive.google.com/file/d/0B7j-gqmWcjK9NG5RSDNCZzE0NTQ/view)
The link to "Use OpenStack Autopilot" will currently fail, a coming branch will create this page (the whole build will be tested prior to release to confirm this)
This relies on #1302 being merged
> /download/cloud/conjure-up

- static/css/section/_local.scss
- templates/cloud/index.html
Updated content and structure of /cloud page. Updated the pie chart generation and vimeo styling.
Check `/cloud` in all viewports and check the [copy](https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit#heading=h.561g5td2vnk3)
> Cloud overview

- templates/download/cloud/index.html
Updated the content of  `/download/cloud`
Check `/download/cloud` in browser and check that the [copy](https://docs.google.com/document/d/1y3uaLNn7dxZKcLq2OmVJ96o3NOqn4OTJflty2GmxV9I/edit#) is correct.
> Cu download cloud

- templates/download/_nav_tertiary.html
- templates/download/cloud/autopilot.html
Added new /download/cloud/autopilot page
Go to `/download/cloud/autopilot` and check against the [copydoc](https://docs.google.com/document/d/1zZFBl_P0VYUSHAN7TbNLSVjDjx-zNoJFayxO8tFnCtM/edit#heading=h.4rkgldloed83)
> add new download/cloud/autopilot page

- templates/cloud/index.html
- templates/cloud/openstack/autopilot.html
- templates/cloud/openstack/index.html
- templates/download/cloud/conjure-up.html
- templates/download/cloud/index.html
Fix various links to tie together all the new pages
Click around the sections `/cloud/openstack` and `/download/cloud/`
> Cu link fixes

- templates/download/cloud/conjure-up.html
Two small copy / markup updates
> minor copy update

- templates/index.html
- templates/takeovers/takeunders/_qt-webinar.html
New takeunder
Check left-hand takeunder against the [copy-doc](https://docs.google.com/document/d/1rm5I84gxLiObHhdGl8xqGol50Ab65Uvg0mcH_9YUU9s/edit#)
> new QT webinar takeunder

- templates/containers/index.html
> Add new containers section

- templates/internet-of-things/index.html
* removed utm tracking from all links, except brightalk
* added ?from=iotpage tracking for external links
1. go to /internet-of-things and confirm links with Done and [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#)
Fixes #1323
> 1323 iot tracking links

- static/css/section/_homepage.scss
- templates/index.html
Redesign of the cloud row on the homepage.
Check the homepage cloud row at all viewports.
[design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/homepage/02_2017/Deliverables)
> update the design of the homepage cloud row

- templates/containers/kubernetes.html
Update kubernetes page
Check the copy doc matches the page content
Card: https://trello.com/c/TB4VmIzX
Copy doc: https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit#
> Update Kubernetes page

- templates/info/release-end-of-life.html
Reference title
- Check the numbers match [the sheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=1712489059).
> Fix for 16.04.1 in EOL alt text

- static/css/section/_containers.scss
- static/css/styles.scss
- templates/containers/kubernetes.html
Design review checklist as per card 
Check that the changes stated in the card have been actioned /containers/kubernetes 
Card: https://trello.com/c/TB4VmIzX
Doc: https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit#heading=h.trossd8v86am
> /containers/kubernetes design review checklist

- templates/containers/_nav_secondary.html
- templates/containers/docker-engine-ubuntu.html
- templates/containers/docker-ubuntu.html
Add docker page content
Make sure the page contains the same content as the copy doc /containers/docker-engine-ubuntu
Card: https://trello.com/c/pbT71tGX
Copy doc: https://docs.google.com/document/d/18rdWBRLM6jYWilpT4-NSs6yFEO4aqtO_pHidea59Kfw/edit#
> /containers/docker-ubuntu page

- templates/containers/docker-ubuntu.html
/containers/docker-ubuntu page updates as per design review
Check the card checklist (checked items) against page updates
Card: https://trello.com/c/pbT71tGX
> /containers/docker-ubuntu page updates

- static/css/section/_containers.scss
- templates/containers/lxd.html
Update lxd page as per copy doc changes
Compare page with copy doc
Doc: https://docs.google.com/document/d/1wBAeklBtadvh4jKuoPFSJxoX2k0zyWt07ZI4nytwYSA/edit#
Card: https://trello.com/c/76sNKbU4
> Containers lxd

- static/css/section/_containers.scss
- templates/containers/index.html
- templates/containers/shared/_whitepaper.html
Design tweaks from @joanasa89 
Check that the page renders and the the code is not bad - `/containers`
> snags for voerview page

- templates/containers/lxd.html
Update /containers/lxd page as per card checklist
Check that the changes on the checklist have been made on the page
Card: https://trello.com/c/76sNKbU4
> /containers/lxd update

- templates/containers/docker-ubuntu.html
snaps should be always lower case (apart from Snap Store)
Check all instances of snap meet the above criteria 
Card: https://trello.com/c/pbT71tGX
> /containers/docker - snaps should be always lower case (apart from Snap Store)

- templates/containers/docker-ubuntu.html
- templates/containers/kubernetes.html
- templates/containers/lxd.html
Added context parameters to the contact us links
See that the parameter is added to the contact us link URLs
> add context params to the contact URLs of the containers section

- templates/containers/shared/_whitepaper.html
Added a comma to make the sentence read better
See that the comma is present in the whitepaper include on, for example, `/containers`
> add a comma to the white paper row

- templates/containers/lxd.html
Update LXD page as per card checklist
Card: https://trello.com/c/76sNKbU4
> lxd updates

- templates/containers/kubernetes.html
Add webinar row to k8s page
See that the row is now present
> add webinar view to k8s row

- templates/containers/docker-ubuntu.html
Ever so small copy update
Check that the change is the same as the change requested in the copy doc
https://docs.google.com/a/canonical.com/document/d/18rdWBRLM6jYWilpT4-NSs6yFEO4aqtO_pHidea59Kfw/edit?disco=AAAABHYojxs&usp=todo_email_discussion
> /containers/docker copy updates

- templates/containers/kubernetes.html
Restyled the webinar row on the Kubernetes page
View `/cotnainers/kubernetes`
> restyling of the webinar row on k8s

- templates/containers/shared/_whitepaper.html
Updated the whitepaper include with the correct URL.
Go to `/containters` and see that the whitepaper has the correct URL and no longer has the note that the URL is missing.
> update whitepaper URL

- templates/cloud/training.html
Updated the copy of the `/cloud/training` page, including adding a new class.
Check  `/cloud/training`
[Copy](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit#heading=h.dhqg5z2vyc0)
> copy update to the cloud training page

- templates/containers/kubernetes.html
- templates/containers/shared/_whitepaper.html
Updated the content of the webinar row on `/containers/kubernetes`
[copydoc](https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit#)
> update tenses used for webinar in the past

- templates/containers/kubernetes.html
Updated webinar URL
NOTE: the URL isn't live yet so will 404
See that the URL is updated
> update URL for k8s webinar to the on-demand one

- templates/support/index.html
* updated a bullet on the /support page
* ```s/Deployed or rollback security updates/Install, upgrade, or downdate packages/````
1. go to /support
2. see that the one bullet changed per the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit)
> update landscape bullets on /support page

- templates/shared/_cloud-contact-us-form.html
Removed some phone numbers and updated the remaining ones
Check a page using the cloud contact template (like `/containers/contact-us`) against the [copy doc](https://docs.google.com/document/d/1eTF2u8oOFGg-h-sQQwZtx3D6pOfqlJSXCuNo5-dh3Fg/edit#)
> remove some phone numbers and update the remaining ones

- static/css/section/_footer.scss
- templates/containers/_nav_secondary.html
- templates/templates/footer.html
- Added containers to the footer
- Shrunk the footer columns slightly to fit the new content
- Shortened the docker page title
Check the footer at all viewports
> add containers to the site footer

- gulp/watch.js
change sass watch path
docker-compose run --service-ports web
gulp watch
> change watch path

- .travis.yml
Added the `gulp test` test to Travis to lint the sass
See the travis build on this PR
> add sass linting to travis test

- static/js/core.js
- static/js/forms.js
- static/js/scratch.js
Various js linting fixes and whitespace cleanup / general hygiene.
`gulp lint-js` and see that there are no issues.
Click around the site and check that there are no JS issues
See that the CI is passing.
> fix the js lint issues

- templates/takeovers/takeunders/_iot-02-2017.html
Replace takeunder picto with new one
Check that the image has been replaced and is now the one specified in the card
Card: https://trello.com/c/p8ibDOjA
> Replace takeunder picto with new one

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/ngmqtC7e)
> update /cloud overview events - remove MVC

- static/css/section/_footer.scss
- templates/templates/footer.html
Added phone numbers to the site footer
Look at the footer in all viewports.
[design](https://www.dropbox.com/sh/e7gw7okhht84se5/AABK9Z6Z-lThJFEaJDqAcF93a/Exportables?dl=0&preview=+B.jpg)
> add phone numbers to footer

- README.md
* added a section on requirements for Docker and npm
* added more details on sass errors
1. run through the install from scratch, see if they help
Fixes #53
> Update readme with requirements and more sass help

- templates/legal/_nav_tertiary.html
- templates/legal/terms-and-policies/index.html
- templates/legal/terms-and-policies/jaas-beta-terms-of-service.html
* added new JAAS tos doc
* added box and link to /legal/terms-and-policies
1. check /legal/terms-and-policies/jaas-beta-terms-of-service and compare to the [copy doc](https://docs.google.com/document/d/1XybaOlJhaTjKUWwY07h7RNbQ_K5J6bAclGyJRtCwIDc/edit#)
2. check that /legal/terms-and-policies/ has a box for the new terms and compare to the [brief](https://docs.google.com/document/d/1euY9CPm2yDjXQHeIEqMNz0Vyw2zgf1IohDD_10XVmSo/edit#heading=h.8w6y62obfima)
> add jaas beta terms of service

- templates/cloud/managed-cloud.html
- templates/containers/lxd.html
Fixed the support image on `/containers/lxd` to 200px wide.
See that the support image size is updated on `/containers/lxd`
> Lxd support image

- templates/index.html
- templates/templates/base.html
- Corrected the tabbling for index.html and base.html
- Corrected HTML validation errors!
- Simplified the multiple "with" template tags
- General sensitisation
No visual changes. Check that the homepage and site still renders the same.
> Validate and sanitise homepage and base template

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/fR3EnvBq)
> update events on the /cloud overview

- static/css/section/_homepage.scss
- templates/index.html
- templates/takeovers/_containers-ebook.html
New homepage takeover 
Check the takeover on the homepage against the [brief](https://docs.google.com/document/d/1_-Ns4VFpnW8BPbf7cLfQdobWxDhi-_LO6czJ-wA4f7U/edit#) and [design](https://www.dropbox.com/sh/3hld9oy7350bgnw/AACUYs551xaXSSma1bG6n9qJa/Exportables?dl=0&preview=Containers-takeover-desktop.jpg).
> containers ebook takeover

- templates/takeovers/_containers-ebook.html
removed the alt tag that should have been empty
See that it is, indeed, no longer there
> remove old alt tag

- templates/takeovers/_containers-ebook.html
Updated the copy based on post-release feedback
See that the copy of the homepage takeover is different now.
> update takeover copy - post launch

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/mg0YG0zA)
> updating events for /cloud overview

- templates/cloud/juju.html
* replaced link to Top 12 reasons with docs Getting started
* didn’t update the copy doc as Tom has updated it
1. go to /cloud/juju
2. see the link to https://jujucharms.com/docs/stable/getting-started#getting-started-with-juju
Fixes #1439
> update pdf on /cloud/juju

- templates/cloud/juju.html
- templates/containers/kubernetes.html
Upgraded juju-cards to the latest version
- Go to https://www.ubuntu.com/containers/kubernetes
- Scroll to the Production features section and see the card does not work
- Go to http://0.0.0.0:8001/containers/kubernetes
- Scroll to the Production features section and see the card does work
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/1434
> Upgraded juju-cards to v1.4.0

- templates/server/maas.html
Copy updates for `/sever/maas`
Check `/server/maas` against the [copydoc](https://docs.google.com/document/d/1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM/edit#heading=h.4di4xumqn3tl). I've only actioned changes marked with a comment.
[Demo](http://www.ubuntu.com-maas-copy.demo.haus/server/maas)
> various copy updates to /server/maas

- HACKING.md
- run
"project" should be "projects". Also use latest django image.
`./run`
> A one-character change to hacking.md

- static/css/section/_homepage.scss
- templates/index.html
Added containers to the homepage signpost row and restyled the row.
Also tidied up the Sass to use Sass features and BEM'd it.
View the homepage in all viewports
[Demo](http://www.ubuntu.com-homepage-update.demo.haus/)
[Design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/homepage/03_2017/Exportables/old?preview=Homepage_03_2017.jpg)
> restyle homepage signpost row and add containers

- .gitignore
- run
Update to using the very latest docker images for yarn and django.
QA
---
``` bash
./run --help
./run
// etc.
```
Check everything works as it did.
> Use latest versions of docker images

- templates/about/contact-us/index.html
Update contact us page
Check the page correlates with the doc
Card: https://trello.com/c/10iRmAyD 
Doc: https://docs.google.com/document/d/1LK7lJlhke8hKesVSglHxNSfUCDw0bfddzM4vezeXvBQ/edit#
> Update contact us page

- templates/download/cloud/autopilot.html
Updated the autopilot instructions
Check `/download/clout/autopilot` against the changes in the [copydoc](https://docs.google.com/document/d/1zZFBl_P0VYUSHAN7TbNLSVjDjx-zNoJFayxO8tFnCtM/edit#)
> Download autopilot update

- static/css/modules/_ubuntu_patterns_footer.scss
- static/css/section/_global.scss
- templates/templates/footer.html
Add global nav
Refactor ubuntu_patterns_footer.scss second level link styling
Uses existing live ubuntu.com global nav solution
Run ./run to get the site running
Check in s/m & l
> Add global nav

- templates/index2.html
Created a second homepage for AB testing
- Check the code is ok
> Homepage 2 for AB test

- static/css/section/_local.scss
- templates/shared/_systems_management_tool.html
- templates/support/index.html
Some small copy updates and a new "Systems management tool: Landscape" section.
- Pull code and run `./run`
- Go to http://localhost:8001/support
- Check that the copy matches the copy doc
Copy doc https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit?pli=1#
> Update /support for landscape-self-service

- templates/info/release-end-of-life.html
- templates/shared/_release_schedule.html
Replace two eol images
- Pull code and run ./run
- Go to:
- http://localhost:8001/info/release-end-of-life
- http://localhost:8001/desktop/enterprise
- Check that the images are the same as the images specified in the card
Design sign off will be made on the 1704-dev branch
Card: https://trello.com/c/aZJCSIus
> Update eol images

- templates/download/server/index.html
Added "Your next steps with Ubuntu Server" section and added the list in Ubuntu Server 16.04.1 LTS for OpenStack.
- Pull code
- Check the code is ok
- Run `./run` and go to http://0.0.0.0:8001/download/server
- Check that the page works on all sizes and looks like the screenshot
Copy doc: https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit?pli=1
> Landscape self service download server

- templates/download/_nav_tertiary.html
- templates/download/server/thank-you.html
Add the "Your next steps with Ubuntu Server" section.
- Pull code and run `./run`
- Go to http://0.0.0.0:8001/download/server/thank-you
- Check that the page looks ok
- Check the copy matches the copy doc
Copy doc: https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit?pli=1
> Update /download/server/thank-you for landscape-self-service

- static/css/section/_desktop.scss
- templates/desktop/developers.html
Update /desktop/developers What’s new section as per copy doc
- Pull code and run ./run
- Go to http://localhost:8001/desktop/developers
- Check that the What’s new section is the same as copy doc
- Make sure the laptop image has gone as per card
Doc: https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#heading=h.78m14zr2rvaj
Card: https://trello.com/c/F0j0GPmJ
> Update /desktop/developers what’s new in 17.04 copy

- static/css/section/_desktop.scss
Replace /desktop/kylin hero image
- Pull code and run ./run
- Go to http://localhost:8001/desktop/ubuntu-kylin
- Check that the hero image has changed to the image specified in the card message
This will get design sign off on the 1704-dev branch
Card: https://trello.com/c/DqZqZmvt
Doc: https://docs.google.com/a/canonical.com/document/d/1NF1udWXWGmzw5gXCZYhPMWNmYQ3BCQ2t8QMRp5xb06c/edit?disco=AAAABIieRz0
> Kylin screenshot

- templates/cloud/index.html
Remove self-service livepatch feature from /cloud
- Pull code and run `./run`
- Go to http://0.0.0.0:8001/cloud
- Check that the page looks ok
- Check the comments are complete in the copy doc
Copy doc: https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit?pli=1#
> Remove self-service livepatch feature from /cloud

- templates/server/index.html
Remove self-service livepatch feature from /server
- Pull code and run `./run`
- Go to http://0.0.0.0:8001/server
- Check that the page looks ok
- Check the comments are complete in the copy doc
Copy doc: https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit
> Remove self-service livepatch feature from /server

- templates/google22f4ff04a7577fe4.html
* adding a file to help google webmaster tools verify our site
1. Confirm successful upload by visiting https://www.ubuntu.com/google22f4ff04a7577fe4.html in your browser.
> add verification file for webmaster tools

- static/css/section/_homepage.scss
- templates/index.html
- Removed mobile row from homepage
- Removed mobile icon and associated styling from signpost
view the homepage in-browser.
[Demo](http://www.ubuntu.com-remove-mobile-from-homepage.demo.haus/)
> Remove mobile from homepage

- static/css/section/_download.scss
- templates/desktop/ubuntu-kylin.html
- templates/info/release-end-of-life.html
Fixes some small review points in the 17.04 review
- Check the code looks good
> Some review points

- static/css/section/_homepage.scss
- templates/takeovers/_1704_takeover.html
- templates/templates/footer.html
Design review tweaks
- Pull code and run ./run
- Go to http://localhost:8001/
- Check the page in s/m and l, check the code
> 1704 takeover tweaks

- static/css/section/_homepage.scss
- templates/takeovers/_1704_takeover.html
Make first two items appear on page load
Check that the first date 04 10 is visible on page load
> 17.04 takerover tweaks

- static/css/section/_local.scss
- templates/download/server/thank-you.html
Fixed design points
- Check that the review points were addressed at https://github.com/canonical-websites/www.ubuntu.com/pull/1533#issuecomment-293603801
> Landscape self service

- templates/index2.html
Updated the B homepage to match the A takeover and take under.
- Pull branch and run `./run`
- Go to http://localhost:8001/index2
- Check it works and has no template errors
> Fix A/B test homepage

- templates/support/_nav_secondary.html
- Check footer displays correctly
> Fix typo on footer support menu

- templates/base_index.html
- templates/index.html
- templates/index2.html
- templates/templates/base-v1.html
- templates/templates/base.html
Updated the homepage copy to match the copy doc
- Pull down this branch and run `./run`
- Make sure the updated heading looks ok.
- Check its matches the copy doc 
Copy doc: https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit
> Remove more mobile references across the site

- templates/containers/kubernetes.html
Updated k8s version to 1.6.x and updated [the copy doc](https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit).
- Check the version is correct in the copy
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/1669
> Update k8s version to 1.6.x

- templates/about/base_about-v1.html
- templates/shared-v1/contextual_footers/_cloud_bootstack.html
- templates/shared-v1/contextual_footers/_cloud_further_reading.html
- templates/shared-v1/contextual_footers/_contextual_footer.html
- templates/shared-v1/contextual_footers/_further_reading.html
- templates/shared-v1/contextual_footers/_generic_download.html
- templates/templates/_contextual_footer-v1.html
- templates/templates/_further_reading_links-v1.html
Migrate contextual footers for /about
- These changes are all v1 namespaced so will not appear anywhere
- Check code to ensure they don't break anything
- Visual QA will be when these changes are made visible by /about demo feature branch
> Migrate contextual footers for /about

- static/sass/_v1_pattern_site_search.scss
Make text color in search white
- Go to [http://0.0.0.0:8001/about](http://0.0.0.0:8001/about)
- Type in search box and make sure text is white
Related #1686
> Make text color in search white

- templates/shared-v1/contextual_footers/_cloud_bootstack.html
- templates/shared-v1/contextual_footers/_cloud_further_reading.html
- templates/shared-v1/contextual_footers/_desktop_further_reading.html
- templates/shared-v1/contextual_footers/_further_reading.html
- templates/shared-v1/contextual_footers/_generic_download.html
- templates/shared-v1/contextual_footers/_iot_further_reading.html
All contextual headers should be h4
- Check code
- Check everything namespaced
Related #1683
> All contextual headers should be h4

- templates/about/index.html
- Add borders to strips
- Check code
- Check that strips have border displayed
#1682
> Add borders to strip

- static/sass/_v1_pattern_navigation.scss
Reduce font-size of breadcrumb
- Pull code
- Run `./run build`
- Navigate to /about
- Verify that breadcrumb links are now 14px
#1692
> Reduce breadcrumb font size

- static/sass/_v1_pattern_navigation.scss
- static/sass/styles-v1.scss
Reduce nav font size and increase font weight
- Pull code, run `./run serve`
- Verify primary nav is now 14px and font-weight 400
Related #1694
> Reduce nav font size and increase font weight

- static/sass/_v1_pattern_footer.scss
- templates/shared-v1/contextual_footers/_contextual_footer.html
Add border top to contextual footer
- Pull code
- View /about
- Check that contextual footer has 16px top border 
Related #1685
> Add border top to contextual footer

- static/sass/_v1_pattern_footer.scss
- Fixed footer heading font size (after the base font-size consolidation, across viewports)
- Fixed the padding under headings in the footer at medium and large viewports.
Pull the code and look at the footer headings in all viewports.
> 1704 footer headings

- templates/cloud/_nav_secondary-v1.html
- templates/cloud/_nav_tertiary-v1.html
- templates/containers/_nav_secondary-v1.html
- templates/core/_nav_secondary-v1.html
- templates/desktop/_nav_secondary-v1.html
- templates/desktop/_nav_tertiary-v1.html
- templates/download/_nav_secondary-v1.html
- templates/download/_nav_tertiary-v1.html
- templates/internet-of-things/_nav_secondary-v1.html
- templates/legal/_nav_secondary-v1.html
- templates/legal/_nav_tertiary-v1.html
- templates/server/_nav_secondary-v1.html
- templates/server/_nav_tertiary-v1.html
- templates/support/_nav_secondary-v1.html
- templates/templates/_nav_breadcrumb-v1.html
- templates/templates/base-v1.html
This is so nav links can appear highlighted when on relevant page
- Pull code
- Run site
- Navigate to http://0.0.0.0:8001/about/about-ubuntu
- 'About Ubuntu' in the breadcrumbs nav should be highlighted orange
> Change 'active' class to 'is-active'

- templates/cloud/shared/_events_overview.html
[trello card](https://trello.com/c/8NoePgGx)
> update cloud overview events

- static/sass/_v1_pattern_navigation.scss
- templates/templates/base-v1.html
- Make sure links in primary nav are soft on small screens
- Make tertiary nav inline when space becomes available
- Make font size in nav 14px across the board
- Improve spacing
- Pull code
- Check nav works correctly
Related #1693
> Tidy up secondary level nav

- static/sass/_v1_pattern_navigation.scss
- static/sass/_v1_pattern_site_search.scss
- templates/templates/base-v1.html
Move search box behind toggle on medium screens
- Pull code
- Check search box on medium screens work behind toggle
Related #1688
> Move search box behind toggle on medium screens

- static/sass/_v1_pattern_footer.scss
Simplified and fixed the vertical spacing in the footer at medium & large viewports.
`./run`
Go to `/about` and see that there is good footer vertical spacing at all viewports
> Footer padding

- static/sass/_v1_pattern_footer.scss
Reduced padding in the bottom part of the footer so that the links line up with the links in the menu above.
See how the left-hand of the footer all lines up now.
> Footer small padding

- templates/legal/terms-and-policies/confidentiality-agreement.html
Correct capitalisation in confidentiality-agreement.html
Check the code to ensure only 3 instances of capitalisation have occurred.
Related #1749
> 1749 Correct capitalisation in confidentiality-agreement.html

- templates/download/_base_download-v1.html
- templates/download/_nav_secondary-v1.html
- templates/download/ubuntu-flavours.html
- templates/templates/base-v1.html
* started on converting the download section
* flavours - http://0.0.0.0:8001/download/ubuntu-flavours
* NOTE: the hover-menu class has made the nav very complicated, I think we need to look at this
Fixes #1647 
[demo](http://www.ubuntu.com-v1-download-flavours.demo.haus/download/ubuntu-flavours)
> update download/flavours to VBT

- .github/PULL_REQUEST_TEMPLATE.md
I write these lines multiple times a day, may as well be part of the template. 
Check code makes sense.
> Update PR template with generic instructions to run site

- templates/legal/ubuntu-advantage/service-description-ja.html
Amend date on /legal/ubuntu-advantage/service-description-ja
- Check code and ensure change matches #1793 
Fixes #1793
> Change date on /legal/ubuntu-advantage/service-description-ja

- .gitignore
- manage.py
- package.json
- run
- yarn.lock
QA
--
Check all run functions
``` bash
./run clean
./run
./run watch
etc.
```
> Python3 and latest run script

- templates/download/_nav_tertiary-v1.html
- templates/download/ubuntu-kylin.html
* update /download/ubuntu-kylin to vbt
[page](http://0.0.0.0:8001/download/ubuntu-kylin)
* compare to the [design](https://www.dropbox.com/search/work?path=%2F00_web_team%2F_ubuntu.com%2Fnew+projects%2Fvanilla+update%2Fpatterns+inventory&preview=download-ubuntu-kylin.png&qsid=21830873026803084826401499240920&query=containers) and [demo](http://www.ubuntu.com-1648-download-ubuntu-kylin.demo.haus/download/ubuntu-kylin)
Fixes #1648
> update /download/ubuntu-kylin to vbt

- static/sass/_v1_contribution.scss
- static/sass/styles-v1.scss
- templates/download/_nav_tertiary-v1.html
- templates/download/desktop/contribute.html
* update /download/desktop/contribute to vbt
* I know the button text is white... that's been fixed in several other PRs
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/desktop/contribute?version=16.04.2&architecture=amd64)
* compare to the [design](https://www.dropbox.com/search/work?path=%2F00_web_team%2F_ubuntu.com%2Fnew+projects%2Fvanilla+update%2Fpatterns+inventory&preview=download-contribute.png&qsid=21830873026803084826401499240920&query=containers) and the [demo](http://www.ubuntu.com-1629-download-desktop-contribute.demo.haus/download/desktop/contribute?version=16.04.2&architecture=amd64)
Fixes #1629
> update /download/desktop/contribute to vbt

- templates/download/_nav_tertiary-v1.html
- templates/download/server/power8.html
* updated /download/server/power8 to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/server/power8)
* compare to the [design](https://www.dropbox.com/search/work?path=%2F00_web_team%2F_ubuntu.com%2Fnew+projects%2Fvanilla+update%2Fpatterns+inventory&preview=download-server-power8.png&qsid=01007770716940212773576207606415&query=download-server) or [demo](http://www.ubuntu.com-1643-download-server-power8.demo.haus/download/server/power8)
Fixes #1643
> update /download/server/power8 to vbt

- templates/download/_nav_tertiary-v1.html
- templates/download/desktop/thank-you.html
* updated /download/desktop/thank-you to vbt
- [page](http://0.0.0.0:8001/download/desktop/thank-you) and [demo](http://www.ubuntu.com-1634-download-desktop-thank-you.demo.haus/download/desktop/thank-you)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/patterns%20inventory/9.%20Download?preview=download-server-thank-you.png)
Fixes #1634
> 1634 download desktop thank you

- static/sass/_v1_pattern_strip.scss
- templates/download/_nav_tertiary-v1.html
- templates/download/server/linuxone-signup-thank-you.html
- templates/shared-v1/_thank_you_footer.html
* update download/server/linuxone-signup-thank-you to vbt
- View the site locally in your web browser at: [[page](http://0.0.0.0:8001/download/server/linuxone-signup-thank-you)
* compare to the [design](https://www.dropbox.com/search/work?path=%2F00_web_team%2F_ubuntu.com%2Fnew+projects%2Fvanilla+update%2Fpatterns+inventory&preview=containers-thank-you.png&qsid=21830873026803084826401499240920&query=containers) *based on containers* and the [demo](http://www.ubuntu.com-1641-download-server-linuxone-signup-thank-you.demo.haus/download/server/linuxone-signup-thank-you)
Fixes #1641
> update download/server/linuxone-signup-thank-you to vbt

- templates/download/_nav_tertiary-v1.html
- templates/download/server/linuxone.html
* update /download/server/linuxone to vbt
* moved the t&c to under the button
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/server/linuxone)
* compare to the [design](https://www.dropbox.com/s/few9kkpkqlwz52a/download-server-linuxone.png?dl=0) and [demo](http://www.ubuntu.com-1642-download-server-linuxone.demo.haus/download/server/linuxone)
Fixes #1642
> update /download/server/linuxone to vbt

- static/sass/_v1_pattern_link.scss
- templates/download/_nav_tertiary-v1.html
- templates/download/server/thank-you.html
* updated /download/server/thank-you to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/server/thank-you) and [demo](http://www.ubuntu.com-1646-download-server-thank-you.demo.haus/download/server/thank-you)
- compare to the [design](https://www.dropbox.com/search/work?path=%2F00_web_team%2F_ubuntu.com%2Fnew+projects%2Fvanilla+update%2Fpatterns+inventory%2F9.+Download&preview=download-server-thank-you.png&qsid=08186058431934915572202485356221&query=server-thank-you)
Fixes #1646
> update /download/server/thank-you to vbt

- static/js/scratch-v1.js
- static/sass/styles-v1.scss
- templates/legal/contributors/submit.html
- Add submit visibility toggle to form on /legal/contributors/submit
- Added spacing for consecutive fieldsets
- Linted existing JS file
- View the site locally in your web browser at: [http://0.0.0.0:8001/legal/contributors/submit](http://0.0.0.0:8001/legal/contributors/submit))
- Toggle to radio buttons to verify the correct forms appear
Fixes #1763 
[http://www.ubuntu.com-1763-submit-toggle.demo.haus/legal/contributors/submit](http://www.ubuntu.com-1763-submit-toggle.demo.haus/legal/contributors/submit)
> 1763 Add submit visibility toggle to form on /legal/contributors/submit

- package.json
- static/sass/_v1_pattern_navigation.scss
- static/sass/styles-v1.scss
- yarn.lock
Bump VBT to latest version
- Go to [http://0.0.0.0:8001/about](http://0.0.0.0:8001/about))
- Make sure the nav looks ok in s, m and l
Fixes #1824
> Bump VBT to latest version

- static/js/scratch-v1.js
Ensure forms fields exist running toggle check
- View the site locally in your web browser at: [http://0.0.0.0:8001/legal](http://0.0.0.0:8001/legal))
- Check no JS error
- Go to http://0.0.0.0:8001/legal/contributors/submit
- Check forms still toggle
Fixes #1835
> Ensure forms fields exist running toggle check

- requirements.txt
- webapp/settings.py
QA
--
``` bash
./run
```
Check the site loads fine, including styles. view source, and check `?v=dsfgds` has been added to the local CSS file paths.
> Use latest canonicalwebteam.versioned-static

- static/sass/_v1_pattern_navigation.scss
Remove horizontal scroll on S screens
- View the site locally in your web browser at: [http://0.0.0.0:8001/](http://0.0.0.0:8001/))
- Reduce screen width to S screen breakpoint
- Ensure there is no horizontal movement
Fixes: #1798 
http://www.ubuntu.com-1798-horizontal-scroll.demo.haus
> Remove horizontal scroll on S screens

- templates/core/thank-you.html
* update /core/thank-you to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/core/thank-you)
- [demo](http://www.ubuntu.com-1600-core-thank-you.demo.haus/core/thank-you)
Fixes #1600
> update /core/thank-you to vbt

- static/sass/_v1_pattern_card.scss
- static/sass/styles-v1.scss
- templates/download/index.html
- templates/shared-v1/contextual_footers/_download_cloud_buy_landscape.html
- templates/shared-v1/contextual_footers/_download_enterprise_support.html
- templates/shared-v1/contextual_footers/_server_contact_us.html
- templates/shared-v1/contextual_footers/_support_contact_us.html
* converted /download to VBT
- see the page http://0.0.0.0:8001/desktop/developers
- [see the demo](http://www.ubuntu.com-1620-desktop-overview-vbt.demo.haus/download)
Fixes #1620
> update download overview to vbt

- templates/containers/_nav_secondary-v1.html
- templates/containers/contact-us.html
- templates/containers/thank-you.html
- templates/shared-v1/_cloud-contact-us-form.html
- templates/shared-v1/_thank_you.html
- templates/shared-v1/_thank_you_footer.html
- templates/templates/base-v1.html
* update /containers/contact-us to vbt
- View the site locally in your web browser at:- [page](http://0.0.0.0:8001/containers/contact-us)
- [demo](http://www.ubuntu.com-1605-containers-contact-us.demo.haus/containers/contact-us)
Fixes #1605
> 1605 containers contact us

- static/sass/_v1_pattern_navigation.scss
Fix hover nav positioning
- View the site locally in your web browser at: [http://0.0.0.0:8001/about](http://0.0.0.0:8001/about))
- Make sure the hover menu is in the correct position 
Fixes #1834 
[Demo](http://www.ubuntu.com-nav-fix.demo.haus/about)
> Fix hover nav positioning

- templates/containers/thank-you.html
- update /containers/thank-you to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/containers/thank-you)
- [demo](http://www.ubuntu.com-1606-containers-thank-you.demo.haus/containers/thank-you)
Fixes #1606
> 1606 containers thank you

- static/sass/_v1_patterns_testimonials.scss
- static/sass/styles-v1.scss
- templates/containers/docker-ubuntu.html
- templates/containers/shared/_whitepaper.html
- templates/containers/thank-you.html
- templates/shared-v1/contextual_footers/_containers_juju.html
* added testimonial pattern
[page](http://0.0.0.0:8001/containers/docker-ubuntu)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/4.%20Containers?preview=containers-docker-ubuntu.png) and the [demo](http://www.ubuntu.com-1604-containers-docker-ubuntu.demo.haus/containers/docker-ubuntu)
Fixes #1604
> 1604 containers docker ubuntu

- static/sass/_v1_pattern_navigation.scss
- templates/server/_nav_secondary-v1.html
- templates/server/_nav_tertiary-v1.html
- templates/server/index.html
- templates/server/thank-you.html
* update /server/thank-you to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server/thank-you)
- look at the [demo](http://www.ubuntu.com-1585-server-thank-you.demo.haus/server/thank-you) or the [core thank-you design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/11.%20Forms?preview=core-thank-you.png)
Fixes #1585
> 1585 server thank you

- static/sass/_v1_pattern_navigation.scss
- templates/server/_nav_secondary-v1.html
- templates/server/_nav_tertiary-v1.html
- templates/server/contact-us.html
- templates/server/index.html
* update /server/contact-us to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server/contact-us)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/11.%20Forms?preview=server-contact.png) and the [demo](http://www.ubuntu.com-1580-server-contact-us.demo.haus/server/contact-us)
Fixes #1580
> 1580 server contact us

- static/sass/_v1_pattern_navigation.scss
- templates/server/_nav_secondary-v1.html
- templates/server/_nav_tertiary-v1.html
- templates/server/index.html
* got secondary and tertiery nav ready for vbt
* removed extra chevron
- look at the code and the screenshot
> nav for /server move to vbt

- static/sass/_v1_pattern_hero.scss
- static/sass/_v1_pattern_inline-images.scss
- static/sass/styles-v1.scss
- templates/server/_nav_secondary-v1.html
- templates/server/_nav_tertiary-v1.html
- templates/server/index.html
- templates/server/maas.html
* update /server/maas to vbt
* created pattern_hero for hero images that need to go off screen
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server/management)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/3.%20Server?preview=server-maas.png) and the [demo](http://www.ubuntu.com-1583-server-maas.demo.haus/server/maas)
Fixes #1583
> 1583 server maas

- static/sass/_v1_pattern_card.scss
- templates/server/_nav_secondary-v1.html
- templates/server/_nav_tertiary-v1.html
- templates/server/index.html
- templates/server/livepatch.html
* update /server/livepatch to vbt
* added .p-card--resource, with no animation - needs design and perhaps better css
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server/livepatch)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/3.%20Server?preview=server-livepatch.png) and the [demo](http://www.ubuntu.com-1582-server-livepatch.demo.haus/server/livepatch)
Fixes #1582
> 1582 server livepatch

- templates/internet-of-things/_nav_secondary-v1.html
- templates/shared-v1/contextual_footers/_iot_contact.html
- templates/shared-v1/contextual_footers/_iot_newsletter_signup.html
* fix secondary nav
* a few contextual footers
- review the code
> common iot section fixes for vbt

- templates/server/management.html
- templates/shared-v1/_ubuntu_advantage_cloud_virtual_guests.html
- templates/shared-v1/_ubuntu_advantage_community.html
- templates/shared-v1/_ubuntu_advantage_server.html
* update /server/management to vbt
* updated the [copy doc](https://docs.google.com/document/d/1Oqzs4utcIAdmFwZlSqlA6m5ioDlNnAjj_OTi_RHF2f8/edit#heading=h.csnsfyl4zut5)
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/server/management)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/3.%20Server?preview=server-management.png) and [demo](http://www.ubuntu.com-1584-server-management.demo.haus/server/management)
Fixes #1584
> 1584 server management

- static/sass/_v1_pattern_navigation.scss
Add is-active styles
- View the site locally in your web browser at: [http://0.0.0.0:8001/download](http://0.0.0.0:8001/download))
- Make sure the download nav item has the dark active background the same as other non v1 sections
> Add is-active styles

- templates/desktop/thank-you.html
Move /desktop/thank-you to VBT. 
This was simply switching out some includes that already been flipped so there should be no design review required.
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/thank-you](http://0.0.0.0:8001/desktop/thank-you))
- Check it all looks good
Fixes #1663
> Upgrade /desktop/thank-you

- templates/about/index.html
- templates/desktop/_nav_secondary-v1.html
- templates/desktop/ubuntu-kylin.html
- templates/shared-v1/contextual_footers/_desktop_kylin_learn_more.html
- templates/templates/_further_reading_links.html
Upgrade /desktop/ubuntu-kylin to Vanilla v1
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/ubuntu-kylin/](http://0.0.0.0:8001/desktop/ubuntu-kylin/))
- Ensure updated pages matches [patterns](https://www.dropbox.com/home/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/5.%20Desktop?preview=desktop-kylin.png) as outlined
Fixes #1664 
http://www.ubuntu.com-1664-desktop-kylin.demo.haus
> 1664 Upgrade /desktop/ubuntu-kylin to Vanilla v1

- templates/internet-of-things/_nav_secondary-v1.html
- templates/internet-of-things/index.html
- templates/internet-of-things/newsletter-thank-you.html
- templates/shared-v1/contextual_footers/_iot_contact.html
- templates/shared-v1/contextual_footers/_iot_newsletter_signup.html
* update /internet-of-things/newsletter-thank-you to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/internet-of-things/newsletter-thank-you)
- compare to the [demo](http://www.ubuntu.com-1595-internet-of-things-newsletter-thank-you.demo.haus/internet-of-things/newsletter-thank-you) or [core thank-you](http://0.0.0.0:8001/core/thank-you)
Fixes #1595
> 1595 internet of things newsletter thank you

- run
Update ./run, and it should be compatible for PR demos!
Hopefully a comment will appear below about a demo...
> Update to latest ./run

- templates/shared-v1/_systems-management-tool.html
- templates/shared-v1/_ubuntu_advantage_server.html
- templates/support/plans-and-pricing.html
Updated the /support/plans-and-pricing page to VBT
- View the site locally in your web browser at: [http://0.0.0.0:8001/support/plans-and-pricing](http://0.0.0.0:8001/support/plans-and-pricing)
Fixes #1587
> 1587 support pricing

- templates/cloud/_nav_secondary-v1.html
- templates/cloud/_nav_tertiary-v1.html
- templates/cloud/thank-you.html
- templates/shared-v1/contextual_footers/_cloud_contact_us.html
- templates/shared-v1/contextual_footers/_cloud_juju.html
* update /cloud/thank-you to vbt
[page](http://0.0.0.0:8001/cloud/thank-you) compare to [server thank-you](https://www.ubuntu.com/server/thank-you) 
Fixes #1618
> 1618 cloud thank you

- templates/cloud/contact-us.html
* update /cloud/contact-us to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/cloud/contact-us)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory?preview=cloud-contact.png)
Fixes #1608
> 1608 cloud contact us

- static/sass/_v1_pattern_matrix.scss
- static/sass/styles-v1.scss
- templates/cloud/juju.html
- templates/shared-v1/contextual_footers/_cloud_contact_us.html
- templates/shared-v1/contextual_footers/_cloud_juju.html
- templates/shared-v1/contextual_footers/_cloud_newsletter.html
* update /cloud/juju to vbt
* replaced 3 broken charms and a few broken bundles with new ones from this issue #1888
* pointed to JAAS beta
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/cloud/juju)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-juju.png)
Fixes #1609
Fixes #1888
> 1609 cloud juju

- static/sass/styles-v1.scss
- templates/cloud/managed-cloud.html
* update /cloud/managed-cloud to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/cloud/managed-cloud)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-managed-cloud.png)
Fixes #1613
> 1613 cloud openstack managed cloud

- templates/support/thank-you.html
Updated the thank you page
- View the site locally in your web browser at: [http://0.0.0.0:8001/support/thank-you](http://0.0.0.0:8001//support/thank-you)
- See it's majesty at all viewports.
Fixes #1588
> Support thank you page to VBT

- static/sass/_v1_pattern_strip.scss
- templates/cloud/storage.html
* update /cloud/storage to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/cloud/storage)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-storage.png)
Fixes #1617
> 1617 cloud storage

- .github/PULL_REQUEST_TEMPLATE.md
Removed the extra closing parenthesis in the PR template
See that the number of opening and closing parens now match
> Remove extra closing parenthesis

- templates/base_index-v1.html
- templates/base_index.html
- templates/index_kylin.html
* update /index_kylin to vbt
* added a breadcrumb as well
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/index_kylin)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/1.%20Home?preview=homepage-china.png)
Fixes #1578
> update /index_kylin to vbt

- static/sass/section/_v1_homepage.scss
- static/sass/styles-v1.scss
- static/sass/takeovers/_kubernetes-webinar.scss
- templates/index.html
- templates/takeovers/_kubernetes_webinar.html
New takeover for the Kubernetes takeover.
- Check the homepage takeover at all viewports.
Fixes #1916
> New kubernetes webinar takeover.

- templates/internet-of-things/thank-you.html
* update /internet-of-things/thank-you to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/internet-of-things/thank-you)
- compare to the [containers design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/11.%20Forms?preview=containers-thank-you.png) and [demo](http://www.ubuntu.com-1597-internet-of-things-thank-you.demo.haus/internet-of-things/thank-you)
Fixes #1597
> 1597 internet of things thank you

- templates/about/contact-us/form/index.html
- templates/about/contact-us/index.html
- templates/shared-v1/_cloud-contact-us-form.html
Update /about/contact-us/form to VBT
- View the site locally in your web browser at: [http://0.0.0.0:8001/about/contact-us/form](http://0.0.0.0:8001/about/contact-us/form)
- Check the above page matches the patterns doc
Fixes #1890
> Update /about/contact-us/form to VBT

- templates/desktop/snappy.html
- templates/download/ubuntu-flavours.html
- templates/support/index.html
* add is-trisected to p-matrix with no grid pattern
- View the site locally in your web browser: 
* [desktop snappy](http://0.0.0.0:8001/desktop/snappy)
* [download flavours](http://0.0.0.0:8001/download/ubuntu-flavours)
* [support overview](http://0.0.0.0:8001/support)
Fixes #1951
> add is-trisected to p-matrix with no grid pattern

- templates/about/about-ubuntu/flavours.html
- templates/about/about-ubuntu/index.html
- templates/about/about-ubuntu/licensing.html
- templates/about/about-ubuntu/our-philosophy.html
Update /about strip spacing so that content has adequate space top and bottom.
Check strip spacing looks correct on the following pages (compared with live)
- http://www.ubuntu.com-about-strip-spacing.demo.haus/about/about-ubuntu
- http://www.ubuntu.com-about-strip-spacing.demo.haus/about/about-ubuntu/our-philosophy
- http://www.ubuntu.com-about-strip-spacing.demo.haus/about/about-ubuntu/licensing
- http://www.ubuntu.com-about-strip-spacing.demo.haus/about/about-ubuntu/flavours
Closes #1555, Closes #1552, Closes #1554
> Update /about strip spacing

- templates/about/about-ubuntu/conduct.html
Update spacing on /about-ubuntu/conduct
- View the site locally in your web browser at: [http://0.0.0.0:8001/about/about-ubuntu/conduct](http://0.0.0.0:8001/about/about-ubuntu/conduct)
- Check spacing here against live
Fixes #1550
> Update spacing on /about-ubuntu/conduct

- static/sass/_v1_pattern_pull_quotes.scss
- static/sass/_v1_pattern_strip.scss
- static/sass/styles-v1.scss
- templates/desktop/partners.html
* update /desktop/partners to vbt
* added an ‘is-compact’ class to pull quotes added as a [Vanilla proposal](https://github.com/vanilla-framework/vanilla-framework/issues/1108)
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/desktop/partners)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/5.%20Desktop?preview=desktop-partners.png) and the [demo](http://www.ubuntu.com-1661-desktop-partners.demo.haus/desktop/partners)
Fixes #1661
> update /desktop/partners to vbt

- static/sass/_v1_pattern_pull_quotes.scss
- templates/desktop/government.html
* update /desktop/government to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/desktop/government)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/5.%20Desktop?preview=desktop-government.png) and [demo](http://www.ubuntu.com-1660-desktop-government.demo.haus/desktop/government)
Fixes #1660
> update /desktop/government to vbt

- static/sass/_v1_pattern_sun-animation.scss
- static/sass/styles-v1.scss
- static/sass/v1_section/_v1_cloud.scss
- templates/cloud/index.html
- templates/cloud/shared/_events_overview.html
- templates/cloud/shared/_openstack_clients.html
Update /cloud to vbt including new foundation cloud section
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud](http://0.0.0.0:8001/cloud))
- Compare to the [design](https://www.dropbox.com/home/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/2.%20Cloud?preview=cloud-overview.png)
- Demo www.ubuntu.com-v1-cloud-setup.demo.haus
Foundation cloud: https://trello.com/c/tuTC0Ucn
Cloud overview: https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit#
> V1 cloud overview

- static/sass/_v1_pattern_pull_quotes.scss
- static/sass/_v1_pattern_strip.scss
- templates/desktop/enterprise.html
- templates/shared-v1/contextual_footers/_desktop_contact_us.html
- templates/shared-v1/contextual_footers/_support.html
* update /desktop/enterprise to vbt
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/desktop/enterprise)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/5.%20Desktop?preview=desktop-enterprise.png) and the [demo](http://www.ubuntu.com-1658-desktop-enterprise.demo.haus/desktop/enterprise)
Fixes #1658
> 1658 desktop enterprise

- templates/support/index.html
Small wording change.
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/1970
> Re-wording of a UA feature to make it more accurate

- templates/about/about-ubuntu/conduct.html
- templates/about/about-ubuntu/diversity.html
- templates/about/about-ubuntu/flavours.html
- templates/about/about-ubuntu/governance.html
- templates/about/about-ubuntu/index.html
- templates/about/about-ubuntu/licensing.html
- templates/about/about-ubuntu/our-philosophy.html
- templates/about/about-ubuntu/ubuntu-and-debian.html
- templates/about/base_about-v1.html
- templates/about/base_about.html
- templates/about/canonical-and-ubuntu.html
- templates/about/contact-us/form/index.html
- templates/about/contact-us/form/thank-you.html
- templates/about/contact-us/index.html
- templates/about/index.html
- Corrected indentation
- Switched divs for sections where appropriate
- Remove -v1 base template and switched include paths
- View the site locally in your web browser at: [http://0.0.0.0:8001/about](http://0.0.0.0:8001/about)
- Click through each page and verify that everything is hunky-dory
> Final sweep: /about

- templates/download/server/provisioning.html
* update /download/server/provisioning to vbt
* moved marketo js to extra footer block
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/download/server/provisioning)
- compare to the [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/new%20projects/vanilla%20update/Patterns%20inventory/9.%20Download?preview=download-server-provisioning.png)
Partially fixes #2004
> Update /download/server/provisioning to vbt

- static/js/scratch.js
Add back in the cookie policy JS which was erroneously removed.
- Make sure you remove the _cookies_allowed cookie
- Check that the cookie notification is displayed and it times out in 10 seconds
> Add back the cookie policy JS

- static/sass/_pattern_takeunders.scss
- templates/index.html
- templates/takeovers/takeunders/_iot-02-2017.html
- templates/takeovers/takeunders/_landscape-self-service.html
- templates/takeovers/takeunders/_stuck-stack.html
- New homepage takeunder
- Tidied and simplified the takeunder styling
- See the new takeunder (right hand) in all viewports
- [copy](https://docs.google.com/document/d/1rTHWfeuZbusH_nMBY2QJmoUSdKYTDQucLu1qYXZd_nU/edit?ts=595662bc#)
- [design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/takeunders/07.2017/Exportables?preview=07.2017-takeunders.jpg)
Fixes #2029 
[demo](http://www.ubuntu.com-stuck-stack.demo.haus/)
> Stuck stack takeunder.

- templates/cloud/partners.html
- templates/containers/index.html
- templates/desktop/partners.html
- templates/internet-of-things/gateways.html
- templates/internet-of-things/robotics.html
- templates/server/hyperscale.html
- templates/server/index.html
> Remove feeds temp

- templates/containers/index.html
- templates/containers/lxd.html
- templates/server/index.html
* updated lxd logo to new version
* [/server/](http://0.0.0.0:8001/server)
* [/containers](http://0.0.0.0:8001/containers)
* [/containers/lxd](http://0.0.0.0:8001/containers/lxd)
- see the new round logo
Fixes #2017
> Update lxd logo to new version

- templates/cloud/openstack/index.html
- templates/cloud/shared/_openstack-pie-chart.html
- templates/shared/contextual_footers/_cloud_contact_us.html
- templates/shared/contextual_footers/_download_cloud_buy_landscape.html
* updated /cloud/openstack text
- View the site locally in your web browser at: [page](http://0.0.0.0:8001/cloud/openstack)
- compare to the [copy doc](https://docs.google.com/document/d/12z6QEGpqMVbNPJOd5aUfn0VnXQ0Sa5YriEBLA7VGNwI/edit)  NOTE: the link to foundation cloud is to a contact us page for now
> Openstack updates

- static/sass/styles.scss
- templates/index.html
- templates/takeovers/_iot-business.html
- templates/takeovers/takeunders/_kubernetes.html
A new takeover for the IoT whitepaper.
- Check that the takeover and left-hand takeunder look good on all viewports
> IoT business takeover

- templates/legal/ubuntu-advantage/service-description.html
Moved a row in a table
- View the site locally in your web browser at: [http://0.0.0.0:8001/legal/ubuntu-advantage/service-description](http://0.0.0.0:8001/legal/ubuntu-advantage/service-description)
- See that the row "Ubuntu Legal Assurance programme" is now under ESM
> Move table row

- static/sass/_pattern_card.scss
- static/sass/styles.scss
- templates/cloud/plans-and-pricing.html
- templates/cloud/shared/_guest-list.html
- templates/internet-of-things/digital-signage.html
- templates/internet-of-things/index.html
- templates/shared/_ubuntu_advantage_cloud_per_node.html
- templates/shared/_ubuntu_advantage_cloud_service_provider.html
- templates/support/plans-and-pricing.html
Updated the price information of various cloud products.
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud/plans-and-pricing](http://0.0.0.0:8001/cloud/plans-and-pricing)
- See that the updates in the [copydoc](https://docs.google.com/document/d/1yZ7wClcmxGCqMyyyBJLO66Z3YlpT-4soWLFmJ6uXeMM/edit) are all addressed
- Go to: [http://0.0.0.0:8001/support/plans-and-pricing](http://0.0.0.0:8001/support/plans-and-pricing)
- See that the included shared portions updated for the other page look good here too
Fixes #2077
> Price updates

- deleted.yaml
- templates/410.html
- Update meta title of 410 page
- Add one more deleted page
- Simplify `deleted.yaml` syntax
QA
--
`./run` and check deleted pages still work as expected.
> Fix 410 page title

- navigation.yaml
- static/sass/styles.scss
- templates/cloud/contact-us.html
- templates/cloud/foundation-cloud/index.html
- templates/cloud/thank-you.html
- templates/templates/_product.html
Created a new Foundation Cloud Build page
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud/foundation-cloud](http://0.0.0.0:8001/cloud/foundation-cloud)
- Check against [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
Fixes #2094
> Add new Foundation Cloud Build page with supporting contact form edits and a new nav item.

- templates/index.html
- templates/takeovers/takeunders/_iot-business-report-08-2017.html
* designed, wrote and created the IoT business take-under
Fixes #2099
> Add iot business whitepaper takeunder

- templates/index.html
- templates/takeovers/takeunders/_iot-business-report-08-2017.html
Reverts canonical-websites/www.ubuntu.com#2132
> Revert "Revert "Add iot business whitepaper takeunder""

- templates/index.html
- templates/takeovers/_tell-us-your-story.html
Reverts canonical-websites/www.ubuntu.com#2133
> Revert "Revert "Add ‘tell us your story’ takeover""

- templates/internet-of-things/gateways.html
* updated resource strip to the new icon design
* updated the [copy doc](https://docs.google.com/document/d/1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU/edit#)
- View the site locally in your web browser at: [http://0.0.0.0:8001/internet-of-things/gateways](http://0.0.0.0:8001/internet-of-things/gateways)
- compare to the copy doc and the design to the /server/maas page 'Learn about MAAS' section
Fixes #2140
> Update iot gateway resource strip design for RTP

- .dockerignore
- Dockerfile
So it can be served with Kubernetes
``` bash
./run build
docker build -t www.ubuntu.com .
docker run -ti -p 8101:80 www.ubuntu.com
```
Browse to `http://127.0.0.1:8101` and behold the ubuntu.com website!
> Dockerfile for building www.ubuntu.com

- templates/server/maas/index.html
- templates/shared/_maas-support-pricing.html
Added new MAAS pricing table
- `./run`
- Visit [the maas page](http://localhost:8001/server/maas)
- Check the maas support price table against the [copydoc](https://docs.google.com/document/d/1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM/edit#)
> New maas pricing

- templates/server/maas/index.html
- templates/shared/_maas-support-pricing.html
Updated the title and content of the MAAS support pricing table
- View the site locally in your web browser at: [http://0.0.0.0:8001/server/maas](http://0.0.0.0:8001/server/maas)
- Compare the support pricing table to the [copydoc](https://docs.google.com/document/d/1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM/edit?ts=59ae60a6#)
> Small updates to the MAAS support pricing

- templates/shared/_maas-support-pricing.html
Updated the support operation times.
- View the site locally in your web browser at: [http://0.0.0.0:8001/server/maas](http://0.0.0.0:8001/server/maas)
- Check the MAAS support pricing table copy against the [copydoc](https://docs.google.com/document/d/1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM/edit#heading=h.jjeo4lsp2fnu)
> Maas pricing

- templates/server/maas/index.html
Updated heading
- View the site locally in your web browser at: [http://0.0.0.0:8001/server/maas](http://0.0.0.0:8001/server/maas)
- Check the heading of the support row against the [copydoc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit?ts=59aeab00#)
> Update MAAS support pricing section heading

- navigation.yaml
- templates/download/cloud/build-openstack.html
- templates/shared/contextual_footers/_download_cloud_buy_landscape.html
Created the new /download/cloud/build-openstack page
- View the site locally in your web browser at: [http://0.0.0.0:8001/download/cloud/build-openstack](http://0.0.0.0:8001/download/cloud/build-openstack)
- Check that the copy matches the [copy doc](https://docs.google.com/document/d/1b-KJ3Ext5geHtRU26UrXusLNoulSJ3jqvLl5NlwbyQo/edit#heading=h.wc7vrfwrcrio)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/2181
> Create new /download/cloud/build-openstack page

- templates/kubernetes/index.html
* updated the k8s datasteet on /kubernetes
* updated the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#heading=h.p7422u13r7qq)
- View the site locally in your web browser at: [k8s page](http://0.0.0.0:8001/kubernetes#enterprise)
* compare to the copy doc, or see that the datasheet has been updated
> Update datasheet on /kubernetes

- templates/server/maas/index.html
* Udpated MAAS logo on /server/maas page
- View the site locally in your web browser at: [maas page](http://0.0.0.0:8001/server/maas)
Fixes #2174
> Udpate MAAS logo on /server/maas page

- templates/cloud/index.html
* fix matrix pattern
* remove animation from /cloud
- View the site locally in your web browser at: [cloud overview](http://0.0.0.0:8001/cloud)
- see the animation has been removed and the matrix looks correct
> fix matrix pattern and remove animation from /cloud

- package.json
- static/sass/_pattern_link.scss
- yarn.lock
Copied package.json commands from snapcraft.io
- Check that external link icons look correct (shouldn't be black box)
Fixes Issue #660.
> Fixed auto-prefixing

- templates/kubernetes/index.html
Made a few minor edits to the /kubernetes page
- Check the page against the [copydoc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#)
Fixes #2225
> A number of small copy/layout updates

- templates/support/index.html
- Updated /support page intro paragraph RE: https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit
- Check that /support page intro has been updated to current copy doc requirements
- Check that code references current LTS release automatically
Fixes #2244
> Amended support page intro

- templates/cloud/foundation-cloud/index.html
- templates/cloud/index.html
- templates/cloud/managed-cloud.html
- templates/cloud/shared/_openstack_clients.html
- templates/containers/lxd.html
- templates/desktop/index.html
- templates/internet-of-things/digital-signage.html
- templates/internet-of-things/gateways.html
- templates/internet-of-things/robotics.html
- templates/kubernetes/index.html
- templates/server/index.html
- templates/server/maas/index.html
- templates/shared/_partner-logos.html
- templates/support/index.html
- templates/templates/_product.html
* replaced p-heading—muted with p-muted-heading
- View the site locally in your web browser at the following and confirm the fix: 
* [cloud/foundation-cloud/](http://0.0.0.0:8001/cloud/foundation-cloud/]
* [cloud/](http://0.0.0.0:8001/cloud/]
* [cloud/managed-cloud](http://0.0.0.0:8001/cloud/managed-cloud]
* [cloud/shared/_openstack_clients](http://0.0.0.0:8001/cloud/shared/_openstack_clients]
* [containers/lxd](http://0.0.0.0:8001/containers/lxd]
* [desktop/](http://0.0.0.0:8001/desktop/]
* [internet-of-things/digital-signage](http://0.0.0.0:8001/internet-of-things/digital-signage]
* [internet-of-things/gateways](http://0.0.0.0:8001/internet-of-things/gateways]
* …
> Replace .p-heading—muted with .p-muted-heading

- templates/desktop/developers.html
- templates/templates/base.html
- Updated /desktop/developers with 17.10 content as per [copydoc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#)
- Check that /desktop/developers has been properly updated with 17.10 content.
Closes #2287
> Updated /desktop/developers with 17.10 content

- templates/server/index.html
- templates/templates/base.html
- Updated /server with 17.10 content as per [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4)
- Check that /server has been properly updated with 17.10 content.
Closes #2288
> 2288 server page update

- static/sass/takeovers/_1710-release.scss
- Changed takeover bg colour to color-brand
- Check that the background load-in is relatively subtle
> Changed takeover bg colour to color-brand

- templates/takeovers/_1710_takeover.html
- Updated laptop image to one with dock on the bottom
- Check that the new laptop image has the dock on the bottom
> Updated laptop image to one with dock on the bottom

- templates/takeovers/_1710_takeover.html
- Changed laptop image back to one with dock on left
- Check image of laptop on takeover has the dock on the left instead of the bottom
Fixes #2321
> Changed laptop image back to one with dock on left

- templates/desktop/1710.html
Add hero image to the 1710 page
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/1710](http://0.0.0.0:8001/desktop/1710)
- Check the hero image looks ok
> Add hero image to the 1710 page

- templates/takeovers/_1710_takeover.html
Updated the image in the takeover
- See that the takeover is updated
Fixes #2340
> Replace takeover image

- templates/cloud/plans-and-pricing.html
- Small changes to pricing in Consulting Packages and Storage as per [copydoc](https://docs.google.com/document/d/1yZ7wClcmxGCqMyyyBJLO66Z3YlpT-4soWLFmJ6uXeMM/edit?ts=59e49888#)
- Navigate to /clouds/plans-and-pricing and check that it matches the copydoc
Fixes #2300
> Small amends to /cloud/plans-and-pricing

- templates/internet-of-things/index.html
* Update name again
- View the site locally in your web browser at: [http://0.0.0.0:8001/internet-of-things](http://0.0.0.0:8001/internet-of-things)
- Ensure the name matches what's on the linked website
> IoT Grove -> Grove IoT

- navigation.yaml
- templates/kubernetes/managed.html
- templates/shared/pricing/_kubernetes-managed.html
Added a new managed kubernetes section
- View the site locally in your web browser at: [http://0.0.0.0:8001/kubernetes/managed](http://0.0.0.0:8001/kubernetes/managed)
- Check the page content against the [copydoc](https://docs.google.com/document/d/1viNQgt99D2_b873Yd98iNT5vEzIbPQFgNI5XBFnszHk/edit#)
Fixes #2333
> Add new managed k8s page

- static/sass/_pattern_navigation.scss
Fix secondary nav 
- [http://0.0.0.0:8001/legal/terms-and-policies](http://0.0.0.0:8001/legal/terms-and-policies)
- [http://0.0.0.0:8001/cloud/thank-you](http://0.0.0.0:8001/cloud/thank-you)
- [http://0.0.0.0:8001/server/thank-you](http://0.0.0.0:8001/server/thank-you)
- Make sure the secondary nav is inline and not like the live versions, also check small and medium screens
Fixes #2392
> Fix secondary nav

- templates/download/cloud/try-openstack.html
Add sudo to code snippet
- View the site locally in your web browser at: [http://0.0.0.0:8001/download/cloud/try-openstack](http://0.0.0.0:8001/download/cloud/try-openstack)
- Make sure 'sudo' has been added to the code snippet as per issue
Fixes #2261 
Doc: https://docs.google.com/document/d/1TXnoE_RZCgms1K3beJNjzYLNzZEIjfeuNYg_zhkYQTA/edit
> Add sudo to code snippet

- templates/cloud/shared/_guest-list.html
- templates/core/index.html
- templates/kubernetes/index.html
* Updated the Azure logo per request from Microsoft
- View the site locally in your web browser at: [cloud/public-cloud](http://0.0.0.0:8001/cloud/public-cloud), [k8s](http://0.0.0.0:8001/kubernetes) and [core](http://0.0.0.0:8001/core)
> Updated the Azure logo

- templates/kubernetes/index.html
Update resources section
- Make sure the three resources in the issue have been made on the page
Issue/Card: https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2421
Fixes #2421
> Add new resources to /kubernetes

- templates/kubernetes/index.html
Replace datasheet and fly by add link
- Make sure the changes correlate to the changes requested in the doc
Fixes #2441 
Doc: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#
> Replace datasheet and add link

- templates/download/server/linuxone.html
- templates/download/server/thank-you-linuxone.html
- templates/shared/_call-sales-long.html
- templates/shared/_call-sales.html
* Updated sales phone numbers per [brief](https://docs.google.com/document/d/14CQg3WMMe2oHh4QirQI0Lm-mruY-OCMhZpjqsL8Njdo/edit)
* Updated z-series as well with UK number
- View the site locally in your web browser at the following URLS:
- [esm](http://0.0.0.0:8001/support/esm) and [copy doc](https://docs.google.com/document/d/1BK-XXECYJJllG8jIe3WN3X8EMo_3wBBa03nlzYDP8xE/edit)
- [support](http://0.0.0.0:8001/support) and [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#)
- [about contact-us](http://0.0.0.0:8001/about/contact-us) and [copy doc](https://docs.google.com/document/d/1v8mR0qE_AWVXBw0yQutdDaTmooodtMhc9dMzGqba4vg/edit#)
- [cloud …
> Updated sales phone numbers

- templates/kubernetes/index.html
- templates/shared/pricing/_kubernetes-consulting.html
Implement small text changes on /kubernetes page#2453
- Make sure the text changes requested in the copy doc have been made NB: Does not include the Rancher section
Fixes #2453 
Doc: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#
> Implement small text changes on /kubernetes

- templates/resources/index.html
- templates/templates/footer.html
Updated the resources page from design review
- Check it looks ok
Fixes https://github.com/ubuntudesign/web-squad/issues/265
> Updated the resources page from design review

- templates/resources/index.html
- templates/templates/footer.html
Somehow the design review branch got lost in the merging of branches. This is a cheery-pick of the two missing commits.
- The changes should be the same as https://github.com/canonical-websites/www.ubuntu.com/pull/2474
> Add resources design

- webapp/views.py
Filter by resources only
- Check that the first page only has resources
> Filter by resources

- templates/support/plans-and-pricing.html
- templates/templates/_tag_manager.html
- templates/templates/base.html
- Add hero CTA in order to set up the A/B test
- Add Optimize code
- View the site locally in your web browser at: [http://0.0.0.0:8001/support/plans-and-pricing](http://0.0.0.0:8001/support/plans-and-pricing)
- Make sure there's a CTA button in the 'hero'
Fixes #2483
Doc: https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#
> Add hero CTA in order to set up A/B test

- package.json
- static/sass/_pattern_navigation.scss
- static/sass/styles.scss
- yarn.lock
Update Vanilla and add hotfix for a max-width issue
- Check around the site
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1462
> Update Vanilla to v 1.6.3

- templates/cloud/foundation-cloud/index.html
* Update hardware requirements pdf for foundation cloud
* Uploaded the pdf
* Made datasheet and hardware requirements local links as they are only on assets.u.c
* Updated the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit?ts=5a26a7b1#)
- View the site locally in your web browser at: [fcb page](http://0.0.0.0:8001/cloud/foundation-cloud)
Fixes #2498
> Update hardware requirements pdf for foundation cloud

- navigation.yaml
- templates/security/index.html
- templates/shared/_case-study-itstrategen.html
- templates/shared/contextual_footers/_security_discussion.html
- templates/shared/contextual_footers/_security_esm.html
- templates/shared/contextual_footers/_security_further_reading.html
Add new security page
Todo: Find out where this is going to live in the UI
- View the site locally in your web browser at: [http://0.0.0.0:8001/security](http://0.0.0.0:8001/security)
- Make sure the page is as per [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#)
Fixes #2389 Fixes https://github.com/canonical-websites/www.ubuntu.com/pull/2495
Doc: https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#
> Add security page

- navigation.yaml
- templates/shared/contextual_footers/_telco_further_reading.html
- templates/telecommunications/index.html
Add Telco page 
**Contact us link needed for 'hero' not to be merged until this is added**
- View the site locally in your web browser at: [http://0.0.0.0:8001/telecommunications](http://0.0.0.0:8001/telecommunications)
- Make sure the page is as per [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit)
Fixes #2390 
Doc: https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit
> Add telco page

- static/sass/styles.scss
- templates/resources/index.html
- webapp/views.py
Add pagination to the resources page
- Check out the pagination at the bottom of the items
- Play around with the filtering and check it all works as expected
Fixes https://github.com/ubuntudesign/web-squad/issues/289
> Add pagination to the resources page

- templates/security/index.html
Small test change on security page
- Check copy matches the copy doc:
https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#heading=h.kbvgn35tfq4g
> Small test change on security page

- static/js/core.js
Fix syntax error
- See no JS error in console
> Fix core.js syntax error

- templates/legal/terms-and-policies/privacy-policy/index.html
* Converted list of cookies from table to list
* Removed extra line breaks
- View the site locally in your web browser at: [privacy policy page](http://0.0.0.0:8001/legal/terms-and-policies/privacy-policy), see that it is easy to read at many viewports
Fixes #1838
> Converted list of cookies from table to list

- templates/resources/index.html
- webapp/views.py
Make the posts and OrderedDict so they always display in the correct order.
- Check that the posts are displayed Cloud and server, IoT, Desktop
- Check filtering works as expected
Fixes https://github.com/ubuntudesign/web-squad/issues/299
> Make posts and OrderedDict

- templates/resources/index.html
- webapp/views.py
Add whitepapers to resources
- Filter by whitepapers
- Check it all works
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/2488
> Add whitepapers to resources

- webapp/views.py
Normalise resources so we get featured image
- Check it runs with no errors. Not many have images so its difficult to test.
> Normalise resources so we get featured image

- webapp/views.py
Display featured images on the homepage of resources
- Check there is an image on a post
> Featured homepage resources

- static/sass/styles.scss
- templates/resources/index.html
- webapp/views.py
Add global search functionality to the resources page.
- Search in the search box
- Check that the resources are search results for that search query
https://github.com/ubuntudesign/web-squad/issues/288
>  Add search functionality

- templates/download/desktop/index.html
Add bug link to disabled download notice
> Add bug link to disabled download notice

- templates/templates/_tag_manager.html
* Commented out google optimize code as it isn’t being used currently
- See that there are no errors in the console
> Commented out google optimize code

- templates/download/desktop/index.html
Replaced the but link with the wiki notice link as requested.
- Check code and see the link works
> Update the 17.10 download issue link

- package.json
- run
> Module support

- templates/download/core/kvm.html
- Created /download/core/kvm page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/core/kvm
- Check that content matches the [copydoc](https://docs.google.com/document/d/1FHIArLpuAyLe2gnDwymefvzc4Lg8dSGvN8QAl8wX18Q/edit#)
Fixes #2676
> 2676: Create /download/core/kvm page

- static/sass/_pattern_global-nav.scss
- templates/templates/base.html
- templates/templates/global-nav.html
- Built global nav according to [copydoc](https://docs.google.com/document/d/14EJRVoh2Hfc_K3ZFZbPPRkqeZ_NQUwDJp9vnyIuadf4/edit#heading=h.g1x8grgh273y) and [design](https://github.com/canonical-websites/www.ubuntu.com/issues/2643)
- Check that the global nav matches the [copydoc](https://docs.google.com/document/d/14EJRVoh2Hfc_K3ZFZbPPRkqeZ_NQUwDJp9vnyIuadf4/edit#heading=h.g1x8grgh273y) and [design](https://github.com/canonical-websites/www.ubuntu.com/issues/2643)
- Check that it closes if you click outside of it (if it's open)
Fixes #2649
> 2649: Build beta global nav

- webapp/views.py
If insights.ubuntu.com is unavailable, show a friendlier error message.
QA
--
First, `./run` and go to http://127.0.0.1:8001/resources and see it work.
Now, edit `webapp/views.py` line 42 to put a fake domain:
```
INSIGHTS_URL = 'https://fake-insights.ubuntu.com'
```
`./run` and go to http://127.0.0.1:8001/resources, see the error, and a 503 status.
> More resilient /resources

- webapp/views.py
QA
--
`./run`, check /resources
> Point directly at admin.insights for resources

- requirements.txt
- templates/cloud/index.html
- templates/index.html
- templates/shared/_insights_news_strip.html
- templates/templates/_further_reading_links.html
- webapp/templatetags/utils.py
Switched from RSS to JSON feeds
Check the feeds work on:
- /
- /cloud
- /server
> Replace the RSS feed loading with JSON feeds

- templates/legal/shared/_appendix-support-scope_toc.html
- templates/legal/ubuntu-advantage/service-description.html
Removed duplicated response times section
Fixed/reordered TOC
Fixes #2799
> UASD: Remove duplicate response times, clean up TOC

- templates/shared/pricing/_openstack-consulting.html
- templates/shared/pricing/_openstack-support.html
- templates/shared/pricing/_storage-support.html
- templates/shared/pricing/_ua-server-support.html
Fix UI issues on pricing page
Update SDN and SDS options for FCP
- Check against [copydoc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit)
Fixes #2810
> Fix UI issues on pricing page, update FCP SDN and SDS options

- static/sass/styles.scss
- static/sass/takeovers/_kubernetes-month.scss
- templates/index.html
- templates/takeovers/_kubernetes-month.html
Build takeover for Kubernetes Month
- Check that takeover matches design from https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2738
[Fixes #2738](https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2738)
> Build Kubernetes Month takeover

- templates/takeovers/_kubernetes-month.html
Changed copy of takeover
- Check copy matches [copy doc](https://docs.google.com/document/d/1Kr_Y_1LdB_AjqeVEdlAiEWVuNjj6o12WCQte_Uj1cSk/edit?ts=5aa1a997#heading=h.jc1a6wf9ixi5)
[Fixes #2738](https://github.com/canonical-websites/www.ubuntu.com/issues/2738#issuecomment-374249860)
> Update kubernetes takeover copy

- static/js/navigation.js
- static/sass/_pattern_navigation.scss
- templates/templates/_navigation-community.html
- templates/templates/_navigation-developer.html
- templates/templates/_navigation-download.html
- templates/templates/_navigation-enterprise.html
- templates/templates/_navigation.html
- templates/templates/base.html
- Added a slight fade in and vertical movement to beta nav dropdown
- Moved navigation javascript to navigation.js file
- Fixed formatting on Download tab
- Check that the navigation dropdowns animate
- Go to a page with breadcrumbs (e.g. /cloud) and test the animation there too
- Check that the Download tab doesn't have a second resource column
Fixes #2740
> 2740: Add animation to beta nav dropdown

- navigation.yaml
- templates/legal/trademarks/index.html
Add trademark page
- View the site locally in your web browser at: <http://0.0.0.0:8001/legal/trademarks>
- Make sure page matches [copy doc](https://docs.google.com/document/d/1o4P7HEIop3o4oibUH8rbj6mxIBmHakt-djZlpcpTW-I/edit)
Fixes #2825
> Add trademarks page

- navigation.yaml
- static/sass/_pattern_contribution.scss
- templates/internet-of-things/appstore.html
- templates/legal/data-privacy-enquiry/index.html
- templates/legal/terms-and-policies/thank-you.html
Create data privacy enquiry page and add new form
- View the site locally in your web browser at: <http://0.0.0.0:8001/legal/data-privacy-enquiry>
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1_sM2dGQNd5FRda2gITWL1jD1oWsIekAw2jCxPTPD1Ss/edit)
- Make sure the form functions as you would expect
Fixes #2732
> Build data privacy form

- templates/desktop/features.html
Replace apps with snaps
- View the site locally in your web browser at: <http://0.0.0.0:8001/desktop/features>
- Make sure apps match the [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit#heading=h.5c33fi1slr4o)
Fixes #2893
> Update apps to snaps

- templates/internet-of-things/gateways.html
- Updated list of resources/case studies, to reflect [copydoc](https://docs.google.com/document/d/1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU/edit#heading=h.5e4ji3wb6znp)
- Changed enterprise CTA to button
- View the site locally in your web browser at: [http://0.0.0.0:8001/internet-of-things/gateways](http://0.0.0.0:8001//internet-of-things/gateways)
- Check the page reflects the [copydoc](https://docs.google.com/document/d/1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU/edit#heading=h.5e4ji3wb6znp)
- Check links to Resources work
Fixes: #2879
> Update Gateways page 

- static/sass/styles.scss
- static/sass/takeovers/_1804-release.scss
- templates/index.html
- templates/takeovers/_1804-takeover.html
Build 18.04 release takeover
- Make sure homepage takeover matches designs
Fixes #2896
> Build 18.04 release takeover

- templates/kubernetes/index.html
Copy updates on Kubernetes page
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes>
- Make sure changes in [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#) are implemented
Fixes #2942
> Update kubernetes copy

- static/sass/_global-settings.scss
- static/sass/_pattern_navigation.scss
- templates/templates/_navigation-community.html
- templates/templates/_navigation-developer.html
- templates/templates/_navigation-download.html
- templates/templates/_navigation-enterprise.html
- updated the enterprise dropdown per the [copy doc](https://docs.google.com/document/d/14EJRVoh2Hfc_K3ZFZbPPRkqeZ_NQUwDJp9vnyIuadf4/edit#)
- updated the colours of the menus per meeting with Mark
- tightened the text and reduced the font-size in dropdowns per meeting with Mark
- Click on the 'Enterprise' dropdown and see the changes
> Update enterprise nav

- templates/index.html
Update homepage screenshot
- Check that laptop image matches attached asset
Fixes [#471](https://github.com/ubuntudesign/web-squad/issues/471)
> Update homepage screenshot

- templates/desktop/partners.html
- Updated Partners page to match [copydoc](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit#)
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/partners](http://0.0.0.0:8001//desktop/partners)
- Check if the page matches the [copydoc](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit#)
Fixes: #2882
> Partners page

- static/sass/_pattern_gaming.scss
- static/sass/_pattern_strip-photos.scss
- templates/desktop/features.html
- templates/shared/contextual_footers/_desktop_buy_preinstalled.html
- templates/shared/contextual_footers/_desktop_get_started.html
- templates/shared/contextual_footers/_professional_support.html
Update desktop features page
- View the site locally in your web browser at: <http://0.0.0.0:8001/desktop/features>
- Make sure page matches [copy doc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit)
Fixes #2893
> Update features page

- templates/cloud/public-cloud.html
Replace laptop image on `/cloud/public-cloud`
- View the site locally in your web browser at: <http://0.0.0.0:8001/cloud/public-cloud>
- Check that laptop image is [same as this](https://assets.ubuntu.com/v1/79439f53-Dell_XPS_Laptop_Front-Developer.png)
Fixes #2974
> Update screenshot image

- templates/server/livepatch.html
Replace background image and remove pictograms
- View the site locally in your web browser at: <http://0.0.0.0:8001//server/livepatch>
- Check that page matches the [copy doc](https://docs.google.com/document/d/1ObUSvkDcWOe01pmhh_Aryqxs87D8X2khbJbn3RgqZE0/edit#heading=h.mie3433mu0s8)
Fixes #2975
> Update livepatch page

- templates/download/cloud/build-openstack.html
Copy updates on `/download/cloud/build-openstack`
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/cloud/build-openstack>
- Check page matches [the copy doc](https://docs.google.com/document/d/1b-KJ3Ext5geHtRU26UrXusLNoulSJ3jqvLl5NlwbyQo/edit?ts=5ad500cc#)
> Copy updates on /download/cloud/build-openstack for 18.04

- templates/containers/lxd.html
Copy updates for `/containers/lxd`
- View the site locally in your web browser at: <http://0.0.0.0:8001/containers/lxd>
- Make sure page matches [the copy doc](https://docs.google.com/document/d/1wBAeklBtadvh4jKuoPFSJxoX2k0zyWt07ZI4nytwYSA/edit#)
Fixes #2976
> Update /containers/lxd page - 18.04

- templates/download/server/index.html
Copy updates on `/download/server`
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/server>
- Check that page matches the [copy doc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit#)
Fixes #2866
> Update /download/server page - 18.04

- templates/containers/docker-ubuntu.html
- templates/containers/index.html
- templates/containers/lxd.html
- templates/core/thank-you.html
- templates/kubernetes/index.html
- templates/shared/_call-sales-long.html
- templates/shared/_cloud-contact-us-form.html
- templates/shared/contextual_footers/_cloud_lxd.html
- templates/shared/forms/_desktop_help.html
- templates/shared/pricing/_kubernetes-consulting.html
- templates/support/thank-you.html
These are some suggestions. @pmahnke please take a look and comment on them, ask me if you don't understand why I did something.
When this is merged, I'll go and update the copy doc to reflect the changes you agreed with.
Also please consider https://github.com/canonical-websites/www.ubuntu.com/issues/3016.
> Suggestions for container section copy

- templates/telecommunications/index.html
Fixes the issues listed on the review issue.
- Check all the issues have been resolved from the issue below
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3013
> Copy doc changes for /telecommunications for 18.04

- templates/server/livepatch.html
Update copy
- View the site locally in your web browser at: <http://0.0.0.0:8001/server/livepatch>
- Check that the hero copy and three modules underneath match the [copy doc](https://docs.google.com/document/d/1ObUSvkDcWOe01pmhh_Aryqxs87D8X2khbJbn3RgqZE0/edit#)
Fixes #3005
> Update livepatch copy

- templates/cloud/index.html
Fixes the issues listed on the review issue.
- Check all the issues have been resolved from the issue below
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3007
> Copy doc changes for /cloud for 18.04

- templates/download/alternative-downloads.html
- templates/download/server/index.html
Updated the download/server page and the alt downloads page.
- View the site locally in your web browser at: [http://0.0.0.0:8001/download/alternative-downloads](http://0.0.0.0:8001/download/alternative-downloads)
- Check it matches the [copy doc](https://docs.google.com/document/d/1VhmFVE3dK81mE3zcC9FVA6f5SGJ-DHan7WWlrlfRcvo/edit#)
- Go to [http://0.0.0.0:8001/download/server](http://0.0.0.0:8001/download/server)
- Check that it matches the [copy doc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3023
> Download server 18.04

- .github/ISSUE_TEMPLATE.md
- added a note to the issue template to help people file bugs against Ubuntu OS
> Update the issue template to help people filing Ubuntu OS bugs

- templates/containers/index.html
- templates/kubernetes/index.html
> Replace "Canonical's Kubernetes" with better wording

- templates/takeovers/takeunders/_ubuntu-product-month.html
Update homepage takeunder
- Check that first homepage takeunder is Kubernetes and matches [design](https://user-images.githubusercontent.com/36884067/39246185-b625fafa-488d-11e8-8001-8d30905577a3.jpg) and [copy doc](https://docs.google.com/document/d/1Kr_Y_1LdB_AjqeVEdlAiEWVuNjj6o12WCQte_Uj1cSk/edit#)
Fixes #3049
> Build k8s takeunder

- templates/download/server/index.html
Update hero copy on `/download/server`
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/server>
- Make sure hero section matches the [copy doc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit#)
Fixes #3050
> Update server page copy

- navigation.yaml
- templates/desktop/index.html
- templates/download/desktop/index.html
- templates/download/index.html
- templates/download/server/index.html
- templates/download/server/s390x.html
- templates/download/server/thank-you-s390x.html
- templates/server/index.html
- templates/takeovers/_1804-takeover.html
Copy updates
- Check this addresses the issues below
Fixes #3056
> 3056 last minute fixes

- templates/desktop/index.html
Update copy on `/desktop`
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop](http://0.0.0.0:8001/desktop)
- Check that hero section matches [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit)
Fixes #3069
> Copy update

- templates/download/cloud/build-openstack.html
Change download link to relative link
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/cloud/build-openstack>
- Change download link as per issue below
Fixes #3075
> Make local link

- templates/desktop/features.html
QA
--
Compare the "Web browsing" image on http://www.staging.ubuntu.com/desktop/features to the demo
> Make browser image bigger

- templates/download/alternative-downloads.html
Update the server torrent link
> Update the server torrent link

- templates/resources/index.html
Update resources link to insights
- View the site locally in your web browser at: <http://0.0.0.0:8001/resources>
- Make sure link under main heading links to blog.ubuntu.com and not insights.ubuntu.com
Fixes [#517](https://github.com/ubuntudesign/web-squad/issues/517)
> Update resource link

- templates/download/server/s390x.html
- templates/download/shared/_get-ebook-security.html
- templates/download/shared/_get_ebook.html
- templates/download/shared/_get_ebook_maas.html
- templates/shared/_client-contact-us-form.html
- templates/shared/_cloud-contact-us-form.html
- templates/shared/contextual_footers/_cloud_newsletter.html
Replace NewsletterOpt-In with canonicalUpdatesOptIn site wide
- Check the code is ok
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3110
> Replace NewsletterOpt-In with canonicalUpdatesOptIn site wide

- templates/legal/companies.html
Add list of all Canonical companies page
- View the site locally in your web browser at: <http://0.0.0.0:8001/legal/companies>
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1RwfIptMKBpP3hWw0zLNVa7YT0JNO3dnm6wMPyl6sbGc/edit)
Fixes #3118
> Add all companies page

- templates/search.html
- webapp/templatetags/utils.py
Replace www.ubuntu.com with beta.ubuntu.com
- Do a search
- Make sure any links for ubuntu.com point to beta.ubuntu.com
> Update search result links

- templates/openstack/developer.html
Remove merge conflict that had found it's way onto the page
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/developer>
- Check that no merge conflicts are visible in the page
Fixes #3158
> Fix merge conflict in code

- package.json
- templates/resources/index.html
- yarn.lock
Bump global nav version
- Make sure navigation has a blog link and not an insights link
Fixes [#512](https://github.com/ubuntudesign/web-squad/issues/512)
> Bump global nav version

- templates/_gdpr.html
> Add the GDPR test page

- templates/shared/_client-contact-us-form.html
- templates/shared/_cloud-contact-us-form.html
-Added google's reCAPTCHA to main forms
- View the site locally in your web browser at: [cloud forms](http://0.0.0.0:8001/cloud/contact-us) and [device
forms](http://0.0.0.0:8001/desktop/contact-us)
- see that there is a recaptcha and that the form still works (note that it might not work on all domains)
Fixes #3190
> Added google's reCAPTCHA to main forms

- static/sass/_pattern_navigation.scss
- static/sass/_vanilla-placeholders.scss
- templates/templates/_navigation-download-h.html
- templates/templates/_navigation-enterprise-h.html
• Copy changes (please double check)
• Layout changes (3 columns for the first row, added a tablet breakpoint to top row; difficult to add to rest aas the grid is 6 col on tablet, and we have 4 elements that wouldn't divide nicely. We should consider changing the number of columns on tablet to make this more flexible)
> 170beta nav update

- static/sass/styles.scss
- static/sass/takeovers/_openstack-queens.scss
- templates/index.html
- templates/takeovers/_openstack-queens.html
Build OpenStack Queens takeover
- Check the takeover matches the design in the issue
Fixes #3196
> Build OpenStack Queens takeover

- templates/legal/terms-and-policies/index.html
Update terms and policies page
- View the site locally in your web browser at: <http://0.0.0.0:8001/legal/terms-and-policies/systems-information-notice>
- Check that page matches [the copy doc](https://docs.google.com/document/d/1p3ZWroZ3nkw8XJJdPvPxSlWGYcLZLT8UbUVuppBcyHk/edit#)
Fixes #3209
> Update terms and policies page

- templates/legal/terms-and-policies/terms.html
Update title of terms and conditions page
- View the site locally in your web browser at: <http://0.0.0.0:8001/legal/terms-and-policies/terms>
- Make sure title (h1) has been updated as per [copy doc](https://docs.google.com/document/d/1wlfspMWQ2ztlMC7vfk_CxKpekZ3U-HAoK_0OwpcFcfo/edit)
Fixes #3213
> Update terms and conditions page

- templates/openstack/developer.html
Update page according to the [copy doc](https://docs.google.com/document/d/1QIXOAlCDV2cyQqU5uEW2kpITobf7OkFHr-tsEvjd_1Q/edit#)
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/developer>
- Check that changes have been made as per the [copy doc](https://docs.google.com/document/d/1QIXOAlCDV2cyQqU5uEW2kpITobf7OkFHr-tsEvjd_1Q/edit#) - please resolve comments as you verify they are correct
Fixes #3200
> Update openstack developer page

- templates/download/shared/_get-ebook-security.html
- templates/download/shared/_get_ebook.html
- templates/download/shared/_get_ebook_maas.html
- templates/shared/_client-contact-us-form.html
- templates/shared/_cloud-contact-us-form.html
Add hidden field <input type="hidden" name="Consent_to_Processing__c" value="yes" /> to all contact forms
> Add fields to forms

- templates/download/cloud/build-openstack.html
- templates/download/server/provisioning.html
- templates/download/shared/_get-ebook-security.html
- templates/download/shared/_get_ebook.html
- templates/download/shared/_get_ebook_maas.html
- templates/shared/_client-contact-us-form.html
- templates/shared/_cloud-contact-us-form.html
Updated maas command
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/server/provisioning>
- Check that commands have been updated as per the [copy doc](https://docs.google.com/document/d/12GXYcP9WrOgoso6Sf3bQql6nALRUzpdlcRW3Gbu-npM/edit#)
Fixes #3238
> Update maas command

- .travis.yml
- templates/internet-of-things/appstore.html
Added a Rigado logo
- View the site locally in your web browser at: [http://0.0.0.0:8001/internet-of-things/appstore](http://0.0.0.0:8001/internet-of-things/appstore)
- check it looks ok
Fixes: #3251
> added rigado logo

- static/js/navigation.js
- static/sass/_global-settings.scss
- static/sass/_pattern_global-nav.scss
- static/sass/styles.scss
- templates/templates/global-nav.html
Move global nav to bottom of page on mobile
- Resize the browser to mobile size
- See that the global nav is at the bottom of the page and is good
Fixes #3231
> Fixing global nav

- templates/internet-of-things/index.html
Changed col size of a heading as per @anasereijo 
- View the site locally in your web browser at: [http://0.0.0.0:8001/internet-of-things](http://0.0.0.0:8001/internet-of-things)
- check the col size has changed
#3264
> changed col size

- static/sass/_pattern_footer.scss
Change dotted black border in footer to solid grey border
- Check that the border on the footer is solid grey and not dotted black
Fixes #3267
> Change footer border

- static/sass/takeovers/_private_cloud_economics.scss
- templates/takeovers/_private_cloud_economics.html
Update takeover copy and background gradient colours
- Make sure takeover copy matches [copy doc](https://docs.google.com/document/d/1trccDAaYcapXudN-pvNKcUciRceIZhFA14uNSG3u8dg/edit?ts=5b0f2252)
- Make sure background gradient of takeover is blue
> Takeover update

- templates/takeovers/_private_cloud_economics.html
- UTMized takeover link
- Ensure the takeover link contains UTM parameters
> UTMize takeover link

- static/js/navigation.js
- static/sass/_pattern_global-nav.scss
- static/sass/_pattern_navigation.scss
- templates/templates/_navigation-developer-h.html
- templates/templates/_navigation-download-h.html
- templates/templates/_navigation-enterprise-h.html
- templates/templates/_navigation.html
- templates/templates/global-nav.html
Increase size of logos in Enterprise and Products navigation
This PR is branched from https://github.com/canonical-websites/www.ubuntu.com/pull/3315 and therefore that should be merged first.
- Open the Enterprise navigation and the Products navigation and see the logos are 32px
Fixes #3319
> 3319 change icon size

- templates/download/server/thank-you.html
- templates/download/shared/_get_ebook.html
- templates/openstack/developer.html
- templates/openstack/install.html
- Add ebook section to `/download/server/thank-you`
- Remove ebook section from `/openstack/developer`
- Remove ebook section from `/openstack/install`
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/server/thank-you>
- Check that ebook section is on page
Fixes #3283
> Add ebook to server download thank you page

- templates/takeovers/_private_cloud_economics.html
Add a comma to the copy on the takeover
- See that the takeover copy matches the [copy doc](https://docs.google.com/document/d/1trccDAaYcapXudN-pvNKcUciRceIZhFA14uNSG3u8dg/edit?ts=5b0f2252)
Fixes #3372
> Update copy of takeover

- static/sass/_pattern_feedback.scss
- static/sass/styles.scss
- templates/base_index.html
- templates/shared/_feedback.html
- templates/templates/base.html
Add site feedback button and modal
- See the feedback button at the bottom of the screen
- See that it behaves as expected
Fixes #3198
> Add beta feedback modal

- static/js/navigation.js
Remember nav state when leaving page
This PR is branched from https://github.com/canonical-websites/www.ubuntu.com/pull/3315 and therefore should be merged after that PR
- Open one of the navigation tabs, then click a link to another page
- Hit the browsers back button and see that the previously selected menu is open
- Close the menu by clicking the active tab or the overlay beneath it
- Go to another page
- Hit the back button and see that the menu is still closed
Fixes #3273
> 3273 nav anchors

- static/sass/_pattern_matrix.scss
- templates/kubernetes/index.html
- templates/shared/pricing/_kubernetes-consulting.html
- templates/shared/pricing/_kubernetes-enterprise-support.html
Update `/kubernetes`
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes>
- See that it matches the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#)
Fixes #3356
> 3356 kubernetes overview page

- static/js/navigation.js
- static/sass/_pattern_global-nav.scss
- static/sass/_pattern_matrix.scss
- templates/templates/global-nav.html
Add login menu to global nav
- View the site locally in your web browser at: <http://0.0.0.0:8001/>
- See the login dropdown menu is there and that it matches the design
Fixes #3286
> Add login menu

- static/sass/styles.scss
- templates/openstack/managed.html
Update `openstack/managed`
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/managed>
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#)
Fixes [#639](https://github.com/ubuntudesign/web-squad/issues/639)
> 639 openstack managed page

- navigation.yaml
- templates/kubernetes/_get_ebook.html
- templates/kubernetes/install.html
- templates/shared/contextual_footers/_cloud_bootstack.html
- templates/shared/contextual_footers/_cloud_further_reading.html
- templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
- yarn.lock
Add Kubernetes install page
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/install>
- See that page matches the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#)
Fixes #3362
> 3362 kubernetes install page

- templates/cloud/index.html
> Adds missing “of”

- templates/ai/base_ai.html
Add base template for ai pages
- See that there is a `base_ai.html` template
> Add base template for ai pages

- static/sass/_pattern_card.scss
- templates/openstack/consulting.html
- templates/shared/_resources_openstack.html
Update `openstack/consulting`
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/consulting>
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
Fixes [#637](https://github.com/ubuntudesign/web-squad/issues/637)
> Update openstack consulting page

- templates/templates/_navigation-community-h.html
Update community menu
- Open the community menu
- See that it matches the [copy doc](https://docs.google.com/document/d/1TgsBJdGgsP4KrGiz5kU5QYkdGSlKqhAVnZGnCJgshYY/edit)
Fixes #3294
> Update community menu

- templates/kubernetes/contact-us.html
- templates/kubernetes/thank-you.html
- update the contact-us [copy doc](https://docs.google.com/document/d/1Zf_xYK57S5T_T3HtKCPK7bf7vMVIMNuhJggSb-EdgAc/edit#heading=h.ywnvlhsclzyk)
- updated the thank-you [copy doc](https://docs.google.com/document/d/1rkHUgJ4WqEL9Eu7GFgikr5dtIRVYNDjl8YV-tU4irLg/edit#heading=h.azkkey9h30vf)
- http://0.0.0.0:8001/kubernetes/contact-us
- http://0.0.0.0:8001/kubernetes/contact-us?product=kubernetes
- http://0.0.0.0:8001/kubernetes/contact-us?product=kubernetes-managed
- http://0.0.0.0:8001/kubernetes/contact-us?product=kubernetes-install
- http://0.0.0.0:8001/kubernetes/contact-us?product=kubernetes-features
- http://0.0.0.0:8001/kubernetes/contact-us?product=kubernetes-e …
> Create kubernetes contact-us and thank-you pages

- templates/templates/base.html
Remove link to global nav stylesheet
See that the link to the global nav stylesheet is removed
> Remove dead global nav link

- templates/ai/contact-us.html
- templates/ai/thank-you.html
- Created the ai contact-us [copy doc](https://docs.google.com/document/d/185NqOTBSWuVIAppRIT0K7hcQzTHm6Rk7XyZXcjNTFQM/edit#heading=h.lzlfbccmhrvi)
- Created the ai thank-you [copy doc](https://docs.google.com/document/d/1fLjt6qfj8p03d0wTZdN_yWbBcoi4umT2lGeiFT_c6NQ/edit#heading=h.m39yhaeljg9a)
- http://0.0.0.0:8001/ai/contact-us?product=ai-index-workshop
- http://0.0.0.0:8001/ai/contact-us?product=ai-index-assessment
- http://0.0.0.0:8001/ai/contact-us?product=ai-index-managed
- http://0.0.0.0:8001/ai/contact-us?product=ai-install
- http://0.0.0.0:8001/ai/contact-us
- http://0.0.0.0:8001/ai/thank-you?product=ai-index-workshop
- …
> Create the /ai contact-us and thank-you pages

- templates/kubernetes/_get_ebook.html
- templates/kubernetes/install.html
Update copy on `/kubernetes/install` page
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/install>
- See that the page matches the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#heading=h.yb98vv47gv6p)
Fixes #3449
> k8s install copy updates

- templates/ai/features.html
- templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
Built the new AI features page.
- View the site locally in your web browser at: [http://0.0.0.0:8001/ai/features](http://0.0.0.0:8001/ai/features)
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1DT5nCRSJH-OkvDmlyKh6vVhofeHPHZJHTTBDNu44wCY/edit#)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3341
> Create the AI features page

- static/sass/_pattern_feedback.scss
- templates/templates/base.html
- Swap position of livechat and feedback buttons
- Adjust height of livechat button to match feedback button
As the livechat button only appears on the live site and feedback button is not yet on the live site, the only way this can be seen in the browser is if you open the web inspector and paste the following code before the closing `</body>` tag:
```
<style>
#livechat-compact-container {
right: 0 !important;
height: 2.3rem !important;
background: #e95420 !important;
}
#livechat-compact-container iframe {
top: .25rem !important;
}
@media (min-width: 620px) {
#livechat-compact-container {
right: 160px !important;
border-top-left-radius: .125rem;
border-top-right-radius: .125rem;
}
}
</style>
<div id="livechat-compact-container" style="position: fixed;bottom: 0px;right: 15px;width: …
```
> Livechat button

- static/sass/_pattern_lists.scss
- templates/ai/install.html
Created the AI install page.
- View the site locally in your web browser at: [http://0.0.0.0:8001/ai/install](http://0.0.0.0:8001/ai/install)
- Check that the page matches the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit#)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3344
> Create the AI install page

- navigation.yaml
- templates/kubernetes/features.html
Add `/kubernetes/features`
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/features>
- See that is matches the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#)
Fixes #3361
> Add kubnetes features page

- templates/public-cloud/index.html
Update style of card on `/public-cloud`
- View the site locally in your web browser at: <http://0.0.0.0:8001/public-cloud>
- See that card has been updated to match proposed design
Fixes #3377
> Update card style

- navigation.yaml
- templates/ai/index.html
- templates/kubernetes/index.html
Add `/ai` page
- View the site locally in your web browser at: <http://0.0.0.0:8001/ai>
- See that it matches the [copy doc](https://docs.google.com/document/d/1mJq8PxH8FVRVF9i1Xzh0f6M73eyjqZE4NaKYHRcRAKM/edit#)
Fixes #3338 
Fixes #3466
> 3338 ai index page

- templates/ai/features.html
Update images as per copy doc
- View the site locally in your web browser at: <http://0.0.0.0:8001/ai/features>
- Check that images are correct
Fixes #3464
> 3464 image updates

- static/js/navigation.js
- templates/containers/index.html
- templates/containers/shared/_whitepaper.html
- templates/templates/_navigation-community-h.html
- templates/templates/_navigation-developer-h.html
- templates/templates/_navigation-download-h.html
- templates/templates/_navigation-enterprise-h.html
- templates/templates/_navigation.html
Update the containers page with the latest copy changes.
- View the site locally in your web browser at: [http://0.0.0.0:8001/containers](http://0.0.0.0:8001/containers)
- Make sure the page matches the [copy doc](https://docs.google.com/document/d/1OtyfNeA--EJgpgvDzqcbJ8jqa6d9H5H9xyxHNxcKXvc/edit#heading=h.o1s37lxyci13)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3468
> Update the containers page

- static/sass/styles.scss
- templates/download/server/s390x.html
- design updates 
- removed card
- removed divided line
- removed equal heights
- lowered h2 
- View the site locally in your web browser at: [/download/server/s390x](http://0.0.0.0:8001/download/server/s390x)
Fixes #3476
> 3476 design fix s390x page

- static/js/navigation.js
- static/sass/_pattern_global-nav.scss
- templates/templates/_navigation-community-h.html
- templates/templates/global-nav.html
Fix mobile version of global nav
- Look at the global nav on mobile (at the bottom of the page) and see it looks/works as expected
Fixes #3392
> 3392 mobile global nav

- templates/shared/pricing/_kubernetes-enterprise-support.html
Update Kubernetes pricing table
- View the site locally in your web browser at: <http://0.0.0.0:8001/support/plans-and-pricing>
- See that page matches the [copy doc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#)
Fixes #3505
> Update kubernetes pricing table

- templates/kubernetes/index.html
- templates/shared/pricing/_kubernetes-enterprise-support.html
Remove duplicated link
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes>
- See that there is only one 'For more information about Kubernetes support, contact us ›' link
Fixes #3537
> 3537 duplicated link

- templates/server/hyperscale.html
Move hyperscale image
- View the site locally in your web browser at: <http://0.0.0.0:8001/server/hyperscale>
- See that the image is in the hero and not the second section
Fixes #3553
> Move hyperscale image

- templates/internet-of-things/digital-signage.html
Update copy on `/internet-of-things/digital-signage`
- View the site locally in your web browser at: <http://0.0.0.0:8001/internet-of-things/digital-signage>
- See that page matches the [copy doc](https://docs.google.com/document/d/1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ/edit)
Fixes #3551
> IOT copy updates

- static/sass/styles.scss
- templates/openstack/consulting.html
- templates/shared/_resources_openstack.html
- templates/shared/pricing/_openstack-consulting.html
Copy changes as per copy doc
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/consulting>
- See that page matches the [copy doc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
Fixes #3485
> Copy updates for openstack consulting

- templates/templates/_navigation-download-h.html
Change padding at top of download menu
- See that padding at top of download menu is 24px
Fixes #3526
> Change padding on download menu

- static/sass/_pattern_footer.scss
Change height of footer hr
- See that footer border is only 1px high
Fixes #3512
> Fix footer border width

- static/sass/styles.scss
- templates/shared/_cloud-contact-us-form.html
Change colour of fieldset border
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/contact-us>
- See that grey box on form has a border
Fixes #3528
> 3528 fieldset border

- templates/kubernetes/contact-us.html
- templates/shared/_cloud-contact-us-form.html
Uppcase title on kubernetes contact page and add padding around captcha
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes/contact-us?product=kubernetes-explorer>
- See that the title is capitalised and that there is sufficient padding around the captcha
Fixes #3521
> 3521 capitalise title

- templates/templates/global-nav.html
Update videos link in global nav
- See the videos link goes to resources filtered by video
Fixes #3517
> Update videos link in global nav

- templates/shared/pricing/_kubernetes-enterprise-support.html
Fix table horizontal scroll on mobile
- View the site locally in your web browser at: <http://0.0.0.0:8001/kubernetes>
- See that the table scrolls horizontally on small screens
Fixes #3564
> Fix table on mobile

- templates/resources/index.html
Fix resource filters on mobile
- View the site locally in your web browser at: <http://0.0.0.0:8001/resources>
- See that the resource filters work on mobile
Fixes #3513
> Fix resource filters on mobile

- static/sass/_pattern_card.scss
- templates/download/cloud/index.html
Center align card images
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/cloud>
Fixes [#696](https://github.com/ubuntudesign/web-squad/issues/696)
> Center align card images

- templates/templates/_navigation-developer-h.html
Fix developer menu top padding on mobile
- See that developer menu has correct padding on mobile
Fixes #3522
> Fix padding on developer menu on mobile

- templates/openstack/index.html
Change image on openstack hero
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack>
- See that the hero image has been updated
Fixes #3618
> Update image on openstack hero

- templates/ai/index.html
- templates/kubernetes/features.html
- templates/openstack/features.html
- templates/templates/_navigation-developer-h.html
- templates/templates/_navigation-enterprise-h.html
Fix a number of links to none existing pages.
- Check that the travis linkchecker passes
> Fix the links to none existing pages

- templates/openstack/managed.html
Update copy on openstack managed page
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/managed>
- See that requested copy changes have been done
Fixes #3653
> Update openstack managed page

- templates/openstack/features.html
Update copy as requested in issue
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/features>
- See that requested copy changes have been done
Fixes #3642
> Udpate copy on openstack features page

- templates/openstack/managed.html
Fix spacing between buttons in openstack managed hero
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack/managed>
- See that button spacing is correct in hero
Fixes #3645
> 3645 spacing

- static/sass/_pattern_lists.scss
Fix alignment of middots in footer
- See middots are centre aligned in footer
Fixes #3627
> Fix middots in footer

- templates/ai/features.html
Updated `/ai/features` as per the copy doc
- View the site locally in your web browser at: <http://0.0.0.0:8001/ai/features>
- See that page matches the [copy doc](https://docs.google.com/document/d/1DT5nCRSJH-OkvDmlyKh6vVhofeHPHZJHTTBDNu44wCY/edit#)
Fixes [#699](https://github.com/ubuntudesign/web-squad/issues/699)
> 699 ai features

- templates/ai/install.html
Fixed some misspelt microk8s. Updated the [copy doc](https://docs.google.com/document/d/1KVyyvZsDyrfoi5tK2m5SLWs9YuHg9hgqVz0c8cWHsf8/edit)
- Check the spelling is correct in the code
> Fix typos of microk8s

- templates/takeovers/_private_cloud_economics.html
> Add UTMs to takeover

- templates/templates/_tag_manager.html
- Update to the new Optimize container ID
- Update page-hiding snippet to match Optimize proposed defaults (also matches what was used on the blog.ubuntu.com homepage experiment) 
If you have access to the right Google Optimize account, you should be able to verify experiments without errors.
**Update:** Successfully created an experiment on the demo website. :+1:
> Update Google Optimize container ID

- templates/openstack/index.html
- templates/shared/_resources_openstack.html
- templates/shared/contextual_footers/_cloud_contact_us.html
- templates/shared/contextual_footers/_cloud_ubuntu_advantage.html
Update openstack page
- View the site locally in your web browser at: <http://0.0.0.0:8001/openstack>
- See that the page matches the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#)
Fixes #3638
> 3638 update openstack page

- static/js/navigation.js
- static/sass/_pattern_global-nav.scss
- static/sass/_pattern_navigation.scss
- templates/templates/_navigation-community-h.html
- templates/templates/_navigation-developer-h.html
- templates/templates/_navigation-download-h.html
- templates/templates/_navigation-enterprise-h.html
Increase speed on dropdown menus
- See that the dropdown speed is acceptable
Fixes #3619
> Increase speed on navigation transition

- templates/cloud/thank-you.html
- templates/contact-us/form/thank-you.html
- templates/containers/thank-you.html
- templates/core/thank-you.html
- templates/desktop/thank-you.html
- templates/download/desktop/thank-you.html
- templates/download/server/thank-you-linuxone.html
- templates/download/server/thank-you-s390x.html
- templates/download/server/thank-you.html
- templates/internet-of-things/thank-you.html
- templates/server/maas/thank-you.html
- templates/server/thank-you.html
- templates/templates/base.html
Fixes #3508
QA
--
Umm... just check the code and that the site still runs?
> noindex thank-you pages

- static/js/navigation.js
- static/sass/_pattern_lists.scss
- templates/templates/_navigation-developer-h.html
Update to latest developer menu
- See that page matches [the copy doc](https://docs.google.com/document/d/1l6Ywrj_HRcg2-WYKorjRAUE_dvPdwZYPtL4a6z66Uc8/edit#)
Fixes [#709](https://github.com/ubuntudesign/web-squad/issues/709)
> Update developer menu

- templates/download/desktop/index.html
Change padding on header icon cards
- View the site locally in your web browser at: <http://0.0.0.0:8001/download/desktop>
- See that padding under header icons is sufficient
Fixes #3698
> Change padding on header icon cards

- templates/shared/pricing/_maas-support.html
- templates/shared/pricing/_openstack-support.html
- templates/shared/pricing/_ua-desktop-support.html
- templates/shared/pricing/_ua-server-support.html
Fix horizontal scrolling tables
- View the site locally in your web browser at: <http://0.0.0.0:8001/support/plans-and-pricing>
- See that tables scroll horizontally on mobile
Fixes #3702
> Fix table horizontal scrolling on mobile

- requirements.txt
- templates/search.html
- webapp/settings.py
- webapp/urls.py
- webapp/views.py
This reverts commit e4802a623f800e65e6b41f426141e767165d7762.
> Revert "Replace GSA with Google Custom Search"

- templates/ai/index.html
- templates/download/server/arm.html
- templates/kubernetes/features.html
- templates/kubernetes/index.html
- templates/kubernetes/managed.html
- templates/openstack/features.html
- templates/openstack/index.html
- templates/openstack/install.html
- templates/openstack/managed.html
- templates/server/hyperscale.html
- templates/shared/contextual_footers/_maas-faq.html
- templates/templates/global-nav.html
Make sure all instances of "bare metal" are sentence case and unhyphenated
- <http://0.0.0.0:8001/ai>
- <http://0.0.0.0:8001/download/server/arm>
- <http://0.0.0.0:8001/kubernetes/features>
- <http://0.0.0.0:8001/kubernetes>
- <http://0.0.0.0:8001/kubernetes/managed>
- <http://0.0.0.0:8001/openstack/features>
- <http://0.0.0.0:8001/openstack>
- <http://0.0.0.0:8001/openstack/install>
- <http://0.0.0.0:8001/openstack/managed>
- <http://0.0.0.0:8001/server/hyperscale>
- See that all instances of "bare metal" are sentence case and unhyphenated
Fixes [#716](https://github.com/ubuntudesign/web-squad/issues/716)
> Fix bare metal everywhere

- templates/cloud/foundation-cloud/index.html
Updated the link to the Foundation Cloud Build datasheet. 
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud/foundation-cloud](http://0.0.0.0:8001/cloud/foundation-cloud)
- Check that the links go to the updated datasheet.
Fixes: #3741
> Update FCB datasheet

- templates/openstack/consulting.html
- Added FCB hardware requirements datasheet to openstack consulting page
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/consulting](http://0.0.0.0:8001/openstack/consulting)
- Check the links go to the updated datasheet
- Check the filename matches the structure
- Check the link is updated on the copydoc https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#
Fixes: #3756
> Fcb hardware req

- templates/cloud/foundation-cloud/index.html
Updated the FCB hardware requirements on the foundation cloud build page on master
- View the site locally in your web browser at: [http://0.0.0.0:8001/cloud/foundation-cloud](http://0.0.0.0:8001/cloud/foundation-cloud)
- Check that the datasheet goes to the updated one
Fixes: #3762
> Update FCB requirements datasheet

- static/sass/_utility-animations.scss
- static/sass/styles.scss
- static/sass/takeovers/_private_cloud_economics.scss
- static/sass/takeovers/_rigado-webinar.scss
- templates/index.html
- templates/takeovers/_private_cloud_economics.html
- templates/takeovers/_rigado_webinar.html
- Add new takeover
- Show old takeover after first session
- See that the takeover matches the design
- Start a new session (e.g. open page in another tab) and you should see the old takeover
Fixes [#726](https://github.com/ubuntudesign/web-squad/issues/726)
> Add new takeover

- static/sass/_utility-animations.scss
- static/sass/styles.scss
- static/sass/takeovers/_private_cloud_economics.scss
- static/sass/takeovers/_rigado-webinar.scss
- templates/index.html
- templates/takeovers/_private_cloud_economics.html
- templates/takeovers/_rigado_webinar.html
- Add new takeover
- Show old takeover after first session
- See that the takeover matches the design
- Start a new session (e.g. open page in another tab) and you should see the old takeover
Fixes [#726](https://github.com/ubuntudesign/web-squad/issues/726)
> Add new takeover to beta site

- .gitignore
- .travis.yml
- Dockerfile
- package.json
- requirements.txt
- static/global-nav
- Improve Dockerfule to use Bionic and Talisker
- Copy global-nav in place as part of the standard build
Fixes #3814
QA
--
``` bash
docker build --tag ubuntu.com --build-arg COMMIT_ID=`git rev-parse HEAD` .
docker run -ti -p 8901:80 ubuntu.com
```
Go to http://localhost:8901 and http://localhost:8901/_status/check
> Improvements to building of production image

- templates/shared/_insights_news_strip.html
- Updated blog section styling on homepage
- Check that the blog section matches the original [design](https://github.com/ubuntudesign/web-squad/issues/728)
Fixes ubuntudesign/web-squad#752
> Update blog section styling on homepage

- .gitignore
- Dockerfile
- entrypoint
QA
--
``` bash
./run
```
See that it mentions "Booting worker" 3 times, and that it runs the site.
> Use 3 workers for beta

- Dockerfile
- entrypoint
QA
--
``` bash
./run
```
See that it mentions "Booting worker" 3 times, and that it runs the site.
> Use 3 workers

- templates/500.html
- templates/search.html
QA
--
Ask Robin for the search API key, then:
`./run --env SEARCH_API_KEY=xxx`
And go to http://0.0.0.0:8001/search?q=kubernetes, see it works.
> Fix search template

- requirements.txt
QA
--
`./run`, check things still work
> Be more accurate about statsd requirement

- templates/shared/pricing/_openstack-packages.html
- Updated the OpenStack packages pricing (as seen on /openstack)
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack](http://0.0.0.0:8001/openstack)
- Check the page matches the [copydoc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#heading=h.k1h44d84khlr)
Fixes: #3930
> Update openstack packages pricing

- templates/engage/de/vmware-to-openstack.html
> Moving the webinar up on the page EVEN HIGHER :)

- templates/shared/pricing/_kubernetes-enterprise-support.html
- templates/shared/pricing/_maas-support.html
- templates/shared/pricing/_openstack-consulting.html
- templates/support/plans-and-pricing.html
Update the content to the plans and pricing page
- View the site locally in your web browser at: [http://0.0.0.0:8001/support/plans-and-pricing](http://0.0.0.0:8001/support/plans-and-pricing)
- Check that the copy matches the [copy doc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#)
> Update the content to the plans and pricing page

- entrypoint
QA
--
**Run script**
`./run`, check you see "= Running talisker with development settings =" in the output, and check the site works at http://localhost:8001.
**Docker image**
``` bash
docker build --tag ubuntu --build-arg COMMIT_ID=`git rev-parse --short HEAD` .
docker run -ti -p 8901:80 ubuntu
```
Check you *don't* see "= Running talisker with development settings =" in the output, and check the site works at http://localhost:8901.
> Align Talisker with other projects

- static/sass/_pattern_global-nav.scss
- static/sass/_pattern_navigation.scss
- Fixed z-index of navigation
- Open the main navigation and check that it looks good
- Open the global nav and check that it looks good
- Go to any page that has a secondary nav (e.g. http://0.0.0.0:8001/ai)
- Open the main navigation and check that it looks good
- Open the global nav and check that it looks good
> Fix dropdown z-index

- templates/takeovers/_de-vmware-to-os.html
* UTMize de takeover
- Ensure german takeover on the `/index_de` page has UTMs
> UTMize de takeover

- templates/engage/de/openstack-made-easy.html
This is a new landing page (in German) to house the OpenStack Made Easy ebook in German.
> OpenStack Made Easy German Landing Page

- templates/shared/_systems-management-tool.html
- templates/support/index.html
Cleanup of support page
- [Copydoc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#heading=h.se64at4drd8e)
Fixes #3620
> Cleanup /support page

- templates/kubernetes/install.html
- Updated the text of the /kubernetes/install page
- View the site locally in your web browser at: [http://0.0.0.0:8001/kubernetes/install](http://0.0.0.0:8001/kubernetes/install)
- Compare to the [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#heading=h.yb98vv47gv6p)
Fixes #3999
> Updated the text of /kubernetes/install

- templates/legal/managed-services/service-description.html
Change order of older versions on "Managed Services description" page
- Check that the order matches the [copy doc](https://docs.google.com/document/d/1kHRTIFjuK3pbK3kp-hKGrlKsKBKG7_HnotmN4iy8_eU/edit#)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4044
> Change order of older versions on "Managed Services description" page

- templates/engage/de/vmware-to-openstack.html
Updated the page to reflect the German takeover and AI / ML webinar page.
> Vmware to openstack de

- templates/engage/de/openstack-made-easy.html
Quick form ID fix for openstack DE landing page
> Fix form id - Openstack Made Easy DE

- templates/shared/pricing/_kubernetes-consulting.html
- templates/shared/pricing/_openstack-support.html
- templates/shared/pricing/_ua-server-support-add-ons.html
- templates/support/plans-and-pricing.html
Updates to the plans and pricing page content
- Make sure the changes match the [copy doc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/3971
> Updates to the plans and pricing page content

- static/js/navigation.js
- templates/base_index.html
- templates/index.html
- templates/takeovers/_ai_webinar-2018-10-01.html
- templates/takeovers/_de-vmware-to-os.html
- templates/takeovers/_financial-services.html
- templates/takeovers/_multicloud-operations.html
- templates/takeovers/_rigado_webinar.html
- templates/takeovers/_robotics-takeover.html
- templates/takeovers/_tackling_iot.html
- webapp/views.py
Takeovers now change based on the users browser default language. Takeovers are now only display for a particular region based on the language detected on the browser.
- Changed the default browser language to German (Deustche) or German
- Refresh the multiple times to German Takeover
Fixes #4081
> Detect language

- static/js/navigation.js
Reset navigation.js to it previous version.
> Reset navigation.js

- templates/desktop/developers.html
- Added the What's new in Ubuntu 18.10 section to /desktop/developers
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/developers](http://0.0.0.0:8001/desktop/developers)
- compare to the [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#)
Fixes #4101
> Added the What's new in Ubuntu 18.10 section to /desktop/developers

- templates/kubernetes/managed.html
- templates/shared/pricing/_kubernetes-managed.html
- Copy updates to the kubernetes/managed page
- View the site locally in your web browser at: [http://0.0.0.0:8001/kubernetes/managed](http://0.0.0.0:8001/kubernetes/managed)
- Compare to the [copy doc](https://docs.google.com/document/d/15jzhasokjH5Ql9Za56ZxRknXNNhEXYdIFXXtLODGxns/edit#heading=h.6ur0dg5t8cpo)
Fixes #4114
> Copy updates to the kubernetes managed page

- package.json
- static/sass/_global-settings.scss
- static/sass/_pattern_chart.scss
- static/sass/_pattern_feedback.scss
- static/sass/_pattern_footer.scss
- static/sass/_pattern_gaming.scss
- static/sass/_pattern_lists.scss
- static/sass/_pattern_navigation.scss
- static/sass/_pattern_strip-photos.scss
- static/sass/_pattern_ubuntu_intro.scss
- static/sass/_utility-animations.scss
- static/sass/mixins/_full-width-breakout.scss
- static/sass/print.scss
- static/sass/styles.scss
- static/sass/takeovers/_1804-release.scss
- static/sass/takeovers/_ai-webinar.scss
- static/sass/takeovers/_financial-services.scss
- static/sass/takeovers/_kubernetes-month.scss
- static/sass/takeovers/_openstack-queens.scss
- static/sass/takeovers/_private_cloud_economics.scss
- static/sass/takeovers/_rigado-webinar.scss
- static/sass/takeovers/_ubuntu-product-month.scss
- static/sass/takeovers/_vmware-to-os.scss
Lint the scss files so the CI passes.
- Skip the code has no errors
- Check the sass-lint CI passes
> Lint the scss

- requirements.txt
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4175
QA
--
`./run`, check the site runs fine
> Use compatible talisker and prometheus versions

- static/js/desktopStatistics.js
- static/js/dummyData.js
- templates/desktop/statistics.html
Changed the Graphics setup page to match the visual design.
- Check out this feature branch user 
- go to the url http://0.0.0.0:8001/desktop/statistics
- Check that the layout matches the design https://github.com/canonical-websites/www.ubuntu.com/issues/4094
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4128
> User report page graphics setup 4128

- static/js/desktopStatistics.js
- static/js/dummyData.js
- static/sass/_pattern_desktop-statistics.scss
- templates/desktop/statistics.html
Updated the Firware section of the user report page to match design.
- Check out this feature branch user 
- go to the url http://0.0.0.0:8001/desktop/statistics
- Check that the layout matches the design https://github.com/canonical-websites/www.ubuntu.com/issues/4094
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4127
> User report page firmware 4127

- static/js/desktopStatistics.js
- static/js/dummyData.js
- static/sass/_pattern_desktop-statistics.scss
- templates/desktop/statistics.html
Updated the legend for desktop spec section, increased the height of the horizontal barchart for popular screens section, updated live data for firmware section
- Check out this feature branch user 
- go to the url http://0.0.0.0:8001/desktop/statistics
- Check that the layout matches the design https://github.com/canonical-websites/www.ubuntu.com/issues/4094
> User report page grafana data 3952

- static/js/desktopStatistics.js
- static/js/dummyData.js
- templates/desktop/statistics.html
Updated Clean install to match live data and changed the barchart to match the design spec.
- Check out this feature branch user 
- go to the url http://0.0.0.0:8001/desktop/statistics
- Check that the layout matches the design https://github.com/canonical-websites/www.ubuntu.com/issues/4094
> User report page clean install

- templates/desktop/statistics.html
Updated the firmware description on the statistics page
- View the site locally in your web browser at: [http://0.0.0.0:8001/desktop/statistics](http://0.0.0.0:8001/desktop/statistics)
- Check that the firmware content matches the [copy doc](https://docs.google.com/document/d/153OkfZHM_eTfAoUZF3f38VMtiFzaa2txB9B2lvs8xXA/edit)
Fixes #4256
> Update the firmware description

- templates/index.html
- templates/takeovers/_juju-webinar-takeover.html
Created the juju takeover page 
- View the site locally in your web browser at: [http://0.0.0.0:8001/statistics#desktop-specs](http://0.0.0.0:8001/statistics#desktop-specs)
- Check it matches https://docs.google.com/document/d/1e2qjJUrcgZVsvYeR9GgCu6nHUWFMkcDEstAKTqE4k5M/edit#heading=h.meo0azuz09li
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4145
> Added juju takeover

- package.json
- static/sass/styles.scss
- templates/index.html
- templates/takeovers/_1810-takeover.html
- templates/takeovers/_ai_webinar-2018-10-01.html
- templates/takeovers/_de-vmware-to-os.html
- templates/takeovers/_tackling_iot.html
- Refresh pages 4 times and you should see 4 different takeovers
- Change the browser language to German and refresh 5 times you should see 5 takeovers including a german one.
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4268
> Takeovers styling

- templates/engage/ubuntu-core-and-kura.html
New landing page for a whitepaper on /engage
> New landing page - Ubuntu Core, Kura Whitepaper

- templates/index.html
- templates/takeovers/_1810-takeover.html
- templates/takeovers/_ai_webinar-2018-10-01.html
- templates/takeovers/_german_takeover_k8.html
- templates/takeovers/_german_takeover_openstack_made_easy.html
- templates/takeovers/_juju-webinar-takeover.html
- templates/takeovers/_tackling_iot.html
Moved the locales to the index page and passed through the include. Updated the locales to reflect the master content document.
- Refresh and see that the locales matches the [master content document](https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit#gid=564832475)
> Fix the locale of the takeovers

- templates/engage/de/what-can-you-do-with-kubernetes.html
Updated hero image area and page CTA button text
> Update German K8s webinar page hero strip

- templates/openstack/what-is-openstack.html
Add image to What is openstack section
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/what-is-openstack](http://0.0.0.0:8001/openstack/what-is-openstack)
- Check that the image is aligned as specified in the [copy doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#)
Fixes https://github.com/ubuntudesign/web-squad/issues/862
> Image for what is openstack added

- templates/index.html
- templates/takeovers/_multicloud-solutions.html
Created multicloud takeover for solutions
- Refresh the page and until you see the multicloud solutions takeover, and follow the QA steps to make sure that it matches. Here are the [copy doc](https://docs.google.com/document/d/1H0sNENNBW3Xzy-SvMtjztEkLX4tU4x4ebiAvP0TDhuI/edit#) and [design specs](https://github.com/ubuntudesign/web-squad/issues/867)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4301
> Multi cloud takeover 868

- templates/openstack/managed.html
Updated OpenStack page updates - Managed build to match [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#heading=h.uasr0ce2c7v3) 
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/managed](http://0.0.0.0:8001/openstack/managed)
- Check the [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#heading=h.uasr0ce2c7v3) and check to make sure that the page changes are reflected in the page
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4215
> Open stack page updates managed build 4215

- templates/engage/kubernetes-case-study.html
Copy changes - updating language to 'Ubuntu K8s' where possible
> Copy changes to K8s case study landing page

- requirements.txt
fix vulnerability on requests module found by github
- `./run`
- make sure it works as usual
> Upgrade requests to v2.20.0

- templates/kubernetes/managed.html
Reverts canonical-websites/www.ubuntu.com#4309
> Revert "Updated /kubernetes/managed copy"

- templates/core/index.html
- View the site locally in your web browser at: [/core](http://0.0.0.0:8001/core)
- Check that the images in the Features section are the same as the[ copy doc ](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#heading=h.muim5mbixesh)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4203
> Changed the feature section images as per design spec

- templates/openstack/features.html
Updated openstack/features Page based on [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/features](http://0.0.0.0:8001/openstack/features)
- 
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4212
> Openstack page updates features 4212

- templates/openstack/install.html
Made updates as per [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#)
- View the site locally in your web browser at: [http://0.0.0.0:8001/openstack/install](http://0.0.0.0:8001/openstack/install)
- Check that the changes match the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#)
Fixes  https://github.com/canonical-websites/www.ubuntu.com/issues/4294
> Openstack Install copy doc changes

- static/sass/_layout_documentation.scss
- templates/kubernetes/docs/shared/_side-navigation.html
Add some responsive styling and functionality to the docs theme.
- Go to /kubernetes/docs
- Check the navigation works on small screens
- Check it opens and closes
- Click Logging and see the page loads
Fixes https://github.com/ubuntudesign/web-squad/issues/901
> Make the documentation template responsive

- templates/legal/ubuntu-advantage-service-description/index.html
Fixing what looks like a rogue search and replace
> Remove japanese from main UASD page

- templates/engage/ubuntu-18-10.html
Updated the CTA from register to view on-demand
> 18-10 CTA update

- templates/legal/shared/_appendix-support-scope.html
- templates/legal/ubuntu-advantage-service-description/index.html
Updated UASD
[Copydoc](https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit#)
Fixes #4396
> Updates to UASD

- templates/takeovers/_compliance-webinar.html
- Changed the copy of the compliance takeover, as requested by Marketing
- Check the text has changed
Fixes: #4414
> Updated copy of compliance takeover

- templates/index.html
- templates/takeovers/_appelix-takeover.html
Build the Appelix takeover
- Refresh until you see the Appelix takeover
- Check the takeover copy matches the [copy doc](https://docs.google.com/document/d/1I8TUiG_u1tksV1ElqzTTaO5ECjdVhKiA1Y71HRAWfMc/edit)
- Check it matches [the design](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/166#issuecomment-439872559)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4380
> Appelix takeover

- templates/kubernetes/features.html
- Updated /kubernetes/features copy
- View the site locally in your web browser at: [/kubernetes/features](http://0.0.0.0:8001/kubernetes/features)
- Compare to and resolve the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit?ts=5bd759c1#)
Fixes #4310
> Updated /kubernetes/features copy

- templates/engage/developer-desktop.html
- [New landing page](https://www-ubuntu-com-canonical-websites-pr-4425.run.demo.haus/engage/developer-desktop): developer desktop whitepaper at `/engage/developer-desktop`
- Ensure [the page](https://www-ubuntu-com-canonical-websites-pr-4425.run.demo.haus/engage/developer-desktop) matches the copy doc, and that the downloadable is what's expected.
> First pass at developer desktop wp lp

- templates/kubernetes/index.html
- Used correct capitalisation of MicroK8s
- Added link to https://microk8s.io/#quick-start for install instructions
Fixes #4424 
Fixes #4429
> Updating MicroK8s copy & links

- templates/kubernetes/features.html
- templates/kubernetes/index.html
- templates/kubernetes/install.html
- templates/kubernetes/partners.html
- text updated in k8s section
- check the overview, features, install and partners
> More kubernetes name updates

- templates/kubernetes/features.html
- Updated /kubernetes/features from the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/preview?ouid=109108038802750262539)
- View the site locally in your web browser at: [/kubernetes/features](http://0.0.0.0:8001/kubernetes/features)
- Compare to the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit)
Fixes #4498
> Updated /kubernetes/features with SEO and text updates

- templates/templates/_navigation-enterprise-h.html
> 15-11-18 updates

- static/js/stickyNav.js
- static/sass/_pattern_matrix.scss
- static/sass/_pattern_separator.scss
- static/sass/styles.scss
- templates/core/index.html
- templates/desktop/statistics.html
- Complete update to the /core page
- View the site locally in your web browser at: [/core](http://0.0.0.0:8001/core)
- Compare to the [copy doc](https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#heading=h.xnpkx4ypduk)
Fixes #4508
> Update to the /core page

- static/sass/styles.scss
- templates/base_index.html
- templates/core/index.html
Add basic modal contact us on core page
- Go to /core
- Open the console and enter `dynamicContactUs();`
- Click any of the contact buttons and see the modal is displayed
- Click through the modal and check it goes back and forward
- Once complete check the Network tab has a form submission
- Check the contents of the request is correct
> Add basic modal contact us on core page

- requirements.txt
Fixes (minor) security issue.
QA
--
`./run`, check site works as expected.
> Update to Django v1.11.18

- templates/kubernetes/docs/docker-registry.md
- templates/kubernetes/docs/upgrading.md
Kubernetes Docs updates - 
- Added new registry options
- Clarified some steps of the upgrading doc
check the pages: 
- [http://0.0.0.0:8001/kubernetes/docs/docker-registry](http://0.0.0.0:8001/kubernetes/docs/docker-registry)
- [http://0.0.0.0:8001/kubernetes/docs/upgrading](http://0.0.0.0:8001/kubernetes/docs/upgrading)
> Kubernetes docs updates

- navigation.yaml
- templates/esm/faq.html
- templates/esm/index.html
- Updated the /esm page and added a /esm/faq page
- View the site locally in your web browser at: [http://0.0.0.0:8001/esm](http://0.0.0.0:8001/esm) and [http://0.0.0.0:8001/esm/faq](http://0.0.0.0:8001/esm/faq)
- Compare them to the copy docs [esm](https://docs.google.com/document/d/1BK-XXECYJJllG8jIe3WN3X8EMo_3wBBa03nlzYDP8xE/edit#) and [faq](https://docs.google.com/document/d/13V50u0YuwVOzLDyIczxLyErdsxwTfoeWh9DRdM2Nda4/edit#)
Fixes #4615
> Update ESM and add FAQ page

- static/js/dynamic-contact-form.js
- templates/base_index.html
- templates/templates/footer.html
Add the interactive form to the homepage and also added a document ready listener to the script to pick up contact buttons in the footer.
- Go to the homepage
- Try adding "#get-in-touch" to the URL
- Close and click the contact button in the footer
- Check it opens the general form
> Add the interactive form to the homepage

- static/js/dynamic-contact-form.js
- templates/shared/forms/interactive/_embedded.html
- templates/shared/forms/interactive/_general.html
Fixed the list of review points from exec review.
- Go to /core#get-in-touch
- Check that the bullet list is complete from the issue.
Fixes #4631
> Address interactive form feedback

- templates/engage/finserv-multi-cloud.html
* New landing page for the finserv multi-cloud wp
* [Copy doc](https://docs.google.com/document/d/1Wkl-yzrQ9M0Uz7p71vDfi2KzQ0B_PTbQPsktKLCyJzc)
- Ensure [the page](https://www-ubuntu-com-canonical-websites-pr-4642.run.demo.haus/engage/finserv-multi-cloud) matches the copy doc and the form takes you to the right download
> finserv-multi-cloud lp

- templates/engage/finserv-multi-cloud.html
- templates/engage/fr/esm.html
* Update meta description on /engage/finserv-multi-cloud
* Update copy on /engage/fr/esm
> Small copy changes on /engage/fr/esm and /engage/finserv-multi-cloud

- templates/openstack/_base_openstack.html
- templates/shared/forms/interactive/_openstack.html
Add interactive forms to the OpenStack section
- Go to /openstack
- Click a contact link/button
- Check the form that opens matches the [copy doc](https://docs.google.com/document/d/140P1Z--hkWuW9-S2cNAR_uCW3BRW1VPKtFWkDtc7eBk/edit#)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4589
> Add interactive forms to the OpenStack section

- templates/engage/iot-disk-encryption.html
* New landing page for FDE whitepaper at `/engage/iot-disk-encryption`
* [Copy doc](https://docs.google.com/document/d/1zAv3ouUrzQcQDw2DSefaePXcMu35BAumIMpzqmIkycs/edit)
- Ensure the page matches the copy doc
> FDE whitepaper lp

- static/js/dynamic-contact-form.js
- templates/openstack/managed.html
- templates/shared/forms/interactive/_bootstack.html
- templates/shared/forms/interactive/_embedded.html
- templates/shared/forms/interactive/_general.html
- templates/shared/forms/interactive/_kubernetes.html
- templates/shared/forms/interactive/_openstack.html
- templates/shared/forms/interactive/_robotics.html
- templates/shared/forms/interactive/_support.html
Improve the summary messaging from the interactive forms and applied the design points to the header of the modal.
- Go to /core#get-in-touch
- Fill in the form until you reached the third page which asks for your details
- Open the console and enter `Comments_from_lead__c.value`
- Check that the information is correct and looks better then on live
> Improve the summary messaging from the interactive forms

- templates/ai/features.html
- templates/ai/index.html
- templates/ai/install.html
- templates/shared/forms/interactive/_kubeflow.html
Created the kubeflow form and integrated it with the ai section.
- Go to /ai#get-in-touch
- Check the form matches the [copy doc](https://docs.google.com/document/d/1PSLBJWNqWfonEfQFrWvJ4NpqCHcBoDR2wWmk8IldbOg/edit#heading=h.6fmcpt1fngq7)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4596
> Add interactive forms to the kubeflow section

- templates/openstack/features.html
Update the openstack/features content for UA4I
- Go to /openstack/features
- Check it matches the [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edi)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4726
> Update the openstack/features content for UA4I

- templates/shared/_call-sales.html
- templates/shared/_case-study-allan-gray.html
- templates/shared/_case-study-itstrategen.html
- templates/support/index.html
Updated /support for UA for Infrastructure
- View the site locally in your web browser at: [http://0.0.0.0:8001/support](http://0.0.0.0:8001/support)
- Compare to the [copy doc](https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit#)
Fixes #4703
> Update /support overview

- templates/livepatch/index.html
- Updated the /livepatch page for UA for Infrastructure
- View the site locally in your web browser at: [http://0.0.0.0:8001/livepatch](http://0.0.0.0:8001/livepatch)
- Compare to the [copy doc](https://docs.google.com/document/d/1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A/edit#)
Fixes #4725
> Updated the /livepatch page for UA for Infrastructure

- templates/ai/features.html
- templates/ai/index.html
Update the AI section
- Check the content in the /ai and /ai/features pages match [the copy docs](https://drive.google.com/drive/u/0/folders/1ktGxpcrrvlpJktHGtTEG1xI_UIhVg-Jo)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4706
> UA for Infrastructure - Update the AI section

- templates/server/index.html
- templates/shared/_release_schedule.html
- Update for UA for I
- View the site locally in your web browser at: [http://0.0.0.0:8001/server](http://0.0.0.0:8001/server)
- Compare to the [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit?ts=5c6dca12#)
Fixes #4728
> Update server overview for UA for I

- templates/engage/14-04-esm.html
Here's the updated copy, layout for ESM Engage Page 
> ESM Engage Page Update

- templates/kubernetes/index.html
- templates/legal/ubuntu-advantage-service-description/index.md
- templates/shared/pricing/_landscape.html
- templates/shared/pricing/_maas-support.html
- templates/shared/pricing/_storage-support.html
- templates/shared/pricing/_ua-desktop-support.html
- templates/shared/pricing/_ua-for-infrastructure-physical.html
- templates/shared/pricing/_ua-for-infrastructure-virtual.html
- templates/support/plans-and-pricing.html
- Updated the /support/plans-and-pricing page with updates from product mgmt and mkting
- Cleaned up the layout of tables to be more consistent
- View the site locally in your web browser at: [/pricing](http://0.0.0.0:8001/pricing)
- compare to the [copy doc](https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#heading=h.9q52wbh3nkil)
Fixes #4748
> Updated the /support/plans-and-pricing page

- templates/templates/_tag_manager.html
Disable Google Optimize script as it's not being used.
> Disable Google Optimize script

- templates/containers/index.html
update link on containers
- Compare with [copydoc](https://docs.google.com/document/d/1OtyfNeA--EJgpgvDzqcbJ8jqa6d9H5H9xyxHNxcKXvc/edit#)
Fixes #4767
> update link on containers

- templates/takeovers/_ubuntu-core-full-disk-encryption.html
Reverts canonical-websites/www.ubuntu.com#4737
> Revert "update full disc encryption cta"

- templates/takeovers/_ubuntu-core-full-disk-encryption.html
Update the FDE takeover button and link.
> Update the FDE takeover link

- package.json
- yarn.lock
Update global-nav dep to @canonical/global-nav
- Check global nav displays correctly
> Update global-nav dep to @canonical/global-nav

- templates/index.html
- templates/takeovers/_ai_webinar.html
- templates/takeovers/_german_ai_webinar.html
Build the AI/ML webinar takeover in German
Fixed the existing takeovers to work in the new system.
- Set you browser lang to German
- Refresh the homepage until you see the German AI takeover
- Check it matches [the copy doc](https://docs.google.com/document/d/1CQNGRpldiJ1js5fRczKc8kDDZOlrVyNkfYIJ3r8OCVc/edit)
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/4809
> Create the AI/ML german takeover

- templates/download/iot/intel-nuc.html
* NUC Core image update
* [Copy tweaks](https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit#) to streamline install steps
* Don't merge: SE team needs to review
> Update NUC image + copy tweaks
