static/js/src/dynamic-contact-form.js, templates/engage/base.html, templates/shared/_client-contact-us-form.html, templates/shared/_cloud-contact-us-form-german.html, templates/templates/base.html
- Move google recaptcha script into form so that it doesn't load on every page, even if you never fill in a form
- *Note - please confirm I did it correctly in the `static/js/src/dynamic-contact-form.js`
- http://0.0.0.0:8001/openstack#get-in-touch
- http://0.0.0.0:8001/openstack/contact-us
- http://0.0.0.0:8001/engage/it/deployment-azienda-manuale
- See that the recaptcha loads and works
Fixes #5229
=> Move google recaptcha script into form load

templates/openstack/index.html
- Created a flat version of the OpenStack charm diagram and added image tag tool
- See that the page goes from
|    | Requests | MBs | resouces | time |
| -- | -------- | --- | -------- | ---- |
| original |294|3|8.9|7.8min|
| this version |63|1.5|3|2.15min|
=> Remove openstack charm diagram from /openstack

navigation.yaml
Update navigation item from Fips to FIPS in Azure
- View the site locally in your web browser at: http://0.0.0.0:8001/azure
- See that the navigation is FIPS and not Fips
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8867
=> Update Fips to FIPS

templates/security/esm.html
Reverts the revert canonical-web-and-design/ubuntu.com#8293
- Check that https://ubuntu-com-8847.demos.haus/security/esm matches the [copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#)
=> Revert "Revert "Add notification banner to ESM page""

static/sass/_pattern_cve.scss
To match the Vanilla font size scale.
- Changed CVE table font size from 0.8rem to 0.875rem.
- Check that the table still looks okay
No issue, but raised by @lyubomir-popov in [vanilla-framework#3399](https://github.com/canonical-web-and-design/vanilla-framework/issues/3399).
=> Changes CVE table from 0.8rem to 0.875rem

templates/advantage/index.html
Inline the sign out button in the advantage dashboard
- Login
- See the Sign out button is inline and dense on large screens
- Wraps on medium and small screens
- See there is padding now between the text and the button on small screens 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8633
=> Inline the sign out button in the advantage dashboard

templates/advantage/subscribe/index.html
- Change 'Software only' to 'Software and security updates only'
- See that IS: “Software only” is now “Software and security updates only”
Fixes #8887
=> Copy update on /advantage/subscribe

templates/sitemap_index.xml, webapp/app.py, webapp/views.py
- Redirect sitemap generated by yoast and wordpress to ubuntu.com/blog/sitemap.xml 
- Add sitemap index for blog
- Add sitemaps for blog
Known issue:
- Unknown Links for webinars
- I am not excluding tags here, I would say that this is ok for now as a first iteration of the sitemap madness
- Connect to the VPN
- http://0.0.0.0:8001/blog/sitemap.xml
- Make sure that the links in there are ok!
=> Redirect wordpress sitemap to ubuntu.com/blog

templates/security/docker-images.html
- Update copy on /security/docker-images with links to Amazon
- View the site locally in your web browser at: http://0.0.0.0:8001/security/docker-images
- Compare to and resolve comment in the [copy doc](https://docs.google.com/document/d/1zZibtjU141e4mBxo_0PtfYxJ6e5fyaaAdFZ6v945XAM/edit#)
Fixes #8895
=> Update copy on /security/docker-images

static/js/src/chart.js, static/js/src/release-chart.js
Added an optional boolean param to the `createChart` function which removes the date based padding. 
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle#charmed-kubernetes-release-cycle
- See that the yAxis no longer overlap
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8875
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/101674117-fe682e80-3a4f-11eb-8d10-6d467e658f20.png) | ![image](https://user-images.githubusercontent.com/1413534/101674088-f3150300-3a4f-11eb-9e75-0eccfad2a015.png) |
=> Remove the date based padding on the k8s release chart

static/sass/_pattern_contextual-footer.scss, static/sass/_pattern_footer.scss
Switch global and contextual footer borders.
- Go to https://ubuntu-com-8904.demos.haus/support/community-support scroll down and take a look at the contextual and the global footer the borders should be switched.
Fixes #8877
=> Change footer design

konf/site.yaml
`^~`: If a carat and tilde modifier is present, and if this block is selected as the best non-regular expression match, regular expression matching will not take place.
=> Added ^~ for nginx proxy locations

konf/site.yaml
Do not merge until https://github.com/canonical-web-and-design/ubuntu-com-security-api/pull/18 is merged!
Changes the paths we link to the API app.
Fixes https://github.com/canonical-web-and-design/ubuntu-com-security-api/issues/6
=> Add general /security/api to path

README.md
I had some issues with the docker snap before @nottrobin told me to use the official version instead. So I'm removing links to docker snaps in the readme to prevent future headaches
- Remove the link to docker snap and replaced it with the docker.com official install instruction
- Look at the readme
=> Replace link to docker snap with trad install

templates/blog/index.html, templates/templates/base.html
- Add RSS metatag for blog
- Make sure that blog index page has the metatag for rss feed
=> Add RSS metatag

static/sass/_pattern_cube-animation.scss, static/sass/_pattern_strip.scss, static/sass/styles.scss, templates/cube/index.html
- Add CUBE animation to hero on `/cube`
- Add watermark cube background to hero and strip on `/cube`
- Edit `p-strip--square-suru` class, to ensure the gradient is visibile on all screen sizes. This class is only used in one other place on `/automotive`. Spoke to @anasereijo who confirmed that across ubuntu.com the suru gradient should be visible on all screen sizes. 
- View the demo at: https://ubuntu-com-8905.demos.haus/cube
- Check the CUBE animation on the hero and the watermark background. 
- Check the animation transforms on page load similar to _animation9_, see [here](https://drive.google.com/drive/folders/1nlQ-MxfebuI8T9xuczU559AOWQ4c7l9c)
Fixes #8882
=> Add CUBE animation to landing page hero

webapp/app.py, webapp/cube/api.py, webapp/cube/mappings/courses.yaml, webapp/cube/views.py, webapp/views.py
Adds a mapping for course topics and badges, so we can list them on the microcerts page
- Visit `http://localhost:8001/cube/microcerts`
- See you have a list of courses with topics and badges
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3585
=> Cube topics badges

static/js/src/core.js
- Add were hiring link to global nav
- Look at the global nav, see that it says "We're hiring" and links to https://canonical.com/careers/start
=> Add were hiring link to global nav

templates/blog/product-cards/_raspberry-pi_2010-livestream.html
- Updated the text from the product card (it was talking  to the live stream & invited people to join it) as it was outdated
- Check the product card appears on Raspberry-pi tags (eg:[ blog post](https://ubuntu.com/blog/raspberry-pi-and-ubuntu-2020-roundup) )
-Check the text from the product card text updated
Fixes #
=> Update text _raspberry-pi_2010-livestream.html

templates/appliance/adguard/intel-nuc.html, templates/appliance/adguard/raspberry-pi.html, templates/appliance/adguard/raspberry-pi2.html, templates/appliance/lxd/intel-nuc.html, templates/appliance/lxd/raspberry-pi.html, templates/appliance/mosquitto/intel-nuc.html, templates/appliance/mosquitto/raspberry-pi.html, templates/appliance/mosquitto/raspberry-pi2.html, templates/appliance/openhab/intel-nuc.html, templates/appliance/openhab/raspberry-pi.html, templates/appliance/openhab/raspberry-pi2.html, templates/appliance/plex/intel-nuc.html, templates/appliance/plex/raspberry-pi.html, templates/appliance/plex/raspberry-pi2.html, templates/appliance/shared/_base_appliance_index.html
Changed appliance page titles of various forms to one of these three:
- “Install {appliance name}”
- “Install {appliance name} on a {hardware}”
- “Try the {appliance name} Ubuntu Appliance in a virtual machine” (left unchanged).
- View the site locally in your web browser at: http://0.0.0.0:8001/appliances and browse the sub-pages
Fixes #8914.
Supersedes #8928.
=> Consistent appliance page titles

templates/base_index.html
- Adding CentOS notice on homepage
- Ensure the notice is visible on the homepage and links to the relevant blog post
=> centos notice on homepage

static/js/src/ua-payment-modal.js
Remove the font src when initialising the card input element.
**This unblocks the US Navy and other institutions that are required to use Silo browser**
- Open the demo and check the card input is working as live
- Go to https://www.authentic8.com/company/ and click "Try Silo risk free."
- Then enter the demo link into the simulated browser and check the card input works 
- If you want to switch to production in Silo and see that the card input is not rendered.
=> Enable the card field on the Silo browser

templates/server/index.html
Remove the "LTS" from the what's new 20.10 section.
- Go to the demo
- Scroll to the "What’s new in 20.10" and see the heading doesn't have LTS.
=> Remove LTS from 20.10

templates/blog/newsletter-form.html
Include the grecaptcha script in the newsletter sign up include
- See that the grecaptcha field appears in the Newsletter sign up box
- Check on live it fails due to it being missing
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8971
=> Include the grecaptcha script in the newsletter sign up include

templates/shared/_cloud-contact-us-form.html
Include the grecaptcha script in the contact us form
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us/form?product=generic-contact-us
- Fill in the form and see it works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/8980
=> Include the grecaptcha script in the contact us form

static/js/src/chart-data.js
> The OpenStack Ussuri LTS line, the period between May 2020 and April 2025 should be represented in grey - matching OpenStack release support - rather than in orange.
> drop the tech preview period from OpenStack Ussuri LTS and OpenStack Ussuri. 
- See that the colour is grey for the LTS bar for May 2020 to April 2025 and that the tech preview is removed (I left the key commented in the js for next time)
=> Remove Tech Preview from Openstack chart

navigation.yaml, templates/cube/contact-us.html, templates/cube/index.html, templates/cube/thank-you.html, templates/shared/forms/interactive/cube-beta.html
- Add modal contact us form for requesting beta access
- Add `/cube/contact-us` and `/cube/thank-you` pages
- Remove links from titles on `/cube`
- Edit quote section on `/cube` to content about requesting beta access
- View the page at: https://ubuntu-com-8982.demos.haus/cube
- At the bottom of the page, use the *Request beta access* cta to view the modal. 
- Check the modal against the [design](https://app.zeplin.io/project/5f5268731d98b38800528395/screen/5fc4e38351755eb3e8ccbfbb)
- Check the Contact us page for non JavaScript enabled users at `/cube/contact-us`
Fixes #8972
=> Add contact us for CUBE beta

templates/cube/microcerts.html
- link the prepare button on `/cube/microcerts` to `qa.cube.ubuntu.com` until we have a link to the correct preparation material
- View page at: https://ubuntu-com-8991.demos.haus/cube/microcerts
- Check Prepare button link works
=> Fix prepare button - broken link

webapp/app.py
Remove the engage page part for homepage takeovers.
=> Remove the engage takeover on the homepage

static/files/sitemap.xml
- Update sitemap.xml for static files
- I changed my script to just look at the files in the /templates directory as we now have code to generate most of the module created pages (docs, engage pages, tutorials, cves, usns).
- View the site locally in your web browser at: http://0.0.0.0:8001/static/files/sitemap.xml
- See that it looks correct and validates
=> Update sitemap.xml for static files

static/js/src/advantage/contracts-api.js
- Fix the case of `account_name`
- View the site https://ubuntu-com-9007.demos.haus/advantage/subscribe?test_backend=true
- Make a purchase using a new email and check in the network tab that the right username is used in the customer-info response
Fixes #8997
=> Switch account name property to the right case

templates/advantage/index.html, templates/advantage/table/_attached-machines.html
Changed the subscription table “Attached” expanded cell to explain that attaching is not necessary on Ubuntu 16.04/18.04.
- Sign in
- In the “Your paid subscriptions” table, expand any of the “Attached” cells
Fixes PART OF #9001. DOES NOT fix the Livepatch token part of it.
=> Explain that attaching is unnecessary on 16.04/18.04

redirects.yaml
Check you get a redirect at /server/guide
``` bash
dotrun
curl -sI http://127.0.0.1:8001/server/guide | grep -i location
```
Check you see a location header for `/server/docs`.
=> redirect /guide

templates/telco/index.html
- Update logos on /telco added 2 and made the rest lazy load
- View the site locally in your web browser at: http://0.0.0.0:8001/telco
- Compare to the [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit?ts=5fd92d66#)
Fixes [#3593](https://github.com/canonical-web-and-design/web-squad/issues/3593)
=> Update logos on /telco

package.json, static/js/src/contextual-menu.js, static/sass/_pattern_cube-table.scss, static/sass/_pattern_strip.scss, templates/cube/index.html, templates/cube/microcerts.html, webapp/cube/views.py, yarn.lock
- Add conditionals to render different views of the microcerts depending on if the user is:
- - not logged in or enrolled
- - logged in but not enrolled
- - enrolled
- - enrolled and passed all 15 microcerts
**Note**: The links for LinkedIn, twitter and copy to clipboard will be completed in the following issue
*Design*
- View the page at: https://ubuntu-com-9008.demos.haus/cube/microcerts
*qa* 
- Run the site using the command ./run serve or dotrun
- Check not logged in or enrolled view by clearing cookies, and changing 'has_enrollment' on line 115 in `webapp/cube/views.py` to false.
- Check logged in and enrolled view by logging in
- Check enrolled and still in progress view by changing 'has_enrollment' …
=> Add different views for microcerts page

navigation.yaml, templates/templates/footer.html
- Add Cloud (/cloud) to the footer
- Look in the footer and see "Cloud" below "Public cloud"
Fixes #9010
=> Add /cloud to the footer

static/js/src/ua-payment-modal.js
- Check for existence of "I'm purchasing for" fields before attaching events to them
- View the site in your web browser at: https://ubuntu-com-9037.demos.haus/advantage?test_backend=true
- Log in with your SSO account
- If you don't see a contract up for renewal, ask @alnvdl to create one for you
- When you have that, find it in the table, open the dropdown, and click "Renew"
- The payment modal should launch and the Stripe field should render correctly
This is related to, but doesn't fix #9018 - this fixes the problem the user was seeing, we should still handle Stripe failing to initialise.
Before:
After:
=> Fix JS error on renewal form blocking purchases

templates/advantage/index.html
Simplify the advantage hero sections and remove an erroneous closing section tag.
- Visit the demo link
- Check that the title starts at the same point as https://ubuntu.com/security/esm
- Login and check that is also at the same place
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9038
=> Simplify the advantage hero sections

templates/cube/index.html, templates/cube/microcerts.html, webapp/cube/views.py
- Replace CUBE certified badge on `/cube` and on `/cube/microcerts`
- Add class to `Apply for access` button on homepage to fix background watermark overlaying button
- Visit page at: https://ubuntu-com-9033.demos.haus/cube   and: https://ubuntu-com-9033.demos.haus/cube/microcerts
- Check badge matches new spec see [here](https://app.zenhub.com/workspaces/web--ubuntu-clan-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/3635)
- Check watermark isn't overlaying button at the bottom of homepage.
Fixes [#3635](https://github.com/canonical-web-and-design/web-squad/issues/3635)
New badge:
Button:
=> Replace CUBE certified badge

scripts/create-releases.py, webapp/security/alembic/versions/0fe2f3a871da_update_release_12_04.py
- Update 12.04 end of life date from 2021-04-30 to 2019-04-30.
- Don't fetch changes and go to http://0.0.0.0:8001/security/cve you will see the 12.04 in the table
- Fetch changes and go to http://0.0.0.0:8001/security/cve you will not see the 12.04 in the table
Fixes #9045
=> Fix 12.04 esm date

webapp/app.py
The x-frame-options is primarily to protect us against clickjacking attacks against logged-in users.
(The attack would involve hiding an iframe of one of our sites behind a link or button on the attacker's site, and presenting that site to a user who is already logged in to our site. You could then trick the user into unknowingly clicking on a logged-in action on our site.)
However, the TemplateFinder pages are always static content, and so don't include any logged-in actions that could be exploited.
The x-frame-options header caused an issue where a PDF is supposed to include a frame of https://ubuntu.com/legal/ubuntu-advantage-service-terms. If we're too broad with x-frame-options we could well see further issues of the same type.
``` bash
$ curl -sI …
```
=> Exclude x-frame-options header for templatefinder

static/sass/_pattern_cve.scss, templates/security/cve/_cve-table.html, templates/security/cve/cve.html
- Optimise CVE table cells
Go to /security/cve look at the table it should have:
- `Does not exist` on 2 lines instead of 3
- Update the UA texts under the status, inside the cell and they should be smaller
- It should look better than https://ubuntu.com/security/cve
Fixes #8832
Fixes #9036
=> Optimise CVE table cells

static/js/src/cve/cve.js, static/sass/_pattern_cve.scss, templates/security/cve/_cve-table.html
- Make cve table pretty.
- Fetch changes
- Go to http://0.0.0.0:8001/security/cve and look at the table
- Table should have an extra column called priority. If you hover the cell you will see a tool tip with details about the priority.
- Status cells no longer display priority like https://ubuntu.com/security/cve currently does
- Status cells tooltips no longer display priority details. Only `Not vulnerable` and `Pending` have tooltips now.
- Status text will only be listed on one single line
Fixes #9057
=> Make cve table pretty

templates/advantage/_ubuntu_version_select.html, templates/pricing/devices.html, templates/shared/pricing/_ua-for-infrastructure.html, templates/telco/index.html
- Replace text describing Landscape from 'Landscape on-prem management system' to either a version with a link or not of 'Ubuntu systems management with Landscape'
- 
- http://0.0.0.0:8001/telco [copy doc](https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#heading=h.3nuxg1fpsqog)
- http://0.0.0.0:8001/pricing/infra [copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit)
- http://0.0.0.0:8001/pricing/devices [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
- https://ubuntu.com/advantage/subscribe [copy …
=> Replace text describing Landscape

static/sass/_pattern_takeovers.scss, static/sass/styles.scss, templates/base_index.html, webapp/app.py
- Make sure Homepage doesn't go down if discourse APIs fail.
- To test robustness change the `/takeovers.json` endpoint to anything else, and you will see the default 20.04 takeover.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3615
=> JS homepage takeover with endpoint to avoid taking down homepage

templates/takeovers/index.html, webapp/app.py
If the Discourse requests have errors which lead to /takeovers.json failing and returning a 500 status, the content-cache would stop cache responses. This would potentially lead the the application being inundated by requests to /takeovers.json, and in turn inundating the Discourse API with requests.
Including the `stale-if-error` header will hopefully lead to the content-cache providing us with more cover (although I don't know exactly how the content-cache behaves in this case).
QA
--
``` bash
$ curl -sI https://ubuntu-com-9066.demos.haus/takeovers.json | grep -i cache-control
cache-control: max-age=300, stale-while-revalidate=360, stale-if-error=600
```
=> Protect /takeovers.json from Discouse errors (a bit)

navigation.yaml
Enable CVE in /security subnav. It's time. This has been the official CVE portal for a while now.
Fixes #7301
Go to https://ubuntu-com-9067.demos.haus/security. See "CVEs" in nav.
Click it, check it works (CVE section will be empty).
=> Enable CVE in /security subnav

templates/wsl/index.html
Added; 
Type the following command to enable WSL 2:
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
As per the [copy doc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#).
- Accept comment in copy doc if correct.
Fixes #
=> Added missing instruction to WSL page

webapp/app.py, webapp/views.py
Make appliance URL regex more specific
To avoid error when people request invalid URLs e.g. https://ubuntu.com/appliance/docs/distribution/tour_page1.htm, and show a 404 instead.
See https://sentry.is.canonical.com/canonical/ubuntu-com/issues/10662/.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9028
Also did a drive-by tidy of server steps code.
=> fix appliance regex

templates/takeovers/index.html, webapp/app.py
Fix takeovers index template
Fixes #9073
=> Fix index takeovers count

static/js/src/navigation.js, templates/base_index.html
Send a GA impression event when displaying a takeover
@caldav can you confirm you are happy with the structure of the event. I couldn't find any "www.ubuntu.com-impression-takeover" events in GA.
- Check out the demo link
- In the network tab see a GA event is triggered when the takeover is displayed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9075
=> Send a GA impression event when displaying a takeover

templates/kubernetes/docs/cdk-addons.md
Update a 404 to point to the store for coredns
Fixes charmed-kubernetes/kubernetes-docs#524
=> K8sDocs: update store link for coredns

templates/advantage/index.html, templates/advantage/subscribe/index.html
- Added a copy doc link for /advantage/subscribe.
- Updated the copy doc link for /advantage.
The text on /advantage varies depending on whether you are signed in, what kind of subscriptions you have, whether any of them are new, whether any have expired (or are about to), and so on.
If this was all spelled out in a separate copy doc, that document would become very similar to the relevant section of the design specification. More accurate just to link to the design spec. In the spec, UI text is in green to make it easier to find.
With the copy doc browser extension installed:
- View http://0.0.0.0:8001/advantage and http://0.0.0.0:8001/advantage/subscribe
- Follow the “copy document” link
none
=> /advantage copy doc link update

templates/advantage/_stripe-modal.html
Updated the labelling on the UA payment form
- Go to https://ubuntu-com-9059.demos.haus/advantage/subscribe
- Check that the "I'm buying for" field defaults to "An organisation"
- Check that the following field is labelled "Organisation" rather than "Choose an account name"
Fixes #3623
=> Update organisation field

static/js/src/ua-payment-modal.js, static/sass/styles.scss
Disable entire payment form whilst submitting
- Go to https://ubuntu-com-9058.demos.haus/advantage/subscribe
- Select "Servers", type a number in the "How many..." field and select "No thanks" under "Do you want tech support?"
- Click the "Add" button
- Click "Buy now"
- Fill out the form with card number `4242 4242 4242 4242`, expiry date `04/24`, CVC `242` and make up a postcode
- Fill out the rest of the form with dummy information
- Click "Continue" and check that all the form fields are disabled whilst the form is submitting
- This form will fail, check that the all the form fields that should be, are enabled
Fixes #8319
=> Disable entire payment form whilst submitting

templates/cube/microcerts.html
Passed microcert badge received from badger was squashed 
- Fix size and position of passed badge to line up with not yet passed badges 
- Check the passed badge is the correct shape and lines up with the not yet passed badges
=> Fix squashed passed badge from badgr issue

requirements.txt
Upgrade ubuntu-release-info to 21.1, which loosens dependencies
so they no longer conflict.
See https://github.com/powersj/ubuntu-release-info/issues/4
``` bash
dotrun exec pip3 install --upgrade pip  # Get on pip 21
dotrun install  # See install succeed
```
=> Fix dependency conflicts

static/js/src/ua-product-selector.js, templates/advantage/subscribe/index.html
Focus quantity field when option has been selected on the subscribe page
- Go to https://ubuntu-com-9055.demos.haus/advantage/subscribe
- Select either "Servers", "Other VMs", or "Desktops"
- Check that the page scrolls so the "How many ..." field is visible and that it is focused
- Select either "AWS" or "Microsoft Azure" and check that the page doesn't scroll or focus the "How many..." field
Fixes #8247
=> Focus quantity field when product is selected

templates/advantage/_table.html, templates/pricing/infra.html, templates/shared/pricing/_ua-for-infrastructure.html
- Add 'Pricing per year' and 'What's included' heading rows to all pricing tables 
- Add Landscape row on /advantage
- Updated /uasd copy doc
- http://0.0.0.0:8001/advantage
- http://0.0.0.0:8001/pricing/infra
- http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- See that all tables have ' / year' added to the pricing row per #8932 
- See that /advantage has a row for landscape added
Fixes #8932 and #9065
=> Add pricing and what's including headings to all pricing tables and Landscape row on /advantage

static/sass/_pattern_cube-table.scss, templates/cube/microcerts.html
- Add a new class for the badge column so the badge lines up correctly in mobile view
- Check the badges line up correctly in the mobile view of the table.
=> Fix badge alignment on mobile view

templates/security/cve/cve.html, webapp/security/models.py
- Fix CVE broken links. We worked with the assumption that all the patches/references/bugs are simple links. But it turns out some links can have an invalid format or have a comment in parenthesis. 
- Before Examples:
- Make the links work even by removing the `(exmaple)`.
- Have a database
- Fetch changes
- Go to http:/0.0.0.0:8001/security/CVE-2002-2439 
- Check that the patch link works:
- Check that the references links and the bug links work.
Fixes #8918
=> Fix CVE broken links

navigation.yaml
Core docs navigation changes
- View the site locally in your web browser at: https://ubuntu-com-9098.demos.haus
- Check that the items in the docs navigation appears
- Removed obselete sub-docs from navigation
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3663
=> Ammend navigation items for core docs

templates/advantage/shared/_livepatch-info.html
- Replaced the Livepatch command line, which contains the wrong token, with a link to auth.livepatch.canonical.com.
- Sign in, then expand the “Livepatch” cell for any of your paid subscriptions
Fixes the rest of #9001.
=> Correct Livepatch instructions for 16.04/18.04

templates/kubernetes/docs/1.19/upgrading.md, templates/kubernetes/docs/1.20/upgrading.md, templates/kubernetes/docs/troubleshooting.md, templates/kubernetes/docs/upgrade-notes.md, templates/kubernetes/docs/upgrading.md
- Adds a note on upgrade pages re Juju bug with LXD
-  Adds troubleshooting section for fixing LXD profiles
=> K8sdocs: add warning about juju/lxd bug

templates/security/cve/cve.html
- Add the body text “This CVE does not apply to software in Ubuntu archives.” for `not-in-ubuntu` CVEs.
- Have a database.
- Fetch changes
- You need a `not-in-ubuntu` CVE, run following commands:
```
docker-compose up -d  # start db
docker exec -it db psql -U postgres  # open postgresql shell
update cve set bugs=null, cvss3=null, description=null, notes=null, published=null, patches=null, tags=null, ubuntu_description=null, status='not-in-ubuntu' where id='CVE-2005-4890';  # update cve to be a not-in-ubuntu CVE
```
- Launch website with `dotrun` and go to http://0.0.0.0:8001/security/CVE-2005-4890
- You will see the body text “This CVE does not apply to software in Ubuntu archives.”
Fixes #9060
=> Add not-in-ubuntu details

static/js/src/ua-payment-modal.js
Related to this PR (https://github.com/canonical-web-and-design/ubuntu.com/pull/9058) - disabling all the fields prevented the form values from being read at key points and made payments impossible, `readonly` achieves a similar thing but allows the values to be read and payments to be made.
- Check out this feature branch or visit the demo
- Easy way to QA is to be logged out of SSO, then visit /advantage/subscribe and select a product as a guest
- Open the network tab in your dev tools
- Click "Add", then "Buy Now".
- Fill out the modal form with the following card details:
- 4242 4242 4242 4242 / expiry: 04/24 / cvc: 242 / zip: 42424
- And then any valid details for the rest of the form
- When you click "Continue", you should see a request made to purchase_account, the headers for …
=> UA: make form inputs readonly when submitting customer info

templates/support/community-support.html
- Removes the implication that Discourse is a support forum
- Links to a more complete list of support forums
- As a bonus, shortens the “Find community support” section to more closely match the other cards
[Copy doc updated](https://docs.google.com/document/d/1vrnljXUx71ZZhz3cQ6NupUNw6yNqW2OWkyY8Ozx2bqw/edit).
- View the site locally in your web browser at: http://0.0.0.0:8001/support/community-support
- Read the “Find community support” card
Fixes #8654.
=> Clarifies description of community support sources

templates/legal/data-privacy/cube-beta.md, templates/legal/data-privacy/index.html
- Add CUBE privacy notice to `/legal/data-privacy` page at `/legal/data-privacy/cube-beta`
- View page at: https://ubuntu-com-9102.demos.haus/legal/data-privacy/cube-beta
- Check CUBE Beta privacy notice added [ here ](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit?ts=600ae145) - see [copy doc](https://docs.google.com/document/d/1Ovw3ypWDQwxWZ_tU_2U57uWUW-437v6R2UIMX6wfYYg/edit?ts=600ae156#heading=h.yxezur7gyf9f)
Fixes #9083
=> Add CUBE Beta privacy notice

templates/templates/footer.html
- Add Industrial link to Sectors section of the footer
- See a link to /industrial in the footer in the Sector's list
Fixes #9134
=> Add Industrial link to Sectors section of the footer

konf/site.yaml, webapp/cube/views.py, webapp/decorators.py
Make CUBE views only accessible to users with `@canonical.com` emails.
- Make sure you can still see `/cube` and `/cube/microcerts` you should be redirected to SSO if you are not logged in.
- Login as a user that does not have a `@canonical.com` email and see you get a 403 page.
=> Restrict CUBE views to Canonical employees

templates/cube/microcerts.html, tests/cassettes/TestCube.test_microcerts_authenticated.yaml, tests/test_cube.py, webapp/cube/api.py, webapp/cube/content/cube.yaml, webapp/cube/views.py
- Update mappings file to contain the newly created course IDs
- Update take URLs
- Add test coverage for cube endpoints
-  Make sure you see the 15 certifications in the state they should be for your account
=> Course mappings and URLs

templates/core/features/index.html
- Add links to `/core/features/secure-boot`,  `/core/features/full-disk-encryption` and `/core/features/recovery` to `/core/features` page. 
- Will add OTA link once page is built 
- View page at:
OR
- View the site locally in your web browser at: http://0.0.0.0:8001/core/features
- Check secure-boot, full disk encryption and recovery links are correct
=> Add links to features page

navigation.yaml, static/sass/_pattern_strip.scss, templates/core/index.html
- Update /core page
- Add `/smartstart` and `tutorials` to the nav 
- Smart start bubble moved [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9144)
- Or view demo at: https://ubuntu-com-9142.demos.haus/core
- Check page against [copydoc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#heading=h.cc4g322ve6sn) 
Fixes [#3643](https://github.com/canonical-web-and-design/web-squad/issues/3643) and [#3668](https://github.com/canonical-web-and-design/web-squad/issue …
=> Update /core page

templates/robotics/index.html
- Update Core 18 with Core 20 on /robotics
- See that the section at the bottom points to core 20 and the new docs for 'Build a custom Ubuntu Core image' link
Fixes [#3794](https://github.com/canonical-web-and-design/web-squad/issues/3704)
=> Update Core 18 with Core 20 on /robotics

templates/download/iot/index.html, templates/download/kvm.html, templates/download/raspberry-pi-core.html
- Update /download/kvm and /download/raspberry-pi-core to use core 20
- Updated the copy docs
- View the site locally in your web browser at: http://0.0.0.0:8001/download/kvm and http://0.0.0.0:8001/download/raspberry-pi-core
- Or http://ubuntu-com-9165.demos.haus/download/kvm http://ubuntu-com-9165.demos.haus/download/raspberry-pi-core
- See that it used UC 20 and the links work
=> Update /download/kvm and /download/raspberry-pi-core to use core 20

webapp/views.py
Related to but doesn't fix #9109 - when a user submits a payment, we currently capture the purchase request in Sentry if there is an error, but nothing else. This adds the error response from the API, so we have more visibility over the issue.
- Check the code, see that it looks OK
- Tricky to actually QA, we can't reproduce the issue in #9109 yet, so this is more to help us debug that issue if it happens again in production while we're investigating it.
=> Capture error response in sentry when posting to contracts API

templates/download/iot/index.html
- Update to UC20 on /download/iot page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot
- See that the 'Browse all supported images' links points to https://cdimage.ubuntu.com/ubuntu-core/20/stable/current/
Fixes [#3781](https://github.com/canonical-web-and-design/web-squad/issues/3781)
=> Update to UC20 on /download/iot page

templates/financial-services/index.html
- Fix nested `p-strip` class on `/financial-services`
- See explanation of issue [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9110#discussion_r566778918)
- Check layout on desktop and mobile view
- Check the code - implementation of strip classes, rows and cols
Fixes #9168
=> Fix nested strips on financial services page

static/js/src/ua-payment-modal.js, webapp/app.py, webapp/views.py
- Reduce the amount of calls we're making to the purchase preview endpoint, previously it would happen twice when launching the payment modal on /subscribe
- Explicitly set account and previous_purchase_id as `None` if we know the user isn't logged in
- Disable caching on /advantage/subscribe
- Check the [demo](https://ubuntu-com-9175.demos.haus/advantage/subscribe?test_backend=true)
- While not logged in, inspect the page source for "accountID" and "previousPurchaseID" variables, see that both values are empty strings.
- Log in
- Open network panel in dev tools
- Select a product, add it to cart, then click "Buy Now"
- Fill out the form, select "United Kingdom" as your country
- Card details: 4242 4242 4242 4242 / CVC: 242 / Expiry: 04/24 / Zip: 42424
- Click "Pay"
- In the network …
=> UA: bug fixes

releases.yaml
- Update to releases.yaml to support 20.04.2 release
- http://0.0.0.0:8001/download/alternative-downloads
- http://0.0.0.0:8001/download/desktop
- See that they all point to 20.04.2
Fixes #9178
=> Update to releases.yaml to support 20.04.2 release

templates/download/raspberry-pi/index.html
- The existing layout no longer could work if we added a new pi device, so tweaked the layout.
- Update layout of /download/raspberry-pi to support new CM4
- I need to update the copy doc as well.
- See that the links work and the text reads well
Fixes #9179
=> Update layout of /download/raspberry-pi to support new CM4

navigation.yaml
- Capitalise FIPS on aws secondary nav
- View page at: https://ubuntu-com-9193.demos.haus/aws
- Check that FIPS in the secondary nav is capitalised as requested [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/9124#issue-796812323) 
Fixes #9124
=> Capitalise FIPS on aws secondary nav

templates/managed/index.html
- Add Video to hero section
- Change background to suru so video can be seen 
- Or view page at: https://ubuntu-com-9192.demos.haus/managed
- Check page against [copy doc](https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit?ts=60114f22) comment 
Fixes #9172
=> Copy update - Add video to hero on managed

templates/cube/microcerts.html, tests/test_cube.py, webapp/cube/content/cube.yaml, webapp/cube/views.py
Some fixes for issue found while QAing the `cube` branch.
- “Prepare” Button
- IF the customer has not purchased the Study Labs; THEN “Prepare” will be a link to purchase (or request enrollment for the purposes of Alpha/Beta testing). Table prepare links are hidden if you don't have the material.
- ELSE all “Prepare”  buttons should direct to: https://qa.cube.ubuntu.com/courses/course-v1:ubuntu+cubereview+coursecommandsdev/course/
- Failed Exams
- IF the user has failed an exam; THEN display a button the links to https://support.canonical.com:
- Resume button
- IF the user has left the exam tab, accidentally or otherwise AND there is still time left on the running exam; THEN ‘Resume’ should send them right back to the same link as ‘Take’
- Change ‘Virtualization’ to ‘Virtualisation’  in …
=> Cube alpha fixes

templates/cube/contact-us.html, templates/shared/_cube-contact-us-form.html, templates/shared/forms/interactive/cube-beta.html
- Create a bespoke static contact us form for CUBE
- Update submit button on contact us modal
- View the site locally in your web browser at: http://0.0.0.0:8001/cube and check the pop up modal when you select 'Apply for access' now says 'Join the beta'
- View the site locally in your web browser at: http://0.0.0.0:8001/cube/contact-us and check the form has only first name, last name, and email address fields and there are no phone numbers visible. 
- Points addressed from this [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/9202)
Fixes #9202
=> Update CUBE contact us form

templates/cube/microcerts.html, templates/shared/forms/interactive/cube-beta.html
- Change the contact form email field label to be just `Email:`.
- Use `Apply for access` as the button text for getting preparatory material.
- Check the copy changes are there.
=> Cube alpha copy changes

redirects.yaml
- Redirects for 2 blog posts 
- blog/what-is-elasticsearch-and-how-are-enterprises-using-it -> /blog/what-is-elasticsearch
- blog/managed-postgresql -> /blog/what-is-postgresql
=> what is (postgresql|elasticsearch) blog posts redirects

konf/site.yaml
Redirect core.docs.ubuntu.com to ubuntu.com/core/docs
Pair with me to QA on microk8s
Urls to test:
- https://core.docs.ubuntu.com/
- https://core.docs.ubuntu.com/en
- https://core.docs.ubuntu.com/en/using-core
- Any other URLs may not match, but this will be dealt with in the [redirects table](https://discourse.ubuntu.com/t/ubuntu-core-documentation/19764)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3780
=> Redirect core docs to ubuntu.com/core/docs

templates/cube/base_cube.html, templates/cube/index.html, templates/cube/microcerts.html
- Copy update on `/cube` and `/cube/microcerts`
- Add copy doc links to pages
- View the site locally in your web browser at: http://0.0.0.0:8001/cube and http://0.0.0.0:8001/cube/microcerts
- Check pages against [copy docs](https://drive.google.com/drive/folders/1XqlPwl4su8nwIjbnhbfTpG5vJOl8JLxI)
=> CUBE: Copy update 

webapp/cube/api.py
Badgr API: Authenticate and retry request after HTTP 401
- Make sure the page renders fine
=> Badgr API: Authenticate and retry request after HTTP 401

releases.yaml, templates/download/alternative-downloads.html, templates/download/desktop/index.html, templates/templates/navigation-download-h.html
- Update for the 20.04.2.0 desktop respin
- Added a variable for this
- **note, the file isn't in place, so it will not download**
- View the site locally in your web browser at: http://0.0.0.0:8001/download/desktop and http://0.0.0.0:8001/download/alternative-downloads
- See that it points to the 20.04.2.0 download
=> Update for the 20.04.2.0 desktop respin

templates/ai/services.html, templates/ai/shared/_learn-more.html, templates/shared/contextual_footers/_ai_further_reading.html, templates/shared/contextual_footers/_kubeflow_news_signup.html
- Rebuild `/ai/services` page
- Update learn more section to include dynamic AI blog post list
- View page at: https://ubuntu-com-9219.demos.haus/ai/services
- Check page against [copy doc](https://docs.google.com/document/d/19Mx1zRJKqH2hz5kRF_oDsgyFUw67FgJvW4I_OGda-wk/edit#)
Fixes [#3767](https://github.com/canonical-web-and-design/web-squad/issues/3767)
=> Rebuild /ai/services page

templates/core/index.html
- Fix IoT link on `/core` to point to `/internet-of-things` not `/internet-of-things/networking`
- View page at: https://ubuntu-com-9233.demos.haus/core
- Check the IoT link in the 'For smart use cases' section points to `/internet-of-things`
Fixes #9200
=> Fix IoT link in smart use cases section

package.json, yarn.lock
- Removed packages `husky` and `lint-staged`
- Pull down this branch
- Run `dotrun clean`, then `dotrun`
- If you have Prettier installed as an extension, disable formatting on save (easy way is with [Formatting Toggle extension](https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle))
- Commit a Prettier sin in any sass file and try to commit it
- You should be able to commit
=> Remove husky and lint-staged

webapp/app.py
Extend the no-cache to include the entire all advantage endpoints
- Go to the demo
- Go to advantage
- See the page request has no-cache headers
- Check the paths after /advantage such as "/advantage/subscribe", "/advantage/customer-info", "/advantage/subscribe/preview", etc all have no-cache headers.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9256
=> Extend the no-cache to include the entire all advantage endpoints

package.json, yarn.lock
- /advantage/subscribe .p-card--radio were 100% @ big media screens for some reason, so I am downgrading the version for now.
- Check https://staging.ubuntu.com/advantage/subscribe look at the cards from the **What are you setting up?** section. They should be aligned on one row, but instead they are full row width.
- Check https://ubuntu-com-9258.demos.haus/advantage/subscribe
- Are the 4 cards on one row?
=> Downgrade Vanilla to 2.23.0

webapp/app.py
Add discourse module for Openstack charms docs
- Check https://ubuntu-com-9251.demos.haus/openstack/docs
- Check discourse https://discourse.ubuntu.com/t/openstack-charms-introduction/20998
Fixes #9247 #9246
=> Add discourse module for openstack charms docs

static/js/src/advantage/contracts-api.js, static/js/src/ua-product-selector.js, templates/advantage/subscribe/index.html, webapp/advantage.py, webapp/app.py, webapp/views.py
- The way a new contract gets attached to a subscription had to be updated. 
- Before you could always make the assumption that from all the subscriptions you get from that account, the first one (and the only one) is the right subscription to attach the new contract to it
- Now that users can have up to two subscriptions (yearly and monthly), we can no longer rely on that assumption. 
- The purchase form had to be adapted to cover the new situations.
- Go to https://ubuntu-com-9252.demos.haus/advantage?backend_testing=true make a purchase. It should work.
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/3833
=> Update purchase to subscription matching

redirects.yaml
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9279
Go to `/blog/topic` and `/blog/topic/design` in the demo. Check you're redirected to the working page in both cases.
=> Redirect /blog/topic to prevent 500

navigation.yaml, templates/ceph/install.html
- Build new page at `/ceph/install` 
- View the site locally in your web browser at: http://0.0.0.0:8001/eph/install
- Check page against [copy doc](https://docs.google.com/document/d/1EmOtHjuEMKhVLQA7GwyrKfCzOKfc8UCEyh-p04-PxzA/edit#)
Fixes #9232
=> Build new page at /ceph/install

templates/kubernetes/compare.html
Removed the second GlusterFS on / compare
- Check and accept correct copy changes in the [copy doc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit?ts=602a7fd3)
Fixes #3837
=> Typo on /compare

webapp/security/alembic/versions/8008e46e6ea8_add_is_hidden_column_for_notices.py, webapp/security/database.py, webapp/security/models.py, webapp/security/schemas.py, webapp/security/views.py
- Add new column to usn table
- add BaseFilterQuery class is overriding the default Query class and applies a default filtering based on the set rules of the Model set inside the `_base_filters`.
If we wish to bypass this default filtering, we would call
`without_default_filtering` on the query:
`usn = db_session.query(Notice).without_default_filters().get(notice_id)`
- Have a database
- Do not fetch changes
- `docker-compose up -d` and `dotrun`
- Browse to http://0.0.0.0:8001/security/notices/USN-4417-2 # can be any id.
- You should get a 200
- Let's make USN-4417-2 private:
```sql
docker exec -it db psql -U postgres
select id,is_hidden from notice where id='USN-4417-2'; -- you will see the is_hidden value is set to false
update notice set is_hidden=True where id='USN-4417-2'; -- set …
```
=> Add is_hidden column to usn

tests/test_cube.py, webapp/app.py, webapp/cube/views.py
Make sure all CUBE routes are not cached by setting the correct headers.
- Go on the demo and check `/cube` and `/cube/microcerts` both set the following headers
- `"Cache-Control": "no-cache, no-store, must-revalidate"`
- `"Pragma": "no-cache"`
=> CUBE: Add Cache-Control headers to routes starting with '/cube'

templates/kubernetes/docs/charm-reference.md
Fix the typo in the nav include for k8s docs.
- Go to /kubernetes/docs/charm-reference
- check it does not 500 like on live
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9285
=> Fix the side-nav ref in kubernetes docs

templates/core/index.html
Updated button in the sub heading to "watch the webinar" linking to “https://ubuntu.com/smartstart” with “https://ubuntu.com/engage/ubuntu-core-20-webinar”
- Check the changes against the [copy doc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit?ts=602e6dca#) and accept the correct changes
Fixes [#3838](https://github.com/canonical-web-and-design/web-squad/issues/3838)
=> Updated button in sub heading

templates/azure/index.html
- Changed 20.04 to 18.04 and updated links
- Compare the changes against the [copy doc](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit?ts=602ea235#) and accept the correct ones.
Fixes [#3839](https://github.com/canonical-web-and-design/web-squad/issues/3839)
=> Changed 20.04 to 18.04 and updated links

templates/cube/index.html, webapp/cube/content/cube-qa.yaml, webapp/cube/content/cube.yaml
- Fix typo on view microcerts button on `/cube`
- Update module titles in table on `/cube/microcerts`
- View the site locally in your web browser at: http://0.0.0.0:8001/cube and http://0.0.0.0:8001/cube/microcerts
- Check titles of modules on the microcerts table match updated titles seen [here](https://docs.google.com/document/d/1a8GvqITokFmAZvhDCQCq8tc3urSfDGW0GxeLDFGDda0/edit) 
- Check View Microcerts button against [copy doc](https://docs.google.com/document/d/1QuhO-9FEOGLrYp8bErS_9snqdljl7d6tFAUoNQxoVDQ/edit?ts=6037ec8b#heading=h.pldvznbtjgmu) on `/cube`
Fixes #9320
=> CUBE: Update module titles

templates/kubernetes/docs/1.20/upgrading.md, templates/kubernetes/docs/docker-registry.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/quickstart.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/supported-versions.md, templates/kubernetes/docs/upgrade-notes.md, templates/kubernetes/docs/upgrading.md
- update bundle revisions
- update release notes
- add docker-registry clarifications
=> K8s1.20+ck1

Dockerfile, requirements.txt, webapp/app.py
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9274
This switches over to using the default talisker session, without such aggressive timeouts.
At present it points to the branch behind this PR: https://github.com/canonical-web-and-design/canonicalwebteam.search/pull/8
QA
--
Check e.g. https://ubuntu-com-9287.demos.haus/search?q=ubuntu works
=> Upgrade to canonicalwebteam.search v1 to use default session

templates/advantage/_table.html
- Update /advantage table as mentioned [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/9111#issue-795952899)
- Select "Add another subscription"
- Check the two points mentioned in this [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/9111) have been resolved
Fixes #9111
=> Copy update - /advantage table

webapp/views.py
Fixes #9275
I don't know how [the error](https://sentry.is.canonical.com/canonical/ubuntu-com/issues/12076/events/a0274d47ecc34e66b68e758a17875e2e/) is happening *exactly8, but it looks like it happens when people load the form with `POST`, but without a `next-step`. Maybe this is because the user refreshes the page, and the browser resubmits the post request but doesn't include the form data for some reason?
Anyway, this should fix it - if you submit an empty `POST` request for `/download/server`, you should now see step 1.
QA
--
First, reproduce the error:
```
$ curl -I -X POST https://ubuntu.com/download/server
HTTP/2 500 
```
Now try on my branch:
```
$ curl -I -X POST https://ubuntu-com-9336.demos.haus/download/server
HTTP/2 200 
```
Rejoice!
```
=> Make empty POST show step 1, instead of 500

requirements.txt, templates/templates/docs/discourse.html, tests/cassettes/TestRoutes.test_ceph_docs.yaml, tests/cassettes/TestRoutes.test_server_docs.yaml, webapp/app.py
- Discourse v3 changes
- Provisional index topics with v3 changes
Check docs are working:
- https://ubuntu-com-9335.demos.haus/server/docs
- https://ubuntu-com-9335.demos.haus/ceph/docs
- https://ubuntu-com-9335.demos.haus/core/docs
- https://ubuntu-com-9335.demos.haus/core/docs/modem-manager
- https://ubuntu-com-9335.demos.haus/core/docs/bluez
- https://ubuntu-com-9335.demos.haus/core/docs/networkmanager
- https://ubuntu-com-9335.demos.haus/core/docs/wpa-supplicant
- https://ubuntu-com-9335.demos.haus/core/docs/easy-openvpn
- https://ubuntu-com-9335.demos.haus/core/docs/wifi-ap
- https://ubuntu-com-9335.demos.haus/core/docs/alsa-utils
- https://ubuntu-com-9335.demos.haus/openstack/docs
=> Bump discourse-docs to v3

templates/core/index.html
- Add DFI logo to page
- See that the logo is there
Fixes #9347
=> Add DFI logo to /core

webapp/app.py, webapp/views.py
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9346
Fix 500 error by updating tutorials search to use the new interface for canonicalwebteam.search v1.0.0.
QA
--
Search here: https://ubuntu-com-9351.demos.haus/tutorials. Check it works. E.g.: https://ubuntu-com-9351.demos.haus/tutorials?q=ubuntu
=> Adapt tutorials search for new module version

templates/cube/microcerts.html, webapp/cube/views.py
- Correct the links to access the preparation material for cube.
- Check when you click the prepare buttons you are redirected to the right link
- https://cube.ubuntu.com/courses/course-v1:CUBE+study_labs_2020+alpha/course/
=> Correct links to CUBE prepare material

templates/core/index.html
- Update Embedded Linux whitepaper link
- Add new whitepaper section
- Check both links for `Embedded Linux: make or buy?` point to correct whitepaper. 
Fixes #9328
=> Add new whitepaper section

templates/azure/fips.html
- Update Ubuntu components table on `/azure/fips`
- View the site locally in your web browser at: http://0.0.0.0:8001/azure/fips
- Check table has new row as per [copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit?ts=603d1978#heading=h.nnv3rdrfhrzr) and resolve comment on copy doc 
Fixes [#3899](https://github.com/canonical-web-and-design/web-squad/issues/3899)
=> Copy update - Ubuntu components table /azure/fips

navigation.yaml, static/js/src/contextual-menu.js, static/sass/_pattern_cube-progression.scss, templates/cube/index.html, templates/cube/microcerts.html
- Fix typo in nav
- Revert to using `getAttribute` not `nextElementSibling` to be more specific when targeting share menu
- Make the `.is-faded` styling a placeholder which is then extended instead of extending a class
- Add meta descriptions 
- Add `js-` prefix to class
- View the site locally in your web browser at: http://0.0.0.0:8001/cube and http://0.0.0.0:8001/cube/microcerts
- Check (update?) meta descriptions and titles
- Check points raised in this this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/8990) have been addressed
- Check refactored code
Fixes #9308
=> CUBE: refactor code and add meta data

templates/engage/base.html
- `primary_cta` to be optional (this still keeps the primary and secondary hierarchy)
- Fix opened `<script>` tag
- Fix double quotes in Jinja string
- You can try by emptying a `primary_cta` of an engage page and visit it the page on https://ubuntu-com-9356.demos.haus. The button should not appear anymore (remember to check this in smaller screen sizes)
Fixes #9349
=> Optional primary cta and syntax fixes

static/js/src/advantage/contracts-api.js, static/js/src/advantage/manage-subscription.js, static/sass/styles.scss, templates/advantage/index.html, templates/advantage/shared/_certifications-info.html, templates/advantage/shared/_esm-info.html, templates/advantage/shared/_livepatch-info.html, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html
- Added options to resize or cancel monthly contracts from the table
- Build the view for yearly subscriptions
Trying to cancel returns a `405 (METHOD NOT ALLOWED)`
Trying to resize throws an error about `product_listing_id` being a number instead of a string
- go to https://ubuntu-com-9315.demos.haus/advantage?test_backend=true
- login
- expand one of your subscriptions and try the different settings
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3787
=> Build subscription management options into the table

templates/advantage/index-no-login.html, templates/advantage/index.html, webapp/views.py
The `enterprise_contracts` has now:
-  `enterprise_contract["is_detached"]` -> "true" or "false"
-  `enterprise_contract["period"]` -> "yearly" or "monthly" 
-  `enterprise_contract["is_cancelable"]` -> "true" or "false" 
-  `enterprise_contract["price_per_unit"]` -> {"currency": "USD", "value": 20000} 
There is now the concept of `is_detached`, which if it's `True`, then it means that the contract is either a legacy contract or an already cancelled contract. Either case you should not show the cancelation/upsize-downsize view on expand. `period`, `price_per_unit` and `is_cancelable` will not exist if `is_detached` is `True`.
=> Add contract details

static/js/src/chart-data.js, templates/about/release-cycle.html
- Add dates for 1.20 k8s to release-cycle chart
N.B. The length of support has changed due to upstream changes. There will be changes to the chart in future to indicate a 'security patch support' period, though this is currently waiting approval (at which point I will update the text also).
- See the chart at <http://0.0.0.0:8001/about/release-cycle#charmed-kubernetes-release-cycle> renders correctly
=> add 1.20 release to k8s chart

webapp/advantage/schemas.py, webapp/advantage/views.py
- Change cancel contract to only accept one `product_listing_id`. Before it was accepting a list of ids, but we only ever cancel one product at a time, so it's pointless.
=> Change cancel contract

webapp/security/schemas.py, webapp/security/views.py
Fix pocket error name. It was copy-pasted wrongly. Resulting in a 500.
Add `without_default_filters` to the get query for `update_notice` and
`delete_notice`.
We filter out by default notices with `is_hidden = True` in all select
queries. For update and delete we need to add `without_default_filters`
to bypass that default filter, otherwise we will always get a 404,
making both endpoints unusable.
Updates and deletes can only be done by canonical people, so
no need for the filter.
Fixes #9390
=> Fix security endpoints bugs

konf/site.yaml, webapp/cube/views.py
Add the possibility of allowing non canonical e-mail addresses to access the CUBE beta.
I will ask one of the users the change is intended for to test in the demo to see if they can access it.
=> CUBE: Authorize specific users

templates/gcp/index.html
- Removed Walmart, Spotify, and Netflix logos
- Changed  "3-4.5%" to "3-6%" 
- go to https://ubuntu-com-9438.demos.haus/gcp
- Check that the logos are gone and the numbers updated correctly
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9437
=> Remove logos section and update number

tests/test_certification.py, tests/test_routes.py, webapp/certification/api.py, webapp/certification/views.py
- Move certification Api requests
- Add tests
- Cleanup names
- https://ubuntu-com-9434.demos.haus/certification should still work
- Check that tests pass
- Check that code matches https://github.com/canonical-web-and-design/certification.ubuntu.com/blob/master/webapp/api.py
Fixes #https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/166
=> Move Certification Api requests

templates/advantage/index.html
Copy the beta programme for Ubuntu Pro form to advantage page
- Go to /advantage and see there is a call-out at the top to fill in the form for the beta.
- Click the link and ensure that the modal form appears
- Check it is present in both logged in and logged out versions.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3956
=> Copy the beta programme for Ubuntu Pro form to advantage page

templates/legal/contributors/agreement.html
Update the agreement file downloads to use assets
- Go to /legal/contributors/agreement
- Check that the two "download as a PDF" links work from assets
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/367
=> Update the agreement file downloads to use assets

webapp/advantage/schemas.py
I assumed tax_id would be a string. It turns out it's a dictionary. I
updated the validation to expect a dictionary instead.
- Go to https://ubuntu-com-9443.demos.haus/advantage/subscribe?test_backend=true
- Select and item and get to the modal
- Open the network tab
- Insert a VAT number: 123 you should get an error (correctly, as it's an invalid number) from the calls: `POST /advantage/customer-info` and `POST /advantage/customer-info-anon` will fail
- Insert GB 123 123 123 it should work this time then finish the payment
=> Fix tax_id parameter

templates/legal/index.html, templates/legal/modern-slavery-statement/_base_markdown.html, templates/legal/modern-slavery-statement/index.md
- Build a Modern Slavery landing page using the content from the latest statement
- Added links to all version to download in PDF form
- Updated the link on the legal main page to link to the page instead of the PDF
- Open the demo and go to /legal/modern-slavery-statement
- Check the content matches [the copy](https://docs.google.com/document/d/16q1jDEr_ArWdCnWzEVuXmC66deXeCnuEHy2G_jX0hqE/edit#)
- Ensure the PDF downloads all work
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9453
=> Update the Modern Slavery legal pages

templates/azure/pro.html
Add new datasheet link in `/azure/pro`.
- wait for the demo.
- got to `/azure/pro` and make sure we are linking to the new datasheet as described in #9447.
=> 9447: Add new datasheet link Ubuntu Pro Azure

redirects.yaml
Add nvidia redirect to the engage page for Marketing
- Go to /nvidia
- Check the redirect works
- Engage page to come
Fixes #9459
=> Add nvidia redirect to the engage page

static/sass/_pattern_navigation.scss, templates/templates/_navigation.html
Extend the search input full width to match the [design](https://app.zeplin.io/project/5ffdb21a3714151de9cf750c/screen/5fff03c52885841ced879a74)
- Check out the demo
- Activate the search
- See that it extends across the entire navigation
- Click the X and see that closes
- Check small screens work as before
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9291
=> Extend the search when activated

webapp/certification/views.py
- Fix Iot var swap 
- add URLs for search results (path property, they will work once the search results page is landed)
- https://ubuntu-com-9473.demos.haus/certification should have correct `iot_releases` and `iot_vendors`
- URLs have been added to the path for the template use (nto working until search results is landed)
Fixes some issues #https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/165
=> Fix Iot var swap and add URLs for search

navigation.yaml, templates/certification/index.html
- Build new page at `/certification`
- Add to secondary nav 
- The link `Ubuntu Desktop certified hardware self-testing guide` is too large to uploaded to the asset server even after being compressed
- IoT vendor/server are mixed up in the backend which @carkod is fixing [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9473)
- View the site locally in your web browser at: http://0.0.0.0:8001/certification
- Check page against [design](https://app.zeplin.io/project/5f3f890c6afe2512594898b2/screen/605a172718df5f07ed12dfe4) and [copy …
=> Build overview page

templates/blog/article.html
- juju.is is getting its own blog
- To appear there the articles should have the tag 4059 (juju.is)
- To make sure we are indexing juju.is and not ubuntu we replace the canonical url with juju.is  (like snapcraft)
- http://0.0.0.0:8001/blog/kubernetes-operators
-  Make sure the canonical url is https://juju.is/blog/kubernetes-operators
- Try another blog post. The canonical url should be ubuntu.com
=> Canonical url to juju.is for article with tag 4059 (juju.is)

requirements.txt, tests/test_cube.py, webapp/app.py, webapp/decorators.py
Use the [new caching defaults](https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/pull/45) from flask-base 0.8.0, for improved client performance and freshness of content.
Also simplify caching rules as follows:
- For private pages, simply use `cache-control: no-store`, as all the other options (`no-cache`, `must-revalidate`, `Pragma: nocache`, `max-age=0`) are simply less complete ways of doing the same thing.
- Remove the `max-age=61` special cache override for `/` and `/blog`, as the new default is `max-age=60` which is even fresher
- *Note: The reason it was `61` and not `60` is because we used to use Squid as our proxy cache, and for some bizarre reason Squid wouldn't cache pages with `max-age=60` or less*
QA
--
Click around, refresh pages a fair bit, check they …
=> Update caching rules with flask-base v0.8.0

tests/test_advantage.py, webapp/advantage/api.py, webapp/advantage/views.py
advantage: implement view as functionality.
This will allow admins to view /advantage as a specific user by providing the `email` query.
- Go to http://0.0.0.0:8001/advantage?test_backend=true , log in and check that you see your contracts as usual.
- Now, assuming you have the contract ACL in ua-contracts staging, go to http://0.0.0.0:8001/advantage?test_backend=true&email=allan.vidal@canonical.com and you should see Allan's contracts.
=> advantage: implement view as functionality

static/js/src/ua-payment-modal.js
- Given I am a guest user and I want to make a purchase.
- When I go to the modal after selecting my product.
- And I insert all my info and press submit to trigger the purchase
preview.
- After that every time you make a click on the modal and even after
closing the modal everywhere on the website we trigger a request.
- This request is not necessary for guest users. It's only useful for
existing users when we try to prefill their contact info.
- Go to https://ubuntu-com-9508.demos.haus/advantage/subscribe?test_backend=true
- Open the Network tab
- Start making a guest purchase
- Insert your info and press the green button to preview purchase
- Click anywhere on the modal it should NOT make get requests to customer-info endpoint on click
- Start making a purchase as a logged in user
- …
=> Fix repeated get customer info calls bug

templates/internet-of-things/index.html
- Update IOT index page copy according to #9488.
- Check the copy matches the proposed changes and mark them as resolved in the document
Fixes #9488
=> 9488: IOT index copy change

templates/legal/terms-and-policies/cube-terms.html, templates/legal/terms-and-policies/index.html
- Add CUBE terms of service
- Check there is a new entry for CUBE in `/legal/terms-and-policies/`
- Check `/legal/terms-and-policies/cube-terms` matches what is specified on https://github.com/canonical-web-and-design/web-squad/issues/3973
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3973
=> Add CUBE terms of service

templates/internet-of-things/contact-us.html
Changed copy according to #9487
- Check the copy matches what is on the doc on `/iot/contact-us?product=appstore`
- 
Fixes #9487
=> 9487: Change IOT app stores contact-us copy

static/js/src/contextual-menu.js
Fix the contextual menu functionality in Chrome
- Login and scroll to the Free personal token section
- Click the reveal button both on Chrome/Chromium and Firefox
- Check the token is revealed
- Click of the panel and see there is now no console errors
=> Fix the contextual menu functionality in Chrome

templates/kubernetes/docs/metallb.md
- Update metallb links following repo move (we discovered that github doesn't redirect everything).
=> k8sdocs -update metallb docs following move

templates/openstack/index.html, templates/shared/contextual_footers/_openstack_next_step.html, templates/shared/pricing/_ua-for-infrastructure.html
- Rebuild page at `/openstack`
- Check page against [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#). I've suggested a change to the hero text to keep it more inline with the rest of ubuntu.com. 
- The graph mentioned with the slider will be done as a separate [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/9524) as this will take some time. 
Fixes [#3821](https://github.com/canonical-web-and-design/web-squad/issues/3821)
=> Rebuild /openstack page 

redirects.yaml
- Blog article redirect
- Ensure https://ubuntu.com/blog/kubernetes-1-21-available-from-canonical exists before merging
=> Redirect K8s 1.21 release blog post to a better URL

navigation.yaml, static/sass/_pattern_component-table.scss, static/sass/styles.scss, templates/certification/model-details.html, templates/certification/search-results.html
- Added page to show model details
- Page is at `/certification/<canonical_id>`
Check the following views:
- 1 release with no component devices: https://ubuntu-com-9537.demos.haus/certification/201612-25300
- 4 releases with no component devices: https://ubuntu-com-9537.demos.haus/certification/201911-27455
- 1 release with component devices including third party driver: https://ubuntu-com-9537.demos.haus/certification/202004-27860
- 2 releases with component devices including in progress status: https://ubuntu-com-9537.demos.haus/certification/202005-27924
Fixes [#154](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/154)
=> Build model details page

static/js/src/advantage/contracts-api.js, static/js/src/ua-payment-modal.js, tests/test_advantage.py, webapp/advantage/api.py
We will soon introduce a requirement in ua-contracts so that all endpoints sending us shop customer information must always include both the name and the country. This is to ensure we don't create invalid entries in Stripe and Salesforce.
It seems this requirement is currently respected everywhere here, except in `ensurePurchaseAccount` (which is fine, it never required such field). Including this field in the request now before we make it mandatory should have no harmful effects: it will just be ignored for now.
- Go to https://ubuntu-com-9534.demos.haus/advantage/subscribe?test_backend=true
- Try to make a guest purchase in the UA shop; it should still succeed, and both the Flask app and ua-contracts should be receiving the country.
=> Add country to ensurePurchaseAccount

webapp/advantage/api.py, webapp/advantage/schemas.py, webapp/advantage/views.py, webapp/app.py, webapp/decorators.py
`POST /advantage/post-guest-trial` with
```
email: string
acount_name: string
name: string
address: {
city: string
country: string
line1: string
postal_code: string
state: string
}
products: [
{
product_listing_id: string
quantity: int
}
]
```
It will store the info of the purchase in the session. Once the user
logs in and arrives on `/advantage` it will trigger the
`GET /advantage/save-guest-trial` endpoint with that data.
This second endpoint will fetch an `account_id` for the user(using email and
account_name), update the customer info(using name and address) and then
make the trial (using account_id and products).
`POST /advantage/post-trial` with
```
acount_id: string
products: [
{
product_listing_id: string
quantity: int
}
],
name: string,
address: {
city: string
country: string …
```
=> Start trial

static/js/src/navigation.js
Add a null check for the login menu when logged out
- Open the demo and login
- Check there is no error in the console
- Check the login menu works 
- Open the demo in a private window with the console open
- Check there is no error in the console
=> Add a null check for the login menu when logged out

templates/server/hyperscale.html
- Updated link to MAAS
- Hover over link to MAAS (or inspect in DevTools)
- Verify it points straight to https://maas.io/ and not /cloud/orchestration/...
=> Fix link to MAAS on hyperscale page

navigation.yaml, templates/certification/index.html, templates/certification/model-details.html, templates/certification/search-results.html, webapp/certification/views.py
- Add form factor headers only if user selects form factor from secondary nav, or selects the "All ubuntu certified <form> hardware" link from the overview page. If user selects filters and clicks `update` the header should now be the standard search results header.
- Fix SoC path in `/certification/views.py`
- Fix error by null checking `forms` in `/certification/views.py`
- Add `filters=True` flag to URL to be able to differentiate between form factor view and search results view. 
- Start here: https://ubuntu-com-9551.demos.haus/certification
- Click through to the search results from the "All ubuntu certified `<form>` hardware" links from the cards on the overview page. This should show the form-factor specific headings. 
- Use the secondary nav to select "Desktop" or "IoT" etc - …
=> Refactor search results page

static/js/src/advantage/subscribe/reducers/form-reducer.js, static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/form/_tech_support.html
- Added a feature flag around ESM apps to hide the option and allow us to release UA monthly
drive by: 
- Aligned the tech support link with the rest of the form
- go to https://ubuntu-com-9558.demos.haus/advantage/subscribe?test_backend=true
- check that everything is working correctly and the "Feature coverage" section is missing.
- go to https://ubuntu-com-9558.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true
- check that the feature coverage is showing and working as expected.
=> Feature flag esm apps

templates/cube/microcerts.html, webapp/cube/views.py
When a user lands in `cube/microcerts` and have no eDX account, they are then presented a modal where they can accept the terms and register for an account. When the button is clicked they are redirected to cube.ubuntu.com and then redirected back to ubuntu.com/microcerts(in QA they are redirected to qa.cube.ubuntu.com and not redirected back).
- If you have no account you should see a popup where you can accept the terms and create an account.
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/3934
=> CUBE: Show register modal if user as no eDX account

releases.yaml, templates/download/desktop/index.html, templates/download/index.html, templates/download/server/step2.html
- Update releases.yaml and mascot for 21.04
- Added release-notes-urls to releases.yaml
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) 
- http://0.0.0.0:8001/download - see the new mascot and 20.10 webinar removed
- http://0.0.0.0:8001/download/desktop - see 21.04 as the latest release
- http://0.0.0.0:8001/download/alternative-downloads - see 21.04 as a bit torrent option
- http://0.0.0.0:8001/download/server (manual step 2) - see 21.04 as latest and 21.04 webinar
Fixes #9564
=> Update releases.yaml and mascot for 21.04

templates/desktop/developers.html, templates/server/index.html
- Updated the /server page with:
- new 21.04 webinar
- new what's new
- updated release note links on /server and /desktop/developers with variables
- View the site locally in your web browser at: http://0.0.0.0:8001/server and https://0.0.0.0:8001/desktop/developers
- See that the webinar and what's new and release note link are all updated
Fixes #9563
=> Update /server for 21.04

templates/desktop/developers.html
- Updated 'What's new' for /desktop/developer
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/developer
- Compare to the [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit?ts=608029d7#)
=> Updated "What's new" for /desktop/developer

static/js/src/advantage/subscribe/renderers/form-renderer.js
- Add a + to the support prices to show it's additional cost
- go to https://ubuntu-com-9584.demos.haus/advantage/subscribe?test_backend=true
- check that there is a + in front of the support price
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4030
=> Add a + to the support prices to show it's additional cost

templates/16-04/index.html, webapp/app.py, webapp/views.py
We need 3 dynamic values:
1) Number of patches applied to version 16.04. Number of LSNs released on 16.04.
Will have to be hard coded for now, until all LSNs reach prod.
2) Number of USNs applied to version 16.04. Number of USNs that have affected 16.04.
https://ubuntu.com/security/notices.json?release=xenial
3) Number of CVEs addressed by 16.04.  Number of CVEs that have the status "released" on 16.04.
https://ubuntu.com/security/cves.json?version=xenial&status=released
We also need the latest 5 USNs released that affected 16.04 for the feed.
https://ubuntu.com/security/notices.json?release=xenial&limit=5
- QA won't be possible (easily) due to CORS errors.
Fixes #9410
=> Add dynamic content to the 16.04 page

releases.yaml
- Updated checksums for 21.04 release
- Test the raspberry-pi, desktop and server downloads to see if the checksums appear on the thank-you page
- 
Fixes #9565
=> Updated checksums for 21.04 release

templates/16-04/index.html, webapp/views.py
- Fix links without `href` on production.
- https://ubuntu-com-9595.demos.haus/16-04 
- scroll down to `Ubuntu 16.04 LTS security updates`
- Latest notice release titles should be working links. They will redirect to 404 on the demo, but if you change the host to ubuntu.com, they should work
=> Fix 16-04 links

templates/advantage/index.html
- Add missing link to /advantage/subscribe on /advantage on small screens
- go to https://ubuntu-com-9596.demos.haus/advantage?test_backend=true
- resize the window to get the small VP layout
- check that the "Add a new subscription" button is here and working
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9574
=> Add missing "Add a new subscription" link to shop on small screens

static/sass/_pattern_certification-results.scss, templates/certification/search-results.html, templates/dell/index.html, webapp/certification/views.py
- Add vendor specific view to search results page
- Update links on `/dell` to point to `/certification`
- View the site locally in your web browser at: http://0.0.0.0:8001/certification
- Search for something to view the search results page
- Click through to the vendor view by clicking the link to the vendor in the table (e.g. Dell or Acer)
- The vendor filters on the left should now not be visible
- The h1 should include the vendor name
Fixes [#182](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/182)
=> Build vendor specific view of search results

static/sass/_pattern_component-table.scss, static/sass/_pattern_hardware-details-table.scss, static/sass/styles.scss, templates/certification/hardware-details.html, templates/certification/model-details.html, templates/certification/search-results.html
- Build hardware details page for each model-release
- Change in progress to untested as per wireframe
- Go to https://ubuntu-com-9598.demos.haus/certification
- Search for something to land on search results page. 
- Select any model to land on model details page
- Click the hardware details link in the releases section
- See a list of hardware. The list is no longer links as we no longer have the "component catalog" which exists on the current site. 
- Compare the page against the [design](https://app.zeplin.io/project/5f3f890c6afe2512594898b2/screen/606c439a5cdfed97af0303f0) 
Fixes [#158](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/158)
=> Build hardware details page

static/js/src/advantage/manage-subscription.js
- Show a spinner on the confirm cancel button when it's clicked
with a monthly subscription :
- go to https://ubuntu-com-9597.demos.haus/advantage?test_backend=true
- cancel your monthly subscription
- check that the spinner is displaying in the correct button
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9467
=> Toggle loading state on the correct button for cancellation

templates/advantage/index.html, webapp/advantage/views.py
- select every single subscription of the account, but filter out the deactivated ones. (locked subscriptions were excluded by mistake)
- both yearly and monthly subscriptions can have a locked status, but before we were only dealing with monthly ones
- if a user encounters payment issues, through resizing or purchasing, the transaction will finish they get redirected to /advantage and the notification saying that a payment issue has happen will show up.
1.
- Make a new purchase yearly and/or monthly product with this card number: 4000000000000341
- You will reach /advantage and you will see the notification
2.
- Change your default credit card to 4000000000000341
- Then resize a product
- You will reach /advantage and you will see the notification
Fixes #9463
=> Fix broken state after failed purchase

templates/appliance/shared/_featured_appliances.html, templates/download/raspberry-pi/index.html
- Updated /download/raspberry-pi layout
- Added a list when small for the 'Works on'
- See that it matches the [design](https://app.zeplin.io/project/6033b7828f2f35114a10d3b0/screen/6033b7a465dbf119a81a9187)
Fixes [#3844](https://github.com/canonical-web-and-design/web-squad/issues/3844)
=> Update /download/raspberry-pi layout

templates/download/server/step2.html
- Replace 'Download the release notes' with 'Read the release notes'
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server step 2
- See that the release note text is better
=> Read the... /download/server

static/js/src/advantage/subscribe/product-selector.js, static/js/src/advantage/subscribe/reducers/form-reducer.js, static/js/src/advantage/subscribe/reducers/ui-reducer.js, static/js/src/ua-payment-modal.js, static/js/src/utils/persitState.js
- Persist redux state to local storage so the form remembers the user's selection.
- go here https://ubuntu-com-9609.demos.haus/advantage/subscribe?test_backend=true
- make some changes to the form
- refresh/navigate to another page and go back
- check that the changes are still here
- make the purchase
- go back to /subscribe
- check that the form "forgot" about your last purchase and is reset to the default state
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9605
@wgx @elioqoshi The way it's done now, the form will remember "forever" the selection. Do we want to clear it at some point? (on a successful purchase or another action?)
=> Persist redux state to local storage

templates/advantage/index.html
Changed "Initially, free subscription is available for Ubuntu 14.04 LTS only." to "Ubuntu 14.04 LTS machines can receive Extended Security Maintenance (ESM) updates and other Ubuntu Advantage benefits" as per the copy doc; https://docs.google.com/document/d/1So3n5HEpBX39xxEkkChnve09gKSr9TgYUcbfdOTCevk/edit?ts=6082875c
- Check the change against the [copy doc](https://docs.google.com/document/d/1So3n5HEpBX39xxEkkChnve09gKSr9TgYUcbfdOTCevk/edit?ts=6082875c).
Fixes #
=> Updated small text in "Free for personal use" section

webapp/certification/api.py, webapp/certification/views.py
Fix vendor params for certified models endpoint
- Go to https://ubuntu-com-9600.demos.haus/certification?text=&form=SoC&vendor=Applied+Micro+Circuits+Corp.&vendor=Qualcomm+Inc&filters=True Some results show up
Fixes https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/179
=> Fix vendor param issue

templates/kubernetes/kubernetes-operations-survey.html
Add k8s survey page
- View the site locally in your web browser at: localhost:8001/kubernetes/kubernetes-operations-survey
- Check the content matches the copydoc on #9615
- Check the form works
Fixes #9615
=> 9615: Add k8s survey page

templates/download/desktop/thank-you.html
- Re-add captcha to /desktop/download/thank-you
- On /desktop/download/thank-you, ensure - in the console - that the nl subscription form goes through when submitting.
=> Re-add captcha to /desktop/download/thank-you

webapp/advantage/views.py
- Fix error handling for payment methods page
How it worked before:
- Go to https://ubuntu-com-9240.demos.haus/advantage?test_backend=true and login
- Go to https://ubuntu-com-9240.demos.haus/advantage/payment-methods?test_backend=true
- Go to https://ubuntu-com-9240.demos.haus/advantage/payment-methods
- it will return you an ugly json saying authentication required
How it works after:
- Go to https://ubuntu-com-9620.demos.haus/advantage?test_backend=true and login
- Go to https://ubuntu-com-9620.demos.haus/advantage/payment-methods?test_backend=true
- Go to https://ubuntu-com-9620.demos.haus/advantage/payment-methods
- It will redirect you nicely to /advantage
=> Fix error handling for payment methods page

static/sass/_pattern_component-details-table.scss, static/sass/styles.scss, templates/certification/component-details.html, templates/certification/model-details.html
- Build component page
- Update URL from model details page to point to component page
- View the site locally in your web browser at: http://0.0.0.0:8001/certification/component/682 or http://0.0.0.0:8001/certification/component/710
- Check the page against the [design](https://app.zeplin.io/project/5f3f890c6afe2512594898b2/screen/6076cde233a60f47a193f604)
Fixes [#162](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/162)
=> Build component page

static/js/src/advantage/subscribe/reducers/form-reducer.js, static/js/src/advantage/subscribe/renderers/form-renderer.js
- Set the default quantity to 0 on small screens so the product summary doesn't show until the user has chosen a quantity
- go here https://ubuntu-com-9606.demos.haus/advantage/subscribe?test_backend=true
- resize your browser until you get the small VP view (875px)
- refresh and fill the form
- The summary and buy button should remain hidden until you increase the quantity
- Verify that it isn't the case on large VP sizes
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9573
=> Remove default quantity for small screens

templates/kubernetes/kubernetes-operations-survey.html
- making the typeform not an iframe, but a popup
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/kubernetes-operations-survey
- See that is works as a popup better than before
Fixes #9650
=> Pop-up survey

navigation.yaml, templates/appliance/community.html, templates/appliance/hardware.html, templates/appliance/index.html, templates/certification/search-results.html, templates/core/features/full-disk-encryption.html, templates/core/features/recovery.html, templates/core/features/secure-boot.html, templates/core/smartstart/guide/certification-and-validation.md, templates/core/smartstart/guide/hardware-setup.md, templates/core/smartstart/guide/index.md, templates/desktop/developers.html, templates/desktop/organisations.html, templates/desktop/partners.html, templates/legal/websites.html, templates/openstack/index.html, templates/server/index.html, templates/shared/forms/interactive/_appliance.html, templates/shared/pricing/_smart-start-prices.html, templates/templates/navigation-enterprise-h.html
- Update links to point to /certification
- Add `Get certified` to secondary nav
- Visit https://ubuntu-com-9619.demos.haus
- Check all links that previously pointed to `certification.ubuntu.com` now point to `/certification`
- Check the "Get certified" link from the secondary nav
Fixes [#168](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/168)
=> Update links to point to /certification

static/js/src/advantage/subscribe/reducers/form-reducer.js, static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/index.html
- Added a check to add the period dropdown if no monthly products are present
- check here, https://ubuntu-com-9651.demos.haus/advantage/subscribe?test_backend=true select server, essential and see that you can choose monthly or yearly at the bottom
- Check here, https://ubuntu-com-9651.demos.haus/advantage/subscribe select server essential and see that there is no dropdown for the billing period
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9647
=> Hide monthly options if no products are available

navigation.yaml, webapp/advantage/views.py
Remove the /payment-methods link from the sub-nav.
If a user has no ubuntu one account and they try to go to
/payment-methods, we send them back to /advantage
If a user has an ubuntu one account but no stripe account we throw a
500.
Users should have no business on the /payment-methods page without both
a ubuntu one account or a stripe account.
- Go to https://ubuntu-com-9653.demos.haus/advantage the payment-methods link from the sub-nav is gone
- Log out and try to go to https://ubuntu-com-9653.demos.haus/advantage/payment-methods it will send you to /advantage because you are not logged in
- Log in and try to go to https://ubuntu-com-9653.demos.haus/advantage/payment-methods it will throw a 500. A bit rude but you should not try to update a card of an account that does not exist. At …
=> Update payment-methods page

webapp/security/schemas.py, webapp/security/views.py
- Accept binary packages for notices. These should not be displayed on the website, but they should be accessible through the API.
Fixes #https://github.com/canonical-web-and-design/ubuntu-com-security-api/issues/46
=> Accept binary packages for notices

templates/certification/model-details.html
- Remove accordion from model details page when there is only one release 
- Visit: https://ubuntu-com-9658.demos.haus/certification/202005-27924 and see accordions visible for releases
- Visit: https://ubuntu-com-9658.demos.haus/certification/202004-27860 and see accordion no longer visible for one release
Fixes [#185](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/185)
One release: 
Multiple releases:
=> Remove accordion for one release

navigation.yaml
Add docs navigation for OpenStack
- Open the demo and go to /openstack
- Click the docs navigation item and check docs load
- Click around docs and see the navigation is persistent
=> Add docs navigation for OpenStack

templates/base_index.html
Fixes according to [w3c validation ](https://validator.w3.org/nu/?doc=https%3A%2F%2Fubuntu.com%2F)
Check demo on w3 Validator:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fubuntu-com-9666.demos.haus%2F
as opposed to current ubuntu.com
https://validator.w3.org/nu/?doc=https%3A%2F%2Fubuntu.com%2F
- Check nothing looks wrong on the takeovers
- Check that logos or elements with `p-inline-images__item` look all right.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9665
=> Fix w3c non-compliant issues

templates/templates/navigation-enterprise-h.html
Updated enterprise AI link to /ai/what-is-kubeflow
- Check it against the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit#heading=h.x5bjdjaazslx)
Fixes #9520
=> Update AI link

webapp/advantage/views.py
- Fix payment warning notification. The problem is that the `payment_method_warning` would take the value of the last subscription. Now the if conditions if you want to update it or not.
=> Fix payment warning notification

templates/templates/footer.html, templates/templates/navigation-enterprise-h.html
- Add Goverment back to enterprise mega menu and footer
- See that 'Government' is in the list of sectors
Fixes #9664
=> Add Goverment back to enterprise mega menu and footer

webapp/cube/views.py
- auth_entry=login instead of auth_entry=register
- View the site locally in your web browser at: http://0.0.0.0:8001/cube
- see the changed get parameter
Fixes #9674
=> Change cube register link

templates/kubernetes/contact-us.html, templates/kubernetes/index.html, templates/kubernetes/install.html
- Fix contact us modals on /kubernetes and /kubernetes/install
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes and http://0.0.0.0:8001/kubernetes/install
- See that all the contact us cta's open a modal
=> Fix contact us modals on /kubernetes and /kubernetes/install

templates/openstack/consulting.html, templates/openstack/index.html, templates/pricing/consulting.html, templates/shared/pricing/_openstack-packages.html
- Update /openstack/consulting page
- http://0.0.0.0:8001/openstack
- http://0.0.0.0:8001/openstack/consulting
- http://0.0.0.0:8001/pricing/consulting
- See that the 'Private Cloud Build' and 'Private Cloud Build Plus' tables are the same, but have different CTA
Fixes [#4078](https://github.com/canonical-web-and-design/web-squad/issues/4078)
=> Update /openstack/consulting page

templates/workstations-journey-to-ai/index.html
Add Canonical and Dell AI webinar page
- View the site locally in your web browser at: http://0.0.0.0:8001/workstations-journey-to-ai
- Check the [copy](https://docs.google.com/document/d/1qFj7Q1lAQpVCKOFjlJz0S6VKy9ElJ-sy2aS3xPF_e04/edit#)
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/4067
=> Add Canonical and Dell AI webinar page

templates/financial-services/index.html
- View the site locally in your web browser at: http://0.0.0.0:8001/financial-services 
- See that the strip loads the correct data and the url works
Fixes #9633
=> Add blog strip on /financial-services page

templates/advantage/index-no-login.html
- Remove space after Sign in link on /advantage
- Hover over the 'Sign in' link and see that there is no underline on the space after the 'n'
Fixes #9661
=> Remove space after Sign in link on /advantage

templates/kubernetes/index.html
- Fix meta title of the K8s overview page
- Ensure the meta title of the kubernetes overview page is "Enterprise Kubernetes for multi-cloud operations | Ubuntu"
=> Meta title fix for K8s overview page

templates/aws/pro.html, templates/azure/pro.html
- Update CTA on `/aws/pro` and `azure/pro` to point to contact us modal
- Fix extend from ceph to aws
- View the site locally in your web browser at: http://0.0.0.0:8001/aws/pro and http://0.0.0.0:8001/azure/pro
- Check against comments and resolve them in [aws copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit) and [azure copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit?ts=6082cee7#) 
Fixes #9614
=> Update CTA on aws and azure

static/js/src/chart-data.js, templates/about/release-cycle.html
- Update OpenStack X to Xena on /about/release-cycle
- See that X is now Xena
Fixes [#4080](https://github.com/canonical-web-and-design/web-squad/issues/4080)
=> Update OpenStack X to Xena on /about/release-cycle

templates/security/livepatch.html
- Updated datasheet link on livepatch page
- Open the demo and go to /security/livepatch
- Check the asset link goes to the new link suggested in the issue
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9681
=> updates datasheet link on livepatch page

templates/openstack/index.html
- Update /openstack with new whitepaper and logo
- See that there is a new whitepaper in the banner and the KAUST logo replaces Cape Town
Fixes [#4081](https://github.com/canonical-web-and-design/web-squad/issues/4081)
=> Update /openstack with new whitepaper and logo

templates/kubernetes/docs/1.21/release-notes.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/supported-versions.md
- Added 1.21ck1 release notes
- Updated bundle revision number in various places
=> K8s1.21+ck1 release updates

templates/download/iot/index.html
- Fix typo on /download/iot - replace s/machinei/machine/
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot
- See that the typo has been fixed
=> Fix typo on /download/iot

templates/gcp/pro.html
- updated the 'Priced for cloud' section, changing the hourly price ranges.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4084
=> updates average hourly ubuntu pro cost range

webapp/cube/views.py
=> CUBE: Fix login URL

templates/certification/model-details.html
- This was done initially [here](https://github.com/canonical-web-and-design/ubuntu.com/pull/9658), but was lost in the rebase.
- An additional conditional render of `aria-hidden=true` has been added to fix [this](https://github.com/canonical-web-and-design/ubuntu.com/pull/9658#discussion_r623284826)
- Visit: /certification/202005-27924 and see accordions visible for releases
- Visit: /certification/202004-27860 and see accordion no longer visible for one release
Fixes [#188](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/188)
One release: 
Multiple releases:
=> Remove accordion one release

templates/azure/private-offer.html
- Update link text to match the latest change in the [copydoc](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/azure/private-offer
- Check the link text is now `Learn more >`
=> Azure private offer link text

templates/shared/pricing/_ua-for-infrastructure.html
Add FIPS to the UA service description
- Go to https://ubuntu-com-9718.demos.haus/legal/ubuntu-advantage-service-description
- Check FIPs is a row on the table
- Also check its in the table at https://ubuntu-com-9718.demos.haus/pricing/infra
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9716
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9717
=> Add FIPS to the UA service description

static/js/src/ua-payment-modal.js
- Correctly catch errors for the payment modal call and remove loading state even if it fails.
This is a bit tricky to QA
Here is one way: https://app.zenhub.com/workspaces/web--ubuntu-clan-5931746dba512f05402b61f6/issues/canonical-web-and-design/ubuntu.com/9724
Another way would be to fetch this branch and modify the call to purchase preview so it always returns an error and see that the modal still loads.
This addresses https://github.com/canonical-web-and-design/web-squad/issues/4087 and should remove the bug for users but I don't believe this fixes the root cause of the payment preview failing.
=> Remove loading state from modal if the payment preview fails

static/js/src/advantage/contracts-api.js, static/js/src/ua-payment-modal.js, webapp/advantage/api.py, webapp/advantage/schemas.py, webapp/advantage/views.py
This is needed for a new requirement we will be introducing in ua-contracts: that calls to set customer info must always contain the customer name and country. While that doesn't roll out to production in ua-contracts, it should still be safe to call this method with this added field.
=> Pass customer name when setting customer info as guest

templates/kubernetes/docs/1.21/components.md
- The 1.21 components page needed updated references to the shipped revisions of charms
- includes new list of image deltas
=> K8s charm rev updates for 1.21+ck1

templates/16-04/azure.html
- Update removes title from 'ubuntu on azure' video at /16-04/azure
- View the site locally in your web browser at: http://0.0.0.0:8001/16-04/azure
- Compare to copy doc (https://docs.google.com/document/d/1V99KwimN8Hla8L_CikNc6I0amqj99cSrBsVlAjIkBqE/edit?ts=6082b410) and mark as resolved
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9621
=> update removes title from ubuntu on azure video at /16-04/azure

templates/templates/navigation-enterprise-h.html
- Update adds managed app link to navigation
- Compare against [Copy-doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9776
=> Update adds managed app link to navigation

webapp/advantage/views.py
- Use contract allocations to display the number of machines on the table row.
- Have a detached contract
- Check the /advantage page. You should see a number instead of the "-" as the number of machines.
Fixes #9750
=> Change to number of machines

templates/blog/article.html
- Add rich strucutre data for blog posts https://developers.google.com/search/docs/data-types/article
- Connect to the VPN
- View the site locally in your web browser at: http://0.0.0.0:8001/blog/ubuntu-16-04-lts-transitions-to-extended-security-maintenance-esm
- Inspect HTML
- Make sure that there is a `application/ld+json` script in the header with the releavant information
- This should be green (test with the demo link): https://search.google.com/test/rich-results
=> Add rich structure data ubuntu.com/blog posts

templates/cube/microcerts.html, tests/test_cube.py, webapp/cube/views.py
CUBE: Use links that authenticate the user before redirecting to EDX
- Asked Kellen to QA see his comment bellow
Fixes #9787
=> CUBE: Use links that authenticate the user before redirecting to EDX

navigation.yaml, templates/certification/index.html, templates/certification/model-details.html
- First draft of refactoring overview page  - see list of tasks [here](https://docs.google.com/document/d/1FRi83535YcpAv3jJ2lb4dpcBNlviA2JomD0d9gD5yAQ/edit#)
- Add `persist: True` to nav to keep secondary nav on model details pages
- Replace download link section and fix accordion on model details page which was accidentally removed in a previous rebase
- Check the page against the [doc](https://docs.google.com/document/d/1FRi83535YcpAv3jJ2lb4dpcBNlviA2JomD0d9gD5yAQ/edit#)
- This page is also being looked at …
=> [Certs] Refactor overview page

package.json, static/sass/_pattern_cube-progression.scss, static/sass/_pattern_cube-table.scss, templates/cube/microcerts.html, yarn.lock
- Extract `.is-faded` to it's own class so it can be conditionally added to progression hero depending on module status
- Add media query to width of tables to fix mobile view
- Fix text overflow on cards by adding `white-space: normal` to the list of topics
- Filed an [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3754) on Vanilla
- Force all statuses of modules to passed by adding `course["status"] = "passed"` to line 127 of `webapp/cube/views.py`
- See the progression hero change to show passed microcerts
- Check the microcerts table on mobile view
Fixes #9789 
none passed:
force …
=> [CUBE] Fix progression hero and broken mobile view

templates/cube/microcerts.html, webapp/cube/content/cube-qa.yaml, webapp/cube/content/cube.yaml
Update `/cube/microcerts` copy
- go to `/cube/microcerts`
- check against [copy](https://docs.google.com/document/d/1IHmr2SIxcEKVNN2sA-z_32PV0fCXi38pmeVP7k7O1mM/edit?ts=60a669a4#) and resolve the comments
Fixes #9800
=> CUBE: Microcerts page copy

templates/certified/index.html
- The API returns the number of IoT devices for a make in the `smart_core` field and `soc` for SoC devices. The `total` field counts all of the machines for that make, not just the IoT or SoC ones. This fixes the template to get the data from the correct field.
- Verify that the total for IoT Dell is 4 and not 326 and that the total for SoC Huwai is 6 and not 72.
Fixes #9825
=> Fix certified device count for IoT and SoC

package.json
Fixes #9838
Since there's no hope of actually fixing these errors in this PR, I'm making the `lint-scss` check non-mandatory for now. And I've filed https://github.com/canonical-web-and-design/ubuntu.com/issues/9843 to be addressed soon.
QA
--
See the glorious `lint-scss` check fail.
=> Fix stylelint command, and `lint-scss`

static/sass/_pattern_navigation.scss
- Fixes over-sized navbar
- Check to see if the navbar is the right size.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9814
=> Fixes over-sized navbar

templates/templates/_error_login.html, webapp/login.py
- Show error page when user tries to login but has blocked cookies
- Disable cookies on your browser for `localahost:8001`
- Try to login and see the error page
Fixes #9283
=> Handle login failure when cookies are blocked or missing

templates/ai/what-is-kubeflow.html
- Copy update on `/ai/what-is-kubeflow`
- View the site locally in your web browser at: http://0.0.0.0:8001/ai/what-is-kubeflow
- Check the page against the [copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit?ts=60ae04f8#heading=h.17ts46pu1qo0)
Fixes [#4161](https://github.com/canonical-web-and-design/web-squad/issues/4161)
=> Copy update what-is-kubeflow

templates/kubernetes/index.html
- Add `is-dark` class to `p-divider`
- Check text colour
Fixes #9836
=> Fix dark text on dark background

templates/advantage/index.html
- Remove unnecessary echo
- Go to https://ubuntu-com-9857.demos.haus/advantage does it take ages to load the page to see your canonical subscriptions? If no, it works.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/13
=> Fix slow page problem

templates/0_docs/content_strips.html, templates/aws/fips.html, templates/azure/fips.html, templates/security/esm.html
- Found all places where the `is-dark` class on the strip has a `row p-divider` child - as the text contrast is broken 
Fixes #9854 
[Before]
[After]
=> Move is-dark class from strip to row

templates/shared/_cloud-contact-us-form.html
- Removing lpid field from cloud contact form to avoid overriding the form acquisition program name
- Fill a form such as `/support/contact-us?product=education-discount`
- Contact GE team to verify the outcome
=> Removing lpid field from cloud contact form

templates/blog/product-cards.html, templates/blog/product-cards/_docker-security.html
- Adding the Docker security product card on blog posts with the "Docker" tag
- Ensure the card is present on blog posts tagged with "Docker", such as `/blog/what-is-virtualisation-the-basics`
Fixes #
=> Adding Docker security product card

templates/openstack/compare.html, templates/shared/contextual_footers/_openstack_further_reading.html, templates/shared/contextual_footers/_private_cloud_contact_us.html
- Update `/openstack/compare`
- The copy doc asks for "Recent blogs tagged with 'openstack' and 'private cloud' keywords" but I'm not sure how to use 2 different tagIds? 
- Check against [copy doc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit#)
Fixes #9846
=> Copy update on /compare

templates/security/cis.html
- Builds /security/cis page
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cis
- Compare against [copy-doc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9751
=> 9751 cis page build

templates/security/cc.html
- Builds /security/cc page
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cc
- Compare against [copy-doc](https://docs.google.com/document/d/1JLnHR9Xuuc1t6ojrnBuMWir5XABgf1L7WVpGGtlLaBo/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9748
=> 9748 cc page build

templates/openstack/compare.html
- I made a typo, fixed it
- See that is says 'OpenStack Charms'
=> Add an "s" on /openstack/compare

templates/legal/websites.html
- Update list of active Canonical websites
- Made the list `is-split`
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/websites
- Compare to the [copy doc](https://docs.google.com/document/d/1UPhx8ARReA6-vDYNHbsGmJN-rY1LHGacq6g4PV6eCoA/edit#)
Fixes #9878
=> Update list of active Canonical websites on /legal/websites

templates/security/livepatch.html
- This is a minor fix that updates the way to get a free token to prevent a recursive link when connecting to the now deprecated auth.livepatch.canonical.com
Resolves #9891
=> Corrects the URL to prevent recursive links

templates/index.html
Add meta image to the homepage
- Go to https://www.opengraph.xyz/url/https:%2F%2Fubuntu-com-9890.demos.haus%2F/
- Check it looks better then https://www.opengraph.xyz/url/https:%2F%2Fubuntu.com/
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9864
=> Add meta image to the homepage

templates/certified/hardware-details.html, templates/certified/model-details.html
- Clean ducplicate `| Ubuntu`
- The `| Ubuntu` is added by default by the base template
- View the site locally in your web browser at: http://0.0.0.0:8001/certified/201811-26620 
- Page title should only have one `| Ubuntu`
=> Clean titles for certified pages

templates/training/index.html
- Fix rich data on training page
- The google search console was signaling this page as failing (see: https://search.google.com/test/rich-results?id=XI6RL64zVxpqUekTbJ4xUQ )
- Get HTML and paste it on the code tab: https://search.google.com/test/rich-results
- Or get the demo link directly: https://search.google.com/test/rich-results?id=yLUA_7IuL3HSO3R-4gDHsg
=> Fix rich data training page

webapp/advantage/views.py
- Fix lost renewal bug
- Go to https://ubuntu-com-9896.demos.haus?email=email@address.com
- The email address should have an account with both `lost` and `active` renewals
=> Fix lost renewal bug

static/sass/_pattern_navigation.scss, templates/templates/_navigation.html
- Increase the height of the navigation to 56px to match the latest in Vanilla
- Removed the duration of the animation of the links to make it feel faster
- Check the header is 56px height
- Check live is shallower
- Check the dropdowns work
- Check the user menu aligns when open
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9865
=> Align the navigation height with the new Vanilla styling

static/sass/_pattern_takeovers.scss, templates/base_index.html, templates/shared/_notice_default.html
- Only render the `lang` attr on the takeover if it's setting a difference lang
- Remove redundant alt contents. If the contents match sibling text the alt is redundant.
- Switching some skip level headings to paragraphs with heading classes
- Install Waves the browser extension
- Go to https://ubuntu.com and run it.
- Open the demo in a different tab and run Waves. 
- See there are no errors and less alerts in the demo
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9915
=> Homepage accessibility improvements

templates/certified/model-details.html
Fixes #9921
Updated the template to use form_factor instead of category.
Verify that this shows _Industrial PC system certified with Ubuntu_ and not _Ubuntu Core_.
https://ubuntu-com-9922.demos.haus/certified/202103-28845
=> show form factor for certified models

templates/certified/index.html
Fix centered classname on ccertified
- Open the demo and go to /certified
- Check the hero image is centered in the `col-5`
=> Fix centered classname on certified

templates/cube/index.html
- Add copy for open badges to /cube
- View the site locally in your web browser at: http://0.0.0.0:8001/cube
- Compare to the [copy doc](https://docs.google.com/document/d/1QuhO-9FEOGLrYp8bErS_9snqdljl7d6tFAUoNQxoVDQ/edit?ts=60c8af8f)
Fixes [#4183](https://github.com/canonical-web-and-design/web-squad/issues/4183)
=> Add copy for open badges to /cube

templates/kubernetes/docs/1.19/upgrading.md, templates/kubernetes/docs/azure-integration.md, templates/kubernetes/docs/charm-azure-integrator.md
- small fix for upgrade page
-  added details of new azure relations
- added instructions for using Azure LB
=> K8sDocs-azure/upgrade additions

templates/certified/search-results.html
Added https://docs.google.com/document/d/1pSkPo5fvgrLb-Tjiq_he9MAvPLFX79xiz-H9s2mSXgI/edit# to the meta_copydoc to https://ubuntu.com/certified?q=Dell
- Check that the copy doc plugin opens to https://docs.google.com/document/d/1pSkPo5fvgrLb-Tjiq_he9MAvPLFX79xiz-H9s2mSXgI/edit# in https://ubuntu.com/certified?q=Dell
Fixes #9905
=> Added the correct copy doc

static/js/src/advantage/manage-subscription.js, templates/advantage/index.html, templates/advantage/payment-methods/index.html, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html, webapp/advantage/views.py
TLDR; List of changes:
- display messages on success or failure for both resizing and cancellation
- show up the 3DS modal if the resizing fails because of 3ds_authorizaion missing.
_______
- we refresh the page
- the new number of machines will be displayed
- we echo message saying that the resizing was successful
- we refresh the page
- the new number of machines will be displayed
_______
- we refresh the page
- the number of machines does not change
- we show the payment methods notification
- we do not refresh the page
- we show a message giving some feedback of what happened
- if the user tries to make any other resizing of this subscription of another subscription of the same type we will show the following message and reload the page (the reload is needed because they likely have a …
=> Update resizing and cancellation

navigation.yaml, templates/telco/osm/onboarding-network-functions.html
Onboarding network functions page, part of /telco
- Check https://ubuntu-com-9884.demos.haus/telco/osm/onboarding-network-functions against [copy docs](https://docs.google.com/document/d/1_35nO3riTFlSFSp2B7FFdl60cjZe7Owwv0bcjY1s8Kg/edit#)
Design:
Fixes canonical-web-and-design/web-squad#4154
=> Build onboarding network functions page

templates/desktop/partners.html
- Fix 404 on certification link
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/partners
- Link `Learn more about Ubuntu Certified hardware` (at the bottom of the page) shouldn't 404
=> Fix 404 certification link

templates/contact-us/form/index.html, templates/contact-us/form/thank-you.html
- Adding a temp form for blender support
- View the site locally in your web browser at: http://0.0.0.0:8001/contact-us/form?product=blender-support
- See that the form uses formid 4052 and returns you to https://ubuntu.com/contact-us/form/thank-you?product=blender-support
=> Adding a temp form for blender support

templates/templates/navigation-enterprise-h.html
Added a link to the Juju k8s report
- Go to https://ubuntu-com-9939.demos.haus/#enterprise
- Open the enterprise navigation
- Click the "Industry report" link
- Check that it takes you to https://juju.is/cloud-native-kubernetes-usage-report-2021
=> Add link in navigation to k8s report

templates/certified/index.html
Fixes #9944
This removes the reference section from /certified.
Navigate to https://ubuntu-com-9945.demos.haus/certified and verify that the reference section has been removed.
=> Remove Certification reference section

static/js/src/utils/persitState.js
Fix a bug where user who visited the site on a previous version would have a missing attribute in their localstorage state
=> Override the defaultState values instead of trusting blindly the local state

templates/cube/study/index.md, webapp/app.py, webapp/cube/views.py
Add link to the study labs from the study materials index page
- Go to `/study/materials`
- Click the purchase study labs button and:
- If you have the enrolment you should be redirected to the course in the EDX platform.
- If you don't have the enrolment you should be redirected to `/cube/microcerts` which is where the purchase will be done from in the future.
Fixes #9867
Fixes #9913
=> Add link to the study labs from the study materials index page

templates/advantage/subscribe/index.html, templates/download/server/s390x.html
- Remove noindex on subscribe page 
- Remove noindex on s390x download page
- View the site locally in your web browser at: http://0.0.0.0:8001/download/server/s390x
- Make sure those 2 pages don't have a noindex tag (in the header)
=> Remove noindex on subscribe page and s390x page

templates/advantage/shared/_certifications-info.html
- Change UA cert text
- check that the texts in the certification tab on https://ubuntu-com-9959.demos.haus/advantage have the changes described here: https://github.com/canonical-web-and-design/ubuntu.com/issues/9607
Fixes #9607
=> Change UA cert text

templates/kubernetes/docs/index.md
Adds a link from Kubernetes docs to survey report.
Alex wants this link to go live by/on 29th June
=> add link to survey

templates/openstack/compare.html, templates/openstack/features.html, templates/openstack/index.html, templates/openstack/managed.html, templates/openstack/what-is-openstack.html, templates/shared/contextual_footers/_openstack_documentation.html
Replace the newsletter contextual footer from OpenStack
- Open then demo
- Go to /openstack#get-in-touch
- Go to the last stage and click the label "I agree to receive information about Canonical's products and services." and check it works.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9958
=> Replace the newletter contextual footer from OpenStack

templates/cube/study/index.md
Made it more explicit that the Study Labs are an enhanced version of the free materials, per Marketing's request.
- Check the content on `/cube/study`
=> New language for "Further preparation" section

navigation.yaml, templates/security/certifications/docs/document.html, templates/security/certifications/docs/search-results.html, tests/cassettes/TestRoutes.test_security_certs_docs.yaml, tests/test_routes.py, webapp/app.py
- Add discourse module for Security certification docs
- Add search for docs
- Check https://ubuntu-com-9949.demos.haus/security/certifications/docs
And compare with [current site](https://security-certs.docs.ubuntu.com/en/) and see that the content is the same.
Discourse content [is here](https://discourse.ubuntu.com/t/about-the-documentation-category/22810)
- I couldn't get search to work on demo, but it works on local when absolute URL is provided. e.g. `site=localhost:8001/security/certifications/docs` to `build_search_view`. So on demo, it will work but it will not be able to find anything
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4207
=> Security certification docs

static/js/src/advantage/subscribe/react/components/Summary.jsx, static/js/src/advantage/subscribe/reducers/form-reducer.js, static/js/src/advantage/subscribe/reducers/ui-reducer.js
- Added the ability to prepop the wizard with a query param
- go here https://ubuntu-com-9963.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true&free_trial=uai-essential-physical&quantity=222
- experiment with different ids and quantities in the url
- check that the selected product and quantity matches
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9493
`uaa-essential`
`uaa-essential-virtual`
`uaia-essential-physical`
`uaia-essential-virtual`
`uaa-advanced`
`uaa-advanced-virtual`
`uaa-essential-desktop`
`uaa-standard`
`uaa-standard-virtual`
`uaia-advanced-physical`
`uaia-advanced-virtual`
`uai-advanced-desktop`
`uai-advanced-physical`
`uai-advanced-virtual`
`uaia-standard-physical`
`uaia-standard-virtual`
`uai-essential-desktop`
`uai-essential-physical` …
=> Pre-fill the product selector with a free trial

templates/security/certifications.html
- Copy update removed SCAP 20.04
- Check against [copy doc](https://docs.google.com/document/d/1CiF-dPqG1Y--h4FWfgKB1ft4G3nC2Boa8NT_JG7D6dQ/edit?ts=60dc11c8#
)
Fixes #4212
=> Copy update removed SCAP 20.04

konf/site.yaml
- Redirects old seucrity certs site https://security-certs.docs.ubuntu.com/en/ to new site https://ubuntu.com/security/certifications/docs/fips-cloud-containers
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4208
=> Security cert docs redirects

static/js/src/advantage/subscribe/react/PurchaseModal.jsx
- Display the second step of the form only if there is a default payment method
- Go to https://ubuntu-com-9985.demos.haus/advantage/subscribe?test_backend=true 
- log in with an account that has no payment method set
- open the modal and check that you see the form
- log out
- Log in with an account with a payment method
- open the modal and  check that you see the summary + pay button
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/43
=> Check for defaultPaymentMethod instead of customerId to decide which step to show

static/sass/_pattern_card.scss
- Removed arrows from selected Ubuntu version input
- go to https://ubuntu-com-9986.demos.haus/advantage/subscribe and check that the arrows are gone
Fixes #9840
=> Remove arrow on selected version

static/sass/_pattern_navigation.scss
- Replaces deprecated variable with correct use for Vanilla 2.32
This should fix Vanilla build errors when updating to v2.32 in #9937
- Check out this feature branch or use [demo](https://ubuntu-com-9993.demos.haus)
- Make sure navigation renders as expected
=> Fix missing grid-margin-width in Vanilla 2.32

static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoAnon.jsx, templates/advantage/subscribe/form/_feature_coverage.html
- Took the link out of the cards and put it in the section's subtitle
- Renamed cards to Infra, Apps and Infra + Apps
- replaced periods in number by commas
- go to https://ubuntu-com-9994.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true
- check that it matches the [design](https://user-images.githubusercontent.com/5436686/124556647-d485b780-de38-11eb-8baf-ed450413c3bc.png)
Fixes #9961
=> Fix links and number in product selector

static/js/src/advantage/set-modal-info.js, static/js/src/advantage/tests/fixtures/renewal-data.js, static/js/src/advantage/tests/set-modal-info.test.js, templates/advantage/table/_renewal-actions.html
- Fix renewal dates
- Renewal modal shows incorrect start and end date of the renewal
- The logic before was to look at the contract end and add X amount of months
- Now we use the start and end dates of the renewal
- Have a renewal (ask for help)
- Click the renew button
- Confirm that the dates match the renewal dates
Fixes #9920
=> Fix renewal dates

static/js/src/ua-payment-modal.js
- If you have an account with a renewal but you have no customer stripe account 
- You press on the renew button
- Everywhere you click after will trigger an `get-customer-anon` request
- Have an account without a stripe customer account and a renewal
- Open the console
- Click on the renew button
- Close the modal
- No more `get-customer-anon` requests get made onclick
Fixes #41
=> Fix onclick endless requests

navigation.yaml, templates/telco/cnf.html, templates/telco/index.html
- Builds telco/cnf page
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/cnf
- Compare against [copy-doc](https://docs.google.com/document/d/1IpOPiWidozQ7w1hyM52yQn1gSwHODsItn1ZnMQ0retw/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4191
This image was made by a non-design team member, just thought I should flag it. But it looked good to me.
=> Builds telco/cnf

templates/certified/base_certification.html, templates/certified/component-details.html, templates/certified/hardware-details.html, templates/certified/index.html, templates/certified/model-details.html, templates/certified/search-results.html
- Some pages were using cube copydocs
- Since there is one copydocs for this section, use the index one on the template
- Check copydocs
=> Replace copydocs links with correct links

templates/cube/microcerts.html, webapp/cube/content/cube-qa.yaml, webapp/cube/content/cube.yaml, webapp/cube/views.py
Prepare buttons on cube microcerts now link the the courseware
- Check the prepare buttons link to the appropriate sections of the study labs course(see #9953)
Fixes #9953
=> Prepare buttons on cube microcerts now link the the courseware

static/sass/_pattern_card.scss, templates/advantage/subscribe/form/_feature_coverage.html, templates/advantage/subscribe/form/_tech_support.html
- Added a "free trial" label on no support option
- changed the Apps "new" label to grey so it doesn't look like a :christmas_tree: 
- go to /advantage/subscribe?test_backend=true
- Check that it looks good
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/67
=> Add free trial label on support section

templates/advantage/index-no-login.html
- Added free trial paragraph to logged out /advantage
- Added a button to a pre-filled product selector
- go to https://ubuntu-com-10014.demos.haus/advantage?test_backend=true
-  Click the button and see that it brings you to a modal where you can start the trial
=> Add extra copy on logged out advantage

static/js/src/advantage/subscribe/renderers/form-renderer.js, static/sass/_pattern_shop-cart.scss, templates/advantage/subscribe/index.html
- Added a "Free trial" label in the sticky footer for eligible products
- Go to /advantage/subscribe?test_backend=true
- play with the selectors and check that it displays it for products that are eligible for a trial
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/68
=> Add free trial label to sticky footer if product is eligible

templates/kubernetes/docs/1.16/charm-containerd.md, templates/kubernetes/docs/1.16/charm-flannel.md, templates/kubernetes/docs/1.16/charm-keepalived.md, templates/kubernetes/docs/1.17/charm-containerd.md, templates/kubernetes/docs/1.17/charm-flannel.md, templates/kubernetes/docs/1.17/charm-keepalived.md, templates/kubernetes/docs/1.18/charm-containerd.md, templates/kubernetes/docs/1.18/charm-easyrsa.md, templates/kubernetes/docs/1.18/charm-flannel.md, templates/kubernetes/docs/1.18/charm-keepalived.md, templates/kubernetes/docs/1.19/charm-containerd.md, templates/kubernetes/docs/1.19/charm-easyrsa.md, templates/kubernetes/docs/1.19/charm-flannel.md, templates/kubernetes/docs/1.19/charm-keepalived.md, templates/kubernetes/docs/1.20/charm-containerd.md, templates/kubernetes/docs/1.20/charm-easyrsa.md, templates/kubernetes/docs/1.20/charm-flannel.md, templates/kubernetes/docs/1.20/charm-keepalived.md, templates/kubernetes/docs/1.21/charm-containerd.md, templates/kubernetes/docs/1.21/charm-easyrsa.md, templates/kubernetes/docs/1.21/charm-flannel.md, templates/kubernetes/docs/1.21/charm-keepalived.md, templates/kubernetes/docs/charm-containerd.md, templates/kubernetes/docs/charm-easyrsa.md, templates/kubernetes/docs/charm-flannel.md, templates/kubernetes/docs/charm-keepalived.md
- Various charm docs needed to be updated to namespace charms
=> K8sDocs Charm deploy updates

templates/security/cc.html
- Updates copy on /security/cc
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cc
- Compare https://ubuntu-com-10027.demos.haus/security/cc against [copy-doc](https://docs.google.com/document/d/1JLnHR9Xuuc1t6ojrnBuMWir5XABgf1L7WVpGGtlLaBo/edit#)
- I have set the links to the form to /security/contact-us as the links provided in the copy didn't make sense.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4228
=> Copyupdate-4228

templates/templates/navigation-developer-h.html, templates/templates/navigation-enterprise-h.html
- Added 'Become a Certified Ubunut Engineer' links on the Enterprise and Developer menu
- Removed all the extra '>' on the Developer menu
- Removed all the non-link list items as a test... need to remove the comments later
- View the site locally in your web browser at: http://0.0.0.0:8001/#enterprise http://0.0.0.0:8001/#developer
- Compare to the copy docs [enterprise](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit?disco=AAAANcZBZ5M&ts=60edf8d8&usp_dm=true) and [developer](https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7Gl …
=> Update enterprise and developer menus with CUBE

webapp/cube/views.py
The key that holds the study labs course ID was updated on the YAML config file so we need to update the view to get the right key.
- Go to `/cube/study` and make sure you get a button rather than an error message.
Fixes #10031
=> Fix KeyError on cube_study_labs_button view

static/js/src/advantage/subscribe/reducers/ui-reducer.js
- Stopped auto-opening the modal when a user lands on /subscribe after having clicked the free trial button
- go to /advantage (logged out)
- click Try ESM Apps free
- See that you land on / subscribe with Physical Apps and essential pre-selected but the modal is closed
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/75
=> Don't show the modal for prepopulated free trial

static/sass/_pattern_shop-cart.scss, templates/advantage/subscribe/index.html
- Move label to the right of the period select
- tweak spacing
- Go to /advantage/subscribe and play with different free trials options
- or check screenshots
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/76
=> Move label to the right of the select period select

templates/blog/newsletter-form.html
- Add `formVid` to newsletter form
- Fill in the newsletter form
- In the insprector, see that you get a 200, not a 403 from marketo
Fixes #10038
=> Fix newsletter form with formVid

templates/security/certifications.html, templates/security/fips.html
- Updates copy on /security/certifications
- Last minute copy changes on fips.
- Compare against certification [copydoc](https://docs.google.com/document/d/13RcVvHBAoywfk3o5Dy-16F3KrMytL9-2v6wWbW444Ko/edit)
- Compare against fips [copydoc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit?ts=60f04150)
- Note: waiting on the link to the embedded video, see screenshot below.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4227
Where the video …
=> /security/certifications copyupdate

templates/advantage/table/_manage-monthly.html
- Number of days to expiry can be flawed if a product was purchased both from a monthly and a yearly subscription, so we will hide it for now
- Have a monthly subscription on your testing account
- Login to https://ubuntu.com/advantage/subscribe?test_backend=true
- Disable auto-renewal for your account
- Take a look at your monthly product -> Click change subscription
- You will see a notification telling you how many days until expiry
- Go to: https://ubuntu-com-10037.demos.haus/advantage?test_backend=true
- Take a look at your monthly product -> Click change subscription
- You will **_NOT_** see a notification telling you how many days until expiry
Fixes #74
=> Hide expiration date

templates/training/index.html
- Fix missing name issue from new product added from https://github.com/canonical-web-and-design/ubuntu.com/pull/9976
- See: https://search.google.com/test/rich-results?id=1gW1vYru48TDbSsic0_wEg
- Make sure it still works and that the content of the Juju Administrator and Charm Developer are still well formatted (last 2 products)
- Use demo link and test on https://search.google.com/test/rich-results (or look at this result: https://search.google.com/test/rich-results?id=eJeash2iZOTwxkKM5KITvw )
=> Add missing name for Product schema

konf/site.yaml, tests/test_cube.py, webapp/app.py, webapp/cube/views.py
- Remove login requirement from `/cube`
- Remove custom authorization from `/cube/microcerts` and `/cube/study` so it's open to anyone with an Ubuntu ONE SSO account (not only users with `@canonical.com` emails)
- Update tests
- Clear session so you aren't logged in to SSO
- View cube homepage page at: https://ubuntu-com-10055.demos.haus/cube - the page should be visible
- Go to: `/cube/microcerts` and `/cube/study` (still not logged in), you should be asked to log in to SSO. 
- log into SSO with an email that doesn't end in `@canonical.com`. Check you are authorized to view both `/cube/microcerts` and `/cube/study`
Fixes #10051
=> [CUBE] - Remove custom authorization from cube pages

templates/workstations-journey-to-ai/index.html
- fixed some malformed html I noticed
- View the site locally in your web browser at: http://0.0.0.0:8001/workstations-journey-to-ai
- See that the h4's end properly
=> Fix html in /workstations-journey-to-ai

templates/openstack/what-is-openstack.html
Add the OpenStack project chart to what is OpenStack page
- Go to /openstack/what-is-openstack
- Jump to the "How big is the OpenStack project?" section
- See the OpenStack chart
Fixes #10052
=> Add the OpenStack project chart to what is OpenStack page

static/js/src/dynamic-forms.js, templates/openstack/pricing-calculator.html, templates/shared/forms/interactive/openstack-cost-calculator.html
- Added an option to add another instance type (up to 4) on pricing calculator contact form
- Visit page at: https://ubuntu-com-10054.demos.haus/openstack/pricing-calculator
- Click on the "Get cost estimates" button
- Click the "Add another instance" button
- Check Instance Type 2 appears. Then 3, then 4, then the button to add another instance should be disabled
Fixes #10049
=> Add button to add another instance type

static/js/src/advantage/subscribe/react/APICalls/registerPaymentMethod.jsx
- Fix a typo in a variable name causing the organisation name not to be saved correctly for new customers
- go to /advantage/subscribe?test_backend=true as a guest
- make a new purchase 'for an organisation'
- check that the organisation name is passed correctly to the backend
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/80
=> Fix organisation name not being saved correctly

package.json, tsconfig.json, yarn.lock
- Add TypeScript config according to the [esbuild docs](https://esbuild.github.io/content-types/#typescript).
- Emit errors when building TypeScript files.
- Check that the site builds and runs as it did.
- If you wish you could add a .ts or .tsx file to build.js and check that it builds (or emits errors) when running the site.
Fixes canonical-web-and-design/commercial-squad#83.
=> Build typescript

templates/advantage/index.html
- removed "Initially, this free subscription is available for Ubuntu 14.04 ESM and 16.04 ESM." for free users
- got to https://ubuntu-com-10069.demos.haus/advantage?test_backend=true
- login
- see that the Free personal subscription section doesn't mention eligible ubuntu versions anymore.
Fixes #10041
=> Remove outdated copy on /advantage

static/sass/_pattern_certification-results.scss, templates/certified/search-results.html
- Add "See all vendors" and "See all versions" links
- Add functionality to expand and collapse the filter lists
- Ensure the links are hidden when accordions are closed
- Following [design](https://app.zeplin.io/project/60c1ca887b99f18a380e57e9/screen/60f169f4009bd51281d0a3ff) increase size of headings, and add `<hr>` to after tab title instead of before
- View page at: https://ubuntu-com-10071.demos.haus/certified?q=dell
- Check the links in the filter list work as expected by expanding and collapsing list of filters.
- Check the links aren't present when the accordions are closed
- This PR is addressing the show and reveal functionality - the buttons, pagination and table will be updated in future PRs. 
Fixes [#4249](https://github.com/canonical-web-and-design/web-squad/issues/4249)
=> [Certified improvements] - add functionality to toggle filter lists

HACKING.md, build.js, static/js/src/advantage/subscribe/react/app.jsx
- Update the `esbuild` config to allow the environment to set `NODE_ENV`.
- Check out this branch.
- Either add `NODE_ENV="development"` to your `.env.local` file and then run `dotrun` or run: `dotrun -e NODE_ENV="development"`.
- Visit `/advantage/subscribe`, fill out the form and then click "Buy now".
- You should see the devtools flower in the bottom left of the screen.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/124.
=> Allow NODE_ENV to be set by the environment.

package.json
- Update `check-prettier` and `format-js` to only run against source files.
- Check out this branch.
- Run `check-prettier` or `format-js`.
- It should run much faster and you shouldn't see warnings about dist or .venv files.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10087.
=> Only run prettier against source SCSS and JavaScript files.

static/js/src/advantage/subscribe/react/APICalls/registerPaymentMethod.jsx
- Check buyingFor value instead of the presence of an organisation name to decide what to pass to the backend.
- Go to https://ubuntu-com-10077.demos.haus/advantage/subscribe?test_backend=true as a guest
- select a product
- open the modal
- enter an organisation name then click Myself radio
- Check that the organisation name is ignored and the customer name is used instead as the account name
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/81
=> Fix `buyingFor` radio being ignored if an organisation name is entered

templates/shared/forms/interactive/openstack-cost-calculator.html
The lpid hidden field in this form is causing a 403 when submitting. Removing it fixes it.
- Remove lpid hidden field from
- Ensure the form at https://ubuntu.com/openstack/pricing-calculator#get-in-touch is not returning a console error when submitting
=> Remove lpid hidden field from openstack-cost-calculator form

navigation.yaml, static/js/src/advantage/subscribe/react/PurchaseModal.jsx, static/js/src/navigation.js, static/js/src/ua-payment-modal.js, templates/account/invoices/index.html, templates/account/payment-methods/index.html, templates/advantage/_table.html, templates/advantage/index-no-login.html, templates/advantage/index.html, templates/advantage/subscribe/index.html, templates/advantage/subscribe/thank-you.html, templates/templates/_navigation.html, templates/templates/base.html, webapp/advantage/views.py, webapp/app.py, webapp/decorators.py, webapp/login.py
- Make test flag consistent
- We now have `{% if get_test_backend %}` everywhere in the front-end to check the environment
1. Logout keeps does not lose the flag
- Go to https://ubuntu-com-10093.demos.haus?test_backend=true
- Login using the link in the nav bar
- Logout using the link in the nav bar
- You will still have the flag
2. Login without flag still works
- Go to https://ubuntu-com-10093.demos.haus
- Login using the link in the nav bar
- Logout using the link in the nav bar
- You not have the flag
3. Flag shows up in both nav dropdown, subnab and all links on the page
- Go to https://ubuntu-com-10093.demos.haus/advantage?test_backend=true
- Login
- Check the urls in the nav dropdown, subnab and all links on the page, you will have the flag
4. No flag for both nav dropdown, subnab …
=> Make test flag consistent

static/js/src/openstack/react/components/CostCalculatorForm.jsx, templates/openstack/pricing-calculator.html, templates/shared/forms/interactive/openstack-cost-calculator.html
- Updated default values and fixed incorrect range values
- Added another instance option to contact form to give the option of 5 instances instead of 4 as per [comment](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit?disco=AAAAMvOaL-I)
- View page at: https://ubuntu-com-10083.demos.haus/openstack/pricing-calculator
- Check max range for Ephemeral storage is 6144 and for persistent storage is 221184 on both calculator and in "Get cost estimates" form
- Check default value for RAM is 2 on calculator and form as per [comment](https://docs.google.com/document/d/1n3ExZwFVlw5LyAp7O3CgPthVgx8yRX5-Wg_gBQLf73c/edit?disco=AAAAIqPYt3U) 
- on the "Get cost estimates" form, check default value for "External network bandwidth" is 1 as per …
=> TCO calc - Fix incorrect range and default values

templates/support/index.html
- Add abbr for LMA on /support
- See that there is a abbr for the acronym LMA twice on the page
Fixes #10074
=> Add abbr for LMA on /support

static/sass/_pattern_certification-results.scss, templates/certified/search-results.html
- Add Apply filters button
- Add functionality so button is only enabled when the filters have been updated
- View page at: https://ubuntu-com-10100.demos.haus/certified?q=dell
- On page load see the "Apply filters" filters button is disabled
- Add filters and click "Apply filters"
- See when page reloads the button is disabled again until different filters are applied
Fixes [#4254](https://github.com/canonical-web-and-design/web-squad/issues/4247) and [#4252 ](https://github.com/canonical-web-and-design/web-squad/issues/4252)
=> [Certified Improvements] - Add functionality to disable/enable apply filters button

templates/legal/terms-and-policies/cube-terms.html
- Updates terms of service at /legal/terms-and-policies/cube-terms
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/terms-and-policies/cube-terms
- Compare against [copy-doc](https://docs.google.com/document/d/1vRtCO-FDMC8rqthi4sgI1Fn3ofT6zqcCpjHbOyiyhjY/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4278
=> Updates cube terms of service

templates/openstack/install.html, webapp/app.py, webapp/views.py
Get openstack install instructions from microstack.run/docs
- Check https://ubuntu-com-10061.demos.haus/openstack/install compare with current https://ubuntu.com/openstack/install
Styling is done by discourse module, so it cannot be modified. Docs content comes from https://microstack.run/docs
- [Tabs UX wireframe](https://miro.com/app/board/o9J_l5Llu-A=/)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4263
=> Microstack installation instructions on openstack page

templates/certified/index.html, templates/certified/search-results.html
- Add placeholders to search bar
- Add clear filters button which reloads page, clears all filters and fetches all results
- View page at:  https://ubuntu-com-10107.demos.haus/certified?q=
- Select some filters and click "Apply filters" 
- Select the "Clear filters button"
- See there are no filters applied and the page is displaying all results
Fixes [#4253](https://github.com/canonical-web-and-design/web-squad/issues/4253)
=> [Certified improvements] - Add clear filters button

static/sass/_pattern_accordion.scss, static/sass/_pattern_certification-results.scss, static/sass/styles.scss, templates/certified/search-results.html
Co-authored-by: Beth Collins <bethcollinsliv92@gmail.com>
- Moved `is-dense` and `is-collapsed` accordion modifiers to `p-accordion` class scope
- Drive by: added calculation for determining exact height of accordion section when collapsed, so that it shows 5 rows exactly.
- Open the mega nav, see that "Open Stack" heading is not indented (compare to live site)
- See that the accordion filters on the left side of the page still work, and look good
Fixes #10111
=> move is-dense accordion modifier to accordion

templates/kubernetes/docs/1.21/release-notes.md, templates/kubernetes/docs/charm-containerd.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/monitoring.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/supported-versions.md
- Update references for bundles
- Add release notes for 1.21ck3
- Changes to monitoring page
=> K*sDocs-1.21+ck3 updates

webapp/advantage/views.py
- Not providing VAT will correctly remove your VAT from your customer info
- Delete spaces from VAT number. It's causing problems.
1. Back-end error fixed:
- Be logged out
- Go to https://ubuntu.com/advantage/subscribe?test_backend=true
- Insert card, customer info including VAT number
- Press continue
- Hit change details
- Insert same VAT number again you will get the error:
`{"errors":"{"code":"resource_already_exists"}.....}`
- Go to: https://ubuntu-com-10124.demos.haus/advantage?test_backend=true
- Do the same steps from above
- It will not error out
2. VAT left blank gets deleted now:
- Be logged in
- Go to: https://ubuntu-com-10124.demos.haus/advantage/subscribe?test_backend=true
- Select item, reach the modal
- Select UK give a VAT number press continue
- Go a CURL request of your …
=> Fix VAT problems

static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx, static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx, static/js/src/advantage/react/components/Subscriptions/Notifications/index.ts, static/js/src/advantage/react/components/Subscriptions/Subscriptions.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/useURLs.test.tsx, static/js/src/advantage/react/hooks/useURLs.ts
- Add notifications component to the subscriptions page.
- Add hook for appending the test backend flag to urls.
- Visit /advantage?test_backend=true
- You should see a couple of dummy notifications.
Fixes: canonical-web-and-design/commercial-squad#135.
=> Add subscription notifications component

templates/certified/model-details.html
Fix components table releases
- Check https://ubuntu-com-10133.demos.haus/certified/202102-28728 components table contains 20.04 checkmark for nVidia Quadro P400
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9923
=> Fix components table releases

templates/ceph/index.html
- Created a new ceph copy doc
- Update ceph copy doc meta data
- Add the an 'a' to the opening h4
- See that the new [copy doc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit#heading=h.vnx6txk2yt47) is linked
=> Update ceph copy doc

templates/observability/index.html
- Add link to /managed that was super obvious but I did not realized it was needed until after page went live :-)
Fixes #
=> Add link to /managed from /observability

static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/index.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/index.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/sass/_pattern_subscriptions.scss, static/sass/_pattern_tabs.scss
- Add subscription details components.
- Add subscription tabs component.
- You should see the layout of the subscription content (all dummy content at this point).
- You should be able to switch Features and Documentation tabs.
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/108.
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/110.
=> Add components for the subscription details content

build.js, static/js/src/certification-results.js, static/js/src/certified-search-results.js, static/sass/_pattern_accordion.scss, static/sass/_pattern_certification-results.scss, templates/certified/search-results.html
- Add counter to accordion tab when the accordion is closed
- Move javascript functionality into it's own file
- View page at: https://ubuntu-com-10125.demos.haus/certified?q=
- Select filters on the LHS and close the accordion - check the chip is visible on each section with the correct number of filters applied. 
- Check when there are no filters applied the chip isn't visible. 
Fixes [#4250](https://github.com/canonical-web-and-design/web-squad/issues/4250)
=> Add count to closed accordion

webapp/marketo.py
We were not swaping the token after authentication when retrying a request
and that would result in another failed request.
=> Marketo API token refresh

webapp/cube/api.py
- Call [`urllib.parse.quote()`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) on an email address before using it to look up the associated account
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10131
=> Encode email address when calling Open edX API

static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx, static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/usePendingPurchaseId.test.tsx, static/js/src/advantage/react/hooks/usePendingPurchaseId.ts, templates/advantage/index.html
- Update the pending purchase notification to only appear when the id is set.
- Visit https://ubuntu.com/account/payment-methods?test_backend=true
- Change your card number to `4000000000000341`.
- Visit https://ubuntu.com/advantage?test_backend=true
- Open the edit form for a subscription and change the number of machines and click save.
- Run this branch and visit /advantage?test_backend=true
- You should see a payment method notification.
- Visit https://ubuntu.com/account/payment-methods?test_backend=true
- Change your card number to `4242424242424242`.
- The page will reload and a notification will appear. Click "Retry payment".
- In this branch go to /advantage?test_backend=true
- You should not see a payment method notification.
Fixes …
=> Display a pending purchase notification

package.json
- Update javascript test runner so that the timezone is fixed to prevent failures when running from different timezones.
- This was the failing test: https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/advantage/subscribe/react/components/Summary/Summary.test.jsx#L84.
- Fly to Australia.
- Wait until the afternoon.
- Run `dotrun test-js`.
- The tests should all pass.
=> Fix timezones in js tests

templates/security/index.html, templates/shared/contextual_footers/_security_esm.html
- Copy updates on /security
- Note: *there is an outstanding question about a link to the wiki*
- Compare to the [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#)
Fixes [#4279](https://github.com/canonical-web-and-design/web-squad/issues/4279)
=> Copy updates on /security

package.json
- Use concurrently to properly run watch for both CSS and JS
- Run the watch command `./run watch`, make sure both CSS and JS changes trigger build
- Run just watch for JS files `./run exec yarn run watch-js` - make sure that JS files changes trigger build
Fixes canonical-web-and-design/web-squad#4314
=> Fix watch script

static/js/src/advantage/react/components/FormikField/FormikField.test.tsx, static/js/src/advantage/react/components/FormikField/FormikField.tsx, static/js/src/advantage/react/components/FormikField/index.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/sass/_pattern_subscriptions.scss
- Add a subscription edit form.
- Copy over the FormikField component from maas-ui.
- Click "Edit subscription..."
- You should see a form to resize the subscription.
Fixes canonical-web-and-design/commercial-squad#112.
=> Add a subscription edit form

navigation.yaml, templates/templates/footer.html, templates/templates/navigation-enterprise-h.html
- Adding `/observability` to the enterprise navigation
- View the site locally in your web browser at: http://0.0.0.0:8001/ and https://ubuntu-com-10162.demos.haus/observability
=> Add observability to navigation

static/js/src/advantage/contracts-api.js, static/sass/styles.scss, templates/account/index.html, templates/account/invoices/index.html, templates/account/payment-methods/index.html, webapp/advantage/api.py, webapp/advantage/schemas.py, webapp/advantage/views.py, webapp/app.py
With the release of `/account/invoices`, I took the time to look at `/account/payment-methods` and bring them in line with each other. `/payment-methods` was originally intended to be part of the `/advantage` domain. Now it's part of the `/account` pages, making it a higher level page, independent of product names.
**At the moment this page allows only editing existing card information. It does not allow for adding a card, if you do not already have one set.**
1) Updating the meta title and description.
2) Removing the Ubuntu Advantage title
3) Removing the "You are signed in as". That was forgotten there. It's been remove already from all other pages.
4) Making the Payment methods title an h1. Similar to the title on /invoices.
5) Mini fix CSS to bring the Update button in line with the …
=> Update payment methods page

static/sass/_pattern_footer.scss, templates/templates/_footer_item.html, templates/templates/_footer_item_small.html, templates/templates/footer.html
- Broke the old `_footer_item.html` into two partials, one for navigation sections with sub-pages and one with no sub-pages.  It used to be based on the number of subpages; however, that doesn't work in cases where there are hidden pages like contact-us and thank-you perfectly.
- Look at the footer and see that all the sections that should be expanded are and those that are not are not
https://ubuntu-com-10167.demos.haus/
FYI @mmanciop
=> Add footer_item_small to make adding footer lists more explicit

templates/engage/index.html, webapp/views.py
Add language filter
Note: preferably test this on local to use a different [discourse API key](https://pastebin.canonical.com/p/wNW3cF6YPs/) to avoid getting the Connection error (I believe this is due to rate limits per minute).
- Filter by each of the languages given, and check that only engage pages in the chosen language appear.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3682
=> Engage language filter

static/sass/_pattern_tco-calculator.scss, static/sass/styles.scss, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html, templates/certified/component-details.html, templates/certified/hardware-details.html, templates/certified/index.html, templates/certified/model-details.html
- Extract tco calculator styles into their own file
- Remove `p-text-muted` class as this is now in vanilla as `u-text--muted` - and replace all uses of `p-text--muted`
Remove custom styles for: 
- `abbr[title]` as fixed [here](https://github.com/vanilla-framework/vanilla-framework/issues/1962)
- `[class^="p-strip"].is-bordered` as fixed [here](https://github.com/vanilla-framework/vanilla-framework/issues/2045)
- `p-code-copyable__input` as fixed [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/3564)
- `p-accordion__tab` as fixed [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/2926)
- `h4.p-stepped-list__title + .p-stepped-list__content` as fixed [here](https://github.com/canonical-web-and-design/vanilla-framework/issues/3066)
- …
=> Tidy up redundant css

templates/telco/osm/onboarding-network-functions.html
- Added `,` after `day 1`
- Updated `which` to `that` Explorer to Training & onboarding package
- Updated `fulfi` to `fulfill`
- Deleted one space after `should`
- Updated `VNF onboarding in OSM Hackfests` to  `Network function VNF onboarding in OSM Hackfests`
- Added `Hackfest MR-10`, `Hackfest11` and `Hackfest MR 11`
- Updated `in` to `with`
- Please check page against [copy doc](https://docs.google.com/document/d/1_35nO3riTFlSFSp2B7FFdl60cjZe7Owwv0bcjY1s8Kg/edit#) and resolve comments
Fixes [#4327](https://github.com/canonical-web-and-design/web-squad/issues/4327)
=> Copy update on /telco/osm/onboarding-network-functions

templates/certified/desktops.html, templates/certified/devices.html, templates/certified/laptops.html, templates/certified/servers.html, templates/certified/socs.html, webapp/certified/api.py, webapp/certified/views.py
Show vendors and filters only for that specific category #4317
- Check https://ubuntu-com-10171.demos.haus/certified/desktops and check only shows filters that apply to that category (that have results)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4317
=> Limit number of filters by category

package.json, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/RenewalSettingsFields.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/RenewalSettingsFields.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/index.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/index.ts, static/sass/_pattern_subscriptions.scss
- Add renewal settings component.
- Click one of the 'Renewal settings' contextual menus.
- You should see the form.
- Clicking cancel should close the form.
Fixes: canonical-web-and-design/commercial-squad#97.
=> Add renewal settings component.

webapp/advantage/views.py
- Add tax ID condition. When implementing the recent `tax_id` validation, it was not taken into account that sometimes the `tax_id` parameter can be `null`. 
- The wizard always provides `tax_id` even if the value is `""`
- However the renewal modal, does not. Which makes it fail at the moment.
- have a renewable renewal (ask Albert for help if needed)
- go to on https://ubuntu.com/advantage?test_backend=true
- press the renewal button
- insert your customer details in the modal
- press continue
- you will get a 500 in the console from `POST get-costomer-info`
- try on http://ubuntu-com-10155.demos.haus/advantage?test_backend=true
- you will get a 200 in the console `POST get-costomer-info`
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/137
=> Add tax id condition

static/js/src/ua-payment-modal.js
Fix renewal modal:
- Address info would never be pre-filled due errors
- Address would not be sent to the back-end due to capitalised "Country" field name 
- have a renewable renewal (ask Albert for help if needed)
- go to on https://ubuntu.com/advantage?test_backend=true
- press the renewal button
- you will notice address does not get pre-filled
- insert customer info
- press continue
- you will notice that POST get-costomer-info does not send the country to the back-end
- try on http://ubuntu-com-10157.demos.haus/advantage?test_backend=true
- everything will be pre-filled
- pressing continue will take you to step 2
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/154
=> Fix renewal modal problems

templates/base_index.html, templates/observability/index.html
- Update MAAS contact-us link on the homepage
- Update the observability contact us link
- _Drive by:_ removed the chevron from the external link on the homepage
- You could just check the code to be honest. 
- Check it fixes the issues reported: https://github.com/canonical-web-and-design/ubuntu.com/runs/3298132611?check_suite_focus=true
=> Fix linkchecker issues

templates/security/livepatch.html
- Use new logo pattern on /security/livepatch to improve logo spacing
- View the site locally in your web browser at: http://0.0.0.0:8001/security/livepatch
- See that the logo cloud looks better
Fixes #10174
[orig]
[new]
=> Use new logo pattern on /security/livepatch

templates/legal/data-privacy/index.html
- Added facebook's data conversion cookies ot the data-privacy page.
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/data-privacy
- Compare to the [copy doc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit#) and resolve comments
=> Add conversion api cookies to facebook on /legal/data-privacy

package.json, static/js/src/advantage/api/enum.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/usePersonalAccount.test.tsx, static/js/src/advantage/react/hooks/usePersonalAccount.ts, static/js/src/advantage/react/utils/dedupeArray.test.ts, static/js/src/advantage/react/utils/dedupeArray.ts, static/js/src/advantage/react/utils/getFeaturesDisplay.test.ts, static/js/src/advantage/react/utils/getFeaturesDisplay.ts, static/js/src/advantage/react/utils/index.ts, static/js/src/advantage/react/utils/removeFalsy.test.ts, static/js/src/advantage/react/utils/removeFalsy.ts, static/js/src/advantage/tests/factories/contracts.ts
- Display free token details from the API.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10172.demos.haus/advantage?test_backend=true).
- You should see a free personal token card and it should show the correct data from the API ([design here](https://app.zeplin.io/project/60ec5fb4e07cc90fbbf2b318/screen/60eeee7dbe6908aeed7151c8)).
Fixes: canonical-web-and-design/commercial-squad#103.
=> Display free token details from the API

templates/kubernetes/index.html
- Updated image and text in the `Kubernetes resources` section
- Updated `WEBINAR` to `CASE STUDY`
- Please check page against [copy doc](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit) and resolve comments
Fixes [#4346](https://github.com/canonical-web-and-design/web-squad/issues/4346)
=> Copy update on /kubernetes

build.js
- Fail the build when esbuild has an error.
- Check that the demo service has successfully built the branch.
- If you wish you could also test that this fails locally by adding `import nothing from "nothing";` to a js file and running `dotrun build-js` and you should see a failure.
=> Fail the build when esbuild has an error

navigation.yaml, templates/cube/faq.html
- Create /cube/faq page
- Add `FAQ` in the navigation menu
- View the site locally in your web browser at: http://0.0.0.0:8001/cube/faq
- Please check page against [copy doc](https://docs.google.com/document/d/1tDByDnXmf6QnpvtzxrX3JsgNYuBZbv1Bx7o6mGnbzSg/edit#heading=h.g1eby6bz6419)
Fixes [4354](https://github.com/canonical-web-and-design/web-squad/issues/4354)
=> Create /cube/faq page

static/sass/styles.scss, templates/account/invoices/index.html, webapp/advantage/views.py
- Change 1:
Some invoices do not come with a total cost field. This change makes it so that we handle those situations more graceful. If total is missing we just display `-`.
- Change 2:
The table is overriding the footer. Replacing `height` with `min-height`.
- Change 3:
Canonical CUBE invoices should not show show `(annual)` in the service column.
- Be someone with access to the Canonical Staff account
- Go to https://ubuntu-com-10206.demos.haus
- Login
- Go to https://ubuntu-com-10206.demos.haus/account/invoices
- Change 1: The page should work
- Change 2: The table should not overlap the footer
- Change 3: Canonical CUBE should not show `(Annual)`
=> Fix invoices page

static/js/src/certified-search-results.js, templates/certified/desktops.html, templates/certified/devices.html, templates/certified/laptops.html, templates/certified/search-results.html, templates/certified/servers.html, templates/certified/socs.html
Fix limit appending twice.
Refactored loops and unnecessary conditions.
- Check /certified/desktops or any search results page, and try the different page sizes (20, 40, all...) and make sure the URL does not append the `limit` query twice.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4316
=> Fix results per page

.github/workflows/mirrors.yaml
- Added the cron job to check in `/mirrors.json` returns a list of links
This is a cron job in GH action, so not sure how to QA it.
The job was tested running on staging here:
https://github.com/canonical-web-and-design/ubuntu.com/runs/3321716261?check_suite_focus=true
Part of #8583
=> Add cron job to check Ubuntu download mirrors

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/sass/_pattern_subscriptions.scss
- Update the subscription list column sizes for small screens.
- Remove the highlight from the card on small screens.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10211.demos.haus/advantage?test_backend=true)
- Resize your window down to mobile size.
- Check that the cards appear like the [design](https://app.zeplin.io/project/60ec5fb4e07cc90fbbf2b318/screen/60f6fa108d36bb10a7f201a0)
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/105.
=> Update the subscription list for small screens

webapp/advantage/api.py
- Filter out CUBE contracts form /advantage
- Login to https://ubuntu.com production
- Go to /advantage you will see the Canonical Staff account with lots of CUBE contracts
- Switch to the demo site: https://ubuntu-com-10214.demos.haus
- Go to /advantage you will not see the Canonical Staff account with any CUBE contracts
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/182
=> Filter out CUBE contracts

static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.jsx, static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx
- the VAT error occurs because the [checkVAT function](https://github.com/canonical-web-and-design/ubuntu.com/blob/master/static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx#L93-L119) that's calling the API is being called even when VAT is undefined (e.g. hasn't been entered by the user yet). 
- invoke the checkVAT function only if a VAT country is selected and VAT is defined
- go to https://ubuntu-com-10215.demos.haus/advantage/subscribe?test_backend=true
- make sure you're logged in
- select "buy" and fill out the form
- select United Kingdom as a country
- enter incorrect VAT (any random string will do)
- you should see an error `Error: That VAT number is invalid. Check the number and try again.`
- enter a valid VAT (e.g. GB 123 1234 12 123)
- error should …
=> Fix price preview recalculation 

static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.jsx, static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx
- ensure user has an account before updating the account
- currently the app is making a request to update the account for guest users (when `accountId` is undefined)
- this causes `customer-info-anon`endpoint to throw an `unauthorised` error
- log out
- Go to https://ubuntu-com-10220.demos.haus/advantage/subscribe?test_backend=true
- make a selection and press "Buy now"
- verify `customer-info-anon` isn't being called before you press "Continue"
- Verify `customer-info` and `preview` are called after you press "Continue" and correct price is displayed
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/172
=> Fix guest user vat calculation

tests/advantage/fixtures/account.json, tests/advantage/fixtures/accounts.json, tests/advantage/fixtures/contract-items.json, tests/advantage/fixtures/contract.json, tests/advantage/fixtures/contracts.json, tests/advantage/fixtures/entitlements.json, tests/advantage/fixtures/product-listing.json, tests/advantage/fixtures/product-listings.json, tests/advantage/fixtures/product.json, tests/advantage/fixtures/products.json, tests/advantage/fixtures/subscription-items.json, tests/advantage/fixtures/subscription.json, tests/advantage/fixtures/subscriptions.json, tests/advantage/helpers.py, tests/advantage/test_api.py, tests/advantage/test_parsers.py, webapp/advantage/models.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/ua_contracts/primitives.py
Adding the parser functions to convert the API json responses to Objects and List of Objects. This conversion will happen only if the flag `convert_responses` is set to `true` when instantiating the `UAContractAPI` class.
Adding tests for each parser as well as adding tests for the changed api functions whose responses get parsed. Creating fixture files as a mock for each json response.
We have the following parsers:
- **parse_account**: Parses a single account json and converts it to an `Account` instance 
- **parse_accounts**: Parses an array of accounts json and converts it to a `List` of `Account` instances
- **parse_subscription_items** - Parses an array of purchased product listings of a subscription and returns a `List` of `SubscriptionItem` instances
- **parse_subscription** - …
=> Backend new advantage add parsers

webapp/views.py
- Pass IP and user agent to the Marketo API during form submission
- This fixes the lack of country/OS lead data we experienced since the move to the Marketo API
- Ensure forms (eg. blog subscription) submit successfully and that the generated lead has country data
=> Pass IP and user agent to the Marketo API during form submission

static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/Content/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/sass/_pattern_subscriptions.scss
- Display the subscription details in a modal on small screens.
- Make it possible to open and close the modal.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10212.demos.haus/advantage?test_backend=true).
- On a large screen the list of subscriptions and the subscription details should appear side by side.
- Resize your screen down to mobile size.
- The subscription details should now appear in a modal.
- Close the modal and you should be able to see the list of subscriptions.
- You should now be able to open and close subscriptions.
- With the modal close resize your window to the large size.
- You should see both the list and details again.
Fixes: canonical-web-and-design/commercial-squad#111.
=> Display the subscription details in a modal on small screens.

static/js/src/certified-search-results.js, templates/certified/base_certification.html, templates/certified/component-details.html, templates/certified/desktops.html, templates/certified/devices.html, templates/certified/hardware-details.html, templates/certified/index.html, templates/certified/laptops.html, templates/certified/model-details.html, templates/certified/servers.html, templates/certified/shared/category-search-results.html, templates/certified/socs.html
- Copy updates and setup for certified/<category> views
- Refactor category view templates into one single template
- Removed `base_certification` include template, as this doesn't provide any value (only a few linesand we need also direct access to `meta_copydoc` in `base.html`)
- Navigate to https://ubuntu-com-10207.demos.haus
- In the top navigation try each link (Desktops, Laptops, Devices etc...)
- Make sure the following work as on https://ubuntu.com/certified:
- Filters, select multiple filters and apply them
- Clear filters
- Click to show or hide filters when applicable
- Results per page work as expected and they do not duplicate the `limit` query
- Pagination works as expected
- Check copy docs are correctly linked and the content matches. To see this, inspect in developer …
=> Certified category copy

templates/cpu-compatibility/base_cpu-compatibility.html, templates/cpu-compatibility/index.html
- Created `/cpu-compatibility` page
- View the site locally in your web browser at: http://0.0.0.0:8001/cpu-compatibility
- Please check page against [copy doc](https://docs.google.com/document/d/16E0xMuCIrGRwGa1G0poDEil9zd_5UAWTpxFRiA8j-KU/edit).
- Check against [design](https://app.zeplin.io/project/611fb1a83c7c1d56eaae1239)
Fixes [#4368](https://github.com/canonical-web-and-design/web-squad/issues/4368)
=> build /cpu-compatibility page

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
- Don't display the cancel and edit modals on top of each other.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10247.demos.haus/advantage?test_backend=true).
- Resize down to mobile.
- Click on a subscription.
- Click the 'Edit subscription...' button.
- Click the 'You can cancel this subscription online or contact us.' link.
- There shouldn't be stacked portals (you can kind of see this by the transparency of the page overlay not getting darker).
Fixes #207.
=> Only display the edit or cancel modal.

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/sass/_pattern_subscriptions.scss
- Adapt the resize form for the mobile view.
- Update the details HTML structure to support the mobile resize form.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10248.demos.haus/advantage?test_backend=true)
- Resize your browser down to mobile size.
- Click on a subscription.
- Click on the 'Edit subscription...' button.
- Check that the modal appears like [the design](https://app.zeplin.io/project/60ec5fb4e07cc90fbbf2b318/screen/60f82e36b24ad91391e16c44).
Fixes canonical-web-and-design/commercial-squad#147.
=> Adapt the resize form for the mobile view.

templates/embedded/index.html
- Added "Xilinx Evaluation Kits and SOMs" to reference platforms at `/embedded#hardware`
- View page at: https://ubuntu-com-10259.demos.haus/embedded#hardware
- Check against [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit#heading=h.ybs0qqava5l5) and resolve Thibaut's comment
Fixes [#4146](https://github.com/canonical-web-and-design/web-squad/issues/4146)
=> Add Xilinx to /embedded

templates/robotics/index.html
- Add Xilinx board to "Broad compatibility with development boards" section
- Add links to images
- View page at: https://ubuntu-com-10261.demos.haus/robotics
- Check design - I'm not sure what looks best with the arrangement of the 4 cards. I felt like they looked too wide with 6 cols but happy to change. 
- Check against [copy doc](https://docs.google.com/document/d/1JNFk2C0shH3DapKuJM8X0QfAiD1RzHvXoydn8P9mEMg/edit#heading=h.a27qa2blaakw) - The copy doc is really confusing and very different to the live page. I've spoken to @SirSamTumless and we are just adding the new board for now so ignore the rest of the page for now. 
Fixes [#4145](https://github.com/canonical-web-and-design/web-squad/issues/4145)
=> Add Xilinx board to /robotics

templates/openstack/compare.html
- Added a space between "our" and "datasheet"
- Please check this [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/10254#event-5231050605) as there was no copy doc
Fixes #10254
=> Add a space

templates/shared/pricing/_kubernetes-consulting.html
- Updated Kubernetes cards and list items
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/consulting
- Please check page against [copy doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit#heading=h.z516x9uv6lts).
Fixes [#4391](https://github.com/canonical-web-and-design/web-squad/issues/4391l)
=> Copy update on /pricing/consulting

templates/cube/faq.html
- Updated copy title and contact link for CUBE /faq per:
https://docs.google.com/document/d/1tDByDnXmf6QnpvtzxrX3JsgNYuBZbv1Bx7o6mGnbzSg/edit#heading=h.g1eby6bz6419
- View the site locally in your web browser at: http://0.0.0.0:8001/cube/faq
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4388
=> Updated copy title and contact link for CUBE /faq

templates/kubernetes/docs/1.21/components.md
- Updated component page for new charm refs
=> K8sDocs component updates 1.21+ck3

tests/advantage/test_helpers.py, webapp/advantage/ua_contracts/helpers.py, webapp/advantage/views.py, webapp/app.py
- Add /advantage/last-purchase-ids endpoint
- Be logged in
- Go to: https://ubuntu-com-10257.demos.haus/advantage/last-purchase-ids/<account_id>?test_backend=true
- You will see your last purchases ids
1) Find your token:
Go to:  https://ubuntu-com-10257.demos.haus/account.json
2) Make CURL request:
`curl -H "Authorization: Macaroon <token>" https://contracts.staging.canonical.com/v1/accounts`
Make sure you do not choose your free token account_id (it's usually the first one)
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/185
=> Add last-payment-ids endpoint

templates/core/index.html
- Added ARM, NXP, Xilinx, and Mediatek logos to /core page
- Updated Yocto image 
Copydoc: 
https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4390
=> Update logos on /core page

templates/public-cloud/index.html
Updated copy and replaced needed images on /public-cloud-page per : 
https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4389
=> updated copy and images on /public-cloud page

templates/automotive/index.html
- Add Xilinx to automotive page. I tried to use the logo section vanilla pattern but it was pushing the xilinx logo to a new line. Happy to update if there are any design suggestions/. 
- View page at: 
- Check Xilinx is added to logo strip as requested in [copy doc](https://docs.google.com/document/d/1PVliB92h4ZqexaZV9F5MIcX7aRG6yBAGH1hG7x8UZTw/edit#) - please resolve comment
Fixes [#4147](https://github.com/canonical-web-and-design/web-squad/issues/4147)
=> Add Xilinx to automotive

static/js/src/advantage/api/enum.ts, static/js/src/advantage/api/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/react/utils/formatDate.ts, static/js/src/advantage/react/utils/getFeaturesDisplay.test.ts, static/js/src/advantage/react/utils/getFeaturesDisplay.ts, static/js/src/advantage/react/utils/index.ts, static/js/src/advantage/react/utils/isFreeSubscription.test.ts, static/js/src/advantage/react/utils/isFreeSubscription.ts, static/js/src/advantage/tests/factories/api.ts
- Update the free token card to display data from the new user subscriptions API.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10255.demos.haus/advantage?test_backend=true).
- Check that the 'Free Personal Token' card is displayed in the list (both cards will show the free data for now). The data shown in the card should be exactly the same, but it is coming from the new API.
Fixes canonical-web-and-design/commercial-squad#209
=> Display free token data from the new API

tests/advantage/test_api.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/views.py, webapp/app.py
- Create endpoint /advantage/contracts/`contract-id`/token
- Returns `{"contract_token":  <token>}`
- Refactor `ua_contracts/api.py > get_contract_token` function:
-  It uses now `error_rules` property to catch exceptions allowing us to delete a lot of bespoke exception catching
- Add tests to cover the funciton
- Be logged in
- Go to: https://ubuntu-com-10267.demos.haus/advantage/contracts/<contract_id>/token?test_backend=true
- You will see your contract token
1) Find your token:
Go to:  https://ubuntu-com-10267.demos.haus/account.json
2) Make CURL request to find your `account_id`:
`curl -H "Authorization: Macaroon <token>" https://contracts.staging.canonical.com/v1/accounts`
Make sure you do not choose your free token account_id (it's usually the first one)
3) Make a CURL request to …
=> New advantage contract token endpoint

templates/download/contact-us.html, templates/download/iot/index.html, templates/download/thank-you.html
- Included Xilinx in two places on `/download/iot`
- The page isn't live yet so the PR is blocked until it's built
- View page at: https://ubuntu-com-10262.demos.haus/download/iot
- Check page against [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#heading=h.v1842hnm1pef) and resolve comments
- The Xilinx image needs to be 45px high to keep inline with other logos - but this makes it too wide. Could a design suggestion be given please.
- Also - not sure of the best position for the "Can't find your board of choice?" text
Fixes [#4149](https://github.com/canonical-web-and-design/web-squad/issues/4149)
=> Include Xilinx on /download/iot

build.js, navigation.yaml, static/js/src/advantage/users/app.jsx, templates/advantage/users/index.html, webapp/advantage/views.py, webapp/app.py
- add advantage/users route
- create a dummy advantage_account_users_view
- create empty React app mounted at #advantage-account-users-app
- add "Account users" child item to navigation
- When logged out, go to `https://ubuntu-com-10271.demos.haus/advantage/users`
- Confirm you were redirected to `/advantage`
- Log in
- go to `https://ubuntu-com-10271.demos.haus/advantage/users`
- Confirm a page with content "Account users" has been displayed
- [Account management architecture - Proposed URL structure](https://docs.google.com/document/d/1BwKC43kx-keG3vS5YDYHBRgCN_T0cSfCtsSxeavnhHc/edit#heading=h.ywle6en6olpl)
- https://app.zeplin.io/project/610280dbf760649f5868dfc7/screen/6102811bc3850a9b98915c0c
=> Add advantage/users route

templates/templates/navigation-download-h.html
- Add "Xilinx Evaluation kits & SOMs" under "Ubuntu IoT" section of download meganav 
- View demo at: https://ubuntu-com-10284.demos.haus
- Select download section of mega nav and check the new Xilinx link is there as referenced in the[ copy doc](https://docs.google.com/document/d/11pX5gxOE6UWljIGRBZdwuCL1MHzs4pNgxJpK0mcIqdQ/edit)
Fixes [#4395](https://github.com/canonical-web-and-design/web-squad/issues/4395)
=> Add Xilinx to mega nav

templates/download/xilinx/index.html
-Remove release notes on Xilinx page 
-  Accepts chagnes against copy doc: https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit#
Fixes #
=> Remove release notes on Xilnix page

tests/advantage/fixtures/subscriptions.json, tests/advantage/test_helpers.py, tests/advantage/test_parsers.py, webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/ua_contracts/primitives.py, webapp/advantage/views.py, webapp/app.py
- Add `/advantage/user-info` endpoint: Endpoint that returns overall user information like auto renewal status ~~and other global warnings (i.e. pending purchases)~~. 
- Global warnings will have to be deduced from looking at all user subscriptions: `/advanage/user-subscriptions`. 
- Added `statuses.has_pending_purchase` to `UserSubscription` to determine if there are pending purchases for the user
Schema if user has monthly subscriptions:
```
{
has_monthly_subscription: Boolean(),
is_auto_renewing: Boolean(),
last_payment_date: Date(),
next_payment_date: Date(),
total: Int(),
currency:["usd"],
}
``` 
Schema if user has no monthly subscriptions:
```
{
has_monthly_subscription: Boolean(),
}
``` 
It can return 404 if user has no purchase account. Meaning they have never made a purchase with …
=> New advantage user info endpoint

templates/download/xilinx/index.html
- Updates requested by xilinx
- Pointed to the correct download image
- Condensed Kira board options from 3 list items to 1
- Removed code name from download text (not the actual link yet)
- Updated image of the board
- View the site locally in your web browser at: http://0.0.0.0:8001/download/xilinx
- See that the above items have been updates
=> Updates to /download/xilinx

static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useScrollIntoView.test.tsx, static/js/src/advantage/react/hooks/useScrollIntoView.ts, static/sass/_pattern_subscriptions.scss
- Scroll to the subscription content if it is off the screen.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10256.demos.haus/advantage?test_backend=true).
- Scroll down until all the subscription details is visible on the screen.
- Click on a subscription and the window shouldn't scroll.
- Click on the top subscription.
- Scroll down until just the free personal token card on the left is visible.
- Click on the free personal token card.
- You should get scrolled up until the top of the details is visible.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/93.
=> Scroll to the subscription content if it is off the screen

templates/core/smartstart/guide/certification-and-validation.md, templates/desktop/partners.html, templates/legal/ubuntu-advantage-service-description/index.md, templates/pricing/shared/_enablement-strip.html
- Replace uppercase C with lower case C in all instances of "Ubuntu certified..." for consistency 
- Checkout this branch
- Search codebase for "Ubuntu certified" and check all instances of capital C have been changed to lower case c
Fixes #10230
=> Lower case c in all instances of "Ubuntu certified..."

templates/0_docs/content_strips.html, templates/containers/shared/_whitepaper.html, templates/core/index.html, templates/kubernetes/index.html, templates/managed/apps/cassandra.html, templates/managed/apps/kafka.html, templates/openstack/index.html, templates/security/esm.html, templates/security/livepatch.html
- This was something we were going to add to Vanilla - but it was [decided](https://github.com/canonical-web-and-design/vanilla-framework/pull/3935#issuecomment-905288532) that the muted heading doesn't work with this size of icon. Therefore it needs to be replaced with a `<h4>`.
- View demo at: 
- /0_docs/content-strips
- /core
- /managed/cassandra
- /managed/kafka
- /openstack
- /security/esm
- /kubernetes
- /security/livepatch
- Check it replicates this [suggestion](https://github.com/canonical-web-and-design/vanilla-framework/pull/3935#issuecomment-903651888)
Fixes #10237 
Example on /security/esm
=> Remove inline muted heading content strip styles

templates/download/xilinx/index.html
- Updated the /download/xilinx page with new link and file locations
- Updated the [copy doc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/download/xilin
- See that it points to https://people.canonical.com/~platform/images/xilinx and the renamed images
=> Update xilinx links on people.c.c

templates/managed/apps/cassandra.html, templates/managed/apps/index.html, templates/managed/apps/kafka.html, templates/managed/index.html
- Removed `js-invoke-modal` so cta's go to /managed/contact-us instead of modal per PdM request
- See the contact us cta's open http://0.0.0.0:8001/managed/contact-us
Fixes [#4396](https://github.com/canonical-web-and-design/web-squad/issues/4396)
=> Remove modal class to contact us CTA under /managed

templates/download/raspberry-pi/index.html
- Add pi4 to /download/raspberry-pi desktop 
- See that the pi 4 is added
Fixes #9796
=> Add pi4 to /download/raspberry-pi desktop 21.04

templates/advantage/subscribe/index.html
- Added a subtitle to let users know about free trials
- Copy coming from this doc https://miro.com/app/board/o9J_lSky0cQ=/
- go to https://ubuntu-com-10249.demos.haus/advantage/subscribe
- check that there is a subtitle letting you know about a first month free
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/165
Logged in
logged out
=> Add trial information to header of product selecto

static/js/src/advantage/subscribe/renderers/form-renderer.js, static/sass/_pattern_shop-cart.scss, templates/advantage/subscribe/index.html
- added free trial label for eligible products
:warning: *The free trial backend is not yet implemented in the target branch so, it will never show* :warning: 
- Go on https://ubuntu-com-10250.demos.haus/advantage/subscribe?test_backend=true logged out
- Select any annual product
- you should see a grey tag on the bottom summary telling you you're eligible for 1month free trial
Fixes #canonical-web-and-design/commercial-squad/issues/166
=> Add trial label to sticky footer on the product selector

static/js/src/certified-search-results.js
- Fix the count so it includes already applied filters and newly selected filters. 
- View page at: https://ubuntu-com-10278.demos.haus/certified?q=
- Select any filters and check when the accordion closes the filter count is correct. 
- Now click apply filters
- After the page reloads close the accordion again and check the count is correct
- Select some more filters and check these are added to the count as expected
Fixes [#4373](https://github.com/canonical-web-and-design/web-squad/issues/4373)
=> Fix filter count on /certified search results

navigation.yaml, templates/security/livepatch/docs/document.html, templates/security/livepatch/docs/search-results.html, templates/sitemap_index.xml, webapp/app.py
- Adds security/livepatch/docs to ubuntu with search feature.
- View the site locally in your web browser at: http://0.0.0.0:8001/security/livepatch/docs/
- Check all the different pages load.
- Test the search feature is working.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4393
=> Adds security-livepatch docs

navigation.yaml, templates/security/livepatch.html
This is an update related to the launch the next few days.
- Link to new documentation of livepatch
- Reduce the name of the docs sub-menu, it was too big and didn't reflect the actual name of the product (from "Security Livepatch Docs" -> "Docs"
Follows the [copydoc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#)
=> Fix presentation issues on livepatch pages

.eslintrc.js, static/js/src/advantage/users/AccountUsers.test.tsx, static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/app.tsx, static/js/src/advantage/users/components/TableView.tsx, static/js/src/advantage/users/mockData.ts, static/js/src/advantage/users/types.ts
- Add TableView to Account Users
- Log in
- Go to https://ubuntu-com-10309.demos.haus/advantage/users
- make sure philip.p@ecorp.com user is displayed
=> Account Users/Add TableView

static/js/third-party/typer.js, templates/security/docker-images.html
- Updated the page title 
- Updated `LTS Docker Images` to `Long Term Supported OCI Images`
- Added a code snippet and created the `typer.js`file  in the`js/dist` to make the code snippet animated.
- Set `$ docker pull ubuntu/nginx` as a default placeholder just in case js not working.
- Added a link with "Explore our CVE-fixing track record >" 
- Added `Contact` and `Get in touch` and linked them to the contact form.
- View the site locally in your web browser at: http://0.0.0.0:8001/security/docker-images
- Please check page against [copy …
=> Copy update on /security/docker-images

static/sass/_pattern_certification-results.scss, templates/certified/search-results.html, templates/certified/shared/category-search-results.html
Search results and category search results filters have applied the following changes:
- Adapted filter titles to what is in the Accordion pattern originally (or Navigation).
- "Apply" and "Clear" filter buttons positioning
Not done:
- The section titles have a hover state when closed but not when open - this is a Vanilla discussion as there is discrepancy among designers, so [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/3950) was created.
- Remove left padding from filter buttons - I believe there is a `u-no-padding-right` already.
- check https://ubuntu-com-10224.demos.haus/certified/desktops (or any other item on the top navigation, the code comes from the same file)
- See that the accordion titles fit the [Vanilla accordion …
=> Certified design fixes

tests/advantage/test_helpers.py, webapp/advantage/ua_contracts/helpers.py, webapp/advantage/views.py
- Fix `get_subscription_by_period` in case listing is None, it should return None instead of 500
- Make make `g.api.convert_reponse(True)`. This converts the API responses from json to List of Objects. `/advatnage/user-subscription` expects the responses to be converted, not having it set to `True` breaks the endpoint.
- Login on https://ubuntu-com-10318.demos.haus
- Go to https://ubuntu-com-10318.demos.haus/advantage/user-subscriptions
- You should get a 200
=> Fix user subscriptions endpoint

static/js/src/advantage/react/components/Subscriptions/Content/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
- Close the edit form when switching subscriptions or closing the modal.
- Enable tests for showing the cancel form.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10313.demos.haus/advantage?test_backend=true).
- Click on a non-free subscription.
- Click the edit button. You should see the form.
- Click on a different subscription. The edit form should close.
- Resize down to mobile.
- Click on a subscription to open the modal.
- Click the edit button and the form should open.
- Close the modal and click on the same subscription.
- The modal should appear and the edit form should be closed.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/208.
=> Close the edit form when switching subscriptions or closing the modal

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
- Sort the subscriptions by most recently started.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10314.demos.haus/advantage?test_backend=true).
- Look through the "Created" dates of your subscriptions in the list on the left (ignoring the free token), they should be in descending order (i.e. the most recently created should be at the top).
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/120.
=> Sort the subscriptions by most recently started

templates/advantage/subscribe/index.html, tests/advantage/fixtures/subscription.json, tests/advantage/helpers.py, tests/advantage/test_api.py, tests/advantage/test_helpers.py, tests/advantage/test_parsers.py, webapp/advantage/decorators.py, webapp/advantage/models.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/ua_contracts/helpers.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/ua_contracts/primitives.py, webapp/advantage/views.py
- Extracts the subscription `started_with_trial` attribute form subscription json
- Set `can_be_trialled` property to each product listing; 
- When can a user trial a product? 
- has no active or locked subscription with us
- no expired subscription started as a trial (meaning they trialled already a product) 
- product listing `trial_days` is more than 0.
- Will be QA-able when the front-end is ready
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/217
=> Add `can_be_trialled` to product listings

templates/security/cis.html, templates/security/fips.html
- Sync with [copydoc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#) for cis.html
- Sync with copydoc for fips.html
=> Sync with copydoc for FIPS and CIS pages

static/js/src/certified-search-results.js, templates/certified/search-results.html, templates/certified/shared/category-search-results.html
- Added a small amount of right padding to the buttons to ensure there is space between them and the right side of the drawer on small screens
- Added a function to ensure the drawer closes when the page reloads after applying/clearing filters
- Noticed the clear filters button on the generic search page takes you back to `/certified` which isn't the expected behaviour but this is out of scope for this PR. Issue created [here](https://github.com/canonical-web-and-design/ubuntu.com/issues/10325)
- View page at: https://ubuntu-com-10326.demos.haus/certified/desktops or /certified/laptops or /certified/devices (any in the secondary nav)
- Reduce your screen size until you see the toggle drawer button. 
- Click the button to open the filter drawer
- Apply some filters and click "Apply"
- When …
=> Ensure drawer is closed on page reload (small screens)

templates/advantage/index.html, templates/advantage/table/_contract-name.html, templates/advantage/table/_free-trial.html
- Added back in the free trial row element
- Added a "Free trial label" before the free trial row
- Go to http://0.0.0.0:8001/advantage?test_backend=true with a free trial
- it should look like this
- it won't at the moment because the backend is not yet implemented
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/164
=> Add trials label to /advantage table

templates/cube/index.html
- Updated margin to make covered texts visible on `/cube`
- View the site locally in your web browser at: http://0.0.0.0:8001/cube
- Please check if any texts are covered by any images on small screens 
Fixes #10333
=> Make covered texts visible on /cube

webapp/advantage/schemas.py, webapp/advantage/views.py, webapp/app.py
Start a trial endpoint:
```
{
"accountID": account_id,
"purchaseItems": [
{
"productListingID": product_listing_id,
"metric": "active-machines",
"value": 1
}
],
"previousPurchaseID": "",
"inTrial": True
}
POST /advantage/subscribe
```
Cancel a trial endpoint:
`DELETE /advantage/trial/<subscription_id>`
- Make a purchase using https://ubuntu-com-10316.demos.haus 
- Everything should still work
- We can QA the trials easier when the front-end is ready
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/219
=> Add trial endpoints

webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py
- Update /advantage/user-subscriptions with the new trial rules
- The trial user subscription should be listed as its own item on /advantage and not be aggregated with the rest of the purchases for the same product listing
- Will be easier to test when trials are out.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/224
=> User subscription in trial

webapp/views.py
Changed key in `views.py` line 570 from "topic" to "link" to stop search from returning 505 on /tutorials
- View the site locally in your web browser at: https://ubuntu-com-10336.demos.haus/tutorials
- Run a search
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10323
=> added fix for search function on /tutorials

templates/certified/index.html
'See all' for each category should go to the category's landing page rather than a generic category search.
- Visit https://ubuntu-com-10241.demos.haus/certified
- Click on each 'See all' for each category and verify that it goes to each category's landing page rather than performing a search.
=> use certified category pages instead of search

package.json
- make `watch-js` ignore `.test` files - the build was triggered unnecessarely every time a test file would change
- exclude *.test* files from watch-js glob pattern
- check out this branch
- run `dotrun`
- make a change to a `.tsx` file, e.g. `static/js/src/advantage/users/components/AddNewUser/AddNewUser.tsx`
- javascript should be rebuilt
- make a change to a  `.test.tsx` file, e.g. `static/js/src/advantage/users/components/AddNewUser/AddNewUser.test.tsx`
- javascript should not be rebuilt
Fixes #
=> exclude test files from watch-js glob pattern

static/js/src/advantage/api/types.ts, static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/Content/types.ts, static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/react/utils/getSubscriptionCost.test.ts, static/js/src/advantage/react/utils/getSubscriptionCost.ts, static/js/src/advantage/tests/factories/api.ts
- Update subscription types to latest API shape.
- Use the contract id to identify subscriptions.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10322.demos.haus/advantage?test_backend=true) and log in.
- Click on subscriptions on the left, the same subscription should get displayed on the right.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/210.
=> Select subscriptions via contract id

tests/advantage/fixtures/user.json, tests/advantage/fixtures/users.json, tests/advantage/test_api.py, tests/advantage/test_parsers.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/ua_contracts/primitives.py, webapp/advantage/views.py, webapp/app.py
- Add `/advantage/account-users` endpoint following the docs: https://docs.google.com/document/d/1BwKC43kx-keG3vS5YDYHBRgCN_T0cSfCtsSxeavnhHc/edit#heading=h.tlxxyux070vs
- Login on: https://ubuntu-com-10345.demos.haus
- Go to: https://ubuntu-com-10345.demos.haus/advantage/account-users
- Get 200.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/229
=> Add account users endpoint

navigation.yaml, redirects.yaml
- Removed /robotics from IoT subnav 
- View the site locally in your web browser at: https://ubuntu-com-10341.demos.haus/internet-of-things
- **NOTE: The same issue is happening for `/embedded` and `/automotive`, I will submit a separate PR to fix the subnav not persisting on these** 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9504
=> Removed /robotics from IoT subnav

static/js/src/certified-search-results.js, tests/cypress/certified_spec.js
- Ensure that the "Clear" button clears only the filters applied - not the typed query string
- Add some tests for /certified search results
- Fix console errors when the pagination drop downs don't exist when there are no results 
1. 
- View page at: https://ubuntu-com-10353.demos.haus/certified
- In the search bar search for something i.e. "dell"
- When you land on the search results page, apply a filter i.e. "Desktop"
- Select "Apply"
- Then select "Clear"
- You should remain on the search results page, with no filters applied but with the query string still present
2.
- Go to the live site: https://ubuntu.com/certified?q=dell&limit=20&vendor=Ampere+Computing%2C+LLC and see the error in the console.
- Go to the demo: https://ubuntu-com-10353.demos.haus/certified?q=dell&limit=20&vendor=A …
=> [Certified] - Keep query string when filters are cleared

static/js/src/advantage/tests/utils.ts, static/js/src/advantage/users/AccountUsers.test.tsx, static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx, static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.test.tsx, static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.tsx, static/js/src/advantage/users/components/TableView/TableView.test.tsx, static/js/src/advantage/users/components/TableView/TableView.tsx, static/js/src/advantage/users/components/TableView/components.tsx, static/js/src/advantage/users/mockData.ts, static/js/src/advantage/users/types.ts, static/js/src/advantage/users/utils.ts
- Add Delete User modal
- reorganise tests - move edit test up to AccountUsers.test.tsx
- add `getTextContentMatcher` test util
1. Go to https://ubuntu-com-10355.demos.haus/advantage/users?test_backend=true and login
2. Click edit in the actions column
3. Verify that the confirmation message includes the correct user email and closes when clicking a button
https://github.com/canonical-web-and-design/commercial-squad/issues/206
=> account users/delete user modal

navigation.yaml, templates/ceph/managed.html
- Create `/ceph/managed` page
- There is no design for this page so please refer to this [page](https://ubuntu.com/kubernetes/managed). 
- Please check page against [copy doc](https://docs.google.com/document/d/1Ff3TDYBsukagu85dNZuK0FDdPRSjXEwS6Tv6JphXUvY/edit#).
Fixes [#4426](https://github.com/canonical-web-and-design/web-squad/issues/4426#event-5292103962)
=> Build /ceph/managed page

navigation.yaml, templates/ceph/consulting.html, templates/shared/pricing/_ceph-cluster-build-pricing.html
- Create `/ceph/consulting` page 
- There is no design for this page. Please check page against [copy doc](https://docs.google.com/document/d/1LK8mut0O30Zk60mmbgCPFiQ2COR-BUnJnbASMMdyycU/edit#).
Fixes [#4425](https://github.com/canonical-web-and-design/web-squad/issues/4425#event-5292092558)
=> Build /ceph/consulting page

templates/certified/index.html
- Fix links from `/certified`. Point them to e.g. `/certified/desktops?q=&limit=20&release=18.04+LTS` instead of '/certified?category=Desktop&release=18.04%20LTS`
- View page at: https://ubuntu-com-10367.demos.haus/certified
- Click on each of the vendor and release links in the cards
- Check they point to the category specific search results pages such as `/certified/desktops` and `/certified/devices` instead of taking you to the generic search results
Fixes #10364
=> Fix links from certified homepage

static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx, static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/index.html
- Added the error states listed [here](https://miro.com/app/board/o9J_lSky0cQ=/)
- Go to https://ubuntu-com-10363.demos.haus/advantage/subscribe?test_backend=true
- Log in
- You should not be able to start a trial
- You should see error messages telling you your account is not eligible on the bottom of the wizard and on step 2 of the modal
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/169
=> Free trial error states

templates/advantage/index.html
- Change the window title when logged in.
- Visit [/advantage?test_backend=true](/advantage?test_backend=true) when logged out.
- The window title should be "Ubuntu Advantage for Infrastructure | Ubuntu".
- Log in.
- The window title should now be "Ubuntu Advantage Dashboard | Ubuntu".
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/227.
=> Ua subs window title

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
- Display contract features and docs links.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10357.demos.haus/advantage?test_backend=true) and log in.
- Click on the 'Features' and 'Documentation' tabs, you should see appropriate features/docs.
- Click on some different subscriptions on the left and check that they too have appropriate features/docs.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/134.
=> Display contract features and docs links

releases.yaml
- Ubuntu 18.04.6 was released, so we have to update the releases.yaml, or the bit torrents break on /download/alternative-downloads
- View the site locally in your web browser at: http://0.0.0.0:8001/download/alternative-downloads
- See that the 18.04.6 bitorrents all work
=> Update releases.yaml for bionic to point 6

static/js/src/advantage/api/contracts.js, static/js/src/advantage/api/contracts.test.ts, static/js/src/advantage/api/types.ts, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/useCancelContract.test.tsx, static/js/src/advantage/react/hooks/useCancelContract.ts, static/js/src/advantage/react/hooks/useLastPurchaseIds.test.tsx, static/js/src/advantage/react/hooks/useLastPurchaseIds.ts, static/js/src/advantage/tests/factories/api.ts
- Add support for fetch the last purchase ids from the API.
- Add support for cancelling a subscription via the API.
N/A CI should pass, it will be able to be QAed in https://github.com/canonical-web-and-design/ubuntu.com/pull/10369.
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/139.
=> API subscription cancel

templates/kubernetes/docs/proxy-settings.md
- [added missing proxy config page
=> Add proxy docs for k8s

templates/managed/apps/index.html
- Fixed /managed/apps modal contact form not opening 
- Go to the website: https://ubuntu-com-10397.demos.haus/
- Click on the button "Free deployment assessment"
- Make sure that the modal form is shown instead of falling back to the page /managed/contact-us
Fixes #10377
=> Modal form not working on /managed/apps

webapp/advantage/ua_contracts/builders.py
- Fix 500 error if auto renewal is off. 
- Turns out the API returns no payment data if the auto renewal is turned off so we cannot show at the moment display the next payment information:
- Have a montly subscription
- Turn the auto renewal off
- Go to: /advantage/user-info
- You will not get a 500
- You will see
```
{
has_mothly_subscriptions: True,
is_auto_renewing: False
}
```
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/274
=> Fix user info page

static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/sass/_pattern_subscriptions.scss
- Display a border under the expiry notification in the subscription card.
- You will need some expiring subscriptions to QA this, I'm not sure exactly how you can set that up (maybe ask @albertkol). I have some monthly subscriptions that are in that status.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10389.demos.haus/advantage?test_backend=true) and log in
- Find an expiring sub in the list on the left.
- You should see a border between the expiring notification and the rest of the card content.
- The non-expiring subs should have even space inside the card.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/222.
=> Expiry notification border

static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, templates/advantage/index.html
- Display a spinner for the initial load
- Visit /advantage?test_backend=true and log in.
- When the card initially appears you should see a nicer loading state.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/265.
=> Display a spinner for the initial load

package.json, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/index.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, yarn.lock
- Add support for fetching the last purchase ids from the API.
- Add support for cancelling a contract via the API.
- Update the cancel component to cancel the contract.
- Visit [/advantage?test_backend=true](/advantage?test_backend=true) and log in.
- Click on a monthly contract (there is an issue at the moment where you can't select a monthly contract that you also have a yearly subscription for: https://github.com/canonical-web-and-design/commercial-squad/issues/253).
- Click 'Edit subscription'
- Click the 'You can cancel this subscription online or contact us.' link at the bottom.
- Type cancel and then click the red button.
- You subscription should get cancelled.
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/116.
=> Cancel a subscription via the API.

templates/ceph/managed.html
- Update the Ceph webinar link
- Update the copy doc link
- Go to /ceph/managed and click the "Watch the webinar" link in the hero section and see if loads the correct page
- Check the copy doc link is not point to Ceph not K8s
=> Update the Ceph webinar link

konf/site.yaml
Because we can only have 1 per node with our affinity config, and we only have 9 nodes
=> 9 replicas

static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.tsx, static/js/src/advantage/users/components/TableView/TableView.test.tsx, static/js/src/advantage/users/components/TableView/TableView.tsx, static/js/src/advantage/users/components/TableView/UserRow.test.tsx, static/js/src/advantage/users/components/TableView/UserRow.tsx, static/js/src/advantage/users/components/TableView/components.tsx, static/js/src/advantage/users/utils.ts
- handle user editing
-  refactor TableView to use React components - wrap only a single editable row with Formik
- fix long email overflow
- fix column widths
- refactor to use a single notification
- display last admin error message
- display last admin error on failed update
- Go to https://ubuntu-com-10381.demos.haus/advantage/users?test_backend=true and login
- Add a new user
- Edit a role of that user
- Delete a user
- Make sure error/success messages are displayed on each action
https://github.com/canonical-web-and-design/commercial-squad/issues/200
=> 200/account users/edit view

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/react/utils/getSubscriptionCost.test.ts, static/js/src/advantage/react/utils/getSubscriptionCost.ts
- Convert the subscription cost from cents to dollars
- Visit [/advantage?test_backend=true](https://ubuntu-com-10404.demos.haus/advantage?test_backend=true) and log in.
- Click on some subscriptions and compare their cost to the price returned by the API (you could use the backoffice tool to easily see the values, note that /advantage accounts for the number of machines as well as converting from months to years).
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/276.
=> Display subscription cost in dollars

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts
- Update cards and details for displaying legacy contracts.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10406.demos.haus/advantage?test_backend=true) and log into a UA account with a legacy contract (if you have one).
- Click on a legacy contract.
- You should see the legacy details and both the card and the details should match [the design](https://app.zeplin.io/project/60ec5fb4e07cc90fbbf2b318/screen/60ef0929cb3cd60cbfb63144). Note that the renew button does not doing anything yet.
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/157.
Fixes: https://github.com/canonical-web-and-design/commercial-squad/issues/119.
=> Display legacy contracts

static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/utils/index.ts, static/js/src/advantage/react/utils/sortSubscriptionsByStartDate.test.ts, static/js/src/advantage/react/utils/sortSubscriptionsByStartDate.ts
- Select the most recently started subscription by default.
- Visit [/advantage?test_backend=true](/advantage?test_backend=true) and log in.
- The subscription at the top of the list should be selected on first load.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/101.
=> Select the most recently started subscription

static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
- fix new user submission on press of an Enter key
- originally reported by @ClementChaumel here: https://github.com/canonical-web-and-design/ubuntu.com/pull/10381#issuecomment-922777780
This happened because submit is the default if the attribute is not specified for buttons associated with a form
- login and go to /advantage/users?test_backend=true
- Click "Add new user"
- Fill out the form
- Press enter on the keyboard
- user should be added successfully
=> fix new user submission on Enter key

static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx
- Display a message if the subscriptions can't be loaded.
- Open your network dev tools and load [/advantage?test_backend=true](https://ubuntu-com-10386.demos.haus/advantage?test_backend=true) and log in.
- Find the entry for `/advantage/user-subscriptions?test_backend=true`.
- Right click on the entry and click "block" (don't forget to unblock at the end).
- Reload the page.
- The page should load and you should see a message about the subscriptions not loading.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10384.
=> Subscription loading failed message

static/js/src/chart-data.js, templates/about/release-cycle.html
- Update release cycle tables to change end dates for `14.04` to 2024 and `16.06` to 2026 as per copy doc
- View this page at: https://ubuntu-com-10436.demos.haus/about/release-cycle
- Check against the comments in the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) and [spreadsheet](https://docs.google.com/spreadsheets/d/1KIuOAa620yseE0uhIl67u2SlS0bWlPI_d98bvYM2Yl8/edit#gid=677434053)
- The only thing to be updated in this PR is the end dates mentioned. Please ignore the other differences in the chart for now. 
Fixes #10417
=> Updates to release cycle

static/js/src/advantage/users/api.ts, static/js/src/advantage/users/components/TableView/UserRow.tsx, static/js/src/advantage/users/types.ts
- Fix display date when when lastLoginAt is null
- Go to /advantage/users
- Add a new user
- Make sure last login column value for that user is empty
https://github.com/canonical-web-and-design/commercial-squad/issues/281
=> Fix display date when when lastLoginAt is null

static/js/src/advantage/api/types.ts, static/js/src/advantage/react/app.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/useLoadWindowData.test.tsx, static/js/src/advantage/react/hooks/useLoadWindowData.ts, static/js/src/advantage/react/hooks/useStripePublishableKey.test.tsx, static/js/src/advantage/react/hooks/useStripePublishableKey.ts, templates/advantage/index.html
- Set up Stripe for the resize form.
- Add resize form validation.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10423.demos.haus/advantage?test_backend=true) and log in.
- Select a resizable subscription and then click 'Edit subscription...'.
- Check that the 'Number of machines' field matches what's shown in the card.
- Enter "0" into the field and it should show a validation error.
- Enter a valid number and click 'Resize'.
- In your browser console it should log the stripe key.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/280.
=> Set up Stripe

static/js/src/advantage/api/contracts.js, static/js/src/advantage/api/contracts.test.ts, static/js/src/advantage/api/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/useUserInfo.test.tsx, static/js/src/advantage/react/hooks/useUserInfo.ts, static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/tests/factories/api.ts
- Fetch user info from the API.
- Display the renewal settings data.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10387.demos.haus/advantage?test_backend=true) and log in.
- Click on "Renewal settings" at the top of the list.
- The number of subs, price and renewal date are displayed from the API data.
- The 'Auto-renewal' checkbox should reflect the state of your auto renewal settings (probably on).
- Note: the form doesn't update your settings yet (will be done in https://github.com/canonical-web-and-design/commercial-squad/issues/272).
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/99.
=> Display the renewal settings

static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts, static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/index.html
- Removed free trial messaging on live until we release
- reduced the size of the message
- go to https://ubuntu-com-10435.demos.haus/advantage/subscribe?test_backend=true
- select a non trialable product (monthly) see that the message is smaller
- go to https://ubuntu-com-10435.demos.haus/advantage/subscribe
- see that the message is not there
=> Hide free trial message on live if not eligible

static/js/src/advantage/contracts-api.js, static/js/src/advantage/manage-subscription.js, templates/advantage/table/_free-trial.html, webapp/app.py
- Changed the copy to better reflect what the button does
- calls the endpoint on click
- go to https://ubuntu-com-10422.demos.haus/advantage/subscribe?test_backend=true and add a trial if you don't already have one
- then on https://ubuntu-com-10422.demos.haus/advantage?test_backend=true open the corresponding row
- click the button
- the page should reload and the trial should go away
=> Call the delete trial endpoint when the button is clicked

templates/robotics/ros-esm.html
- Fixed duplicated normal strip at the end of the page
- Go to https://ubuntu-com-10451.demos.haus/robotics/ros-esm
- Make sure `p-strip` and `.p-strip--light` are applied on sequentially (should be one section light and the section after a bit darker)
Fixes #
=> Fixed duplicated normal strip at the end of the page

templates/legal/contributors/agreement.html
- Updated PDF links for "Contributor licence agreement"
- Go to the website https://ubuntu-com-10453.demos.haus/legal/contributors/agreement
- Inspect the page and search for the term "Canonical-HA-CLA-ANY"
- There should be two hidden links
- Make sure that these 2 PDF links are reachable
Fixes https://github.com/canonical-web-and-design/canonical.com/issues/427
=> Updated links for "Contributor licence agreement"

templates/openstack/index.html
- Added pit chart to `/openstack` as per: https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#
- View the site locally in your web browser at: https://ubuntu-com-10448.demos.haus/openstack
- See the pie chart is there and that content is displayed correctly on different page sizes (i.e chart replaced by table on smaller screens and vice versa)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10360
=> added pie chart to page

templates/advantage/index-no-login.html, templates/advantage/index.html
- Added notification linking to ubuntu pro beta on /advantage
- go to https://ubuntu-com-10444.demos.haus/advantage
- see the notification
- log in
- check that the notification is also here for the logged in state
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/271
=> Reintroduce the ubuntu pro beta invite

README.md, build.js
- disable JS minification in development
- add `NODE_ENV=development` to README.md
##
- checkout this branch locally and run `dotrun` verifying nothing has changed
- run `NODE_ENV=development dotrun` and verify JS is no longer minified (and you can see full component names in React DevTools)
**Component names are no longer obfuscated** in development.
=> Disable JS minification in development

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx
- Reorder the docs links.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10490.demos.haus/advantage?test_backend=true) and log in.
- Click on the Documentation tab.
- FIPS, CC-EAL and CIS should be the last in the list (before the "to attach..." entry).
Fixes:  https://github.com/canonical-web-and-design/commercial-squad/issues/289.
=> Reorder docs links

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/RenewalSettingsFields.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettingsFields/RenewalSettingsFields.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/useSetAutoRenewal.test.tsx, static/js/src/advantage/react/hooks/useSetAutoRenewal.ts
- Add API support for updating renewal settings.
- Update the renewal settings from the form.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10455.demos.haus/advantage?test_backend=true) and log in.
- Open the 'Renewal settings' dropdown at the top of the list.
- Change the setting and click save.
- Open the form again.
- The form should show the new state.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/272.
=> Update the renewal settings via the API

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx
- Only display the ua subscriptions group if there are ua subscriptions.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10489.demos.haus/advantage?test_backend=true) and log into an account without any UA subscriptions (e.g. a new account).
- You should not see the "UBUNTU ADVANTAGE" group in the list.
- Log out and log back in with account that does have ua subs.
- You should now see the "UBUNTU ADVANTAGE" group.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/286.
=> Conditional ua subscriptions group

static/js/src/advantage/subscribe/react/components/ModalSteps/StepTwo.tsx
Fix the render of enabled free trials in step two
- Go to http://0.0.0.0:8001/advantage/subscribe?test_backend=true
- Step through the purchase and see the purchase model load up
- Purchase with 4242 all the way and see it works
=> Fix the render of enabled free trials in step two

.github/workflows/cypress.yaml, tests/cypress/integration/forms_spec.js, tests/cypress/support/commands.js
Following [a debrief on advantage subscriptions issue](https://github.com/canonical-web-and-design/meeting-notes/issues/903): 
- enable cypress tests on PRs
- skip failing forms tests
- make acceptCookiePolicy selector more explicit
- disable "Send message on failure" (it was failing anyway)
verify Cypress tests are passing https://github.com/canonical-web-and-design/ubuntu.com/pull/10522/checks?check_run_id=3732090457
=> Run cypress on PRs

templates/kubernetes/docs/equinix.md
- Changed instructions for Equinix to reference an example bundle, temporarily
=> K8s: add link for Equinix bundle

templates/templates/footer.html
- Add Observability section to footer as it has 2 pages now
- Remove single link to section
- Scroll to the footer and see the section
Fixes #10496
=> Add Observability section to footer

static/js/src/chart-data.js, static/js/src/release-chart.js
- Removed the maintenance updates from the release cycle in the page ubuntu.com/about/release-cycle as requested in the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)
- Go to the website https://ubuntu-com-10512.demos.haus/about/release-cycle
- Make sure that the maintenance updates are removed as mentioned in the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) and mark the discussion in the [doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#) as done
Fixes #10504
=> Removed the maintenance updates from the release cycle

static/sass/styles.scss, templates/kubernetes/what-is-kubernetes.html
- Remove local style for `.is-crossed` as Vanilla has updated it to a red cross
- Removed `.is-ticked__cross` and `.u-inline` as they are not in use
- View the site locally in your web browser at: http://0.0.0.0:8001/cloud
- See the vanilla red cross
Fixes #10415
=> Remove local style for .is-crossed

templates/kubernetes/docs/1.21/charm-kubernetes-worker.md, templates/kubernetes/docs/1.22/components.md, templates/kubernetes/docs/docker-registry.md
a few minor fixes for k8s docs:
- fix some broken links
- update the calico charm reference
=> K8sDocs - minor updates

.github/workflows/pr.yaml
Dotrun can't be installed with the stable version of the docker snap. There is a fix for this problem in the beta channel.
See that the "run-dotrun" check passes.
See that the "test-python" check now fails because tests are broken, which is a good reason.
=> Fix PR checks: Install Docker beta before dotrun

templates/shared/_cube-contact-us-form.html, templates/shared/_telco-contact-us.html, templates/shared/contextual_footers/_openstack_install_newsletter.html, templates/shared/forms/interactive/cube-beta.html, templates/shared/forms/interactive/observability-contact-us.html
- Update /cube/contact-us and /cube#get-in-touch forms with new fields per the [brief](https://docs.google.com/document/d/14p8YZpe9z7H65pN_C5ebuVEajlLSgLU59zfIgepCwH8/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/cube/contact-us and http://0.0.0.0:8001/cube#get-in-touch
- See that the fields match the brief and that the form works
Fixes #10481 and #10482
=> Update /cube contact forms

static/js/src/advantage/users/AccountUsers.test.tsx, static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/api.ts, static/js/src/advantage/users/app.tsx, static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.test.tsx, static/js/src/advantage/users/components/DeleteConfirmationModal/DeleteConfirmationModal.tsx, static/js/src/advantage/users/components/TableView/TableView.test.tsx, static/js/src/advantage/users/components/TableView/TableView.tsx, static/js/src/advantage/users/components/TableView/UserRow.test.tsx, static/js/src/advantage/users/components/TableView/UserRow.tsx, static/js/src/advantage/users/components/UserSearch/UserSearch.tsx, static/js/src/advantage/users/mockData.ts, static/js/src/advantage/users/types.ts, tests/cypress/integration/advantage-users_spec.js
- add search to account users page
- remove `async` from `fetchJSON` - https://github.com/canonical-web-and-design/ubuntu.com/pull/10509#discussion_r716504047 @carkod 
- remove redundant `id` from `User` type (some ids are missing, this can't be used as a unique ID - use email as a unique identifier instead)
- go to https://ubuntu-com-10524.demos.haus/advantage/users and login
- type in the searchbox and verify that correct results are shown
- try to break things
https://github.com/canonical-web-and-design/commercial-squad/issues/198
https://user-images.githubusercontent.com/7452681/135111859-f64da05c-2f30-40b2-acb0-1e88847f1ad5.mp4
=> 198/Account users/Search

templates/download/shared/_get-ebook-security.html
- Updated `MktoPersonNotes` to `mktoPersonNotes` to make the form submit
http://0.0.0.0:8001/download/up-squared-iot-grove-server, http://0.0.0.0:8001/download/intel-nuc-desktop, http://0.0.0.0:8001/download/intel-iei-tank-870, http://0.0.0.0:8001/download/qualcomm-dragonboard-410c, http://0.0.0.0:8001/download/kvm, http://0.0.0.0:8001/download/raspberry-pi-coreand http://0.0.0.0:8001/download/intel-nuc
- See that the security ebook form now submits.
=> Update marketo field for security ebook

templates/shared/contextual_footers/_iot_newsletter_signup.html, templates/shared/contextual_footers/_robotics_newsletter_signup.html
- Updated two forms with field `canonicalOptIn` to `canonicalUpdatesOptIn` which is the correct field name
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/edgex and http://0.0.0.0:8001/robotics
- Go to the newsletter sign-up and see that it submits
#10537
=> Update forms with field canonicalOptIn to canonicalUpdatesOptIn

templates/kubernetes/compare.html
- Updated icon from whitepaper to case study
- Replaced the muted headings with `h4` as per design advice [here](https://github.com/canonical-web-and-design/vanilla-framework/pull/3935#issuecomment-903651888). We are no longer to use the whitepaper/case-study/webinar icons with the muted heading. 
- View page at: https://ubuntu-com-10549.demos.haus/kubernetes/compare
- Check the icon is now a case study instead of a whitepaper
- Check the headings are `h4` not muted. 
Fixes [#4470](https://github.com/canonical-web-and-design/web-squad/issues/4470)
=> Copy update on /kubernetes/compare

navigation.yaml, templates/kubernetes/docs/1.20/charm-kubernetes-worker.md, templates/kubernetes/docs/1.22/components.md, templates/kubernetes/docs/1.22/release-notes.md, templates/kubernetes/docs/charm-etcd.md, templates/kubernetes/docs/docker-registry.md, templates/kubernetes/docs/ingress.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/install-offline.md, templates/kubernetes/docs/proxies.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/supported-versions.md
- Adds a page for offline install
-  Adds Ingress page
- Updates to the proxy page
- minor correction to etcd docs
=> K8sdocs offline docs

.github/workflows/cypress.yaml, tests/cypress/integration/advantage/subscribe_spec.js, tests/cypress/integration/advantage/subscriptions_spec.js
- skip failing e2e tests
intermittent cypress test failures for logged-in state are due to payment issues (concurrency on the back-end) that occur on the single test account that we use.
I will work on using a better method to avoid this issue in the future, but disabling these until it's done.
=> Skip failing e2e tests

templates/download/raspberry-pi/index.html, templates/download/raspberry-pi/thank-you.html
- Updates /raspberry-pi as per [copydoc](https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#heading=h.pcvvnawhd192)
- View the site locally in your web browser at: https://ubuntu-com-10754.demos.haus/download/raspberry-pi
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9722
=> Update raspberry-pi page 

tests/advantage/test_api.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/views.py, webapp/cube/views.py
This new endpoint behaves exactly like the old one, it's just a different path. The change in ua-contracts happened because of early account management developments, and some requirements we anticipate will arrive in the future.
The same migration was done to the new `EnsureAccountForMarketplace` last week, when the captcha for guest purchases was introduced. This PR is just finishing the work.
To test it, go to https://ubuntu-com-10763.demos.haus/advantage/subscribe?test_backend=true and view your payment methods. If it works, it works :)
=> Use the new GetAccountForMarketplace endpoint from ua-contracts

webapp/advantage/views.py
- If for some reason the payment gets stuck with the status `started` and no invoice is attached to the payment, the /invoices breaks.
- Go to https://ubuntu-com-10748.demos.haus/account/invoices?test_backend=true&email=albert.kolozsvari@canonical.com
- Can you see the missing invoice?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/353
=> Prevent invoices page to break on payment without invoice

templates/certified/model-details.html, webapp/certified/views.py
- Add `hardware_website=model_release["hardware_website"]` to view
- For most models this is empty so add conditional render of website link to model_details page. 
- View page at: https://ubuntu-com-10774.demos.haus/certified/202105-29115
- Check the website link is available under the header
- Check on another model with no website link the page doesn't break i.e. https://ubuntu-com-10774.demos.haus/certified/202012-28554
Fixes #10723
=> [Certified] - Add website link on model details page

static/js/src/advantage/api/contracts.js, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/components/FeaturesTab/FeaturesTab.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useResizeContract.test.tsx, static/js/src/advantage/react/hooks/useResizeContract.ts, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/react/utils/index.ts, static/js/src/advantage/react/utils/isBlenderSubscription.test.ts, static/js/src/advantage/react/utils/isBlenderSubscription.ts, webapp/advantage/ua_contracts/builders.py
- Added blender subscriptions to /advantage
- Made adjustments to components to display blender infos correctly
- Go to https://ubuntu-com-10724.demos.haus/advantage?test_backend=true with a blender subscription (you can buy one here https://ubuntu-com-10711.demos.haus/advantage/subscribe/blender?test_backend=true )
- Check that it displays correctly
Fixes 
https://github.com/canonical-web-and-design/commercial-squad/issues/341
https://github.com/canonical-web-and-design/commercial-squad/issues/342
=> Display blender subscriptions on /advantage

templates/download/iot/index.html, templates/templates/navigation-download-h.html
- Removed up2 from the download mega menu
- Removed numbers from Raspberry Pi models from the download mega menu
- Fixed the link to Up2 on /download/iot
- View the site locally in your web browser at: http://0.0.0.0:8001/#download and http://0.0.0.0:8001/download/iot
- Compare to the [copy doc](https://docs.google.com/document/d/11pX5gxOE6UWljIGRBZdwuCL1MHzs4pNgxJpK0mcIqdQ/edit#) and resolve comments
Fixes #10780
=> Update download megamenu remove up2

templates/security/notices/lsn.html, templates/security/notices/usn.html
- Adjust CVE references links
What happens now:
- Go to https://ubuntu.com/security/notices/USN-5114-1
- Scroll down to the **References** section you will see a list of CVE ids
- If you take a look at the URL of the CVE ids, it will use our old people.canonical.com url. Which will make the redirect to ubuntu.com, but ideally we should just use the ubuntu.com url
QA the new behaviour:
- Fetch the branch changes locally
- Ask @albertkol for the email of how to set up the CVE database locally.
- Go to a notice page: https://0.0.0.0:8001/security/notices/USN-4414-1 
- Scroll down to the **References** section you will see a list of CVE ids
- Check the links of the CVE ids, the new link will be to <localhost_url>/security/<cve_id> (which on prod is ubuntu.com)
Fixes …
=> Adjust CVE references links

templates/download/raspberry-pi-core.html
- Updates copy on raspberry-pi-core as per [copydoc](https://docs.google.com/document/d/1Ig906jbgB39QHw61uHMvIsRbSBUjchJBDkMZl0WzlWM/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10710
=> Update copy on raspberry-pi-core

templates/kubernetes/docs/1.22/components.md, templates/kubernetes/docs/1.22/release-notes.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/supported-versions.md
- Update release notes
- Update and fix components page
- Add ingress page to navigation
=> K8sdocs 1.22+ck2 updates

templates/advantage/beta/thank-you.html, templates/shared/forms/interactive/advantage-beta.html
- Create a new page under /advantage/beta/thank-you
- go to https://ubuntu-com-10785.demos.haus/advantage
- click "Join our free beta programme for Ubuntu Pro on prem ›"
- fill in the form
- submit
- see that you land on https://ubuntu-com-10785.demos.haus/advantage/beta/thank-you
Fixes canonical-web-and-design/commercial-squad#352
=> Create ad hoc thank you page for pro beta contact form

static/js/src/advantage/api/contracts.js, static/js/src/advantage/react/hooks/useCancelContract.test.tsx, static/js/src/advantage/react/hooks/useCancelContract.ts, webapp/advantage/schemas.py, webapp/advantage/views.py
- Add marketplace parameter to the cancel subscription endpoint
- Have a monthly blender purchase
- If you do not have one use this demo and purchase one: https://ubuntu-com-10711.demos.haus/advantage/subscribe/blender?test_backend=true
- After you finished purchasing the blender product go to this demo: https://ubuntu-com-10787.demos.haus/advantage?test_backend=true
- You will see you blender subscription you purchased
- Hit edit subscription and then try to cancel the subscription
- It should work and after that the edit subscription button will disappear because the status of the subscription is `is_cancelled`. You can confirm that by checking the raw data ttps://ubuntu-com-10787.demos.haus/advantage/user-subscriptions?test_backend=true
Fixes …
=> Fix blender cancel subscription

templates/download/iot/index.html
- Fix form modal id to 1266 as mentioned in the [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot or https://ubuntu-com-10793.demos.haus/download/iot 
- Please mark the discussion as resolved in the [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit) once the QA is done
Fixes #10791
=> fix modal form id

navigation.yaml
- fix the missing subnav in /embedded and /automotive
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things or https://ubuntu-com-10800.demos.haus/internet-of-things
- Click on the subnav `embedded` and `automotive`
- Make sure that both pages have the subnav
Fixes #10427 
=> persist embedded and automotive to show the subnav in both pages

navigation.yaml, templates/containers/what-are-containers.html, templates/kubernetes/what-are-containers.html
- Builds what-are-containers as per [copydoc](https://docs.google.com/document/d/1hStuIzY8dDdFEW4Q0TwboOx0_-SB5klk8zRuNIn3V4o/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/containers/what-are-containers or https://ubuntu-com-10761.demos.haus/containers/what-are-containers
- Check navigation works
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4567
=> Build what-are-containers

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts
This is fixing a small issue that caused the renewal settings button and menu to be displayed empty if the user had any active subscription (monthly/yearly), even if it was not time to display it yet (nothing was displayed though, the menu would be empty).
Tests were also updated to catch this.
=> Fix issue that caused renewal settings to be displayed empty

templates/templates/navigation-developer-h.html, templates/templates/navigation-enterprise-h.html
- Update Enterprise and Developer mega menus with new and updated urls
- View the site locally in your web browser at: http://0.0.0.0:8001/#enterprise and http://0.0.0.0:8001/#developer
- Compare ENTERPRISE to the [copy doc](https://docs.google.com/document/d/1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ/edit?usp=drivesdk)
- Compare DEVELOPERS to the  [copy doc] and resolve comments(https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit?disco=AAAAQvhOfSo&usp_dm=true) and resolve comments
Fixes #10797
=> Update Enterprise and Developer mega menus

navigation.yaml, templates/openstack/tutorials.html
- Create /openstack/tutorials page
**NOTE**: Waiting for tutorials to be uploaded to discourse
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/tutorials or https://ubuntu-com-10687.demos.haus/openstack/tutorials
- Compare page against [copydoc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#)
- Check tutorials appear in navigation of openstack and are accessible through /openstack/install 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4586
=> [OpenStack tutorials] Create /openstack/tutorials page

templates/kubernetes/what-is-kubernetes.html
- Added link to glossary section as per [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#)
- View the site locally in your web browser at: https://ubuntu-com-10822.demos.haus/kubernetes/what-is-kubernetes#tab3
- See that the update has been made and that the link works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10821
=> Added link to /what-are-containers inside glossary

static/js/src/chart-data.js, templates/about/release-cycle.html
- Update openstack-eol chart to changes 'Openstack Y' to 'Openstack Yoga' and removes the row 'Openstack Queens'.
- |Compare against [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10817
=> Update openstack-eol chart

templates/templates/base.html, templates/templates/base_no_nav.html
- Removed `meta` tag that had `theme-color` so the header can be default colour on safari. 
- Check if the header colour turns to orange on safari. 
Fixes [#10540](https://github.com/canonical-web-and-design/ubuntu.com/issues/10540)
=> Remove theme-color

templates/templates/navigation-download-h.html
- Added "Intel IoT platforms" link to Download dropdown nav, per [copy doc](https://docs.google.com/document/d/11pX5gxOE6UWljIGRBZdwuCL1MHzs4pNgxJpK0mcIqdQ/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/ or visit https://ubuntu-com-10830.demos.haus
- Click the "Download" nav item, and see that "Intel IoT platforms" appears as the second link below Ubuntu for IoT
- Click the link, it should take you to https://ubuntu-com-10830.demos.haus/download/iot/intel-iotg
Fixes #10820 
=> add Intel IoT platforms link to download nav

webapp/advantage/decorators.py, webapp/advantage/views.py, webapp/login.py
- added extra metadata needed for marketing campaigns. On further discussion with marketing, we need to pay attention to `utm_source` when adding metadata for marketing-triggered purchase.
- go to http://0.0.0.0:8001/support?utm_source=google_ad&utm_medium=search&utm_campaign=7014K000000gaQfQAI&gclid=this-is-a-click-id
this extends the work on the linked 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10696 …
=> add extra purchase metadata for marketing purposes

static/js/src/chart-data.js
- Update kernel-eol graph data to have the correct dates as per spreadsheet data
- Compare against [copydoc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit) and spreadsheet
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10834
=> Update kernel-eol graph data

redirects.yaml
- Redirect risc-v to wiki.ubuntu.com/RISC-V for the [video](https://docs.google.com/document/d/1vSMf_p1AXkPPzJhC-8pmceQSeyODGuWHuGcl6ROcxms/edit?disco=AAAAQ0sgz-8&usp_dm=true)
- View the site locally in your web browser at: http://0.0.0.0:8001/risc-v and see that it redirects to https://wiki.ubuntu.com/RISC-V
=> Redirect risc-v to wiki.ubuntu.com/RISC-V

templates/legal/ubuntu-advantage-service-description/_base_legal_markdown.html
- Removes p-stick-toc class from contents in UASD as a temporary fix for the contents not fitting properly on the screen.
- Check down [demo](https://ubuntu-com-10845.demos.haus/legal/ubuntu-advantage-service-description)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10835
=> Temporary fix for TOC not working properly in UASD

navigation.yaml
- This introduces a direct link to documentation from the certifications page. The documentation has been improved significantly and it can be directly linked to.
=> Explicitly reference documentation in certifications

templates/openstack/install.html, templates/shared/contextual_footers/_openstack_install.html, templates/shared/contextual_footers/_openstack_install_documentation.html
- Updates links to point to /openstack/tutorials
- Updates to correct asset and fixes formatting
- Compare against [copydoc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)
=> Fixed link and formatting issue in '/openstack/install"

static/js/src/advantage/react/utils/filterAndFormatEntitlements.test.ts, static/js/src/advantage/react/utils/filterAndFormatEntitlements.ts, static/js/src/advantage/react/utils/getFeaturesDisplay.test.ts, static/js/src/advantage/react/utils/getFeaturesDisplay.ts
- Changed the logic to only display ESM Apps if it's included in the conctract
- go to [/advantage?test_backend=true](https://ubuntu-com-10803.demos.haus/advantage?test_backend=true) with an ESM Apps contract (you can buy one at [/advantage/subscribe?test_backend=true](https://ubuntu-com-10803.demos.haus/advantage/subscribe?test_backend=true) )
- Check that the badge and the toggle for ESM Apps display correctly for this subscription
- Check that no mention of ESM apps appear on infra only subscriptions
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4569
=> Show ESM Apps only if it's included

static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
- go to https://ubuntu-com-10861.demos.haus/advantage?test_backend=true
- log in with an account that has a blender subscription
- click edit subscription on the side panel and see that every mention of machine has been replace by "user"
Fixes canonical-web-and-design/commercial-squad#397
=> Replace machine with user for blender subs

requirements.txt, webapp/login.py
- This is a copy of this PR for snapcraft.io: https://github.com/canonical-web-and-design/snapcraft.io/pull/3740
- Stop using our own fork FlaskOpenID-Stateless to use the original module.
- Check the authentication is working as usual.
=> Use original Flask-OpenID instead of FlaskOpenID-Stateless

static/js/src/openstack/react/components/CostCalculatorForm.jsx
- Updated inputs to include `aria-label` instead of `arialabel` to ensure voice over works correctly 
- View page at: https://ubuntu-com-10874.demos.haus/openstack/pricing-calculator
- Use the voice over tool to tab through the inputs in the pricing calculator to check the label is read out with the value. 
- alternatively inspect the inputs and check they have `aria-label` attribute.  
=> Accessibility - Fix typo in aria-label

static/js/src/tutorial.js, static/js/src/tutorial.test.js, static/sass/_layout-tutorial.scss, templates/tutorials/tutorial.html
This fixes accessibility of the tutorial chapter menu button.
- go to this example to test: http://127.0.0.1:8001/tutorials/setting-up-lxd-1604
Fixes #10867 
=> fix: accessibility for tutorial chapter menu button

templates/shared/_cloud-contact-us-form.html
- Updated input name from `jobTitle` to `title` as marketo expects it to be`title`
=> fix input name on cloud-contact-us-form

webapp/views.py
- Add a function that HTML encodes. 
- Encode `Comments_from_lead__c` in `form_fields` before submitting.
- Check if `Comments_from_lead__c`  in `form_fields` is html encoded before submitting.
- Please check if this PR resolves this [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/10394) 
Fixes[#10394](https://github.com/canonical-web-and-design/ubuntu.com/issues/10394)
=> Add function that HTML encodes

navigation.yaml, static/js/src/advantage/api/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/hooks/useContractToken.test.tsx, static/js/src/advantage/react/hooks/useContractToken.ts, static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/tests/factories/api.ts, templates/account/forbidden.html, tests/advantage/fixtures/account.json, tests/advantage/fixtures/accounts.json, tests/advantage/helpers.py, tests/advantage/test_api.py, tests/advantage/test_helpers.py, tests/advantage/test_parsers.py, webapp/advantage/schemas.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/ua_contracts/primitives.py, webapp/advantage/views.py
- Implement user roles rules:
- `technical`: Cannot access /invoices and /payment-methods
- `billing`: Cannot see Support portal button and token
Test billing user:
- Go to https://ubuntu-com-10819.demos.haus/advantage?test_backend=true&email=albert.kolozsvari%2Btester7%40canonical.com
- Check the support button is not there on any of the user subscriptions while Edit subscription is there
- Check the token never shows up
Test billing user:
- Go to https://ubuntu-com-10819.demos.haus/advantage?test_backend=true&email=albert.kolozsvari%2Btester3%40canonical.com
- Check the support button is there on any of the user subscriptions
- Check that no edit subscription buttons are there
- Check the token shows up
Test admin user (with your own account):
- can do all
Fixes …
=> Fix ua permissions

webapp/views.py
Only escape form comments when they exist
- Go to /engage/enterprise-kubernetes-comparison
- Check you land on the thank you page
Resolves: https://sentry.is.canonical.com/canonical/ubuntu-com/issues/23366/
=> Only escape form comments when they exist

templates/account/invoices/index.html
Add option to filter for Blender Support invoices
- If you don't have blender invoices make a test purchase
- Go to /account/invoices
- Filter by blender support
=> Add option to filter for Blender Support invoices

navigation.yaml, webapp/advantage/views.py
- Re-enable user management feature
Test the user management:
- `billing` cannot: see support portal button, subscription tokens, access user management page 
- `billing` can: view invoices, payment methods, make resizes, cancellations and purchases
- `technical` cannot: edit subscriptions, access buy subscription, invoices, payment methods and user management pages
- `technical` can: see support portal button, subscription token
- `admin` can do all
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/406
=> Re-enable user management

.github/workflows/cypress-main.yaml, README.md
- Update github action to send messages to the `web & design` and `marketing` channels on Mattermost when it fails.
- not sure how we can QA this PR because this github action(`cypress-main` workflow) only runs when a PR is pushed to main (after merge).
- I tested it with the `cypress-pr` workflow and it worked. 
Fixes [#4440](https://github.com/canonical-web-and-design/web-squad/issues/4440)
=> Update github action to send message on failure

konf/site.yaml, webapp/advantage/decorators.py, webapp/cube/api.py, webapp/cube/views.py
- Fix issues between environments mentioned in https://github.com/canonical-web-and-design/commercial-squad/issues/366 that manifest in https://github.com/canonical-web-and-design/ubuntu.com/pull/10743#issuecomment-957316184
- Refactored API classes into CUBE decorator function and removed reliance on `flask.g` global store
- Removed some variables unused by front-end in the `microcerts.json` endpoint
- I believe best way to QA this is to use [Morgan's PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10743#issuecomment-957316184)
- One way to do this, would be to:
```
git checkout -b carkod-microcerts-fix-envs main
git pull https://github.com/mrgnr/ubuntu.com.git cube-purchase-study-labs
git pull https://github.com/carkod/ubuntu.com.git microcerts-fix-envs
```
- Purchase a …
=> Microcerts fix data inconsistencies across environments

templates/telco/openran.html
- Add links to cloud pages on '/OpenRAN' as per [copydoc](https://docs.google.com/document/d/181cqeYzSZ_RinjPTMMNDyAEMwKVvdeoc30iQDrwl4aQ/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/openran
- Check links work, compare against copydoc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4639
=> Add links to cloud pages on '/OpenRAN'

tests/advantage/test_helpers.py, webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py
- Before I was assuming that user subscriptions that end in year 9999 are always of type free, if the user subscription is not of type free and would end in year 9999, then the page crashes.
- Have rights to view as 
- Log in on https://ubuntu.com
- Go to https://ubuntu.com/advantage?email=domas.monkus@canonical.com
- It will error out
- Log in on https://ubuntu-com-10918.demos.haus
- Go to https://ubuntu-com-10918.demos.haus/advantage?email=domas.monkus@canonical.com
- It will work!!!
Fixes #https://github.com/canonical-web-and-design/ubuntu.com/issues/10915
=> Non-free subscriptions can end in year 9999

templates/engage/base.html, templates/engage/shared/_de_engage_form.html, templates/engage/shared/_en_engage_form.html, templates/engage/shared/_es_engage_form.html, templates/engage/shared/_fr_engage_form.html, templates/engage/shared/_it_engage_form.html, templates/engage/shared/_pt_engage_form.html, tests/cypress/forms/forms_spec.js
- Add cypress test for forms on engage pages
- Removed `aria-label` and  fixed label texts  in the engage form 
1. Create `cypress.env.json` file
2. Copy and paste below (Reach out to me if you don't have keys)
`{ "UBUNTU_USERNAME": "", "UBUNTU_PASSWORD": "", "MARKETO_CLIENT_ID": "", "MARKETO_CLIENT_SECRET": "", "MARKETO_AUTHORISED_USER": "", "MARKETO_TOKEN": "" }`
3. Move forms_spec.js file in the /tests/cypress/forms folder to /tests/cypress/integration folder for testing
4. Run the site using the command ./run serve or dotrun
5. Use `yarn run cypress open --config-file tests/cypress/cypress.json --config baseUrl=http://0.0.0.0:8001/` to run cypress test
6. Click `forms_spec.js`
7. Check if the test passes. (You can skip static contact-us page and interactive forms tests by adding …
=> Add cypress test on engage pages

templates/observability/index.html
- Add blog post strip for the `observability` tag
=> Add blog post strip to /observability

templates/about/release-cycle.html
- Updated text not in copy doc
The text replaced (end-of-life) was picked by google when searching for "ubuntu 16.04 lifecycle", but it was incorrect. It is not visible in the page itself. If the text is coming from a supported spreadsheet let me know, but the spreadsheet I checked did not use these terms for LTS releases, so I'm updating the page directly.
=> release-cycle: updated text

static/js/src/chart-data.js, templates/about/release-cycle.html
- Update "21.10 kernel" to "5.13 kernel" on `/about/release-cycle#ubuntu-kernel-release-cycle`
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle#ubuntu-kernel-release-cycle
- Please go to the [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/10866) and double check if this PR fixes the issue properly
Fixes [#10866](https://github.com/canonical-web-and-design/ubuntu.com/issues/10866)
=> Update kernel on /about/release-cycle#ubuntu-kernel-release-cycle

templates/financial-services/index.html
- Updates copy as per [copydoc](https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit#)
- Updates logo sections patterns to use the current vanilla pattern
- Some formatting changes
- View the site locally in your web browser at: https://ubuntu-com-10913.demos.haus/financial-services
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10905
=> Update copy for '/financial-services'

templates/engage/base.html
- Display the engage page publish_date.
- Go to https://ubuntu-com-10948.demos.haus/engage/developer-desktop-productivity-whitepaper
- Open code inspector, you should find this publish date inside `id="main-content"` with `id="publish_date"`
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10598
=> Add publish date to engage page

templates/security/cve/index.html, webapp/context.py
- Fixes 'version/status' not being retained between pages on cve-search
- Check that the filter parameters are retained between pages, specifically when there is more than one version/status.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10799
=> Fix 'version/status' not being retained between pages on cve-search

templates/security/cve/_cve-table.html
- Made a sticky table with first column and horizontal scroll on `/security/cve`
- You need to setup your local database with the cve data to see the table (Refer to [this](https://gist.github.com/goulinkh/3b4d6228de316d3a2cb2bf9450a97290) and let me know if you need anything about how to set up) 
- Please check the responsiveness and if everything works properly on all screens 
Fixes #9325 
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/ …
=> Fix responsiveness on /security/cve

templates/templates/navigation-enterprise-h.html
- Update cloud menus in the mega menu 
- Click `Enterprise` in the navigation bar and check if `Cloud` menu is updated properly
- Refer to this [brief](https://docs.google.com/document/d/1SCt5PuvmXgMdVCiQ837QnAnrMI9XLcJt8KRV4HyNsQ4/edit#)
Fixes [#4645](https://github.com/canonical-web-and-design/web-squad/issues/4645)
=> Update clouds in the mega menu

navigation.yaml, templates/legal/ubuntu-advantage-service-description/_toc.html, templates/legal/ubuntu-advantage-service-description/ros-esm-service-description/_base_legal_markdown.html, templates/legal/ubuntu-advantage-service-description/ros-esm-service-description/_toc.html, templates/legal/ubuntu-advantage-service-description/ros-esm-service-description/index.html
- Build a new page on `/legal/ubuntu-advantage-service-description/ros-esm-service-description`
- Added this new page as an element in the content table on `/legal/ubuntu-advantage-service-description`
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description/ros-esm-service-description
- Please refer to [Brief](https://docs.google.com/document/d/1TqixK0VoBC-mOUInYKGs1uNZfAwpORlU9SB1oqRcT48/edit) and [Copy doc](https://docs.google.com/document/d/12OGV0hnxPvwY2pT8gbS2vHQp3icndJeaEyqc1G_oIoM/edit#)
- Please check if this new page is linked properly on …
=> Build a new page on /legal/ubuntu-advantage-service-description/ros-esm-service-description

templates/edge-computing/index.html
- Make /edge-computing responsive on small screens as per the conversation on the original [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10928) 
- View the site locally in your web browser at: https://ubuntu-com-10960.demos.haus/edge
- Check responsiveness of the site on small screens
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10959
=> Make /edge-computing responsive on small screens

static/js/src/advantage/subscribe/react/app.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, templates/advantage/subscribe/blender/index.html, templates/advantage/subscribe/index.html
- No longer redirects logged in users to the thank you page.
- Create blank Ubuntu One account
- Login
- Buy a product
- Be redirected to /advantage
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/395
=> Fix thank you redirect

tests/advantage/test_parsers.py, webapp/advantage/ua_contracts/parsers.py
- If `obligations.enabledByDefault` was missing from the entitlement payload the code would crash. This change prevents that, defaulting to `False`.
- Go to /advantage. Does it error out?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/420
=> Fix entitlement problem

templates/kernel/index.html
- Replace use of 'custom kernels' with 'optimised kernels' to follow modern descriptive patterns
- Updated copydoc
- View the site locally in your web browser at: https://ubuntu-com-10964.demos.haus/kernel
- Check no use of 'custom kernel' exist. 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10863
=> Replace use of 'custom kernels' with 'optimised kernels'

templates/download/iot/intel-iotg.html
- Updated links to release notes according to latest comments in the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- View the site locally in your web browser at: https://ubuntu-com-10968.demos.haus/download/iot/intel-iotg
- Check the links, make sure they match the comments in the [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
=> Update intel iot release notes to nov 30th versions

templates/tutorials/index.html
- /tutorials now has an option for Ubuntu Advantage
- if you add 'ua' as a cateogry on discourse, it will appear on /tutorials
- See that there are 2 UA tutorials
=> Add Ubuntu Advantage as topic category on /tutorials

templates/appliance/adguard/index.md
- Update AdGuard specifications to match snapcraft.io (see attached issue)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10767
=> Update AdGuard specifications to match snapcraft.io

templates/security/docker-images.html
- Update links to 'ECR Public' on '/security/docker-images' as per [copydoc](https://docs.google.com/document/d/1zZibtjU141e4mBxo_0PtfYxJ6e5fyaaAdFZ6v945XAM/edit#)
- View the site locally in your web browser at: https://ubuntu-com-10981.demos.haus/security/docker-images
- Check the 'ECR Public' links go to the right place
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10972
=> Update links on '/security/docker-images'

templates/security/cve/_cve-table.html
- Reverted file to before this [pr merge](https://github.com/canonical-web-and-design/ubuntu.com/pull/10945)
- Still need to reimplement mobile [redesign](https://github.com/canonical-web-and-design/ubuntu.com/issues/9325) in a way that will not break desktop
- View the site locally in your web browser at: https://ubuntu-com-10975.demos.haus/security/cve
- See that the concerns listed in [issue](https://github.com/canonical-web-and-design/ubuntu.com/issues/10974) are no longer there
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10974
=> CVE table styling fix

templates/security/cis.html
- Adds a new section about CIS benchmarking
- Updates video link
- Small copy changes
- Some fly-by layout changes
- Compare against [copydoc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10973
=> Update '/security/cis' with CIS benchmark section and copy changes

webapp/advantage/decorators.py, webapp/advantage/views.py
- Fix the login redirect of the thank you page. Right now it sends people back to the thank you page which asks them to register/sign in again, even if the user is already logged in.
- Now we only allow logged out users to hit the /thank-you page
- Go to https://ubuntu-com-10980.demos.haus/advantage/subscrive/thank-you?email=abc@canonical.com&test_backend=true
- Click the green button to log in
- Log in
- You will hit /advantage?test_backend=true.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/423
=> Fix thank you login redirect

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/PurchaseModal/components/ModalSteps/StepTwo.tsx, static/js/src/PurchaseModal/utils/utils.ts, static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/RenewButton.tsx, static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewalModal.tsx, static/js/src/advantage/subscribe/blender/BlenderPurchase.tsx, static/js/src/advantage/subscribe/blender/BuyButton.tsx, static/js/src/advantage/subscribe/react/UAPurchase.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts
- Add marketing opt-in checkbox to the purchase modal (for Advantage, Blender, and renewals)
- Add checkbox value and store name to Marketo form
- Run the server with `dotrun`
- Go to http://localhost:8001/advantage/subscribe?test_backend=true
- Click the "Buy now" button and enter payment info to get to step 2 of the purchase modal
- Verify that the marketing opt-in checkbox appears and is functional
- Complete the purchase
- Verify in Marketo that the settings have been updated (Morgan can check for you)
- Go to http://localhost:8001/advantage/subscribe/blender?test_backend=true and repeat
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/399
=> Add marketing opt-in checkbox for purchases.

static/sass/_pattern_cve.scss
- The table header ellipsis was not fixed by this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10985) 
- Fixed table header ellipsis on medium size screens
- Be sure to test on mobile, tablet and desktop screensizes
- You need to setup your local database with the cve data to see the table
- Please check the responsiveness and check if everything works properly on all screens
Fixes #
from 
to
=> Fix table header on /security/cve

templates/download/xilinx/index.html
Update the download links as the names have been changed for the new release, the new links can be found in the [copydoc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10992
=> Update download links on '/xilinx'

static/sass/_pattern_cve.scss
- Fix the truncated texts/numbers in the table.
- Update styles that didn't work on Firefox. 
- Please check the responsiveness and check if everything works properly on all screens
- Please QA on Firefox 
1. check if truncated texts are fixed with Firefox custom font setting and 
2. check if borders styles are working properly on Firefox
Fixes [#10778](https://github.com/canonical-web-and-design/ubuntu.com/issues/10778) …
=> Fix invisible text on /security/cve

static/js/src/chart-data.js, templates/about/release-cycle.html
- Updates the release cycle table for Kubernetes correct as of  2020-12-07
=> release-cycle-update

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListGroup/ListGroup.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts
- Add selector to filter auto-renewable subscriptions by marketplace
- display blender auto-renewal settings
- go to https://ubuntu-com-10997.demos.haus/advantage?test_backend=true with a monthly blender sub
- (if you don't have one, you can buy it at https://ubuntu-com-10997.demos.haus/advantage/subscribe/blender?test_backend=true (credit card 4242424242...) )
- See that the auto-renewal dropdown displays at the top of the blender section
- check that the values displayed in the dropdown are correct
- toggle it off and on and see that the change gets saved
- check that it doesn't mess with UA subs
Fixes canonical-web-and-design/commercial-squad#380
=> Blender auto-renewal settings implementation

templates/download/xilinx/index.html
- Copy update on `/download/xilinx`
- Switch the two tabs position 
- View the site locally in your web browser at: http://0.0.0.0:8001/download/xilinx
-  Be sure to test on mobile, tablet and desktop screen sizes
- Please check page against [copy doc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit#) and resolve comments
Fixes [#4675](https://github.com/canonical-web-and-design/web-squad/issues/4675)
Before:
After : 
=> Copy update on /download/xilinx

webapp/security/views.py
- Made search queries case insensitive
- Added ability to search by title
- TODO: add ability to search by package name (will address in separate pr)
- Search for runc and runC and ensure they both return the same thing
- Attempt to search for notice by title and see that it is returned 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9454
https://github.com/canonical-web-and-design/ubuntu.com/issues/9856
=> Update security/notices query filter

templates/download/cloud/index.html
- Updated /download/cloud according to most recent comments in the [copy doc](https://docs.google.com/document/d/1kp7QQXst1EbCjZjzWZP3YZwfmG0EIXLfQoRUVaMEZng/edit#)
- View the demo in your web browser at: http://0.0.0.0:8001/
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4681
=> Remove mention of Rackspace from /download/cloud

tests/cassettes/TestRoutes.test_engage_index.yaml, tests/cassettes/TestRoutes.test_engage_index_with_preview_flag_sees_inactive_pages.yaml, tests/cassettes/TestRoutes.test_engage_index_without_preview_flag_cannot_see_inactive_page.yaml, tests/test_routes.py, webapp/app.py, webapp/views.py
- Reduce size engage pages https://github.com/canonical-web-and-design/ubuntu.com/issues/10299
These engage pages are most active, so they don't want us to put it in an archive section. Instead we are separating takeovers and engage pages, so the discourse post is reduced about half, this should ease the max limit (180000 characters), although in a year or so might need to be revisited as the number of engage pages grow again.
- Check the new source of [engage pages](https://discourse.ubuntu.com/t/test-engage-pages/18033) and [takeovers](https://discourse.ubuntu.com/t/test-takeovers/25642). This is the main issue this PR is trying to improve, the code is more complementary.
- Code is basically just refactoring. Moving to views.py with a new instance, since we are now using 2 separate …
=> Separate engage pages and takeover views

static/js/src/advantage/subscribe/blender/BuyButton.tsx, webapp/advantage/views.py, webapp/app.py
- Fix Blender redirects
Two places to check:
1. Check the thank you allows only guest users
- Go to: https://ubuntu-com-11000.demos.haus/advantage/subscribe/blender/thank-you
- If you are logged in it will redirect you to /advantage otherwise you will see the thank you page
2. Logged in user without purchase account gets redirected to /advantage
- Create a fresh UO account
- Login at: https://ubuntu-com-11000.demos.haus?test_backend=true
- Buy a blender product at https://ubuntu-com-11000.demos.haus/advantage/subscribe/blender?test_backend=true
- The modal will show you the 1st step of the purchase flow
- One you click buy, you will be sent directly to /advantage instead of the thank you page
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/428
=> Fix Blender redirects

webapp/advantage/schemas.py, webapp/advantage/views.py, webapp/app.py
- Create offer endpoint
- Tricky to QA without front-end. I use Postman with the cookie capture feature, but CURL works too:
```
curl --location --request POST 'https://ubuntu-com-11023.demos.haus/advantage/offer?test_backend=true' \
--header 'Content-Type: application/json' \
--header 'Cookie: <browser-cookie>' \
--data-raw '{
"marketplace": "canonical-ua",
"offer_id": "asd",
"account_id": "asd"
}'
```
- It should return 200.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/432
=> Add buy offer endpoint

navigation.yaml, templates/internet-of-things/contact-us.html, templates/internet-of-things/iot-management.html, templates/internet-of-things/management.html, templates/internet-of-things/thank-you.html
- Build `/internet-of-things/iot-management` page
- Add `IoT Management` on secondary navigation
- Update contact form
- Please check page against [copy doc](https://docs.google.com/document/d/1C-1ywVzBHkc4I3f-G7Rpy-epaXdbPisbolHUC1Jb7cE/edit#) 
- Please refer to this [brief](https://docs.google.com/document/d/1ENKan1AIRTkzdARyYYE6U9lW1jhw5sRVY76GKrRRa2Y/edit) and [doc](https://docs.google.com/document/d/1Se-fD5hhb7EaR75jd_1D-JkADmg6aLjUs7_bScATvwE/edit#) for contact form 
Fixes [#4671](https://github.com/canonical-web-and-design/web-squad/issues/4671) & …
=> Build /iot-management page

templates/tutorials/index.html, webapp/views.py
In the issue, the topic "development" isn't returning any results, because the authors writing those tutorials haven't used this topic and the list showing in the dropdown is a static list (authors may add or remove topics and the front-end doesn't know)
Therefore, to definately solve this issue, I compiled the list of topics directly from all the tutorials, so we will always have an up to date list.
- Check https://ubuntu-com-11024.demos.haus/tutorials
- Open the topics dropdown to find a new up to date generated list of topics (you can compare with current https://ubuntu.com/tutorials)
- You can check that every single topic contains at least one tutorial
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/6841
[QA …
=> Generate dynamic list of topics for dropdown

templates/engage/shared/_ru_engage_form.html, templates/engage/shared/_ru_thank-you.html
Add form and thank you page for engage pages in Russian
- Check /engage and click on the Engage page in Russian language
- Boom it should work now, with form and thank you in English language (until we can get the translation)
- Make sure the form works, and you can reach the thank you page and download the whitepaper
=> Support for engage pages in Russian language

tests/advantage/fixtures/offers.json, tests/advantage/test_api.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/views.py, webapp/app.py
Add endpoint to surface users purchase account linked offers
- Create an offer using the contracts API
- Go to http://0.0.0.0:8001/advatage/offers and check the offer
=> Add endpoint to surface users purchase account linked offers

templates/security/index.html
- Update links on `/security`
- Please compare against this [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit) and check the links are correct.
=> Update links on /security

templates/openstack/tutorials.html
**BLOCKED:** waiting on a link to the cheat sheet to be provided here: https://github.com/canonical-web-and-design/brand-squad/issues/610
- Updated the openstack tutorials list with a CTA link to a cheat sheet, per the [copy doc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#)
- View the demo in your web browser at: https://ubuntu-com-11017.demos.haus/openstack/tutorials
Fixes [#4663](https://github.com/canonical-web-and-design/web-squad/issues/4663)
=> Add cheat sheet CTA to openstack tutorials

templates/engage/base.html
Add support for vimeo embeded videos in engage pages
- Go to https://ubuntu-com-11031.demos.haus/engage 
- Click on the first "Test Vimeo on engage pages" engage page.
- Make sure that the video displays and plays.
Here is the [test topic](https://discourse.ubuntu.com/t/test-engage-pages-and-takeovers/25747) index used
Here is the [engage page](https://discourse.ubuntu.com/t/test-vimeo-videos-on-engage-pages/25751) you'll see the new `vimeo_id` there
Because this is using test engage pages, the topic id must be replaced with the production one before merging and deploying, that's why tests are failing
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11021 …
=> Add Vimeo to engage pages

tests/advantage/test_helpers.py, webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py
- Legacy user subscription need to be renewable 90 before and after expiry date: so is_expiring starts 90 days before expiry date and grace period ends 90 after expiry date
- Legacy user subscriptions are listed 90 (of grace period) + 30 days = 120 after expiry
Before:
- Login with an account that can view as on https://ubuntu.com?test_backend=true
- Check on https://ubuntu.com/advantage?test_backend=true&email=albert.kolozsvari%2Btester26%40canonical.com
- Tester26 has a legacy subscription that has expired more than 30 days ago so it's not listed at all
- Check on https://ubuntu.com/advantage?test_backend=true&email=albert.kolozsvari%2Btester27%40canonical.com
- Tester27 has a legacy subscription that has more than 30 days ago until expiry so there is no warning at all
After:
- Login …
=> 90 +- days to renew

static/js/src/PurchaseModal/hooks/registerPaymentMethod.tsx, static/js/src/PurchaseModal/hooks/usePostCustomerInfoForPurchasePreview.tsx, static/js/src/advantage/countries-and-states.js
:warning: Don't merge until @alnvdl says it's good to go (should be on Wednesday) :warning: 
- Added `ZA` to the list of VAT countries
- Check if the country is ZA to set the type as `za_vat` instead of `eu_vat`
- Go to https://ubuntu-com-11038.demos.haus/advantage/subscribe?test_backend=true
- select a product and click buy
- select "South Africa" as your country
- fill in the VAT code with `4220122222`
- see that if can get the preview and make a purchase correctly
Fixes canonical-web-and-design/commercial-squad#443
=> Add VAT option for South Africa

webapp/advantage/ua_contracts/helpers.py
- If `renewal.actionable` is `null`, then the value of the `statuses.renewal_is_actionable` is `null`. It should default to `False` instead. 
- Login with your account that has view as permissions: https://ubuntu-com-11036.demos.haus/advantage?test_backend=true
- View as https://ubuntu-com-11036.demos.haus/advantage?test_backend=true&email=albert.kolozsvari%2Btester16@canonical.com you should see the renewal button
- View as https://ubuntu-com-11036.demos.haus/advantage?test_backend=true&email=albert.kolozsvari%2Btester19@canonical.com you will not see the renewal button
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/442
=> If actionable is null make it false

templates/core/stories.html
- Updated page as per [copy doc](https://docs.google.com/document/d/1mXnYnpaCJznDLtYn9Q74aVeEI3iFxVOMzF0pdL7wdu0/edit)
- View the site locally in your web browser at: https://ubuntu-com-11058.demos.haus/core/stories
- Check against copy doc and see that all changes are there
- Test link and see that it works as expected
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4724
=> Added Screenly section

templates/internet-of-things/management.html
Add "y" to "A technical introduction to the Snap Store Prox" webinar link.
- Check the code is good
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11069
=> Fix typo on iot/management page

templates/certified/model-details.html, webapp/certified/views.py
Display hardware details specific to each certificate rather than displaying one set of hardware details for all.
note: it's the Friday before winter break, so you may want to wait on merging this on the off chance it breaks anything before everyone goes on break.
This updates the view so that it collects hardware info per certificate rather than grabbing the most recent certificate's hardware details to display everywhere.
- View https://ubuntu-com-11076.demos.haus/certified/201809-26501
- verify that the first certificate shows _Intel(R) Xeon(R) Platinum 8276 CPU @ 2.20GHz_ as the processor.
Fixes #11074
=> use hardware details per certified entry

static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/RenewButton.tsx, static/js/src/advantage/subscribe/blender/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
- Replace `leadCapture/save2` with the marketo endpoint
- Please check the submission is working properly on `/advantage/subscribe`
Fixes [#4733](https://github.com/canonical-web-and-design/web-squad/issues/4733)
=> Replace `leadCapture/save2` with the marketo endpoint

templates/core/smartstart/guide/app-store-commissioning.md
- Adds link to IoT data sheet in 'App store commissioning'
- View the site locally in your web browser at: http://0.0.0.0:8001//core/smartstart/guide/app-store-commissioning
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11061
=> Add link to IoT data sheet in 'App store commissioning'

templates/model-driven-operations/index.html
- Use the adjusted "Why use Juju" diagrams for Jaas.ai provided by @waynecrosby 
=> /model-driven-operations: Add "Why use Juju" diagrams

templates/core/smartstart/guide/app-store-commissioning.md
- Updated list of resources according to changes in the [copy doc](https://docs.google.com/document/d/15WmVD7i1nZ8ntQjDKhEcBymaEAdTyqH4yrM62r0VIsM/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/core/smartstart/guide/app-store-commissioning
- See that the list of resources at the end of the guide matches that of the copy doc, and that the links work
=> Update resource links on app store commissioning guide

templates/templates/docs/shared/_docs.html
- Add the version switcher conditionally to the docs template.
- Go to /server/docs
- Check the version switcher is there.
- Check the version switcher works
- Check different screens sizes work and look ok
- Check navigating just using the keyboard
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11109
=> Add version switcher to the docs template

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/PurchaseModal/hooks/registerPaymentMethod.tsx, static/js/src/advantage/subscribe/react/app.tsx
- Remove the explicit instruction to ignore VAT validation. :thinking: 
I can't remember why this was done. I tried most journeys, they still work as expected.
- go to https://ubuntu-com-11040.demos.haus/advantage/subscribe?test_backend=true as a guest or with a brand new SSO account
- select a product
- Fill in the details
- Select a country where VAT is applicable (eg. UK)
- input `GB123` as the VAT number
- Click next
- it should fail with an error telling you to fix the VAT number
=> Second step of the modal is reached even if setting customer info fails

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
Show a label saying a subscription is not editable when they are not.
- View the site locally in your web browser at: http://0.0.0.0:8001/advantage?test_backend=true
- Check a subscription that was purchased on offer and make sure it displays `This subscription cannot be edited online.`
=> UA Shop: Add label to subscriptions that are not editable

templates/engage/shared/_ru_engage_form.html, templates/engage/shared/_ru_thank-you.html
*This PR is for the two issues listed below*
https://github.com/canonical-web-and-design/web-squad/issues/4659
https://github.com/canonical-web-and-design/web-squad/issues/4659
- Adds an engage form in Russian
- Adds thank you page in Russian
1 . http://0.0.0.0:8001/engage/сравнение-платформ-red-hat-openstack-canonical-charmed-openstack or https://ubuntu-com-11103.demos.haus/engage/сравнение-платформ-red-hat-openstack-canonical-charmed-openstack
2 .  http://0.0.0.0:8001/engage/сравнение-платформ-kubernetes or https://ubuntu-com-11103.demos.haus/engage/сравнение-платформ-kubernetes
- Check …
=> Create Russian translation for engage form and thank you

.env, .github/workflows/a11y.yaml, .github/workflows/cypress-main.yaml, .github/workflows/cypress-pr.yaml, .github/workflows/pr.yaml, requirements.txt
- After merging a large batch of dependency updates (https://github.com/canonical-web-and-design/ubuntu.com/pull/11081), we ran into a number of issues with the dependency update on sqlalchemy while building the Jenkins job on staging:
- [AttributeError: 'BaseFilterQuery' object has no attribute '_mapper_zero](https://pastebin.canonical.com/p/gQ7cmw6sq6/) when trying to view /security/cve
- We realised we needed to update a secret in k8s to use the new URL format, `postgresql://` rather than `postgres://`
The first issue needs more investigation, so this is to unblock deploys until we can make time for that.
- Checks should pass.
=> Roll sqlalchemy to back to 1.3.23

static/js/src/cube/components/CubeBuyButton/CubeBuyButton.tsx, static/js/src/cube/components/CubePurchaseModal/CubePurchaseModal.tsx
- Add marketing opt-in terms to the purchase modal
- Submit the Marketo form on purchase
- Run the server with `dotrun`
- Go to http://localhost:8001/cube/microcerts?test_backend=true
- Click the "Buy now" button and enter payment info to get to step 2 of the purchase modal
- Verify that the marketing opt-in checkbox appears and is functional
- Complete the purchase
- Verify in Marketo that the settings have been updated (Morgan can check for you)
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/426
=> Add marketing opt-in and Marketo form for CUBE purchases

templates/model-driven-operations/index.html
- Change screenshot for JAAS as the one we currently have live refers to a UI that is deprecated.
Fixes #
=> /model-driven-observability: Update JAAS screenshot

templates/cloud/private-cloud.html
- Replaced the Ubuntu Server card at the bottom of the page with a card about MAAS, as detailed in the [copy doc](https://docs.google.com/document/d/19g24YRYzF5dBpUKI1QzTG7fXKj1z0OvwgFll69dFoOs/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/cloud/private-cloud
- See that the card at the bottom of the page matches the [copy doc](https://docs.google.com/document/d/19g24YRYzF5dBpUKI1QzTG7fXKj1z0OvwgFll69dFoOs/edit#)
Fixes [#4755](https://github.com/canonical-web-and-design/web-squad/issues/4755)
=> Replace Ubuntu Server section on /cloud/private-cloud with MAAS section

tests/advantage/test_parsers.py, webapp/advantage/models.py, webapp/advantage/ua_contracts/parsers.py
- Add account id to offers endpoint
- login using the demo or pull changes
- Login with an account that has offers
- go to /advantage/offers.json 
- You will see account id
=> Add account ID to offers

tests/advantage/test_helpers.py, webapp/advantage/models.py, webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py
- Add `current_number_of_machines` as a property of the `user_subscription`. This value is the actual number of machines the user will have starting with the next billing cycle. It should also be used as the pre-filled value in the edit number of machines field.
- Go to https://ubuntu-com-11110.demos.haus or check out this feature branch 
- Do you have a stripe subscription that you can down-sell? If no, buy one.
- Down-sell the user subscription; you might have to manually refresh the page, as the front-end is not fully supporting the new kind of resizing
-  On /advantage you will still see the old value of machine numbers (as until the end of the billing period it won't change), but on /advantage/user-subscriptions you will see a new property called `current_number_of_machines` which …
=> Surface actual number of machines

templates/robotics/community.html
- Updated the community news video on /robotics/community according to the [copy doc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit)
- See that the video that accompanies the "Keep up on the State of Robotics" section is from December, not November
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4759
=> Update robotics community news video

templates/certified/why-certified.html, webapp/app.py, webapp/certified/views.py
**BLOCKED:** waiting on a link to the data sheet 
- Build page on `/certified/why-certified`
-Please check page against [copy doc](https://docs.google.com/document/d/1q3rOtDgJ_7_seGCP5pbCKyJYzXLvY45y8gis2FSKxXI/edit#)
- Demo at https://ubuntu-com-11132.demos.haus/certified/why-certified
Fixes [#4728](https://github.com/canonical-web-and-design/web-squad/issues/4728)
=> Build page on /certified/why-certified

templates/certified/index.html, templates/certified/search-results.html, tests/cypress/integration/certified_spec.js
**BLOCKED:** The`certified/why-certifed` page ([issue](https://github.com/canonical-web-and-design/web-squad/issues/4728)) needs to be merged first 
- Rebuild page on /certified
- The image in the last section needs to be updated. 
- Please check page against [copy doc](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#) 
- Demo at https://ubuntu-com-11118.demos.haus/certified
Fixes [#4697](https://github.com/canonical-web-and-design/web-squad/issues/4697)
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/q …
=> Rebuild page on /certified

templates/security/fips.html
- Updated /security/fips with a new webinar and copy changes from the [copy doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit#heading=h.335zx3wyom0b)
- View the site in your web browser at: https://ubuntu-com-11148.demos.haus/security/fips
- See that the page matches the [copy doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit#heading=h.335zx3wyom0b)
Fixes [#4776](https://github.com/canonical-web-and-design/web-squad/issues/4776)
=> Update /security/fips copy

templates/ceph/managed.html, templates/ceph/what-is-ceph.html, templates/shared/_resources_ceph.html
- Update webinar link on `/ceph`, `/ceph/consulting`, `/ceph/managed` and `/ceph/what-is-ceph`
- Please check page against copy doc and and resolve comments
- https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit
- https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/edit
- https://docs.google.com/document/d/1Ff3TDYBsukagu85dNZuK0FDdPRSjXEwS6Tv6JphXUvY/edit
- https://docs.google.com/document/d/1LK8mut0O30Zk60mmbgCPFiQ2COR-BUnJnbASMMdyycU/edit 
- Demo
- https://ubuntu-com-11153.demos.haus/ceph
- https://ubuntu-com-11153.demos.haus/ceph/consulting
- …
=> Update webinar link on /ceph pages

navigation.yaml
Add /why-certified to bubble menu
- Check https://ubuntu-com-11155.demos.haus/certified contains the bubble menu
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4771
=> Add why-certified link to menu

templates/kubernetes/docs/1.23/charm-azure-integrator.md, templates/kubernetes/docs/1.23/charm-calico.md, templates/kubernetes/docs/1.23/charm-containerd.md, templates/kubernetes/docs/1.23/charm-docker.md, templates/kubernetes/docs/1.23/charm-kubernetes-master.md, templates/kubernetes/docs/1.23/charm-kubernetes-worker.md, templates/kubernetes/docs/1.23/charm-openstack-integrator.md, templates/kubernetes/docs/1.23/charm-tigera-secure-ee.md, templates/kubernetes/docs/1.23/components.md, templates/kubernetes/docs/charm-azure-integrator.md, templates/kubernetes/docs/charm-calico.md, templates/kubernetes/docs/charm-containerd.md, templates/kubernetes/docs/charm-docker-registry.md, templates/kubernetes/docs/charm-docker.md, templates/kubernetes/docs/charm-kubernetes-master.md, templates/kubernetes/docs/charm-kubernetes-worker.md, templates/kubernetes/docs/charm-openstack-integrator.md, templates/kubernetes/docs/charm-tigera-secure-ee.md
- removed blank lines causing tables not to render on some pages
- removed component links for charms not specifically accessible in CharmHub (which also removes some breaking links)
=> K8s doc fixes

static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.test.tsx, static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx, static/js/src/advantage/react/hooks/useURLs.ts
Added a notification on /advantage to let users know if they have offers available 
- go to https://ubuntu-com-11159.demos.haus/advantage?test_backend=true
- log in with an account that has offers available
- check that the notification displays correctly
- click the link
- check that it takes you to the offers page
=> Add notification on /advantage if offers are available

templates/download/raspberry-pi/index.html
- Ubuntu 21.04 is now out of support, so this is to remove it from the Raspberry Pi downloads.
- I also updated the copy doc
=> Remove 21.04 from /download/raspberry-pi

konf/site.yaml, navigation.yaml, redirects.yaml, templates/legal/ubuntu-advantage-service-description/index.md, templates/legal/ubuntu-advantage-service-description/ja/index.html, templates/security/cve/cve.html, templates/security/docker-images.html, templates/security/notices/usn.html, templates/sitemap_index.xml, templates/templates/navigation-developer-h.html, webapp/app.py, webapp/security/views.py
- Remove unused /security/api/notices endpoints
- Tidy up routing of /security section
- Only route /security/notices and /security/cves to `ubuntu-com-security` service - this is because I want to isolate specifically the security database logic in this service, so problems with the database can be seen very clearly and won't effect other areas.
- Route /security/certifications/docs to `ubuntu-com-discourse` (like other docs)
- change /security/cve URL to /security/cves
- This is to match the API (/security/cves.json) and because all our other URLs follow this plural scheme, as well as this being the recommendation in [Web API Design](https://robinwinslow.uk/api-design-ebook-2012-03.pdf).
Can't really QA the k8s routing stuff, we have to put that on a k8s platform first. But you can QA …
=> Tidy up security routing

templates/ai/services.html, templates/automotive/index.html, templates/aws/index.html, templates/azure/index.html, templates/base_index.html
- Updated the logo section with the [new Vanilla logo section pattern](https://vanillaframework.io/docs/patterns/logo-section) on:
- homepage
- /aws
- /azure
- /automotive
- /ai/services
There will be a few of these PRs to come, there are logo sections all over the project that need updating, and would make for one massive PR otherwise.
Also - I used VSCode's auto indent tool to help me out while pasting in the many new logo image templates, it made unrelated indent adjustments in a number of places throughout the files that were updated.
- View the site at https://ubuntu-com-11184.demos.haus
- See that the logo sections look good
- Do the same for:
- https://ubuntu-com-11184.demos.haus/aws
- …
=> Logo section update - part 1

webapp/advantage/decorators.py, webapp/advantage/views.py, webapp/app.py
- Send people to login if hitting /advantage/offers logged out
- use demo
- go to /advantage/offers?test_backend=true
- it will redirect you to login with staging account and then send you back to /advantage/offers?test_backend=true
- do the same but without the test flag, it should work the same
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/471
=> Adjust offer redirect

static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/js/src/advantage/react/utils/getNextCycleStart.test.ts, static/js/src/advantage/react/utils/getNextCycleStart.ts, static/js/src/advantage/react/utils/index.ts
- Updated the interactive copy when user change the number of machine according to the design:
- Log in on [/advantage](https://ubuntu-com-11179.demos.haus/advantage?test_backend=true)
- click edit on a monthly subscription
- change the number of machines up and down
- check that it matches the design
Fixes canonical-web-and-design/commercial-squad#474
=> Update diff explaining copy

static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
- Only display "You will pay now $X" if the user will actually pay as a result of the resize
- Display the correct amount in the pay now paragraph if the user has downsized their subscription during the same cycle
- Go to [/advantage](https://ubuntu-com-11189.demos.haus/advantage?test_backend=true)
- log in with an account that has a monthly subscription
- downsize it
- the resize it again but up this time
- check that it states that you will pay when you click on resize only for an amount of machines greater than what you had initially
=> Fix "Pay now" display for resizes

webapp/views.py
Fix `KeyError: 'email'`
- Sentry error points to this engage page https://ubuntu.com/engage/wellcome-sanger-case-study as the referrer, but it probably will not fail even without this check.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11143
=> Fix email keyerror in marketo forms

templates/appliance/shared/_steps_pi_imager_macos.html, templates/appliance/shared/_steps_pi_imager_ubuntu.html, templates/appliance/shared/_steps_pi_imager_windows.html
- Fixed broken links to Raspberry Pi imager tools for each OS
- View the site locally in your web browser at: http://localhost:8001/appliance/plex/raspberry-pi2#macos
- Under "Installation Instructions", check that the link in Step 1 of each OS tab works
Fixes #11180
=> Update broken RPi imager download links

static/js/src/chart.js, static/js/src/tabbed-content.js, templates/about/release-cycle.html
- Refactored /about/release-cycle content into tabs, according to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
- View the site locally in your web browser at: https://ubuntu-com-11162.demos.haus/about/release-cycle
- See that the content of the page is now in tabs, and that the tabs work as expected
- Visit:
- https://ubuntu-com-11162.demos.haus/about/release-cycle#ubuntu
- https://ubuntu-com-11162.demos.haus/about/release-cycle#ubuntu-kernel-release-cycle
- https://ubuntu-com-11162.demos.haus/about/release-cycle#openstack-release-cycle
- …
=> Refactor release cycle page into tabbed content

templates/certified/index.html, webapp/certified/views.py
- Add "HPE", "Lenovo" and "Dell" vendor links to server block on /certified
- Drive by: added missing names to search action buttons
- View the site locally in your web browser at: https://ubuntu-com-11199.demos.haus/certified
- See that "Ubuntu certified servers" contains 3 vendor links, which all work
Fixes #9828
=> Add "HPE", "Lenovo" and "Dell" vendor links to server block on /certified

templates/certified/index.html
- Fixed "Ubuntu certified" case on /certified
- Numerous small grammar tweaks requested in the [copy doc](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#)
- See that the word "certified" is only capitalised in the page heading, and that the comments in the copy doc have been addressed.
=> Fix "Ubuntu certified" case on /certified

templates/advantage/index-no-login.html, templates/advantage/index.html
- Removed the beta invite from the top of /advantage
- Go to https://ubuntu-com-11202.demos.haus/advantage
- check that the beta invite is gone
- log in
- check that it's still gone
Fixes #11196
=> drop the beta invitation from /advantage

templates/legal/ubuntu-advantage-service-description/_toc.html
Fix typo in UA service description legal page
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/ubuntu-advantage-service-description
- Make sure the typo is corrected
Fixes #11181
=> Fix typo in UA service description legal page

templates/security/cve/_pagination.html
- Fixes pagination on cve search to correctly display the available pages and use the appropriate offset.
- **Note** won't work in demos, you will need to run locally. If you need help setting up a local CVE database reach out to me or Albert. 
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cve or https://ubuntu-com-11208.demos.haus/security/cve
- Check the pagination work, and that no number are skipped.
- Hover your mouse over every pagination button and make sure the offset is correct.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11188
=> Fix CVE pagination

.gitignore, requirements.txt, scripts/generate-sample-security-data.py, webapp/security/database.py
We run the site with Gunicorn's [gevent workers](https://docs.gunicorn.org/en/latest/design.html#async-workers). This means all parts of the code must be [compatible](https://stackoverflow.com/questions/23278482/compatibility-of-gevent-with-other-packages) with gevent's coroutines.
Psycopg2 is [not natively compatible](https://www.psycopg.org/docs/advanced.html#support-for-coroutine-libraries) with gevent coroutines, and so by default separate gevent threads making database calls will block each other leading to sub-par performance.
This commit patches psycopg2 with psycogreen, so that database calls can be made concurrently by separate gevent threads.
https://github.com/psycopg/psycogreen/
https://gist.github.com/pawl/0f0d87e7ee42f0a8eaf28f0d13629674
1. Pull down this branch and run it …
=> Patch psycopg2 (for SQLAlchemy) with psycogreen

entrypoint
The big question is - why 3? Well, there's quite a lot going on there.
Why 1 worker up to now?
---
Firstly, the reason we were running only 1 worker up to now was because of two misconceptions on my part:
1. That Docker containers are supposed to only have 1 process per container, as mentioned in [this SO answer](https://stackoverflow.com/a/51873337)
2. That gevent workers elastically create new workers as needed
Both of these are wrong, because:
1. The real point of the Docker container advice is not to run more than one *service* or *function* per container, and the official guidance wording has since been updated, as mentioned in [this SO answer](https://devops.stackexchange.com/a/451).
2. Gevent threads are not at all the same thing as workers (read about the [different sorts of …
=> Run the site with 3 gunicorn workers

templates/security/cve/_pagination.html
- Fixes a bug with the pagination on /certified search 
- View the site locally in your web browser at: http://0.0.0.0:8001/certified or https://ubuntu-com-11214.demos.haus/certified
- Go to /certified, try and search in the search bar near the top of the page.
- Check pagination behaves appropriately when changing pages and with different amounts of results.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11188
=> Fix /certified pagination

templates/azure/index.html
- Adding an anchor on the "Choose the right Ubuntu" section to help with a marketing campaign
- Ensure /azure#standard-pro takes you down the page
=> Adds #standard-pro anchor to /azure page

static/js/src/PurchaseModal/components/PaymentMethodForm.tsx, static/js/src/PurchaseModal/hooks/useStripeCustomerInfo.jsx, static/js/src/navigation.js
- If we can't fetch Stripe data, fall back on `account.json` to prepopulate the name and email fields
- disable email field if it was prepopulated 
- Go to [/advantage/subscribe](https://ubuntu-com-11205.demos.haus/advantage/subscribe?test_backend=true)
- Log in with a brand new SSO account
- your name and email should be prepopulated, email field should be disabled
- Log in with an account that already has made a purchase
- the same should happen
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/299
=> Disabe email field if it was prepopulated

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx, tests/shop/advantage/test_helpers.py, webapp/shop/api/ua_contracts/builders.py, webapp/shop/api/ua_contracts/helpers.py
- Change is cancelled condition. A stripe subscription is cancelled if the `current_number_of_machines` is 0.
- Login using current code https://ubuntu.com/?test_backend=true
- Have a monthly subscription
- Cancel it
- You will be allowed to edit subscription anymore
- Login using demo
- Have a monthly subscription
- Cancel it
- You will be allowed to edit subscription anymore
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/482
=> Change is cancelled condition

templates/aws/pro.html, templates/azure/pro.html, templates/gcp/pro.html
- Updated /azure/pro, /aws/pro and /gcp/pro:
- Moved the strip that was originally third on the page (featuring the "Launch now" CTAs) to second on the page.
- Inverted the colours of the strips below so the delineation between each is the same as it was previously
- View the site in your web browser at: 
- https://ubuntu-com-11240.demos.haus/aws/pro
- https://ubuntu-com-11240.demos.haus/azure/pro
- https://ubuntu-com-11240.demos.haus/gcp/pro
- See that the changes match the copy doc
Fixes:
- https://github.com/canonical-web-and-design/web-squad/issues/4813
- https://github.com/canonical-web-and-design/web-squad/issues/4814
- https://github.com/canonical-web-and-design/web-squad/issues/4815
=> Update /pro pages

templates/kubernetes/docs/install-offline.md, templates/kubernetes/docs/monitoring.md
Some very minor updates
- Fixes some broken links for updated juju docs
-  adds a note on monitoring
=> K8s docs link fixes

static/sass/_global-settings.scss, static/sass/styles.scss, templates/engage/index.html
- Enabled display of cyrillic characters
- Added Russian ("Русский") as an option in the /engage index
- Select "Русский" from the language dropdown, there should be four results
- Click any of them, the font on the engage page should look a lot better than it does on the live site, and the font family being used should be "UbuntuFullCharSet".
- Go to a non Russian engage page, inspect the text, the font family should be "Ubuntu"
Before:
After:
=> Russian engage pages

static/sass/_pattern_subscriptions.scss
- prevented the subscription detail from overlapping the meganav
- go to https://ubuntu-com-11248.demos.haus/advantage
- open the meganav, it should display correctly
- switch to a small viewport size
- click on a subscription, it should display correctly
Fixes #11121
=> Fix content overlapping meganav

static/js/src/advantage/api/contracts.js, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/usePreviewResizeContract.ts
- Added a resize preview call to the contracts API file
- created a hook that calls the preview endpoint on quantity change
- displays the correct (incl taxes) amount that will be charged when the user clicks "Resize"
- go to [/advantage](https://ubuntu-com-11215.demos.haus/advantage?test_backend=true)
- log in with an account that has a monthly subscription
- resize it up and down and up again and check that the correct amount is displayed each time
Fixes canonical-web-and-design/commercial-squad#488
=> Call preview for resizes

templates/shared/_cube-contact-us-form.html, tests/cypress/forms/forms_spec.js
- Fix `/cube/contact-us` cypress test in `/forms_spec.js`
- Please do `context.skip` or `it.skip` to save time and avoid making a bunch of spam submission
- Move the `/tests/cypress/forms/forms_spec.js` file to the `/tests/cypress/integration` folder
- Open another terminal and run `yarn run cypress:open`
- Click `forms_spec.js` in the cypress test window
- Check the test for the `/cube/contact-us` passes
Fixes #
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices …
=> Fix /cube/contact-us cypress test

templates/cube/index.html, templates/shared/forms/interactive/cube-beta.html, tests/cypress/forms/forms_spec.js
-Fix cube interactive form cypress test
- Please do `context.skip` or `it.skip` to save time and avoid making a bunch of spam submission
- Move the `/tests/cypress/forms/forms_spec.js` file to the /tests/cypress/integration folder
- Open another terminal and run yarn run cypress:open
- Click forms_spec.js in the cypress test window
- Check the test `interactive contact modal on /cube` passes
Fixes #
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/comm …
=> Fix cube interactive form cypress test

.env, .github/workflows/a11y.yaml, .github/workflows/cypress-main.yaml, .github/workflows/cypress-pr.yaml, .github/workflows/pr.yaml, docker-compose.yaml, requirements.txt
- Made pg db accessible without a password 
- Ensure migrations run as expected
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11258
=> Remove auth from pg db

templates/security-error.html, templates/security/cve/cve.html, webapp/app.py, webapp/security/api.py, webapp/security/views.py
- Wrote api class with functionality for get requests to security api (cve and releases)
- Refactored views to consume api 
- Refactored template to comply with new data format 
- Added an error page to offer more clarity when api is down 
**NOTE: Must be merged after https://github.com/canonical-web-and-design/ubuntu-com-security-api/pull/75** 
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cves
-Click on any cve and check that table renders correctly
Fixes https://github.com/canonical-web-and-design/master-epics/issues/402, https://github.com/canonical-web-and-design/ubuntu.com/issues/11253
=> Add api class to consume security api

templates/managed/apps/index.html
fix complaint/compliant typo on /managed/apps
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/apps
- See that the typo in the copy doc has been fixed: https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit
=> fix complaint/compliant typo

templates/security/fips.html
In templates/security/fips.html:
- Update modules table to include a Bionic kernel recertification (FIPS module 4018) that had been omitted.
- Change grammar in the "FIPS 140-3 and Ubuntu" section -- September 2021 has passed.
Relates to #11068
=> [security/fips] Add recert module, update 140-3 grammar.

templates/engage/index.html
Co-authored by: Adolfo Jayme-Barrientos <fito@libreoffice.org>
- Fixed a wrong entity for “ñ”
This was originally QAd in [this PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11262) before I rebased it with the flask-base update (which was causing the build to hang), force pushed to the branch and somehow lost the original commit.
=> Engage: Fix spelling of “Español” in language selector

build.js, static/js/src/utm-inheritance.js, templates/azure/index.html, templates/azure/pro.html
- Added the ability to persist UTM campaign parameters on links to the Azure Marketplace from our Azure pages
- View the site in your web browser at: 
- https://ubuntu-com-11274.demos.haus/azure?OCID=7014K000000UZtoQAG&utm_source=linkedin_ad&utm_medium=banner&utm_campaign=7014K000000UZtoQAG&utm_content=q1_2022
- https://ubuntu-com-11274.demos.haus/azure/pro?OCID=7014K000000UZtoQAG&utm_source=linkedin_ad&utm_medium=banner&utm_campaign=7014K000000UZtoQAG&utm_content=q1_2022
- See that any links to azuremarketplace.com include the `OCID`, `utm_campaign`, `utm_source`, `utm_medium` and `utm_content` parameters, and any other links do not.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4839
=> Add UTM inheritance script, apply to Azure marketplace links

static/js/src/utm-inheritance.js, templates/16-04/azure.html, templates/16-04/index.html, templates/azure/fips.html, templates/azure/index.html, templates/azure/pro.html, templates/cloud/hybrid-cloud.html, templates/cloud/multi-cloud.html, templates/cloud/public-cloud.html, templates/security/fips.html, templates/shared/_ubuntu_pro_on_public_cloud.html
- The sequel to https://github.com/canonical-web-and-design/ubuntu.com/pull/11274
- @malina-i was given a [guide on how to implement campaign tracking](https://docs.google.com/document/d/1wMJvS_IzbxH3s61fh1WyszdZ0KVX-CE5BAc9nvaFvnA/edit) for Azure Marketplace links, including removing `tab=Overview` from existing links e.g.
- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-pro-bionic?tab=Overview
- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-pro-bionic
Both links lead to the same place, so this PR cleans up all such links across the project.
- Visit:
- https://ubuntu-com-11275.demos.haus/16-04/azure
- …
=> Remove `tab=Overview` from Azure Marketplace links

tests/cassettes/TestCertification.test_vendor_pages.yaml, tests/test_certification.py
- Updated vendor test to make a request to /certified/vendors/HP, rather than /certified/vendors/Dell (Dell seems to have been removed from the partners API)
- See that all the checks pass
=> Fix vendor test to request a vendor that currently exists

templates/telco/index.html
- added an MWC banner to /telco
- View the site in your web browser at: https://ubuntu-com-11282.demos.haus/telco
- See that the banner matches the [design](https://github.com/canonical-web-and-design/web-squad/issues/4832)
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/4833
=> add MWC banner to /telco

templates/azure/private-offer.html, templates/azure/shared/_azure-logo-strip.html, templates/azure/shared/_how-ubuntu-pro-helps-you.html
- Updated /azure/private offer according to the [design](https://github.com/canonical-web-and-design/web-squad/issues/4808#issuecomment-1039029837) and the [copy doc](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit#)
- this page was [originally part of a PR](https://github.com/canonical-web-and-design/web-squad/issues/4823) that included another, related page featuring an ebook download, but we're still waiting on the ebook asset, so I've created a new PR to unblock this page. I've added the Design +1 label, as it was given there, and the design hasn't changed in the process of creating this PR.
- View the site locally in your web browser at: https://ubuntu-com-11285.demos.haus/azure/private-offer
- Be sure to test on mobile, tablet and desktop screen …
=> Update azure private offer page

releases.yaml
- Bump the point release from 20.04.3 to 20.04.4
- Check the file names and checksums match the ones in [the issue](https://github.com/canonical-web-and-design/web-squad/issues/4841#issuecomment-1049688375).
- Visit:
- https://ubuntu-com-11281.demos.haus/download/desktop
- https://ubuntu-com-11281.demos.haus/download/server (and click Option 2)
- https://ubuntu-com-11281.demos.haus/download/raspberry-pi (scroll down to "Download Ubuntu Server")
- See that any links to download point to the links given in the issue
- **Note:** The download **won't** work yet
- Go to https://ubuntu-com-11281.demos.haus/download/alternative-downloads and see it says 20.04.4, not 20.04.3
Fixes [#4841](https://github.com/canonical-web-and-design/web-squad/issues/4841)
=> Bump the point release to 20.04.4

templates/security/cve/cve.html
- Fixed empty href in bug section links 
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cves
- Click on any cve and check that the links in the "Bugs" section work as expected
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11278
=> Fix bug links

static/sass/_layout-tutorial.scss, static/sass/styles.scss, templates/advantage/table/_contract-name.html, templates/security/cve/_pagination.html, templates/shared/_pagination.html, templates/tutorials/tutorial.html
- Changed p-icon--contextual-menu to p-icon--chevron-down
- Select any tutorial
- See that the next/previous pagination icons are correct (compare them to live to confirm)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4862)
=> change p-icon--contextual-menu to p-icon--chevron-down
