templates/advantage/index.html, webapp/views.py
- Added a warning to /advantage if a user has monthly subs and the payment method is invalid
- Fixed the links to /subscribe so they keep the `?test_backend=true` parameter if it's present
[Design](https://app.zeplin.io/project/601d6513b99f24a8412ecfa5/screen/6024087b77a6eab466624106)
- Not sure how to QA that yet. @ me on mattermost so I can show you!
Fixes #3800
- The text wraps using the copy provided and the vanilla component.
If we remove the `.` then it fits, what should we do?
- The link is broken but will be implemented in https://github.com/canonical-web-and-design/ubuntu.com/pull/9248
=> Build warning payment issue

templates/support/index.html
- Copy updates for /support
- Compare to the [copy doc](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit?ts=6047d14b#)
Fixes #9371
=> Copy updates for /support

navigation.yaml
Fix typo on NextCloud navigaiton
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9380
=> Fix typo on NextCloud navigaiton

webapp/advantage/views.py
- Add `contract["product_listing_id"]`
=> Add contract product listing

webapp/advantage/views.py
- Change location of the parameter for the auto renewal endpoint.
=> Change auto renewal parameter location

webapp/advantage/views.py
=> Fix auto renewal status read

webapp/advantage/views.py
- Rename `subscriptions` to `monthly_information`.
- We keep `total_subscriptions` remove `current_subscriptions_no`
=> Adjust monthly info

templates/gov/index.html
Copy changes to `/gov`
- Check the copy on `/gov` matches the document.
Fixes #9392
=> Copy updates to '/gov'

webapp/advantage/views.py
=> Add contracts total

static/sass/styles.scss, templates/advantage/index.html, templates/advantage/shared/_certifications-info.html, templates/advantage/shared/_esm-info.html, templates/advantage/shared/_livepatch-info.html, templates/advantage/table/_attached-machines.html, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html
- Updated the table's dropdowns according to the [designs](https://app.zeplin.io/project/601d6513b99f24a8412ecfa5/screen/6036811573cb392a12077b84)
- go to https://ubuntu-com-9373.demos.haus/advantage?test_backend=true and check each tab on a subscription
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3878
and https://app.zenhub.com/workspaces/web--ubuntu-clan-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/3903
New:
machines
ESM
Livepatch
Certifications
=> Dropdown visual improvements

static/sass/_pattern_lists.scss, templates/templates/navigation-enterprise-h.html
- Change the copy according to #9433
- Use the demo to check the enterprise nav content matches what is in the copy.
- Make sure the middots on the nav list are aligned
Fixes #9433
=> 9433: Enterprise nav copy changes

static/sass/_pattern_contact-modal.scss, templates/shared/forms/interactive/bootstack.html, templates/shared/forms/interactive/support-openstack.html
Fixed fields overlapping in two forms:
- /openstack/managed#get-in-touch
- /pricing/consulting#get-in-touch
- Go to the demo and make sure the forms listed above don't ahve overlapping fields
Fixes #9318
=> 9318: Fix form fields overlapping

webapp/advantage/views.py
This is for us to determine if a user's selected item can be trialled or not.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3946
=> Add "can_be_trialled" prop to listings

templates/certification/index.html, webapp/certification/api.py, webapp/certification/views.py
Desktop, Server, Iot, SoC data for overview page
https://ubuntu-com-9442.demos.haus/certification should show all the data in json format
Fixes #https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/165
=> Overview page

templates/financial-services/_base_financial-services.html, templates/shared/forms/interactive/financial.html
- Add new financial modal contact us
- View the site locally in your web browser at: http://0.0.0.0:8001/financial-services#get-in-touch
- See that the form matches the [copy doc](https://docs.google.com/document/d/1iLmk4KdZ4-i6OU3K2btSETa72AKBH-iFPZqR_hg_zzQ/edit)
- Fill in the form and see that it submits
Fixes [#3938](https://github.com/canonical-web-and-design/web-squad/issues/3938)
=> Add new financial modal contact us

templates/16-04/index.html
16.04 page copy updates
- View the site locally in your web browser at: http://0.0.0.0:8001/16-04
- Check the copy changes are good
Fixes #9444
=> #9444: 16.04 page copy updates

templates/legal/ubuntu-advantage-service-description/index.md, templates/shared/pricing/_ua-for-infrastructure.html
Update copy on the site to match the changes marked as "Done" in the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit?ts=605dc3e3#)
- Check the code.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3966
=> Copy update to UA service description

templates/appliance/lxd/_next-steps.html
The command was missing the `config` part
- Check the code matches the issue
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9364
=> Fix the LXD set password command

templates/advantage/index.html, templates/advantage/subscribe/index.html
- updated meta tags on both /advantage and /advantage/subscribe to the correct copydocs
Fixes #3930
https://github.com/canonical-web-and-design/web-squad/issues/3930
=> fixes #3930

.github/workflows/ceph-docs-links.yaml, .github/workflows/core-docs-links.yaml, .github/workflows/kubernetes-docs-links.yaml, .github/workflows/server-docs-links.yaml
Add actions to check docs links for:
- ceph/docs
- server/docs
- kubernetes/docs
- core/docs/
- Check CI passes
=> Add actions to check docs links

static/js/src/advantage/auto-renewal.js, static/js/src/advantage/manage-subscription.js, templates/advantage/index.html
Add events as follow
```js
{
event: "GAEvent",
eventCategory: "Advantage",
eventAction: "set-auto-renewal",
eventLabel: "Save changes",
eventValue: undefined,
}
```
```js
{
event: "GAEvent",
'eventCategory' : 'Advantage',
'eventAction' : 'table-row-expand',
'eventLabel' : {{columnName}},
'eventValue' : undefined
}
```
```js
{
event: "GAEvent",
'eventCategory' : 'Advantage',
'eventAction' : 'table-row-collapse',
'eventLabel' : {{columnName}},
'eventValue' : undefined
}
```
```js
{
event: "GAEvent",
eventCategory: "Advantage",
eventAction: "cancel-subscription",
eventLabel: "Cancel subscription",
eventValue: undefined,
}
```
```js
{
event: "GAEvent",
eventCategory: "Advantage",
eventAction: "update-subscription",
eventLabel: "Save changes",
eventValue: undefined,
}
```
```js
{
event: …
```
=> Add GA events

webapp/decorators.py
=> Fix linting

templates/shared/forms/interactive/robotics_ros.html
Update the robotics interactive contact form
- Go to https://ubuntu-com-9505.demos.haus/robotics#get-in-touch
- Check the copy matches the [copy doc](https://docs.google.com/document/d/1vDbdFBrG6tWDUb5z5ltny_7d-GZU78wS8K7Nru2BSj8/edit#)
- Fill out the first page and click Next
- In the console check the values are correct when you enter: `Comments_from_lead__c.value`
- Fill out the contact details and ensure you see the thank you panel 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3976
=> Update the robotics interactive contact form

templates/security/esm.html
Update ESM page copy according to #9446.
- Check the copy matches the changes proposed in #9446 and accept the suggestions in the document.
Fixes #9446
=> 9446: ESM page copy update

static/sass/styles.scss, templates/openstack/compare.html
Rebuild the page as specified in https://github.com/canonical-web-and-design/web-squad/issues/3939
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3939
=> Openstack compare copy update

templates/openstack/features.html
- Update openstack/features page
- Check against the [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#) comments and resolve comments as you go
Fixes [#3872](https://github.com/canonical-web-and-design/web-squad/issues/3872)
=> Update openstack/features page

templates/managed/index.html
- Added the copy doc https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit
- Check the copy doc plugin works
=> Updated the copy doc on /managed

webapp/advantage/api.py, webapp/advantage/schemas.py, webapp/advantage/views.py, webapp/app.py, webapp/decorators.py
- `contract["is_trialled"]` is true or false depending if the contract is
being trialled or not.
- `contractp["customerInfo"]["daysTillExpiry"]` show the number of days
left of the contract (it already existed)
- We will QA with the front-end, when it's ready
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/3975
=> Subscription trialled status

navigation.yaml, templates/16-04/_release-chart-1604.html, templates/16-04/azure.html, templates/16-04/index.html, templates/shared/forms/interactive/azure-1604.html
- Created the new /16-04/azure page and modal contact us
- View the site locally in your web browser at: http://0.0.0.0:8001/16-04/azure and http://0.0.0.0:8001/16-04/azure#get-in-touch
- Compare to the copy docs - [page](https://docs.google.com/document/d/1V99KwimN8Hla8L_CikNc6I0amqj99cSrBsVlAjIkBqE/edit#), [contact-form](https://docs.google.com/document/d/1NgT2MPNmF1SdVMCGU-Vr_I2wlm25C5z-p_rPZTnJrww/edit#)
Fixes [#4025](https://github.com/canonical-web-and-design/web-squad/issues/4025)
=> Add /16-04/azure page and contact-us

webapp/advantage/views.py
- Fix number of paid subscriptions
- It's a bit tricky. Check if the number of rows in the table matches the number in the header.
Fixes #9516
=> Fix number of paid subscriptions

templates/certification/hardware-details.html, tests/cassettes/TestCertification.test_model_hardware_details.yaml, tests/test_certification.py, webapp/app.py, webapp/certification/views.py
Hardware details page, a.k.a Models-release hardware details page.
Wireframe
Check /certification/202102-28707/20.04%20LTS
Fixes https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/173
=> Certification hardware details

webapp/advantage/schemas.py, webapp/advantage/views.py
- Fix bug where country was not an accepted parameter.
- Have the console open
- Make a purchase as a guest
- If perview returns 200, it works
Fixes #4034
=> Add country parameter

templates/advantage/subscribe/form/_feature_coverage.html
- Update feature coverage section (ESM Apps) copy to the [copydoc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?ts=6076a9df#) 
- go here https://ubuntu-com-9572.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9486
and https://github.com/canonical-web-and-design/web-squad/issues/4029
=> Update feature coverage copy

static/js/src/advantage/manage-subscription.js, static/js/src/utils/debounce.js
- Default to 0 if the machine number field is empty
- go to https://ubuntu-com-9585.demos.haus/advantage?test_backend=true
- click a subscription name 
- click "Change subscription"
- Delete the number of machine in the field
- check that it instead of going blank defaults to the min value for the field.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9465
=> Default to 0 if the machine number field is empty

static/js/src/advantage/subscribe/renderers/form-renderer.js
- Fix subtotal amount for guest purchases
- go to https://ubuntu-com-9583.demos.haus/advantage/subscribe?test_backend=true
- select some product and click continue to open the modal
- Check that the price matches what the "cart" said
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4031
=> Fix subtotal amount

webapp/views.py
- Fix dateutil problem.
- Are checks passing?
=> Fix dateutil problem

templates/certification/component-details.html, tests/cassettes/TestCertification.test_component_details.yaml, tests/test_certification.py, webapp/app.py, webapp/certification/views.py
Components detail page
- Check https://ubuntu-com-9580.demos.haus/certification/component/682
- Check the data provides content for the different sections of the [design](https://app.zeplin.io/project/5f3f890c6afe2512594898b2/screen/6076cde233a60f47a193f604)
Fixes #9419
=> Certification component details

templates/16-04/index.html
- Update table and layout on /16-04
- View the site locally in your web browser at: http://0.0.0.0:8001/16-04
- Compare to the [copy doc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit?usp=drivesdk)
Fixes #9602
=> Update table and layout on /16-04

navigation.yaml, templates/robotics/esm.html, templates/robotics/index.html, templates/robotics/shared/_download-make-strip.html, templates/robotics/shared/_learn-more-about-robotics.html, templates/templates/footer.html
- New page /robotics/esm
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/esm
- Compare to the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit?ts=606301c9#)
Fixes [#4001](https://github.com/canonical-web-and-design/web-squad/issues/4001)
=> New page /robotics/esm

templates/kernel/variants.html
Changes as per the copy doc https://docs.google.com/document/d/1UVxrF8raNb5Pggj05P0ar_OzV_uwhrTRHv9XRiuM4zs/edit?ts=6082d302#
- Accept the correct changes in the [copy doc](https://docs.google.com/document/d/1UVxrF8raNb5Pggj05P0ar_OzV_uwhrTRHv9XRiuM4zs/edit?ts=6082d302#) 
Fixes #9622
=> Copy changes on /kernel/variants

templates/kernel/index.html
- Added "and the Canonical livepatch service" with a link to https://ubuntu.com/security/livepatch
- Check the changes against the [copy doc](https://docs.google.com/document/d/1XLdk2Slh4vi4AjGnatcK1BmJGmMNKIjN27KwbTwG5iI/edit?ts=607d8d65#) and accept the correct ones.
#9581
=> Copy change to the /kernel page

templates/advantage/index.html, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html, templates/advantage/table/_renewal-actions.html
- Fix renewal button for legacy contracts
=> Fix renew button

templates/legal/ubuntu-advantage-service-description/index.md
Copy changes based on the copy doc https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit?ts=6080348e#
- Check changes against the [copy doc](https://docs.google.com/document/d/1vQNdVmpsB3iQP7SnJHxT3A8rbD5jSAzTEoYUOepR-SM/edit?ts=6080348e#)
=>  Copy changes to legal / ubuntu-advantage-service-description

templates/certification/index.html, webapp/certification/views.py
Correction on number of vendors and releases
- go to https://ubuntu-com-9608.demos.haus/certification and check that the numbers are correct (not sure how to check the accuracy, but as far as I know Desktop = Laptop and desktops, and Iot = smart core so it should be correct)
Fixes #9554
=> Fix homepage vendors

templates/advantage/index-no-login.html, templates/advantage/payment-methods/index.html
- removed the logged out section in the /advantage index file since it lives in index-no-login now
- Update the copy according to https://github.com/canonical-web-and-design/web-squad/issues/4035
- go to https://ubuntu-com-9630.demos.haus/advantage?test_backend=true
- check that it matches the design
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4070
=> Update /advantage logged out copy

templates/kubernetes/kubernetes-operations-survey.html
Update the copy of the page
- Check copy matches what is on #9631
- 
Fixes #9631
=> Update k8s survey page copy

templates/16-04/azure.html
Made changers as per the [Copy doc](https://docs.google.com/document/d/1V99KwimN8Hla8L_CikNc6I0amqj99cSrBsVlAjIkBqE/edit?ts=6086ec55#)
- Run through the [Copy doc](https://docs.google.com/document/d/1V99KwimN8Hla8L_CikNc6I0amqj99cSrBsVlAjIkBqE/edit?ts=6086ec55#) and accept any correct changes.
Fixes #9634
=> Updated as per the copy doc on 16-04/Azure

webapp/app.py
@pmatulis created a new one
Go to https://ubuntu-com-9657.demos.haus/openstack/docs
=> Update the openstack index topic ID

templates/kubernetes/docs/install-local.md, templates/kubernetes/docs/using-vault.md
- add note regarding current LXD bug to manual install page
- update link and clarify vault docs
=> k8sdocs minor updates

static/sass/_pattern_tabs.scss, templates/kubernetes/_install-aws.html, templates/kubernetes/_install-azure.html, templates/kubernetes/_install-google.html, templates/kubernetes/_install-linux.html, templates/kubernetes/_install-lxd.html, templates/kubernetes/_install-macos.html, templates/kubernetes/_install-windows.html, templates/kubernetes/install.html
- K8s install page refresh
- Check the copy matches what is on the copy doc
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/3984
=> K8s install page refresh

templates/kubernetes/index.html
Kubernetes landing page refresh
=> Kubernetes landing page refresh

templates/security/esm.html
- Update /security/esm copy
- View the site locally in your web browser at: http://0.0.0.0:8001/security/esm 
- Compare to the [copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit?ts=60896f74#) and resolve comments
Fixes [#4079](https://github.com/canonical-web-and-design/web-squad/issues/4079)
=> Update /security/esm copy

templates/16-04/index.html
- Update the title of the /16-04 page
- View the site locally in your web browser at: http://0.0.0.0:8001/16-04
- See that the page title has changed
Fixes #9671
=> Update the title of the /16-04 page

templates/openstack/features.html
Update the OpenStack features page content
- Open the demo and go to /openstack/features
- Check the changes in this PR match [the copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#) 
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9686
=> Update the OpenStack features page content

templates/16-04/index.html
- Add ROS and update link to azure on /16-04
- View the site locally in your web browser at: http://0.0.0.0:8001/16-04
- Compare to the [copy doc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit?ts=608976f4#heading=h.nbdpwjukuof7)
Fixes #9671
=> Add ROS and update link to azure on /16-04

static/js/src/advantage/contracts-api.js, static/js/src/advantage/manage-subscription.js, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html
- Pass the correct period instead of always passing monthly to the resizing endpoint
- go here https://ubuntu-com-9659.demos.haus/advantage?test_backend=true
- log in
- resize a contract
- check in the network tab that the right period is specified
=> Fix period being hardcoded to monthly for resizing

static/js/src/advantage/subscribe/renderers/form-renderer.js, static/sass/_pattern_card.scss, templates/advantage/subscribe/form/_type_select.html
- Added GCP to the wizard
- https://ubuntu-com-9670.demos.haus/advantage/subscribe?test_backend=true
Fixes #9548
=> Add GCP to the product selector

navigation.yaml, redirects.yaml, templates/robotics/base_robotics.html, templates/robotics/ros-esm.html, templates/robotics/shared/_learn-more-about-robotics.html, templates/robotics/thank-you.html, templates/shared/contextual_footers/_robotics_newsletter_signup.html
- Update text on the ros esm page
- Redirect from /robotics/esm to /robotics/ros-esm
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/ros-esm
- Compare to the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit?ts=60898010#) and test the redirect
Fixes #9673
=> Update /robotics/ros-esm page

konf/site.yaml
=> Add release paths for API

templates/azure/private-offer.html
Add azure private offer page
- Check [copy](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit) matches
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9698
=> Add azure private offer page

templates/azure/private-offer.html
- Text changes on private offer page
- View the site locally in your web browser at: http://0.0.0.0:8001/azure/private-offer
- Compare to the [copy doc](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit)
Fixes #9709
=> Text changes on private offer page

templates/advantage/index.html, templates/download/desktop/thank-you.html
Add closing script tab to allow download script to work
Make the `contributions.js` load from the compiled version.
- Go to /download/desktop/thank-you?version=20.04.2.0&architecture=amd64
- Check the download kicks off after a few seconds
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9727
=> Add closing script tab to allow download script to work

templates/cube/study/admin-tasks/part-4.md
Added `vmstat` sample and removed an unnecessary empty line.
=> Added `vmstat` sample

templates/certification/search-results.html
- Refactor search results following this [document](https://docs.google.com/document/d/1FRi83535YcpAv3jJ2lb4dpcBNlviA2JomD0d9gD5yAQ/edit#)
- View page at: https://ubuntu-com-9762.demos.haus/certified?q=
- Search for some hardware and use the filters - check the changes match what was requested [here](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/191).
- Some examples to check: 
- https://ubuntu-com-9762.demos.haus/certified?q=&category=Laptop
- https://ubuntu-com-9762.demos.haus/certified?q=&category=Device
- https://ubuntu-com-9762.demos.haus/certified?q=&category=Laptop&vendor=Dell
- https://ubuntu-com-9762.demos.haus/certified?q=&vendor=Dell
Fixes [#191](https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/191)
=> Refactor search results page

templates/aws/pro.html
Update copy on aws/pro
- Compare to [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#) and accept suggestions
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9755
=> Update copy on aws/pro

static/js/src/ua-payment-methods.js, templates/advantage/index.html, templates/advantage/payment-methods/index.html, webapp/advantage/api.py, webapp/advantage/views.py, webapp/app.py
Update payment methods page.
If they user has a failed payment they will see the following notification at the top of the page:
The button will allow them to retry the payment using the same details already stored.
If the payment failed because of 3ds, when they click retry -> the modal will show up:
- if the 3ds succeeds we show the success message and the page reloads after 2 seconds
- if the 3ds fails error message shows up. The user is offered the chance only one time to redo the 3ds, if it fails they have to change the card
If the payment failed because it needs a new payment method, when they click retry -> they will just retry with the same details:
- if the retry succeeds we show the success message and the page reloads after 2 seconds
- if the retry fails, they can still retry …
=> Update payment methods page

templates/cube/index.html
- Change the copy according to the [copydoc](https://docs.google.com/document/d/1QuhO-9FEOGLrYp8bErS_9snqdljl7d6tFAUoNQxoVDQ/edit?ts=60904800#)
- Check the copy matches the suggested change and mark it as resolved if it does.
Fixes #9696
=> Change CUBE homepage copy

templates/aws/pro.html, templates/azure/pro.html, templates/gcp/pro.html
Updates copy on /azure/pro
- Compare against [copy-doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#) and accept changes
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9756
=> Updates copy on /azure/pro

templates/certification/index.html, webapp/certification/views.py
- Certified overview laptops. 
- Check https://ubuntu-com-9775.demos.haus for the new laptops card
Fixes https://github.com/canonical-web-and-design/certification.ubuntu.com/issues/195
=> Certified overview laptops

templates/robotics/ros-esm.html
- Replace dupe paragraph on /robotics/ros-esm
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/ros-esm
- Compare to the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs/edit) and resolve comments
=> Replace dupe paragraph on /robotics/ros-esm

templates/kubernetes/kubernetes-operations-survey.html
- Updates copy on /kubernetes/kubernetes-operations-survey
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/kubernetes-operations-survey
- Compare to [Copy-doc](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit?ts=609a3c11#) and accept changes
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9760
=> Updates copy on /kubernetes/kubernetes-operations-survey

webapp/security/schemas.py, webapp/security/views.py
- Rename `is_binary` to `is_visible`.
=> Rename is_binary to is_visible

templates/financial-services/index.html
- Update `/financial-services` adding 2 case studies
- Check the page against [copy doc](https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit#) - two case studies added
Fixes #9773
=> Add case studies to financial-services

templates/kubernetes/managed.html, templates/shared/forms/interactive/managed-kubernetes.html
- Add contact form for /kubernetes/managed
- Follow the 'Talk to us' link and check the contact form against the [copy doc](https://docs.google.com/document/d/1iikqgW0rAFHRN-mAnlUArtF2cDt0OA0C4OheveP120w/edit#)
Fixes [#4142](https://github.com/canonical-web-and-design/web-squad/issues/4142)
=> Add contact form for /kubernetes/managed

templates/security/esm.html
- Updates copy on /security/esm
- View the site locally in your web browser at: http://0.0.0.0:8001/security/esm
- Compare against [Copy-doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit?ts=609a6315#) and accept changes
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9761
=> Updates copy on /security/esm

templates/public-cloud/index.html, templates/shared/_ubuntu_pro_on_public_cloud.html
- Updates copy on /public-cloud
- Compare against [Copy-doc](https://docs.google.com/document/d/1ZzUIh9Tfz5SvkrHyo4-izzmUjRka1Tn0UQisKcXGEPA/edit#heading=h.cdrr54m6neu5)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9754
=> Updates copy on /public-cloud

templates/cube/study/_navigation.md
Renamed the various "Parts" of "Performing Administrative Tasks" to be more accurate/informative.
Fixes #
=> Updates to "Performing Administrative Tasks"

templates/ibm/index.html
- Copy update on IBM 
- Waiting on someone to get back to me on copy doc about link to power point for 'Ubuntu Server update'. 
- View the site locally in your web browser at: http://0.0.0.0:8001/ibm
- Check against [copy doc](https://docs.google.com/document/d/10-dfyLyXBfsqoj0p1_omJhVpMYowX277kcPfdMLkzBA/edit?ts=60a6a338#)
- Waiting on link for Ubuntu Server update
Fixes #9802
=> Copy update IBM

templates/pricing/consulting.html, templates/shared/pricing/_kubernetes-consulting-add-ons.html, templates/shared/pricing/_kubernetes-consulting.html
- Updates copy on /pricing/consulting
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/consulting
- Compare against [copy-doc](https://docs.google.com/document/d/1sXeOQ9eLq53NcfbrorYstHkZYTdut33jbN5LyHoDdYY/edit?ts=60a7f5e3#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9812
=> Updates copy on /pricing/consulting

templates/openstack/features.html
- Copy update on `/openstack/features`
- Check against [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Fixes #9820
=> Copy update /openstack/features

templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html
- Gray out change subscription button if there is a pending payment.
- Have a pending payment
- Check the change subscription button for both a yearly and a monthly subscription
Fixes #9641
=> Gray out button

templates/advantage/index.html, templates/advantage/table/_manage-monthly.html, templates/advantage/table/_manage-yearly.html, webapp/advantage/api.py, webapp/advantage/views.py
Changes:
- hide next payment information if auto-renewal is disabled
- have the next payment information include VAT
- Have monthly subscriptions
- Check next payment includes VAT
- Check next payment date has not changed
Fixes #9736
=> Chanage subscription price to include VAT

templates/openstack/what-is-openstack.html, templates/shared/contextual_footers/_cloud_costs_increasing.html, templates/shared/contextual_footers/_contextual_footer.html
- Rebuilds /what-is-openstack page at /openstack
- Compare against [copy-doc](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#heading=h.c45r73q8oci4)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4134
=> Rebuilds /what-is-openstack page at /openstack

templates/security/disa-stig.html
- Build new page at `security/disa-stig`
- View page at: https://ubuntu-com-9862.demos.haus/security/disa-stig
- Check the page against the [copy doc](https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit#)
Fixes #9746
=> Build /security/disa-stig page

templates/advantage/index-no-login.html
Removed <p>See the table below to find the plan that’s right for you</p> as per the copy doc https://docs.google.com/document/d/1So3n5HEpBX39xxEkkChnve09gKSr9TgYUcbfdOTCevk/edit
Fixes #
=> Removed text from the "Free for per..." section</p>

templates/server/index.html
- Updates copy on /server
- Compare against [copy-doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9859
=> Updates copy on /server

static/js/src/chart-data.js, templates/about/release-cycle.html
- Update text and some chart images on /about/release-cycle
- Compare to the [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)
Fixes #9870
=> Update text and some chart images on /about/release-cycle

navigation.yaml, templates/kubernetes/docs/1.21/release-notes.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/multiple-networks.md, templates/kubernetes/docs/release-notes.md, templates/kubernetes/docs/shared/_side-navigation.md, templates/kubernetes/docs/supported-versions.md, templates/kubernetes/docs/vsphere-integration.md
- Add vsphere-integration docs
-  add updates for 1.21+ck2 release
=> K8sdocs 1.21+ck2

templates/openstack/compare.html, templates/shared/contextual_footers/_private_cloud_contact_us.html
- Update copy on /openstack/compare
- Compare to the [copy doc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit)
Fixes #9871
=> Update copy on /openstack/compare

templates/azure/pro.html
- Update pricing and datasheet on /azure/pro
- Compare to the [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit?ts=60c366a5#)
=> Update pricing and datasheet on /azure/pro

templates/advantage/index.html, templates/advantage/shared/_certifications-info.html, templates/advantage/shared/_esm-info.html, templates/advantage/shared/_livepatch-info.html
- Change copy
- Go to https://ubuntu-com-9895.demos.haus/advantage
- Check the text against the issue https://github.com/canonical-web-and-design/ubuntu.com/issues/9874
Fixes #9874
=> Change advantage copy

konf/site.yaml, redirects.yaml, webapp/certified/views.py
Redirect https://certification.ubuntu.com to https://ubuntu.com/certification
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9429
=> Add redirects for certified microsite

konf/site.yaml
Fix certification host redirect
Fixes #9898
=> Fix certification host redirect

templates/certified/model-details.html
Add feedback link
check https://ubuntu-com-9906.demos.haus/certified/201710-25838 has feedback link at the bottom of the page
Fixes #9827
=> Add feedback link

.github/workflows/ceph-docs-links.yaml, .github/workflows/core-docs-links.yaml, .github/workflows/kubernetes-docs-links.yaml, .github/workflows/openstack-charm-deployment-guide-docs-links.yaml, .github/workflows/openstack-charm-guide-docs-links.yaml, .github/workflows/server-docs-links.yaml, templates/kubernetes/docs/1.16/charm-containerd.md, templates/kubernetes/docs/1.17/charm-containerd.md, templates/kubernetes/docs/1.18/charm-containerd.md, templates/kubernetes/docs/1.19/charm-containerd.md, templates/kubernetes/docs/1.20/charm-containerd.md, templates/kubernetes/docs/1.21/charm-containerd.md, templates/kubernetes/docs/charm-containerd.md
Ignore and format the openstack-charm-deployment-guide-docs-links action
Update all other docs actions to ignore as much as its right too 
Update some local docs links
- Check the code and see if looks right
- QA will be on Monday morning :)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9918
=> Update docs link actions

build.js, package.json, static/js/src/cloud-price-slider.js, templates/openstack/index.html
- Added slider for representation of cost of public and private cloud
- Check slider https://ubuntu-com-9917.demos.haus/openstack
See design in the issue
Fixes #9524
=> Openstack public vs private cloud slider

templates/about/release-cycle.html
- Remove extra double quote from table
- See that a random '"' has been removed
Fixes #9941
=> Remove extra double quote from table

webapp/advantage/views.py
- `contract.contractInfo.grace_period_end` shows the formatted grace period of the contract. It will only show up if the contract is expired.
=> Add grace period

templates/internet-of-things/appstore.html
- Updates copy on /internet-of-things/appstore
- View the site locally in your web browser at: http://0.0.0.0:8001/internet-of-things/appstore
- Compare against [copy-doc](https://docs.google.com/document/d/1CKwmPDDtXOIgw-jSZFwzP-qLMc_rS_dUACpHQXlg0fA/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9927
=> Updates copy on /internet-of-things/appstore

templates/download/server/s390x.html
Remove the scrollbar from the server s390x form
- Go to /download/server/s390x
- Check the form card has no scrollbar
- Submit form and check it works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9957
=> Remove the scrollbar from the server s390x form

static/js/src/utils/persitState.js, templates/about/release-cycle.html, templates/advantage/index.html, templates/advantage/table/_free-trial.html, templates/certified/index.html, templates/contact-us/form/index.html, templates/contact-us/form/thank-you.html, templates/templates/navigation-enterprise-h.html
- Build a view for free trials
Go to this demo and start a trial (UA Apps / infra + apps) https://ubuntu-com-9940.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true
Then go here https://ubuntu-com-9951.demos.haus/advantage?test_backend and check that it appears correctly
For expired trials, wait a month? (or ask Allan)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3854
=> Build free trial view

build.js, static/js/src/advantage/contracts-api.js, static/js/src/advantage/subscribe/react/APICalls/useFreeTrial.jsx, static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoAnon.jsx, static/js/src/advantage/subscribe/react/APICalls/useProduct.jsx, static/js/src/advantage/subscribe/react/PurchaseModal.jsx, static/js/src/advantage/subscribe/react/components/Buttons/FreeTrialButton.jsx, static/js/src/advantage/subscribe/react/components/Buttons/PayNowButton.jsx, static/js/src/advantage/subscribe/react/components/Buttons/PaymentMethodFormButton.jsx, static/js/src/advantage/subscribe/react/components/FormRow.jsx, static/js/src/advantage/subscribe/react/components/FreeTrialRadio.jsx, static/js/src/advantage/subscribe/react/components/PaymentMethodForm.jsx, static/js/src/advantage/subscribe/react/components/PaymentMethodSummary.jsx, static/js/src/advantage/subscribe/react/components/PositiveButton.jsx, static/js/src/advantage/subscribe/react/components/Summary.jsx, static/js/src/advantage/subscribe/react/components/TermsCheckBox.jsx, static/js/src/advantage/subscribe/react/components/TotalSection.jsx, static/js/src/advantage/subscribe/reducers/form-reducer.js, static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/index.html
- Added ability to start a free trial when the product is eligible
- go here https://ubuntu-com-9940.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true
- select infra + apps essential
- start a trial!
Fixes #9494
=> 9494 add free trial to purchase modal

templates/azure/pro.html
- Copy update on `/azure/pro`
- Visit the page at: https://ubuntu-com-9980.demos.haus/azure/pro
- Check against [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit?ts=60d61637) and please resolve comment
Fixes [#4211](https://github.com/canonical-web-and-design/web-squad/issues/4211)
=> Copy update on azure pro

templates/training/contact-us.html, templates/training/index.html, templates/training/thank-you.html
- Add new sections and update `/training`
- Add custom contact us/thank you pages
- View page at: https://ubuntu-com-9976.demos.haus/training
- Check against [copy doc](https://docs.google.com/document/d/1gyxy75qXC5Ta08o6Vnm13yK6aeN4qOnsETB2gZ4e0ZY/edit?ts=60d47bcc#)
Fixes #9952
=> Copy update on /training

templates/azure/private-offer.html
Update the content for the Azure proivate offer page
- Open the demo and go to /azure/private-offer
- Check the content matches the suggestions in [the copy doc](https://docs.google.com/document/d/1ZgV1ZiyHJe3UNQkj0I-OCpZ4MIAWLHheig2Q2rclcuk/edit?ts=60d4d594)
- Please approve the suggestions if correct
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4221
=> Update the content for the Azure proivate offer page

static/js/src/ua-payment-modal.js
- Fixes some js issues which might be the cause of the renewal issue.
- This will be insane
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/40
=> Fix renewals

templates/cloud/index.html
Copy update private cloud link text
Check /cloud against [copy docs](https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit?ts=60dde350#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/9988
=> Copy update private cloud link

static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoAnon.jsx, static/js/src/advantage/subscribe/react/APICalls/usePreview.jsx, static/js/src/advantage/subscribe/react/APICalls/useStripeCustomerInfo.jsx, static/js/src/advantage/subscribe/react/app.jsx
- Fix the modal for users who don't have a stripe account yet. (Users with only salesforce contracts)
- Ask Albert :joy: 
or 
- Create a new Ubuntu one account, ask Albert or Allan to add a renewal to your account
- go to /subscribe and open the modal
- check that it displays the form correctly
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/60
=> Fix modal loading forever for users with only salesforce contracts

templates/advantage/subscribe/form/_tech_support.html, templates/advantage/subscribe/form/_type_select.html
- changed Servers to Physical servers
- Made AWS instances wrap on 2 lines
- replaced Software only by "Software and security updates only' in the support section
- go to https://ubuntu-com-9999.demos.haus/advantage/subscribe
- check against the [copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit)
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/64
=> Update /subscribe copy

static/js/src/advantage/subscribe/react/APICalls/useProduct.jsx, static/js/src/advantage/subscribe/react/PurchaseModal.jsx, static/js/src/ua-payment-modal.js, static/js/src/utils/getSessionData.js
- Added checkout events at each step of the checkout
- Added Purchase event on successful payment
- Added Marketo form send on successful payment
Not sure how to QA that one @pmahnke @caldav ?
https://ubuntu-com-9995.demos.haus/advantage/subscribe?test_backend=true&esm_apps=true
Fixes #63
=> Add missing ecom events on purchase modal

navigation.yaml, templates/telco/index.html, templates/telco/openran.html
- Builds telco/openRAN page
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/openran
- Compare against [copy-doc](https://docs.google.com/document/d/181cqeYzSZ_RinjPTMMNDyAEMwKVvdeoc30iQDrwl4aQ/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4192
=> Builds telco/openRAN page

navigation.yaml, templates/telco/index.html, templates/telco/vnf.html
- Creates VNF page
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/vnf
- Compare against [copy-doc](https://docs.google.com/document/d/1xq3tFh1vWhNm1gFzddB6LQ65DggVMHsRUSXvqFPqYc0/edit#)
- 'Contact us' form wont work until it's PR is merged
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4190
=> Creates VNF page

static/js/src/advantage/subscribe/react/APICalls/useProduct.jsx, static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/index.html
- Changed the /subscribe button to "Next step"
- updated the references to the button to reflect the change
- Go to https://ubuntu-com-10007.demos.haus/advantage/subscribe
- check that the button now displays Next step
=> Change /subscribe's button label

templates/security/livepatch.html
- Added new security certifications bubble
- PR's have been reviewed but please check against the [brief](https://docs.google.com/document/d/1cBC6Q6yeKuYejxLEDAd1YE6mpNsfmQXp9h6hP4C7DuI/edit#) and copy docs.
=> [Security certifications] - Merge changes into upstream feature branch

templates/security/cis.html
Copy update page
Check  https://ubuntu-com-10009.demos.haus/security/cis against [copy docs](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4230
=> Security certs cis update

templates/openstack/index.html
Based on https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?ts=60defa2d#
- Check the changes against the [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?ts=60defa2d#) and accept the correct ones.
Fixes #
=> Removed training and tracking

static/js/src/advantage/subscribe/react/components/Summary.jsx, static/js/src/advantage/subscribe/react/components/TotalSection.jsx
- Changed the top and bottom section of the modal when a free trial is selected
- Go to /advantage/subscribe?test_backend=true and play around with free trials
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/70 https://github.com/canonical-web-and-design/commercial-squad/issues/71
=> 70 71 modal changes

templates/kubernetes/index.html, templates/kubernetes/install.html, templates/kubernetes/what-is-kubernetes.html
K8s copy updates
Check  https://ubuntu-com-10020.demos.haus/kubernetes against [Copydoc](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit#)
Check  https://ubuntu-com-10020.demos.haus/kubernetes/what-is-kubernetes against [Copydoc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#heading=h.o5s83ba2s3zx)
Check https://ubuntu-com-10020.demos.haus/kubernetes/install [Copydoc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4241
=> K8s pages copy updates

templates/security/disa-stig.html
Copy updates
Check https://ubuntu-com-10029.demos.haus/security/disa-stig against [copy docs](https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4229
=> Security certs disa-stig

templates/security/fips.html
Copy updates
- Check  https://ubuntu-com-10015.demos.haus/security/fips  against [copy docs](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4231
=> Security certifications fips copy updates

templates/cloud/index.html
- Updated the link on /cloud based on Tytus's comment; https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit?ts=60ec2a6c
- Accept Tytu's comment https://docs.google.com/document/d/1DJZFADvRr_hrHzRWJrUTJxAM2ocZJ_ZWEnQVdKi6JBE/edit?ts=60ec2a6c
Fixes #
=> Update the link on /cloud

templates/advantage/subscribe/form/_feature_coverage.html, templates/advantage/subscribe/form/_tech_support.html
- Renamed products and updated support copy according to [the copy doc](https://docs.google.com/document/d/1UqL8YJH9ywvOXnrt3syY0U8fiOakfAGWmLS9uerwAWk/edit?ts=60ef1acb)
- go to /subscribe and check that the copy is ok
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/77
=> Rename products and update support copy

templates/openstack/index.html, templates/shared/pricing/_ua-for-infrastructure.html
- Updates copy on /openstack
- Compare against [copy-doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#)
- Note: Pie-chart will be implemented in another issue.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10042
=> Updates copy on /openstack

templates/openstack/features.html
- Updates copy /openstack/features
- Compare against [copy-doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10044
=> Updates copy /openstack/features

templates/openstack/compare.html
- Updates copy on /openstack/compare
- Compare against [copy-doc](https://docs.google.com/document/d/1ibpATi-e0rKP3GaLgvzwO_XyFU9ZTsUaCHMwrg96MZM/edit)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10043
=> Updates copy on /openstack/compare

templates/download/cloud/index.html
Update the Ubuntu on Azure marketplace link to https://azuremarketplace.microsoft.com/en-gb/marketplace/apps?search=Canonical+linux+for+the+cloud+Ubuntu%20Server&page=1.
- Check the code that the link matches the copy doc suggestion and link.
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10018
=> Update the Ubuntu on Azure marketplace link

templates/blender/contact-us.html, templates/blender/index.html, templates/blender/thank-you.html, templates/shared/_blender-contact-us-form.html
- Builds blender contact form and associated files.
- View the site locally in your web browser at: http://0.0.0.0:8001/blender
- Compare against [copy-doc](https://docs.google.com/document/d/1Qtxk3cQ_dUBVVNfcAm75Ap-D3h90sTMrrOEhxa1RMIA/edit#)
- Check form opens properly and is submitted correctly.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4267
=> Builds blender contact form

webapp/certified/views.py
Sort filters to the top when selected.
- Check https://ubuntu-com-10065.demos.haus/certified?q=xps and choose different filters 
- After clicking update, you should see filters going to the top
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4251
=> Sort filter list by selected

babel.config.js, package.json, yarn.lock
- Set up Jest to allow TypeScript files.
N/A tests should pass.
Fixes canonical-web-and-design/commercial-squad#125.
=> Set up Jest to allow TypeScript files

templates/openstack/install.html, templates/shared/contextual_footers/_openstack_install.html, templates/shared/contextual_footers/_openstack_install_documentation.html, templates/shared/contextual_footers/_openstack_install_newsletter.html
openstack./nstall updates
- Compare https://ubuntu-com-10073.demos.haus/openstack/install to [copy docs](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#heading=h.s4axx05c1d9a)
The download PDF form is not included, this will be done in another PR, as it is a complicated task.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4277
=> Openstack install copy update

navigation.yaml, static/js/src/navigation.js, templates/account/invoices/index.html, webapp/advantage/api.py, webapp/advantage/schemas.py, webapp/advantage/views.py, webapp/app.py
- Add invoice endpoints `/account/invoices`
- Add invoice table
- Add invoice table filter
- Add `?email=example@email.com` to view as invoices
- Login at https://ubuntu-com-10062.demos.haus/advantage?test_backend=true
- Go to https://ubuntu-com-10062.demos.haus/account/invoices?test_backend=true
- Play around on the page: 
- Check that you have the invoices
- Test the filter
- Try to view as https://ubuntu-com-10062.demos.haus?test_backend=true&email=example@email.com
Fixes #52 #51 #58
=> Add invoice page

static/sass/_pattern_certification-results.scss, templates/certified/search-results.html, tests/cassettes/TestCertification.test_search_results.yaml, webapp/certified/views.py
- Update page based on [design](https://app.zeplin.io/project/60c1ca887b99f18a380e57e9/screen/60f169f4009bd51281d0a3ff)
- Add functionality to be able to change the number of results per page
- The width of the pagination dropdown is wider than design as when 100 was selected it was cutting off the 0 (I made it as small as possible).
- On the table, I couldn't have the "CATEGORY" heading touching the edge of the table without right aligning it (which we can't do with the content of that column as they aren't numbers), as when the screen size changes slightly it causes the ellipses. I've made it work for the main screen sizes, let me know what you think. 
- View page at: https://ubuntu-com-10092.demos.haus/certified?q=dell
- Check page against …
=> [Certified improvements] - add pagination select 

static/js/src/advantage/react/app.test.tsx, static/js/src/advantage/react/app.tsx, static/js/src/advantage/react/components/Subscriptions/Content/Content.test.tsx, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/Content/index.ts, static/js/src/advantage/react/components/Subscriptions/Subscriptions.test.tsx, static/js/src/advantage/react/components/Subscriptions/Subscriptions.tsx, static/js/src/advantage/react/components/Subscriptions/index.ts, templates/advantage/index.html
- Add basic subscriptions component.
- Add basic subscriptions content component.
- You should see a card with "Subscription list" and "Subscription details" inside it.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/91.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/86.
=> Add basic subscriptions and subscriptions content components.

templates/telco/cnf.html
- Updates copy on /cnf
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/cnf
- Compare against [copy-doc](https://docs.google.com/document/d/1IpOPiWidozQ7w1hyM52yQn1gSwHODsItn1ZnMQ0retw/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4284
=> Updates copy on /cnf

.eslintrc.js, .github/workflows/pr.yaml, static/js/src/openstack/react/components/CostCalculatorForm.jsx
- Fix JavaScript linter.
- Fix linting errors.
- Add lint-js CI job.
N/A CI should pass.
Fixes: canonical-web-and-design/commercial-squad#131.
=> Fix JavaScript linter.

redirects.yaml, templates/certified/desktops-search-results.html, templates/certified/index.html, templates/desktop/developers.html, webapp/app.py, webapp/certified/views.py
Add new /certified/desktop page
This is just a copy of the /certified code removing all category filtering
Check https://ubuntu-com-10108.demos.haus/certified/desktops
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4285
=> Add new /certified/desktops page

navigation.yaml, templates/shared/forms/interactive/osm-contact-us.html, templates/telco/osm/contact-us.html, templates/telco/osm/index.html, templates/telco/osm/thank-you.html
- Creates /osm page
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/osm
- Check modal form works and that the static form works is JS is disbaled.
- Compare against [copy-doc](https://docs.google.com/document/d/1LQim0WRVdDZE9-ToFKSD52O7kgurMoytrgDDAPYnug8/edit)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10064
=> Creates /osm page

templates/shared/_blender-contact-us-form.html, templates/shared/contextual_footers/_robotics_newsletter_signup.html, templates/shared/forms/interactive/openstack-cost-calculator.html, templates/shared/forms/interactive/osm-contact-us.html, templates/shared/forms/interactive/telco-networks.html
- Fix some forms so marketo submissions work
=> Form fixes

templates/legal/companies.html, templates/shared/contextual_footers/_cloud_bootstack.html
- Copy update on `/legal/companies`
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/companies
- Please check page against [copy doc](https://docs.google.com/document/d/1y1wPpmeS_BhbRXRdoUJmaTPIMHC_72UzqZG36oP0yWw/edit#heading=h.8d8ieshhle87) and resolve comments
Fixes #10113
=> Copy update on /legal/companies

templates/ceph/what-is-ceph.html
- Copy update on `/ceph/what-is-ceph`
- Please check page against [copy doc](https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/editl) and resolve comments
- View page at : [https://ubuntu-com-10128.demos.haus/ceph/what-is-ceph](https://ubuntu-com-10128.demos.haus/ceph/what-is-ceph)
Fixes [#4299](https://github.com/canonical-web-and-design/web-squad/issues/4299)
=> Copy update on /ceph/what-is-ceph

templates/download/index.html
- Copy update on `/download`
- Please check page against [copy doc](https://docs.google.com/document/d/1egsCcmFiz8czeHsvwoB9Jz815Ij5Urtf7Ngrru6Zd4o/edit) and resolve comments
- View demo at : [https://ubuntu-com-10130.demos.haus/download](https://ubuntu-com-10130.demos.haus/download)
Fixes [#4298](https://github.com/canonical-web-and-design/web-squad/issues/4298)
=> Copy update on /download

templates/azure/index.html
- Copy update on /azure
- Please check page against [copy doc](https://docs.google.com/document/d/1GUlSATrqZmGrsk4DhP9W0s-gcOuFxpdKVgx7YE4g780/edit#) and resolve comments
- View demo at : [https://ubuntu-com-10139.demos.haus/azure](https://ubuntu-com-10139.demos.haus/azure)
Fixes #10137
=> Copy update on /azure

webapp/views.py
- Report issues with the marketo API into sentry
=> Report issues with the marketo API into sentry

templates/observability/index.html
- Streamline first subtitle to avoid repetition [Changes already reflected in GDocs]
Fixes #
=> /observability: Streamline first subtitle

templates/managed/kafka.html
- Copy update on /managed/kafka
- Please check page against [copy doc](https://docs.google.com/document/d/15c89-PyMc-QnSHglG1hf_Tub5lMkEcVYALL0rm5-LvA/edit#) and resolve comments
- View demo at : [https://ubuntu-com-10148.demos.haus/managed/kafka]( https://ubuntu-com-10148.demos.haus/managed/kafka)
Fixes #10144
=> Copy update on /managed/kafka

templates/desktop/developers.html
Copy updates for /developers page
- Check https://ubuntu-com-10099.demos.haus/developers against [copy docs](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4280
=> Desktop developers copy updates

templates/kubernetes/what-is-kubernetes.html
- Copy update on /kubernetes/what-is-kubernetes
- Please check page against [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#) and resolve comments
- View demo at : [https://ubuntu-com-10160.demos.haus/kubernetes/what-is-kubernetes](https://ubuntu-com-10160.demos.haus/kubernetes/what-is-kubernetes)
Fixes #10156
=> Copy update on /kubernetes/what-is-kubernetes

package.json, static/js/src/advantage/api/contracts-types.ts, static/js/src/advantage/api/types.ts, static/js/src/advantage/react/hooks/useLoadWindowData.test.tsx, static/js/src/advantage/react/hooks/useLoadWindowData.ts, static/js/src/advantage/tests/factories/api.ts, static/js/src/advantage/tests/factories/contracts.ts, yarn.lock
- Added test factory dep.
- Added testing factories for the API and contract API types.
- Updated window data hook to use the types and factories.
N/A
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/145.
=> Add testing factories for the contract API

templates/shared/_telco-contact-us.html, templates/shared/contextual_footers/_openstack_install_newsletter.html, templates/shared/forms/interactive/observability-contact-us.html, templates/shared/forms/interactive/osm-contact-us.html
Update some more forms to work with the new endpoint by removing unneeded fields.
=> Update some more forms to work with the new endpoint

static/js/src/imageBuilder.js, templates/core/build/index.html
- Added Ubuntu Core 20 to OS list and Fixes #10152
=> Bugfix for arch and board selection & Added Ubuntu Core 20

static/js/src/advantage/api/types.ts, static/js/src/advantage/react/hooks/useLoadWindowData.ts, static/js/src/advantage/react/hooks/useURLs.test.tsx, static/js/src/advantage/react/hooks/useURLs.ts, static/js/src/advantage/react/hooks/useUsingTestBackend.test.tsx, static/js/src/advantage/react/hooks/useUsingTestBackend.ts, templates/advantage/index.html
- Fetch and store the test backend flag.
- Append the test backend flag to URLs.
- In the payment method notification click on "update your payment methods".
- You should get taken to /account/payment-methods?test_backend=true
- Visit /advantage
- In the payment method notification click on "update your payment methods".
- You should get taken to /account/payment-methods
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/136
=> Append the test backend flag to URLs

templates/16-04/index.html
- Updated the copy according to the [copydoc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit#)
- go on https://ubuntu-com-10164.demos.haus/16-04
- check that the copy matches the copydoc
Fixes #10067
=> 16.04 ESM page discusses 'april 2021' in the future tense

templates/kubernetes/index.html
- Updated `Kubernetes Explorer` to `Training & onboarding package`
- Please check page against [copy doc](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit#) and resolve comments
- View demo at [https://ubuntu-com-10170.demos.haus/kubernetes](https://ubuntu-com-10170.demos.haus/kubernetes)
Fixes #10168
=> Copy update on /kubernetes

templates/telco/osm/index.html
- Updated logo in`Flexible VIM options`
- Added `OSM Community`
- Please check page against[ copy doc](https://docs.google.com/document/d/1LQim0WRVdDZE9-ToFKSD52O7kgurMoytrgDDAPYnug8/edit) and resolve comments
Fixes [#4326](https://github.com/canonical-web-and-design/web-squad/issues/4326)
=> Copy update on /telco/osm

templates/kubernetes/docs/1.21/charm-kubernetes-master.md, templates/kubernetes/docs/1.21/charm-kubernetes-worker.md, templates/kubernetes/docs/1.21/charm-tigera-secure-ee.md, templates/kubernetes/docs/certs-and-trust.md, templates/kubernetes/docs/charm-kubernetes-worker.md, templates/kubernetes/docs/cni-calico.md, templates/kubernetes/docs/cni-multus.md, templates/kubernetes/docs/docker-registry.md, templates/kubernetes/docs/encryption-at-rest.md, templates/kubernetes/docs/ipv6.md, templates/kubernetes/docs/scaling.md, templates/kubernetes/docs/security.md, templates/kubernetes/docs/storage.md, templates/kubernetes/docs/upgrade-notes.md, templates/kubernetes/docs/using-vault.md
Fix a range of links across the kubernetes documentation.
- Check that the links address the issues reported here: https://github.com/canonical-web-and-design/ubuntu.com/runs/3340341563?check_suite_focus=true
=> Fix broken links across the kubernetes docs

templates/engage/_article-card.html, templates/engage/index.html, webapp/views.py
- Tags filter for engage pages
- Show tags on each card
- Check https://ubuntu-com-10192.demos.haus/engage
- Use the tags filter
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4325
Fixes https://github.com/canonical-web-and-design/web-squad/issues/3874
=> Engage pages tags filter

templates/managed/kafka.html
Updated Kafka copy according to doc 
- Go to http://localhost:8001/managed/kafka to check for copy changes 
Fixes 
https://github.com/canonical-web-and-design/web-squad/issues/4369
=> #4369, updated kafka copy

templates/internet-of-things/index.html
- Update with new Xilinx content
- Complete copy request about SNA Displays (from March)
- View page at: https://ubuntu-com-10258.demos.haus/internet-of-things
- Compare against [copy doc ](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#)
- Resolve all comments on copy doc
Fixes [#4144](https://github.com/canonical-web-and-design/web-squad/issues/4144)
=> Xilinx copy update on /internet-of-things

templates/security/livepatch.html
Rebuilt /security/livepatch page and updated needed links according to :
https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#
- View the site locally in your web browser at: http://0.0.0.0:8001/security/livepatch
Design:
https://app.zeplin.io/project/611e602c86dd4c5928359e48/screen/611e605ce9a2e085a5a677fe
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4347
=> Rebuilt /security/livepatch page 

templates/kubernetes/compare.html
- Updated copy and added whitepaper and consulting links 
- copydoc: https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes/compare
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4392
=> Updated copy and links on /kubernetes/compare

navigation.yaml, templates/download/xilinx/index.html
- Build new page at `/download/xilinx`
- View page at: https://ubuntu-com-10275.demos.haus/download/xilinx
- Compare the page against the:
- [Copy doc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit#)
- [Design](https://github.com/canonical-web-and-design/web-squad/issues/4151#issuecomment-909274349)
Fixes [#4148](https://github.com/canonical-web-and-design/web-squad/issues/4148)
=> Build Xilinx download page

templates/legal/contributors/agreement.html
- Form assembly updated the recaptcha and I had to update the /legal/contributors/agreement form
- There was also an issue with the email the form was sending from, so I updated that on form assembly ([see this RT](https://rt.admin.canonical.com/Ticket/Display.html?id=132756))
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/contributors/agreement
- See that the form isn't horrible looking (it needs a lot of css and classes from FA)
- See that the form submits in the inspector networking tab
=> Update recaptcha on the /legal/contributors/agreement form

konf/site.yaml
=> Added missing secrets

templates/shared/forms/interactive/bootstack.html, templates/shared/forms/interactive/openstack.html
- Updated contact form on the following pages. 
- Please check page against [copy doc](https://docs.google.com/document/d/140P1Z--hkWuW9-S2cNAR_uCW3BRW1VPKtFWkDtc7eBk/edit) and resolve comments
Fixes [#4382](https://github.com/canonical-web-and-design/web-squad/issues/4382)  [#4383](https://github.com/canonical-web-and-design/web-squad/issues/4383)  [#4384](https://github.com/canonical-web-and-design/web-squad/issues/4384)
=> Rebuild openstack contact form

templates/shared/forms/interactive/bootstack.html, templates/shared/forms/interactive/openstack.html
- Fixed the "Let's discuss your requirements" button (in the last page of the form) moving to next line on bigger screens.
- Fixed the checkbox-not-working issue.
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack#get-in-touch
- Please check if the two buttons stay in one line on big screens 
- Please check all the checkboxes working well 
- Please check the checkboxes in the `/openstack/managed#get-in-touch` page as well
Fixes #10306
=> Align buttons in one line

templates/account/payment-methods/index.html, templates/advantage/_stripe-modal.html, templates/advantage/subscribe/index.html, webapp/advantage/context.py, webapp/advantage/decorators.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/views.py, webapp/app.py, webapp/decorators.py
- Extract the `stripe_publishable_key` from the decorator and make it globally accessible to the front end
- Refactor the advantage_check decorator to instantiate the `UAContractsAPI` object
- Refactor views to use the new advantage_decorator
Documentation of the decorator: https://docs.google.com/document/d/10H9Fu-BvHEVzFvsfpP5czGMFUHf_JhnG_dXZJVML_JA/edit#
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/215
=> Refactor advantage decorator

templates/kubernetes/docs/1.22/components.md
Reformat the k8s image list so it renders properly
=> fix k8s image list

navigation.yaml, templates/download/iot/intel-iotg.html
- Build new page at `/download/iot/intel-iotg`
- Add to secondary nav 
- View page at: https://ubuntu-com-10332.demos.haus/download/iot/intel-iotg
- Check page against [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit#)
- Note: the TM and R symbols are only used on the first and most prominent mentions of the mark word
Fixes [#4406](https://github.com/canonical-web-and-design/web-squad/issues/4406)
=> Build new /download/iot/intel-iotg page

templates/managed/apps/index.html
- Aligned logos and texts center
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/apps
- Please check page against [copy doc](https://docs.google.com/document/d/1fLRWW-Gtslaia2ypSrLJVBxZVHo5FY5Q84o97Gs2-w4/edit)
- Please check the page on smaller screens as well
Fixes [#4405](https://github.com/canonical-web-and-design/web-squad/issues/4405#event-5265868395)
=> Fix logo alignment

templates/kubernetes/index.html, templates/kubernetes/what-is-kubernetes.html
Updated ctas on /kubernetes
/index copydoc:https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit
Updated needed ctas and added section as per docs on /kubernetes/what-is-kubernetes Also changed the styling of preceding section to match visual flow (see screen shot)
/what-is-kubernetes copydoc: https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#
- View the site locally in your web browser at: http://0.0.0.0:8001/kubernetes and http://0.0.0.0:8001/kubernetes/what-is-kubernetes
- [List additional steps to QA the new features …
=> updated ctas on /kubernetes and /kubernetes/what-is-kubernetes

webapp/advantage/views.py, webapp/app.py
- Fix URL
- Remove period from url
- Login on https://ubuntu-com-10338.demos.haus
- Go to: https://ubuntu-com-10338.demos.haus/account/invoices
- Try to download invoice
- It should work
=> Fix invoice download

webapp/advantage/views.py
- Adding `is_trialled` property to `enterprise_contracts`
- If `is_trialled` then the cancel trial button should show up
- Go to https://ubuntu-com-10321.demos.haus/advantage
- You should see your subscriptions as before
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/218
=> Contract enterprise in trial

package.json, static/js/src/advantage/users/AccountUsers.test.tsx, static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/components/AddNewUser/AddNewUser.test.tsx, static/js/src/advantage/users/components/AddNewUser/AddNewUser.tsx, static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.test.tsx, static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx, static/js/src/advantage/users/components/TableView/TableView.test.tsx, static/js/src/advantage/users/components/TableView/TableView.tsx, static/js/src/advantage/users/components/TableView/components.tsx, static/js/src/advantage/users/constants.ts, static/js/src/advantage/users/mockData.ts, static/js/src/advantage/users/types.ts, yarn.lock
- add NewUserForm within modal
- add validation, formSubmissionError handling, success message
- remove "date added" column
- add name form field
- add @testing-library/user-event
1. Go to https://ubuntu-com-10348.demos.haus/advantage/users?test_backend=true and login
2. Add a new user
3. Verify that form validation requires all fields to have a value
4. Verify the success message has been displayed on successful submission
https://github.com/canonical-web-and-design/commercial-squad/issues/197
=> Account users/new user modal

tests/advantage/fixtures/subscription.json, tests/advantage/test_parsers.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/ua_contracts/primitives.py, webapp/advantage/views.py
- Add `is_trialling` to shop view
- Make a guest purchase
- Nothing broke
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/247
=> Add is trialling to shop view

webapp/advantage/views.py
- Add account name to /advantage/account-users
- Go to https://ubuntu-com-10358.demos.haus/advantage/account-users
- Name field should exist
=> Add account name

static/js/src/dynamic-forms.js, templates/kubernetes/install.html, templates/shared/forms/interactive/kubernetes.html, templates/shared/forms/interactive/managed-kubernetes.html
- Updated contact form on `/kubernetes`, `/kubernetes/what-is-kubernetes`, `/kubernetes/compare`, `/kubernetes/install`, and `/kubernetes/managed`
- copydoc: https://docs.google.com/document/d/1u6IkVfDNNwdz4XgHU6FSCnUFfVtfTMNMmtINIPT31cU/edit#
- View the site locally in your web browser at: https://ubuntu-com-10368.demos.haus/kubernetes
- Visit all relevant pages (see above) and check confirm the titles match the copydoc
- Try to submit without filling out filling all relevant fields, check that it correctly fails
- Do the same but with all fields filled and submit 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4429
=> Update contact form

templates/kubernetes/features.html
- Added a link to https://ubuntu.com/openstack on the website: https://ubuntu.com/kubernetes/features
- Changed "Logging and monitoring" section's title to "Observability and metrics"
- Open the website: https://ubuntu-com-10361.demos.haus
- Make sure that there is a title called "Observability and metrics" 
- Make sure that OpenStack is a link in the section: https://ubuntu-com-10361.demos.haus/kubernetes/features#bare-metal
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4431
=> Content update on the page "Charmed Kubernetes features"

webapp/advantage/views.py
- Fix trial parameter typo.
QA with the front-end
=> Fix trial parameter typo

templates/aws/pro.html, templates/azure/pro.html
- Updated the page /aws/pro to match the copy doc
- Updated the page /azure/pro to match the copy doc
- Go to the website https://ubuntu-com-10392.demos.haus/aws/pro
- Make sure that the content matches the copy doc (link in the linked issue)
- Go to the website https://ubuntu-com-10392.demos.haus/azure/pro
- Make sure that the content matches the copy doc (link in the linked issue)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4434
=> Copy update azure aws pro

templates/legal/ubuntu-advantage-service-description/_toc.html, templates/legal/ubuntu-advantage-service-description/index.md, templates/shared/_ubuntu-advantage-service-description.html
- Build new uasd at `/legal/ubuntu-advantage-service-description`
- Build new table of contents
- View page at : https://ubuntu-com-10402.demos.haus/legal/ubuntu-advantage-service-description
- Check against [copy doc](https://docs.google.com/document/d/15URkXf2vh7bv89n-cWQPeaP2EehSNUnUCoZvGbNTYFA/edit#heading=h.eddnsno5g76l)
- Check the table of contents works as expected
Fixes [#4435](https://github.com/canonical-web-and-design/web-squad/issues/4435)
=> Build new ubuntu advantage service description

static/js/src/navigation.js, static/sass/_pattern_navigation.scss, templates/templates/_navigation.html
- Made Ubuntu logo and secondary nav grayed out when search bar is active 
Fixes #9914
=> Gray out the logo and secondary nav

build.js, static/js/src/cube/app.tsx, static/js/src/cube/components/MicrocertificationsTable/MicrocertificationsTable.tsx, static/js/src/cube/components/MicrocertificationsTable/index.ts, templates/cube/microcerts.html
Fixes canonical-web-and-design/commercial-squad#249
- Added an anchor for the react app to mount on the page
- Added a dummy app to test that it mounts correctly
- go to https://ubuntu-com-10380.demos.haus/cube/microcerts
- check that you see two tables
- the one on the top (with the kittens) is the new one
=> Build simple cube purchase app

webapp/app.py
- Expect account_id instead of subscription_id.
- Test with front-end
=> Fix typo cancel trial

webapp/advantage/models.py, webapp/advantage/ua_contracts/builders.py, webapp/advantage/ua_contracts/helpers.py
- Add user subscription id
- Login on the demo
- Go to /advantage/user-subscription 
- See id for each `UserSubscription`
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/273
=> Add user subscription id

templates/managed/index.html
Invoke modal from managed
Straightened the quote in the button
Check the code.
=> Invoke modal from managed

konf/site.yaml
See https://chat.canonical.com/canonical/pl/651ar557b7f7t8t9sscren9obc
=> Up to 10 replicas, for now

templates/ceph/index.html, templates/ceph/managed.html
- Update ceph main page
- Open the website https://ubuntu-com-10400.demos.haus/ceph
- Make sure that the changes matches the copy doc (link in the linked issue)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4423
=> Update the content of /ceph to match the copy doc

templates/16-04/index.html
- Updated the page https://ubuntu.com/16-04 to match the copy doc
- Go to the website: https://ubuntu-com-10412.demos.haus/16-04 
- Make sure that the changes on the copy doc (link in the issue) are applied
Fixes #10408
=> Update the content of /16-04 to match the copy doc

templates/security/esm.html
- Minor changes to match the copy doc
- Added a new column in the section "What is covered?"
- Added a new Q & A: "How to enable ESM?"
- Open the website: https://ubuntu-com-10410.demos.haus/security/esm
- Make sure that the changes matches the copy doc (link in the issue)
- Verify the newly added Q & A:  "How to enable ESM?" (with the code block)
Fixes #10407
=> Update the content of /security/esm to match the copy doc

.github/workflows/blog-links.yaml, .github/workflows/ceph-docs-links.yaml, .github/workflows/core-docs-links.yaml, .github/workflows/kubernetes-docs-links.yaml, .github/workflows/live-links.yaml, .github/workflows/openstack-charm-deployment-guide-docs-links.yaml, .github/workflows/openstack-charm-guide-docs-links.yaml, .github/workflows/security-links.yaml, .github/workflows/server-docs-links.yaml
- Increase the timeout when linkchecking to avoid discourse timeouts
- Check the code changes look good.
- Run the command locally
=> Increase the timeout when linkchecking

static/js/src/advantage/api/types.ts, static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/Content/types.ts, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.test.tsx, static/js/src/advantage/react/hooks/useUserSubscriptions.ts, static/js/src/advantage/tests/factories/api.ts
- Update selecting subscriptions to use the unique id.
- Visit [/advantage?test_backend=true](https://ubuntu-com-10405.demos.haus/advantage?test_backend=true).
- Click on some subscriptions in the list. The corresponding subscription details should be shown.
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/253.
=> Select subscriptions using their id

templates/robotics/ros-esm.html
- Update the content of https://ubuntu.com/robotics/ros-esm to match the copy doc
- Added a new section "Security maintenance you can trust"
- Go to the website: https://ubuntu-com-10382.demos.haus/robotics/ros-esm
- Make sure that all the new changes in the [copy doc](https://docs.google.com/document/d/1oiz_006n9U1Ya50wdSkKIyj_jsxSr92FdCpkDU4kpHs) are applied 
- Make sure that the new section is added and has the good styling
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4432
=> Copy update ros esm

templates/16-04/azure.html
- Updated the content of https://ubuntu.com/16-04/azure
- Go to the webiste https://ubuntu-com-10420.demos.haus/16-04/azure
- Make sure that the changes in the [copy doc](https://docs.google.com/document/d/1V99KwimN8Hla8L_CikNc6I0amqj99cSrBsVlAjIkBqE/edit#) are applied
Fixes #10416
=> Updated the page /16-04/azure (copy doc)

static/js/src/advantage/users/AccountUsers.tsx, static/js/src/advantage/users/app.tsx, templates/advantage/users/index.html
- display h1 before react app loads
- display loading spinner on initial fetch
- go to /advantage/users and login
- verify the spinner has been shown
https://github.com/canonical-web-and-design/commercial-squad/issues/277
=> Account users/incremental loading

static/js/src/openstack-deployment-chart.js, templates/openstack/consulting.html
- Updates pie-chart as per suggestions on the [copydoc](https://docs.google.com/document/d/1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/consulting or at https://ubuntu-com-10376.demos.haus/openstack/consulting
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10359
=> Update pie-chart with suggestions

static/js/src/cube/components/MicrocertificationsTable/MicrocertificationsTable.tsx, static/sass/_pattern_cube-table.scss
Fixes canonical-web-and-design/commercial-squad#250
- Styled the table to match the designs
- the cats are gone :sob: 
- 
- go to https://ubuntu-com-10438.demos.haus//cube/microcerts
- see that both tables look pretty much the same
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/250
=> Build the table layout

.github/workflows/pr.yaml, package.json, static/js/src/advantage/subscribe/react/APICalls/usePostCustomerInfoForPurchasePreview.tsx
- add missing FormValues import causing a TS error.
- add TypeScript check to GitHub actions to prevent such errors in the future
https://github.com/canonical-web-and-design/ubuntu.com/runs/3687925212
=> add TypeScript check to GitHub actions

static/js/src/advantage/subscribe/renderers/form-renderer.js, templates/advantage/subscribe/index.html
- Remove mentions of free trial at the top of /subscribe
- Go to https://ubuntu-com-10484.demos.haus/advantage/subscribe
- check that no there is no mention of free trials anywhere
=> Remove hide free trial header until we release it

navigation.yaml, templates/cloud/hybrid-cloud.html
- Build `/cloud/hybrid-cloud` page
- View the site locally in your web browser at: http://0.0.0.0:8001/cloud/hybrid-cloud 
- Please check page against [copy doc](https://docs.google.com/document/d/1oIggNSXR5sfl0Ab35x2NIL7I858I7QdPCUXeQI8IIPc/edit#) and [design](https://app.zeplin.io/project/6141d0b4743dc928767d815e/screen/61485017b52e5828498726fd).
- [Demo](https://ubuntu-com-10447.demos.haus/cloud/hybrid-cloud)
Fixes [#4413](https://github.com/canonical-web-and-design/web-squad/issues/4413)
=> Build /cloud/hybrid-cloud page

navigation.yaml, templates/kubernetes/docs/equinix.md, templates/kubernetes/docs/shared/_side-navigation.md
- added a page for Equinix metal installs
=> K8s: Add Equinix page

tests/cypress/advantage_spec.js
=> fix advantage cypress test

navigation.yaml, templates/cloud/hybrid-cloud.html, templates/cloud/multi-cloud.html
- Build /cloud/multi-cloud page
- Please check page against [copy doc](https://docs.google.com/document/d/1nWsDaRiUzaupjKDzu1ZqjlmxHGv2HCgW8oBBEacYFLs/edit#) and [design](https://app.zeplin.io/project/6141d0b4743dc928767d815e/screen/6149c055f798ec581c0f5431).
- [Demo](https://ubuntu-com-10466.demos.haus/cloud/multi-cloud)
Fixes [#4416](https://github.com/canonical-web-and-design/web-squad/issues/4416)
=> Build /cloud/multi-cloud page

tests/advantage/test_api.py, webapp/advantage/schemas.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/views.py, webapp/app.py
- Add endpoint to update default entitlements:
Endpoint: `PUT /advantage/contracts/{contract_id}/entitlements`
Json schema:
```
{
"entitlements": [
{
"type": String(required),
"is_enabled": Boolean(required),
}
]
}
```
- Will be easier when the front-end is ready
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/264
=> Add update default entitlements endpoint

static/js/src/advantage/subscribe/react/app.tsx, static/js/src/advantage/users/app.tsx
- add sentry to advantage/users
- add allowUrls, tracingOrigins to advantage/subscribe to fix error capturing
- add `<Sentry.ErrorBoundary>` for better capture of uncaught errors in the app
https://github.com/canonical-web-and-design/commercial-squad/issues/266
=> Add sentry to advantage/users

templates/kubernetes/compare.html, templates/kubernetes/index.html
- Made copy changes on `/index` as per: https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit#heading=h.8hni8w6zn8zi
- Added CTA on `/compare` as per: https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit#
- View the site locally in your web browser at: https://ubuntu-com-10443.demos.haus/kubernetes and https://ubuntu-com-10443.demos.haus/kubernetes/compare
- Check relevant pages against copydocs and see that all requested changes have been made
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10434
=> Cta copy update

webapp/cube/content/cube-qa.yaml, webapp/cube/content/cube.yaml
- Updated the content of ubuntu.com/cube/microcerts to match [the copy doc](https://docs.google.com/document/d/1IHmr2SIxcEKVNN2sA-z_32PV0fCXi38pmeVP7k7O1mM/edit#)
- Go the website: https://ubuntu-com-10465.demos.haus/cube/microcerts (it may ask you to login with SSO)
- Make sure that the content changes in [the copy doc](https://docs.google.com/document/d/1IHmr2SIxcEKVNN2sA-z_32PV0fCXi38pmeVP7k7O1mM/edit#) are applied
Fixes #10454
=> Updated the page /cube/microcerts

templates/azure/pro.html
- Updated the content of the page ubuntu.com/azure/pro to match [the copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#)
- Go to the website https://ubuntu-com-10458.demos.haus/azure/pro
- Make sure that the content changes in [the copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#) are applied
Fixes #10449
=> Updated the page /azure/pro

templates/aws/fips.html
- Updated the content of the page ubuntu.com/aws/fips to match [the copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit#)
- Go to the website https://ubuntu-com-10464.demos.haus/aws/fips
- Make sure that the content changes in [the copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit#) are applied
Fixes #10462
=> Updated the page /aws/fips

templates/azure/fips.html
- Updated the content of the page ubuntu.com/azure/fips to match [the copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit#)
- Go to the website https://ubuntu-com-10463.demos.haus/azure/fips
- Make sure that the content changes in [the copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit#) are applied
Fixes #10461
=> Updated the page /azure/fips

templates/gcp/pro.html
- Updated the content of the page ubuntu.com/gcp/pro to match [the copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit#)
- Go to the website https://ubuntu-com-10460.demos.haus/gcp/pro
- Make sure that the content changes in [the copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit#) are applied
Fixes #10452
=> Updated the page /gcp/pro

templates/aws/pro.html
- Updated the content of the page ubuntu.com/aws/pro to match [the copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#)
- Go to the website https://ubuntu-com-10459.demos.haus/aws/pro
- Make sure that the content changes in [the copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#) are applied
Fixes #10450
=> Updated the page /aws/pro

templates/kubernetes/docs/equinix.md
- Some small updates for equinix metal docs
=> K8s equinix doc updates

.github/workflows/cypress.yaml, cypress.env.template.json, tests/cypress/integration/forms_spec.js, tests/cypress/integration/navigation_spec.js, tests/cypress/plugins/index.js
- fix cypress login
- move spec files to `tests/cypress/integration` folder
- update cypress env template with marketo
Verify that all tests except forms have passed:
https://github.com/canonical-web-and-design/ubuntu.com/pull/10494/checks?check_run_id=3701632925
=> fix cypress login & navigation tests

templates/security/fips.html
- Small copy changes to `/security/fips`
- View page at: https://ubuntu-com-10498.demos.haus/security/fips
- Check against [copy doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit#) and resolve comments
Fixes #10493
=> Copy update on FIPS

templates/kubernetes/kubernetes-operations-survey.html
- Updated the page ubuntu.com/kubernetes/kubernetes-operations-survey to match the [copy doc](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit#)
- Go to the website https://ubuntu-com-10511.demos.haus/kubernetes/kubernetes-operations-survey
- Make sure that the changes in the [copy doc](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit#) and mark the discussion in the [doc](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit#) as done
Fixes #10506
=> Updated the page /kubernetes/kubernetes-operations-survey

templates/security/livepatch.html
- Updated the page ubuntu.com/security/livepatch to match the [copy doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#)
- Go to the webiste  https://ubuntu-com-10495.demos.haus/security/livepatch
- Make sure that the content changes in the [copy doc](https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#) are applied
Fixes #10486
=> Replace "Canonical livepatch" with "Ubuntu livepatch"

templates/blog/index.html, templates/blog/newsletter-form.html
Properly close the script tag in the newlettter form on blog
- Go to /blog
- See the articles are rendering after the newsletter sign up form
=> FIx the blog page rendering after newsletter

templates/kubernetes/kubernetes-operations-survey.html
Return to button to pop up the new survey.
- Open the demo at /kubernetes/kubernetes-operations-survey
- Click the "Take the survey" button
- See the survey loads
- Mkae sure the copy matches the [copy doc](https://docs.google.com/document/d/1MLNVczyhDYNnZT-4Ddq0D4D5YU5JcgRdt7hR4x7IOnQ/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4473
=> Enable the new k8s survey as a pop up

static/files/sitemap.xml, templates/base_index.html
Fix the live links across the site
- Check the code changes that fixes [these link errors](https://github.com/canonical-web-and-design/ubuntu.com/runs/3800463648)
=> Fix the live links across the site

templates/robotics/shared/_learn-more-about-robotics.html
- Updated as per [copy doc](https://docs.google.com/document/d/1JNFk2C0shH3DapKuJM8X0QfAiD1RzHvXoydn8P9mEMg/edit#)
- View the site locally in your web browser at: https://ubuntu-com-10752.demos.haus/robotics
- See the change has been made correctly and that the link works
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10740
=> Added new case study

templates/kubernetes/what-is-kubernetes.html
- Updated page as per [copy doc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#)
- View the site locally in your web browser at: https://ubuntu-com-10728.demos.haus/kubernetes/what-is-kubernetes
- Check against copy doc and see that all changes have been made
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4551
=> Update what is kubernetes

templates/download/xilinx/index.html
- Add get in touch button as requested in the [copy doc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit)
- View the site locally in your web browser at: http://0.0.0.0:8001/download/xilinx or https://ubuntu-com-10795.demos.haus/download/xilinx
- Please make sure to resolve the discussion in the [copy doc](https://docs.google.com/document/d/1DZxf-ZbJtyS69XQBslJry3Ien1FSHYLB2Qt78iRkhOs/edit) once the QA is done
Fixes #10792
=> add "get in touch"

templates/kernel/lifecycle.html, templates/shared/_kernel-support-schedule.html
- Made copy updates and removed 12.04 LTS instructions as per [copy doc](https://docs.google.com/document/d/1d01SFs7c56ge2o92g6Rwr3SjG8rtxm3jNwIyL1N8mQg/edit#heading=h.c8ycu0jdn8nw)
- View the site locally in your web browser at: https://ubuntu-com-10794.demos.haus/kernel/lifecycle
- Check against copy doc and ensure all changes have been correctly made
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10783
=> Made copy changes and removed 12.04 LTS tab

tests/cassettes/TestCube.test_microcerts_purchase.yaml, tests/test_cube.py
Added a mocked test for purchases
- `test-python` check should pass
- Check that the cassette doesn't contain sensitive data
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/259
=> Microcerts purchase test

templates/observability/what-is-observability.html
Revamp "What is observability" with new, snazzy observability glyphs.
=> What is observability images

static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
drive-by hotfix for the user roles
- amended new users dialog to make role descrtiption accurate
=> Copy amend to make tooltip accurate

.env, konf/site.yaml, webapp/advantage/decorators.py, webapp/cube/views.py
Reverts canonical-web-and-design/ubuntu.com#10788
To fix current 500 error on /cube/microcerts
Make sure https://ubuntu-com-10827.demos.haus/cube/microcerts and https://ubuntu-com-10827.demos.haus/cube/microcerts?test_backend=true are working as usual
=> Revert "Microcerts fix data inconsistencies across environments"

templates/security/cis.html
- [Sync text with copydoc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#)
=> CIS: sync the SEO parts of the copydoc

templates/containers/what-are-containers.html
- Updates cases of 'virtualization' to 'virtualisation'
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10815
=> Update to use British English spelling

templates/internet-of-things/index.html
- Upate based on [copydoc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.vjkro9g6t7si)
- Compare against [copydoc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.vjkro9g6t7si)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10833
=> Update "Ubuntu for the Internet of Things" copy

templates/openstack/managed.html, templates/shared/contextual_footers/_more_than_openstack.html, templates/shared/contextual_footers/_openstack_further_reading.html
- Update the page /openstack/managed as requested in the [copy update](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack/managed or https://ubuntu-com-10809.demos.haus/openstack/managed
- Please mark the discussion as resolved in the [copy doc](https://docs.google.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit#) once the QA is done
Fixes #10805
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workf …
=> copy update /openstack/managed

static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
fixes https://github.com/canonical-web-and-design/commercial-squad/issues/392
- copy edit on new user modal
Fixes #
=> make ui copy accurate

templates/security/index.html
- Updates 'index - security' as per [copydoc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/security 
- Compare against [copydoc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10847
=> Update 'index - security'

templates/engage/base.html
- Added specific code to noindex the ShellOnboarding engage page
- Go to /engage/ShellOnboarding, view source and see there is noindex in the header
- Go to /engage/SQLServerWebinarPart1, view source and see there is no noindex in the header
=> Apply noindex to the ShellOnboarding engage page

static/js/src/advantage/users/components/AddNewUser/AddNewUserForm.tsx
- Update user management role description
- The page is under maintenance but it's a copy change. How bad can I mess it up?
Fixes canonical-web-and-design/commercial-squad#400
=> Update user management role description

webapp/advantage/views.py
- If `technical` users try to go purchase a subscription they get access forbidden.
- Be a technical user
- Click the Buy Subscription button
- Get Access forbidden page.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/401
=> Fix technical 500 for trying to buy

static/js/src/ua-payment-methods.js, tests/cypress/integration/advantage/subscriptions_spec.js
- Fixed a runtime error when viewing /payment-methods without any default payment method
- Skipped tests requiring the test account to have actionable subscriptions
- Scroll down
- look at this 
- :tada: 
Fixes https://github.com/canonical-web-and-design/commercial-squad/issues/385
=> Fix broken advantage e2e tests

templates/gov/index.html
- Copy update on /gov
- Added `VPAT` in the `Security, accessibility and reliability` section
- Added pdf link
- View the site locally in your web browser at: http://0.0.0.0:8001/gov
- Please check page against [copy doc](https://docs.google.com/document/d/1umM1XMEzqeXklPkyCjDr98Q-RvwCcNNXgwNwfLoynTo/edit#) and resolve comments
- Demo : https://ubuntu-com-10885.demos.haus/gov
Fixes[#4554](https://github.com/canonical-web-and-design/web-squad/issues/4554)
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.h …
=> Copy update on /gov

templates/telco/magma.html
- Update copy on '/telco/magma' as per [copydoc](https://docs.google.com/document/d/1xDoW7wsw62lYYiMB5a6i4vJBzdUFjGiyXjRcnyplDGU/edit)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10904
=> Update copy on '/telco/magma'

navigation.yaml, templates/managed/index.html, templates/observability/managed.html, templates/shared/forms/interactive/managed-observability.html, templates/shared/forms/interactive/managed-services.html
- Built new `/observability/managed` page as per [copy doc](https://docs.google.com/document/d/1N11otwvy2TWoK4j9e8iYJLNLYQyWbIPL82GVkm8WHhE/edit#heading=h.mhbttlbulk4)
- View the site locally in your web browser at: https://ubuntu-com-10862.demos.haus/observability/managed
- Compare against copy doc 
- Test ctas and ensure that they and the forms they link to work correctly
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4578
https://github.com/canonical-web-and-design/web-squad/issues/4579
https://github.com/canonical-web-and-design/web-squad/issues/4581
=> Observability managed build

templates/observability/index.html
- Updated as per [copy doc](https://docs.google.com/document/d/1NxJdT3BD6EWnpsu-eathNyranQVImnDGhuCjzsIWh4s/edit#heading=h.olm94bbyu9dm)
- View the site locally in your web browser at: https://ubuntu-com-10883.demos.haus/observability
**NOTE: PAGE MUST BE MERGED IN CONJUNCTION WITH [NEW PAGE](https://github.com/canonical-web-and-design/ubuntu.com/pull/10862)**
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4580
=> Removed mid sections and updated remaining copy

templates/observability/what-is-observability.html
- Copy docs changes for "What is observability"
Implements recent copy doc changes.
=> Copy doc changes for "What is observability?"

templates/shared/forms/interactive/managed-services.html
- Removed typo preventing form submit
- View the site locally in your web browser at: https://ubuntu-com-10929.demos.haus/managed
- Check form submits
=> fixed form id value

static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx, static/js/src/advantage/react/utils/currencyFormatter.ts, static/js/src/advantage/react/utils/index.ts
- Added a preview of what will happen if the user decides to resize
- Moved the formatter to utils
- go to 
- select a subscription (works best with monthly ones because they can go up and down)
- click on Edit subscription
- change the number
- see that it previews how the change will affect your subscription.
Fixes canonical-web-and-design/commercial-squad#387
=> Display new price when resizing

templates/telco/osm/index.html
- Update copy doc on `/telco/osm`
- Please check page against [copy doc](https://docs.google.com/document/d/1LQim0WRVdDZE9-ToFKSD52O7kgurMoytrgDDAPYnug8/edit#) and resolve comments
Fixes [#4640](https://github.com/canonical-web-and-design/web-squad/issues/4640)
=> Update copydoc on /telco/osm

.github/workflows/live-links.yaml
- Migrated the live-links check from linkchecker to linkcheckerrc
- Disable SSL certificate checking to hide external cert issues
=> Disable the SSL check on live link checking

static/js/src/chart-data.js, templates/about/release-cycle.html
- Updated as per [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#)
- Check against doc and make sure all changes have been made
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10898
=> Release cycle update

templates/telco/osm/onboarding-network-functions.html
- Copy update on `/telco/osm/onboarding-network-functions`
- View the site locally in your web browser at: http://0.0.0.0:8001/telco/osm/onboarding-network-functions
- Please check page against [copy doc](https://docs.google.com/document/d/1_35nO3riTFlSFSp2B7FFdl60cjZe7Owwv0bcjY1s8Kg/edit) and resolve comments
Fixes [#4641](https://github.com/canonical-web-and-design/web-squad/issues/4641)
=> Copy update on /telco/osm/onboarding-network-functions

templates/core/index.html
- Update logo on /core
- Please check page against [copy doc](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit) and resolve comments
Fixes [#4644](https://github.com/canonical-web-and-design/web-squad/issues/4644)
=> Update logo on /core

navigation.yaml, tests/cypress/integration/advantage/users_spec.js
- enable users management
-  reverts https://github.com/canonical-web-and-design/ubuntu.com/pull/10759/files
Fixes #
=> enable users management

templates/robotics/shared/_learn-more-about-robotics.html
- Copy update on /robotics
- Please check page against [copy doc](https://docs.google.com/document/d/1JNFk2C0shH3DapKuJM8X0QfAiD1RzHvXoydn8P9mEMg/edit#) and resolve comments
Fixes [#10940](https://github.com/canonical-web-and-design/ubuntu.com/issues/10940)
=> Copy update on /robotics

templates/desktop/developers.html
- Copy update on `/desktop/developers`
- Please check page against [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#) and resolve comments
Fixes #10949 
=> Copy update on /desktop/developers

templates/robotics/community.html
- Copy update on `/robotics/community`
- Please check page against [copy doc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit#) and resolve comments
- [Demo](https://ubuntu-com-10954.demos.haus/robotics/community)
Fixes #10939 
=> Copy update on `/robotics/community`

navigation.yaml, templates/internet-of-things/smart-city.html
**NOTE** Waiting on a datasheet link 
- Builds /smart-city page as per [copydoc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY/edit#)
- Adds to /iot navigation
- View the site locally in your web browser at: http://0.0.0.0:8001/iot/smart-city
- Compare against [copydoc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4631
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messa …
=> Build '/smart-city' page

templates/download/iot/intel-iotg.html
- Updated link URLs
- Please check page against [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit) and resolve comments
Fixes #10930 
=> Copy update on /download/iot/intel-iotg 

templates/edge-computing/index.html
- Add link to new /smart-city page on /edge-computing
=> Add link to new /smart-city page on /edge-computing

templates/containers/what-are-containers.html
- Update assets on `/containers/what-are-containers`
- View the site locally in your web browser at: http://0.0.0.0:8001/containers/what-are-containers
- Please check page against [copy doc](https://docs.google.com/document/d/1hStuIzY8dDdFEW4Q0TwboOx0_-SB5klk8zRuNIn3V4o/edit#) and resolve comments
- [Demo](https://ubuntu-com-10937.demos.haus/containers/what-are-containers)
Fixes [#4638](https://github.com/canonical-web-and-design/web-squad/issues/4638)
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/commit-messages.htm …
=> Copy update on /containers/what-are-containers

templates/internet-of-things/smart-city.html
- Fix broken links on '/smart-city'
- Add alt text to images
- Update logo sizes
- Add form ID
- Check the links "container confinement" and "kernel livepatch" go to the right places
- Compare against [copydoc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10977
=> Fix broken links on '/smart-city'

templates/security/docker-images.html, templates/shared/forms/interactive/docker-images.html
- Build interactive docker-image contact form and update it on `/security/docker-images`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/docker-images
- Click the `Get commercial support` button on the `/security/docker-images` page and please check if the form works well
- compare against this [Doc](https://docs.google.com/document/d/1jl1ibouMLPGNb_KOrF26VpVpUjMudaJxKbTRSBs8Doc/edit#heading=h.jsqxpsz4c39k)
Fixes [#10982](https://github.com/canonical-web-and-design/ubuntu.com/issues/10982) …
=> Build docker-image contact form

templates/security/cis.html
- Synced with copydoc to add missing word
=> cis: added missing word

templates/financial-services/index.html
- Updates casestudy link on '/financial-services' as per [copydoc](https://docs.google.com/document/d/1SEd2nV0GplBTG4lZ9RuhjNXrphU22nGP4Fpgd5g_9BQ/edit#)
- Check the link goes to the right place
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4662
=> Update casestudy link on '/financial-services'

templates/gcp/pro.html
- View the site locally in your web browser at: http://0.0.0.0:8001/gcp/pro
- Please check page against [copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit) and resolve comments
Fixes [#4667](https://github.com/canonical-web-and-design/web-squad/issues/4667)
=> Copy update on /gcp/pro

templates/download/iot/intel-iotg.html
- Update links on /download/iot/intel-iotg
- View the site locally in your web browser at: http://0.0.0.0:8001/download/iot/intel-iotg
- Please check if the updated links work
- Please check page against [copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit) and resolve comments
Fixes [#4668](https://github.com/canonical-web-and-design/web-squad/issues/4668)
=> Update links on /download/iot/intel-iotg

templates/advantage/index.html, webapp/advantage/views.py
- Hide shortcuts from technical users
- Be admin
- See shortcuts
- Be billing user
- See shortcuts
- Be technical
- See no shortcuts
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/408
=> Hide shortcuts from technical

templates/ceph/index.html
- Copy update on `/ceph`
- Please check page against [copy doc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit#) and resolve comments
Fixes [#10970](https://github.com/canonical-web-and-design/ubuntu.com/issues/10970)
=> Copy update on /ceph

templates/internet-of-things/smart-city.html, templates/shared/forms/interactive/internet-of-things.html, templates/shared/forms/interactive/smart-city.html
- Created new contact form as per [copy doc](https://docs.google.com/document/d/1gf-K0hcj5F4JQ8DCwMuaKcnLwaiuSqBpscgg_-eZuCg/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11005.demos.haus/internet-of-things/smart-city#get-in-touch
- Attempt to fill out and submit form without error
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4669
=> Smart city contact form

static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewButton/RenewButton.tsx, static/js/src/advantage/subscribe/blender/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, templates/desktop/partners.html, templates/kubernetes/docs/operations.md
- replaced "with with" with "with" (say that 10 times quickly)
- fixed some formatting on `operations.md`
Fixes canonical-web-and-design/commercial-squad#439
=> Fix "with with" typo

templates/security/fips.html
- Updated /security/fips according to changes in [copy doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit#)
- View the demo in your web browser at: https://ubuntu-com-11022.demos.haus/security/fips
- See that the page includes the changes listed in the copy doc
Fixes [#4680](https://github.com/canonical-web-and-design/web-squad/issues/4680)
=> Update /security/fips copy

templates/azure/pro.html
- Copy update on `/azure/pro`
- Please check page against [copy doc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#) and resolve comments
Fixes [#4666](https://github.com/canonical-web-and-design/web-squad/issues/4666)
=> Copy update on /azure/pro

.github/workflows/live-links.yaml
=> Ignore adlinktech URL from linkchecker

templates/security/index.html
- [Updated the datasheet to the latest on cybersecurity]
=> updated to the latest security datasheet

templates/aws/pro.html, templates/gcp/pro.html
- Copy update on on `/aws/pro` and `/gcp/pro`(Some texts were not updated with this previous [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10999) for the `/gcp/pro` page so I've just made some updates on this current PR together as it is a minor change) 
- View the site locally in your web browser at: http://0.0.0.0:8001/aws/pro and http://0.0.0.0:8001/gcp/pro
- Please check page against 1) /aws/pro : [copy doc](https://docs.google.com/document/d/1pLRWJZSpE04nYt-yHBtCjxGI7VZsigcP2UJIBmR8i-0/edit#) 2) /gcp/pro [copy doc](https://docs.google.com/document/d/1zR1m6CH1POU5tnzNzgNYanG2_EGQtKVNR3_dPew1pf4/edit) and resolve …
=> Copy update on /aws/pro and /gcp/pro

templates/azure/fips.html
- Copy update on `/azure/fips` 
- View the site locally in your web browser at: http://0.0.0.0:8001/azure/fips
- Please check page against [copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit) and resolve comments
Fixes [#4682](https://github.com/canonical-web-and-design/web-squad/issues/4682)
=> Copy update on /azure/fips

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/ListCard/ListCard.test.tsx, static/js/src/advantage/react/utils/formatDate.test.ts, static/js/src/advantage/react/utils/formatDate.ts
- update date format to dd MMM yyyy
- Check out those date formats!
Fixes canonical-web-and-design/commercial-squad#421
=> Change date format on subscription

tests/cypress/cypress.json
- increase cypress page load timeout
- remove invalid formFolder configuration option
=> increase cypress page load timeout

templates/security/index.html
- Copy update on `/security`
- Please check page against [copy doc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#) and resolve comments
Fixes #11042 
=> Copy update on /security

templates/ceph/what-is-ceph.html
- Check /ceph/what-is-ceph against [copy docs](https://docs.google.com/document/d/1gRuOAg6ZFBp-ikMq-DQBgQ4-BrXGeWOOe2cBxD3ohjE/edit#)
You'd have to check all the content, because the comments have been removed
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10969
=> Copy updates for ceph/what-is-ceph

templates/security/index.html
- This updates the security datasheet to the latest version
=> updated link to security datasheet

templates/model-driven-operations/_base_model.html, templates/model-driven-operations/index.html, templates/templates/footer.html, templates/templates/navigation-developer-h.html, templates/templates/navigation-enterprise-h.html
- Built new page as per [copy doc](https://docs.google.com/document/d/1G4sSrM-FQIL2c1Uj8PvW6oGUKcJ9HAK5TwnKhFa4sOY/edit#)
- Added page to #enterprise nav
- Added page to #developer nav
- Added page to footer
- View the site locally in your web browser at: https://ubuntu-com-11026.demos.haus/model-driven-operations
- Check against copy doc and see all changes have bee made
- Test nav and footer links and see that they all work as expected
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4679
=> Model-driven-operations build

templates/observability/what-is-observability.html
Small copy change using one of the [new observability icons](https://github.com/canonical-web-and-design/brand-squad/issues/627#issuecomment-993484902). Changes already reflected in the [copy document](https://docs.google.com/document/d/1eoqDQzFiRJY2u_EO4JBuLBLqae4K3nrEf3qd88KHw0Y/edit#heading=h.extcyact92z9).
N/A …
=> /observability/what-is-observability: add production profiling to telemetry types

templates/managed/apps/cassandra.html, templates/shared/contextual_footers/_managed_further_reading.html
- Update further reading on `/managed/apps/cassandra`
- View the site locally in your web browser at: http://0.0.0.0:8001/managed/apps/cassandra
- Please check page against [copy doc](https://docs.google.com/document/d/1iYMH1ISY4uDtr3ZzH0f_hnEzvqaeufO43z__cMxs0vQ/edit#) and resolve comments
- [Demo](https://ubuntu-com-11035.demos.haus/managed/apps/cassandra)
Fixes [#4696](https://github.com/canonical-web-and-design/web-squad/issues/4696)
=> Update further reading on /managed/apps/cassandra

templates/kubernetes/install.html, templates/shared/forms/interactive/kubernetes.html, templates/shared/forms/interactive/managed-kubernetes.html
- Copy update on `/kubernetes/install`
- Update contact forms for kubenetes pages
- Please check page against [copy doc](https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit#) and resolve comments and this [doc](https://docs.google.com/document/d/1u6IkVfDNNwdz4XgHU6FSCnUFfVtfTMNMmtINIPT31cU/edit#) for the contact form
Fixes #11043
=> Copy update on /kubernetes/install

templates/internet-of-things/edgex.html
- Page refresh on `/internet-of-things/edgex`
- Please check page against [copy doc](https://docs.google.com/document/d/17tvfJBC5VncEVWkEsbyW_slAFFSoWV3jQUN7sa8nkOs/edit) and resolve comments
Fixes [#4653](https://github.com/canonical-web-and-design/web-squad/issues/4653)
=> Copy update on /internet-of-things/edgex

templates/model-driven-operations/index.html
=> /model-driven-operations: Fix mispelling in CTA

templates/internet-of-things/smart-city.html
Update link in '/smart-city' as per [copydoc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4726
=> Update link in '/smart-city'

templates/core/index.html
Ubuntu Core for secure embedded Linux copy update
- Check https://ubuntu-com-11066.demos.haus/core against [copy docs](https://docs.google.com/document/d/1QoM0Yqx4JfDJ2G3OPt5bds-ximG1jASmU_PWX4iff3E/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4725
=> Ubuntu Core for secure embedded Linux copy update

templates/embedded/index.html
- Copy update on `embedded`
- View the site locally in your web browser at: http://0.0.0.0:8001/embedded
- Please check page against [copy doc](https://docs.google.com/document/d/15Tz87YRg4SnX4DWGOSl2TDTHLSStJoma879xHnF0nuo/edit) and resolve comments
Fixes [#4727](https://github.com/canonical-web-and-design/web-squad/issues/4727)
=> Copy update on /embedded

templates/model-driven-operations/index.html
=> /model-driven-operations: Copy changes from Rob

templates/internet-of-things/index.html
- Copy update on `/internet-of-things`
- Please check the page against [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit) and resolve comments
- Demo starting at https://ubuntu-com-11073.demos.haus/internet-of-things
Fixes [#4730](https://github.com/canonical-web-and-design/web-squad/issues/4730)
=> Copy update on /iot

.github/workflows/ceph-docs-links.yaml, .github/workflows/core-docs-links.yaml, .github/workflows/kubernetes-docs-links.yaml, .github/workflows/openstack-charm-deployment-guide-docs-links.yaml, .github/workflows/openstack-charm-guide-docs-links.yaml, .github/workflows/server-docs-links.yaml
Disable the linkchecking jobs
Check schedules are removed from the linkchecking cron jobs
=> Disable the linkchecking jobs

build.js, navigation.yaml, static/js/src/advantage/offers/Offers.tsx, static/js/src/advantage/offers/app.tsx, static/js/src/advantage/offers/components/OffersList.tsx, templates/advantage/offers/index.html
- created basic app for offers
- created empty state
- go to https://ubuntu-com-11050.demos.haus/advantage/offers
- check that it renders correctly
I can't manage to make the nav "suppressed" like we discussed @anthonydillon 
Fixes canonical-web-and-design/commercial-squad#434
=> Sharable cart referral link - create new page

templates/observability/what-is-observability.html
- Clean up the META, add ALT with the relevant keywords based on suggestions by [Moz](https://analytics.moz.com/pro/research/page-grader?keyword=what%20is%20observability&url=https%3A%2F%2Fubuntu.com%2Fobservability%2Fwhat-is-observability)
Fixes the lack of Rank #1 on the [SEO Dashboard](https://datastudio.google.com/u/0/reporting/07ad6bee-cd8b-47b1-ad41-978aacccdfe0/page/rPmpB?mkt_tok=MDY2LUVPVi0zMzUAAAF8USKndkHzSYYjJAJze2BYJniiG8arGmrGxG2ah6yg_s2k-wzd9XsYKQ0RYmHAyRBOm7Oo9diZQ-k7Q5k1_ZqKL …
=> SEO optimization for "what-is-observability"

templates/internet-of-things/appstore.html
Copy updates for iot/appstore
- Check https://ubuntu-com-11070.demos.haus/internet-of-things/appstore against  [copy docs](https://github.com/canonical-web-and-design/web-squad/issues/4731)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4731
=> Copy updates for iot/appstore

templates/security/index.html
- [Synced with the copydoc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit)
=> security: link to the security webinar

konf/site.yaml
- Split discourse docs for ubuntu.com, mainly to investigate production issues
=> Split services for ubuntu.com

konf/site.yaml
- Add missing path to k8s config
- Fix takeovers.json
=> Add missing path to k8s config

konf/site.yaml
- Added security and advantage to k8s
=> Added security and advantage to k8s

.github/workflows/ceph-docs-links.yaml, .github/workflows/core-docs-links.yaml, .github/workflows/kubernetes-docs-links.yaml, .github/workflows/openstack-charm-deployment-guide-docs-links.yaml, .github/workflows/openstack-charm-guide-docs-links.yaml, .github/workflows/server-docs-links.yaml
Reverts canonical-web-and-design/ubuntu.com#11075
=> Revert "Disable the linkchecking jobs"

tests/advantage/fixtures/offer.json, tests/advantage/fixtures/offers.json, tests/advantage/test_parsers.py, webapp/advantage/models.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/ua_contracts/parsers.py, webapp/advantage/views.py
- Update the endpoint /advantage/offers.json to return a cleaner response
- Use demo or pull changes
- Login to an account that has offers
- Go to /advantage/offers.json
- See the offer schema is correct
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/453
=> Update offers endpoint

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsTabs/DetailsTabs.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
- Update support link from support.canonical.com to portal.support.canonical.com
- Use demo or pull changes
- Login
- Check portal link that it works
Fixes #
=> Update support link

redirects.yaml
- Set up a redirect from “Get started with MicroStack” tutorial and all its anchors to `/openstack/tutorials`
- Set up a redirect from “Install single-server OpenStack with conjure-up” tutorial and all its anchors to `/openstack/tutorials`
- Go to “Get started with MicroStack” tutorial and check all redirects to `/openstack/tutorials`
- Go to “Install single-server OpenStack with conjure-up” tutorial and check all redirects to `/openstack/tutorials`
Fixes [#4752](https://github.com/canonical-web-and-design/web-squad/issues/4752)
[QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html) - [Commit guidelines](https://canonical-web-and-design.github.io/practices/workflow/co …
=> Set up redirects to /openstack/tutorials

webapp/advantage/models.py
- Fix account id for offers
- Go to demo and login
- Go to /advantage/offers.json
- You will find account_id
=> Fix account id for offers

webapp/advantage/views.py
- Filter out offers that are inactionable
- Go to demo
- login
- go to /advantage/offer
- once you buy an offer, the offer becomes inactionable and disappears
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/460
=> Filter out inactionable offers

templates/security/disa-stig.html
**BLOCKED:**  The `/security/certification/docs/disa-stig` page needs to be built before merging this PR. This PR will go live on Jan 14th.
- Copy update on `/security/disa-stig`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/disa-stig
- Please check page against [copy doc](https://docs.google.com/document/d/1zJwZzc-cERj9YKNXFtmrXwynJptyT7-D3qCNzBctRfo/edit#) and resolve comments
Fixes [#4739](https://github.com/canonical-web-and-design/web-squad/issues/4739) …
=> Copy update on /security/disa-stig

templates/openstack/index.html
- Update meta data on `/openstack`
- Please check page against [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#) and and resolve comments
Fixes [#4764](https://github.com/canonical-web-and-design/web-squad/issues/4764)
=> Update meta data on `/openstack`

templates/ceph/install.html
- Update contact us link
- View the site locally in your web browser at: http://0.0.0.0:8001/ceph/install
- Please check page against [copy doc](https://docs.google.com/document/d/1EmOtHjuEMKhVLQA7GwyrKfCzOKfc8UCEyh-p04-PxzA/edit) and and resolve comments
- [Demo](https://ubuntu-com-11152.demos.haus/ceph/install)
Fixes [#4750](https://github.com/canonical-web-and-design/web-squad/issues/4750)
=> Update CTA link

tests/advantage/test_api.py, webapp/advantage/ua_contracts/api.py, webapp/advantage/views.py
- Change cancellation feature. Cancellations are technically a downsize to 0. Before it used to have an extra step of logic where if the user cancelled the last stripe user subscription then we cancel the subscription completely. With the new downsize rule, the stripe subscription cancellation is no longer necessary
- Buy a monthly subscription
- Upsize 
- Downsize
- Upsize
- Cancel
- Did it work?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/444
=> Change cancellation feature

tests/advantage/test_parsers.py, webapp/advantage/ua_contracts/parsers.py
- Fix offer price. Instead of sending the price per unit, send the total per item.
- Use the demo link to login
- go to /advantage/offers.json
- the price should be updated
=> Fix offer price

templates/security/index.html
- Updated copy on /security
- Compare against [copydoc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4781
=> Update copy on /security

templates/kubernetes/docs/upgrading.md
- Update internal links for upgrades
Fixes https://github.com/charmed-kubernetes/kubernetes-docs/issues/632
=> Update K8s upgrade page

templates/core/index.html, templates/core/stories.html, templates/robotics/shared/_download-make-strip.html
Grammar and code syntax corrections
- Check https://ubuntu-com-11164.demos.haus/core and https://ubuntu-com-11164.demos.haus/core/stories footer area the following replacement:
"Try Ubuntu Core 20 on one of a popular development board" -> "Try Ubuntu Core 20 on a popular development board"
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4780
=> Gramatical correction on UC

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/advantage/offers/app.tsx, static/js/src/advantage/offers/components/BuyButton.tsx, static/js/src/advantage/offers/components/Offer/Offer.test.tsx, static/js/src/advantage/offers/components/Offer/Offer.tsx, static/js/src/advantage/offers/components/Summary.tsx, static/js/src/advantage/offers/hooks/usePurchaseOffer.tsx, static/js/src/advantage/offers/tests/factories/offers.ts, static/js/src/advantage/offers/types.ts, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/hooks/usePendingPurchase.tsx, templates/advantage/offers/index.html
- Open the payment modal and allow users to purchase offers when they click buy
- go to https://ubuntu-com-11161.demos.haus/advantage?test_backend=true 
- login with an account that has offers available
- go to https://ubuntu-com-11161.demos.haus/advantage/offers?test_backend=true
- try to buy an offer
- it should work correctly and redirect you to /advantage
=> Shareable cart link, buy offers

templates/legal/modern-slavery-statement/_base_markdown.html, templates/legal/modern-slavery-statement/index.md
- Add modern slavery statement 2022 link to `/legal/modern-slavery-statement`
- View the site locally in your web browser at: http://0.0.0.0:8001/legal/modern-slavery-statement
- Please check page against [copy doc](https://docs.google.com/document/d/16q1jDEr_ArWdCnWzEVuXmC66deXeCnuEHy2G_jX0hqE/edit) and resolve comments
Fixes [#4782](https://github.com/canonical-web-and-design/web-squad/issues/4782)
=> Add modern slavery statement 2022

templates/observability/managed.html
=> /observability/managed: Fix typo

templates/security/index.html
- Corrected the link to the datasheet [to match the copydoc](https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit)
=> Corrected the link to the datasheet

templates/security/cis.html
- Copy update on `/security/cis`
- View the site locally in your web browser at: http://0.0.0.0:8001/security/cis
- Please check page against [copy doc](https://docs.google.com/document/d/1bSv8lV9BJoBYh5yog2eYKtvNMitKZetSSBQ3k2Cu5Cw/edit#) and resolve comments
- Demo at https://ubuntu-com-11177.demos.haus/security/cis
Fixes [#4784](https://github.com/canonical-web-and-design/web-squad/issues/4784)
=> Copy update on /security/cis

static/js/src/advantage/react/components/Subscriptions/SubscriptionEdit/SubscriptionEdit.tsx
Change the copy according to the new docs
- log in on https://ubuntu-com-11178.demos.haus/advantage?test_backend=true
- click edit on a monthly subscription
- check that the copy matches the design and there is no typo
Fixes canonical-web-and-design/commercial-squad#473
=> Change resize helper copy

tests/cypress/forms/forms_spec.js
- Remove e2e tests for /advantage beta form
- Tests should pass
=> Remove tests for advantage beta form

templates/cube/study/virtualisation/part-3.md
=> Changed "LXD documentation" URL

entrypoint
Reverts canonical-web-and-design/ubuntu.com#11212
=> Revert "Run the site with 3 gunicorn workers"

webapp/shop/advantage/views.py, webapp/shop/decorators.py
- Remove use of  `flask.g` on the advantage decorator
- Go to /advantage and make sure everything works as before.
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/480
=> Remove flask g

templates/base_index.html
- Update `ESX` to `ESXi`
- Update link of "Super fast install"
- Please check page against [copy doc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#) and resolve comments 
Fixes [#4811](https://github.com/canonical-web-and-design/web-squad/issues/4811)
=> Copy update on base_index

templates/contact-us/index.html
Quick fix: format of address
Check the code.
=> Quick fix: format of address

templates/legal/ubuntu-advantage-service-description/index.md, templates/legal/ubuntu-advantage-service-description/ja/index.html
Correct SLA levels for managed services in UASD
- Check correct levels display on:
- https://ubuntu-com-11237.demos.haus/legal/ubuntu-advantage-service-description
- https://ubuntu-com-11237.demos.haus/legal/ubuntu-advantage-service-description/ja
Fixes #11236
=> Correct SLA levels for managed services in UASD

redirects.yaml, static/js/src/advantage/api/contracts.js, tests/cypress/integration/advantage/subscribe_spec.js, webapp/app.py, webapp/shop/advantage/views.py, webapp/shop/views.py
- Move common endpoints of advantage and CUBE in /shop/views
- These are mostly account related endpoints used by the modal 
- Make a UA and a CUBE purchase. Does it work? 
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/481
=> Move common view function outisde

templates/legal/data-privacy/survey.md
- Updated copy on /legal/data-privacy/survey from the [copy doc](https://docs.google.com/document/d/164IVIF3f8Prh7MTl8gTDal0jaPJt15PxdhMKToFhMu8/edit) (you might need edit permissions to see the suggested changes - let me know if so)
- View the site in your web browser at: https://ubuntu-com-11245.demos.haus//legal/data-privacy/survey
- See that the copy matches the suggestions made by Lydia
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4819
=> update data-privacy/survey copy

webapp/shop/advantage/views.py, webapp/shop/cube/views.py, webapp/shop/decorators.py, webapp/shop/views.py
- Merge `cube_decorator` and `advantage_decorator` together since they have very similar rules.
- Anything exploding?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/479
=> Create shop decorator

templates/managed/apps/index.html
- Removed some out of date listings
- Replaced a listing
APPSPM-85
=> Refresh managed apps

requirements.txt
- Updated to flask-base 1.0.1, and removed two dependencies [it's now pinning](https://github.com/canonical-web-and-design/canonicalwebteam.flask-base/commit/b925ff837f418d2e97de8531a6146e9a28c0f82d)
- `dotrun` or `./run` the project
- It should build successfully, and the checks on this PR should pass
=> update to flask-base 1.0.1

webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/decorators.py
- Create `AdvatnageMapper` class. A mask for the `ua-contracts` API that delivers us exactly what we'd ideally like the API to provide us.
- Go to /advantage. Does it explode?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/512
=> Create AdvantageMapper class

templates/robotics/community.html
- Updated video link as per [copy doc](https://docs.google.com/document/d/1A3iBoD_AAoerI0VwbByl8fR55ljNOjamHtJlkOuaaeA/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/robotics/community 
or via demo at  https://ubuntu-com-11276.demos.haus/robotics/community
- Check that the video loads as expected
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4845
=> Update state of robotics video

templates/security/fips.html
- Updated /security/fips based on the [copy doc](https://docs.google.com/document/d/1moTJCAtFXKD7ZXrxB-EB7GPVyZRTSIdkP-0BhPZl69M/edit)
- View the site in your web browser at: https://ubuntu-com-11277.demos.haus/security/fips
- See that the changes match the comments in the copy doc (and that the new links work)
Fixes [#4844](https://github.com/canonical-web-and-design/web-squad/issues/4844)
=> Update copy on /security/fips

templates/telco/index.html
- Updated /telco with links requested by Julie in the [copy doc](https://docs.google.com/document/d/1a3otoXCbXtddJG2HCnYIIHJiDxvG-pzFPtLobVB4-vw/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/telco
- See that the links match the comments in the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4850
=> Update links on /telco

templates/cube/index.html
- Update copy on /cube
- Open the [demo](https://ubuntu-com-11298.demos.haus/cube)
- Verify that the text on the page matches the [copy doc](https://docs.google.com/document/d/1QuhO-9FEOGLrYp8bErS_9snqdljl7d6tFAUoNQxoVDQ/edit#heading=h.kxbz60mtntuz)
=> Update copy on /cube

static/js/src/navigation.js, static/sass/_pattern_navigation.scss, templates/templates/_menu_section.html
- Updates styles to match that of vanilla-3.0
**note** most styles had already been updated
- Check navigation looks and works as expected
https://github.com/canonical-web-and-design/web-squad/issues/4855
=> Update p-navigation styles to vanilla-3.0

templates/16-04/index.html, templates/account/invoices/index.html, templates/aws/fips.html, templates/azure/fips.html, templates/certified/model-details.html, templates/cpu-compatibility/index.html, templates/cube/index.html, templates/cube/microcerts.html, templates/kernel/variants.html, templates/kubernetes/compare.html, templates/kubernetes/install.html, templates/openstack/features.html
- Mostly changing aria-labels to data-headings, Please give them a read to check they make sense and make any changes you think
appropriate.
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4856
=> Update tables to use vanilla-3.0 patterns

templates/security/cve/cve.html, webapp/security/views.py
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11307
QA
--
Go to https://ubuntu-com-11334.demos.haus/security/CVE-2021-43850, check it loads.
=> Support CVEs without publish date

templates/telco/index.html
- Updates an image on`/telco`
- Minor character changes
- Compare against [copydoc](https://docs.google.com/document/d/1a3otoXCbXtddJG2HCnYIIHJiDxvG-pzFPtLobVB4-vw/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4885
=> Update micro-clouds image on /telco

static/sass/styles.scss, templates/advantage/_table.html, templates/advantage/index-no-login.html
- Update advantage table to include 'free' column.
- Update advantage-table style
- Compare against [copydoc](https://docs.google.com/document/d/1So3n5HEpBX39xxEkkChnve09gKSr9TgYUcbfdOTCevk/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4888
=> Update 'Ubuntu Advantage Plans' table on /advantage

templates/ai/index.html
- Upsates `/ai` as per [copydoc](https://docs.google.com/document/d/1HP9YdHF11yVQ9SLl0VXhLezDZREsr1GHIKNi9wT1Gv0/edit#heading=h.3o08mrwri4n0)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4896
=> Update /ai as per copydoc

templates/openstack/features.html
- Update /openstack/features as per [copydoc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
- Compare against [copydoc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4903
=> Update /openstack/features as per copydoc

templates/core/features/secure-boot.html
- Updates copy on '/core/features/secure-boot'
- Compare against [copydoc](https://docs.google.com/document/d/1ltH7T2boIJ7VcUni4Kmc0XGlmmxWAf5u82LEwkEGP24/edit#heading=h.tsd6rpz4pmhm)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4897
=> Updates copy on '/secure-boot'

templates/ai/what-is-kubeflow.html
- Remove repeating sections that appeared during a rebase
=> Remove repeating sections

templates/kubernetes/docs/1.16/release-notes.md, templates/kubernetes/docs/1.17/release-notes.md, templates/kubernetes/docs/1.18/release-notes.md, templates/kubernetes/docs/1.19/release-notes.md, templates/kubernetes/docs/1.20/release-notes.md, templates/kubernetes/docs/1.21/release-notes.md, templates/kubernetes/docs/1.22/release-notes.md, templates/kubernetes/docs/1.23/release-notes.md, templates/kubernetes/docs/install-manual.md, templates/kubernetes/docs/operations.md, templates/kubernetes/docs/release-notes-historic.md, templates/kubernetes/docs/release-notes.md
- Remove links to store entries which no longer exist
- Update reference about downloading bundles
Fixes #11242 
=> k8s: fix store 404s

templates/containers/what-are-containers.html
- Update link on`/containers/what-are-containers`
- Remove 'p-link--external` classes
- Please compare page with [copy doc](https://docs.google.com/document/d/1hStuIzY8dDdFEW4Q0TwboOx0_-SB5klk8zRuNIn3V4o/edit#)
Fixes [#4950](https://github.com/canonical-web-and-design/web-squad/issues/4950)
=> Update link on`/containers/what-are-containers`

templates/wsl/index.html
- Minor changes on '/wsl', see [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#heading=h.c6wjbvvp8mcm)
- Go to https://ubuntu-com-11388.demos.haus/wsl
- Compare against [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#heading=h.c6wjbvvp8mcm)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4961
=> Update '/wsl' as per copydoc

static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx
- Change `Subscription` to `Token`
- Login to /advantage 
- Subscription is now Token
Fixes #https://github.com/canonical-web-and-design/ubuntu.com/issues/11357
=> Change subscription to token

templates/kubernetes/what-is-kubernetes.html, templates/shared/contextual_footers/_cloud_lxd.html, templates/shared/contextual_footers/_containers_juju.html
*Waiting on feedback from pdm*
- Update /what-is-kubernetes as per [copydoc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11353.demos.haus/kubernetes/what-is-kubernetes
-  Compare against [copydoc](https://docs.google.com/document/d/19ZAsyujRHjOBIKP15F-4Z9L24KpfoYrx0YpL-0gO6sE/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4904
=> Update /what-is-kubernetes as per copydoc

templates/download/iot/intel-iotg.html, templates/shared/forms/interactive/internet-of-things.html, tests/cypress/forms/forms_spec.js, tests/cypress/utils.js
- Add `Learn more` button on the `/download/iot/intel-iotg` page
- Update interactive form
- Update cypress test for the form
- Demo at https://ubuntu-com-11396.demos.haus/download/iot/intel-iotg
- [Copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- [Form doc](https://docs.google.com/document/d/12HsccVGTbjOxRX0go2m7ywFFoqrtU2JIizwIFtVWnWs/edit#)
- Please check the interactive form is working properly and QA all the buttons
- QA done with cypress test
Fixes [#4963](https://github.com/canonical-web-and-design/web-squad/issues/49 …
=> Copy update on `/download/iot/intel-iotg`

templates/legal/ubuntu-advantage-service-description/_toc.html, templates/legal/ubuntu-advantage-service-description/index.md
- Updates the UASD page as per [copydoc](https://docs.google.com/document/d/15URkXf2vh7bv89n-cWQPeaP2EehSNUnUCoZvGbNTYFA/edit#)
- Updates _TOC.html to accommodate new section
- Go to https://ubuntu-com-11406.demos.haus/legal/ubuntu-advantage-service-description and compare against [copydoc](https://docs.google.com/document/d/15URkXf2vh7bv89n-cWQPeaP2EehSNUnUCoZvGbNTYFA/edit#)
- Check the link to 'Embedded services' works as expected
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4978
=> Update UASD page

templates/16-04/index.html
- Copy update on /16-04
- Compare page against [copy doc](https://docs.google.com/document/d/1wclofqY9b3v_M9igpkYn6or5uXx0B_Xb_nVVzGBbOLY/edit#)
- Demo at https://ubuntu-com-11433.demos.haus/16-04
Fixes [#5016](https://github.com/canonical-web-and-design/web-squad/issues/5016)
=> Copy update on /16-04

templates/aws/fips.html
- Updated as per [copy doc](https://docs.google.com/document/d/1RIUejzxrQwvT-qQGG_FhRIaTVzZb07o6mZeiYkaBdqk/edit#)
- View the site locally in your web browser at: http://0.0.0.0:8001/aws/fips
- Test links
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5009
=> Update copy on /aws/fips

templates/download/desktop/thank-you.html
- Updates the /download/desktop/thank-you page as per [copydoc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit#)
- Compare against the [copydoc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4979
=> Refresh desktop download thankyou page

templates/azure/fips.html
- Updated /azure/fips based on the [copy doc](https://docs.google.com/document/d/1Djxdzjy78bau8ELM4-MNGoM2YRa_QjpN1xJ4H4GjFyw/edit#)
- View the site in your web browser at: https://ubuntu-com-11444.demos.haus/azure/fips
- check the updates match the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5008
=> Update /azure/fips copy

navigation.yaml, templates/azure/sql.html
- Build page on `/azure/sql`
- Please compare page with [copy doc](https://docs.google.com/document/d/16QHk3drMIRLeeEdYurIQieo1W93SygetyWdTT4184pE/edit#)
- Demo at https://ubuntu-com-11412.demos.haus/azure/sql
Fixes [#4993](https://github.com/canonical-web-and-design/web-squad/issues/4993)
=> Build page on `/azure/sql`

templates/download/iot/intel-iotg.html
- Replace `Learn more` with `Contact us` on `/download/iot/intel-iotg`
- [Copy doc](https://docs.google.com/document/d/1hxKzPs6e6JQaa9tBqfZ55GAXrVnEryEWBja8HlXy-lc/edit)
- Please check the link works properly 
- Demo at https://ubuntu-com-11451.demos.haus/download/iot/intel-iotg
Fixes [#5056](https://github.com/canonical-web-and-design/web-squad/issues/5056)
=> Update contact us button

templates/download/raspberry-pi/thank-you.html
- Updates raspberry-pi thank-you page for 22.04 release as per [copydoc](https://docs.google.com/document/d/1RXsLbMB-LJVwiG0gAi0HgVEJvZ9_GIU3ESLJ6KmBb54/edit#)
- Compare against [copydoc](https://docs.google.com/document/d/1RXsLbMB-LJVwiG0gAi0HgVEJvZ9_GIU3ESLJ6KmBb54/edit#)
- *Note*: Some names may use the release.yaml that hasn't been updated yet
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4987
=> Refresh raspberrypi thankyou page

static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancel.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionCancel/SubscriptionCancelFields/SubscriptionCancelFields.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx, static/js/src/advantage/react/hooks/index.ts, static/js/src/advantage/react/hooks/useCancelTrail.ts, static/js/src/advantage/react/hooks/useCancelTrial.test.tsx, webapp/shop/api/ua_contracts/api.py
- Add cancel trial button 
- But a trial
- Cancel it
- But a monthly product
- Cancel it
- Did it work?
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/539
=> Add cancel trial button

tests/shop/advantage/test_api.py, tests/shop/advantage/test_helpers.py, webapp/app.py, webapp/shop/api/ua_contracts/api.py, webapp/shop/api/ua_contracts/helpers.py
- Fix expiry status for renewed legacy user subscriptions
- Login with your account on prod using the demo
- Ping me to get the test link
- expiry notification should be gone
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/550
=> Fix expiry for renewed legacy

templates/advantage/subscribe/form/_type_select.html
- changed "Google Cloud Marketplace" to "Google Cloud Console".
- Go to [/advantage/subscribe](https://ubuntu-com-11460.demos.haus/advantage/subscribe)
- select google cloud
- check that the copy is correct
Fixes canonical-web-and-design/commercial-squad#553
=> Change "Google Cloud Marketplace" to "Google Cloud Console".

templates/kubernetes/index.html
- Updates /kubernetes as per [copydoc](https://docs.google.com/document/d/1b018GoKMF3abEFJlUkfAEK2JEhXWICKF4V0dGdTvgJs/edit#heading=h.twfyt04g5k41)
- Check the changes against the copydoc at https://ubuntu-com-11478.demos.haus/kubernetes
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5088
=> Refresh /kubernetes page

templates/desktop/organisations.html, templates/support/index.html
**Note: Some assets are missing so I have added in 'placeholders' for the time being**
- Rebuild page ready for the 22.04 refresh as per [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
- Go to https://ubuntu-com-11492.demos.haus/desktop/organisations and compare against [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4960
=> Refresh /organisations

templates/desktop/developers.html, templates/shared/contextual_footers/_desktop_buy_preinstalled.html, templates/shared/contextual_footers/_desktop_developer_community.html
**Note: Waiting on 22.04 screenshots**
- Updates  /desktop/developers page for the 22.04 refresh, see [copydoc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
- Go to https://ubuntu-com-11493.demos.haus/desktop/developers and compare against [copydoc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4960
=> Refresh /desktop/developers page 

templates/download/desktop/index.html
**note: releases.yaml will be updated on merge so ignore the refs to 20.04**
- Refresh desktop download page for 22.04 release
- Compare against [copydoc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#heading=h.534z663gdsag)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4964
=> Refresh desktop download page

templates/download/index.html, templates/download/raspberry-pi/index.html, templates/download/server/step2.html
- Updates Ubuntu mascot to JammyJellyfish
- Check there are no outdated Ubuntu mascots
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5119
=> Update Ubuntu mascot

templates/ceph/index.html, templates/download/alternative-downloads.html, templates/download/server/step2.html, templates/download/xilinx/index.html, templates/server/index.html
- Updates with suggested changes from QAing the entire 22.04 branch
- Updates ceph version graph on /ceph, see [issue](https://app.zenhub.com/workspaces/-web-tribe-5931746dba512f05402b61f6/issues/canonical-web-and-design/ubuntu.com/11462)
- Compare against comments on [22.04 PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11501)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5102
=> Update with suggestions

templates/desktop/index.html
- Updates screenshot image of Ununtu on /desktop
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5102
=> update desktop image on /desktop

navigation.yaml, templates/raspberry-pi/desktop.html
- Removes /statistics from the navigation
- Flyby formatting change
- See [spreadsheet](https://docs.google.com/spreadsheets/d/1WHyh42eHNT2ka2ac3wMLOuaFwZ0inN7oKWIPLxorMTw/edit#gid=0)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11526
=> Removes /statistics from the navigation

templates/desktop/features.html, templates/raspberry-pi/index.html
- Updates final 22.04 images that were request post release
- Check the images on /features and /raspberry-pi reflect 22.04
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11531
=> Updates final 22.04 images

navigation.yaml, templates/kubernetes/resources.html
- Build page on `/kubernetes/resources`
- Please compare page against [copy doc](https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit)
- Demo at https://ubuntu-com-11544.demos.haus/kubernetes/resources
Fixes [#5089](https://github.com/canonical-web-and-design/web-squad/issues/5089)
=> Build page on /kubernetes/resources

templates/openstack/compare.html, templates/openstack/shared/_cheatsheet.html, templates/openstack/tutorials.html
Copy updates for /openstack
- Visit https://ubuntu-com-11546.demos.haus//openstack/tutorials and compare against [copy docs](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#heading=h.f6xejtisk68)
- Visit https://ubuntu-com-11546.demos.haus//openstack/compare [copy docs](https://github.com/canonical-web-and-design/web-squad/issues/5175#event-6490935572)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5175
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5174 …
=> Openstack copy updates

templates/download/server/power.html
- Updated as per [copy doc](https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit)
- View the site locally in your web browser at: https://ubuntu-com-11555.demos.haus/download/server/power
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5209
=> Update copy on /download/server/power

.github/workflows/cypress-main.yaml, templates/desktop/organisations.html
- Update cypress schedule time for forms
- Remove one data-testid on `/desktop/organisation`
=> Update cypress schedule time 

templates/openstack/what-is-openstack.html, templates/shared/contextual_footers/_openstack-detailed-documentation.html
Refresh /openstack/what-is-openstack page
- Check https://ubuntu-com-11547.demos.haus/openstack/what-is-openstack against [copy docs](https://docs.google.com/document/d/15xrgIq_KUwHaCyFoI7-yS_JmBbsoyXJ4GpRMFAa7_is/edit#)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5173
=> Refresh what-is-openstack page

templates/kubernetes/install.html, templates/kubernetes/managed.html
- Updated as per [copy doc](https://docs.google.com/document/d/1Qv379nYnod9e4jMrsdDND8D7mbPyqELi2lowjkfD-gU/edit)
- View the site locally in your web browser at: https://ubuntu-com-11564.demos.haus/kubernetes/managed
- See that changes match the doc and test links
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5222
=> K8s managed update

templates/openstack/features.html
- Updated as per [copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit)
- View the site locally in your web browser at: https://ubuntu-com-11568.demos.haus/openstack/features
- See that the requested change was made and that link works as expected
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5229
=> Updated copy /openstack/features

templates/kubernetes/charmed-k8s.html
- Updated as per [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#)
- **Note: As we do not have a video link, this change was not added to this pr**
- View the site locally in your web browser at: https://ubuntu-com-11560.demos.haus/kubernetes/charmed-k8s
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11510
=> Update copy /charmed-k8s

templates/download/server/s390x.html
- Updated copy and from as per [copy doc](https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11569.demos.haus/download/server/s390x
- See that the copy matches the doc
- See that all form changes have been made
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5204
=> S390x copy update

templates/pricing/devices.html
- Remove one `data-testid` on `/pricing/devices` as it needs to be only one per page.
- Move this file `/tests/cypress/forms/forms_spec.js` to the `/tests/cypress/integration`folder
- `yarn run cypress:open`
=> Remove data-testid on /pricing/devices

templates/ai/what-is-kubeflow.html
- Copy update on `/ai/what-is-kubeflow`
- Go to `/ai/what-is-kubeflow` or https://ubuntu-com-11574.demos.haus/ai/what-is-kubeflow
- Please compare page against [Copy doc](https://docs.google.com/document/d/1m-96RlGkbzFa1KaGAxYFpY0ztIlsTuViCjXSAlErQlg/edit)
Fixes [#5255](https://github.com/canonical-web-and-design/web-squad/issues/5255)
=> Copy update on /ai/what-is-kubeflow

templates/desktop/flavours.html
- Copy update on `/desktop/flavours`
- Go to `/desktop/flavours`
- Please compare page agains [copy doc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit#)
Fixes [#5099](https://github.com/canonical-web-and-design/web-squad/issues/5099)
=> Copy update on /desktop/flavours

static/js/src/advantage/subscribe/renderers/version-details.js, templates/advantage/subscribe/form/_ubuntu_version_select.html
- Added 22.04 to the list of available versions on /subscribe
- go to https://ubuntu-com-11543.demos.haus/subscribe
- check that 22.04 is showing and that the features are correct
Fixes canonical-web-and-design/commercial-squad#559
=> Add 22.04 to the list of LTSs

templates/kubernetes/charmed-k8s.html
- Upload a video to Vimeo
- Add video on `/kubernetes/charmed-k8s`
- Go to `/kubernetes/charmed-k8s`
- Compare page against [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#)
- Demo at https://ubuntu-com-11590.demos.haus/kubernetes/charmed-k8s
Fixes [#5134](https://github.com/canonical-web-and-design/web-squad/issues/5134)
=> Add video to /kubernetes/charmed-k8s

templates/advantage/_table.html
-  Copy update on `/advantage`
- go to `/advantage`or https://ubuntu-com-11599.demos.haus/advantage
- Compare page against [copy doc](https://docs.google.com/document/d/1So3n5HEpBX39xxEkkChnve09gKSr9TgYUcbfdOTCevk/edit)
Fixes [#5286](https://github.com/canonical-web-and-design/web-squad/issues/5286)
=> Copy update on /advantage

templates/download/intel-nuc.html, templates/download/iot/index.html, templates/download/raspberry-pi/index.html, templates/pricing/shared/_enablement-strip.html
Ubuntu Core 22 beta only copy updates
If you run into comments of Ubuntu 22 stable, you probably need to ignore those changes
- Check https://ubuntu-com-11605.demos.haus/download/iot: against https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#
- Check https://ubuntu-com-11605.demos.haus/download/raspberry-pi: against https://docs.google.com/document/d/1KgnSBa8mbR7qwlxxtqbE5a1wXh5GjtVums8TIB7IGVw/edit#
- Check https://ubuntu-com-11605.demos.haus/download/intel-nuc against https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit#
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5301 …
=> UC22 beta updates

templates/certified/index.html
- Updated text to be more descriptive
- View the site locally in your web browser at: https://ubuntu-com-11608.demos.haus/certified
- See that the changes have been made and that the copy is appropriate 
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5284
=> Update ctas on /certified

templates/pricing/devices.html
- Update "Modification and redistribution rights" to "Trademark use"
- Go to `/pricing/devices`
- Compare page against [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#)
Fixes [#5334](https://github.com/canonical-web-and-design/web-squad/issues/5334)
=> Copy update on /devices

templates/server/index.html
- Updated as per [copy doc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11619.demos.haus/server
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5333
=> Update copy on /server

templates/download/amd-xilinx/index.html
- Copy update on `/download/amd-xilinx` (Updated links)
- Go to `/download/amd-xilinx` or https://ubuntu-com-11628.demos.haus/download/amd-xilinx
- Compare page against [copy doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
Fixes [#5341](https://github.com/canonical-web-and-design/web-squad/issues/5341)
=> Copy update on /amd-xilinx

templates/advantage/_table.html, templates/advantage/index-no-login.html
- Added link to /support in the logged out version of the page
- Go to https://ubuntu-com-11620.demos.haus/advantage
- check that there is now a link to /support
Fixes #11602
=> Add link to /support

static/js/src/PurchaseModal/utils/utils.ts, static/js/src/advantage/api/contracts.js, static/js/src/advantage/offers/components/BuyButton.tsx, static/js/src/advantage/react/hooks/useURLs.test.tsx, static/js/src/advantage/react/hooks/useURLs.ts, static/js/src/advantage/subscribe/blender/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts, static/js/src/navigation.js, templates/account/invoices/index.html, templates/advantage/_table.html, templates/advantage/index-no-login.html, templates/advantage/index.html, templates/advantage/subscribe/blender/index.html, templates/advantage/subscribe/blender/thank-you.html, templates/advantage/subscribe/index.html, templates/advantage/subscribe/thank-you.html, templates/templates/_navigation.html, templates/templates/base.html, tests/cassettes/TestCube.test_microcerts_json.yaml, tests/cassettes/TestCube.test_microcerts_purchase.yaml, tests/cypress/integration/advantage/subscribe_spec.js, tests/cypress/integration/advantage/subscriptions_spec.js, tests/cypress/integration/advantage/users_spec.js, tests/cypress/plugins/index.js, tests/cypress/utils.js, tests/shop/cube/test_cube.py, webapp/app.py, webapp/login.py, webapp/shop/cube/views.py
- In the previous PR we made `test_backend` to no longer switch environments. Now we remove all traces of this little bugger.
- Does cyress pass?
=> Remove test backend flag

templates/desktop/organisations.html
Updates copydoc in /desktop/organisations to this [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#{%)
- Go to and check the copydoc link at the bottom left of the page goes to [this copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#{%)
=> Updates copydoc in /desktop/organisations

templates/ceph/index.html
- Updates link on /ceph
- Go to https://ubuntu-com-11677.demos.haus/ceph and compare against [copydoc](https://docs.google.com/document/d/1gpEjTcdJor2yTGfMz7T_xIfs7BtV6rbBPFYfNZFe52Y/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5430
=> Updates link on /ceph

templates/download/desktop/index.html
Copy update download ubuntu desktop page
- Check https://ubuntu-com-11666.demos.haus/download/desktop against [copy docs](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5433
=> Copy update download ubuntu desktop page

templates/embedding/base_embedding.html, templates/embedding/index.html, templates/shared/forms/interactive/embedding.html, templates/templates/footer.html
- Built as per [copy doc](https://docs.google.com/document/d/1evAFIXbNztOd5yZee-uV8_OM-s6o27P46yXFaaeEhy0/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11621.demos.haus/embedding
- See that the page has been built as requested
- Test form and see that it submits without fail
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5271
=> /embedding build

templates/security/esm.html
- Copy update on `/security/esm`
- Go to t https://ubuntu-com-11693.demos.haus/security/esm
- Compare page against [copy doc](https://docs.google.com/document/d/1RBZX3PJPvODxRlcnIS10Ii4SkIMH5Fm74EmsMQ0cnic/edit#)
Fixes [#5484](https://github.com/canonical-web-and-design/web-squad/issues/5484)
=> Copy update on /security/esm

navigation.yaml, templates/financial-services/resources.html
- Creates /financial-services/resources page
- Add secondary navigation to `financial-services` bubble
- Go to https://ubuntu-com-11672.demos.haus/financial-services/resources and compare against [copydoc](https://docs.google.com/document/d/1FIOi8l7N2On3KVVscIzWUwthhYvdkU21IhanBDUwlCI/edit#heading=h.d2yomvm8pmy4)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11658
=> Create /financial-services/resources page

templates/financial-services/resources.html
- Fix typos on financial-services/resources
- Check the section `SBI reduced infrastructure costs with Charmed OpenStack` matches the [copydoc](https://docs.google.com/document/d/1FIOi8l7N2On3KVVscIzWUwthhYvdkU21IhanBDUwlCI/edit#)
Fixes 
https://github.com/canonical-web-and-design/ubuntu.com/issues/11706
=> Update typos on financial-service/resources

templates/blog/blog-card.html
- Update blog card images to be responsive on smaller screens
- Go to https://ubuntu-com-11709.demos.haus/blog and check that the images on the blog card fit the card size on all screen sizes
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11690
=> Update blog card images to be responsive on smaller screens

tests/cassettes/TestRoutes.test_tutorials_search.yaml, webapp/app.py, webapp/views.py
It appears to be costing us a lot.
Go to the demo, run searches on each of the effected search pages.
=> Disable site restricted search

templates/download/iot/_login.html, templates/download/raspberry-pi-core.html
- Remove repeated section
- View the site locally in your web browser at: http://0.0.0.0:8001/download/raspberry-pi-core or go to https://ubuntu-com-11708.demos.haus/download/raspberry-pi-core
- Compare page against [copy doc](https://docs.google.com/document/d/1Ig906jbgB39QHw61uHMvIsRbSBUjchJBDkMZl0WzlWM/edit)
Fixes [#5511](https://github.com/canonical-web-and-design/web-squad/issues/5511)
=> Remove repeated section

tests/cassettes/TestRoutes.test_tutorials_search.yaml, webapp/app.py, webapp/views.py
Reverts canonical-web-and-design/ubuntu.com#11710
=> Revert "Disable site restricted search"

templates/core/features/index.html
- Updated /core/features based on the copy doc: https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit#heading=h.lixa1zw495b2
**Don't merge yet, this is to go live on the 16th July**
- View the site in your web browser at: https://ubuntu-com-11705.demos.haus/core/features
- See that the changes reflect the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5469
=> update /core/features page

navigation.yaml, static/js/src/openstack/react/components/CostCalculatorForm.jsx, templates/openstack/_resource-card.html, templates/openstack/resources.html, webapp/app.py, webapp/views.py
- Added resource page
- Added logic for dynamic engage paper cards
- Added card template
- Built as per [copy doc](https://docs.google.com/document/d/1ySynE6LOEWKbg4Q_udqM_W3BWkMPi5AfLjiM0qcLrn4/edit#)
- View the site locally in your web browser at: https://ubuntu-com-11665.demos.haus/openstack/resources
- See that page matches doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5257
=> /openstack/resources build

tests/cassettes/TestRoutes.test_tutorials_search.yaml, webapp/app.py, webapp/views.py
Reverts canonical-web-and-design/ubuntu.com#11717
=> Revert "Revert "Disable site restricted search""

webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/api/ua_contracts/schema.py, webapp/shop/schemas.py
- Have the new purchase endpoint allow purchase offers too. 
- Bit hard to test without UI
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/601
=> New purchase endpoint offers

webapp/shop/api/ua_contracts/models.py, webapp/shop/api/ua_contracts/schema.py
- Fixed error caused by trials in invoice page
- Buy a trial subscription for [UA](https://ubuntu-com-11747.demos.haus/advantage)
- Going to [invoice page](https://ubuntu-com-11747.demos.haus/account/invoices) should not give an error
Fixes [#626](https://github.com/canonical-web-and-design/commercial-squad/issues/626)
=> Invoice cost for trial fixed

static/sass/_pattern_table-of-contents.scss, templates/legal/data-privacy/_toc.html, templates/legal/terms-and-policies/index.html
- Updated /legal/terms-and-policies and /legal/data-privacy according to the [issue](https://github.com/canonical-web-and-design/web-squad/issues/5239) and the copy docs linked from it
- View the site in your web browser at: https://ubuntu-com-11753.demos.haus/legal/terms-and-policies
- See that it matches the [copy doc](https://docs.google.com/document/d/1p3ZWroZ3nkw8XJJdPvPxSlWGYcLZLT8UbUVuppBcyHk/edit#)
- Visit https://ubuntu-com-11753.demos.haus/legal/data-privacy
- See that it matches the [copy doc](https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit#heading=h.a41ehw5ql4g)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5239
=> Update /legal copy

navigation.yaml
- Updated the order of items in the subnav on /core, according to the issue: https://github.com/canonical-web-and-design/ubuntu.com/issues/11578
- Visit https://ubuntu-com-11761.demos.haus/core
- See that the items in the subnav match what is given in the issue
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/11578
=> update order of nav items on /core

templates/openstack/install.html, templates/openstack/tutorials.html
- Added openstack survey to /openstack/install ([copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit)) and /openstack/tutorials ([copy doc](https://docs.google.com/document/d/1_4EJlX-fbcQBVC9Ojhjdbls6kbmITGvHKi5IEqw-HAA/edit#heading=h.1yyo8h5981hh))
- Visit https://ubuntu-com-11762.demos.haus/openstack/install and https://ubuntu-com-11762.demos.haus/openstack/tutorials
- See the openstack survey section has been added
Fixes:
- https://github.com/canonical-web-and-design/web-squad/issues/5570
- https://github.com/canonical-web-and-design/web-squad/issues/5571
=> Openstack survey

templates/internet-of-things/smart-city.html
- Copy update on /security/smart-city
- Go to https://ubuntu-com-11768.demos.haus/security/smart-city
- Compare page against [copy doc](https://docs.google.com/document/d/1Zh-IkLDnaqmPr4TTeUZ3mtyY2_OGW4iElfntYWZyveY/edit#)
Fixes [#5581](https://github.com/canonical-web-and-design/web-squad/issues/5581)
=> Copy update on /security/smart-city

requirements.txt
Update search module with [user agent bot block](https://github.com/canonical-web-and-design/canonicalwebteam.search/commit/04cdd962484a368a41b668c372add7712222d0fe)
=> Update search module

templates/core/index.html
- Fix wrong links on `/core`
- Go to https://ubuntu-com-11770.demos.haus/core
- Compare page against [copy doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit#)
Fixes #11765
=> Fix wrong links on /core

templates/tutorials/index.html, webapp/views.py
Reverts canonical-web-and-design/ubuntu.com#11764
Put back tutorials search.
On the demo, go to tutorials and do some searches.
=> Revert "Disable tutorials search again"

templates/landscape/pricing.html
- Updated copy on /landscape/pricing to match the [copy doc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#heading=h.3u064lpm03n6)
- visit https://ubuntu-com-11773.demos.haus/landscape/pricing
- See that it matches the copy doc: https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#heading=h.3u064lpm03n6
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5574
=> update landscape pricing copy

templates/core/index.html
Fix contact link typo
Fixes https://github.com/canonical-web-and-design/ubuntu.com/runs/7107277537?check_suite_focus=true
=> Fix contact link typo

webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/schemas.py
- Have the new purchase endpoint allow purchase renewals too.
- Bit hard to test without UI
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/600
=> New purchase endpoint renewals

navigation.yaml, templates/internet-of-things/smart-home.html, templates/shared/forms/interactive/smart-home.html
- Added /smart-home to /internet-of-things bubble based on [copy doc](https://docs.google.com/document/d/1zwB-6Flt0Jm7XIxhWUWRJjKC1WCGVmVVNmPHtyOTHuE/edit#)
- Added new contact form based on [copy doc](https://docs.google.com/document/d/1a_OLqNDCkxxS7EHPV0Q1clCZru8h5FQUqljVWMgW1Og/edit#)
- visit https://ubuntu-com-11781.demos.haus/internet-of-things/smart-home
- Click "Get in touch", see that the form submits correctly
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5370
=> Add /iot/smart-home

templates/about/release-cycle.html
=> Fix small typographical error on ubuntu.com/about/release-cycle

konf/site.yaml
- Put Security API Docs back up.
Fixes #https://github.com/canonical-web-and-design/ubuntu-com-security-api/issues/57
=> Enable API docs again

README.md
- Remove linkcheck Github badges
=> Remove linkcheck Github badges

konf/site.yaml, redirects.yaml
Proxy the USN database from people.canonical.com.
Fixes https://github.com/canonical/Web-design-systems-squad/issues/35
=> Add USN proxy

templates/openstack/index.html
-Update a link on /openstack 
- View the site locally in your web browser at: http://0.0.0.0:8001/openstack or https://ubuntu-com-11824.demos.haus/openstack
- Compare page against [copy doc](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit?disco=AAAAcmLvnwU&usp_dm=false)
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/5663
=> Update a link  /openstack 

templates/about/release-cycle.html
- Copy update on /about/release-cycle
- View the site locally in your web browser at: http://0.0.0.0:8001/about/release-cycle or t https://ubuntu-com-11825.demos.haus/about/release-cycle 
- Compare page against [copy doc](https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit)
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/5662
=> Copy update on /about/release-cycle

templates/legal/contributors/agreement.html
- Add org name field to the Contributor agreement form
- Go to /legal/contributors/agreement
- Click the "I am signing as an individual contributor." option and see the details appear and the form is missing the Organisation name
- Click the other option option and see the details appear and the form has a Organisation name field
Fixes [#11819](https://github.com/canonical-web-and-design/ubuntu.com/issues/11819)
=> Add org name field to the Contributor agreement form

templates/desktop/organisations.html
=> Remove `>`

templates/desktop/developers.html
- Update image on `/desktop/developers`
- Go to https://ubuntu-com-11874.demos.haus/desktop/developers
- [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#) - just this image update for this PR. Other updates will be done by this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/11823) or in the fulture
=> Update image on `/desktop/developers`

templates/desktop/developers.html
=> Increase image size

static/js/src/navigation.js
Fix the global navigation click
Click products in the global nav and see it works.
=> Fix the global navigation click

static/js/src/ua-payment-methods.js
- Fix payment method postcode - update button interation
Part 1:
- Go to: https://stagin.ubuntu.com
- Login
- Go to: https://stagin.ubuntu.com/account/payment-methods
- Use card: `4000 0082 6000 0000`
- Try inserting a random UK postcode fx: `SS10 99SS`
- The Update focus will interrupt you
Part 2:
- Go to https://ubuntu-com-11898.demos.haus/
- Login
- Go to: https://stagin.ubuntu.com/account/payment-methods
- Use card: `4000 0082 6000 0000`
- Try inserting a random UK postcode fx: `SS10 99SS`
- It will work
Fixes #https://github.com/canonical-web-and-design/commercial-squad/issues/684
=> Remove Update Focus

templates/desktop/partners.html
- Updated the image of hardware on /desktop/partners, according to the [copy doc](https://docs.google.com/document/d/1b4pwQYVHm8-R5_Wqx5zj09Qn8QsrKt3JblteauspmKI/edit)
- Visit https://ubuntu-com-11903.demos.haus/desktop/partners
- See that the comment in the copy doc has been addressed
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5746
=> update image on /desktop/partners

run
Update run script dev image version
=> Update run script dev image version

static/js/src/main.js, static/js/src/mobile-footer-navigation.js, static/sass/_pattern_footer.scss, templates/templates/_footer_item.html, templates/templates/footer.html
- [Increased the font-size of the drop-downs.]
- [Added padding-inline to the drop-downs.]
Fixes #11831
=> Fixed mobile footer links and added some padding.

static/sass/_pattern_gaming.scss, templates/desktop/features.html, templates/shared/contextual_footers/_desktop_flavours.html
- Copy updates for desktop features page
- Removes unnecessary CSS animation (after gaming background changed)
Fixes canonical/vanilla-squad/issues/1415
- Review content changes:
- Visit https://ubuntu-com-11922.demos.haus/desktop/features
- Make sure changes from comments in copy doc are implemented: https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit#
=> Content updates for desktop features page

templates/desktop/organisations.html
Copy update - only image
- Check https://ubuntu-com-11924.demos.haus/desktop/organisations against [copy doc image](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit)
Fixes https://github.com/canonical/web-squad/issues/5781#event-7116333559
=> Replace laptop image with XPS laptop image

templates/certified/model-details.html
Add model name as requested in the issue 
- Go to https://ubuntu-com-11921.demos.haus/certified/202202-29982 and check that metadata title contains the form factor as reported in the issue
Fixes https://github.com/canonical/ubuntu.com/issues/11826
=> Add model name to meta title

templates/support/index.html
Fix typo in `/support`: `s/thcommunity/the community/`
=> Fix typo on /support

templates/kubernetes/docs/supported-versions.md
Close markdown code section
- Go to https://ubuntu-com-11934.demos.haus/kubernetes/docs/supported-versions and check that the code section is closed and Vanilla styles are rendered..
=> Close markdown code

static/js/src/dynamic-forms.js, templates/shared/forms/interactive/intel-iotg.html
- Updated the copy according to the [copydoc](https://docs.google.com/document/d/12HsccVGTbjOxRX0go2m7ywFFoqrtU2JIizwIFtVWnWs/edit?disco=AAAAcF8vgUE&usp=comment_email_document&ts=62e97c6d&usp_dm=false)
- go on [/download/iot/intel-iotg](https://ubuntu-com-11928.demos.haus/download/iot/intel-iotg)
- click "contact us" 
- check that the form matches the copydoc
- try to progress to the last page of the form without filling in any details
- you should see a validation message on the "Tell us more about your project" field
- fill out the field and try to progress again
- you should be able to progress
Fixes canonical/commercial-squad#687
=> [Copy Update] Download Intel IoT G Contact Us form

.github/workflows/a11y.yaml, .github/workflows/blog-links.yaml, .github/workflows/cypress-main.yaml, .github/workflows/cypress-pr.yaml, .github/workflows/live-links.yaml, .github/workflows/mirrors.yaml, .github/workflows/security-links.yaml
- Update repo from `canonical-web-and-design/ubuntu.com` to `canonical/ubuntu.com`
Fixes #11919
=> Update repo for github actions

templates/desktop/index.html
Update copy of the desktop page for the new release.
- Make sure the copy matches the document
=> Desktop page: Copy update for the new release

templates/security/docker-images.html
- Copy doc update /securtiy/docker-images
- Go to https://ubuntu-com-11938.demos.haus/security/docker-images
- Make sure that the updates match the copy doc
- Please, mark the request changes in the copy doc as resolved once the QA is done
Fixes https://github.com/canonical/workplace-engineering-squad/issues/788
=> copy doc update /securtiy/docker-images

templates/download/amd-xilinx/index.html
- updated /download/amd-xilinx according to [copy doc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit)
- **note:** this doesn't address any of the comments about expandable sections, see the issue for more context on that
- Visit: https://ubuntu-com-11827.demos.haus/download/amd-xilinx
- See that the page matches the copy doc
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5656
=> update /amd-xilinx copy

templates/download/iot/index.html
- Updated copy according to https://github.com/canonical/marketplace-tribe/issues/2786
- View the demo, or checkout the branch and run `dotrun`.
- Visit /download/iot
- Check copy against the copy doc and the design against the design
Fixes https://github.com/canonical/marketplace-tribe/issues/2786
=> [Copy update] IoT Download Page

templates/hpc/_hpc-contact-us-form.html, templates/hpc/contact-us.html, templates/hpc/thank-you.html, templates/shared/_cloud-contact-us-form.html
Dynamic contact us form for HPC
Compare with [copy docs](https://docs.google.com/document/d/1Tdu0Z60hSE8BSMMYAShfF5KFCJ_tE11eRp31oryk5xg/edit#)
Check that text changes correctly according to different product names:
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-demo
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-charmed
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-ubuntu
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-maas
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-ceph
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-kubernetes
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=hpc-openstack
https://ubuntu-com-11956.demos.haus/hpc/contact-us?product=openinfra-summit …
=> Create contact-us form for HPC

templates/credentialing/schedule.html, templates/credentialing/scheduled.html, webapp/shop/api/trueability/api.py, webapp/shop/cube/views.py
=> Cred poc abhigyan

webapp/views.py
- Fix for tags and related posts not showing
- Go to any blog e.g. https://ubuntu-com-12003.demos.haus/blog/publish-software-operators
- Check that tags and related posts are showing up now
Fixes #
=> Change to correct method to get article context

templates/credentialing/index.html
Tweaked some of the design for credentialing
- Open the demo and go to /credentialing
- Check on different viewports that the site looks ok
=> Tweaked some of the design for credentialing

navigation.yaml, templates/blog/topics/design.html
- Updated the topic navigation form `Design` to `Web and Design`
- Refreshed the topic header content 
- Go to /blog/topics/design
- Check the header content is good and the navigation item is updated
=> Update the web and design blog topic

templates/openstack/features.html
Following suggested changes in https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#
Fixes https://github.com/canonical/web-squad/issues/5937
Go to https://ubuntu-com-12014.demos.haus/openstack/features.
Check each of Tytus' suggested changes in [the copy doc](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#) have been done.
=> Copy updates to /openstack/features - NVidia vGPU row, and others

templates/hpc/_base_hpc.html, templates/hpc/index.html
Build new HPC index page
- Check https://ubuntu-com-12005.demos.haus/hpc against [copy doc](https://docs.google.com/document/d/1d4E1IA2mEu72q277sihNSkl7QRKsU1ezwA3jVgJ0TCE/edit)
Fixes https://github.com/canonical/web-squad/issues/5856
=> Build new HPC page

package.json, static/js/src/side-navigation.js, templates/core/docs/document.html, templates/templates/docs/shared/_docs.html, yarn.lock
- This feature makes side navigation expandable. 
> Note: The data i used in first screenshot is from https://microk8s.io/docs, the second one is from the current API that should add home page as first level like we have in microk8s.io
- View the site locally in your web browser at: http://0.0.0.0:8001/core/docs
Fixes #12026 
**Image 1**
**Image 2**
=> add expandable navigation to core docs

templates/automotive/developers.html
- Build page on /automotive/developers
- Demo at https://ubuntu-com-12022.demos.haus/automotive/developers
- Compare page against [copy doc](https://docs.google.com/document/d/1tO6WLB0Mk4jx_s22Yi2502nfGzsXbuNZCzSr56MnHWw/edit#) 
Fixes [#5933](https://github.com/canonical/web-squad/issues/5933)
=> Build page on /automotive/developers

navigation.yaml, templates/automotive/index.html
- Refresh automotive page
- Go to [https://ubuntu-com-12039.demos.haus/automotive](https://ubuntu-com-12039.demos.haus/automotive)
- Compare page against [copy doc](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit#)
Fixes [#5934](https://github.com/canonical/web-squad/issues/5934)
=> Refresh automotive page

templates/desktop/index.html, templates/shared/contextual_footers/_support-image.html
- Update desktop index page
- Compare page against [copy doc](https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit#)
Fixes [#5938](https://github.com/canonical/web-squad/issues/5938)
=> [pro update] Update desktop index page

templates/download/desktop/index.html, templates/download/desktop/thank-you.html
- Updates `/download/desktop` as per [copydoc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#)
- Updates `/download/desktop/thank-you` as per [copydoc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit#heading=h.l36uteh9lad7)
- Go to /download/desktop and compare againast copy doc
- Same for /download/desktop/thank-you, but make sure you test with different url parameters to display and hide different content. See the file templates/download/desktop/thank-you.html 
Fixes https://github.com/canonical/web-squad/issues/5619
=> Update /download/desktop & /download/desktop/thank-you

templates/desktop/developers.html, templates/desktop/organisations.html
- Copy update on /desktop/organisations
- Go to https://ubuntu-com-11813.demos.haus/desktop/organisations
- Compare page against [copy doc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo4b4_9fYaaMtGQuH_xc/edit#)
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/5617
=> [pro update] Copy update on /desktop/organisations

konf/site.yaml
- Revert login URL
- Try the demo link. Can you login?
=> Revert login URL change

static/js/src/developer-chart.js, templates/desktop/developers.html
- Copy update on /desktop/developers
- View the site locally in your web browser at: http://0.0.0.0:8001/desktop/developers or https://ubuntu-com-11823.demos.haus/desktop/developers
- Compare page against [copy doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#heading=h.q5r79xcdu7p7)
Fixes #https://github.com/canonical-web-and-design/web-squad/issues/5618
=> [pro update] Copy update on /desktop/developers

navigation.yaml, templates/pricing/desktops.html
- Build page on /pricing/desktop
- Compare page against [copy doc](https://docs.google.com/document/d/1xVtaZ7wr5sdBqye3Gc-XWXEpNqXaol8uDdMwJ_KyOO8/edit)
- Demo at https://ubuntu-com-12044.demos.haus/pricing/desktops
Fixes [#5616](https://github.com/canonical/web-squad/issues/5616)
=> [pro update] Build page on /pricing/desktop

templates/security/index.html, templates/shared/contextual_footers/_security_esm.html
- Updated /security according to this copy doc: https://docs.google.com/document/d/1yEocR1WXQvN_B1L1yBYrG_0D7ikS6QhcOz27sYs-teI/edit#
- Visit https://ubuntu-com-12073.demos.haus/security
- See that the page matches the copy doc
Fixes https://github.com/canonical/web-squad/issues/6014
=> Update /security for pro launch

templates/pricing/index.html
- Change Pricing page for Ubuntu Pro release
- Check out copy doc: https://docs.google.com/document/d/1iOM6oBqsTkptsst3yG-U3sGaYLQqs27go_8yJQdhMBE/edit#heading=h.va0t5yspw785
- Compare it to the demo
Fixes #https://github.com/canonical/web-squad/issues/6007
=> Pro change pricing

navigation.yaml, templates/aws/workspaces.html
- added page at /aws/workspaces
- visit https://ubuntu-com-12081.demos.haus/aws/workspaces
- See that it matches the [copy doc](https://docs.google.com/document/d/1qC22TM6KZTlxK3CScf-RQ4RUiMUhIBcjSWGur-dbYVA/edit)
Fixes https://github.com/canonical/web-squad/issues/5947
=> add /aws/workspaces page

templates/security/livepatch.html
- Changes to /security/livepatch for ubuntu pro release
- Got to: https://ubuntu-com-12079.demos.haus//security/livepatch
- Check against the copy doc: https://docs.google.com/document/d/1g_Ip5MzlBRpbM2wULpSnsR5XaHJVWgLPLdq8_7fCHrs/edit#
Fixes #https://github.com/canonical/web-squad/issues/6026
=> Pro change livepatch

templates/shared/_security-patching-logo-cloud.html, templates/support/index.html
- Make changes to /support for Ubuntu pro release
- Go to https://ubuntu-com-12078.demos.haus/support 
- Check against the copy: https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit#
Fixes #[Issue](https://github.com/canonical/web-squad/issues/6024)
=> Pro change support

static/js/src/advantage/subscribe/react/UAPurchase.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx, static/js/src/advantage/subscribe/react/components/Form/Form.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.test.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx, static/js/src/advantage/subscribe/react/components/PaymentModal/PaymentModal.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts, static/sass/_pattern_card.scss, static/sass/_pattern_shop-cart.scss, static/sass/_pattern_subscribe.scss, templates/advantage/subscribe/index.html
- Update the Feature and support section to match the designs
=> WIP- Pro selector

templates/legal/ubuntu-advantage/personal/index.md
- Change legal personal page for Ubuntu Pro release 
Go to: https://ubuntu-com-12095.demos.haus/legal/ubuntu-advantage/personal
Check against: https://docs.google.com/document/d/1b2TSeqGfBsmZMepXGEGkEWyTDo0M5aHmyqaQIzEZfPs/edit#
Fixes #https://github.com/canonical/web-squad/issues/6040
=> Pro change legal personal

navigation.yaml, templates/credentialling/self-study.html, webapp/app.py, webapp/shop/cube/views.py
- Add copy for /credentialling/self-study
- Visit the [demo](https://ubuntu-com-12066.demos.haus/credentialling/self-study)
- Verify that the copy matches the [copy doc](https://docs.google.com/document/d/1H_ug8HenT_qVXGachnj0bzf3MWSrUFc83scAmwtsyNo)
Fixes https://github.com/canonical/commercial-squad/issues/720
Fixes https://warthogs.atlassian.net/browse/CRED-162
=> Add copy for /credentialling/self-study

static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx, static/js/src/advantage/subscribe/react/utils/utils.ts, static/sass/_pattern_subscribe.scss
- updated product listings IDs according to this 
```
uaa-standard-physical -> removed from the shop
uaa-advanced-physical -> removed from the shop
uii-standard-physical -> became uio-standard-physical
uii-advanced-physical -> became uio-advanced-physical
uaa-essential-physical -> became uaia-essential-physical
```
- Remove the "Apps support only" option from the form
Fixes 
https://github.com/canonical/commercial-squad/issues/724 
https://github.com/canonical/commercial-squad/issues/725
=> Update product listings and remove Apps support

static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/sass/_pattern_card.scss, static/sass/_pattern_shop-cart.scss, static/sass/_pattern_subscribe.scss
- stuff listed here
https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-UA-%2Fsubscribe?node-id=1599%3A12666
=> Fix mobile version

templates/kubernetes/docs/1.25/release-notes.md, templates/kubernetes/docs/release-notes.md
- Only updates for the release notes pages
=> K8s updates for ck2

konf/site.yaml, templates/advantage/index.html, templates/advantage/maintenance.html, webapp/app.py, webapp/shop/api/ua_contracts/helpers.py, webapp/shop/decorators.py
- Take shop down PR
- Go to /advantage/subscribe you should see the shop is down
- Login to /advantage you will see the notification at the top
=> Take down shop

templates/support/index.html
- Removed table column as per [request](https://docs.google.com/document/d/1AU2dwTXpQk2UuEvSuAqRKrbPWYb-LR0ZGvWu6xw95I8/edit?disco=AAAAhkObSL0)
- See that the changes have been made
=> /support table update

konf/site.yaml, tests/shop/advantage/test_advantage_mapper.py, tests/shop/advantage/test_api.py, tests/shop/advantage/test_helpers.py, tests/shop/advantage/test_parsers.py, webapp/app.py, webapp/shop/api/ua_contracts/helpers.py, webapp/shop/decorators.py
=> Enable ubuntu pro shop

static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx
=> Update subscribe copy

templates/advantage/index.html
copy change to advantage / pro 
Fixes #
=> change advantage to pro

static/js/src/advantage/offers/Offers.tsx, static/js/src/advantage/offers/components/Offer/Offer.tsx, static/js/src/advantage/react/components/Subscriptions/Notifications/Notifications.tsx, static/js/src/advantage/react/components/Subscriptions/RenewalModal/RenewalModal.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/DetailsContent/DetailsContent.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/SubscriptionList.tsx, static/js/src/advantage/subscribe/blender/components/PaymentModal/PaymentModal.tsx, static/js/src/advantage/subscribe/react/components/Heading/Heading.tsx, templates/advantage/index-no-login.html
- Update remaining UA to Pro (and fix a typo)
=> Update remaining UA to Pro

static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/sass/_pattern_shop-cart.scss
=> Fix sticky footer

templates/azure/pro.html
- Update /azure/pro as per [copydoc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#heading=h.uigj6r7m1pr5)
- Go to https://ubuntu-com-12101.demos.haus//azure/pro and compare against [copydoc](https://docs.google.com/document/d/1WaQ5n3GxwZzbX0T6rLiRNejFvxIPIHd5V5XgdAwKmSw/edit#heading=h.uigj6r7m1pr5)
- **note** the copydoc is a bit messy and there are a lot of unresolved questions.
Fixes https://github.com/canonical/web-squad/issues/5998
=> Update /azure/pro as per copydoc

static/sass/styles.scss, templates/advantage/index-no-login.html, templates/pro/beta.html
- fix blurry logos; 
- fix testimonial author column count 
- fix spacing of links inside h2s (links were outside with an h2 class applied to them, which inserted extra space we don't need)
- check the above looks right
=> fix blurry logos; fix author and h2 spacing

templates/desktop/developers.html, templates/desktop/flavours.html, templates/download/desktop/index.html
-Get blog section dynamically on /desktop/flavours
- Go to `/desktop/flavours`
- Check blog section displays properly 
Fixes [#5960](https://github.com/canonical/web-squad/issues/5960)
=> Get blog section dynamically on /desktop/flavours

templates/advantage/subscribe/index.html, templates/advantage/subscribe/thank-you.html
driveby - more UA to Pro copy changes
Fixes #
=> UA to Pro copy changes

templates/ai/index.html, templates/aws/index.html, templates/base_index.html
- Remove Netflix logo's from the site
- Check out the pages effected
- See that the logo sections still look good
- Bonus points for grep for anything I missed (_There is a quote from them which I believe we have permission to use_)
Fixes https://github.com/canonical/web-squad/issues/6009
=> Remove Netflix from the site

templates/pricing/pro.html, templates/shared/pricing/_ua-for-infrastructure.html
- Updated the pricing content based on suggestions in [this copy doc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#).
- Go to /pricing/pro
- See the content and the copy doc match
Fixes https://github.com/canonical/ubuntu.com/issues/12149
=> Update the pro pricing content

.gitignore
- Added .idea folder to .gitignore, because we don't track local env config
=> Add JetBrains .idea folder to .gitignore

static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/sass/_global-settings.scss, static/sass/_pattern_subscribe.scss
- Replaced chips with status labels.
- Added some styles for status labels
- Go to https://ubuntu-com-12159.demos.haus/pro/subscribe
Fixes #12158
=> Replace chips with status labels

templates/legal/ubuntu-pro-description/index.md
- Copy update on /legal/ubuntu-pro-description
- Go to https://ubuntu-com-12165.demos.haus/legal/ubuntu-pro-description
- Compare page against [Copy doc](https://docs.google.com/document/d/15URkXf2vh7bv89n-cWQPeaP2EehSNUnUCoZvGbNTYFA/edit?disco=AAAAhvDXAVE)
Fixes [#6088](https://github.com/canonical/web-squad/issues/6088)
=> Copy update on /legal/upd

static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.test.tsx, static/js/src/advantage/react/components/Subscriptions/ExpiryNotification/ExpiryNotification.tsx
- Update expiration notification messages.
- Hard to QA since we only have yearly subscriptions now so getting them to expire requires hardcoding
Fixes #https://github.com/canonical/commercial-squad/issues/734
=> Change renewal notification message

static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx
- Remove USG for 16.04 and 18.04
- Compare page against [copy doc](https://docs.google.com/document/d/1xFKLAtqHZYJ46d5ZYQQQR8ZL1-bLTPkMNX7Tj3_F554/edit)
Fixes [#730](https://github.com/canonical/commercial-squad/issues/730)
Before
after
=> Remove USG for 16.04 and 18.04

templates/kubernetes/index.html, templates/security/cve/cve.html, tests/cassettes/TestRoutes.test_engage_index.yaml, tests/cassettes/TestRoutes.test_engage_index_with_preview_flag_sees_inactive_pages.yaml, tests/cassettes/TestRoutes.test_engage_index_without_preview_flag_cannot_see_inactive_page.yaml
Fixes https://github.com/canonical/ubuntu.com/issues/12178
```
find ./ -type f -exec sed -i -e 's/Ubuntu security team/Ubuntu Security Team/g' {} \;
```
=> capitalize Ubuntu Security Team

templates/desktop/flavours.html
-  Copy update on `/desktop/flavours`
- Go to `/desktop/flavours`
- Compare page against [copy doc](https://docs.google.com/document/d/1M5nkigcSRzq1YVjiXOZkeU4EUCqT0uYBR3Y_sjxM-wM/edit#)
Fixes #12164
=> [22.10 update]Update page on /desktop/flavours

templates/kubernetes/charmed-k8s.html
- Fixes typo reported in [this issue](https://github.com/canonical/ubuntu.com/issues/12202), updates to match the [copydoc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit#)
- Compare against copydoc/issue
Fixes https://github.com/canonical/ubuntu.com/issues/12202
=> Fix typo on /kubernetes/charmed-k8s

templates/download/server/manual.html
- 22.10 update  on /download/server
- Go to /download/server
- Compare page against [copy doc](https://docs.google.com/document/d/1Qob4Ni_y1ffIdSWqaw2xH0dxiHZQmkRGP5nuoBhIfyM/edit#heading=h.azl4arg09op)
Fixes #12163
=> [22.10 update] on /download/server

templates/server/index.html, templates/shared/_release_schedule.html
- Update copy of /server
- Open demo
- (Or check out this feature branch and run the site using the command `./run serve` or `dotrun`)
- Go to /server
- Compare changes with [copydoc](https://docs.google.com/document/d/1vxLhtbjgPs9PCNEhr7fbhEoErCPMXYFfU4UTKH7Kbq4)
Fixes https://github.com/canonical/workplace-engineering-squad/issues/856
=> ubuntu server page: update copy

templates/pricing/pro.html
- Update copy on /pricing/pro based on [copydoc](https://docs.google.com/document/d/1Ynk0iLa9hjrdich6ATTsybtPbDwW_k4vRI0nk_HNhcI/edit#)
- go to /pricing/pro and compare against copydoc
Fixes https://github.com/canonical/web-squad/issues/6097
=> Update copy on /pricing/pro

redirects.yaml
- New engage page redirect
- Ensure https://ubuntu.com/engage/smart-start-whitepaper redirects to https://ubuntu.com/engage/4-ways-to-accelerate-time-to-market-for-iot-devices
=> Add new engage page redirect: iot time to market

navigation.yaml, templates/azure/support.html
- Build page on `/azure/support`
- Add a support link to the azure bubble menu ubuntu.com/azure/support
- Go to /azure/support
- Compare page against [Brief](https://docs.google.com/document/d/1y-cjuND8Lm66w2_9FTYdMx01XTBHI_o-fnURYfbLsAU/edit), [Design](https://www.figma.com/file/HNEdP4oXC23OBdiZrChWai/%2Fpro-support-pages), [UX](https://miro.com/app/board/uXjVPMizhN8=/) and [Copy doc](https://docs.google.com/document/d/1XjmCkpSjHMLdc6Hdn4L8ml9sQL2wZWfwZg_h94dcgMU/edit#)
Fixes [#6068](https://github.com/canonical/web-squad/issues/6068)
=> Build page on /azure/support

static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.test.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionList/RenewalSettings/RenewalSettings.tsx
- Fix renewal css
- Have a yearly subscription
- Open renewal settings
- Is it pretty? 
Fixes #https://github.com/canonical/commercial-squad/issues/741 
Before:
After:
=> Fix renewal css

templates/landscape/install.html
- Updated the copy on /landscape/install to match the [copy doc](https://docs.google.com/document/d/1tU1z9PUm_kSwGJEsopJibE4gI8Gfv_3Dw_qN2_io_ao/edit#)
- Visit https://ubuntu-com-12233.demos.haus/landscape/install
- See that the page matches the copy doc
Fixes https://github.com/canonical/web-squad/issues/6133
=> update copy on landscape/install

templates/legal/ubuntu-pro-description/_toc.html, templates/legal/ubuntu-pro-description/index.md, templates/shared/_ubuntu-pro-description.html
- updated /legal/ubuntu-pro-description to match the copy doc
- visit /legal/ubuntu-pro-description
- see that it matches the outstanding suggestions in the copy doc
- see that the side nav headings match the content
Fixes https://github.com/canonical/web-squad/issues/6151
=> updated /legal/ubuntu-pro-description

templates/legal/companies.html
Update company delivery addresses according to [copy doc comments](https://docs.google.com/document/d/1y1wPpmeS_BhbRXRdoUJmaTPIMHC_72UzqZG36oP0yWw/edit)
- Check https://ubuntu-com-12245.demos.haus/legal/companies against [copy docs](https://docs.google.com/document/d/1y1wPpmeS_BhbRXRdoUJmaTPIMHC_72UzqZG36oP0yWw/edit)
Fixes https://github.com/canonical/web-squad/issues/6164
=> Update company delivery addresses

templates/hpe/_base_hpe.html, templates/hpe/index.html, templates/shared/forms/interactive/basic.html, templates/shared/forms/interactive/hpe.html
- builds /hpe page based on [copydoc](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit)
Fixes https://github.com/canonical/web-squad/issues/5894
=> Update /hpe page

static/js/src/advantage/subscribe/blender/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/Form/Feature/Feature.tsx, static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/js/src/advantage/subscribe/react/components/Form/Quantity/Quantity.tsx, static/js/src/advantage/subscribe/react/components/Form/Support/Support.tsx, static/js/src/advantage/subscribe/react/components/Form/Version/Version.tsx, static/js/src/advantage/subscribe/react/components/ProductSummary/ProductSummary.tsx, static/js/src/advantage/subscribe/react/utils/FormContext.tsx
- Store the selected product in the local storage
- Go to https://ubuntu-com-12260.demos.haus/pro/subscribe
- Select items 
- Refresh page and see the selected items remains as selected.
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/787?modal=detail&selectedIssue=WD-77
=> Store states in the local storage

tests/cypress/forms/forms_spec.js
- Remove cypress test for /credentials/sign-up
https://discourse.canonical.com/t/how-to-run-cypress-test-locally-for-forms-on-ubuntu-com/558
=> Remove cypress test for /credentials/sign-up

static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
- Add tax id type in payload
1. Go to /pro/subscribe or https://ubuntu-com-12299.demos.haus/pro/subscribe
2. Buy subscription
3. Go to /pro/subscribe 
4. Buy another subscription
5. Check inputs are pre-filled 
Fixes 
https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-390
https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-389
https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-388
Input values are pre-filled for me.
=> Add tax id type in payload

static/js/src/PurchaseModal/hooks/useMakePurchase.tsx
- Add product info to payload for trial
- Go to /pro/subscribe 
- Make sure you don't log in  
- Make a trial purchase
- Check payment is successful 
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-392
=> Add product info to payload for trial

webapp/views.py
- Adds redirect for when id us not passed
- go to https://ubuntu-com-12306.demos.haus/subscription-centre and see that you are redirected to https://ubuntu-com-12306.demos.haus/blog
Fixes https://warthogs.atlassian.net/browse/WD-235
=> Add redirect for when id us not passed

templates/landscape/pricing.html
- updated /landscape/pricing based on the comments in the [copy doc](https://docs.google.com/document/d/1pESmRniuiaDHkbzY_60GlOJdCiH2pZ9erI9KV49eDyM/edit#)
- Visit https://ubuntu-com-12319.demos.haus/landscape/pricing
- See that the changes match the comments in the copy doc
Fixes https://github.com/canonical/web-squad/issues/6199
=> update /landscape/pricing copy

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/advantage/error-handler.js, static/js/src/advantage/offers/components/BuyButton.tsx, static/js/src/advantage/subscribe/blender/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/react/components/BuyButton/BuyButton.tsx
Ubuntu Pro: Handle new VAT validation error codes
Fixes https://warthogs.atlassian.net/browse/WD-653
=> Ubuntu Pro: Handle new VAT validation error codes

templates/shared/forms/interactive/hpe.html
Update contact form according to [copy doc](https://docs.google.com/document/d/1GtHoXJPGqTaxJxj1d9ul7hZukb_piUdBunXAwx7J28k/edit#)
- Go to https://ubuntu-com-12322.demos.haus/hpe click on the "Get in touch" button and compare with [copy doc](https://docs.google.com/document/d/1GtHoXJPGqTaxJxj1d9ul7hZukb_piUdBunXAwx7J28k/edit#)
Fixes https://github.com/canonical/web-squad/issues/6219
=> Update HPE contact form

static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx
- Update CTA from white to green
-  Go to `/pro/subscribe`
- Click "Public cloud instances" in the first step "What are you setting up?"
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-789
=> Update CTA to green

static/js/src/advantage/subscribe/react/components/Form/ProductType/ProductType.tsx, static/sass/_pattern_subscribe.scss
- Update "Physical servers" selector 
- Go to  https://ubuntu-com-12331.demos.haus/pro/subscribe
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-791
=> Update physical servers selector 

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx, static/js/src/PurchaseModal/components/FreeTrial/FreeTrial.test.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.tsx, static/js/src/PurchaseModal/components/UserInfoForm/UserInfoForm.tsx, static/js/src/advantage/subscribe/blender/components/Summary/Summary.test.jsx, static/js/src/advantage/subscribe/react/components/Summary/Summary.test.jsx, static/js/src/advantage/subscribe/react/utils/test/Mocks.js
- Fix code so `test-js` & `lint-ts` pass.
- `dotrun lint-ts`
- `dotrun test-js`
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-464
=> Fix test-js & lint-ts

static/js/src/PurchaseModal/components/Taxes/Taxes.tsx
- Show display mode when saved country exists. 
- Go to /pro/subscribe 
- Sign in with ubuntu one 
- Check Region and taxes section shows display mode 
Fixes #https://warthogs.atlassian.net/browse/WD-924
=> Show display mode

static/sass/_pattern_lists.scss, static/sass/_pattern_strip.scss, static/sass/styles.scss, templates/certified/index.html, templates/pricing/pro.html, templates/pro/index.html, templates/security/esm.html
- Refreshed /certified according to the [design](https://www.figma.com/file/Mpyhs1ZUsyeKxltxOskYp4/Certified-refresh?node-id=93%3A12567&t=7xGzlbmGYzHaShYX-1)
- Visit https://ubuntu-com-12353.demos.haus/certified
- See that it matches the design and the [copy doc](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit)
Fixes [WD-741](https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/932?modal=detail&selectedIssue=WD-741)
=> /certified refresh WD-741

static/js/src/PurchaseModal/components/ConfirmAndBuy/ConfirmAndBuy.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.tsx, tests/cypress/integration/pro/subscribe_spec.js
- Move reCAPTCHA to step 6
- Go to `/pro/subscribe`
- 
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-931
=> Move reCAPTCHA to step 6

static/js/src/advantage/react/components/Subscriptions/Content/Content.tsx, static/js/src/advantage/react/components/Subscriptions/ReBuyExpired/ReBuyExpiredButton/ReBuyExpiredButton.tsx, static/js/src/advantage/react/components/Subscriptions/ReBuyExpired/ReBuyExpiredModal.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.tsx
- PR to make modal autoload using query parameters
- Example of purchase url is:
https://ubuntu-com-12361.demos.haus/pro/dashboard?something=csv,comma#repurchase,aAHxjBg3sK_-gWf8zrbSG0fVUnAZI2zB9B4BeR7KE8hM,lABCTG1ioCNYYB-eV3MN7B1iVLgjl4l0l8VOLNZHEjhc,12,yearly,canonical-ua,90000,Ubuntu%20Pro%20(Infra-only)%20-%20Virtual
Fixes #https://warthogs.atlassian.net/browse/WD-951
=> Patch rebuy after expiry

templates/download/iot/index.html
**BLOCKED**: I am waiting on a reply to a questioned I asked in the [copydoc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#) about another link
- Updates a link's text based on [copydoc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit#)
Fixes https://github.com/canonical/web-squad/issues/6286
=> Update link text on /download/iot

templates/download/amd-xilinx/index.html
**DON'T MERGE**: We will share the demo with amd and wait for there approval
- Update /amd-xilinx based on the changes laid out in the [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit#)
- go to https://ubuntu-com-12376.demos.haus/download/amd-xilinx and compare against [copydoc](https://docs.google.com/document/d/1cxQnEErs8FZ3dZ_IhlfcaJ03gE_vrMJfRC-5me9IDd4/edit#)
Fixes https://github.com/canonical/web-squad/issues/6285
=> Update /amd-xilinx based on copydoc

static/js/src/navigation.js
- Add buy button on nav
- Go to  https://ubuntu-com-12379.demos.haus/pro
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-994
[WD-994]: https://warthogs.atlassian.net/browse/WD-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add buy button on nav

meganav.yaml, package.json, static/js/src/core.js, static/js/src/navigation.js, static/sass/_pattern_navigation.scss, static/sass/styles.scss, templates/templates/_navigation.html, templates/templates/meganav/base.html, yarn.lock
- Fixed a number of small bugs on the new meganav, including:
- Fixed broken layout when transitioning between small and large breakpoints
- Fixed keyboard navigation being impossible
- Fixed opening "All Canonical" menu failing to close other open meganav sections
- Visit https://ubuntu-com-12390.demos.haus/
- Test the meganav at various breakpoints, the layout shouldn't break
- Test that you can navigate successfully via both mouse and keyboard
- Visit /openstack
- See that the meganav still works well in the "reduced" navigation view
Fixes https://github.com/canonical/web-squad/issues/6178
=> Meganav bug fixes

static/js/src/PurchaseModal/PurchaseModal.tsx, static/js/src/PurchaseModal/components/BuyButton/BuyButton.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.test.tsx, static/js/src/PurchaseModal/components/Taxes/Taxes.tsx, static/js/src/PurchaseModal/hooks/useMakePurchase.tsx, static/js/src/advantage/subscribe/react/components/Summary/Summary.tsx, webapp/shop/schemas.py
- Call calculate endpoint on step 1 only for guest users
- QA when logged in and when guest
- Change country and VAT and click "Save" button 
- Check calculate endpoint is called only when guest 
- Also check tax changes in summary properly
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-911
[WD-911]: https://warthogs.atlassian.net/browse/WD-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Call calculate endpoint on step 1 only for guest users

templates/core/index.html
- Updates a link on /core as requested in the [copydoc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit#)
- Go to https://ubuntu-com-12407.demos.haus/core
- Check the requested link has been updated
Fixes https://github.com/canonical/web-squad/issues/6313
=> Update link on /core

templates/support/contact-us.html
- Updates advantage to pro on /support/contact-us
- Go to https://ubuntu-com-12419.demos.haus/support/contact-us and check it says 'Ubuntu Pro'
Fixes https://github.com/canonical/commercial-squad/issues/749
=> Update advantage to pro on /support/contact-us

templates/desktop/developers.html
- Copy changes on [this doc](https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit) 
Fixes [#753](https://github.com/canonical/commercial-squad/issues/753)
=> Copy Changes #753

templates/download/desktop/thank-you.html
**DON'T MERGE** until 26th Jan
Updated the copy on the desktop download thank you page
- Go to https://ubuntu-com-12417.demos.haus/desktop
- Download Ubuntu so you can see the thank you page
- Check that the changes requested in [the copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit) have been made
- Resolve the comments in the copy doc
Fixes https://github.com/canonical/marketplace-tribe/issues/2953
=> Copy update /download/desktop/thank-you

templates/edge-computing/index.html
- Quick fix for a separator issue that I spotted in staging
Fixes #
=> Fix hr separators on /edge-computing

templates/automotive/index.html
- Applied the remaining changes from the [automotive copy doc](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit#heading=h.hxalq3o52ayh)
- Check the updates match the [copy doc](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit#heading=h.hxalq3o52ayh)
=> Apply additional updates to the automotive page

templates/pricing/devices.html
- Applied copy changes as per [copy doc](https://docs.google.com/document/d/1uiKNaT59tk2rvjuM24vpqVblcNO90PmE4wUlq9A9Rsk/edit#heading=h.2r4boi163qbs)
- View the site locally in your web browser at: http://0.0.0.0:8001/pricing/devices
Fixes https://warthogs.atlassian.net/browse/WD-1349
=> Update copy on /pricing/devices

templates/internet-of-things/index.html
- Change logo according to the copy doc
- Update link
- Visit demo: https://ubuntu-com-12432.demos.haus/internet-of-things
- See Felicia's comment in the [copy doc](https://docs.google.com/document/d/1nBx1SP3Y10gXX0rZPDaz1Gudy-hWP4XRMUcETyPBldI/edit#heading=h.iqtg6b1bg6rk)
- Check that the logo is correct
Fixes https://github.com/canonical/workplace-engineering-squad/issues/872
=> change intel logo

templates/automotive/index.html
- Applied the remaining changes from the [automotive copy doc](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit#heading=h.hxalq3o52ayh)
- Check the updates match the [copy doc](https://docs.google.com/document/d/10jSLdwz2Ks7gnEMXlKWzrpsY6TQFxISUgnQo4y3yOrA/edit#heading=h.hxalq3o52ayh)
=> Apply more additional updates to the automotive page

templates/kubernetes/compare.html
*Note* you can ignore the illustration, Alex would like to get the copy changes out ASAP and doesn't want to wait for the illustration.
- Update incorrect information on /kubernetes/compare table, based on [copydoc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit)
- Go to https://ubuntu-com-12438.demos.haus/kubernetes/compare and compare against [copydoc](https://docs.google.com/document/d/1JngYmRhohPo62yU72V1xpzCCILI21SmHKKttBxHjPog/edit)
Fixes https://warthogs.atlassian.net/browse/WD-1404
=> Update incorrect information on /kubernetes/compare table

templates/certified/index.html
- Very small updates to the certified page as per [the copy docs](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#) 
- Check the code matches the changes requested in the copy doc.
=> Very small copy updates on the certified page

templates/openstack/why-openstack.html
- Update the button on the why-openstack
- Check the code matches [the copy doc](https://docs.google.com/document/d/1StqylVToo1URkhLvNfl17vZ52H35fXCVOR1aMKG1aGU/edit#).
Fixes https://warthogs.atlassian.net/browse/WD-1473
=> WD-1473 Update the why-openstack button

navigation.yaml, templates/gcp/fips.html
- Build GCP FIPs page, same as https://ubuntu.com/azure/fips
- Compare https://ubuntu-com-12416.demos.haus/gcp/fips with [copy docs](https://docs.google.com/document/d/17Rr6Fdrr7xSPi1g2h7GMTztQUGYqz2hdbNUqK0uQihw/edit#)
Fixes https://github.com/canonical/web-squad/issues/6130
=>  Build new gcp FIPS page

templates/desktop/organisations.html, templates/download/desktop/index.html, templates/pricing/desktops.html, templates/shared/contextual_footers/_professional_support.html
**Don't merge** until Jan 26th
- This PR addressed 4 different issue, all with minor/similar changes to them, to be merged into the feature branch [ubuntu-pro-ga-release](https://github.com/canonical/ubuntu.com/tree/ubuntu-pro-ga-release) on the 26th Jan
- /desktop/features [copydoc](https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit#)
- /pricing/desktops [copydoc](https://docs.google.com/document/d/1xVtaZ7wr5sdBqye3Gc-XWXEpNqXaol8uDdMwJ_KyOO8/edit) *there are some comments about the table that have been ignored in this PR as it is out of scope*
- /download/desktop [copydoc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit#) 
- /desktop/organisations [copydoc](https://docs.google.com/document/d/1RuxCA6GYh9UriNv26HCZP9UHo …
=> update desktop bubble from Advantage to Pro

templates/security/notices/usn.html, templates/shared/contextual_footers/_security_need.html
- Update `/security/notices` page 
- Compare page with [Miro](https://miro.com/app/board/uXjVPw0Ocf8=/?moveToWidget=3458764543891939558&cot=14)
- Go to /security/notices
- Search for example, `USN-5761-2` or go to https://ubuntu-com-12458.demos.haus/security/notices/USN-5761-2
- Compare page with [Miro](https://miro.com/app/board/uXjVPw0Ocf8=/?moveToWidget=3458764543891939558&cot=14)
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-1465
=> Copy update /security/notices page

static/js/src/navigation.js, templates/contact-us/form/index.html, templates/pro/index.html, templates/pro/tutorial.html, templates/shared/_pro-contact-us-form.html, templates/shared/forms/interactive/advantage-beta.html, webapp/app.py, webapp/shop/advantage/views.py
=> /pro index page

templates/pro/tutorial.html
Correct contact us link on /pro/tutorial
=> Correct contact us link on /pro/tutorial

templates/wsl/index.html
- Refresh /wsl landing page based on [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#heading=h.fqpazxhydeus)
- Go to /wsl and compare against [copydoc](https://docs.google.com/document/d/1M7e2B08GgPA7K6Wx0ThE6s9_xQINM0MSkarfdKUTEYI/edit#heading=h.fqpazxhydeus)
Fixes https://warthogs.atlassian.net/browse/WD-1294
=> Refresh /wsl landing page

templates/pro/index.html
- Fix /pro page accessibility error
- Are cypress checks passing?
=> Fix a11y cypress error

templates/pro/index.html
- Move tab to pre from code element
- Cypress tests passing?
=> Adjust /pro tabindex

navigation.yaml
- Add tutorial in the nav
- Go to `/pro`
Fixes https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-1552
=> Add tutorial in the nav

templates/credentials/schedule.html
- Visit https://ubuntu-com-12469.demos.haus/credentials/schedule
- Verify that the copy says "Your exam will take up to one hour to complete."
Fixes https://warthogs.atlassian.net/browse/CRED-260
=> Update copy with time to complete exam

templates/pro/index.html
- Update logo section according to [design](https://www.figma.com/file/ZAihKxF2wmj9wvoPSnPKmY/Commercial%3A-Ubuntu-Pro?node-id=3016%3A16960)
- go to `/pro` or https://ubuntu-com-12481.demos.haus/pro
- compare logo section with design
Fixes #https://warthogs.atlassian.net/jira/software/c/projects/WD/boards/801?modal=detail&selectedIssue=WD-1635
=> Update logo section

templates/hpe/index.html
- Copy update on /hpe based on [copydoc](https://docs.google.com/document/d/1A2__NxIU6jFKprs5thPNtIPfOc7E9VhZEoPFu01lT_8/edit)
- Go to https://ubuntu-com-12474.demos.haus/hpe and compare against copydoc
Fixes https://warthogs.atlassian.net/browse/WD-1580
=> Copy update on /hpe

tests/shop/advantage/helpers.py, webapp/certified/api.py, webapp/certified/views.py, webapp/security/views.py, webapp/shop/api/ua_contracts/helpers.py, webapp/views.py
- Fix python linting quickly
- Does the pipeline pass?
=> Fix python linting

redirects.yaml, static/js/src/dynamic-forms.js, static/sass/styles.scss, templates/nvidia/index.html, templates/shared/forms/interactive/nvidia.html
Build Nvidia partners page
- Check https://ubuntu-com-12441.demos.haus/nvidia against [copy docs](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#)
- Check https://ubuntu-com-12441.demos.haus/nvidia against [design ](https://www.figma.com/file/S6KvNUt0agl0bcbp6wjhnB/Partners?node-id=576%3A9683&t=mHdjBYcAY7pSpuxX-0)
- Check contact-us form works
Fixes https://github.com/canonical/web-squad/issues/6062
=> Nvidia partners page

templates/pro/tutorial.html
=> Fix typo in /pro/tutorial

requirements.txt, templates/financial-services/index.html, templates/financial-services/resources.html, templates/shared/forms/interactive/financial.html, tests/shop/advantage/helpers.py, webapp/certified/api.py, webapp/certified/views.py, webapp/security/views.py, webapp/shop/api/ua_contracts/helpers.py, webapp/views.py
Finserve copy updates
- https://ubuntu-com-12486.demos.haus//financial-services compare with  [Copy doc](https://docs.google.com/document/d/1CMEo3IsFkybk1SuKWpvZGxU6e24iNoDZkjrgloYXEkU/edit#heading=h.xko89ia4v7f1)
- https://ubuntu-com-12486.demos.haus//financial-services/resources compare with [copy doc](https://docs.google.com/document/d/1ARHCltg-5mS7djCl6ZeCf8su_Hs8_JtFt_4jzTY0u5s/edit#heading=h.l9ymkeeqk855)
Fixes https://warthogs.atlassian.net/browse/WD-1459
=> Copy update finserv

templates/openstack/features.html, templates/openstack/index.html, templates/openstack/support.html
Copy updates
Compare https://ubuntu-com-12502.demos.haus/openstack with [u.c./openstack](https://docs.google.com/document/d/1eqHK0hc9v7Mn-XV36QRyNkJenTXgBQR_-RULKm5rZ5o/edit#heading=h.r7b5xqn3u5oj)
Compare https://ubuntu-com-12502.demos.haus/openstack/features with [u.c./openstack/features](https://docs.google.com/document/d/1odFXuFtN1GjuZvgd8tW48HB4J9PjZJtP3w6wY0xlmog/edit#)
Compare https://ubuntu-com-12502.demos.haus/openstack/support with [u.c./openstack/support](https://docs.google.com/document/d/1mHaZQ_VZnISTUEpYKiVK-Ejr5ne8lVevpxEc0LpXYKI/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-1802
=> Copy updates for rebranding Advantage into Pro

static/js/src/advantage/offers/components/PaymentButton/PaymentButton.test.tsx, static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.test.tsx, static/js/src/advantage/react/components/Subscriptions/RenewalButton/RenewalButton.tsx, static/js/src/advantage/react/components/Subscriptions/SubscriptionDetails/SubscriptionDetails.test.tsx, static/js/src/advantage/subscribe/blender/components/PaymentButton/PaymentButton.test.tsx, static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.test.tsx, static/js/src/advantage/subscribe/checkout/utils/test/Mocks.ts
- Adding some extra tests
- Is pipeline green?
Fixes #https://warthogs.atlassian.net/browse/WD-1376
=> Improve testing

templates/kubernetes/resources.html
- Updates logos on /kubernetes/resources based on the [copydoc](https://docs.google.com/document/d/1enaCJ4Vt9a_2_l6xYccnZ-fBVUejPSmfMi8LP2aDA9c/edit#)
- Go to https://ubuntu-com-12519.demos.haus/kubernetes/resources and compare against the copydoc
Fixes https://warthogs.atlassian.net/browse/WD-1884
=> Update logos on /kubernetes/resources

templates/nvidia/index.html
Update NVIDIA page diagram according to https://warthogs.atlassian.net/browse/WD-1833
- Check https://ubuntu-com-12505.demos.haus/nvidia agaist [copy](https://docs.google.com/document/d/1DJ1FuEswAojPNSX9JCLcWJwy-va5VMzuuLGwSNM0lRY/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-1833
=> Update NVIDIA page updates

templates/pricing/pro.html, templates/pro/tutorial.html
- Update pro tutorial copy.
- Update pricing page copy.
- Make sure the changes matches what is on the copy for both templates
Fixes #https://warthogs.atlassian.net/browse/WD-1941
=> Pro tutorial copy

templates/shared/_credentials-exit-survey.html
- go to https://ubuntu-com-12488.demos.haus/credentials/exit-survey
- Check the last 2 questions. They should be a slider scale
Fixes #
=> changed NPS scores to range

webapp/app.py, webapp/shop/advantage/views.py, webapp/shop/api/ua_contracts/advantage_mapper.py, webapp/shop/api/ua_contracts/api.py, webapp/shop/api/ua_contracts/primitives.py, webapp/shop/api/ua_contracts/schema.py
- Create new endpoint to replace the current /pro/user-subscriptions
- The new endpoint /pro/subscriptions.json will be consuming the new endpoint to generate the /pro subscriptions
- Aggregation on the items we get from the endpoint is not done as part of this PR
- Open /pro/subscriptions.json? Does it work?
https://github.com/canonical/commercial-squad/issues/745
=> Create annotated contract items endpoint

templates/core/features/index.html, templates/core/index.html
- Updated /core as per [copy doc](https://docs.google.com/document/d/1UFpefDRSAcndNBnWp0hDyzqk74aciqhBWJEi05htWmU/edit#heading=h.ljeurx6cb36j)
- Updated /core/features as per [copy doc](https://docs.google.com/document/d/10S6FGVRA1R1qi9v859CnFrl8rS25Za2SjEmSpPVQkzY/edit#heading=h.avfvxsb34rlb)
**NOTE: MUST GO LIVE ON 14/2** 
- View the site locally in your web browser at: https://ubuntu-com-12537.demos.haus/core and https://ubuntu-com-12537.demos.haus/core/features
Fixes https://warthogs.atlassian.net/browse/WD-1893
=> [copy update] /core and /core/features 

templates/base_index.html, templates/industrial/index.html
**Don't merge until Feb 14th 13:00GMT**
- /industrial [copydoc](https://docs.google.com/document/d/1QiU75g49lRKebt82oyLSxR3-PU96Sk87nqauAZ4vvIY/edit#)
- /index [copydoc](https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit#)
- Go to https://ubuntu-com-12527.demos.haus/industrial and https://ubuntu-com-12527.demos.haus/ and compare against the copydocs
Fixes https://warthogs.atlassian.net/browse/WD-1872
=> Copy update on /industrial and /index

templates/certified/index.html
- Swapped the certified laptop images to the jammy background
- Go to certified and see if the laptop images have the jammy background
- Check it fixes the comment in the [copy doc](https://docs.google.com/document/d/1Cq9RLNjSbX83WB5fFKYCFRvo_1JEfMydMecqrVeKBP8/edit#heading=h.47d7xq5tut1z)
=> WD-1836 Swapped the certified laptop images to the jammy background

templates/cpu-compatibility/index.html
Copy update. Added new entry to compatibility matrix
- Check https://ubuntu-com-12546.demos.haus/cpu-compatibility against [copy doc](https://docs.google.com/document/d/16E0xMuCIrGRwGa1G0poDEil9zd_5UAWTpxFRiA8j-KU/edit#)
Fixes https://warthogs.atlassian.net/browse/WD-1959?atlOrigin=eyJpIjoiZjRmNmVkOTlmYTMyNDg0YmE0NTNkMjc0NjkzZTBkMDYiLCJwIjoiaiJ9
=> Update CPU compatibility table

package.json, static/js/src/advantage/subscribe/checkout/components/BuyButton/BuyButton.tsx, static/js/src/advantage/subscribe/checkout/components/Checkout/Checkout.tsx, static/js/src/advantage/subscribe/checkout/components/ConfirmAndBuy/ConfirmAndBuy.tsx, static/js/src/advantage/subscribe/checkout/components/SignIn/SignIn.tsx, static/js/src/advantage/subscribe/checkout/components/Summary/Summary.tsx, static/js/src/advantage/subscribe/checkout/components/Taxes/Taxes.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/PaymentMethodSummary/PaymentMethodSummary.tsx, static/js/src/advantage/subscribe/checkout/components/UserInfoForm/UserInfoForm.tsx, static/js/src/advantage/subscribe/checkout/hooks/usePollPurchaseStatus.tsx, static/sass/_pattern_checkout.scss, templates/account/checkout.html, yarn.lock
- Update checkout redesign to look like https://miro.com/app/board/uXjVONNsexk=/?openComment=3458764546051510037
- go to /pro/subscribe
- select any product
- proceed to checkout
- Checkout should look like https://miro.com/app/board/uXjVONNsexk=/?openComment=3458764546051510037 and accommodate all the changes suggested
Fixes #
=> Checkout visual changes

templates/internet-of-things/edgex.html
Update integrated framework image
- Check https://ubuntu-com-12543.demos.haus/internet-of-things/edgex has the [new image](https://warthogs.atlassian.net/browse/WD-1253?atlOrigin=eyJpIjoiMmQzZmJiZDQxY2QyNDkyZDk1NjQ4Y2JmYWNkYmJhYTYiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1253?atlOrigin=eyJpIjoiMmQzZmJiZDQxY2QyNDkyZDk1NjQ4Y2JmYWNkYmJhYTYiLCJwIjoiaiJ9
=> Update edgex integrated framework image

.github/workflows/kubernetes-docs-links.yaml
Wild card the localhost ignore from k8s linkchecker
=> Wild card the localhost ignore from k8s linkchecker

templates/internet-of-things/index.html, templates/internet-of-things/management.html, templates/openstack/compare.html, templates/openstack/features.html
Update assets on IoT pages
- Check https://ubuntu-com-12557.demos.haus/internet-of-things/management [new images](https://warthogs.atlassian.net/browse/WD-1257?atlOrigin=eyJpIjoiODk0ODYxMjI4ZDFlNGM0MzkxMWQ0ZjQ0Y2EyYmFjNjkiLCJwIjoiaiJ9)
- Check https://ubuntu-com-12557.demos.haus/internet-of-things have the [new images](https://warthogs.atlassian.net/browse/WD-1250?atlOrigin=eyJpIjoiZDNiNGRmOTNmMTg4NDZkMzliYmZmYzdiYTkzNTNjNGIiLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1257?atlOrigin=eyJpIjoiODk0ODYxMjI4ZDFlNGM0MzkxMWQ0ZjQ0Y2EyYmFjNjkiLCJwIjoiaiJ9
Fixes https://warthogs.atlassian.net/browse/WD-1250?atlOrigin=eyJpIjoiZDNiNGRmOTNmMTg4NDZkMzliYmZmYzdiYTkzNTNjNGIiLCJwIjoiaiJ9
[QA steps](https://discourse.canonical.com/t/qa-steps/152) …
=> Replace logos for IoT pages

templates/embedded/index.html
Update logos
- Check https://ubuntu-com-12542.demos.haus/embedded has the [new logos](https://warthogs.atlassian.net/browse/WD-1271?atlOrigin=eyJpIjoiNjhjMDY3MTdhYzA0NDg3OWE1YzExZWFjYWVhOTRiZTciLCJwIjoiaiJ9)
Fixes https://warthogs.atlassian.net/browse/WD-1271?atlOrigin=eyJpIjoiZDMwNTlkZDM5ZGE1NDYzZjk4MWMwMTUyNjhiOWZjMTMiLCJwIjoiaiJ9
=> Update embedded logos

.github/workflows/a11y.yaml, .github/workflows/ceph-docs-links.yaml, .github/workflows/core-docs-links.yaml, .github/workflows/cypress-main.yaml, .github/workflows/cypress-pr.yaml, .github/workflows/kubernetes-docs-links.yaml, .github/workflows/openstack-charm-deployment-guide-docs-links.yaml, .github/workflows/openstack-charm-guide-docs-links.yaml, .github/workflows/pr.yaml, .github/workflows/server-docs-links.yaml
Another PR to make the renovate PR lighter: https://github.com/canonical/ubuntu.com/pull/12389
- Upgrade GH actions to use latest actions versions
- Checkout the github actions!
=> Upgrade GH actions to use latest actions versions

templates/pricing/pro.html, templates/pro/index.html
- UIpdate pricing page as per @lechsandecki 's requests.
Fixes #
=> Pricing page updates

templates/cloud/hybrid-cloud.html, templates/cloud/multi-cloud.html, templates/cloud/private-cloud.html
Copy updates for /cloud/ pages
- Check https://ubuntu-com-12532.demos.haus/cloud/hybrid-cloud against [copy docs](https://docs.google.com/document/d/1oIggNSXR5sfl0Ab35x2NIL7I858I7QdPCUXeQI8IIPc/edit#)
- Check https://ubuntu-com-12532.demos.haus//cloud/multi-cloud against [copy docs](https://docs.google.com/document/d/1nWsDaRiUzaupjKDzu1ZqjlmxHGv2HCgW8oBBEacYFLs/edit#heading=h.6gx8ccowcd3a)
- Check https://ubuntu-com-12532.demos.haus/cloud/private-cloud against [copy docs](https://docs.google.com/document/d/19g24YRYzF5dBpUKI1QzTG7fXKj1z0OvwgFll69dFoOs/edit#heading=h.evj3u5y98j9v)
Closes https://warthogs.atlassian.net/browse/WD-1322?atlOrigin=eyJpIjoiYTczMGNmNGY3Yjc0NDc0MGE4YTBmZTgzNzA5ZDMwZWIiLCJwIjoiaiJ9
Closes https://warthogs.atlassian.net/browse/WD-1321?atlOrigin=eyJpIjoiODA4MWZjMjg0YTF …
=> Cloud copy updates
